### ISSUE TITLE
Cannot edit path / extension of extracted images if Emmet is installed

### ISSUE THREAD

**Issue by monirulalom** [adobe/brackets#10007]
https://forums.adobe.com/thread/1643318

**Comment by peterflynn** [comment]
You can do this already.  @monirulalom can you provide the exact steps you're following?

For example, this works for me:

1. Select an image in the Extract panel
2. In an HTML file, type `<img` and then press Space
3. Use arrows to highlight the "src=_Extract Asset..._" code hint item, then press Enter
4. Now I see code like `src="images/Layer-2.png"`, and the `images/Layer-2.png` part has a blue highlight drawn around it.
5. I edit the highlighted text so it says, for example, `images/test.jpg` -- then press Enter.
6. No newline is inserted (the cursor is positioned after the closing `"`), and the file is generated in my project under the 'images' folder.

Does the behavior differ if you follow those steps?  If not, what steps cause a problem for you?

If you're seeing odd behavior when you press Enter, check if you have the Emmet extension installed -- that has been known to cause problems with code hints before...

**Comment by monirulalom** [comment]
When I press ENTER a newline is interted. But It works fine when I disable EMMET extension.@peterflynn

**Comment by imiMike** [comment]
That's still broke in 1.3 and emmet 1.2.2:( Disabling emmet helps as monirulalom mentioned.

**Comment by nethip** [comment]
@prafulVaishnav Could you take a look at this and see if `emmet` extension is overriding anything that is causing this behavior?

**Comment by abose** [comment]
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
