### ISSUE TITLE
Weird characters...

### ISSUE THREAD

**Issue by vimxts** [adobe/brackets#10044]
Please suggest a title, too weird to think for a proper one.

Essentially, when you change over to your browser and Brackets too many times, this happens:

Yes, it is a whole transparent webpages I'm looking at.

![default](https://cloud.githubusercontent.com/assets/5255292/5237856/71efff44-78dd-11e4-8693-9b1468f4ebbb.JPG)

**Comment by JeffryBooher** [comment]
@vimxts are you still seeing the weird characters or should I close this issue?

**Comment by peterflynn** [comment]
Looks like this could be a flavor of #7338, which was fixed in 1.1

**Comment by vimxts** [comment]
I'm not seeing this now, but something else bothers me now. I guess this post can be closed
