### ISSUE TITLE
I edited a php file and git diff shows me a lot of odd newly added characters

### ISSUE THREAD

**Issue by wolfgangihloff** [adobe/brackets#10100]
I edited a php file and git diff shows me a lot of odd newly added characters, see sceenshot, they are not expected, just my text changes.
![screen shot 2014-12-06 at 11 44 12 am](https://cloud.githubusercontent.com/assets/162688/5327102/3e875b7a-7d3d-11e4-8836-961ab9340534.png)

**Comment by JeffryBooher** [comment]
@wolfgangihloff i'm closing this issue as it looks like a Windows CRLF issue. Please reopen this issue if you continue seeing problems.
