### ISSUE TITLE
Brackets freezes while browser reloads

### ISSUE THREAD

**Issue by ansorensen** [adobe/brackets#10133]
I'm using a grunt build for live reload, so I'm NOT using Brackets' Live Preview.  However, Brackets freezes every time Grunt reloads the browser (Chrome) -- which is every time I save.  This leads to horrible bugs when I reflexively save and keep typing.

I would normally assume that, if I'm NOT using Live Preview, Brackets would not have a dependency on the browser that causes it to freeze with great regularity while my browser loads.

I'm using Brackets version: 
Release 1.0 build 1.0.0-15191 (release 3f2eb90a4) 
build timestamp: Fri Oct 31 2014 14:26:26 GMT-0700

**Comment by ingorichter** [comment]
@ansorensen on which platform are you working? How many files are usually getting regenerated when the grunt script runs? How big is your project?
Would you mind trying with the latest Brackets 1.1 release? We have fixed some issues with the file watching and project tree update, which might cause your issue.

**Comment by ficristo** [comment]
If you still have problems, please open a new issue.
