### ISSUE TITLE
Blank panels

### ISSUE THREAD

**Issue by keld30** [adobe/brackets#10136]
![brackets](https://cloud.githubusercontent.com/assets/826470/5369579/b4a33376-7fca-11e4-94f1-2a6671b83805.jpg)
Minimizing Brackets and re-opening it makes it crash sometimes. Can't close it either, you have to kill it form the task manager. Looks like a display issue as the text is blurry. Sometimes you can see a bit the code from the opened files by moving your mouse around.

**Comment by JeffryBooher** [comment]
Closing. @keld30 let us know if 1.1 doesn't fix it for you.
