### ISSUE TITLE
Deleting a key binding to null in the user key map does not restore the original key binding

### ISSUE THREAD

**Issue by RaymondLim** [adobe/brackets#10157]
1. Open user key map.
2. Add a key binding to null (e.g. `"Cmd-O": null` on mac).
3. Save the file and check the File menu. File > Open does not have any shortcut.
4. Delete the key binding added in step 2.
4. Save the file and check the File menu again.

Result: Cmd-O shortcut is not restored to File > Open.

Workaround: Quit and Restart or Reload.

**Comment by redmunds** [comment]
@RaymondLim While testing #10247 , I discovered another case where original key binding is not restored. Let me know if I should open a separate issue:

1. Edit keymap.json to define 2 shortcuts to same command:

    "overrides": {
        "Ctrl-PageUp": "view.increaseFontSize",
        "Ctrl-+":      "view.increaseFontSize"
    }

2. Save file shows an error: "You are assigning multiple shortcuts to these commands". Click OK.
3. Neither shortcut wor5ks at this point. Delete both:

    "overrides": {
        
    }

4. Save file.

Result:
The original key binding is not restored

**Comment by RaymondLim** [comment]
@redmunds Thanks for catching another case that I missed. I can fix it easily and will add the new fix to the same pull request.

**Comment by redmunds** [comment]
Confirmed. Closing.
