### ISSUE TITLE
.brackets.json specified language.fileExtensions is not being applied for extension language upon startup

### ISSUE THREAD

**Issue by liamjones** [adobe/brackets#10177]
Repro steps:

1. Install Brackets fresh, no extensions
2. Create a new project directory containing an `index.html` (contents doesn't matter)
3. Open Brackets and point it at the project directory via open folder
4. Open `index.html` and note it's selected HTML as the language (as expected)
5. Install swig-brackets extension (https://github.com/abdelouahabb/swig-brackets/)
6. Create and save a `.brackets.json` in the project directory containing:   
    ```json
    {
        "language.fileExtensions": {
            "html": "swig"
        }
    }
    ```

7. Close and reopen Brackets
8. Open `index.html`
    Expected behaviour: language for `.html` files in this project is now Swig
    Observed behaviour: language is still HTML

9. In `.brackets.json`, change `swig` to something else, save then change it back to `swig` and save again
10. Switch back to `index.html` and observe that it's now defaulting `.html` files to Swig formatting (this will persist until Brackets is restarted)

**Comment by peterflynn** [comment]
Looks like a timing issue with LanguageManager reading the preferences before extensions have finished loading.

**Comment by MarcelGerber** [comment]
Closing in favor of #11252.
See https://github.com/adobe/brackets/issues/11252#issuecomment-111472993 for more info.
