### ISSUE TITLE
[CEF 2171] Image views don't scale when the height of the view changes

### ISSUE THREAD

**Issue by jasonsanjose** [adobe/brackets#10180]
1. Open the find in files panel
2. Resize it tall enough to cause scrolling when an image is viewed
3. Select an image from the project tree

Actual: Image is clipped on the bottom edge
Expected: Scale to fit or provide scroll bars

![image](https://cloud.githubusercontent.com/assets/1148713/5444415/31484716-845f-11e4-9162-7fb943a1665d.png)

**Comment by peterflynn** [comment]
Note: I updated the repro Gist to an even 500px height for simplicity.

Some related info:
http://stackoverflow.com/questions/1948249/how-to-set-maximum-height-for-img-but-keep-proportions
http://stackoverflow.com/questions/17329040/img-max-height-100-causes-img-to-exceed-bounds

**Comment by EJanuszewski** [comment]
I believe whilst fixing the meta data I may have also fixed this, see 356/357 https://github.com/EJanuszewski/brackets/commit/30cfd3833df69b6df1ad64836eebf9dad3e207b6#diff-d170b001614b4677146b7f46339e2d88R356

**Comment by EJanuszewski** [comment]
@prksingh See my comment above, from what I can tell it seems to be working fine after those changes.

**Comment by EJanuszewski** [comment]
Is there something wrong with the fix I did? Just curious why it's not been merged as it's tagged for the 1.2 release :)

**Comment by prafulVaishnav** [comment]
@EJanuszewski Can you create the pull request for this fix? I have added a note at  EJanuszewski@30cfd38#diff-d170b001614b4677146b7f46339e2d88R356.

**Comment by EJanuszewski** [comment]
@prafulVaishnav Already did just here https://github.com/adobe/brackets/pull/10364, let me know if there's something wrong with that pull and i'll make the changes

**Comment by prafulVaishnav** [comment]
@EJanuszewski This pull contain fixes for different issues. Can you please create different pull request for different files? Brackets.less has fix for issue #5960 and #10180. QuickView.less has fix for issue #10362..

**Comment by EJanuszewski** [comment]
@prafulVaishnav Sure, I didn't know different files needed different pull requests especially when they are related.

To clarify I need to make another pull request for https://github.com/adobe/brackets/issues/10362 and somehow remove https://github.com/EJanuszewski/brackets/commit/45a74c50c1de5300a0a04dfff8010565650ca26d from the current pull request?

**Comment by prafulVaishnav** [comment]
@EJanuszewski Ideally we make pull requests for each issue. In this case, change in Brackets.less is fixing two issues and change is related to both issues  #5960 and #10180. That's why one pull request for two issues is fine. Whereas, issue #10362 and its fix is independent so creating separate pull request will be good. Hope I clarify.. 

It will be easy if you create two new pull requests. In your case, one PR(Pull Request) containing Brackets.less file change and another PR containing QuickView.less file change.

Please let me know if any doubt.

**Comment by EJanuszewski** [comment]
#10514 New pull request, thanks for clarifying it all, I must have somehow missed the branch bit in all the excitement of wanting to get involved.

**Comment by prafulVaishnav** [comment]
Pull request #10514 merged.. Thanks @EJanuszewski for the fix..
