### ISSUE TITLE
.git directory in the project tree after using FileSystem.resolve

### ISSUE THREAD

**Issue by zaggino** [adobe/brackets#10183]
Since installing `Brackets.Release.1.1.msi` I keep seeing `.git` folder in my project tree, which wasn't there before (and shouldn't be as no-one should ever touch that directory manually). Core is linked to the latest master branch.
![image](https://cloud.githubusercontent.com/assets/1067319/5448308/7877358e-8531-11e4-8134-a2a537956f33.png)

**Comment by peterflynn** [comment]
I left a very long comment in the PR with ideas about fixing, but one clarification on the discussion in this thread...  Re @busykai's comment "there's an API, actually, to at least unwatch an entry within a watched root, but it's private (for a reason)": it's not actually possible on Mac or Win to unwatch a subset of a watched root.  The native watching API we use watches an entire subtree with no ability to exclude parts of it.  The private `_unwatchEntry()` API is only ever called on the watch root or on entries that have been deleted (for cleanup).

And even _adding_ watches is very basic & limited right now: early on we talked about the public `FileSystem.watch()` supporting overlapping file tree regions, but that was never implemented.  In theory we do support multiple _non-overlapping_ watch roots, but then that has never really been tested :-)  (So note, for example, that opened files from outside the project aren't currently watched, nor is the prefs JSON file).
