### ISSUE TITLE
provide update notification json for e4b bundle

### ISSUE THREAD

**Issue by ingorichter** [adobe/brackets#10196]
Currently, we have to hard code the e4b version into brackets.io/index.html. This is not sustainable in the long term, since Brackets is picking up all the information about the versions and build names from the updateNotification.json. This should be similar for the e4b bundle.

**Comment by peterflynn** [comment]
Reviewed -- moving to 1.3 milestone since this is a cleanup task.

@ingorichter Could you clarify what the E4B version number is needed for?  I don't see the string "0.6" anywhere in the HTML source or in the visible content of the webpage.

**Comment by nethip** [comment]
Moving this to 1.4 as not enough time to take this change.

**Comment by le717** [comment]
I have put up a PR to automatically update the E4B URL like we do for the non-E4B URL in adobe/brackets.io#174.

**Comment by ficristo** [comment]
Since Extract is deprecated I close this.
http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview

Let me know if I missed something here.
