### ISSUE TITLE
[CEF 2171] Text at the beginning of the inline editor is sometimes truncated

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#10203]
On MAC, When working with multiple inline editors open in the same view, I got a truncation at the beginning of the inline editor. Here is the screenshot.

![truncationerror](https://cloud.githubusercontent.com/assets/1577184/5471033/70804128-8616-11e4-9777-38df29fc0946.png)

I am not able to consistently repro this. From what I can recall, I was able to repro this bug when working with a combination of Increase/Decrease the font size and opening multiple inline editors. I will update this issue, if I get this again.

**Comment by redmunds** [comment]
@nethip Please re-open if you discover a reproducible recipe. Closing.
