### ISSUE TITLE
Live Preview MultiBrowser does not launch browser on Linux

### ISSUE THREAD

**Issue by jatin7gupta** [adobe/brackets#10229]
i did what ever was written in the text, but it didn't open in mozilla firefox beta version

**Comment by thediex09** [comment]
Well, Now it starts the browser but it doesnt update

**Comment by thediex09** [comment]
The fix strats firefox, but does not update the page!

**Comment by busykai** [comment]
@thediex09, could you please file another issue since it sounds like you're hitting different problem now? if you have any errors on console (*Debug -> Show Developer Tools*), please make sure to include them in the report along with [normally needed](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue) information.

**Comment by MarcelGerber** [comment]
Fix over at #10267 (was not yet linked).

**Comment by busykai** [comment]
Thanks @MarcelGerber! I only references the issue from the commit. By the way, it may be an incomplete solution since I'm not sure if the copying/packager preserves the file modes. If not, then a change to post-install script would be needed. Haven't gotten to test it yet, but will do this week.

**Comment by peterflynn** [comment]
Reopening as FBNC -- we shouldn't close until the adobe/brackets-shell#505 fix has landed in master too.

**Comment by peterflynn** [comment]
Fix is in master too now/

**Comment by Rahajustone** [comment]
in ubuntu 15.10 you have to change brackets.json file
go to home/.config/Brackets theris a brackets.json file add  "livedev.multibrowser":true
 to the end of file it going to priview in any browsers

**Comment by YousefYounis** [comment]
Hello,
I had same problem on Linuxmint 18, tried pixelr0's solution, but it didn't work directly, there was no such path on my system.
So I went to the path where I installed XDK, and tried the previous solution, then restarted XDK, and it worked, the path has change a little. On my system it is:

/home/yousef/intel/XDK/xdk/brackets/b/LiveDevelopment/MultiBrowserImpl/launchers/node/node_modules/opn

where "/home/yousef/intel" is where I installed XDK
