### ISSUE TITLE
Mac: Cmd+Delete should trigger Don't Save in Save Changes dialog

### ISSUE THREAD

**Issue by jeremiahlee** [adobe/brackets#10228]
This is the Mac OS X system default for save dialog boxes.

**Comment by JeffryBooher** [comment]
http://support.apple.com/en-us/HT201236

**Comment by pthiess** [comment]
@jeremiahlee As a workaround you may use tab to go to the Don't Save button.

**Comment by peterflynn** [comment]
Closing as fixed
