### ISSUE TITLE
UI text rendering is not clear in linux.

### ISSUE THREAD

**Issue by lixiaoyan** [adobe/brackets#10235]
I noticed that the default UI font is loaded by web font (`@font-face`). I tried to change the font to some local font, and it looked better than before. I'm not true that is a cef's bug or not, but as a workaround, adding a custom font option to brackets may be a good solution.

* * *

"Source Sans Pro" loaded by `@font-face`

![brackets](https://cloud.githubusercontent.com/assets/1610614/5504862/94dd4840-87c4-11e4-91b9-7264022cc108.png)

* * *

local font "Source Sans Pro"

![brackets-after](https://cloud.githubusercontent.com/assets/1610614/5504888/f35f8e6e-87c4-11e4-8d1b-031bb74f6311.png)

**Comment by pthiess** [comment]
https://github.com/adobe/brackets/issues/6094

**Comment by JeffryBooher** [comment]
closing as dup
