### ISSUE TITLE
Shortcuts with some key names like PageUp/PageDown do not show up in mac menus.

### ISSUE THREAD

**Issue by RaymondLim** [adobe/brackets#10249]
Note: You need to do the following steps either with release 44 build or use `rlim/more-key-names` branch (from pull request #10247).

1. Try to reassign some shortcuts with `PageUp` or  `PageDown` in src/base-config/keyboard.json. Or remap a shortcut in user key map if you are using `rlim/more-key-names` branch.
2. Save the file and relaunch or reload Brackets.

Result: The reassigned shortcut does not show up in the reassigned menu item. You can see the issue with `Home`, `End` and `Insert` keys also.

On Windows, you can see shortcuts with all those keys but the execution of shortcuts with PageUp/PageDown is not invoked from the native menu.

**Comment by redmunds** [comment]
Confirmed. Closing.
