### ISSUE TITLE
Brackets underlines file names as typing errors

### ISSUE THREAD

**Issue by nicolo-ribaudo** [adobe/brackets#10241]
![](https://cloud.githubusercontent.com/assets/7000710/5511455/069cab66-87ce-11e4-9e0b-d28e1d653515.jpg)

Can you see the red line under the `.gitignore` word?

**Comment by JeffryBooher** [comment]
Try adding `autocorrect=off` to the input field http://css-tricks.com/snippets/html/autocomplete-off/

**Comment by JeffryBooher** [comment]
This affects all input fields (quick open, find, find in files, etc...)

**Comment by pthiess** [comment]
Ok, lets make a medium priority.

**Comment by MarcelGerber** [comment]
Found an easy fix over at #10321.

**Comment by JeffryBooher** [comment]
@nethip can we get the fix in for the next release? this is a major annoyance...

**Comment by nethip** [comment]
@JeffryBooher Sure! will look at it.

**Comment by nethip** [comment]
Closing this as this got fixed by #10321
