### ISSUE TITLE
Support rebeccapurple

### ISSUE THREAD

**Issue by le717** [adobe/brackets#10250]
Both LESS 2.0 and Sass 3.4 support [recbeccapurple `#663399`](http://lists.w3.org/Archives/Public/www-style/2014Jun/0312.html). [All browsers](http://browsernative.com/rebeccapurple-ccs-named-color-378/) and [IE 11+](https://github.com/InternetExplorer/Status.IE/issues/103) supports it. Right now, trying to use Quick Edit on the color results in a "No Quick Edit Available" message.

This would also require updating our copy of TinyColor to v1.1.1, the newest (and currently only) version of TinyColor to support it. However, the author made breaking API changes in v1.0 that breaks QE.

(Side note: I've already updated TinyColor and fixed the API calls in #9596).

**Comment by peterflynn** [comment]
Already in progress, but not considered urgent so removing milestone

**Comment by le717** [comment]
@peterflynn Yea, full support is tied up in the complicated PR #9596. :\

**Comment by redmunds** [comment]
Confirmed. Closing.
