### ISSUE TITLE
Project Root vs. (Webservers) Document Root

### ISSUE THREAD

**Issue by bbak** [adobe/brackets#10268]
It's not uncommon to have projects, where the (physical) file-root - and therefore Brackets Project root - differs from the Webservers Document-Root. But Brackets doesn't seem to support such a setup. E.g. look at a typical Zend Framework 2 MVC-style project, where views (HTML) are placed in e.g. $DOCUMENT_ROOT/../module/Application/view

Despite the fact, that Live-Preview will (presumably) never work in such kind of Projects, since there's a complex relation (MVC-Router) between FileSystem Paths and URL's, it should be possible to set the $Project-Root to $DOCUMENT_ROOT/../, and have brackets resolve (relative or absolute) paths according to the Webservers $DOCUMENT_ROOT (e.g. $Project-Root/public).

IMHO there should be an Option to set a subfolder of the Project-Root as Webservers Document-Root.

**Comment by peterflynn** [comment]
Related to this item on our feature backlog: [Make Live Development Work For Router-Based Technologies](https://trello.com/c/uKewlref/708-research-make-live-development-work-for-router-based-technologies).  But maybe for simpler use cases like this, we don't need that full feature.

**Comment by peterflynn** [comment]
Closing since it looks like [Live Preview: using a local server is confusing](https://trello.com/c/7OaIE6lV/1301-live-preview-using-a-local-server-is-confusing) already covers this.  Please upvote!  I'm hoping this is one we can get to soon...
