### ISSUE TITLE
Adobe Extract "Copy text" in PSD not working in Linux version

### ISSUE THREAD

**Issue by camplusplus** [adobe/brackets#10261]
Cannot copy text from PSD in Linux

**Comment by nethip** [comment]
@camplusplus which flavor of Linux are you using?

**Comment by camplusplus** [comment]
Standard ctrl-v don't work in gentoo,ubuntu 14.4 and fedora 21.
Found a solution with ctrl-space. 
Please point this out to new users!
Thanks!

**Comment by nethip** [comment]
@camplusplus Thanks for reporting this. We are now tracking this bug internally in Adobe Extract bug tracker. We will provide an update once we have one on this bug.

**Comment by hardikdangar** [comment]
Any update on this bug? i have the same issue in ubuntu 14.04

**Comment by nethip** [comment]
@hardikdangar We are tracking this internally and targeting for 1.4 which is due shortly. 
@prafulVaishnav Could you take a look into this issue?

**Comment by alnat2** [comment]
Ubuntu 14.04, brackets 1.5 - copy text still doesn`t work (

**Comment by limestreet** [comment]
Hi all,
Ubuntu 14.04 - brackets 1.6 - doesn't work.

**Comment by libertyswift** [comment]
Debian 8.2  - brackets 1.6 - doesn't work.

**Comment by abose** [comment]
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
