### ISSUE TITLE
Adobe Extract overrides important AltGr shortcuts on international keyboards

### ISSUE THREAD

**Issue by FezVrasta** [adobe/brackets#10270]
On QWERTY keyboards we use:

<kbd>Alt Gr</kbd> + <kbd>+</kbd> to write <kbd>]</kbd>

But when I've Adobe Extract opened it is used to zoom the PSD and the symbol is not inserted.

**Comment by yoyoy** [comment]
@redmunds hello,
please whai is the code to handle Alt Gr ? 
i tried in keymap.json

{
    "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
    "overrides": {
         "AltGr-P": "xxxxx.shortcuts"
    }
}

but brackets say the shortcut is not good
i do not find anything about it on https://github.com/adobe/brackets/wiki/User-Key-Bindings

thanks

**Comment by MarcelGerber** [comment]
@yoyoy You can simply write "Ctrl-Alt-P" rather than "AltGr-P".

**Comment by WilliamVercken** [comment]
Same problem on Windows and Brackets 1.2 on an AZERTY keyboard.
If I want to do this <code>}</code> I have to do <code>AltGr</code> + <code>+</code>, and when Extract if open, it zooms.

![image](https://cloud.githubusercontent.com/assets/1272792/6940383/8d8aee14-d876-11e4-8d84-81e092fdf288.png)

**Comment by FezVrasta** [comment]
Fixed buying a MacBook with american keyboard layout :D 

I'm still sure there must be some easier fix...

**Comment by prksingh** [comment]
I have filed this internally for Extract. I may not get fixed in this release but hopefully the next one

**Comment by JulienJo** [comment]
Hi! The problem seems to be still there: on an PC AZERTY keyboard.
If I want to do this  `}`, I have to do `AltGr` + `=`,  and when Extract if open, it zooms.

**Comment by abose** [comment]
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
