### ISSUE TITLE
Unable to access the extensions registry. Please try again later.

### ISSUE THREAD

**Issue by darkcyber** [adobe/brackets#10279]
Just try access extensions registry via File > Extensions manager and get this error.

Unable to access the extensions registry. Please try again later.

Enable show developer tools to see what going on and here is the error.

registry.json?_=1419591267246
s3.amazonaws.com/extend.brackets
GET	(failed)
net::ERR_PROXY_CONNECTION_FAILED

my connection without proxy, so how to fix this problem ? is i use bad ip or something ? 

thanks a lot.

**Comment by nethip** [comment]
@darkcyber are you still seeing this issue? If you are still seeing this problem could you try connecting to a different network and launch extension manager? 

And also could you paste the following into the browser and see if you are able to get some contents from the server?

"https://s3.amazonaws.com/extend.brackets/registry.json"

**Comment by darkcyber** [comment]
Sorry for late update. now it's work. what i do is Control panel > internet options > connections tab > LAN Setting > make sure Automatically detect setting is checked and leave the other unchecked.

dont know why this things happen.

**Comment by rajnishcs** [comment]
plz check your internet connection. aal this works while you are online..
