### ISSUE TITLE
Improvements to Quick Open / Quick find definition

### ISSUE THREAD

**Issue by ronen1malka** [adobe/brackets#10278]
1) When project get bigger, it is very hard to find files.
Allowing wildcard ('*') in Quick Open / Quick find definition (like in eclipse search dialogs) is very useful

2) Allow filter sets for Quick Open / Quick find definition, so it is posible to exclude node_modules or other files.

**Comment by peterflynn** [comment]
(1) -- This is how it works already.  Quick Open & Quick Find Definition use a "fuzzy search," so you can omit any characters you want and it will be treated as if you had typed a `*`.  If it doesn't work this way for you, could you give an example of a filename you're expecting to find plus a search string where that filename does not appear in the top results?

(2) -- It's not possible yet, but I think we may start work on a solution for this soon.  Please upvote this item on our feature backlog to help raise priority: [File exclusion/filtering beyond Find in Files](https://trello.com/c/zd77LxFS/1229-2s-file-exclusion-filtering-beyond-find-in-files).

**Comment by peterflynn** [comment]
Closing since there doesn't appear to be a bug here, and the missing feature (2nd point) is already tracked on our backlog.
