### ISSUE TITLE
Brackets can't be closed when full screen

### ISSUE THREAD

**Issue by kartikm** [adobe/brackets#10287]
OS: Debian GNU/Linux, Sid/Unstable.
Brackets version: 1.1.0-15558

Steps to reproduce:
1. Open Brackets.
2. Full screen it.
3. Click on close button.
4. It won't close.
5. Unmaximize the Brackets.
6. Click on close button.
7. Brackets will close!

**Comment by peterflynn** [comment]
Closing as a duplicate of #4611
