### ISSUE TITLE
UI font invisible resulting in Brackets 1.1 unusable.

### ISSUE THREAD

**Issue by dmxt** [adobe/brackets#10282]
OS: Windows 8 Pro x64.

Bug appeared after updating to Brackets 1.1 from 1.0. 

Brackets 1.1 screenshot
![udtoyp](https://cloud.githubusercontent.com/assets/3248782/5560098/7561d9d2-8d27-11e4-8c40-b168fc33e898.png)

Brackets 1.0 screenshot
![uhlnxb](https://cloud.githubusercontent.com/assets/3248782/5560107/129446cc-8d28-11e4-89b5-8685789a02e9.png)

**Comment by ankitjaininfo** [comment]
+1 facing the same issue: 
![brackets error](https://cloud.githubusercontent.com/assets/3761243/5610314/382d3802-94db-11e4-843e-1b262985a185.png)

**Comment by ankitjaininfo** [comment]
Updated all of my extensions and it is working good. Thankx for help @RaymondLim

**Comment by peterflynn** [comment]
Closing as extension problem -- we haven't heard back from @dmxt but the screenshot clearly shows one of the tree-icon extensions installed, so all evidence suggests it's the same as #10213.  Let us know if not, and we can reopen this.
