### ISSUE TITLE
git configuration is broken

### ISSUE THREAD

**Issue by openube** [adobe/brackets#10292]
On MacOSX  Yosemite 10.10.1, running Bracket Release 1.1 build 1.1.0-15558 (release ea908cae5) 
build timestamp: Thu Dec 18 2014 10:23:06 GMT-0800.

The "Path to Git Executables" is set to "git" by default, and does not allow changes. Everytime when value is changed and saved, bracket restart, and goes back to "git".

**Comment by MarcelGerber** [comment]
That's an issue with the brackets-git extension. Please report it over here: https://github.com/zaggino/brackets-git

**Comment by busykai** [comment]
@openube, closing as it is an extension issue. Please file an issue against zaggino/brackets-git.

cc @zaggino
