### ISSUE TITLE
[Linux] showOpenDialog initialPath doesn't work

### ISSUE THREAD

**Issue by Wikunia** [adobe/brackets#10297]
When I use initialPath inside `showOpenDialog` my File Manager shows me the recently used folders and when I use it in `showSaveDialog` everything works as I expect.
My initialPath variable is `ProjectManager.getProjectRoot()._path` 
So this is working 
`FileSystem.showSaveDialog(title, initialPath, "",`

this isn't
`FileSystem.showOpenDialog(allowMultipleSelection, chooseDirectories, title, initialPath, fileTypes,`

My machine:
Linux 3.17.6
Brackets 1.1.0

**Comment by sbruchmann** [comment]
Try using `ProjectManager.getProjectRoot().fullPath` instead of `ProjectManager.getProjectRoot()._path`.

**Comment by Wikunia** [comment]
@sbruchmann it shows the same path and doesn't work as well. And I think because it works with the save dialog it should work with the open dialog, too.

**Comment by sbruchmann** [comment]
Ah, I misread your issue. Sorry for the inconvenience.

**Comment by Wikunia** [comment]
Do you have the same problem? I will try it with Windows in the next days.

**Comment by sbruchmann** [comment]
Works on my machine™

My setup:
  - OS X 10.9.5
  - Brackets Release 1.2 development build 1.2.0-15578 (master da48369fb) 
build timestamp: Thu Jan 01 2015 23:47:59 GMT+0100
  - Brackets Shell [d9b1cae](https://github.com/adobe/brackets-shell/commit/d9b1cae9d126f9712f426d08d0408d3dfc20b6c2)

Tested with the following code sample:

```javascript
define(function () {
    "use strict";

    var AppInit = brackets.getModule("utils/AppInit");
    var FileSystem = brackets.getModule("filesystem/FileSystem");
    var ProjectManager = brackets.getModule("project/ProjectManager");

    function main() {
        FileSystem.showOpenDialog(
            false,
            false,
            "Open a file",
            ProjectManager.getProjectRoot().fullPath,
            null
        );
    }

    AppInit.appReady(main);
});
```

**Comment by MarcelGerber** [comment]
![](http://blog.codinghorror.com/content/images/uploads/2007/03/6a0120a85dcdae970b0128776ff992970c-pi.png)

Windows 8.1
Brackets @ latest master
Release 1.1 Brackets Shell

**Comment by sbruchmann** [comment]
So, it appears to be Linux only then, right?

**Comment by Wikunia** [comment]
Yes it is a Linux only problem! I've tested it on my Windows machine and everything works properly.

**Comment by peterflynn** [comment]
Fixed in 1.2 -- see PR adobe/brackets-shell#496.

**Comment by nethip** [comment]
@Wikunia As the fix now in the master, could you verify if the PR has fixed the problem?

**Comment by Wikunia** [comment]
@nethip is this fix already in Brackets or onlu in brackets-shell? I updated my fork yesterday and it didn't work.

**Comment by nethip** [comment]
@Wikunia . This is a fix in brackets-shell. You need to rebuild brackets-shell on Linux. As master branch is not yet ready for Linux compilation please use jasonsanjose/cef_217_linux branch to build Brackets on Linux. Here is the wiki for building brackets on Linux.

https://github.com/adobe/brackets-shell/wiki/Building-Brackets-Shell

**Comment by nethip** [comment]
@wikunia I checked if this is fixed or not and it is now fixed on Linux. The current Linux installer(posted at brackets.io) does not have this change. So when we post the next Linux installer, you can expect this issue to be fixed. Currently we are struggling with fixing the hang issues when quitting Brackets on Linux(after updating to latest version of chromium). All of the fixes relating to this are tracked at this PR. https://github.com/adobe/brackets-shell/pull/499. 

I am closing this issue. Feel free to open this, if you feel the fix is not proper. Thanks!
