### ISSUE TITLE
Code Snippets

### ISSUE THREAD

**Issue by assunluis** [adobe/brackets#10299]
Please add code snippets support, something easy like Emmet: expandable snippets with TAB. It's a huge time saver for any kind of projects. I have tried already some plugins, but they're just too complicated and messy. And it's a really shame that Emmet doesn't supports snippets for JavaScript.

**Comment by peterflynn** [comment]
@assunluis Please upvote this item on our feature backlog: [Code Snippets/Template: Insert & manage snippets](https://trello.com/c/tVSVhAg2/342-code-snippets-template-insert-manage-snippets).  Also definitely check out the very popular [Brackets Snippets extension](https://github.com/jrowny/brackets-snippets).

Closing to avoid duplication.
