### ISSUE TITLE
Linux version on ARM architecture

### ISSUE THREAD

**Issue by henrywright** [adobe/brackets#10298]
I'm running Ubuntu Linux on a Chromebook that has a Samsung Exynos processor (an ARM chip). When I use my package installer I get the error "Error: Wrong architecture i386"

Is a version of Brackets available for me?

Thank you in advance.

**Comment by peterflynn** [comment]
@henrywright From https://github.com/adobe/brackets/issues/9877#issuecomment-64026586: CEF (Chromium Embedded Framework) [doesn't currently support ARM](http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=1319) as far as I know, and that's a blocker for Brackets.  It looks like other similar desktop shells don't yet support ARM either -- see rogerwang/node-webkit#437 and atom/atom-shell#366.

**Comment by jasonsanjose** [comment]
@henrywright I wouldn't recommend it since I haven't used it, but there's an unofficial port of Brackets as a Chrome Web App. It's called Tailor. See https://chrome.google.com/webstore/detail/tailor/mfakmogheanjhlgjhpijkhdjegllgenf.

Closing.

**Comment by henrywright** [comment]
@jasonsanjose isn't that port way out-of-date?

**Comment by jasonsanjose** [comment]
Seems like it, yeah. You could bug the author https://github.com/ryanackley/tailor.

**Comment by henrywright** [comment]
Can I instead bug you guys for an officially supported port? ha :)

**Comment by peterflynn** [comment]
@henrywright You can upvote this item on our feature backlog: [Brackets as a ChromeOS / Chrome Packaged App](https://trello.com/c/VdWIbNqo/698-brackets-as-a-chromeos-chrome-packaged-app).  But it's definitely not a high priority for the core team at the moment -- we've got our hands full with the other platforms as it is!

**Comment by henrywright** [comment]
Thanks @peterflynn I've voted
