### ISSUE TITLE
Can’t use console API from within an extension command handler

### ISSUE THREAD

**Issue by sbruchmann** [adobe/brackets#10305]
This is strange. Take a look at the following code of a sample extension:

```javascript
define(function () {
    "use strict";

    var AppInit = brackets.getModule("utils/AppInit");
    var CommandManager = brackets.getModule("command/CommandManager");
    var Menus = brackets.getModule("command/Menus");

    function main() {
        CommandManager.register("test", "com.example.test", test);
        Menus.getMenu(Menus.AppMenuBar.FILE_MENU).addMenuItem("com.example.test");
    }

    function test() {
        console.log("hello world");
    }

    AppInit.appReady(main);
});
```

In case you don’t know, the code above registers a new command and adds a menu item to `File` menu as soon as Brackets is ready. The command logs `"hello world"` to the console.

The problem is, that the command handler (`test()`) doesn’t get executed when triggered via the menu item as soon it contains a call to the `console` API. Substituting `console.log("hello world")` with `$("#main-toolbar").toggle()` works. Calling `test()` directly works as expected, no matter what is being executed inside of `test`.

There are no errors logged to the console and Brackets did behave as usual afterwards. I’ve yet to find a way to debug this.

‘Reload without extensions’ is not applicable here, so I’ve temporarily disabled all user extensions.

System Setup:
  - OS X 10.9.5
  - Brackets Release 1.2 development build 1.2.0-0 (master da48369fb)
  - Brackets Shell [d9b1cae](https://github.com/adobe/brackets-shell/commit/d9b1cae9d126f9712f426d08d0408d3dfc20b6c2)

**Edit**: Fixed copy & paste error as mentioned in [this comment](https://github.com/adobe/brackets/issues/10305#issuecomment-68622687).

**Comment by busykai** [comment]
`COMMAND_ID` is `undefined`. If changed to `"com.example.test"` works perfectly for me.

**Comment by sbruchmann** [comment]
@busykai Oops, this was just a copy & paste error. Still doesn’t work for me.

**Comment by sbruchmann** [comment]
To make things a tad weirder as before: Adding a key binding to the command executes the command handler. Invoking the menu item directly is still not working.

**Comment by sbruchmann** [comment]
Damn, I found the culprit! He was sitting 10 inches in front of the screen…

The problem was that I invoked the command while devtools were focused. It’s too early on a Sunday morning (GMT) ;). Closing.
