### ISSUE TITLE
Find All and Select with RegEx

### ISSUE THREAD

**Issue by gmaggio** [adobe/brackets#10306]
Not sure how handy it is but can we add the ability to use **RegEx** with **Find All and Select**?

**Comment by peterflynn** [comment]
@gmaggio How do you picture this working?  Do you want a button in the Find bar that selects all the results?  Or would you type a regexp into the code editor, select that text, and then hit the current 'Find All and Select' keyboard shortcut?

There's a similar feature in Sublime (Quick Find) which doesn't appear to support a regex either...

**Comment by redmunds** [comment]
We have this item in our backlog: https://trello.com/c/eZTEudAp/1140-multiselect-find-all-from-find-bar

**Comment by gmaggio** [comment]
I think it would be more convenient if could have a dedicated **button in the Find bar**, just like how **Notepad++** does it.

**Comment by peterflynn** [comment]
So the first thing I said above, right?  I believe that's already captured in the backlog item Randy linked to above, so I'll close this issue to avoid redundancy.  Please upvote that item to help raise its priority (it's already got my vote!).
