### ISSUE TITLE
Brackets freezes after opening a file

### ISSUE THREAD

**Issue by llewellynathan** [adobe/brackets#10301]
Immediately after opening a file (I've tried html and css files) Brackets freezes up and will not do anything. The only thing I can do is use Force Quit to quit the application. Before opening a file I can do things such as view the About page or view the extensions manager. I've tried uninstalling an re-installing Brackets but the issue persists. I've also tried reverting to Brackets 1.0 but the issue exists in the older version as well.

**Comment by redmunds** [comment]
Try [Clearing your cache](https://github.com/adobe/brackets/wiki/Cache-Folder). This will remove all preferences, extensions, etc. and reset Brackets back to factory settings. When you open Brackets you should be in the Getting Started folder with index.html open. Do you get that far?

If not, what's you OS and version?

If so, it may be related to the files in your project. Try narrowing it down to a particular set of files.

See [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting) for more things to try.

**Comment by peterflynn** [comment]
@llewellynathan Also, try disabling all extensions via _Debug > Reload Without Extensions_.  (Note: clearing your cache will _not_ actually remove all extensions -- if you want to do that, delete the entire parent folder of the cache folder).

**Comment by peterflynn** [comment]
Closing since there's been no response.  @llewellynathan let us know if you've been able to try any of the suggestions above & we can reopen this.
