### ISSUE TITLE
Brackets scroll speed

### ISSUE THREAD

**Issue by Max-Enrik** [adobe/brackets#10307]
How can I slow brackets scroll speed?
Thanks.
Please quickly answer.

**Comment by Max-Enrik** [comment]
I fix it already! :)

**Comment by sbruchmann** [comment]
Hello @Max-Enrik,

it would be nice if you could share how you resolved your problem so other people, who have the same problem, can benefit from it.

**Comment by doodack** [comment]
I've also noticed that scroll speed increased recently (not sure it's a Brackets issue or something with my drivers). @Max-Enrik, please let us know how have you handled this problem.

**Comment by peterflynn** [comment]
@doodack This is a duplicate of #10214, so it'd be better to have the discussion there.

**Comment by vimxts** [comment]
My reproduction, not sure if relevant is:

1. Have Windows 10 (Maybe it's a "Windows 8" problem)
2. Use Brackets 1.1

**Comment by trjstewart** [comment]
Did anyone find a solution to this? Having same issue with Windows 10 and Brackets 1.4

**Comment by 50l3r** [comment]
+1 Tell us how you solve
