### ISSUE TITLE
Code hint command doesn't work after automatic scrolling

### ISSUE THREAD

**Issue by Wikunia** [adobe/brackets#10319]
I have an issue for my FuncDocr extension:
https://github.com/Wikunia/brackets-FuncDocr/issues/11

and I think it's a brackets error. 
I use the following code to set a selection and start the show code hints command:

```
editor.setSelection(posStart, posEnd);
CommandManager.execute(Commands.FILE_SAVE).done(function() {
	CommandManager.execute(Commands.SHOW_CODE_HINTS);
});
```

It doesn't work when the text between `posStart` and `posEnd` isn't visible at the moment -> scrolling needed.

**Comment by redmunds** [comment]
@Wikunia Try using `editor.setCursorPos()`. That should scroll the cursor into view.

**Comment by Wikunia** [comment]
@redmunds I've tried this:

```
editor.setCursorPos(posEnd);
editor.setSelection(posStart, posEnd);
CommandManager.execute(Commands.FILE_SAVE).done(function() {
	CommandManager.execute(Commands.SHOW_CODE_HINTS);
});
```

But unfortunately it doesn't work.

**Comment by redmunds** [comment]
Actually, `editor.setSelection()` should work. Try passing 'true' for `center` parameter to horizontally center selection:

```js
    editor.setSelection(posStart, posEnd, true);
```

**Comment by Wikunia** [comment]
@redmunds that works but maybe isn't the expected behavior.

**Comment by redmunds** [comment]
@Wikunia There are additional parameters, so see if there are better `centerOptions` to use.

**Comment by Wikunia** [comment]
Thanks @redmunds !
