### ISSUE TITLE
Expect to provide a stronger support for Vim Mode

### ISSUE THREAD

**Issue by cmgddd** [adobe/brackets#10311]
There are about two good extensions of Vim Mode for Brackets. But there is  a bug both of them.
The cursur disappears when I move to the HTML Tag. And it really makes me upset. Is there any good solution, pls take care of this defect, tks. ) ^ - ^ (
![111](https://cloud.githubusercontent.com/assets/2402885/5612936/7d4d2a00-9517-11e4-8bc3-723235f2ad18.gif)

**Comment by redmunds** [comment]
@cmgddd You'll need to open issues in the repos of the extensions. I suspect extensions have not been updated since Brackets added multicursor support, but author can contact us if they don't know how to fix issue.

**Comment by peterflynn** [comment]
It looks related to the matching-tag highlighting to me -- possibly a z-order issue.  @cmgddd Does this still happen if you revert back to the default light-colored theme?

**Comment by cmgddd** [comment]
yes，both of the two default theme do.

**Comment by redmunds** [comment]
@cmgddd I think the extensions need to add CSS Rules similar to the [`div.CodeMirror-cursors` rule in brackets_codemirror_override.less](https://github.com/adobe/brackets/blob/master/src/styles/brackets_codemirror_override.less#L108-L1170). Can you file issues on the repos of those extensions and post links back to here?

**Comment by peterflynn** [comment]
(Edited title to be more specific)
