### ISSUE TITLE
highlight the similar texts if selected one and close/delimit the braces and quotes or apostrophes automatically while coding

### ISSUE THREAD

**Issue by brohi-ag** [adobe/brackets#10310]
Sir,
I want to have a feature in brackets that highlights the similar texts when selected one. The other feature, which demand is that when I code in the brackets, the braces and quotes are not closed/delimited automatically.

These features can be seen in phpdesigner version 8.

Without having these features, I feel a lot of difficulty while coding and intend to switch on PhpDesigner.

thanks,
Abdul Ghafoor Brohi

**Comment by sbruchmann** [comment]
Hello @brohi-ag,

today’s your lucky day! as all these features are already implemented! ;)

To enable the automatic closing of braces and quotes, go to `Edit -> Auto Close Braces`.
To enable the highlighting of the word matches, go to `Debug -> Open Preferences File` and add `"highlightMatches": true,` (Note the trailing comma!)

**Comment by peterflynn** [comment]
Closing since there doesn't appear to be a bug here.
