### ISSUE TITLE
Remember which linter is 'open'

### ISSUE THREAD

**Issue by cfjedimaster** [adobe/brackets#10316]
If you view a file with N filters, you can collapse and open each one. Imagine you hit a JS file and it shows JSLint and JSHint issues. You close the list of JSLint ones, navigator to another file, and then return. When you return, the JSLint issues are opened again.

**Comment by nethip** [comment]
@cfjedimaster possibly related (https://github.com/adobe/brackets/issues/10317).

**Comment by ficristo** [comment]
Fixed by https://github.com/adobe/brackets/pull/11641
