### ISSUE TITLE
Disabling F keys

### ISSUE THREAD

**Issue by moeiscool** [adobe/brackets#10318]
How do i disable the F1 - F12 keys on  brackets? Whenever i F12 by accident it opens my web browser and when i go back to brackets, brackets crashes. I need either it to stop crashing or to disable the keys from functioning so that I don't lose my work again and again.

**Comment by redmunds** [comment]
Use: Debug > Open User Key Map to create and open a new keymap.json file. Then set each of those keys to `null` in the `override` section as follows:

```json
    "overrides": {
        "F1": null,
        "F2": null,
        "F3": null,
        "F4": null,
        "F5": null,
        "F6": null,
        "F7": null,
        "F8": null,
        "F9": null,
        "F10": null,
        "F11": null,
        "F12": null
    }
```

**Comment by moeiscool** [comment]
Thank you!!!!!!!!!!!!!
