### ISSUE TITLE
Problem installing Brackets (error 2503)

### ISSUE THREAD

**Issue by dcutlan** [adobe/brackets#10330]
When I try to install Brackets (on my PC using Windows 8.1) I get an error message as follows:
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The eror code is 2503.
Can someone please help me overcome this.
Many thanks
David

**Comment by nethip** [comment]
@dcutlan Looks like this has to do something with the administrator privileges. Could you please try the steps mentioned in one of the following links and let us know if you are able to install Brackets?

http://www.fixkb.com/2014/01/error-2503-and-2502-when-uninstalling-on-windows-8.html

http://answers.microsoft.com/en-us/windows/forum/windows_7-system/internal-error-25032502/28b361b7-b2d7-494d-8470-5969f6850f5a

**Comment by peterflynn** [comment]
I'd suggest trying these steps:

1. Re-download the installer from http://brackets.io to make sure the download didn't get corrupted
2. [Run installer as admin](https://github.com/adobe/brackets/wiki/Troubleshooting#windows-error-installation-directory-must-be-on-a-local-drive)
3. Gather an installer log following [these instructions](https://github.com/adobe/brackets/issues/10173#issuecomment-68761584) (through please upload the log to a Gist and post the link, so the thread here doesn't get cluttered)

**Comment by prksingh** [comment]
@dcutlan Were you able to resolve this issue? If yes, could you close the issue?

**Comment by dcutlan** [comment]
Thanks, problem solved when I did a clean install of Windows, etc.

 

Many thanks

 

David

**Comment by prksingh** [comment]
Glad its fixed. Closing
