### ISSUE TITLE
File drag and drop, and bundles equivelent

### ISSUE THREAD

**Issue by ApertureStudiosMedia** [adobe/brackets#10334]
Hi i am Willie W,

I have two small request i would like to suggest.

The first request is the option to drag and drop a file in the sidebar into a folder in the sidebar. Example: "If a folder was created in the sidebar, and a file was created in the sidebar but in the wrong folder, having the option to easily drag the file into the correct folder directly from the sidebar without right clicking > reveal in finder (Mac OS)". Also it would be great to make this an boole option incase users do not want files moved accidentally.

The second request i would like to suggest may be a feature already implemented that i am not aware of. I would like to suggest a feature of something like Textmate Bundles, or a macro feature that allows var's to be passed in for easily custom templating/macro codes in a easily development process. Example below:

template $main-layout~ (Enter/Return key)

Equals:

```html
<template name="main-layout">
<users pre defined code></users pre defined code>
</template>
```

=
Sincerly,
Willie W.
Aperture Studios Media

**Comment by peterflynn** [comment]
@ApertureStudiosMedia these suggestions are currently tracked on our feature backlog.  Please upvote them there to help raise priority:

* [Drag/drop within file tree (Copy/Move file)](https://trello.com/c/0WJ1aKw2/287-drag-drop-within-file-tree-copy-move-file)
* [Code Snippets/Templates: Insert & manage snippets](https://trello.com/c/tVSVhAg2/342-code-snippets-templates-insert-manage-snippets)

In addition, you may want to check out the very popular Brackets Snippets extension.

I'll close this though, to avoid duplication with what's already tracked on our backlog.
