### ISSUE TITLE
Wrong order for folders and files in project three

### ISSUE THREAD

**Issue by FezVrasta** [adobe/brackets#10332]
I've just installed Brackets on my new Macbook with Yosemite and there is a problem.

Usually I had all the folders ordered alphabetically first, then all the files ordered alphabetically.
Instead now I have folders and files mixed order alphabetically.

So Instead of:

folder A
folder B
file A
file B

I have

folder A
file A
folder B
file B

**Comment by busykai** [comment]
@FezVrasta, it's by design. Mac default sort order is alphabetical. There's an option to change that: `sortDirectoriesFirst`. See more at [preference section of how-to](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#list-of-supported-preferences).

Closing.
