### ISSUE TITLE
HTML5 video tag not recognized

### ISSUE THREAD

**Issue by zppinto** [adobe/brackets#10339]
Brackets doesn't seem to recognize the video tag used to create the HTML5 videos.

All code after this video tag, will be completely messed up in terms of theme color!

**Comment by redmunds** [comment]
@zppinto Please paste in some markup or a link to markup that causes this problem. You may have some invalid syntax.

**Comment by MarcelGerber** [comment]
This may also be related to https://github.com/adobe/brackets/issues/6774#issuecomment-34303695.
I don't know if our build of CEF 2171 supports video tags.

**Comment by zppinto** [comment]
I have a mix of html with some php echos! And I'm missing a quotation mark, that was the problem!
Sorry for this misunderstood...
Please remove this topic.
