### ISSUE TITLE
Not Working Properly in Ubuntu Gnome

### ISSUE THREAD

**Issue by iamvoid13** [adobe/brackets#10337]
I installed the brackets in ubuntu gnome but it's not working properly.
Firstly it takes some time for startup.Then when I try to install the monokai theme, it just keep loading the after 10 mins when I decided to cancel the installation ,this cancellation screen is not closing  and it is on my screen even after quiting the brackets till now (after 3 hrs of quitting brackets).
![screenshot from 2015-01-09 15 55 31](https://cloud.githubusercontent.com/assets/8265616/5678409/2304e584-9818-11e4-80c8-66eb4e3c88c3.png)

**Comment by JeffryBooher** [comment]
@iamvoid13 are you running a proxy server?

**Comment by iamvoid13** [comment]
yes

**Comment by JeffryBooher** [comment]
You need to open the preferences file `Debug > Open Preferences File` and add add a [proxy](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences) . 

for example
```json
"proxy": "http://localhost:8080/"
```

where "http://localhost:8080/" is the proxy server

**Comment by iamvoid13** [comment]
But what about the screenshot i.e why after cancelling the installation the dialog is not going off .

**Comment by JeffryBooher** [comment]
@dangoor might know better about why ExtensionManager hangs on a cancel with a proxy server.  Looks like there were some issues with Brackets hanging after installing extensions but I don't see any known issues about brackets hanging after canceling a download.  

@iamvoid13 Can you open dev tools and see if anything is reported in the console?  If you start Chrome and navigate to `http://localhost:9234` you will get dev tools for Brackets. Thanks!

**Comment by iamvoid13** [comment]
I think that was a internal error now everything is working fine after setting proxy.
Thanks for your help.

**Comment by peterflynn** [comment]
Just fyi, it _shouldn't_ stay stuck as shown in the screenshot forever.  After 10 seconds, it's supposed to time out ("Canceling the install is taking a long time. An internal error may have occurred.") and give you a Close button.  If it gets hung again without showing that message, please go to http://localhost:9234, click the link to open dev tools, and see if there are any errors listed in the Console view -- that will help us debug why the timeout didn't work as expected.

**Comment by iamvoid13** [comment]
@peterflynn I erase the proxy conf. in the prefrences and try to install the extension ,now it says couldn't connect to server and that dialog can be closed by clicking the close button.So,that was perhaps an internal error on my system.
