### ISSUE TITLE
Brackets Window Permanently Hidden

### ISSUE THREAD

**Issue by spongessuck** [adobe/brackets#10333]
While I was working yesterday, the Brackets UI disappeared and I couldn't get it to reappear. It wasn't after I installed any extensions or updated the version.

The Brackets icon is active in the taskbar, and Task Manager shows it's running, but the window is still hidden.

Uninstalling/re-installing didn't work. Deleting cache folder and preferences files didn't work.

I'm running Windows 7.

**Comment by RaymondLim** [comment]
@spongessuck Try to remove Brackets cache by deleting [username]/AppData/Roaming/Brackets/cef_data and brackets.json file next to that folder.

**Comment by spongessuck** [comment]
@RaymondLim Please see my OP: I already tried deleting the cache folder and preferences files and it didn't fix the issue.

**Comment by RaymondLim** [comment]
@spongessuck Ok, then how about deleting `HKEY_CURRENT_USER/Software/Brackets/Window Position` in system registry.

**Comment by spongessuck** [comment]
That fixed it. Thanks!

Should I close the issue, or is this something the programmers will want to address?

**Comment by RaymondLim** [comment]
Yes, close it. If you can find steps that can corrupt the Brackets window position, then reopen it.
