### ISSUE TITLE
To save window size(Zorin OS 9 Lite).

### ISSUE THREAD

**Issue by fujitatakesh** [adobe/brackets#10335]
It would be better for saving window size when the Brackets closed.

**Comment by peterflynn** [comment]
@fujitatakesh It should be remembering it already.  What OS are you on?  Are you running on a low-privileges user account or anything unusual like that?  Are you plugged into the same monitor(s) as you were when you quit Brackets?

**Comment by fujitatakesh** [comment]
I tried on Windows 8.1 the window size was remembered.
I guess it's cause of OS. I'm using ZorinOS 9 Lite(not so major). Normal user and same monitor.

**Comment by busykai** [comment]
This is duplicated of #7174.

**Comment by fujitatakesh** [comment]
Thank you for pointing out.

**Comment by peterflynn** [comment]
Shoot, sorry -- I'd forgotten Linux doesn't have that implemented yet
