### ISSUE TITLE
Replace in Files, Replace in Selected Files/Folder - Exclusion Set - no option to create inclusion set

### ISSUE THREAD

**Issue by LukaszGrela** [adobe/brackets#10336]
I'm trying to do a search and replace in specific files (*.srt) the easiest would be to have a pattern *.srt but as the "Edit Exclusion Set" in purpose limits the results I have to enumerate everything that should be excluded. I have a number of various files and listing them would be problematic. Can the negation operation could be added to this functionality - we could do something like !*.srt which would exclude all not matching the pattern? or the new "Edit Inclusion Set" that will work in opposite way, will allow only files/folders matched the pattern.

**Comment by redmunds** [comment]
@LukaszGrela Thanks for filing feature requests! We are tracking that feature in [this product backlog item](https://trello.com/c/9IBv6zRq/1359-find-in-files-inclusive-filters) and [this epic card](https://trello.com/c/BVOItG11/987-epic-find-search-replace). Please add your vote. Closing this issue.
