### ISSUE TITLE
Live Preview With Other Browsers Not Working

### ISSUE THREAD

**Issue by CEOofApple** [adobe/brackets#10345]
I have tried to edit the .json file, but Live Preview with safari still does not work

**Comment by redmunds** [comment]
Can you paste the contents of your brackets.json file here to make sure there are no syntax errors?

**Comment by CEOofApple** [comment]
{
    "debug.showErrorsInStatusBar": false,
    "themes.theme": "ruby-blue",
    "useTabChar": false,
    "linting.collapsed": true
    "livedev.multibrowser": true
}

**Comment by RaymondLim** [comment]
@CEOofApple You have  a missing comma after `"linting.collapsed": true`

**Comment by CEOofApple** [comment]
Yeah, I just realized after i posted that. its working now. Thanks anyways
