### ISSUE TITLE
Brackets 1.1 Live Preview renders nodes instead of real content

### ISSUE THREAD

**Issue by 01Kuzma** [adobe/brackets#10349]
Brackets 1.1 Live Preview renders nodes instead of real content 
(Windows7 x64)
![untitled-1](https://cloud.githubusercontent.com/assets/569504/5695440/649b335a-99ac-11e4-8f95-1e8614e6dd87.jpg)

**Comment by ApfelUser** [comment]
Which Browser are you using? Have you tried disabling all plugins?

**Comment by 01Kuzma** [comment]
Chrome 39, after the app's  restart the problem has disappeared, but the precedent took place

**Comment by ApfelUser** [comment]
So, after restarting - does the problem still occur, or is it gone?

**Comment by 01Kuzma** [comment]
at this moment it's gone

**Comment by ApfelUser** [comment]
Okay, well I guess you can close this now. If it re-occurs just reopen this issue.

**Comment by 01Kuzma** [comment]
ok
