### ISSUE TITLE
Live preview with Opera browser doesn't work - stuck with "connecting"

### ISSUE THREAD

**Issue by 4rlekin** [adobe/brackets#10353]
As encouraged in last blog post i tried cross-browser live preview with Opera (`26.0.1656.60`) running it on  Linux Mint with Cinnamon interface (`Ubuntu 14.04.1 LTS (x86_64; X-Cinnamon)` as seen by browser).
So far (~10 minutes) nothing happened and when i hover mouse pointer over live preview button i see in tooltip: "Live preview - connecting..."
AFAIK Opera is based on the same engine as Chrome.
Brackets used (from brackets):
`sprint 1 experimetnal build 1.1.0-15558 (release ea908cae5)` 
`build timestamp: Wed Dec 17 2014 13:00:52 GMT-0800`

**Comment by MarcelGerber** [comment]
Could you just try [this workaround](https://github.com/adobe/brackets/issues/10229#issuecomment-67845699)?

**Comment by 4rlekin** [comment]
Worked like charm! Thanks a lot.
Also im very sorry, i searched through the issues using keyword "opera" (silly me) so i didn't found that issue.
