### ISSUE TITLE
Open With Function

### ISSUE THREAD

**Issue by CEOofApple** [adobe/brackets#10354]
Whenever I double click on the HTML file, it opens up Safari. Me, being annoyed by this, decided to right click --> Open With --> Other. I then choose Brackets, and there is an option to always open files like this using Brackets so I check the box, and the next time I double click the HTML file it takes me to Safari again. Is this a Mac problem?

Thanks,

CEOofApple
![screen shot 2015-01-12 at 8 43 38 am](https://cloud.githubusercontent.com/assets/7943257/5703642/39fec16c-9a37-11e4-92f1-4762f2bd7bdc.png)

**Comment by peterflynn** [comment]
I _believe_ the "Always Open With" checkbox only affects that one file, index.html.  If you want to open _all_ HTML files in Brackets, I think you need to right click > Get Info > Open with > Change All.  See "Changing the Default App" in [this tutorial](http://computers.tutsplus.com/tutorials/quick-tip-how-to-change-the-default-application-to-open-files--mac-51413).

**Comment by CEOofApple** [comment]
Thank you very much. It worked
