### ISSUE TITLE
Co-operating

### ISSUE THREAD

**Issue by FyreFeonix** [adobe/brackets#10351]
Is it possible to work in teams on Brackets. I would really like to co-operate with some fellow developers.

**Comment by redmunds** [comment]
@FyreFeonix I think you'll have a better chance of finding people interested in working together by posting on the [brackets-dev forum](https://groups.google.com/forum/?fromgroups#!forum/brackets-dev). There's a [recent post](https://groups.google.com/forum/?fromgroups#!topic/brackets-dev/5fW7BpuUi34) of someone looking for help with an extension.

**Comment by FyreFeonix** [comment]
I know who I want to co-operate with, I just don't know how.

Date: Sun, 11 Jan 2015 17:36:00 -0800

**Comment by prksingh** [comment]
@FyreFeonix Take a look at: 
https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md , especially the Submitting a Pull Request section.You should be creating a separate branch in your local fork of Brackets, pushing that branch to Brackets repo, and then creating a pull request for your branch. It's the same process whether it's 1 file or many. 

Closing this issue.
