### ISSUE TITLE
light theme issue

### ISSUE THREAD

**Issue by jgato** [adobe/brackets#10352]
I have realized that all light themes are showing the same issue: in the area for current open files the font for the name of the miles is dark over a dark background. Almost unreadeable (see attached). This affect all the light themes so it seems to be some core style.

I am using the last version of Brackets on Linux Ubuntu 32bits. 

![aeon](https://cloud.githubusercontent.com/assets/3435696/5701526/9f3e902e-9a4c-11e4-954f-769ae31996f8.png)

**Comment by MarcelGerber** [comment]
Could you just try "Debug > Reload without extensions"?
It looks like your file tree icon provider may be causing this.

**Comment by jgato** [comment]
You are perfectly right. The extension causing my problem was:

https://github.com/thomasvalera/Brackets-Workspaces

Now it looks perfectly. Thanks

**Comment by MarcelGerber** [comment]
Nice. Could you please file an issue over there and close this issue then?

cc @thomasvalera

**Comment by peterflynn** [comment]
Closing as extension problem
