### ISSUE TITLE
Find "exact match"

### ISSUE THREAD

**Issue by j-w-miller** [adobe/brackets#10367]
Evaluating this tool and first obstacle was that there was no option to search for an **exact match**. Search the internet and couldn't find any documentation for this feature. Did i miss something? Many editor have this feature and is nearly a showstopper for me. Otherwise, nice tool.

**Comment by redmunds** [comment]
@j-w-miller You can enable regex searching by clicking on `.*` toggle button. Then you can use `\bword\b` to find an exact match for "word". With that said, we hope to simplify that some day.

**Comment by j-w-miller** [comment]
That helps, thanks for timely response
