### ISSUE TITLE
Quickview min image size too large

### ISSUE THREAD

**Issue by EJanuszewski** [adobe/brackets#10362]
Only a small change, seems there's no need for a min-width on the container either.

I have tested with various image sizes and all seem to behave as expected, I will send the pull request shortly.

**Comment by prafulVaishnav** [comment]
@EJanuszewski @peterflynn I was trying to know the pros and cons for keeping min-width for preview. I think, minimum width of 100px will be useful for preview of small image size. If its large, we can reduce the min width size.

**Comment by EJanuszewski** [comment]
@prafulVaishnav @peterflynn Shall I hold back on both pull requests then until a final decision?

**Comment by prafulVaishnav** [comment]
@EJanuszewski Fixes to issue  #5960 and #10180 which is present in Brackets.less are considerably good and can be merged. So, as discussed you could create Pull Request for same.

**Comment by EJanuszewski** [comment]
@prafulVaishnav I'm not too sure how to do a pull request for just one file, could you give me some assistance?

**Comment by redmunds** [comment]
@EJanuszewski You should be creating a separate branch in your local fork of Brackets, pushing that branch to Brackets repo, and then creating a pull request for your branch. It's the same process whether it's 1 file or many. Take a look at the [How to Hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) article, especially the [Submitting a Pull Request section](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets#submitting-a-pull-request).

**Comment by baherramzy** [comment]
Friendly ping to close this issue if it has been fixed.
