### ISSUE TITLE
Server disk space full

### ISSUE THREAD

**Issue by EJanuszewski** [adobe/brackets#10363]
No space left on device

http://dev.brackets.io/brackets-contributor-license-agreement.html

![Screenshot](http://puu.sh/er9BH/d448a2ff69.png)

**Comment by EJanuszewski** [comment]
This appears to have been fixed as I managed to successfully submit the form this morning, i'll let you close it if you feel it's ok.

**Comment by ingorichter** [comment]
Okay, if this was resolved, then we close it for now.
