### ISSUE TITLE
Package Brackets as a zip file

### ISSUE THREAD

**Issue by James-Parsons** [adobe/brackets#10365]
I am trying to get Brackets to be more portable, and non-admin friendly to get. I've noticed that earlier releases of brackets were available as a zip file. This would make things a lot easier, as I don't have to have administrator access on Windows to install it, as well as making it easier to extract to a flash-drive. Could someone possibly do an up to date Brackets release with Extract as a zip file. It would make it a lot easier for me, and I'm sure others to get.

**Comment by redmunds** [comment]
@James-Parsons There's [work being done](https://github.com/adobe/brackets-shell/pull/333) on making a portable Brackets build, so please add your comment there.

Closing this issue.
