### ISSUE TITLE
CSS display: flex doesn't have syntax highlighting

### ISSUE THREAD

**Issue by TriforceOfKirby** [adobe/brackets#10371]
In a CSS document, typing display: flex; doesn't have syntax highlighting for the flex value to match other property values(orange with default theme).

OS: Ubuntu 14.10
Brackets Version: Release 1.1 experimental build 1.1.0-15558

**Comment by MarcelGerber** [comment]
Upstream PR: https://github.com/codemirror/CodeMirror/pull/3032

**Comment by MarcelGerber** [comment]
This is now part of the upstream CodeMirror and is going to make it into Brackets 1.3 (not 1.2).

**Comment by ficristo** [comment]
I can confirm now it works.
