### ISSUE TITLE
"Recent Projects UI" * JS Code Hints unit tests sporadically failing on Mac

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10375]
Of the last 16 builds, half have failed unit tests:

* Recent Projects UI failed ~5 times, every time the same pair of tests failing: "should open the recent projects list with only the getting started project" & "should open the recent project list and show 5 recent projects"
* JS Code Hints failed ~4 times, with _some_ consistency in which tests fail: "JavaScript Code Hinting with modules.should read properties created in parent module" & "JavaScript Code Hinting with modules.should read methods created in parent module" failed twice, "JavaScript Code Hinting Basic.should list declared variable and function names in outer scope" failed twice (once in combination with the other two, once alone), and one failure didn't match the others at all (see next bullet).
* All the failures except for one were on Mac.  The [one failure on Win](http://webauthoringbuild.corp.adobe.com:8080/job/Brackets_Test_Extensions_Matrix/767/testReport/) was "JavaScript Code Hinting with test.html file.should jump to function name with non ascii chars"

There doesn't appear to be any pattern in the build sequence (e.g. one suite failure always occurring in the build just before the other suite failed).  Each suite failed alone at least once after a preceding good build.

**Comment by peterflynn** [comment]
Looks like the Recent Projects failures started early evening on [Dec 12](http://webauthoringbuild.corp.adobe.com:8080/job/Brackets_Test_Extensions_Matrix/750/), and have been failing very often ever since.  The JS Code Hints tests have had sporadic issues going back at least as far as [Sept 26](http://webauthoringbuild.corp.adobe.com:8080/job/Brackets_Test_Extensions_Matrix/582/)

**Comment by peterflynn** [comment]
Nm, looks like actually [Dec 11](http://webauthoringbuild.corp.adobe.com:8080/job/Brackets_Test_Extensions_Matrix/label=osx/743/) (b12f8eda9cddc0571814e4e0257827e0bb31ef6d) was the first failure, and [the build earlier that morning](http://webauthoringbuild.corp.adobe.com:8080/job/Brackets_Test_Extensions_Matrix/label=osx/742/) (13f85b4e89b33bf7225f2d77c20c75e3bb5e1070) was ok.

The only thing that landed in that range was #7362.  (Though the original Dec 12 date correlates with #10163, which sounds like it could affect this test, the failures really did start earlier than that...)

**Comment by abose** [comment]
This doesn't seem to happen anymore. Closing.
