### ISSUE TITLE
[Yosemite][German]Some Elements in Japanese

### ISSUE THREAD

**Issue by Dumbaz** [adobe/brackets#10387]
I have installed the German version of Brackets, it´s up to date. Some buttons, however, are in Japanese for some reason.

![image](https://cloud.githubusercontent.com/assets/6582804/5750326/68f17eb0-9c53-11e4-9f76-2aaad3e97312.png)

![image](https://cloud.githubusercontent.com/assets/6582804/5750327/77c7f400-9c53-11e4-999a-f1004bfc69a3.png)

![image](https://cloud.githubusercontent.com/assets/6582804/5750331/8cfdad1a-9c53-11e4-91c0-8188e6597105.png)

![image](https://cloud.githubusercontent.com/assets/6582804/5750333/b0111670-9c53-11e4-8a02-f809ff73f0ed.png)

Will attempt a complete reinstall now.

Edit: Reinstalled, removed Extensions, switched Languages to English(UK), (US) and back, problem persists.

**Comment by ApfelUser** [comment]
Hi, 

this is a duplicate of #10114. 

I've had this problem too. Try changing your system language to English and restart. Then switch back to German

**Comment by Dumbaz** [comment]
Thanks, could not find that entry. Solution worked, closing.
