### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by tsteinholz** [adobe/brackets#10388]
(Edit>Autoformat>Select File/Files)

This would then Format an entire HTML, CSS, or JS file.

**Comment by ApfelUser** [comment]
@tsteinholz 

I think you are searching for this: [Beautify](https://github.com/drewhamlett/brackets-beautify)

**Comment by peterflynn** [comment]
This is already tracked here on our feature backlog -- [Code Formatting / Beautify](https://trello.com/c/BTl2J30K/428-code-formatting-beautify) -- so I'll close this to avoid duplication.  Please upvote the backlog item if you think this should be built into Brackets (as opposed to using one of the existing, popular extensions).
