### ISSUE TITLE
Javascript File Inference Problem will cause crash

### ISSUE THREAD

**Issue by sudosiyang** [adobe/brackets#10393]
It will generate a file called '.bracket.json'.And then the Brackets will crash in a minute.
When I open the program again ,  the code hints can't use. 

This question led me to not be able to write code in this project, which has seriously affected me with this software.

![111](https://cloud.githubusercontent.com/assets/5602140/5776978/4133ed50-9dc9-11e4-8364-9c0f79d6eaa6.png)

**Comment by redmunds** [comment]
@sudosiyang Brackets creates the project preference file (.brackets.json) to set preference to exc;lude the problematic file from future JS code hint processing. You can safely delete it if you think it causing a problem. For more info see: https://github.com/adobe/brackets/wiki/JavaScript-Code-Hints#javascript-file-inference-problem

As stated in that article, you can also try increasing the timeout value of `jscodehints.inferenceTimeout` preference.

Does that help?

**Comment by sudosiyang** [comment]
Thanks@redmunds
