### ISSUE TITLE
Live preview crashes after SCSS save

### ISSUE THREAD

**Issue by mmajko** [adobe/brackets#10392]
Immediately when I hit Ctrl+S, live preview crashes, because compass (I'm using grunt) is watching my project directory and compile the scss files everytime i make changes.

Brackets says: ![](http://goo.gl/KMcvEw)

What more information can I provide? And if it's not possible to make Brackets live preview work with grunt and compass, the message should be more informative, than ({0}) :)

**Comment by redmunds** [comment]
@MMajko Sorry to hear that you're having problems with Brackets. This sounds similar to #9846. Do you have the CSS Shapes Editor for Brackets extension installed? If so, does removing it fix problem?

**Comment by MMajko** [comment]
No I don't. I'm using this extensions:
- PHPLint for Brackets
- Lorem ipsum 
- Extract for Brackets 
- Extensions Rating
- Brackets Git
- Beautify
- PHP Smart hints

Do you think there could be problem with extensions? Is it possible to run Brackets temporarily without loading extensions, so I don't have to remove all of them, find out which one is problematic and install them again?

**Comment by peterflynn** [comment]
@MMajko Yes -- choose _Debug > Reload Without Extensions_ from the menu and see if the problem still occurs.  If it's gone, you can follow [these steps](https://github.com/adobe/brackets/wiki/Troubleshooting#disabling-extensions-individually) to determine which extensions is causing the problem.  Please let us know what you find out!

**Comment by MMajko** [comment]
All extensions are disabled and the problem still persists. After compass compilation, the Live Preview crashed with the "({0})" message. What now?

**Comment by MMajko** [comment]
Running latest version Release 1.1 build 1.1.0-15558 (release ea908cae5), Windows 8.1 64bit

**Comment by redmunds** [comment]
>  After compass compilation, the Live Preview crashed with the "({0})" message. What now?

Take a look at the comments in #9846 and #10274 and let us know if any of those suggestions solve it.

**Comment by akimu13** [comment]
I have the same problem here , tried every step but the problem persist

**Comment by Tigeda** [comment]
Same issue here.

**Comment by MMajko** [comment]
I'l try the steps from #9846 and #10274, gimme a sec.
