### ISSUE TITLE
Gitter instead of / in addition to Freenode

### ISSUE THREAD

**Issue by ApfelUser** [adobe/brackets#10395]
I think that [Gitter](https://gitter.im/) is a good replacement for freenode as it:

1. Integrates with GitHub's
    * Pull Requests
    * Issues
    * User Accounts (OAuth)
2. Looks way nicer
3. Supports GitHub flavored MD

This is just my personal opinion. What do you think?

**Comment by ApfelUser** [comment]
I'm soo stupid :smile: 
Sorry, a Gitter group already exists. Closing

**Comment by peterflynn** [comment]
@ApfelUser The Gitter group is basically deprecated.  We tried it out as an experiment, but IRC proved much more popular, so no one from the Brackets core teams actively monitors Gitter anymore.  At this point there's rarely anyone logged into the Gitter room, whereas our IRC room usually has 20+ in it at any given time.
