### ISSUE TITLE
Open only with a new empty document?

### ISSUE THREAD

**Issue by MojoDK** [adobe/brackets#10397]
Hi

When I open Brackets, I wan't it to open only with a new document (like Notepad++). 

I don't want it to remember last opened files and I don't want to press CMD + N - I just want it to open in a new empty document.

Is that possible?

Thansk

**Comment by peterflynn** [comment]
This idea is tracked on our feature backlog, here: [Brackets should support having no active project](https://trello.com/c/RFi7TFyj/412-brackets-should-support-having-no-active-project).  Note many useful Brackets features such as Quick Edit (inline editors) and Live Preview would not be available when you have no project open, however.

I'll close this bug to avoid duplication -- please upvote the item on our feature backlog, though.

**Comment by peterflynn** [comment]
In the meantime, it's probably possible to simulate this behavior with an extension: Brackets would still open the last-used project, but not any of the files you'd left open before (the extension would either block Brackets from reopening the previous files, or immediately close them again).  And the extension could also automatically create a new, untitled document for you.  Marking 'extension idea' in case anyone is interested in trying that.
