### ISSUE TITLE
Brackets File Tree Blank

### ISSUE THREAD

**Issue by shawnpk** [adobe/brackets#10417]
I'm running Brackets Release 1.1 build 1.1.0-15558 (release ea908cae5) on a Mac running Yosemite 10.10.2. Whenever I open a folder, the file tree is blank. I see the triangles, but no text.

**Comment by redmunds** [comment]
Does Debug > Reload Without Exensions fix it? If so this was caused by an extension, so open File > Extension Manager to update all of your installed extensions.

**Comment by shawnpk** [comment]
It was definitely an extension. Thanks for your help.

Shawn Kearney
InEpt Software	
310-864-1460
shawnpk@ineptsoftware.com
www.ineptsoftware.com
