### ISSUE TITLE
update isn't compatible with this version

### ISSUE THREAD

**Issue by jcgallaher** [adobe/brackets#10411]
I updated a theme I created and the upload went smoothly, however when I went into Bracket's extension manager to update it, the green update button was dark and when I hovered my cursor over it, it displayed the message "update isn't compatible with this version". I uninstalled/reinstalled the theme; It installed successfully and instantly switched to the new theme.

Also, I checked the theme files in the extension folder and everything was updated correctly there.

**Comment by peterflynn** [comment]
@jcgallaher Are you able to reproduce the problem again if you start by reinstalling the older version, then check for updates?

**Comment by jcgallaher** [comment]
@peterflynn Yup, I just reproduced the issue by updating the theme and uploading it to the extension registry. The green update button is dark and I get the same message. When remove it, reload brackets, and re-install it, it's successfully installed and running the updated version. The theme in question is at https://github.com/jcgallaher/cobalt-brackets-theme if you want to look at the source code.

**Comment by jcgallaher** [comment]
@nethip @peterflynn The fix showed that I had to fix my package.json files so any changes/fixes I make will be updated correctly. I've made the fix to my two theme files I submitted and they now update correctly.

**Comment by nethip** [comment]
@jcgallaher That's great. Thanks for reporting this issue. The PR https://github.com/adobe/brackets/pull/10421 should fix the problems with other extensions which will have a similar effect when Brackets version is not listed in package.json

**Comment by MarcelGerber** [comment]
Confirmed fixed.
Closing.
