### ISSUE TITLE
1.1 preview jslint error: [object Object]

### ISSUE THREAD

**Issue by jmichae3** [adobe/brackets#10419]
JSLint (1)
1	JavaScript URL.	{"windows":[{"tabs":[{"entries":[{"url":"about:blank","ID":58911958,"docshellID":5,"docIdentifier":0,"persist":true}],"lastAccessed":1416104449769,"pinned":true,"hidden":false
com.github.mrmeku.closure-linter.gjslint (1)
com.github.mrmeku.closure-linter.gjslint terminated with error: [object Object]	

this is from opening the sessionstore.js file in firefox's profile. as is typical with many .JSON files, the whitespace between punctuation syntax has been removed and the whole file is a 1-liner.
there are a number  of XML files that have that 1-liner format too.
ability to handle that would be nice, if possible.

of course, the error line number is going to be line 1. but it's unclear to me exactly what the problem is, because "JavaScript URL" doesn't mean anything to me as an error message. yeah, it probably contains a whole bunch of them. so that means what? 

Actual: error message lacks semantics. if there was a bax syntax URL, it (the problem) was not displayed. no column number information was given (would be extremely helpful in the case of 1-liners)
Expected: 
line number and column number
semantics in the error message (helpful description of the problem)
section of problem syntax should be displayed. you don't have to attempt to display the whole line.

**Comment by jmichae3** [comment]
here's my commandline run of javascriptlint as an example of some of what I should be getting (buggy error messages though, doesn't recognize JSON files):
sessionstore.js
C:\Users\Jim-Michaels\AppData\Roaming\Mozilla\Firefox\Profiles\3i4mlenf.default2\sessionstore.js(1): lint warning: meaningless block; curly braces have no impac
t
{"windows":[{"tabs":[{"entries":[{"url":"about:blank","ID":58911958,"docshellID":5,"docIdentifier":0,"persist":true}],"lastAccessed":1416104449769,"pinned":true
,"hidden":false,"attributes":{},"image":null,"index":1},{"entries":[{"url":"https://addons.mozi
^

C:\Users\Jim-Michaels\AppData\Roaming\Mozilla\Firefox\Profiles\3i4mlenf.default2\sessionstore.js(1): SyntaxError: invalid label
{"windows":[{"tabs":[{"entries":[{"url":"about:blank","ID":58911958,"docshellID":5,"docIdentifier":0,"persist":true}],"lastAccessed":1416104449769,"pinned":true
,"hidden":false,"attributes":{},"image":null,"index":1},{"entries":[{"url":"https://addons.mozi
..........^


1 error(s), 1 warning(s)

**Comment by redmunds** [comment]
@jmichae3 That's just how JSLint works. JSLint is installed with Brackets and is enabled by default and there are several ways to fix this problem:

1. If you don't want any linting, then disable all listing using: View > Lint Files on Save

2. You can also install other linters for JS and use the `linting.prefer` and `linting.usePreferredOnly` preferences to use them instead. Learn more about setting preferences [here](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences).

3. You can use `linting.enabled`preference to disable linting for selected files, folders, language, or project. Let me know if you want more info about that.

**Comment by redmunds** [comment]
> doesn't recognize JSON files

There's a JSONLint extension for that.

**Comment by peterflynn** [comment]
I think unhelpful linter errors are somewhat expected here since 'sessionstore.js' contains JSON (a very constrained declarative format) while its file extension indicates it contains JS (executable JavaScript).

If you click a linting error, it should put the cursor on the exact position -- line _and_ column -- which helps pinpoint what the error is.

In this case, the JSLint error "JavaScript URL" is warning you about a `"javascript: ..."`-style URL.  JSLint is pretty strict, and you may not agree with what it complains about.  You can disable it if you want (see Randy's note 2 above).

The "[object Object]" error you're seeing means the "Closure Linter" extension you have installed is crashing.  It's not the type of error you'd expect to see when things are working properly.  Please file a bug with the extension's author about that problem.

**Comment by peterflynn** [comment]
Closing since I believe that addresses all the issues, and it doesn't look like there's anything wrong in core Brackets that we need to fix.
