### ISSUE TITLE
Add support for .jslintrc

### ISSUE THREAD

**Issue by awebdeveloper** [adobe/brackets#10420]
Could you guys add support for .jslintrc

**Comment by busykai** [comment]
Brackets does not ship JSHint by default. JSHint is [an extension](https://github.com/cfjedimaster/brackets-jshint) and it does support `.jshintrc`. To install it, go to `File -> Extensions Manager` and search for JSHint.

**Comment by awebdeveloper** [comment]
Sorry i meant .jslintrc

**Comment by busykai** [comment]
JSLint options/configuration is supported via preferences. There's a [`jslint.options`](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#list-of-supported-preferences) preference which you could specify either per project (placing it in `.brackets.json` in the root of the project) or globally (global preferences file: `Debug -> Open Preferences File`).

**Comment by awebdeveloper** [comment]
Sounds Great

**Comment by awebdeveloper** [comment]
I added following in the .brackets.json file in the root of the opened folder(hope is same as project) it didn't work 

"jslint.options": {
    "globalstrict"  : true,     // true: Allow global "use strict" (also enables 'strict')
    "browser"       : true,     // Web Browser (window, document, etc)
    "predef"        : [
        'angular',
        'smartMerge'
    ]
}

**Comment by sprintr** [comment]
@awebdeveloper JSON does not support comments, try removing those comments.

**Comment by awebdeveloper** [comment]
As suggested i removed comments and a few lines and tried this. But this thing also doesn't work  Finally i tried adding this globally and it works globally in brackets.json

`"jslint.options": {   
    "predef"        : [
        "smartMerge"
    ]
}`

**Comment by sprintr** [comment]
Try wrapping your preferences.

    {
        "jslint.options": {
            "predef" : [ "smartMerge" ]
        }
    }

**Comment by awebdeveloper** [comment]
facepalm

**Comment by awebdeveloper** [comment]
also do you know how to allow global use strict. I tried both `"globalstrict" : true` and `"strict" : false`

**Comment by sprintr** [comment]
`"use strict";` is a Part of JavaScript, there is not way to set it via `jslint.options` or via preferences.

**Comment by awebdeveloper** [comment]
i mean the error thrown for use strict i wish to disable it

**Comment by sprintr** [comment]
```js
{
    "jslint.options": {
        "sloppy": true
    }
}
```

@awebdeveloper
