### ISSUE TITLE
Live Preview not working with Portable Chrome

### ISSUE THREAD

**Issue by chintan9** [adobe/brackets#10428]
Live Preview not working with Portable Chrome

![image](https://cloud.githubusercontent.com/assets/1642564/5846804/ea031c20-a194-11e4-9b21-c4241658fee9.png)

**Comment by redmunds** [comment]
I've never heard of Portable Chrome. Do you have a link to project?

Take a look at the [Chrome Issues section of Troubleshooting page](https://github.com/adobe/brackets/wiki/Troubleshooting#livedev-chrome) to see to Registry key that Brackets uses to find Chrome. You should be able to manually update that key.

**Comment by chintan9** [comment]
http://portableapps.com/apps/internet/google_chrome_portable

very useful for when you can not install anything .

![image](https://cloud.githubusercontent.com/assets/1642564/5847090/77202524-a197-11e4-9485-e8de9d811cff.png)

**Comment by peterflynn** [comment]
I believe this is already tracked here: [Live Development w/ Custom Chrome Install (e.g. Canary, portable Chrome, Dartium)](https://trello.com/c/MYaUdJOR/508-live-development-w-custom-chrome-install-e-g-canary-portable-chrome-dartium).  Please upvote that item to raise its priority.

The workaround suggested by @redmunds above is a good idea though -- please let us know if that works!

**Comment by chintan9** [comment]
THANKS
