### ISSUE TITLE
Improve line number column

### ISSUE THREAD

**Issue by pancheps** [adobe/brackets#10429]
The line number column could be improved with this two features (useful for me):

1. Select the whole line by clicking on the line number. Also select multiple lines dragging the mouse cursor up or down over the line numbers.
2. Create 'breakpoints' by clicking on the right side of the line number, or perhaps right-clicking the line number. This helps me to follow up some code fragments when I have to look somewhere else before continuing editing said fragment.

Hopefully these ideas can be taken into account. Thanks.

**Comment by peterflynn** [comment]
@pancheps Thanks for the suggestions.  These ideas are tracked on our feature backlog, here:

1. [Click/drag in gutter selects line(s), double-click selects block](https://trello.com/c/rQOTX8JH/1022-click-drag-in-gutter-selects-line-s-double-click-selects-block)
2. [JavaScript Breakpoint Debugging](https://trello.com/c/4PuQjpGR/305-javascript-breakpoint-debugging)

Please upvote those items to help raise their priority.  I'll close this issue to avoid duplication.

**Comment by pancheps** [comment]
Thanks a lot, couldn’t find them. Anyway, already voted for both.

 

De: Peter Flynn [mailto:notifications@github.com] 
Enviado el: jueves, 22 de enero de 2015 01:48 a.m.
Para: adobe/brackets
CC: pancheps
Asunto: Re: [brackets] Improve line number column (#10429)

 

@pancheps <https://github.com/pancheps>  Thanks for the suggestions. These ideas are tracked on our feature backlog, here:

1.	Click/drag in gutter selects line(s), double-click selects block <https://trello.com/c/rQOTX8JH/1022-click-drag-in-gutter-selects-line-s-double-click-selects-block> 
2.	JavaScript Breakpoint Debugging <https://trello.com/c/4PuQjpGR/305-javascript-breakpoint-debugging> 

Please upvote those items to help raise their priority. I'll close this issue to avoid duplication.
