### ISSUE TITLE
Might be a nice feature: ability to open multiple windows.

### ISSUE THREAD

**Issue by faridstark** [adobe/brackets#10423]
I have multiple displays on my desk and sometimes would love to use Brackets on 2 of them. However, right now there's no way to open a 2nd window.

**Comment by ApfelUser** [comment]
Actually there is:

```
Debug > New Brackets Window
```

**Comment by MiguelCastillo** [comment]
@ApfelUser It works, but it can be unreliable due to both instance sharing resources like preferences files...  With that said, I use it when I need it.  There is already a trello card for this one :)

**Comment by peterflynn** [comment]
Closing -- please upvote the feature on our backlog: [Multiple separate windows (official "New Window" command)](https://trello.com/c/YM0YySxX/679-multiple-separate-windows-official-new-window-command).

As Miguel pointed out, the Debug menu command is intended for testing only, and has serious bugs (including losing preferences, conflicts with unsaved changes, and keyboard shortcuts not working).  It's better to use split view within a single window for now.
