### ISSUE TITLE
freeze on windows 8 x64

### ISSUE THREAD

**Issue by altaihero** [adobe/brackets#10426]
i am using windows 8 x64. CPU i7 4770k memory 16GB
when i work on 1000 lines codes brackets is freeze 3-5 seconds. 

How to handle this freeze action?

**Comment by redmunds** [comment]
@altaihero Can you give us more details about when the lag occurs?

Is it when you first click in the file tree to open the file? This triggers the JavaScript Code Hint engine to process all of the JS files in that *folder*. If there's a lot of JS in that folder, there can be a noticeable lag.

Is it every time you open that same file? Try double-clicking to put file in working set so it stays in memory.

Is the file minified JS? Brackets is slower to process minified files, but there is a fix in master branch (coming in the next release) that may help.

Something else? Maybe a combination of these? Please provide more details.

**Comment by peterflynn** [comment]
Also, try with _Debug > Reload Without Extensions_ to make sure this isn't caused by an extension you have installed

**Comment by altaihero** [comment]
Thank all reply. i try without extensions No freeze .
Nice working on big file without extensions

**Comment by peterflynn** [comment]
@altaihero You can follow the steps at https://github.com/adobe/brackets/wiki/Troubleshooting#disabling-extensions-individually to figure out which extension is causing the problem.  Please file a bug with the extension's author if you're able to.

**Comment by altaihero** [comment]
thank you reply @peterflynn but i am using sublime this time.
maybe i will check this when i want use agian
