### ISSUE TITLE
Shift + Page Down sometimes scrolls too far, doesn't show selection

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#1042]
1. Open a tall file (I used InlineEditorProviders-test.js, at a window height that shows about 73 1/2 lines)
2. Scroll down a screenful or two and put the cursor down there
3. Ctrl+Home -- notice that the scrollbar doesn't _quite_ go all the way to the top (bug #1024).  I'm not sure if this state is required to repro or not.
4. Shift+Page Down

Result:
View scrolls down, but selection highlight is not visible.  If you scroll up a line you'll see that it ends on the line just off the top of the viewport.  (Technically the cursor / selection endpoint is in view, at char 0 of the next line... but there's no selection highlight painted there).

Expected:
View scrolls down one line less, so that part of selection highlight is visible.

**Comment by le717** [comment]
@peterflynn This issue can be closed. It was resolved back in 2013. ;)

**Comment by peterflynn** [comment]
Thanks for the reminder!

If you're really careful about how you follow the modified repro steps in [my comment above](https://github.com/adobe/brackets/issues/1042#issuecomment-6922158), you can still repro an issue almost as bad as the original bug:

![selection off edge](https://cloud.githubusercontent.com/assets/1197510/6460381/a8e66db0-c14b-11e4-9847-01c744ef6fc6.png)

But since the selection isn't 100% invisible and it's now a lot harder to hit (you need an especially unlucky scroll pos instead of just hitting Ctrl-Home), I think it's fair to close it at this point.
