### ISSUE TITLE
Error submitting Brackets CLA

### ISSUE THREAD

**Issue by jeff-foster** [adobe/brackets#10430]
Trying to sign the BRACKETS CONTRIBUTOR LICENSE AND DISTRIBUTION AGREEMENT ("AGREEMENT") at http://dev.brackets.io/brackets-contributor-license-agreement.html and getting a couple of "No space left on device" messages.

Would love to start hacking but can't sign up.
![dev_brackets_io_submit-cla_cfm](https://cloud.githubusercontent.com/assets/430288/5850871/482cb43a-a1ba-11e4-8513-c7721e80d8ff.png)

**Comment by EJanuszewski** [comment]
This happened recently, is there no permanent solution that can be put in? Or at least prevent it happening as this often
#10363

**Comment by peterflynn** [comment]
Yes, we should fix this in a way that lasts more than 9 days :-/

**Comment by ingorichter** [comment]
I have cleaned up some disk space. There was a huge apache log file. I have removed this log file and disabled the logging for redirects.

**Comment by nethip** [comment]
Awesome! Thanks @ingorichter for fixing this. Closing..

**Comment by jeff-foster** [comment]
Thanks!
