### ISSUE TITLE
Right click and copy from contextmenu

### ISSUE THREAD

**Issue by sebass** [adobe/brackets#10448]
Such a simple and very often missed feature.

**Comment by peterflynn** [comment]
Please upvote this item on our feature backlog: [Clipboard Cut/Copy/Paste in Editor Context Menu](https://trello.com/c/ZriVEu50/935-clipboard-cut-copy-paste-in-editor-context-menu).

In the meantime, you can use the 'Right Click Extended' extension to get this functionality.
