### ISSUE TITLE
Brackets Extract - Doubt

### ISSUE THREAD

**Issue by willianschenkel** [adobe/brackets#10447]
Brackets Extract only work with PSD? 
Someday this will works with PNG?

Thanks!

**Comment by peterflynn** [comment]
@willianschenkel How do you picture that working?  Unlike PSDs, PNGs are not composed of separate layers that could be extracted individually, and there is no embedded information about fonts, gradients, shapes, etc. that could be extracted into CSS...

**Comment by sprintr** [comment]
@willianschenkel In case you just want to extract colors out of a PNG image, you can use my (color palette extension)[https://github.com/sprintr/brackets-color-palette]

**Comment by whoisbenjamin** [comment]
Any chance Sketch support is coming??
