### ISSUE TITLE
[regex] Allow \A and \Z when finding by regexp

### ISSUE THREAD

**Issue by mitchhentges** [adobe/brackets#10454]
`\A` should match the beginning of the file, while `\Z` should match the end.

**Comment by le717** [comment]
Regex search uses the [JavaScript regex syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Special_characters_meaning_in_regular_expressions), and JS does not support `\A` and `\Z` as valid special characters.
