### ISSUE TITLE
Split View Acting Funny

### ISSUE THREAD

**Issue by tylertrotter** [adobe/brackets#10450]
When I open 2 files from Windows Explorer in Brackets, then turn on split view, the active file is in the left pane and the right pane is empty. If I select the right pane and then select the other file, it shows up in the left pane and the right pane stays empty. 

Everything behaves as expected if I select two files from Brackets' file manager menu. It's only when I open up two files "the old fashioned way."

I'm using Windows 8, Brackets 1.1

See more at this conversation: https://forums.adobe.com/message/7122538#7122538

**Comment by redmunds** [comment]
@tylertrotter 

> If I select the right pane and then select the other file, ...

By "select the other file", do you mean "select the file that is *not* being viewed in the Left working set list" ? If so, this is working as designed. If not please provide more details.

**Comment by tylertrotter** [comment]
That is what I meant. It wasn't clear to me it would work that way. Not sure of the rationale but feel free to close this issue. 

—

**Comment by redmunds** [comment]
@tylertrotter Thank for following up. As you saw in the forum thread, you can drag a file from one working set to the other. Closing.
