### ISSUE TITLE
Live preview error: An error occured when launching the browser. (error unknown). For more information, see Troubleshooting Live Preview connection errors.

### ISSUE THREAD

**Issue by TobyLaroned** [adobe/brackets#10462]
Brackets and chrome up to date
I am using a windows 7 x64 machine

I checked the registry like on #7372 and it seems fine.

Here is what the console said when i tried to live preview:  

GET http://127.0.0.1:9222/json net::ERR_CONNECTION_REFUSED
/LiveDevelopment/Inspector/Inspector.js:264 

Tried it on my windows 7 x64 laptop and it's working fine

What should i do? :c

**Comment by redmunds** [comment]
@TobyLaroned Take a look at what's different between those 2 machines. The [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting) will give you ideas about most of the known issues.

**Comment by nethip** [comment]
@TobyLaroned Have you tried the steps in the troubleshooting guide to see if the issue is resolved?

**Comment by hirenvanza** [comment]
just u have to open full folder in bracket and select File> live preview option
so u ll get ip address in browser followed by your file
something like this "http://124.0.0.1:51234/index.html"

**Comment by abose** [comment]
Closing inactive thread.

**Comment by diman82** [comment]
Facing the same issue, followed the troubleshooting guide but no luck.
Can you please advise steps for debugging the problem?
