### ISSUE TITLE
Project Folder Text Hidden

### ISSUE THREAD

**Issue by derrickityo** [adobe/brackets#10460]
Ever since I updated to the latest version, I can't see the project file list or file names.

![capture](https://cloud.githubusercontent.com/assets/3065391/5889360/c0068b8c-a419-11e4-82e4-648840a7af86.JPG)

**Comment by redmunds** [comment]
@derrickityo There is an extension that was causing this, but I can't remember which one. It has since been updated, so try applying any pending extensions updates and let us know if it still happens.

**Comment by le717** [comment]
@redmunds @derrickityo The two offending extensions which have indeed been fixed were [Brackets-Icons](https://github.com/ivogabe/Brackets-Icons) and [Brackets-File-Icons](https://github.com/drewbkoch/Brackets-File-Icons).

**Comment by derrickityo** [comment]
Updating the extensions worked. Cheers guys.
