### ISSUE TITLE
Brackets can't run on Debian 8 (Jessie)

### ISSUE THREAD

**Issue by Nexc** [adobe/brackets#10465]
$ sudo dpkg -i Brackets.Release.1.1.64-bit.deb
Selecting previously unselected package brackets.
(Reading database ... 110225 files and directories currently installed.)
Preparing to unpack Brackets.Release.1.1.64-bit.deb ...
Unpacking brackets (1.1.0-15558) ...
dpkg: dependency problems prevent configuration of brackets:
 brackets depends on libgcrypt11 (>= 1.4.5); however:
  Package libgcrypt11 is not installed.
dpkg: error processing package brackets (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for menu (2.1.47) ...
Errors were encountered while processing:
 brackets

$ brackets
/usr/bin/brackets: error while loading shared libraries: libgcrypt.so.11: cannot open shared object file: No such file or directory 

$ sudo apt-get install -y libgcrypt11
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libgcrypt11 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'libgcrypt11' has no installation candidate

(also, Atom also misses libgcrypt11 too, but runs anyway.)

**Comment by prksingh** [comment]
This may be a duplicate of issue#10255. Check out this thread:
https://github.com/adobe/brackets/issues/10255

The build posted on the thread may fix your problems

**Comment by peterflynn** [comment]
I agree - closing as duplicate

**Comment by Damey37** [comment]
Hi guys ! It You must install the package "libgcrypt20" and "libgcrypt20-dev" first. Then, recompile the package .deb and changed in the file "control" the dependence "libgcrypt11" to "libgcrypt20". Finally, rebuilt a package .deb of folder "Brackets" . And it work !

**Comment by Gontxal0** [comment]
Nope, it doesn't work:
/usr/bin/brackets: error while loading shared libraries: libgcrypt.so.11: cannot open shared object file: No such file or directory

And after a symbolic link to libgcrypt.so.20 I get:
/usr/bin/brackets: /lib/x86_64-linux-gnu/libgcrypt.so.11: version `GCRYPT_1.2' not found (required by /opt/brackets/lib/libcef.so)

So don't lie to the people.

**Comment by mackenza** [comment]
"so don't lie to the people" is a pretty rude thing to say to people who are trying to help you get a free, open source project running.

**Comment by abose** [comment]
![image](https://cloud.githubusercontent.com/assets/5336369/8401451/28736fda-1e4c-11e5-9b55-8597be775b5c.png)

**Comment by RaulSalinasVal** [comment]
google searching I found a possible solution faster.

installing the library contained in a .deb package

https://launchpad.net/ubuntu/+source/libgcrypt11

and i'm installed
I have installed on my debian brackets jessie 8.1


ref -> http://www.webupd8.org/2015/04/fix-missing-libgcrypt11-causing-spotify.html

**Comment by ProfitHunter** [comment]
download install libgcrypt11.xx.deb using Debian 7 version deb package
url:https://packages.debian.org/search?keywords=libgcrypt11
1.5.0-5+deb7u3 
i tested,it's working.

**Comment by roniedson** [comment]
hello, Download Package: 
Package: libgcrypt11 1.4.5-2+squeeze1 or  
libgcrypt11_1.5.0-5+deb7u3
# dpkg -i Brackets.1.4.Extract.32-bit.deb 
(Lendo banco de dados ... 176189 ficheiros e directórios actualmente instalados.)
A preparar para desempacotar Brackets.1.4.Extract.32-bit.deb ...
A descompactar brackets (1.4.0-16380) sobre (1.4.0-16380) ...
Configurando brackets (1.4.0-16380) ...
A processar 'triggers' para hicolor-icon-theme (0.13-1) ...

OK

**Comment by roniedson** [comment]
Olá, Download Pacote: 
Pacote: libgcrypt11 1.4.5-2 + squeeze1 ou libgcrypt11_1.5.0-5 + deb7u3
(Lendo Banco de Dados ... 176189 ficheiros e directórios ACTUALMENTE instalados.) 
A preparar parágrafo desempacotar Brackets.1.4.Extract.32-bit.deb ... 
A suportes descompactar (1.4.0-16380) Sobre (1.4.0- 16380) ... 
suportes Configurando (1.4.0-16380) ... 
parágrafo hicolor-icon-theme 'gatilhos' A Processar (0,13-1) ...

**Comment by dvp1964** [comment]
THIS is why Linux sucks.  Well, not Linux, but the devlopers and the documenters. SUCK SUCK SUCK.  Do you really think all this bullshit is acceptable? "no install this first, then do this unless you have that, then do this, and dont forget to run this first"..... Im so tired of this shit.  i've been running Linux suince 1994 - Im no newbie but I know bullshit when I see it.When its this much work to just install something, then something is very, very wrong. Until its fixed, this shit shouldn't be out for public use.  There should be a deb package ready to download, run, install, and use. Come on people, this is UNACCEPTABLE.

**Comment by MiguelCastillo** [comment]
@dvp1964  **That's completely unnecessary and unacceptable way to address any community, including the Brackets community**.  I don't quite understand the frustration because I am not a Debian user...  However, it would be much more helpful/meaningful if you - or anyone else - could help us fix the issues we have around that environment.  Do you have any ideas how we can achieve that?  I am sure the community would *love* you for that.

**Comment by mackenza** [comment]
@MiguelCastillo I was going to say the same thing. If Brackets doesn't have a code of conduct, it certainly needs one as that kind of response is so not cool.

For those still complaining, I have not seen anyone say whether they tried the solution mentioned above, found at: http://www.webupd8.org/2015/04/fix-missing-libgcrypt11-causing-spotify.html

Instead of ranting and swearing, perhaps you can say "I tried the proposed solution and it does/does not work for me"?

**Comment by dvp1964** [comment]
Too many coders just want their name associated with a project.  To help at interview and just to have bragging rights. why is it that you can get a windows or mac file to install and it works?  Trying to get Kompozer HTML editor to work on Linus is a doom pain as well. Not on windows or mac. But then someone as a fork called BlueGriffon which is almost exactly like Kompozer and it works. In the linux world its for debian, slackware, or red hat (or any of the 1000's that copy them). If a group or individual were serious about getting their software out there, then they would be damn sure it would work on each of those, quick and easy. And if certain libraries/files are needed...fine, just say so and have links to them. All with clear, step-by-step instructions. and in less than 10 minutes (and that's generous) the software should be working on their distribution.   Others may be more patient than me, for sure, but by the number of posts regarding problems of installing or running it tells you something right there.

**Comment by dvp1964** [comment]
Too many coders just want their name associated with a project. To help at interview and just to have bragging rights. why is it that you can get a windows or mac file to install and it "just works"? Example: Trying to get Kompozer HTML editor to work on Linux is a doomed pain as well. Not on windows or mac! But then someone has a fork called BlueGriffon which is almost exactly like Kompozer BUT IT WORKS/INSTALLS PROPERLY. Probably because the Kompozer people couldn't get it right or didn't care. Great, now we have 2 versions of the same thing and only one really works.  In the linux world all programs are for debian, slackware, or red hat (or any of the 1000's that copy them). If a group or individual were serious about getting their software out there, then they would be damn sure it would work on each of those, quick and easy, with clear step-by-step instructions, leaving nothing out. And if certain libraries/files are needed...fine, just say so and have links to them. All with clear, step-by-step instructions. and in less than 10 minutes (and that's generous) the software should be working on their distribution. Others may be more patient than me, for sure, but by the number of posts regarding problems of installing or running it tells you something right there.

**Comment by roniedson** [comment]
You use the operating sistem you want, Linux is amazing!

**Comment by mackenza** [comment]
@dvp1964 is there somewhere in your post that indicates you have tried the posted workaround? If not, can we keep the discussion focused on *this* issue (this is the Brackets repo btw)

**Comment by mihawk90** [comment]
> https://github.com/adobe/brackets/issues/10465#issuecomment-124963611

Confirmed working for me
Kubuntu 15.04, pretty fresh install

Would be nice if Brackets could be repackaged for the new lib version or the original in the package :)

**Comment by jws121295** [comment]
Found a two line solution to run in a console to get installation working:

$ sudo echo 'deb http://ftp.us.debian.org/debian/ wheezy main contrib non-free'
$ sudo apt-get update && sudo apt-get install libgcrypt11

Seems reasonable enough to me. Don't know why there's so much fuss here.

**Comment by AnonymousJoe** [comment]
@jws121295 

brackets : Depends: libgcrypt11 (>= 1.4.5) but it is not installable

**Comment by Joepete** [comment]
The solution that worked for me (Brackets.1.5.Extract.64-bit.deb installed on Ubuntu 15.10) was precisely what has been referenced numerous times: Download a previous .deb of the libgrypt11:
Example from Ubuntu 14.04
64 bit: https://launchpad.net/ubuntu/+archive/primary/+files/libgcrypt11_1.5.3-2ubuntu4.2_amd64.deb
32 bit: https://launchpad.net/ubuntu/+archive/primary/+files/libgcrypt11_1.5.3-2ubuntu4.2_i386.deb

It strikes me that dvp1964 must have been having a bad day when posting. Clearly he/she wrote with a broad and incorrect brush. (Is your gripe Linux or the ports of other open-source projects that are written for Linux? A bad or immature project is just that - regardless of the OS is it is written for). But a "code of conduct" etc.? We all just need thicker skins and thinner skulls. Like the development, the community will maintain itself one way or the other.

**Comment by drupalalsur** [comment]
Joepete thanks, work for me.

**Comment by dhaliti** [comment]
What I did is, I added "deb http://ftp.us.debian.org/debian/ wheezy main contrib non-free" to the apt-get source list. Update the list and install libgcrypt11. That worked for me.

sudo nano /etc/apt/sources.list
#add this ---> deb http://ftp.us.debian.org/debian/ wheezy main contrib non-free
sudo apt-get update && sudo apt-get install libgcrypt11*

**Comment by isosatl** [comment]
The **dhaliti** solution worked for me too.
1.) Added 'deb http://ftp.us.debian.org/debian/ wheezy main contrib non-free' to sources.list
2.) sudo apt-get update
3.) sudo apt-get install libgcrypt11
4.) sudo dpkg -i Brackets.1.6.Extract.64-bit.deb
and that's it.

**Comment by backnight** [comment]
I don´t understand how it can be an acceptable solution to add Debian Wheezy repositories to a Debian Jessie installation.......

This can fuck up an entire system.

**Comment by isosatl** [comment]
It might not be an acceptable solution, but it's a common way on Debian to use backport to resolve things like that.
I tried a lot of things before accepting this solution.

**Comment by jws121295** [comment]
@AnonymousJoe whoops I accidentally left out part of the command (please forgive my composition on a phone)

The two line fix should be:
$ sudo echo 'deb http://ftp.us.debian.org/debian/ wheezy main contrib non-free' > /etc/apt/sources.list
$ sudo apt-get update && sudo apt-get install libgcrypt11

**Comment by medBouzid** [comment]
## To install brackets on debian jessie 8.X 


**1- install libgcrypt11**

`sudo wget http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/libg/libgcrypt11/libgcrypt11_1.5.3-5_amd64.deb`

Then 

`sudo dpkg -i libgcrypt11_1.5.4-3_amd64.deb`

**2- install gdebi**

`sudo apt-get install gdebi
`

**3-  go to http://brackets.io/ and download brackets from there**


**4- install brackets**

`sudo gdebi Brackets.Release.1.6.64-bit.deb`

**_Congratulation your brackets is now installed :)_**

**Comment by nessross77** [comment]
@[Joepete] your solution did it for me

**Comment by antmaze** [comment]
@medBouzid
a correction is needed:
sudo dpkg -i libgcrypt11_**1.5.3-5_**amd64.deb

and Gdebi is not needed as it can be substitued by dpkg:
dpkg -i Brackets.1.6.Extract.64-bit.deb

It works form me :) Thanks

**Comment by medBouzid** [comment]
@antmaze Thank you for the correction. Awesome that it works for you! I've switched to Atom since then and I am happy with it :)

**Comment by SheNNawy2015** [comment]
http://www.webupd8.org/2015/04/fix-missing-libgcrypt11-causing-spotify.html

**Comment by Orses** [comment]
@Joepete your solution did it for me as well.
Thanks

**Comment by humanfactors** [comment]
Same issue on Debian Testing (Stretch). Honestly, some of the replies here are saddening for this community. Whilst I respect that developers should actually track package dependencies in distributions of claimed support; the replies here are not in the spirit of open source. 

The solution is much simpler than others here have posted and do not require any changes to your sources.

1. Download the libgcrypt11 .deb for your system https://packages.debian.org/wheezy/libgcrypt11 (I use AMD64).
2. `cd ~/DownloadLocation` and then `sudo dpkg -i libgcrypt11_1.5.0-5+deb7u4_amd64`
3. Install brackets deb file
4. Success, enjoy your coding.

Anyone who claims to have used Linux for 10+ years but doesn't know how to do very simple backporting probably should go back to using Windows. Thanks again Brackets team for your awesome work :) :+1:

**Comment by accjiyun** [comment]
sudo apt-add-repository ppa:webupd8team/brackets
sudo apt-get update
sudo apt-get install brackets

**Comment by 2015hzz** [comment]
@Joepete ,thinks,work for me.

**Comment by SheNNawy2015** [comment]
sudo apt-get install -f 
sudo dpkg -i Brackets.Release.1.1.64-bit.deb

**Comment by zaggino** [comment]
https://nathanjplummer.github.io/Brackets/

**Comment by aliaksandr-adzinets** [comment]
I agree that installing software on Linux sucks. 

I've added ppa:webupd8team/brackets and now getting this on apt-get update:

W: Failed to fetch http://ppa.launchpad.net/webupd8team/brackets/ubuntu/dists/jessie/main/binary-i386/Packages  404  Not Found

WHAT? Ok, that's just another fucking error as usual. There are only 10% of software that I can install as discribed in their manuals. You have a whole thread with different ways, some work for one people, some work for other.

And never (well, in 95% cases) have problems in Windows.

**Comment by aliaksandr-adzinets** [comment]
Ah, and before that I had to install another crap because apt-add-repository was not found... software-properties-common... Without stackoverflow, I'd spend all my life to install a single fucking HTML/CSS IDE. If you want to use Linux you should spend 5 years to understand it. If you want to use Win or Mac - just turn it on.

**Comment by aliaksandr-adzinets** [comment]
Managed to install using this guide (it's in Spanish)
http://enavas.blogspot.com.by/2016/10/instalar-brackets-en-debian-jessie.html

**Comment by Joepete** [comment]
@aliaksandr-adzinets, glad you managed to get it to work. I would caution against leaping to conclusions based on the ease (or difficulty) of installing software on an OS. Arguably, installing software should take a little thought and occasional work. The issue confronted here is fairly simple. Brackets depends on an older library. Yes, there are a number of ways of installing that library so that the install completes. If you were to compare the common vulnerabilities list for any flavor of Windows, it dwarfs most other OS. Maybe it's actually a very bad that installing on Windows tends to be point and click.

**Comment by aliaksandr-adzinets** [comment]
@Joepete, thanks for you patient answer on my lashing, I'll take it into account.

**Comment by vrmartins** [comment]
> Hi guys ! It You must install the package "libgcrypt20" and "libgcrypt20-dev" first. Then, recompile the package .deb and changed in the file "control" the dependence "libgcrypt11" to "libgcrypt20". Finally, rebuilt a package .deb of folder "Brackets" . And it work !

@Damey37 That worked for me! Thanks!!!

1. Extract brackets.deb
2. Edit /DEBIAN/control, to replace libgcrypt11 (> = 1.4.5) with libgcrypt20
3. Generate the package with dpkg-deb -b /debian /destiny_folder
4. Execute new Bracket.deb

**Comment by mfrasca** [comment]
and for the lazy ones, who prefer copy&paste:

```bash
ar x Brackets.Release.1.10.64-bit.deb control.tar.gz
gzip -df ./control.tar.gz
tar xf control.tar ./control
sed -i 's/libgcrypt11[^,]*,/libgcrypt20,/' ./control
tar uf ./control.tar.gz ./control
gzip -f ./control.tar
ar x Brackets.Release.1.10.64-bit.deb control.tar.gz
```

indeed, a small change.
