### ISSUE TITLE
"File type select" should be enabled in new files

### ISSUE THREAD

**Issue by MojoDK** [adobe/brackets#10467]
If I create a new document, I want to paste in some json and then select json from the "Click to change file type" select box at the lower right and finally run the beautifier plugin.

But I can't .... In new documents the "File type select" is disabled :(

I see no reason to disable this - I would like to be able to chose file type eventhough it's a new document.

:)

Thanks

**Comment by RaymondLim** [comment]
@MojoDK You need to save the new document first with the json extension. "File type list" in the status bar is for viewing an existing file as a different file type. e.g. if you open a file with .php file extension and you can select `HTML` from that list to view it as html instead of php.

**Comment by Pot-Nut** [comment]
Could you enable file type list in the status bar, and if a file has not yet been saved it prompts the user to save it as the selected file type, then:
- If the user saves then switch to that file type.
- If the user does not save then revert to no selected file type.

**Comment by peterflynn** [comment]
This is tracked on our feature backlog: [Switch language / type of Untitled documents (fix JS Code Hints problems with untitled documents)](https://trello.com/c/CNXuU4TY/1369-switch-language-type-of-untitled-documents-fix-js-code-hints-problems-with-untitled-documents).  As the title suggests, some Brackets features -- including JS Code Hints -- run into trouble when exposed to untitled documents.  So we'd like to fix this, but there may be significant effort involved.  Please upvote the backlog item to help raise its priority.

@Pot-Nut Personally I'm not sure that change would be worth the trouble. It still requires users to save the file, so the workflow remains just as clunky.  It seems mainly like a usability workaround for users who don't realize that saving the file will let you specify a file type/extension, and I'm not sure if that confusion is very common.

**Comment by nethip** [comment]
Please up vote the trello card.

**Comment by rvarbanov** [comment]
Does anyone know of an extension that does that?

**Comment by paulgc34** [comment]
It would be nice to be able to quickly edit some code with the option of selecting the file type to enable the proper color coding. I understand you can do this by saving the file but when I'm quickly editing some code snippets I do not need the file saved to my computer. For now I use sublime for quickly editing snippets for this purpose alone. I would much rather just use Brackets for all my editing purposes.

**Comment by cloverink** [comment]
any update ?

**Comment by TetrisSmalls** [comment]
I am also interested if this is still in the works.

**Comment by ashish450001** [comment]
Any update on this one ?????
