### ISSUE TITLE
Folder names missing in latest dev build

### ISSUE THREAD

**Issue by mat-mcloughlin** [adobe/brackets#10461]
![image](https://cloud.githubusercontent.com/assets/2362687/5891340/66d9d2ee-a487-11e4-92e6-2fef52b4da6e.png)

On the latest dev build with no extensions installed. Some of the folder names don't appear. Not sure why

**Comment by redmunds** [comment]
@mat-mcloughlin There are some icon extensions that were causing that. They have been updated to fix the problem, so look in the Extension Manager and apply any updates.

**Comment by mat-mcloughlin** [comment]
yeah I saw that thread. However I no extensions installed

**Comment by RaymondLim** [comment]
Are you running release 1.1 installed build or using your own compiled build? If you compile yourself, then you need to run `grunt` again to get cef 2171.

**Comment by mat-mcloughlin** [comment]
running from master using the `setupforhacking` script

**Comment by RaymondLim** [comment]
So make sure you have changes from this pr #10002 that fixed the issue.

**Comment by mat-mcloughlin** [comment]
:S sorted. Thanks
