### ISSUE TITLE
Feature request: Ask for password to change restricted files (OSX)

### ISSUE THREAD

**Issue by bax-** [adobe/brackets#10479]
Hey!

This applies to OSX.
If I want to safe a file that I would need admin rights for, Brackets at the moment just wouldn't allow it.
Other editors ask for the admin password and then change the file.

Thanks!

**Comment by peterflynn** [comment]
That suggestion is on our feature backlog: [Allow user to force file save with elevated permissions](https://trello.com/c/nbxEyz1n/966-allow-user-to-force-file-save-with-elevated-permissions).  Please upvote it there to help raise its priority -- I'll close this to avoid duplication.
