### ISSUE TITLE
feature request: Modelica syntax highlight

### ISSUE THREAD

**Issue by thorade** [adobe/brackets#10472]
I am programming in [Modelica](https://modelica.org/) and would like to add syntax highlight for it. 
Modelica is already listed on CodeMirror: 
http://codemirror.net/mode/modelica/index.html
so adding syntax highlight should be not too hard, BUT: the file extension for Modelica source code files is *.mo, the same as [gnu gettext](http://en.wikipedia.org/wiki/Gettext) binary files, so marking all mo files as Modelica might break some things for some people (see https://github.com/github/linguist/issues/119 )

Same thing might happen for other extensions, e.g. *.n files might be Nemerle code (text) or Neko applications (binary).

How should this be treated? Does this case have to be treated somehow?
On https://github.com/adobe/brackets/wiki/Language-Support I could not find how to treat this case (or did I just miss it?).

**Comment by redmunds** [comment]
@thorade The "mo" file extension is not yet defined in Brackets so Modelica will be easy to add to Brackets.

I don't think Modelica support will be added to BraCkets core code any time soon, so you should write an extension to do this. The [Defining a New Language section of Language Support wiki page](https://github.com/adobe/brackets/wiki/Language-Support#defining-a-new-language) explains how to do it.

Comt to the [brackets-dev forum](https://groups.google.com/forum/?fromgroups=#!forum/brackets-dev) or #brackets chat room on IRC if you have any questions.

Closing as an extension idea.
