### ISSUE TITLE
Feature Request: JSX syntax highlighting

### ISSUE THREAD

**Issue by aldendaniels** [adobe/brackets#10485]
Would be great to have JSX (react) syntax highlighting natively in brackets. This functionality was previously provided by [this plugin](https://github.com/automenta/brackets-jsx) but the plugin is no longer being supported.

**Comment by redmunds** [comment]
You can always fork the repo and submit a new version to the BRackets Extension Registry.

**Comment by aldendaniels** [comment]
Yes indeed - I may do that if I find the time.

Feel free to close the issue if this is unlikely to be prioritized. I mainly opened this in case enough other users would benefit from JSX support to justify adding JSX to the core language set.

**Comment by redmunds** [comment]
Marking as an Extension Idea and Closing.
