### ISSUE TITLE
Merging auto match pairs legacy extension

### ISSUE THREAD

**Issue by maityarkodeb** [adobe/brackets#10486]
[Auto match pairs](https://github.com/zr0z/brackets-automatch-pairs) last commit was 2 years ago.  It is safe to say this legacy extension would be very useful.  There is a pull request from [vilic](https://github.com/vilic) updated for compatibility with Release 1.1 that I am afraid will never be merged.  Is there a way to get these legacy extensions into the current registry?

**Comment by redmunds** [comment]
@maityarkodeb 

>  Is there a way to get these legacy extensions into the current registry?

Fork the repo, change the name to avoid confusion, make your updates, and then submit your version to the Brackets Extension Registry.

**Comment by maityarkodeb** [comment]
@redmunds With the proposed pull request on the current extension, it works fine.  However, I take no credit for the writing of that code.

Is it still appropriate to fork the repo?

**Comment by maityarkodeb** [comment]
@redmunds Thank you :)

**Comment by redmunds** [comment]
Another option is to download zip file from [vilic's forked repo](https://github.com/vilic/brackets-automatch-pairs) and then manually install it into Brackets.

**Comment by maityarkodeb** [comment]
@redmunds i did that and it suited my needs, thanks.  it would be nice to have a way to get these legacy extensions into the extension registry.  i'm sure i won't be the last person requesting the auto complete feature.  any plans for this sort of support in the future?

**Comment by maityarkodeb** [comment]
@redmunds i did that, and it suited my needs.  thanks.
