### ISSUE TITLE
HTML5 video tag support

### ISSUE THREAD

**Issue by miragevideo** [adobe/brackets#10487]
Hi,
I see the comments about adding video support into the Brackets shell. These are great, but not detailed enough for me to make it happen.  Is there more details and examples on how to add the ffmpeg libraries into the shell?  Can this be posted someplace?
thanks,

**Comment by jasonsanjose** [comment]
I'm not sure what the situation would be on windows and linux, but on mac part of the project setup in the gyp build removes this line related to ffmpeg https://code.google.com/p/chromiumembedded/source/browse/branches/2171/cef3/cef.gyp#1349.

The Brackets team originally removed ffmpeg over licensing/legal questions. I don't believe anyone has built a good case for re-enabling support.

If you're trying to fork the shell for your own use, you may be better off looking for CEF support http://magpcss.org/ceforum/.
