### ISSUE TITLE
Content Not Highlighting In Live Preview

### ISSUE THREAD

**Issue by kmcrayton7** [adobe/brackets#10489]
Hello,
I am new to coding and decided to tryout Brackets. I'm learning how to use this editor and I can't seem to get this feature to work as it does in the index.html file included. When I place my cursor on the tags I've created the tags highlight within the file but not the content in the browser using Live Preview. I can get it to work if I open open Inspect Element. Please advise.  

"Now, place your cursor on the  tag above. Notice the blue highlight that appears
            around the image in Chrome."

**Comment by redmunds** [comment]
@kmcrayton7 Be sure that you're using the Brackets built-in server (not using a Base URL to local server) and also make sure all of your files are in your current "project" using File > Open Folder...

**Comment by kmcrayton7** [comment]
I believe the latter is the issue because when I attempt to access them from the open folder they can't be selected. I can only access these files through Finder.
![screenshot 2015-01-29 21 09 36](https://cloud.githubusercontent.com/assets/9155255/5970087/53598e72-a7fb-11e4-83a3-28dbf2c42fea.png)

**Comment by redmunds** [comment]
Use FIle > Open Folder... to select the root folder of your "project" so it contains all of the files you are working with. They will be displayed in file tree on left.

**Comment by kmcrayton7** [comment]
It works...it works...thank you so much :-)

**Comment by schroef** [comment]
I also see this happening. Live Preview Highlight is greyed out. I got the site open using project. Nothing shows 
<img width="538" alt="screen shot 2018-07-13 at 20 28 51" src="https://user-images.githubusercontent.com/6923008/42718855-62df969e-86db-11e8-9b1f-95a68792b9cb.png">

**Comment by schroef** [comment]
I got it "fixed", i had been using css from url address so it doesnt get cached. Deleting that part and make the paths relative did make it work again.
