### ISSUE TITLE
Add support for JSF

### ISSUE THREAD

**Issue by abeneto** [adobe/brackets#10484]
Add support for JSF, for example quick access to tags styleClass (class in HTML). If you tell me where can i add this, i can try do it (i'm developer too) =). Thanks!

**Comment by svenvNL** [comment]
You can write an extension for this if you want. Otherwise you can add it in the /src/language folder

**Comment by nethip** [comment]
@svenvNL Thats correct. This sure is a good candidate to be coded as extension.
