### ISSUE TITLE
Providing CodeHints for new languages.

### ISSUE THREAD

**Issue by keir-rex** [adobe/brackets#10481]
Hey, 
I'm trying to provide ExtendScript (a superset of JS) CodeHints. 

In order to achieve this I have forked the default JavaScriptCodeHints extension.

Now, I'm able to get this working by replacing the JavaScriptCodeHint extension.

Do I need to register the language in //src/language/languages.json in order to show up in the Status bar's language-selector? Or can I do this dynamically?

Thanks in advance.

p.s. I really enjoy working with Brackets: keep up the good work!

**Comment by redmunds** [comment]
@keir-rex 

> Do I need to register the language in //src/language/languages.json in order to show up in the Status bar's language-selector? Or can I do this dynamically?

It depends on your goal. If this update is only for you on your local machine, then you can simply update the languages.json file.

But, this will be extra maintenance as you will need to re-merge this update any time that file is updated in Brackets. It will be much easier to maintain and share if you implement your changes as an extension.

To do this, create your ExtendScript Code Hints as an extension. You just need to register the provider with a higher priority than JavaScriptCodeHints so your extension is used instead.

Then read the [Language Support](https://github.com/adobe/brackets/wiki/Language-Support) article for adding ExtendScript.

**Comment by peterflynn** [comment]
Closing since I think that answers the question and there's no 'bug' to fix here.

**Comment by peterflynn** [comment]
More specifically, take a look at: https://github.com/adobe/brackets/wiki/Language-Support#defining-a-new-language

Also, I think this is unnecessary: "You just need to register the provider with a higher priority than JavaScriptCodeHints so your extension is used instead."  Since they're two different language ids, there's no conflict and thus you don't need the priority stuff.
