### ISSUE TITLE
80 characters Vertical guide in split view

### ISSUE THREAD

**Issue by demisx** [adobe/brackets#10494]
Is it possible to turn on  a vertical line guide at 80 characters similar to Atom and Sublime? This helps to keep the code going beyond 80 characters wide. Thank you.

**Comment by peterflynn** [comment]
Please upvote this item on our feature backlog to help raise its priority: [Column Ruler/Guide](https://trello.com/c/0VyU36nG/340-3-column-ruler-guide).  In the meantime, check out the popular Column Ruler extension for this.

Closing this issue to avoid duplication.

**Comment by demisx** [comment]
Thanks @peterflynn Just upvoted it. Unfortunately, the extension doesn't work in vertical split mode, so can't use it.

**Comment by peterflynn** [comment]
@demisx Lance Campbell is a very active member of the Brackets community, so normally I'd encourage you to file a bug report given that he'd probably respond quickly -- but looks like someone beat you to it: lkcampbell/brackets-ruler#37.  Currently blocked on some missing extensibility functionality in Brackets core, unfortunately: #9891.

**Comment by Hirse** [comment]
Not knowing about the [__Column Ruler__](https://github.com/lkcampbell/brackets-ruler) extension, I have written the [__Brackets Print Margin__](https://github.com/Hirse/brackets-print-margin) extension to add a column guide. I called the guide line "print margin" as in the Eclipse preferences though.
I don't have the ruler on top, but the vertical line is also displayed in multiple editors in splitview.

@demisx, you could have a look until the missing functionality is added.
