### ISSUE TITLE
Debug port for developer tools should be off by default

### ISSUE THREAD

**Issue by isonno** [adobe/brackets#10490]
The release version of Brackets automatically starts listening for the Chrome developer tools on localhost:9234.  Unfortunately, this prevents _other_ apps from listening on the same port if they launch after Brackets does.

The developer tools port should be off by default in the release version, so as to not conflict with other software you're using or creating.  It's also good security practice to not leave ports open unless they're actively in use.

**Comment by peterflynn** [comment]
Re security: note that the dev tools port does not accept any connections from the network.

**Comment by nethip** [comment]
Closing this as dev tools do not accept any connections from the network other than from Brackets.
