### ISSUE TITLE
Brackets auto insert a space character each new line

### ISSUE THREAD

**Issue by nhieu92** [adobe/brackets#10506]
Hi guys, i got a problem about enter new line, as the title
![screen shot 2015-02-01 at 9 58 31 pm](https://cloud.githubusercontent.com/assets/10509903/5992460/8883a7cc-aa5d-11e4-90a6-1b29a7f443ae.png)
Pls help me guys, i dont need this useless space, i want it look like:
![screen shot 2015-02-01 at 9 59 10 pm](https://cloud.githubusercontent.com/assets/10509903/5992468/b94773b6-aa5d-11e4-9acb-a59df9c642cf.png)

Thanks and sorry about my english :)

**Comment by RaymondLim** [comment]
@nhieu92 By default, Brackets is using 4 spaces for indentation. Your document is using 2 space indentation. So you just have to change it to 2 spaces in the status bar (close to bottom right corner of the Brackets window).

**Comment by nhieu92** [comment]
@RaymondLim Thanks bro, it worked.

**Comment by RaymondLim** [comment]
Ok, closing since it's not a real issue.
