### ISSUE TITLE
Enable the simple mode addon for CodeMirror

### ISSUE THREAD

**Issue by Belgabor** [adobe/brackets#10501]
The simple mode addon allows extension authors to write new CodeMirror modes in a more simple (regex-based) manner.

Reference: http://codemirror.net/demo/simplemode.html

The issue was briefly discussed on the google group: https://groups.google.com/forum/#!topic/brackets-dev/hoL6w3Iwg-M

**Comment by sprintr** [comment]
@MarcelGerber We can close this one as well.

**Comment by MarcelGerber** [comment]
This will be possible in Release 1.4
Closing.
