### ISSUE TITLE
Brackets - All links/buttons unresponsive upon opening.  

### ISSUE THREAD

**Issue by kevinIN3D** [adobe/brackets#10508]
I just updated Brackets from 1.0 to 1.1 the other day.  However today upon restarting my computer things started getting wonky with it.  Whenever I open Brackets it will all load fine, but when I try to select anything from the dropdown menu's or use any of the buttons they are completely unresponsive(the standard Windows move-maximize-minimize commands on the Brackets Icon work).  However none of the 'close' work and I must use Task Manager to force close it.

I have tried uninstalling and reinstalling, I have tried clearing the cache and nothing is working.  Running from the cmd line I open up Brackets, if I load an alternative 'index.html' I am able to use the minimize, maximize and close buttons in the window.  If I load in the base index.html the buttons become unresponsive.  It sounds like its not linking to something correctly inside the index.html, but on a fresh install I don't know why.

Debug cannot be run from the console window, and command line isn't throwing any errors.

**Comment by peterflynn** [comment]
@kevinIN3D You can do a deeper reset by deleting the _parent_ of the [cache folder](https://github.com/adobe/brackets/wiki/Cache-Folder) (the entire folder containing `cef_cache`, including everything else in there).  Also, after uninstalling make sure the install folder is completely gone -- if not, try deleting it manually.

If none of that helps, open http://localhost:9234 in a Chrome tab after launching Brackets.  You should see a link that takes you to a dev tools view in the Chrome tab.  What errors are listed on the Console?

**Comment by kevinIN3D** [comment]
It worked, much appreciated.  Tried out Atom to do some work in the mean time, but its not all setup out of the box like Brackets is!

**Comment by peterflynn** [comment]
Thanks, glad it hear it worked!
