### ISSUE TITLE
Search/Replace-Dialog disappears by switching between Windows

### ISSUE THREAD

**Issue by DerFu** [adobe/brackets#10513]
By switching between Windows the Search/Replace-Dialog disappears. That's not nice for Copy/Paste.

**Comment by peterflynn** [comment]
@DerFu What exact steps are you taking to switch windows?  It doesn't disappear for me if I switch using Alt-Tab or by clicking in the taskbar.  If that's not the case for you, try _Debug > Reload Without Extensions_ to make sure it's not caused by an extension you have installed.

**Comment by DerFu** [comment]
OK, if i choose 'Reload Without Extensions' it works fine. Thank You.
