### ISSUE TITLE
v1.1 does not render my custom font

### ISSUE THREAD

**Issue by luboslives** [adobe/brackets#10510]
I updated to 1.1 and it will not use my local font anymore, specified under View > Themes. It's defaulting to SourceCodePro.

Did something change with font handling? I've been using 'EcoCoding' successfully for a while now. It's a truetype font, no issues in the past. For the heck of it I tried out 'Corbel' and that worked fine (also truetype).

**Comment by peterflynn** [comment]
@luboslives What OS are you on?  On Mac & Windows, Brackets 1.1 uses a much newer version of Chromium in its native app shell.  If you make a simple HTML page with `font-family` set to the same value you're using in Brackets, and open that page in your regular Chrome browser, does it render as desired there?

Maybe also try formatting variations like spaces in the name.

**Comment by luboslives** [comment]
@peterflynn I'm on Windows 7. I've tracked down the problem, it's in the font name itself. The "font name" is fine but the "font family name" in my font manager is displayed as 'EcoCoding ?'

Even Firefox wasn't displaying the font inside of a test page, so maybe the Chromium engine was updated to look for the *font family name* instead of *font name*.

**Comment by peterflynn** [comment]
@luboslives Is it ok to close this then? Sounds like you're figured out how to get it to display?

**Comment by luboslives** [comment]
Yes i got it, I just used the family name. Might look into changing that font's family name if I have any software that can do that.
