### ISSUE TITLE
Brackets freezes while open folder twice on OS X 10.10.2

### ISSUE THREAD

**Issue by leeching** [adobe/brackets#10515]
The Brackets just freezes when I try to open folder the second time after initiating the app (clicking in the left navigator or in the menu above share the same problem).

It is very weird that the first time opening folder goes well, but the second time fails. The file select box doesn't exist and the app window freezes.

I have cleaned cache according to [Cache Folder](https://github.com/adobe/brackets/wiki/Cache-Folder) and even re-install it, but problem remains.

It seems not the problem of Brackets. Maybe it is the conflict with the latest edition of OS X (10.10.2). Because everything is O.K. before the upgrade. Or it's just an individual issue. My Brackets on mac is also the latest edition (Release 1.1 build 1.1.0-15558).

 May check it. Thanks!

**Comment by leeching** [comment]
I find the fact that once calling the file select box of OS X system in Brackets, even I don't open folder and click the cancle button, freezing occurs when calling it again. It is very likely a conflict. May the information helps.

**Comment by leeching** [comment]
@redmunds Yes, it is the problem of OS X, some other apps are also in the same situation. Thanks for your kind advice. I hope apple could fix it as soon as possible.

**Comment by redmunds** [comment]
Thanks for following up! Closing.
