### ISSUE TITLE
windows 8.1 — crashes on startup

### ISSUE THREAD

**Issue by tobibeer** [adobe/brackets#10518]
I have tried to install brackets 1.1 somewhere between 3-5 times.

Whenever I start it, it goes...

![brackets](https://cloud.githubusercontent.com/assets/97566/6044694/4c010a08-ac95-11e4-8ea2-b7da119d48e8.png)

Essentially Windows is telling me that brackets is no longer working whereas what it means is it never did... for me.

Actually, it kinda does, when I go through the program compatibility assistant. At some point after some 3 minutes of having windows do its thing it even finds some configuration to have it start. But then, windows doesn't actually remember whatever settings worked, even though it asked whether it should and I confirmed.

So, next startup I am again greeted with the above.

**Comment by redmunds** [comment]
@tobibeer [this article](https://github.com/adobe/brackets/wiki/Cache-Folder) explains where to find your "cache" folder. The parent folder is the `Brackets` user folder. Delete `Brackets` folder to clear everything out before trying to re-install. You may also want to re-download installer as it may have been corrupted.

**Comment by tobibeer** [comment]
@redmunds: I deleted any Brackets folder under `C:\Users\<username>\AppData\`. Unfortunately, that didn't help. I have updated the above screenshot to actually show the problem signature given by windows.

**Comment by JeffryBooher** [comment]
@tobibeer can you send us a crash log.  https://github.com/adobe/brackets/wiki/Crash-Logs describes how to setup your system to get the crash log.  Then if you could share it over something like Google drive or Dropbox so we can take a look at it.  Thanks!

**Comment by tobibeer** [comment]
Here's the dump: https://dl.dropboxusercontent.com/u/2040050/debug/Brackets.exe.5480.dmp

**Comment by peterflynn** [comment]
The crash log contains reference to a `FileBXH32.dll`, which is apparently part of an app called "FileBox eXtender."  @tobibeer do you have that app installed?  If so, maybe try disabling or uninstalling it temporarily to see if the crash goes away -- that would be valuable to know.

**Comment by tobibeer** [comment]
Thank @peterflynn, that solved the problem.
