### ISSUE TITLE
Renaming folder breaks file selection

### ISSUE THREAD

**Issue by njx** [adobe/brackets#10527]
1. Create a new project
2. Create a file "file.js" at the top level
3. Create a folder "folder" at the top level
4. Create a file "file-in-folder.js" inside "folder"
5. Select "file-in-folder.js" in the file tree (not the working set)
6. Rename "folder" to something else
7. Try to select "file.js" in the file tree

Result: The filename turns blue but does not get the background highlight. Clicking back and forth between file-and-folder.js and file.js in the file tree causes inconsistent state (the correct document doesn't open in the editor and sometimes the filename goes into rename mode).

**Comment by njx** [comment]
This seems important to fix - it pretty much breaks the file tree until you switch projects.

**Comment by ryanstewart** [comment]
@madanbn Do you think we can mark this for 1.2 and get a fix in?

**Comment by RaymondLim** [comment]
@njx I can't reproduce it on my Mac 10.9.

**Comment by redmunds** [comment]
I'm not seeing it either in latest master on 10.10.2 .

**Comment by njx** [comment]
Let me pull master - this was in 10.1 release.

**Comment by njx** [comment]
I can reproduce it in master with a slightly altered set of steps. Updated above.

**Comment by RaymondLim** [comment]
Yes, now I can reproduce it with the updated steps even in release 44.

**Comment by njx** [comment]
I put up a possible fix in #10541, but there are other issues that someone more familiar with the file tree code should probably address.

**Comment by peterflynn** [comment]
There's a separate bug with the view panes if you follow these steps and then reselect "file-in-folder.js" again (see https://github.com/adobe/brackets/pull/10541#issuecomment-73821322), but the tree bug is fixed -- closing.
