### ISSUE TITLE
Won't save when making changes in CSS file.

### ISSUE THREAD

**Issue by apolloinfinity** [adobe/brackets#10526]
If I make a changes in my CSS file. Whether I make a small change in color or add a new rule, the file will not save. It will only save after I quit the program. I don't know if its brackets itself or one of the plug-ins that is causing this problem.

**Comment by redmunds** [comment]
@apolloinfinity You can quickly check to see if this is caused by an extension by using Debug > Reload Without Extensions and then trying again to save.

**Comment by apolloinfinity** [comment]
Thank you. It is an extension. Now I got to figuire out which one.

**Comment by redmunds** [comment]
Closing. Please let us know here which extension it was. Also, open an issue on the repo of the extension.

**Comment by peterflynn** [comment]
The instructions at https://github.com/adobe/brackets/wiki/Troubleshooting#disabling-extensions-individually should help you figure out which extension.

**Comment by mainstreetmark** [comment]
brackets-beautify v1.2.0 is causing this issue for me on .scss files (and i presume .css too)
