### ISSUE TITLE
Project naming

### ISSUE THREAD

**Issue by cdpritcha** [adobe/brackets#10538]
I'd love a way to name projects. Right now, the projects display using the local folder name. I have a over a dozen different projects in Brackets, and when I go to switch to a different project, it is difficult to find the one I need due to the way we name our project folders. Final web sites are put in a folder called 'www-'. So I see a long list of 'www-' in the Open Folder/Projects dropdown. 

In Project Settings, I think there should be another field for the Project Name. Then, that name would appear in the project dropdown as well as at the top of the file sidebar.

**Comment by ivangretsky** [comment]
+1 for this

**Comment by ivangretsky** [comment]
+1 for this. I got a long list of the same named folders too ((

**Comment by mihawk90** [comment]
As a temporary solution, there is currently this:
https://github.com/petetnt/brackets-name-a-project

seems to work pretty well, though I would like if the name was stored in the brackets.json, but I guess we can't have everything :)

**Comment by abose** [comment]
As there is already an extension that takes care of this- lowering priority. I have moved this issue to backlog for later consideration.

**Comment by petetnt** [comment]
@mihawk90 The names should be saved to `brackets.json`... there was a short while between 0.0.1 and 0.0.3 when the preferences weren't correctly saved, but 0.0.3. should have fixed that. However if you still have that issue, file an issue to that repo and I'll investigate asap :+1:
