### ISSUE TITLE
Tag Error

### ISSUE THREAD

**Issue by kmcrayton7** [adobe/brackets#10533]
Why when I add <b></b> tags to my code is it bolding other parts of my document?
![screenshot 2015-02-05 22 14 34](https://cloud.githubusercontent.com/assets/9155255/6074065/f5c87d92-ad84-11e4-8f91-52a43d05f437.png)

**Comment by codymaines** [comment]
It appears you have an opening bracket (<) on line 16 - "<b><The Strong Tag</b>".This is causing your title to be treated as a tag and not fully rendering the text or closing the bold tag.

**Comment by kmcrayton7** [comment]
Thank you
