### ISSUE TITLE
Live Preview can't connect

### ISSUE THREAD

**Issue by Ringli** [adobe/brackets#10539]
Since I updated to Release 1.1 build 1.1.0-15558 (release ea908cae5) on Mac 10.10.2 (14C109) live preview can't call up Chrome anymore. 
When I click the Live Preview icon it turns half orange and shows: Live Preview: Connecting... Chrome does not open, nothing further happens. I am running Chrome Version 40.0.2214.111 (64-bit).

Could this be a Proxy issue?
Thanks for your help.

**Comment by redmunds** [comment]
@Ringli Yes, try removing any proxies.

**Comment by Ringli** [comment]
Thanks @redmunds, after removing all proxies it worked.
