### ISSUE TITLE
Adding file extensions to .brackets.json doesn't work as documented

### ISSUE THREAD

**Issue by Brade** [adobe/brackets#10543]
Followed the instructions here for use in a Drupal project: https://github.com/adobe/brackets/wiki/Language-Support

My .brackets.json in project root looks like this:

```
{
	"language.fileExtensions": {
		"inc": "php",
		"module": "php
	}
}
```

Restart Brackets, and it doesn't work. Thoughts?

**Comment by sprintr** [comment]
You have a missing quote.

```json
{
    "language.fileExtensions": {
        "inc": "php",
        "module": "php"
    }
}
```

**Comment by Brade** [comment]
FFFFUUUUUUUUU.... thanks!
