### ISSUE TITLE
Working files section should be shown horizontally

### ISSUE THREAD

**Issue by a2ankitrai** [adobe/brackets#10547]
hi,

It would be a great help if the working file section can be shown horizontally rather than vertically like that of eclipse IDE.

**Comment by sprintr** [comment]
Extensions are available to do that. You can choose what is best for you.

- [Brackets Document Toolbar](https://github.com/dnbard/brackets-documents-toolbar)
- [Tabs - Custom Working](https://github.com/DH3ALEJANDRO/custom-work-for-brackets)
- [Brackets Working File Tab](https://github.com/demonmhon/brackets-working-file-tabs)
- [Brackets Tabs](https://github.com/crot4lus/Brackets---Tabs)

**Comment by a2ankitrai** [comment]
Thanks a lot.


On Sun, Feb 8, 2015 at 12:54 PM, Amin Ullah Khan <notifications@github.com>
wrote:

> Extensions are available to do that. You can choose what is best for you.
>
>    - Brackets Document Toolbar
>    <https://github.com/dnbard/brackets-documents-toolbar>
>    - Tabs - Custom Working
>    <https://github.com/DH3ALEJANDRO/custom-work-for-brackets>
>    - Brackets Working File Tab
>    <https://github.com/demonmhon/brackets-working-file-tabs>
>    - Brackets Tabs <https://github.com/crot4lus/Brackets---Tabs>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/10547#issuecomment-73400232>.
>



-- 
With Regards,
Ankit Rai
Mob: 7405677330, 8109687159

**Comment by redmunds** [comment]
There's already an [item in our backlog for this](https://trello.com/c/k5ToJ7xE/743-tabs-for-open-editors-files-instead-of-working-files-vertical-list) if you care to vote for it. Closing.
