### ISSUE TITLE
Go Programming Language

### ISSUE THREAD

**Issue by pythonme** [adobe/brackets#10559]
Nice if we have it added to the list...

**Comment by peterflynn** [comment]
Cold easily be done in core or as an extension, since there is a [Go mode for CodeMirror](http://codemirror.net/mode/go/) already available.

**Comment by petetnt** [comment]
Simple extension for this: 
https://github.com/petetnt/brackets-codemirror-go

**Comment by ApfelUser** [comment]
There is already an extension :smile: 

https://github.com/devinceble/brackets-go

**Comment by petetnt** [comment]
Dang, I searched the registry but somehow missed it. Figures.

----- Alkuperäinen viesti -----
Lähettäjä: "ApfelUser" <notifications@github.com>
Lähetetty: ‎12.‎2.‎2015 22:29
Vastaanottaja: "adobe/brackets" <brackets@noreply.github.com>
Kopio: "Pete Nykänen" <petelive138@gmail.com>
Aihe: Re: [brackets] Go Programming Language (#10559)

There is already an extension  
https://github.com/devinceble/brackets-go

**Comment by peterflynn** [comment]
Closing since it looks like at least two extensions are already available.

**Comment by kortemy** [comment]
Current extension only supports syntax highlighting. I am working on one to incorporate all useful go tools (gofmt, go imports, golint, gocode).
So far formatting is done, currently working on linter and autocomplete.

https://github.com/kortemy/gockets
