### ISSUE TITLE
Invisible popover from live preview overlaps text editor

### ISSUE THREAD

**Issue by spongessuck** [adobe/brackets#10556]
It seems like the popover showing the state of the live preview isn't removed from the UI after it fades out. The cursor turns into a regular arrow instead of an i-bar when hovering in the top-right area of the editor, and you cannot select the text under it.

Running in Windows 7.

**Comment by redmunds** [comment]
@spongessuck Thanks for reporting bugs. Closing this as a duplicate of #10309.
