### ISSUE TITLE
Indenting in HTML can get messed up

### ISSUE THREAD

**Issue by jeffshaver** [adobe/brackets#10557]
If you type out something like

```
<template name="application">
  <div class="header"></div>
  <div class="footer"></div>
</template>
```

if you go back and hit return right after the template tag (before .header), if will indent incorrectly

```
<template name="application">
 <div class="messed-up"></div>
  <div class="header"></div>
  <div class="footer"></div>
</template>
```

**Comment by redmunds** [comment]
@jeffshaver Brackets does not yet detect the indenting type and level in your page, so you need to set it as desired. According to your example, it looks like you want to indent 2 spaces. On the right side of the status bar at the bottom of editor, if you see "Tabs", then click it so it toggles to "Spaces". In the field to the right of that, click it to edit and change it to "2" then hit Enter. Does that fix it?

**Comment by jeffshaver** [comment]
@redmunds yeah. I am saying, my indentation level is set to 2 spaces (says so in preferences and at the bottom right of the application), but this issue occurs, consistently. I can't get it to not occur, actually.

Basically type out a div. nest a div inside that. go back to the end of the first line and hit enter. Your indenting is now wrong. For me it is only one space instead of two

**Comment by peterflynn** [comment]
@jeffshaver Sounds like you're using the Emmet extension, which causes exactly this problem -- see #9482.  If you don't have Emmet installed, please let me know and we can reopen this for more investigation.
