### ISSUE TITLE
[L10N][Sample file]: The string "Extension Manager" should be localized in the sample html file.

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets#10569]
Steps:
1. Launch Brackets and open the sample html file
2. Hover on the Extension Manager sidebar icon.

Result:
The string " Extension Manager" is not localized in the sample file.

Expected:
The string should be localized and keep consistent with sidebar icon tooltip.

ENV: Win7 and Mac 10.9 JP & FR os
Build: 1.2.0-15675

Screenshots:
ENU reference:
![en-1](https://cloud.githubusercontent.com/assets/4251563/6142770/0bd47c68-b1f8-11e4-8c15-aecd046fb1ff.png)
FR:
![fr-1](https://cloud.githubusercontent.com/assets/4251563/6142759/b7ebdf06-b1f7-11e4-8776-a5047a08705f.png)
JP:
![jp-1](https://cloud.githubusercontent.com/assets/4251563/6142761/bc865bb8-b1f7-11e4-9617-accd0724a56e.png)

**Comment by pantkowiak** [comment]
fixed with PR https://github.com/adobe/brackets/pull/10572

**Comment by lmariz** [comment]
Extension Manager is a product name and normally they stay in English. Is this not the case?

**Comment by peterflynn** [comment]
@lmariz It looks like the dialog name is translated in most Brackets translations.  It's not really a product name, it's the name of a feature / command / screen, and normally those are translated.  Same for other Brackets commands like Quick Edit.

**Comment by lmariz** [comment]
OK, thanks for confirming @peterflynn

**Comment by rawat11** [comment]
@peterflynn thanks for confirming.

**Comment by KatarzynaWodzinska** [comment]
For FR please change 'Extension Manager' to: Gestionnaire d’extensions. A curly quote should be used to keep consistency with the rest of the text. Other than that, the FR string is correct.

**Comment by pantkowiak** [comment]
fix is in PR https://github.com/adobe/brackets/pull/10624

**Comment by peterflynn** [comment]
@julieyuan Fix in PR #10625 was merged -- please verify on the `release` branch

**Comment by julieyuan** [comment]
Thanks @pantkowiak @peterflynn , verified the FR string is correct. 

@pantkowiak ,please also help to change the same FR string with other two string ID to: Gestionnaire d’extensions. Their string ID is: `CMD_EXTENSION_MANAGER`,`EXTENSION_MANAGER_TITLE`. And please notes that the translation for `EXTENSION_MANAGER_TITLE` is not same as the translation for the string 'Extension Manager' right now, could you please help to check whether it need to be kept consistency? Thanks.

![screen shot 2015-02-26 at 6 01 59 pm](https://cloud.githubusercontent.com/assets/4251563/6406319/d4ab5cdc-bde3-11e4-9717-73c2be5aef3a.png)
![screen shot 2015-02-26 at 6 03 43 pm](https://cloud.githubusercontent.com/assets/4251563/6406321/dc206da4-bde3-11e4-8449-fb73a00e9ec1.png)

**Comment by pantkowiak** [comment]
@julieyuan issue is fixed with PR #10767, please verify.

**Comment by julieyuan** [comment]
Thanks @pantkowiak .Confirmed it is fixed with latest build 1.3.0-15767 (master 2d880bcbe), closing as fixed.
![screen shot 2015-03-23 at 7 41 35 pm](https://cloud.githubusercontent.com/assets/4251563/6794903/95195aae-d195-11e4-9ca6-e68af59ecd06.png)
![screen shot 2015-03-23 at 7 41 53 pm](https://cloud.githubusercontent.com/assets/4251563/6794905/9ac28df4-d195-11e4-8800-921fb698845f.png)
