### ISSUE TITLE
[FeatureSuggestion] Tab control for snippets

### ISSUE THREAD

**Issue by forbsie1888** [adobe/brackets#10575]
I'd quite like to see an option similar to NetBeans where if you type something from your snippets, and TAB, then it inserts the block of code.

For instance, if I type html5 and press tab, it will insert this: 

<!DOCTYPE HTML>
&lt;html>
&lt;head>
&lt;meta charset="utf-8">
&lt;meta name="viewport" content="width=device-width, initial-scale=1" />
&lt;script type="text/javascript" src="scripts/jquery-2.1.1.js"></script>
&lt;script type="text/javascript" src="scripts/scripts.js"></script>
&lt;link rel="stylesheet" href="stylesheets/stylesheet1.css" />
&lt;title>Change title Here&lt;/title>
&lt;/head>
&lt;body class="body">

&lt;/body>
&lt;/html>

Instead of having to go all the way to snippets and then search the one you want, then add it.... maybe I'm just lazy.

**Comment by nethip** [comment]
@forbsie1888 What you are looking for is available in the form `Emmet`. Please go through this link to know more about it. (http://emmet.io).

Good news is there an extension available for brackets already. Launch extension manager and search for "emmet". You should be able to find the Brackets Emmet extension there.

**Comment by peterflynn** [comment]
@forbsie1888 There are several extensions available that can give you this functionality -- just search for "snippets" in Extension Manager.  Also check out Emmet, which already has a built-in `html:5` snippet you can insert and also supports custom snippets similar to the other extensions.

If you'd like to see this as a built-in Brackets feature, please upvote this item on our feature backlog: [Code Snippets / Templates](https://trello.com/c/tVSVhAg2/342-code-snippets-templates-insert-manage-snippets).  I'll close this issue to avoid duplication.

**Comment by peterflynn** [comment]
@nethip Oops, sorry for the redundant reply!

**Comment by nethip** [comment]
@peterflynn No issues :smile: . I think your reply was quicker than mine :smile:
