### ISSUE TITLE
Clicking to left of filename can collapse parent folder

### ISSUE THREAD

**Issue by busykai** [adobe/brackets#10574]
To reproduce:

1. Expand a folder in the project tree which would contain at least one file in it.
2. Click on file at the width of parent's expand triangle (e.g. slightly left to the file name, could be tricky :).

Observed: parent collapses independently of whether file is selected or not.
Expected: if the file is selected, the selection stays. if it's not selected, then selection changes. Parent should not be collapsed.

**Comment by peterflynn** [comment]
Yep.  And for deeply nested files, depending on how far to the left of the filename you click, it'll collapse a folder farther up the parent hierarchy.

I'm going to tweak the title a little to clarify.

**Comment by nethip** [comment]
Closing as this is fixed by PR https://github.com/adobe/brackets/pull/10652

**Comment by nethip** [comment]
Reopening this as the fix was not the right fix.

**Comment by ficristo** [comment]
While is a small issue, when you hit it is quite annoying.
Can be prioritized for the next release?
