### ISSUE TITLE
Can't use correcly Brackets 1.1 without been ROOT on Debian

### ISSUE THREAD

**Issue by bastri** [adobe/brackets#10589]
Hi. When I open Brackets been ROOT i can open folders correctly. 
but when i run it as a NORMAL user i cant do these. 

What can I do? 
Sorry for my bad english, also I am new at Linux. Thanks.

**Comment by mightypenguin** [comment]
@bastri  I think you have a permissions problem.
http://ryanstutorials.net/linuxtutorial/permissions.php

**Comment by prafulVaishnav** [comment]
@bastri Have your problems resolved?

**Comment by prksingh** [comment]
Closing. Please let us know if the issue persists and I can reopen this
