### ISSUE TITLE
Add Reload with custom extensions

### ISSUE THREAD

**Issue by datamweb** [adobe/brackets#10580]
I have an idea for Brackts.
1.Add Debug menu option **Reload with custom extensions**.
2.Then open a ModalDialoag for the selection of plugins and load with selected extensions  Brackts.
3.Click the OK button. 
4.Realod brackets with selected extension.

**Comment by redmunds** [comment]
@datamweb [This feature](https://trello.com/c/DtVjozXu/865-2-enable-disable-individual-extensions) is already being tracked in the Brackets product backlog. Please add your vote. Closing.

**Comment by datamweb** [comment]
OK. 
@redmunds Thanks  for your response.
