### ISSUE TITLE
JSLint docs refers to an older menu item.

### ISSUE THREAD

**Issue by cfjedimaster** [adobe/brackets#10586]
From: https://github.com/adobe/brackets/wiki/How-to-Use-Brackets

"JSLint is very picky about formatting. JSLint is very picky about a lot of things. You can hide the JSLint results panel by clicking the close box at the top (the status bar icon will still indicate if JSLint has found problems with either a green checkmark or yellow warning symbol), or you can turn off JSLint completely by unchecking View > Enable JSLint."

View/Enable JSLint is no longer a menu option.

**Comment by peterflynn** [comment]
Good catch! Fixed.
