### ISSUE TITLE
Browsersync integration

### ISSUE THREAD

**Issue by AllThingsSmitty** [adobe/brackets#10582]
Consider providing Browsersync integration in the Brackets IDE. The Live Preview feature in Brackets is nice but a tool like Browsersync would provide a more robust preview across multiple browsers and devices simultaneously.

**Comment by redmunds** [comment]
@AllThingsSmitty Brackets 1.0 introduced the [Live Preview MultiBrowser experimental feature](https://github.com/adobe/brackets/wiki/Live-Preview-Multibrowser) -- have you tried that? I'm not familiar with Browsersync -- are there significant improvements over the Brackets MultiBrowser feature?

**Comment by AllThingsSmitty** [comment]
@redmunds I didn't know about the MultiBrowser experiment feature. I don't know how it compares to Browsersync; I'll have to work with it some.

**Comment by redmunds** [comment]
Cool. Closing this for now. Feel free to log any improvements to MultiBrowser feature.

**Comment by peterflynn** [comment]
There is also a Brackets extension for Adobe Edge Inspect, which I think is similar to BrowserSync.  And an extension for LiveReload, which is a bit simpler but also works more broadly across browsers/devices.  And then as @redmunds said, there's the new built-in Multi-Browser Live Preview feature available in beta.

**Comment by LayZeeDK** [comment]
BrowserSync can synchronize scrolling and form field population across browsers and devices.

**Comment by ApfelUser** [comment]
Yeah, BrowserSync seems better than Live Preview

**Comment by peterflynn** [comment]
@ApfelUser Live Preview updates continuously as you type, or even while you're dragging colorpicker sliders, etc.  It does not need to trigger a full page reload to update, so the state of the page (including  animation) is not interrupted or reset.  It's designed for use while you're still heavily editing a page.

BrowserSync seems designed more for testing workflows with pages that are mostly already built, syncing your _viewing_ of a page across devices.  But like other such tools, it only updates when you save a file and updating usually (or always?) requires a full page reload.  This is similar to other tools like LiveReload and Adobe Edge Inspect.

So they are two different tools and you might use both, at different stages in your development process.
