### ISSUE TITLE
Case sensitive `Command+D` word matching

### ISSUE THREAD

**Issue by demisx** [adobe/brackets#10597]
Hi. Currently, if I click on a word, then hit `Command+D` to highlight matching words, it matches them without any regards to the case. Since Javascript and many others is a case sensitive language, I'd like to make all of my matches to be case sensitive by default. Is there a way to do this now? I can't seem to find the right setting.

Thank you.

**Comment by redmunds** [comment]
@demisx There is not yet a way to do that in core Brackets with a shortcut, so you'll have to use `Command+F`, then click the "Aa" toggle to make it case-sensitive.

**Comment by demisx** [comment]
@redmunds Thank you for your prompt reply. Is this something in one of the Trello cards, though? `Command+F` would not replace `Command+D` -- doesn't give me multiple cursors.

**Comment by redmunds** [comment]
Oh, I was confused when you said `Command+D` -- I thought you were referring to an extension. That's `Command+B` in Brackets.

That feature is being tracked here: https://trello.com/c/eZTEudAp/1140-multiselect-find-all-from-find-bar

**Comment by demisx** [comment]
Sorry. `Command+B` doesn't work for me. I probably have an extension that remaps it to `Command+D` to match SublimeText. Anyway, multiselect is what I guess I need to refer to is as and I am glad it's being already tracked. Thank you.
