### ISSUE TITLE
Please sign Linux and source releases!

### ISSUE THREAD

**Issue by lrebrown** [adobe/brackets#10595]
Starting with the upcoming 1.2 release, could you please start providing a gpg signature for Linux and source releases.

This doesn't have to be a detached sig for each individual file, you could provide sha512 hashsums in a text file and provide a detached sig file for that.

**Comment by peterflynn** [comment]
@lrebrown There is no source release that we distribute, but if you clone the Git repo you'll be getting the source securely over SSH.  That's the only official way to get source.

**Comment by lrebrown** [comment]
> There is no source release that we distribute

See here:
https://github.com/adobe/brackets/releases

Sprints 1-31a and a few misc others are only available as source, each with small zip and tar.gz download options (presumably those are just auto-created by github), but for every other release since sprint 31a, there's a source .zip and a .tar.gz download available as proper large-ish links right alongside the deb, dmg and msi download links. Are these source archive downloads put together by yourselves, or is github auto generating these?

> but if you clone the Git repo you'll be getting the source securely over SSH

Which is isn't sufficiently secure imo.

Why should I trust an SSH connection to github to securely obtain source of an application? I should only trust my SSH connection to github if I properly verify their public key through the WOT, which would similarly have to be done directly with yourselves otherwise, but, via github, then furthermore I must trust that yourself and every other Adobe-Brackets developer collectively have similarly gone to sufficient lengths to verify the github SSH fingerprint prior to setting up your SSH login with github, and then just hope that no github staff members are compromising the source repo, nor that any breaches of github security occur. Direct trust to yourselves is obviously much preferred.

As you probably already appreciate, any and every application you install has the potential to entirely compromise your machine, and being able to properly trust that source/binaries you have obtained at least truly come directly from the developer, without modification, is valuable towards maintaining system security. The best model for doing so is for a WOT to be setup which incorporates those developers. Obviously personally reviewing every line of code you download would be best, but is impractical.

Using that WOT, should you start offering signed binaries/source-archives, we users, as long as we trust that whoever posts the release has sufficiently verified every commit that has gone into it, have decent means available to us for ensuring that what we have obtained is the original copy generated by yourselves. Signed git tags/commits would also be excellent to have, providing obvious further benefits.

**Comment by MarcelGerber** [comment]
Yeah, all the `.zip` and `.tar.gz` files listed under Releases were auto-generated by GitHub.

I don't know how familiar you're with git, but actually every git commit hash (SHA1) is a checksum of the changes made in this commit, so by `git clone`-ing a repo, you can be sure that you have the exact same source that is on GitHub.

**Comment by rroshan1** [comment]
We recommend using ``git clone`` to get trusted Brackets source code. The source TARs are auto-generated by GitHub and thus don't have the signature.
