### ISSUE TITLE
Brackets on Windows 10

### ISSUE THREAD

**Issue by Zzz01Breikoft** [adobe/brackets#10601]
I'm testing Windows 10, and Brackets seems to be not working well on it.

or that's what I think

I'm not sure about it.

When I installed Brackets for the first time, appearing errors like "The specified file is not found." "You can't delete the file, unknown error".

And One day, I was going to open it and the program freezes and stops responding, you can't do anything.

The only way to fix the problem was reinstalling again Brackets and seems to be working normally again, but it works a little slow.

I know that this is stupid, But I hope that Brackets work correctly when Windows 10 is released to the public

**Comment by RexXxuS** [comment]
Hey, I'm using Windows 10 since it came out. Brackets since one month ~. Everything runs smooth and fast from day 1. Don't know what happened to you.
I installed the msi from their website. Even copy paste my program folger + roaming folder and pasted it at work on windows 7 worked without problems.

**Comment by Zzz01Breikoft** [comment]
No, don't worry; Maybe, I did something wrong while using brackets because the program crashes horrible, but after reinstall, is working correctly. A little slow but work.

**Comment by peterflynn** [comment]
Closing since it sounds like the problems have gone away.  If you hit any more crashes, please [gather a crash log](https://github.com/adobe/brackets/wiki/Crash-Logs#windows) and then let us know so we can investigate further.

**Comment by bamptini** [comment]
Happening to  me. Was working fine in Windows 7, then I had a new laptop and had to resintall Brackets. Same OS but now nothing responds. It sjust sits there. No mouse clicks work and I can only close it by going into Mangers and killing the process. Not ideal
