### ISSUE TITLE
Extension Registry (website) is down

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#10603]
https://brackets-registry.aboutweb.com/ responds on Chrome with status

```
(failed)
net::ERR_CONNECTION_CLOSED
```

and with Firefox with just:

```
Status: Aborted
```
![image](https://cloud.githubusercontent.com/assets/7641760/6203521/f9556392-b52e-11e4-878d-c49b28dd9ae6.png)

Same thing over `http://`, Extension Manager works fine though.

**Comment by ApfelUser** [comment]
:+1: 
Same in Frankfurt am Main, Germany

**Comment by petetnt** [comment]
Aaaand it's alive again

**Comment by JTruax** [comment]
it's currently down again.

**Comment by boopeshmahendran** [comment]
@JTruax Thanks for reporting. Fixed it now.
