### ISSUE TITLE
Unknown Internal Error, when installing Emmet

### ISSUE THREAD

**Issue by Exoticness** [adobe/brackets#10607]
Hello. I've got troubles installing extensions. Each time I try to there's this error message showing
"Installation failed. Unknown internal error". Developer Tools console shows only this error: 

/extensibility/Package.js:408 Unknown installation error Object
/extensibility/Package.js:408 Unknown installation error Object
/extensibility/Package.js:408 Unknown installation error Object {code: "EPERM" errno: 50 path: "C:\Users\Vlasenko\AppData\Local\Temp\bracketsPackage_115116-2388-1sj9b14\node_modules\emmet\test\actions\expandAbbreviation.js"__proto__: Object

I have encountered with this problem only with Emmet. All other extentions is functioning normally. Reinstalling Brackets and uninstalling all extentions don't resolved this problem. I look forward to your reply.

Brackets 1.2.0 | Windows 8.1 | No proxy

**Comment by redmunds** [comment]
@Exoticness The Brackets Extension Registry server was down this weekend and has been restarted. Do you still see problem?

**Comment by Exoticness** [comment]
@redmunds Nope, i still see this problem

**Comment by zaggino** [comment]
That's an EPERM error (operation not permitted) when accessing `\AppData\Local\Temp\bracketsPackage_115116-2388-1sj9b14\`
No idea why, haven't seen this one before.

**Comment by Exoticness** [comment]
I tried to change the write, and other permission to the directory "Temp". But nothing happened.

**Comment by zaggino** [comment]
Have you tried disabling any antivirus solutions? They may block access to script files they might consider dangerous. Some I've seen are especially strict on files in temp folders.
