### ISSUE TITLE
Javascript File Inference Problem

### ISSUE THREAD

**Issue by alastairparagas** [adobe/brackets#10604]
Every time I work on a project that uses Bower (specifically, with Ionic and AngularJS), NodeJS and so forth, I get the error below. I have looked at configuring Brackets JS Hinting feature off [through the docs](https://github.com/adobe/brackets/wiki/JavaScript-Code-Hints#configuration), but it is quite tedious that I have to do this for every Ionic project that I have. Is there any way I can exclude any child "node_modules" or "bower_components" globally? Or do I have to this for each project?

![screenshot from 2015-02-15 09 59 59](https://cloud.githubusercontent.com/assets/5952869/6203638/74504c5a-b4f9-11e4-8190-7acc7391c46f.png)

Also, could this be the culprit to why Brackets seems to respond very slowly on my computers? Sometimes, Bracket crashes or my computer slows down with Brackets running.

**Comment by redmunds** [comment]
@alastairparagas Sorry to hear you're having problems with Brackets.

> ...it is quite tedious that I have to do this for every Ionic project that I have

After you setup the `.jscodehints` file, then you can just copy it (outside of Brackets) to any other project. Or are your projects too different?

There's also an [Exclude Folders extension](https://github.com/gruehle/exclude-folders) for globally excluding files from Brackets. Note that this extension excludes files from *all* Brackets features (i.e. you won't even see them in the file tree).

Another option is to take a look in the `.brackets.json` project prefs file in the root of your project that is created, if necessary, and then updated with `jscodehints.detectedExclusions` entries to prevent problematic files from be processed again. You can also manually copy projects prefs files to each of your project.

> Also, could this be the culprit to why Brackets seems to respond very slowly on my computers?

Yes, this can cause a noticeable slowdown.

**Comment by alastairparagas** [comment]
@redmunds Thank you! My problem is, sometimes I find myself opening Brackets in a Cordova project's root folder, and sometimes, I find myself opening Brackets in a Cordova project's www folder. ``node_modules`` would be in my project's root folder, whereas my ``bower_components`` folder would be in my www folder. It seems like the extension can solve this problem.

**Comment by redmunds** [comment]
Brackets caches the compiled JS used for code hints per project, so changing the project folder less often should also help performance. Closing this issue.

**Comment by alastairparagas** [comment]
@redmunds Okay. I installed the ``exclude-folders`` plugin, modified it to ignore ``bower_components`` and everything seems to check out beautifully from this point on. Brackets is running much faster too! Thank you so much!
