### ISSUE TITLE
Upon CSS editing, Live Preview was canceled for an unknown reason ({0})

### ISSUE THREAD

**Issue by z82n** [adobe/brackets#10614]
Title says it all. Fresh install, Mac Yosemite, installed the coolwater theme, that's it.  What to do

**Comment by redmunds** [comment]
@z82n Start by reading the [Live Preview section of the How To Use Brackets doc](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#live-preview) and the [Live Preview Isn't Working section of the Brackets Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting). Let us know if that helps you solve the problem.

**Comment by z82n** [comment]
I did, it doesnt

**Comment by redmunds** [comment]
Wow, that was quick! There is a lot of info in those links, so I'm hoping you had already went thru that before I sent those links. Also try removing any network proxies.

**Comment by ryanstewart** [comment]
Have you tried the experimental Live Preview? Instructions for enabling it [are here](https://github.com/adobe/brackets/wiki/Live-Preview-Multibrowser) We're hoping to move over to that as the default implementation in the not too distant future.

**Comment by z82n** [comment]
experimental worked. Cheers!
