### ISSUE TITLE
Reset extension manager's scroll position to top on filtering

### ISSUE THREAD

**Issue by stowball** [adobe/brackets#10611]
When you search/filter extension manager's results after you have already scrolled down, the scroll position will be incorrectly remembered (if applicable), or it will scroll down to the last item if there are less results than your current scroll position.

When a new search is performed, scrolling should be reset to the top.

### Steps to reproduce
1. Open extension manager
2. Scroll all the way to the bottom on available extensions
3. Search for "doc"

### Actual result
You're viewing the least relevant(?) results at the end of the list.

### Expected result
To be scrolled to the top of panel for the most relevant matches.

**Comment by darkcoderrises** [comment]
i was working at this,
would adding window.scrollTo(0,0); fix this?

**Comment by MarcelGerber** [comment]
Take a look at [this](https://github.com/adobe/brackets/blob/5f2ccda1937a11ddc86cd807ba5530d0dabf37ad/src/extensibility/ExtensionManagerDialog.js#L330) to see what we already do to keep the scroll position for each tab.
So `$(".modal-body", $dlg).scrollTop(0);` should work for you.

**Comment by darkcoderrises** [comment]
Thanks, i have updated the pull request

**Comment by darkcoderrises** [comment]
@MarcelGerber it says $dlg is not defined

**Comment by darkcoderrises** [comment]
I have made a new pull request, (sorry i went on a vacation, so things were outdated)
https://github.com/adobe/brackets/pull/11378

**Comment by haiderali2385** [comment]
www.cash-time44.com

**Comment by mansimarkaur** [comment]
I have cached `$(".modal-body", $dlg)`  in to its own variable in #12805
