### ISSUE TITLE
Generate CSS file by scanning a PSD file

### ISSUE THREAD

**Issue by stealthprism** [adobe/brackets#10619]
Instead of we selecting each layer in the PSD file to get its CSS, there should be an automated mechanism of scanning all the PSD layers and generating a CSS file.

This will ensure that we don't miss out any of the sections/ layers in the PSD file while converting the PSD file to an HTML page.

Also, this will be fast and reliable approach to convert PSD files to HTML files.

**Comment by MarcelGerber** [comment]
The first problem that comes to my mind after reading this: How should Extract/Brackets determine what rules it should create, i.e. what selectors it should apply?

**Comment by rishabhp** [comment]
+1

**Comment by stealthprism** [comment]
Brackets is able to apply the rules based on the layer selected by the
user. This is already happening. It is able to determine the rules and
generate it (CSS) for the user.

Instead of selecting individual layers and checking the CSS rules for the
selected layer, Brackets should parse all the layers, generate their CSS
rules and put them all in a separate file.

Hope this clarifies my point.


On Wed, Apr 15, 2015 at 10:57 AM, Rishabh <notifications@github.com> wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/10619#issuecomment-93249896>.
>



-- 
Regards,
Mohammed Anwaar

**Comment by abose** [comment]
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
Marking as extension idea.
