### ISSUE TITLE
Directory labels are blank in Release 1.2 Pre Release - Linux CEF 2171

### ISSUE THREAD

**Issue by Revlin** [adobe/brackets#10615]
I installed this release from the 32-bit deb binaries on Ubuntu 14.04

![brackets release 1 2 32-bit on-ubuntu-14 04](https://cloud.githubusercontent.com/assets/307921/6232062/92f28020-b67e-11e4-8075-76eb3a442e78.png)

**Comment by redmunds** [comment]
@Revlin There was an extension (that I forget the name of) that was causing this. This extension has been updated, so open Extension Manager and apply any updates. Closing.
