### ISSUE TITLE
Remember "Find..." state

### ISSUE THREAD

**Issue by B-iggy** [adobe/brackets#10621]
Found nothing to this related.
When I press CTRL+F and searching something I want Brackets to remember my input (like in Sublime). Even when I'm clicking in the file around or press ESC after finding the word (hiding the search panel).
At the moment I have to retype my word.

Is this possible?

**Comment by redmunds** [comment]
@B-iggy Brackets pre-populates the Find field with the currently selected text, but it does not yet remember the previous value. This is in our backlog [here](https://trello.com/c/IzACddEv/344-s-find-recent-search-history) so add your vote! Closing this issue.
