### ISSUE TITLE
Touch Screen Usability Issues

### ISSUE THREAD

**Issue by chylex** [adobe/brackets#10630]
Since updating to Brackets 1.1 (1.1.0-15558), I've had problems with touch screen:

When I try open a file from the left panel, the screen dims for half a second and then the touch screen menu appears in the text area. Same with the buttons on the right. Moving the scrollbar works fine.

When tapping and moving the cursor, instead of selecting text nothing happens. Single tap opens the touch screen menu, which gets a bit annoying when trying to be precise and having to tap elsewhere to make it go away. Also the menu "hides" behind the top part of the window when tapping into Search input.

Tested without extensions; Win7 x64, touchscreen laptop. The touch controls used to work fine in Brackets 1.0. My assumption is that the touch screen menu introduced those bugs, but not entirely sure how to fix it. Any help is appreciated!

EDIT: Fixed a typo ("Single tap _opens_ the touch screen menu")

**Comment by JeffryBooher** [comment]
I can confirm this is broken on my Samsung Windows Slate as well.  This is definitely a regression but someone needs to confirm that Microsoft Surface is broken as well since CEF 2171 seemingly fixxed touch on Surface Pro Devices: #10075

**Comment by rp4rk** [comment]
Confirmed broken on Surface Pro 2, exact same problems as in original post.

**Comment by JeffryBooher** [comment]
Marking this as Needs Review since it's a recent regression.

**Comment by georgewhite5** [comment]
Can replicate on original Surface Pro. Tapping on anything in the right sidebar does nothing, but pressing every where else brings up virtual keyboard.

**Comment by fractalawareness** [comment]
I've created an extension fixes some of those touchscreen issues for myself and then decided to publish it, so everyone can use Brackets on their touchscreen devices:
https://github.com/fractalawareness/brackets-touch-me
It was tested on Windows 8.1 x64, if anybody have suggestions or issues - please report.
Hope it helps!

**Comment by criptych** [comment]
Also having this problem as of Brackets 1.4 (haven't tried earlier versions on this computer though).  If I'm not mistaken, the OSK popup is a long-standing "wontfix" problem with Chromium; the "dim screen and do nothing" response seems to be the real problem here.

@fractalawareness Thanks very much for writing that extension; it works perfectly for me. :+1:

**Comment by Icehawk78** [comment]
I can confirm that this is still an issue as of Brackets 1.5 on a Surface Book. Will try the referenced extension, but this seems like it should be natively supported.

**Comment by drozzy** [comment]
This is a problem on Windows 10 (using Acer R7). My brackets routinely crashes when I try to touch it...

**Comment by breeky5** [comment]
Smae problem here on windows 10 (Acer P3)

**Comment by marshmatter** [comment]
I'm having this issue on Windows 10 64-bit, Surface Pro 4. 

Touching anywhere opens the on screen keyboard, even with the typecover plugged in and not in tablet mode. The expected behaviour is to move the cursor on tap. 

I tried the Touch Me extension, but still having this usability issue.

**Comment by fractalawareness** [comment]
@marshmatter OK, I will try to fix this issue in the next version of the **brackets-touch-me** extension as soon as I have free time.

**Comment by fractalawareness** [comment]
I've recently downloaded a new version of Brackets and it seems like now it has a good touchscreen support, you don't need my extension anymore.

**Comment by chylex** [comment]
Closing the issue as the comment indicates that it's been fixed (I moved away from Brackets a long time ago, so I haven't checked it myself).
