### ISSUE TITLE
'chrome=1' can be removed from all the Getting Started pages

### ISSUE THREAD

**Issue by coliff** [adobe/brackets#10632]
The Getting Started pages have the following:
meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"

'chrome=1' was for Chrome Frame which has long since been discontinued and is no longer available, and was only ever needed for old versions of Internet Explorer (for Windows XP) which is also no longer supported by Brackets.

**Comment by redmunds** [comment]
@coliff Do you know which version of Chrome/Chromium discontinued this support? Linux is still using a back-level version of CEF so we need to be sure this will work on all platforms before making this change. Thanks.

**Comment by coliff** [comment]
Hi Randy - it was never actually used in Chrome/Chromum itself. It was intended to use for websites so users with IE6/IE7 could install a ChromeFrame plugin for their old browsers which would render the page using Chrome/Webkit.
https://developers.google.com/chrome/chrome-frame/

**Comment by peterflynn** [comment]
Marking as a Starter Bug -- if someone can submit a pull request removing `chrome=1` from all the copies of the Getting Started page, that would be great!

**Comment by Denisov21** [comment]
Working in progress...

**Comment by tinyx** [comment]
So all index.html in samples folder, change content="IE=edge,chrome=1" to content="IE=edge"
Someone confirm it and I'll be right working on it :)

**Comment by tinyx** [comment]
NVM, looks Denisov21 already done the job

**Comment by Denisov21** [comment]
@tinyx, I confirm! I did the PR to solve the small problem! 
@peterflynn The job is completed!!

**Comment by courtnic** [comment]
Sooooo, is this bug consider closed? Or is there work that still needs to be done?

**Comment by coliff** [comment]
@courtnic It looks like @Denisov21 opened a Pull Request but it hasn't been accepted yet.

**Comment by nethip** [comment]
Fixed now via #10694
