### ISSUE TITLE
Brackets on WIN7 always starts asking for "Git Projects: First Run" base path

### ISSUE THREAD

**Issue by 3und60** [adobe/brackets#10636]
Hi there,

after I installed the Git Projects extension for Brackets I get a window asking for a base path at its first run. Since I was just curious about the extension I was not thinking deeply about the usage. Anyways. Every attempt to put in any path fails, I mean the GUI does not respond anymore. I uninstalled it and re-installed it, no change. Still the software ( extension ) wants to have a path at startup, without it it seems I can not use the software. Can somebody please help me out? Can I start Brackets without extensions? Or can I remove this extension manually to solve the issue.

THANKS!

Cheers Thomas

**Comment by peterflynn** [comment]
If the whole Brackets UI is blocked by the dialog, you can still use these instructions to manually uninstall the extension: https://github.com/adobe/brackets/wiki/Troubleshooting#disabling-extensions-individually

Please also file a bug with the extension's author, here: https://github.com/brad-jones/git-projects/issues

**Comment by peterflynn** [comment]
Closing since I think there's no core Brackets change needed here.
