### ISSUE TITLE
CSS autocomplete in html files

### ISSUE THREAD

**Issue by MartinJBates** [adobe/brackets#10649]
In brackets on a html page, I have referenced a couple of css files, for example:

`<link href="/bower_components/uikit/css/uikit.css" rel="stylesheet" />`

When I type `<div class="uk-` and do a control space no autocomplete appears showing the list of classes available. When I type "uk-" I would expect it to show a list of all available classes matching the text I have typed in from the referenced css files or project css files like other IDEs. 

Is this feature implemented?

**Comment by redmunds** [comment]
No, this is not in core Brackets. There's an extension called Brackets CSS Class Code Hint that implements that.

**Comment by MartinJBates** [comment]
I've installed this extension, but when I open `<div class="uk` with ctrl+space no autocomplete or anything appears. Am I doing something wrong?

**Comment by redmunds** [comment]
@MartinJBates I am not familiar with that stylesheet, so that should only show classes that start with "uk".

Also, that extension may not detect partial tags or attribute values. What happens if you have `<div class="">`, put cursor between quotes then press ctrl+space or start typing?

**Comment by MartinJBates** [comment]
I don't get any autocomplete with either an empty `class=""` or if I start typing a known class name that's within a css file. My css stylesheet lives in the following path `app/css` not in the root of the project so I don't know if that makes a difference or not?

**Comment by redmunds** [comment]
In general with Brackets, you use *File > Open Folder...* to choose the root folder for your "project", and feature that list selectors, etc. process all files in that folder, so make sure the stylesheet is inside your "project" folder.

I'm not sure how that extension is doing it, so you'll need to look at the code, or open an issue on the repo for that extension: https://github.com/wn9FHW2nhO/Brackets-CSS-Class-Code-hint

**Comment by peterflynn** [comment]
Also, if you'd like this to be a built-in feature supported by the core Brackets team, please upvote this item on our feature backlog: [HTML Code Hinting: CSS Class and ID used in CSS](https://trello.com/c/doY5Dbpb/529-3-html-code-hinting-css-class-and-id-used-in-css).

**Comment by MartinJBates** [comment]
This works when:
 - the css is inline in `<style>` tags or if the `.css` file is in the root folder

It needs to support looking for `.css` files within subfolders. I will upvote this as it will be a useful feature to have as standard.
