### ISSUE TITLE
Node.js vs io.js detection

### ISSUE THREAD

**Issue by jasonsanjose** [adobe/brackets#10658]
Now that io.js has forked, modules like node-sass are relying on the name of the executable to detect node vs. io.js. 

Examples:

https://github.com/sass/node-sass/blob/master/lib/extensions.js#L9 resolves to `Brackets-node`

```
function getRuntimeInfo() {
  var execPath = fs.realpathSync(process.execPath); // resolve symbolic link

  var runtime = execPath
               .split(/[\\/]+/).pop()
               .split('.').shift();

  runtime = runtime === 'nodejs' ? 'node' : runtime;

  return {
    name: runtime,
    execPath: execPath
  };
}
```

Another example at stackexchange uses the same technique http://stackoverflow.com/questions/28259154/is-there-a-reliable-way-of-detecting-whether-io-js-or-node-js-is-running?rq=1.

Part of the responsibility should be on packages to do more robust detection. However, my question is, is there still a compelling reason to name our binary `Brackets-node`?

**Comment by jasonsanjose** [comment]
Also, it's worth noting that node-sass is fixing their approach in a future release https://github.com/sass/node-sass/issues/694.

**Comment by peterflynn** [comment]
I think @busykai was looking into trying to rename the binary back to just plain `node`.  IIRC there was some problem with our native extension for Windows file watching if we didn't rename it...?

**Comment by busykai** [comment]
@peterflynn, I was going the other way, actually. :) I wanted to rename Windows `node.exe` to `Brackets-node.exe`.

@jasonsanjose, I believe the major reason to have it as `Brackets-node` is to be able to distinguish it from other node processes which could be running on the system (for example, if one wanted to debug or restart it).

**Comment by petetnt** [comment]
Not valid issue anymore, closing
