### ISSUE TITLE
gitignore file created after Cache dump

### ISSUE THREAD

**Issue by cfristoe** [adobe/brackets#10650]
Sorry to bother, but this issue seemed weird. The git hub extension froze up so followed the guidelines to clear the cache and reinstall, which worked. Brackets now works, however, when I open  iTerm or Terminal I'm getting the following message: 
 <pre><code>calebfristoe at Calebs-iMac in ~/Desktop on master* </pre></code>

When I <pre><code>$git branch -v</pre></code> I get the following message: 

 <pre><code>  list   4b10dd6 .gitignore created by brackets-git extension
* master 4b10dd6 .gitignore created by brackets-git extension</pre></code>

Not really sure how to remedy this. Any help would be great. Thanks.

**Comment by MarcelGerber** [comment]
This is an issue with the brackets-git extension, so you're probably better off filing that issue on [the brackets-git repo](https://github.com/zaggino/brackets-git).

cc @zaggino

**Comment by cfristoe** [comment]
Sure thing. Thanks @MarcelGerber

**Comment by peterflynn** [comment]
Closing since this is not a core Brackets bug
