### ISSUE TITLE
Quotes don't auto-close anymore

### ISSUE THREAD

**Issue by aniforprez** [adobe/brackets#10654]
I'm not sure when this issue started because I skipped a bunch of versions but when I recently installed 1.1, quotes would not auto-close. Parentheses, braces and square brackets all close just fine with the "Auto Close Braces" setting enabled but single quotes and double quotes don't.

I've reloaded with and without extensions with no resolution. I have a standard ANSI US-style keyboard layout.

**Comment by peterflynn** [comment]
What type of file are you typing in?  Auto closing quotes only operates in cases where you're opening a string literal, so in files where CodeMirror doesn't recognize the syntax it won't happen.  Ditto for typing a `"` inside a comment, etc.

**Comment by aniforprez** [comment]
It doesn't seem to happen in JS, JSON, CSS or HTML files as far as I've tested. The syntax has been detected properly and is displayed below.

**Comment by peterflynn** [comment]
@aniforprez It works fine for me in all those filetypes.  Can you provide a sample code snippet (maybe post a Gist or JSFiddle) that shows the problem?  Please specify exactly where you're putting the cursor when you type `"` so we can reproduce your steps exactly.

**Comment by aniforprez** [comment]
I'm not sure how to put something like this in a JSFiddle.

An example would be if I'm making an img element, `<img src= >` putting the cursor after the "=" sign and adding a " doesn't close it automatically.

More simply, they don't close ANYWHERE in the document. Be it inside or outside comments.

**Comment by patrickfatrick** [comment]
@aniforprez Do you have https://github.com/caseyg1204/brackets-quoter installed? I'm pretty sure the bug is in that extension. Same thing was happening for me but uninstalling that extension fixed it.

**Comment by peterflynn** [comment]
@aniforprez You said you already tested using _Debug > Reload Without Extensions_, right?

Can you create a snippet at https://gist.github.com/ and say exactly where you're putting the cursor?  Or barring that, can you provide precise steps using the default Getting Started project that comes with Brackets?  For example:

1. Open the index.html in Getting Started
2. Put cursor at the end of line 14 (after the `</h2>`)
3. Press Enter
4. Type `<img src="` longhand (without accepting any code hint suggestions)

Result: for me, it automatically enters `<img src=""`, with the cursor between the `""`.  Does something different happen for you?

**Comment by aniforprez** [comment]
@patrickfatrick was right on the money. It's apparently an issue with the quoter plugin. Thanks for creating an issue in the extension repo too!

@peterflynn Apparently I didn't notice that was the issue because _Debug -> Reload Without Extensions_ doesn't reload without extensions. This seems to be a more concerning issue than what I had... I'm closing this issue for now.
