### ISSUE TITLE
Installation fails with scripterror

### ISSUE THREAD

**Issue by cgarveyie** [adobe/brackets#10656]
Installation fails:

`Running "jasmine:src" (jasmine) task
Testing jasmine specs via phantom
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.grunt\grunt-contrib-jasmine\require.js:31
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.grunt\grunt-contrib-jasmine\require.js:14 z
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.grunt\grunt-contrib-jasmine\require.js:31
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.grunt\grunt-contrib-jasmine\require.js:31
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.grunt\grunt-contrib-jasmine\require.js:14 z
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.grunt\grunt-contrib-jasmine\require.js:31
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.gru
nt\grunt-contrib-jasmine\require.js:31
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.gru
nt\grunt-contrib-jasmine\require.js:14 z
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.grunt\grunt-contrib-jasmine\require.js:31
>> Error: Load timeout for modules: text!config.json_unnormalized2,text!language
/languages.json_unnormalized3,i18n!nls/strings_unnormalized4,i18n!nls/urls_unnor
malized5,i18n!nls/strings-app_unnormalized6
>> http://requirejs.org/docs/errors.html#timeout at
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.grunt\grunt-contrib-jasmine\require.js:31
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.grunt\grunt-contrib-jasmine\require.js:14 z
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.grunt\grunt-contrib-jasmine\require.js:16 w
>> ..\..\..\..\..\C:\Users\dev1\Downloads\brackets-master\brackets-master\.grunt\grunt-contrib-jasmine\require.js:16

Warning: PhantomJS timed out, possibly due to an unfinished async spec. Use --force to continue.

Aborted due to warnings.`

**Comment by peterflynn** [comment]
@cgarveyie Just to clarify what you're trying to accomplish... you don't need to run _**any**_ Grunt tasks to use Brackets, even when running from source.  To "install" Brackets, just download a build from http://brackets.io.  If you want to run directly from source instead, follow our [How to Hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets#quick-start) instructions.

**Comment by peterflynn** [comment]
The Grunt task you're running above is intended for a build machine (Travis, in particular) to run automated tests.  I'm not sure whether it is supposed to run successfully outside of the Travis environment or not.  @jasonsanjose might know more.

**Comment by yeahnoob** [comment]
@cgarveyie Before using `grunt build`, try to run `git submodule update --init`.

**Comment by nethip** [comment]
@cgarveyie Could you try what @peterflynn had suggested and update us if it has worked.

**Comment by peterflynn** [comment]
Closing since there's been no response since this was filed

**Comment by peterflynn** [comment]
Note that another person posted here with similar confusion recently: https://groups.google.com/forum/#!topic/brackets-dev/dNaAWnXUPMQ.  I wonder if we should have the default Grunt task just print a message pointing people to the wiki setup guide, since so many people instinctively see a Gruntfile and assume running it is necessary?

**Comment by rodrigob** [comment]
I got the same issue (after downloading bracket from source code). 
I think the problem is that README.md does not provide any build instructions (that I could notice).

**Comment by Panzerfather** [comment]
This problem only occurs when trying to build brackets from source release (tested with 1.3). It doesn't exists when building it from a cloned release branch. So either its fixed or theres a problem with fetching the right dependencies via npm.

@rodrigob:
There is a build instruction in the wiki for [Brackets](https://github.com/adobe/brackets/wiki/Building-Brackets-Releases)

**Comment by ThiagoFontes** [comment]
Had the same problem, cloned from git and used the commmand @yeahnoob provided, now it worked! Thanks!
