### ISSUE TITLE
D'oh! How do I hide the Console?

### ISSUE THREAD

**Issue by STaRDoGG** [adobe/brackets#10655]
I've been tinkering with Brackets on and off to see if I want to replace my usual editor with it, and somewhere along the line I think I remember selecting to show the console, but now for the life of me I can't find how to hide it again? I installed the Console+ extension and thought I'd see if I like it better, but now they both show?

![Screenshot of console I want hidden](https://i.imgur.com/CLYFq17.png)

**Comment by TadorHead** [comment]
Have you tried to double click to the console + icon?

**Comment by peterflynn** [comment]
@STaRDoGG Please file extension bugs/questions in the repo for that extension -- this issue list is just for core Brackets issues.

In general though, if you've installed two extensions that do similar things and you've decided you only want one of them, you can just use Extension Manager to uninstall the other one.

**Comment by STaRDoGG** [comment]
@peterflynn Ahhh, sorry. For some reason I was thinking that was part of Brackets itself. Turned out I also had the "Console tools" extension installed as well, which is what that was. I'm overworked! ;)
