### ISSUE TITLE
MATLAB bundle

### ISSUE THREAD

**Issue by ksphil** [adobe/brackets#10661]
This is a request for the developer of Brackets. 
Could you add MATLAB bundle? 
Hope it doesn't bring much burden.

**Comment by peterflynn** [comment]
@ksphil Out of the box, Brackets is focused more specifically on client-side web languages.  However, Brackets is highly extensible and this is definitely something [an extension could add](https://github.com/adobe/brackets/wiki/Language-Support#defining-a-new-language).  It looks like the CodeMirror text editor widget we use [already supports the Octave/MATLAB language](http://codemirror.net/mode/octave/index.html), so it would be easy to add syntax highlighting.  Deeper support, such as code hints, would require greater effort.

**Comment by joeyfreeman** [comment]
I created an extension to add Octave/MATLAB syntax highlighting (also available in the Extension Manager):
https://github.com/joeyfreeman/brackets-octave-syntax

**Comment by ksphil** [comment]
Great! thank you.

**Comment by peterflynn** [comment]
Closing, and removing tag since an extension now exists
