### ISSUE TITLE
Infinite error loop 

### ISSUE THREAD

**Issue by mnttnm** [adobe/brackets#10667]
'Console Plus' logs are showing same error again and again. Not able to find any option to stop this without uninstalling the console plus. The pic below is showing that console has reported the same error 
2149 times and yet doing the same thing again and again.

![screen shot 2015-03-01 at 3 15 40 pm](https://cloud.githubusercontent.com/assets/8184277/6430210/f592aa10-c025-11e4-84a9-81149cd9efaa.png)

os version os x 10.9.1
bracket version Release 1.1 build 1.1.0-15558 (release ea908cae5)

**Comment by prafulVaishnav** [comment]
Hii.. Can you provide some details : 1>  Is there any workflow that is causing this error ? If yes, please tell. 2> Open Developer Tool from Brackets (Debug -> Show Developer Tools ) and check whether these errors are also there. 3> Reload Brackets without Extensions (Debug -> Reload Without Extensions) and repeat the workflow and check whether these errors are in Developer Tools console.

**Comment by abose** [comment]
The file causing exception belongs to extract which is a Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . 
Console plus extension works when tested.
Closing.
