### ISSUE TITLE
[ Live Preview Multibrowser] Live Development Session has Ended ("Live Preview: Connecting...")

### ISSUE THREAD

**Issue by Blossomy** [adobe/brackets#10677]
Runtime Environment:
Windows 8.1 64bit
Chrome Stable 40.0.2214.115 m (64-bit) ←Default browser
Firefox 36.0
Brackets Release 1.2 build 1.2.0-15697 (release 8f82e2a97) 
build timestamp: Sun Feb 22 2015 22:34:56 GMT-0800

Steps:
1. Launch Brackets
2. Enable Experimental Live Preview
3. Click the Live Preview icon on the top right sidebar
4. Chrome auto open http://127.0.0.1:49923/index.html
5. Copy and paste the URL from Chrome  into Firefox 

Result:
At step 4 and 5. 
"Live Development Session has Ended" message show on the top. 
Brackets show "Live Preview: Connecting..."
Chrome:
![Chrome](https://cloud.githubusercontent.com/assets/5909257/6462037/8bfef074-c1e0-11e4-90e6-b70cdda3d5e0.png)
Firefox:
![Firefox](https://cloud.githubusercontent.com/assets/5909257/6462047/9dea32f8-c1e0-11e4-891f-f2fbe275333c.png)
Brackets:
![Brackets](https://cloud.githubusercontent.com/assets/5909257/6462055/ac6fb6ae-c1e0-11e4-8795-cc92c7c07bdf.png)

Steps:
1. Un Enable Experimental Live Preview
2. Press F5 reload Brackets
3. Click the Live Preview icon on the top right sidebar again
4. Chrome auto open new window
Result:
At step 4. The current LiveDevelopment architecture still work

**Comment by nethip** [comment]
@Blossomy Are you using any proxy servers? Also it would be helpful if you can check and tell us if you are seeing any errors in the developer tools console. To access developer tools choose *Debug->Developer tools*. Upon opening the developer tools window, click on the console to see console log messages.

**Comment by Blossomy** [comment]
@nethip I'm not use any proxy servers.

All console log (Without Extensions ):
 /LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 
 NodeSocketTransport - send,,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":1}

**Comment by nethip** [comment]
@Blossomy Thanks for posting the response. Are you using a firewall? Also you could you tell us if you are using any local webservers, like WAMP e.t.c?

From the log it looks like the there is a problem in communication between Brackets and node module which is responsible for Live Preview. 
@Blossomy Thanks for posting the response. Are you using a firewall? Also you could you tell us if you are using any local webservers, like WAMP e.t.c?

From the log it looks like the there is a problem in communication between Brackets and node module which is responsible for Live Preview.

**Comment by Blossomy** [comment]
@nethip 
When you mention the local server once again, reminded me that I also installed Visual Studio Community 2013, Android Studio. Visual Studio installed IIS to me, 
I did not notice that before, because I did not use vs development Website. So I go to download a virtual machine frome https://www.modern.ie. Then I install the firefox and Brackets to test Live Preview Multibrowser, it can work. It's my bad. Thank you for your answer.

**Comment by StillFeb** [comment]
I think I was wrong.
The real cause is  [shadowsocks](https://github.com/shadowsocks/shadowsocks-windows/tree/2.5.6) or some similar proxy software.
When i start up shadowsocks, whether I enable proxy or not, it all will lead Live Preview connection  failure.
If I want to use live preview. Only I can do is exit shadowsocks then press F5 reload Brackets and Click the Live Preview icon again.
It seems they have a conflict.
Unfortunately,  shadowsocks's author stop to maintain this software [because of the Chinese government](https://en.greatfire.org/blog/2015/aug/chinese-developers-forced-delete-softwares-police) 
I am not sure know if you team can find and solve the problem? 
It will be beneficial to chinese user like me.

**Comment by zd9027** [comment]
yes, i meet this problem also,when i quit shadowsocks ,live preview displays well.

**Comment by netalex** [comment]
Hello!

 

You have a new message, please read <http://conexxiontech.com/twist.php?el8i>

 

netalex@tiscali.it
