### ISSUE TITLE
Line wrap when dragging long filename in working set

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10675]
1. Open a file whose name is wider than the sidebar
2. Add file to working set
3. Drag within working set to rearrange

Result: wraps onto multiple lines (with only the first line fully visible, the rest clipped)

**Comment by MarcelGerber** [comment]
Weird, I do not see this issue on Windows.

**Comment by peterflynn** [comment]
Repros for me on either platform.  Presumably the filename needs to have spaces (or maybe hyphens) in the name before the browser is willing to line-wrap it... did you test with a filename like that?

**Comment by MarcelGerber** [comment]
Ah, that's the point. Looking for a fix...

**Comment by peterflynn** [comment]
Closing as fixed -- thanks @MarcelGerber!
