### ISSUE TITLE
Emmet does not self-close tags when doctype is set to XHTML Transitional

### ISSUE THREAD

**Issue by skube** [adobe/brackets#10678]
Does anyone else have this issue? Setting the doctype to:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
```

Then using Emmet to expand a self-closing tag such as an image tag, results in:

```html
<img src="" alt="">
```

Instead of what I get in Sublime Text:
```html
<img src="" alt="" />
```

I'm not exactly sure if it's an Emmet issue or Brackets (or perhaps even something I've set inadvertently).

Using Brackets (v 8f82e2a97) on OS X with Emmet installed.

**Comment by skube** [comment]
This also occurs on Win7 version of Brackets too. Seems like a fundamental thing to be broken which makes me think it's something on my end.

**Comment by peterflynn** [comment]
Please file this bug with the Emmet extension authors: https://github.com/emmetio/brackets-emmet.  It's unlikely to be related to Brackets core.
