### ISSUE TITLE
Preferred linting preference

### ISSUE THREAD

**Issue by cfjedimaster** [adobe/brackets#10682]
I'm only 50% or so sure I'm right about this, so please forgive me if not.

A while ago I told Brackets to use my preferred linter for JS:

    "linting.prefer": [
        "JSHint"
    ],
    "linting.usePreferredOnly": true,

I did this so I wouldn't have two linters for JS files. However, it seems that doing this disables linting completely outside of JSHint.

So the question is - how do I tell Brackets to only use JSHint for JS, but for anything else use what is there? Do I need to specify every single linter just to not have two show up for one file type?

**Comment by redmunds** [comment]
@cfjedimaster You can specify those prefs for JS only like this:

```json
    "language": {
        "javascript": {
            "linting.prefer": [
                "JSHint"
            ],
            "linting.usePreferredOnly": true,
        }
    },
```

**Comment by cfjedimaster** [comment]
Ah, ok, thanks.

On Tue, Mar 3, 2015 at 2:20 PM, Randy Edmunds <notifications@github.com>
wrote:

> @cfjedimaster <https://github.com/cfjedimaster> You can specify those
> prefs for JS only like this:
>
>     "language": {
>         "javascript": {
>             "linting.prefer": [
>                 "JSHint"
>             ],
>             "linting.usePreferredOnly": true,
>         }
>     },
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/10682#issuecomment-77026148>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
