### ISSUE TITLE
Failing to see disk changes (OSX, 1.2 build 1.2.0-15697 (release 8f82e2a97))

### ISSUE THREAD

**Issue by andyburke** [adobe/brackets#10696]
Hi, I updated to the latest brackets and now my editor doesn't seem to be aware of changes on disk:

1) Changing a file on disk will not reload the file in the editor
2) Creating a folder on disk, then doing Open Folder... will not see the folder in the file browser

Steps to reproduce:

1) Open an existing file in Brackets
2) Modify file on disk
3) Observe that file is *not* reloaded inside Brackets

1) Open Brackets
2) Create a new folder on disk
3) Select File->Open Folder...
4) Observe that the new folder cannot be found in the file browser

**Comment by abose** [comment]
@andyburke Which version of OSX are you on? Are you still facing this issue? 
Works in my machine™

**Comment by andyburke** [comment]
It seems to have abated. This was actually only happening under a Dropbox controlled folder. Maybe a new version of Dropbox came out that fixed this. Closing.
