### ISSUE TITLE
Color preview doesn't work when value contains a zero padded number

### ISSUE THREAD

**Issue by bounasserabdelouahab** [adobe/brackets#10699]
When i hover over `rgb(255, 129, 159)` a box appears and displays the color, but when i hover over something like `rgb(255, 176, 008)` it does not show up, in the other hand if i change `008` to just `8` it works.

**Comment by le717** [comment]
I've got a fix, PR will be up momentarily.

**Comment by le717** [comment]
I have a fix up at #10705.
