### ISSUE TITLE
Window title bar on fullscreen Mac should be more readable

### ISSUE THREAD

**Issue by chadwtkns** [adobe/brackets#10701]
When going into fullscreen on my mac the text at the top of Brackets that shows what directory I am in and the file that I am editing is black. This is making it hard to read this information and it only happens when I go into fullscreen mode. I have turned off extensions and it still shows up black. I imagine that this text should be white to have a better reading contrast. 

Technical Info:
MacBook Pro (Mid 2014) 
Yosemite 10.10.2
Brackets 1.2 (though I think I remember seeing this in Brackets 1.1 as well)

![screen shot 2015-03-05 at 1 40 05 pm](https://cloud.githubusercontent.com/assets/5611546/6514088/0131b3d8-c33d-11e4-867e-4965efb8d893.png)

**Comment by peterflynn** [comment]
@chadwtkns Are you building Brackets yourself?  This sounds like #10446

**Comment by chadwtkns** [comment]
No I'm not building Brackets myself. I am just using the .dmg file to install Brackets. I looked at the issue that you linked to, mine may be a duplicate but the difference is that my is only like that when I click the green fullscreen button and hover over top. When I'm not in fullscreen mode the text appears white just like it should. Hopefully this makes sense. : )
