### ISSUE TITLE
Hi DPI support function doesn't release DC

### ISSUE THREAD

**Issue by JeffryBooher** [adobe/brackets#10707]
The function below doesn't release the drawing context it uses to get the Device Capabilities which could lead to instability -- Windows will allocate memory for new ones (unless you change the CEF Window class to use a shared DC). 

Even though this is only called once per Window, each new Debugger Window, Popup window (PSDLens Cloud Login), or using `Debug > New Brackets Window` will create a new window and eventually Brackets will run out of handles.

```C
UINT cef_window::GetDPIScalingX() const
{
    HDC dc = GetDC();
    float lpx = dc ? GetDeviceCaps(dc,LOGPIXELSX):DEFAULT_WINDOWS_DPI ;
    //scale factor as it would look in a default(96dpi) screen. the default will be always 96 logical DPI when scaling is applied in windows.
    //see. https://msdn.microsoft.com/en-us/library/ms701681(v=vs.85).aspx 
    return (lpx/DEFAULT_WINDOWS_DPI)*100; 
}
```

**Comment by peterflynn** [comment]
@JeffryBooher Good catch!

@abose Can you look into this for 1.3?  (Looks like this code is yours)

Lowering priority to Medium though, since opening new windows is a fairly uncommon workflow in Brackets currently, making the impact of this likely to be rare in practice.

**Comment by abose** [comment]
Pull request submitted.
https://github.com/adobe/brackets-shell/pull/508

**Comment by prafulVaishnav** [comment]
PR has been merged to shell.
