### ISSUE TITLE
New update reportedly available when manually checked and running from source

### ISSUE THREAD

**Issue by le717** [adobe/brackets#10706]
Running off master at c4e83a630, Windows 7 x64.

Steps to repo:
1. Help > Check for Updates

Expected results: dialog saying no update available.
Actual results: Reports the v1.2 update is available, adds update icon. Goes away upon app reload.

This only happens when manually checking for updates, the auto-check does not trigger this. Since I'm running off v1.3 source, I did not expect to be told the v1.2 update was available.

This is happening because the condition at [line 376](https://github.com/adobe/brackets/blob/c4e83a63064e52567c0be07be399ef067b2823d9/src/utils/UpdateNotification.js#L376) unconditionally checks if `allUpdates` is true without checking if this is a dev build or not. A simple edit to make the condition read `if (allUpdates  &&  _buildNumber !== 0) {` fixes it and shows the up-to-date dialog.

**Comment by le717** [comment]
It seems this behavior has been present since the update system was introduced in #1386, but that fix is causing three tests to fail. That's fine, because it was the wrong fix. The _correct_ fix is `if (allUpdates  && _buildNumber !== 0) {`. This triggers the no update dialog only on dev build _and_ keeps the unit tests running. :)

**Comment by peterflynn** [comment]
I believe it's by design that the dev build always shows all available updates.  If you're in a dev build, Check for Updates isn't able to give a truly correct result either way.  Is it any more correct for clicking it to do nothing, even when your dev build might be behind the latest stable release?

**Comment by MarcelGerber** [comment]
I vote for leaving it as it is. At the very least, it's great for seeing and reviewing the Brackets update notifications (and translations) in context.

**Comment by le717** [comment]
Thinking it over, yea, it should be left as-is. It just _feels_ a bit weird, but if it was by design and is useful for some things, then it shouldn't be changed. 

Closing.
