### ISSUE TITLE
Account already exists

### ISSUE THREAD

**Issue by miskit** [adobe/brackets#10711]
Version: 1.2
OS: Windows 8.1

I tried to install the latest version of Brackets on my desktop and keep getting the error message at the point in which it begins to install."Specified account already exists". What does this mean and why won't it install?

**Comment by peterflynn** [comment]
From what I can tell, this is error generally means the Windows Installer service is having problems on your computer.  Microsoft recommends running this utility: http://support.microsoft.com/mats/program_install_and_uninstall/en

If that doesn't help, please follow these steps on the command line to generate an installer log file:

1. `cd` to the folder containing the installer
2. Run `msiexec /i "Brackets.Release.1.2.msi" /l*v .\brackets-install.log`
3. Upload the generated log file to something like [Gist](https://gist.github.com/), pastebin, etc. and post the link to it here

**Comment by miskit** [comment]
Thank you so much. This solved it for me.
