### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by youssefdetovernickr** [adobe/brackets#10712]
It would be great if there's a better autocompletion tool (like PHPStorm) as the current one isn't that good (except for JS files it's a bit better)  

It should read comments of functions and use that to its advantage.

**Comment by peterflynn** [comment]
@youssefdetovernickr Are you talking about code hints in PHP files specifically?  Check out the extensions PHP SmartHints and PHP Syntax Hint.

The core Brackets download is focused on front-end web languages, so we probably won't add PHP code hints to core.  But if you have suggested improvements for code hints in JS, HTML, CSS/LESS/SCSS, etc., please let us know and we can reopen to discuss those ideas.

**Comment by youssefdetovernickr** [comment]
Well I'm talking about PHP and JS here. The js autocompletion doesn't care about the documentation about your functions. It would be great if Brackets could read, for example, JSDoc style of documentation, and use that to improve its autocompletion. Then color these autocompletion by function, variable, etc. 

Of course this could also apply to PHP but I'd rather see this for JS first.

**Comment by peterflynn** [comment]
The JS code hints in Brackets are already aware of type annotations embedded in JSDoc.  For example:

![code hints 1](https://cloud.githubusercontent.com/assets/1197510/6538094/5e13956e-c412-11e4-8d63-88ba19835b32.png)

If that's not working for you, please post a code snippet that shows the problem in isolation.

In terms of color-coding the hints or adding icons, I'd suggest starting a conversation on [brackets-dev](https://groups.google.com/forum/#!forum/brackets-dev) with some specific design proposals, or a solid description of the use case you want to improve.  Brackets definitely aims for a cleaner look than the screenshot linked from your post, but that doesn't mean there's not a happy medium to be found...

**Comment by youssefdetovernickr** [comment]
Oops, I just checked and you're right. However I now see what I really mean: code hinting of JavaScript code in a <script> tag doesn't work in a HTML document.

**Comment by youssefdetovernickr** [comment]
By the way could you tell to me what the code hints actually read of the JSDoc?

**Comment by peterflynn** [comment]
Code hints work fine for me in a script tag.  Can you post an example of when it's not working for you?

The code hints parse any type annotations found inside JSDoc comments, like the example I showed above. A bit more detail here: http://ternjs.net/doc/manual.html#plugin_doc_comment

**Comment by youssefdetovernickr** [comment]
I don't have the same results.. Picture as example:

http://i.imgur.com/G8pSpgW.png

Also as far as I know, the autocompletion doesn't actually read the description which you supplied by JSDoc, is that correct?

**Comment by youssefdetovernickr** [comment]
@peterflynn
