### ISSUE TITLE
Find in Files results don't update to reflect external changes unless file is open

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10717]
1. Open the Getting Started project
2. Be careful not to open the main.css file
3. Find in Files and search for "h2"
4. Use a different text editor to open main.css, delete the two rules referencing "h2," and save the file

Result: Find in Files panel still lists both results from main.css

Same thing happens if you edit it to add new results.

But if you create, delete, or rename a file, Find in Files _does_ update correctly -- even if the file isn't open.

Happens at least as far back as 0.43, so this is not a new bug.

**Comment by peterflynn** [comment]
The FileSystem change event has a lot of complex edge cases, and `FindInFiles._fileSystemChangeHandler()` isn't handling one of them -- when `entry` is a Directory but `added`/`removed` are non-null empty arrays, it means _any_ immediate child may have changed.  The current code ignores such change events completely.

I think that type of change event only/mainly happens on Mac.

**Comment by peterflynn** [comment]
Would be great to add a unit test for this too, but: [sigh...](https://github.com/adobe/brackets/blob/release-1.2/test/spec/FindInFiles-test.js#L979-L985)

**Comment by jburtondev** [comment]
Hi, i'm new to the Brackets project and would like to work on this issue. Do I have the go ahead to get started?

**Comment by abose** [comment]
Hi @jburtondev Thanks for helping us out. 
You can get started with issues labeled `starter bugs`. 
Once you have a fix on this/ any other issues, please sign the brackets [CLA](http://dev.brackets.io/brackets-contributor-license-agreement.html) and raise a pull request :+1: 

Also join the [brackets-dev](https://groups.google.com/forum/#!forum/brackets-dev) groups to be update with the community.

**Comment by jburtondev** [comment]
@abose Sure great. Thanks for your message.

**Comment by tallandroid** [comment]
Is there an update on the issue ? If not , I would like to pick it up.

**Comment by nethip** [comment]
@tallandroid Sure! We really appreciate it. Let us know if you require any help on this.

**Comment by tallandroid** [comment]
So , I tried to replicate the bug and here is what i did : 
1) Opened Getting Started project in Brackets. 
2) Didn't open main.css, so it didn't come under my Working Files tab. From my understanding of the code, its not one of the documents under document manager but is still a part of file system.
3) Did a search for h2 and results showed up for main.css.
4) Changed the file in a different editor as directed and saved it back.
 
From my expectation , the breakpoint on filesystemChangeHandler should have been hit, but it didn't seem to be the case. Neither did file change update reflect to the file in editor until i refreshed Brackets. Can someone confirm what is the desired behavior expected ?

**Comment by cynicaldevil** [comment]
It seems this bug is fixed now. I went through the steps and the Find in Files updated correctly for me.

**Comment by zaggino** [comment]
Fixed in https://github.com/adobe/brackets/pull/11602
