### ISSUE TITLE
Problems installing brackets for Win

### ISSUE THREAD

**Issue by mareSLO** [adobe/brackets#10724]
Hi there

When i try to install brackets, this happens. If i click cancel, it gives me error 2755. Works fine on my laptop. Cant find a solution. Please help.
![untitled](https://cloud.githubusercontent.com/assets/11389588/6554832/0c2aa184-c660-11e4-8121-033599fed510.jpg)

**Comment by redmunds** [comment]
Please specify which version of Windows you are using. What's the location of the installer and installation folders (local drive? network drive? removable drive?)

**Comment by peterflynn** [comment]
Can you check whether you have any of the issues listed here? https://support.microsoft.com/kb/834549?wa=wsignin1.0

Also, [this page](http://knowledge.autodesk.com/support/inventor-products/troubleshooting/caas/sfdcarticles/sfdcarticles/Error-The-system-cannot-open-the-device-or-file-specified.html) says having Trend Micro Anti-Virus can cause this problem.  If you have that app installed, try temporarily disabling it.

If none of those help, please follow these steps on the command line to generate an installer log file:

1. `cd` to the folder containing the installer
2. Run `msiexec /i "Brackets.Release.1.2.msi" /l*v .\brackets-install.log`
3. Upload the generated log file to something like [Gist](https://gist.github.com/), pastebin, etc. and post the link to it here

**Comment by mareSLO** [comment]
I`m using win 8.1, location of the installer is on my D: drive. I left the installation folder on default, so c:/program files, and no i dont have trend anti-virus. Will try to generate an installer log...

**Comment by mareSLO** [comment]
Just solved the problem. I just had to move the setup file from d to my c partition. My C partition is actually an SSD, while my D is a regular drive. I dont know why trying to install from D caused problems but it did. I`m just glad its working now.

**Comment by peterflynn** [comment]
Great, glad to hear you got it to work!
