### ISSUE TITLE
Extensions won't update

### ISSUE THREAD

**Issue by nickfmc** [adobe/brackets#10720]
the https://brackets-registry.aboutweb.com/ extension updloader has been offline for 2 days now, I just get BAD REQUEST when trying to upload.  Also http://konstantinkobs.github.io/BracketsExtensionStats/ is not recording any downloads for the same time.  The updated plugin list on the upload page has not budged for 2 days so I'm sure it's not just me having the issue.

**Comment by le717** [comment]
BracketsExtensionStats is not an official Brackets component. The only official way to upload extensions/extension registry is at https://brackets-registry.aboutweb.com. You will need to file this issue [here](https://github.com/konstantinkobs/BracketsExtensionStats) .

**Comment by nickfmc** [comment]
No my issue is that I can not update my extension! and judging that no extension has been added or updated since March 5rd I don't think this is only my issue. I just gave the statistic site as an example that something is up. Look at the dates here, they haven't moved! https://brackets-registry.aboutweb.com/

**Comment by le717** [comment]
OK, I see the issue now. I'm getting a 400 Bed Request error when POSTing to /upload, and visiting that page returns a "Cannot GET /upload" error. I forget who manages the registry... @ingorichter, I believe?

**Comment by peterflynn** [comment]
I've notified AboutWeb and hopefully they'll restart the server soon.

**Comment by mackenza** [comment]
I am also getting the BAD REQUEST error on trying to update an extension.  Hopefully this gets fixed soon ;)

**Comment by dnbard** [comment]
Also, `totalDownloads` field for any extension in registry (`https://s3.amazonaws.com/extend.brackets/registry.json`) aren't changed for several days.

**Comment by redmunds** [comment]
Should be working again.

**Comment by rainje** [comment]
Bad request is back.

**Comment by prksingh** [comment]
I will contact AboutWeb to restart the server again

**Comment by brad-jones** [comment]
+1 bad request is coming up for me too. Any progress been made with AboutWeb?

**Comment by JosephGF** [comment]
I have probelms too

**Comment by prksingh** [comment]
The server has been restarted. Can you guys check if you are still facing any issues

**Comment by brad-jones** [comment]
Sweet worked for me.

Probably not the place to have this discussion someone might point me to an exiting discussion.
Are there plans to setup the brackets registry in a similar vain to that of composer, bower, npm, etc... Eg: Just hook straight into github, allowing me to simply push a new version tag, bypassing the manual zip upload workflow we have currently.

**Comment by SteveMcArthur** [comment]
OK - looks like the BAD REQUEST error is back again...

**Comment by warapitiya** [comment]
Bad Request is back! :/

**Comment by prafulVaishnav** [comment]
@warapitiya  We will notify AboutWeb and restart the server.

**Comment by warapitiya** [comment]
@prafulVaishnav thanks buddy :+1:

**Comment by prafulVaishnav** [comment]
@warapitiya @SteveMcArthur Can you please try uploading the extension. Someone is successfully able to upload the extension.

**Comment by dnbard** [comment]
@prafulVaishnav You can look at the downloads chart at http://brackets.dnbard.com/extension/dnbard.documents-toolbar and see if it is possible to use Brackets Registry or not(Day with *zero* downloads are the one when registry isn't working) - Today it is working.

**Comment by ryanstewart** [comment]
I'm going to go ahead and close this because the registry is back up. One of the things we will be looking at for the 1.4 release is dedicating some time to improve the stability of the extension registry. We understand it's very frustrating for users and extension developers when it's down.

**Comment by prafulVaishnav** [comment]
@dnbard Thanks a lot. It is really helpful.

**Comment by SteveMcArthur** [comment]
@warapitiya Yep - working now

**Comment by warapitiya** [comment]
@prafulVaishnav Working :+1:

**Comment by le717** [comment]
It's baaaaaaaaackkkkk... \*sigh*

Is there any clue why these bad request errors keep occurring?

**Comment by ryanstewart** [comment]
I've got a meeting with the folks hosting the registry today (Wednesday) so I'm hoping we can get some info about how we can help triage the issues.

**Comment by le717** [comment]
@ryanstewart Thank you. Hopefully this sudden issue can be resolved soon!

In the meantime, can we get the server restarted? The error is persisting this morning/afternoon. :)
