### ISSUE TITLE
Brackets code hint with python not working.

### ISSUE THREAD

**Issue by GAZ082** [adobe/brackets#10722]
Hi there. It used to work and not it's not. Where should i look?

**Comment by peterflynn** [comment]
Brackets core does not include any code hints for Python.

You were probably seeing code hints from an extension you'd installed, such as WordHint.  Under the Installed extensions list in Extension Manager, you can click the "More info..." link and then file a bug with that extension's author.  The more specific you can be (e.g. providing a simple example file where hints don't work), the more likely the extension author will be able to help you.
