### ISSUE TITLE
Add support for Node.js 0.12.0

### ISSUE THREAD

**Issue by ghostoy** [adobe/brackets#10734]
Node.js 0.12.0 is released. Will Brackets upgrade to support this version?

**Comment by prksingh** [comment]
I have created a task for this in the backlog. https://trello.com/c/DJwcfxyh

Please upvote it so it can be picked up on priority.

**Comment by peterflynn** [comment]
@ghostoy If you or someone else could comment on that card about the benefits of upgrading Node, I think it would be helpful.  Updating is a bunch of work and could be destabilizing, so we'd want to know that Brackets is getting something worthwhile out of it before undertaking that work.

See also #10001, which is about a much shorter-term upgrade to a newer version of 0.10.x...
