### ISSUE TITLE
PHP code Beautify

### ISSUE THREAD

**Issue by kneeki** [adobe/brackets#10739]
Hey all,

I've looked through the extensions and I was unable to find an extension that supports formatting PHP code. I've tried `jsbeautify` and `beautifier`, neither work with a `.php` file. Anyone have any tips as to how I could go about beautifying my php files?

**Comment by peterflynn** [comment]
Closing and adding to 'Extension Ideas' list.  I'm not aware of any existing extensions that do this, but it would be a great one to have!

There are several open-source PHP formatters on GitHub, so extension authors might want to take a look at one of these as a starting point:
https://github.com/mmoreram/php-formatter
https://github.com/clbustos/PHP_Beautifier
https://github.com/NathanWong/phpformatter
https://github.com/DennisBecker/php-code-formatter
