### ISSUE TITLE
Don't lose history when refresh

### ISSUE THREAD

**Issue by yahyaKacem** [adobe/brackets#10735]
When using Brackets and hit the F5 button to refresh the ability to undo changes is lost.
OS: Ubuntu 14.04.
Bracket Build: Release 1.2 experimental build 1.2.0-15697.

**Comment by prafulVaishnav** [comment]
We have this item on the backlog https://trello.com/c/H8AyDwFA/391-local-history-versioning. You can upvote this.

**Comment by prksingh** [comment]
Closing the issue to avoid duplicate tracking

**Comment by peterflynn** [comment]
This may actually be more a duplicate of #10222.

@yahyaKacem What are you using F5 for?  Normally it's only used if you're developing an extension for Brackets or modifying the core source code...

**Comment by yahyaKacem** [comment]
@peterflynn sometimes some plugins like [interactive linter](https://github.com/MiguelCastillo/Brackets-InteractiveLinter) stop working so I have to refresh brackets so it continue to work I didn't find why this is happening  probably there's's another bug.
