### ISSUE TITLE
How to create a custom shortcut

### ISSUE THREAD

**Issue by yoyoy** [adobe/brackets#10749]
Hello everybody...
i'm looking for a simple thing on google but did not find any example.

I would like to create my own shortcuts to write code...

for example if I do ALTGr+G I like to write $_GET[''] in my code directly...
same for ALTGr+P with $_POST['']
if my cursor can be positionned beetween the 2 quotes it would be fantastic...

please could you explain me the way to do that ? 
thanks a looooottt :)

**Comment by peterflynn** [comment]
Check out the popular "Brackets Snippets" extension.

Snippets are not a built-in core Brackets feature right now, but if you'd like them to be, please upvote this item on our feature backlog: [Code Snippets/Templates: Insert & manage snippets](https://trello.com/c/tVSVhAg2/342-code-snippets-templates-insert-manage-snippets).
