### ISSUE TITLE
code select

### ISSUE THREAD

**Issue by redosendoken** [adobe/brackets#10740]
select all codes in a line by clicking the line number

**Comment by prksingh** [comment]
Good candidate for an extension

**Comment by peterflynn** [comment]
You can also upvote this item on our feature backlog if you'd like this to be a built-in feature: [Click/drag in gutter selects line(s), double-click selects block](https://trello.com/c/rQOTX8JH/1022-click-drag-in-gutter-selects-line-s-double-click-selects-block).
