### ISSUE TITLE
Incorrect SCSS syntax highlighting after using interpolation.

### ISSUE THREAD

**Issue by dustindowell22** [adobe/brackets#10747]
When using interpolation, `#{}`, syntax highlighting in SCSS looks like this.
![](http://cl.ly/image/0t3e0j001p3p/Screen%20Shot%202015-03-15%20at%204.35.32%20AM.png)

Instead of how it normally would look, which would be like this.
![](http://cl.ly/image/3f42341a0C2K/Screen%20Shot%202015-03-15%20at%204.35.43%20AM.png)

**Comment by MarcelGerber** [comment]
Cross-filed: codemirror/CodeMirror#3133

**Comment by MarcelGerber** [comment]
Will be fixed in Release 1.4
There was another fix (https://github.com/codemirror/CodeMirror/commit/cffaa81922905e226109b868a7be232581e0c60b) which we probably won't get in Release 1.4, but that's only a minor annyoance either way (imho).

Closing.
