### ISSUE TITLE
Anti-Virus (NOD32) blocking the "Live Preview"

### ISSUE THREAD

**Issue by GuyZipory** [adobe/brackets#10744]
Hello,
Whenever I hit Live Preview, Chrome opens up like it's supposed to. However, it is stuck at "Waiting". It takes extremely long to load, to the point where I don't even feel like using Live Preview anymore. And in the rare case that it does work, it's not live. It's like any other static http server.
so I tried to stop the my antivirus (NOD32) and suddenly problem fixed!

Now I don't sure how to make nod32 stop blocking the live preview.....

I hope some one can help :)

**Comment by WackiDesign** [comment]
Yes, I can confirm that. 
But NOD32 also blocks some extensions (for example eqFTP) and even some functions of Brackets.

Fortunately, you can exclude the protocol filtering in NOD32: advanced settings -> web and mail -> protocol filtering -> excluded aplications -> brackets.exe

**Comment by rainje** [comment]
Two days ago I noticed that brackets hangs every 5 minutes or so, I tried disabling some extensions, then all with no success. I cleaned brackets and reinstalled it, after only a minute working with this fresh  bracket install (no extensions) it froze again... I'm also using NOD32 so it may be related, I excluded the application from filtering and no more freeze.

**Comment by prksingh** [comment]
@GuyZipory Are you still facing the issue?

**Comment by GuyZipory** [comment]
No, problem solved! Thanks!
בתאריך 25 במרץ 2015 09:56, ‏"Prashant Kumar Singh" <notifications@github.com>
כתב:
