### ISSUE TITLE
Extension Manager not fully visible

### ISSUE THREAD

**Issue by GameplayJDK** [adobe/brackets#10743]
I've docked the brackets window to the right side of my screen, but as I tried to open the extension manager it wasn't fully visible:

![screenshot_1](https://cloud.githubusercontent.com/assets/4069263/6651897/9d6569e8-ca59-11e4-87c3-268960a98f50.png)

**Comment by petetnt** [comment]
Duplicate of #10728

**Comment by prksingh** [comment]
Closing as it looks like a duplicate. Please reopen if your problem is different
