### ISSUE TITLE
Include autocompletion from class and id

### ISSUE THREAD

**Issue by abdelouahabb** [adobe/brackets#10756]
Hi,
I wish I can do this in Brackets, where I can have the `class` and `id` from the project, I guess this is easy to do, because it will scan the DOM using some XML parser, and get all the values of the classes and id, and of course the scan will be only in the same directory.
Here is an example from Eclipse:
![sans titre](https://cloud.githubusercontent.com/assets/2527234/6691450/e7d06202-ccc6-11e4-90b1-d77a0c4b14e2.jpg)

**Comment by peterflynn** [comment]
@abdelouahabb I agree that would be very cool!  We're tracking that idea on our feature backlog here: [CSS Code Hinting: CSS Class and ID used in HTML](https://trello.com/c/oldLUN3g/1032-css-code-hinting-css-class-and-id-used-in-html).  Please upvote that item to help raise its priority -- I'll close this bug to avoid duplication.

**Comment by abdelouahabb** [comment]
ah wonderful! thank you! VOTING :+1:

**Comment by voidish** [comment]
I'm also needing this
