### ISSUE TITLE
Drop images/files in the sidebar where the files are standing

### ISSUE THREAD

**Issue by elice82** [adobe/brackets#10750]
I'm working in Brackets 1.2 on Yosemite (Mac OS X 10.10) and I can't seem to drop images in the sidebar where the files are. Sometimes I do get + sign but it opens in the top part.
I thought I could dot this in Mavericks (10.9).

**Comment by prafulVaishnav** [comment]
Are you saying you are not able to open the image file when you drop it to brackets. Ideally droping any supported file will open it and add it to the brackets working files. 
![untitled](https://cloud.githubusercontent.com/assets/10204469/6661356/00524206-cbd1-11e4-8136-0a32cdb4fd06.png)

**Comment by peterflynn** [comment]
@elice82 "Sometimes I do get + sign but it opens in the top part." -- That's the correct behavior.  Dropping a file on Brackets always opens it.

If you want dropping a file onto the folder tree to actually move/copy the file into that folder, please upvote this item on our feature backlog: [Drag/drop from OS to File Tree (Copy/Move file)](https://trello.com/c/xwNIcxO6/347-drag-drop-from-os-to-file-tree-copy-move-file).

**Comment by elice82** [comment]
@prafulVaishnav
Yes, this the behavior now.

Example: 
I use Skitch (another app), drag the image outthere into Brackets and dropped into the folder "IMG". Not working files.
This what I did on Mavericks but on Yosemite it isn't supported anymore.

@peterflynn
I hope it is the same thing as I 'm writing about.

**Comment by peterflynn** [comment]
@elice82 That has never been supported in Brackets, but we'd like it to be a feature in the future. Please upvote the link I gave above to help raise its priority.

Closing to avoid redundancy since drag & drop files to copy is already tracked on our feature backlog.
