### ISSUE TITLE
Unable to open files larger than 16mb

### ISSUE THREAD

**Issue by nsyrax** [adobe/brackets#10759]
I have tried running Brackets with and without extensions and get the same result. The error I receive is **"Error Opening File. An error occurred when trying to open the file C:/Users/nsyrax/20150312.txt. Files larger than 16 MB cannot be opened in Brackets."** I've tried opening several files that were also above 16 mb with no luck. My Brackets version is Release 1.2 build 1.2.0-15697 running on Windows 7 SP1. No errors were logged in the consloe.

**Comment by peterflynn** [comment]
@nsyrax The error message is correct: Brackets does not open files larger than 16 MB, to protect performance and stability.  How often do you need to edit text files larger than 16 MB?  How much larger are they?

**Comment by nsyrax** [comment]
@peterflynn Every Tuesday and Thursday I process files that are between 16-17mb, so I do it pretty regularly. It's a new process I've been given, so it's also a new problem I hadn't encountered with Brackets before. BTW, I LOVE Brackets. Since I started using it, this is the ONLY thing where it's let me down.

**Comment by ryanstewart** [comment]
Moving this to the backlog. But it will undoubtedly be part of a larger performance story and I'm not sure when we'd do that work.

**Comment by ryanstewart** [comment]
Closing and tracking on this card - https://trello.com/c/zvJT4OV8/1416-add-support-for-files-greater-than-16-mb

**Comment by Globegitter** [comment]
@ryanstewart Just wanted to raise my voice here that I needed that as well. Downloaded Sublime Text 3 just for that. It opens a 17.5MB json just fine.

**Comment by shaneparsons** [comment]
+1 for this.. Even though file sizes above 16mb aren't used everyday, a code editor shouldn't be crippled by the size of a file, especially one as low as 17mb.

What if you make the max limit a changeable value in the preferences file? that way the people who really need it can use it.

You can even add a comment stating `//>16mb not recommended` if you needed to.

**Comment by prakash-freshdesk** [comment]
please take concern of this file size issue... I am UI developer all the psd getting from UX designer is > than 16mb .. i cannot use the psd feature in brackets..yet i love it..

**Comment by abose** [comment]
Extract in brackets can open files>16 MB. Please upload the file to your creative cloud folder to use extract.

**Comment by prakash-freshdesk** [comment]
is it safe to use creative cloud space ?

**Comment by abose** [comment]
yes. open extract> upload a psd button> login to cc> upload the file there.

**Comment by prakash-freshdesk** [comment]
Thank you !

**Comment by ugacodedawg** [comment]
I'm a bit late to the Brackets & PSD party...just downloaded the app...Where is the option for "extract"?  I don't see it in the menus.  I tried to open a PSD, and got the error > 16Mb message as well.  Thanks for the help!

**Comment by zoulja** [comment]
What a shame - in 2017 with Core i7 CPU and 16Gb RAM this software still can't open files larger than 16Mb

**Comment by MordecaiEldrige** [comment]
I have to agree with zoulja... Opening 400 MB text files in Sublime causes A FEW performance issues... what kind of performance issues do you expect by allowing Brackets to open files > 16 MB??

**Comment by s1dekick223** [comment]
i need to open files of 20mb size or files like 500mb size. why i there a limit downloaded sublime and i'm fine with it. But i just dont understand it just a bool for removing the sizelimit is fine...

**Comment by chylex** [comment]
Come on, 16 MB? Windows notepad can open that, can't Brackets at least try? Especially if it's a format that doesn't have any syntax highlighting (or disable it for large files).

**Comment by asmajlovicmars** [comment]
Same thing. Need to open db restore sql scripts that are over 30mb. Sublime edits them perfectly fine, but it's unnecessary to exit brackets, just to edit couple files. If not a big deal, please remove the limit.

**Comment by mporubek22395** [comment]
I have now also made the switch to Sublime - it is very unfortunate that a 16mb limitation will ultimately lead to the downfall of such a great utility.

**Comment by chylex** [comment]
I'd recommend switching to VS Code, the 64-bit version has no size limit.

**Comment by CMSHostingLLC** [comment]
Today I am deleting brackets because I can't open files larger than 15 MB I have a 12 core 96GB of ram desktop and notepad will open it and no performance issue... Why you got to hunt for a needle in a 500MB SQL file this is beyond unacceptable.

**Comment by Gofer01** [comment]
Hahaha, okay you need my setup. I have a AMD Ryzen 9 3950X 16-core with 128GB RAM with RAID 0 m.2 nvme 1TB SSD’s. I have no problems what so ever.

Mike
.
