### ISSUE TITLE
Error Message when .brackets.json file has bad syntax

### ISSUE THREAD

**Issue by bstopp** [adobe/brackets#10757]
Plugins fail to work correctly when a project's *.brackets.json* file has a bad format (like an extra **,** in an object). However there's no indicator that there is an issue with the configuration file.

Can there be a log message that pops-up when this is the case, similar to when it is a JS file?

![capture](https://cloud.githubusercontent.com/assets/6520270/6696726/6f806e58-ccb9-11e4-894b-67635462c118.PNG)

**Comment by prafulVaishnav** [comment]
@bstopp Hii.. Brackets do show the message about the corrupt preference file when the brackets is loaded and it finds corrupt preference file. 
![untitled](https://cloud.githubusercontent.com/assets/10204469/6703237/857edf50-cd5e-11e4-9db4-1b653e554aab.png)

Are you not able to see this message on brackets launch?

**Comment by nethip** [comment]
@prafulVaishnav I think @bstopp is referring to the .brackets.json present in the project folder not the global preference one.

**Comment by petetnt** [comment]
Ingo Richter's JSONLint Extension for Brackets (also available in the extension registry) does what @bstopp wants.

https://github.com/ingorichter/de.richter.brackets.jsonlint

**Comment by prafulVaishnav** [comment]
@bstopp I misunderstood.. We don't have check for the projects preference. Make sense to check for the corrupt preference file when project loads and show dialog if its bad.

**Comment by bstopp** [comment]
Sorry, should have been more specific. I am referring to the file within a given project; not the global preferences file.

**Comment by prksingh** [comment]
This does seem like something brackets should do. Would be good to hear what @ryanstewart thinks.

**Comment by nethip** [comment]
IMO we should do what we are doing with the corrupted global preference file. I think applying the above workflow(which @prafulVaishnav has pointed out) for project's bracket.json should be the ideal fix.

**Comment by ryanstewart** [comment]
Agreed, seems ideal to do what we're doing with the global preferences file. Moving it to the backlog column.

**Comment by prksingh** [comment]
It may be a good idea to also look at #10796 I think we should show an error in case 'any' JSON that brackets is expected to understand is not properly formatted.

**Comment by prafulVaishnav** [comment]
@rroshan1 I think this issue has been fixed. Can you close this?

**Comment by rroshan1** [comment]
Fixed by PR #10819.
