### ISSUE TITLE
Wrap with abbreviation shortcut has been removed

### ISSUE THREAD

**Issue by iampeterbanjo** [adobe/brackets#10762]
Hi. I love Brackets and especially it's integration with Emmet.

The "Wrap with abbreviation" shortcut is no longer working - sometime in the past week or so it seems to have been disabled or removed. The shortcut used to be Ctrl (Cmd) + Shift + A but it no longer works or appears under the Emmet drop-down next to "Wrap with abbreviation". I don't know if it's related to #3280. 

I am using a Mac and Brackets Release 1.2 build 1.2.0-15697 (release 8f82e2a97) 
build timestamp: Sun Feb 22 2015 22:34:50 GMT-0800

Is there a way to re-enable this?

Thanks

**Comment by nethip** [comment]
@iampeterbanjo Just to rule out some possibilities can you try running Brackets without extensions. Choose `Debug->Reload without Extensions`. The next step you could try is to check to see if you have any custom key bindings. You could access the same from `Debug->Open User Key Map`. More about key bindings can be found at this location. (https://github.com/adobe/brackets/wiki/User-Key-Bindings)

**Comment by peterflynn** [comment]
@iampeterbanjo Since this is a problem with the Emmet extension specifically, and not Brackets core, please file this bug with the Emmet extension's developers instead.

Actually, looks like someone beat you to it: emmetio/brackets-emmet#78.  Might want to leave a comment over there.

**Comment by iampeterbanjo** [comment]
@peterflynn @nethip Thanks both.
