### ISSUE TITLE
When trying to open a PSD for the first time in Extract it says "To sign in, please connect to the internet."

### ISSUE THREAD

**Issue by unproductiveefficiency** [adobe/brackets#10765]
Obviously I am connected to the internet. I have tried turning off firewall and reinstalling. I tried versions 1.1 and 1.2, but am having the same problem.

http://i.imgur.com/4yckfBk.png

**Comment by nethip** [comment]
@unproductiveefficiency Sorry for not being able to use Extract. Could you confirm if you are able to install any extension and also tell us if you able to use Live Preview feature? Also please check if you are able to open the PSD by pasting the short URL of your PSD?

**Comment by unproductiveefficiency** [comment]
Yes. I was able to use other extensions. For some reason it just started working. Sorry I could not give a reason why.

**Comment by prksingh** [comment]
Closing for now. Please reopen if you see the issue again.

**Comment by hardikdangar** [comment]
I have the same issue with my system. I could connect to internet and adobe bracket extension site even brackets extension manager shows extensions to download but extract fails with "To sign in please connect to internet."

I removed the brackets package totally to fix this and reinstalled but nothing worked.

OS: ubuntu 14.04
