### ISSUE TITLE
Quick edit with Jade

### ISSUE THREAD

**Issue by greasan** [adobe/brackets#10764]
Hi,

is it possible to use quick edit css feature with Jade?

**Comment by prafulVaishnav** [comment]
@greasan We don't have Jade support in Brackets. There are some extensions available for Jade highlighting and snippets in Brackets.

**Comment by prksingh** [comment]
Brackets focuses on core web languages (HTML, CSS and Javascript). There may be extensions contributed by developers for other languages though as mentioned by @prafulVaishnav.
