### ISSUE TITLE
Can’t translate string `FIND_IN_FILES_SCOPED` correctly

### ISSUE THREAD

**Issue by valtlai** [adobe/brackets#10775]
I’m not able to translate string `FIND_IN_FILES_SCOPED` correctly into Finnish, because it’s used in two different places.

When an user clicks file tree item and selects “Find in…” `FIND_IN_FILES_SCOPED` should be `kohteesta <span class='dialog-filename'>{0}</span>`.

When s/he selects “Replace in…” the string should be `kohteessa [...]`.  (Letter _s_, not _t_)

For this reason, there should be two separate strings for these functions.

**Comment by abose** [comment]
@valtlait isn't there actually two different strings for find in and replace in?

**Comment by valtlait** [comment]
Value in `FIND_IN_FILES_SCOPED` is `in <span class='dialog-filename'>{0}</span>`. There should be `REPLACE_IN_FILES_SCOPED` which contains the same value. But in Finnish translation there would be two different values.

**Comment by ficristo** [comment]
@valtlai do you want to setup a PR?

**Comment by valtlai** [comment]
I’m no longer contributing to the project, so closing.
