### ISSUE TITLE
Adobe Extract crop tool missing.

### ISSUE THREAD

**Issue by holdav** [adobe/brackets#10772]
Hello,

could it be possible to implement crop tool in Adobe Extract plugin? This tool is very useful. Pure layers aren't always that what HTML coder needs and crop tool is necessary in this cases.

Thanks.

**Comment by nethip** [comment]
CC @ryanstewart

**Comment by ryanstewart** [comment]
@holdav it's definitely something we'd like to look at. How would you want the crop tool to work? You'd want to be able to extract any area on the canvas? Not just layers? And multiple layer selection doesn't work for your needs in this case?

=Ryan
ryan@adobe.com

**Comment by holdav** [comment]
There is many use cases where crop tool is the only way to gain required .png. Especially when the only option to code something is usage of "CSS hack". For example if you need to crop only a part of a layer or if graphic design some CSS "non-logic" layer.

**Comment by abose** [comment]
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
