### ISSUE TITLE
Extensions manager is positionned strangely

### ISSUE THREAD

**Issue by TheTeapot418** [adobe/brackets#10778]
I have noticed this bug since the last update. I don't know if it depends on the screen resolution ...

Expected behavior : 
Opening the extensions manager brings up the window horizontally and vertically centered

Actual behavior : 
The extensions manager window is correctly positionned vertically, but is not centered horizontally

**Comment by prafulVaishnav** [comment]
@TheTeapot418 Can you paste here the screenshots? What is your platform and version of Brackets? We have some ongoing issues related to Extension Manager positioning : https://github.com/adobe/brackets/issues/10728 https://github.com/adobe/brackets/issues/9838

**Comment by TheTeapot418** [comment]
Sorry, here is a screenshot : 

![capture d ecran 119](https://cloud.githubusercontent.com/assets/11538064/6779818/348b6b58-d160-11e4-9f75-0e917b5ad3fb.png)

I am running Brackets 1.2.0-15697 on Windows 8.1 Update 1. My screen resolution is 1366x768px

**Comment by peterflynn** [comment]
@TheTeapot418 Can you try [manually disabling all extensions](https://github.com/adobe/brackets/wiki/Troubleshooting#disabling-extensions-individually) and see if the problem goes away?  (If so, you can re-enable extensions one-by-one or in small groups to pinpoint which one is causing the problem).

**Comment by TheTeapot418** [comment]
@peterflynn Ok so apparently, the extension which causes the problem is the preview of Extract

**Comment by peterflynn** [comment]
@TheTeapot418 If you look in the "Installed" tab in Extension Manager, what version of Extract for Brackets does it show?

**Comment by TheTeapot418** [comment]
I'm runing the 0.6.1-1719-release version of Extract, but something strange happened : right after re-enabling the extension, the bug dissapeared.

**Comment by prksingh** [comment]
Are you still seeing this issue with Extract?

**Comment by TheTeapot418** [comment]
Nope, as I said, after re-enabling Extract, the issue didn't show up anymore.

**Comment by peterflynn** [comment]
Closing.  Please let us know if the issue comes back, though.
