### ISSUE TITLE
Brackets dose not recognise my css file for quick edits

### ISSUE THREAD

**Issue by JohnL3** [adobe/brackets#10782]
Brackets wont recognise my css file for quick edits .... when i go to quick edits and hit new it opens up a list of other css like main.css Quickveiw.less styles.less .
i can manuall click on my css file and add styles and it updates the html that im working on.
when i installed brackets it had this problem and would only bring up the read me  main.css for the help html. so after trying a few times i decided to delete the styles folder this was in but still no luck ... this is when it the started to show a list of other css and .less files 
i then decided to uninstall and try reinstalling but still no luck ... so then i tried a systm restore to a date prior to first installing ... again no luck and still cant quick edit css 
any thoughts on this would be appreciated (i am pretty new to all this so hope you can help)

**Comment by JohnL3** [comment]
Managed to close the other files that were showing up under the file i was working on. still hasnt helped but from the attached image you can see the simple example i am trying. you can see the preview in the browser with the css styles and you can see in the edting window when i now click quick edit it says "They are no stylesheets in your project create one to add CSS rule."
would really appreciate some help on this as i would love to use this programm.

![brackets problem](https://cloud.githubusercontent.com/assets/11596539/6771601/8bffce96-d0da-11e4-8cba-1e3ef9ac490c.jpg)

**Comment by PavanKu** [comment]
@JohnL3 , I think, you need to open the folder which contains CSS and html files in brackets then only Brackets will come to know linked css files.

So follow below steps:
1) Click on "screenshots" drop down in side bar
2) Open folder containing css and HTMLS
3) Try "Quick Edit"

**Comment by JohnL3** [comment]
Thank you very much for this ... clicked on screenshots and opened my flolder throught the option there and it worked can now quick edit ....

**Comment by Pjdaze** [comment]
OMG thanks so much !!!!!

**Comment by Shahzaib-Rehman** [comment]
Thank you so much. I had the some problem but now resolved with this solution.

**Comment by ajtg2018** [comment]
I think it's about opening the whole folder. Thank you very much. It works for me now.
