### ISSUE TITLE
Extension's update button disabled

### ISSUE THREAD

**Issue by Garito** [adobe/brackets#10794]
Hi!
Some extensions like Brackets builder or VisibleTabs has and update button but is disabled (can't click on it and it's grayer)

How can I update this extensions (or how to proceed)?

Thanks!

**Comment by nethip** [comment]
@garito Could you open dev tools from *Debug->Show Developer Tools* and tell us if you seeing any console  error messages?

**Comment by MarcelGerber** [comment]
Dupe of #10411 (I confirmed "Brackets builder" doesn't have a engines section in it's package.json).
Fix already up for review at #10421.

**Comment by Garito** [comment]
I have a pretty long console log so if you don't mind i prefer to resume the thing
I have 2 errors:
1.- Cannot assign Alt-Cmd-B to builder.build. It is already assigned to builder.build
2.- GET http://brackets-rating.herokuapp.com/ratings/ 500 (Internal Server Error)
and 31 deprecation warnings

Are you looking for something concrete or perhaps @MarcelGerber has a point?

**Comment by Garito** [comment]
Seems @MarcelGerber has a point

**Comment by MarcelGerber** [comment]
Yeah, as stated above, it's a known issue with a fix already submitted, but not yet merged.
Hopefully it's fixed in the next Brackets Release.

**Comment by Garito** [comment]
So, i can close this?

**Comment by prksingh** [comment]
I will close the issue, once #10421 is merged.

**Comment by MarcelGerber** [comment]
Confirmed fixed.
Closing.
