### ISSUE TITLE
Feature request: Find/Replace in Working Files

### ISSUE THREAD

**Issue by stowball** [adobe/brackets#10804]
It would be great to provide an option that searches (and replaces) across just the files open as Working Files.

In a new code-base especially, I often can't remember exactly which previously opened file has a thing I'm looking for, so do a search. Searching across all files is a bit slow and heavy-handed for this task.

**Comment by prafulVaishnav** [comment]
@stowball Hii.. We have backlog for comprehensive features of Find/Replace. Please upvote [here](https://trello.com/c/xFElZcT2/1090-find-replace-extensibility) . Aso I have created separate backlog for this specific feature.  Please upvote [Find/Replace in Working Set Files] (https://trello.com/c/jTn9lvIM/1417-find-replace-in-working-set-files) on our feature backlog.

**Comment by abose** [comment]
Find and replace now prioritizes working set files at the start of the list.
If this fixes the use case, Please close the issue.

**Comment by abose** [comment]
Closing stale thread.

**Comment by stowball** [comment]
Prioritising isn't the same as *only*

**Comment by abose** [comment]
This issue is now tracked under 
https://trello.com/c/9IBv6zRq/1359-find-in-files-inclusive-additive-filters
and 
https://trello.com/c/jTn9lvIM/1417-find-replace-in-working-set-files

Feature requests are not tracked as issues usually. So closed.
