### ISSUE TITLE
Various .sass syntax highlight bugs [1.2] apart from #10692

### ISSUE THREAD

**Issue by oreqizer** [adobe/brackets#10807]
**Brackets:** 1.2
**OS:** Elementary OS Freya

**Notice:** i fixed the CodeMirror sass.js bug with the "properties" typo

Hi,

I noticed a couple of syntax highlight bugs with .sass files. Here's a
 screenshot of all the issues i encountered:
![screenshot from 2015-03-30 21 39 06](https://cloud.githubusercontent.com/assets/11172408/6905168/6a91a20a-d726-11e4-81ff-d53d9580561f.png)

The bugs are commented. Let me know if you need further info!

**Comment by le717** [comment]
So you are saying this _is_ different than #10692? Does correct highlighting work in Brackets v1.1? If so, can you post a comparison screenshot? The SASS mode in CM underwent some major changes in the last CM version, and what you have here may be further regressions.

**Comment by Oreqizer** [comment]
Haven't tried 1.1 (started writing .sass only very recently), but yes, based on the issue u posted i fixed the 1.2 issue today. This is different.

**Comment by sthag** [comment]
I can confirm the highlighting problems with sass files.
I'm using Brackets 1.2 Build 1.2.0-15697 on Windows 7 and 8.1
There is no difference in using Brackets with or without extensions.
It appears in every sass file.

**Comment by ficristo** [comment]
It seems to me that CodeMirror gives some css classes we don't have styled.
Possibly relevant the comments of @peterflynn at https://github.com/codemirror/CodeMirror/pull/3116

**Comment by ficristo** [comment]
The code in the screenshot:
```sass
$defined-bs-type: border-box !default
//declaration causing highlight bug...

//...here
=bs($bs-type: $defined-bs-type)
    -webkit-box-sizing: $bs-type
    -moz-box-sizing: $bs-type
    box-sizing: $bs-type

// @mixin substitution with = not highlighting
=button-links($button-base: darken($color11, 10%), $button-hover: darken($color11, 15%))
    border: 1px solid darken($color11, 16%)
    padding: .3em .6em
    //not writing zeros in numbers (0.6 -> .6) causes many highlight bugs...
    margin-left: .7em
    +border-radius(8px) // @include substitution with + not highlighting [2]
    +text-shadow(0 1px 2px $color11)
        color: lighten($color10, 50%)
    background-color: $button-base

    //
    //VERSUS
    //

$defined-bs-type: border-box !default
//declaration causing highlight bug...

//...also here
@mixin bs($bs-type: $defined-bs-type) 
    //a space above, and bug happens below
    -webkit-box-sizing: $bs-type
    -moz-box-sizing: $bs-type
    box-sizing: $bs-type

// @mixin substitution with = not highlight
@mixin button-links($button-base: darken($color11, 10%), $button-hover: darken($color11, 15%))
    border: 1px solid darken($color11, 16%)
    padding: 0.3em 0.6em
    //see? numbers are ok now
    margin-left: 0.7em
    @include border-radius(8px)
    // @include substitution with + not highlighting
    @include text-shadow(0 1px 2px $color11)
    color: lighten($color10, 50%)
    background-color: $button-base
```

**Comment by ficristo** [comment]
Thanks to #13116, in next release Sass syntax highlight should be better. (Not perfect...)
