### ISSUE TITLE
brackets in taskbar goes obsolete after update

### ISSUE THREAD

**Issue by balasivagnanam** [adobe/brackets#10805]
The brackets link which we pin to taskbar in windows doesn't work after we do an update to current brackets.. "it says the program has been moved or renamed or deleted"

**Comment by le717** [comment]
Duplicate of #6297. This has been a long-standing issue, but as I have extensively documented on there, it is not a easy fix to make.

**Comment by balasivagnanam** [comment]
thank you :) I am bit new so din't realize it.
