### ISSUE TITLE
Drag & drop text preference (dragDropText) doesn't take effect properly on files already open

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10812]
1. Start with the preference off
2. Open a few files
3. Open the preferences file, turn `dragDropText` on, and save
4. Try to drag the selected text in any of the already open editors

Result:
- on Mac, dragging the selection does nothing
- on Win, dragging the selection appears to drag an image of the entire editor area

Expected:
Selection should be dragged normally, as seen if the files are closed & reopened or if Brackets is restarted.

**Comment by peterflynn** [comment]
Nominating for 1.3 because I've heard several complaints about this already.

@MarcelGerber would you be willing to look into this one?  Not sure if it's a CM bug or a problem in our Editor code that handles preferences changes.

**Comment by MarcelGerber** [comment]
It's a CodeMirror issue: codemirror/CodeMirror#3167

**Comment by rawat11** [comment]
@MarcelGerber Does it happen for all the features that are enabled from prefernces file ?

**Comment by MarcelGerber** [comment]
Nope, it's just the `dragDropText` preference. And it's already fixed on the CM side.

**Comment by peterflynn** [comment]
@prksingh @prksingh Have we done the start-of-sprint CM merge yet for 1.3?  If so, I wonder if we should do a second merge to pick up the fixes for this and #10590, plus codemirror/CodeMirror#3151.

**Comment by MarcelGerber** [comment]
@peterflynn [You haven't yet](https://github.com/adobe/brackets/commits/master/src/thirdparty/CodeMirror2).

**Comment by prksingh** [comment]
@peterflynn We will pick codemirror early next week and test the issue. I will update the bug accordingly.

**Comment by peterflynn** [comment]
Cool, thanks

**Comment by prafulVaishnav** [comment]
@MarcelGerber This bug has not been fixed on Mac. On Windows it has been fixed. Can you please reopen the bug.

**Comment by MarcelGerber** [comment]
Are you sure? I can't see where that bug could be platform-specific. Are you sure you use the same CM version on both platforms?

**Comment by prafulVaishnav** [comment]
@MarcelGerber You are right. I found it but forgot to update. Problem is in Brackets, its not picking up the preference change from the file.

**Comment by prafulVaishnav** [comment]
I have checked this with the new version of code mirror and it seems to work fine. I am running unit tests with the latest version of code mirror in Brackets and will push the merge once the unit tests pass.

**Comment by madanbn** [comment]
It looks risky to be doing a merge of CM now so close to the release for 1.3, shouldn't we move this to 1.4?

**Comment by prafulVaishnav** [comment]
Issue has been fixed as CM is merged.

**Comment by teuk1** [comment]
Doesn't seem working with comments starting by //
