### ISSUE TITLE
[Live Preview MultiBrowser] Doesn't work with CodeMirror pages

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#10815]
1. Clone [CodeMirror](https://github.com/codemirror/codemirror) (or download a .zip and extract) and open it in Brackets.
2. Open `index.html` in Brackets.
3. Make sure MultiBrowser Live Preview is enabled.
4. Start Live Preview.

Result: The Live Preview symbol is only ever half-filled.
The console logs look fine, though:
```
NodeSocketTransport - start
NodeSocketTransport - send,,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":1}
NodeSocketTransport - send,,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":2}
NodeSocketTransport - send,,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":3}
```

cc @busykai @sebaslv

**Comment by MarcelGerber** [comment]
From my tests, it looks like the missing `html`/`head`/`body` structure causes these problems.

**Comment by busykai** [comment]
@MarcelGerber, does it work with the default version?

**Comment by MarcelGerber** [comment]
I haven't tested Live Editing or Highlighting, but the icon is completely filled at least.

**Comment by busykai** [comment]
Thanks! I will take a look at this. I'm back and have a couple of holidays ahead of me. :)

**Comment by MarcelGerber** [comment]
Btw, you don't need to clone CodeMirror -- a simple page without the aforementioned structure should suffice.
Probably, even a text-only HTML page works.

**Comment by MarcelGerber** [comment]
So, I've just taken another look on this:
* I was able to reproduce the issue with a .html file containing nothing than `abc`
* The browser opens just fine and displays the page correctly
* As soon as you edit the document, the icon changes from a yellow half-filled one to a purple filled one, indicating a syntax error
* With this very simple file, I got a `couldn't find the dom for ...` error message (I didn't get that message with CodeMirror, though)

**Comment by MarcelGerber** [comment]
Just tested with normal (non-MultiBrowser) Live Preview:
With that simple `abc` webpage, I get symptoms 3 and 4 from above, too.
But a simple `<div>abc</div>` works just fine, including Live Editing and Highlighting.

And now as I tested `<div>abc</div>` with MultiBrowser Live Preview, I got different findings... again:
* There's no `couldn't find the dom for ...` error message
* As soon as I edit my document, the half-filled icon turns into a filled icon
* The changes are not pushed to the browser, though
* Highlighting doesn't work, either
