### ISSUE TITLE
Ruby mode not un-indenting on "end" statement

### ISSUE THREAD

**Issue by frayer** [adobe/brackets#10829]
When editing Ruby files, a line is not un-indented or dedented when an "end" statement is encountered closing a block of code.

Steps

1. Create a new Ruby "*.rb" file.
2. Enter code like the following:

    ```ruby
    def say_hi
        puts 'hi'
        end
    ```

I'm expecting that when I type the "d" in "end" that the line shifts back one indentation level.  You can do the same on the CodeMirror Ruby test page and get the desired results.

https://codemirror.net/mode/ruby/index.html

**Brackets Version**
Release 1.2 build 1.2.0-15697 (release "8f82e2a97")
build timestamp: Sun Feb 22 2015 22:34:50 GMT-0800

**OS version**
OS X Yosemite
Version 10.10.2

**Did this work in a previous version?**
I've just recently started using Brackets as of 1.2, so I'm not aware of how it worked previously

**Were Extensions Disabled?**
Yes

**Were any errors logged?**
Nothing was logged

**Comment by peterflynn** [comment]
This should be fixed by PR #9387

**Comment by ficristo** [comment]
Works for me.
Closing
