### ISSUE TITLE
Integrating With Git Repo 

### ISSUE THREAD

**Issue by Bagusa4** [adobe/brackets#10825]
Integrating With Git Repository e.g Bitbucket or GitHub ...
Maybe this feature looks like in Visual Studio...
This feature can upload project into Git Repo directly via Bracket Editor ...
Look like Visual Studio, the project working in Editor can upload directly The project Issue, Update New code and etc into Visual Studio Online ...

Just it! I'm Sorry for my bad English :)  #Suggestion

**Comment by le717** [comment]
[Brackets-Git](https://github.com/zaggino/brackets-git). 'Nuff said. :)

**Comment by abose** [comment]
Brackets Git Extension from the extension registry :100:
