### ISSUE TITLE
trouble with Cyrillic in Extract for Brackets (Preview)

### ISSUE THREAD

**Issue by h0m1c1de** [adobe/brackets#10824]
![brackets-bug](https://cloud.githubusercontent.com/assets/9438211/6988470/716882f6-da5a-11e4-8503-6464ca43f53d.png)

not help:
reinstall brackets,
 instal version 1.1 ,
 new adobe acc, 
new windows.

Please help

**Comment by abose** [comment]
Could you share a sample psd with the Cyrillic font problem?

**Comment by h0m1c1de** [comment]
Problem is in all psd files with Cyrillic text
http://rghost.ru/6bLpqgXSc for exemple

**Comment by abose** [comment]
@h0m1c1de thanks for the upload, I was able to reproduce the issue in brackets. Most probably a font issue, the issue is not present in cc web.

**Comment by MarcelGerber** [comment]
#8985 will probably fix that issue.

**Comment by peterflynn** [comment]
@MarcelGerber I think this one is different -- it's not just an ugly font, it's glyphs not getting encoded right and showing up as "X"es, which is probably a server-side Extract bug.

**Comment by abose** [comment]
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
