### ISSUE TITLE
Brackets indents code even with smartIndent off

### ISSUE THREAD

**Issue by cfjedimaster** [adobe/brackets#10823]
I've got smartIndent turned off in my preferences, but if I'm writing a template, Brackets will auto indent a { character. It continues to do so even after I hit delete *multiple* times. This is a video demonstrating the bug. And again, I've got smartIndent set to false.

https://www.youtube.com/watch?v=J0CT_B2ka0Y&feature=youtu.be

**Comment by MarcelGerber** [comment]
This is fixed in Release 1.3

Part of #9387

**Comment by rroshan1** [comment]
Verified the fix.. The issue no longer exists!! 
Closing the issue.
