### ISSUE TITLE
Extension Registry error.

### ISSUE THREAD

**Issue by nicolo-ribaudo** [adobe/brackets#10832]
When I try to upload (update) an extension, I get this error:
```
An error occurred, but unfortunately I don't know how to say this nicely: ENOSPC, mkdir '/home/aboutweb/tmp/bracketsPackage_11536-1774-1q3tmxz'
```

**Comment by dnbard** [comment]
Same for me:
```
An error occurred, but unfortunately I don't know how to say this nicely: ENOSPC,
mkdir '/home/aboutweb/tmp/bracketsPackage_11536-1774-qsodmm'
```

Not enough disk space on registry machine?

**Comment by mikaeljorhult** [comment]
I've been getting the same kind of errors since yesterday. Now it's only "BAD REQUEST" though.

**Comment by prafulVaishnav** [comment]
@nicolo-ribaudo @dnbard @mikaeljorhult Hii. I have reached out to aboutweb team. Will let you know when it is resolved.

**Comment by zorgzerg** [comment]
Can't upload new version my extension too. Getting "Bad request". Fix it soon please )

**Comment by zorgzerg** [comment]
Thx for quick fix )

**Comment by nicolo-ribaudo** [comment]
I saw that some extensions have been updated today (e.g. Brackets Git), but I'm still getting a Bad Request error :sob:
