### ISSUE TITLE
Request for shortcuts customization

### ISSUE THREAD

**Issue by bhagatdinesh** [adobe/brackets#10837]
Hi,
Bracket is nice and light IDE for HTML,css, js coding.
I am eclipse user and have java programming knowledge.
I know important keyboard shortcuts to work in eclipse.
I searched web to get same shortcuts for brackets or to change it, but I did not find any.
It is nice to have same shortcuts instead of remembering new one.
I feel it will help me and other java/j2ee programmer to use Brackets easily.

Thanks,
D.B.

**Comment by nethip** [comment]
@bhagatdinesh Please go through this link to know about keyboard mapping inside Brackets.
https://github.com/adobe/brackets/wiki/Brackets-Shortcuts

**Comment by abose** [comment]
@bhagatdinesh additionally you can customize the shortcuts by editing the preferences file at brackets.json or the keyboard mapping files see. https://github.com/adobe/brackets/wiki/User-Key-Bindings . 
If you prefer to get eclipse shortcuts in brackets; you could always write an 'eclipse shortcuts' extension to share with everyone.

**Comment by peterflynn** [comment]
See also ['Keyboard Shortcut profiles matching other popular editors'](https://trello.com/c/ckAel1Cl/358-keyboard-shortcut-profiles-matching-other-popular-editors) on our backlog.

**Comment by peterflynn** [comment]
(@bhagatdinesh fyi, you can upvote that backlog link to help raise its priority)

**Comment by bhagatdinesh** [comment]
Thank you! guys,
As suggested by abose, I will edit preference file, but my concern is will it interfere with existing shortcuts of brackets?; never mind, I will give a try.

**Comment by peterflynn** [comment]
Anything you put in the user keybindings file will take precedence over the existing default shortcuts.
