### ISSUE TITLE
Most Code Folding preferences don't take effect until close/reopen or restart

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10848]
1. Open a JS file in the working set
2. Open brackets.json and add `"code-folding.enabled": false`
3. Switch back to the JS file

Result: code folding still enabled
Workaround: close & reopen the file

1. Restart Brackets
2. Remove the `"code-folding.enabled": false` line
3. Open any number of files you want

Result: code folding not enabled
Workaround: restart Brackets

This pattern occurs with other preferences like `"fadeFoldButtons"` too.

Other Brackets features all monitor for preference-change events and adjust at runtime.

**Comment by peterflynn** [comment]
PR #10850 fixes this for `"enabled"`, `"fadeFoldButtons"`, `"maxFoldLevel"`.

It doesn't yet fix it for `"minFoldSize"` or `"alwaysUseIndentFold"` -- it will start working if you bump a file hard enough to re-compute its folding markers, but the markers won't otherwise reflect the change right away.  We need to do something to force recomputing the markers when these prefs change.

**Comment by abose** [comment]
/brackets/issues/10870 has been filed for tracking minFoldSize and alwaysUseIndentFold issue.

**Comment by abose** [comment]
PR #10850  merged and  "enabled", "fadeFoldButtons", "maxFoldLevel" working without reload.
issue#10870 tracks issue with minFoldSize and alwaysUseIndentFold.
Closing this issue.
