### ISSUE TITLE
Lost undo history after save

### ISSUE THREAD

**Issue by fazelmk** [adobe/brackets#10845]
If I save the file I can't undo the last modifications, and I still with the file open.

How to reproduce:
1) Make some changes
2) save
3) try to undo

If the file is not saved the undo works fine

Brackets version: Release 1.2 experimental build 1.2.0-15697 (release 8f82e2a97)

**Comment by peterflynn** [comment]
@fazelmk Do you have any sort of background process running that might modify the file, or its timestamp, after saving?  Also, please try _Debug > Reload Without Extensions_ and see if that makes the problem stop.

**Comment by fazelmk** [comment]
Without extensions it works.

**Comment by peterflynn** [comment]
You can follow these steps to narrow down which extension is causing the problem: https://github.com/adobe/brackets/wiki/Troubleshooting#disabling-extensions-individually

**Comment by fazelmk** [comment]
Brackets Git is the one that broke the undo function.

**Comment by peterflynn** [comment]
@fazelmk Can you file a bug with the extension's author [here](https://github.com/zaggino/brackets-git/issues)?  I'll close this since it appears not to be a core Brackets bug.

**Comment by fazelmk** [comment]
Done. And the bug is a change in files timestamp like you said. Caused by the Clear withespace on file save option o brackets-git. If anyone else got this problem. =D

**Comment by peterflynn** [comment]
@fazelmk Definitely file a bug then -- there should be a cleaner way for the extension to do that feature without breaking Undo history.

**Comment by fazelmk** [comment]
I did file a bug report to then using the bug report in the brakets extension. I saw that it was a known bug and I get the option that causes the error from another guy issue report.

**Comment by abose** [comment]
https://github.com/zaggino/brackets-git/issues/958 says its a core issue: any external modifications to a file will clear the undo cache.

**Comment by pramodkumaar** [comment]
Thank's a lot man.. @peterflynn

**Comment by arunroy** [comment]
I had the same issue with AngularJs extension. I had to disable it to get the undo function working.

**Comment by Luk4** [comment]
The extension BracketstoIX creates the same issue. Once disabled, undo-after-save works fine.

**Comment by apptoix** [comment]
I have tested the latest version of Brackets (1.6) and BracketstoIX both in Windows and OSX 10, and in both situations the undo was working after save.
Please, provide details on https://github.com/apptoix/bracketstoix/issues/19, in order to determine which conditions exactly generate this issue.
Also, include if you have any operations defined on "After Save" dialog.

**Comment by rcosgrave** [comment]
Thank you @peterflynn !!!! I should have known
