### ISSUE TITLE
FileFilter match negation

### ISSUE THREAD

**Issue by timseverien** [adobe/brackets#10841]
Sometimes—in fact, most times—I want to replace strings that occurs in only one type of file, for example a CSS file. I’ve been looking for documentation of the Exclusion Set’s syntax which pointed me to FileFilters. I browsed [the code responsible for indexing files](https://github.com/adobe/brackets/blob/master/src/search/FileFilters.js#L204) to see if I could find any undocumented syntax, but I couldn’t find anything, nor could I do a simple pull request. Wildcards (`*`, `**` and `?`) are the only special characters that are being parsed.

I really hoped I wouldn’t have to add all extensions to the list except the one I wish to replace in. Bummer. Could you implement the ability to negate a pattern, please? Something along these lines:

    !*.css  // excludes anything but .css
    !*.scss // excludes anything but .scss

**Comment by peterflynn** [comment]
@timseverien Please upvote this item on our feature backlog: [Find in Files: Inclusive/Additive Filters](https://trello.com/c/9IBv6zRq/1359-find-in-files-inclusive-additive-filters).  I'll close this issue to avoid duplication.

**Comment by timseverien** [comment]
@peterflynn Oh, sorry, I didn’t know it was there. Thanks and upvoted :+1:

**Comment by peterflynn** [comment]
No worries!
