### ISSUE TITLE
Code folding pollutes preferences file with view state

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10846]
1. Collapse a block of code in any file
2. Open brackets.json preferences file

Result: some verbose stuff has been added tracking the code-folding state

We very specifically want to keep transient, less-semantic stuff like this out of the main preferences file -- that's what the separate view state (state.json) file was added for.

Flagging as a priority for 1.3 because it will be a pain to undo the effects of this if we ship 1.3 without fixing this first -- so we probably want to fi this before 1.3 ships.

**Comment by thehogfather** [comment]
@peterflynn @abose is this something you are already working on? or is this something you would like me to sort out?

**Comment by abose** [comment]
we have not started to work on this, I have just started reading through the code to figure out usability and unit test issues.
It would be great if you could submit a fix to this.
Also could you take a look at this #10848?

**Comment by abose** [comment]
We could use PreferencesManager.getViewState("codefolding.states"); and PreferencesManager.setViewState("codefolding.states", state) to store the states into the file.

**Comment by abose** [comment]
Merged PR fixing the issue. Now the fold states are stored in state.json.
