### ISSUE TITLE
brace-fold frequently throws exceptions

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10856]
Put this in a JS file:
```
var test = {
    "foo": {
        "one": true,
        "two": true,
        "three": true
    },
    "bar": false
};
```

1. Select lines 3-5 entirely (i.e. everything inside the foo `{}`s)
2. Press delete

Result: `Uncaught TypeError: Cannot read property 'lastIndexOf' of undefined`

1. Undo
2. Select lines 2-6 entirely (i.e. the entire `"foo": { ... },` block)
3. Press delete

Result: same exception thrown again

Nothing immediately obvious is broken afterwards, but it spams the console and looks bad, so I think we need to fix this for 1.3.

**Comment by peterflynn** [comment]
Other examples:

```
define(function () {
    "use strict";
    
    function one() {
        foo = 1;
    }
    
    function two() {
        foo = 2;
    }
    
});
```

Deleting lines 2-3 will throw an exception.
Deleting lines 4-7 or 4-11 will throw an exception.

```
define(function () {
    "use strict";
    
    var foo;
});
```

Deleting lines 2-3 (or 2-4) even in this very simple case will throw an exception.

**Comment by abose** [comment]
The unit test failures after the code folding integration and this bug has the same root cause.

**Comment by abose** [comment]
Verified the fix, closing.
