### ISSUE TITLE
Fix colour editor for use in browsers that don't use -webkit- prefix

### ISSUE THREAD

**Issue by AJDBenner** [adobe/brackets#10853]
With the fork of Brackets I'm working with right now, located [here](https://github.com/humphd/brackets), we're running Brackets in the browser. Brackets is set up with the `-webkit-` prefix. It would help our use case to allow for other browser prefixes. @le717 has been involved with the discussion in our issue [here](https://github.com/humphd/brackets/issues/150).

**Comment by humphd** [comment]
Some additional context: this bug is about fixing issues specific to the inline color editor, not fixing all `-webkit-*` issues in general.

**Comment by AJDBenner** [comment]
[This PR](https://github.com/adobe/brackets/pull/10854) will fix this issue.

**Comment by petetnt** [comment]
Revamped and fixed finally in #12861
