### ISSUE TITLE
Clicking code folding collapsed marker should expand it

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10858]
1. Click a gutter triangle to collapse a block of code
2. Click the "↔" indicator that appears inline in the code

Result: nothing happens

Expected: in many other editors (though not all), clicking this indicator un-collapses the folded section

**Comment by abose** [comment]
Clicking on the "↔" indicator does expand the folded code; but it doesn't seem to work in all the cases.

**Comment by thehogfather** [comment]
On a somewhat related note, the `cursor: pointer` css rule for `.CodeMirror-foldmarker` in main.less does not seem to have any effect. Cursor still renders as text when one mouses over the collapsed marker.

**Comment by larz0** [comment]
I think this only happens when the collapsed code has a nested collapsable code.

**Comment by MarcelGerber** [comment]
> On a somewhat related note, the cursor: pointer css rule for .CodeMirror-foldmarker in main.less does not seem to have any effect. Cursor still renders as text when one mouses over the collapsed marker.
Our `pointer-events: none` rule causes this problem.

**Comment by nethip** [comment]
PR https://github.com/adobe/brackets/pull/10960 merged. Closing this.
