### ISSUE TITLE
Code folding doesn't play well with View > Line Numbers toggle

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10864]
1. Uncheck _View > Line Numbers_
   - Result: code folding triangles are too close to the left edge of the editor -- need more padding
2. Re-check _View > Line Numbers_
   - Result: code folding is on the _left_ of the line numbers now -- should be to the right

This seems relatively edge-casey, to the point where I could envision shipping 1.3 without fixing this.  I suspect most people who have line numbers hidden will also want folding triangles hidden, and they're unlikely to re-enable line numbers afterward (and issue 2 is easy to work around).

**Comment by VitorLuizC** [comment]
<a href="https://gyazo.com/db7cb0136c4c3ba5ca3649b332c179ac"><img src="https://i.gyazo.com/db7cb0136c4c3ba5ca3649b332c179ac.gif" /></a>

**Comment by petetnt** [comment]
Fixed in #12673

**Comment by zaggino** [comment]
Re-opening as #12673 had to be reverted.

**Comment by ficristo** [comment]
I cannot reproduce anymore. Fixed by #10864
