### ISSUE TITLE
Cleanup CSS

### ISSUE THREAD

**Issue by qdlaczian** [adobe/brackets#10866]
Remove and optimize unused css code and html.

**Comment by prafulVaishnav** [comment]
@qdlaczian Please mention the files in which you have find any unused css and html code

**Comment by qdlaczian** [comment]
I mean plugin or someting else that will find unused css in my HTML project and remove it.

**Comment by prafulVaishnav** [comment]
@qdlaczian Core brackets do not provide this functionality. Though, they are lot of extensions for Brackets. You can get the list [here](https://brackets-registry.aboutweb.com/) and search if any suffice.

**Comment by prafulVaishnav** [comment]
It will be good to have as an extension in the future. Closing it and adding to the Extension Ideas list.

**Comment by qdlaczian** [comment]
Ok. Thanks.

**Comment by peterflynn** [comment]
@ryanstewart I wonder if this is the kind of thing we might be interested in adding to core eventually... seems relatively in the Brackets wheelhouse.  Should we mark this 'move to backlog' and leave open for a while?
