### ISSUE TITLE
Bucket code folding states by project in state.json instead of dumping every thing into one bucket.

### ISSUE THREAD

**Issue by abose** [adobe/brackets#10869]
rather than dumping folding state for all files together in one map, it might make sense to bucket it by project, like we do for other similar prefs like the scroll position & selection state of editors.

MainViewManager has an example of how to do that:

            context = { location : { scope: "user",
                                     layer: "project" } },
            state = PreferencesManager.getViewState(PREFS_NAME, context);
and

            context         = { location : { scope: "user",
                                         layer: "project",
                                         layerID: projectRoot.fullPath } },
        ...
        PreferencesManager.setViewState(PREFS_NAME, state, context);
Add a line note

**Comment by peterflynn** [comment]
Nominating for 1.3 because it would be a pain to change this later...

**Comment by abose** [comment]
PR merged, So closing the issue.
