### ISSUE TITLE
Brackets becomes unresponsive when scrolling brackets.min.css

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#10879]
1. In the Brackets repo, run `grunt build` to generate a new `src/styles/brackets.min.css` (I created mine based on a5a2cd53d5bf9486a3ebf33e715f991a4b3a4c3e)
2. Ensure `View > Word Wrap` is enabled
3. Open the aforementioned file in Brackets
4. Scroll all the way to the end

Result:
Sooner or later, Brackets freezes with the renderer process (not the main process) utilizing around 17-20% of CPU usage.

Windows 8.1, Brackets 1.2 Shell (official), a5a2cd53d5bf9486a3ebf33e715f991a4b3a4c3e.
I reproduced this with a vanilla version of Brackets, without any extensions and with all preferences set to their default (aka first launch).

**Comment by MarcelGerber** [comment]
It's literally an issue with f3644f7e2a97265f8fe56fb37b7240e42edf8b3d. (I `git bisect`ed 3 times to find that, and double-checked the actual culprit, so yeah, it is).

**Comment by le717** [comment]
If this is confirmed to be caused by that commit, I think you just won the weirdest bug origin award.

**Comment by MarcelGerber** [comment]
There are others that qualify, like https://github.com/zaggino/brackets-git/issues/436, but thanks :D

I guess there's something wrong with the way CM measures fonts, and then it's not too obscure.

**Comment by MarcelGerber** [comment]
Interesting. Looking further into this issue, it does not repro when I disable the QuickView default extension.
