### ISSUE TITLE
Minor formatting issue in Health Data dialog

### ISSUE THREAD

**Issue by njx** [adobe/brackets#10876]
On a retina MacBook Pro, the Health Data launch dialog has "Help->Health Data Report" broken across two lines between the "-" and the ">" (see below). I think traditionally we write menu items as "Help > Health Data Report", which would still be broken across two lines but might look better. Also, it might be worth rewriting that line so that the link doesn't get broken up by default.

![image](https://cloud.githubusercontent.com/assets/697759/7093859/98c53aa8-df71-11e4-9e6c-5cb804a1cc9a.png)

**Comment by njx** [comment]
Also, it looks to me like the dialog header is too tall - dunno if this design has changed or if I'm just imagining it. @larz0?

**Comment by ryanstewart** [comment]
Hmm, it looks like the new experience hasn't been checked in yet. We're not going to keep the big dialog on first launch. Instead we're going to do a toast-style notification in the upper right hand corner. I think @prksingh is working on the new experience in a branch but I can't find it at the moment.

**Comment by prksingh** [comment]
I have create a pull request for this at: https://github.com/adobe/brackets/pull/10887 

There is a screenshot in the request showing what it looks like.

**Comment by valtlait** [comment]
@njx You can use non-breaking hyphen to prevent line break between hyphen and greater than sign. In that case, “->” becomes “\u2011>”.

**Comment by njx** [comment]
@valtlait Thanks for the info. In general, though, we've just used ` > ` in documentation that refers to menu items, and I think it looks nicer anyway - it looks less like a fake ASCII arrow and more just like a delimiter.

**Comment by prafulVaishnav** [comment]
Fixed by this [PR](https://github.com/adobe/brackets/pull/10912)
