### ISSUE TITLE
Font looks weird

### ISSUE THREAD

**Issue by afonsomatos** [adobe/brackets#10886]
My font (on the left) looks super weird compared to others I see. How can I make it more anti-aliasing? I've searched in the entire web but the solutions are not clear or don't work.

![image](https://cloud.githubusercontent.com/assets/10373500/7106714/a0fc7196-e142-11e4-91bd-76dd86eeba18.png)
![image](https://cloud.githubusercontent.com/assets/10373500/7106715/a3900a08-e142-11e4-8b5d-561c8fbcbef6.png)

**Comment by abose** [comment]
@afonsomatos Is the problem solved now?

**Comment by afonsomatos** [comment]
@abose Yes, I reinstalled Brackets and It solved the problem. It must had been a file that was replaced or edited.

**Comment by abose** [comment]
:cool:
