### ISSUE TITLE
Code folding doesn't have any unit tests

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10893]
Usually as part of a major feature (in the Trello/Waffle workflow), we're required to add unit tests before calling the feature 'done.'  That hasn't happened yet for code folding.

(Filing this as a placeholder per discussion in #10859)

**Comment by peterflynn** [comment]
Note: these unit tests should include regression tests for the issues fixed in PR #10888

**Comment by nethip** [comment]
We are going to add unit tests in 1.4

**Comment by ryanstewart** [comment]
Moving this to the Release 1.4 planning column.

**Comment by thehogfather** [comment]
Anyone currently working on this? I've got a few  local tests and could send a PR.

**Comment by abose** [comment]
:smile: Would be helpful if you could sumbit the PR. I didn't get time to work on this yet !

**Comment by abose** [comment]
CODE-FOLDIN CAN HAS UNIT TESTS NAO. :smile_cat:
