### ISSUE TITLE
Need help with Grunt for Brackets

### ISSUE THREAD

**Issue by kupoback** [adobe/brackets#10899]
I've posted on the developers repo, however I fear that the developer has abandoned his plugin. 

Essentially, when I have the program detect my grunt file, it see's the functions, and when I click on them to execute, I get "###" and nothing more.

When checking the devtools, I see in the console: 
    
    [node-log 11:14:21 AM] { '0': { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' } } 

However I am unsure what that means or what that does. 

Anyone who is using the plugin, can you help?

**Comment by abose** [comment]
ENOENT = Error NO ENTry, which could mean no such file or directory.
our grunt script could be accessing some non existent file. Have you tried running the grunt script from the command line?
which os are you on? system config?

**Comment by abose** [comment]
We do not maintain extension issues in open state in the brackets repo, so closing this; But we could help with what we know .

**Comment by kupoback** [comment]
I am on Windows 8.1, current Brackets build, and the latest version of Grunt and the extension. Is there anyone who has experience on this?
