### ISSUE TITLE
Base64 encoding crashes

### ISSUE THREAD

**Issue by activenode** [adobe/brackets#10896]
In OSX when opening CSS-Files with big images encoded in Base64 Brackets crashes completely (it does not crash but stand still).

**Comment by prafulVaishnav** [comment]
@activenode What is the size of the file containing the image encoding?

**Comment by abose** [comment]
similar issue #10738

**Comment by activenode** [comment]
Yes and no. I am experiencing this problem with 35kb files! Which is not large at all!

The structure is as follows
.JM_icon-draghandles-white{background-image:url(data:image/png;base64,iVBO ....
.JM_icon-test-white{background-image:url(data:image/png;base64,iVBO ....

**Comment by abose** [comment]
Yes probably the line length would be the issue here. Brackets doesn't handle long lines very well,  issue #10738 describes similar issues with files the the 100KB range.

**Comment by activenode** [comment]
Why is that so? Any reason for that? I totally switched the Editor because we are working with auto-generated icons.css and this breaks the workflow.

**Comment by abose** [comment]
Very sorry to hear that this issue is breaking your workflow. 
I have marked for fixing for the next release. Please give us some time to fix the issue.

**Comment by MarcelGerber** [comment]
@activenode I _think_ my branch (PR #10882) will fix that issue. Would you be willing to try? I could generate a test build for you so you can just replace some files in the Brackets install dir - only if you want, of course.

**Comment by activenode** [comment]
@MarcelGerber I sure will.

**Comment by MarcelGerber** [comment]
@activenode I've created a custom build for you at https://mega.co.nz/#!iEsTlKrJ!HLCCBqLsJ8RoTpeKlrxYLZNEPAHdyJu9eFdGXdPDcug.

1. Download and unzip it
2. When launching Brackets, hold down Shift
3. In the dialog, select `www/index.html` of the unzipped folder

**Comment by activenode** [comment]
I'll give it a try and tell you the experiences the next days.

**Comment by activenode** [comment]
It did not help. Here you go with a file that crashes Brackets: https://gist.github.com/activenode/d1d8706328b7a0bf462c

**Comment by activenode** [comment]
Ok this seems to be not a Bracketsproblem at all. At least not for this example.
This plugin was the reason: https://github.com/Hirse/brackets-outline-list

**Comment by MarcelGerber** [comment]
Could you maybe file an issue with that extension so its developer (@Hirse) can take a look?
