### ISSUE TITLE
Brackets memory keeps increasing on reload

### ISSUE THREAD

**Issue by prksingh** [adobe/brackets#10906]
Over brackets with devtools and *Reload with extensions* every 10 seconds. Monitor brackets memory in Windows task manager. Memory keeps increasing on reload. I could go from ~70MB to ~600MB in 10 reloads.

I can see similar behavior on Mac but much not as bad as windows. Memory increases for Brackets helper on reload but not by much and stops increasing after like 200MB.

Thanks to @SeanJM for reporting

**Comment by nethip** [comment]
I am kind of adding the same labels as present in #8116  & #10779. It would be good to debug it though.

**Comment by SeanJM** [comment]
It would be. Doing a plug in without having to quit brackets and open it after a few reloads would take a bit off my mind.

**Comment by prksingh** [comment]
Closing as a duplicate of #10498
