### ISSUE TITLE
can't use adobe extract - requires internet connection and I am connected....

### ISSUE THREAD

**Issue by silooz** [adobe/brackets#10901]
I am connected to the internet and still get this error when trying to open PSD file.
what is the problem ?
any help would be highly appreciated.

![capture](https://cloud.githubusercontent.com/assets/8035482/7147364/237b86d6-e303-11e4-9d2c-0628aa6b4ca3.JPG)

**Comment by petetnt** [comment]
Related to/Duplicate of #9793

**Comment by silooz** [comment]
I don't think its a duplicate , cause I have internet connection and still the program show this error.

**Comment by petetnt** [comment]
Oh right, should have clarified that I think that it's a firewall issue (which is reported in that issue).

**Comment by silooz** [comment]
thanks a lot! indeed its a firewall issue.

**Comment by prksingh** [comment]
Closing as a duplicate.
