### ISSUE TITLE
Home/End keys goes to beginning/end of line only

### ISSUE THREAD

**Issue by fr32c** [adobe/brackets#10902]
If I want to navigate quickly at the top or bottom of my document, I can't use home or end keys, because they seem to only move within 1 line. I have to type multiple pageUps or pageDowns to achieve the expected result.

This happens on Mac in Version 1.2 édition 1.2.0-15697 (release 8f82e2a97) 
Horodatage de la version : Sun Feb 22 2015 22:34:50 GMT-0800

**Comment by petetnt** [comment]
You can use CTRL+Home/End to jump to top/bottom of the document.

**Comment by abose** [comment]
Closing as brackets already have uniform shortcuts across platforms to scroll to start and end of page.
