### ISSUE TITLE
Uploading to a file system?

### ISSUE THREAD

**Issue by kupoback** [adobe/brackets#10915]
I am working for a web firm who does hosting as well through our own servers. With that, we are networked into those servers and do a lot of local uploads.

Is there a way to set brackets to push a file to that folder on the server, without having to edit from the server? We use Git for repositories, to keep up to date on everything that's been changed.

I can upload to SFTP, to Media Temple, but I can't push to a local server.

**Comment by abose** [comment]
There are many FTP/SFTP extensions available in brackets. Please check if one of those suits your requirement.

**Comment by kupoback** [comment]
I checked out the FTP/SFTP sites however nothing supports what I need. The file system I use is such

    \\ICS-dev-02\var\www\domain.dev.com\filesofdomain

We work off repos, while I can open them directly from the server, it's best if I do it on my own repo. The FTP/SFTP 2 plugins I found do not support those.

**Comment by abose** [comment]
@kupoback the path `\\ICS-dev-02\var\www\domain.dev.com\filesofdomain` looks like an SMB share. You could directly mount the network share in linux/windows and edit the files as if on a local drive. Would this work in your case?

**Comment by kupoback** [comment]
Unfortunately we use Git Repositories, so editing on the local server is not really an option. I mean, yes I can, however, I would have to pull those files onto my desktop and then push them to bitbucket. A bit of extra work. I was merely curious.
