### ISSUE TITLE
[IQE]: A rectangular pop up appears after Health data pop up which vanishes instantly when Bracket is launched for the first time

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#10913]
Steps:
1. Launch Brackets for first time with Cache cleared.

Result: Health Data notification comes followed by a strange pop up that vanishes instantly.

Expected : Only Health Data Notification should pop up.

ENV : Win 7
Build:1.3.0-15958

Note: Screenshot is not available as the pop up box vanishes instantly

**Comment by prafulVaishnav** [comment]
@rawat11 Can you send the screenshot of that strange popup?

**Comment by rawat11** [comment]
@prafulVaishnav - Hope it works.

![image](https://cloud.githubusercontent.com/assets/10069885/7175080/3ff0244e-e42e-11e4-8359-e73e9b052742.png)

**Comment by prafulVaishnav** [comment]
@rawat11 We will not be using this dialog box. Rather, we will be using the pop-up. You can see the conversation on this [PR](https://github.com/adobe/brackets/pull/10912) We will merge the change by tomorrow definitely. This also includes string change.

**Comment by nethip** [comment]
Removing the 1.3 label as we are now going to use popup instead of this dialog.

**Comment by prafulVaishnav** [comment]
Closing this as we don't have this dialog anymore.
