### ISSUE TITLE
Can't use Live Preview

### ISSUE THREAD

**Issue by PandawanFr** [adobe/brackets#10918]
So I updated Brackets a couple days ago. And now when I want to use Live Preview, it asks me for a BASE URL, which I don't want to modify, i just want it to use default, so I searched on google, and apparently, default is localhost, so when i type http://localhost/ and open live preview, I get a chrome error "ERR_CONNECTION_REFUSED"

I am not really experienced with Brackets, sorry if that's easy but I just can't find it in the wiki

**Comment by PandawanFr** [comment]
I tried removing the live-dev folder, removing all baseurl from state.json... Nothing

**Comment by ryanstewart** [comment]
Are you using the experimental live preview or just the default?

**Comment by prafulVaishnav** [comment]
You can find how live preview works [here](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#live-preview) . For any live preview troubleshooting, please try the suggestions given in this [link](https://github.com/adobe/brackets/wiki/Troubleshooting#livedev) Please let us know if you still face any problem.

**Comment by PandawanFr** [comment]
Default, I tried experimental, it just uses safari instead of chrome

**Comment by PandawanFr** [comment]
I know how Live preview was it used to work, but now that I updated, it asks me for a Base URL which I don't want to modify, I just want to use the "no backend logic"

But I don't know how...

**Comment by redmunds** [comment]
@PandawanFr Brackets should only prompt for Base URL for file extensions that it recognizes as server-side files (which are only supported using a Base URL). What's the file extension of your file?

**Comment by PandawanFr** [comment]
php

**Comment by redmunds** [comment]
PHP is "backend logic". Using a local server and specifying Base URL is the only way it works with default live preview.

**Comment by PandawanFr** [comment]
So I have to use html if I want it to be normal? How could I make it work with a BaseURL? When I put localhost, it tells me ERR_CONNECTION_REFUSED

**Comment by redmunds** [comment]
It sounds like you don't have a local server installed or it hasn't been started. Mac comes with a built in server. On Windows, you can use something like WAMP.

**Comment by PandawanFr** [comment]
Whoops, just did something bad...

**Comment by AGNOCKI** [comment]
Yep
-cody


On Apr 17, 2015, at 6:32 PM, PandawanFr <notifications@github.com> wrote:

php

**Comment by PandawanFr** [comment]
?

**Comment by nethip** [comment]
@PandawanFr Is this issue resolved yet?

**Comment by PandawanFr** [comment]
Idk if you could call it resolved or not. I don't know how to setup a custom server, but i understood why it doesn't work... (You should maybe put a hint or a small help on how to setup a custom server on the wiki)

Other than that, yes it is resolved...

**Comment by prafulVaishnav** [comment]
@PandawanFr May be this will help you to [setup custom server]( https://github.com/adobe/brackets/wiki/Brackets-Server-Smoke-Tests#server-setup-macwindows) 

Closing the issue..
