### ISSUE TITLE
Health Data dialog barely readable using dark theme

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#10923]
The dialog currently looks like this with a dark theme applied:
![image](https://cloud.githubusercontent.com/assets/2641501/7203227/546e2132-e519-11e4-968c-62092cb779e5.png)

As you can see, the actual data is gray on gray, so it's barely readble.

**Comment by njx** [comment]
This also happens with other dark themes like Mystique.

**Comment by prafulVaishnav** [comment]
Fixed and merged. Closing it..
