### ISSUE TITLE
Command line should be lowercase

### ISSUE THREAD

**Issue by cfjedimaster** [adobe/brackets#10929]
I can't test this because my Debug menu doesn't have the 'install command line' thing mentioned in the draft release notes, but the command line really should be "Brackets", but "brackets". The capital letter is awkward and will slow folks down when typing.

**Comment by ryanstewart** [comment]
Whoops, that's moved to the _File_ menu and we made it lower case. I'll fix the draft release notes.

**Comment by ryanstewart** [comment]
Updated the release notes and linked the [command line](https://github.com/adobe/brackets/wiki/Command-Line-Tools) wiki correctly. Closing.
