### ISSUE TITLE
Update CodeMirror 

### ISSUE THREAD

**Issue by ryanstewart** [adobe/brackets#10921]
Update code mirror to latest version and fix issues.

**Comment by MarcelGerber** [comment]
I'd like to take this, as well as trying to fix the unit test failures you stated. Is that ok?

**Comment by nethip** [comment]
@MarcelGerber Sure go ahead and continue with the tasks. We were half way through the fixes. @prafulVaishnav Could you chime in here with the SASS issues you were facing when try to update CM to latest version.

**Comment by MarcelGerber** [comment]
I wonder what fixes you're talking about?
For me, one fix (see #11071) sufficed to make everything work as expected. What other issues were you running into?

Are the SASS issues you mentioned related to the CSS Parsing unit test? I've fixed that issue.

**Comment by nethip** [comment]
It could be them but I am not sure as@prafulVaishnav is the one who is actively looking into it.
