### ISSUE TITLE
`brackets` versus `bkts` or Something Smaller for Command Line Tools

### ISSUE THREAD

**Issue by ryanstewart** [adobe/brackets#10932]
In the 1.3 release we're going to be introducing an official [command line tool](https://github.com/adobe/brackets/wiki/Command-Line-Tools) so you can open any file/folder in Brackets from the terminal or command prompt. 

After a bit of discussion the team decided that `brackets` wasn't too long and would be fine as the command to launch it. Other editors have gone with something 4 characters (`mate` or `subl`) and there is an [NPM package](https://www.npmjs.com/package/bkts) which maps to `bkts` on Mac.

The launch is scheduled for next week so we can still make changes and thought it would be worth opening up an issue for discussion. 

So: `brackets`? `bkts`? Something else?

**Comment by hpoom** [comment]
Personally I am a fan of short CLI commands. I like what sublime did with subl. I am also a fan of bkts and have been using it for some time.

I would like to see bkts used.

**Comment by mezpahlan** [comment]
I prefer legibility over short names. With tab auto complete, brackets makes more sense. What if I don't know know the alias? Typing brackets rather than bkts would be more natural to me.

**Comment by johnbillion** [comment]
How about both? `bkts` could be an alias for `brackets`.

**Comment by p4bl1t0** [comment]
I prefer `brackets` over `bkts`. I sometimes had problems remembering commands so the larger one it's more rememberable for me.

**Comment by taggon** [comment]
+1 for `brackets`

**Comment by larz0** [comment]
```brackets```

**Comment by Equinoxdawg** [comment]
As others have said: `brackets`, with the alias`bkts` available, too.

**Comment by abose** [comment]
+1 for `brackets`, with alias `bkts`.

**Comment by stephenkeep** [comment]
As suggested on twitter simply  {}

**Comment by le717** [comment]
I vote for `brackets` with possible `bkts` alias. My reasoning is `bkts` can be hard to remember. Personally, I want to keep typing `brkts` just when typing the shortcut above.

> As suggested on twitter simply `{}`

Yea, that won't happen. :stuck_out_tongue:

**Comment by nethip** [comment]
Thanks for the inputs! I will update the wiki, https://github.com/adobe/brackets/wiki/Command-Line-Arguments, on how to manually create alias to Brackets.

**Comment by omegahm** [comment]
I believe it should be `brackets`. If you want a smaller name, you can alias it yourself:

```bash
alias b="brackets"
alias bkts="brackets"
```

**Comment by sprintr** [comment]
I am using `[]` as an alias to `brackets` on Git Bash.

**Comment by ryanstewart** [comment]
Thanks for the feedback everyone. I'm going to go ahead and close this since we settled on `brackets` and it's pretty straight forward to set up an alias.

**Comment by nethip** [comment]
@omegahm @sprintr That are some interesting aliases. You could now open files and folders through aliases as well. Here are my aliases. I got inspired from @sprintr :smile: and tweaked a little.

```
alias [b]='brackets /c/brackets-source/brackets'
alias [bs]='brackets /c/brackets-source/brackets-shell'
alias [brackets.io]='brackets /c/brackets-maintain/brackets.io'
alias [bu]='brackets /c/brackets-maintain/brackets-updates'
```
