### ISSUE TITLE
Windows: Command line shortcut doesn't work in Git Bash

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#10938]
1. Open Git Bash (Msysgit) on Windows
2. Type `brackets`

Result:
```
sh.exe": brackets: command not found
```
even though it works just fine in cmd (both admin and non-admin)

Expected:
Brackets launches

Problem:
As the Git Bash emulates a Linux/*NIX-like bash, it doesn't interpret `.bat` files, but Brackets only has one of those. That's probably also an issue with cygwin and similar environments.

Possible solution:
Also include a `brackets` file (extensionless) so a bash-like environment can run those.
That's also what [node does for `npm`](https://cloud.githubusercontent.com/assets/2641501/7217266/5ce75f70-e61f-11e4-8095-f4ca2854a6ec.png) and [ruby does for `gem`](https://cloud.githubusercontent.com/assets/2641501/7217268/6be77532-e61f-11e4-823c-fb8d70b8fb64.png).

**Comment by peterflynn** [comment]
We should consider fixing this for 1.3, especially since it seems like the fix might be easy (just add another file in the `command` subfolder that gets installed).

Note: I think it would also work if the file has a .sh extension (without the user needing to type ".sh").  This might be a little more clear since the type of the file is more obvious from its name.

**Comment by nethip** [comment]
@MarcelGerber @peterflynn Sure! Surprisingly issuing `brackets` in GitBash works fine on my system. I will look into this. And thanks for the pointers @MarcelGerber.

**Comment by MarcelGerber** [comment]
@nethip Perhaps you still have the old path (pointing to the installation directory directly rather than the `command` subfolder) included in your PATH?

**Comment by nethip** [comment]
@MarcelGerber I think I still have the Path to 'command' folder on my system. I can check this tomorrow when I get to the office.

**Comment by MarcelGerber** [comment]
Yeah, that's the folder the current installer adds to the PATH, so it's fine.
What I meant was the part added by the old installer.

**Comment by nethip** [comment]
You are right @MarcelGerber. This does not work in GitBash. I am looking into this.

**Comment by nethip** [comment]
This is fixed now with PR https://github.com/adobe/brackets/issues/10938

**Comment by nethip** [comment]
Closing as the PR is now merged.
