### ISSUE TITLE
Loc:JP: The string "Help" should be localized on Brackets Health Report first pop up

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets#10948]
Stteps:
1. Install Brackets on Japanese OS
2. Launch it and Brackets Health Report menu will pop up

Result:
The string "Help" is not localized

Expected result:
The string should be localized

ENV: Mac 10.10 Japanese OS
Build:  Release 1.3 build 1.3.0-15996

Screenshots:
ENU ss:
![en-help](https://cloud.githubusercontent.com/assets/4251563/7225828/62840e82-e6f7-11e4-9d58-8e697ae90e82.png)
JPN ss:
![jp_help](https://cloud.githubusercontent.com/assets/4251563/7225830/692d415e-e6f7-11e4-9245-38f22bc39b93.png)

**Comment by nethip** [comment]
@rawat11 Could you look into this?

**Comment by rawat11** [comment]
Closing the issue, Since the translations are awited.
