### ISSUE TITLE
Loc: JP, FR: Unlocalized string HEALTH_DATA_PREVIEW_INTRO on Brackets Health Report dialog

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets#10949]
Steps:
1. Launch Brackets
2. Click Help > Health Report

Result:
There are unlocalized strings on this dialog. Its string id is HEALTH_DATA_PREVIEW_INTRO.

Expected Result:
The string should be localized. 

ENV: Mac 10.10 JPN and FRA OS
Build: Release 1.3 build 1.3.0-15996 

Screenshots:
Met some problem to upload the screenshot, will try again once it is available.

**Comment by rawat11** [comment]
Closing the issue, since the translations in french are awaited
