### ISSUE TITLE
Editor jumps upward upon cursor-placement when at EOF

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#10941]
1. Open `brackets.js`
2. Scroll all the way down to the bottom
3. Click somewhere in the editor to place the cursor

Result:
The editor shifts a little upward

Possibly a regression of the Code Folding work

**Comment by MarcelGerber** [comment]
`git bisect` points to c3c10de479e4ed1767174ab2c79ed32479a197c0. cc @peterflynn

**Comment by MarcelGerber** [comment]
@peterflynn The issue lies in this line change: https://github.com/adobe/brackets/commit/c3c10de479e4ed1767174ab2c79ed32479a197c0#diff-faf67ee120ecabfc547fc41ee34e0707R33

**Comment by prafulVaishnav** [comment]
@MarcelGerber Thanks a lot Marcel for figuring this out.. You are right it was due to the padding on CodeMirror-foldgutter. Padding was done to keep folded/open marker sync with line number on left.
