### ISSUE TITLE
Health Report *does not work* in release builds

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10959]
1. Download & run the 1.3 prerelease build.  Leave Health Report enabled and then wait.

No data is ever sent.  If you look in dev tools, it's sending POSTs to the local Brackets index.html file instead.

This is because config.json is actually machine-generated and gets overwritten by the build script (see [write-config task](https://github.com/adobe/brackets/blob/master/tasks/write-config.js)).  The health report URL needs to go into brackets.config.json as well, so that when the script regenerates config.json it is preserved.

See discussion in PR #2654, where config.json was introduced, about this exact pitfall :-/

**Comment by prafulVaishnav** [comment]
@peterflynn Thanks a lot Peter for figuring it out before release. I have created [PR](https://github.com/adobe/brackets/pull/10961)

**Comment by prafulVaishnav** [comment]
PR merged so closing it..
