### ISSUE TITLE
Recycle Bin project.

### ISSUE THREAD

**Issue by Equinox** [adobe/brackets#10956]
I'm not sure if it's something you're going to fix in the future or not at all, but if you right click the recycle bin, in the context menu, it shows it available to open as a Brackets project: 

![](http://i.imgur.com/YKxnahW.png)

Other editors like Atom don't offer this same ability, as you can see from the screenshot - so it's either a work in progress removing it or a feature Brackets has over the competition. Using Windows 7 and the 1.3 prerelease version.

**Comment by nethip** [comment]
Good catch @Equinox . Thanks for catching this. I have already made the required changes for this. Would you mind testing the build that I have posted at the following location. Before installing this, please uninstall the already installed Brackets instance.

https://www.dropbox.com/s/001xo6ejgmb7t4i/Brackets%20Release%201.3_ContextMenuChange.zip?dl=0

Let me know if you run into any issues using this build.

**Comment by nethip** [comment]
This is fixed now with PR https://github.com/adobe/brackets/issues/10938

**Comment by Equinox** [comment]
Sorry, I should have commented I wasn't able to switch versions due to a [nasty](https://groups.google.com/forum/#!topic/brackets-dev/63XpRpL7bMg) extension bug I was facing, and since I've for the time being fixed it -- I don't really want to lose it working correctly.

**Comment by nethip** [comment]
@Equinox This is now fixed with 1.3. Closing this.

**Comment by Equinox** [comment]
After removing the 1.3 development version and all other Brackets versions I had, the option was still there. Clicking it gave me an error saying whatever I had clicked on wasn't an application. I've just installed 1.3 release but still the option is there for the rubbish bin. If this is registry related, any idea what I have to remove?

**Comment by Equinox** [comment]
I'm also now getting double of the commands, as per my last comment: ![](http://i.imgur.com/V1YPvuj.png)

**Comment by nethip** [comment]
@equinox this might be happening because of multiple pre release builds as we have renamed and moved the keys. Please delete the flowing entry 

'HKCR/*/Shell/Open with Brackets'

**Comment by Equinox** [comment]
That sadly didn't fix it.

**Comment by Equinox** [comment]
I looked up the location of the registry values before you removed the ability to use commands on the rubbish bin, ie "Root="HKCR" Key="Folder\shell\!(loc.ExplorerFolderOpenContextMenu)\command" deleting the Brackets reference there worked.

**Comment by nethip** [comment]
@Equinox I thought you have this double entry for file context menus. You have to remove it at both the places. I mean at `HKCR\*\Shell\Open With Brackets` and `HKCR\Folder\shell\Open As Brackets Project`(which you had already removed). Could you double check at both the places. Thanks!

**Comment by Equinox** [comment]
I was getting it doubled on all places where it was added (folders, files etc), removing both entries and then reinstalling the release version fixed it and put it back to the expected output: ie the option with the icon (and only one instance).

**Comment by nethip** [comment]
@Equinox Thanks for bearing with us on this. Also we would like to thank you for your testing efforts in making this a solid feature.

**Comment by Equinox** [comment]
It was a pleasure to help! I hang around the IRC channel too and try to help people going there for help. Keep making Brackets by far the best editor and we're even. ;)

**Comment by nethip** [comment]
Sure! :smile:
