### ISSUE TITLE
[Core][Find in Files]: Scroll bar causes the bad layout on Exclusion Set menu 

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets#10963]
Steps:
1. Launch Brackets and open any project
2. Click Find > Find in Files
3. Click the Exclusion Set dropdown button 
4. Click New Exclusion Set button and new several sets (maybe 5~6 sets) to make the scroll bar show
5. Drag the scroll bar to observe the sets name on the dropdown menu

Result:
The line space between different sets is inconsistent and cause the bad layout. If there are many sets, the edit icon for the last set will be on different line with the set.

Expected Result:
The line space should be consistent

ENV: Win8.1 and Mac 10.10 English OS
Build: Release 1.3 build 1.3.0-16008

Screenshots:
![2](https://cloud.githubusercontent.com/assets/4251563/7311355/392ac2aa-e9f0-11e4-8e23-935606379b9d.png)
![3 1](https://cloud.githubusercontent.com/assets/4251563/7311356/39315250-e9f0-11e4-8808-dea4739c46f9.png)

**Comment by MarcelGerber** [comment]
Somehow related to #9305

**Comment by MarcelGerber** [comment]
Fixed in #12671.
Closing.
