### ISSUE TITLE
"SecurityError: the operation is insecure." accessing cssRules in Firefox for different domain

### ISSUE THREAD

**Issue by humphd** [adobe/brackets#10965]
The MultiBrowserImpl Live Dev code expects to be able to access the `cssRules` property for stylesheets in the previewed DOM:
* https://github.com/adobe/brackets/blob/b8f92c1b36c2a15396e36b732d7f3fe52e8f4a8d/src/LiveDevelopment/MultiBrowserImpl/protocol/remote/DocumentObserver.js#L60
* https://github.com/adobe/brackets/blob/0ebf3737b8e2fba8c16dc839326338acd0aac2d2/src/LiveDevelopment/MultiBrowserImpl/protocol/remote/LiveDevProtocolRemote.js#L205

In Chrome, a stylesheet from a different domain will not have `cssRules`, so it is safe to test `sheet.cssRules`.  In Firefox, accessing this property will result in a `SecurityError` and break the remote scripts.

Here's a test case that triggers the problem:

```html
<!doctype html>
<html>
  <head>
  <link href="https://stuff.webmaker.org/webmaker-kits/v2/css/style.css" rel="stylesheet" type="text/css">
  <title>SecurityError Bug</title>
  </head>
  <body>
  </body>
</html>
``` 

The fix is to wrap a `try/catch` around all access to `cssRules` so it always returns `undefined` instead of throwing, for example:

```js
var cssRules;
try {
    cssRules = sheet.cssRules;
} catch(e) {
    if(e.name !== "SecurityError") {
        throw e;
    }
    return;
}
```

cc @busykai

**Comment by busykai** [comment]
@humphd, would you mind submitting a PR? Your suggested fix is doing the right thing.
