### ISSUE TITLE
Is it possible to setup another download site for brackets?

### ISSUE THREAD

**Issue by PeterDaveHello** [adobe/brackets#10972]
Hi, the download speed from the GitHub release page is slow from here(Taiwan), I wonder if brackets can has its own download site for it? If we have rsync protocol to access, it'll be easy to setup a mirror, so we can download brackets faster, thanks!

**Comment by abose** [comment]
Lots of third party websites mirrors brackets installers, a google search for `download brackets` will give lots of alternate download locations.
one i found is.
http://www.softpedia.com/get/Programming/File-Editors/Brackets.shtml#download

Brackets being a community driven project, You could also host brackets mirrors if interested.
