### ISSUE TITLE
French: text appears partially truncated

### ISSUE THREAD

**Issue by Tania-Jiacomini** [adobe/brackets#10986]
Bottom line of second checkbox name is horizontally truncated (for example, bottom part of "p" letters is not displayed). Please adjust layout.

![enu_brackets_001_win_1 3 0-16017](https://cloud.githubusercontent.com/assets/2284774/7297461/5b6f5f14-e9c9-11e4-91ff-e74b3f525bf0.png)
![fr_brackets_001_win_1 3 0-16017](https://cloud.githubusercontent.com/assets/2284774/7297460/5b66a73e-e9c9-11e4-80c2-31efdfb90f39.png)

**Comment by nethip** [comment]
This is now fixed with https://github.com/adobe/brackets-shell/pull/522 . The screen now looks like below.

![frinstallerwindow](https://cloud.githubusercontent.com/assets/1577184/7313753/c18223de-ea7a-11e4-878c-eb4a27446ed4.PNG)

**Comment by Tania-Jiacomini** [comment]
Thanks for fixing the issue, now closing the bug.
