### ISSUE TITLE
French: "Open with Brackets" menu item missing

### ISSUE THREAD

**Issue by Tania-Jiacomini** [adobe/brackets#10987]
See screenshots, "Open with" menu item is not available in French menu.

![enu_brackets_002_win_1 3 0-16017](https://cloud.githubusercontent.com/assets/2284774/7297496/a12c40b2-e9c9-11e4-9c2f-dacccb871fac.png)
![fr_brackets_002_win_1 3 0-16017](https://cloud.githubusercontent.com/assets/2284774/7297495/a12b3b2c-e9c9-11e4-93e8-31484ce8677c.png)

**Comment by nethip** [comment]
@Tania-Jiacomini This is not a bug. I think you installed two versions of the pre-release builds(English). Could you uninstall of versions of Brackets and only have the latest pre-release version. The one which you are seeing in French version are correct.

And about the menus, for folder it is going to be "Open as Brackets Project" and for file it is going to be "Open With Brackets"

**Comment by Tania-Jiacomini** [comment]
Okay, thanks for clarifying! Now closing the bug.
