### ISSUE TITLE
Loc: FR: Some fonts are not clear on Health Data pop up

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets#10982]
Steps:
1. Install Brackets 
2. Launch Brackets at first time, the Health Data menu pops up

Result:
Some fonts in black color and the link in blue color are not clear on the menu.

Expected Result:
All strings should show clearly on UI

ENV: Win8.1 FR and Mac 10.8 FR OS
Build: Release 1.3.0-16017

Notes:
Only reporduces for FR. it looks ok on JP OS

Screenshots:
Will upload the screenshots once it is available.

**Comment by prafulVaishnav** [comment]
@julieyuan Can you please share the screenshot? Health Data popup has blue background color and white text color.

**Comment by julieyuan** [comment]
@prafulVaishnav Uploading the screenshot. I think those strings in black color are not so clear
![health data-fr](https://cloud.githubusercontent.com/assets/4251563/7310972/0d5c5a0e-e9ea-11e4-9ecf-c19af04795c5.png)

**Comment by nethip** [comment]
@julieyuan Thanks for reporting this. The problem was with the translated FR string. I have corrected the string and pushed in the change to `release` branch.

**Comment by nethip** [comment]
https://github.com/adobe/brackets/commit/cd0a6aae5284ff37eca04c7b74b727b09a31852f fixed this.

The Popup now looks like below.

![screen shot 2015-04-24 at 12 06 53 pm](https://cloud.githubusercontent.com/assets/1577184/7313559/caa0f32a-ea78-11e4-80b0-5d0dc7eeb4ad.png)

**Comment by julieyuan** [comment]
Verified with Release 1.3 build 1.3.0-16022. It is fixed and the screenshot is the one offered by nethip. Closed as fixed.
