### ISSUE TITLE
Can't install extensions in brackets  1.2.0-15697 on kubuntu 14.04

### ISSUE THREAD

**Issue by joconnell4** [adobe/brackets#10992]
I can't install extensions, either manually or automatically. Others have reported a similar issue (https://github.com/adobe/brackets/issues/10266), but their solutions haven't help me. 
I have an etc/hosts file and pinging local host returns 127.0.0.1 as the ip address

Developers tools console output:

---

Download the React DevTools for a better development experience: http://fb.me/react-devtools /thirdparty/react.js:4356
[Extension] Error -- could not read native directory: /home/username/.config/Brackets/extensions/user /utils/ExtensionLoader.js:338
NodeSocketTransport - start /LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87
4
Unknown installation error extensionManager domain is undefined /extensibility/Package.js:408

---

I'm a bit new to all of this, but the error seems to suggest that brackets needs the following path/file:
/home/username/.config/Brackets/extensions/user /utils/ExtensionLoader.js:338

However, this file isn't present. The .config/Brackets only has: cef_data (directory) and state.json (file), and that's it.

**Comment by ficristo** [comment]
Were you able to solve your problem?

**Comment by ficristo** [comment]
I close this issue since there wasn't an answer.
