### ISSUE TITLE
New Release Tasks for 1.4

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#10998]
### Checklist for starting a new release cycle

- [x] \( @prafulVaishnav ) All unnecessary branches deleted from GitHub repos.
- [x] \( @prafulVaishnav  ) \(Win) Check Live Development feature(s) with Chrome (beta) - in case a new beta release is available. See also: [googlechromereleases](http://googlechromereleases.blogspot.com/).
- [x]  \( @prafulVaishnav ) \(Mac) Check Live Development feature(s) with Chrome (beta) - in case a new beta release is available. See also: [googlechromereleases](http://googlechromereleases.blogspot.com/).
- [x] \( @nethip )Decide whether to Integrate new CEF
- [x] \( @prafulVaishnav ) Check wiki for spam (MUST do on Mac!)

**Comment by nethip** [comment]
Verified whether we need to pickup the latest branch of CEF. The diff can be found here.

https://bitbucket.org/chromiumembedded/cef/branch/2272?dest=2171

I did not see a compelling reason to update to 2272. Let us just skip updating CEF for this sprint.

**Comment by njx** [comment]
Looks like the checklist item for merging a new upstream CM might be missing?

**Comment by nethip** [comment]
@njx We are tracking this at https://github.com/adobe/brackets/issues/10921. We usually have that as part of the template. I am thinking we would have removed this from here as we are tracking this as a separate card.

**Comment by njx** [comment]
Ah ok - this issue was referenced from adobe/CodeMirror2#91 as the issue where we were tracking the update. Looks like that PR has already been handled anyway.

**Comment by prafulVaishnav** [comment]
We have completed this, so closing it.
