### ISSUE TITLE
[IQE]: Code Folding expand and collapse indicators in JS files comes only for script tags braces, does not come for html tags

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#10994]
Steps To Reproduce :
1. Launch Brackets
2. Open any JS file

Result : Code Folding expand and collapse indicators in JS files is only visible near script tag for functions

Expected Result :  Code Folding expand and collapse indicators in JS files should come for html tags as well.

ENV: Win 7 Eng OS
Build: Brackets 1.3.0-16017

![2015-04-24 10_26_21-a js getting started - brackets](https://cloud.githubusercontent.com/assets/10069885/7312630/7526a234-ea6c-11e4-9a40-d0362888dfd3.png)

**Comment by nethip** [comment]
@rawat11 We don't put in HTML tags in the above form inside a JS file. Are you facing this issue with JS inside an HTML file?

**Comment by rawat11** [comment]
@nethip It is a JS file along with HTML tags.

**Comment by nethip** [comment]
@rawat11 As I said above, we don't put in HTML tags(at least in the format that you are using in) inside JS file. The other way is possible. That is putting the JS code, inside a script tag, inside an HTML file.
