### ISSUE TITLE
File Cacheing causing issues

### ISSUE THREAD

**Issue by RoryPicko** [adobe/brackets#10996]
Brackets caches files that you open and close, so when you reopen a closed file it doesn't load it from disk, which is great when one person is working on a project.

But when working along side another developer on the same files over a network this causes issues, as when I save and close a file, the other developer then opens it his end to make his changes, but its his previous cached version without my changes, and then he overwrites my changes or vice versa.

It would be neat to be able to toggle on/off the file cacheing to allow the file to be read from disk on every load on a per project/folder basis.

**Comment by nethip** [comment]
@RoryPicko When you don't have local changes(or did a Ctrl-S),  Brackets automatically loads these external changes. Am I misunderstanding something?

**Comment by RoryPicko** [comment]
@nethip No, I think you've understood correctly, it's just not what I was experiencing. 

Regardless of when I was saving/closing and re-opening files. Once a file is loaded, you only work from that version on the respected machines, until you close/reopen the brackets IDE. so 2 developers working on the same folder would constantly be overwriting each others changes.

**Comment by abose** [comment]
Brackets do not currently support multiple users editing the same file- in this case, brackets will always reload the file from disk if it finds any changes. This is an expected behavior for now.
But multi-user cursors and workflows can be implemented as an extension. 
Closing as extension idea.
