### ISSUE TITLE
Code folding not working on sass, jade & some others.

### ISSUE THREAD

**Issue by labo-css** [adobe/brackets#11006]
With the past solution (the plugin) they worked well. :/

**Comment by AhoyLemon** [comment]
:+1: 
Yes please. Sass is still folding as it should for me (as is JS & HTML), but I use jade a lot these days and it's a bummer to lose that ability.

**Comment by labo-css** [comment]
Scss syntax? I use sass syntax and it don't work. And jade... ^^'

**Comment by prafulVaishnav** [comment]
@labo-css Can you please elaborate problem in code folding for sass. Is code-folding not working at all for sass file and working with js/html/css ?

**Comment by labo-css** [comment]
It work with css, html but not sass (sass syntax) & jade.

**Comment by AhoyLemon** [comment]
Oh yeah, @labo-css is right. `.scss` folds up nicely, but I made a little test document with the `.sass` syntax and that one doesn't have any fold arrows. Couldn't confirm if `.sass` used to work with the extension, as I've always used `.scss`

**Comment by labo-css** [comment]
Jade & Sass syntax worked well with the extension, and now i can't install it because it is not supposed to work with 1.3.

So... i'm screwed :D

**Comment by thehogfather** [comment]
@labo-css  the extension had the `alwaysUseIndentFold` preference on by default. This preference is off by default in 1.3. In your `.brackets.json` file (either at project or user level) create an entry for `"code-folding.alwaysUseIndentFold": true` and your sass and jade files should get back the fold markers.

Be aware though that this will cause more fold markers to appear in your files - even plain text documents.

**Comment by AhoyLemon** [comment]
Did that, jade is folding as expected now. The odd misinterpreted indentation is possible, but this solves way more problems than it creates, so thanks @thehogfather.

**Comment by labo-css** [comment]
Oh yeah thanx :+1: 
http://cdn.meme.am/instances/22489608.jpg
