### ISSUE TITLE
No Admin Rights

### ISSUE THREAD

**Issue by fernandez954** [adobe/brackets#11005]
I cant get the extensions to work under my profile. I dont have admin rights, is there a way to make the extensions work under my profile? The company I work for has a high level of security. I love using this program at home and would like to be able to use all the extensions at my work place.

**Comment by fernandez954** [comment]
I am running windows 7 professional.

**Comment by rroshan1** [comment]
@fernandez954 Thanks for expressing your love for Brackets. :)
I think I can help you on this. Following are the steps:-
**1.** From your home machine, go to ``Help > Show Extensions Folder``. On Windows, you will be redirected to the "C:\Users\username\AppData\Roaming\Brackets\extensions". 
**2.** Go inside "user" folder and you will see a folder corresponding to each Extension.
**3.** You can just copy the folders equivalent to your favorite extensions from your local machine to that at your workplace. I think you should have the permissions to copy folders as this is inside C:\Users\.

Please share if it helped.

**Comment by abose** [comment]
Closing as inactive. Please reopen if you are still facing this.
