### ISSUE TITLE
Non UTF-8 problem

### ISSUE THREAD

**Issue by JosephNovak** [adobe/brackets#11002]
I have some files that have non UTF-8 code in them.  Brackets will not open them.  How do I fix them if they can't be opened?

**Comment by Equinox** [comment]
You could try opening the file in another editor like notepad or something, removing the offending characters then going back to Brackets. There's also [this](https://github.com/Hiromi-Ayase/brackets-shizimily-multiencoding) extension that might help.

**Comment by rroshan1** [comment]
Thanks @Equinox for the prompt reply. That should solve this issue.
@JosephNovak Closing this issue.
