### ISSUE TITLE
issue installing 1.3 on Windows?

### ISSUE THREAD

**Issue by ohNegative** [adobe/brackets#11003]
I'm having an issue installing the 1.3 version on Windows 7. I've tried several different PC's, on wi-fi, and then on my dedicated internet connection and for some reason it will get to the end of the install and then say "an internal error occurred" and then roll back the install.

Wondering if anybody else is having issues installing 1.3 on Windows 7

P

**Comment by redmunds** [comment]
@ohNegative I just installed 1.3 on Windows 7. Maybe your download was somehow corrupted -- try re-downloading.

**Comment by ohNegative** [comment]
@redmunds Got it. I'll give it another go later this afternoon and then close this if I'm successful. I kind of figured it was something on my end.

P

**Comment by mesosteros** [comment]
I'm also having an issue with installing 1.3 but on Windows 8.1 x64bits... it starts looking for the 1.2 msi installer which is really weird. Is it the same with you?

**Comment by abose** [comment]
@mesosteros where you able to install brackets 1.3?

**Comment by MarcelGerber** [comment]
@abose Yes he was, see #11018.

**Comment by mesosteros** [comment]
@abose yeah. As @MarcelGerber said, check #11018
