### ISSUE TITLE
Formating  and autocomplete for html/css

### ISSUE THREAD

**Issue by ConstantinChirila** [adobe/brackets#11008]
I've been using Brackets a lot, and it's missing some important features that i kinda took it for granted while using Sublime and Visual Studio.
1. The CSS and HTML core is not formatted properly. I mean it does it, but it does it poorly.
2. Autocomplete (for a lack of a better word) is not that efficient. For example:
In sublime when you create a div/h/p/header/body/etc you g about and write "div" hit tab and you get <div>'with cursor inside here'</div>
3. In CSS or JS it does not auto close parentheses or square/curly brackets.

These are some of the features that me personally (and from what i read in other blogs) slowed me down while using Brackets.
I tried to read amongst feature requests on Trello and couldn't find someone that  did this, but if i repeated this i do apologise. 
Quite new to this whole github/community build software etc.

**Comment by nethip** [comment]
@ConstantinChirila 

* CSS and HTML core formatting: Have you tried this extension. https://github.com/drewhamlett/brackets-beautify. We are in the process of prioritizing this item.

* Autocomplete: Have you tried the emmet extension for Brackets. It give you something what you are asking for, though it is completely meant to be used for inserting emmet code hints, which I think is pretty awesome.

* I have create a trello card for autoclosing parentheses or square/curly brackets at https://trello.com/c/27bkKWdp/1419-autoclose-parentheses-or-square-curly-brackets . Please upvote this card.

**Comment by Equinox** [comment]
On the topic of 'auto-complete': you can also use this [snippets extensions](https://github.com/chuyik/brackets-snippets) for exactly that. I recently moved all the functions and code that I have to write many times over to a snippet and it's extremely easy to manage, document and use. So the choice is yours in that respect.

**Comment by ConstantinChirila** [comment]
@nethip Thank you!
I have just tried emmet, it is the best solution for it, but it's a bit crude as in if you hit tab after any word, it would take that and wrap it like ca = <car></car>... and so on. 
Regarding the beautify, it seams to work so far. Thanks!

@Equinox 
This is dead on what i need, i guess now it's a matter of keeping adding the snippets.
Thank you!

**Comment by redmunds** [comment]
Autoclose functionality is provided in core Brackets, but you have to enable it at *Edit > Auto Close Braces*.

**Comment by nethip** [comment]
@redmunds Duh! I completely forgot we had this built into Brackets. Thanks for pointing out :smile: I have closed the trello card too.

**Comment by mittalyashu** [comment]
Any package which can suggest the relevant code snippets while typing?
