### ISSUE TITLE
Code folding hideUntilMouseover broken

### ISSUE THREAD

**Issue by cheesypoof** [adobe/brackets#11017]
Is the pref `code-folding.hideUntilMouseover` actually working properly for anyone else? I am only able to trigger this over what seems like a 1px-wide area that extends along the gutter (visualized below in red). When my cursor is anywhere else in the gutter, the folding arrows are still hidden...

![hitbox](https://cloud.githubusercontent.com/assets/2069528/7385740/d9c837f2-edff-11e4-8967-59bdd1b3711f.png)

**Comment by thehogfather** [comment]
@cheesypoof do you by any chance have brackets-git extension installed? Or any other extension that uses the gutter? The issue sounds similar to the one reported [here](https://github.com/thehogfather/brackets-code-folding/issues/121).

**Comment by cheesypoof** [comment]
Yes, I do have brackets-git installed. I should have taken a few seconds to test this without extensions - palm meet face. I thought that since I didn't have "Use Git gutter marks" enabled, the extension was unlikely to be the culprit. There obviously is a conflict though - the same issue as the one you referenced. Thanks @thehogfather.

Closing as an extension issue. See zaggino/brackets-git#1019.
