### ISSUE TITLE
Version 1.3 Installation issue on Windows 8.1

### ISSUE THREAD

**Issue by mesosteros** [adobe/brackets#11018]
I'm trying to upgrade from 1.2 on a Windows 8.1 x64 bits. The installer keeps asking me... for the 1.2 msi installer?

![brackets](https://cloud.githubusercontent.com/assets/1943233/7388162/0b109d8a-ee5b-11e4-8736-b87c1dd8b416.jpg)

**Comment by nethip** [comment]
@mesosteros Hmm. looks like the, remove existing installation, phase of the installer is failing. I would suggest running Brackets 1.2 installer again which is going to remove the existing 1.2 installation and then re-run Brackets 1.3 installer.

The following posts have some info about this issue as well.

https://support.microsoft.com/en-us/kb/258847
http://answers.microsoft.com/en-us/protect/forum/mse-protect_start/the-feature-you-are-trying-to-use-is-in-a-network/80d4be22-aab6-47f0-a7dc-8a3131fc8df0

**Comment by mesosteros** [comment]
Thanks @nethip , I was just coming here to close this: I solved it last night by downloading the Brackets 1.2 installer and then when I ran 1.3 it automatically found 1.2 and ran it to uninstall that version and update to the new one.
