### ISSUE TITLE
Дерево проекта.

### ISSUE THREAD

**Issue by IDrakon** [adobe/brackets#11026]
sprint 3 build 1.3.0-16022 (release cd0a6aae5) 
Нельзя перетаскивать файлы в дереве проекта мышкой.

**Comment by abose** [comment]
you cannot currently drag and drop files in the file tree. Please upvote this feature in trello at https://trello.com/c/0WJ1aKw2/287-5-drag-drop-within-file-tree-copy-move-file if you want this in brackets. Popular requests usually gets implemented. closing the issue.

**Comment by IDrakon** [comment]
+1
