### ISSUE TITLE
right click on an empty space selects the last word on line. [ Контекстное меню.]

### ISSUE THREAD

**Issue by IgorNovozhilov** [adobe/brackets#11027]
sprint 3 build 1.3.0-16022 (release cd0a6aae5) 

Oh yes got it now, also writing the description in English. 
On any file, right-click on an empty space, this selects the last word in the line. no word should be selected in the case and the right click context should be appropriately handled.

Если кликать правой кнопкой мыши, в окне редактирования файла, в пустое место окна то выделяется последнее слово в строке. Выделение при клике правой кнопкой мыши должно происходить только при клике на само слово.

**Comment by abose** [comment]
Щелкните правой кнопкой мыши выберет слово под курсором мыши в скобках . Ожидается, что это . Быстрые документы и другие функциональные затем будет направлена ​​на выбранном слове .
Я перевел это на русский с Google Translate . извините , если есть какие-либо ошибки .
закрыть вопрос .

**Comment by IDrakon** [comment]
Клик происходит не по слову под курсором а в пустое место.
-1

**Comment by IgorNovozhilov** [comment]
неактуально
