### ISSUE TITLE
Brackets + Angular JS + Jasmine

### ISSUE THREAD

**Issue by alaksandarjesus** [adobe/brackets#11025]
I am facing trouble while running angularjs unit test with Jasmine. The detailed description can be found in    http://stackoverflow.com/questions/29960928/angularjs-jasmine-unit-test/29961759#29961759

Just want to confirm whether brackets was overriding Jasmine as commented.

P.S:  If i test simple javascript it works. But not with angularjs.

**Comment by ficristo** [comment]
Based on the stackoverflow link it seems to me you were using some extensions.
It is possible that one of them was culprit.
If you still have problems, please open a new issue.
