### ISSUE TITLE
Unable to see 'dist' folders

### ISSUE THREAD

**Issue by apricot13** [adobe/brackets#11029]
Using bower if I install jquery I cannot see the dist folder in the file tree and its not picked up in my HTML either when adding the script tags. 

This is the case for all folders called dist. I have to open it in finder and drag and drop the file to be able to view it! 

![capture](https://cloud.githubusercontent.com/assets/649148/7413942/6b8ee954-ef47-11e4-8108-6b649e665866.JPG)

I'm running windows 8 
Brackets: 
Release 1.3 build 1.3.0-16022 (release cd0a6aae5) 
build timestamp: Wed Apr 29 2015 11:07:50 GMT+0100

**Comment by abose** [comment]
Works in my machine :tm: .
Could you goto 'debug menu>reload without extensions'  and see if the problem persists?

**Comment by MiguelCastillo** [comment]
@apricot13 do you the extension File Tree Exclude?

**Comment by Rodsevich** [comment]
I had the same "problem", and it was an extension hiding it

**Comment by ficristo** [comment]
Closing as most likely an extension behaviour.
