### ISSUE TITLE
Typing } in CSS file does not preserve indent

### ISSUE THREAD

**Issue by edgaa** [adobe/brackets#11037]
All of the sudden, when I enter following:

```css
.an-element{}
     .an-element1{
```

the moment I enter } I'm getting

```css
.an-element{}
.an-element1{}
```

How can I keep the indentation?

Same happens when I press ENTER

**Comment by nethip** [comment]
@edgaa You could disable smart indent by changing this preference. 

`"smartIndent": false`

Use *Debug->Open Preference File* to open preference file and add following code.
```
{
  `"smartIndent": false`
}
```

**Comment by edgaa** [comment]
Thanks that worked.. don't know why it would suddenly be changed though.. could be an extension?

**Comment by prafulVaishnav** [comment]
@edgaa Brackets auto-indent when you pressed `}`  Setting `smartIndet: false` will disable the indentation across all the files.
