### ISSUE TITLE
Cannot launch brackets 1.3.0.0 - Windows 8.1

### ISSUE THREAD

**Issue by javilopezc** [adobe/brackets#11039]
It was working ok a few days ago, and suddenly could not launch it anymore.

Before positing this issue I followed the instructions to clear cache as indicated in the [Brackets not launching](https://github.com/adobe/brackets/wiki/Troubleshooting#launching) Troubleshooting section, but to no avail.

The Windows Event log error indicates that the `libcef.dll` module is the one with errors.
 
Here is [the gist](https://gist.github.com/javilopezc/40a7c34ba98d94a65658) containing the data obtained from the Windows Event Error Log.

A screenshot about windows event error log follows:
![image](https://cloud.githubusercontent.com/assets/3148402/7438522/7c7c4c06-f033-11e4-9624-7fcf612b7995.png)

This is an image of the location in which brackets is installed:
C:\Program Files (x86)\Brackets
![image](https://cloud.githubusercontent.com/assets/3148402/7438686/48052d14-f036-11e4-96b1-aa7a783a5107.png)

This is the image showing the brackets extensions installed:

![image](https://cloud.githubusercontent.com/assets/3148402/7438421/13180e4a-f032-11e4-864a-798134c18293.png)
I had these extensions installed before upgrading from brackets 1.2.x.x, with the notable mention that the code folding extension (and one other more I don't recall) was included by default in new version 1.3.0.0.

A zipped copy of the faulty dll can be downloaded [from here](https://www.dropbox.com/s/v3jprgiotn19kvd/libcef.zip?dl=0). 

Another notable mention is that I installed (and later in time upgraded) brackets using the cinst command from the Chocolatey install package manager.

**Comment by ryanstewart** [comment]
If you try clearing out the `AppData/Roaming/Brackets/cef_data` folder, does that help?

**Comment by javilopezc** [comment]
I cleared out the `cef_data` folder as mentioned in the `Brackets not launching` section in the ` Troubleshooting` page, which I referenced in the original issue.
It did not help.

**Comment by nethip** [comment]
@javilopezc Looks like the installation did not go fine and it ended up with corrupt `libcef.dll`. 

Could you re-download 1.3 installer from https://bracket.io and run the installer again. 
Note: Please uninstall existing instance of Brackets before going through the above step.

**Comment by webteckie** [comment]
I too cannot install Brackets 1.3 in my windows 7 box.  At some point it complains that I have insufficient privileges even though I'm running the install as admin.  Hasn't been a problem before.

**Comment by prksingh** [comment]
@webteckie Were you able to install brackets? @nethip  Could be an installer issue. We have made changes to the windows installer for 1.3

**Comment by nethip** [comment]
@webteckie Could you uninstall and reinstall Brackets again?  

@prksingh The changes I have done are to do with adding optional check boxes. But that is not going to effect the overall installation as such. Installers are usually run in admin mode and that is what we are doing with our Brackets installers.

**Comment by webteckie** [comment]
@nethip just tried on my work laptop with win8.1 and worked fine.  Will try in my home PC with win7 later today and update.

**Comment by webteckie** [comment]
@prksingh @nethip confirming that win7-pro is all good as well.

**Comment by prksingh** [comment]
Glad to hear that. Closing the issue. Will reopen in case this is seen again
