### ISSUE TITLE
RPM distro?

### ISSUE THREAD

**Issue by mab9824** [adobe/brackets#11032]
It would be good to have RPM or other distro suitable for RedHat/Centos.

**Comment by dacrhu** [comment]
https://copr.fedoraproject.org/coprs/dacr/brackets/

I think you can build RPM to Centos too.

**Comment by abose** [comment]
RPM distros is not in our current roadmap for brackets. However, it would be awesome if you could contribute to the RPM install scripts for linux :gift: . An introduction for generating our installers could be found at https://github.com/adobe/brackets/wiki/Building-Brackets-Releases. Closing and moving to backlog.
