### ISSUE TITLE
keymap.json not working properly

### ISSUE THREAD

**Issue by ntkog** [adobe/brackets#11034]
When i try to remap some keys for default extensions (codefolding ) it doesn't override the shorcut , instead it creates an alias ,

Take a look : 

![screen shot 2015-05-01 at 13 33 10](https://cloud.githubusercontent.com/assets/1333901/7429748/b40aa068-f007-11e4-9d2f-e299791ff8f7.png)

**Platform : OSX Yosemite 10.10.1

**Comment by redmunds** [comment]
That's correct because you can have multiple shortcuts for a command. To remove a shortcut, set it to `null`.

**Comment by ntkog** [comment]
Ok thanks, a lot for the explanation.
