### ISSUE TITLE
Working Files closing issue.

### ISSUE THREAD

**Issue by the-simian** [adobe/brackets#11045]
Closing an Item in the Working files and choosing 'dont save' does not close the file. It works identically to cancel.

Steps to reproduce:
1. Open a file
2. Alter it. A little dot appears to the left of the unsaved file.
3. You change your mind, lets just close that file.
4. Click the x, a popup appears "save, don't save and cancel"
5. select "don't save". Nothing happens. It is the same as choosing the cancel button. It was expected the file would close, discarding your changes.

**Comment by rroshan1** [comment]
@the-simian I do NOT see the issue!!   For me, it works as one would expect it to.
Can you please share the OS and version of Brackets you are using. 
You can try reloading without extensions OR try after deleting your preferences. Refer [Troubleshooting](https://github.com/adobe/brackets/wiki/Troubleshooting#other).

**Comment by the-simian** [comment]
Its possible an extension is interfering. I am using Windows and version 1.3.0. 

I'll audit my extensions. I'll close the issue, then. Thanks for confirming!

**Comment by tofanelli** [comment]
Actually I was opening an issue just like that but searched before post....

Well, I do have this same behavior in my as well.
Yes, I already reload it with no extensions, and still having this same behavior
Yes, I already did a fresh install, same error
Yes, nothing on console
Yes, this is driving me crazy


And, another issue I could noticed is, sometime a dozen of files randomly open with anyone asked to open them, and stay on my open files as if i alter them and they are waiting to be saved and closed, and as long I cannot click in ""don't save"" and expect them to be closed with no changes at all, I'm forced to click in "Save" and really hope to have no changes at all in that file.


How can i proceed to help you guys?



cheers =)

**Comment by the-simian** [comment]
@tofanelli : I had to switch to atom. It was unuseable

**Comment by ficristo** [comment]
Keep in mind that uninstalling Brackets doesn't remove everything. See https://github.com/adobe/brackets/wiki/Cache-Folder
You could take a backup of your extensions before remove that folder, so you can copy them back without reinstalling all of them.

**Comment by tofanelli** [comment]
@the-simian .... unfortunately i'm trying Sublime now... i personally didn't liked Atom.... i don't know why... if anything works as intended, i will give a shot on VS Code.... I've been heard good words from it =)

@ficristo .... Sorry about misunderstanding, but when I said "Yes, I already did a fresh install, same error", i was talking about a real fresh one.... I installed windows from scratch... and still got this same error... 

Even on its latest version i still experiencing this behavior. Using Windows 8.1 english fully updated. 


Cheers =D
