### ISSUE TITLE
Switch Case Code Folding

### ISSUE THREAD

**Issue by designcise** [adobe/brackets#11048]
Case code block (ending with break, continue, return etc.) inside a switch statement cannot be folded in v1.3

**Comment by prafulVaishnav** [comment]
@designcise Please set the preference `"code-folding.alwaysUseIndentFold": true` in the preference file (`Debug->Open Preference File` ). It is by default off to avoid too many code fold markers.

**Comment by designcise** [comment]
Thanks, that works! Can we expect to see this implemented as an option in settings sometime later?

**Comment by ryanstewart** [comment]
@designcise I don't think we'll make it a checkmark but I am hoping in the next release we do something better around exposing preferences so that it's easier to change.

I'll go ahead and close this now since it's resolved, but will create a card for preferences.
