### ISSUE TITLE
add possibility to replace with new line

### ISSUE THREAD

**Issue by yahyaKacem** [adobe/brackets#11041]
Hi, I'm on Ubuntu 14.04 using Release 1.3 experimental build 1.3.0-16022 is it possible to search for a string and replace it with line return, like this,
original:

    azerty, qwerty

expected result:

    azerty,
    qwerty

so search for `', '` and replace with `',\n'` or `',\r'` do it this will result in `azerty,\nqwerty` or `azerty,\rqwerty` 

also can write multi-line replace string or search string in the search boxes.

**Comment by prafulVaishnav** [comment]
@yahyaKacem No. Its not possible currently to include newline in replace string. Although you can use newline in search. Information is given [here](https://trello.com/c/yho8jb7y/1082-find-replace-allow-matching-across-lines-n-or-multiline-regex-or-replacement-text-containing-newlines) We have feature backlog for this. Please upvote [here](https://trello.com/c/yho8jb7y/1082-find-replace-allow-matching-across-lines-n-or-multiline-regex-or-replacement-text-containing-newlines) to help in picking this feature. Similar to issue #8093 . Closing this
