### ISSUE TITLE
[CEF 2171][Linux only] Upgrade Linux app-shell's to use CEF 2171

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#11047]
Upgrade app-shell CEF version to 2171 on Linux. I am creating this placeholder card to track the following issues.

https://github.com/adobe/brackets/issues/4611
https://github.com/adobe/brackets/issues/10231
https://github.com/adobe/brackets-shell/pull/503
https://github.com/adobe/brackets-shell/pull/501
https://github.com/adobe/brackets-shell/pull/499
https://github.com/adobe/brackets-shell/pull/458
https://github.com/adobe/brackets-shell/pull/483
https://github.com/adobe/brackets-shell/pull/491
https://github.com/adobe/brackets/issues/10255

All of these issues are related to upgrading CEF on linux to 2171

**Comment by FriendOfFatBeagle** [comment]
I have this problem here:
https://github.com/adobe/brackets/issues/11161

Why not make the extension manager dialog box as part of a tab view?

**Comment by Fordi** [comment]
I'd like to help.

On Windows, brackets was my primary non-IDE editor for a long while, and I'd like to go back to using it now I'm on a linux box.  The lack of command-line control and preservation of basic state is essentially what's preventing me from making the switch from Geany.  If I can help clear this migration, I'll fork, do the thing, and create a pull request appropriately.

Can you (nethip or rroshan1) comment as to the set of issues regarding migration to CEF 2171, as well as any ancillary concerns you have?  I'd like to avoid re-analyzing the problem where it might have already been sussed, and to have a fair idea of what you want to accomplish that's not implied with the basic CEF upgrade.

**Comment by nethip** [comment]
@Fordi We really appreciate your help on this! 

About the issue; After upgrading to CEF 2171 on Linux, we are getting intermittent crashes while quitting. Just launch brackets with CEF 2171 and then quit and you should see the crash in the terminal. We spent some time on this with our own theories :smile: but did not land with a clean solution. `brackets-shell`, a thin wrapper around CEF, is based out of `cefclient`, the sample app packaged as part of `CEF`. We are currently using the code from `cefclient` that was packaged as part of older version of CEF. My guess is, we have not moved our code to latest version of `cefclient`. So carefully examining all the methods of `cefclient`, which is based out of `CEF 2171` and comparing that with `brackets-shell` should lead us somewhere. If I were you, I would probably start fresh by taking `cefclient` as a base and would start adding `brackets-shell` code piece by piece to nail the problem. But that's just me. Maybe there is a better way to figure out the issue and fix it. By the way all of the work in happening on this branch `jasonsanjose/cef_2171_linux` in `brackets-shell` repository. Do let me know if you require any more information on this. Thanks!

**Comment by ficristo** [comment]
Fixed. See https://github.com/adobe/brackets-shell/pull/619
