### ISSUE TITLE
HAML not folding in Brackets 1.3

### ISSUE THREAD

**Issue by unyo** [adobe/brackets#11050]
HAML does not fold in Brackets 1.3. I'm reverting to 1.2 since the code folding extension (https://github.com/thehogfather/brackets-code-folding) allows folding HAML.

**Comment by petetnt** [comment]
Try setting `code-folding.alwaysUseIndentFold: true` on your Preferences file (Debug -> Open Preferences File)

**Comment by unyo** [comment]
Thank you, that worked.
