### ISSUE TITLE
Add Performance Metrics to Health Data Report

### ISSUE THREAD

**Issue by ryanstewart** [adobe/brackets#11055]
Add performance-specific metrics to the [Health Data Report](https://github.com/adobe/brackets/wiki/Health-Data). Things we want to start tracking:

- [x] Startup Time
- [x] Average File Switching Time
- [x] Project Size (number of files)
- [x] Type of file(s) opened in Brackets

**Comment by abose** [comment]
Closing as all events will now be registered.
