### ISSUE TITLE
unable to launch custom brackets.exe

### ISSUE THREAD

**Issue by 2007ay** [adobe/brackets#11058]
Hi,
I have created a desktop app using brackets-shell version sprint-38. I have done the following changes.

 1. config.h -changed APP_NAME from 'Brackets' to 'MyBrackets'.
 2. appshell_config.gypi - changed appname from 'Brackets' to 'MyBrackets'.
 3. Gruntfile - changed build.name from 'Brackets' to 'MyBrackets'. 

After building brackets-shell with these changes i used to get 'MyBrackets.exe'
inside brackets-shell/release folder. 
while executing the exe one file chooser popup comes, and node & MyBrackets.exe processes will start in the background. 
this works fine with Sprint-38,But after migrating to brackets-shell tag version release-1.3 or master, this dose not work. The file chooser is not coming as well as no node process starts. 
Is any thing i am missing with the latest release ?

**Comment by nethip** [comment]
@2007ay We have not changed anything much in our shell code in 1.3. Make sure you do not have any `Brackets.exe` process running in the background. 

Also could you try rebuilding Brackets shell by cleaning the existing build and by building it again. If you are still not able to get this running, then the you could see what is happening using the debugger. Put a breakpoint at this place `cefclient_win.cpp:175`, start debugging brackets from Visual Studio, and see where exactly it is quitting. You can post me the results and I can help you with where exactly it might be breaking.

**Comment by 2007ay** [comment]
I got the problem. actually xcopy command is not generating properly in MyBrackets.vscsproj file. and this is well know problem i think so. To fix this problem one fix-msvc.sh file has written.

Since brackets.vscsproj name is hardcoded here so changes is not reflecting in my MyBrackets.vscsproj

Basically In fix-msvc.sh need to change brackets.vcxproj to <appname>.vsxproj . 
since this is hard coded
