### ISSUE TITLE
Improve Preferences Experience

### ISSUE THREAD

**Issue by ryanstewart** [adobe/brackets#11056]
# Background
Until now we've kept the preferences menu item disabled because we'd planned on doing a more robust UI around preferences. But in the few years that Brackets has been around, more and more editors have adopted the JSON file as a preference and in general our users seem comfortable with that approach.

# Proposal
* Enable the Preferences menu item in the default menu on Mac and Windows
* Show *all* of the available preference items in the brackets.json file with their default values. (So it's easier for users to change them)
* Make sure the [preferences documentation](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences) is up to date

**Comment by ryanstewart** [comment]
@prafulVaishnav @nethip @rroshan1 Would it be possible to add a `"documentation"` property to `brackets.json` that points to our documentation?

I know JSON doesn't support comments so we can't show something like:

`\\ Go here for documentation` 

But could we do something like:

`{
   "documentation":"https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences"
    "steelbisondev.fixmyjs.on_save": false,
    "linting.collapsed": true,
    "linting.enabled": false,
    "BracketsNewProjectExtension.newProjectsFolder": "/Users/ryanstewart/Library/Application Support/Brackets/extensions/user",
    "livedev.multibrowser": true,
    "me.drewh.jsbeautify.on_save": false,
    "themes.theme": "light-theme",
    "fonts.fontSize": "11px",
    "wordWrap": false
}
`

And just ignore that property? Is that clear enough for users who want to know more about preferences?

**Comment by nethip** [comment]
:+1: 

@ryanstewart About documentation, we could do that.

**Comment by sprintr** [comment]
I am going to submit a PR to allow code hints for preferences next week.

@ryanstewart I was thinking about adding a little description of each preference beneath it when it is active.

**Comment by ryanstewart** [comment]
@sprintr yes! The code hints PR would be awesome!

**Comment by rroshan1** [comment]
@sprintr :+1:

**Comment by sprintr** [comment]
The PR for code hints is #11130

**Comment by TomMalbran** [comment]
Should we consider shipping with a JSON lint extension and warn users that the preference will not work if there are errors in the file.

I also find it as a bad user experience that after the popup saying that there is an error in preference, fixing that error, saving the file, it doesn't switches to the preference file and I have to reload to trigger it.

**Comment by mackenza** [comment]
@TomMalbran I get the preferences file opened when it loads Brackets and there is an error in JSON.

I don't know about adding JSON lint tool by default, but it might be good to do the JSON file verification on save rather than waiting for a reload.

**Comment by TomMalbran** [comment]
@mackenza I mean that the file is displayed for me to fix it. I fix the error and save the file. But now I need to reload to see the preferences being applied.

We can have it both ways. Verify the JSON file on save and show me where are the errors. Which is kind of having JSON lint just for the preference files on save. For people that don't know much about JSON it might be hard to find the errors, or know why the file is broken.
