### ISSUE TITLE
How can I generate a .ai file？

### ISSUE THREAD

**Issue by GisKook** [adobe/brackets#11052]
Hello,
    I am sorry for ask such a question here.But I have no place to ask.How can I generate a .ai file with a stand alone program?Is it possible?Is there any open source library to write .ai file?What is the different between .ai and .pgf file.If I bother you.I am really sorry.Or can you tell me where should I ask this question?
Thanks,
zhangkai

**Comment by rroshan1** [comment]
Sorry, we may not be able to help you on this unrelated question.
Still, see if this helps you [http://en.wikipedia.org/wiki/Adobe_Illustrator_Artwork#Programs_that_support_AI_files](http://en.wikipedia.org/wiki/Adobe_Illustrator_Artwork#Programs_that_support_AI_files).
