### ISSUE TITLE
Ugly cyrillic fonts

### ISSUE THREAD

**Issue by akaRem** [adobe/brackets#11060]
Cyrillic fonts are ugly

**Comment by abose** [comment]
can you provide a screenshot?

**Comment by akaRem** [comment]
@abose Sorry, but no. After 15min of using brackets, I've decided to remove it (ugly, slow, partially localized, etc). :-(

About fonts.
The problem was that text in editor pane was looking like this:

~~~
<tag> English text. R  u  s  s  i  a  n    t  e  x  t .  <tag> English text. </tag>  R  u  s  s  i  a  n    t  e  x  t  with some english phrase  c  o  n  t  i  n  u  e  d    <tag>  w  i  t  h </tag>    R  u  s  s  i  a  n. </tag>
~~~

**Comment by MarcelGerber** [comment]
@abose See https://github.com/adobe/brackets/issues/3465 for a screenshot and a workaround.
That's the corresponding issue, I guess.

@akaRem Could you give us more informations on the speed issue? How big was your project, which features did you use, where would you like the performance to improve (e.g. startup, scrolling)?
Your feedback would be very valuable and much appreciated!

Unfortunately, we can't do much about the half-localized UI. Russian translation is done by open source contributors, so the translations aren't updated regularly.

**Comment by akaRem** [comment]
@abose looked at #3465 — same thing. I'll close this issue.

@MarcelGerber 
I didn't work with my project and didn't use any features. I've installed and started this app, horrified about fonts, then I googled for 3-5 minutes on how to fix it, installed extension, which promised to fix this by choosing another font. In readme it was said, that some menu should appear, but it did not (or I didn't find it). By the way I installed few plugins. Restarted the app, but nothing did changed.
Tried another themes, fonts, etc. It was still ugly.

Brackets is NOT slow app, but brings overall feeling of laggy, which is annoying a little bit:
laggy scroll, laggy plugins window opening. waiting for plugin to be installed (why not to do it in foreground?), etc.

When I started to hate this app (in 15 min), I've just removed it.

----

I've installed it one more time, and hate it even more...

on mouseover there is preview:
![2015-05-08 0 24 54](https://cloud.githubusercontent.com/assets/1472728/7526243/b1268540-f518-11e4-82bb-792b6a556938.png)
What is it for? It's small, but on hover it disappears, I can't click/resize/whatever..

Translation is not about plugins:
here i see translated text
![2015-05-08 0 29 32](https://cloud.githubusercontent.com/assets/1472728/7526333/520a4aa0-f519-11e4-9f7d-3f3039abb5c3.png)
![2015-05-08 0 31 08](https://cloud.githubusercontent.com/assets/1472728/7526364/97d565d8-f519-11e4-86a6-73db639a604d.png)

**Comment by akaRem** [comment]
here i dont:
![2015-05-08 0 30 25](https://cloud.githubusercontent.com/assets/1472728/7526448/41bc58e0-f51a-11e4-938f-2071961bd5e3.png)
![2015-05-08 0 30 33](https://cloud.githubusercontent.com/assets/1472728/7526451/47e0c030-f51a-11e4-8edb-ccfcb6466fb0.png)
![2015-05-08 0 30 45](https://cloud.githubusercontent.com/assets/1472728/7526456/4ced4756-f51a-11e4-9bee-1b83c8204786.png)
![2015-05-08 0 30 20](https://cloud.githubusercontent.com/assets/1472728/7526458/52c19f74-f51a-11e4-92c1-57fdbf56f60d.png)

**Comment by akaRem** [comment]
@MarcelGerber I dont think that there could be any workaround with fonts.
Default fonts MUST be good for any charset.
And nobody should #$%^&* with make them readable.

**Comment by MarcelGerber** [comment]
I'm sorry to hear that.

The image preview (the overall feature is named Quick View) is supposed to work like this, it just displays the image so you can get a quick impression of what it looks like and how big it is (which is very useful when hardcoding the dimensions in CSS/HTML). It's also available for plain colors (hex/rgb/rgba/hsl/hsla), gradients and data URLs, where it might be even more useful.
In Brackets, ever user-visible string is translatable, but unfortunately it looks like the Russian translation hasn't been updated for quite some time. As Brackets is open source, everyone can go ahead translating these strings and submitting them back to core; you can too.

**Comment by akaRem** [comment]
@MarcelGerber 

 Quick View - ok, but it could be better (for example, act like preview in OSX) — too small image, unfortunately.

Translation — ok, understood. But I'm not going to use brackets (may be later I'll change my opinion) and spending time on the translation does not make sense. Sorry.
