### ISSUE TITLE
There is still miss wording at 'split view' tab in Korean ;)

### ISSUE THREAD

**Issue by zeakd** [adobe/brackets#11063]
separate vertical is "왼쪽/오른쪽으로 분할" that means "left/right"
separate horizontal is "위/아래로 분할" that means "up/down"

there is mismatch. :D

**Comment by rroshan1** [comment]
@zeakd Can you please raise a PR with the fix. Thanks.

**Comment by rroshan1** [comment]
@zeakd Thanks for pointing out. 
Will it be possible for you to raise a PR with the fix and add someone for linguistic review. Thanks!

**Comment by rroshan1** [comment]
@zeakd Basically, the **Vertical split** option causes the main editor to be split vertically into 2- left and right editors; while **Horizontal Split** does the same into top and bottom. Hence, the Korean string "left/right split" is used for vertical split and "top/bottom split" for horizontal split.
Hope that resolves your confusion.

**Comment by rroshan1** [comment]
You can verify that the "left/right split" and "top/down split" options split the main editor as per the name.

**Comment by zeakd** [comment]
I checked. thanks!
