### ISSUE TITLE
about jshint

### ISSUE THREAD

**Issue by futurefeeling** [adobe/brackets#11070]
> Has someone meet this problem ? 

***following is my js code in the js file;***
![js code](https://cloud.githubusercontent.com/assets/9881593/7549402/7045ad28-f665-11e4-983a-026faaf1f645.png)

***and it make a mistake the jshint gave:***
![problem](https://cloud.githubusercontent.com/assets/9881593/7549414/cb4cbe3c-f665-11e4-9491-282f68244e9e.png)

of course,it can run in the browser.

 Is this a issues ? or it had been solved and I miss it.
 And if not,can someone give me some tips?

**Comment by ldez** [comment]
Not an issue.
Use JSLint configuration file `.jslintrc` or use comment jshint command to define your lint rules.

See JSLint documentation: http://jshint.com/docs/

**Comment by ldez** [comment]
Sorry I give link to JS**H**int Doc not JS**L**int see here: http://www.jslint.com/help.html

**Comment by ldez** [comment]
In your case add this at the top of the file: ` /*global $,console */`

**Comment by ldez** [comment]
Please close this issue.

**Comment by abose** [comment]
Closing the issue.
This is an expected behavior. As pointed out by @ldez ,Adding `/*global $,console */` to the beginning of the file would solve your case.

**Comment by futurefeeling** [comment]
sorry,having some trivial thing  these day,and thanks for your help

**Comment by abose** [comment]
No issues, please keep logging issues that you see is relevant :smile:
