### ISSUE TITLE
Find and Replace tick marks not positioned correctly when using with scrollPastEnd

### ISSUE THREAD

**Issue by futurizing** [adobe/brackets#11079]
When enabling `"scrollPastEnd": true` in preferences file, Find and Replace tick marks (the yellow ticks on the right scroll bar that show occurrence positions) are not positioned correctly. It is positioned as the same as when the `"scrollPastEnd": false`, which makes it harder to find the text occurrences.

How to reproduce:
- Turn on `"scrollPastEnd": true` in preferences file.
- Use the *Find* (`Ctrl + F`) to find some texts.

![screenshot 87](https://cloud.githubusercontent.com/assets/7562314/7552601/40b5d456-f6e8-11e4-8e6a-d8f5c8cccb1c.png)

Tested on Brackets 1.4 without extensions, Windows 10 Insider Preview and Windows 8.1, but it should be reproducible on any OSes.

**Comment by MarcelGerber** [comment]
This will finally be fixed in the next version of Brackets.
Closing,
