### ISSUE TITLE
Can't load the resource : http://s3.amazonaws.com/files.brackets.io/updates/stable/zh.json?_=1431317777528

### ISSUE THREAD

**Issue by YaoLinHsieh** [adobe/brackets#11082]

**Comment by nethip** [comment]
@YaoLinHsieh What were you trying to access? We do not support any updates for zh locale?

**Comment by YaoLinHsieh** [comment]
I did not try anything... I just use it as usual.
I extended the code folding, beautify, and change the theme to the dark version, and switch the language to the traditional Chinese after setup brackets.
I have not changed other setting or other things.

**Comment by nethip** [comment]
@YaoLinHsieh Oh you mean you saw this error in the console? I tried your repro steps(change language and invoke *Check For Updates*) but I don't see any issue in the console. Can you repro this issue?

**Comment by YaoLinHsieh** [comment]
Yes, I just saw that in the console.
well...I do not know...I could not compile jquery file(.js) with autoCompleted / Hint when I saw this error 403 in the console.

**Comment by MarcelGerber** [comment]
That's an expected error we cannot suppress (I think?). It can be seen for pretty much all locales.
Closing.
