### ISSUE TITLE
Open file with not work on linux

### ISSUE THREAD

**Issue by daaru00** [adobe/brackets#11086]
open file with brackets not work on Linux. 
My version is: _Linux 3.13.0-37-generic x86_64 - Linux Mint Cinnamon edition_

**Comment by WausauBill** [comment]
This works for me on Linux.  Here is my Brackets version:
Release 1.11 build 1.11.0-17524 (release 86b5e2d4e) 
build timestamp: Wed Sep 20 2017 10:21:22 GMT+0000

Here is my system information:
Linux Mint 18.3
KDE Plasma 5.8.8
Kernal: 4.8.0-53 generic

**Comment by daaru00** [comment]
Hi,
this issue is 2 years old... I do not use brackets anymore.
I think we can close.
