### ISSUE TITLE
CodeHinter gets confused completing a pre-populated attribute 

### ISSUE THREAD

**Issue by sedge** [adobe/brackets#11087]
To my understanding, the hinter should completely replace the contents of the `""` when doing a hint replacement. It's somewhat unreliable at the moment:

![autocompleteerror](https://cloud.githubusercontent.com/assets/1616860/7570520/d199659a-f7de-11e4-8512-9a6f0470f061.gif)

**Comment by deandersson** [comment]
Dont forget cases when we have multiple statements inside `""`
ex: `class="class1 class2"`
So maybe the delimiter should be spaces aswell?

**Comment by TomMalbran** [comment]
I was able to repro it. The url hints are handled with the url code hints and those always replace the entire string, unlike other code hint providers. It looks like the issue occurs when deleting some chars, and not when just typing them.

CC: @redmunds

**Comment by redmunds** [comment]
> To my understanding, the hinter should completely replace the contents of the "" when doing a hint replacement.

In most cases, code hints will *not* completely replace the contents for the sake of being safe (and not removing desired content).

For URL hints, they should insert **folder** names and replace **file** names, so, yes, this looks like a bug.

**Comment by MarcelGerber** [comment]
This should be fixed now that #11284 was merged.

**Comment by sedge** [comment]
👍
