### ISSUE TITLE
CodeHinter: `background-image` property only shows CSS `url()` hints when quotes are included

### ISSUE THREAD

**Issue by sedge** [adobe/brackets#11088]
To my understanding, the background-image property in a CSS file should show code hints for the url function without quotes, since they aren't required:

![urlerror](https://cloud.githubusercontent.com/assets/1616860/7570662/d7e17234-f7df-11e4-8d69-1a92899bc994.gif)

**Comment by redmunds** [comment]
Yes, that seems to be a recently injected bug.

As a workaround, hit Enter after typing `url` and *before* typing `(`.

**Comment by humphd** [comment]
@sedge, would you mind `git bisect`ing this and see if you can find a regression range?

On May 11, 2015 2:08 PM, Randy Edmunds <notifications@github.com> wrote:

Yes, that seems to be a recently injected bug.

As a workaround, hit Enter after typing url and before typing (.

**Comment by redmunds** [comment]
Just to be clear, I don't work on brackets every day, so "recently" for me may mean a few releases. Also, you need to build Brackets locally to use `git bisect`.
