### ISSUE TITLE
Ctrl+Shift+arrow doesn't move a line

### ISSUE THREAD

**Issue by thany** [adobe/brackets#11095]
It's always worked like this:

`Ctrl+Shift+up`: Move current line/selection up
`Ctrl+Shift+down`: Move current line/selection down

Somehow, Brackets recently started to act differently:

`Ctrl+Shift+up`: Select from current position up to the beginning of the document
`Ctrl+Shift+down`: Select from current position down to the end of the document

This is weird, since I've used this feature a LOT, and it has always worked fine. Suddenly, it starts acting like that. Why, and how/where do I change this?

Windows 7 x64, Brackets 1.0.

**Comment by thany** [comment]
Update: might be [this one](https://github.com/thehogfather/brackets-code-folding/issues/136) actually.

**Comment by rroshan1** [comment]
@thany I do NOT see the issue in Brackets v1.3. For me, `Ctrl+Shift+Up/Down` works as per the expectation. Can you try reproducing the issue in v1.3.
May be it's time you upgrade to v1.3.  :smiley:

**Comment by abose** [comment]
Closing inactive thread.
@thany Please reopen the issue if you still face this.

**Comment by thany** [comment]
The problem definitely persists in 1.3. But only sometimes.

**Comment by thany** [comment]
Possibly related: Brackets from time to time extends the selection a line up or down in addition to moving a line up or down. Like it's doing Ctrl+Shift+up and Shift+up at the same time.
