### ISSUE TITLE
Undo not working

### ISSUE THREAD

**Issue by wgrs** [adobe/brackets#11090]
Running undo command not working. Issue seems to be linked to the beautify on save command.

**Comment by busykai** [comment]
Beautify is not part of the Brackets core. Beautification is not done as a sequence of editing commands, it's ran though an external process and then the entire content of the editor is [replaced](https://github.com/drewhamlett/brackets-beautify/blob/master/main.js#L169). Whenever that happens, the undo/redo stack is emptied (which means the editor thinks nothing has been edited). Please file this issue with (the extension)[https://github.com/drewhamlett/brackets-beautify/issues].

I'm closing this one.
