### ISSUE TITLE
Install extension failed on ubuntu 14.04

### ISSUE THREAD

**Issue by darkcyber** [adobe/brackets#11098]
Just download last Brackets Release 1.3 experimental build 1.3.0-16022 (release cd0a6aae5) and do fresh install.

Try to install ftp-sync extension and get this

Installation failed
Unknown internal error

what i see in developer tools console is

Unknown installation error Object {errno: 3, code: "EACCES", path: "/home/darkcyber/.config/Brackets/extensions/user/ftp-sync"} /extensibility/Package.js:408

Let me know how to fix this problem. 
Thanks.

**Comment by abose** [comment]
Is this only this extension you are having difficulty to install?
can you try installing any other extension and see if the error persists?

**Comment by darkcyber** [comment]
no, the other extension too.

**Comment by abose** [comment]
I looks like brackets does not have permission to access `/home/darkcyber/.config/Brackets/extensions/user/ftp-sync` could you check the location and that brackets has r/w access to it??

**Comment by abose** [comment]
Closing inactive thread.
@darkcyber Fell free to reopen this if you are still facing the issue [Also please check the premission settings as in above comment].
