### ISSUE TITLE
can't install brackets on ubuntu 15.04

### ISSUE THREAD

**Issue by sarangbaheti** [adobe/brackets#11092]
Downloaded Brackets Brackets.Release.1.3.64-bit.deb today and not able to install because dependency on libgcrypt11(>= 1.4.5).

![brackets-installation-error](https://cloud.githubusercontent.com/assets/1380950/7581233/3f2f3778-f835-11e4-9891-2578319f68c1.png)

Any help in this matter is appreciated.
Thanks

**Comment by nethip** [comment]
@sarangbaheti Could you take a look at this thread https://github.com/adobe/brackets/issues/10255 and try the steps mentioned there.

**Comment by sarangbaheti** [comment]
Thanks @nethip, dowloaded libgcrypt11 ( libgcrypt11-dbg_1.4.5-2_amd64.deb) from http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/libg/libgcrypt11/ and now i am able to launch and work with brackets
