### ISSUE TITLE
Code folds uncollapse when selecting over the ... marker (on nested collapses)

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#11091]
Steps to repro:

Write some HTML
``` html
<div class="test">
    <p>        
        <span>Test</span>
    </p>
</div>
```

Fold the inner `<p>`

![image](https://cloud.githubusercontent.com/assets/7641760/7581030/b62c04ea-f886-11e4-8858-c478a1e0d371.png)

Start selecting text from the beginning or end of line 4 (the collapsed one). The fold uncollapses when mouse hovers over `...`

(Brackets 1.3, Win 8.1)

**Comment by nethip** [comment]
@petetnt I just followed the steps that you mentioned above and I am not able to repro this. Are any other steps involved here to repro the issue?

**Comment by petetnt** [comment]
@nethip nope, that is all. Here's a (low quality) gif:
![giffo](https://cloud.githubusercontent.com/assets/7641760/7582401/d9b0de2c-f895-11e4-90cc-873bd2230b8a.gif)

**Comment by nethip** [comment]
@petetnt Yes I am repro this now. But it is quite strange that I followed the exact steps in the before run and I was not able to repro it.

**Comment by petetnt** [comment]
It seems to be a CodeMirror issue as it works on the CodeMirror's [code folding demo too](https://codemirror.net/demo/folding.html), crossref codemirror/CodeMirror#3255

**Comment by petetnt** [comment]
Okay, it's not a bug, it's a feature that can be controlled by `clearOnEnter` option to `markText` as confirmed on the Code Mirror issue. Preference idea then? :dancers:
