### ISSUE TITLE
CSS close curly braces - row problem

### ISSUE THREAD

**Issue by tatof** [adobe/brackets#11099]
Hello,

I really like Brackets only have one problem I can't find a solution to.

When I type css it always starts at the beginning row. (no problem there) 
so I tab to the position I want the class to be.
Then I open and close the "curly braces" and the hole row go's to the beginning! So I have to Tab the row again.

Can't find out how to change this.
Here is a gif with the problem:
http://jxerot.com/share/problem.gif

**Comment by nethip** [comment]
@tatof Have you tried installing the [beautify] (https://github.com/drewhamlett/brackets-beautify) extension?

**Comment by tatof** [comment]
I installed "preferences setup UI" and enabled the "automaticly close Brackets".
And now it doesn't go back to the begin row!

Only I think this sould be fixed in Brackets.. don't think there are people who want to work this way.

Will tryout beautify

**Comment by nethip** [comment]
@tatof We are prioritizing the issues with indentation in Brackets. Just that we want to understand if the above extension solves the aforementioned issues and unblocks your workflow.

**Comment by tatof** [comment]
No beautify doesn't solve the problem.

**Comment by sprintr** [comment]
You should set `smartIndent` pref to `false` to get the behavior you want.

```json
{
    "smartIndent": false
}
```

**Comment by MarcelGerber** [comment]
Note: You can also do that for css files only with something like this:
``` json
{
    "language": {
        "css": {
            "smartIndent": false
        }
    }
}
```

See also: [Usage of Preferences](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences)

**Comment by tatof** [comment]
oke nice! looks like a solution :). 
what file do I need to edit?

preferences file?

**Comment by sprintr** [comment]
@tatof Go to `Debug` > `Open preferences file` and add the JSON @MarcelGerber posted. Make sure it is valid JSON.

**Comment by tatof** [comment]
Oke this works! :) nice!

Is this going to be fixed in later versions? 
Don't think anyone would want this behavior when coding.

(could make the JSON from marcel work so I disabled the global smartIndent)

**Comment by rroshan1** [comment]
@tatof **:   Smart indent** preference when enabled determines the indentation from the block level (as in the block depth in which it is) rather than from the previous line. Hence, the behaviour that you see.
In general, it works well with most file types except the scenario in your case in which different blocks at the same level needs to be differently indented. But yes, we can consider having it disabled for CSS files by default.
Closing the issue.

**Comment by MarcelGerber** [comment]
@rroshan1 We shouldn't default it to disabled in CSS because that would pretty much break the common "every rule on their own line" practice:
``` css
.foo {
  color: red;
  background: blue;
}
```

**Comment by tatof** [comment]
That wouldn't break "every rule on ther own line" pracitice.
Only thing it would to is making it posible to Nest your css like your div structure.

[code]
test
[/code]
