### ISSUE TITLE
[Performance] Find In Files Optimization

### ISSUE THREAD

**Issue by rroshan1** [adobe/brackets#11093]
- [x] Measure the performance of "Find In Files".
- [x] Compare the same with other Brackets-like editors.
- [x] Analyzing the scope for improvements in "Find In Files".
- [ ] Implement the optimizations.
- [ ] Measure the improvements.

*Method used to measure the performance*:-

We have run multiple FindInFiles searches and used iPhone 5S to capture the slo-mo (slow-motion) videos with 120 fps. After capturing the videos, we used Adobe Premier-Pro to calculate the time elapsed in the searches to the nearest frames (accuracy= 1/120th of a second). 

*Parameters to consider for testing this*.

1) Test this for small(<500 files), medium(5K files approx) and large(>25K) projects.
2) Run it on Windows and Mac systems with most likely configurations.
3) Find the performance differences in a repeated search, case-sensitive search and the very first search.

**Comment by rroshan1** [comment]
**WINDOWS Configuration**

OS: Windows 7 Enterprise 64-bit.
Processor: Intel Xeon E3, 3.40 GHz.
RAM: 16 GB.

EDITORS | Small Project | Medium Project | Large Project
------------ | ------------- | ------------ | -------------
**Brackets v1.3** | 133 msec  | 741 msec  | 2767 msec 
**Atom** | 350 msec | 3941 msec | 3950 msec
**Visual Studio Code** | - | 1733 msec  | 9066 msec 
**Sublime Text 2** |  33 msec  | 1100 msec | 5241 msec
*Refer following section for Visual Studio Code and Sublime Text limitations!*


**Limitations**
1. Almost all of the editors are very slow at the first search and perform consistently after the second search. Hence, readings have been noted from second search onwards.
2. **Sublime Text** populates the search results in an editor. There is no indicator to show that the search has ended (unless you keep on scrolling to the end of the page). Hence, we had to go for searches with occurrence in single digits for Sublime.
3. **Visual Studio Code** cannot handle searches even for 2100 occurrences approx. Hence, most readings for it are for a subset of the search (around 2000 occurrences) it has done and not the entire search.
4. For all editors, the time taken for a repeated search or a case-sensitive search does not significantly differ. However, the time taken for a single and multi-word search does differ. We have taken readings for two single-word search and two multi-word search and displayed the average in the table above.

Below is a graphical comparison of the performances:-
![findinfilesperf](https://cloud.githubusercontent.com/assets/11662297/7656515/87da2742-fb48-11e4-8962-a99131d6e08b.jpg)

**Analysis**
Brackets performs much better than most editors for most types of project. However, the very first "Find In Files" search takes much longer than other editors and also makes Brackets kind of non-responsive. This may be giving a very bad and untrue perception to the users about this performance when other editors populate their search results progressively!!

**Comment by abose** [comment]
#11128 PR with incremental update.

**Comment by rroshan1** [comment]
Performance scores for Windows and Mac updated in previous comment.

**Analysis w.r.t. FindInFiles performance on various editors:-**
1. Brackets performs much better than most editors for most types of project. However, the very first "Find In Files" search takes much longer and also makes Brackets kind of non-responsive. This may be giving a very bad and untrue perception to the users about this performance while other editors populate their search results progressively!! [**ToDo**: Make find in files UI non-blocking, when search is performed for the first time after the project is opened.]
2. Sublime is exceptionally well for small projects but quite bad for large projects.
3. All editors except Atom have considerable differences between medium and large project performances.
4. While most editors perform similar on Windows and Mac, Brackets performance gets almost halved on Mac environment.

**Comment by rroshan1** [comment]
FindInFiles Performance **ToDo**
1. Make find in files UI non-blocking, when search is performed for the first time after the project is opened. Review this solution #11128 and consider improvements.
2. Currently, Brackets does not update the search results after external updates are made to files (with the file NOT being open in Brackets). Explore the solutions to this issue #10717.
3. Take performance scores on couple of more Mac and Windows systems to verify if Brackets performance on Mac wrt Windows needs attention.

**Comment by nethip** [comment]
@rroshan1 Thanks for the breakup. Could you go about creating individual cards for each of the items you have mentioned above?
