### ISSUE TITLE
[Performance] Scrolling performance

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#11105]
- [ ] Measure the performance of scrolling comparing this to other apps in the market
- [ ] Analyze any code bottlenecks that is bringing the scrolling speed down.
- [ ] Fix the identified issues.

Method used perform the testing.

We used iPhone 5S to capture the slo-mo video. Once captured, we then loaded the videos into Premier-Pro and started calculating the time difference between when scrolling is initiated and when the scroll happened.

Parameters to consider for testing this.

1) Test this with small, medium large projects
2) Run it with code hints enabled and disabled.
4) Use flash update on MAC from quartz debug to figure out the paint areas

**Comment by nethip** [comment]
Suspending this card temporarily.

**Comment by cubuspl42** [comment]
Why is this issue closed? Bracket's scrolling doesn't literally lag, but it feels so much worse than in Atom, which is made using web technologies, too. I'm not comparing it to Sublime!

**Comment by abose** [comment]
https://github.com/adobe/brackets/issues/11083 tracks the scrolling related issues.
This was a performance analysis task issue created for book keeping.

**Comment by cubuspl42** [comment]
@abose Well, that seems to be a very specific bug about scrolling being too fast sometimes, I was talking about general scrolling experience which seems to be bad in Brackets. But maybe that's just my opinion and other find the scrolling performance good enough. :)

**Comment by abose** [comment]
Yes, we are tracking scroll issues saperately. Please search for scroll related issues in the repository.
As mentioned, this issue was created to track an internal task we took.
Please raise another issue with the exact problem description you are facing.

**Comment by vimxts** [comment]
"Analyze any code bottlenecks that is bringing the scrolling speed down."??

The scrolling speed is way too fast! And I don't think the list is all there is to the bug, or rather, **bugs**.
