### ISSUE TITLE
Brackets [ ] css not loading in live view at all

### ISSUE THREAD

**Issue by Azraeleas** [adobe/brackets#11103]
I have a html project that I am working on using adobe brackets. When i try to use live veiw, the html code loads fine but any CSS I type does not register. Brackets itself recognises the codes and tags i am typing in for CSS but they do not load along with my html code...
![screen shot 2015-05-13 at 12 47 45 pm](https://cloud.githubusercontent.com/assets/12425837/7608924/4fefdea2-f96e-11e4-9b98-8efe59a0c543.png)
![screen shot 2015-05-13 at 12 47 52 pm](https://cloud.githubusercontent.com/assets/12425837/7608925/50dd9782-f96e-11e4-9548-f1a8c04b7bcb.png)

**Comment by abose** [comment]
Try toggling `file menu -> Enable Experimental Live Preview` and see if the problem persists.

**Comment by Azraeleas** [comment]
Unfortunately this is still not fixing it... 😕

Yours sincerely
Graeme Ford

**Comment by abose** [comment]
Could you share the code with us if you don't mind? :smile:

**Comment by humphd** [comment]
If you're using the HTML page in your screenshot, note that you need to add a `<link rel="stylesheet" href="Test.css">` to your `<head>` element, otherwise the browser won't know about the sheet.

**Comment by abose** [comment]
Closing as this is a user code problem.
