### ISSUE TITLE
Selected theme wont save as default

### ISSUE THREAD

**Issue by FrankTrog** [adobe/brackets#11118]
Good morning,

Ever since this morning every time I open brackets it defaults to the harsh white theme that comes with the program by default. I have tried picking one of the themes that comes with brackets and I have tried a plugin theme. The themes will take but when the program is closed and re-opened the default theme is the default once again. Any thoughts?

Windows 8.1
Brackets 1.3.0-16022

**Comment by rroshan1** [comment]
@FrankTrog Looks like your preferences file is corrupt. If you do not mind losing your current extensions, you can delete the contents inside "C:\Users\username\AppData\Roaming\Brackets\". Open Brackets and apply your preferred theme. It should persist thereafter.
Please share if this helped.

**Comment by FrankTrog** [comment]
That worked. Thanks for your help, rock on!

Kind Regards,

Frank J. Troglauer Jr.
Whirlwind Production, LLC.
803-466-0314
frank@frankt3d.com

**Comment by MarcelGerber** [comment]
Nice!
Closing.
