### ISSUE TITLE
Can't open the root of a drive on Windows 7

### ISSUE THREAD

**Issue by sbrl** [adobe/brackets#11110]
I just created a new temporary Ramdisk (using ImDisk), and went to open it in brackets. I selected the folder, but nothing happened! I was able to select the folder, but then nothing changed - brackets did not open the folder, nothing in the UI changed. It kept with the old folder.

Edit: Just noticed that I only have this problem if the ramdisk is empty, for some reason....

**Comment by abose** [comment]
I installed ramdisk and i was able to properly launch brackets with an empty ramdrive. could you verify this again and post a screenshot of the projects pane & developer console messages(press f12) after opening an empty ramdrive project?

**Comment by sbrl** [comment]
That's strange, it's working correctly now. perhaps a restart was all 
that was needed :)
