### ISSUE TITLE
Github.com Branch Dropdown Bug

### ISSUE THREAD

**Issue by surajduah** [adobe/brackets#11121]
Hello

I noticed a bug in https://github.com account.

If I'm in a branch and I have selected a folder to view files, then if from the drop-down I change branch to a different one, The browser redirect me to 404 page.

So If I have 2 branches "Master" and "Dev"

If I select the branch "Master" and then open any folder within it. Then if I select Branch "Dev" from drop-down, I get redirected to 404 page.

Seems a huge bug.

Thanks
Suraj
suraj02@gmail.com
91-9897695552

**Comment by ldez** [comment]
What is the relationship with Brackets?

Contact Github: https://github.com/contact

Please close this issue.

**Comment by MarcelGerber** [comment]
@surajduah It's quite possible the folder you're in doesn't exist in the branch you then select. In that case, the 404 page is _expected_.

Anyways, I'm going to close this issue as it's not an issue with Brackets. For further advice about this bug, please contact GitHub like @Idez recommended.

Closing.
