### ISSUE TITLE
Live Preview Multibrowser, stuck on connecting

### ISSUE THREAD

**Issue by martiuh** [adobe/brackets#11122]
I can't get  to see Multibrowser Preview, yesterday it was all right but today it just don't work.

![captura de pantalla 2015-05-15 a las 12 29 16](https://cloud.githubusercontent.com/assets/12422855/7658294/87bf0240-fafe-11e4-9216-f1ee09a88409.png)

The lighting bolt icon just color by half and it stays that way and the hover text (I don't know how to call it) just says "Connecting".
The Live Preview (not Experimental) is working but I cant see the live changes (I need to save and then the web page loads itself to show the changes) and the HTML/CSS highlight box isn't visible.

Hope you guys can help me!!!

**Comment by martiuh** [comment]
So I solved this problem

I'm on a Mac running OSX Mavericks

Yesterday I downloaded some stupid "web player" called MPlayerX that is nothing but an adware.

The pop-ups were annoying me and I decided to get rid of them. I downloaded "adwareMedic" and wipe the Adware but I still wasn't able to enter the Multibrowser Preview.

Then I went to the Brackets Debug/Show Developer/ Tools and saw the console, I saw that the localhost couldn't be accessed so I went to finder and went to the folder 
/private/etc/hosts

The host file was corrupted, full of stuff that wasn't supposed to be there, and I made a new hosts file following this tutorial

http://osxdaily.com/2014/04/12/restore-original-hosts-file-mac/

It was really.

So that's how I solved this, hope it could be useful for someone in the future.

**Comment by s1awek** [comment]
Bless you for sharing this solution.

**Comment by martinneumann** [comment]
For Ubuntu users: in my case, I had the same issue when running brackets with super user rights. Without them, it suddenly worked. This error is reproducible on my system (Kubuntu 17.04). 
If you encounter it, try running just `brackets` instead of `sudo brackets`.
