### ISSUE TITLE
Brackets doesn't open any project

### ISSUE THREAD

**Issue by rayoujines** [adobe/brackets#11125]
I want to create HTML file, but Brackets does not respond .
 I tried all attempts without interest, nothing works I do not know why.
![bracketserreur1](https://cloud.githubusercontent.com/assets/12466606/7664337/d2f32f1c-fb7a-11e4-8227-4b1ed6c49db8.jpg)
I hope to find an answer and a solution as soon as
Thanks in advance

**Comment by MarcelGerber** [comment]
Could you just open the developer tools (`Debug > Show Developer Tools`) and copy the contents you see in the `Console` tab?

**Comment by rayoujines** [comment]
Does not respond to any command :(
![bracketserreur2](https://cloud.githubusercontent.com/assets/12466606/7666535/6349d636-fbe1-11e4-9a33-3bae229b0ef8.jpg)

**Comment by redmunds** [comment]
Do you have any extensions installed? Try restarting without extensions (*Recharger sans les extensions*)

**Comment by rayoujines** [comment]
but I uninstalled and then installed the program but no response

**Comment by redmunds** [comment]
Uninstalling and re-installing Brackets may not remove the extensions. See article on how to [clear your cache](https://github.com/adobe/brackets/wiki/Cache-Folder), but instead of deleting `cef_data` folder, delete the entire `Brackets` (parent) folder to also delete extensions.

**Comment by nethip** [comment]
@rayoujines Were you able to resolve this after deleting the `brackets` folder from `%appdata%`?

**Comment by abose** [comment]
Closing inactive thread. 
Try out deleting `%appdata%/brackets` folder as suggested. 
@rayoujines feel free to reopen this is you are still facing the issue.
