### ISSUE TITLE
Add "Replace all" button when doing Find -> Replace

### ISSUE THREAD

**Issue by larsenwork** [adobe/brackets#11126]
Clicking "Batch..." in the top of the screen and then "Replace" in the bottom takes too much time :wink:

![screen shot 2015-05-16 at 14 08 12](https://cloud.githubusercontent.com/assets/3859425/7666070/54bda73e-fbd5-11e4-9fde-556c787a1b08.png)

**Comment by nethip** [comment]
tagging @abose

**Comment by ficristo** [comment]
Fixed by #12988
