### ISSUE TITLE
request for workingfile *folders*

### ISSUE THREAD

**Issue by sweather131** [adobe/brackets#11120]
I have recently been working on a large project that involves editing multiple different sites within the same repo.

I have been searching for a plugin that allows you to essentially group working files into a folder/group, so that when you have to switch between editing one site+it's corresponding files and another (in the same repo), you would not have to find all the individual working files again.

I understand that my use case might be a marginal one, but brackets seems to have plugins for all shapes and sizes, and as I am not experienced enough to write one myself I thought I would put this idea out there and see if others were interested (in using such a feature or even better, creating it :smile:)

**Comment by redmunds** [comment]
Use *File > Open Folder...* to set the "project" that Brackets uses. Open each "site" or "group" as a Brackets project and the working files will be remembered when you switch back to it. Use the dropdown list under working set and above file tree to quickly switch between project. Does that work?

**Comment by sweather131** [comment]
ooh @redmunds thanks for the tip... this is a neat method.
However, the files that I want grouped are dispersed in several different folders in my repo.
For example all of our css is under our master css folder, all views fall under the master views folder, etc.. so setting a single folder as a project still doesn't really do the trick.
I would like to grab a couple files from each of those 'master folders' and have them in a group so I don't always have to search through the whole filetree and cherrypick them again.

I understand this might be tricky because these groups would not have any correspondence to the actual file tree... they would be brackets-specific and only for the sake of workflow.

**Comment by redmunds** [comment]
There's no way to do that in core Brackets. That could be implemented as an extension, so try searching the Extension Manager to see if someone has already done something like this.

**Comment by sweather131** [comment]
@redmunds yeah I was kind of posting this hoping someone else would make the extension if they find it useful :P.
I already searched for the extension in as many ways as I could possibly think.. but haven't found what I'm looking for yet.
Thanks a lot.

**Comment by redmunds** [comment]
Marking this as an `Extension Idea` for any extension authors looking for ideas. Closing.
