### ISSUE TITLE
diffrernt icons, diffrent formats

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [adobe/brackets#11132]
can provide breackets diffrent icons for diffrent formats?? that can help to recognize  files easily!

**Comment by sprintr** [comment]
You can use https://github.com/ivogabe/Brackets-Icons or https://github.com/drewbkoch/Brackets-File-Icons

**Comment by abose** [comment]
There are popular extensions to do the same as @sprintr pointed out. closing.

**Comment by MahdiMajidzadeh** [comment]
no, I mean in file explorer of windows for example, like other IDEs 
![diffrernt icons, diffrent formats in kmplayer](http://forums.kmplayer.com/forums/gallery/files/1-arseneicon.png)
!diffrernt icons, diffrent formats](http://www.dmxzone.com/downloads/images/Image018_12.png)

**Comment by abose** [comment]
oh! got it. you meant separate brackets icons for individual file types. 
@nethip @ryanstewart

**Comment by MahdiMajidzadeh** [comment]
yep :)

**Comment by abose** [comment]
I have added a trello card for this at https://trello.com/c/y8j8ERPZ/1421-add-file-type-specific-brackets-icons-to-explorer-finder 
Upvote the feature there.

**Comment by MahdiMajidzadeh** [comment]
thanks! :+1:
