### ISSUE TITLE
da window

### ISSUE THREAD

**Issue by PennyScripter** [adobe/brackets#11138]

**Comment by abose** [comment]
Can you give more details on this issue?

**Comment by younishd** [comment]
da issue

**Comment by mackenza** [comment]
Da bomb

**Comment by ApfelUser** [comment]
Da process

**Comment by redmunds** [comment]
da closed issue :)

**Comment by younishd** [comment]
da dum tsss

**Comment by abose** [comment]
![preview](https://cloud.githubusercontent.com/assets/5336369/7785521/b9d720ce-01b0-11e5-9b36-2fc239642ee4.jpg)
