### ISSUE TITLE
select closing tag and edit simultaneously

### ISSUE THREAD

**Issue by techsin** [adobe/brackets#11135]
It's a feature that worked with emmet but doesn't work in brackets. 

say i go to <p> and change it to h1 then i should have a way so i dont have to go to the end of of tag and change </p> to </h1>

**Comment by abose** [comment]
Did you mean that it used to work with the brackets extension in emmet previously?
i Do not remember brackets natively supporting this feature.

**Comment by techsin** [comment]
no in sublime emmet lets you do this...

**Comment by sbruchmann** [comment]
Hello @techsin

You can do achieve this in Brackets with [Emmet](https://github.com/emmetio/brackets-emmet) via _Update Tag_ (on OS X: <kbd>Shift</kbd> + <kbd>Command</kbd> + <kbd>I</kbd>) while the cursor is on the tag you want to update.

**Comment by abose** [comment]
Brackets emmet extension also supports this.
Closing.
