### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by tatof** [adobe/brackets#11143]
I'm using brackets on 3 different computers and I not happy about the stability.
Just wondering what the problem could be and if it will be better in the future?

All 3 computers are Windows7  dutch and english.
They all got some plugins:
eqftp (always crashes first startup), 
tomorrow night theme, 
brackets icons, 
brackets clientlibs combine

Problem is sometimes it loads quit good and works like heaven.
But mostly it crashes and I need to F5 till it works "stabel".

Is it something with my plugins or windows?
Is brackets still in beta and will it be upgraded to a more stabel version?

**Comment by zaggino** [comment]
@tatof I'm using Brackets daily for all my development work for more than a year and I have no stability issues. Did you try working without the `eqftp` plugin (or just without any plugins at all) ?

**Comment by zaggino** [comment]
Looking at the plugin, it seems it probably causes the problems that you have: https://github.com/Equals182/eqFTP/issues/132

**Comment by abose** [comment]
As @zaggino mentioned we rarely see stability issues logged in brackets core;[ but that doesn't mean it won't have any stability issues].
@tatof Could you remove the ftp extension[and others if necessary] and test the stability?

**Comment by tatof** [comment]
I will test the stability without the plugins and post my findings.
If the problem is with eqFTP do you guy's know a good FTP program that can live edit "online" files?

**Comment by abose** [comment]
brackets-ftp-sync, FTP-Sync Plus seems to have good ratings. but i have not used any of the ftp extensions myself.
You could install the `Extensions Rating` extension to see popularity of extensions in the extension manager .

**Comment by mackenza** [comment]
eqFTP is the only extension I am aware of that supports the editing of a "live" remote file system via ftp. The other ftp extensions upload local files to a remote server not the 2way workflow you are suggesting @tatof

**Comment by tatof** [comment]
FTP sync plus only connects to one single server at the time and can't store more than one ftp account  or project. Its a good plugin only way to simple

Tryed to install SFtpUpload but brackets crashed so don't think that will work...

Hope eqFTP will fix the bugs soon! cause thats the only ftp client that fits my needs.
Is brackets getting an FTP function in the future? (something simple like notepad++)

**Comment by abose** [comment]
@tatof If you logged an issue in eqFTP, please refer that issue here. I am closing this issue as an extension problem.

Also if you want to have native FTP support in brackets; please upvote this feature in https://trello.com/c/anjphhsw/610-ftp-upload-syncing-integration

**Comment by tatof** [comment]
Made a topic here: https://github.com/Equals182/eqFTP/issues/138

@abose Only still don't know for sure if Brackets wil be more stable without eqFTP. So thats why I didn't close the topic. Need an week to test this propper and rule out what crashes are made by eqFTP and what not.

Also I upvoted the ftp integration!

**Comment by abose** [comment]
:cool: , feel free to reopen this issue if you find any stability issues in core.
