### ISSUE TITLE
[IQE] : Code folding shortcuts not working on Win 10 platform

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11145]
Steps to Reproduce:

1 Open Brackets on Win 10
2 open any file eg index.html
3 Try "Collapse All" via shortcut "ALT+1"

Result : 
the file is not collapsed

ENV: Brackets Release 1.3 build 1.3.0-16022
Platform : Win 10 Eng

**Comment by prafulVaishnav** [comment]
@rawat11 Can you share the error if any on developer tools console (Go to Debug > Show Developer Tools)

**Comment by rawat11** [comment]
@prafulVaishnav : It is an intermittent issue, There are no errors related to it in the  dev tools console.
Currently the shortcuts are working.

But the code folding icons are not getting visible for php code while it picks for html

![1](https://cloud.githubusercontent.com/assets/10069885/7766791/965b6640-008a-11e5-8571-b39e9b1d18dd.png)

**Comment by rawat11** [comment]
@prafulVaishnav Yes, its working fine
