### ISSUE TITLE
Problemas en códificación

### ISSUE THREAD

**Issue by resback** [adobe/brackets#11146]
Usaba Edge Code para editar mis archivos, al actualizarme a Brackets veo que les quita la codificación utf8, pues todos mis archivos editados con Brackets ahora se ven con simbolos raros, la única forma de recuperarlos es abrirlos con el block de notas y guardar como > utf8

**Comment by abose** [comment]
Brackets can only work with UTF8 encoded files for the time being. 
But I did not get the rest of the question as I don't understand spanish.

**Comment by ficristo** [comment]
Closing as answered.
