### ISSUE TITLE
Can't install Brackets on Windows 8.1 x64

### ISSUE THREAD

**Issue by vhanadium** [adobe/brackets#11149]
Hi guys,

I'm trying to install Brackets on my Win 8.1 computer but Ican't seem to do it.
When I launch the .msi the installation abruptely stop without any error message but a window saying that de Brackets installation stopped before it ends and that no modification where operated on my computer.

I thought of a wrong download so I tried to download it one more time without any luck. I even tried to install Brackets without Adobe Extract.

Anyone got an idea ?

Thx

**Comment by prafulVaishnav** [comment]
@vhanadium Are you able to see any error while installing ? If not, you can get the logs for installation and share it here. To get the logs, can you install the Brackets from command line. Cmd is msi `msiexec /i C:\Users\vaishnav\Downloads\Brackets.msi /Lime C:\Users\vaishnav\Desktop\logFile.txt`

Please share logFile.txt

**Comment by vhanadium** [comment]
@prafulVaishnav here is the log file a bit is in french:

=== Début de l’écriture dans le journal : 22/05/2015  10:27:51 ===
Début de l’action 10:27:51 : INSTALL.
Début de l’action 10:27:51 : FindRelatedProducts.
Fin de l’action 10:27:51 : FindRelatedProducts. Valeur de retour 1.
Début de l’action 10:27:51 : LaunchConditions.
Fin de l’action 10:27:51 : LaunchConditions. Valeur de retour 1.
Début de l’action 10:27:51 : ValidateProductID.
Fin de l’action 10:27:51 : ValidateProductID. Valeur de retour 1.
Début de l’action 10:27:51 : CostInitialize.
Fin de l’action 10:27:51 : CostInitialize. Valeur de retour 1.
Début de l’action 10:27:51 : FileCost.
Fin de l’action 10:27:51 : FileCost. Valeur de retour 1.
Début de l’action 10:27:51 : CostFinalize.
Fin de l’action 10:27:51 : CostFinalize. Valeur de retour 1.
Début de l’action 10:27:51 : SetARPINSTALLLOCATION.
Fin de l’action 10:27:51 : SetARPINSTALLLOCATION. Valeur de retour 1.
Début de l’action 10:27:51 : MigrateFeatureStates.
Fin de l’action 10:27:51 : MigrateFeatureStates. Valeur de retour 0.
Début de l’action 10:27:51 : ProgressDlg.
Informations 2898. For WixUI_Font_Normal textstyle, the system created a 'Tahoma' font, in 0 character set, of 13 pixels height.
Informations 2898. For WixUI_Font_BannerTitle textstyle, the system created a 'Tahoma' font, in 0 character set, of 19 pixels height.
Informations 2898. For WixUI_Font_Title textstyle, the system created a 'Tahoma' font, in 0 character set, of 14 pixels height.
Fin de l’action 10:27:52 : ProgressDlg. Valeur de retour 1.
Début de l’action 10:27:52 : MyInstallDirDlg.
Début de l’action 10:27:57 : WixUIValidatePath.
Fin de l’action 10:27:58 : WixUIValidatePath. Valeur de retour 1.
DEBUG: Error 2826:  Control InstallTitle on dialog MyVerifyReadyDlg extends beyond the boundaries of the dialog to the right by 287 pixels
Le programme d’installation a rencontré une erreur inattendue. Cela peut indiquer un problème lié à ce package. Le code d’erreur est : 2826. Les arguments sont : MyVerifyReadyDlg, InstallTitle, to the right
Fin de l’action 10:27:59 : MyInstallDirDlg. Valeur de retour 1.
Début de l’action 10:27:59 : MyProgressDlg.
Fin de l’action 10:27:59 : MyProgressDlg. Valeur de retour 1.
Début de l’action 10:27:59 : ExecuteAction.
Fin de l’action 10:27:59 : ExecuteAction. Valeur de retour 3.
Début de l’action 10:27:59 : FatalError.
Informations 2898. For WixUI_Font_Bigger textstyle, the system created a 'Tahoma' font, in 0 character set, of 19 pixels height.
Fin de l’action 10:28:00 : FatalError. Valeur de retour 2.
Fin de l’action 10:28:00 : INSTALL. Valeur de retour 3.
=== Fin de l’écriture dans le journal : 22/05/2015  10:28:00 ===
MSI (c) (50:7C) [10:28:00:653]: Produit : Brackets -- Echec de l’installation.

MSI (c) (50:7C) [10:28:00:653]: Windows Installer installed the product. Product Name: Brackets. Product Version: 1.3. Product Language: 1033. Manufacturer: brackets.io. Installation success or error status: 1603.

**Comment by abose** [comment]
Could you switch the os language to English and execute `msiexec /i {path\of\Brackets.msi} /Lime {path\of\\logFile.txt}`

**Comment by petetnt** [comment]
This is the error: https://support.microsoft.com/en-us/kb/834484 

Here's some more possible solutions: http://www.msigeek.com/715/how-to-troubleshoot-the-error-1603-fatal-error-during-installation

**Comment by vhanadium** [comment]
@petetnt thx the problem was that this value NtfsDisable8dot3NameCreation was at 2 instead of 0 in the regedit

**Comment by abose** [comment]
Closing as fixed.
