### ISSUE TITLE
Remember undo history

### ISSUE THREAD

**Issue by ile** [adobe/brackets#11158]
How about remembering the undo history between closing/re-opening the project folder and even between closing/restarting the whole editor?

Would be often useful.

**Comment by AuntyPoll** [comment]
I agree, it would be very helpful. Although I am still learning, it is really handy to be able open recently closed files. I went looking for this feature today :-(

**Comment by mackenza** [comment]
@auntypoll there is an extension for mru files https://github.com/DH3ALEJANDRO/Show-Recently-Used

**Comment by petetnt** [comment]
There's a related Trello-card here: [local history/versioning @ Trello.com](https://trello.com/c/H8AyDwFA/391-local-history-versioning)

**Comment by prafulVaishnav** [comment]
Closing it as we are already tracking it. @ile Please upvote it [here](https://trello.com/c/H8AyDwFA/391-local-history-versioning)

**Comment by ile** [comment]
Hi,

I upvoted, thanks.

But Brackets really needs something like this badly. As it's now, if I change the "opened folder" in the left panel, I lose all the editing history. And, as I can have only one "main folder" (you could also call that a project), and switching between projects is a frequent operation, I tend to lose the editing history a lot.

This makes the editor almost impossible to use, unfortunately. Unless I missed something/I'm doing womthing wrong/there is an extension to help to remember the editing history.

**Comment by petetnt** [comment]
@ile I wrote this extension to enable remembering editing history between projects / closing brackets.

https://github.com/petetnt/brackets-persistent-history

It's still WIP so your mileage may vary but it's worth trying! Basic functionality is there and it *should* work well

**Comment by ile** [comment]
Awesome, @petetnt! 

Just came back to Brackets to see if there's improvement here, and there were. Seems to exactly what I was looking for. Great! Thanks a bunch and kiitos!
