### ISSUE TITLE
Search only inside specific file type?

### ISSUE THREAD

**Issue by FezVrasta** [adobe/brackets#11151]
I need to search, for example, the string `fullscreen` only inside the `.hbs` files, is it possible?

If not, I think it would be a great addition.

I tried to write this on Trello but I don't know how to :/

**Comment by prafulVaishnav** [comment]
@FezVrasta We already have [card](https://trello.com/c/9IBv6zRq/1359-find-in-files-inclusive-additive-filters) for this. Please upvote this card. Closing it as we already have this item in backlog
