### ISSUE TITLE
Indentation-type should depend on file type

### ISSUE THREAD

**Issue by Lichtjaeger** [adobe/brackets#11153]
I use whitespaces with an incrementation of 2 for .jade, .styl and other whitespace sensitive files.
For .html, .css and other files that use closing tags or brackets I prefer to use tap stop with an incrementation of 4.

It would be usefull if brackets can remember the last indentation option I used for a specific file type and automatically change the preference back when I switch to another file type.

**Comment by busykai** [comment]
@Lichtjaeger, you can configure different indentation for different file extensions or different languages. You can use either global preference file (*Debug -> Open Preferences File*) or per-project file configuration file (`.brackets.json`). See [pref scope](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#scope-of-preferences) for more details. For example, the following would configure indentation of 4 spaces in files with "*.js", 2 spaces in files which have language "html" and will use tab everywhere else:
```
{
    "path": {
        "*.js": {
            "spaceUnits": 4,
            "useTabChar": false
        }
    },
    "language": {
        "html": {
            "spaceUnits": 2,
            "useTabChar": false
        }
    },
    "spaceUnits": 4,
    "useTabChar": true
}
```

Additionally, there's a Proper Indent extension, it would detect the indentation in the currently opened file and would set it for you automatically, independently of its language and the editor's configuration.

**Comment by Lichtjaeger** [comment]
I didn't know that I can scope my preferences.
It works.

Thanks.

**Comment by busykai** [comment]
glad it helped.
