### ISSUE TITLE
Extract needs better error reporting for connection errors

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#11164]
See #9793, #11147, #10901

Users are experiencing the following error despite being connected to the internet (due to firewall restrictions or other networking reasons):

![image](https://cloud.githubusercontent.com/assets/7641760/7806369/98c7c1a2-0388-11e5-8ac9-dec09b5b9840.png)

My guess is that the "*please connect to the internet*" is being used as catch-all for all connection errors. More accurate reporting would make debugging issues like ones mentioned easier, plus less confusing for the users. If more accurate error isn't possible, I'd say that that a more vague one (such as *there was a connection error, please try again later...*) would be less confusing for the user.

**Comment by prksingh** [comment]
I have logged this internally for extract for brackets. The team is not working on Extract for brackets for release 1.4 though. So there may be some delay in picking up this issue

**Comment by petetnt** [comment]
:+1: Thanks @prksingh.

**Comment by abose** [comment]
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
