### ISSUE TITLE
Change code folding shortcut as it is used for pipe (|) on Mac

### ISSUE THREAD

**Issue by Garito** [adobe/brackets#11173]
Hi!
Anyone has noticed that the fold feature is using the keystrokes to add a pipe (|)?
That is to fold we use alt + 1 so in mac is the pipe

Could someone correct this?

Thanks!

**Comment by rroshan1** [comment]
@Garito 
You can override Brackets default keyboard shortcuts in the `~/Library/Application\ Support/Brackets/keymap.json` file. You can even reassign another key binding for an action.

Please refer #11114 for details on the fix and do let us know if this solves your issue.

**Comment by Garito** [comment]
Sure, but don't you think that this shortcut is a troublemaker?
Think would be more sane for all us to use a better one instead to tell anyone how ask to change it

What do you think?

**Comment by Garito** [comment]
BTW doing what you point brackets raises "Alt+1" is an invalid shortcut

**Comment by Garito** [comment]
And doesn't work at all

**Comment by abose** [comment]
Alt +1 was used as a standard shortcut in many of the windows apps for collapsing code; So to keep with consistency; we used the same shortcut in all the platforms so that people moving from windows to mac version of brackets have less friction in doing so. 
But yes it seems that had a use case in mac that we overlooked.
What would you suggest as a shortcut in mac for expand and collapse all.
@thehogfather

**Comment by Garito** [comment]
Don't really care. What I do care is if I can use the pipe (which in Jinja2 is used)
I'm not a good candidate for this question since I don't really use fold/unfold too much so don't need a shortcut for that

Could you point me why I can't dissable it?

Thanks!

**Comment by abose** [comment]
@Garito You could disable by `debug menu> open preferences file>` add `"code-folding.enabled": false` to file.

**Comment by Garito** [comment]
Oh, no! I don't wanna disable folding (I almost never use it but when I need it it is super usefull)
What I want is to disable the shortcut!
I've tryed keymap.json thing but the error I point out above is raised

Any alternative way?

**Comment by MarcelGerber** [comment]
Added to Release 1.4 milestone. We've heard multiple reports of this being an issue, so we should really consider changing it.

**Comment by Garito** [comment]
Thanks a lot!
Tell me if you need something :)

**Comment by abose** [comment]
@MarcelGerber what about collapse all with `cmd+1` and `cmd+shift+1` for expand in mac?

**Comment by rroshan1** [comment]
Yes.. That should be good.. Similar to Sublime on Mac. :+1:

**Comment by Garito** [comment]
Those shortcuts seem to be free right now so good for me too

**Comment by prafulVaishnav** [comment]
Raised [PR](https://github.com/adobe/brackets/pull/11273) for this

**Comment by abose** [comment]
This is fixed for brackets 1.4. closing the issue.

**Comment by Garito** [comment]
Thanks a lot!
