### ISSUE TITLE
Request: Multi-line Find and Replace

### ISSUE THREAD

**Issue by ybitso** [adobe/brackets#11179]
Docked window for Multi-line Find and Replace

**Comment by rroshan1** [comment]
@ybitso 
We already have a card in Trello for it. Please upvote this card https://trello.com/c/yho8jb7y/1082-find-replace-allow-matching-across-lines-n-or-multiline-regex-or-replacement-text-containing-newlines so that we can prioritize this task.
Closing this issue.
