### ISSUE TITLE
Ruby on Rails inline view comments break tag matching and syntax highlighting

### ISSUE THREAD

**Issue by AndrewFreemantle** [adobe/brackets#11170]
The hash `#` character seems to throw out the editor, which results in tag matching, indentation assistance and syntax highlighting not working correctly for subsequent lines of code:

![github-brackets-issue-11170](https://cloud.githubusercontent.com/assets/1304992/7831322/91937abe-044d-11e5-8769-6538de6b1f94.png)

*File extension:* `.html.erb` (Embedded Ruby)
*Theme:* Brackets Dark, *and* Brackets Light (Default)
*Version:* Release 1.3 build 1.3.0-16022 (release cd0a6aae5), build timestamp: Fri Apr 24 2015 01:53:21 GMT-0700
*Issue exists with all extensions disabled:* ✓

**Comment by MarcelGerber** [comment]
This is already fixed in Release 1.4.
It apparently was some fix in CodeMirror we got for free in our merge.

![image](https://cloud.githubusercontent.com/assets/2641501/7897139/cb1f849a-06d1-11e5-8102-802c328eb441.png)
