### ISSUE TITLE
Small typo in wiki

### ISSUE THREAD

**Issue by abea** [adobe/brackets#11172]
In [How to Use Brackets](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets)

Current version: "The content is served statically from a built-in server that Brackets run — it doesn't contain any of your app's backend logic."

Correction (bolded): "The content is served statically from a built-in server that Brackets **runs** — it doesn't contain any of your app's backend logic."

**Comment by busykai** [comment]
Fixed, thank you!
