### ISSUE TITLE
Can't close and cancel save

### ISSUE THREAD

**Issue by bobrocke** [adobe/brackets#11186]
If I attempt to close an open file from the Working Files pane and click `Don't Save` in response to the Save Changes dialog, the file will not close.

Maybe this only happens with a split view? I'll try to confirm.

**Comment by bobrocke** [comment]
No, it happen without a split view, too. But I still can't reliably reproduce it.

**Comment by MarcelGerber** [comment]
Closing. Seems to be an extension problem (per Slack).
