### ISSUE TITLE
Open recent files - in other directories

### ISSUE THREAD

**Issue by szabgab** [adobe/brackets#11192]
While working on a project sometimes I also need to open some unrelated files. Then if I close the, it is hard to find them again. Would it be possible to add an "Open Recent files" menu option that would list the 10-20 most recently opened files? Probably only keeping the files that are not related to any of the open projects.

**Comment by nethip** [comment]
@szabgab Yeah I think this would be really helpful. I have created a trello card for this. https://trello.com/c/B85Z2Hod/1422-open-recent-files. Please upvote it.
