### ISSUE TITLE
Add a "back button" that returns to the last edited file

### ISSUE THREAD

**Issue by fritzwf** [adobe/brackets#11206]
A back button that would return you to the last file you were editing.  It would also update the left file pane to show the file in the pane (if the file/folder list is long and cannot fit entirely into the pane).  This would be helpful if you are editing a particular file and you just need to look at another file in the project to possibly copy some code or whatever, and then go back to editing the previous file.  This is currently a pain when your project is large and you have to navigate the file structure to go to the other file, and the navigate it again to re-ropen the file you were actually editing.

**Comment by redmunds** [comment]
Does `Ctrl-Tab` do what you need?

**Comment by PatchGuru** [comment]
``` Ctrl-Tab ``` should be exactly what you need for a "back button". Works quickly to switch between recently edited files.

**Comment by prafulVaishnav** [comment]
@fritzwf You can also use SplitView feature of Brackets and open two files at once vertically/horizontally. Enable this feature through menu `View > Vertical Split` or `View > Horizontal Split`

**Comment by lkisac** [comment]
If I hit `Ctrl-J` to jump to a function definition, `Ctrl-Tab` will not switch back to that same function call.  Can this be achieved?

**Comment by tusharjagtap** [comment]
In which release was this issue fixed?
