### ISSUE TITLE
Docs for Prefs code hints 

### ISSUE THREAD

**Issue by abose** [adobe/brackets#11200]
- [x]  Update wiki pages on how to define code hints for preferences
- [x]  JS Docs for define preference.
- [x]  remove data.json
- [x]  Find out core preferences that has not used the define preference API and add prefs docs.
- [x]  Update preference WIKI pages.
- [x]  Mail brackets committers/slack channel about the new API. Create entry in release notes for 1.4 for API change.

**Comment by abose** [comment]
Update the wikis
https://github.com/adobe/brackets/wiki/Preferences-System and https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences

**Comment by sprintr** [comment]
> Find out core preferences that has not used the define preference API and add prefs docs.

I think @MarcelGerber covered this story in #11197.

**Comment by abose** [comment]
Yes, but I see that some properties are still left not defined as a preference. But that could go in at a later time.

**Comment by MarcelGerber** [comment]
@abose Which preferences do you still see un-defined?
From what I can tell, every preference is defined, unless you're talking about things that should be preferences but aren't (JS Code Hints comes to mind)

**Comment by abose** [comment]
@nethip I remember you mentioned about undefined preferences, Could you specify which ones did you see as udefined?

**Comment by sprintr** [comment]
I don't think there are any undefined preferences, [since we suppress](https://github.com/adobe/brackets/blob/015400e6d53dcbe3eeacbf901f2c31e863412a13/src/document/DocumentCommandHandlers.js#L661) `defaultExtension` pref, so it got excluded from code hints. `_windowsScrollFix` was excluded intentionally.

**Comment by nethip** [comment]
@sprintr I am working on this story https://github.com/adobe/brackets/issues/11056 wherein we are going to display default preferences along with brackets.json side by side in the split view. Right now I am regenerating default preferences by looping through all preferences using this call `PreferencesManager.getAllPreferences()`. While iterating through all preferences, I found that the following preferences do not have description field.

```
"linting.asyncTimeout": 10000,
"linting.usePreferredOnly": false,
"codehint.TagHints": true,
"codehint.AttrHints": true,
"codehint.SpecialCharHints": true,
"codehint.CssPropHints": true,
"staticserver.port": 0,
"codehint.UrlCodeHints": true,

```

**Comment by MarcelGerber** [comment]
Those are the exact ones we altered in #11197.

**Comment by nethip** [comment]
@MarcelGerber Yes I see that these are now going through `definePreference`, but the description is missing for all the properties.

**Comment by MarcelGerber** [comment]
I see, but #11201 should have fixed that.

**Comment by nethip** [comment]
@MarcelGerber you are right. I must be working on my branch which might have not this change.Thanks for pointing out the PR.

**Comment by sprintr** [comment]
I believe this can now be closed since all the checklist items are done.

**Comment by abose** [comment]
Thanks @sprintr . Closing as done.
