### ISSUE TITLE
last position missing(?)

### ISSUE THREAD

**Issue by pipiscrew** [adobe/brackets#11215]
hi,

I would like when editing a file and Im on line 35, imagine I press CTRL+F (search) and landed on line 780 press a key-combination to return on *last position* aka line 35!

thanks

**Comment by MarcelGerber** [comment]
You can already do that using `Cmd/Ctrl+U` (or `Ctrl/Cmd+Alt+U` for redo).
In general, this shortcut undoes changes including cursor/selection changes.

**Comment by pipiscrew** [comment]
wow, working, 

Ctrl+U - Last Position
Ctrl+Shift+U - Next Position

@MarcelGerber thanks!!

undocumented(?)
https://github.com/adobe/brackets/wiki/Brackets-Shortcuts

**Comment by redmunds** [comment]
@pipiscrew When I open the Display Shortcuts panel, I see those shortcuts listed.

**Comment by MarcelGerber** [comment]
@redmunds Would you mind adding these two shortcuts to the wiki page linked to above? They are not currently listed over there...

**Comment by redmunds** [comment]
@MarcelGerber Oops, I thought @pipiscrew was referring to Display Shortcuts extension.

Added. FYI, you should be able to update the wiki, so let Ryan know if you can't.

**Comment by MarcelGerber** [comment]
I can, but I'm a lazy guy that doesn't have the extension installed right now ;)
