### ISSUE TITLE
Cannot parse EJS Trim-mode ending tag -%>

### ISSUE THREAD

**Issue by everbeen** [adobe/brackets#11220]
Cannot parse `-%>` tag ([trim-mode ending tag][npm]):

![1](https://cloud.githubusercontent.com/assets/188089/8018748/8f0b9f70-0c5d-11e5-908f-abfafe4ecad2.png)

[npm]: https://www.npmjs.com/package/ejs#features

When change to `%>` it works:

![2](https://cloud.githubusercontent.com/assets/188089/8018751/96b07e6c-0c5d-11e5-8e64-4c3f2ae6a965.png)

**Comment by MarcelGerber** [comment]
This is already fixed in the upcoming Release 1.4.
It apparently was some fix in CodeMirror we got for free in our merge.
