### ISSUE TITLE
Pick up new CodeMirror in release 1.4?

### ISSUE THREAD

**Issue by bobrocke** [adobe/brackets#11228]
Are there already plans to pick up the new version of CodeMirror (with the new Twig mode) for version 1.4 of Brackets? I use a lot of Twig mixed with HTML and am looking forward to making a multimode extension using the "real" Twig and HTML modes. Maybe JavaScript, too.

**Comment by abose** [comment]
Usually, code mirror integrations happen early in the cycle as that would give us enough testing window. The last code mirror integration happened as part of #11167 (cm master as on  May 26, 2015). The next code mirror integration will happen after release 1.4 if there are no blocking issues.

**Comment by bobrocke** [comment]
OK, so most likely in v1.5. Is Brackets still on a 4ish-week release/sprint cycle?

**Comment by abose** [comment]
yes, 1.4 is due within the next 2 weeks.

**Comment by bobrocke** [comment]
Thanks.

**Comment by mackenza** [comment]
I realize this is now closed so forgive me for commenting on a closed issue. 
I just wanted to note that the post 1.0 release cycle has been more like a point release every 2 months or so.  @bobrocke if cm is updated at the beginning of the 1.5 release cycle you would be able to use the new Twig mode right away if you run Brackets off master.
