### ISSUE TITLE
Disable JavaScript Hinting

### ISSUE THREAD

**Issue by doostinharrell** [adobe/brackets#11231]
Is there a way to completely disable javascript hinting within brackets?  Every time I change the file language to javascript on a .js file Brackets freezes and is unusable. I have to pull up task manager and kill all processes and relaunch to continue coding.

I have tried running Brackets without extensions and the issue persists. 

Any assistance would be appreciated!

Thanks!

**Comment by redmunds** [comment]
Set the `codeHint.JSHints` preference to false as described [in this doc](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences).

**Comment by doostinharrell** [comment]
Thanks! That worked.
