### ISSUE TITLE
make to be able to uncheck file/folders associations in explorer

### ISSUE THREAD

**Issue by bambus1980** [adobe/brackets#11233]
make to be able to uncheck file/folders associations in explorer. It some times can break OS because didn't working properly. My OS WindowsXP (I know it that didn't supported).
![2015-06-09_11-41-22](https://cloud.githubusercontent.com/assets/12805956/8049035/9d84cae0-0e9c-11e5-8658-44fdccb50aa5.png)
As you can see on screenshot, dblclick on folder didn't simple open folder but open Brackets with this folder.

**Comment by nethip** [comment]
@bambus1980 Please uninstall Brackets and while reinstalling, from the below installer window, make sure to **uncheck** "Add Open With Brackets to Explorer context menus for all files and folders". This would remove the entries in the explorer context menus.

![image](https://cloud.githubusercontent.com/assets/1577184/8050279/25c8cc22-0e88-11e5-883c-c97af07ab921.png)

**Comment by bambus1980** [comment]
Thank you, it is really helped me. But it will be better to add this option in Brackets settings.

**Comment by nethip** [comment]
We are depending on installer to do this, as it helps in managing the program installation scope meaning when uninstalling, it just undoes every thing that was part of the installation. In the above case, upon installation it would remove the explorer context menu entries, had you chosen "Add "Open With Brackets"..." option.

**Comment by bambus1980** [comment]
I understand, thank you.
