### ISSUE TITLE
Open dialog does not reflect changes on disk

### ISSUE THREAD

**Issue by bobrocke** [adobe/brackets#11237]
Using Mac OS X 10.10.3 and Brackets 1.3, changes made on disk are not reflected in Brackets' open dialog.

For example, if a new extension is added, you can't browse to that folder in Brackets until you quit and restart Brackets.

**Comment by MarcelGerber** [comment]
So you're saying you can neither see nor open files/folders created after Brackets was started?
To me, this sounds more like an OS issue, as Brackets just uses the built-in OS X dialog.

**Comment by bobrocke** [comment]
Well.....

That's what I was saying. But now I can't reproduce the steps to demonstrate the problem! That's good (for Brackets, because there's nothing to fix), and bad (for me, because I might be going crazy).
