### ISSUE TITLE
Updating to 1.3 instead of replacing existing version

### ISSUE THREAD

**Issue by miguelpaz** [adobe/brackets#11230]
I download the Brackets 1.3 version on MacOS Yosemite. Instead of updating my current version, it wants to replace the existing version.

**Comment by mackenza** [comment]
This is by design, I believe. The installers are not updaters, unless I am missing something. But this should not be of concern as the personalizations (state, installed extensions, configuration / prefs) are not erased or lost when you reinstall as they are not kept in the install location.

**Comment by ryanstewart** [comment]
Yup, we overwrite the existing location. But as @mackenza says your preferences, extensions, and anything else user generated will stay.

=Ryan

**Comment by miguelpaz** [comment]
That was my main concern so it`s ok. Thanks to both of you.

2015-06-08 12:47 GMT-04:00 Ryan Stewart <notifications@github.com>:
