### ISSUE TITLE
Feature request: Entered search string in extension search should remain when switching search area tab

### ISSUE THREAD

**Issue by netsi1964** [adobe/brackets#11247]
When I do a search for installed extensions and then switch to a search in all extensions or themes the entered string is cleared. However sometimes the search string is also relevant for a search in another tab area.

**Comment by prafulVaishnav** [comment]
@netsi1964 I think that's a good idea. I have submitted a [PR](https://github.com/adobe/brackets/pull/11254) for this. @ryanstewart @nethip @abose @prksingh @rroshan1 What you think on this?

**Comment by TomMalbran** [comment]
BTW, that is how the search worked after the initial PR, and the opposite was requested #5856 and fixed #7388. So if we implement this, we should be clear about what to do.

**Comment by abose** [comment]
Closing as the decision to clear the search string on tab switch was an XD choice.

**Comment by netsi1964** [comment]
@abose what is a "XD choice"?

**Comment by abose** [comment]
XD = Experience Design. We used to keep the search query on tab switched, but that was confusing to some. So brackets Experience Designers opted to clear the search filter on tab switch.
