### ISSUE TITLE
js function

### ISSUE THREAD

**Issue by pipiscrew** [adobe/brackets#11241]
hi again,

when some ***function*** written on line 900 and there is a ***call*** to this function on line 3, how we go to line 900 with a click ?

**Comment by mackenza** [comment]
if it's JS, you can put your cursor on the call on line 3, then `navigate -> jump to definition` or ctrl-j. If it's PHP (which I am guessing based on some of your prior questions), someone would need to write a QuickSearch for PHP extension, I believe.  To my knowledge, such an extension does not currently exist.

**Comment by pipiscrew** [comment]
@mackenza thanks!
