### ISSUE TITLE
Right click copy and paste by default.

### ISSUE THREAD

**Issue by thenbman** [adobe/brackets#11243]
A real faux pas of Brackets is not having cut/copy and paste on right click, I mean for goodness sake notepad has it on. 
The extension that is right click extended is useless, it never works and that's on different machines, with different OS.

**Comment by Denisov21** [comment]
I create this extension: https://github.com/Denisov21/Popup-menu-extension

**Comment by Denisov21** [comment]
Please vote: https://trello.com/c/ZriVEu50/935-clipboard-cut-copy-paste-in-editor-context-menu

**Comment by thenbman** [comment]
Hi Denis,You've become my hero 😎 thank you so much, it works perfectly. The right click extension that is always promoted if you like just never worked for me.
Many thanksNigel

Date: Wed, 10 Jun 2015 14:32:44 -0700

**Comment by Denisov21** [comment]
Now @thenbman can close this issue!
