### ISSUE TITLE
global - js intellisense (?)

### ISSUE THREAD

**Issue by pipiscrew** [adobe/brackets#11240]
hi, 

I realize, when editing a ***html*** file and press ctrl+space intellisense appears... 

![snap507](https://cloud.githubusercontent.com/assets/3852762/8086930/b8538532-0fa0-11e5-97c3-117b2ba06673.png)

when editing a ***php*** file (which is 50% mix w/ html+js) there is no intellisense!!

![snap508](https://cloud.githubusercontent.com/assets/3852762/8086936/bc20560e-0fa0-11e5-85d5-fcd3ef8ce381.png)

**Comment by mackenza** [comment]
@pipiscrew for "intellisense" (which is called Code Hints in Brackets) on PHP files, you can use one of the code hint extensions. I, being biased as I wrote it, would suggested Brackets PHP SmartHints, but there is at least one other in the extension registry. In Brackets go to the extension manager and search for PHP and see what's out there for PHP. I will warn you that it's not as well supported as JS is and your overall PHP experience won't be as good as, say, PHPStorm or another PHP IDE.

**Comment by pipiscrew** [comment]
@mackenza yes, ***PHP SmartHints*** suggested on previous post, the request is to have intellisense for js on .php files

thanks

**Comment by mackenza** [comment]
oh, I see... sorry, I didn't get the nuance there.
