### ISSUE TITLE
HTML autocomplete doing horrible things

### ISSUE THREAD

**Issue by Tigt** [adobe/brackets#11253]
Screenshot:

![Screenshot of Brackets prematurely ending an <em> tag, swallowing the adjacent phrase "width-constrained." as part of the closing tag name.](https://cloud.githubusercontent.com/assets/8072522/8123146/5574ff84-1092-11e5-88ac-02f12714d6cd.png)

To reproduce:

1. Open an .html file
2. Insert caret directly before non-whitespace text
3. Write an HTML element's opening tag

Brackets will then prematurely auto-close the tag as soon as you type `>`, and somehow include the adjoining text as part of the closing element tag name. It seems like it will go until the next word boundary.

This behavior persists when reloading without extensions. I really don't want to do a fresh install halfway through a project, but as you can imagine this makes editing HTML a miserable experience.

OS X 10.10.3 (14D136)

Brackets info:
Release 1.3 build 1.3.0-16022 (release cd0a6aae5) 
build timestamp: Fri Apr 24 2015 01:53:21 GMT-0700

**Comment by nethip** [comment]
@Tigt This behavior can be overridden using a preference. Open the preference files from *Debug->Open Preferences File*. That would open the preferences file *brackets.json*. Please add this code to *brackets.json*.

```
"closeTags": {
    "whenOpening": false
 },
```

**Comment by Tigt** [comment]
Instant relief. Thank you so much; I was worried I was going to have to fix a regex somewhere.

**Comment by nethip** [comment]
:smile:
