### ISSUE TITLE
Brackets can't find Chromium on Windows

### ISSUE THREAD

**Issue by 2bdkid** [adobe/brackets#11265]
I have Chromium installed from [googleapis.com](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/334343/)

But Brackets cannot find it for Live Preview. I tried adding the chrome.exe directory to the path but that didn't work.

**Comment by nethip** [comment]
@2bdkid Hmmm Interesting. Have you enabled multi browser preview by choosing *File->Enable Browser Preview*.

But you could try the following steps.

1) Install Google Chrome
2) *File->Enable Multi Browser Preview*, launch live preview 
3) Launch live preview and make sure it opens live preview in google chrome window
4) Copy the URL and from the address bar and paste it in Chromium browser.

There is no guarantee that this could work as by default, clicking on the live preview icon is only going to launch google chrome.

Having said that we have never tried testing live preview on Chromium browser.

**Comment by 2bdkid** [comment]
The "Enable Experimental Live Preview" option is making it work in Chromium. Thank!
