### ISSUE TITLE
CodeMirror simple mode doesn't load

### ISSUE THREAD

**Issue by kerabromsmu** [adobe/brackets#11267]
I've created a highlight mode for Factor language, and made it use CodeMirror's simple mode. But it didn't work because simple mode is not loaded by the Brackets. Is it possible to add the simple mode module to Brackets?

**Comment by sprintr** [comment]
Brackets doesn't load all the modes provided by CodeMirror. You'll have to load it yourself in an extension. [Read this wiki](https://github.com/adobe/brackets/wiki/Language-Support#defining-a-new-language) to learn how to add a new language.

**Comment by kerabromsmu** [comment]
I have read it, and it doesn't help. Try using simple mode to define a new language, and you'll find it doesn't work.

**Comment by petetnt** [comment]
Similar to #10501
