### ISSUE TITLE
Automatic ' ' or " "

### ISSUE THREAD

**Issue by noahfernstrom** [adobe/brackets#11269]
if you write e.g. id=" " / id=' ' you have to write two '  /  " it will be better if brackets automatically writes two ' / " e.g. i write class=" / class=' and automatically transform it to class=" " class=' '.

Noah 
P.S Sorry my English. )-:

**Comment by RaymondLim** [comment]
@noahfernstrom What you're asking is already available in Brackets, but is not on by default. You just have to turn it on from Edit > Auto Close Braces.

**Comment by Noffica** [comment]
@noahfernstrom Thanks for asking this question. I also wanted this.

**Comment by TomMalbran** [comment]
if you accept the codehints in html, it will both complete the hint and add from start and close quotes and move your cursor.

I am not sure if it should do that by default with no user input since it feels a bit intrusive and it might fail to do what you want in many cases.

**Comment by rroshan1** [comment]
@noahfernstrom As mentioned in the comments earlier, enabling "Auto close braces" from Edit menu will address your issue. 
Closing the issue for now. Please feel free to get back here in case you need it.
