### ISSUE TITLE
Suggestion: Remember previous colors used in css

### ISSUE THREAD

**Issue by ebadler** [adobe/brackets#11270]
For example, if you started to type the css attribute "background-color: " and the auto-hint box displayed all the previous colors you used. If you typed "background-color: #f" it would show all the ones that begin with f. Additionally, it would be great if you could declare colors as variables in brackets. For example, if you are making a website with a gold color scheme and want to primarily use 6 shades of yellow, 3 shades of gray, and 2 shades of red, you could name your colors "yellow1", "yellow2", etc, or alternatively name them something like "main-red", "secondary-red", "dark-red" etc. Then when you type "background-color:y", among the hint suggestions that already come up like "yellow" and "yellowgreen", the user-defined colors like "yellow1", "yellow2" show up. This would be an HUGE time saver!

**Comment by rroshan1** [comment]
Thanks for the suggestion! Please raise a card for this to track on Trello <https://trello.com/b/LCDud1Nd/brackets>. Depending on the number of upvotes on it, we can prioritize it or someone from the community could work on it.

**Comment by nethip** [comment]
@ebadler Did you consider switching to LESS/SASS. A part of your use case mentioned above will get addressed if you are using LESS/SASS.
