### ISSUE TITLE
brackets doesn't open all psd templates

### ISSUE THREAD

**Issue by filip-mustatea** [adobe/brackets#11272]
I try to open large psd different templates.Some open, others are not.  Any suggestions why not open all?

**Comment by prafulVaishnav** [comment]
@filip-mustatea Do you see any errors for the psd not opening? Please go to `Debug > Show Developer Tools` and check console tab is any error.

**Comment by filip-mustatea** [comment]
The psd template appears in brackets, but it shows: Error displaying error file. An error occurred when trying to display  the file files / name of the file. In the attachment, you cand see the the capture image with the error.  Also in Developer Tools, appears: Failed to load resource: the server responded with a status of 409 (Conflict) . 


     În Luni, 15 Iunie 2015 13:45:52, Praful Kumar Vaishnav <notifications@github.com> a scris:
   

 @filip-mustatea Do you see any errors for the psd not opening? Please go to Debug > Show Developer Tools and check console tab is any error.—

**Comment by filip-mustatea** [comment]
Also i made my own custom template(50mb file size) and it works fine. It doesn't work with other psd templates from my clients. 


     În Luni, 15 Iunie 2015 14:53:03, Alexandru Mustatea <filip.mustatea@yahoo.com> a scris:
   

 The psd template appears in brackets, but it shows: Error displaying error file. An error occurred when trying to display  the file files / name of the file. In the attachment, you cand see the the capture image with the error.  Also in Developer Tools, appears: Failed to load resource: the server responded with a status of 409 (Conflict) . 


     În Luni, 15 Iunie 2015 13:45:52, Praful Kumar Vaishnav <notifications@github.com> a scris:
   

 @filip-mustatea Do you see any errors for the psd not opening? Please go to Debug > Show Developer Tools and check console tab is any error.—

**Comment by nethip** [comment]
@filip-mustatea Will you be able to share to PSD. It would be great if you can as that would help us identify which specific element in the PSD is causing this issue. Also would you mind uploading the same asset at https://assets.adobe.com/files and see if you are able to open the same there?

**Comment by filip-mustatea** [comment]
Yes, I can. Where I can load the PSD?

**Comment by nethip** [comment]
@filip-mustatea Great! Please upload it at https://assets.adobe.com/files and choose *Send Link* from drop-down which appears at the bottom of the asset.

**Comment by filip-mustatea** [comment]
http://adobe.ly/1HVXYbg this is the psd

**Comment by nethip** [comment]
Thanks @filip-mustatea . We will take a look at this. Another question. Were you able to use extract service from the above link, where you have uploaded this PSD?

@prafulVaishnav Would you mind downloading this PSD and see where we are breaking?

**Comment by filip-mustatea** [comment]
No. I was able to use extract service. You can download and take a look. Thanks.

**Comment by nethip** [comment]
Yeah I am able to open up this asset via ccweb. We should probably dig in more inside E4B itself.

**Comment by filip-mustatea** [comment]
I will wait  your answer. Thanks a lot.

**Comment by filip-mustatea** [comment]
Anything?

**Comment by prafulVaishnav** [comment]
@filip-mustatea @nethip I am able to use given PSD in E4B w/o any error. @filip-mustatea Is this psd consistently throwing error in opening? Given 409 error given by error, can you please share the response body of the request which is failing?

**Comment by ficristo** [comment]
Extract is deprecated: http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/
Closing

**Comment by maxvizual** [comment]
just replace node.exe from 1.7 version
