### ISSUE TITLE
Open file to a line number from command-line

### ISSUE THREAD

**Issue by mrjbq7** [adobe/brackets#11277]
I can't see how to open a file to a line number in the documentation (https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#command-line-integration).

That's a really useful feature we'd like to use from our editors integration in https://github.com/slavapestov/factor.

Thanks!

**Comment by MarcelGerber** [comment]
You can do so using Quick Open.
Invoke Quick Open using `Ctrl+Shift+O` (on Windows), then type the file name or parts of it, followed by a trailing colon and the line number.

For example, to open `EditorCommandHandlers` to line 134, you can type `dch:134`

**Comment by mrjbq7** [comment]
Thats awesome from the UI, but is that possible from the command-line?

**Comment by MarcelGerber** [comment]
Oh, I see now. I don't think there's anything like this right now.

**Comment by mrjbq7** [comment]
Also, I can't figure out how to use the command-line to "open a file into [existing Brackets if running else a new Brackets]".

**Comment by nethip** [comment]
@mrjbq7 We have command line integration only for 1.3. Make sure you are on 1.3 for this command line feature to work.

**Comment by sprintr** [comment]
Think what @mrjbq7 Wants is to open a file at a certain line. E.g

```bash
brackets main.js:100
```
It should open main.js at line 100.

**Comment by nethip** [comment]
@sprintr Yeah you are right about the "go to line" number not working through command line. I was replying to @mrjbq7 's latest comment.

**Comment by MarcelGerber** [comment]
@nethip From what I can tell, the command-line integration works for him, all he wants is a way to open files in an existing Brackets instance it has been launched before.

**Comment by mrjbq7** [comment]
@nethip on Mac OS X, if I run the ``Brackets.app/Contents/MacOS/Brackets`` twice, I get two instances of Bracket.  I was wondering how to open a file into a running instance, or launch a new instance if not running.

**Comment by nethip** [comment]
@mrjbq7 On MAC we don't parse the command line via `argv` passed to `main`, which is the typical way of parsing command line in any C/C++ application. We parse the command line through `applescript`. You could check `openFile` and `openFiles` objective C selectors that are overridden by our brackets-shell on MAC. Keeping out all the technicalities follow the steps below to use `brackets` via command line.

1) Choose *File>Install Command Line Shortcut*. This is going to install necessary scripts required for `brackets` command line to work. 
2) Relaunch `Terminal` and use `brackets <filename/foldername>`. This is going to take care of whether to launch new instance or use existing instance to load the file or folder.

**Comment by mrjbq7** [comment]
Isn't ``brackets`` just a bash script that does ``open -a Brackets.app file:line``?

That's a fine workaround for now, although it would be great if the line functionality works (the original report).  Thanks for the info on the command line shortcut.

**Comment by nethip** [comment]
@mrjbq7 Yes! The `Install Command Line Shortcut` does exactly `open -a <Brackets.app>`. It installs a shortcut in `/usr/local/bin` which has some script code that launches the right `Brackets` instance, from which the script was installed (through `File>Install Command Line Shortcut`) which would be really handy in case you have multiple versions of `Brackets` on your system.

About the `go to line number`, I have created a trello card for this. Please up vote [this](https://trello.com/c/ikTpxs58/1424-ability-to-browse-to-a-specific-line-in-a-file-using-command-line)
