### ISSUE TITLE
Comment large amount of code

### ISSUE THREAD

**Issue by Claw-Hammer** [adobe/brackets#11279]
Brackets 1.3.0-16022 (release cd0a6aae5) crash when i did comment a large amount of code in a .php file. I'm using Windows 7 Pro x64 - No errors logged

**Comment by MarcelGerber** [comment]
How large is _large_ (in lines, preferably).

Can you also try `Debug > Reload without extensions` to see if it's caused by an extension?

**Comment by Claw-Hammer** [comment]
Hi.-

About 150 lines of code, but i think it was caused by Live Reload
extension, i'm trying again, thanks

2015-06-15 13:30 GMT-04:30 Marcel Gerber <notifications@github.com>:

> How large is *large* (in lines, preferably).
>
> Can you also try Debug > Reload without extensions to see if it's caused
> by an extension?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/11279#issuecomment-112153799>.
>



-- 



                     Julio Vergara
                Caracas - Venezuela
       http://www.tecnored.blogspot.com
http://www.habanosenvenezuela.blogspot.com

**Comment by abose** [comment]
@Claw-Hammer Was the extension responsible for this issue?

**Comment by abose** [comment]
Closing inactive thread.
