### ISSUE TITLE
Can't get live preview working with angular routing and webserver

### ISSUE THREAD

**Issue by Fatxx** [adobe/brackets#11286]
Hi there,

I have a webserver with a virtualhost set to my application, the routing is handled by angular router. I already have defined my virtualserver name at "Project Settings..." but when I launch Live Preview it sends me to the file location I've opened in Brackets, not letting angular handle the routes which breaks the application. 

Is there any way to work with angular and a webserver within Brackets?

**Comment by pupkah** [comment]
Hi,
I'm facing the same issue. Does anyone know the answer?
Thank you!
