### ISSUE TITLE
Add New Hinting for MYSQLi

### ISSUE THREAD

**Issue by sahilr2050** [adobe/brackets#11289]

**Comment by abose** [comment]
MySql I think is part of the web domain. So brackets core could support mysql syntax hilighting.

**Comment by MarcelGerber** [comment]
@abose We already have the `SQL` language, which uses CM's MySQL syntax highlighting.

What this issue is about is, I think, MySQL Hinting, as we can see [in this CM demo](http://codemirror.net/mode/sql/) (hit `Ctrl-Space` to show hints).

**Comment by abose** [comment]
got it! Would be good to have I think. We will be adding health logs this release to get the distribution of standard file types being edited in brackets. I will update this thread after that.

**Comment by sahilr2050** [comment]
Mysql and Mysqli is different.
