### ISSUE TITLE
Right click open folder like visual studio code - Windows 8.1

### ISSUE THREAD

**Issue by wormeyman** [adobe/brackets#11281]
I love the shell integration with brackets and the only thing missing for me is the ability to right click inside a folder and have it open with brackets. Visual Studio Code has this ability and it is so convenient not to have to navigate up a folder to open it which is what i currently do with brackets. I tried really hard to see if this was a duplicate but this project is so large it is hard to search for an issue like this.

Some of the missing registry keys http://stackoverflow.com/a/29769228

Specifically:

`HKEY_CLASSES_ROOT\Directory\Background\shell` **if you are administrator**
`HKEY_CURRENT_USER\Software\Classes\directory\Background\shell` **if you are a normal user**

**Comment by redmunds** [comment]
When I right-click on a folder in Win7, I see an item for "Open as Brackets Project". Also, you can drag folder and drop it on Brackets to perform same action.

**Comment by wormeyman** [comment]
I mean right click in the blank space of a folder, as the registry calls it the background.

**Comment by abose** [comment]
@nethip Could we add this to the context menu eazily?

**Comment by nethip** [comment]
Yes this is very easy to do. It is just another registry entry.

**Comment by nethip** [comment]
I am marking this for 1.4.

**Comment by wormeyman** [comment]
Good news! Thanks everyone.

**Comment by nethip** [comment]
@wormeyman Unfortunately we could not find time for this in 1.4. I am moving this to the next release.

**Comment by wormeyman** [comment]
@nethip it doesn't look like this landed in 1.5?

**Comment by nethip** [comment]
Unfortunately this did not land in 1.5. I did not get time to make this change and validate. It is very easy to add this to the Explorer context menu. 

Please add the following entries to the registry.

```

Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\directory\background\shell\Brackets]
"Icon"="C:\\Program Files (x86)\\Brackets\\Brackets.exe"
@="Open As Brackets Project"

[HKEY_CLASSES_ROOT\directory\background\shell\Brackets\command]
@="C:\\Program Files (x86)\\Brackets\\Brackets.exe \"%V\""

```

You could actually save the the above contents as a .reg file and import it from Registry Editor.

1) Open Registry Editor using `Windows + R` and typing `regedit`
2) `File->import` and select the `.reg` file that you would have created with the above contents.

Note: As this involves changing registry, please take extreme care in making changes to registry.

**Comment by wormeyman** [comment]
@nethip I have been using the registry change successfully, however it looks like this did not land in 1.6?
