### ISSUE TITLE
Extension Manager - pressing return key in search box closes the dialog

### ISSUE THREAD

**Issue by gullyfoyle** [adobe/brackets#11288]
Pressing the return key while the search box clearly has focus closes the extension manager dialog. I'm not sure if this is intentional? It doesn't seem intuitive to me. 

* __Windows 8.1__
* __Brackets__ Release 1.3 build 1.3.0-16022

**Comment by MarcelGerber** [comment]
Already filed under #6904.
Closing as a dupe.
