### ISSUE TITLE
"About" popup missing credits

### ISSUE THREAD

**Issue by derek-skinner** [adobe/brackets#11285]
In the "About" window popup, the bottom line is missing the credit to the team/people who built Brackets. 
It currently just says "Made with ♥ and JavaScript by: <blank>"

![screen shot 2015-06-16 at 10 17 49 am](https://cloud.githubusercontent.com/assets/801299/8189422/0e7f0764-1411-11e5-890e-ec54f808ec8c.png)

**Comment by ryanstewart** [comment]
If you scroll down in that window, does it show? Sometimes the images are just below the fold.

**Comment by derek-skinner** [comment]
I was not able to scroll down until I loaded Brackets without Extensions for some reason. Must be just some weird bug instead of an actual issue with Brackets.
