### ISSUE TITLE
Bracket frame work in browser !!!

### ISSUE THREAD

**Issue by hirenvanza** [adobe/brackets#11287]
Can We Type code and Run Directly in Browser only ???
like w3school  providing "Try it your Self" & other website also...

**Comment by nethip** [comment]
@hirenvanza Did you try our live preview feature in Brackets. Please look at the following link https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#live-preview.

**Comment by abose** [comment]
@hirenvanza If you are looking for running brackets natively in browser, you could look at the following forks of brackets 
https://github.com/humphd/brackets
https://github.com/mozilla/nimble

**Comment by abose** [comment]
Closing inactive thread.
