### ISSUE TITLE
Quick Find Definition with no files open

### ISSUE THREAD

**Issue by meancode** [adobe/brackets#11294]
I am coming over from using Sublime Text 3. And I use Cmd-T all the time. Brackets seems to have duplicated this functionality for opening files in a project, but with one major drawback, if no files are open, I cannot hit Cmd-T to open/find a file in my project.

Is it possible to utilize the Quick Find Definition UI when no files are open?

**Comment by sprintr** [comment]
You can use `Ctrl-Shift-O` when no files are open.

**Comment by prafulVaishnav** [comment]
@meancode Cmt-T shortcut is used for `go to Defintion` in file which require a file to be opened. As @sprintr mentioned, use `Cmd-Shift-O` for opening files in the project.

**Comment by prafulVaishnav** [comment]
@meancode You can override the shortcuts. Steps mentioned [here](https://github.com/adobe/brackets/wiki/User-Key-Bindings)

**Comment by meancode** [comment]
Never knew that, thanks guys!

I was just hitting Cmd-T and deleting the @ thus allowing me to open files.
