### ISSUE TITLE
Error when trying to open any PSD file

### ISSUE THREAD

**Issue by Zewkin** [adobe/brackets#11292]
Uncaught SyntaxError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': 'files/main.psd' is not a valid HTTP header field value.

**Comment by tkisme** [comment]
now this bug still exists on mac

**Comment by tkisme** [comment]
Now I know chinese filename not supported,change the filename to english such as 1.psd can fix this problem,but it NEED TO FIX

**Comment by abose** [comment]
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
