### ISSUE TITLE
Find Filter is Cleared

### ISSUE THREAD

**Issue by randdusing** [adobe/brackets#11296]
1. Cmd + F
2. Type "Hello World"
3. Edit an instance of "Hello World"
4. Search for the next instance

Unfortunately "Hello World" is cleared out between steps 3 and 4. Is there any way to prevent the find filter from being deleted?

**Comment by MarcelGerber** [comment]
The current behavior is suboptimal, and we know that, but you can always use `F3/Cmd-G` to find the next instance.

**Comment by randdusing** [comment]
Ahh, I didn't know about cmd-g. That works well enough for me
