### ISSUE TITLE
eclipse alt move text

### ISSUE THREAD

**Issue by android272** [adobe/brackets#11297]
whenever moving from eclipse to any other text editor the one thing I always miss is the ability to select text, hold alt and press up or down to move the text up or down lines.

the nice thing about how they do this is you only have to select one character in a line to move it. so if you have two lines you want to move up you can select the whole first line and one character and then move it. this also works for new lines which is very nice when you want to move something in the middle of text and keep the spacing.

**Comment by MarcelGerber** [comment]
This works in Brackets by pressing `Ctrl + Shift + Up/Down`. Is that what you're looking for?

**Comment by android272** [comment]
Oh my goodness thank you yes. This might take a while to get used to as aposed to the alt+Up/Down but this is nice.

**Comment by TomMalbran** [comment]
@android272 You can change the shortcuts to anything you want. More info here: https://github.com/adobe/brackets/wiki/User-Key-Bindings

**Comment by TomMalbran** [comment]
And closing since this is already implemented.

**Comment by rroshan1** [comment]
I think we should update the `Edit> Move Line Up/Down` menus to "Move Line/Selection Up/Down" for clarity.

**Comment by TomMalbran** [comment]
It move the selected lines, not the actual selection... Maybe "Move Selected Lines Up/Down

**Comment by rroshan1** [comment]
Yes, it's even better. 
May be we can discuss on Slack.
