### ISSUE TITLE
Display issue with dual screen

### ISSUE THREAD

**Issue by MomoGunz** [adobe/brackets#11304]
![capture](https://cloud.githubusercontent.com/assets/13026820/8321862/bd57200c-1a2c-11e5-9090-84f0fa77d415.PNG)
Hi,

As you can see on the screenshot, there is a little display issue when using Brackets with two screens. To reproduce the bug, enlarge the Brackets' window while still having a part of the window on the other screen. I don't know if I am clear enough so here is another screenshot : 
![capture2](https://cloud.githubusercontent.com/assets/13026820/8321910/74061182-1a2d-11e5-90b7-f2427c638ceb.PNG)
At this point, enlarge the Brackets' window and you'll get the bug.

Thanks !

**Comment by abose** [comment]
@MomoGunz I am not able to see the screenshots. [screenshot upload problem?]

**Comment by MomoGunz** [comment]
![capture](https://cloud.githubusercontent.com/assets/13026820/8323899/bf9a82a0-1a4a-11e5-8403-63a4a5d1f989.jpg)
![capture2](https://cloud.githubusercontent.com/assets/13026820/8323900/bfb6e72e-1a4a-11e5-8d51-107e43f2f0d0.jpg)

I made a mistake when taking the screenshot, excuse me.
Here are respectively capture and capture2.

**Comment by MomoGunz** [comment]
I cannot reproduce the bug with the latest version of Brackets on Windows 10.

**Comment by abose** [comment]
This looks like a corrupted install/prefernces. Thus the reinstall might have fixed the problem.
Closing. Please reopen the issue if you face this again.
