### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by JeffreyArt1** [adobe/brackets#11300]
as a user I wish there was a splash screen at the beginning of the application

**Comment by sbruchmann** [comment]
![post-31230-ryan-reynolds-but-why-gif-haro-mffw](https://cloud.githubusercontent.com/assets/141435/8294150/ac095eca-193a-11e5-8443-1f7cd58c5ed7.gif)

**Comment by mackenza** [comment]
lol @sbruchmann

**Comment by ryanstewart** [comment]
@JeffreyArt1 can you elaborate on what exactly you mean/would want from a splash screen?

**Comment by NickersF** [comment]
Chiming in here. Splash screens are good if they output loading progress/information. Since brackets loads fast it doesn't really warrant the need for a splash image. Otherwise it's just aesthetics.

**Comment by abose** [comment]
I was about to tag this as an extension idea, but then i remembered brackets itself would not have been loaded at the time. 
@JeffreyArt1 How long does it take for brackets to load in your system? Do you suggest a splash screen because brackets loads slow on your machine or is it just for the :cool: :sunglasses: factor?

**Comment by JeffreyArt1** [comment]
@abose it takes about 5 secs to load, but for example in my friend's laptop it takes about 30-35 secs.
I suggest for slow pc's and for "good appearance".

**Comment by abose** [comment]
@JeffreyArt1 What is your system configuration/OS.
Does brackets load faster on subsequent launches after the first launch?

**Comment by JeffreyArt1** [comment]
@abose intel core i5 4200U / 8GB RAM
first launch 5-8 secs
after first launch: 1-3 secs
They could put a splash on at least four seconds at start of a program?

**Comment by abose** [comment]
which OS are you on? and the correct version number of the OS. How many extensions are installed by default?

**Comment by JeffreyArt1** [comment]
@abose i'm on Windows 8.1 Pro, and I have installed 7 extensions (w3c validator, extract, some themes etc.)

**Comment by abose** [comment]
thanks @JeffreyArt1 . The setup should have launched brackets within 2 secs on subsequent launches. We do not want to delay the load times for showing the splash screens. Usually brackets loads within 1-2 secs the second time onwards. We will be logging the startup time from this release onwards, If we are seeing concerns in startup performance across the board, we will target improving startup performance in the subsequent releases.
