### ISSUE TITLE
Auto-save files

### ISSUE THREAD

**Issue by cumminsd** [adobe/brackets#11317]
It would be awesome to auto-save all modified files in the editor when the editor loses focus. You could then make a change, click on the browser window (losing focus on Brackets) and then you would see your changes update in the browser. Other IDE's do this and it definitely increases productivity.

**Comment by humphd** [comment]
I've done a version of this as a custom extension in my fork, if you want to try in Brackets:

https://github.com/humphd/brackets/blob/bramble/src/extensions/default/Autosave/main.js

**Comment by abose** [comment]
@cumminsd Thanks for reporting this issue. In brackets you could do this using the live preview feature, and that does not even require any file saving. Autosave on focus switch is a bit worrying to me especially fo js/non html-css files. I think that rightly fits in the extension territory for those who prefer it.
@humphd Is the extension available in the brackets extension registry?
