### ISSUE TITLE
Unable to load rpm CodeMirror mode

### ISSUE THREAD

**Issue by manderson23** [adobe/brackets#11314]
I was investigating trying to write an extension to support RPM spec file syntax highlight. From reading the wiki my understanding was the the following should suffice
```
LanguageManager.defineLanguage("rpm", {
        name: "RPM",
        mode: [ "rpm", "text/x-rpm-spec" ],
        fileExtensions: ["spec"],
        lineComment: ["#"]
    });
```
However the developer console shows the following error
```
CodeMirror mode "rpm" is not loaded        /language/LanguageManager.js:995 
(anonymous function)
```
From searching issues and PRs I came across #3912 which mentioned rpm modes being a special case but my understanding is that specifying the MIME type should load the correct mode even though the mode name in https://github.com/adobe/CodeMirror2/blob/923bf9b9b9f03fe4a00454ffaccf9422f71e2d1c/mode/rpm/rpm.js is ```rpm-spec```.

**Comment by sprintr** [comment]
This should do the trick.

```js
define(function (require, exports, module) {
	var LanguageManager = brackets.getModule("language/LanguageManager");
	brackets.getModule(["thirdparty/CodeMirror2/mode/rpm/rpm"], function () {
		LanguageManager.defineLanguage("rpm", {
	        name: "RPM",
	        mode: ["rpm-spec", "text/x-rpm-spec"],
	        fileExtensions: ["spec"],
	        lineComment: ["#"]
    	});
	});	
});
```

**Comment by manderson23** [comment]
Thanks.
