### ISSUE TITLE
Brackets Uninstallaton in order to reset its settings to default does not take effect...

### ISSUE THREAD

**Issue by motealle** [adobe/brackets#11319]
When i installed brackets it was fully working and i satisfied instantly.
but when i changed some settings, the live preview function corrupted completely, i don't remember
ITS DEFAULT VALUES to set them again on base URL field or such. And i cant find it on docs either.
I tried reinstalling it, to reset these settings to default but all my settings and extensions remain intact after a complete re-installation.
it's really boring. please help.

**Comment by abose** [comment]
if you are on windows, go to %appdata%  (run>%appdata%)  and delete the Brackets folder.
relaunching brackets will clear your preferences.

**Comment by abose** [comment]
Closing inactive thread. Please feel free to reopen if you still face the issue.

**Comment by Diggerati** [comment]
thank you abose this helped me too
