### ISSUE TITLE
[IQE] : [Ctrl+PageUp/PageDown] Navigate menu blinks on file traversing on MAC

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11327]
Steps To Reproduce:

1) Launch Brackets
2) Open and edit some files in the Working set
3) Use Ctrl+PageUp/PageDown Shortcut to traverse files

Result: Navigate menu blinks on each traversal

ENV : Release 1.4 build 1.4.0-16190 (master e35f2a4b5) 
OS- MAC 10.10.02

**Comment by nethip** [comment]
@rawat11 This is not a bug but an OS feature. The shortcut is listed in the `Navigate menu` and they why you see the blink.
