### ISSUE TITLE
Please integrate Lingohub for translations!

### ISSUE THREAD

**Issue by diomed** [adobe/brackets#11323]
Can you please integrate translations into [Lingohub](https://lingohub.com)
which is free for open source projects, so you could ease up on translators,
so we don't have to look all around what's translated and what's not, and fix and change things with simplicity, instead of wandering within the code?

**Comment by nethip** [comment]
@diomed Thanks for letting us know about [LingoHub] (http://lingohub.com). I had a word with their support guys and it looks like they don't have a straight forward GitHub connector yet. Also they don't process strings present in code files (which is the case with us) but rather take standard formats like eg: .init/angular.js e.t.c. Let us know once they have an improved workflow and then we would definently give it a try.
