### ISSUE TITLE
[IQE] : [Ctrl/Cmd +(Shift) + Tab] for file traversing doesn't work on MAC 

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11329]
Steps To Reproduce:

1) Launch Brackets
2) Open and edit some files in the Working set
3) Use [Ctrl/Cmd +(Shift) + Tab] Shortcut to traverse files

Result: Doesn't work on MAC

ENV : Release 1.4 build 1.4.0-16190 (master e35f2a4) 
OS- MAC 10.10.02

**Comment by nethip** [comment]
@rawat11 This works for me. Try resetting the preferences and see if that fixes the issue.

**Comment by rawat11** [comment]
@nethip but this worked on windows without setting any prefernces. Do we have to set preferences for MAC

**Comment by rawat11** [comment]
Yes it worked with (Cmd+shft+])
