### ISSUE TITLE
Debugging and stepping through brackets code

### ISSUE THREAD

**Issue by omefire** [adobe/brackets#11332]
How do I step through brackets code ?

I have cloned the repo, but now I want to step through the code and have a look at its behavior. so far, I haven't been able to figure that out..
Any help ?

**Comment by sprintr** [comment]
Go to `Debug` -> `Show Developer Tools`. You can step through the code there.

**Comment by omefire** [comment]
Hmmm, seems like I might be able to get what I want by just loading it into chrome ?

**Comment by omefire** [comment]
@sprintr , thanks. I want to step through brackets' code itself, not through my app's code.

**Comment by TomMalbran** [comment]
`Debug -> Show Developer Tools` open the devtools of Brackets with Brackets code, not yours. Since Brackets shell is essentially a version of chromium, it can use the same developer tools as Chrome.

**Comment by sprintr** [comment]
`Debug` > `Show Developer Tools` is only for Brackets' own code. Switch to Sources tab to have a look at the files.

**Comment by omefire** [comment]
cool, didn't know that.
does it work in Ubuntu, I see nothing when trying it on my Ubuntu box.

**Comment by sprintr** [comment]
I am not sure about its functionality on Ubuntu. You should open up an issue if it doesn't work for you. @TomMalbran Has this been reported earlier?

**Comment by TomMalbran** [comment]
I don't remember, and I don't know if it works or not.

**Comment by sprintr** [comment]
I don't remember either. Search also didn't help.

**Comment by omefire** [comment]
Thanks guyz, I've opened an issue regarding this : https://github.com/adobe/brackets/issues/11334

**Comment by omefire** [comment]
Another question, now that I've been able to open the `Debug > Show Developer Tools` (in Windows) :
    - Every file seems to be minified and starts with :  "eval("/*\r\n * Copyright (c) 2012 Adobe S ..."
    How do I 'unminify' them all ? (to faciliate setting breakpoints and stepping through the code ?)

**Comment by TomMalbran** [comment]
You need to load Brackets using the code from the repo. Here are the instructions:
https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets#setting-up-your-dev-environment

**Comment by omefire** [comment]
Awesome! I'm all set up and can already step through the code.
Thanks a lot !

**Comment by mackenza** [comment]
This totally works on ubuntu, I use it almost every day
