### ISSUE TITLE
Splitscreen UX

### ISSUE THREAD

**Issue by Wikunia** [adobe/brackets#11345]
It would be awesome to right click on a file and choose the name of the splitted screen to display the content in that screen. Or a drag & drop feature. At the moment I don't know how to see the content of an unopened file on the "second" screen.

**Comment by petetnt** [comment]
Similar to #11308

**Comment by prafulVaishnav** [comment]
@Wikunia Single left click on the file in project tree will show the content of the file in the focused screen. You can use (View > Vertical/Horizontal Split) and drag & drop the file to desired split view. If second screen is in focus then left click on file in project tree will be opened in that screen.
