### ISSUE TITLE
Old traffic lights on OS X El Capitan

### ISSUE THREAD

**Issue by alexbock** [adobe/brackets#11342]
It appears that a lot of the support for OS X Yosemite in brackets-shell is predicated on the system version being exactly 10.10 (rather than checking for 10.10 or later). This causes the old "gumdrop" traffic lights to appear on OS X 10.11 El Capitan (and breaks fullscreen mode, but I see #11268 already exists for that).

**Comment by nethip** [comment]
@alexbock I have already fixed this. This [PR](https://github.com/adobe/brackets-shell/pull/526) should take care of it.

**Comment by nethip** [comment]
And we most likely would target this for 1.4. If you are familiar with Cocoa/C++ programming, feel free to take a look that PR and provide your comments.

**Comment by edfullest** [comment]
When is this fix going live?

**Comment by abose** [comment]
release 1.5 by this month end. Closing as fixed.

**Comment by theone1989** [comment]
It seems that this issue happens again after 10.11.1 update
![brackets](https://cloud.githubusercontent.com/assets/4074434/10680932/56f42308-78f2-11e5-8f7c-844a2b82580c.png)

**Comment by abose** [comment]
Please update to brackets 1.5 which has the fix for the issue.

**Comment by theone1989** [comment]
I think I found the problem, this happens on additional windows of Brackets.(Already updated to 1.5)
![brackets2](https://cloud.githubusercontent.com/assets/4074434/10688480/82bff1a6-7942-11e5-8b47-7531528a2bfe.png)

**Comment by abose** [comment]
That would be fixed in 1.6 :sweat_smile: we missed that case for 1.5.
https://github.com/adobe/brackets/issues/11827
