### ISSUE TITLE
Preview files while browsing up and down in the Quick Open results

### ISSUE THREAD

**Issue by astorije** [adobe/brackets#11350]
It would be very useful to open (not completely open but display its content) the file that is highlighted. If one goes up or down, the opened file changes at the same time. It gives a better incentive when hesitating on which file one is looking for.

This is default behavior in Sublime Text FYI.

**Comment by nethip** [comment]
@astorije Are you talking about the quick view in ST that appears one the right side?

**Comment by astorije** [comment]
I am not sure anymore about what I meant a year and a half ago, sorry. And sorry I did not answer immediately, I very quickly moved to Atom that more appropriately fulfilled my needs and did not switch back.

I am closing this, best of luck on this project and thanks for your collective efforts!
