### ISSUE TITLE
Mac not loading PSD's

### ISSUE THREAD

**Issue by andreimarin90** [adobe/brackets#11353]
Hi guys,

I'm using brackets successfully on a Windows pc, however my MAC PC just won't load PSD's. It takes forever to load even the tiniest PSD's, and when it does finally finish, it usually crashes when I try to open the PSD. Is there anything I might do to fix this?

**Comment by prafulVaishnav** [comment]
@andreimarin90 Do you see any errors for the psd's not opening? Please go to `Debug > Show Developer Tools` and check console tab if any error

**Comment by andreimarin90** [comment]
Hi,

Yes. As soon as something gets uploaded it shows this: https://www.dropbox.com/s/4ddepm7pcdt2e62/Screenshot%202015-07-07%2012.49.48.jpg?dl=0 

and then if it eventually gets opened up I get: https://www.dropbox.com/s/58246jev3l02y1b/Screenshot%202015-07-07%2012.50.06.jpg?dl=0 , https://www.dropbox.com/s/9rk1l4lmtm9ua20/Screenshot%202015-07-07%2012.50.20.jpg?dl=0 , https://www.dropbox.com/s/tthynkk08klo4ub/Screenshot%202015-07-07%2012.50.34.jpg?dl=0

Great job overall with the app guys

**Comment by prafulVaishnav** [comment]
@andreimarin90 Do you have any extensions installed? Can you please reload Brackets Without Extensions `Debug > Reload Without Extensions ` and let me know if problem exists.

**Comment by andreimarin90** [comment]
I don't have any extensions, but I did and the same kinds of errors are
coming up. I can try reinstalling if you think it would help. for what's
worth, it actually seems to be working a bit better with the debug tool
active (weird), but still very slow and tends to crash when using real-life
size PSD's and not the tiny ones I was trying before.

**Comment by prafulVaishnav** [comment]
@andreimarin90 Can you please reset Cache and Preference as given [here](https://github.com/adobe/brackets/wiki/Cache-Folder#resetting-cache--preferences). Cache Location on Mac is `~/Library/Application Support/Brackets/`

**Comment by ficristo** [comment]
Extract is deprecated: http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/
Closing
