### ISSUE TITLE
Mac上的文件夹和文件排序不正常（Sidebar filesort exception）

### ISSUE THREAD

**Issue by starriv** [adobe/brackets#11358]
其他编辑器应该为文件夹优先于文件的这种排序方式
(Other editors, such as ATOM, should be higher than file folders sorted)

#### This is the sort Brackets file

![qq20150709-3 2x](https://cloud.githubusercontent.com/assets/7098001/8585922/1e6d275c-261b-11e5-93ff-889307e9cd35.jpg)

#### This is the sort ATOM file 
![qq20150709-2 2x](https://cloud.githubusercontent.com/assets/7098001/8585722/b2055a0a-2618-11e5-9f4e-4424a17084a5.jpg)

Thanks

OS: Mac OS X 10.10
Brackets : Brackets 1.3.0

**Comment by sprintr** [comment]
Add this as a preference,
```json
"sortDirectoriesFirst": true
```
[Here](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#list-of-supported-preferences) is a complete list of supported preferences.
