### ISSUE TITLE
Second Brackets window issues

### ISSUE THREAD

**Issue by dnbard** [adobe/brackets#11352]
I'm opening second window via `Debug > New Brackets Window` and place it to second monitor workspace. Select first (main) window. Then select second window via mouse-click.

At this point focus clearly was switched to second window. But I'm unable to do anything since second window does not responds to key pressing. If I click to second window once more with the mouse then second window become usable.

OS: Windows 7
Brackets v1.3

**Comment by nethip** [comment]
@dnbard Unfortunately Brackets does not perform in a multi window environment. We are tracking this item at https://trello.com/c/YM0YySxX/679-multiple-separate-windows-official-new-window-command. Please upvote this card that will help us prioritising this issue.
