### ISSUE TITLE
problem of window, the code is not visible

### ISSUE THREAD

**Issue by EmixDev** [adobe/brackets#11351]
These screens will explain the problem : 
![brackets problem issue github](https://cloud.githubusercontent.com/assets/10252674/8531145/a01eb95c-2425-11e5-99a0-18e84ee32983.png)
For precision, i can't scrolling
Sorry for my bad english..

**Comment by nethip** [comment]
@EmixDev Could you try loading `Brackets` without extensions. You could do this. `Debug > Reload Without Extensions`. If you don't see any problem after that, it is most probably some extension which is causing the issue.
