### ISSUE TITLE
Code folding not working well with multi-line-attributes tag in html

### ISSUE THREAD

**Issue by liuxiaole** [adobe/brackets#11356]
Steps to repro:

Write some HTML like below:
```html
<div title="very long content
with 
line breaks">
    <p>abcdefghijk</p>
</div>
```
or
```html
<div data-options="some options"
     data-tips="some tips">
    <p>abcdefghijklmn</p>
</div>
```

Fold the `<div>` tag and then unfold it. Now if you'd like to fold this tag again, you'll find that it doesn't work.

OS: Mac OS X 10.10.3 & Windows 7
BracketsVersion: 1.3.0-16022

**Comment by thehogfather** [comment]
@prafulVaishnav I've got a pretty good idea why this is happening - happy to submit a pr in the next couple of days if no one is assigned.

**Comment by prafulVaishnav** [comment]
@thehogfather Thanks. Currently, one is assigned so Please go ahead and submit a PR.

**Comment by thehogfather** [comment]
@prafulVaishnav you can check out and test PR #11366 as a fix for this issue.
