### ISSUE TITLE
Illustrator Integration

### ISSUE THREAD

**Issue by mimoYmima** [adobe/brackets#11354]
Why all the focus on pulling info from photoshop, the current trend in web design is toward vector / svg / illustrator.  It would be nice to have tighter Illustrator integration with brackets.  I just downloaded it so forgive me if that's already possible but the website talks a lot about ps and not at all about Illustrator.

**Comment by ficristo** [comment]
Extract is deprecated http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/
Closing
