### ISSUE TITLE
Cyrillic characters in extract

### ISSUE THREAD

**Issue by SPAHI4** [adobe/brackets#11362]
Cyrillic characters in extract are copying from layer as html entity, not as normal characters

**Comment by nethip** [comment]
@prafulVaishnav Please have a look at this.

**Comment by SPAHI4** [comment]
still nox fixed(

**Comment by SPAHI4** [comment]
still nox fixed(

**Comment by Constantine-k** [comment]
Yeah, it's no way to copy cyrillic text from Extract properly. It's a big bummer for everyone who works with Russian text...

**Comment by abose** [comment]
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
