### ISSUE TITLE
Extension description vs localization?

### ISSUE THREAD

**Issue by dvorapa** [adobe/brackets#11363]
I miss the possibility to make localized descriptions for extensions (e.g. inside of the package.json file). I know it is not really easy to add that possibility, but I think it is great idea to realize.

**Comment by Denisov21** [comment]
Hi,
Already exists @dvorapa!
You must following this step:

1. Open a file package.json
2. Edit e.g. (for Italian language):

"package-i18n": {
        "it": {
            "description": "Un'estensione per Brackets che aggiunge ulteriori funzionalità al menù contestuale: taglia, copia, incolla, salva tutto, notazione a cammello, maiuscole, minuscole e alcune funzionalità dal menù di modifica.",
            "title": "Menù contestuale Brackets"

**Comment by dvorapa** [comment]
Really? Thank you, I'll try it!

**Comment by Denisov21** [comment]
@dvorapa I have update comment!

**Comment by dvorapa** [comment]
Thank you again
