### ISSUE TITLE
Measure the Line Indentation

### ISSUE THREAD

**Issue by HanSolo0001** [adobe/brackets#11360]
I've seen several text editors have built-in measuring for line indentation. So it would look a little something like the following:

```html
<div>
|  <header>
|  </header>
</div>
```

Is this something you all could please implement into Brackets?

**Comment by redmunds** [comment]
If you are you referring to the vertical lines between opening and closing tags, then try the Indent Guides extension.

**Comment by abose** [comment]
Closing inactive thread.
