### ISSUE TITLE
[Feature request] Word-wrap per open file

### ISSUE THREAD

**Issue by mkoske** [adobe/brackets#11377]
Hello, 

a feature request: make word-wrap work per open file, i.e. if you have multiple files open, changin word-wrap settings in one doesn't affect others.

Thanks!

**Comment by valtlait** [comment]
This is possible now:

```json
    "path": {
        "csp-raportit.log": {
            "wordWrap": false
        }
    }
```

See https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#a-sample-preferences-json-file- for more information.

**Comment by mkoske** [comment]
Seems I can set it also by filetype. Thanks!
