### ISSUE TITLE
[Preferences Code Hints] Not all preferences are displayed while viewing Code Hints

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11385]
Steps:
1) Launch Brackets and open Preferences file
2)Start typing for any preference

Result:
All the preferences are not displayed eg themes

Note: We have to explicitly type 't' and then it is displayed

![2015-07-13 13_56_28- c__users_rawat_appdata_roaming_brackets_brackets json tracker - brackets](https://cloud.githubusercontent.com/assets/10069885/8645686/17ac75f4-2967-11e5-8373-c99649ac27ac.png)

Preferences ends on 'S'

**Comment by sprintr** [comment]
We have a preference `maxCodeHints` which is by default set at 50.

**Comment by rawat11** [comment]
Got it. I can see all the preference
