### ISSUE TITLE
Opening preferences brackets.json in split view along with default preferences, switches to split view not vice versa

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11386]
Steps:
1 Launch Brackets and open Preferences file
2 The editor switches to split view
3 In Brackets.json file, edit the preference "preferencesView.openPrefsInSplitView": true,
set it to false

4) Reload Brackets
5) Open preferences again

Result:

The previous state of file is opened since we are still in split mode doesnt switch to no split view, we have to explicitly change it to "No Split mode"

**Comment by nethip** [comment]
@rawat11 This was omitted for release 1.4. We should target this in the later releases. How about tracking this as a trello card?

**Comment by rawat11** [comment]
@nethip Surely we can take it up in next release, should I form a trello card ?

**Comment by nethip** [comment]
@rawat11 Yes please! And close this issue as we will track the trello card.

**Comment by rawat11** [comment]
Closing the issue. 
Trello details: https://trello.com/c/sFbpQZqL/1427-opening-preferences-brackets-json-in-split-view-along-with-default-preferences-switches-to-split-view-not-vice-versa
