### ISSUE TITLE
An error occurred when trying to view the folder files

### ISSUE THREAD

**Issue by glen-84** [adobe/brackets#11384]
![55a36f70168ba](https://cloud.githubusercontent.com/assets/261509/8645495/2bfe1db0-2948-11e5-99ec-7f482dede00d.png)

**Comment by nethip** [comment]
@glen-84 Will you be able to share the asset?

**Comment by glen-84** [comment]
I haven't selected a file yet.

**Comment by nethip** [comment]
@glen-84 Could you open developer tools from `Developer > Show Developer Tools` and post the console log.

**Comment by glen-84** [comment]
http://ctrlv.in/603620

I'm using Node 0.12.6, if that matters. (Windows 7)

**Comment by nethip** [comment]
@glen-84 hmm. This looks like a client side error. We have had issues earlier with some firewall access and also some AV programs are blocking access to `localhost`. Could you confirm if there is any AV program on your system, which might be blocking accessing `localhost`?

**Comment by glen-84** [comment]
I disabled AVG and the Windows firewall, and I still get the error.

**Comment by nethip** [comment]
@glen-84 OK Do you have any extensions installed? Can you try running Brackets without this extensions to figure out if any extension is causing this issue? Follow the steps below.

* Open `%AppData%\Roaming\Brackets`
* Rename this folder so you don't loose any settings or extensions
* Launch Brackets.
* Check if you are able to use extract from within Brackets.

**Comment by glen-84** [comment]
Same error. I only had one extension anyway (ShowWhitespace).

I updated Node to 0.12.7.0, and it's still not working. Is there code in Brackets that depends on an older version of Node? If so, when will this be updated? Older versions are insecure.

**Comment by nethip** [comment]
@glen-84 The version of node bundled with Brackets is 0.10.33.

**Comment by glen-84** [comment]
Which is insecure, as far as I know. This is quite possibly the reason why I can't get Extract to work. When will there be a new release of Brackets that supports Node 0.12.* ?

**Comment by glen-84** [comment]
I confirmed that Extract works with Node 0.10.33.0 (which is [insecure](http://ctrlv.in/603641)).

0.10.40.0 also works, and is secure.

Thanks.

**Comment by nethip** [comment]
@glen-84 Glad that this got resolved by changing the node version. Thanks for pointing out the security issues with 0.10.33. We will make sure node version is updated in the future releases.

**Comment by glen-84** [comment]
Thanks @nethip.

**Comment by jmordeno** [comment]
I just installed Brackets and I have the same error. Do I need to configure something in order to use this extension ?

**Comment by glen-84** [comment]
@nethip Brackets is still installing an insecure version of Node. When will this be fixed?

**Comment by nethip** [comment]
@glen-84 Agree with you that this needs to be fixed. Right now we are having a resource crunch and that is the reason we are not able to allot dedicated time for this work item as the scope is really huge. It would be great if you can take a look at it.

@swmitra Could you have a quick look at this and provide a rough estimate of how much work is involved here. I tried updating Node but ended up with issues.

**Comment by glen-84** [comment]
@nethip Just update it to `0.10.40.0`, which is secure, but within the same version range.

**Comment by Coderkid91** [comment]
@nethip 
Brackets is currently saying the same thing to me. "An error occurred when trying to view the folder files." It will not upload a PSD file for me at all. Is there a way to fix this yet?

**Comment by lokatsky** [comment]
![2016-11-21 16 38 59](https://cloud.githubusercontent.com/assets/19574074/20484632/205678c4-b009-11e6-869b-dd21de3da1f6.png)
@nethip
I have the same problem on my Mac. Can you help me to remove that problem?

**Comment by aqbarid** [comment]
![screenshot_102](https://cloud.githubusercontent.com/assets/9152125/20508833/f3e560e6-b096-11e6-8217-3e61a8052aa6.png)
@nethip Hello, i have the same problem here, i've tried just like @glen-84 do, but it not works for me. 
i also trying to reinstall bracket and node with other version but it's look like not working on me

**Comment by racnagore** [comment]
Hi! I had the same problem in Brackets 1.8, but Extract still works in 1.7.

**Comment by lokatsky** [comment]
Oh! Great! Thanx a lot. It's really working in 1.7.

**Comment by ficristo** [comment]
Extract is not supported anymore by Brackets:
http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/
