### ISSUE TITLE
Unresponsive - CSS w/ Base64 String

### ISSUE THREAD

**Issue by shaneparsons** [adobe/brackets#11393]
So this is kind of a weird bug and may be hard to replicate, which I apologize for.

Basically, brackets freezes when trying to open a big CSS file with a base64 string in it.

In my problematic CSS file, there are **10436** lines of code (concatenated vendor stylesheets) and within the CSS contains a base64 string (approx. **103327** chars).

The file is fine without the base64 string in it, and the string itself is fine on it's own and with smaller files, but the combination of the both causes brackets to freeze each time.. which I then have to force quit to get working again.

Let me know If you need further details or anything else from me.

Thanks.

**Comment by shaneparsons** [comment]
Here's an example of a problematic css file.

https://gist.github.com/shaneparsons/6c5bd2a9ff1f16fbe0bb

If you remove the base64 string (**line: 9953**) you'll notice it opens up fine.

**Comment by Hirse** [comment]
Have you tried to start Brackets without extensions?
There was a problem like this with one of my extensions, but I thought I fixed it in the last release.
https://github.com/Hirse/brackets-outline-list/issues/37

**Comment by shaneparsons** [comment]
Starting brackets without extensions still gives me the issue.

Also, #11250 refers to the issue only being there when buddy tries saving the file, mine wont even open to begin with.

**Comment by Hirse** [comment]
Alright.
It just sounded familiar.

**Comment by shaneparsons** [comment]
Yeaa thanks, I appreciate your input

**Comment by MarcelGerber** [comment]
Could you please test this in Release 1.4? It might very well have been fixed since, as there was some effort towards performance when looking at CSS.

**Comment by shaneparsons** [comment]
Seems to be fixed now!
Thanks
