### ISSUE TITLE
White line under title bar in kubuntu 15.04

### ISSUE THREAD

**Issue by kmoskwiak** [adobe/brackets#11394]
There is white line under title bar (above menu) when I start brackets from system shortcut (you can see it on left window in screenshot).
When I open second window (Debug -> New Brackets Window) there is no white line (window on right in screenshot).
![snapshot1](https://cloud.githubusercontent.com/assets/5294519/8656608/d1c86a0c-2998-11e5-99ac-1b904a5757df.png)

I tried it on several windows styles on kde, but the line was always there. Screenshot is taken for default window style in kde - breeze. It's not big issue, but it's little distracting when someone's working in dark.

When I worked on ubuntu with unity there was no line. 

OS: kubuntu 15.04 64-bit, kde plasma 5.3.1
Brackets: Release 1.3 experimental build 1.3.0-16022 (release cd0a6aae5)

**Comment by nethip** [comment]
@kmoskwiak Unfortunately we only support Ubuntu and Debian as of now. Feel free to open this bug, in case you are seeing this on the platforms. Thanks!
