### ISSUE TITLE
Can't change adobe id used for Extract extension

### ISSUE THREAD

**Issue by whatwasyouremail** [adobe/brackets#11395]
When registering for an adobe id to use for the extract extension, I mis-typed the email by accident.  So now I am unable to verify that email and I can't switch the one extract for bracket uses when clicking on Open a PSD->sign in for free button.  I tried uninstall and re-installing and searching for where it's storing the id it's trying to use in the registry or file but can't find it.  So the program is stuck in this state where it can't log in to use the extension since it's waiting for a confirmed email account and you can't switch which adobe id to use after signing up with the correct email address.

Steps to reproduce:
1) Install Extract extension if not already installed. 
2) Click open psd and then sign in for free button.
3) Signup for a new adobe account with wrong email address.
4) Exit out of app or a couple days, not sure when the  verification check kicks in.
5) Open app and extract extension again later and try to sign in.
6) Only options is to verify again or resend confirmation email.
7) Both of which you are stuck here forever using the wrong adobe id since you can't change or verify the confirmation email because it's an invalid email.
 
Brackets:
Release 1.3 build 1.3.0-16022 (release cd0a6aae5) 
build timestamp: Mon May 11 2015 10:52:31 GMT+0100

OS:
Windows 7 Enterprise SP1 64bit

**Comment by ryanstewart** [comment]
Can you go to Help->Sign Out of Creative Cloud?

If not, try `Ctrl`+`Shift`+`C` and that should reset everything.

**Comment by whatwasyouremail** [comment]
No go with the Sign Out of Creative Cloud, it shows as sign in to Creative
cloud... which brings up the dialog with the wrong email still.

Tried the Ctrl+Shift+C and that got some weird results.  So Ctrl+Shift+C is
mapped to Live Preview Higlight correct.  So had to enable live preview for
it to be enabled. Anyways after hitting Ctrl+Shift+C once when enabled, the
popup won't stay open, it opens and then quickly minimizes. I have to exit
the program and come back in to have the window stay open. The old email
address is still present when i do.

**Comment by ryanstewart** [comment]
Sorry, wrong shortcut on Windows. Try `Ctrl`+`Alt`+`C`.

**Comment by whatwasyouremail** [comment]
Looked like it reset things with a notification to click here to get
started with Extract but after selecting open psd file and then sign in,
the popup opens up but still has the invalid one.  No additional options
that I can see.

**Comment by UKRNAZ** [comment]
I had the same problem, to solve it I deleted brackets and deleted folder C:\Users\%username%\AppData\Brackets (or C:\Users\%username%\AppData\Roaming\Brackets) then I installed brackets again and everything was ok

**Comment by Zewkin** [comment]
The solution is to open developer tools from the window there Adobe is asking for email confirmation (right click) and delete cookies.

**Comment by luciadisanto** [comment]
I am having the same problem! I can't solve it, I have followed the above comments and had a go at each suggestion. Can you be more detailed in your description of deleting cookies please, I would so appreciate it.

**Comment by Zewkin** [comment]
@luciadisanto 
![untitled-1](https://cloud.githubusercontent.com/assets/3065426/14642346/c5ac567e-0652-11e6-9450-110251b8fdf1.png)

**Comment by luciadisanto** [comment]
Could you maybe be more specific about the following steps. 
![printscreen](https://cloud.githubusercontent.com/assets/15907765/14652059/8c1d8898-066a-11e6-8a9d-e1fe92bf0164.jpg)

**Comment by Zewkin** [comment]
@luciadisanto tab "Resources" -> Cookies

**Comment by luciadisanto** [comment]
Great thank you @Zewkin it worked that time

**Comment by abose** [comment]
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
