### ISSUE TITLE
Openssl.NET - SSL_get0_alpn_selected() returns NULL

### ISSUE THREAD

**Issue by IArun74** [adobe/brackets#11396]
SSL_get0_alpn_selected(IntPtr ssl, out IntPtr data, out int len); returns null. I’m using standard openssl console client and my own server ( with ManagedOpenSsl.dll) 
 
The exception thrown – "Cant get selected protocol. See if ALPN was included into client/server hello");
 
In Native.cs, this function is defined as below,

public static extern void SSL_get0_alpn_selected(IntPtr ssl, out IntPtr data, out int len);
 
Here is below the code for SSL_get0_alpn_selected() call, out ptr is always returns NULL.

public string AlpnSelectedProtocol
		{
			get
			{
				var ptr = new IntPtr();
				var len = 0;

				Native.SSL_get0_alpn_selected(Handle, out ptr, out len);

				if (ptr == IntPtr.Zero)
					throw new AlpnException("Cant get selected protocol. See if ALPN was included into client/server hello");

				var buf = new byte[len];
				Marshal.Copy(ptr, buf, 0, len);
				return Encoding.ASCII.GetString(buf, 0, len);
			}
		}
 
Here is my client hello commands, that I tried.
 
C:\OpenSSL-Win32\bin>openssl s_client -servername MyServer –connect x.x.x.x:443  -alpn tls
 
C:\OpenSSL-Win32\bin>openssl s_client -servername MyServer –connect x.x.x.x:443  -alpn tls1_1
 
C:\OpenSSL-Win32\bin>openssl s_client -servername MyServer –connect x.x.x.x:443  -alpn “tls1, tls1_1, tls1_2”
 
Thanks
Arun

**Comment by nethip** [comment]
@IArun74 Please use this forum for topics relating to `Brackets` application. From what you have posted above, it seems to be not related to anything to do with `Brackets`. I am closing this issue and feel free to open if at all it is relating to `Brackets` application (in which case please be a little more descriptive). Thanks!
