### ISSUE TITLE
[Health Data Log-New Metrics] Working File stat count does not increase on clicking the files from working set itself

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11403]
Steps:
1) Launch Brackets
2) Open some php files
3) open health data report
4) Click some files in the working set which is already opened and open health data report

Result : 
Working File stat count in "fileStats" does not increment on clicking the files in working set

**Comment by abose** [comment]
Working set files are only incremented when a file is added to the working set and not when a user has clicked on files in working set. It is as designed.
There exists a bug however that the working set files get incremented when we close a file in the working set.

**Comment by abose** [comment]
There also seems to be the other bug that does not track txt files opend in  brackets that you pointed out..
