### ISSUE TITLE
Brackets does not start as a nested application on Mac

### ISSUE THREAD

**Issue by jedkcanderson** [adobe/brackets#11405]
We have an application in which we ship Brackets.  The format on disk is:

`MyApp.app/Contents/MyApp/nested/path/to/Brackets.app`

Launching that Brackets.app both on the command line and from within our MyApp code fails.  Our expectation was that Brackets would have happily launched from inside MyApp.

To be clear, when we launch from within the code we use:

`MyApp.app/Contents/MyApp/nested/path/to/Brackets.app/Contents/MacOS/Brackets`

And this failed to launch with the following error:

`icudtl.dat not found in bundle`

We did some investigation of our own and found that copying the frameworks from the Brackets install to `MyApp.app/Contents/Frameworks` got us farther, but then we got stuck.  When we brought up this issue on the slack chat @nethip (I think I have the right Prashant, correct me if I'm wrong) suggested the following:

> I think there is lot of spaghetti going on there. I am baffled at how Mac OS just changes basic fundamental stuff like loading a dylib from release to release. I am suspecting the`install_name_tool` step. While I investigate more about it, I found a workaround. Just like you have copied Chrome Embedded Framework.framework to enclosing app's Frameworks folder,  copy the following libraries to the same location. Brackets Helper EH.app, Brackets Helper NP.app, Brackets Helper.app to the enclosing app's  Frameworks folder. Also you need to copy appshell_extensions.js and Brackets.sh from Resources folder of Brackets to Resources folder of the enclosing app. Try this out and let me know if it works. 

It did work!  And I have verified that just creating symlinks in the MyApp.app/Contents/Frameworks and MyApp.app/Contents/Resources directory is enough to launch the internal Brackets.

**Comment by ficristo** [comment]
@madanbn @nethip anything more to do here?
