### ISSUE TITLE
[IQE]: Health Data Report File Stat metric for working set does not capture the preferences file count opened from debug menu in the w

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11409]
Steps:
1) Launch Bracekts
2) Open preferences file from debug menu
3) Open Health Data Report

Result : Health Data Report File Stat metric for working set does not capture the preferences file count opened from debug menu, only openedFileExt count increases

**Comment by abose** [comment]
The main idea of tracking file types is to get the distribution of standard file extensions used by user. 
Since the Preferences is brackets centric, this will not affect the aggregate metric we want to track. So this won't affect the tracking requirements. 
Closing as never fix.

**Comment by rawat11** [comment]
@abose But don't we want to track, how many users are actualy making changes in the preferences file for which have brought a change and included default preferences file as well. We would definitely want to know the no of users making changes to their prefernces.

**Comment by abose** [comment]
The main intent is to get an approximate distribution of standard file types opened by the user. This metric is not intended to track the preferences file usage.
We only track the file extension right[say js].

**Comment by rawat11** [comment]
Got your point but I opened a json file which is not trackable how about that. And I understand that its the exception for preferences file which supposedly is json but we should have tracked it.
However I believe our intent is to capture any file that is being used in the editor be it prefernces or any other file. Up to you to decide :+1: :)
