### ISSUE TITLE
[Find In Files] : On Brackets first launch find in files doesn't work on "first" enter

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11418]
Steps: 
1 Launch Brackets
2 Start Find in files with CTRL+SHIFT+F
3 look for any string and press enter

Result : Indexing for instant search spinning is displayed, but results are displayed on second enter

**Comment by abose** [comment]
It is waiting for the indexing to be complete/ 100 search results to be avilable.
Even if you do not press the scond enter key, The result should appear once the results are available. 
Please check it out.

**Comment by abose** [comment]
@rawat11 Did you check this out?

**Comment by pl-ekleft** [comment]
Same problem.

**Comment by abose** [comment]
https://github.com/adobe/brackets/pull/11869 should fix this. Closing.
