### ISSUE TITLE
Brackets hangs or freezes on the very first launch

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11413]
Steps:

Install Bracket on a fresh machine and launch it

Result: in both Win and MAC, Brackets editor freezes for a while wherein
- health pop up doesn't come
- instant search is not done
- on double clicking any file-> doesn;t show up in the working set

We have to explicitly close bracket and relaunch it again after which it works fine

**Comment by abose** [comment]
@rawat11 is this issue still present?

**Comment by rawat11** [comment]
@abose Yes the issue is fixed now
