### ISSUE TITLE
[Find In files] : Exclusion set not working appropriately in Japanese Windows OS

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11423]
Steps:
1) Launch Brackets
2) start find in files and create a new exclusion set
3) search some word from the files that fall in the exclusion set

Result : Some of the results from the Exclusion set are also shown

**Comment by abose** [comment]
Is this japanese only?

**Comment by rawat11** [comment]
It is reproducible in french as well

**Comment by abose** [comment]
@rawat11 I could not reproduce this issue. Could you verify this is english builds and then in japanese builds?

**Comment by rawat11** [comment]
@abose I verfied it with latest build in English. Now it is reproducible in english as well

**Comment by rawat11** [comment]
Please find SS below:

![1](https://cloud.githubusercontent.com/assets/10069885/8843277/2c7d0aba-3124-11e5-932b-5d77938c4c3a.png)
![2](https://cloud.githubusercontent.com/assets/10069885/8843278/2caae232-3124-11e5-9aa2-7f7e6ef39fe9.png)


![3](https://cloud.githubusercontent.com/assets/10069885/8843282/375c69b2-3124-11e5-865e-2e9d5f2c512a.png)
![4](https://cloud.githubusercontent.com/assets/10069885/8843283/3760f2de-3124-11e5-8ffe-0b9a9bbb6c04.png)
![4](https://cloud.githubusercontent.com/assets/10069885/8843285/399bf94a-3124-11e5-9a4b-ad37ec0ddde8.png)
![3](https://cloud.githubusercontent.com/assets/10069885/8843286/399d8238-3124-11e5-9a04-f930c62866a9.png)

**Comment by abose** [comment]
@rawat11 The exclution set does not apply to the content of the file.
Exclution set means that any `file names with full path` containing the given exclution word, would be omitted from the search result. The contents of the file are never part of the exclution set.
Please close this bug if this is the case.

**Comment by rawat11** [comment]
Closing the issue if this is the case
