### ISSUE TITLE
Multi-line return issue

### ISSUE THREAD

**Issue by JoshHarrington** [adobe/brackets#11425]
Hope this hasn't already been mentioned! If it has please ignore.

...

When I cmd click to edit multiple lines and then press enter, the line returns get created but the cursors get placed at odd points. Usually the top cursor will be in the expected place (beneath the original line), however the other cursors will be a couple of lines up from where it had been.

OS - Mac OS 10.10.4
Brackets version - Release 1.3 build 1.3.0-16022

Thanks!
Josh

![before return](https://cloud.githubusercontent.com/assets/6818387/8782049/d20deeac-2f0a-11e5-9f6a-f403dedafc6c.png)
![after return](https://cloud.githubusercontent.com/assets/6818387/8782058/e1b8dfba-2f0a-11e5-958d-e0ebcd0aa703.png)

**Comment by purplemur** [comment]
I am also seeing this issue on Mac OSX 10.10.5, running on Windows 7 through Parallels.

The cursor is consistently being placed on the next line based on where it originally was, instead of accounting for any lines that get moved down above it. So if you have the cursors on lines 8, 12, and 27, the cursors will be placed on lines 9, 13, and 28 instead of lines 9, 14, and 30.

Makes the multi-select rather difficult to use if you have to use carriage returns.

**Comment by MarcelGerber** [comment]
Can you please try running Brackets with extensions disabled (Debug > Reload without extensions) to see if you can still repro?

**Comment by JoshHarrington** [comment]
Will do, on holiday atm.
Will remind myself to check this Monday.

**Comment by JoshHarrington** [comment]
@MarcelGerber I've just checked this and seems that it works fine when brackets is loaded without extensions.

Not sure if this will help find the problem or whether it's worth looking for now that's likely something to do with an extension, but here are all the extensions that I'm currently using:
- SASSHints https://github.com/konstantinkobs/brackets-SASShints
- Emmet http://emmet.io/
- Autosave on Blur https://github.com/martypenner/brackets-autosave-files-on-window-blur
- Beautify https://github.com/drewhamlett/brackets-beautify
- Exclude folders https://github.com/gruehle/exclude-folders

Mac version - 10.10.4
Brackets version - Release 1.4 build 1.4.0-16380 (release 273804eb3)

Cheers,
Josh

**Comment by purplemur** [comment]
Bug does not happen for me when Extensions are disabled.

I re-enabled Extensions and disabled Emmet (which I figured would be a good candidate for this issue), and sure enough, the Bug went away again. Re-enabled Emmet, and the bug came back.

Logging an issue with the Emmet extension author.

**Comment by JoshHarrington** [comment]
@purplemur cheers for the update, just closed as it's an issue with Emmet not brackets. Thanks
