### ISSUE TITLE
Add cmd inside application use support

### ISSUE THREAD

**Issue by LuanGB** [adobe/brackets#11424]

**Comment by mackenza** [comment]
can you provide more detail? I am not sure this can be addressed with a terse title and no description.

**Comment by LuanGB** [comment]
I mean, you could provide terminal access inside of the application... It was supposed to be really useful...

**Comment by LuanGB** [comment]
Specially for rails developers... it was compete directly with other ide's as rubymine...

**Comment by abose** [comment]
There is a brackets terminal extension that does this. Also there are several other extensions that adds  shell related functionality in brackets. As brackets is an editor for the web, terminal access might not be a good fit for the basic package. Closing a extension available.
