### ISSUE TITLE
Find In Files: Spinning indexing for instant search is not visible in french Win

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11421]
Steps:

1) Launch Brackets in french OS
2) Start find in files and search any word

Result : Spinning indexing for instant search is not visible in french Win

**Comment by abose** [comment]
Is intant saerch functioning as intended? Then it could be that the indexing complete faster than you did the search.

**Comment by abose** [comment]
@rawat11 Were you able to confirm this?

**Comment by rawat11** [comment]
@abose yes it's coming with the new build. Closing the issue
