### ISSUE TITLE
[UI Issue] : On adjusting the project panel, the UI of the selected file in the panel slightly disrupts

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11449]
Steps:
1) Launch Brackets 
2) Select a file in the project panel
3) Scroll/Adjust the project panel

Results:
the selection of selected file comes out of window

![defect](https://cloud.githubusercontent.com/assets/10069885/8843496/befe586a-3126-11e5-8524-2b993af5244f.png)

**Comment by ficristo** [comment]
@rawat11 Is this the same of https://github.com/adobe/brackets/issues/11341?

**Comment by ficristo** [comment]
I assume this is a dupe of #11341. I close this.
