### ISSUE TITLE
Brackets freezes on opening - Mac Yosemite

### ISSUE THREAD

**Issue by omarsafwany** [adobe/brackets#11446]
I have been using brackets editor for a while but suddenly after updating one of the extentions and reloading it, it froze.
Anytime i try to open the editor, it just freezes and nothing works. No menu, no search, no project toggle and I can't even even type. The cursor itself doesn't move at all.

Any idea how this can be fixed?!

**Comment by nathanayling** [comment]
Do you know which extension it is? If not, have you tried adding all of the extensions back in one by one until it starts to freeze.

**Comment by omarsafwany** [comment]
The problem is I can't find any folder containing the extensions. I even tried a fresh install but still opens with the previous extensions

**Comment by abose** [comment]
It lives in Library/Application Support/Brackets.
You could delete the folder.

**Comment by omarsafwany** [comment]
I know but it's not there

**Comment by abose** [comment]
hdd>Users>[user name]>Library/Application Support/Brackets.
It should be there. Brackets is only programmed to load from that folder.

**Comment by mackenza** [comment]
you could also use Finder to look for files named `main.js` which should find your extension folders too.

**Comment by omarsafwany** [comment]
nothing found

**Comment by omarsafwany** [comment]
@abose +1 for hdd>Users>[user name]>Library/Application Support/Brackets.
That helped although I tried opening it from Library but not that path.

Thank you

**Comment by abose** [comment]
:+1: Closing as fixed.
