### ISSUE TITLE
Adding History of Changes of HTML / CSS / SCSS / JS Files

### ISSUE THREAD

**Issue by manojbabu** [adobe/brackets#11457]
team, 
I would like to suggest a feature, that brackets needs to maintain a log history of changes based on every timestamps. where users can able to compare or revert back the code changes from the History backlog tool and update the same. something like code recovery from brackets time to time.

we can have panel like "validation problems" at footer of the console and they can view the changes respective to corresponding pages and they select and compare with working copy and modify those changes if required.

thanks
Manoj

**Comment by mackenza** [comment]
This is exactly what a version control system is for and Brackets has a very functional and well-maintained git extension. I would suggest that recreating git in Brackets is not advised and git should fill the requirements just fine.

**Comment by abose** [comment]
There is a very powerful `brackets git` extension for exactly the same purpose you suggested. Please check it out. There is a steep learning curve for getting used to Git though. Closing.

**Comment by manojbabu** [comment]
thanks fro reply, i was not aware of extension.
