### ISSUE TITLE
Bracket code suggestion and completion not working

### ISSUE THREAD

**Issue by BonsonJohnson** [adobe/brackets#11458]
Hi - Just loaded Brackets and code suggestion and completion aren't working. Nor is the colour coding of the syntax. Help please

**Comment by BonsonJohnson** [comment]
![screen shot 2015-07-23 at 13 42 18](https://cloud.githubusercontent.com/assets/13468019/8850566/0471c2b4-3141-11e5-92b0-b22b1603feb4.png)

here's what I'm seeing in glorious grey

**Comment by TomMalbran** [comment]
Are you editing a newly created document inside off Brackets? Try to save it with with an html extension to get syntax highlight and code hints and more.

**Comment by BonsonJohnson** [comment]
Hi and thanks - that worked. Doh!

Anne

**Comment by rroshan1** [comment]
Closing the issue as it has been resolved.

**Comment by mishahul** [comment]
why  am getting a png file with html user guide instead of a text file?
