### ISSUE TITLE
[InstantSearch] Find in Files results  panel displays in-memory file even after saving

### ISSUE THREAD

**Issue by le717** [adobe/brackets#11464]
- Open [this sample project](https://dl.dropboxusercontent.com/u/58490278/Downloads/Brackets-Bug.zip) and do a Find in Files search for "Brackets"
- Leaving the results pane open, create a new file and type "Brackets"
- Save the file

**Result**: The saved file and temporary, in-memory version are both listed in the results pane.

![image](https://cloud.githubusercontent.com/assets/3382464/8865333/ce001aba-317b-11e5-92db-1f625f3d0391.png)

Brackets 1.4 @ `master` 57826746a, Windows 7 SP1 x64

**Comment by abose** [comment]
similar to #11450

**Comment by abose** [comment]
Searching for Brackets again(press enter key in the search bar) would update the count as a temporary workaround.
