### ISSUE TITLE
Brackets freezing on startup

### ISSUE THREAD

**Issue by Vaetas** [adobe/brackets#11463]
Hello,
yesterday I was forced to downgrade Brackets to version 1.1 because ver 1.3 freezes on startup (and ver 1.2 is very slow). It kind of works after clean install (though slow to use), but after a while it's about he same. I'm running Win 7 Ultimate 64bit and it used to work pretty well until some update. The navbar (File, Edit, etc) responds, however the rest of Brackets doesn't.

Thanks.

**Comment by rroshan1** [comment]
@Vaetas Can you try uninstalling Brackets and deleting the Brackets folder inside "%appdata%".
See if it helps you go through the startup with a fresh installation.
By the way, you can try Brackets v1.4 releasing in the coming week.

**Comment by Vaetas** [comment]
I tried reinstalling Brackets with deleting appdata, but after a while it started freezing again. I will wait for v1.4., thanks.

**Comment by ficristo** [comment]
We are at 1.8 now, if you still have problems please open a new issue.
