### ISSUE TITLE
Correct Identation

### ISSUE THREAD

**Issue by reoxb** [adobe/brackets#11475]
I wish can used this option into a document html, or css. I supossed you have done, but I cant find it.

**Comment by rroshan1** [comment]
@reoxb We do have auto indentation on by default even for html and css files.
You can explicitly enable or disable auto indentation by going to ``Debug > Open Preferences File`` and adding the line `"smartIndent": true,` or `"smartIndent": false,` respectively in the brackets.json preference file that opens in the right panel. 
I hope it answers your concern and closing the issue for now.
In case your query remains unanswered, feel free to reopen the issue and comment.

**Comment by TomMalbran** [comment]
I feel like you are looking for something like https://github.com/Hirse/brackets-beautify?
