### ISSUE TITLE
Resizer module uses depreated function

### ISSUE THREAD

**Issue by le717** [adobe/brackets#11488]
(Split from https://github.com/adobe/brackets/pull/11174#issuecomment-119032811)

`src/utils/Resizer.js` uses `PreferencesManager.convertPreferences`. which is deprecated, so the error is being thrown in core.  I have no clue how that preference should be updated to the current system (prefixed? Global preferences file), and I am unsure if deprecation errors should be thrown in core (I think historically that is a "no").

**Comment by ficristo** [comment]
/cc @peterflynn @abose
Do you know how to fix this?

**Comment by abose** [comment]
also see related use in `src/project/ProjectManager.js`.

**Comment by sprintr** [comment]
I removed all the code using deprecated code and Brackets kept on working. I seem to have lost that branch.

**Comment by abose** [comment]
Was there a lot of places using deprecated API in core?

**Comment by sprintr** [comment]
15-20 places maybe. I'll submit a PR tonight.

**Comment by abose** [comment]
:+1: Thanks @sprintr

**Comment by sprintr** [comment]
@swmitra This is fixed and should be closed.
