### ISSUE TITLE
PreferencesManager save prefs to project root

### ISSUE THREAD

**Issue by abagshaw** [adobe/brackets#11480]
Is there a way to use the PreferencesManager API to set preferences to a `.brackets.json` file in the current project root folder, or does that need to be done by manually writing the file?

If I am correct `PreferencesManager.getExtensionPrefs("my-plugin").get("my-pref")` will automatically look in the project root for the prefs before looking in the normal brackets wide location.

How can I specify where I save my prefs though?

**Comment by sprintr** [comment]
Here is an [example](https://github.com/adobe/brackets/wiki/Preferences-System#setting-prefs) of doing it.

**Comment by abose** [comment]
@abagshaw Please close this issue if that answered your question.

**Comment by abagshaw** [comment]
Yes this has answered my question. Thank you!
