### ISSUE TITLE
[InstantSearch] Find in Files results panel displays wrong file count after change is made

### ISSUE THREAD

**Issue by le717** [adobe/brackets#11490]
- Open this [sample project](https://dl.dropboxusercontent.com/u/58490278/Downloads/Brackets-Bug.zip) and do a Find in Files search for "Brackets"
- Leaving the results pane open, open `file-2.txt` and remove the text, no need to save
- "In x files" text does not update with new results

![bug](https://cloud.githubusercontent.com/assets/3382464/8898762/ac4fd746-33f8-11e5-9bc1-2bbae95f0bd7.png)

**Comment by abose** [comment]
Searching for Brackets again(press enter key in the search bar) would update the count as a temporary woraround.
@rroshan1 Update count issue.

**Comment by abose** [comment]
Similar to #11464
