### ISSUE TITLE
[Find in files] Search causes system-wide freezes

### ISSUE THREAD

**Issue by dnbard** [adobe/brackets#11496]
I'm experiencing the system-wide freezes when I press the key in Find in Files panel. Basicaly, everything are stop working: music, background tasks ... 

Brackets v1.4
Windows 7

**Comment by abose** [comment]
What is the system memory? also could you give more details on the size of the brackets project? the cpu configuration? 
Instant search is a bit cpu intensive. 
You can disable the feature by setting the preference "findInFiles.nodeSearch": to false.

**Comment by dnbard** [comment]
CPU: Intel I7-4790
Memory: 16GB

Size of project:
* ~200 javascript files 
* ~20 htmls 
* ~20 css 
* a lot of dependencies(bower + npm) but all of them are included in .gitignore and ignored for the search (at least they was in Brackets v1.3)

**Comment by abose** [comment]
In that configuration, it should be super smooth.
Can you see any error in the developer console?
Which key press in find in files panel leads to this behavior?

**Comment by dnbard** [comment]
`Which key press in find in files panel leads to this behavior?`
Any key.

I cannot reproduce this issue next day (no reboot were made).
If I stumble upon this issue again then I'll update the issue with details.

**Comment by abose** [comment]
Closing inactive thread. Please feel free to reopen if you still face the issue.
