### ISSUE TITLE
Brackets Release updates

### ISSUE THREAD

**Issue by manojbabu** [adobe/brackets#11509]
team

Whenever brackets updates / new releases are there, its coming like exe and manually we need to download and install each and every time,instead of that why can we you apply update automatically whenever there was new release like Firefox or chrome. Once we install we should upgrade the version updates so please fix this concerns

**Comment by nethip** [comment]
@manojbabu We already have a trello card for this. https://trello.com/c/dCplDYlN/578-auto-update-mechanism-shell Please up vote this trello card. I am closing this issue for now.
