### ISSUE TITLE
Disable element highlighting in live preview

### ISSUE THREAD

**Issue by gajus** [adobe/brackets#11502]
* "When you move the cursor around an HTML file, the corresponding element is highlighted in the browser"
* "When you move the cursor around a CSS/LESS/SCSS file, all elements matching the current rule are highlighted in the browser"

from: https://github.com/adobe/brackets/wiki/How-to-Use-Brackets

How to disable these features?

**Comment by MarcelGerber** [comment]
There's a toggle `View > Live Preview Highlight` that you can use to disable and re-enable this feature.

**Comment by gajus** [comment]
Sorry, missed it.
