### ISSUE TITLE
PHP Class search

### ISSUE THREAD

**Issue by AlanTr77** [adobe/brackets#11512]
Search the classes and its function included in a php document

**Comment by TomMalbran** [comment]
For functions (including methods inside classes), you can use this extension: https://github.com/aonic/brackets-QuickOpenPHP (which you need to install manually since it is not in the extensions registry) and then you can use Ctrl+T (Navigate -> Quick Find Definition)

**Comment by AlanTr77** [comment]
Thank you for your answer

--------
Alan Trebeschi
Tel: 3480130648
Mail: alan.trebeschi@gmail.com
Web: http://trebeschi.altervista.org

**Comment by abose** [comment]
Closing as answered.
