### ISSUE TITLE
Brackets crashes when reloading without extensions

### ISSUE THREAD

**Issue by saviorfromthenorth** [adobe/brackets#11511]
How to reproduce:
1. Add a project or open a folder on the sidebar.
2. Open a file not located in the project folder.
3. Reload without extensions.

Issue:
Brackets will crashes when you try to reload without extensions and there is an open file that is not from the project directory.

Version:
Release 1.4 build 1.4.0-16380 (release 273804eb3) 

-I do not know if it worked previously.

OS:
Windows 8

Extensions:
None

**Comment by nethip** [comment]
@saviorfromthenorth Would you be able to pull this [PR](https://github.com/adobe/brackets/pull/11505#event-368520930) and check if it solves the issue? Note that you will have to run Brackets from source.

**Comment by ficristo** [comment]
Closing as the PR has merged.
Reopen if you still have the problem.
