### ISSUE TITLE
Feature Request - Inspect Element within Brackets

### ISSUE THREAD

**Issue by purplemur** [adobe/brackets#11515]
I love that you can open the Dev Tools within Brackets to see how it is styling everything, but it is a real PITA to have to drill down through the code to find the specific element you are trying to target.

It would be great to have "Inspect Element" added to the context menu when you right-click on things in the editor so you can reveal it instantly in the Dev Tools dialog.

**Comment by abose** [comment]
Souldn't this button help you with that?
![image](https://cloud.githubusercontent.com/assets/5336369/8990361/4eb8ac06-370f-11e5-9b7e-7d4643cd1de0.png)

**Comment by purplemur** [comment]
You would think so, but when you try and click on a specific element in the code window, it selects the entire code block instead of drilling down to the element.

It does select elements outside of the code block pretty well (i.e. filenames in the sidebar, toolbar icons). It's just when trying to select an element in the code editor window that it doesn't get specific enough.

**Comment by TomMalbran** [comment]
@purplemur This extension will help with that: https://github.com/MiguelCastillo/Brackets-InspectEditor

**Comment by abose** [comment]
@purplemur If the extension addresses the problem, please close this issue.

**Comment by purplemur** [comment]
That worked! Thank you so much! :+1:
