### ISSUE TITLE
JS elements given incorrect css classnames

### ISSUE THREAD

**Issue by purplemur** [adobe/brackets#11514]
<img width="393" alt="screen shot 2015-07-30 at 10 19 16 am" src="https://cloud.githubusercontent.com/assets/1580157/8987194/683cfffc-36a5-11e5-8c02-c9d314ac9e31.png">

In a function's aruguments, variable elements (line1:"whichOverlay") are given the class cm-def.
In the function body, internally declared variables (line2:"thisOverlay") are given the class cm-def, while argument calls (line2:"whichOverlay") are given the class cm-variable-2.

I think the classes should be switched for the internally declared variables and argument calls.

**Comment by ficristo** [comment]
The classes are coming from [CodeMirror](https://github.com/codemirror/CodeMirror) and we aren't gonna to change them.
