### ISSUE TITLE
Brackets incorrectly identify a file as being non-encoded in utf-8 and refuse to open it

### ISSUE THREAD

**Issue by aroberge** [adobe/brackets#11525]
I have a very simple json file whose entire content is

```
{ }
```

Bracket refuses to open it, claiming it is not a utf-8 encoded file.  Notepad++ identifies it as being a utf-8 encoded file (with no BOM).

**Comment by abose** [comment]
could you upload the file here.

**Comment by aroberge** [comment]
@abose Apparently I can not upload the file; however here is a link to it on github:
https://github.com/aroberge/reeborg/blob/master/src/worlds/empty_world.json

**Comment by petetnt** [comment]
Did some testing, any file that:

* Starts with any unicode char from 0061 to 007C (a-z and |)
* Then has a space
* Ends with } (007D, the char after |)

fails to be recognized as UTF-8. Adding any other characters (including new lines etc.) fixes the problem.

**Comment by MarcelGerber** [comment]
@petetnt Thanks for looking into this very weird issue.
It looks like this is Win only as it works just fine in my Linux VM.

**Comment by MarcelGerber** [comment]
It's the [`IsTextUnicode` call](https://github.com/adobe/brackets-shell/blob/959c7da3394de5b748f8b575339bd5d0123617d5/appshell/appshell_extensions_win.cpp#L760) that returns `true` when it shouldn't.
Specifically, it's the `IS_TEXT_UNICODE_STATISTICS` flag (included in the `IS_TEXT_UNICODE_UNICODE_MASK` flag) that causes this issue.

According to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318672(v=vs.85).aspx):
> The IS_TEXT_UNICODE_STATISTICS and IS_TEXT_UNICODE_REVERSE_STATISTICS tests use statistical analysis. These tests are not foolproof. The statistical tests assume certain amounts of variation between low and high bytes in a string, and some ASCII strings can slip through. For example, if lpv indicates the ASCII string 0x41, 0x0A, 0x0D, 0x1D (A\n\r^Z), the string passes the IS_TEXT_UNICODE_STATISTICS test, although failure would be preferable.

I guess we're seeing some sort of this bug.
Maybe @JeffryBooher @nethip?

**Comment by MarcelGerber** [comment]
Btw: Would Brackets save it's files with a BOM, this would not be an issue at all...

**Comment by nethip** [comment]
@MarcelGerber Let me do some reading on this. I will get back to you. Thanks!

**Comment by petetnt** [comment]
@MarcelGerber RE: Saving files with BOM,

When I was looking into this I noticed that UTF-8 & BOM has been under discussion for a long time in #3898 (and others such as #10583) plus there is this card on Trello too: https://trello.com/c/I5sgI4SV/1164-editor-and-bom-byte-order-mark

**Comment by nethip** [comment]
@MarcelGerber You were right about the `IsTextUnicode` Win32 call that could be the possible reason for the failure. The thing is, detecting the encoding of a file, without BOM, is a very difficult task and is not fool proof. I checked file encoding detection code in Dreamweaver and it seems very complex. 

@petetnt Thanks for trying out various steps in nailing down the problem. Saving with BOM seems to be a good idea. Unfortunately, that is not a recommended way.

By the way, we have already started to think about what are the best ways to support various encodings.  I will keep you updated on that. Thanks!

**Comment by MarcelGerber** [comment]
@nethip Notepad++ has a good encoding detection, which is not ultra-long at least (it's not by any means comprehensble, but I guess that's simply the nature of encodings):
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/85c728573e0c81ff9df7a1adf4b1934fb01661e7/PowerEditor/src/Utf8_16.cpp#L182-L232 (plus a ASCII/UTF8 distinction [a few lines above](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/85c728573e0c81ff9df7a1adf4b1934fb01661e7/PowerEditor/src/Utf8_16.cpp#L52-L109)).

As it's all licensed under the GPL, we could completely reuse their implementation.

**Comment by petetnt** [comment]
Can't comment on Notepad++'s method from a technical perspective, but in practice N++ has worked as an general "solve this encoding problem" workhorse for me for years. :+1:

**Comment by nethip** [comment]
@MarcelGerber Thanks for the pointer. It looks like a good place to start this activity. Hopefully, we will be able to map Win32 calls in the repo to their Mac and Linux equivalents.

**Comment by MarcelGerber** [comment]
Yes, they have a solid detection rate.

A working encoding detection is also the foundation for multi-encoding support, so it doesn't interfere with those efforts at all.
