### ISSUE TITLE
An Extra Guide line on every document !! 

### ISSUE THREAD

**Issue by amibappy** [adobe/brackets#11521]
i don't know how it happened !! those guide lines is annoying me a lot. it automatically comes on every document i open. 
Someone please give me a SOLUTION......... :(  

* screenshot of that problem:

![capture](https://cloud.githubusercontent.com/assets/13586412/9005310/f1db89e6-379e-11e5-9e66-3f06dbbbf2a6.PNG)

**Comment by abose** [comment]
I think it is an extension drawing the guide line.
Could you go to help menu> health report and copy the extension list here?

**Comment by amibappy** [comment]
{
    "uuid": "7b0a34d6-6bd7-495d-9ae3-d8b740b056ec",
    "snapshotTime": 1438338609513,
    "os": "win",
    "userAgent": "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.4.0.0 Chrome/39.0.2171.36 Safari/537.36",
    "osLanguage": "en-GB",
    "bracketsLanguage": "en-GB",
    "bracketsVersion": "1.4.0-16380",
    "e4b": {
        "userAutoSignedIn": true,
        "isCCSubscribedUser": false
    },
    "ProjectDetails": {
        "prj3556498": {
            "numFiles": 52,
            "cacheSize": 721777
        },
        "prj2126339": {
            "numFiles": 41,
            "cacheSize": 1080291
        }
    },
    "fileStats": {
        "openedFileExt": {
            "scss": 45,
            "css": 11,
            "rb": 4,
            "html": 13,
            "json": 8,
            "js": 9
        },
        "workingSetFileExt": {
            "rb": 3,
            "css": 3,
            "scss": 2,
            "html": 5,
            "json": 2,
            "js": 1
        }
    },
    "projectLoadTimes": ":574",
    "fileOpenTimes": ":197(813)2013[849]:198(228)289[36]:185(389)686[215]:466(467)468[1]:20(62)103[42]:205(238)271[33]:276:80:338",
    "ModuleDepsResolved": 686,
    "AppStartupTime": 3443,
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": [
        {
            "name": "bracket-match-highlighter",
            "version": "0.1.2"
        },
        {
            "name": "deddy.additional-right-click-menu",
            "version": "0.5.1"
        },
        {
            "name": "jdiehl.less-autocompile",
            "version": "1.1.9"
        },
        {
            "name": "lesshints",
            "version": "1.1.0"
        },
        {
            "name": "sasshints",
            "version": "1.1.0"
        },
        {
            "name": "y0nnyy.specialchars",
            "version": "1.3.0"
        },
        {
            "name": "brackets.google-search",
            "version": "1.1.2"
        },
        {
            "name": "mignonstyle.brackets-wp-hooks-hints",
            "version": "1.0.1"
        },
        {
            "name": "brackets-preferences-viewer",
            "version": "1.0.5"
        },
        {
            "name": "brackets-wp-functions-hint",
            "version": "2.0.4"
        },
        {
            "name": "mignonstyle.brackets-wp-functions-hints",
            "version": "1.0.1"
        },
        {
            "name": "camden.caniuse",
            "version": "2.1.1"
        },
        {
            "name": "brackets-ruler",
            "version": "2.3.11"
        },
        {
            "name": "yellowhangar.guidelines",
            "version": "1.0.1"
        },
        {
            "name": "woocommerce-hints-for-brackets",
            "version": "1.0.0"
        },
        {
            "name": "insya.units",
            "version": "0.0.6"
        },
        {
            "name": "pflynn.inline-gradient-editor",
            "version": "1.0.0"
        },
        {
            "name": "edc.brackets-snippets",
            "version": "1.8.1"
        },
        {
            "name": "brackets-lorem-ipsum",
            "version": "1.0.3"
        },
        {
            "name": "dnbard.projects",
            "version": "0.1.7"
        },
        {
            "name": "jsbeautifier",
            "version": "0.0.3"
        },
        {
            "name": "insya.tools",
            "version": "0.2.0"
        },
        {
            "name": "mackenza.php-smarthints",
            "version": "1.2.2"
        },
        {
            "name": "open.recent.file",
            "version": "0.5.7"
        },
        {
            "name": "georapbox.brackets-notes",
            "version": "1.0.9"
        },
        {
            "name": "camden.w3cvalidation",
            "version": "2.2.2"
        },
        {
            "name": "brackets-special-html-chars",
            "version": "1.2.2"
        },
        {
            "name": "brackets-emmet",
            "version": "1.2.2"
        },
        {
            "name": "mikaeljorhult.brackets-autoprefixer",
            "version": "0.6.0"
        },
        {
            "name": "adobe.brackets.extract",
            "version": "0.8.0-1747-release"
        },
        {
            "name": "mrdollywaggit.encode",
            "version": "1.0.0"
        }
    ],
    "bracketsTheme": "light-theme"
}

**Comment by amibappy** [comment]
Help me PLEASE :(

**Comment by abose** [comment]
It should be one of the extensions
"name": "brackets-ruler",
"name": "yellowhangar.guidelines",
goto extension manager and remove/disable them.

**Comment by amibappy** [comment]
OMG !! it worked :) :) 
THANK YOU .......@abose. You are a life Saver :)

**Comment by abose** [comment]
:cool: closing as fixed
