### ISSUE TITLE
Brackets-Reload with extensions crashing with developer tools open

### ISSUE THREAD

**Issue by ravindrababukota** [adobe/brackets#11539]
Brackets is crashing when to reload brackets, after opening show developer tools for debugging purposes. I am using Version 44.0.2403.125 m of chrome.

**Comment by ravindrababukota** [comment]
Steps
1. Launch Brackets 
2. Launch Developer Tools from Debug->Show developer tools
3. Select Reload with Extensions

The tool crashes.  Brackets version is Release 1.4 build 1.4.0-16380

Chrome Version: Version 44.0.2403.125

**Comment by ravindrababukota** [comment]
This is happening under Windows7 Enterprise.

**Comment by nethip** [comment]
@ravindrababukota This might have got fixed with this PR https://github.com/adobe/brackets/pull/11505, which is not merged to master yet. Will you be able to pull this PR, in which case you need to run Brackets from source, and see if it helps

**Comment by ravindrababukota** [comment]
@nethip With the merge PR #11505, we are not having the issue.
