### ISSUE TITLE
New-brackets window

### ISSUE THREAD

**Issue by mmkaw** [adobe/brackets#11531]
After installing brackets 1.4, when i open a new brackets window CTRL stops working. here's the step.
bracket window1 > open new brackets window >bracket window2 > any-file >
control stops working like type something and try to hit ctrl+z, it doesn't "undo". you can by using the menu btw. need to refresh the new window(refresh with/without extension) to make it work.

**Comment by petetnt** [comment]
Couldn't replicate on Windows 10 with Brackets 1.4. Does the developers console (F12) show any errors? Have you tried this without any extensions?

**Comment by mmkaw** [comment]
Its working now. had this issue earlier, may be my system problem. closing issue.
