### ISSUE TITLE
Reloading brackets causes a crash and requires a force quit

### ISSUE THREAD

**Issue by DCRichards** [adobe/brackets#11545]
### Description

Reloading Brackets (with or without extensions) causes Brackets to crash and not reload the project view. Users are then unable to refresh after this and must force quit.

### Steps

1. Open a project in brackets
2. Go to Debug > Reload with (or without) extensions
3. Reload begins but view does not reload and stays blank, the user is then unable to reload and Brackets must be quit and restarted.

### Version

* Brackets 1.4
* OSX 10.10.4 (Yosemite)

**Comment by petetnt** [comment]
#11505 should fix this

**Comment by VitorLuizC** [comment]
Same issue here.

* Brackets 1.4
* Windows 10 Pro 32bits

**Comment by nethip** [comment]
This is fixed now in master. Please run Brackets from source, until this is available in 1.5. 

Feel free to open the issue, if you are still seeing it.

**Comment by DCRichards** [comment]
@nethip @petetnt thanks guys, will keep an eye out
