### ISSUE TITLE
Extract for Brackets crash on Windows 7

### ISSUE THREAD

**Issue by makzav** [adobe/brackets#11541]
Brackets 1.4 crashes when I press on "Open a PSD..." button or Help -> Sign In to Creative Cloud.

DMP files:
http://1drv.ms/1N73mYT
http://1drv.ms/1N73pUE

**Comment by kyrenator** [comment]
I face the same issue!

**Comment by nethip** [comment]
@makzav @kyrenator Sorry that you guys are facing this issue. Are you able to use extract with 1.3? And also, do you have creative cloud app installed on your system?

@makzav Thanks for the crash logs.

**Comment by kyrenator** [comment]
@nethip I haven't try to export using 1.3. Is creative cloud app necessary in order to use the export feature?

**Comment by ficristo** [comment]
Extract is deprecated: http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/
Closing
