### ISSUE TITLE
How to install custom font in Bracket 

### ISSUE THREAD

**Issue by shohan4556** [adobe/brackets#11556]
I want to use custom font in Bracket and I want to make custom font extension, where can I found enough resource ?

**Comment by sprintr** [comment]
> I want to use custom font in Bracket

You can change font via View -> Themes

> I want to make custom font extension, where can I found enough resource ?

You can load custom css file via `ExtensionUtils.loadStyleSheet` to change the font. Have a look at the [docs](http://brackets.io/docs/current/modules/brackets.html) and this [wiki](https://github.com/adobe/brackets/wiki/How-to-write-extensions) page.

**Comment by shohan4556** [comment]
thanks :+1:

**Comment by fuadmaster** [comment]
Can someone tell me how can I get more fonts on brackets?
