### ISSUE TITLE
Live Preview not working - no selected (blue) borders

### ISSUE THREAD

**Issue by the1nikola** [adobe/brackets#11550]
I don't know what caused it, possibly installing Windows 10, as brackets still worked for me on friend's computer on Win 7; including with the same page I'm coding - only html and css.

What doesn't work?

Live Preview starts up and is live, though it doesn't mark what I've selected in the code with those blue borders. Also, Live Preview crashes much more often ("Live Preview was cancelled because the page was closed in the browser"), though I can (sometimes) get it to work.

What didn't help?

Anything in the FAQ
Reinstalling brackets and chrome
Brackets v1.3
Chrome disconnected account

![image](https://cloud.githubusercontent.com/assets/13682458/9119004/adccc46a-3c74-11e5-952e-75bbfe451271.png)

Cheers :)

**Comment by MarcelGerber** [comment]
Just to sort the simple things out, could you just check that "View > Live Preview Highlight" is still checked?

**Comment by the1nikola** [comment]
Thank you :D
What solved the problem was toggling it on and off (but a reinstall didn't...)

**Comment by LanQ** [comment]
I also got this problem on Windows 10. and toggling it off and on not work for me.

sad...
