### ISSUE TITLE
How to count, number of times downloaded an extension or theme from Bracket registry ?

### ISSUE THREAD

**Issue by shohan4556** [adobe/brackets#11555]
How to count, number of times downloaded an extension or theme from Bracket registry ?

**Comment by abose** [comment]
@shohan4556 You could get the active usage data of extensions in the wiki page https://github.com/adobe/brackets/wiki/Health-Report-Data
This is updated monthly. If this suffices your use case, please close the issue.

**Comment by shohan4556** [comment]
:+1:

**Comment by MarcelGerber** [comment]
Notice that the numbers referenced above is the unique user count, which is often times more important than the download count.
To get (daily) download counts, head over to http://brackets.dnbard.com/

**Comment by shohan4556** [comment]
thanks
