### ISSUE TITLE
Dialog telling you to reload Brackets in order to update extensions is no longer shown

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#11552]
1. Open the Extension Manager
2. Update one of your extensions (if you don't have any extension to update, edit the package.json of one so it'll show an update. For example, change `brackets-git`'s local version to `0.14.27`)
3. Close the "Installation finished" dialog
4. Close the Extension Manager

Result: No dialog shown
Expected: A dialog telling you to restart Brackets in order to actually update the extensions should be shown

Bisecting brackets-shell pointed me to adobe/brackets-shell@fd6738ad20505488bdbf7c772e7acd784bee8878 as the culprit.
cc @zaggino @abose @nethip 

~~May be Windows only.~~ Confirmed on Windows (10) and OS X (El Capitan)

Windows 10, brackets-shell@release-1.4 (both custom built and downloaded one)

**Comment by MarcelGerber** [comment]
That's how it used to look (Release 1.3 shell):
![image](https://cloud.githubusercontent.com/assets/2641501/9121588/7e3107ac-3c83-11e5-9de2-0ebb8d230cef.png)

That's how it looks now (Release 1.4 shell):
![image](https://cloud.githubusercontent.com/assets/2641501/9121583/70d2c9ba-3c83-11e5-8d98-c9ccf753f9a6.png)

Look for the different values of `installationStatus`. It looks like `ExtensionManager.updateFromDownload` is now called later in time.

**Comment by zaggino** [comment]
@MarcelGerber can you check the PR?

**Comment by abose** [comment]
#11553 fixes the issue.
