### ISSUE TITLE
Reloading may crash

### ISSUE THREAD

**Issue by thany** [adobe/brackets#11562]
I've had several instances where reloading Brackets will crash it with a "Brackets stopped working" message from Windows. Just hitting F5 inside of Brackets occasionally makes it crash like that.

After the crash, the Brackets chrome remains behind, unclosable. Only option is to kill it (again!) manually by pulling up the task manager, finding brackets, killing it, and finally restarting it.

Brackets 1.4, Windows 7 x64. Extensions or not makes no difference.

**Comment by petetnt** [comment]
This has been fixed in #11505 (you can try the master branch if you want to test it out)

**Comment by abose** [comment]
Closing as fixed.
