### ISSUE TITLE
JS Code Hints won't work when there's ".." in a HTML file

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#11568]
1. Take the HTML below and paste it into a HTML file
2. In line 4, write out `test.`
3. Remove the two trailing dots and save
4. Restart Brackets
5. Repeat step 2

``` html
..
<script>
    var test = 1;
    
</script>

```

Result:
In step 2, you don't get JS Code Hints, whereas in step 5, you get Code Hints

**Comment by MarcelGerber** [comment]
For this to work, we need a Tern update (this issue was fixed with Tern commit https://github.com/marijnh/tern/commit/2863d70864e679086e72e487ee66a8b60318984c#diff-540f19149eab02b91106eb3e07eaeceeR1220).

I'll look into updating Acorn & Tern.

**Comment by K-Thompson** [comment]
@MarcelGerber  you may want to monitor this issue #11570.
