### ISSUE TITLE
Issue with plugin enabled status discrepancy

### ISSUE THREAD

**Issue by K-Thompson** [adobe/brackets#11571]
Brackets 1.4 running on Windows 7.

These two screen shots shows that the bracket.json file (as accessed via the new open preferences feature) show one the TODO plugin disabled. However, the extension manager shows it as enabled.

![brackets-jason-not-enabled-extension](https://cloud.githubusercontent.com/assets/6936008/9158478/78fa1418-3ee5-11e5-9cf6-e4f412bf538e.png)

![brackets-extension-manager](https://cloud.githubusercontent.com/assets/6936008/9158481/802440e2-3ee5-11e5-9b7d-ba92e80ef486.png)

**Comment by abose** [comment]
The extension disable feature of brackets is a master switch which will disable the extension from being loaded. 
The preference, on the other hand, is provided by the extension itself and not a brackets feature. Please log an issue with the extension author referencing this issue. The extension might have to call brackets api's to disable itself. [But enabling it after it gets disabled from a preference change is still not implemented.]
