### ISSUE TITLE
PSD can't be loaded if the file name of PSD has Chinese characters

### ISSUE THREAD

**Issue by Samciu** [adobe/brackets#11575]

**Comment by nethip** [comment]
@Samciu There are known issues with double byte characters, in the extract context. We have fixed this in the backend. However, there are some changes we need to take up on the client side. We are on it.

**Comment by abose** [comment]
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
