### ISSUE TITLE
high priority Fix Instalations package Brackets.Release.1.4.64-bit.deb Alta Prioridad Instalacion de paquete Brackets.Release.1.4.64-bit.deb 

### ISSUE THREAD

**Issue by macdg** [adobe/brackets#11591]
The problem is in the package not install result error: "Error in dependency libgcrypt11>=1.4.5" also as well in the package Brackets.1.4.Extract.64-bit.deb show the same error: "Error in dependency libgcrypt11>=1.4.5".
El problema es en el paquete de instalación no instala y muestra el error: "Error. No se puede satisfacer la dependencia: libgcrypt11>=1.4.5" así como también en el paquete Brackets.1.4.Extract.64-bit.deb muestra el mismo error: "Error. No se puede satisfacer la dependencia: libgcrypt11>=1.4.5"

**Comment by ganchito55** [comment]
There is a problem with libgcrypt11 in Ubuntu, I think that you know Spanish so this web can help you http://ubunlog.com/libgcrypt11-hace-que-spotify-y-brackets-no-funcionen-en-ubuntu-15-04/

You need to download the .deb package and then run sudo dpkg -i package_name

**Comment by MarcelGerber** [comment]
Please head over to https://github.com/adobe/brackets/issues/10255 for this discussion. Looks like http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/libg/libgcrypt11/ is the place to download the libgcrypt11 package.

Closing.

**Comment by macdg** [comment]
Thank you. closed
