### ISSUE TITLE
Dual monitor support / Tear out to of an open file to a 2nd instance of Brackets.

### ISSUE THREAD

**Issue by wyattbiker** [adobe/brackets#11598]
I assume it would be similar to a Chrome browser tab being dragged out to its own Chrome window. In a sense it would be a 2nd instance of Brackets.

**Comment by nethip** [comment]
@wyattbiker We have enabled creating a new Brackets windows from a running Brackets instance (Debug > New Brackets Window). This is experimental. We have captured this requirement in our trello card (where we maintain our backlog). https://trello.com/c/YM0YySxX/679-multiple-separate-windows-official-new-window-command. Please up-vote this card. I am closing this issue but feel free to open it back if you feel not everything that you require, is not captured on that card.

**Comment by wyattbiker** [comment]
haha that's what i was looking for. i up-voted it.thanks!
