### ISSUE TITLE
Blank page after refresh (Windows 10)

### ISSUE THREAD

**Issue by hppypnda** [adobe/brackets#11596]
Whenever I refresh Brackets by pressing F5, I get a blank page as you can see on the screenshot below, and I am unable to quit Brackets by pressing Alt+F4 or the "X" button, I have to open the task manager and force close Brackets, which does not appear "not responding".
![image](https://cloud.githubusercontent.com/assets/8338157/9293574/a2d2da40-4430-11e5-960a-d917fa117b34.png)

Here is what I get in the console before I refresh (i cannot open the console after) :
![image](https://cloud.githubusercontent.com/assets/8338157/9293568/8064c306-4430-11e5-8ee7-67cb0cc5789e.png)

This issue appears on 3 computers running Windows 10 Professional 64 bits at my home, 1 on which Brackets was updated, 2 with fresh install.

Windows 10 Professional 64 bits
Brackets Release 1.4 build 1.4.0-16380 (release 273804eb3)

**Comment by petetnt** [comment]
This has been fixed by #11505 and will ship with 1.5. Meanwhile, you can fork the master branch and try that out.

**Comment by hppypnda** [comment]
Thank you petetnt for your answer, will do that until 1.5 ! :)

**Comment by petetnt** [comment]
:+1:
