### ISSUE TITLE
Replace: There is no way to add number to a regexp search result

### ISSUE THREAD

**Issue by minhtran28982** [adobe/brackets#11604]
For example, I have some strings on document such as ab = 100, ab = 125, ab = 32, etc... And I would like to add 0 to the end of these string to be ab = 1000, ab = 1250, ab = 320, etc...

My Regexp string on the search field is : ab = (\d*)
My replace string on Replace field is : ab = $10

Result will be : ab =
because it thinks I want to get the Regexp result $10 instead of $1 and add number 0

**Comment by petetnt** [comment]
Took me a while to figure out non-hackish way, but you use Complete Match Contents-substitution `$&` to perform this

> Complete Match Contents $&
> This will return a string with the complete match result from the regex.

Regexp string: `ab = (\d*)`
Replace string: $&0;

Results 

```
ab = 100 --> ab = 1000
ab = 125 --> ab = 1250
```

and so on.

You can test it online [here](https://regex101.com/r/wS6eY8/7)

**Comment by minhtran28982** [comment]
fantastic!!! It works like a charm... thanks :)

**Comment by abose** [comment]
Closing as regexp construction issue.
