### ISSUE TITLE
Problem with Farsi character selection

### ISSUE THREAD

**Issue by Netman82** [adobe/brackets#11612]
Hi,
I need to choose part of the text which is Farsi/Persian but it seems Brackets is no compatible with RTL languages, because i can't select it.
here is the sample text:

```
                <div class="col-md-4">
                    <p>
                     لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیستری را برای طراحان رایانه ای و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
                     </p>
                </div>
```

if you copy/paste it into Brackets you won't be able to select part of it. You can't even put the cursor between the text.
That makes it impossible to use Brackets for my projects.
Is there any solution to solve this?
Thanks

**Comment by MarcelGerber** [comment]
Cross-filed as https://github.com/codemirror/CodeMirror/issues/3489

**Comment by ficristo** [comment]
We have upgraded CodeMirror in #13116 which, _I think_, should have some fixes about this case.
Worth testing again in 1.9
