### ISSUE TITLE
(person 1) apparel bug

### ISSUE THREAD

**Issue by ialsaud** [adobe/brackets#11617]
Hello, 

I've been using Brackets for two days and I've faced a minor problem with appearance but not functionality. 

It was when I checked my list of apps on my mac that I noticed that I have four new apps that are google/chrome related and are all labeled "youtube (person 1)", "gmail (person 1), or "*** (person 1)". That wasn't annoying but the fact that they were not functional was. In addition, they were extras for my own "***" ie youtube, gmail apps were there too. 

![screen shot 2015-08-22 at 9 35 48 am](https://cloud.githubusercontent.com/assets/13893914/9424212/e6af68ac-48b1-11e5-87b4-92b0ef517eb6.png)

The problem seems to be caused by the bata that allows to run websites on chrome for testing. 

I'm not an experienced programmer, and I've just started using git hub. 

Help is greatly appreciated.

**Comment by abose** [comment]
brackets does not sideload any other applications. Could you specify how brackets is related to this issue?

**Comment by ialsaud** [comment]
I'm quite sure it does load chrome on Macintosh systems when you press the "live preview" button, that looks like little lightening icon. In addition, brackets does it in a weird way, such that it loads a different chrome. One without your personal data.

**Comment by abose** [comment]
Brackets does not install chrome, it just uses an already installed chrome install maybe under a different profile. @nethip will that cause this problem?

**Comment by nethip** [comment]
That's correct. We don't go about changing any apps. For live preview we just use existing instance of Chrome.

**Comment by petetnt** [comment]
`Person 1` is the name of the default profile of Chrome (when you are not signed in). (At least the non-experimental) LivePreview launches Chrome with that profile (== no profile at all). 

If you pin an Google Chrome App (Youtube, Google Drive, Gmail...) to your taskbar when using that instance of Chrome, I think those will always use the said profile they were pinned from, which leads to the situation @ialsaud has.

**Comment by petetnt** [comment]
`--disable-default-apps` flag should prevent this behavior

> --disable-default-apps : Disables installation of default apps on first run. This is used during automated testing. (from http://peter.sh/experiments/chromium-command-line-switches/)

**Comment by ialsaud** [comment]
Thank you @petetnt , @abose , and @nethip for contributing.

**Comment by abose** [comment]
Closing as answered.

**Comment by petetnt** [comment]
Fixed in https://github.com/adobe/brackets-shell/pull/533
