### ISSUE TITLE
Could not access to "http://brackets-registry.aboutweb.com/"

### ISSUE THREAD

**Issue by kooohei** [adobe/brackets#11625]
the past few days, I could not access to brackets extension registry.
Is there any other way? for update extension.

**Comment by petetnt** [comment]
Seems to work for me

http://downforeveryoneorjustme.com/brackets-registry.aboutweb.com

Still down for you?

**Comment by ryanstewart** [comment]
Talked to the About Web team and they restarted the server. Closing this one. Thanks all!

**Comment by kooohei** [comment]
yea thx I can update my extension :)

**Comment by nmaxcom** [comment]
This seems to be happening again

**Comment by swmitra** [comment]
Brackets extension registry is accessible. 
@nmaxcom Can you please check and confirm, so that this issue can be closed?

**Comment by nmaxcom** [comment]
It did work the time I used, yes. Someone should look this intermitence
though.

Thanks

**Comment by saurabh95** [comment]
Now we have upgraded the server and we haven't had any outage in the last 2 months, so I am closing this issue.
