### ISSUE TITLE
Code hint/completion regardless of extension

### ISSUE THREAD

**Issue by jspellert** [adobe/brackets#11629]
I don't know if this is an error or as intended but I can not under any circumstances get code completion for my css to appear if the file extension is .php.

It will complete the tag... "&lt;style&gt;" "&lt;/style&gt;" but if I add a class and begin entering style definitions, the popup window with suggestions never appears... however If I simply change the file extension to "html" and start typing the same style under my class it works as expected.

I believe this may be an error as it works correctly inside javascript tags regardless if the extension is PHP. Whether or not this is an error it would be nice to see it resolved so CSS would auto-complete regardless of file extension, Furthermore I have tried many different preference changes to no avail but if there is some workaround now that would be great.

**Comment by abose** [comment]
Fixed for 1.5. Closing.
