### ISSUE TITLE
Scrolling on Windows distance inconsistence

### ISSUE THREAD

**Issue by vimxts** [adobe/brackets#11627]
**I've read other issues regarding this, not sure where to put this post in.**

When you scroll down the codemirror or the working files, they all scroll too far on Windows.

Here are the results from my scrolling:

- Sometimes 7 lines with a scroll (A)
- Sometimes 20 lines with a scroll (B)

How to reproduce:

1. Open Brackets with a long document
2. Scroll down and observe. You will get either (A) or (B)
3. Spam scrolling up and down.
4. For a chance, you will be switched to the other (A) -> (B) or (B) -> (A)

Also, the chrome development tool is also scrolling way too fast.

**Comment by MarcelGerber** [comment]
Already filed as #11083. Closing as a duplicate.

**Comment by vimxts** [comment]
@MarcelGerber Thanks, I'll add my comment on #11083
