### ISSUE TITLE
Brackets hangs when pressing F5

### ISSUE THREAD

**Issue by sjoerd222888** [adobe/brackets#11631]
Pressing the F5 key makes everything turn white. Then brackets is frozen and does also not react on attempts to close the application. Application does not recover withing a minute so I guess it will remain in this state. Can only be stopped in the Task Manager.

Tested on Windows 8.1 using Release 1.4 build 1.4.0-16380 (release 273804eb3)

**Comment by petetnt** [comment]
This has been fixed in #11505 (you can try the master branch if you want to test it out)

**Comment by abose** [comment]
closing as fixed.
