### ISSUE TITLE
Confused word wrap

### ISSUE THREAD

**Issue by wesleifreitas** [adobe/brackets#11633]
The word wrap in Brackets looks confused .

**Currently**
![current_word_wrap fw](https://cloud.githubusercontent.com/assets/6631277/9526586/8a9cc86c-4cc0-11e5-85f1-bed29ec5ae52.png)

**Suggestion**
![suggestion_word_wrap fw](https://cloud.githubusercontent.com/assets/6631277/9526588/908d037c-4cc0-11e5-9d9e-3ecb3277f63c.png)

### e.g. javascript code

**In Brackets** :(
![b fw](https://cloud.githubusercontent.com/assets/6631277/9526766/b1963ace-4cc1-11e5-9f48-668503d399af.png)

**In Sublime Text** - Best to read, of course this is more visible in larger codes
![s fw](https://cloud.githubusercontent.com/assets/6631277/9526808/dd58a926-4cc1-11e5-87e8-92d752f16561.png)

I believe that the word wrap should respect indent code equal to Sublime Text and others.

What do you think?

**Comment by LeonMay** [comment]
I have the same issue, is there any fix for it? I really like brackets and would hate to switch, but this is really anoying. Please any help would be great

**Comment by abose** [comment]
Will be Fixed by #11909   scheduled for relase 1.6
