### ISSUE TITLE
Quick key for "console.log();"?

### ISSUE THREAD

**Issue by kramer65** [adobe/brackets#11648]
I'm editing a lot of javascript and I often need to type the inevitable `console.log();`. Is there some kind of quick key, or easy way of getting this line in my code?

All tips are welcome!

**Comment by sprintr** [comment]
You might wanna have a look at this (extension)[https://github.com/bguzmanrio/console-autocompleter-bracketsio].

**Comment by kramer65** [comment]
Thanks for the tip. Unfortunately that extension doesn't work for me.. :S

**Comment by redmunds** [comment]
This sounds like a good use of snippets. Search the Extension Manager for a few Snippets extensions.

**Comment by smelyakov** [comment]
This one works for me https://github.com/chuyik/brackets-snippets

**Comment by kramer65** [comment]
Awesome, that works brilliantly!
