### ISSUE TITLE
I have a problem about i drag a psd into the brackets

### ISSUE THREAD

**Issue by semi-xi** [adobe/brackets#11646]
1. i  sign into my Creative Cloud,so i can add the psd 
2. when i drag a psd into the brackets ,the previewing is ok,but when i click into the psd for some detail,there is nothing ,what'is wrong?Is it the file is so large?

just like the img
![pic1](http://ww1.sinaimg.cn/mw690/69327637gw1evltwqifb1j218k093mya.jpg "pic1")
![pic2](http://ww3.sinaimg.cn/mw690/69327637gw1evltx1k3lpj21810jeq38.jpg "pic2")

**Comment by czmj** [comment]
+1

**Comment by ryanstewart** [comment]
Are you using PSDs with artboards in them? We haven't updated Extract for Brackets with robust artboard support yet.

**Comment by ficristo** [comment]
Extract is deprecated: http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/
Closing
