### ISSUE TITLE
Brackets GUI Transparency / Opacity

### ISSUE THREAD

**Issue by tSynaptik** [adobe/brackets#11647]
It would be nice that Brackets have such an option. It could be useful for some of us.

![sublimetexttrans_by_vhanla-d6x17yw](https://cloud.githubusercontent.com/assets/13053170/9578535/8109d85e-4ff3-11e5-89ea-6c8e6a50d3ac.jpg)

**Comment by nethip** [comment]
:+1:

I have created  a trello card for this. Please up-vote [this](https://trello.com/c/w3dp09A3/1428-add-transparency-to-brackets-window) card

**Comment by nethip** [comment]
I am closing this as this is captured in [this](https://trello.com/c/w3dp09A3/1428-add-transparency-to-brackets-window) trello card.
