### ISSUE TITLE
Comment shortcut

### ISSUE THREAD

**Issue by mavct** [adobe/brackets#11643]
It'd be great if we could have a shortcut to comment and uncomment a line of code. If there is one, it's not indicated in the Edit menu.

**Comment by sprintr** [comment]
It is indicated as `Toggle Line Comment` and `Toggle Block Comment` in the Edit menu.

**Comment by mavct** [comment]
Exactly, but there's no keyboard shortcut to activate them unfortunatly. After selecting a line you need to go the the menu to comment it. It would be much faster with a keyboard shortcut

**Comment by sprintr** [comment]
There are shortcuts for them `Ctrl-/` and `Ctrl-Shift-/` respectively.

**Comment by mavct** [comment]
Sweet thanks! I wonder why they're not displayed in the edit menu like the others. In any case, thanks a lot :)

**Comment by sprintr** [comment]
Can you see if there is any warning logged in the brackets' dev tools console. They should be displayed like others.

**Comment by mavct** [comment]
Is this what you're looking for ? 

![brackets](https://cloud.githubusercontent.com/assets/13253468/9569333/bb15b626-4f35-11e5-952e-75cbe83557c6.png)

**Comment by sprintr** [comment]
It means that the shortcut is already been registered by an extension. Go to `Debug` > `Reload Without Extensions` to make sure it is happening because of an extension. If so, disable your extensions one after another to find the extension causing this.

**Comment by mavct** [comment]
Reloading without Extensions didn't change anything. In my extensions manager, I only had the default "Extract for Brackets (Preview)" from Adobe, which I disabled just in case. The shortcuts still don't show.

I don't really mind as long as I can still use them with the keyboard.

**Comment by sprintr** [comment]
Most of those warnings are generated because of Extract. I am not sure if extract causes that behavior. If the keyboard shortcut works for you then it should be fine for now.

**Comment by mundorfd** [comment]
I have the same issue - the keyboard shortcuts don't display in the menu, nor does it work. 
![Screen Shot 2021-02-25 at 7 22 53 AM](https://user-images.githubusercontent.com/57678987/109175137-59015480-773a-11eb-9d4b-b0ca8acd9c39.png)
