### ISSUE TITLE
Newline doesn't indent.

### ISSUE THREAD

**Issue by sphinx9** [adobe/brackets#11650]
As the title says, starting a new line after typing the opening code for an element (in html, for example) doesn't create the required indentation.

Eg, typing `<div>` then hitting return then typing "what" will end up with this:

```html
<div>
what
```

rather than

```html
<div>
    what
```

...as expected.

edit: I've also tried relaunching without extensions, no difference.

**Comment by petetnt** [comment]
Not sure if I missed something in your description but newlines indent correctly for me in Brackets 1.4. and in the CodeMirror demo (http://codemirror.net/1/htmltest.html)

**Comment by sphinx9** [comment]
How odd. I have Brackets 1.4 (build 1.4.0-16380), running on Windows 10, and newlines are certainly not indenting properly for me.

I just tested further and if I type "<div>what" as described in my original post then there's no indentation, but if I press the up key then the end key (as in, using the keyboard to navigate to the end of the previous line) THEN hit return, then the indentation is correct. Is this a bug...?

**Comment by sphinx9** [comment]
I made a gif to more accurately explain: https://gyazo.com/7f799f854df3006b8ea09a3363669f8a

**Comment by sphinx9** [comment]
.

**Comment by torvalamo** [comment]
I think it is because it cannot distinguish between whether you have auto-closing tags or not.

When you type `<div>` and have auto-closing tags on, it will create a `</div>` after the cursor. When you then press enter, it moves it to the next line at the same indentation level as the start tag. If it indented it, you would have had to de-indent it to have it be correct.

I do believe a better system can be made, for instance creating two new lines, and indenting the first one, leaving the end tag on the second line at the same indentation as before, but the cursor on the first line, indented.

**Comment by sphinx9** [comment]
> When you then press enter, it moves it to the next line at the same indentation level as the start tag. If it indented it, you would have had to de-indent it to have it be correct.

You've misunderstood. I'm not suggesting that I should have an indented "</div>", as that would indeed be incorrect. What it should do is add two newlines, the first one being indented once more and the second one consisting of "</div>" with the indentation unchanged from the original line.

> because it cannot distinguish between tags that are supposed to be self-closing and tags that have start and end tags. 

Yes it can. Other text editors can. It's not hard to work out. If it'd be valid to close the 'tag', do it - if not, don't. No such thing as </img>.

**Comment by sphinx9** [comment]
Just to clarify, this is what happens: https://gyazo.com/dfa36da3aab4b71978a89342908494cd

This is wrong.

This is what should happen, only without having to navigate up a line and hit enter again: https://gyazo.com/71f6110fc5953804555cb26609133e16

**Comment by jeffstahlin** [comment]
This is happening to me too on build 1.5.0-16538 on Windows 10.

**Comment by ethan7878** [comment]
I've been having the exact same issue, I made a short video on youtube to demonstrate.
https://youtu.be/--wmPGfKdU8
I don't have any extensions, I haven't touched any settings, I even re-installed but nothing is fixing it.

**Comment by ficristo** [comment]
If you set the closeTags preference, does solve your problem? Something like:
```json
  "closeTags": {
    "indentTags": ["div"]
  }
```
[Here](https://github.com/codemirror/CodeMirror/blob/d0dca6532dd668cf415b2740152b93d1cb454410/addon/edit/closetag.js#L50) the complete list of tags set in CodeMirror.

**Comment by Sumkeee** [comment]
Did you find the solution on this?
