### ISSUE TITLE
EXTRACT does't load after updating to WINDOWS 10

### ISSUE THREAD

**Issue by goprofast** [adobe/brackets#11659]
I just updated to Windows 10 and can't start Adobe Extract  anymore! I just get extension error. I tried to uninstall/install Brackets and Extract and nothing did help! Any ways to make it work again?
![extract2](https://cloud.githubusercontent.com/assets/14100588/9646656/1ab50c92-51ef-11e5-8780-eb1441ab6942.jpg)
![extract](https://cloud.githubusercontent.com/assets/14100588/9646658/22dcf09c-51ef-11e5-9e2c-573cda8afa47.jpg)

**Comment by goprofast** [comment]
Problem fixed after I deleted all extensions and then reinstalled it back.

**Comment by sixertoy** [comment]
Hey did you get a lot of bug with windows 10 ?
With a fresh install, no extension i can't open a new project
Seems like Brackets is not supported by Windows 10 :(

**Comment by goprofast** [comment]
After I fixed my problem with Extract, no other bugs I've noticed yet. Just some small stuff that described in other topics - like extensions list slow loading for example. I hope they will fix everything soon.
