### ISSUE TITLE
Blank screen after reloading

### ISSUE THREAD

**Issue by stritar** [adobe/brackets#11656]
It started out of nowhere. Whenever I reload (cmd-r) app frame goes blank without going back to the initial state. Toolbar is responding and that's about it. I have the latest version.
![_users_stritar_library_application_support_brackets_brackets_json__html__ _brackets](https://cloud.githubusercontent.com/assets/3016106/9626435/de22582a-515d-11e5-889e-d5b2fb77ebfd.png)

**Comment by ryanstewart** [comment]
Is this 1.4 or did you build Brackets from source?

**Comment by stritar** [comment]
@ryanstewart It started working normally again the next day. It was probably some bug on my OS...perhaps memory issue...who knows. It works fine now. Thanks.

**Comment by nethip** [comment]
@stritar This was a known issue. It is now fixed in 1.5.
