### ISSUE TITLE
after installing brackets by npm just can be used in browser

### ISSUE THREAD

**Issue by NikosEfthias** [adobe/brackets#11665]
I installed brackets throug npm but now i cant open gui just listening port and i need to use browser to use and opening psd files are unavailable

I also checked here https://github.com/adobe/brackets-shell/wiki/Building-Brackets-Shell downloaded and tried to install as in instructions but everything fails

**Comment by petetnt** [comment]
This is an [brackets-server](https://github.com/rabchev/brackets-server) issue, a third party project. It's meant for in-browser use. If you want a standalone version, download and install Brackets via the [installer](https://github.com/adobe/brackets/releases). If you want to hack Brackets, check out [How to hack Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets).

If you just want to use package manager to install Brackets, it's at least available as Chocolatey package on Windows.

**Comment by NikosEfthias** [comment]
<p>while following the instructions u sent me after typing grunt gives following error</p>
<code>Running "build-linux" task
>> In file included from appshell/command_callbacks.h:4:0,
>>                  from appshell/client_handler.h:15,
>>                  from appshell/appshell_extensions.h:27,
>>                  from appshell/appshell_extensions.cpp:24:
>> appshell/appshell_extensions_platform.h: In function ‘void* getMenuParent(CefRefPtr<CefBrowser>)’:
>> appshell/appshell_extensions_platform.h:74:57: error: ‘GTK_WIDGET’ was not declared in this scope
>>          GTK_WIDGET(browser->GetHost()->GetWindowHandle()),
>>                                                          ^
>> appshell/appshell_extensions_platform.h:75:9: error: ‘GTK_TYPE_VBOX’ was not declared in this scope
>>          GTK_TYPE_VBOX);
>>          ^
>> appshell/appshell_extensions_platform.h:75:22: error: ‘gtk_widget_get_ancestor’ was not declared in this scope
>>          GTK_TYPE_VBOX);
>>                       ^
>> make: * [out/Release/obj.target/Brackets/appshell/appshell_extensions.o] Error 1
Warning: Task "build-linux" failed. Use --force to continue.

Aborted due to warnings.
</code>

**Comment by ryanstewart** [comment]
As @petetnt, installing via npm isn't something that's part of the core Brackets project. So I'm going to go ahead and close the issue.

**Comment by NikosEfthias** [comment]
@ryanstewart  installing from source gives the error i posted above i removed npm version so far as i understand it is not possible to install on arch linux is that right?

**Comment by codecowboy** [comment]
@NikosEfthias Did you get any further with this? @ryanstewart what is the procedure for installing / building from source?

**Comment by petetnt** [comment]
@codecowboy for instructions on installing / building from source, see [How to hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) and [Building Brackets Shell](https://github.com/adobe/brackets-shell/wiki/Building-brackets-shell)

**Comment by NikosEfthias** [comment]
@codecowboy  nope just swithced to a debian based distro

**Comment by NikosEfthias** [comment]
@codecowboy  and as you can see the reply by @ryanstewart  simply they build this for deb only i guess you are actually not supported as he says "IT IS YOUR BUSSINESS" if you are not under a deb based distro

**Comment by petetnt** [comment]
@NikosEfthias, no, that's not what @ryanstewart meant. He means that the Brackets that is on `npm` is a third party project called [brackets-server](https://github.com/rabchev/brackets-server/issues). If you have issues with that, you should report them on that repo instead. 

It's true that only Debian based builds are officially supported, but it should be possible to build on other distributions too. For example your earlier build issue might be because you were missing `GTK+` on your Arch Linux installation, but I am not completely sure about that.

**Comment by NikosEfthias** [comment]
@petetnt  after that i wrote anyway by instructions i installed from source by removing npm version but topic stayed closed
