### ISSUE TITLE
Files are not being closed on OS level when closed in Brackets.

### ISSUE THREAD

**Issue by iamyenz** [adobe/brackets#11666]
If you close a file by clicking the cross next to the file in the sidebar, the file is not properly closed. File cannot be moved or deleted as Windows reports it as being open. Not until you close Brackets can the file be moved or deleted. This happens in Windows 10 Pro 64-bit and bug can readily be recreated.

**Comment by petetnt** [comment]
Cannot replicate on Windows 10 Pro 64-bit myself. Do you have any very specific steps (or file types) that this happens to?

**Comment by iamyenz** [comment]
I have now re-installing Brackets and the issue has disappeared...
