### ISSUE TITLE
Errors in Arduino Alpha < A.S.>

### ISSUE THREAD

**Issue by FrankOcean11** [adobe/brackets#11667]
The ArduinoStudios is giving me a error saying:Command failed: C:\Users\Franks\AppData\Local\Temp\build1441644299986\MPU6050_Tx.cpp:16:18: fatal error: Wire.h: No such file or directory #include "Wire.h" ^ compilation terminated. 

(let me add a side note that this new error just occur while at first it was giving errors about SPI now is about Wire when Wire is in there as well)

in the regular IDE i dont get this issue but in the Alpha/ArduinoStudios i do, any fix for this?

**Comment by petetnt** [comment]
Try posting this in the [ArduinoStudio-repos issues](https://github.com/arduino-org/ArduinoStudio/issues), it seems to be fairly active (outside of issues that is).

**Comment by FrankOcean11** [comment]
thanks pete.
