### ISSUE TITLE
goDocStart/goDocEnd show as "nonexistent commands"

### ISSUE THREAD

**Issue by tvidal-net** [adobe/brackets#11662]
Not sure if this is actually a bug, but I could not find anything related to it, so please forgive me in advance if this is not appropriate.

I'm trying to replace Cmd-Home and Cmd-End to Ctrl-Home and Ctrl-End keyboard shortcuts on brackets for Mac.

Steps to reproduce:
using the display shortcuts extension (which is optional):
- Open the display shortcuts extension (Ctrl-Opt-/)
- Lookup the shortcuts I want to change (Cmd-Home, Cmd-End)
- Cmd-Click and choose "Override shortcut for command"
- The User Key Map file is opened, and the following line is added:
    "[new-shortcut-here]": "goDocStart",
- I change "[new-shortcut-here]" for "Cmd-Home".
- When I save, I get the message "You are assigning shortcuts to nonexistent commands:" (see attached screenshot)

The same happens if I just click "Debug/Open User Key Map", and add the line to the overrides list manually. So I think it's not related to the display shortcuts extension.

If this is not a bug, please advise on the correct way to remap the keyboard shortcuts I mentioned.

Thank you, and congrats for the excellent work!!
Best regards.

![screen shot 2015-09-05 at 14 57 55](https://cloud.githubusercontent.com/assets/1281128/9699311/60cc7e2a-53d6-11e5-9534-6eb70ed10741.png)

**Comment by redmunds** [comment]
@tvidal-net Look in the origin column and you'll see those are CodeMirror commands. Unfortunately, the Brackets keymap does not override CodeMirror shortcuts.

I took a quick look but was not able to find an easy way to override CodeMirror shortcuts, but you can edit thirdparty/CodeMirror/lib/codemirror.js directly.
