### ISSUE TITLE
Cannot open a new Brackets Instance (window) on Windows 10 

### ISSUE THREAD

**Issue by yahyazini** [adobe/brackets#11660]
Since there's no Open new window link under the file menu, the only way I used to open a new instance was by right clicking the Brackets icon on the task bar and do open. But since I upgraded to Windows 10 this would only take me to the already open window.

Is there a work around to fix this?

**Comment by nethip** [comment]
@yahyazini You could get a new brackets window by choosing `Debug > New Brackets Window`.

**Comment by petetnt** [comment]
I have an open issue #11504 about taskbar integration (right clicking the icon) ideas, including opeting a `New Brackets Window` if you have Windows native coding skills or if you happened to know someone who did and would be interested in contributing to this feature.

**Comment by yahyazini** [comment]
@nethip Thanks a lot for the tip. I didn't know that, it's not very intuitive.

**Comment by yahyazini** [comment]
@petetnt That's a brilliant idea.I'll share it with a couple of friends. Thanks.

**Comment by ryanstewart** [comment]
Yeah, this is on the backlog (https://trello.com/c/YM0YySxX/679-multiple-separate-windows-official-new-window-command) but isn't planned yet. But definitely something we know we need to get to.

**Comment by ariansacct** [comment]
The Debug menu is not the best place to put that option. First, it's not clear this is most relevant to debugging. Second, most popular IDEs/editors put that in either the File or the Window menu.
