### ISSUE TITLE
FEATURE REQUEST - tabs

### ISSUE THREAD

**Issue by TreyTaylor** [adobe/brackets#11661]
Instead of a working file menu and then a menu of all files, can tabs be opened instead? A lot of cool features could be implimented.. like hitting CTRL + x to change tabs for increased productivity. As well as double clicking one tab and it splitting with the tab next to it, (or you can right click the tab, hit a button thats says split with.. and it comes up with all files in current working directory)?

(if you still dont understand what I mean take a look at Atom or Sublime Text)

-Trey

**Comment by petetnt** [comment]
There seems to be multiple extensions that do this, such as:

https://github.com/DH3ALEJANDRO/custom-work-for-brackets
https://github.com/demonmhon/brackets-working-file-tabs
https://github.com/crot4lus/Brackets---Tabs/issues/7

I haven't tried them myself, but seems like they would be worth trying.

**Comment by ryanstewart** [comment]
This is definitely something we've talked about, but for now we suggest you get one of the tabs extensions.
