### ISSUE TITLE
Liveview Freezing

### ISSUE THREAD

**Issue by AnthonyMichaelc** [adobe/brackets#11670]
After the latest release of Brackets My version has been freezing when I code with the liveview on. The machine is a lenovo with an i7 and an ssd so the hardware is not the issue. Seems like something is being held up when the liveview is on for a period of time. The only solution I have made is in order to see the changes close the program and reopen it then it works for a little, until I have to do it again. Brackets is my go to editor, Dreamweaver is my top editor on my machines and visual studio is a backup, but this issue makes me have to open up dreamweaver until the liveview freezing stops.

**Comment by ingorichter** [comment]
Does this happen with every html file? Does this happen with the getting started project?

**Comment by AnthonyMichaelc** [comment]
Yes. It will turn off and on if it's only left on for a little but I'd I
make changes to my file for a few minutes or more it freezes. I haven't
tried it on my Mac machine but windows 10 machine is freezing.

**Comment by AnthonyMichaelc** [comment]
I tried typing a few letter sin the starter file and then let it sit for a minute and then clicked the liveview of and it was stuck. So far it only happens on my windows machine since I do not use my mac machine often.

**Comment by nethip** [comment]
@AnthonyMichaelc If it is not too much of an effort, could you try this with 1.3 and tell us if you are seeing any issue with that build. (Be sure to rename the preferences directory, before launching 1.3 as there is a hard dependency we have introduced in E4B with 1.4.)?

**Comment by prafulVaishnav** [comment]
@AnthonyMichaelc Can you go to `Debug > Show Developer Tools` and check `console` if there is any error.

**Comment by AnthonyMichaelc** [comment]
I completely wiped everything on my computer related to brackets 1.4 and tried 1.3. Then wiped it again and installed the 1.4 prerelease and the problem seems to have stopped for now but have not had much time to run it for a long edit period.

**Comment by AnthonyMichaelc** [comment]
I completely removed everything brackets has installed, including the appdata files and then installed the latest and reinstalled the extensions I had before. I will test this out to see if the liveview continues to freeze and give you an update on whether or not that fixes the issues on Windows

**Comment by ficristo** [comment]
I close this since we haven't heard any news and the problem seems have been fixed.
If you have still problems reopen.
