### ISSUE TITLE
Bracket consume lot of cpu when open it

### ISSUE THREAD

**Issue by atussec** [adobe/brackets#11677]
am using brackets 1.4 but since i move to 1.4 it consumes upto 80% of my cpu usage.
am on lenovo T420 intel i5 2.5 processor
my ram is 8gb with 360 ssd drive
my OS is debian jessie 
![screenshot from 2015-09-09 10 06 50](https://cloud.githubusercontent.com/assets/14014310/9759211/ffab0884-56da-11e5-83ed-1100eec22c33.png)

**Comment by nethip** [comment]
Tagging @abose

**Comment by abose** [comment]
Can you try `debug>reload without extensions` and see if that helps.
Also i have seen this issue in windows rarely, the browser processes takes up lots of cpu. Restarting usually fixed the problem for me.

**Comment by atussec** [comment]
after doing that brackets uses less than 5% of cpu. whats the posible cause?
![screenshot from 2015-09-09 10 38 01](https://cloud.githubusercontent.com/assets/14014310/9759753/fada8ff6-56de-11e5-9c22-678d570f7b90.png)

**Comment by abose** [comment]
It might be some extensions that is consuming lots of cpu. You could go into extension manager and disable each plugins utill you find the extension causing the problem. Please post back your findings for tracking this issue.

**Comment by atussec** [comment]
am able to narrow it down is the theme am using, will add issue to the theme developer but he doesnt allow post of issues.
the theme am using is delkos dark theme

**Comment by abose** [comment]
Please raise the issue with the extension developer as that is not under brackets domain. 
There are several alternative dark themes available. Check it out :+1: 
Closing as extension issue.
