### ISSUE TITLE
Shortcut to select text inside tags

### ISSUE THREAD

**Issue by dm4000** [adobe/brackets#11680]
It would be excellent if there could be a keyboard shortcut to select all the text inside the tags that the cursor is in!
> Cmd + Shift + A?

**Comment by mseiler025** [comment]
I just finished making this

https://github.com/mseiler025/select-tag-contents

**Comment by dm4000** [comment]
Wow!
Thank you!!
I'm looking forward to trying it out!


Kind regards,

Daniel

**Comment by abose** [comment]
Thanks @mseiler025
