### ISSUE TITLE
Unable to write in Popup text box, if no file is present in Working files

### ISSUE THREAD

**Issue by msareen** [adobe/brackets#11681]
Way to reproduce : 

1) Open a project, close every file in "Working files" pane
2) Open "Extension Manager", when it loads try to search for anything, you will see that you are unable to type(write) in anything.

**Comment by ingorichter** [comment]
I can't repro this on OSX with the latest Brackets version. Which version do you have installed? On which platform?

**Comment by ipbebnev** [comment]
ubuntu 14.04

**Comment by ingorichter** [comment]
Version 1.6?

**Comment by pwnorbitals** [comment]
@msareen still reproducible on latest builds ?

**Comment by msareen** [comment]
Sorry I moved to VS Code 5 years ago.
