### ISSUE TITLE
Brackets Showing Legacy "Close, Minimize, Maximize" Buttons (Mac OS 10.11)-bug

### ISSUE THREAD

**Issue by ajarshem** [adobe/brackets#11689]
Just upgraded to the GM release of El Capitan, and for some reason brackets won't allow for full screen mode anymore and is using the classic ui elements for the "Close, Minimize, and Maximize" Buttons.  More of a minor bug than anything.
![screen shot 2015-09-11 at 9 35 30 am 2](https://cloud.githubusercontent.com/assets/10198510/9817533/2c11afc4-5869-11e5-9da5-e736698e7da2.png)

**Comment by abose** [comment]
This is fixed in release 1.5[to be release soon].Closing as fixed.

**Comment by ajarshem** [comment]
Awesome, thanks!
