### ISSUE TITLE
Unable to Save SFTP Host with Nonstandard Port

### ISSUE THREAD

**Issue by watsonit** [adobe/brackets#11699]
When changing the SFTP port from the default 22, the APPEND button enters a disabled state. Trying to trick the UI by entering all information and then changing the port (without exiting the port field) and clicking APPEND does not work.

**Comment by watsonit** [comment]
I found where SynapseDomain.js read the port from the form and hard-coded to my needed port. This allowed saving of the host. I then found where brackets.json stores the brackets-synapse.server-settings. I reverted my hard-coded port hack and now have the syntax needed for the remote SFTP host definitions. This gets me going for now, but I do believe ports should not be limited to those containing 22.

**Comment by petetnt** [comment]
This is an [brackets-synapse](https://github.com/kooohei/brackets-synapse)-extension issue, correct? You should file this issue there, the repo seems fairly active too!

**Comment by watsonit** [comment]
I should know better. Thanks for the response.
