### ISSUE TITLE
Brackets live preview not working 

### ISSUE THREAD

**Issue by JartOfDeath** [adobe/brackets#11694]
When I open the live preview it will often give me an error saying"Unable to load live preview page" my chrome browser and brackets are both most current versions, I'm not using a local server, and there are no html errors/live preview isn't red. And when it does open it doesn't change as I type only if i ex out of it save my file and then it might update changes but still not live.

**Comment by prafulVaishnav** [comment]
@JartOfDeath Can you tell Brackets version and how many files you have in your project?

**Comment by JartOfDeath** [comment]
@prafulVaishnav version 1.4 and theres only one file in the project

**Comment by abose** [comment]
Could you go to `debug>show developer tools> console` and comment the error here?

**Comment by JartOfDeath** [comment]
@abose Max connection attempts reached (anonymous function)
Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by abose** [comment]
How many files are in your project? 
Could you copy the full call stack here?

**Comment by JartOfDeath** [comment]
There's only one file in my project and it doesn't work with the getting started page that brackets opens up to either

**Comment by abose** [comment]
would it be possible to share the call stack, or any specific on which port is issuing a  net::ERR_CONNECTION_REFUSED 
Which os are you on?
Do you have google chrome installed?

**Comment by yohanes-ai** [comment]
If you are using Windows, try run brackets as administrator. It worked for me

**Comment by blind0x** [comment]
For everyone, this problem can be resolved by following steps:- 

1. On menu bar, go to  File --> Open Folder (folder which have your html file for live preview)

2. Select Folder

3. Select your html file from left side bar for live preview

4. Click on bolt icon on right (preview button) 

All it melts down to the fact, that you need that folder(which have your file) selected to view your output in live preview. 
Let me know, if it helps someone. :)
