### ISSUE TITLE
.DS_Store and all hidden .folder or .file are shown in Project Tree

### ISSUE THREAD

**Issue by levous** [adobe/brackets#11707]
I've just installed a fresh copy of 
Release 1.4 build 1.4.0-16380 (release 273804eb3) 
build timestamp: Sun Jul 26 2015 23:37:22 GMT-0700

No extensions are enabled.
In the left pane, I see all the hidden files I don't want to see or accidentally mess with

![screen shot 2015-09-15 at 10 23 43 am](https://cloud.githubusercontent.com/assets/28144/9879094/dfd652e4-5b93-11e5-9753-3b53b6099f5b.png)

I see this has been reported and closed before.  I don't see any option or documentation on hiding these files.

**Comment by ingorichter** [comment]
Have you tried this [extension](https://github.com/zaggino/brackets-file-tree-exclude)?

**Comment by abose** [comment]
Closing inactive thread.
