### ISSUE TITLE
Cannot open Developers Tools (F12)

### ISSUE THREAD

**Issue by IgorNovozhilov** [adobe/brackets#11709]
Если не установлен Chrome, инструменты не открываются и нет никаких сообщений об ошибке. Нужно выводить окно с ошибкой.

Linux Mint 17.2 KDE
sprint 4 Экспериментальная сборка 1.4.0-16380 (release 273804eb3)

**Comment by abose** [comment]
Chrome needs to be installed for dev preview to work. an error dialog needs to be shown if chrome remote debugging session is not enabled.

**Comment by GelaniNijraj** [comment]
Is it okay if I check if chrome is installed by executing a shell command first to achieve this?

**Comment by GreenRobot777** [comment]
Debug -> Show developer tools (F12) wasn't work.

Solution (if Google Chrome is already installed, but F12 still not work):

`ln -s /opt/google/chrome/google-chrome /bin/google-chrome`

Note: you will probably need to run as root
This adds the proper symlink. Confirmed working Sabayon Linux 16.02

I found this solution from here #7372

**Comment by kaustubhmallik** [comment]
Is this still open?

**Comment by ficristo** [comment]
This issue is still valid. But instead of showing an error if Chrome is not installed, we should upgrade the brackets-shell to use a more up-to-date CEF version. This would enable to show the developer console inside Brackets itself.
See https://github.com/adobe/brackets-shell/pull/589 for my last attempt.

**Comment by nyteksf** [comment]
I am having the same problem currently with Debian Jessie (x86) running XFCE.

**Comment by IgorNovozhilov** [comment]
неактуально
