### ISSUE TITLE
Bad menu panel

### ISSUE THREAD

**Issue by iNovozhilov** [adobe/brackets#11708]
https://drive.google.com/open?id=0B79v8XZ-aTqweTJMZmxCZEVBTXc

Linux Mint 17.2 KDE
sprint 4 Экспериментальная сборка 1.4.0-16380 (release 273804eb3)

**Comment by iNovozhilov** [comment]
https://github.com/adobe/brackets/issues/11501
Это печально... хотя бы удалите дублирование имени файла из меню, а то оно огромным шрифтом съедает много места.

**Comment by abose** [comment]
This is by design in linux. Please enlarge the window to a greater dimension to see the menu.
#11501 can only fix the actual problem. So closing as cant fix.
