### ISSUE TITLE
ES6 template strings mess up color coding

### ISSUE THREAD

**Issue by globexdesigns** [adobe/brackets#11714]
Not sure if I should file this here or with CodeMirror, but using template strings with JSX results in broken syntax styling in Brackets.

Sample code that fails:

```javascript
export default class Test extends Component {
	render () {
		return (
			<div className={`${CLS}-Pane`}>
				Oops. Everything below this line is now in the wrong colour.
			</div>
		);
	}
}
```

And here is how Brackets renders this:

![screen shot 2015-09-16 at 8 43 39 am](https://cloud.githubusercontent.com/assets/226640/9909871/1a2aedc2-5c4f-11e5-8078-d8b7b6ce5b5e.png)

**Comment by petetnt** [comment]
Actually it's not the template strings, it's the JSX-syntax in general. There's a long-running issue about adding React support #11061 which I was (sort of) working on but right after I started on it I was flooded with other work. It's still high on my list but haven't had the time to work on it for months.

**Comment by globexdesigns** [comment]
This issue is not specific to JSX as some plain ES6 code also fails to process template strings correctly. See:

![screen shot 2015-09-17 at 4 40 01 pm](https://cloud.githubusercontent.com/assets/226640/9948774/d669fbc0-5d5a-11e5-9932-5b317ab80c31.png)

**Comment by zaggino** [comment]
Guys, I believe you need to direct this against https://github.com/codemirror/codemirror

**Comment by zaggino** [comment]
And btw, @globexdesigns are you sure this is not caused by some plugin? I'm running latest Brackets and it looks like this to me: 
![image](https://cloud.githubusercontent.com/assets/1067319/9948893/9698151e-5dea-11e5-8e01-9743774bfa26.png)

**Comment by globexdesigns** [comment]
@zaggino Same issue with all extensions disabled. The issue is not consistent. Some template strings work, but others do not. I think it depends on where the template string is. Seems to fail if it's inside `<>` or if it contains colons. I'll more this to codemirror.
