### ISSUE TITLE
"Find in Files" causes Brackets to freeze every time

### ISSUE THREAD

**Issue by MattSlone** [adobe/brackets#11719]
Every time I try "Find in Files" the program hangs and becomes unresponsive.

**Comment by abose** [comment]
How many file are there in the project?
Could you go to `debug > show developer tools` console and comment the error message here?
And finally if the problem persists, you could use the old search infrastructure by `debug>open preferences file`and then add `"findInFiles.nodeSearch": false `to the preferences.

**Comment by ficristo** [comment]
Closing as we haven't heard you back.
If you still have the problem, reopen after trying the suggestions given by @abose.
