### ISSUE TITLE
Support any charsets

### ISSUE THREAD

**Issue by marconiduarte** [adobe/brackets#11718]
Support any charsets

**Comment by petetnt** [comment]
There's an [Trello card](https://trello.com/c/DShzQztM/731-support-encodings-other-than-utf-8) for this feature.

**Comment by marconiduarte** [comment]
I installed it did not work properly




On 17 September 2015 at 12:32, Pete Nykänen <notifications@github.com>
wrote:

> There's an Trello card
> <https://trello.com/c/DShzQztM/731-support-encodings-other-than-utf-8>
> for this feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/11718#issuecomment-141123325>.
>



-- 
*Ezequiel 3:14*
Então, o Espírito me levantou e me levou; eu fui amargurado na excitação do
meu espírito; mas a mão do SENHOR se fez muito forte sobre mim.

*NOTA:* Este e-mail e seus anexos são dirigidos tão somente ao(s)
destinatário(s) nomeado(s). Caso o tenha recebido por engano, não copie,
não distribua e não divulgue, notifique o remetente imediatamente.
*NOTE: *This email and its attachments are addressed solely to (s)
recipient (s) named (s). If received in error, do not copy, do not
distribute and do not disclose, notify the sender immediately.
