### ISSUE TITLE
Markdown & Tag

### ISSUE THREAD

**Issue by ldez** [adobe/brackets#11723]
Syntax highlighting failed with simple tag in code fences.

![brackets-markdown-syntax](https://cloud.githubusercontent.com/assets/5674651/9977963/1241c67a-5f1b-11e5-9729-cba66b5964ee.png)

**Comment by petetnt** [comment]
Couldn't replicate with Brackets 1.4. on Windows in Markdown or in Markdown (Github) myself...

Are there any specific steps to re-perform this issue? Tried just writing it in and fiddling around the code ```:s to no avail.

**Comment by ldez** [comment]
I use Brackets 1.4 on WIn 7 x64.

```markdown
# Title

## First Heading

Foobar

\```html
<div>
\```

## Second Heading

Fiibar
```
I put  `\` before backticks only for valid display witihin GItHub.

I try without extension with same result.

**Comment by petetnt** [comment]
This is how it looks for me:

![image](https://cloud.githubusercontent.com/assets/7641760/9982188/b34f1b2e-5fdb-11e5-807d-1c0d9e21cb96.png)

(Github flavored)

![image](https://cloud.githubusercontent.com/assets/7641760/9982194/ef12f66c-5fdb-11e5-87db-81b7ec13bf5d.png)

**Comment by ldez** [comment]
I use default theme 'Barckets Dark'

**Comment by ldez** [comment]
Fail only with default Markdown'.
Works with GFM.

**Comment by lucasecardoso** [comment]
Is this still a problem for you? Tried to reproduce on Brackets 1.7 Win 7 64 bits and I'm not getting the same result. 

Default Markdown:
![image](https://cloud.githubusercontent.com/assets/12672911/17821733/8dee5598-6629-11e6-81c0-1fd1e35cba02.png)

GFM:
![image](https://cloud.githubusercontent.com/assets/12672911/17821751/a77a84aa-6629-11e6-9da3-ee2a55be3e05.png)

Let me know if it's still the case.

**Comment by ldez** [comment]
I confirm it's fixed.
