### ISSUE TITLE
Indentation bug 

### ISSUE THREAD

**Issue by gautamz07** [adobe/brackets#11720]
Well i have a task.txt file and when copy a peice of text , that looks like so:

grunt.js {
    - install grunt.js.
    - Learn basics of grunt.js.
}

and paste it on a new line , The indentation is gone , like so:

grunt.js {
- install grunt.js.
- Learn basics of grunt.js.
  }

Why is this happening and what is the fix to this ? 

Thank you.

**Comment by ficristo** [comment]
I cannot reproduce, if you still have problems please open a new issue.
