### ISSUE TITLE
Feature Request: Keep search bar open while editing

### ISSUE THREAD

**Issue by spongessuck** [adobe/brackets#11735]
Right now, if you click in the edit panel, the search bar closes. It would be nice if the search bar would remain open while editing, or at least for it to remember the last thing you searched for. I often search around for matches to do some minor edits and move on to the next match, but I have to re-open the search and type my pattern again.

**Comment by kidwm** [comment]
and keep the highlight effects too.

**Comment by fabio-farolfi** [comment]
every time I have to reopen the search and type my pattern again.
I hope for a solution as it is terribly annoying.

**Comment by abose** [comment]
Search bar will now remember the last searched phrase. closing as fixed for 1.6.

**Comment by phanect** [comment]
Hi @abose, 

> Search bar will now remember the last searched phrase

It doesn't help when I want to:

1. Copy phrase from opening file and paste it as phrase to find
2. Copy another phrase from opening file and paste it as phrase to replace

Phrase to find is discarded when you copy another phrase.
So I appreciate if search bar is kept open, or Brackets remember last *entered* phrase, not searched phrase.

**Comment by Likewise42** [comment]
Just commenting to say that I would also like the search bar to stay open until I manually close it.
