### ISSUE TITLE
[Feature Request] Find with Special Characters

### ISSUE THREAD

**Issue by krazykhris875** [adobe/brackets#11737]
I can't find anywhere were this has been requested before, but the ability to search with special characters would make my life about a 100x easier. I work primarily with PHP, and the fact that I can't include the "$" when searching for a variable in a file makes things a lot more difficult. Are there plans to support searching with characters like "()", "$", "*"?

**Comment by redmunds** [comment]
If you are doing a regex search (i.e. the `.*` button) then `$` is a special character and needs to be escaped as `\$`. Brackets uses the JS RegExp engine, so you can find all special chars here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by krazykhris875** [comment]
The fact that I can just escape them changes my life haha. Thank you. You are a gentleperson and a scholar.

**Comment by redmunds** [comment]
Glad it helped. Closing.
