### ISSUE TITLE
Brackets is Acting Weird

### ISSUE THREAD

**Issue by erayerdin** [adobe/brackets#11739]
I decided on this table since there's a couple of issues in my case. I installed Brackets in my Kubuntu 14.04 machine via dpkg.

The first error I'm getting whenever I open is:

 > **Error Opening File** An error occured when trying to open the file /opt/brackets/samples/root/Getting Started/index.html. Brackets currently only supports UTF-8 encoded text files.

Later on, I choose a project folder to see my project files (which is *$HOME/Documents/Project Folder*), but I cannot see them, not any single folder or a file. However, whenever I open my Apache project folder (which is */var/www/html/projects* and **already has chmod 777**), I see my folders now, but I cannot expand it (I cannot see again.). 

![image](https://cloud.githubusercontent.com/assets/2399084/10088580/7a561e0c-6324-11e5-8434-00014fbe5a98.png)

![image](https://cloud.githubusercontent.com/assets/2399084/10088593/8a1aef0c-6324-11e5-8cfc-c179579b2592.png)

The strangest thing is whenever I double-click this folder, expander gets to a new column which is empty while I don't have any other folders in this path.

![image](https://cloud.githubusercontent.com/assets/2399084/10088623/d3d3dc12-6324-11e5-8058-cf472b462efd.png)

I don't know, maybe some dependencies might be missing or locale configuration is not compatible?

**Comment by ingorichter** [comment]
@erayerdin if you open the devtools from the "Debug->Show Developer Tools" menu, do you see any errors in the console output? Can you attach the output to this issue? Thanks.

**Comment by erayerdin** [comment]
I actually removed KDE and installed XFCE to my Linux distribution. Now it works well, it must be an issue about KDE.

**Comment by joepie91** [comment]
I have just found the solution to this issue, while I was in the process of describing my own issues. I have `export LC_ALL=C` in my `.bashrc` to deal with a bug in another application, but this apparently sent Brackets crazy. The issue started manifesting after a reboot.

Unsetting the variable resolved the issue - this should probably be looked into anyway, though. The mode of failure here is very strange.

The original post that I was writing is below:

-----

* __Platform:__ openSUSE 13.1, x86_64, XFCE
* __Brackets version:__ Release 1.4 experimental build 1.4.0-16380 (release 273804eb3)
* __Brackets build timestamp:__ Mon Jul 27 2015 06:20:50 GMT+0000
* __Package version:__ 1.4-1.1 (home:robert_munteanu) / 1.4-2.1 (home:FunkyPenguin)
* __Installation source:__ [home:robert_munteanu](https://software.opensuse.org/ymp/home:robert_munteanu/openSUSE_13.1/brackets.ymp?base=openSUSE%3A13.1&query=brackets) / [home:FunkyPenguin](https://software.opensuse.org/ymp/home:FunkyPenguin/openSUSE_13.1/brackets.ymp?base=openSUSE%3A13.1&query=brackets)

I'm currently also experiencing this issue. The following are the symptoms of @erayerdin that I am also experiencing:

* UTF-8 error on "Getting Started/index.html"
* Not displaying any files for a project

I am also experiencing the following:

* Brackets seems to be unable to either read or write to `.config/Brackets/brackets.json` - it ignores all settings, and doesn't retain anything either. The same goes for `state.json` - the developer tools console indicates that it couldn't read `state.json` and thus trashed it: `Brackets has recreated the unreadable preferences file /home/sven/.config/Brackets/state.json. You may refer to the deleted file in trash in case you need it!! `

Extensions are loading correctly, but are of course completely confused as they can't see their corresponding configuration (so WakaTime asks for an API key, and so on).

The following symptom of @erayerdin is one that I __cannot__ reproduce:

* Seeing folders but not files for a particular project. I've even `chmod 777`ed a project folder to test, but cannot reproduce it. It still won't show me anything in the folder/file list.

Things I've tried:

* Reinstalling the Brackets package.
* Updating to a newer Brackets package from a different vendor (both user repositories, see above)
* Removing `brackets.json` (after making backups, of course).
* Removing `state.json`.
* Removing both.
* Removing the entire `.config/Brackets` folder.
* Running a full `fsck` on my entire system.
* Rebooting system.
* Exiting all other GUI applications on my system.

None of these have solved the issue, and I have no idea how to proceed - Brackets is fairly critical to me, so this is a rather problematic situation. Worth noting that I don't run KDE, but XFCE - given that switching to XFCE supposedly fixed it for @erayerdin, this seems to indicate that it's not tied to any specific desktop environment.

An image of the console output is attached (after removing the `.config/Brackets` folder, so without any extensions installed). The following is my locale configuration:

![selection_440](https://cloud.githubusercontent.com/assets/1663259/10419410/7fc898b4-7077-11e5-9b32-377c0f7a1874.png)

**Comment by erayerdin** [comment]
Thanks for further debug @joepie91. :)
