### ISSUE TITLE
feature: close split view automatically

### ISSUE THREAD

**Issue by zaggino** [adobe/brackets#11746]
steps:
1) open preferences file
2) split view opens
3) click to close the `brackets.json` in the right pane, nothing else is remaining in the right pane

i believe, that the split view should now close automatically, given it was also automatically opened

**Comment by petetnt** [comment]
Makes sense in the `preferences` scenario, I think that the preferences split view should be more isolated anyway. Auto-closing the panel when it's possible to modify the views while the preferences are open is a bit tricky too. Consider something like this:

1. Open preferences file
2. Split view opens
3. Drag another file to right panel
4. Close `brackets.json` -> Right view should stay open right?

But what if

4. Drag the file back to left panel
5. Close `brackets.json` - nothing stays in the right panel but it shouldn't auto close as it has been "*dirty*" - right?

**Comment by zaggino** [comment]
Well, I'd implement it in a way that if split-view was automatically opened (forced on me) it also should automatically close. If it was opened manually, it should never auto-close. I don't really like split view and how it's forcing itself anytime I want to change something in preferences.

**Comment by petetnt** [comment]
This was added in #11749 right?
