### ISSUE TITLE
Opens Slowly and removal of 'Getting Started' section

### ISSUE THREAD

**Issue by akash-vartak** [adobe/brackets#11741]
I am running Window 10 on Lenovo S510P.

Release 1.1 build 1.1.0-15558 (release ea908cae5) 
build timestamp: Thu Dec 18 2014 10:23:10 GMT-0800

Brackets takes about 2 full minutes to start.

The sequence of Brackets startup is as follows:
![screenshot 7](https://cloud.githubusercontent.com/assets/8259599/10108134/e2d03f9a-63dc-11e5-9eca-9ca7a91f5475.png)
![screenshot 8](https://cloud.githubusercontent.com/assets/8259599/10108136/e2d2f960-63dc-11e5-8096-c978777adeb3.png)
![screenshot 9](https://cloud.githubusercontent.com/assets/8259599/10108135/e2d0831a-63dc-11e5-9cee-320e3a3e649e.png)
![screenshot 10](https://cloud.githubusercontent.com/assets/8259599/10108137/e2f89d32-63dc-11e5-8cc7-8feff5908bcf.png)

Additionally I request you to remove the 'Getting Started' section once a file is opened or a workspace is open/loaded. I have shown the section:
![screenshot 11](https://cloud.githubusercontent.com/assets/8259599/10108179/16a54a9a-63dd-11e5-8146-b5cdb3a76b67.png)

**Comment by abose** [comment]
Could you update the latest version of brackets? You can download the latest version from http://brackets.io/ .
