### ISSUE TITLE
Errors when building brackets 1.4 under linux when using linux-1547 of brackets-shell

### ISSUE THREAD

**Issue by artynet** [adobe/brackets#11753]
Hi folks,

as describer in topic, I get a lot of output errors when building the exact hash of the 1.4 release with the usual branch of brackets-shell for linux (linux-1547) usign CEF-1547. Have I missed something or not ? Has something changed in the meanwhile ?

Kind Regards, Arturo

**Comment by artynet** [comment]
sorry guys, much "ado" about nothing. A fresh clone of the brackest-shell repo did the trick. I was able to build the stable release of brackets 1.4 with the linux-1547 branch. I was wondering, any news about using CEF-2371 with linux ? Is still the work in progress or not ?

          Regards, Arturo

**Comment by abose** [comment]
Work in progress!  In the sense that no one is actively looking into the issue.
We have requested help from Linux community members for a while now to fix the Linux shell related issues. You too are welcome to contribute to that effort :+1: 
https://github.com/adobe/brackets-shell/pull/503

**Comment by artynet** [comment]
ok, thank you. I'll take a look too into the CEF-2371 work. Closing current issue ;)
