### ISSUE TITLE
Opening multiple brackets in Windows 8

### ISSUE THREAD

**Issue by vjkumarsw** [adobe/brackets#11750]
I am not able to open multiple bracket sessions in Windows 8.
In my previous installation in Windows 7 I would open brackets with one folder. 
I would right click on the Brackets icon in the toolbar and I would click the Brackets exe and would get a new instance of brackets. This helped me to look at 2 folders which was very convenient to copy contents from different files in the second folder to the files in the working folder.
This functionality has disappeared in Windows 8. Any ideas about how to open multiple bracket sessions?

**Comment by petetnt** [comment]
This done in adobe/brackets-shell#524 and then later reverted in adobe/brackets-shell#534, so it will be back as it used to be before 1.5. 

I have an issue open for Improved Windows Taskbar integration in #11504 if you are interested or know someone who might be.

**Comment by vjkumarsw** [comment]
If I am understanding you correctly, the problem is fixed in shell#534.
I have no idea about how to gain access to this version. 
I downloaded the version from the web.
I do not have Linux and only have the windows 8 environment.
Any help is appreciated. Thanks.

**Comment by vjkumarsw** [comment]
I had a  Brackets.Sprint.37.msi  version (which I used in the WIndows 7 installation).
I uninstalled the latest  Brackets.1.4.Extract.msi which I had recently installed in Windows 8 and installed the .37 version which gives the multiple brackets sessions. Only annoyance I have to live with now is the brackets prompting me ( every time I open it) to upgrade to the new 1.4 version.
I hope some one improves the 1.4 version to reinstate the old multiple brackets sessions behavior.

**Comment by petetnt** [comment]
@vjkumarsw oh yeah, sorry about that: the version that with the revert isn't actually released yet, it will be out soon-ish.

Meanwhile, you can build `brackets-shell` from the source if you want to try it out:

https://github.com/adobe/brackets-shell/wiki/Building-Brackets-Shell

**Comment by abose** [comment]
Brackets 1.5 to be released this week/next will fix this. Closing.

**Comment by fischgeek** [comment]
Excited to see this update! Thanks for addressing this issue.
