### ISSUE TITLE
.tern-project file

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#11754]
Does Brackets support it?
Or do I need an extension like https://github.com/MiguelCastillo/Brackets-Ternific?
I would like to enable the angular and node modules for my works.

**Comment by ficristo** [comment]
@MiguelCastillo maybe you can help me?

**Comment by MiguelCastillo** [comment]
@ficristo Brackets does not support .tern-project, so if you want to customize those you will need something external like ternific.  I have not enabled the angular module so I couldn't tell you how well it work.  However, the node module works pretty well.

I would be interested to know how the angular modules works out for you.  I would suggest opening up an issue with ternific if you encounter any issues.

**Comment by abose** [comment]
@ficristo If this is not something brackets can fix, please close the issue when the question gets answered.

**Comment by ficristo** [comment]
@MiguelCastillo Thank you for the answer.
@abose When I read that tern is integrated in Brackets I was expecting it could read a .tern-project file.
I don't know the architecture, but I think it is something to integrate in the core.
My specific need was answered so I'll close this issue.

**Comment by abose** [comment]
I am not very well-versed with the tern-integration with brackets :sweat_smile: 
Suggested to close the issue to keep the open issues tracking in check :)
