### ISSUE TITLE
Look likes Maverick on El Capitan 

### ISSUE THREAD

**Issue by AlvaroJeanpier** [adobe/brackets#11752]
When i installed brackets on OS X El Capitan, the appearance changed like OS X Maverick...

![captura de pantalla 2015-09-27 a las 10 08 04 p m](https://cloud.githubusercontent.com/assets/13040276/10127268/8ba23424-6564-11e5-8fe7-b952649a9bf9.png)

**Comment by petetnt** [comment]
This is fixed in version 1.5. which should be out soon.

**Comment by abose** [comment]
fixed in 1.5 to be release this/next week. closing.

**Comment by AlvaroJeanpier** [comment]
Thank's for the answer...
