### ISSUE TITLE
Dilato: Core: The new created file under the Working Files can't be renamed/showed in File Tree/Showed in Explorer with no message, if it isn't saved.

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#11763]
Steps:
1. Install and launch the Brackets
2. Click File menu and click New, then user would create a file under the Working Files
3. Right click on the file, click Rename/Show in File Tree/Show in Explorer

Result: There is no response after click these, if the file is not saved
Expect: There is an error message pop up to prompt user to save the file
![noresponse](https://cloud.githubusercontent.com/assets/2245179/10196484/abf4409c-67c5-11e5-8724-a8c345d41705.png)

**Comment by manoharprabhu** [comment]
Hi,
I am currently working on this bug, and I am having trouble phrasing the error message that needs to be shown.
Right now, it looks like this:
![image](https://cloud.githubusercontent.com/assets/2051859/10811249/e6c3e7b0-7e2f-11e5-9c3f-273a6a4492b3.png)

Is this fine?

**Comment by abose** [comment]
@manoharprabhu Thanks For contributing to brackets.
Please raise a Pull request with the fix. Community members would help you in reviewing strings used in brackets once you raised the PR :+1:

**Comment by mansimarkaur** [comment]
I want to start contributing to brackets. Is this issue still open for working? If yes, please help me get started.

**Comment by ficristo** [comment]
If @manoharprabhu will not work on this anymore, yes.
Personally I'd prefer to simply disable the menu items than showing a message, maybe you can check other code editor like Notepad++ or Sublime and see what they do.

**Comment by manoharprabhu** [comment]
@mansimarkaur can go ahead and contribute the fix for this issue.
Sorry, I got caught up in a lot of stuff and couldn't continue contributing.

**Comment by mussakhojayeva** [comment]
is this issue still valid?
i would like to work on fixing it, if it is possible

**Comment by ficristo** [comment]
Maybe I closed the related PR a bit hastily...
@petetnt was it ready to be merged but lacked only tests?
Maybe we could merge as is and add some tests in a different PR.
WDYT @petetnt?

**Comment by petetnt** [comment]
@ficristo sounds good to me

**Comment by ficristo** [comment]
@petetnt could you double check and eventually merge?
@mussakhojayeva are you willing to write tests for this feature? (I need to wait for the merge before)

**Comment by petetnt** [comment]
See the follow up in #13134, fixed in #12806
