### ISSUE TITLE
Brackets won't start on Mac / El Capitan 

### ISSUE THREAD

**Issue by Vlasterx** [adobe/brackets#11768]
Hello, I have one really persistent issue with brackets on Mac. Brackets won't start no matter what I do. It only loads  main panel and stays there. I have tried to uninstall it, tried a version without Extract and nothing helps. Is there any chance to fix this since Brackets has become my main programming editor?

![Stuck on this screen](http://i.imgur.com/MJVaFJb.png)

**Comment by fplgusmao** [comment]
This happens to me too. Probably because of El Capita. Also, notice the menu bar with the old, pre-Yosemite look.

I actually managed to use it for a while before this happened. Still, the menu bar had that look already and Cmd+F was causing it to toggle fullscreen mode, which is quite frustrating as you can imagine

**Comment by petetnt** [comment]
The Yosemite-look thing has been fixed in the latest `brackets-shell` which is shipping with 1.5. very soon, however I think is that this is the first time of someone reporting Brackets not working at all on El Capitan.

**Comment by ryanstewart** [comment]
Are others seeing this behavior? I don't have El Capitan yet so I can't test it myself.

**Comment by munkacsimark** [comment]
I have El Capitan updated from Yosemite, and Brackets works for me.

**Comment by jsrothwell** [comment]
Updated to El Capitan this morning. Brackets is hanging on start

**Comment by petetnt** [comment]
For those having problems, have you tried [clearing out the cache folder](https://github.com/adobe/brackets/wiki/Cache-Folder)? (Backup the stuff before deleting them though).

**Comment by jsrothwell** [comment]
I got it working by removing the cef_data folder, brackets.json and state.json

**Comment by Vlasterx** [comment]
Clearing Cache didn't help.

**Comment by Vlasterx** [comment]
I have tried to update Chrome today and with Chrome update, Brackets worked as well on El Capitan.

**Comment by rroshan1** [comment]
Closing as this issue seems to be fixed.
Workaround- Clear cache + Chrome Update.
Please feel free to reopen if needed.

**Comment by meGenius** [comment]
I'm having the same problem as well.
El Capitan fresh install and Brackets won't start. Tried everything mentioned here but it also don't help. @Vlasterx, by any chance was the whole OS becoming non-responsive when you were having the issue with Brackets? For me, everything works fine until I try to run Brackets, and then non of the apps would work. It seems to be a bigger problem than just Brackets, definitely Apple has screwed something up, but just wanted to confirm whether you were getting the same behavior I'm getting right now.

**Comment by Vlasterx** [comment]
@meGenius - It also happened to me just after upgrade, but I was unable to start anything related to Chrome or Chromium. Clearing cache didn't help, but I got an idea to uninstall both Brackets and Chrome, then downloaded new version of Chrome, which worked and then installed Brackets, which also worked. Try it as well and if you succeed, post it here as well for people with similar problems.

**Comment by meGenius** [comment]
Well, @Vlasterx, I actually decided to reinstall the whole OS X thing. I couldn't use Adobe Illustrator as well, so I thought let's just get rid of this altogether. I reinstalled OS X 10.11 and now everything is fine. Note that so far I didn't try to install Chrome as my primary browser is always been FireFox and I install Chrome only for testing purposes. I'm not sure if installing Chrome will break Brackets again thus I'm not gonna do this for now.

**Comment by Sergio1967** [comment]
me preguta siempre por abrir el programa como si fuese la primera vez, cada vez q lo abro

**Comment by Sergio1967** [comment]
Aptana ist better!

**Comment by 79tom** [comment]
Hello, I have the same problems. Starting Brackets leaves me with grey window and the app stucks, even CMD-Q doesn't work anymore.

I tried all mentioned here but nothing works.

Has anyone a solution?

**Comment by kenzo44** [comment]
Running OS X 10.11.2El Capitan and facing no problems with Brackets. 

A clean install of Brackets should help fix the problem.

**Comment by OctoberBloom** [comment]
I have the same problem with Brackets 1.12 on macOS Hight Sierra. It just stopped working. I did't do updates and did't install new applications. I have a gray screen and the menu responds only to closing  and minimizing the window. I was trying to remove the new version of the old version, clean up the cache and even updated the system again. Still not working. Please, help.

**Comment by fepe89** [comment]
Sry for reply after all those years. Came by (google search) with same problem and just wanted to leave my fix: in my case there was a problem with the local folder synced (Sourcetree) at the moment i started the update. Had same issues as described here. Workaround was to close Sourcetree and all open folders. After i've done that, brackets started as supposed.
