### ISSUE TITLE
easier row selection

### ISSUE THREAD

**Issue by matsimental** [adobe/brackets#11765]
i have been using the brackets software for windows for a day now. it is great! just one thing keeps bugging me, it is difficult to see where the row-count bar ends and the text editing area starts. it makes it hard to accurately select blocks of text at exactly the start of the row. my suggestion is to either widen the area from where i can "start" selecting, that is, i can click all the way over the row number and start dragging to select. often editing softwares will mirror the arrow cursor in a situation like this. OR keep the row-count bar slightly different color than the text area for easier aiming. thanks again for a otherwise amazing software!

**Comment by stamminator** [comment]
Bump.

**Comment by busykai** [comment]
@matsimental, @stamminator I believe if you search through the themes, you could find the ones that make the line start perfectly visible. To install themes, *File -> Extension Manager -> Themes tab*. To browse through the themes, use [this site](http://brackets-themes.github.io/). You can also [create your own](https://github.com/adobe/brackets/wiki/Creating-Themes).

**Comment by petetnt** [comment]
There is also an extension called [Brackets Select Lines](https://github.com/talmand/Brackets-Select-Lines) that adds some features to the line numbers (such as clicking a number to select a row), which could help the situation.

**Comment by matsimental** [comment]
the Select Lines extension was exactly what i was looking for! thank you petetnt and especially talmand for saving my sanity!

**Comment by busykai** [comment]
thanks @petetnt for the right hint! closing the issue.
