### ISSUE TITLE
Dilato: Win/Mac: Core: Code Folding extension cannot be installed in the current version build.

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#11761]
![code-foldingerror](https://cloud.githubusercontent.com/assets/2245179/10192837/c19c3080-67b1-11e5-9e51-a9868c3777fa.png)
1. Launch Brackets on Win/Mac system.
2. Open Extension Manager.
3. Search for "Code Folding".

Actual Result: This extension cannot be installed in the current version build.

Expect Result: This extension should can be installed in the current version build.

**Comment by petetnt** [comment]
Code Folding has been integrated to Brackets since version 1.4. so not being able to install the extension should be expected, right?

**Comment by abose** [comment]
Code folding extension cannot be installed in brackets 1.3+ as we ship it with our default extensions. This is as expected. Closing.
