### ISSUE TITLE
Brackets window appears with old traffic lights on OS X El Capitan

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [adobe/brackets#11774]
![](https://i.imgur.com/XVPiGMY.png)

**Comment by CoWinkKeyDinkInc** [comment]
![](https://i.imgur.com/OEsMTgq.png)
The green button and full screen button still work as intended before Yosemite/Mavericks.

**Comment by petetnt** [comment]
This has been fixed in the latest `brackets-shell`, shipping with 1.5. very soon

**Comment by abose** [comment]
Closing as fixed in 1.5
