### ISSUE TITLE
Changing from css style hinting to HTML tag

### ISSUE THREAD

**Issue by awaemmanuel** [adobe/brackets#11779]
Hello team, 

Please I need your help, I don't know how to get my editor to work right. 

I am watching a tutorial where the instructor is literarily writing css in a html file and it's converted to html tags, but I cannot get it to work.

Like div.someClass#SomeID --> <div class="someClass" id="someID"></div>

Thanks for your help. I have tried to research on my own, but it's all in vain.

**Comment by petetnt** [comment]
Sounds like [Emmet](http://emmet.io/) to me. The extension you are looking for is called [brackets-emmet](https://github.com/emmetio/brackets-emmet) and it can be found via the extension manager!

**Comment by awaemmanuel** [comment]
Hi Petetnt, 

That's right. I just figured that out and then came here to see that you commented the same. Thanks a lot for your response.

I can close this now.
