### ISSUE TITLE
Black window title with latest brackets-shell

### ISSUE THREAD

**Issue by FezVrasta** [adobe/brackets#11770]
I have compiled the latest bracket-shell release (https://github.com/adobe/brackets-shell/commit/1dec5811bf295f0e668f04e2359e22d87f723513) on my OS X El Capitan.
I've linked to it the files of Brackets 1.6 dev.

The window title is black but it should be white:

![image](https://cloud.githubusercontent.com/assets/5382443/10262646/c99aab96-69d1-11e5-981e-a7bab41f622b.png)

**Comment by ficristo** [comment]
@nethip I think this is fixed with the latest release

**Comment by ficristo** [comment]
I close this since I cannot reproduce.
