### ISSUE TITLE
CMD=F or CTRL-F switches to Window > Enter Full Screen

### ISSUE THREAD

**Issue by geooogle** [adobe/brackets#11782]
Release 1.4 build 1.4.0-16380 (release 273804eb3) 
build timestamp: Sun Jul 26 2015 23:20:45 GMT-0700

On a mac anyway, when you hit CMD-F you usually get the Find bar (obviously.) But after about 20-50 uses, CMD-F acts like Window > Enter Full Screen. Even the Symbol for CMD-F is shown in the menu item (Enter Full Screen).

When bug exists:

![screen shot 2015-10-06 at 1 32 49 pm](https://cloud.githubusercontent.com/assets/6183510/10316749/ee2a359e-6c2e-11e5-9ebf-171b02157d28.png)
![screen shot 2015-10-06 at 1 33 09 pm](https://cloud.githubusercontent.com/assets/6183510/10316751/f2fc43d2-6c2e-11e5-9d42-db0bc6ae29cc.png)

After restarting brackets:
![screen shot 2015-10-06 at 1 33 27 pm](https://cloud.githubusercontent.com/assets/6183510/10316758/fc0a4e10-6c2e-11e5-845b-3b9c795e0168.png)
![screen shot 2015-10-06 at 1 33 33 pm](https://cloud.githubusercontent.com/assets/6183510/10316765/0057aee0-6c2f-11e5-9872-8b787eff760f.png)

**Comment by mattbell87** [comment]
I'm on OSX Yosemite 10.10.5 with the same build as you. I can't get this bug to replicate, even if I hold down Cmd-F. What extensions do you have? (Not a brackets dev btw, just curious)

**Comment by geooogle** [comment]
This only started happening after a format, fresh install of El Capitan 10.11 (15A284) on a MacBookAir. Never on Yosemite.

Extensions:
- Brackets Git 0.14.32
- Jade (Official Plugin) 2.0.0
- JSCS for Brackets 0.7.3
- JSHint 2.2.18
- JSHint Configurator 1.1.6
- QuickDocsJS 1.6.8
- Show Recently Used Items 0.5.7

Thanks!

**Comment by mattbell87** [comment]
Out of the extensions you have installed I only have Brackets Git 14.32. You could try a fresh Brackets install (or maybe rename the ~/Library/Application Support/Brackets folder) and see if it still happens. If it does then it may be an El Captain issue!

**Comment by abose** [comment]
Once the shortcut stops working, can you go to `debug>show developer tools> console` and post the errors here?

**Comment by MiguelCastillo** [comment]
This issue started to happen to me also after i updated to El Capitan a few days ago. *No changes in extensions*. I am probably going to tale a closer look today or tomorrow as this is really disabling for me.

**Comment by geooogle** [comment]
@abose I encountered the issue just now. It occurred after CMD-R and I can now recreate the issue.

- Start brackets
- Debug > Reload with Extensions (may have to do this more than once)
- Test for Window > Enter Full Screen and check if CMD-F shortcut exists.

In any case, I reloaded without extensions and same occurred.

![image](https://cloud.githubusercontent.com/assets/6183510/10343680/fb5fdfde-6cec-11e5-9a51-5e2737d40cc1.png)

**Comment by shichongrui** [comment]
I have the same problem and closing brackets and then opening it again seems to bring back the desired find functionality with CMD-F

**Comment by MiguelCastillo** [comment]
So, I restarted brackets after I pulled from master and I have the find key binding back...  I am guessing brackets restart fixed though. Odd.  Never seen this issue before.

**Comment by breadadams** [comment]
This same issue has just started happening for me too. Randomly midday during work, after using brackets for a couple of hours. Just quit and relaunched and `cmd + F` is back to finding.

I have none of the same extensions as @geooogle

**Comment by ingorichter** [comment]
I hit the same thing last night. After restarting Brackets, it went away. But there might be something more to it, that causes this behavior. Interesting fact, is that the shortcut `CMD+F` disappears from the menu.

**Comment by geooogle** [comment]
@breadadams Did you try refreshing Brackets to see if that was the cause? It's not random as far as I can tell. 

I refresh Brackets when I need give `Brackets Git 0.14.32` a clean look at what was just pushed or pulled. Then the frustration begins.

**Comment by breadadams** [comment]
@geooogle Do you mean a `cmd + R` refresh? If so, yeah - tried that, but no change. Like I said, only quitting and opening Brackets again _fixed_ the issue. Not ran into again since then.

**Comment by MiguelCastillo** [comment]
@breadadams yup, that did it for me as well. Quit then re-open.

**Comment by geooogle** [comment]
@breadadams What I mean is:

- to cause the problem use `cmd + R` (may need to do more than once)
- to fix the problem, yeah, restart Brackets

As far as I can tell, the problem spawns from `cmd + R` OR `option + cmd + R`

**Comment by breadadams** [comment]
@geooogle AHA! Sorry, completely mis-read you. That is the issue, if you press `cmd + R` then open the *Find* menu item, you see the shortcuts all start blinking/flashing and finally `cmd + F` disappears from the main Find option.

**Comment by nethip** [comment]
Phew! Finally fixed it with this [PR](https://github.com/adobe/brackets-shell/pull/537). The fix is not documented and it took a while for me to figure out what is going on.

Apple mandates all applications to have "Enter Full Screen" menu which executes "toggleFullScreen:" and target as nil. Now if applications don't do that, they are going to add this menu to menubar.

So added the a new menu "Enter Full Screen" with shortcut as Ctrl-Cmd-F. This will make sure the OS does not go about randomly assigning shortcuts to "Enter Full Screen".

Another interesting observation is the fact that, OS automatically substitutes the language equivalent of "Enter Full Screen" for the current system language, provided we have the resource files for that languages. So in our case, this menu entry is automatically translated in cases of french and jp and we have resource files for that. Unfortunately for other languages the menu is going to be in english which is the same case with "Minimize" and "Zoom" menus. It is really weird!

Now what is also weird is the fact that this behavior is found only in El Capitan and not on Yosemite.

@ingorichter @abose @madanbn Will you be able to review this PR? Let us target this for 1.5. I have not tested this with Mountain Lion. Hopefully it should work just fine there as well.

**Comment by Seakla** [comment]
Another quick workaround while we wait for 1.5 to be released:

If you don't use the Reload shortcut all that much, you can temporarily override it in your key bindings. Process is outlined here: https://github.com/adobe/brackets/wiki/User-Key-Bindings

I used "Cmd-R": "" which removes the shortcut entirely for the moment.

**Comment by abose** [comment]
1.5 will be released today :)

**Comment by geooogle** [comment]
@nethip Thanks for the fix!

**Comment by nethip** [comment]
@geooogle No problem ! We have fixed all full screen related issues on El Capitan. Please install 1.5 and let us know if you are still facing the issue.
