### ISSUE TITLE
Ruby Support

### ISSUE THREAD

**Issue by cbuchert** [adobe/brackets#11785]
I love Brackets. I use Ruby. I'd love to have Ruby support (ie. code completion and not flip out with rspec).

**Comment by abose** [comment]
rb and erb files account for .5% of file opens in brackets(aug-sep15 health data). Marking for needs review. 
End to end ruby workflows are better supported by extensions. 
Could you tell us more about what functionalities you would expect for ruby support from brackets?

**Comment by cbuchert** [comment]
You know, you're totally right about it being an extension thing. I'm
totally barking up the wrong tree here. I'll see if I can throw something
together. I guess I'm still always looking for someone else to do it for me
;)

Chris.

**Comment by abose** [comment]
:cool: Use brackets slack channel @ https://brackets.slack.com/messages/general/ if you need any help from the community :+1:

**Comment by abose** [comment]
Closing as extension idea.
