### ISSUE TITLE
Can't intall on Debian Mint

### ISSUE THREAD

**Issue by garrett85** [adobe/brackets#11791]
When I try to install I get the following error.

Error: Dependency is not satisfiable: libgcrypt11 (>= 1.4.5)

**Comment by hlepesant** [comment]
Same thing on debian 8.2


$ sudo dpkg -i Brackets.Release.1.4.64-bit.deb
Sélection du paquet brackets précédemment désélectionné.
(Lecture de la base de données... 208737 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de Brackets.Release.1.4.64-bit.deb ...
Dépaquetage de brackets (1.4.0-16380) ...
dpkg: des problèmes de dépendances empêchent la configuration de brackets :
 brackets dépend de libgcrypt11 (>= 1.4.5) ; cependant :
  Le paquet libgcrypt11 n'est pas installé.

dpkg: erreur de traitement du paquet brackets (--install) :
 problèmes de dépendances - laissé non configuré
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.13-1) ...
Des erreurs ont été rencontrées pendant l'exécution :
 brackets

**Comment by petetnt** [comment]
`libcrypt11` has been purged and replaced with `libcrypt20`. There's a PR tracking updating the libcrypt here: adobe/brackets-shell/pull/501.

Until that gets merged, see adobe/brackets/issues/10255 for workarounds.

**Comment by fizzvr** [comment]
> libcrypt11 has been purged and replaced with libcrypt20. :-1: 



> Until that gets merged, see adobe/brackets#10255 for workarounds. :+1:

**Comment by ficristo** [comment]
Closing as a duplicate of https://github.com/adobe/brackets/issues/10255
