### ISSUE TITLE
Suggestion about "File Info to Clipboard" (author: Vince Malone)

### ISSUE THREAD

**Issue by rdmauser** [adobe/brackets#11790]
Love being able to grab the file names especially for uneditable files such as MP3's and MP4's. The problem is that both path options go all the way back to the drive root. I would really love it if there was a way to use the Project Directory as the path starting point, rather than the drive root. 

Even without this option "File Info to Clipboard" is a MUST option. Thanks for creating it Vince.

**Comment by abose** [comment]
did you intended to register this issue in the extension author's repo at https://github.com/VinceMalone/Brackets-FileInfoToClipboard ?

**Comment by rdmauser** [comment]
I just clicked on what looked to be the fastest way to make a  suggestion. 
On Oct 7, 2015 2:48 PM, Arun Bose <notifications@github.com> wrote:did you intended to register this issue in the extension author's repo at https://github.com/VinceMalone/Brackets-FileInfoToClipboard ?

**Comment by abose** [comment]
Brackets does not own or control any of the extensions. Please log the issue in the extension author's repo at https://github.com/VinceMalone/Brackets-FileInfoToClipboard . Closing.
