### ISSUE TITLE
Find Keyboard Shortcut Disabled, Can't Override

### ISSUE THREAD

**Issue by curiousaaron** [adobe/brackets#11797]
I just installed OS X El Capitan and the Brackets Beautify extension, so I'm not sure which (if either) of those is to blame, but... my keyboard shortcut for "Find" has now been changed to toggle full screen in OS X. 

I have accessed the User Key Map file and followed the directions on the documentation page to override and restore Cmd-F as the Find shortcut, but to no avail. It just tells me that command doesn't exist no matter what configuration I use (find, find.find, edit.find, etc).

I use this keyboard shortcut about once a minute, so Brackets is unusable to me without it. Maybe the issue is mine and not the software's, but any help would be appreciated.

**Comment by petetnt** [comment]
Same symptoms as  #11782

**Comment by abose** [comment]
this will be fixed in 1.5 due to be out in a few days.
