### ISSUE TITLE
Brackets compatibility issue with OS X El Capitan

### ISSUE THREAD

**Issue by Phacometer** [adobe/brackets#11794]
As the title suggests, there is a problem with OS X El Capitan compatibility. When I open Brackets in El Capitan, the title bar displays the OS X Mavericks style title bar, with the "full-screen" button to the right. I don't know why this happens. Could someone give a suggestion? Thanks!
<img width="1276" alt="index_html__my_journal__ _brackets" src="https://cloud.githubusercontent.com/assets/11540657/10381018/ff706416-6ded-11e5-8411-f5477ebd32d2.png">

**Comment by busykai** [comment]
It's fixed in the current master of adobe/brackets-shell, will be included in 1.5. See  #11774.

I'm closing this one.
