### ISSUE TITLE
Core: "Font Size" field on themes settings dialog could accept any non-ASCII characters and any number for font size.

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#11801]
1. Launch Brackets
2. Click View->Themes
3. Input some non-ASCII characters into the "Font Size" field or input small/large number.
   such as "ДЁЙФ龘龜び>_$#@&*ぷ龝" or 01px/1000000px

Result: "Font Size" field could accept any non-ASCII characters and any number for font size.

Expect: The "Font Size" field could add some control to forbid the incorrect format data.
![1](https://cloud.githubusercontent.com/assets/2245179/10411156/1a4b204e-6f8f-11e5-9f48-e0b505aad3c5.jpg)

**Comment by jerrak0s** [comment]
If your font size input field for your theme is non-numeric, font is set to default that is 12px

**Comment by MiguelCastillo** [comment]
We restrict the input when setting the value.  Perhaps we should add the pattern to the input field as well to only allow numbers and optionally the units.

https://github.com/adobe/brackets/blob/master/src/view/ViewCommandHandlers.js#L303

**Comment by nyteksf** [comment]
Hello. If it's still possible, I'd like to take this issue on, please.

**Comment by zaggino** [comment]
Go ahead @nyteksf , this issue still hasn't been solved.

**Comment by 99M8** [comment]
Hello! Has this issue been resolved?

**Comment by Zhanxin** [comment]
Verified as fixed.
![forbid](https://user-images.githubusercontent.com/2245179/35957293-db445ee2-0cd5-11e8-8869-2368ce307f42.png)
