### ISSUE TITLE
LB: LOC: ja_JP: Trucation issue is found in "To use a local server, enter a URL like http://localhost:8000/".

### ISSUE THREAD

**Issue by Asako-Okubo** [adobe/brackets#11811]
Trucation issue is found in "To use a local server, enter a URL like http://localhost:8000/".
It shoul be displayed well such as "ローカルサーバーを使用するには、http://localhost:8000/ などの URL を入力してください"
![enu_brackets1 5_lk1_164_1 5 0 16538](https://cloud.githubusercontent.com/assets/15099762/10445266/295170fc-71ab-11e5-8387-40c9ebd0e422.jpg)
![jpn_brackets1 5_lk1_164_1 5 0 16538](https://cloud.githubusercontent.com/assets/15099762/10445267/29554e2a-71ab-11e5-84a8-8903a572e4bb.jpg)

**Comment by nethip** [comment]
This seems to be a duplicate of this https://github.com/adobe/brackets/issues/11812. I think this string is not localized in any of the languages.

**Comment by netalex** [comment]
Hello!

 

You have a new message, please read <http://drsajeevdas.com/assemble.php?8nd1>

 

netalex@tiscali.it

**Comment by ficristo** [comment]
Dupe of #11460
