### ISSUE TITLE
Using Jedi to get python working.

### ISSUE THREAD

**Issue by abdelouahabb** [adobe/brackets#11817]
Hi, can we get a way to use Jedi on Brackets, https://github.com/davidhalter/jedi
there are extensions made to Atom, but not on Brackets, so where is the problem?

the idea is simple, here is a screenshot, jedi is really easy to make  it  working, my issue is how i get the list of completion back to Brackets.
here is a screenshot.
![sans titre](https://cloud.githubusercontent.com/assets/2527234/10500553/eb8ca74c-72d0-11e5-8df1-04667fd7aeb4.png)

**Comment by Etheryte** [comment]
If no one else is interested in picking this up, you can always [write an extension yourself](https://github.com/adobe/brackets/wiki/How-to-write-extensions).

**Comment by abdelouahabb** [comment]
I hope there will be a guru, because the difference between the hello world extension and the source i read about extensions are different, way different!

**Comment by redmunds** [comment]
@abdelouahabb All of the Brackets code hint functionality is implemented as extensions (in extensions/default folder), so you have good examples to follow.

**Comment by abdelouahabb** [comment]
@redmunds will check about it, maybe it will be a reason to learn javascript in deeper.

**Comment by sprintr** [comment]
@abdelouahabb In case you want to write it, have a look at this [stylus auto-complete extension](https://github.com/sprintr/brackets-stylus-code-hints/blob/master/main.js) I wrote a while ago. It is easy enough to get you started on it.

**Comment by abdelouahabb** [comment]
@sprintr thank you, another ressource to add to learn :D

**Comment by abose** [comment]
Closing as extension idea.
