### ISSUE TITLE
1.5 breaks Markdown Preview

### ISSUE THREAD

**Issue by couzteau** [adobe/brackets#11819]
When trying to preview a markdown doc using the extension below, the preview panel doesn't open and the following is logged to the console:
~~~~~
Uncaught ReferenceError: baseUrl is not definedVM466:3 (anonymous function)thirdparty.min.js:556 n.accessthirdparty.min.js:557 n.fn.extend.attrmain.js:149 _loadDocmain.js:278 _setPanelVisibilitymain.js:318 _toggleVisibilitythirdparty.min.js:557 n.event.dispatchthirdparty.min.js:557 r.handle
~~~~

https://github.com/gruehle/MarkdownPreview

**Comment by couzteau** [comment]
Key extensions should be tested and extension owners should be notified.

**Comment by petetnt** [comment]
Filed PR upstream, `gruehle/MarkdownPreview/pull/88`

**Comment by abose** [comment]
Closing as not core brackets issue.
