### ISSUE TITLE
LOC: Japanese: The CC-BY 3.0 Unported link doesn't redirect to the Japanese page

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#11814]
Steps:
1. Launch the Brackets
2. Click Help->About Brackets
3. Click the link "CC-BY 3.0 Unported"

Result: The link would redirect to the English page
Expect: It should redirect to the Japanese page
Not reproduce on French
![linknotlocalized](https://cloud.githubusercontent.com/assets/2245179/10453925/112f25a4-71e3-11e5-8a87-56b1c2d21f02.png)

**Comment by Blackweda** [comment]
Took care of it.

**Comment by Zhanxin** [comment]
Verified as fixed. It links to https://creativecommons.org/licenses/by-sa/2.5/deed.ja now
