### ISSUE TITLE
Update to latest release(1.5) removes all extensions in previous installations

### ISSUE THREAD

**Issue by Manish-Giri** [adobe/brackets#11829]
I downloaded and updated to the latest release (1.5) just a few seconds ago. I had release 1.4 prior to this, and had carefully selected and installed more than 20 extensions from the in-built extension manager. Upgrade to the latest release removed all those extensions, which have to be re-installed manually again.

OS - Windows 7 64 bit.

**Comment by abose** [comment]
Thanks for reporting this. We have not heard of similar issues. Could be a one off issue. Keeping this open for some time to see if anyone else is affected.

**Comment by iegik** [comment]
Linux x64: Have to disable all installed extensions, remove ~/.config/Brackets folder, restore ~/.config/Brackets/extensions and enable all installed extensions

**Comment by maxime-beguin** [comment]
Same thing as @Manish-Giri but looking at user files (extensions and configuration), everything was there but not read by Brackets. I had to remove Brackets 1.4 and then install Brackets 1.5. User files are now read, everything works fine.

Windows 7 64 bits.

**Comment by hussainb** [comment]
Just wanted to share my experience while upgrading.
Before installing 1.5, I uninstalled the 1.4 so that I would get a clean start, but after installing 1.5, I found my extensions intact and the user folder present under the extensions folder.

**Comment by abose** [comment]
Closing as the release has been out for a while now.
