### ISSUE TITLE
MAC OS X - Can't open the dmg file

### ISSUE THREAD

**Issue by ThorinDev** [adobe/brackets#11823]
https://gyazo.com/1b8d10edd17769ada98409e5f671db4b - can't open it

**Comment by abose** [comment]
Where did you download the DMG from?

**Comment by ThorinDev** [comment]
Brackets.io

**Comment by abose** [comment]
It could be a corrupt download. Please retry a fresh download.

**Comment by ThorinDev** [comment]
It worked!

**Comment by abose** [comment]
:cool:  Closing.
