### ISSUE TITLE
Save As dialog wrong position on OS X

### ISSUE THREAD

**Issue by dominik0711** [adobe/brackets#11821]
After selecting "Save As" the dialog appears from top of the window and then jumps to another position. See screenshot

![screen shot 2015-10-14 at 17 35 46](https://cloud.githubusercontent.com/assets/1011188/10488713/4aaa0e22-729a-11e5-8de9-0f52a4f7bd73.png)

The dialog should be bound to the top window bar!

This is somehow an error in `CEF` but I couldn't find the right position. Maybe you will have more luck! Please let me know if you're able to fix it!

Thanks dominik

**Comment by ceokzoo** [comment]
I tried to recreate this issue and I didn't have any success. Can you elaborate on this issue? Or is it now working?

**Comment by ficristo** [comment]
@dominik0711 can you reproduce with latest version?

**Comment by ficristo** [comment]
I have not been able to reproduce the error.

**Comment by dominik0711** [comment]
It's now fixed. So this issue can be closed.
