### ISSUE TITLE
Please add Line Height Configuration

### ISSUE THREAD

**Issue by fanjavaid** [adobe/brackets#11839]
Hello Brackets, please add line height in preferences configuration.

**Comment by abose** [comment]
Tagging @MarcelGerber

**Comment by petetnt** [comment]
There are some line height related issues which make this feature surprisingly hard to implement IIRC

I think the discussions about this begin in adobe/brackets/issues/7800 but spawl around various other issues too.

**Comment by MiguelCastillo** [comment]
They are just not doable without any sort of side effects in Brackets core at this point.  I had added it, and removed it after lots of testing and conversation with the team.  But I created an extension for if you really need the functionality.  https://github.com/MiguelCastillo/Brackets-LineStyle.  It is not published in the registry yet, but you can still install it directly from git.

@petetnt Yeah, that thread is definitely the one with the most information.  Although I vaguely recall another issue with some information as well.

**Comment by ficristo** [comment]
I close this as a dupe of #11141
