### ISSUE TITLE
The multiple cursors are on wrong position while editing HTML document

### ISSUE THREAD

**Issue by tnRaro** [adobe/brackets#11837]
The cursors go to wrong position when I press enter while having multiple cursors on HTML document.

Select like this(| is cursors): 

```html
<div>|</div>
<div>|</div>
<div>|</div>
```
and then I press enter:

```html
<div>
    |
<|/div>
<|div>
    
</div>
<div>
    
</div>
```

I using Brackets 1.5 on 64-bit Debian

**Comment by petetnt** [comment]
Cannot repeat on Windows 10 x64 or plain CodeMirror... have you tried `Debug -> Reload Without Extensions` to rule out extension issues? Otherwise it might be a Linux CEF bug too.

**Comment by tnRaro** [comment]
Oh, It is work. It seems like emmet extension issue.
