### ISSUE TITLE
[MAC] Tooltip over the corner when closed plug-in's window

### ISSUE THREAD

**Issue by christmo** [adobe/brackets#11836]
I have OS X El Capitan 10.11, when I opened the plug-in's window after see the PSD section, the tooltip of the tutorial was shown over the corner.

<img width="1440" alt="captura de pantalla 2015-10-17 a las 11 17 48 p m" src="https://cloud.githubusercontent.com/assets/291154/10562555/ca3386a8-7526-11e5-8032-665502cc170e.png">

This tooltip will not be closed.

<img width="890" alt="captura de pantalla 2015-10-17 a las 11 32 34 p m" src="https://cloud.githubusercontent.com/assets/291154/10562566/806dd8f6-7527-11e5-9c2a-5a3a0d3ba5da.png">

**Comment by abose** [comment]
The popup is brawn by extract extension, and when the extract window is closed, the help popup gets dislocated.
The  workaround is to reload brackets(press `f5`), restart brackets, or login into the extract panel.

**Comment by abose** [comment]
Extract window placement issue.
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.
