### ISSUE TITLE
Brackets won't install on Ubuntu 15.04

### ISSUE THREAD

**Issue by doug65536** [adobe/brackets#11841]
$ sudo dpkg -i Brackets.Release.1.5.64-bit.deb
    Selecting previously unselected package brackets.
    (Reading database ... 311636 files and directories currently installed.)
    Preparing to unpack Brackets.Release.1.5.64-bit.deb ...
    Unpacking brackets (1.5.0-16538) ...
    dpkg: dependency problems prevent configuration of brackets:
     brackets depends on libgcrypt11 (>= 1.4.5); however:
      Package libgcrypt11 is not installed.
    
    dpkg: error processing package brackets (--install):
     dependency problems - leaving unconfigured
    Processing triggers for menu (2.1.47ubuntu1) ...
    Processing triggers for hicolor-icon-theme (0.14-0ubuntu1) ...
    Errors were encountered while processing:
     brackets

libgcrypt11 is deprecated due to security risk. It no longer exists.

Even if I dismiss the risk, the package has been removed from Ubuntu download servers, so I can't even force install the old package.

**Comment by petetnt** [comment]
Duplicate of adobe/brackets/issues/10255, there are some workarounds and a pending PR listed in that topic too :)

**Comment by doug65536** [comment]
What a joke. Thanks, at least now I know Brackets is abandoned. Linux support is a lie. It has been almost a year and they can't fix one build dependency.

**Comment by abose** [comment]
Closing issue as this is duplicate. 
We request the help of linux community members in sorting out this issue.
