### ISSUE TITLE
Erros Brackets in Portuguese-Brazil + suggestions

### ISSUE THREAD

**Issue by benavenuto** [adobe/brackets#11840]
Hello!

My name is Luan, I am web developer and Brackets fan and would like to report some errors in the IDE in my language (Portuguese-Brazil).

I also hope they can understand me, because I do not speak English and am using Google Translate for it ;)

I will also send images of links with printscreens of errors to make it easier to understand.

ERRORS:
1 - Enable copy and paste option on the right mouse buttom | Printscreen: https://drive.google.com/file/d/0B_DPX2-a4PDxM2k4MWI5aUNpcmc/view?usp=sharing 

2 - Fix the error charset utf-8 option "copy text" in Photoshop using the "Extract is Brackets" in the cloud | Printscreen : https://drive.google.com/file/d/0B_DPX2-a4PDxUWMxVVJNbmpfcnM/view?usp=sharing

3 - Enable option cloud PSD delete directly in Brackets (option Extract is Brackets) | Printscreen: https://drive.google.com/file/d/0B_DPX2-a4PDxbDdBUHBIeWcyb3c/view?usp=sharing

4 - Differentiate color classes and tags in css (They are always blue)

Any other doubt, I am willing to respond in luanbenavenuto@outlook.com

Grateful right now!

**Comment by abose** [comment]
The images cannot be accessed due to permission issues. Could you copy and paste the image to the comment section here? You can directly paste images into github commets.

**Comment by benavenuto** [comment]
![1_copy_and_paste](https://cloud.githubusercontent.com/assets/4792134/10574877/8912be16-7637-11e5-93c0-f46a5a180639.jpg)
![2_copy_text_error_charset_utf-8_portuguese](https://cloud.githubusercontent.com/assets/4792134/10574878/89326766-7637-11e5-86b6-50a23eb76e33.jpg)
![3_tags_and_classes_blue](https://cloud.githubusercontent.com/assets/4792134/10574879/896ee1d2-7637-11e5-997e-8a6a7a3afec1.jpg)

Excuse me! But I had forgotten to release the permission of the first image in the drive ... Anyway I am providing images here this comment ...
Thanks for the help Abose.

**Comment by abose** [comment]
@nethip extract issue.

**Comment by drosendo** [comment]
I confirm this issue, still no fix on this?

**Comment by abose** [comment]
Thanks @benavenuto 
Extract is deprecated, the remainig issues to fix are duplicates. Closing.
1 - Enable copy and paste option on the right mouse buttom | Printscreen: https://drive.google.com/file/d/0B_DPX2-a4PDxM2k4MWI5aUNpcmc/view?usp=sharing
`trackets by trello https://trello.com/c/ZriVEu50/935-clipboard-cut-copy-paste-in-editor-context-menu `
2 - Differentiate color classes and tags in css (They are always blue)
  Created https://github.com/adobe/brackets/issues/12558 to track. 
Closing issue.
