### ISSUE TITLE
Error setting menu item shortcut: 1

### ISSUE THREAD

**Issue by IgorNovozhilov** [adobe/brackets#11845]
Error setting menu item shortcut: 1
/command/Menus.js:820 (anonymous function)

sprint 5 build 1.5.0-16538 (release cf9cf4698) 

PS: run without extensions

**Comment by petetnt** [comment]
Duplicate of #11004, similar to #10970

**Comment by redmunds** [comment]
@iNovozhilov Are you trying to override a shortcut? If so, use the keymap.json file to first change the old shortcut to something else (or `null` to remove it), and then set the shortcut to other command.

FYI, you can install the Display Shortcuts extension and use the right-click menu "Override Shortcut for Command " and "Disable Shortcut" commands to facilitate editing the keymap.json file.

**Comment by iNovozhilov** [comment]
Я не менял "shortcut", просто обновил с 1.4 на 1.5

**Comment by rroshan1** [comment]
@iNovozhilov It looks to be some issue with the settings from the previous version.
Can you try renaming the brackets folder in %appdata% and then launch Brackets. Do let us know if it solves the issue.

**Comment by iNovozhilov** [comment]
@rroshan1, i'm deleted the folder "\AppData\Roaming\Brackets", the problem remained.

**Comment by tomlutzenberger** [comment]
I could solve this problem by uninstalling and reinstalling Brackets 1.7.
It seems the update from 1.6 had some issues.

**Comment by zaggino** [comment]
There's also 1.8 here: https://github.com/adobe/brackets/releases
Closing this as this is an old version problem, please report again if there's problem with 1.8
