### ISSUE TITLE
Media Queries file gets over written in Responsive Mode

### ISSUE THREAD

**Issue by photoman** [adobe/brackets#11847]
I'm new to using bracket (but not development) -- I've noticed an issue with the Behavior of bracket when I'm editing code. I have my site.css and media-queries.css files in the root folder and linked to correctly. 

**When editing in 'normal mode' -- all is fine in the world.**

![2015-10-22_1217](https://cloud.githubusercontent.com/assets/1184507/10671111/e7545c24-78b6-11e5-8707-272ac5597481.png)

**When using the responsive mode (CTRL+2), any code in the media-queries.css file gets wiped out when switching to that mode.**

![2015-10-22_1218](https://cloud.githubusercontent.com/assets/1184507/10671172/32368a00-78b7-11e5-8129-243366628f4c.png)

**When i try to edit an object while in inspect mode - I get an error message:** *(This is sort of cryptic as there isn't a menu item in the tool bar that refers to creating a media query.)*

![media-queries_error](https://cloud.githubusercontent.com/assets/1184507/10671057/8dc49f34-78b6-11e5-8245-8dfcf7cdb377.png)

**Please help!** This is very frustrating!

**Comment by petetnt** [comment]
Hi, this issue seems to be related to the [Response-for-Brackets-extension](https://github.com/brimelow/Response-for-Brackets) if I am correct? Try reposting this issue on that repository as this seems to be an an extension, not Brackets core issue. :+1:

**Comment by abose** [comment]
@photoman This seems o be an extension issue as @petetnt pointed out. 
Please raise this issue with the extension author @ https://github.com/brimelow/Response-for-Brackets
Closing this as we do not maintain extension issues open in brackets core.
