### ISSUE TITLE
Code folding - new style

### ISSUE THREAD

**Issue by djAjax** [adobe/brackets#11844]
Hello, 
Please give a code folding style like most programs.
Replace the arrow-down with minus and arrow-right with plus.
![screenshot_1](https://cloud.githubusercontent.com/assets/9333602/10628844/0bfbf338-77d2-11e5-95f3-63844e0db321.jpg)

**Comment by abose** [comment]
Arrow is the default Design for brackets code fold markers. Most editors[sublime,atom,visual studio, DW, et.al.]
This can be overriden by themes. Closing as theme idea.
