### ISSUE TITLE
Sidebar disappears

### ISSUE THREAD

**Issue by edlau** [adobe/brackets#11850]
To reproduce:
- resize the sidebar to the left (reduce in width)
- click the document or the blank space on the right.
- the sidebar will disappear completely.

If you resize the sidebar to the right (expand) this doesn't happen.

**Comment by abose** [comment]
Double click on the left window margin to bring back the sidebar.

**Comment by abose** [comment]
Closing inactive thread.

**Comment by nagaomkar9** [comment]
I had the same issue and for me it seems to occur when the language is set to 'system default'. So I went to Debug -> Switch Language menu and choose english, and it solve the issue. I tried with several other languages and it works perfectly.
This should surely work.
happy coding
