### ISSUE TITLE
linux. bad "Developer Tools". mouse item not select

### ISSUE THREAD

**Issue by IgorNovozhilov** [adobe/brackets#11854]
нельзя выделить элемент мышью
linux mint. 1.5.0-16538 (release cf9cf4698) 
![2015-10-23 22 53 38](https://cloud.githubusercontent.com/assets/3082812/10703647/1ee9d172-79da-11e5-8657-f292d0550c22.png)

**Comment by petetnt** [comment]
Hi @iNovozhilov, these `DevTools` related issues ( #11856, #11855, #11854) are related to the `CEF (Chromium Embedded framework)`, which has it's own issue tracker in https://bitbucket.org/chromiumembedded/cef. Repost these issues there and hopefully the fixes will eventually land in `Brackets` too.

However, IIRC the Linux version of the CEF is still quite old so the issues might already be fixed. If you are experienced in Linux native coding help would be appreciated, adobe/brackets/issues/11047 is a good starting point for that.

**Comment by IgorNovozhilov** [comment]
неактуально
