### ISSUE TITLE
Brackets using excessive GPU on retina iMac

### ISSUE THREAD

**Issue by alex-taffe** [adobe/brackets#11859]
On my retina 5k iMac (2014, 4 GHz Intel Core i7, AMD Radeon R9 M295X 4096 MB), brackets appears to use excessive amounts of GPU power. The activity monitor does not show a spike in activity, but the fan maxes out after about 2 minutes and the temperature monitoring software I have reports the GPU temperature as being 96 degrees celsius, much hotter than it should be running for a text editor.

**Comment by abose** [comment]
can you comment `help>health report` here?

**Comment by alex-taffe** [comment]
`{
    "uuid": "86596980-a3c0-4946-b240-b71a67902a0e",
    "snapshotTime": 1445993176741,
    "os": "mac",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.4.0 Chrome/39.0.2171.36 Safari/537.36",
    "osLanguage": "en",
    "bracketsLanguage": "en",
    "bracketsVersion": "1.4.0-16380",
    "projectLoadTimes": "",
    "fileOpenTimes": "",
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": [
        {
            "name": "brackets-url-helper",
            "version": "0.0.3"
        },
        {
            "name": "dustindowell.fading-cursor-blink",
            "version": "1.0.2"
        },
        {
            "name": "globexdesigns.brackets-jscs",
            "version": "0.7.5"
        },
        {
            "name": "jarradsalmon.rightclickextended",
            "version": "1.3.1"
        },
        {
            "name": "jasonsanjose.brackets-sass",
            "version": "2.0.3-132"
        },
        {
            "name": "martypenner.autosave-files-on-window-blur",
            "version": "1.0.6"
        },
        {
            "name": "pflynn.copy-as-html",
            "version": "1.0.5"
        },
        {
            "name": "quick-multi-cursor-selection",
            "version": "0.0.4"
        },
        {
            "name": "resize-working-files",
            "version": "1.7.0"
        },
        {
            "name": "rhuno.replace.in.selection",
            "version": "1.0.0"
        },
        {
            "name": "shrikantmeena.enhanced-scrollbars",
            "version": "1.0.0"
        },
        {
            "name": "tab-tags",
            "version": "1.0.9"
        },
        {
            "name": "torin.duplicate",
            "version": "1.1.0"
        },
        {
            "name": "brackets-quick-markup",
            "version": "3.3.0"
        },
        {
            "name": "brackets-minifier",
            "version": "1.1.1"
        },
        {
            "name": "enturn.quick-search",
            "version": "1.1.4"
        },
        {
            "name": "jquinter",
            "version": "0.3.2"
        },
        {
            "name": "pockata.striptrailingspaces",
            "version": "1.3.0"
        },
        {
            "name": "camden.jsdownloader",
            "version": "3.2.0"
        },
        {
            "name": "camden.jshint",
            "version": "2.2.18"
        },
        {
            "name": "blueprint.outliner",
            "version": "0.9.3"
        },
        {
            "name": "joeireland.copyright",
            "version": "1.0.3"
        },
        {
            "name": "brackets-various-improvements",
            "version": "2.2.1"
        },
        {
            "name": "dnbard.extensions-rating",
            "version": "0.7.3"
        },
        {
            "name": "nicolo-ribaudo.brackets-svg-font",
            "version": "0.4.5"
        },
        {
            "name": "brackets-custom-region-code-folding",
            "version": "1.1.0"
        },
        {
            "name": "brackets-beautify",
            "version": "1.2.0"
        },
        {
            "name": "le717.html-skeleton",
            "version": "1.4.3"
        },
        {
            "name": "brackets-special-html-chars",
            "version": "1.2.2"
        },
        {
            "name": "mikaeljorhult.brackets-autoprefixer",
            "version": "0.6.1"
        },
        {
            "name": "talmand.html-templates",
            "version": "1.3.5"
        },
        {
            "name": "camden.w3cvalidation",
            "version": "2.2.2"
        },
        {
            "name": "fede91.brackets-preferences-ui",
            "version": "1.4.0"
        },
        {
            "name": "adobe.brackets.extract",
            "version": "0.8.0-1747-release"
        },
        {
            "name": "mackenza.php-smarthints",
            "version": "1.2.2"
        }
    ],
    "bracketsTheme": "dark-theme"
}`

**Comment by abose** [comment]
Can you try updating to latest version (1.5) and `debug>reload without extensions` and see if the peoblem persists? How many files are there in the active project?

**Comment by alex-taffe** [comment]
1.5 by itself seems like it may have fixed the issue (I didn't even know it came out! Either ignored the auto update message or it didn't appear). I'm going to use it a little and see what happens

**Comment by alex-taffe** [comment]
It is definitely still an issue

**Comment by alex-taffe** [comment]
GPU temperature is holding steady at around 95 degrees celsius

**Comment by abose** [comment]
Closing issue as inactive. Please reopen if problem persists.
