### ISSUE TITLE
linux. bad "Developer Tools - Scope Variables" 

### ISSUE THREAD

**Issue by IgorNovozhilov** [adobe/brackets#11855]
В дебагере не разворачиваются переменные объектов и массивы. При клике на "треугольник" предлагает редактировать как текст описание переменной.
linux mint. 1.5.0-16538 (release cf9cf46) 
![2015-10-23 23 08 23](https://cloud.githubusercontent.com/assets/3082812/10703880/af828278-79db-11e5-961b-8d256e68eac4.png)

**Comment by iNovozhilov** [comment]
до
![2015-10-23 23 16 03](https://cloud.githubusercontent.com/assets/3082812/10703982/57c1e50a-79dc-11e5-8067-15c6e8ca50af.png)
после
![2015-10-23 23 15 02](https://cloud.githubusercontent.com/assets/3082812/10703985/5c6a3c88-79dc-11e5-8613-e16ede5d9af3.png)

**Comment by IgorNovozhilov** [comment]
неактуально
