### ISSUE TITLE
"Error Reading Preferences" brackets.json

### ISSUE THREAD

**Issue by melionda** [adobe/brackets#11864]
Brackets Release 1.5 build 1.5.0-16538 (release cf9cf4698)  no Extensions installed.
Running on Win7 Ult 64bit. Never tried a previous version of Brackets.
Trying to create a preference file "brackets.json" using Menue>Debug>Open Preferences File. Then restart using Menue>Debug>Reload with/out Extensions.
Any change/edit to the "brackets.json" leads to the error message right after restart. This cannot be based on syntax issues, because:
a) an "empty" file showing just {} shows the error.
b) a complete copy of "defaultPreferences.json" to "Brackets.json" shows the error.
c) any other syntax conform edit shows the error.
Only the virgin version of "brackets.json" created by itself seems to work. (But it only contains 2 Font Format settings.)
Log File contains messages like: "ParsingError: Invalid JSON settings at C:/Users/********/AppData/Roaming/Brackets/brackets.json(SyntaxError: Unexpected token /)
Brackets is arguing the comment characters of JavaScript ??? Crazy stuff.

**Comment by redmunds** [comment]
> Log File contains messages like: "ParsingError: Invalid JSON settings at C:/Users/********/AppData/Roaming/Brackets/brackets.json(SyntaxError: Unexpected token /)
> Brackets is arguing the comment characters of JavaScript.

JSON doesn't allow comments, so you'll need to remove them.

**Comment by abose** [comment]
Json doesn't allow comments. The sample `defaultPreferences.json` is not a valid JSON file as it is intended only to be taken as a guideline for the actual preferences file.

**Comment by melionda** [comment]
Thanks Arun.

Confusion was around defaultPreferences.json which is actually not used as a json object, but I didn’t know about that.

**Comment by abose** [comment]
Closing as answered.
