### ISSUE TITLE
[SOLVED] JS and Plugin Hints stop after change selected file.

### ISSUE THREAD

**Issue by piscisferro** [adobe/brackets#11868]
I found a very annoying problem with Brackets, when I'm working with JS and I change the current selected file for other. JS code Hint and Plugins Hints stop working and brackets needs to be restarted to make all work again. 

It only happens when I select another file in the editor If I start brackets and work with the file without changing to another file, It works well.

It happens too if the file is .js, code hinting and plugins for code hinting don't work even if I start brackets with that file. If that's the case, weird thing happen: If I start with the .js (hinting don't work) and then switch to the .HTML, js and plugins hinting works (in HTML). if I switch back to js (here don't work), and then switch to the .HTML again, code hinting don't work anymore.  

This bug don't affect HTML and CSS code hinting.

**Comment by tallandroid** [comment]
Can you mention the platform you are using ? I tried it on Mac with brackets 1.6 and it works.

**Comment by abose** [comment]
Brackets 1.6 is not released yet !

**Comment by tallandroid** [comment]
:smile: I tried it on 1.4 . It seemed to work. Can you paste the Health Report Data from `Help> Health Report`

**Comment by redmunds** [comment]
The JS Code Hint engine needs to change context every time the current file changes. Is the problem that JS Code Hints don't work when you initially switch to a new file, but eventually work if you wait? If so, how long is the wait?

**Comment by piscisferro** [comment]
@redmunds when it stop, it don't work anymore

@tallandroid I'm out so I can't, when I come back to the PC I will paste the health report

Btw, I tried brackets without any plugins and it works, so maybe is a pluging conflict? When I come back to home I will try to find if is a pluging what is causing the bug.

**Comment by piscisferro** [comment]
Ok I found what happened. It's a plugin that conflict with the JS hint in some manner, the plugin is: "Simple JS Code Hints" I uninstalled it and now brackets works well again.

So it's solved :D

Thanks all for the support and help! I hope this thread will help more users with the same problem!

**Comment by abose** [comment]
Closing as answered.
