### ISSUE TITLE
Brackets shows nothing.

### ISSUE THREAD

**Issue by AdithyaHarun** [adobe/brackets#11867]
Excuse me, I want to continue my work on Brackets, but the app only shows menubar, blank sidebar, and blank workspace.
I try to close it, but nothing happen so I force-close it via Task Manager. After I reopen it, it returns to normal. Are there anything that I can do so this problem will not happen again?
Sorry for my bad english  :)

![image](https://cloud.githubusercontent.com/assets/7106825/10813091/4914e88e-7e57-11e5-95b7-50ce53e4ec7d.png)

**Comment by tallandroid** [comment]
:100: Happened to me a lot of times. Brackets ends up being slow an unresponsive at times. I am assuming its the issue with chrome shell ?

**Comment by abose** [comment]
can you try `debug>show developer tools` and comment the console messages here?

**Comment by danicholls** [comment]
Same happens to me. I take it it's only helpful if we dump console here if it's when it opens blank, right?

**Comment by ficristo** [comment]
Are you all still able to reproduce with the latest release? Event without extensions?

**Comment by ficristo** [comment]
I close this since we didn't hear back from you.

**Comment by danicholls** [comment]
I stopped using Brackets in the meantime.
