### ISSUE TITLE
Additional cursor

### ISSUE THREAD

**Issue by VictorKolb** [adobe/brackets#11863]
When i press option+shift+up appear additional cursor. 
System: Mac OSX El Captain  10.11.1 
Brackets: sprint 5 build 1.5.0-16538 (release cf9cf4698) 
build timestamp: Wed Oct 14 2015 04:40:12 GMT-0700
![2015-10-28 16 52 57](https://cloud.githubusercontent.com/assets/14196649/10792072/e039dbee-7d93-11e5-928e-923491918a81.png)

**Comment by petetnt** [comment]
This is an feature called `multicursor mode`. You can also hold `ctrl` while clicking to create another cursor in any place in the code area. Multiple cursors can be handy when you have to edit multiple lines with same modifications.

**Comment by abose** [comment]
This is a feature!
![image](https://cloud.githubusercontent.com/assets/5336369/10816089/42fbbfa0-7e56-11e5-8416-e85520b202dc.png)
Closing.
