### ISSUE TITLE
libgcrypt11 Dependency Issue

### ISSUE THREAD

**Issue by trhoy** [adobe/brackets#11877]
Brackets currently depends on libgcrypt11 and throws errors in Ubuntu 15.04 Vivid Velvet, which uses libgcrypt20. As a workaround, libgcrypt11 needs to be installed. This can be done in parallel with libgcrypt20 but is a hassle during the installation process. libgcrypt20 should be referenced so that libgcrypt11 is not required.

**Comment by petetnt** [comment]
See #10255. Brackets is looking for Linux community contributors (there's at least two big things kinda in limbo ATM, this and the CEF Update), if you could help out that would be great!

**Comment by trhoy** [comment]
Alright, thank you! I'll look into things and see about contributing.
