### ISSUE TITLE
Brackets crash when trying to comment

### ISSUE THREAD

**Issue by njezersek** [adobe/brackets#11875]
I have a problem. When I try to comment a line
```
echo '<script>window.location.replace("novice.php");</script>';
```
in a PHP document whole screen turns dark:
![image](https://cloud.githubusercontent.com/assets/10494687/10834101/fd7db762-7e96-11e5-9fb7-020c1c8316fb.png)

**Comment by abose** [comment]
This could be a one off issue, Restarting brackets should fix this.

**Comment by njezersek** [comment]
Restarting Brackets doesn't help. It works normally until I try to comment the line.

**Comment by abose** [comment]
Can you tell the exact steps, how do you comment the line etc..

**Comment by vjudge1** [comment]
I use Brackets 1.5.0-16538 and I created a PHP file to test this issue. 

When I type

    <?php
        echo "<script>alert('a');</script>";

Nothing happened:

However, when I add a "<>" before "\<script>" like this

    <?php
        echo "<><script>alert('a');</script>";

A message box jumped out.

While changing this line, the box always pops as long as this line of code looks like valid.

For example, these codes will pop while editing (PHP tag is required):

    <?php
    echo "<><script>alert('a');</script>";
    echo "<xss><script>alert('a');</script>";
    "<<script>alert('a');</script>";
    print("<a><script>alert('a');</script>";
    echo '<;a'>a<script>alert("a");</script>';  // Although it's not valid.
    //print("<a><script>alert('a');</script>";  // the same

Strangely, if there is no "<>" (or a html tag) before "\<script>", or "<>" is placed after "\</script>", no message box will show. For example, these codes won't make message boxes:

    <?php
    echo '<script>alert("a"); </script> <>';
    echo "<script>alert('a');</script>";
    "<script>alert('a');</script>";
    print( "<a><script>alert('a');</script>";

Codes without PHP tag won't run, either.

**Comment by quarteris** [comment]
1. Open a php file
2. Paste this in new line:
// <script>window.alert('asdf');</script>
3. The script will be executed by brackets and alert will be shown

If the script changes window.location, brackets will redirect there, this makes brackets window show github page:
// <script>window.location.href = 'https://github.com/';</script>

**Comment by vjudge1** [comment]
I have found this problem. However, it's because an extension named minimap. So it's IMPORTANT to DISABLE ALL EXTENSIONS and test it again before commenting issues.

(It's a pity that I have written a lot about this issue before I found [this](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue))

**Comment by ficristo** [comment]
Closing as a dupe of #11938.
(Even if it is more recent its image is clearer about the issue)
