### ISSUE TITLE
The autocompletion does not work anymore ..

### ISSUE THREAD

**Issue by kefuret** [adobe/brackets#11878]
Hi , I come here because autocompletion no longer walk on Brackets , then that is what I use the most ..

I put some pictures to illustrate my problem ..

http://puu.sh/l3gXd/c752430883.png
http://puu.sh/l3h1i/0f1228a712.png

When I wrote , autocompletion does not work ..

http://puu.sh/l3h6Y/eb1248447e.png
http://puu.sh/l3h7B/283d727347.png
http://puu.sh/l3h8f/3bf0c4680a.png

http://puu.sh/l3haT/7e60f6bc62.png

Thank you.

**Comment by petetnt** [comment]
Have you tried running without extensions `Debug -> Reload Without Extensions`. One of your extensions is deprecated (https://github.com/websiteduck/brackets-wdminimap) which might be inferring with the code hints.

For an alternative minimap, maybe try this one: https://github.com/zorgzerg/brackets-minimap

**Comment by abose** [comment]
Closing inactive thread.
