### ISSUE TITLE
linting.enabled set to false not working as expected

### ISSUE THREAD

**Issue by 1951FDG** [adobe/brackets#11871]
linting.enabled set to false for a speficic file or files does not seem to work, tried reloading with extensions, and restarting Brackets, but linting still occurs.

```
"path": {
        "bower_components/semantic-ui/dist/components/**": {
            "linting.enabled": false,
            "linting.collapsed": true
        }
    }
```

**Comment by ficristo** [comment]
I cannot reproduce.
I created a `.brackets.json` file with your snippet and the files under `bower_components/semantic-ui/dist/components/**` aren't linted.

**Comment by 1951FDG** [comment]
maybe camden.csslint extension issue? Try to reproduce by cloning my git repository:  https://github.com/1951FDG/SixtyFour

**Comment by ficristo** [comment]
I tried again with `camden.csslint` extension and it works as expected too:
the files under `bower_components/semantic-ui/dist/components/**` aren't linted.

@1951FDG That repo doesn't have a `.brackets.json` file nor a `bower.json` one: what should I try?

**Comment by 1951FDG** [comment]
Oops, the actual repo is hosted on Bitbucket (https://bitbucket.org/1951FDG/sixtyfourweb), I can give you access rights if you provide me with your Bitbucket username.

**Comment by ficristo** [comment]
I tried again on the repo at https://github.com/1951FDG/SixtyFour.
I've created a `.brackets.json` file at the root of the project with this content:
```json
{
    "path": {
        "stylesheets/**": {
            "linting.enabled": false
        }
    }
}
```
and the linting is disabled as expected.

Can you give me more details on what have you tried?

**Comment by 1951FDG** [comment]
Do you have a Bitbucket account? The actual repo is at (https://bitbucket.org/1951FDG/sixtyfourweb) But it is private. I can give you access rights if you provide me your Bitbucket username. Otherwise, I would have to make the repo public!

**Comment by ficristo** [comment]
I have the same nickname on bitbucket if you want.

**Comment by 1951FDG** [comment]
Bitbucket says unknown username, are you sure it is ficristo?

**Comment by ficristo** [comment]
Yes: https://bitbucket.org/ficristo/
I didn't set the name so you should see something like: Unknown Name (ficristo)

**Comment by 1951FDG** [comment]
Done, try to access the repo now

**Comment by ficristo** [comment]
It works as expected:
files under `bower_components/semantic-ui/dist/components/**` aren't linted
files like `bower_components/semantic-ui/dist/semantic.css` are.
I'm running Brackets from source: I tried master and the 1.5 release branch and still work as I'm expecting.
So or I've misunderstood your problem or I cannot really help you :cry:

**Comment by 1951FDG** [comment]
I am using Release 1.5 build 1.5.0-16538 (release cf9cf4698) on OS X 10.6.8

![brackets](https://cloud.githubusercontent.com/assets/220168/12203590/b777edca-b5fd-11e5-9115-46d440934ba4.png)

**Comment by 1951FDG** [comment]
Works as expected using Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) . Issue can be closed!
