### ISSUE TITLE
IDE shows dialog with message This project contains more than 30000 files..

### ISSUE THREAD

**Issue by harrydroid** [adobe/brackets#11881]
Hi, I started using brackets io few days ago. I wanted to use the ide for my project and having some troubles in using it. Whenever I open the project my editor hangs because of so many files and shows a dialog with message " This project contains more than 30,000 files....". Can anyone please tell me the way to discard some folders like .git and node_modules etc.

Regards

**Comment by petetnt** [comment]
Hi @harrydroid. Check out extensions such as https://github.com/gruehle/exclude-folders and https://github.com/zaggino/brackets-file-tree-exclude to filter out those folders.

**Comment by harrydroid** [comment]
@petetnt. exclude-folders helped me lot. Thanks
