### ISSUE TITLE
Switching into CSS very very slow (10 seconds)

### ISSUE THREAD

**Issue by appijumbo** [adobe/brackets#11889]
Thanks for Brackets, but it seems to have become very slow recently. editing HTML is no problem but when I  move the curser and click into the CSS side in split mode is takes 10 seconds (litteraly)  to be active. Strangely if I then click back into the HTML side from the CSS side, no problem everything works in a slit second.
I've tried disabling all the extensions and that had no effect. The same problem occurs when Im not in split mode with the same weird CSS to HTML 'no problem' asynchronous fault.

Hope you can assist
Thanks again

**Comment by petetnt** [comment]
Hi @appijumbo, can you paste your Help Report here (`Help -> Health Report`).

**Comment by appijumbo** [comment]
Thanks Pete 
---------------


{
    "uuid": "c78be13f-7f65-4ae7-b3e2-1b1af57f714d",
    "snapshotTime": 1446643073190,
    "os": "mac",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.5.0 Chrome/39.0.2171.36 Safari/537.36",
    "osLanguage": "en",
    "bracketsLanguage": "en-US",
    "bracketsVersion": "1.5.0-16538",
    "ProjectDetails": {
        "prj929492837": {
            "numFiles": 2,
            "cacheSize": 12279
        },
        "prj384338437": {
            "numFiles": 15,
            "cacheSize": 203469
        },
        "prj384338438": {
            "numFiles": 14,
            "cacheSize": 195391
        }
    },
    "fileStats": {
        "openedFileExt": {
            "html": 17,
            "css": 17
        },
        "workingSetFileExt": {
            "html": 2,
            "css": 2
        }
    },
    "projectLoadTimes": ":479",
    "fileOpenTimes": ":754:29340",
    "ModuleDepsResolved": 943573,
    "AppStartupTime": 945916,
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": [
        {
            "name": "brackets-mystique-theme",
            "version": "0.1.9"
        },
        {
            "name": "flat-ui-theme",
            "version": "1.0.3"
        },
        {
            "name": "mignonstyle.simple",
            "version": "1.1.0"
        },
        {
            "name": "orchid-theme",
            "version": "1.1.1"
        },
        {
            "name": "warapitiya.unity",
            "version": "1.0.0"
        },
        {
            "name": "brackets-editorconfig",
            "version": "0.0.4"
        },
        {
            "name": "brackets-scss-lint",
            "version": "0.2.0"
        },
        {
            "name": "fdecampredon.brackets-typescript",
            "version": "0.2.0"
        },
        {
            "name": "globexdesigns.brackets-jscs",
            "version": "0.7.5"
        },
        {
            "name": "htmlbars-syntax",
            "version": "1.2.0"
        },
        {
            "name": "jade",
            "version": "2.0.0"
        },
        {
            "name": "jasonsanjose.brackets-sass",
            "version": "2.0.3-132"
        },
        {
            "name": "sasshints",
            "version": "1.1.0"
        },
        {
            "name": "themesforbrackets",
            "version": "2.0.13"
        },
        {
            "name": "brackets-response",
            "version": "0.0.6"
        },
        {
            "name": "camden.csslint",
            "version": "2.0.21"
        },
        {
            "name": "gbratsos.zurb-foundation",
            "version": "1.2.1"
        },
        {
            "name": "io.brackets-sass-code-hints",
            "version": "0.1.0"
        },
        {
            "name": "camden.cordova",
            "version": "0.0.7"
        },
        {
            "name": "chrisgriffith.jqmbrackets",
            "version": "0.1.0"
        },
        {
            "name": "camden.jshint",
            "version": "2.2.18"
        },
        {
            "name": "jade-snippets",
            "version": "0.0.1"
        },
        {
            "name": "quickdocsjs",
            "version": "1.6.9"
        },
        {
            "name": "interactive-linter",
            "version": "1.0.5"
        },
        {
            "name": "swmitra.html-designer",
            "version": "2.0.5"
        },
        {
            "name": "camden.w3cvalidation",
            "version": "2.2.2"
        },
        {
            "name": "brackets-beautify",
            "version": "1.2.0"
        },
        {
            "name": "edge-code-web-fonts",
            "version": "0.1.7"
        },
        {
            "name": "hirse.outline-list",
            "version": "0.7.0"
        },
        {
            "name": "brackets-phonegap",
            "version": "0.1.1"
        },
        {
            "name": "brackets-emmet",
            "version": "1.2.2"
        },
        {
            "name": "jshint.configurator",
            "version": "1.1.6"
        },
        {
            "name": "talmand.html-templates",
            "version": "1.3.5"
        },
        {
            "name": "adobe.brackets.extract",
            "version": "0.8.0-1749-release"
        }
    ],
    "bracketsTheme": "dark-theme"
}

**Comment by appijumbo** [comment]
Just tried switching from JS to HTML and it works fine... so its only when moving in and out of the CSS plane is where its taking soooooooo long !

**Comment by petetnt** [comment]
@appijumbo You seem to have quite many CSS-related extensions installed. Have you tried launching Brackets without the extensions (Debug -> Reload without extensions) to rule out any extension issues?

**Comment by appijumbo** [comment]
ok just tried it and CSS works fine now, cheers :)

But how do I pin down the 'culprit', just disable all the CSS ones and slowly re-try them I guess ?

Thanks,
Tom

**Comment by petetnt** [comment]
@appijumbo Yup, that's it. I would start with the codehint and linter ones.

**Comment by appijumbo** [comment]
OK Cheers for the help
T

**Comment by ficristo** [comment]
@appijumbo if you have still problems feel free to open a new issue.
Closing as most likely an extension problem.
