### ISSUE TITLE
The order of files on the file tree

### ISSUE THREAD

**Issue by yogee412** [adobe/brackets#11888]
The files on the file tree in Brackets are sorted by names, so there will be a situation that the folder was under a file.
This looks like a huge mess in my eyes, who used to be a sublime text user, especially when the number of the files are growing. 
![image](https://cloud.githubusercontent.com/assets/12248555/10926999/03c18e3e-82d7-11e5-808b-bd6bdf0168ff.png)
So how could I adjust the editor to make the file tree sorted in types ,just as what sublime text and atom does.
In addition, I'm on a MAC.

**Comment by sprintr** [comment]
Add this preference.

```json
{
    "sortDirectoriesFirst": true
}
```

**Comment by yogee412** [comment]
I did as you said , and it works. 
Thanks .
