### ISSUE TITLE
After you save the file, ctrl + z not be rolled back

### ISSUE THREAD

**Issue by yuwenlong** [adobe/brackets#11899]
After you save the file, ctrl + z not be rolled back

**Comment by petetnt** [comment]
Duplicate of #11826

**Comment by yuwenlong** [comment]
The next version can fix?

**Comment by petetnt** [comment]
Hopefully yes! If you have some steps that one can use to reproduce this to find out the root cause, do report them at #11826, no-one has found a bullet proof way to repro the issue yet.
