### ISSUE TITLE
How do I use Google Chrome instead of Safari for Live Preview?

### ISSUE THREAD

**Issue by AndersenTobias** [adobe/brackets#11898]
Brackets used to only work with Google Chrome but now it seems to work with Safari as well. That's great, but I rather use Google Chrome with the Live Preview feature as it has better developer tools.

Is this possible to configure somehow?

**Comment by redmunds** [comment]
The "Experimental Live Preview" starts with your default browser. Then copy/paste the url from the default browser to any other browser. It will work with multiple browsers at once!

**Comment by AndersenTobias** [comment]
I see, I'll try this.
It would be nice if I could specify the default browser that Brackets use.

**Comment by abose** [comment]
Closing inactive thread.

**Comment by UserOfHalde** [comment]
hello
