### ISSUE TITLE
Extract for Brackets doesn't account for line-height.

### ISSUE THREAD

**Issue by Etheryte** [adobe/brackets#11896]
When calculating the dimensions for a text element, Extract doesn't account for the element's line-height.   For an example, see the below example from the sample .PSD file provided with Extract:

![Sample image](https://cloud.githubusercontent.com/assets/3171718/10973449/31915410-83e6-11e5-9fae-ee89022bc127.png)

The element's height is computed to be 24px, while in reality, the line-height of the text is 36px. This means that any calculated distance from and to this element is off by a rough (36-24)/2 = 6px when the design is turned into actual code. Hence measurements on elements where the line-height isn't identical to the font-size is pretty much useless.

Is there a work-around for this that I'm not aware of, perhaps there's a plugin to account for this oversight? Is this intentional design?

**Comment by petetnt** [comment]
Closing as Extract is now deprecated
