### ISSUE TITLE
Brackets 1.5 freezes when I open a folder with 1000+ file

### ISSUE THREAD

**Issue by makayjozsef** [adobe/brackets#11892]
Brackets 1.5 freezes for 2-3 minutes when I open a folder with 1000+ file. Brackets 1.4 opened this folder in 1 second.

Ubuntu 15.10

**Comment by petetnt** [comment]
While these kinds of performance issues are being addressed, try extensions such as https://github.com/gruehle/exclude-folders and https://github.com/zaggino/brackets-file-tree-exclude to filter out resource intensive folders such as `node_modules`.

Related to / duplicate of #11833

**Comment by abose** [comment]
Closing as duplicate. Tracked as #11833
