### ISSUE TITLE
HTML tag highlighting is sometimes misleading

### ISSUE THREAD

**Issue by frewat** [adobe/brackets#11890]
If you have an HTML tag `<div>` closed by `</div?>` or a `</div*>` where * denotes any special character (anything other than an alpha-numeric) , the opening and closing tags are both highlighted which is misleading. So the parser assumes that the `<div>` is closed by `</div?>` even though this is not true and this is hard to spot when debugging.

**Comment by petetnt** [comment]
Can confirm as a (minor) CodeMirror tag matching bug (can be replicated on the Tag Matcher demo https://codemirror.net/demo/matchtags.html).

**Comment by petetnt** [comment]
Actually after searching I think that it behaves correctly (see this ooooold commit: https://github.com/codemirror/CodeMirror/commit/9e069dac23aba66b582d66b020bfab38c42fd0d6) in the CodeMirror demo, Brackets just doesn't how the "error" highlighting which it should.
