### ISSUE TITLE
jQuery.ajax() syntax highlighting doesn't work as it should

### ISSUE THREAD

**Issue by MarcelKwaschny** [adobe/brackets#11903]
Hello everybody,

I don't know if it's just me but in my brackets editor the syntax highlighting for ajax-calls doens't work properly. When I added the "async: true" or the "async: false" statement the syntax highlighting stops working.

Brackets Version: 1.5
OS: Windows 7 Professional 64bit
All extensions were disabled.

With async statement:

![withasynctrue](https://cloud.githubusercontent.com/assets/9392778/11059620/0cbeb8cc-879b-11e5-9065-eb08680d9e01.PNG)

Without async statement:

![withoutasync](https://cloud.githubusercontent.com/assets/9392778/11059634/1e481962-879b-11e5-9ede-ee293a9ccffa.PNG)

It seems like "async" is a reserved word in my case because it has the same color as "function".

Thanks in advance :)

**Comment by petetnt** [comment]
Ping @zaggino as he made this change to CodeMirror: https://github.com/codemirror/CodeMirror/commit/94fc3b71e8e9f52b9239276a34658023933aac68 (cross-ref #11644). 

As a workaround you can wrap `async` to quotes to get the correct syntax highlighting back `"async": true`

**Comment by zaggino** [comment]
Yeah, I did this one ... I've tried and failed a lot trying to get that CM syntax highlighting for ES6 right ...

**Comment by MarcelKwaschny** [comment]
Wow I didn't expect that this problem would cause so many problems :D

**Comment by zaggino** [comment]
These are all valid declarations:
```
function foo(args) { return true; } // #1
async function foo(args) { return true; } // #2
const foo = async function (args) { return true; }; // #3
let obj = { async foo(args) { return true; } }; // #4
const foo = async (args) => { return true; }; // #5
let obj = { async: false }; // #6
```

Currently displaying as:
![image](https://cloud.githubusercontent.com/assets/1067319/11308063/2ed0c0fe-9010-11e5-9e2f-9d35592d6421.png)

You can see the problems in 4(function name incorrect) and 6(treated as keyword). I tried to tinker with the syntax highlighter to get it right but I always managed to broke one of the others. cc @marijnh

**Comment by marijnh** [comment]
I've reverted the async patch in 9024f7c, since I consider working ES6 support a priority over half-working ESNext support. @zaggino  If you want to submit a new patch (with test cases) that would be very welcome.

**Comment by ficristo** [comment]
1.8 should have this fixed. If you will still wave a problem please open a new issue.
