### ISSUE TITLE
Css code indent adjust

### ISSUE THREAD

**Issue by bjornandersen** [adobe/brackets#11907]
I am having a problem with brackets when it comes to Css and indent.
Usualy when i type my Css I indent 1 time from the left side before I then again indent the content inside my div. 
Earlier versions of Brackets didnt do anything about that. But now when I press enter, it automaticly pushes my #name back, and in to the left side margin.

How can I solve this. If anyone understood what i ment :-)

**Comment by abose** [comment]
Can you go to 'debug menu>reload without extensions` ans try the same?
Also try setting `debug>open preferences file> add "closeBrackets": false` if reload without extensions doesn't solve the issue.

**Comment by bjornandersen** [comment]
Hi, And thanks for answer.

 

Sadly, it didn’t resolve my problem. Well. First step didn’t.

But I seem unavailable to do any adjustments in the defaultPreferences.json file.

 

I found the “closeBrackets”: true,

 

But the document is read only. Any idea how to solve this?

 

From
Bjørn Arild Andersen

 

Fra: Arun Bose [mailto:notifications@github.com] 
Sendt: torsdag 12. november 2015 07.19
Til: adobe/brackets <brackets@noreply.github.com>
Kopi: bjornandersen <b-andersen@live.no>
Emne: Re: [brackets] Css code indent adjust (#11907)

 

Can you go to 'debug menu>reload without extensionsans try the same?
Also try settingdebug>open preferences file> add "closeBrackets": false` if reload without extensions doesn't solve the issue.

**Comment by bjornandersen** [comment]
Hi again. 

 

Opened my eyes, and found the CSS file attached to the document. 

Changed from true to false, and it solved it.

 

But now the {} doesn’t close by itself.

 

What I am looking for is the css code to stay where I put it in my css. No indent back to left side margin.

 

Any idea how to solve?

 

From
Bjørn Arild Andersen

 

Fra: Arun Bose [mailto:notifications@github.com] 
Sendt: torsdag 12. november 2015 07.19
Til: adobe/brackets <brackets@noreply.github.com>
Kopi: bjornandersen <b-andersen@live.no>
Emne: Re: [brackets] Css code indent adjust (#11907)

 

Can you go to 'debug menu>reload without extensionsans try the same?
Also try settingdebug>open preferences file> add "closeBrackets": false` if reload without extensions doesn't solve the issue.

**Comment by abose** [comment]
You have to do the change in brackets.json file. not the default preferences.json file which is read only.

**Comment by bjornandersen** [comment]
Thanks for answer. I cant seem to find that file. Where is it supposed to be in the folder?

 

Fra: Arun Bose [mailto:notifications@github.com] 
Sendt: torsdag 12. november 2015 09.51
Til: adobe/brackets <brackets@noreply.github.com>
Kopi: bjornandersen <b-andersen@live.no>
Emne: Re: [brackets] Css code indent adjust (#11907)

 

You have to do the change in brackets.json file. not the default preferences.json file which is read only.

**Comment by abose** [comment]
open `debug>open preferences file`  brackets.json should be in the right pane.

**Comment by abose** [comment]
Closing inactive thread.
