### ISSUE TITLE
Translations: DEFAULT_PREFERENCES_JSON_HEADER_COMMENT in Japanese

### ISSUE THREAD

**Issue by mandel59** [adobe/brackets#11900]
The current translation of DEFAULT_PREFERENCES_JSON_HEADER_COMMENT in Japanese is:
```
/*
 * これは、{APP_NAME} で環境設定がサポートされた
読み取り専用ファイルです。
 * このファイルは、他のペインで開かれた環境設定ファイル brackets.json を
 * 変更する際の参照資料として使用します。
 * {APP_NAME} 内で環境設定を使用する方法については、Web ページ
 *  (https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences) を参照してください。
 */
```

This translation has some issues:
- Its word wrapping is random.
- The first sentence 「これは、Brackets で環境設定がサポートされた読み取り専用ファイルです。」 is broken and impossible to understand.
- The subject of the second sentence 「このファイルは、他のペインで開かれた環境設定ファイル brackets.json を変更する際の参照資料として使用します。」 is ambiguous. The original sentence is an imperative form, so the translation should be modified to preserve the meaning.

The following is my trial translation:
```
/*
 * これは、{APP_NAME} がサポートしている環境設定が記録された読み取り
 * 専用ファイルです。
 * もう片方のペインで開かれた環境設定ファイル brackets.json を変更
 * する際の参考としてお使いください。
 * {APP_NAME} 内で環境設定を使用する方法については、Web ページ
 * https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences
 * を参照してください。
 */
```

**Comment by ficristo** [comment]
Since you already have written the code it would be awesome if you could submit a PR, so other japanese contributors can review it.
If you don't already know look at https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets.
Alternatively I think you can create a PR directly through Github modifying the file at `src/nls/ja/strings.js`

**Comment by abose** [comment]
Have forwarded this issue to the internal translations team. Will be mostly considered in the next round of translations.

**Comment by KatarzynaWodzinska** [comment]
Hi All! Our linguist agreed with the proposed correction.The string has now been fixed.
