### ISSUE TITLE
Can't install on Debian 8 64 bit

### ISSUE THREAD

**Issue by rieftux** [adobe/brackets#11912]
I get this error when installing on my laptop with OS Debian 8 64 bit:
![0bracket](https://cloud.githubusercontent.com/assets/9961361/11137533/33fef882-89eb-11e5-97cf-f66c37fc36b6.png)

**Comment by petetnt** [comment]
Possibly related to #10255?

**Comment by abose** [comment]
@rieftux Please go through some work arounds suggested in  #10255 
If that doesn't fix the problem, please update  #10255 with this issue details. 
Closing duplicate.
