### ISSUE TITLE
 Undoing(ctr+Z) behaves weirdly on 1.5

### ISSUE THREAD

**Issue by Madebym** [adobe/brackets#11913]
Ok, there are two things, and they haven't been there before. I am using Brackets since day one.

When undoing on Windows, the cursor jumps to the top of the page, then at the position where it is changing, then again at the top, you get the point. Back and forth, very strange, makes me dizzy :)

More importantly, sometimes it just remembers the last one or two steps that I want to undo. I am afraid to make any changes to the code because of that, haha. Joking aside, before it had very good memory, now it seems that it has lost it :(

**Comment by abose** [comment]
Possibily related to https://github.com/adobe/brackets/issues/11826 .
We are looking into this.

**Comment by Madebym** [comment]
Ok, thanks for the insight. I'll have a look at that thread.

**Comment by abose** [comment]
Closing as duplicate.
@Madebym Could you post the issue you are facing as a comment in  #11826 .

**Comment by Madebym** [comment]
Sure, not a problem. I will just troubleshoot a bit more, maybe it is only PHP files related, not sure 100%.
