### ISSUE TITLE
Shortcuts don't work on new brackets windows.

### ISSUE THREAD

**Issue by SilverSilence** [adobe/brackets#11911]
All shortcuts do not work on any further brackets instances I open.

**Comment by petetnt** [comment]
Most likely related to this: #11826

I have occasionally ran into that too, but haven't found a way to repeat it successfully.

**Comment by SilverSilence** [comment]
To replicate: Try to go to `Debug > New Brackets Window`. And in that window, no shortcuts are working. I'm not sure why you think that it's related to the issue you posted. For it doesn't mention multiple instances of brackets.

**Comment by petetnt** [comment]
@SilverSilence I mention being able to trigger the issue by opening new Brackets window(s) in the bottom of that post. Sometimes I lose the undo ability, sometimes the shortcuts. But most of the times opening them works out just fine, just like when I tried to test this again just now. If it always does it to you, then great (sort of, great as in can you post your Health Report from `Help -> Health report`.

**Comment by petetnt** [comment]
Oh and do you get any errors to console. Have you tried it without extensions?

**Comment by SilverSilence** [comment]
Okay, this ios really weird. I just tried it again now and the shortcuts work?? I didn't change anything, I had the same applications running... And it's the FIRST time that they work :/

As for your questions: Yes, I had the issue with and without the extensions. I'll test it again tomorrow. Should it not work again, I'll let you know.

**Comment by ficristo** [comment]
@SilverSilence If you have still problems feel free to reopen or open a new issue.

**Comment by hariaakash** [comment]
Am facing this problem, I tried loading brackets without extensions and still the same, even after brackets reinstall too.
