### ISSUE TITLE
Feature Request - Sync option / extension

### ISSUE THREAD

**Issue by kxc0re** [adobe/brackets#11916]
I'm working on severall machines and i think a lot of others do so too.
So a simple extension/setting sync would be nice

Greetings

**Comment by mseiler025** [comment]
I found this today, haven't tried it yet
https://github.com/milosh86/Brackets-ExtensionsBulkInstall

For settings you could copy your brackets.json file (User-global preferences) to the new machine, you can find it at by going to Debug > Open Preferences File (then right click on brackets.json and show it in Finder/Explorer)

it would be nice if it was automated maybe using GitHub Gists.

**Comment by abose** [comment]
Closing as extension available.
