### ISSUE TITLE
JS syntax highlighting inconsistent on functions

### ISSUE THREAD

**Issue by jbmonroe** [adobe/brackets#11915]
![js-syntax-highlight](https://cloud.githubusercontent.com/assets/1607804/11154357/de3e0d44-8a0c-11e5-9f50-1d886c24345a.png)

Syntax highlighting for user function names appears inconsistent in 1.5 build 1.5.0-16538 (release cf9cf4698).  (In the example, the function names should be purple, not white; only the last one is correctly highlighted.)  I haven't been able to find a pattern yet.  Removing and replacing the space between the function keyword and the function name corrects the highlighting for that function and those below *only*.  The reversion to unpredictably non-highlighted function names returns afterward, though.

**Comment by abose** [comment]
tagging @swmitra @MarcelGerber

**Comment by petetnt** [comment]
Couldn't replicate myself after typing in the given code visible on the screenshot. Could you most the whole file?

**Comment by jbmonroe** [comment]
Possible NDA issue. How to handle?

**Comment by petetnt** [comment]
@jbmonroe can you create [a minimal, comple and verifiable sample](http://stackoverflow.com/help/mcve) instead? My bet is on that there's something above those lines that contain some malformed syntax which breaks the parser. Also have you tried to run without extensions (Debug -> Launch Without Extensions) to rule out extension issues?

**Comment by jbmonroe** [comment]
I'll do that on Monday when I get back to that computer.  I don't think the syntax is malformed because JSHint and JSLint don't have a problem with it (although they could be wrong, too).  I'll try running without extensions as well.

I'll see if I can fake up an example on this computer, too, since that would save some time.

**Comment by jbmonroe** [comment]
I copied the file and did some editing to obscure the intent of the code a bit, and on first load, neither file has issues with syntax coloring.  My surmise is that enough editing would cause it to happen, and I'll pursue that tack during the day as I finish off the flow.  If I can't reproduce the problem by EOB today, I'll back the issue out.

**Comment by jbmonroe** [comment]
I can't duplicate it.  Even if it occurs after six hours of editing, this would be the next-to-last thing that you'd want to address.  Closing.
