### ISSUE TITLE
Remember session on shutdown

### ISSUE THREAD

**Issue by thany** [adobe/brackets#11922]
Brackets doesn't remember the session after closing & reopening, when it was closed by a shutdown signal, rather than a user quitting the application normally.

This is happening under Windows at least, and so far I've only been able to test this on Windows 7 x64. I'm guessing this is an issue on all Windowses. Not sure about other types of OS, but all of them send some sort of shutdown signal when shutting down, which is probably different from a regular quit.

Tested with Brackets 1.4 (as 1.5 contains a breaking issue).

**Comment by abose** [comment]
is ctrl-z the breaking issue in 1.5?
Is it not present in 1.4?

**Comment by thany** [comment]
That's the one.

**Comment by abose** [comment]
Closing stale thread. Please reopen if This is still an issue.

**Comment by thany** [comment]
This issue still exists in the latest release. So please reopen.

It's failry simple to reproduce, since it's on of those consistent bugs ;)
