### ISSUE TITLE
the html <%= %>  is not use ????

### ISSUE THREAD

**Issue by c941010623** [adobe/brackets#11920]
in html i use the  <%= %> in html
beause i use backbone and use template
it will show error

Special characters must be escaped : [ < ].
Special characters must be escaped : [ > ].

why ???

how can i disable the error info ???

**Comment by c941010623** [comment]
who can help ??

**Comment by ficristo** [comment]
Can you reproduce with `Debug \ Reload without extensions` ?

**Comment by ficristo** [comment]
Likely an extension problem. Closing
