### ISSUE TITLE
RPM package for fedora linux needed!

### ISSUE THREAD

**Issue by Attrash-Islam** [adobe/brackets#11937]
RPM package for fedora linux needed!

**Comment by fnkr** [comment]
+1

**Comment by Vincentdc94** [comment]
+1

**Comment by kuni93** [comment]
+1

**Comment by belenos** [comment]
+1. Please!

**Comment by zaggino** [comment]
Try AppImage from https://github.com/zaggino/brackets-electron/releases

**Comment by utrescu** [comment]
+1

AppImage (1.9.0) does not have Live Preview in Fedora 25

![brackets](https://cloud.githubusercontent.com/assets/2011002/21046583/a9e16df6-be05-11e6-8b2a-d9f8cc21861a.png)

**Comment by Attrash-Islam** [comment]
No more relevant for me
