### ISSUE TITLE
Experimental live preview - background images problem

### ISSUE THREAD

**Issue by Mangatt** [adobe/brackets#11936]
There is an issue when using experimental live preview with background images - live preview starts normally but after changing CSS, background images dissapear.

After some investigation I have found that this issue is caused by folder structure - live preview is not loading images relative to CSS but relative to HTML file (CSS and images are in subfolder).

**Comment by Jacqbus** [comment]
I have the same problem. When insert paths relative to html file, it works fine, but i want to use paths relative to current css file.

**Comment by alekks** [comment]
+1
I mean, it's not a big deal to just do a search and replace before publishing - but you shouldn't have to. :)

**Comment by MarcelGerber** [comment]
This should be fixed in the next Release.
Please chime in in case it still doesn't work.
Closing.
