### ISSUE TITLE
After JSX tags and ES6 template string syntax highlighting breaks down until the end of the file

### ISSUE THREAD

**Issue by antivanov** [adobe/brackets#11939]
Sometimes after encountering a few JSX tags and ES6 template string syntax highlighting in Brackets seems to be broken for the rest of the file. Code fragment to reproduce:

Renders correctly as Github markdown:

```javascript
var progress = 30;
var rendition = <span className="progress-indicator">{{`${progress}%`}}</span>;
var remaining = 100 - progress;
```

Does not render correctly in Brackets Release 1.5 build 1.5.0-16538 (release cf9cf4698) 
build timestamp: Wed Oct 14 2015 15:08:37 GMT+0100:

![alt Broken syntax highlighting](https://docs.google.com/uc?authuser=0&id=0B_oWhP2-85k7QWxjRVhlTlVQbUk&export=download "Broken syntax highlighting")

**Comment by petetnt** [comment]
There's no native support for JSX in CodeMirror yet (template strings do work though), see #11061 for more information.

**Comment by antivanov** [comment]
> There's no native support for JSX in CodeMirror yet (template strings do work though)
Thank you for the comment. No current support for JSX is understandable and fine, however the issue subject is a bit different: most likely normal parsing should still continue after a line that cannot be  parsed. This is how markdown is rendered in Github, for example.

This might still be an issue that still needs to be fixed, but not sure whether this is an issue in CodeMirror or in Brackets.

**Comment by petetnt** [comment]
@antivanov Sorry, I was bit in a hurry so my reply was a bit shortsighted: the issue is exactly that the parsing doesn't return to correct form. The proposed `javascriptmixed` mode (or just plain `jsx`-mode) would fix this, but it is surprisingly hard to get right. We are working on it though, feel free to drop in suggestions or code snippets that would fix or improve the issue on #11061 :+1:

**Comment by antivanov** [comment]
Thanks, I will also read through that related issue

**Comment by petetnt** [comment]
JSX Mode is now available in Brackets
