### ISSUE TITLE
JavaScript code hints not working

### ISSUE THREAD

**Issue by ianrosedev** [adobe/brackets#11933]
~Version 1.5~

The JavaScript code hints worked just fine, then today they stopped working. I downloaded v.1.5 two days ago. I reinstalled v.1.4 and everything works ok. The issue is only with JavaScript, as the HTML and CSS code hints still are working fine. 

Note: I have closed/reopened the app and restarted the computer with mixed results.

**Comment by abose** [comment]
Tagging @swmitra

**Comment by swmitra** [comment]
@ianrosedev do you see any errors in the inspector console? Also please share the preferences set for the project where js hinting is not working.

**Comment by ianrosedev** [comment]
@swmitra I have it working now. I added
```
"codehint.JSHints": true,
"codehint.AttrHints": true
```
to the brackets.json file. I'm sure there is some user error somewhere on my part.

Thanks for the response!
