### ISSUE TITLE
Feature proposal: multiple features

### ISSUE THREAD

**Issue by pelpet** [adobe/brackets#11944]
There could be an 'Open folder' button next to the folder selector that would instantly bring up Windows Explorer with your current folder opened.

I am also missing 'Convert to Lowercase' and 'Convert to Uppercase' functions. (Or did I just miss them? I've been searching for them a while now.)

**Comment by petetnt** [comment]
You can open the current folder in Windows Explorer (or Finder or similar) by right clicking a file in the file tree and selecting `Show in Explorer`.

Check out [`brackets-additional-right-click-menu`](https://github.com/caphodel/brackets-additional-right-click-menu) extension which seems to have Lowercase and Uppercase conversion options.

Hopefully these tips help.

**Comment by pelpet** [comment]
I figured there might be some extensions for the case-changing, however, I'd expect a text editor to have these functions built-in.

Anyway, thank you for such a fast reply. The extension works well.

**Comment by abose** [comment]
Closing as extension available.
