### ISSUE TITLE
A New auto save feature

### ISSUE THREAD

**Issue by sureclick** [adobe/brackets#11946]
I would really love if you guys add an auto save option in your next version of brackets. Thanks, your number one fan.

**Comment by mseiler025** [comment]
These extensions might not be exactly what you have in mind but may help.

https://github.com/joemakev/brackets-backup

https://github.com/martypenner/brackets-autosave-files-on-window-blur

**Comment by tucker-m** [comment]
I've been using one called [Autosave on View Change](https://github.com/marcantony/brackets-autosave-on-view-change) for months now; I highly recommend it. I think the extensions take care of this feature well enough. There's no option for saving on each keystroke, but I haven't found a need for that yet.

**Comment by abose** [comment]
Closing as extension idea.

**Comment by abhijeetbhanjadeo** [comment]
[Autosave every edit](http://brackets.dnbard.com/extension/brackets-autosaver) is a good option as well.

**Comment by tik9** [comment]
Could someone delete the post of @abhijeetbhanjadeo , seems not relevant and possibly misleading.

**Comment by tik9** [comment]
[Here](https://github.com/nmaxcom/brackets-autosaver) is the every edit save, to be found in the plugin manager.
