### ISSUE TITLE
Error when upload an extension 

### ISSUE THREAD

**Issue by rrandom** [adobe/brackets#11943]
error message: `An error occurred, but unfortunately I don't know how to say this nicely: EACCES, mkdir '/home/aboutweb/tmp/bracketsPackage_1151020-12803-zpz3p5'`
I think I have the valid package.json and main.js. Any ideas?

**Comment by petetnt** [comment]
Duplicate of #11932, there seems to be an fix coming

**Comment by abose** [comment]
closing duplicate
