### ISSUE TITLE
online-dnbard.rhcloud.com reported by malwarebytes and Virus Total

### ISSUE THREAD

**Issue by stanlenoir** [adobe/brackets#11958]
Since two days i got every five minutes an alert popup from **Malwarebytes Anti-Malware** about **online-dnbard.rhcloud.com**. He blocked it. 

You can find a VirusTotal report here : https://www.virustotal.com/fr/url/48adb5217e7a77f9b8eb482f4ec520120984b9f5d6e4d68327bd288f5a54fed2/analysis/1448528885/

Malwarebytes Anti-Malware Log : 

Detection, 26/11/2015 10:04, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.165.193.165, online-dnbard.rhcloud.com, 49803, Outbound, I:\Software\Développement\Brackets\Brackets.exe, 
Detection, 26/11/2015 10:04, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.165.193.165, online-dnbard.rhcloud.com, 49804, Outbound, I:\Software\Développement\Brackets\Brackets.exe, 
Detection, 26/11/2015 10:04, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.165.193.165, online-dnbard.rhcloud.com, 49803, Outbound, I:\Software\Développement\Brackets\Brackets.exe, 
Detection, 26/11/2015 10:04, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.165.193.165, online-dnbard.rhcloud.com, 49805, Outbound, I:\Software\Développement\Brackets\Brackets.exe, 
Detection, 26/11/2015 10:04, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.175.208.191, extensions-dnbard.rhcloud.com, 49807, Outbound, I:\Software\Développement\Brackets\Brackets.exe, 
Detection, 26/11/2015 10:04, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.175.208.191, extensions-dnbard.rhcloud.com, 49807, Outbound, I:\Software\Développement\Brackets\Brackets.exe, 
Detection, 26/11/2015 10:04, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.165.193.165, online-dnbard.rhcloud.com, 49808, Outbound, I:\Software\Développement\Brackets\Brackets.exe, 
Detection, 26/11/2015 10:06, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.175.208.191, extensions-dnbard.rhcloud.com, 49861, Outbound, I:\Software\Développement\Brackets\Brackets.exe, 
Detection, 26/11/2015 10:06, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.165.193.165, online-dnbard.rhcloud.com, 49863, Outbound, I:\Software\Développement\Brackets\Brackets.exe, 
Detection, 26/11/2015 10:09, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.165.193.165, online-dnbard.rhcloud.com, 49932, Outbound, I:\Software\Développement\Brackets\Brackets.exe, 
Detection, 26/11/2015 10:09, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.175.208.191, extensions-dnbard.rhcloud.com, 49933, Outbound, I:\Software\Développement\Brackets\Brackets.exe, 
Detection, 26/11/2015 10:14, SYSTEM, LAGROSSEBERTA, Protection, Malicious Website Protection, Domain, 54.165.193.165, online-dnbard.rhcloud.com, 49972, Outbound, I:\Software\Développement\Brackets\Brackets.exe,

**Comment by petetnt** [comment]
Also mentioned on SO Chat: http://chat.stackoverflow.com/transcript/message/27033044#27033044
