### ISSUE TITLE
Toggle Line Comment should comment at the start of the code, not the start of the line

### ISSUE THREAD

**Issue by stowball** [adobe/brackets#11953]
When you use Toggle Line Comment in Sublime, it creates the comment at the beginning of the code on that line, and not the beginning of the line. This is better because linting rules often demand that comments start at the correct indent, so quickly commenting code in Brackets also results in lots of linting errors.

As an aside, lint rules prefer that a space be after `//`, so this should be changed in languages.json.

**Comment by borax12** [comment]
@stowball - i too faced the same issue, added the feature

**Comment by muhsinali** [comment]
Does this still need to get worked on?

**Comment by abhibansal530** [comment]
Is this issue still open??

**Comment by baherramzy** [comment]
This appears to have been fixed by @borax12 in #11954. This issue can be closed.

**Comment by redmunds** [comment]
@baherramzy PR #11954 has not yet been merged into master, so this issue is not yet closed.

**Comment by borax12** [comment]
@redmunds - i am not getting the time to write the per language based preference, i think i will be giving it a shot tomorrow again . But if not , somebody else can pick up the feature of making it per language based

**Comment by redmunds** [comment]
@borax12 Just to be clear, this only needs a preference of something like `indentLineComment: true/false`. Brackets already has a builtin mechanism to allow specifying preferences per language or file extension (although currently json needs to edited manually -- there's not yet a GUI).

Subtle point is that if preference `indentLineComment` is not specified, it defaults to `false`, which defaults to current behavior, which minimizes disruption.

**Comment by borax12** [comment]
Ohk , so that makes sense , i just need to set a single preference value and brackets detects custom langauge specfic overriding of the same preference does it?

**Comment by redmunds** [comment]
Take a look at `language` and `path` sections of [this example](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#a-sample-preferences-json-file-) in the Preferences section of the How to Use Brackets doc.

**Comment by borax12** [comment]
@redmunds - i updated the lineCommentBugFix branch to have a default preference as false and the line commenting indentation now works according to the preference and added respective test cases for each line comment test case existing
