### ISSUE TITLE
Minify does not work - javascript error

### ISSUE THREAD

**Issue by QRMarketing** [adobe/brackets#11956]
Running Minify code cause a javascript error. Here is the call stack and error-ing code:

ncaught SyntaxError: Unexpected token N
push_data @ bpt.js:2
indicator_init @ bpt.js:2
do_svg_update @ bpt.js:1
do_process_tick @ bpt.js:1
(anonymous function) @ bpt.js:1
(anonymous function) @ d3.v3.min.js:1
t @ d3.v3.min.js:1u @ d3.v3.min.js:1

function push_data(data_index, item_name, item, tmp_chart) {
    delete data[tmp_chart][data_index].item_name;
    var data_string = JSON.stringify(data[tmp_chart][data_index]);
    data[tmp_chart][data_index] = JSON.parse(data_string.substr(0, data_string.length - 1) + ",\"" + item_name + "\":" + item + "}");
}

If I run it un Minify or use: http://jscompress.com/ It runs fine.

**Comment by abose** [comment]
Are you using a minify extension to do this?
Brackets does not support minify out of the box.

**Comment by QRMarketing** [comment]
I just download installed the latest version. I saw that if could Minify, tried it and it does not work. My code is a bit complicated so, perhaps problematic. For simpiler code perhaps it does work. But since it is in the standard download package, it sort of implies you sanction it. Debugging code is hard enough. Putting in 'gotchas' is bad PR for your tool, especially since it is not yours.

**Comment by abose** [comment]
The packages are not maintained by adobe . Those are extensions written byt the community.
Could you go to `help> health report` and comment the report here.
We would be able to direct you to the correct github page to raise the issue.

**Comment by QRMarketing** [comment]
To help any one that maybe trying to debug this Minify, I attach here the code that I think it is not Minifing correctly. The bug in the Minify only seems to occur when I do a "MACD" option in my code. So I give the branch out from the switch statement into the functions that do this. As stated before, The failing line is "JSON.parse" which is probably getting a NaN (a divide by 0) from somewhere else, caused deep in the code that loops through data. It is the Minify that is introducing this bug in the code. The fix for me is just not use this Minify and use another Minify and the bug goes away. I hope this helps. Cheers.

case "MACD":

                var data_start_signal;
                data_stop = data[tmp_chart].length - 1;
                if (state == "INIT") {
                    data_start = indicator[tmp_chart][a].items.AvgL - 1;
                    data_start_signal = indicator[tmp_chart][a].items.AvgL - 1 + indicator[tmp_chart][a].items.Signal;
                }
                if (state == "TICK") {
                    data_start = data[tmp_chart].length - 3;
                    data_start_signal = data_start;
                }
                if (data[tmp_chart].length - 1 < data_start_signal) break;
                for (c = data_start; c <= data_stop; c++) {
                    push_data(c, "MACDEMAS", macd(c, indicator[tmp_chart][a].items.AvgL, indicator[tmp_chart][a].items.AvgS, indicator[tmp_chart][a].items.Signal, "1", tmp_chart), tmp_chart);
                }
                for (c = data_start; c <= data_stop; c++) {
                    push_data(c, "MACDEMAL", macd(c, indicator[tmp_chart][a].items.AvgL, indicator[tmp_chart][a].items.AvgS, indicator[tmp_chart][a].items.Signal, "2", tmp_chart), tmp_chart);
                }
                for (c = data_start; c <= data_stop; c++) {
                    push_data(c, "MACDL", macd(c, indicator[tmp_chart][a].items.AvgL, indicator[tmp_chart][a].items.AvgS, indicator[tmp_chart][a].items.Signal, "3", tmp_chart), tmp_chart);
                }
                for (c = data_start_signal; c <= data_stop; c++) {
                    push_data(c, "MACDS", macd(c, indicator[tmp_chart][a].items.AvgL, indicator[tmp_chart][a].items.AvgS, indicator[tmp_chart][a].items.Signal, "4", tmp_chart), tmp_chart);
                }
                for (c = data_start_signal; c <= data_stop; c++) {
                    push_data(c, "MACDH", macd(c, indicator[tmp_chart][a].items.AvgL, indicator[tmp_chart][a].items.AvgS, indicator[tmp_chart][a].items.Signal, "5", tmp_chart), tmp_chart);
                }

                panel2("MACD", a, state, panel_select, tmp_chart);
                panel2Flag[tmp_chart] = "YES";

                break;


/////////////////////////// MACD  
function macd(data_index, AvgL, AvgS, Signal, part, tmp_chart) {
    var i;
    var sum;
    var k;
    if (part == "1") {
        sum = 0;
        k = 2 / (AvgS + 1);

        for (i = 0; i < AvgS; i++) {
            sum = sum + data[tmp_chart][data_index - AvgS + i + 1].Close;
        }
        if (data_index == AvgL - 1) {
            return sum / AvgS;
        } else {
            return ((data[tmp_chart][data_index].Close - data[tmp_chart][data_index - 1].MACDEMAS) * k) + data[tmp_chart][data_index - 1].MACDEMAS;
        }
    }
    if (part == "2") {
        sum = 0;
        k = 2 / (AvgL + 1);

        for (i = 0; i < AvgL; i++) {
            sum = sum + data[tmp_chart][data_index - AvgL + i + 1].Close;
        }
        if (data_index == AvgL - 1) {
            return sum / AvgL;
        } else {
            return ((data[tmp_chart][data_index].Close - data[tmp_chart][data_index - 1].MACDEMAL) * k) + data[tmp_chart][data_index - 1].MACDEMAL;
        }
    }
    if (part == "3") {
        return data[tmp_chart][data_index].MACDEMAS - data[tmp_chart][data_index].MACDEMAL;
    }
    if (part == "4") {
        sum = 0;
        k = 2 / (Signal + 1);

        for (i = 0; i < Signal; i++) {
            sum = sum + data[tmp_chart][data_index - Signal + i + 1].MACDL;
        }
        if (data_index == AvgL + Signal - 1) {
            return sum / Signal;
        } else {
            return (((sum / Signal) - data[tmp_chart][data_index - 1].MACDS) * k) + data[tmp_chart][data_index - 1].MACDS;
        }
    }
    if (part == "5") {
        return data[tmp_chart][data_index].MACDL - data[tmp_chart][data_index].MACDS;
    }
}

function push_data(data_index, item_name, item, tmp_chart) {
delete data[tmp_chart][data_index].item_name;
var data_string = JSON.stringify(data[tmp_chart][data_index]);
data[tmp_chart][data_index] = JSON.parse(data_string.substr(0, data_string.length - 1) + ",\"" + item_name + "\":" + item + "}");
}

**Comment by abose** [comment]
Could you go to `help menu> health report` and comment the report here.

**Comment by abose** [comment]
Closing thread as this is relating to brackets extension not maintained by brackets team.
Please report the issue in https://github.com/wylst/brackets-minifier or the git repo of the minify extension that you installed.
