### ISSUE TITLE
Don't auto close tag on include

### ISSUE THREAD

**Issue by snigglet** [adobe/brackets#11951]
Working with Brackets (just moved over from DreamWeaver to it and loving it!!!) ... but one irritating issue. In Java/JSP, when you add an include such as:
<%@ include file="/includes/core.jsp" %>

Brackets auto closes the tag as follows:
<%@ include file="/includes/core.jsp" %></%@>

i.e. note the <%/%@>

I want to stop this. I tried by going into brackets.json and changing this property:
"closeBrackets": false,

This does not do the trick.

Is there something I can do?

Many thanks.
jean@gatelets.com

**Comment by mseiler025** [comment]
the preference you want to change/add is this:

"closeTags": {
	"whenOpening": false
}


optionally you could do this:

"closeTags": {
        "whenClosing": false,
	"whenOpening": false
}

**Comment by snigglet** [comment]
Fantastic - thank you Matthew.
While I have your attention ... is there a plan to include something like Dreamweaver's "Apply Source Formatting" feature. I think this is one of the only things I have consistently loved and wished it was in editors like Coda or Sublime. It is really useful to be able to format/clean all your code with a single click... just a wish :)

Jean

**Comment by mseiler025** [comment]
I am not sure but I think there may be extensions that do this.  This might be one extension that does that but I have not used it - https://github.com/brackets-beautify/brackets-beautify

**Comment by snigglet** [comment]
Sweet! Thanks!
On November 24, 2015 at 12:52:00 PM, Matthew Seiler (notifications@github.com) wrote:

I am not sure but I think there may be extensions that do this. This might be one extension that does that but I have not used it - https://github.com/brackets-beautify/brackets-beautify

**Comment by abose** [comment]
Closing as answered.
