### ISSUE TITLE
dot underscore files

### ISSUE THREAD

**Issue by angelistudio** [adobe/brackets#11965]
Hi there,
I'm testing Brackets on ubuntu and noticed there are a lot of dot underscore files in my site tree... (external hd shared with a mac).
Is there an easy way to hide them?

Thanks!

**Comment by abose** [comment]
brackets-file-tree-exclude extension can exlude files. Check it out in extension manager.

**Comment by angelistudio** [comment]
thank you abose,
works perfectly!
