### ISSUE TITLE
Tab indentations aren't rendered

### ISSUE THREAD

**Issue by stowball** [adobe/brackets#11963]
I'm using the latest and greatest master (and the same happened for a build from 2 weeks ago), that documents with tabs used for indentation are all rendered flat against the left edge of the document.

Upon inspecting, it appears that the inline `text-indent` and `padding-left` styles are the cause. If you add an overriding style of: 

```css
.CodeMirror-line {
	padding-left: 0 !important;
	text-indent: 0 !important;
}
```

then the indentation works as expected. Files which use spaces for indentation are unaffected by default nor by the override.

I have tried with and without extensions; the same thing happens.

So, what's the point of the crazy text  `text-indent`/`padding-left` inline-styles, and can they safely be removed completely? Because clearly, they break things now.

**Comment by stowball** [comment]
I see that CodeMirror has the same `text-indent`/`padding-left` trick for aligning wrapped items, but their demo correctly renders tabs https://codemirror.net/demo/indentwrap.html

**Comment by petetnt** [comment]
The PR is from here: #11909. Ping @abose @rroshan1 :bomb: 

The hack is, for like you said, for properly wrapping lines. When I verified it it did work properly for tabs and spaces. Later I saw the "all tabs collapsed" thing against a 3rd party repo I cloned, but I though that just the file was borked.

**Comment by abose** [comment]
Could you give a sample file where the problem exists?

**Comment by petetnt** [comment]
@abose I fixed it, PR incoming

**Comment by abose** [comment]
Thanks @petetnt . 
Can you give a sample file that has the problem, just to see the bug when you upload the PR?

**Comment by petetnt** [comment]
@abose Sample file would be:

1. New file `foo.html`
2. Set indentation to `Tab size: 4` from Brackets 
3. Write <h1>Foo</h1>
4. Try to indent it with by pressing tab
5. Text doesn't move at all

**Comment by abose** [comment]
Closing as fixed.
