### ISSUE TITLE
White screen while trying to load .psd file

### ISSUE THREAD

**Issue by mistvan** [adobe/brackets#11966]
Hi guys,

brackets editor v1.5 is unresponsive and with white screen while I tried to load mentioned .psd file.
https://www.dropbox.com/s/51c8r4hsbgdqx22/kasa_web_final_compressed.psd?dl=0

Online via adobe cloud it is working fine as expected.

I had no issues with .psd files till now and I can open them without issues.

Many thanks

**Comment by petetnt** [comment]
Closing as deprecated as Extract isn't supported anymore.
