### ISSUE TITLE
Can't Launch Brackets in openSuse 42.1

### ISSUE THREAD

**Issue by mjeandon** [adobe/brackets#11969]
with version 1.5.0 or 1.4 also
I have an error:
libgcrypt selftest: binary  (0): Échec de l'autotest (/usr/lib64/.libgcrypt.so.11.hmac)
Ohhhh jeeee: ... this is a bug (global.c:137:global_init)

**Comment by petetnt** [comment]
See this #10255 issue for a fix / workaround. The Brackets Linux community is also looking for contributors who could fix this to the main branch (among other Linux related things)

**Comment by ficristo** [comment]
Closing as a duplicate of https://github.com/adobe/brackets/issues/10255
