### ISSUE TITLE
Windows, icons at toolbar are invisible

### ISSUE THREAD

**Issue by sergiodiezdepedro** [adobe/brackets#11975]
I've installed Brackets with the official installer and the icons at the toolbar and the images for the extensions manager don't show
![2015-12-05 18_59_10-curso_javascript_falcon - brackets](https://cloud.githubusercontent.com/assets/15799952/11609254/62088be6-9b82-11e5-8853-d6d97b066e34.jpg)

![2015-12-05 18_58_44-curso_javascript_falcon - brackets](https://cloud.githubusercontent.com/assets/15799952/11609257/76a56178-9b82-11e5-9c10-7679ebfe9a78.jpg)

Brackets 1.5

**Comment by sprintr** [comment]
Duplicate of #7208

**Comment by sergiodiezdepedro** [comment]
Thx, @sprintr , I've deleted two windows registry keys and all the svg icons in Brackets are visible now. For more information, see [#7208](https://github.com/adobe/brackets/issues/7208), @jbwCode comment

**Comment by sergiodiezdepedro** [comment]
Problem solved. Thanks a lot, pal.

Greetings

2015-12-06 14:48 GMT+01:00 Amin Ullah Khan <notifications@github.com>:

> Duplicate of #7208 <https://github.com/adobe/brackets/issues/7208>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/11975#issuecomment-162319162>.
>



-- 
Sergio Díez de Pedro

sergio.d.depedro@gmail.com
Móvil | 637 804 779
Fijo | 918 907 302
-------------------------------
http://sergiodiezdepedro.wordpress.com/ <http://about.me/pezhammer>

<http://instagram.com/pezhammer>
