### ISSUE TITLE
Unable to split the screen and add the live preview and code side by side in the newer version

### ISSUE THREAD

**Issue by gmj06** [adobe/brackets#11971]
I am a newbie to Brackets

I want to have the live preview and my code side by side but unable to do that

could you please guide me through how I can do this in windows 8.1

Thanks in advance
gmj06

**Comment by abose** [comment]
Live preview only works with external browsers in brackets. You can use windows snap to place brackets and the browser window side by side while doing live preview.
There are extensions like `Html Designer` which does things similar to your needs, check it out in the extension manager.
Please upvote this feature in trello https://trello.com/c/YG0BBlrl/302-2-live-preview-within-a-brackets-window for native support.
Closing new feature request as this is already tracked in trello.

**Comment by gmj06** [comment]
Hi Arun,

Thank you for the reply

But, what I want to know is how to get the Brackets gird to resize the window and accommodate the live preview window beside the code. I saw this in one of the web development video. But the instructor does it so quick, I couldn't figure it out how to implement 

Best Regards,
gmj06

**Comment by gmj06** [comment]
Hi Arun,

Please find the attached images which I want to know how to implement

![brackets_grids](https://cloud.githubusercontent.com/assets/7741922/11570974/ec5ad856-99ae-11e5-947e-dfd9b3b1cf44.jpg)
![brackets_code_livepreview](https://cloud.githubusercontent.com/assets/7741922/11570975/ec5f1cc2-99ae-11e5-8e10-8182ab9bc4ad.jpg)

Thank you
gmj06

**Comment by gmj06** [comment]
Hi Arun,

Thank you for the reply

But, what I want to know is how to get the Brackets gird to resize the
window and accommodate the live preview window beside the code. I saw this
in one of the web development video. But the instructor does it so quick, I
couldn't figure it out how to implement

Please find the attached images for your reference.

Any help is really appreciated

Best Regards,
gmj06

**Comment by abose** [comment]
It seems to be an extension , could you give the link for the video?

**Comment by gmj06** [comment]
That is a paid course "Ultimate Web Designer & Developer Course" from Udemy.com (Lecture 47). Unable to download the videos

**Comment by abose** [comment]
ok. That should be an extension in brackets, brackets does not natively support the grid thing shown in the screenshot. (Or that i am not aware of this feature).
@petetnt

**Comment by petetnt** [comment]
I think that in that video/screenshot the screen is just vertically split 50%/50% with Brackets and Google Chrome too.

You can easily achieve this in Windows 8 (and up) but first taking the Brackets window and dragging it all the way to the left side of the screen: when you release the window it should now be 50% of the screen. Then repeat the process to the Chrome window.

You can also use hotkey `Windows Key + Arrow Left` and `Windows Key + Arrow Right` to do it even faster.

**Comment by ficristo** [comment]
If it is only a matter of "split" the window, you can do that in Windows 7 too with the method of @petetnt.
On newer version of OSX just long press the small green button on the top left of the window of Brackets and you should be able to put the window of Brackets on one side of the screen.

**Comment by gmj06** [comment]
Thank you all for helping :)

**Comment by abose** [comment]
:+1:

**Comment by Hebatelniel** [comment]
Hi, 
I need to make a brackets window always on top of other windows.. how can i do this??

**Comment by petetnt** [comment]
@Hebatelniel Hey, maybe something like this would help at least on Windows: https://www.howtogeek.com/196958/the-3-best-ways-to-make-a-window-always-on-top-on-windows/

**Comment by kveeswaran** [comment]
> Thank you all for helping :)

Hi GMJ..  In that video instructor is using different version. I downloaded the latest version Release 1.14 build 1.14.2-17770. I am also not able to bring the "LIVE Preview" to the right split.... Did you got the solution.

Your help is much appreciated

BR
Eeswar
