### ISSUE TITLE
Hidden files showing

### ISSUE THREAD

**Issue by Vickmnc84** [adobe/brackets#11973]
I really want to use Brackets, migrating from Espresso. I have a issue with hidden files like .DS_Store showing in the sidebar. Can you please advise how to remove them?

![screen shot 2015-12-04 at 7 25 45 am](https://cloud.githubusercontent.com/assets/6153018/11589707/88f7169e-9a58-11e5-9901-5ba068eb6c22.png)

**Comment by mseiler025** [comment]
I'm using Brackets for Windows and I think .DS_Store files are hidden by default, but this may be different for Mac.

You could try this extension:
https://github.com/zaggino/brackets-file-tree-exclude

or you could edit the _exclusionListRegEx in src\project\ProjectModel.js if running from source (how to run from source - https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets)

you may be able to edit the _exclusionListRegEx in main.js and main.js.map in the installed app, but I wouldn't recommend that (just run from source and edit the _exclusionListRegEx in ProjectModel.js)

**Comment by Vickmnc84** [comment]
My Brackets broke! Got to uninstall. Please fix this.

**Comment by mseiler025** [comment]
If you tried running from source and got an error message you have to fetch submodules (step 4 under setting up your dev environment on this page - https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets)

also if this is what happened, without uninstalling and reinstalling, try just deleting the repo you cloned/downloaded

I recommend just using the extension - https://github.com/zaggino/brackets-file-tree-exclude

**Comment by Vickmnc84** [comment]
I used that extension.

**Comment by Vickmnc84** [comment]
Finally got it to work, Thanx. I LOVE this code editor! Keep up the good work guys.

Scott

**Comment by abose** [comment]
Closing as answered.
