### ISSUE TITLE
Syntax highlight for new files

### ISSUE THREAD

**Issue by xylodev** [adobe/brackets#11974]
When I create a new file, let's say a scratchpad for editing complicated SQL query, I am not able to select file type and to get proper syntax highlight unless I save this file on the disk.

Would it be possible to implement such a feature, similar to the Sublime Text, which allows you to select desired syntax highlight regardless the file is saved on the disk or not.

**Comment by abose** [comment]
Duplicate of https://github.com/adobe/brackets/issues/9409 
Closing.
