### ISSUE TITLE
Errors/Warnings don't know how to fix them - Need help!

### ISSUE THREAD

**Issue by CoolhandLM** [adobe/brackets#11976]
Receiving some errors/warnings not sure how to fix them.

Errors: https://gyazo.com/c0b84cbeba382fe58da61327429b7154
-------------
Warnings: https://gyazo.com/f152596556a2a6d0b3d03e291184e841
--------------
Once, you open the Gyazo links. *** Click the image to zoom. ***

**Comment by swmitra** [comment]
@CoolhandLM Guess the registry for 'extensions-rating' extension is not reachable. Reload brackets without extensions and confirm whether you see these errors. If not then this is not issue with brackets.

**Comment by CoolhandLM** [comment]
I reloaded brackets without extensions and I didn't show up.

**Comment by CoolhandLM** [comment]
Doesn't happen when the extensions disabled. @swmitra

**Comment by swmitra** [comment]
These errors normally won't cause any trouble in brackets usage, but if you don't want the errors then uninstall 'extension-rating'. You can start a dialog with  the extension developer to resolve the issue. 

I will be closing this as this is not a brackets issue.

**Comment by swmitra** [comment]
Closing as not a brackets issue.
