### ISSUE TITLE
Search project not working on folder root

### ISSUE THREAD

**Issue by senyasocial** [adobe/brackets#11977]
I am using Brackets 1.5 on OSX 10.11. When I open a directory and press COMMAND+SHIFT+F to search all files in that directory (project), the files in the root of the directory are not included in the search, only files in subdirectories within the current working directory. Even though the search query exists within files within the root of the directory, the search returns no results for those files.

**Comment by abose** [comment]
can you go to `help>health report` and comment it here?

**Comment by senyasocial** [comment]
{
    "uuid": "85bde6c6-e214-4bb6-bac9-944d6d6d1bee",
    "snapshotTime": 1449522456910,
    "os": "mac",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.5.0 Chrome/39.0.2171.36 Safari/537.36",
    "osLanguage": "en",
    "bracketsLanguage": "en",
    "bracketsVersion": "1.5.0-16538",
    "fileStats": {
        "openedFileExt": {
            "php": 246
        },
        "workingSetFileExt": {
            "php": 33
        }
    },
    "searchDetails": {
        "searchNew": 44,
        "searchOnReturnKey": 36,
        "searchInstant": 87
    },
    "projectLoadTimes": "",
    "fileOpenTimes": ":72(112)274[41]:79:74(133)188[45]:94(129)184[39]:74(155)210[46]:44(97)120[31]:56(103)146[36]:44(73)120[28]:96(103)109[7]:44(75)106[29]:82(178)224[48]:79:34(67)84[24]:83(154)227[56]:81(208)387[106]:65(124)181[47]:116:65(115)195[49]:196:69(127)198[46]:156:30(73)101[31]:66(80)93[14]:175:73(112)151[39]:87(122)159[26]:46(71)108[27]:35(51)74[17]:88(114)148[25]:50(79)98[21]",
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": [
        {
            "name": "donutteam.disableautoclose",
            "version": "1.0.0"
        },
        {
            "name": "no-fade-in-split-view",
            "version": "0.0.1"
        },
        {
            "name": "qw0101.animations-deactivator",
            "version": "1.0.0"
        },
        {
            "name": "open.recent.file",
            "version": "0.5.7"
        }
    ],
    "bracketsTheme": "light-theme"
}

**Comment by abose** [comment]
There doesn't seem to be any problems with search in health report. Brackets will search through all `text` contents of the project. Could you check if you have not applied any search filters and that regexp mode search is disabled.

**Comment by senyasocial** [comment]
no filters, no regexp mode, still not searching text contents of php files in the root of the currently open folder

**Comment by senyasocial** [comment]
![screenshot 2015-12-08 17 14 13](https://cloud.githubusercontent.com/assets/16092767/11649876/7197fe6c-9dcf-11e5-9c6f-ed0d1c9cb228.jpg)

**Comment by abose** [comment]
can you go to `debug>open preferences file` and set preference `"findInFiles.nodeSearch": false` and repeat the search?

**Comment by senyasocial** [comment]
ah, never mind, found it. i was looking in the preferences file you pointed to and realised from the tag:

"fileFilters": [
        {
            "name": "Default",
            "patterns": [
                ".DS_Store",
               "index.php",
                "*.svg"
            ]
        }
    ],

i'd told it ages ago not to search in index.php files via the exclude default, back when i was calling everything index.html and .php were just for header redirects, and had forgotten i'd done it. removed that line, it works now.

thanks for your help and time!
