### ISSUE TITLE
Switching to ESLint

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#11984]
Branched/continued from #11644, #11693

This issue was created to track down moving to ESLint separately from the existing PR (and the general ES6 support)
- [x] Update Brackets core code to ESLint (done in #11693)
- [x] Integrate ESLint to Brackets core @zaggino (https://github.com/adobe/brackets/pull/11693#issuecomment-162841573)
- [ ] Decide what to do with the existing linter (JSLint)

The integration part should be easy but what about the third box? Possible options include:
- Make ESLint the preferred linter and let the user use JSLint if the user decides to do so (confusing to those who have just used JSLint in the past)
- Make ESLint the preferred linter and remove JSLint altogether (spinning it to non-core extension) (similar issues as above)
- Just let them exist side by side and the let the user configure the settings (most confusing as files get linted twice?)
- Provide UI to select the preferred linter on first launch of Brackets 1.x (most user friendly, needs UI work etc.)

@abose @ficristo @MarcelGerber

**Comment by ficristo** [comment]
I've a biased opinion since I don't like particularly JSLint, but if we want it still in core it should be at the least updated.

**Comment by abose** [comment]
Modified 3. We could default to ESLint only and provide a preference to enable JSLint also.

**Comment by zaggino** [comment]
Submitted a PR https://github.com/adobe/brackets/pull/11988

**Comment by tclzcja** [comment]
Since the brackets-shell ticket has been merged, does that mean ESLint will be formally included in Brackets 1.8 release? Thank you!

**Comment by ficristo** [comment]
@tclzcja no, that ticket is only about to use ESLint to lint brackets-shell code.
You will have still to use an extension for 1.8 for your code.

**Comment by petetnt** [comment]
What's the status of this?

**Comment by zaggino** [comment]
I can setup a PR for "Integrate ESLint to Brackets core" if desired.

**Comment by petetnt** [comment]
Shipped in 1.11.
