### ISSUE TITLE
Data encoded on unexpected closing of application

### ISSUE THREAD

**Issue by wolf00** [adobe/brackets#11987]
The data is encoded on unexpected forced closing of application due to some reason. I am using Brackets on linux and I am not able to recover my data so have to write it again. Please fix this issue.

**Comment by petetnt** [comment]
Data loss is always unfortunate, seems that your data is getting corrupted when file explicitly closes, You could try my [brackets-persistent-history](https://github.com/petetnt/brackets-persistent-history) extension, which should enable you to undo the file to the last working state before the crash.

For the unexpected closing issue itself, do you have any steps that can be reproduced to redo the issue?

**Comment by wolf00** [comment]
Thanks for your advice, I will try that extension.
For redoing the issue I don't have any specific steps because I think their
is a problem with my Ubuntu version which goes into deadlock very
frequently so I have to close everything unexpectedly.

Thanks and Regards,
Rahul lad
