### ISSUE TITLE
Integrate an encoding plugin

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#11986]
Today I was bitten again by a script not in UTF-8 which cannot be opened in Brackets.
I tried to convert it in UTF-8 (with and without BOM) with Notepad++, but Brackets still refused to open it.
(I changed the original file and now I cannot replicate the exact problem)

Looking in the extension manager I found this plugin:
https://github.com/Hiromi-Ayase/brackets-shizimily-multiencoding
With some very (much) stupid examples I wasn't able to detect the right encoding but I was able to open the file and change the encoding so the file looked right.

So I'm proposing to integrate it in the core.
(Of course we need the consensus of the author and more testing)

**Comment by petetnt** [comment]
Related (in the long running history of encoding in Brackets): #11525, #10583, #3898

**Comment by ficristo** [comment]
I looked briefly at the plugin code and it seems to "mess" with File prototype.
So probably cannot be integrated but IMHO still worth to check out.
