### ISSUE TITLE
Shortcut to comment line pls

### ISSUE THREAD

**Issue by Marcuccio** [adobe/brackets#11997]
We need a easier way to comment line

**Comment by redmunds** [comment]
It's *Edit > Toggle Line Comment* in the menu. The shortcut should be listed next to it (which is different based on your OS).

If there is no shortcut listed, then there's probably a conflict with an extension you have installed. Read [this article](https://github.com/adobe/brackets/wiki/User-Key-Bindings) to learn how to set your own shortcuts.

**Comment by abose** [comment]
Feature already present. Closing.
