### ISSUE TITLE
keyboard shortcut

### ISSUE THREAD

**Issue by andrewVoyager** [adobe/brackets#11999]
This is not an issue but is very annoying.
My keyboard does not have the brackets '{' '}'. I must use the combination ALT+123 or ALT+125, but there is a function in the program 'collapse all ALT+1' that keeps me from creating the brackets just because when I press ALT + 1 immediatly all lines are compressed.
Please modify this function with another key combination, so I can create... brakets easly.
Thanks

**Comment by ficristo** [comment]
It is impossible to create shortcuts that are good for everyone.
But it is possible to change the original shortcuts:
`Debug`->`Open User Key Map`
and in the overrides section you can put something like 
`"Alt-9": "codefolding.collapse.all"`
So now you can use `Alt-9` to collapse evrything.

See here:
https://github.com/adobe/brackets/wiki/User-Key-Bindings
You should look the `Display Shortcuts` extension too.

**Comment by andrewVoyager** [comment]
Thanks a lot!!!!!!

**Comment by abose** [comment]
Closing as this is a user preference.
