### ISSUE TITLE
Extract for brackets can't add new PSD

### ISSUE THREAD

**Issue by TolotraRam** [adobe/brackets#12001]
Hi great job,

I have added 2 PSD before and worked like a charm, now i wanted to add another one and see that all functionnality to add another PSD is disable so is it limited to 2 PSD ? How can we remove older PSD?  or it is a bug?

Note : I use brackets 1.5 with extract on windows 7.

Thanks

**Comment by ficristo** [comment]
Extract has been deprecated: http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/
Closing.
