### ISSUE TITLE
Brackets: Installing problems :-(

### ISSUE THREAD

**Issue by UuserT** [adobe/brackets#12007]
Hi,

I visited brackets.io and klicked on the download-button to get it but it doesn´t work (or am I too stupid? ^^). I only have the " Brackets.1.5Extract.msi" in my download files then and if I try to start it it just displays this Free Zip Opener 1.0 and says I have to type in a password :-(
Has anyone a solution? Would be great!

Thank you in advance!
![unbenannt](https://cloud.githubusercontent.com/assets/16307374/11814178/afa58636-a345-11e5-9c4b-551fd8e81419.JPG)

**Comment by mseiler025** [comment]
Is this happening for all .msi files you try to run?  If so, you might need to change the default program for .msi files to Windows installer.

**Comment by UuserT** [comment]
Thank you!! This was the solution!
