### ISSUE TITLE
[Registry] Download counter broken?

### ISSUE THREAD

**Issue by uniphonic** [adobe/brackets#12010]
The download counter for extensions now seem to be broken. This seems to have started happening at the exact same time as the fix was implemented for https://github.com/adobe/brackets/issues/11932 .

If you have the "Extensions Rating" extension installed it shows download counts for all items, but all the download counts seem to have frozen since the 11932 fix was made (everything that was uploaded since then has remained locked at 0 for many days, though I know it's been downloaded many times). Maybe the fix that was made for issue 11932 broke something?

**Comment by lkcampbell** [comment]
Seems like we should at least prioritize and assign this problem. It's been down for quite a while now and, every day, we lose information about how people are using extensions.

**Comment by uniphonic** [comment]
I agree. :-)

**Comment by kolipka** [comment]
Me too :)
I checked the brackets-registry and noticed that there is script:

`downloadStats/downloadStatsUpdater.js`

it will upload stats to registry server. It should be called propably in cron. Can someone check is it actually running?
The second thing is that in my case in lib/downloadData.js:36:

`req.ip === "127.0.0.1"`

is false because req.ip is '::ffff:127.0.0.1'. req.host is localhost, so this part is OK.

**Comment by ingorichter** [comment]
The data for the downloads isn't lost. If the download data doesn't end up in the registry, then it looks like the `downloadStats/downloadStatsUpdater.js` is not running anymore. I set it up to run the script as a cron job.

@kolipka that is definitely an issue.

I don't have access to the registry server anymore. Somebody revoked my permissions and I can't have a look anymore. Perhaps @ryanstewart can help out to get access to the machine and inspect the current setup.

**Comment by lkcampbell** [comment]
@ingorichter okay, glad to hear the data isn't lost anyway :).

**Comment by ficristo** [comment]
@adobe/brackets-committers after 10 months someone at Adobe does care for this issue?
Can non adobe people have access to this machine?

**Comment by uniphonic** [comment]
@ryanstewart @madanbn @nethip Any chance one of you could take a look?

**Comment by ingorichter** [comment]
I don't have access to the machine anymore. Otherwise I could have a look

**Comment by saurabh95** [comment]
@ingorichter I have access to the machine and I searched for currently running cron jobs I was not able to find any, so I will try to add that cron job. 
Just to be sure we need to run `node downloadStats/downloadStatsUpdater.js` ?
Do you remember the time interval that was set for running the above cron job?

**Comment by ingorichter** [comment]
@saurabh95 which user did you use to find the cron job? Did you run `crontab -e`? And that was empty?
Yes, that is the script. The script ran every 15 mins.
I tried to access the machine, but I didn't have the password to unlock the file that contained the certificate to establish a SSH connection.

**Comment by saurabh95** [comment]
@ingorichter  I was logged in as "brackets-team". I checked for cron job using `crontab -l` , it showed nothing and then I used `crontab -e` to check if it was edited or not, there were no edits in that.
Now I have updated the logs for the past 14 months and also started a cronjob for every day(will change it to every 15 minutes). You can check the registry.json file, it has updated download counts now :)

**Comment by ingorichter** [comment]
@saurabh95 thanks for the update. Let me check the json file. :-)

**Comment by swmitra** [comment]
Closing the issue now.
