### ISSUE TITLE
Smart indent missing important functionality for PHP tags

### ISSUE THREAD

**Issue by baileyherbert** [adobe/brackets#12014]
It is becoming increasingly popular to indent PHP code with a tab between the opening and closing tags. For example:

```
<?php
     // hello world

     function hello() {
          echo "Hello world";
     }

     | <-- this is where the cursor should go for new lines [based on my code above]
| <-- this is where it currently goes
?>
```

However, with **Smart Indent** enabled, it will not add that tab at the beginning of each new line I create, unless it is inside brackets (such as the function). It works fine with Smart Indent disabled, as the previous tab position is kept consistent.

My suggestion is to check how the tab was written on the previous line and keep it consistent, like when Smart Indent is off, but only when not writing code inside of brackets (Smart Indent handles that properly):
- It should see that there was an intentional tab before the } in the code above and continue to add the same number of tabs.
- It should see that there was an intentional tab on the line below the "<?php" tag, and it should continue to add the same tabbing on new lines below it.

If the developer does not manually add any tabs, then Smart Indent should handle indentation the same way it currently does.

Sidenote: I've been manually adding a tab on each new line like this for well over a year. My tab key is fading. :+1:

**Comment by petetnt** [comment]
This might be worth reporting to the [CodeMirror](https://github.com/codemirror/CodeMirror/issues) repo, but you might need some numbers to back up the **increasingly popular** part of the claim to land it in the core. I am not a PHP developer or expert myself, but quick googling suggest that `PSR`[0] styleguides are the defacto standard used in PHP development and none of them apply any initial indent after the tag (as do none of the other style guides that I found).

However it might be feature worth of a Brackets Extension, as at least `PHPStorm` offers initial indentation support.

[0] https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md, 
     https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md
     https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md
     https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md
