### ISSUE TITLE
No intuitive way to stop auto-formatting my tabs

### ISSUE THREAD

**Issue by balmyBanzai** [adobe/brackets#12018]
I tried to get on Slack with you guys, but the link didn't work, so sorry in advance for bugging something that's probably a feature, but I can't find out how to stop it.

So, I've got this squished line of code from a Node tutorial I'm working on:

```javascript
    request.on("error",function(error){console.error(error.message);});
```

Now, I want to un-squish it to look more like this (my preference):

```javascript
    request.on(	"error",
    			function(error)
    			{
    				console.error(error.message);
    			}
      		  );
```

Now, I have zero problems doing that in Notepad++, but with Brackets, tabs are getting crazy up in here! First linebreak I make, and it tabs three times. Not cool for me, but hey, it's a shortcut for somebody (but seriously, how do I stop this madness?!). I shift+tab and monkey around to finally 
bring the spacing where I want it, so now I'm here:

```javascript
    request.on(	"error",
    			function(error)
    			{console.error(error.message);});
```

Alright! We're almost there! :D Now, I go to linebreak between the '{' and 'c' and bam, now it looks like this:

```javascript
    request.on(	"error",
    			function(error)
    			{
    		console.error(error.message);});
```

So yeah, the line with console on it is now *behind* the opening curly brace... I don't know what the heck is going on, and I'm sure it's fantastic for whatever it was designed to do, but I'd like to know how I can actually control my tabs instead of some other tabbing design being shoved down my code's throat.

Notes: I've done with with and without extensions enabled, and I use Windows 10 as my OS.

![fileandjson](https://cloud.githubusercontent.com/assets/16359043/11966619/b6ff85b4-a8b1-11e5-94ba-e3a710d278ea.jpg)

**Comment by abose** [comment]
Brackets uses jslint style. 
To alter this behavior, try changing tabs and intent related preferences. You will get code hints and autocomplete for the preferences file in brackets. 
See https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences for help.

**Comment by abose** [comment]
Closing long pending issue. Please feel free to reopen if you still face the problem.
