### ISSUE TITLE
Extension manager does not work

### ISSUE THREAD

**Issue by dome68** [adobe/brackets#12013]
My extension manager does not work properly, when i launch the extension manager it stops in the classic view but i don't see all extensions installed, like in the view that i attached here.
All i can do is close it without update my extensions.
![brackets - extension manager](https://cloud.githubusercontent.com/assets/8546163/11872973/878e975c-a4d8-11e5-9e95-3c6e9472f6de.jpg)

**Comment by petetnt** [comment]
Are there any errors in the Developer Tools `(Debug -> Show Developer Tools / F12)`? Either in console or the network tab.

**Comment by dome68** [comment]
Thanks Pete, I followed your suggestion but I didn't find errors in the
console or network tab.

2015-12-17 19:49 GMT+01:00 Pete Nykänen <notifications@github.com>:

**Comment by petetnt** [comment]
When you open the network tab and open the extension manager, do you see the GET made to `registry.json`? 

The response should look something like this:

![image](https://cloud.githubusercontent.com/assets/7641760/11891613/e72dffd2-a568-11e5-8627-cfeb2e862e8c.png)

**Comment by dome68** [comment]
Sorry Pete, but I didn't find registry.json; take a look to the attached
file.
I suppose the response is really different because Brackets doesn't load
the extension files.

2015-12-18 8:24 GMT+01:00 Pete Nykänen <notifications@github.com>:

**Comment by petetnt** [comment]
@dome68 Sorry, attachments don't show up on Github. You can, however, copy and paste the images to the textfield in Github and the image file should embed itself.

I am fairly certain that this is an firewall issue. Can you check if you can access https://s3.amazonaws.com/extend.brackets/registry.json on your browser? If you can, make sure from your firewall settings that Brackets is allowed to reach that endpoint too.

**Comment by dome68** [comment]
Sorry, here is the image.
![brackets - no json](https://cloud.githubusercontent.com/assets/8546163/11925108/6eb49776-a7b8-11e5-9538-f266ce6b6141.jpg)
If you need something else just ask. Thanks.

**Comment by dome68** [comment]
I don't know how but now the extension manager works properly.
Anyway, thanks to petetnt for the interest.

**Comment by petetnt** [comment]
@dome68 great that you got it working :+1:
