### ISSUE TITLE
Status Bar won't hide

### ISSUE THREAD

**Issue by o-cha** [adobe/brackets#12017]
Hello, 

I'm having an issue with the status bar not hiding. I accidentally hit some key combination (unsure which) that opened it, and I cannot get it closed. The "hide" button does nothing, and I can find no key shortcut on how to hide it. 

Any help is greatly appreciated!

For reference: 

![statusbar](https://cloud.githubusercontent.com/assets/16405042/11963159/e67a66dc-a8b2-11e5-850f-9df38f0dfc83.png)

Thanks!

**Comment by Denisov21** [comment]
Hi @o-cha 
In Windows you must press: CTRL+ALT+H

**Comment by o-cha** [comment]
That's only closing the side navigator for me and not the bar at the bottom. Thanks!

**Comment by o-cha** [comment]
Disregard this. I figured it out. It was an extension causing it to show.
