### ISSUE TITLE
Code Tidy-Up feature

### ISSUE THREAD

**Issue by TheReapersSoundware** [adobe/brackets#12023]
I use Brackets frequently and absolutely love it, but i constantly code fast and don't have time to keep things clean. I would love to see an option to clean up the code, automatically correcting indents and unnecessary spaces and so on.

**Comment by petetnt** [comment]
Hi @TheReapersSoundware, check out great extensions such as [Brackets-Beautify](https://github.com/brackets-beautify/brackets-beautify) which can do those things for you :nail_care: 

There are many other alternatives too, which you can check out through Extension Manager (File -> Extensions)

**Comment by abose** [comment]
closing as answered.
