### ISSUE TITLE
Feature request : Sync preferences/extensions between remote Brackets apps on different computers

### ISSUE THREAD

**Issue by N0bl3** [adobe/brackets#12021]
i find it very difficult to reinstall all the extensions i have when i have to work on a new computer when it would be possible to make a "config" file synced via maybe the AdobeID.
Am i missing something?

**Comment by mseiler025** [comment]
@N0bl3 see https://github.com/adobe/brackets/issues/11916

**Comment by N0bl3** [comment]
great! I close this issue then.
