### ISSUE TITLE
Shift O is a shortcut

### ISSUE THREAD

**Issue by pfeytser** [adobe/brackets#12029]
Typing Shift + O causes a dialog to open that says, "There is no application set to open the URL .... Search the App Store for an application that can open this document, or choose an existing application on your computer."

I'm using the latest version of El Capitan on my Macbook (10.11.12).

**Comment by petetnt** [comment]
Cannot replicate on Yosemite (or Windows 10 for that matter) myself.

**Comment by abose** [comment]
This should be unrelated to Brackets. Is this still reproable?

**Comment by pfeytser** [comment]
It happens on my work computer, but not my personal one (both Macs). Can't figure out why this is happening.

**Comment by abose** [comment]
Does this happen only with brackets?

**Comment by abose** [comment]
Does this happen only with brackets?

**Comment by pfeytser** [comment]
Yes

**Comment by abose** [comment]
can you try `debug>reload without extensions` and see the behavior.

**Comment by pfeytser** [comment]
Yep, that fixed the problem! Thank you!!!

**Comment by abose** [comment]
IT might be some extensions that caused it.
Try uninstalling some extensions to narrow down which one is causing the problem
Closing as extension problem.
