### ISSUE TITLE
Error in Saving Image`

### ISSUE THREAD

**Issue by karthikmm** [adobe/brackets#12020]
![screenshot from 2015-12-23 17 22 16](https://cloud.githubusercontent.com/assets/9219943/11976082/a21c93b4-a99a-11e5-988c-90fff4aa8b27.png)

Can any 1 help me out with this issue as im unable to use any images for my web development with this issue

Thanks in advance.

**Comment by abose** [comment]
the file or its parent directory is read only or you do not have permission to save to the image location.

**Comment by abose** [comment]
Closing long pending issue. Please feel free to reopen if you still face the problem.
