### ISSUE TITLE
SlacK Invite Request Broken

### ISSUE THREAD

**Issue by viruscmd** [adobe/brackets#12033]
The Heroku app for requesting a slack invite is broken.
![screen shot 2015-12-28 at 5 03 45 pm](https://cloud.githubusercontent.com/assets/2870626/12026230/4646fe32-ad85-11e5-8588-b1eef717a690.png)

**Comment by abose** [comment]
Shouold be up now.

**Comment by mikulabc** [comment]
still nothing https://brackets-slack.herokuapp.com/
![proof](https://i.imgur.com/kOVjVFE.png)
