### ISSUE TITLE
How to see all CSS color names in Code Hints

### ISSUE THREAD

**Issue by OrlySedl** [adobe/brackets#12032]
I would like to see all the names of colors. But Code Hints does not show all the colors at once, but only to a certain color. for example as here
![default](https://cloud.githubusercontent.com/assets/16467397/12024378/755d909e-adb4-11e5-90ea-6b17580bb4dc.png)
Is it possible to set or change, so I could see them all.

**Comment by sprintr** [comment]
Set `maxCodeHints` preference to `148` to see all the colors in the code hints.

```json
{
    "maxCodeHints": 148
}
```

**Comment by OrlySedl** [comment]
Thanks!!!
