### ISSUE TITLE
Switching through the Working files

### ISSUE THREAD

**Issue by ile** [adobe/brackets#12030]
Normally when switching through the tabs you can use Ctrl-Tab (next tab) and Ctrl-Shift-Tab (previous tab). This works in most text editors and in most browsers.

Bracket's doesn't seem to support it.

Actually when I press those key combinations, the working file *is* changed, but it's not next/previous, it's more like a random switch. 

So, this is a suggestion to improve this aspect. Thanks.

**Comment by swmitra** [comment]
@ile Ctrl-Tab helps you navigate the working set in MRU order. It's not random. If you want a visually predictive behaviour like navigating the working set in display list order , you can use Ctrl-page down/up keys.

**Comment by ile** [comment]
Ah.

But I'm missing the "usual way", because I'm using the mouse to switch files (or tabs) with the mouse's scroll wheel that can be clicked to left and right.

Perhaps the order can be changed with an extension?

**Comment by swmitra** [comment]
@ile you can override the default shortcuts if you prefer to. But if I understand your request clearly, to me it looks like an extension idea.

**Comment by ile** [comment]
Right, thanks. I found [these](https://github.com/adobe/brackets/wiki/Brackets-Shortcuts):

```
Tab	Ctrl-Shift-Tab	navigate​.prevDoc	Previous Document	Brackets
Tab	Ctrl-Tab	navigate​.nextDoc	Next Document	Brackets
```

Would I corrent to assume, that there exists something like `navigate​.prevDocInVisualOrder` that I could use right now to map a key to?

**Comment by ile** [comment]
Ok, found them.

```
      "Ctrl-Shift-Tab": "navigate.prevDocListOrder",
      "Ctrl-Tab": "navigate.nextDocListOrder"
```

Works just as it should now. Thank you. This issue can probably be closed.

**Comment by ile** [comment]
Sorry if this is in a faq or somewhere, but if I could define two shortcuts to the same function, it would be nice:

```
"Ctrl-Tab,Ctrl-PageDown": "navigate.nextDocListOrder"
```

**Comment by swmitra** [comment]
Thank you @ile for quick confirmation

**Comment by swmitra** [comment]
Closing #12030.

**Comment by abose** [comment]
@ile checkout https://github.com/adobe/brackets/pull/12012 for new file navigation workflows that @swmitra contributed. IT should add new navigation shortcuts that is a bit more `predictable` than the current ones in place.
