### ISSUE TITLE
Beta 1.6 empty line indented

### ISSUE THREAD

**Issue by macbookandrew** [adobe/brackets#12036]
The 1.6 beta is doing something funny with indenting blank lines by 4px; as soon as you start typing, the indent is removed. Looks like it may be a CodeMirror issue?
![screen shot 2015-12-30 at 11 12 27 am](https://cloud.githubusercontent.com/assets/784333/12053354/419f1150-aee6-11e5-902c-f7b61f392cfc.png)

**Comment by ficristo** [comment]
It seems to me you have some extensions: can you reproduce without them?
`Debug -> Reload Without Extensions`

I cannot reproduce on the prerelase branch.

**Comment by macbookandrew** [comment]
Sorry…seems to be related to a Soft-wrap plugin I have installed: https://github.com/scriptin/brackets-indent-softwraps/issues/13

**Comment by ficristo** [comment]
No problem :smile:
If you'll find other issues don't be afraid to file bugs!
