### ISSUE TITLE
[Tracking] Update CodeMirror to a version > 5.10.1

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#12031]
Probably to do after Brackets 1.6 release.
The next version of CodeMirror should fix (at least):
 - https://github.com/adobe/brackets/issues/11683

And ~~there is a pending PR to add JSX support~~ now JSX is supported.

**Comment by petetnt** [comment]
Tracking the JSX support partially here: https://github.com/adobe/brackets/pull/12052 (needed the language change myself just now so I did the PR simultaniously)

**Comment by ficristo** [comment]
Codemirror 5.11 is out.
@MarcelGerber do you can / want do the update?

**Comment by ficristo** [comment]
Closing as the update has been merged.
