### ISSUE TITLE
Native title bar

### ISSUE THREAD

**Issue by Sigmanor** [adobe/brackets#12045]
Please make some option to enable native title bar. 

![brackets_native](https://cloud.githubusercontent.com/assets/7986067/12080187/b9f1eda8-b25b-11e5-8d36-8dd41978720a.png)

WIndows 10

**Comment by petetnt** [comment]
Is that the Linux version? There's a long running issue https://github.com/adobe/brackets/issues/7236 regarding that. If you have Linux native development experience `brackets-shell` could need your help.

**Comment by Sigmanor** [comment]
@petetnt I have WIndows 10 
Screenshot is shown how it can look like with native title bar.

**Comment by ficristo** [comment]
I dupe this against #12320, which I find i bit more clearer.
