### ISSUE TITLE
No more Menu Bar

### ISSUE THREAD

**Issue by AlexandreBT** [adobe/brackets#12040]
Hi,

I've the latest version of Brackets, since today, I can't see the menu bar on the top. I can resize the windows, acces to the menu, etc. 

I reseted the cache, but seems change nothing. I uninstalled / reinstalled the program. Same. 

![2016-01-02_12-11-30](https://cloud.githubusercontent.com/assets/206181/12074274/1a8da02a-b14a-11e5-813d-ea4900e3d822.png)

Thanks

**Comment by petetnt** [comment]
Never have seen that one before. You said that you reset the cache? Did you delete everything in `%Appdata%\Roaming\Brackets`? Take a backup of that folder first. If that doesn't work, delete the folder, remove the program and install it once again. If even that doesn't work, you could try reinstalling Chrome if there's some mix up with Chrome and CEF Brackets is using (that happened sometime ago too IIRC).

**Comment by ficristo** [comment]
Closing because without an answer. Feel free to reopen or open a new issue.
