### ISSUE TITLE
Problem starting Brackets! "Error Loading Project: error occurred when trying to load the directory <file path>"

### ISSUE THREAD

**Issue by ztrat4d** [adobe/brackets#12058]
Hey Bracketeers :)

I'm New to Brackets! Sorry if this issue is solved..... But Brackets no longer works for me. Every time I try to open the program it begins by trying to locate a file/folder that no longer exists on my Mac computer. Afterwards, nothing within the program (Debugger, Help, etc.) will respond. I've tried deleting and downloading the application on my comp several times but the problem persists. Please help. I've attached a screenshot of the error:

"Error Loading Project: error occurred when trying to load the directory <insert file path>. (error not found)."

![screen shot 2016-01-06 at 12 24 05 pm](https://cloud.githubusercontent.com/assets/16582836/12155152/7bb8b62e-b478-11e5-93c2-8ad2fe6c7692.png)

**Comment by petetnt** [comment]
Try deleting `brackets.json` and `state.json` from `~/Library/Application Support/Brackets/` (take backup copies first, they contain your preferences and current state).

**Comment by ztrat4d** [comment]
So weird! There isn't a Brackets folder in Application Support.... I'm on a Mac if that changes things.

**Comment by petetnt** [comment]
Nope, that should be the correct location. Weird. You could try searching for `brackets.json` on your folder if you are looking at the wrong `Application Support` folder though :cat2:

**Comment by ztrat4d** [comment]
hmm search doesn't seem to bring up anything. is there a more involved uninstall on mac that I can perform (other than dragging the app to the trash) that might locate and delete every Brackets file?

**Comment by petetnt** [comment]
I am not an MacOS expert myself :cat:  but I *think* that any uninstall *should* keep all the preferences etc.

If you checkout `Library/Application Support/`, make sure you check out `Users/ztrat4d/Library/Application Support` too.

**Comment by ztrat4d** [comment]
I can't seem to find any App support for Brackets on my Mac.... So weird. I guess the only thing left to ask is if you have any recommendations on another free code editor? lol

**Comment by petetnt** [comment]
Closing this, feel free to reopen if you still have this issue with Brackets 1.7.

**Comment by moeiscool** [comment]
where is this file on windows?

**Comment by zaggino** [comment]
on windows:
```
cd /D %HOMEDRIVE%%HOMEPATH%\AppData\Roaming\Brackets
```
