### ISSUE TITLE
Add right-click-->Copy/Paste

### ISSUE THREAD

**Issue by activegis** [adobe/brackets#12063]
Please add right-click-->Copy/Paste functions which most users are familiar with other code editors. I once saw someone else raise the suggestion but did not get attention.

Thanks a lot!

**Comment by petetnt** [comment]
Hi @activegis , there's an extension available for that! 

https://github.com/caphodel/brackets-additional-right-click-menu

To install it, go to File -> Extension Manager, search for `brackets-additional-right-click-menu` and hit install.

**Comment by activegis** [comment]
The extension is working great. Thanks a lot!

**Comment by petetnt** [comment]
Added to core with #12674
