### ISSUE TITLE
Brackets stops working if Adobe photoshop CC installed. 

### ISSUE THREAD

**Issue by monirulalom** [adobe/brackets#12061]
I installed Adobe photoshop CC and faced some problems in brackets . When I try to open a psd using extract it stops working , Same thing happens when I try to reload with extension . Now I removed Adobe photoshop CC , Brackets is working fine. How to run both together ?

**Comment by stevebeausejour** [comment]
First of all, are you still having this issue? If that is the case are you experiencing this issue on Windows or on MacOS?

**Comment by monirulalom** [comment]
Latest Brackets updates solved my problems on windows platform ,I know use of adobe extract is deprecated.
