### ISSUE TITLE
Can I turn off autocomplete?

### ISSUE THREAD

**Issue by Wallman93** [adobe/brackets#12066]
Hello, just getting in to html and css coding and I'd like as little help as possible to get into "good" habits. So, I'd like to close my own lines for now.

(apparently code wont show up in github, so I'll type around it) Whenever I type in a paragraph for example, the closing piece shows up right behind it, (/p) <---- like that. 

Is there anyway to turn this off? I don't want to get lazy right from the get-go... 

Cheers!

Edit: I've gone into the brackets.json and tried to add the closeTags setting, but I can't really get it to work. This is how my .json looks now in its' fully functional state:

{
    "fonts.fontSize": "12px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "livedev.multibrowser": true,
    "closeBrackets": false,
    "wordWrap": false,
    "showLineNumbers": true
}

When I add the closeTags, it does not turn purple like the others and whenever I open brackets again it just gives me the .json file and says I have to change it because it's formatted incorrectly. So if anyone know the correct way to set this up, please paste the entire .json file text here with closeTags set on false and I'd be forever grateful.

**Comment by petetnt** [comment]
Make sure that you have the correct parentheses and commas when editing the JSON-file

1. Open Debug -> Show Preferences File
2. Go to the `"closeBrackets"` part
3. add `"closeTags": true,` after it. You config should look like this:

```
{
  "fonts.fontSize": "12px",
  "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
  "livedev.multibrowser": true,
  "closeBrackets": false,
  "closeTags": false,
  "wordWrap": false,
  "showLineNumbers": true
}
```

**Comment by Wallman93** [comment]
@petetnt Thank you, that worked, sort of... the only issue now is that it "unpurpled" wordwrap and showlineNumbers and therefore still corrupting the file.

{
    "fonts.fontSize": "12px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "livedev.multibrowser": true,
    "closeBrackets": false,
    "closeTags": {"whenOpening": false, "whenClosing": false } 
    "wordWrap": false,
    "showLineNumbers": true
}
 
according to https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#list-of-supported-preferences

That's how you're supposed to arrange the closeTags-line.

Can you spot my error?

**Comment by swmitra** [comment]
@Wallman93 put a ',' after "whenClosing": false }.

**Comment by petetnt** [comment]
@Wallman93 great! :+1:

**Comment by Faramir24601** [comment]
Still works.
Also [relevant xkcd](https://xkcd.com/979/)
