### ISSUE TITLE
Creating new sub folders

### ISSUE THREAD

**Issue by GerhardKreuzer** [adobe/brackets#12077]
Hi,
there is no way to create new sub folders!!! Please add this feature, thanks.
Now I have to create the folder using the OS file system explorer and than the folder appears in the list.
Not really good user expiriance.

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
... ah, have to right click behind the last file. I tried to right click the root of my web site cause I want to create a subfolder there .... so maybe you can polish that a Little bit.
You also right click on a sub folder to create a sub-sub folder, so this 'feature' breaks the user expieriance, sorry.

With best regards

Gerhard

**Comment by petetnt** [comment]
You can also right click on any file that's on the same level as the level you want to create the folder to and select `New Folder` to create a folder on that specific spot.

**Comment by GerhardKreuzer** [comment]
thanks, but that breaks the ui expiriance, sorry.
