### ISSUE TITLE
Deprecation of Adobe maintained translations

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#12075]
I was doing the finnish translation and noticed this while reading the README.md under `src/nls`, the translation center has the following annoucement: https://translate.adobe.com/Announcement.html

> 
> Home
> EOL Announcement

> We love our international community! 

> A few years ago, we envisioned that our customers wanted to be involved in improving the quality of our products. We built the infrastructure that enabled our community to freely contribute feedback, vote on translations, propose new translations, and create new language offerings for some products. More than 650 contributors worked on 40 plus products and some 26 languages from program inception in 2011 until now.

> While quality work is never "done", we feel that we have achieved many of our objectives. Now is the time to reimagine how we will engage with our Adobe community to support international releases in an agile world, where innovation rules.

> We give heartfelt thanks to you, our generous international community, for supporting this translation initiative over the years. You have lent your time and talents and shown sincere dedication.

> As of this announcement, we will discontinue accepting contributions and will be closing down this site by Jan 31, 2016. You may contact us at Feedback. We would love to receive feedback about your experiences; hear your suggestions for the future; and address your concerns.

> Program managers, international engineers, architects and designers in Adobe Globalization in China, India, Romania and the U.S. have participated in this project over the years.

> Sincere thanks,
> Adobe Community Translation Team

https://github.com/adobe/brackets/tree/master/src/nls#adobe-maintained-translations

And the other link that says 
> Submit a proposal at the Adobe® Translation Center (ATC), under the Brackets product. At ATC, proposals can be voted on by peers and are eventually accepted by moderators.

states that:

>  Notice: We are now coordinating all translation efforts through the open source project at https://github.com/adobe/brackets

So the whole README.md could use a revision. Affects at least: https://github.com/adobe/brackets/pull/12044

**Comment by ryanstewart** [comment]
Ahh, good catch @petetnt. @nethip do we have a way for community users to submit suggestions for the Adobe-run translations? Our loc teams are taking care of es, fr, de and jp, correct?

Seems like we need to confirm those languages and then make the changes to the README.

**Comment by nethip** [comment]
@ryanstewart Our LOC team handles only JP and FR translations. The rest of the locales are community driven. I think filing bugs is the only way where community users can submit suggestions. I will go ahead and update README. Thanks @petetnt for pointing this out.

**Comment by nethip** [comment]
Raised [PR] (https://github.com/adobe/brackets/pull/12076) for the same.
