### ISSUE TITLE
Brackets should open non-UTF-8 files.

### ISSUE THREAD

**Issue by isonno** [adobe/brackets#12083]
If Brackets is intended for software developers, be aware they need to open all sorts of text files. Refusing to open a file because one character in it doesn't meet the expectations of some standards committee in Switzerland is frustrating.

The attached file is a snippet of some 90's-era source code with a funky apostrophe.  Display garbage where the apostrophe appears if you must, but refusing to open the file at all is broken.

[bracksample.txt](https://github.com/adobe/brackets/files/89611/bracksample.txt)

**Comment by petetnt** [comment]
There's a rather long running card on this Trello.com: https://trello.com/c/DShzQztM/731-support-encodings-other-than-utf-8 

See existing issues about encoding detection and BOM's) such as: https://github.com/adobe/brackets/issues/10475, 
https://github.com/adobe/brackets/issues/3898, 
https://github.com/adobe/brackets/issues/11525, 
https://github.com/adobe/brackets/issues/10583
