### ISSUE TITLE
Better html tag formatting

### ISSUE THREAD

**Issue by DrakeXiang** [adobe/brackets#12089]
Brackets' auto-complete function works good enough, only one thing bothers me: after I get a new tag pair, if I hit enter to jump to next line, the closing tag follows the cursor to the next line, but I prefer the closing tag go to the third line  align with the opening tag, and the cursor stays at the second line. As showed below:

_The way brackets behaves now:_
Sometimes this way:

```
<li>
    </li>
```

and sometimes this way:

```
<li>
</li>
```

_The way I want it to be:_

```
<li>
    //cursor
</li>
```

I'm new to programming and brackets, if this issue has been resolved in upcoming 1.6 then ... nevermind

**Comment by petetnt** [comment]
This seems to be working correctly on the [CloseTag](https://codemirror.net/demo/closetag.html) demo with most tags (<li> not included, as they are usually meant to be one liners...) but I cannot repeat either of the ways in Brackets myself.
