### ISSUE TITLE
Text in files move outside the visible window

### ISSUE THREAD

**Issue by arashsa** [adobe/brackets#12093]
Sometimes the text in a file moves outside the visible portion of the window. This has been happening a lot lately, and one way of fixing it is refreshing (cmd R on mac). I have included a picture to show the error. 

<img width="547" alt="screen shot 2016-01-18 at 02 28 42" src="https://cloud.githubusercontent.com/assets/4326328/12381501/68e65f62-bd8b-11e5-90bb-0ce210ad7511.png">

**Comment by petetnt** [comment]
@arashsa Have you tried if it occurs without extensions too (Debug -> Reload without Extensions)? It looks like it could be an theme issue

**Comment by arashsa** [comment]
@petetnt Looks like it might be due to the theme I'm using. Thanks!
