### ISSUE TITLE
Undo/redo often stops working after save

### ISSUE THREAD

**Issue by idosius** [adobe/brackets#12090]
Not sure when/why/how it reproduces, all I know is that suddenly it starts reproducing, especially for SCSS files. When it does it does start reproducing, then it only happens for a certain file and not other files. Restarting brackets makes it go away, for a short while, then it comes back.

**Comment by petetnt** [comment]
See https://github.com/adobe/brackets/issues/11826 for more information

**Comment by ficristo** [comment]
Closing as a duplicate of #11826
