### ISSUE TITLE
Syntax highlighting for multiple languages in one file

### ISSUE THREAD

**Issue by carinlynchin** [adobe/brackets#12097]
IE; html file with javascript inside (i know...its taboo, but thats how my employer wants it done). I know I can change syntax, but not both html and javascript.

**Comment by sprintr** [comment]
This is already supported by htmlmixed mode. In HTML you can write JavaScript inside `<script>` tags.

**Comment by carinlynchin** [comment]
nevermind...i realized it was, i was looking at another custom language we use

**Comment by carinlynchin** [comment]
my employer created his own compiling language and I confused that with js...
