### ISSUE TITLE
package architecture (amd64) does not match system (i386)

### ISSUE THREAD

**Issue by jeijeirenee** [adobe/brackets#12094]
I am running Debian 8 trying to install brackets 1.5 for my i686 laptop and I get this error when I attempt to run dkpg I get this:

root# dpkg -i Brackets.Release.1.5.64-bit.deb 
dpkg: error processing archive Brackets.Release.1.5.64-bit.deb (--install):
 package architecture (amd64) does not match system (i386)
Errors were encountered while processing:
 Brackets.Release.1.5.64-bit.deb

**Comment by ficristo** [comment]
I think you need to try the 32 bit version.
