### ISSUE TITLE
AutoComplete for variable names?

### ISSUE THREAD

**Issue by carinlynchin** [adobe/brackets#12098]
Does this exist ... I don't notice it, but if it doesn't, it would be a nice addition.

**Comment by petetnt** [comment]
Hey @carinlynchin,

autocomplete / code hints is available as an built-in extension for JavaScript and there are other languages available on the Extension Registry, for example PHP: https://github.com/Brackets-PHP/Brackets-PHP-SmartHints

For JavaScript, you should see the variables as you go, or by pressing `ctrl+space`
```
  var hello = "world";
  hel //should prompt "hello" while writing or after pressing `ctrl+space`
```

**Comment by carinlynchin** [comment]
Thanks. So are you saying I need an external extension? or its already in it? Here is a screen shot showing it didn't show up.
<img width="540" alt="screen shot 2016-01-18 at 4 33 03 pm" src="https://cloud.githubusercontent.com/assets/1210918/12403333/496e360c-be01-11e5-9d95-ef5465f667a8.png">

**Comment by petetnt** [comment]
@carinlynchin That's strange, `test` for some reason doesn't show up in the CodeHints while `foo` does:

![image](https://cloud.githubusercontent.com/assets/7641760/12412908/6bd8526c-be93-11e5-84f8-7973fc9cd111.png)

![image](https://cloud.githubusercontent.com/assets/7641760/12412914/7ac97184-be93-11e5-8dea-6f181f40e61f.png)

/cc @sprintr @swmitra

**Comment by carinlynchin** [comment]
wow...that is interesting. Let me know if you find anything out.

**Comment by sprintr** [comment]
Interesting, both `test` and `foo` show up for me.

**Comment by carinlynchin** [comment]
but he did with test...you can see he is on the next line (unless I'm misunderstanding what you are saying)

**Comment by sprintr** [comment]
`test` do show up for me.

![capture](https://cloud.githubusercontent.com/assets/3390089/12429987/ec2ece52-bf0e-11e5-9f27-76d1ac4670fe.PNG)

**Comment by sprintr** [comment]
I digged into it and the problem seems to be with caching of code hints.

**Comment by sprintr** [comment]
@petetnt @carinlynchin [Here](https://github.com/adobe/brackets/blob/master/src/extensions/default/JavaScriptCodeHints/main.js#L304) is the problem. If you request code hints on the same line where it was cached the last time. you get the cached hints instead of the new ones.

**Comment by petetnt** [comment]
@sprintr Can confirm, changing the variable won't trigger the change, which makes the old variable persist in the codehints.

**Comment by carinlynchin** [comment]
Ok. I'll try again. I did press enter to go to the next line though. But I'll try again

**Comment by sprintr** [comment]
@petetnt I believe this should be closed now.
