### ISSUE TITLE
Changing html tags

### ISSUE THREAD

**Issue by arashsa** [adobe/brackets#12102]
If I wanted to add the functionality of changing both sides of an html tag when changing one (like what you would find in many other editors), how would I go about doing that. 

example:
if you have \<h1> \</h1>

and you change the \<h1> to \<h2>, then the \</h1> would automatically change as well.

**Comment by petetnt** [comment]
This comment by CodeMirror author Marijns' on [StackOverflow](
http://stackoverflow.com/questions/27603251/how-to-auto-update-matching-html-xml-tag-in-code-mirror) is most likely the way to go:

> So once the edit has been done, you no longer have the information needed to find the matching tag (which is why the matchtag addon can't help anymore). A good solution might be to track the current matching tag when editing starts (when the cursor is in a tag name) by using the `CodeMirror.findMatchingTag` function exported by the `addon/fold/xml-fold.js` file. Then, on "`change`" events that look like local editing inside the tag name (i.e. their start and end are inside the tag name), immediately follow up by modifying the matching tag.

**Comment by roicos** [comment]
I'd like to try to solve this problem. Shoul we change open tag when closed tag is changed, and if we should, what to do with attributes?

**Comment by petetnt** [comment]
@roicos IMHO we should change the tag but just keep the attributes intact.

**Comment by roicos** [comment]
Ok, thanks!

**Comment by roicos** [comment]
Here https://github.com/roicos/brackets-changing-tags I create a "Changing tags" extension.
Please, be free to coment if it can be improved. I see one thing that should be done better, but have difficulties with the solution: if you changed tag, pair tag automatically changed, but if you press Ctrl+Z, only last change cancels. I thought about document.batchOperation() but the first change is made by user and the second - by the program. If you have any ideas, please let me know.

**Comment by petetnt** [comment]
Cool stuff 👍 Closing this as solved, feel free to reopen if you have any other questions regarding this.
