### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by willy648** [adobe/brackets#12104]
I try to install v1.5 on a windows 10 (64bit) machine, but get a message :
 'Installation directory must be on a local hard drive'

The path set is 'c:\program files(x86)\brackets' which is my local hard drive.
Tried to install on another hdd, but same result
When I run the compatibility check, the ms answer is that this app is not compatible ??? 

Any hints ?

**Comment by petetnt** [comment]
Duplicate of issue https://github.com/adobe/brackets/issues/2407 which also contains various workarounds that you can try. Hopefully one of the workarounds works for you.

**Comment by willy648** [comment]
Opening a command prompt with admin privileges and then calling the msi file from the promp worked ok.
Thanks
