### ISSUE TITLE
unable to edit defaultPreferences.json file

### ISSUE THREAD

**Issue by anbestephen** [adobe/brackets#12108]
I am trying to add proxy setting to Bracket's preference , but i am unable to edit Brackets preference file. This is my current bracket installation info:-

Release 1.5 build 1.5.0-16538 (release cf9cf4698) 
build timestamp: Mon Oct 12 2015 13:14:22 GMT+0100

Can any one suggest??

**Comment by petetnt** [comment]
Hi @anbestephen,

`defaultPreferences.json` is a read-only file: take the options you want to modify and copy them to the `brackets.json` file on the other pane. This will override the defaults. You will also see code hints while typing the values in to `brackets.json` which will help picking the correct options.

**Comment by anbestephen** [comment]
thank's @petetnt it works. But wouldn't it be great to add a separate menu-items for `default-preference` and `user-preference` (similar to sublime Text's preference setting), the current implementation looks magic to me. I didn't even notices the `brackets.json` was opened in the right pane when i opened the preference file.

**Comment by petetnt** [comment]
Yup, there's definitely room for improvements on the Preferences UX-side

**Comment by kolipka** [comment]
Hi @anbestephen 
Try brackets-preferences plugin ;)

**Comment by anbestephen** [comment]
great to know **brackets-preferences** plugin  exists. Can't wait to try it........

**Comment by abose** [comment]
defaultPreferences.json is not supposed t be editable. 
use brackets.json.

Closing.

**Comment by Filip-Rogalski** [comment]
I try to remove Alt-O shortcut from bracket.json file. I remove, I save, but without result. Alt-O still opens window with recent files.
It's important: Alt-O is a shortcut for a polish character!
(Working on Mac.)
Any suggestions how to do it?

**Comment by petetnt** [comment]
@Filip-Rogalski see this comment and report back if it works: https://github.com/adobe/brackets/issues/13115#issuecomment-281627042 👍

**Comment by Filip-Rogalski** [comment]
@petetnt Where would I put it? I put it in brackets.json in following way: (And it's not working)

{ "fonts.fontSize": "15px", "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace", "livedev.multibrowser": false, "beautify.io.on_save": true, "styleActiveLine": true, "linting.collapsed": true, "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings", "overrides": { "Alt-O": "" }, "sacah.keyremapper.loadremapperdialog.keymap": { "navigate.toggleQuickEdit": { "commandID": "navigate.toggleQuickEdit", "key": "Cmd-E" },[…]
