### ISSUE TITLE
Move up folder hierarchy

### ISSUE THREAD

**Issue by carinlynchin** [adobe/brackets#12101]
I have a beginning path for the main folder I need, but it would be nice to be able to move up the hierarchy to the parent and its parent etc...

**Comment by ficristo** [comment]
@carinlynchin are you talking about implementing drag & drop for the file tree?

**Comment by carinlynchin** [comment]
@ficristo no, I mean like say here is a hierarchy:

main -> documents -> www -> html

 and my setup is at html folder.  I am saing that it would be cool to be able to go up to the documents folder or the www folder without having to re-configure the settings for that connection or without having to have multiple connections.. one for each level in the hiearchy

**Comment by ficristo** [comment]
So is about LivePreview settings?

**Comment by ficristo** [comment]
I'm labeling for LivePreview, hope it is correct.

**Comment by humphd** [comment]
@ficristo, while you mention it, is there an existing bug on dnd within the filetree? I can't find one, but surely I'm missing it.  I'm considering implementing it for Thimble, but wanted to see the state of things here first.

**Comment by ficristo** [comment]
Hi @humphd.
AFAIK dnd for filetree is still not available. I found these two issues https://github.com/adobe/brackets/issues/9675 https://github.com/adobe/brackets/issues/10334 and relative trello cards
https://trello.com/c/xwNIcxO6/347-drag-drop-from-os-to-file-tree-copy-move-file
https://trello.com/c/0WJ1aKw2/287-5-drag-drop-within-file-tree-copy-move-file
I think both would be great additions for Brackets.
For the current state of the art probably better to ask @swmitra or @saurabh95

**Comment by carinlynchin** [comment]
sorry @ficristo ... i just saw this. So i am not talking about live preview.. i realize now that i had this in the wrong area.. its actually eqftp that would be in charge of that... separate extension..my bad

**Comment by ficristo** [comment]
If this is related to eqftp I think you should file an issue on the extension you are using.
I close for now.
