### ISSUE TITLE
Setting output directory for LaTeX compiled files/logs 

### ISSUE THREAD

**Issue by adakite** [adobe/brackets#12106]
Hi,

I'm using the LaTeX plugin for syntax highlight and compilation within Brackets. In the LaTeX Settings, it seems that the user can manage the output directory (in the "out" by default) but when changing it, nothing happens and actually is reset to the default value (i.e., 'out'). 

I'd like to build in the same directory as the source files but in the current situation this is impossible. Is this a bug or something? 

FYI: I'm running Brackets Release 1.6 build 1.6.0-16680 on Mac OS X 10.11.3 (so everything is up-to-date).

**Comment by adakite** [comment]
I fixed by editing  CompiledLatex.js
and replace
var dir = path.resolve(options.projectRoot, options.outputDirectory);
by
var dir = folderName; //path.resolve(options.projectRoot, options.outputDirectory);

**Comment by fbblca** [comment]
Hi,
I am having the same issue, but I cannot find any file named CompiledLatex.js. Where should it be located on MacOS?

My LateX settings are in brackets.json and I cannot set a variable here for sending output files in the same input directory: 

{
    "brackets-latex.texBinDirectory": "/Library/TeX/texbin",
    "brackets-latex.outputDirectory": "out",
    "brackets-latex.compiler": "pdflatex",
    "brackets-latex.mainFile": null
}
