### ISSUE TITLE
Can't Install Brackets Extensions

### ISSUE THREAD

**Issue by tiramc** [adobe/brackets#12115]
Here's the message I receive. Apologies in advance for not being that tech savvy and I respectfully ask those providing solutions to be very specific and include detailed step-by-step instructions when providing troubleshooting tips/solutions
![brackets_error](https://cloud.githubusercontent.com/assets/9628221/12493240/049c434a-c039-11e5-8452-8b21e65ff457.png)

**Comment by petetnt** [comment]
Hi @tiramc!

Have you allowed the NodeJS runtime included in Brackets to access outside networks in your firewall settings? Brackets should have notified about it first time you launched Brackets. 

If you didn't you can do it later too! For example in Windows, follow the following steps:

1.  Press the Windows key on your keyboard and type Firewall. Select **Windows Firewall**

2. From the left side menu select **Allow an app or a feature...**
![image](https://cloud.githubusercontent.com/assets/7641760/12493975/7a81cb00-c090-11e5-8af1-dd4483f9957c.png)

3. Select **Change Settings**, then **Allow another app**
![image](https://cloud.githubusercontent.com/assets/7641760/12494004/97c5bf50-c090-11e5-9487-681c511e1a11.png)
4. Select **Browse**, and browse to `C:/Program Files (x86)/Brackets/` and select `node.exe`
![image](https://cloud.githubusercontent.com/assets/7641760/12494045/d5bfe056-c090-11e5-91fe-72f31888a62e.png)

5. Finally select **Add**
![image](https://cloud.githubusercontent.com/assets/7641760/12494052/e5c629a6-c090-11e5-980b-fc07603d2398.png)

6. Restart Brackets and try loading an extension again.

If you are on MacOS or Linux, the steps should be fairly similar.

**Comment by tiramc** [comment]
Hi Petetnt:

Appreciate the quick response. Don't know anything about NodeJS. Hopefully, the steps are similar for Mac. I'll do that and let you know if it works. Thanks!!!

**Comment by petetnt** [comment]
Closing as answered, feel free to reopen if the problem still occurs.
