### ISSUE TITLE
Close Keyboard Shortcut Does not removing the file from the working files sidebar

### ISSUE THREAD

**Issue by pcthomatos** [adobe/brackets#12111]
In OSX:
Close Keyboard Shortcut Does not removing the file from the working files sidebar. It closes the file fine but the filename remains in the working files side bar.

This functionality works correctly if you use your mouse

**Comment by petetnt** [comment]
Can confirm on Windows too: seems that the key combination (CTRL+W) is not triggering the `viewListChange` event.

**Comment by mitorez** [comment]
Also confirmed on Windows 8.1 64-bit running Brackets 1.6.0-16680 with and without extensions loaded.

**Comment by tobibeer** [comment]
Equally affects a bunch of tabs and "document toolbar" type extensions.

**Comment by sanpan93** [comment]
Same trouble in win 8.1 pro 64bits and Bracket 1.6 :(CTRL+W), mouse and wacom intuos pro pen  don't close opened files

**Comment by petetnt** [comment]
There's a fix pending at #12145

**Comment by sanpan93** [comment]
oups sorry, thanks !

**Comment by abose** [comment]
A build refresh is scheduled by his week or next for 1.6 and after that the new installers posted will contain this fix.

**Comment by abose** [comment]
Closing as fixed.
