### ISSUE TITLE
Tabs will no longer close and sometimes create duplicate tabs. Brackets 1.6

### ISSUE THREAD

**Issue by codememobile** [adobe/brackets#12116]
Using Documents Toolbar (Version 0.5.19 latest). When I have more than 1 tab open and I try to close it, the tab will not close. Also, If I have let's say 3 or 4 tabs open at the same time, If I try to close one by hovering over it and hitting the (x), it actually creates a duplicate tab to the right of it instead of closing it. I installed both brackets and brackets w/ extract to see if somehow extract was causing an issue. The same thing is happening on both versions. 

Operating System: Windows 7 Professional

**Comment by israelcollazo** [comment]
I'm running Brackets on OSX El Capitan and same is happening to me since updating to 1.6 yesterday. It's really annoying and cutting into production time. Having to use Sublime for now.

**Comment by codememobile** [comment]
I updated on the windows PC at work to test to see how it worked. I'll wait and continue to use 1.5 on my mac until there is a fix for this issue.

**Comment by swmitra** [comment]
Can confirm the issue both on windows and mac. This looks like a problem with the documents toolbar extension. Closing any file using the working set works fine and only when being closed using the doc toolbar tabs , the issue occurs.

**Comment by codememobile** [comment]
@swmitra I hope there is a fix for this soon. Seems to be more of a documents toolbar fix rather than a brackets fix. It is one of my favorite extensions.

**Comment by codememobile** [comment]
@pthiess Could you please reopen this, I accidentally closed it. Thank you

**Comment by vytalman** [comment]
This is happening to me as well. My only question is how did this release get a green light if one of the most used functions in the app is having issues? Is it not a widespread issue among all 1.6 users (I guess I had another question)? I've switched back to 1.5 until this is resolved.

**Comment by Millsionaire** [comment]
I am having this issue as well. Also, if I click on one tab(say in the bottom of vertical split view) then it will open the file in the top of split view, but still have the same name as the top view tab. Example I click "main.js" in the bottom of vertical split and "index.html" will focus in the top view with the code from "main.js". It's very strange behavior.

**Comment by gnomoide** [comment]
I solve this problem installing "Pestañas - Trabajando Comodamente" extension,(and removing the older one) is the same extension and works fine!
Bye!

**Comment by codememobile** [comment]
@gnomoide  link to extension?

**Comment by gnomoide** [comment]
here: https://github.com/DH3ALEJANDRO/custom-work-for-brackets <https://github.com/DH3ALEJANDRO/custom-work-for-brackets>

Tell me later if this work for you!!

Bye!

**Comment by codememobile** [comment]
@gnomoide Works perfectly thank you! Tabs makes everything so much easier to manage. Thank you again.

**Comment by gnomoide** [comment]
Great!! ur welcome

**Comment by vytalman** [comment]
@gnomoide Just installed the extension and it works like a charm and I dig the icons on each tab. It's a nice little touch. Thanks for the help! :)

**Comment by gnomoide** [comment]
Hi daniel, can you do me a favour?
Im writing a presentation for an exposition in USA, but my english sucks, if a mail you the text can you check the speed for my? it would be a great help for me!

Let me know if you can!

Thank you so much!
