### ISSUE TITLE
Live Preview doesn't connect properly

### ISSUE THREAD

**Issue by superdan54** [adobe/brackets#12117]
I can get live preview to launch, but I'm missing much of the features as described in the guide.

The problem seems to be that Live preview is simply opening the html file using a direct path as (it shows file:///**path to file**.html in the address bar). When I open up the Developer Tools window, I see the following error:

 GET http://127.0.0.1:9222/json net::ERR_CONNECTION_REFUSED

I'm guessing this is why it reverts to simply opening the file rather than connecting to the Brackets servers as described in the guide. What could be causing this? I've ensured there are no proxies, disabled the firewall, and I'm also not using my own path in the Project Settings. I've read through the troubleshooting guide and nothing in it seems to fix the issue. Anything else I can try? It's certainly a permissions issue somewhere, as I am also unable to install any extensions with v1.6. (though I can using v1.0...a separate matter I know).

**Comment by redmunds** [comment]
@superdan54 This usually means that your file is outside your current "project". See troubleshooting guide: https://github.com/adobe/brackets/wiki/Troubleshooting#files-should-be-in-current-project

**Comment by superdan54** [comment]
Hmm well that's not the case in my situation. The file is definitely in the current project. I can actually switch projects to the default "Getting Started" folder and I get the same results when doing live preview with the index.html file in that folder.

**Comment by superdan54** [comment]
I should also not that when I try Experimental Live Preview Mode I get a pop up that says "Open an HTML file or make sure there is an index.html file in your project in order to launch live preview". There is definitely an index.html file in each of the project folders I have opened, using the method describe above.

**Comment by superdan54** [comment]
Here's the full developer tool log. It seems my problems are multifaceted. I get a warning that the project root can't be watched, even though it opens fine in brackets.

![screenshot](https://cloud.githubusercontent.com/assets/16823715/12564686/35528bee-c376-11e5-8f91-4ad3e5beab27.jpg)

**Comment by superdan54** [comment]
I deleted the brackets appdata folder then did a complete reinstall of v1.6. This is what the console log says upon startup...it seems the node server still isn't working right. Any ideas?

![screenshot](https://cloud.githubusercontent.com/assets/16823715/12565669/32f21d42-c37b-11e5-85e8-c65dc48e5a67.jpg)

**Comment by superdan54** [comment]
My issues seem to be tied to changes introduced in v1.1. I've tried every version of Brackets and 1.0 is the last version that installs extensions or displays any different behavior. Live preview doesn't work in that version either, but I don't get the error messages as detailed above and I can also install extensions. Looking at the changelog, it seems that the following new feature in 1.1 is what is causing me problems:

New event dispatching system: Brackets core objects use a new event-listener API that protects against misbehaved extensions. See below for details.

**Comment by superdan54** [comment]
OK I managed to get v1.6 up and working on an old XP machine of mine. I compared the console log b/w the two and it seems that the problem is the NodeConnection errors in the above screenshot. What could be causing the inability to connect to the localhost node?

**Comment by superdan54** [comment]
Update: I'm able to get it to work properly in Safe Mode, now trying to isolate which app/service is causing the problems.

**Comment by superdan54** [comment]
I found the issue!!!! I had a service called Ignite PI Server running. It's a database performance monitoring tool. Not exactly sure what it does to block the localhost from connecting using WebSockets, but disabling it resolved my issues!
