### ISSUE TITLE
Flip View Icons Harsh Shadow

### ISSUE THREAD

**Issue by Jargonius** [adobe/brackets#12119]
On the light theme the flip view icons have a harsh shadow.  I'm running on a high res screen.  They seem to be okay on a low res screen.  They just make my eyes almost bug out looking at them.
<img width="129" alt="2016-01-21" src="https://cloud.githubusercontent.com/assets/6412293/12499371/566434ac-c067-11e5-9e05-7bbf1722218b.png">

**Comment by petetnt** [comment]
Submitted #12124 which removes the shadow completely. It works okay with non-HDPI displays but seemingly not so well with HDPI ones. 

You can remove the shadows manually from `src/styles/brackets.min.css` by searching for `flipview-btn` if you don't want to [hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets)

**Comment by Jargonius** [comment]
Thanks!
