### ISSUE TITLE
Selection highlight is misaligned when line numbers are missing

### ISSUE THREAD

**Issue by fawcett888** [adobe/brackets#12121]
The margin is treated as if the line numbers are there, even though they are hidden.
Selecting a line still selects all the letters, but it is visually unappealing.
Line numbers can be toggled by going to View -> Line Numbers

OS: Windows 10
Version: Release 1.6 build 1.6.0-16680 (release 3df0ac6fa)

The issue happened after upgrading.

![withlinenumbers](https://cloud.githubusercontent.com/assets/16828669/12500176/60846f10-c076-11e5-83c3-d7acf10fec89.JPG)

![withoutlinenumbers](https://cloud.githubusercontent.com/assets/16828669/12500177/6084cbe0-c076-11e5-8360-54a7dd412000.JPG)

**Comment by petetnt** [comment]
Can confirm.

There's something wrong with toggling the line numbers in general: toggling them on and off makes the code folding markers to show up on the wrong side...

/cc @abose @swmitra @thehogfather

**Comment by thehogfather** [comment]
There are two separate issues here. The selection issue is independent of code folding markers. Just disable codefolding and retest. Add `"code-folding.enabled": false` to .brackets.json.

@petetnt I submitted a fix see #11593 (a while ago) for the line numbers issue when code-folding is enabled. But it probably got lost or was simply not prioritised as a serious issue.

As always I'm happy to discuss the background of the issue and the reason for my approach in the solution if it helps anybody.
