### ISSUE TITLE
showing error on html tag incorrectly - php

### ISSUE THREAD

**Issue by chocolatekitkat** [adobe/brackets#12120]
![image](https://cloud.githubusercontent.com/assets/16272248/12500133/47ce2b8e-c07e-11e5-9c9d-e2a88eb64a28.png)

the /div is red even though the opening div is there its just in a comment. no biggie... :)

**Comment by petetnt** [comment]
Hi @chocolatekitkat!

Not sure if there's anything that Brackets (or CodeMirror that powers the editor) can do about this, as the opening tag is `echo`'d with PHP (and considered just a string). Work around would be echoing the end tag or wrapping the whole `<?php ?>` block inside the `<div>`'s, but I can see why writing something this way could be easier (albeit a bit hacky :smile_cat:)

**Comment by bbeale** [comment]
Is there a reason for not just echoing the whole div?

**Comment by ficristo** [comment]
@chocolatekitkat we can't do much here.
In this particular case you can use only html, or `echo` the closing `div` too.
