### ISSUE TITLE
Core: Sidebar can be shown in no distraction mode.

### ISSUE THREAD

**Issue by chunyangwang** [adobe/brackets#12129]
Steps: 
1. Open index.html
2. Click View -> No Distractions
3. Click View -> Show Sidebar

Expect result:
Sidebar can not be shown.

Actual result:
Sidebar was shown as well as No Distractions was checked.

![1-22-2016 3-40-44 pm](https://cloud.githubusercontent.com/assets/16833083/12505430/daf02cfc-c121-11e5-8763-9135801bc1d6.png)

**Comment by bhldev** [comment]
Pull open

**Comment by nethip** [comment]
@bhldev  We essentially are collapsing the project tree. You can still pull open the project tree in no distraction mode. Could you double check on this and update this thread?

**Comment by bhldev** [comment]
This functions as follows currently: if the sidebar is on and no distraction mode is turned on, the sidebar gets turned off. If No distraction mode is on and the sidebar gets turned on, the sidebar appears still. Please update with intended functionality so I can either retract pull or modify pull to match UX experience. Thanks.

**Comment by abose** [comment]
Allowing the user to open the sidebar was conscious decision we made . This is to help with users to see the project contents even in no distraction mode for some time if he choose. Closing .
