### ISSUE TITLE
Tooltip still displayed after panel is closed by using toggle panel menu.

### ISSUE THREAD

**Issue by zhengjingyu** [adobe/brackets#12128]
1. Open Extentsion Manager under file menu.
2. Search Extract and install Extract for Brackets.
3. Click " Extract for Brackets (Preview)" button on right of windows.
4. Close panel by using toggle panel menu(Not close button) and observe.

Expect result:
Panel and tooltip are closed.

Actual result:
Tooltip still displayed after panel is closed.
![tooltip](https://cloud.githubusercontent.com/assets/16832661/12505161/50776f60-c11f-11e5-8bfd-b0e8c638dadd.png)

**Comment by nethip** [comment]
@Zhanxin Thanks for reporting this. I think this is not introduced in Brackets 1.6. Could you double check with earlier builds.

**Comment by Zhanxin** [comment]
@nethip , I have checked this issue on release 1.5 build, there is no Toggle panel menu in that build, seems this is the new feature in this release. If just click "X" to close this panel, it wouldn't reproduce.

**Comment by nethip** [comment]
@Zhanxin I was referring to the extract panel tooltip. I think it is written such a way that, unless all the steps, that appear in the tips are followed, it just stays there.

**Comment by Zhanxin** [comment]
@nethip Yes, on 1.5 release build, this extension is installed by default, the icon is there when we just install and open the Brackets. On 1.6 release build, this extension is not installed by default, so we install it via the Extentsion Manager.

**Comment by abose** [comment]
Deprecated feature, closing.
