### ISSUE TITLE
LOC: Japanese: Translation change for "No Distractions"

### ISSUE THREAD

**Issue by KatarzynaWodzinska** [adobe/brackets#12136]
EN: No Distractions

Current JP: 中断なし

Expected JP: 簡易表示
![jpn_brackets1 6_lk1_007_1 6 0 16680](https://cloud.githubusercontent.com/assets/6737567/12512256/78760862-c117-11e5-8ebb-9cc5296162d0.png)
![enu_brackets1 6_lk1_007_1 6 0 16680](https://cloud.githubusercontent.com/assets/6737567/12512258/7dfc7866-c117-11e5-8857-57da9b834257.png)

**Comment by KatarzynaWodzinska** [comment]
Translation fixed.

**Comment by nethip** [comment]
@vaamica This seems to be a translation issue. How do we track these kind of bugs? Tagging @walfgithub

**Comment by Zhanxin** [comment]
Upload the screenshot with build 1.7.0-16733
![12136](https://cloud.githubusercontent.com/assets/2245179/13139437/92f7be28-d667-11e5-9fbe-97e8d4a3e201.png)

**Comment by KatarzynaWodzinska** [comment]
The string is correct in TM database but still not fixed on screenshot. Please advise.

**Comment by YanChen002** [comment]
Upload the screenshot with build 1.7.0-16739, please verify!
![image](https://cloud.githubusercontent.com/assets/17636671/13568329/82406016-e49b-11e5-8842-a8d3743887f6.png)

**Comment by KatarzynaWodzinska** [comment]
Issue still not fixed.

**Comment by ZuoBaogang** [comment]
Checked this issue on 1.6 refresh build 1.6.0-16692, It has been fixed.
![jpn_fixed](https://cloud.githubusercontent.com/assets/17721679/13700336/5ad97788-e7bb-11e5-82d9-1dfb78440544.png)

**Comment by KatarzynaWodzinska** [comment]
Confirmed as fixed.
