### ISSUE TITLE
LOC: Japanese: Translation change for "Flip this view to [[0]] pane"

### ISSUE THREAD

**Issue by KatarzynaWodzinska** [adobe/brackets#12135]
Current  translation for "Flip" sounds a little awkward. 

EN: Flip this view to [[0]] pane
Current JP: [[0]] ペインにこのビューを反転
New JP: このビューを [[0]] ペインにめくる
![enu_brackets1 6_lk1_001_1 6 0 16680](https://cloud.githubusercontent.com/assets/6737567/12512184/0543b650-c117-11e5-9242-74df4cbf424b.png)
![jpn_brackets1 6_lk1_001_1 6 0 16680](https://cloud.githubusercontent.com/assets/6737567/12512187/0b635996-c117-11e5-9377-fe2d6c28303c.png)

**Comment by KatarzynaWodzinska** [comment]
Translation fixed.

**Comment by nethip** [comment]
Tagging @vaamica and @walfgithub

**Comment by Zhanxin** [comment]
Upload the screenshot with build 1.7.0-16733, please verify!
![12135](https://cloud.githubusercontent.com/assets/2245179/13139468/b279c728-d667-11e5-93b5-7a18d56a1010.png)

**Comment by KatarzynaWodzinska** [comment]
String not fixed on screenshot, correct in TM database. Please advise.

**Comment by YanChen002** [comment]
Upload the screenshot with build 1.7.0-16739, please verify!
![image](https://cloud.githubusercontent.com/assets/17636671/13568303/58035916-e49b-11e5-9be3-4b4a5a61b394.png)

**Comment by KatarzynaWodzinska** [comment]
Issue still not fixed.

**Comment by ZuoBaogang** [comment]
Checked this issue on 1.6 refresh build 1.6.0-16692, It has been fixed.
![jpn_fixed](https://cloud.githubusercontent.com/assets/17721679/13700567/9e45801a-e7bc-11e5-9f21-e8710c0299ce.png)

**Comment by KatarzynaWodzinska** [comment]
Confirmed as fixed.

**Comment by ficristo** [comment]
> Confirmed as fixed.

Closed.
