### ISSUE TITLE
Error when opening Brackets for the first time

### ISSUE THREAD

**Issue by henrywright** [adobe/brackets#12130]
On opening Brackets for the first time, I get this error:

> Error Opening File
> An error occurred when trying to open the file /opt/brackets/samples/root/Getting Started/index.html. Brackets only currently supports UTF-8 encoded text files.

I'm using Ubuntu 14.04 and installed the latest 64-bit release from brackets.io (no Extract).

**Comment by machinezilla** [comment]
Hello. I had this same problem. I'm running Brackets on Ubuntu 14.04 (with i3 as my window manager) via Crouton on a Chromebook. For some reason the locale settings were not correct after installing Ubuntu via crouton.

In my case I was able to fix this issue by doing the following:

```
$ sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
```

after running this command type in:

```
$ locale
```

you should now see something like this:

```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by henrywright** [comment]
Thanks for the info @machinezilla
