### ISSUE TITLE
1.6 can not properly identify end tags in xml/html

### ISSUE THREAD

**Issue by ketansp** [adobe/brackets#12137]
In version 1.6, brackets can not properly identify the end tags of xml/html files and thus marks the directive in red colour.

**Comment by petetnt** [comment]
Can you provide an example of an tag that gets improperly highlighted as red? In `1.5` (and below) there was an issue where structurally non-valid (by HTML5 standards, not necessarily non-working) end tags weren't shown as red.

**Comment by ketansp** [comment]
Herewith sharing a screenshot of the bug and underlying sample code.

![screenshot-92](https://cloud.githubusercontent.com/assets/12011359/12512391/23058282-c13e-11e5-9c98-8375a90b05f5.png)

```
<ion-view view-title="Home">
	<ion-content class="padding-horizontal padding-vertical margin-top-50">
		<div>
			<button class="button button-block button-positive" type="button">
				button 1
			</button>
			<button class="button button-block button-positive" type="button">
				button 2
			</button>
			<button class="button button-block button-positive" type="button">
				button 3
			</button>
		</div>
		<div>
			<form class="margin-top-20" novalidate>
				<label class="item item-input">
					<input type="text" placeholder="Question"></input>
				</label>

			</form>
		</div>
	</ion-content>
</ion-view>
```

**Comment by petetnt** [comment]
The issue there is that `<input>` element shouldn't have an end tag

https://developer.mozilla.org/en/docs/Web/HTML/Element/Input

```
  Tag omission:	Must have a start tag and must not have an end tag.
```

If you change your mark up to 

```
<ion-view view-title="Home">
    <ion-content class="padding-horizontal padding-vertical margin-top-50">
        <div>
            <button class="button button-block button-positive" type="button">
                button 1
            </button>
            <button class="button button-block button-positive" type="button">
                button 2
            </button>
            <button class="button button-block button-positive" type="button">
                button 3
            </button>
        </div>
        <div>
            <form class="margin-top-20" novalidate>
                <label class="item item-input">
                    <input type="text" placeholder="Question">
                </label>

            </form>
        </div>
    </ion-content>
</ion-view>
```
the red errors will disappear.

**Comment by codememobile** [comment]
Issue is with your input tag. It's not valid HTML5. You didn't show us what DOCTYPE you were using though. 

Update:
Testing closing input tag in Brackets with old xhtml doctype.

![capture](https://cloud.githubusercontent.com/assets/15266715/12522797/a8b2683c-c120-11e5-95bc-73aca4022c64.JPG)

Brackets still recognizes the closing input tag as invalid even with deprecated xhtml tag. Since your using ionic, you really shouldn't be using anything other than HTML5, which includes not having to self-close or close the input tag. Hope this helped.

**Comment by ficristo** [comment]
`input` is an autoclosing tag. If you want to close it you can write `<input type="text" />`.
