### ISSUE TITLE
LOC: French: Translation change required in "Flip this view to [[0]] pane"

### ISSUE THREAD

**Issue by Tania-Jiacomini** [adobe/brackets#12133]
Current translation for "Flip this view to [[0]] pane" is not correct due to placeholder content

EN: Flip this view to [[0]] pane
Current FR: Transférer cette vue dans le volet [[0]]
New FR: Transférer cette vue dans le volet de [[0]]

![enu_brackets1 6_lk1_001_1 6 0 16680](https://cloud.githubusercontent.com/assets/2284774/12510322/55fa3a6e-c109-11e5-82c0-eb2a008032c1.png)

![fra_brackets1 6_lk1_001_1 6 0 16680](https://cloud.githubusercontent.com/assets/2284774/12510325/5d4b726a-c109-11e5-82e5-29f02f8abe07.png)

**Comment by KatarzynaWodzinska** [comment]
Translation fixed

**Comment by nethip** [comment]
Tagging @vaamica and @walfgithub

**Comment by Zhanxin** [comment]
Upload the screenshot with build 1.7.0-16733, please verify!
![12133](https://cloud.githubusercontent.com/assets/2245179/13139479/bf8179a2-d667-11e5-88a2-3ee71115b9b3.png)

**Comment by Tania-Jiacomini** [comment]
FR: translation hasn't been fixed, old version is still being used.
Please make sure you use the following, as required: "Transférer cette vue dans le volet de [[0]]"

**Comment by KatarzynaWodzinska** [comment]
The string is not fixed on screen. Please advise.

**Comment by YanChen002** [comment]
Upload the screenshot with build 1.7.0-16739, please verify!
![image](https://cloud.githubusercontent.com/assets/17636671/13568260/07ecd236-e49b-11e5-813a-e2f91a7fc528.png)

**Comment by Tania-Jiacomini** [comment]
Hi,
Sorry but wrong string is still being used, issue is not fixed. (Small word "de" missing before placeholder)
Correct FR: "Transférer cette vue dans le volet de [[0]]"

**Comment by ZuoBaogang** [comment]
Checked this issue on 1.6 refresh build 1.6.0-16692, It has been fixed.
![fra_fixed](https://cloud.githubusercontent.com/assets/17721679/13700661/3599bab2-e7bd-11e5-80ac-95526b2af285.png)

**Comment by Tania-Jiacomini** [comment]
Now confirmed as fixed, thanks!

**Comment by ficristo** [comment]
From the comments it seems fixed, reopen if not.
