### ISSUE TITLE
Double cursor

### ISSUE THREAD

**Issue by ketansp** [adobe/brackets#12134]
Many a times, it happens that brackets start showing two cursors at the same time. Because of this, basic functions like typing, copying, pasting, cutting, selecting do not behave as intended.

**Comment by petetnt** [comment]
It's a feature, not a bug. You can hold down `CTRL` while clicking around the editor to create multiple cursors: this is especially handy when you need to create or remove same values for multiple places.

**Comment by ketansp** [comment]
Oh ok. Cool. Thanks for clarifying.
