### ISSUE TITLE
brackets doesnt run on my turing machine

### ISSUE THREAD

**Issue by Lemmmy** [adobe/brackets#12143]
please help me this is really urgent because i need a good ide to write code with

**Comment by thesturs** [comment]
You can try NETBEANS.  https://netbeans.org

**Comment by Lemmmy** [comment]
sry the https bit thing doesnt work on my turel mschine!

**Comment by abose** [comment]
Can you give your machine configuration.

**Comment by Lemmmy** [comment]
![](http://ichi.lemmmy.pw/grace_binding.jpg) it looks like this

**Comment by abose** [comment]
I meant the turning machine configuration rules, not the picture of the machine itself :smile_cat:

**Comment by Lemmmy** [comment]
oh if you look really close at the green display there you can see it

**Comment by busykai** [comment]
@Lemmmy, maybe you need to lubricate it better.
