### ISSUE TITLE
can no longer close files with CTRL-W in v1.6

### ISSUE THREAD

**Issue by tobibeer** [adobe/brackets#12140]
As the title says, I used to close files using `CLTR-W`. As of with 1.6 Build 1.6.0-16680, files in the left pane under "open files" no longer close when I do that. Nor do they close in any of the tabs extensions.

OS: Windows 10

**Comment by codememobile** [comment]
Closing of files with CLTR-W seems to be working on Windows 7 Professional with Latest build. I did experience an issue though where if i have multiple files open, it lags when closing the files with CTRL-W. If I have 7 files open and and CTRL-W to close them, it takes about 20 seconds before it actually closed them.

**Comment by redmunds** [comment]
It seems to close the files, so I think the working files view is not getting refreshed properly. For example, click on the item that should have been removed and it's removed immediately.

**Comment by tobibeer** [comment]
As said, it appears to equally affect a bunch of tabs and "document toolbar" type extensions.

**Comment by petetnt** [comment]
Duplicate of https://github.com/adobe/brackets/issues/12111

**Comment by tobibeer** [comment]
Ok, closing, thanks @petetnt.
