### ISSUE TITLE
No Distractions Mode hides split view close button

### ISSUE THREAD

**Issue by Jargonius** [adobe/brackets#12142]
If you open two files in vertical split view and then enter and leave the no distractions mode the right panel's close button is no longer accessible.  I assume that it is becoming hidden behind the plugins bar but I'm not sure what the problem is.

**Comment by petetnt** [comment]
Does this happen when running without extension (Debug -> Reload Without Extensions)? Cannot reproduce on Windows 10, Release 1.7 development build 1.7.0-0

**Comment by Jargonius** [comment]
I can't seem to reproduce it with or without extensions.  Strange.

**Comment by petetnt** [comment]
Closing as solved, feel free to reopen if the problem comes back
