### ISSUE TITLE
CTRL+Z it won't work some times!!

### ISSUE THREAD

**Issue by BilalDja** [adobe/brackets#12141]
Some times when I really need to undo some work, the **Ctrl+Z** it won't respond!

**Comment by Lemmmy** [comment]
have you tried writing code first

**Comment by petetnt** [comment]
Duplicate of https://github.com/adobe/brackets/issues/11826

**Comment by ankurloriya** [comment]
I feel Ctrl+Z move scroll even code line on view port(not out of the view area).

**Comment by abose** [comment]
closing duplicate.
