### ISSUE TITLE
Regarding Line comment issue

### ISSUE THREAD

**Issue by borax12** [adobe/brackets#12157]
The preference for the same has been added in the lineCommentBugFix pull request. I think the github mention is not working , hence reporting here

Pull request number - #11954

**Comment by petetnt** [comment]
I can review the PR later today

**Comment by borax12** [comment]
@petetnt - sorry for bugging , but can you just quickly review the last commit which separates the test cases for the two preference values

**Comment by petetnt** [comment]
Closing as the PR was merged 👍
