### ISSUE TITLE
Non-removable space on newline - Brackets 1.6

### ISSUE THREAD

**Issue by MynockSpit** [adobe/brackets#12150]
Didn't see this reported or known -- sorry if it is and I missed it.

Windows 10.0.10240
Brackets 1.6

Line breaks create a small amount of whitespace on the following line. The screenshot shows what happens when you hit Shift + Right Arrow with the cursor on line 7 after the '.' in 'This is a sentence.' Moving your cursor line 8 and hitting delete causes line 8 to be.

![2016-01-25 12_34_32- index html combined projects - brackets](https://cloud.githubusercontent.com/assets/5713867/12563619/0534e1ac-c360-11e5-87fa-1b7e5d739e16.png)

This extra space disappears as soon as you start typing on line 8.

The (minimal) effects of this are 1. degrading my sanity, 2. placing your cursor on a newline and hitting Shift + Up Arrow doesn't select the entire line above. (See screenshot.)

![2016-01-25 12_42_28- index html combined projects - brackets](https://cloud.githubusercontent.com/assets/5713867/12563857/1fe7185c-c361-11e5-94e3-99beda6c0161.png)

EDIT: Forgot to mention that uninstalling / disabling extensions doesn't alter this behavior.

This issue is terribly incredibly amazingly important -- still, thought it should be reported.

**Comment by petetnt** [comment]
Fixed by https://github.com/adobe/brackets/pull/12110 when it lands :fire:

**Comment by ficristo** [comment]
#12110 landed. Closing
