### ISSUE TITLE
Collapse all-feature for Find/Replace in files

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#12152]
Sometimes when you are just quickly finding in / replacing in files you just want to browse which files contain the words you are searching for, or want to pick out specific files by name in general.

Currently there is no easy way to collapse all the entries (which default are open), making this operation significantly harder (mainly when dealing with big result sets). This `feature-request` is a pretty long hanging fruit that could also easily be done as an `extension`, but if there's some interest in this I could also do the change directly to the core.

**Comment by redmunds** [comment]
@petetnt You can Ctrl-click (Cmd-click on Mac) on any expand/collapse triangle to toggle all at once. Is that what you're looking for?

**Comment by petetnt** [comment]
That's exactly it! I thought I tried all the regular Key combinations  but I guess not! Thanks @redmunds

**Comment by redmunds** [comment]
@petetnt Yeah, I use that one a lot!
