### ISSUE TITLE
brackets as internet browser

### ISSUE THREAD

**Issue by khef22** [adobe/brackets#12159]
Hi,
 Got something unique happened to the software becoming a browser or this something like new feature. Don't know how it happen. Don't mind the web content :+

![12](https://cloud.githubusercontent.com/assets/8078951/12606655/1b77f17e-c50a-11e5-9047-b658ec14983e.PNG)
![7](https://cloud.githubusercontent.com/assets/8078951/12606657/1b7c8b62-c50a-11e5-88c3-dab708d0270e.PNG)
![8](https://cloud.githubusercontent.com/assets/8078951/12606658/1b7cd964-c50a-11e5-911e-454fe35d9e01.PNG)
![9](https://cloud.githubusercontent.com/assets/8078951/12606660/1b7e6d74-c50a-11e5-9726-dd9b5b5175b2.PNG)
![10](https://cloud.githubusercontent.com/assets/8078951/12606656/1b7c4d82-c50a-11e5-9004-2f022bab2212.PNG)
![11](https://cloud.githubusercontent.com/assets/8078951/12606659/1b7d88c8-c50a-11e5-8f29-d94be44a333b.PNG)

1:

**Comment by khef22** [comment]
This is not edited by the way.
![13](https://cloud.githubusercontent.com/assets/8078951/12606715/85e85b5c-c50a-11e5-9b57-865388d80da1.PNG)

**Comment by khef22** [comment]
![14](https://cloud.githubusercontent.com/assets/8078951/12606783/fe6e99ba-c50a-11e5-9b2f-f0c64c5dc4da.PNG)

**Comment by petetnt** [comment]
As Brackets is based on [CEF](https://bitbucket.org/chromiumembedded/cef), it can also act as an general Web Browser. You can replicate the behavior for example dropping an URL to the working area.

However this behavior is not supported (at least currently) by any means in Brackets. To resume to the normal state, launch Brackets again.

**Comment by khef22** [comment]
@petetnt thanks.
