### ISSUE TITLE
CMD+W not working anymore

### ISSUE THREAD

**Issue by noxxviii** [adobe/brackets#12161]
Since Version: Release 1.6 build 1.6.0-16680 (release 3df0ac6fa)

On my MacBook Pro (OS X Version 10.11.2) the CMD+W (close current file) 
doesn't work correctly anymore, also Shift+CMD+W.

**Comment by petetnt** [comment]
Fixed in https://github.com/adobe/brackets/pull/12145

**Comment by noxxviii** [comment]
Thank you, didn't find it...
