### ISSUE TITLE
Can't save changes to a .html file

### ISSUE THREAD

**Issue by lgfield** [adobe/brackets#12167]
If I try to save changes to a .html file I get an error code stating "the permissions do not allow you to make modifications":

![image](https://cloud.githubusercontent.com/assets/16946492/12661147/ce967f92-c5cc-11e5-9675-50ed16f28f60.png)

**Comment by petetnt** [comment]
You should move your own projects to an other folder such as under Documents (`C:\Users\username\Documents`) where you are guaranteed to have write access. 

You can do this by opening the folder `C:/Program Files (x86)/Brackets/samples/root/Getting_Started` on Windows Explorer and cutting / pasting them to `C:\Users\username\Documents\`. Then you can open the folder by clicking the button that on the screenshot says `Getting Started` :arrow_right:  `Open Folder` or from `File -> Open Folder`

**Comment by lgfield** [comment]
Thanks for your help! Much appreciated.

**Comment by petetnt** [comment]
:+1: You are welcome

**Comment by al-kanfaroosh** [comment]
I looked on the internet and it happened that I found a solution to my problem on your website / my sincere thanks and gratitude for the help.
