### ISSUE TITLE
Question on the new live preview button

### ISSUE THREAD

**Issue by Veranni** [adobe/brackets#12168]
Hi, I'm trying to activate the multi browser function on the bracket editor?
I read that if you type in "livedev.multibrowser": true 
it will automatically connect to the default browser. I don't have google chrome 
Google Chrome is a terrible browser. I'm using firefox. My question is how can I connect firefox to
Brackets?

**Comment by petetnt** [comment]
You can enable multibrowser livepreview from `File -> Enable Experimental Live Preview`. After enabling this preference the live preview should launch to your default browser.
