### ISSUE TITLE
Cannot install brackets 1.6 on windows 10

### ISSUE THREAD

**Issue by as1ndu** [adobe/brackets#12171]
![brackets](https://cloud.githubusercontent.com/assets/4271996/12671716/a4fa4c84-c682-11e5-887c-c80b9f0f00bb.png)

**Comment by DeeLindesay** [comment]
Can't get past the first hurdle (also 1.6 on windows  10)
![image](https://cloud.githubusercontent.com/assets/1660957/12673933/e110e940-c677-11e5-9e75-28df131d17de.png)

**Comment by AnthonyMichaelc** [comment]
Have you tried removing the current installation? There will be appdata files that will linger and need to be removed as well
