### ISSUE TITLE
Pressing "Command + W" does not close the file in the left sidebar.

### ISSUE THREAD

**Issue by rvarbanov** [adobe/brackets#12174]
A very stange issue where when you press Cmd+W the file closes in the main window, but the tile name is still showen in the left sidebar.

Here is that I am running:
```json
{
    "uuid": "6c5c1ba4-4f5c-40a7-a242-3bcfe1289c92",
    "snapshotTime": 1454092707457,
    "os": "mac",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.6.0 Chrome/39.0.2171.36 Safari/537.36",
    "osLanguage": "en",
    "bracketsLanguage": "en",
    "bracketsVersion": "1.6.0-16680",
    "ProjectDetails": {
        "prj-1147418143": {
            "numFiles": 2572,
            "cacheSize": 143431211
        },
        "prj98782": {
            "numFiles": 186,
            "cacheSize": 8599276
        }
    },
    "fileStats": {
        "openedFileExt": {
            "js": 39,
            "html": 19,
            "scss": 13
        },
        "workingSetFileExt": {
            "html": 6,
            "js": 13
        }
    },
    "searchDetails": {
        "searchNew": 2,
        "searchOnReturnKey": 2,
        "searchInstant": 3
    },
    "projectLoadTimes": ":137",
    "fileOpenTimes": ":452",
    "ModuleDepsResolved": 148401,
    "AppStartupTime": 149180,
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": []
}
```

**Comment by petetnt** [comment]
Fixed with https://github.com/adobe/brackets/pull/12145

**Comment by rvarbanov** [comment]
Thank you!

I just noticed that the "X" button in the left sidebar has a similar issue. It does not close all untouched files...

**Comment by petetnt** [comment]
#12145 should fix that too: if it doesn't, do open a new issue :+1:

**Comment by rvarbanov** [comment]
Great!

Do you think that fix will be added to 1.6.1 or 1.7?

**Comment by petetnt** [comment]
Cannot comment about that myself, but you can apply the fix by following the [guidelines on How to hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) and then doing `git fetch upstream swmitra/BugFixesFor1.6 && git merge fetch_head` :+1:

**Comment by abose** [comment]
A build refresh is scheduled by his week or next for 1.6 and after that the new installers posted will contain this patch.

**Comment by abose** [comment]
Closing as fixed
