### ISSUE TITLE
Live Preview does not close

### ISSUE THREAD

**Issue by Jonas-Drotleff** [adobe/brackets#12176]
After updating to 1.6 the live preview button keeps being orange when the browser is closed or the developer options are opened. Can't click the button to close live preview.
Only restart of brackets closes live preview.

**Comment by AnthonyMichaelc** [comment]
I experienced the same issue, after uninstalling 1.6, keeping the extensions appdata and deleting all the rest, i installed 1.5 and do not see the issue.
