### ISSUE TITLE
Emmet is not working

### ISSUE THREAD

**Issue by salehST** [adobe/brackets#12188]
i couldn't install the emmet at 1st. and when i installed it emmet isn't working.
![problem](https://cloud.githubusercontent.com/assets/13993598/12751918/052f85f0-c9ea-11e5-8c49-72d2a007679a.jpg)

**Comment by petetnt** [comment]
Hi @salehST,

try reposting this to the extension repo (https://github.com/emmetio/brackets-emmet) for a quicker answers :+1:

**Comment by salehST** [comment]
OK THANKS @petetnt ....
