### ISSUE TITLE
CodeMirror Scrolling jerky and laggy bcz this!

### ISSUE THREAD

**Issue by evolutionjay** [adobe/brackets#12183]
![screen](https://cloud.githubusercontent.com/assets/4468540/12723863/500f42c6-c946-11e5-847f-d9b281a9c597.png)

Some one tell me how to change the scroll form "position top" into  CSS3's transform: translateY(...);

**Comment by petetnt** [comment]
I just tried that myself but (somewhat surprisingly) didn't see much difference myself.

The first line that you are looking for is in [src/thirdparty/CodeMirror/lib/codemirror.js#L712](https://github.com/codemirror/CodeMirror/blob/29555c986ddb5be91be177055ecbab605717b397/lib/codemirror.js#L712) 


```
    cm.display.mover.style.transform = "translateY(" + display.viewOffset + "px)";
```

Setting this enables you to test the performance, but **it does break linenumbers and other things that depend on the `top` value of the scroller (so you need to replace to `style.top`'s too.

**Comment by evolutionjay** [comment]
need replace all style.top ................... WTF !

**Comment by petetnt** [comment]
For example if variable `foo` depends on `cm.display.mover.style.top`-value then `foo` will always be `0` if not explicitly set (which it isn't if you change it to `translateY`-transform.

**Comment by evolutionjay** [comment]
how about using iScroll for Codemirror scrolling addon

**Comment by petetnt** [comment]
It might be possible (or most likely is). Might be a better fit question for the CodeMirror discussion forum (https://discuss.codemirror.net/) though.

**Comment by evolutionjay** [comment]
ok....

**Comment by abose** [comment]
closing as tracked in cm repo. 
IF this is a issue with brackets, feel free to reopen this.
