### ISSUE TITLE
Slow accessing files

### ISSUE THREAD

**Issue by Bloom-web** [adobe/brackets#12189]
When I first open brackets, saving files, or especially when I Quick Edit (accessing multiple css files), Brackets is very slow with Brackets Helper at more than 100% CPU until the files load. Restarting without extensions is about the same.

I'm currently using:
Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) 
build timestamp: Tue Jan 12 2016 05:35:00 GMT-0800

**Comment by petetnt** [comment]
How big is your project? You could try excluding some common third party folders and temporary files with https://github.com/zaggino/brackets-file-tree-exclude to see if the performance improves.

If the project you are working in on is relatively small, could you post your Health Report (`Help -> Health Report`)

**Comment by geooogle** [comment]
@petetnt I've been using `brackets-file-tree-exclude` for a few months now, mostly excluding `/node_modules/`. I agree that ever since this last release as mentioned above (I'm using release 3df0ac6fa), brackets response has been shady (i use brackets because response its fast).

- if you have files open in the `Working Files` section, CMD-W is a great way to clear them away. Since this release, there is a delay for them to close. Sometimes, the code-view will clear but the file persists under `Working Files` and takes seconds to be removed. Previous versions never had this problem. Test: Try opening about 10 files so they exist in `Working Files` then tap CMD-W 10 times as quick as you normally would.

- i have noticed that sometimes the delay (mentioned above) will sort of freeze everything and I can not open new files until I quite brackets and re-open.

```{
    "uuid": "c130ea79-abde-4272-a4e9-dea636e80e32",
    "snapshotTime": 1454597501854,
    "os": "mac",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.6.0 Chrome/39.0.2171.36 Safari/537.36",
    "osLanguage": "en",
    "bracketsLanguage": "en",
    "bracketsVersion": "1.6.0-16680",
    "fileStats": {
        "openedFileExt": {
            "js": 145,
            "less": 3,
            "json": 14,
            "jade": 82,
            "html": 73,
            "jshintrc": 2,
            "coffee": 1,
            "md": 9
        },
        "workingSetFileExt": {
            "less": 3,
            "js": 43,
            "jade": 21,
            "html": 15,
            "jshintrc": 1,
            "json": 4,
            "md": 3
        }
    },
    "ProjectDetails": {
        "prj-964862823": {
            "numFiles": 266,
            "cacheSize": 18697406
        },
        "prj1361413784": {
            "numFiles": 240,
            "cacheSize": 977012
        },
        "prj-103463679": {
            "numFiles": 117,
            "cacheSize": 385528
        },
        "prj-762735872": {
            "numFiles": 48,
            "cacheSize": 133251
        }
    },
    "searchDetails": {
        "searchNew": 8,
        "searchInstant": 14,
        "searchOnReturnKey": 5
    },
    "projectLoadTimes": ":205",
    "fileOpenTimes": ":645:46(102)158[56]:98(166)234[68]:174",
    "ModuleDepsResolved": 588835,
    "AppStartupTime": 590543,
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": [
        {
            "name": "globexdesigns.brackets-jscs",
            "version": "0.7.5"
        },
        {
            "name": "jade",
            "version": "2.0.0"
        },
        {
            "name": "brackets-file-tree-exclude",
            "version": "1.0.4"
        },
        {
            "name": "lonelystorm.newline",
            "version": "0.0.1"
        }
    ],
    "bracketsTheme": "light-theme"
}```

**Comment by petetnt** [comment]
@geooogle For the CTRL+W issue there's a fix tracking at #12145

**Comment by geooogle** [comment]
@petetnt Thank you!

**Comment by Bloom-web** [comment]
So the exclude plugin helps if I exclude all of my css and javascript but then I'm left without the ability to see anything useful in Quick Edit. Each time I include a subset of style files from an existing template, it still slows way down for any file access actions.

I'll try to pair down my template files for only what I'm using but it'd be nice if there was some other way to improve performance.

**Comment by abose** [comment]
A build refresh is scheduled by his week or next for 1.6 and after that the new installers posted will contain the fix for the ctrl-w issue.
Please close this issue if this works after the release refresh is out..

**Comment by abose** [comment]
1.7 has been released. @Bloom-web can you verify if this is still an issue?

**Comment by abose** [comment]
Closing long pending issue. Please feel free to reopen if you still face the problem.
