### ISSUE TITLE
Selection highlight misaligned on line selection

### ISSUE THREAD

**Issue by marfarma** [adobe/brackets#12184]
Place cursor at the far left edge of a line.  Hold down Shift key and hit the down arrow.  Selection highlight is misaligned.

<img width="413" alt="app-github-tokenjs--electron-react-boilerplate---mdash--brackets" src="https://cloud.githubusercontent.com/assets/27477/12730162/825fb95c-c8f8-11e5-968d-8424603eb200.png">

Of note, there are no spaces infront of the variable `github`

**Comment by petetnt** [comment]
There's a fix pending in https://github.com/adobe/brackets/pull/12110

**Comment by topherj** [comment]
@petetnt I followed your link to issue #12110, but I'm not sure if there's something I can do right now to fix this, or if I just need to wait for the next release. There you said, "This PR compensates for that by pulling the editor back -4 pixels". I don't know what a PR is. Sorry. :(

**Comment by topherj** [comment]
Never mind. I did manage to find .CodeMirror-lines in brackets.min.css and add the margin-left: -4px. I'm not sure if I was meant to do that by hand or if there was some clever way of getting that out of git, but at least the misalignment is gone.

If there was a better way to do this besides me manually updating the brackets.min.css file, I'd be glad to be told what it was. 

Thanks again.

**Comment by petetnt** [comment]
@topherj No need to be sorry! The quick way is to just edit the `.css` file manually.

Other (proper) way is to use an dev build of Brackets. [How to Hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) is the basic guide, but just to add the patch steps are as follows:

1. Install the latest Brackets build
2. Clone your fork of the repo: git clone https://github.com/adobe/brackets
3. Fetch submodules: `cd brackets` and `git submodule update --init`
4. Run setup_for_hacking script under the `tools/` folder.

When you launch Brackets, you should notice that you are running the `dev` build

Then, again in the `brackets` folder:

5. Add my fork of Brackets as an `origin` `git remote add petetnt https://github.com/petetnt/brackets`
6. Fetch my fix branch `git fetch petetnt petetnt/indent-wrap-minor-fix`
7. Merge it to your master branch `git merge petetnt/petetnt/indent-wrap-minor-fix`

and reload Brackets. You should now notice that the issue should be fixed

**Comment by topherj** [comment]
Thanks @petetnt! :) 
Did you notice that the `margin-left: -4px` fix seems to also throw off the click target of the code folding arrows in the gutter? Clicking on the arrow no longer works, but clicking just to the _right_ of the arrow (probably by about 4px) folds/unfolds the code block. 

Will this be addressed in the real fix for this on the next Brackets update?

**Comment by petetnt** [comment]
@topherj Which theme are you using? And which operating system are you on?

The fold arrows work correctly for me (and in correct position)... do you see a similar gutter between the content and other stuff like in https://github.com/adobe/brackets/pull/12110#issuecomment-173604704. 

![image](https://cloud.githubusercontent.com/assets/7641760/12853637/e271399a-cc3d-11e5-96af-d8ba645efe64.png)

**Comment by topherj** [comment]
@petetnt I'm using the Brackets Dark theme, on Windows 7 Pro SP1 64-bit. I _do_ see a similar gutter like in #12110 (see below)...
![image](https://cloud.githubusercontent.com/assets/760002/12853878/11526d98-cbfc-11e5-89ba-a731d23519f2.png)

**Comment by petetnt** [comment]
@topherj Super weird, as I just tried a fresh copy on a Mac and everything alright there too (as they are on my work PC which is a Windows 8 machine and the one I am writing this on is Win10).

Do you see the gutter if you launch without extensions (Debug -> Launch Brackets without Extensions)?

**Comment by topherj** [comment]
@petetnt I do get the same thing if I reload without extensions. Something I didn't really notice before is that I need to click exactly on that little space between the gutter and the line highlight in order to get code folding to work. Clicking on the arrow itself does nothing. Weird.

**Comment by ficristo** [comment]
Fixed by https://github.com/adobe/brackets/pull/12110
Will be in 1.8
