### ISSUE TITLE
Extract wont open without multiple reloads of brackets

### ISSUE THREAD

**Issue by marioloncarek** [adobe/brackets#12209]
Im using extract for brackets every day and its best thing in brackets for me. But im having big problems. When you open brackets for the first time and trying to open Extract extension, nothing happens, its not responding to clicks. I need to go to Reload with extension for multiple times and somehow after some time Extract opens... Its pain because i can't start working for 10-15 minutes and i have to fight buggy Extract extension

**Comment by abose** [comment]
can you go to 'help> health report `and paste your health report here?

**Comment by marioloncarek** [comment]
@abose Thanks for your time

```
{
    "uuid": "67681665-93f4-4937-a641-ebed8c76478d",
    "snapshotTime": 1455390172195,
    "os": "win",
    "userAgent": "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.6.0.0 Chrome/39.0.2171.36 Safari/537.36",
    "osLanguage": "en-US",
    "bracketsLanguage": "en-US",
    "bracketsVersion": "1.6.0-16680",
    "fileStats": {
        "openedFileExt": {
            "html": 120,
            "less": 171,
            "js": 1,
            "css": 3
        },
        "workingSetFileExt": {
            "html": 16,
            "less": 13
        }
    },
    "e4b": {
        "userAutoSignedIn": false
    },
    "ProjectDetails": {
        "prj1213344984": {
            "numFiles": 45,
            "cacheSize": 1581316
        }
    },
    "searchDetails": {
        "searchNew": 1
    },
    "projectLoadTimes": ":491",
    "fileOpenTimes": "",
    "ModuleDepsResolved": 3460,
    "AppStartupTime": 11204,
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": [
        {
            "name": "beldar.auto-brackets",
            "version": "0.0.9"
        },
        {
            "name": "brackets-css-concat",
            "version": "0.0.1"
        },
        {
            "name": "brackets-js-concat",
            "version": "1.0.0"
        },
        {
            "name": "dcblocks-brackets",
            "version": "0.0.4"
        },
        {
            "name": "drewkoch.icons",
            "version": "1.3.1"
        },
        {
            "name": "lesshints",
            "version": "1.1.0"
        },
        {
            "name": "pflynn.reasonable-comments",
            "version": "1.3.0"
        },
        {
            "name": "tjeffree.extensionhighlighter",
            "version": "1.2.2"
        },
        {
            "name": "camden.csslint",
            "version": "2.0.21"
        },
        {
            "name": "brackets-morecsscodehints",
            "version": "1.2.0"
        },
        {
            "name": "brackets-html5codehints",
            "version": "1.2.1"
        },
        {
            "name": "brackets-viewcalc",
            "version": "0.1.1"
        },
        {
            "name": "io.brackets.color-palette",
            "version": "2.0.1"
        },
        {
            "name": "growlscript.brackets.classcompletion",
            "version": "0.2.1"
        },
        {
            "name": "brackets-minify",
            "version": "1.1.5"
        },
        {
            "name": "camden.w3cvalidation",
            "version": "2.2.2"
        },
        {
            "name": "brackets-beautify",
            "version": "1.2.0"
        },
        {
            "name": "csscomb-brackets",
            "version": "0.0.1"
        },
        {
            "name": "mikaeljorhult.brackets-autoprefixer",
            "version": "0.6.2"
        },
        {
            "name": "edge-code-web-fonts",
            "version": "0.1.7"
        },
        {
            "name": "adobe.brackets.extract",
            "version": "0.8.0-1749-release"
        }
    ],
    "bracketsTheme": "light-theme"
}
```


Also here is errors from console

![console](https://cloud.githubusercontent.com/assets/11228203/13029449/ffa2c312-d28c-11e5-939e-244b5633bff3.png)


Thanks in advance!

**Comment by petetnt** [comment]
Seems like the node connection is going down on launch due to too many connections, similar to https://github.com/zaggino/brackets-git/issues/410, https://github.com/petetnt/brackets-sass-lint/issues/2, https://github.com/jasonsanjose/brackets-sass/issues/106 and tons of others.

**Comment by abose** [comment]
Can you expland the erros for IMSProxy.js in console and comment the errors stack here.
Are you behind a firewall or proxy?

**Comment by marioloncarek** [comment]
@abose No proxy whatsoever

@petetnt but why reloading is fixing it? on reload all connections reload too?

**Comment by petetnt** [comment]
@marioloncarek I think it's due to just the nature of the issue: some script(s) fails to connect a few times, max connection attempts get reached, crashing the Node process. The `MAX_CONNECTION_ATTEMPTS` is rather low, only 10.

https://github.com/adobe/brackets/blob/afb5249413781bf2f25a2d36baa7ba7ce3bca7f8/src/utils/NodeConnection.js#L39

Maybe it would be worth it trying to bump it up a bit (to say, 100) and see if the situation improves. 

Wait, doesn't this line like always return the delay to be like an 1ms:

https://github.com/adobe/brackets/blob/afb5249413781bf2f25a2d36baa7ba7ce3bca7f8/src/utils/NodeConnection.js#L314 ?

**Comment by marioloncarek** [comment]
@petetnt So how things are now, everybody has problems with node connections, all i can do is reload until brackets shows mercy?

**Comment by abose** [comment]
Deprecated feature, closing.
