### ISSUE TITLE
Some twitter bootstrap functionality would be awesome.

### ISSUE THREAD

**Issue by rwilcher** [adobe/brackets#12200]
Some twitter bootstrap functionality would be awesome.

**Comment by rwilcher** [comment]
Not an issue but something that would be really nice.

**Comment by petetnt** [comment]
There's this extension which you can use to add a Bootstrap skeleton to your file: https://github.com/mirorauhala/brackets-bootstrap-skeleton

**Comment by rwilcher** [comment]
On 2/10/2016 3:46 AM, Pete Nykänen wrote:
> There's this extension which you can use to add a Bootstrap skeleton to
> your file: https://github.com/mirorauhala/brackets-bootstrap-skeleton
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adobe/brackets/issues/12200#issuecomment-182254330>.
>
Thanks you so much. Getting now. I had no idea.

--
