### ISSUE TITLE
Using huge memory with SSH connection

### ISSUE THREAD

**Issue by GanjaPowered** [adobe/brackets#12207]
Since i'm working with SSH (Thanks to Synapse), Brackets is using a lot of RAM and is Freezing more and more

[http://gaetan-legac.fr/Upload/brackets-freeze.png](http://gaetan-legac.fr/Upload/brackets-freeze.png)

I'm using Debian 8 x64
Don't hesitate to ask more informations about my workspace if you need

**Comment by petetnt** [comment]
Hi @GanjaPowered,

as this is most likely a Brackets-Synapse issue, you should try reporting this to the [extension repository](https://github.com/kooohei/brackets-synapse) first. If turns out to be an Brackets core issue, feel free to continue the discussion here afterwards.

**Comment by GanjaPowered** [comment]
Thanks for your response, I will report this issue to Synapse devs.

**Comment by petetnt** [comment]
Actually now that I think about this, can you launch Brackets without extensions (Debug -> Launch Brackets Without Extensions) to ensure that this is an extension issue.

There has been couple of issues with high CPU use under Linux too. Can you try installing this https://github.com/zaggino/brackets-file-tree-exclude extension and see if the situation improves (by excluding third party folders such as node_modules)

**Comment by GanjaPowered** [comment]
Without extensions, it consums around 200 Mio and I have no freezes
Also I never had any freeze since I'm using Brackets (> 3 years)

I will try this extension, thanks !

**Comment by petetnt** [comment]
@GanjaPowered thanks, then it's most likely due to the Synapse extension (or some other extension)

**Comment by busykai** [comment]
@GanjaPowered, thank you for filing the issue with Synapse. @petetnt is right, it's most likely an issue due to an extension. I'm going to close this. If it's later diagnosed to Brackets core, we could re-open this.
