### ISSUE TITLE
Error on startup, folders don't load contents on Ubuntu

### ISSUE THREAD

**Issue by chrislambrecht** [adobe/brackets#12215]
I've used Brackets in a crouton/Ubuntu environment for some time now. It ran fine when starting from the terminal, but gave me this error message when trying to run from anywhere else (ie: applications menu, etc):

> "Error Opening File: An Error occurred when trying to open the file /opt/brackets/samples/root/Getting Started/index.html. Brackets currently only supports UTF-8 encoded files"

(It's worth mentioning that it shows this error after a fresh install, and repeated re-installs.)

Now, I get this error regardless of how I start the program, in addition to the other problems I describe below.

After I press OK, I'm able to individually load and edit files, but not much else. Trying to open a folder will show its name but not any of its contents. 

If I create a new file, that works okay and does show up in the folder which it was created. That said, if I close and reopen Brackets, it tries to take me back to the Getting Started page (and fails). In other words, it fails to reopen where I last left off.

I've really only seen this issue mentioned in one other place: [Issue 11739](https://github.com/adobe/brackets/issues/11739). The solution offered there, editing ~/.bashrc to include  `unset LC_ALL` did not work for me.

I've recently decided to abandon Unity in favor of xfce. These errors started once I installed xfce. I did try reinstalling Unity and Brackets _does_ work like it used to in that environment, but it's critical that I get Brackets working in xfce.

I'm using Ubuntu 14.04.

**Comment by sshunter** [comment]
I ran into this today and just found your post. Based on the link you included, I was able to get brackets working sanely by adding "export LC_ALL=en_US.utf8" to ~/.bashrc 

I haven't done enough yet to know if that causes problems with other programs under xfce or even linux in general. But so far so good.

**Comment by jlam55555** [comment]
I'm new to Brackets (and GitHub issues, so bear with me):

I'm experiencing the same issue (Brackets 1.6 on Ubuntu 14.04), and adding `export LC_ALL=en_US.utf8` to ~/.bashrc didn't work for me. Do you have any other possible solutions?

**Comment by sshunter** [comment]
Sorry, put the line at the end of the .profile file instead of .bashrc 

I just double-checked. Adding it to .bashrc lets brackets start from a terminal window, but launching from the menu still shows the error. .profile works for both.

**Comment by chrislambrecht** [comment]
>  I was able to get brackets working sanely by adding "export LC_ALL=en_US.utf8" to ~/.bashrc

That did it. Thanks! Still have to open from Terminal, but I'll take it!
