### ISSUE TITLE
view > word wrap

### ISSUE THREAD

**Issue by robinpecha** [adobe/brackets#12210]
Cant find command to toggle word wrap from keyboard.
To assign keyboard shortcut.

**Comment by robinpecha** [comment]
view.toggleWordWrap

I found shortcut for view.togglePanels and guess word wrap.
Is there some list of all commands?

**Comment by MiguelCastillo** [comment]
Yup - try this https://github.com/adobe/brackets/wiki/User-Key-Bindings.

**Comment by ficristo** [comment]
You can try this extension too https://github.com/redmunds/brackets-display-shortcuts
