### ISSUE TITLE
icons / font missing from treeview

### ISSUE THREAD

**Issue by jmls** [adobe/brackets#12218]
I am obviously missing something - when using 1.6 of brackets, I get this when viewing the directory folders

![image](https://cloud.githubusercontent.com/assets/929523/13071051/d0663dba-d488-11e5-9c1b-f1a85d9a033e.png)

I have tried various icons / fonts but can't seem to find the solution, so here's hoping that some smart person will just say "ah, you need to do this ..." ;)

**Comment by petetnt** [comment]
Most likely an extension / theme issue. Which treeview icon-extension are you using?

**Comment by jmls** [comment]
I tried them all ;) then removed them

**Comment by jmls** [comment]
ah, I *did* install a tabs extension : Tabs - Custom Working

**Comment by jmls** [comment]
yup. removed that, the boxes disappear. Is there a recommended plugin for showing icons ? 

![image](https://cloud.githubusercontent.com/assets/929523/13071192/c9656170-d489-11e5-9b46-b7e9320a1001.png)

This is the "look" I'm trying to get ...

**Comment by petetnt** [comment]
I use https://github.com/ivogabe/Brackets-Icons personally but it's bit fancier.

if you have the icons at hand, you could try making an new icon provider for yourself. It's a bit badly documented feature (I think, I couldn't find any good references to it) but https://github.com/drewbkoch/Brackets-File-Icons/blob/master/main.js could work as a starting point.

**Comment by abose** [comment]
Closing as extension problem. The related documentation bug is tracked.
