### ISSUE TITLE
brackets extensions not working on windows 10

### ISSUE THREAD

**Issue by jckane67** [adobe/brackets#12213]
I have brackets 1.6 installed on my desktop windows 7 machine. The extensions work fine. I did the same install on my laptop windows 10 and although brackets works fine none of my extensions work. They all installed successfully and have a status of enabled. They show no effect when I'm editing. My extensions are indent guide, paste and indent, visual studio theme and w3cvalidator. I've uninstalled brackets, rebooted cleared my cache, even tried installing 1.5 and followed all the procedures from the support articles nothing worked. Any ideas would be appreciated. I'm currently at Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) build timestamp: Tue Jan 12 2016 13:58:11 GMT+0000

**Comment by petetnt** [comment]
Do you see any errors in Debug -> Show Developer Tools?

**Comment by jckane67** [comment]
No, I did not. I just got the warning I pasted in below. I should also mention that I tried removing all my extensions except for the visual studio just to make this easier to debug. I've tried different extentions (one at a time), did not seem to matter. I also am working editing on a remote server (I don't have a local web server installed). This is the environment that works on my desktop. Here is the past from the debug you asked for:  "Download the React DevTools for a better development experience:" Thanks

**Comment by lkcampbell** [comment]
@jckane67 The React Dev Tools message is popping up because the Brackets file tree uses React. Doesn't indicate there is a problem.

When you say you cleared the cache, do you mean you went to C:\Users\<user>\AppData\Roaming\Brackets\ and deleted everything in that folder?

**Comment by jckane67** [comment]
I just tried your way, reinstalled, rebooted and things are working now!! Thanks everyone for all the help.

**Comment by raselshifat** [comment]
i have a problem,when i open brackets and drop my folder on brackets .then always brackets show that "brackets currently only supports UTF-8 encoded text files"

please anyone tell me .what to do :(

**Comment by petetnt** [comment]
Hi @raselshifat, 

Currently, like the error says, Brackets only supports UTF-8 encoded files. Try installing this extension to convert your files: https://github.com/Armacryss/brackets-utf8-converter 👍
