### ISSUE TITLE
Get All Opened Editors

### ISSUE THREAD

**Issue by Murazaki** [adobe/brackets#12226]
Brackets API doesn't allow to get the list of opened editors or even to get the editor linked to a pane.

Proposed solutions :

**Proposition 1:** provide two functions to the Editor API :

````javascript
// in EditorManager
getAllOpenedEditors()

// in Editor
getParentPane()
````

**Proposition 2:** provide one function to the Pane API and get the list of Panes from MainViewManager:

````javascript
// in Pane
getAttachedEditor()
````

**Comment by busykai** [comment]
@Murazaki, what's the context of this issue? What are you trying to accomplish?

**Comment by Murazaki** [comment]
I'm simply trying to have a Minimap per split view pane on Brackets. I've seen that most of the extensions have to dive into the HTML or hack the API code to get that type of info.

Also I have to say the way you handle Editors leaves me confused. (I'm not quite sure if you always have an editor opened per view pane or just one opened on the active view pane ?)

**Comment by busykai** [comment]
The hierarchy is as follows (without getting into too much details): `Pane` => contains 0 or more => `View` => corresponds to => `Document` => has one or more => `Editor`.

Each `Pane` has `getViewList()` which returns an array of files for which this `Pane` instance has views, but it sounds like what you need is really `Pane.getCurrentlyViewedPath()`. Or you can get currently visible editor on currently active pane via `EditorManager.getCurrentFullEditor()`.

There's always an `Editor` instance per each file opened (i.e. the files in the working set + the file opened in the file tree if any). For view-only files (such as images), there's no editor, only a `View` instance in the `Pane`.

**Comment by abose** [comment]
Closing stale issue.
