### ISSUE TITLE
Pasting indentation

### ISSUE THREAD

**Issue by Amosss** [adobe/brackets#12225]
I read the following about pasting indentation:
https://github.com/adobe/brackets/issues/2444
https://trello.com/c/Oy3VvywW/350-code-formatting-auto-indent-on-paste-3
it's from 2012, any idea if/when it will be implemented?

I tried the following extension but it doesn't seem to work, there's also an unanswered issue about it:
https://github.com/ahuth/brackets-paste-and-indent/issues

Is there an extension that fixes this until it will be added to brackets?
Thanks

**Comment by abose** [comment]
Pasting and then applying the `brackets-beautify` extension over the pasted code is one workaround.

**Comment by abose** [comment]
Closing as the trello story already covers this feature request.

**Comment by Amosss** [comment]
It covers it but from a long time ago and I was wondering if/when it will be implemented, thanks
