### ISSUE TITLE
A file "saved as" another file but not showing at the left panel in the file list

### ISSUE THREAD

**Issue by jianlin** [adobe/brackets#12220]
I am using 

Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) 
build timestamp: Tue Jan 12 2016 05:35:00 GMT-0800

on Mac Mavericks.  If I have a file and then I use Save As, to save as another file, it really should show at the left panel in the file list, without we having to "refresh the tree".  I think you can observe on the top directory using some OS call and be notified when the tree structure changes.

(note that the file is under `js` folder in the top folder. the file will show if it is actually right in the top folder, but won't show if in `js` folder.)

**Comment by petetnt** [comment]
Most likely fixed by #12145

**Comment by abose** [comment]
A build refresh is scheduled by his week or next for 1.6 and after that the new installers posted will contain this fix.
Closing as fixed.
Please reopen if the  issue is not fixed.
Will inform when the new installers are avilable.
