### ISSUE TITLE
hinting different languages

### ISSUE THREAD

**Issue by Amosss** [adobe/brackets#12224]
Hi, what extensions do you recommend for the following types:

css: seems like brackets handle it by itself

php: any recommended extension for that?

html: any recommended extension for that?

js: angular js seems to be supported by brackets internally.

json: not sure if hinting is relevant here but if you know of such extension, do share

Thanks

**Comment by petetnt** [comment]
CSS, HTML and JS are handled by Brackets internally. 

For PHP there are at least couple of hint extensions:
https://github.com/Brackets-PHP/Brackets-PHP-SmartHints
http://www.oslibrary.in/other-information-code/brackets-php-syntax-hint

**Comment by abose** [comment]
Closing as answered.

**Comment by Amosss** [comment]
html: Apparently it's even smarter than I thought because it knows if I have attribute "class" (for example) for "div" tag and knows not to hint me on this when I press c, this is why I thought it doesn't work. nice!
