### ISSUE TITLE
Extensions window is loading forever and brackets can't be exited

### ISSUE THREAD

**Issue by Amosss** [adobe/brackets#12223]
Sometimes, with no apparent reason, the extensions windows is loading forever when opening it. I can close the window but I can't close brackets and I have to kill it via the task manager. (I'm on Windows 7)

**Comment by abose** [comment]
Can you go to  `help>health report` and comment the health report here?

**Comment by Amosss** [comment]
{
    "uuid": "e89a71f4-6e2f-4d05-9393-7ab749bab0e8",
    "snapshotTime": 1455704063859,
    "os": "win",
    "userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.6.0.0 Chrome/39.0.2171.36 Safari/537.36",
    "osLanguage": "en-US",
    "bracketsLanguage": "en-US",
    "bracketsVersion": "1.6.0-16680",
    "fileStats": {
        "openedFileExt": {
            "json": 17,
            "js": 9,
            "html": 15,
            "css": 11,
            "php": 6
        },
        "workingSetFileExt": {
            "js": 1,
            "json": 1,
            "php": 1,
            "css": 1,
            "html": 1
        }
    },
    "ProjectDetails": {
        "prj2047334813": {
            "numFiles": 17,
            "cacheSize": 421533
        }
    },
    "projectLoadTimes": ":199",
    "fileOpenTimes": ":492",
    "ModuleDepsResolved": 48126508,
    "AppStartupTime": 48127634,
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": [
        {
            "name": "deddy.additional-right-click-menu",
            "version": "0.5.1"
        },
        {
            "name": "lamo2k123.brackets-file-tree",
            "version": "1.1.1"
        },
        {
            "name": "camden.jshint",
            "version": "2.2.18"
        },
        {
            "name": "custom-color-highlighter",
            "version": "1.0.0"
        },
        {
            "name": "interactive-linter",
            "version": "1.0.5"
        },
        {
            "name": "milosh86.extensions-bulk-installer",
            "version": "0.2.0"
        },
        {
            "name": "mackenza.php-smarthints",
            "version": "1.2.2"
        }
    ],
    "bracketsTheme": "light-theme"
}

**Comment by Amosss** [comment]
When the "loading forever" happens and I close the extensions window, I can do nothing (not only "can't exit"). For example, I open the help menu and press the health report entry but it doesn't do anything.

**Comment by petetnt** [comment]
Try disabling your extensions one by one to rule out extension issues.

Extensions can be found under `%AppData%\Roaming\Brackets\extensions`, just move the extensions to `disabled` folder.

**Comment by Amosss** [comment]
I guess I can disable the extension from the extensions window instead of copying it to the disabled folder but the thing is, it doesn't happen often. It can work for a long time and the suddenly it will happen so testing it by disabling the extensions one by one can take forever since I don't have an exact scenario to reproduce it.

**Comment by abose** [comment]
Are you on a slow internet connection?

**Comment by Amosss** [comment]
Not really, 15mb dsl. I can understand that sometimes a connection is not established correctly but maybe a time out or cancel should occur at some point or when closing the window.

**Comment by abose** [comment]
Closing long pending issue. Please feel free to reopen if the problem persists.
