### ISSUE TITLE
indent softwraps extension switcher

### ISSUE THREAD

**Issue by bucharra** [adobe/brackets#12221]
Hi, I'm using 

1.6.0-16680 (release 3df0ac6fa) 
build timestamp: Tue Jan 12 2016 13:58:11 GMT+0000

I installed the _indent-softwraps-extension_ [https://github.com/scriptin/brackets-indent-softwraps] and it changed line wrap, now I can't change it back. I noticed that such option is already present in editor but there is no such menu or config switch in this release to change it. Can you add it in feauture releases? Or if I missed something please show me.

**Comment by petetnt** [comment]
Word wrap-toggle can be found under `View -> Word Wrap`. Does that fix it?

**Comment by bucharra** [comment]
Unfortunately no, that plugin makes the following -- "When a line does not fit in editing area, it is softwrapped. This extension makes it so the wrapped part (2nd and subsequent lines) has the same indentation as the 1st line" also you can see visual explonation of what exactly it does from upside link

**Comment by abose** [comment]
You can uninstall the extension from the extension manager (`file menu> extension manager`). go to installed extensions and uninstall the extension. 
Brackets 1.6 wraps the line such that the previous line's intent is maintained.

**Comment by bucharra** [comment]
Already done, no changes. There is menu option _View -> Word Wrap_ which changes line wrap, but it doesn't solve this problem. When it's not activated it makes lines full-width and horisontal scrollbar appears to see the entire line. When it is, lines wrap are like as I explained above.

**Comment by petetnt** [comment]
Oh I get it now @bucharra.

#11909 introduced *proper* indents for line wrapping. Bad news is that it's not possible to have the original behavior back easily. I think it would make sense to have the indent-wrapping on and off on preference basis.

If you want to work around this limitation, you can remove this method from `editor.js`:
https://github.com/adobe/brackets/pull/11909/files#diff-3b7e955135e4a77b20767ed40e551395R986

Here's the guidelines on how to hack on Brackets.
https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets

**Comment by bucharra** [comment]
@petetnt thank you alot for advice

**Comment by abose** [comment]
Closing as this is the default behavior.
If we get more upvotes on this request, will add the preference.
Thanks .
