### ISSUE TITLE
Closing files via ctr+w

### ISSUE THREAD

**Issue by addui** [adobe/brackets#12231]
When I close a file via ctr+w it closes the file from the text editor section but it still shows up in the "working files" list  on the left. If I do this to multiple files and then click the "x" next to one of the files in the "working files" list it finally catches up and removes all the files from that list that have been closed.

**Comment by petetnt** [comment]
Hi @addui,

There's a fix tracking at #12145

**Comment by abose** [comment]
A build refresh is scheduled by his week or next for 1.6 and after that the new installers posted will contain this fix.
Closing as fixed.
