### ISSUE TITLE
is there any plugins such as sublimeTmpl ?

### ISSUE THREAD

**Issue by fashman** [adobe/brackets#12244]
there is no templet to quick create html/css/js templet,such as sublimeTmpl plugin;
Is there any plugins in brackets like sublimeTmpl ???
Is there any plugins in brackets like sublimeTmpl ???
Is there any plugins in brackets like sublimeTmpl ???

**Comment by fashman** [comment]
anyone can help me?

**Comment by petetnt** [comment]
@fashman You can use something like https://github.com/chuyik/brackets-snippets to create the templates as snippets. There's also some extensions like https://github.com/talmand/Brackets-HTML-Templates for HTML templates.

**Comment by fashman** [comment]
@petetnt  thanks!

**Comment by abose** [comment]
closing as answered
