### ISSUE TITLE
Epub editor extension

### ISSUE THREAD

**Issue by Editorenbici** [adobe/brackets#12249]
Hi all! 
Will be great to have a extension that allow to create ebooks in epub 3 format with all the awesome options that Brackets has. Is it posible?

**Comment by abose** [comment]
Not possible yet. 
Good idea for extension.
Closing.

**Comment by abose** [comment]
Checked through the extension list and there doesn't seem to an extension for epubs yet. You could write one.
Or alternatively, download `Kitten Cat Dog Gifs for Relaxation` extension; that fixes everything.
