### ISSUE TITLE
Unable to edit CSS with ctrl+e

### ISSUE THREAD

**Issue by debbieweiser** [adobe/brackets#12256]
Hi community,

I'm doing a course on HTML and CSS and when I try to make edits to the class with ctrl+e, I get a message that I don't have any stylesheets in my project. But that doesn't make sense, because in the live preview, my CSS is showing up. Both files are saved in the same folder on my desktop. Help, please. :)

![ctrl issue](https://cloud.githubusercontent.com/assets/17555774/13430488/e95c5d90-dfcd-11e5-9dd1-49d6b236f217.PNG)

**Comment by debbieweiser** [comment]
W

**Comment by debbieweiser** [comment]
Hi @petetnt,

I think I accidentally typed the above comment when my phone was in my pocket. Oops. :)

Thank you for your help. You were right. It was because I opened two individual files instead of a folder and so Brackets didn't recognize that they are connected.

Have a great day,
Debbie

**Comment by petetnt** [comment]
@debbieweiser Great that your problem got fixed! Happy Brackets-ing!
