### ISSUE TITLE
Скорость открытие редактора

### ISSUE THREAD

**Issue by Maxa223** [adobe/brackets#12258]
Очень долго программа запускается,если сравнить с sublime next 3...даже без окн программа долго грузится,сделайте что то..

**Comment by abose** [comment]
Opening Speed ​​Editor

the program runs a very long time when compared with the sublime next 3 ... even without the window long program is loaded , do something ..
Translated.

**Comment by abose** [comment]
duplicate . closing.
https://github.com/adobe/brackets/issues/11106
