### ISSUE TITLE
Use stylus not  AutoComplete?

### ISSUE THREAD

**Issue by yi-huan** [adobe/brackets#12255]
I want use stylus like scss  Key tips,how to do ?
使用 stylus，如何像 scss 的文件那样 有 css 的属性名及值的 提示？ 
在 Brackets\www\extensions\default\CSSCodeHints 中，在 main.js 的 466 行 增加 stylus 不生效。

**Comment by sprintr** [comment]
I wrote one a while ago. [Here](https://github.com/sprintr/brackets-stylus-code-hints) it is. Feel free to file an issue if you want a feature in it.

**Comment by yi-huan** [comment]
Thanks, I'll see if I can customize property value delimiters

**Comment by yi-huan** [comment]
It's works,  I like the syntax of the stylus and the CSS rules。Thank you again

**Comment by abose** [comment]
Closing as answered.
Thanks @sprintr
