### ISSUE TITLE
how to change the color of menu icons?

### ISSUE THREAD

**Issue by tjnapster555** [adobe/brackets#12252]
i want to know how i can change the color of toolbar icon lof these 
![Imgur](http://i.imgur.com/33JA7Do.png)

to white color because i cant see these easily and can i increase the size of these icon too ?

**Comment by petetnt** [comment]
The icons can be found in here: https://github.com/adobe/brackets/tree/master/src/styles/images

To change the `gray` to white, you usually need to change the fill color.

For example:

```
<svg
xmlns="http://www.w3.org/2000/svg"
xmlns:xlink="http://www.w3.org/1999/xlink"
width="13px" height="53px">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <path d="M0,21 L0,32 L13,32 L13,21 L0,21 Z M1,22 L1,31 L6,31 L6,22 L1,22 Z M7,22 L7,31 L12,31 L12,22 L7,22 Z" id="split-horizontally" fill="#6C7478"></path>
        <path d="M0,42 L0,53 L13,53 L13,42 L0,42 Z M1,43 L1,47 L12,47 L12,43 L1,43 Z M1,48 L1,52 L12,52 L12,48 L1,48 Z" id="split-vertically" fill="#6C7478"></path>
        <g id="arrows" transform="translate(1.000000, 3.000000)" fill="#6C7478">
            <path d="M3,0 L3,5 L0,2.50785714 L3,0 Z" id="Fill-3"></path>
            <path d="M11,0 L11,5 L8,2.50785714 L11,0 Z" id="Fill-3-copy" transform="translate(9.500000, 2.500000) rotate(-180.000000) translate(-9.500000, -2.500000) "></path>
            <path d="M2,2 L2,3 L9,3 L9,2" id="Fill-5"></path>
        </g>
        <path d="M0,0 L0,11 L13,11 L13,0 L0,0 Z M1,1 L1,10 L12,10 L12,1 L1,1 Z" fill="#6C7478"></path>
    </g>
</svg>
```

Changing the `fill` to `#fff" on the path changes the color to white.

Best way to do this you most likely should make your own theme which overrides the required values. For example, if you want to change the split view icons to your own:

1. Copy the file to your theme (https://github.com/adobe/brackets/blob/master/src/styles/images/split-view-icons.svg)
2. Change the colors to white
3. Find the line you need to override in [brackets.less](https://github.com/adobe/brackets/blob/master/src/styles/brackets.less#L835)
4. Override it in your theme:

```
.working-set-splitview-btn {
    .sprite-icon(0, 0, 13px, 13px, "images/split-view-icons-tjnapster555.svg");
}
```

(Note that some of the icons are off the `editor` area and changing them with themes might not be entirely supported. See https://github.com/adobe/brackets/wiki/Creating+Themes)
