### ISSUE TITLE
Deleting index.html and main.css default files

### ISSUE THREAD

**Issue by debbieweiser** [adobe/brackets#12253]
Why won't the program allow me to delete the default files?

**Comment by ryanstewart** [comment]
Those are included in part to show you how to use some of the features in Brackets. They usually are stored in a location that isn't meant to be written by the user. Instead you can use File->Open Folder to open a new set of files. Brackets will open the last set of files you opened next time it starts so the default files won't show up every time.

**Comment by debbieweiser** [comment]
Thanks, Ryan. The issue is mainly that when I try to make edits to the class with the quick edit option, it saves my CSS code to the main CSS file and not the new one I created. (Hope that made sense).

**Comment by debbieweiser** [comment]
Oh, I fixed it. I just saw this post. Sorry for the trouble. https://github.com/adobe/brackets/issues/1577

**Comment by ryanstewart** [comment]
Ahh, glad you found that! Happy Brackets-ing!
