### ISSUE TITLE
Extract for Brackets (PSD does not display correctly)

### ISSUE THREAD

**Issue by libertyswift** [adobe/brackets#12263]
seen only on Linux (brackets 1.6)
In Brackets problems with graphics using the Extract for Brackets. PSD does not display correctly.
https://yadi.sk/i/V4fFtSVAppAVo
Just under 100% PSD looks ok, https://yadi.sk/i/LoEwpmw3ppC7C, but if you reduce all the creeps as in the example above. https://yadi.sk/i/zE3NEOM8ppCaQ icon Breckets here, too, it is not displayed correctly.

**Comment by ficristo** [comment]
Extract has been deprecated: http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/
Closing.
