### ISSUE TITLE
The copyright still displayed 2015 in the About dialog with the refresh build.

### ISSUE THREAD

**Issue by YanChen002** [adobe/brackets#12268]
Problem:
The copyright still displayed 2015 in the About dialog with the refresh build.

Method:
1. Launch the Brackets.
2. Click Help - > Brackets

Result:
Copyright displayed as “2012-2015”
![image](https://cloud.githubusercontent.com/assets/17636671/13566366/2b9c6bd4-e490-11e5-988b-1d9730dd7e5f.png)

Expected:
Copyright should be displayed as “2012-2016”

**Comment by abose** [comment]
This is already fixed for 1.7 by https://github.com/adobe/brackets/pull/12092
Closing
