### ISSUE TITLE
Can Brackets Generate The Basic Structure Of A Web Page?

### ISSUE THREAD

**Issue by hawksKane** [adobe/brackets#12267]
Is there a way to generate the basic code of a html page using keystrokes? Like Ctrl+Tab?

**Comment by petetnt** [comment]
Hi @hawksKane, there's variety of extensions available for that, such as [Brackets-html-skeleton](https://github.com/le717/brackets-html-skeleton). You can install it via extension manager (File -> Extensions).

**Comment by abose** [comment]
Closing as answered.

**Comment by hawksKane** [comment]
Ok, thanks for responding. I have Emmet and the HTML Skeleton installed in Brackets. What I don't know is how to work it. How do I create a basic html started page by using those extensions?

**Comment by hawksKane** [comment]
Never mind..... I think I figured  it out.

**Comment by petetnt** [comment]
@hawksKane Great! Do post back if you have anything else to ask :+1:

**Comment by ramahr** [comment]
@petetnt it is better to always provide the solution even though the person has figured out the solution coz someone having the same issue can easily find help
@ghost tell us how you went about to find the solution
otherwise thanks to everyone

**Comment by aharisingh** [comment]
Brackets text editor can generate basic structure of Html for that  you need to install Emmet.
for installing Emmet you need to follow following steps.
 Run Brackets.
 Select File > Extension Manager...
 Find “Emmet” extension and click “Install” button.

**Comment by shadizghe** [comment]
@aharisingh Thank you!!

**Comment by boygagaoriginal** [comment]
> press exclamation mark(!) and then tab key to generate basic structure of html.
Wow! It's really worked. Angela Yu in her video about "What is The HTML Boilerplate" told to "to simply write "html" and hit "Enter"" and it worked in her Atom editor, but the same just didn't worked in my Brackets editor.
Hint:
There is a [Cheat Sheet for Emmet](https://docs.emmet.io/cheat-sheet/).
