### ISSUE TITLE
Cross Browser Live Preview

### ISSUE THREAD

**Issue by GayleAHilton** [adobe/brackets#12260]
On the brackets blog it gave me this code:

    Debug->Open Preferences File
    Add "livedev.multibrowser": true inside of the curly braces on a new line (make sure to add a comma above it if you add it to the end)
    Hit the Live Preview button and Live Preview will open up in your default browser
    

When I hit the Live Preview it takes me to Chrome (which is what always comes up)- and my default browser is Firefox.  I am using a Mac and running the latest version of Firefox - is there something else I can try as I really want to be able to use Firefox as the browser Brackets dafaults to for coding purposes.

Thanks - Gayle

**Comment by petetnt** [comment]
Hi @GayleAHilton, make sure you have `File -> Enable Experimental Live Preview` enabled too.

**Comment by abose** [comment]
Closing as already supported via ` File -> Enable Experimental Live Preview `

**Comment by GayleAHilton** [comment]
Hi Arun,

I have the File/Enable Experimental Live Preview enabled.  I opened an html file called index.html in brackets.  When I click on the live preview
I get an error message saying “Open an HTML file or make sure there is an index.html file in your project in order to launch live preview.  I am new
to brackets and do not understand why when I have an html file open it will not launch.  Could you please tell me what it is that I am doing wrong.

Thanks - Gayle

**Comment by GayleAHilton** [comment]
More Information:  I am using the software that comes with Brackets (the Getting Started index.html and main.css files are open in the Working Files).
Prior to making the changes to use Firefox instead of Chrome I was able to get a live preview of this html file - now it is giving me the error message
below.  I have tried to open other index.html files from my computer but I still get the error message below.  What am I doing wrong?  Thanks in
advance for your insight.

Regards,

Gayle

**Comment by busykai** [comment]
@GayleAHilton, do you have `Getting Started` project opened? You need to open a project to use Live Preview on it, not just files. If that does not help, please use *Debug -> Show Developer Tools* and see if there's any error message in the console.

**Comment by GayleAHilton** [comment]
Hi,

My index.html(Getting Started) file is on the screen.  Under Working Files is index.html and main.css.
Under Getting Started is index.html main.css and then a folder for screenshots with nothing in it.
I wend to Debug/show develper tool console and I have attached the text it gave me back.

Hope this helps, 

Gayle

**Comment by GayleAHilton** [comment]
Hi,

I have been trying to get the instructions (written on Dec 18, 2014) by Ryan Stewart on the brackets blog to allow the
use of cross-browser live preview - specifically I am trying to open live preview in Firefox instead of Chrome.
Here is what I am trying to do as per these instructions:

Debug->Open Preferences File
Add "livedev.multibrowser": true inside of the curly braces on a new line (make sure to add a comma above it if you add it to the end)
Hit the Live Preview button and Live Preview will open up in your default browser
Copy/Paste the URL from that browser to any other browser
Any Live Preview changes will update across all of the browsers open with that page
Brackets give me a live preview in Chrome no problem.  As soon as I add the code"livedev.multibrowser": true inside of the curly braces 
and try to run Live Preview I then get the error message :
Open an HTML file or make sure there is an index.html file in your project in order to launch live preview.

If I remove the line from the preference file I can again use brackets with Chrome - so it appears that these instructions do not work.

Yesterday I sent the Debug code and never heard anything back.

Is this a known problem with Brackets?  I have spent hours trying to fix this as I want a code editor with the features of Brackets but
I want it to work with Firefox.  

Please let me know if this product and the fix for Cross-Browser Live Preview outlined in your blog works?  If so why is it not working when
I follow the instructions.  

If it does not work please let me know so I can stop wasting my time trying to get it to work.  If it does work please let me know what it is I am
doing wrong.

Thanks in advance for your attention to my issue.

Regards,

Gayle

**Comment by redmunds** [comment]
@GayleAHilton There is now a menu item for this, so you no longer have to manually edit your preferences json files. Use: _File > Enable Experimental Live Preview_

**Comment by GayleAHilton** [comment]
Hi,

I have already got that feature activated and I still get the error message to open an html file.  

Gayle

**Comment by GayleAHilton** [comment]
Hi,

I took the line out of my preference file that was in your blog and now I can get a live preview - but Chrome still comes up
and not firefox.

The Enable Experimental Live Preview is active in the menu.  Is there something else I have to do to have brackets
go to Firefox instead of Chrome?

Thanks

Gayle

**Comment by GayleAHilton** [comment]
Hi,

Every time I turn on the Enable Experimental Live Preview I get the error message regarding having an html file loaded.
If I turn it off then it takes me to Chrome.  
Now when I go into my html file and make changes it is not doing anything in Chrome??  I have tried deleting all my brackets
files and reloading brackets from the start to no avail.

Now I cannot even use it to learn as the feature does not make changes unless you save it - I thought it was supposed to be
live changes that you would see in Chrome??

Thanks

Gayle

**Comment by redmunds** [comment]
The Experimental Live Preview opens to your default browser.

The most common error when using Live Preview is that it doesn't work with files outside of your file tree (left sidebar). Use _File > Open Folder..._ to open your "project" folder that contains all of your files.

If it's still not working, be sure to read the [Live Preview section of the How To Use Brackets doc](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#live-preview) and the [Live Preview Isn't Working section of the Brackets Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting).

**Comment by GayleAHilton** [comment]
I have gone through the steps in these documents and still cannot get this code editor to work.  I guess I am just stupid as when
I follow the instructions it still does not work.  This is the most frustrating experience I have had as I have spent hours trying to
get a simple edit to show up when I change my html - it simply does not work.  Seeing as I am not able to get any more support
other than read the documentation I will now look for another code editor where it is not so complicated and they have support
staff that are willing to help resolve problems.

Frustrated and fed up - Gayle

**Comment by Nuc1eoN** [comment]
Hi, I get the exact same error. Can you please reopen?

**Comment by Bru141** [comment]
My guess would be that Chrome is your default browser. If you remove it, Brackets will have no choice but to open in Firefox. Either Brackets or your operating system is defaulting to Chrome (Google malware). I don't have Chrome on my computer and Brackets opens Firefox easily.

**Comment by Bru141** [comment]
Use startpage.com to search for "changing your default browser".

**Comment by Nuc1eoN** [comment]
Nope. Firefox is my default browser.

**Comment by Nuc1eoN** [comment]
Could anyone please reopen??

**Comment by charlie39** [comment]
https://stackoverflow.com/a/35084170/7787654

**Comment by Taariqq** [comment]
> https://stackoverflow.com/a/35084170/7787654

Does not work anymore, after the Firefox update. It will work for simple files but if you want to process a form via say processorder.php, it won't know where to look as it is not running off of the web server!

**Comment by blind0x** [comment]
For everyone, this problem can be resolved by following steps:- 

1. On menu bar, go to  File --> Open Folder (folder which have your html file for live preview)

2. Select Folder

3. Select your html file from left side bar for live preview

4. Click on bolt icon on right (preview button) 

All it melts down to the fact, that you need that folder(which have your file) selected to view your output in live preview. 
Let me know, if it helps someone. :)
![2](https://user-images.githubusercontent.com/16700931/83773286-f8a91f00-a6a1-11ea-9d90-c9b0bdd1c9dd.JPG)
![3](https://user-images.githubusercontent.com/16700931/83773291-f9da4c00-a6a1-11ea-91f2-f70bce65ff9f.JPG)
![4](https://user-images.githubusercontent.com/16700931/83773293-fa72e280-a6a1-11ea-836f-e05eb22c81da.JPG)
![5](https://user-images.githubusercontent.com/16700931/83773297-fb0b7900-a6a1-11ea-95b2-af43a5da4c5e.JPG)
