### ISSUE TITLE
Auto-completion problem

### ISSUE THREAD

**Issue by hoodwink-dude** [adobe/brackets#12273]
The auto-completion key is the ENTER key. However, various IDEs use the TAB key for auto-completion. I can't find an option for changing this, but, if it does exist, I think that it should be made more clear where to find it. Or alternatively, just change the key-bind.

**Comment by sprintr** [comment]
`"insertHintOnTab": true` should do it.

**Comment by hoodwink-dude** [comment]
Where should i put that? in the source code?

**Comment by sprintr** [comment]
Open `Debug -> Open Preferences File` put it in `brackets.json`. Make sure it is a valid JSON

**Comment by hoodwink-dude** [comment]
Oh thanks. Something like this should be put up on the main website. Minor tweaks like this

**Comment by redmunds** [comment]
This is in the wiki tab, How to Use Brackets doc, Preferences section: https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences

**Comment by abose** [comment]
Closing as answered.
