### ISSUE TITLE
LOC: JPN/FRA: local character display as garbage in layer list and tips

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#12277]
1. Launch Brackets.
2. Open extract panel.
3. Double click a local string from tutorial.
4. Observe the string of layer name in layer panel.

Result: local character display as garbage in layer list and tips
Expect: Local character should display correctly.
![enu](https://cloud.githubusercontent.com/assets/17721679/13599362/84cb94f0-e55d-11e5-9043-4edeeb1cd6e0.png)
![fra](https://cloud.githubusercontent.com/assets/17721679/13599365/898600de-e55d-11e5-88ce-93d81444fa67.png)
![jpn](https://cloud.githubusercontent.com/assets/17721679/13599406/b8af8a38-e55d-11e5-8d89-71f914e5d784.png)

**Comment by ficristo** [comment]
Closing as Extract is deprecated.
