### ISSUE TITLE
Flickering highlight on strings that contain a colon character

### ISSUE THREAD

**Issue by lkcampbell** [adobe/brackets#12274]
**OS:** Mac OSX Mavericks

**Brackets Version:** Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) 

**Repro  Steps:**
1. Create a javascript document with the following gist: https://gist.github.com/lkcampbell/8a40b98f307532e871b5
2. Mouse over either of the strings in the code

**Observed Results:**
There is a very brief flickering highlight of the string every time you mouse over it.

**Expected Results:**
No flickering highlight when you mouse over the strings.

**Other Notes:**
This only seems to happen when the string contains a colon character, and I believe the position of the colon characters matters. I have not tested the position, nor other special characters, but the gist posted above should repro the problem.

The problem occurs with all extensions disabled.

The problem occurs with both the Brackets dark and light themes. I have not tested any other themes.

**Comment by petetnt** [comment]
@lkcampbell I think this is due to Brackets trying to retrieve the asset for a mouseover preview.

```
> Resource interpreted as Image but transferred with MIME type text/html: "http://www.foo.com/".
jquery-2.1.3.min.js:3 
> Resource interpreted as Image but transferred with MIME type text/html: "file:///A:/".
jquery-2.1.3.min.js:3 
> GET file:///A:/ net::ERR_FILE_NOT_FOUND
```

This sort of ties into the security issue of being able to perform arbitrary code on Brackets windows too (or just some code getting executed on the window in general)

**Comment by lkcampbell** [comment]
@petetnt, yeah you are correct. When I toggle `Quick View on Hover` off, the problem and the error messages go away.

**Comment by lkcampbell** [comment]
Not really very important. Closing.
