### ISSUE TITLE
AutoSave Feature

### ISSUE THREAD

**Issue by afrcracks** [adobe/brackets#12270]
Please add **autosave feature** to bracket. It will help a lot to me and other developers.

**Comment by abose** [comment]
See extension  `Autosave Files on Window Blur` or `Brackets Backup`  from extension manager.
That should fix your use case.
Closing as extension available.

**Comment by afrcracks** [comment]
Thanks I did'nt see it :+1:

**Comment by timkunze** [comment]
Is there a solution for unsaved files too? I lost my unsaved notes of two days. :(
