### ISSUE TITLE
Resizing sidebar results in resizing at 0

### ISSUE THREAD

**Issue by Donkfather** [adobe/brackets#12292]
When I resize the sidebar the mouse pointer remains in resizing and when I click anywhere the sidebar goes to 0 width. I got this error:
 Uncaught TypeError: Cannot read property 'null' of undefined                           terminal.js:56

Brackets 1.6.0-16680

The only workaround is to resize it and before clicking, press F5 to refresh

**Comment by petetnt** [comment]
Hi @Donkfather,

does this happen without extensions too? (`Debug -> Reload Without Extensions`). There's no `terminal.js` in Brackets core.

**Comment by ficristo** [comment]
I cannot reproduce the problem on master.
The error in console is most likely an extension problem.
Update to the latest release and try the suggestion of @petetnt to see if you can reproduce: if you can reopen the issue.
