### ISSUE TITLE
Function call should be easier

### ISSUE THREAD

**Issue by sajushela** [adobe/brackets#12295]
I have a code where i call a function. In other IDE's if we press Ctrl + Mouse button it will take it to my function. Same kind of feature is needed in brackets

**Comment by abose** [comment]
@swmitra can't we do this like all other editors instead of using it for multi cursor. We could delegate multi cursor shortcut to just the alt key.

**Comment by redmunds** [comment]
@sajushela In Brackets, use: _Navigate > Jump to Definition_ (Ctrl+J).
