### ISSUE TITLE
JavaScript File Interface Problem

### ISSUE THREAD

**Issue by ndkcha** [adobe/brackets#12296]
I am currently working in Ionic framework for building hybrid mobile apps. I had built the project for Android platform (building with Gradle Builder). Then I went on to editing code, which led to this bug that did not show code hints, jump to definition or quick edit. The application does not crashes here, but it stops displaying code hints and other mentioned features.

Here, I'm attaching screenshot of error dialog box that was displayed for this issue.
<img width="1280" alt="screen shot 2016-03-14 at 12 21 31 pm 2" src="https://cloud.githubusercontent.com/assets/8328240/13736970/67c6c1a0-e9df-11e5-9c1f-2ca408ff174b.png">

Brackets Version: 1.5.0-16538 (release cf9cf4698)
OS Version: OS X 10.11.3 (El Capitan)

Logs >>

![screen shot 2016-03-14 at 12 27 53 pm](https://cloud.githubusercontent.com/assets/8328240/13737052/452a3266-e9e0-11e5-8341-ea900e5ee1ab.png)
![screen shot 2016-03-14 at 12 27 56 pm](https://cloud.githubusercontent.com/assets/8328240/13737051/45259166-e9e0-11e5-9919-c6c44b2cc6f8.png)

Do look into this issue.

**Comment by tallandroid** [comment]
Seems like a transient issue while tern.js is loading the code hints. Did restart work ?

**Comment by ndkcha** [comment]
I excluded it by writing that file path into .brackets.json. And then reloaded it, it worked! But I'm getting this error in almost every external javascript file which is part of framework. (e.g. ionic.min.js, and more). I need to exclude every file and then it works.

**Comment by ingorichter** [comment]
Does this still happen with the 1.6 version?

**Comment by ndkcha** [comment]
No. It works well after I re-installed brackets

**Comment by petetnt** [comment]
Closing as solved, feel free to reopen if it occurs again (I've had same kinds of issues with Ionic myself).
