### ISSUE TITLE
[Win] There are two braket programme display in the "Uninstall or change a program" panel when install two 1.6 builds

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#12291]
1. Install the 1.6 build to the windows system.
2. Install the refreshed 1.6 build to the windows system.
3. Open "Control Panel" -> "Programs and Features" from windows system.

Result: There are two braket programme display in the "Uninstall or change a program" panel when install two 1.6 builds

Expect: Only on bracket programme display in the "Uninstall or change a program" panel.
![two icon](https://cloud.githubusercontent.com/assets/17721679/13699718/23fc351a-e7b7-11e5-891e-fd64b1725842.png)

**Comment by ficristo** [comment]
@nethip do you think we can close this, since it was for the refreshed build of 1.6?

**Comment by nethip** [comment]
@ficristo I think we can close this.
