### ISSUE TITLE
LOC: FRA: Miss non-break space before colon in Extract for Brackets(Preview)

### ISSUE THREAD

**Issue by Jiaqinggang** [adobe/brackets#12302]
Problem:
Miss non-break space before colon in Extract for Brackets(Preview)

Method:
1. Launch the Brackets
2. Click Extract for Brackets(Preview) icon or press shortcut key "Ctrl+Alt+X"
3. Observe the two strings "Click on the box below:" and "Like this:"

Result:
Miss non-break space before colon
![fra](https://cloud.githubusercontent.com/assets/17822908/13741532/cc33d7c2-ea11-11e5-8ee3-29227b4adf58.png)

Expected:
A non-break space should be displayed before colon

**Comment by ficristo** [comment]
Closing as extract is deprecated.
