### ISSUE TITLE
There are layout issues appear when user narrow down width the of Brackets

### ISSUE THREAD

**Issue by Jiaqinggang** [adobe/brackets#12304]
Problem:
There are layout issues appear when user narrow down width of Brackets

Method:
1. Launch the Brackets
2. Click Extract for Brackets(Preview) icon or press shortcut key "Ctrl+Alt+X"
3. Narrow down width of Brackets
4. Observe layout

Result:
There are layout issues appear
![800](https://cloud.githubusercontent.com/assets/17822908/13742464/df583758-ea16-11e5-9158-c97f916df757.png)
![655](https://cloud.githubusercontent.com/assets/17822908/13742471/e4469084-ea16-11e5-84be-dd2867691b6a.png)
![347](https://cloud.githubusercontent.com/assets/17822908/13742473/e993d704-ea16-11e5-89f0-61ba836bd3ec.png)

Expected:
No layout issues appear

**Comment by ficristo** [comment]
Closing as extract is deprecated.
