### ISSUE TITLE
LOC: JPN: Punctuation should not be at the beginning of a line in E4B tutorials screen.

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#12305]
Step:
1. Launch Brackets.
2. Click Extract for Brackets icon.
3. Click "?" icon to open tutorials screen.
4. Observe the string "Then press CTRL-Space or start typing in a CSS rule to get code hints. Like this:"

Result: Punctuation is at the beginning of a line in E4B tutorials screen.

Expect: Punctuation should not be at the beginning of a line in E4B tutorials screen.
![enu](https://cloud.githubusercontent.com/assets/17721679/13769396/32a68a92-eaba-11e5-908a-f176510275e1.png)
![jpn](https://cloud.githubusercontent.com/assets/17721679/13769398/36c2c122-eaba-11e5-8727-ab4702230f58.png)

**Comment by ficristo** [comment]
Closing as extract is deprecated.
