### ISSUE TITLE
shortcut for block comment opens help menu?

### ISSUE THREAD

**Issue by carinlynchin** [adobe/brackets#12311]
I am using a mac...so instead of ctrl its actually command (which i had to find out). The line comments (//) work with command + /  but command-shift-/ doesn't do anything

so i experimented and its actually command + option + / to do block comments. Can we update wiki to show mac options?

**Comment by redmunds** [comment]
@carinlynchin I updated the wiki page. As stated on that page, it's hard to keep wiki pages up-to-date with core code and it's impossible with extensions. You can install the Display Shortcuts extension to see the _exact_ shortcuts defined on your system, and also converted to you OS.

Also, the shortcut is displayed next to the _Edit > Toggle Block Comment_ menu item. It's `Cmd-Alt-/`.

**Comment by carinlynchin** [comment]
Thank you so much. I didn't know there was an extension. Awesome
