### ISSUE TITLE
I want to use a NON-default browser for live preview button...

### ISSUE THREAD

**Issue by zeg-io** [adobe/brackets#12315]
Currently Live Preview opens code in the default browser, for me this is Safari.
I would like the option to define which browser opens (namely Chrome).

WHY?  Because Chrome is a much better debugger than Safari, but Safari is more energy efficient.  Whenever I'm coding I'm usually plugged in to power so it doesn't matter, when I'm out and about I'm usually not coding, but working on other aspects of my business, therefore the default of Safari is what I need.

**Comment by abose** [comment]
use `file> enable experimental live preview`. then click on live preview button.
After that you can copy the URL to any browsers you want to live preview in.
closing as feature already suported.

**Comment by zeg-io** [comment]
I am well aware I can copy that URL from one browser to another.  What I'm asking for is a way to _only_ open the browser I want to use.

**Comment by bocande** [comment]
I have the same issue. I'm on a MAC, Safari is my default browser and I want to have live preview on Chrome directly from the live preview button on Brackets. I don't want to copy and paste the URL from Safari to Chrome.

Also, weither I'm on Safari or Chrome, I don't see the changes unless I reload the browser which is the main reason I would use Brackets at this point. 

Please advise, thank you much!

Best,
Michel

**Comment by TD540** [comment]
I am also looking for the configuration how to open a page-preview in a non-default browser. My default is Firefox Dev but I want my previews to open in Brave without copy-and-paste.
