### ISSUE TITLE
shortcut for move to end of word

### ISSUE THREAD

**Issue by tanveer19** [adobe/brackets#12310]
In brackets, what is the shortcut for move to end of word?
in atom it is ctrl+f but i didn't find any way to do this in brackets.
now i am using windows 7 sp1 x64 but will move to Linux very soon. :)

**Comment by petetnt** [comment]
Hi @tanveer19,

You can use `CTRL + Arrow (Left/Right)` to jump to the end/start of the word

If you want to bind it to some other combination, see [User key bindings on Brackets Wiki](https://github.com/adobe/brackets/wiki/User-Key-Bindings)

**Comment by abose** [comment]
closing as answered.

**Comment by tanveer19** [comment]
@petetnt
i have installed the extension.
 if i put  "Alt-F": "goLineEnd" in keymap.json i am getting the following error.
![br](https://cloud.githubusercontent.com/assets/2099045/13809547/769b8e7e-eb95-11e5-9a83-4c616866c252.PNG)

**Comment by petetnt** [comment]
@tanveer19 Oh right, that's a CodeMirror command. The Wiki-page says

> Currently, only key bindings for commands can be updated -- not editor bindings currently handled by the CodeMirror keymap. 

There's a workaround, but sadly it isn't that simple. You could try finding the keymap in Brackets the folder and change the setting there, or your could create an extension to bind the CodeMirror-commands too. You can check out [CodeMirror documentation for keymaps](https://codemirror.net/doc/manual.html#keymaps) here. See the [Hello world-example extension](https://github.com/adobe/brackets/wiki/Simple-%22Hello-World%22-extension) for an extension example.

**Comment by tanveer19** [comment]
thanks.
