### ISSUE TITLE
Search should not clear the last searched term

### ISSUE THREAD

**Issue by felipenmoura** [adobe/brackets#12323]
Just an enhancement that I think could be in Brackets, not in an extension:

**Steps:**
- You open the FindBar
- You type "something" and `doFind`
- You close the FindBar
- You open the FindBar again

**What should happen:**
It should reopen with the last searched term.

**What happens:**
The input in the FindBar comes empty.

**Opinion:**
I say that because I use the keyboard almost all the time and hit:
- Cmd+F
- type
- enter (and go next until I find what I want)
- ESC (closes the FindBar)

I use *esc* to get back to the source code, where the last "match" left my cursor.

I believe the Search tool should open with the last searched term on it, or we could have a shortcut to move the focus/cursor from the search input into the source code, not closing the FindBar.

*TAB* kinda does it...it does close the FindBar, but when we hit cmd+F, it reopens with the last value.
But even using TAB, if I type something in the code, hitting cmd+F brings the FindBar with a clean input again.

**Comment by petetnt** [comment]
Hi @felipenmoura, 

which version of Brackets are you running? It should remember the last searched term on 1.6. after #11869.

There's also a pending PR #11996 for keeping the search bar open.

Also you can use F3 to jump to the next matching term after searching regardless if the bar is open or not. Hope this helps :+1:

**Comment by felipenmoura** [comment]
Helps, indeed.
I updated to 1.6 and it works better, too :)
