### ISSUE TITLE
Code Hints Don't work for me any longer (JS only)

### ISSUE THREAD

**Issue by DavidPotesta** [adobe/brackets#12322]
Everything has worked fine on Release 1.5.  I updated to Release 1.6 and now, even when I create a simple html file, JS hints and intellisense doesn't work.  It works on another computer with Windows, but not on my Mac.  All I do is this:

<html>
        <head>
        </head>

    <body>
         <script type="text/javascript">
        
         </script>
    </body>
</html>

When I type within the script tags, _document_.  and I expect to see all of the functions (GetElementById etc..., nothing happens.  If I add HTML in the body, code hints and intellisense still work.  Its just for JS.

**Comment by petetnt** [comment]
Hi @BorjeoVonDingle,

do you see any errors on the console (Debug -> Show Developer Tools -> Console)

**Comment by kenzo44** [comment]
Hi @BorjeoVonDingle,

May be an extension is causing this problem, try Debug > Reload Without Extensions and get back with the results.

**Comment by BorjeoVonDingle** [comment]
There were no errors in the console.
I rebooted and that didn't fix the problem.
I then uninstalled Brackets (dragged application to trash on OSX) and reinstalled, rebooted again.
Still the same problem!
I shut down for the night and when I started work again this morning everything seems fine now!

Interesting aside is that even though I reinstalled Brackets, all of my extensions and preferences were still there after the reinstall.  Is there a preferences and settings folder/file somewhere that one would need to get rid to completely get rid of Brackets?

**Comment by kenzo44** [comment]
What version of OS X are you running?

When you trash an application on OS X, you are just deleting the app and not the source and cache folders.

This should help you unistall Brackets completely - https://github.com/adobe/brackets/wiki/Cache-Folder.

**Comment by petetnt** [comment]
@BorjeoVonDingle can you also check that the Node binary used by Brackets is unblocked in the firewall.

I am not on OSX myself, but the steps are:

1. Choose System Preferences from the Apple menu.
2. Click Security or Security & Privacy.
3. Click the Firewall tab.
4. Unlock the pane by clicking the lock in the lower-left corner and enter the administrator username and password.
5. Click Advanced to customize the firewall configuration.

The Node executable can be found on the Brackets folder root: On Windows it's C:/Program Files (x86)/Brackets/node.exe so I think it should be something like `~/Applications/Brackets/node`

Also on the developer tools, can you check out if there are anything weird going on in the Network tab.

And like @kenzo44 mentioned just now, try to delete (or better yet, rename) the Cache folder under Application Support and launch Brackets again.

**Comment by BorjeoVonDingle** [comment]
kenzo44
     I'm on 10.10.3 Yosemite. I too read that article, but after following it, I discovered that I do not have a Brackets folder at the specified location at all: Mac: ~/Library/Application Support/Brackets/cef_data

petetnt,
Those 5 steps that you just detailed only lead to the Advanced Firewall configuration page; there are 3 checkboxes for automatic log out preferences, system wide admin login preferences, and disable remote control infrared receiver with a Pair button.  I don't see that this has anything to do with uninstalling Brackets.  Maybe you pasted the wrong snippet?

**Comment by kenzo44** [comment]
@BorjeoVonDingle follow these steps for Brackets - https://www.youtube.com/watch?v=E6jgAIYr8to

**Comment by petetnt** [comment]
@BorjeoVonDingle Oh right, these steps follow those:

1. Click the Firewall Options button
2. Click the Add Application (+) button.
3. Select the app you want to allow incoming connection privileges for.
4. Click Add.
5. Click OK.

**Comment by BorjeoVonDingle** [comment]
kenzo44
     Thanks!  That's what I needed to learn how to do.  user\Library is hidden.  I was going to HD Root\Library and its not there.  Once I turned on the ability to view hidden files and folders, voila!  I am now able to see that folder.

Thanks again!
BVD

**Comment by kenzo44** [comment]
To reveal the library, you need to hold down option.

No problem, glad I could help.

**Comment by K-Thompson** [comment]
I quickly read through this. Is code hints working now or not? Seems to have turned into "how do I remove Brackets issue".

Personally, I feel code hint issues need to be tracked. I think hinting and auto complete is unreliable.


See [Code Hints Unreliable #11570](https://github.com/adobe/brackets/issues/11570)

[Bug with JS autocompletion #12197](Bug with JS autocompletion #12197)

**Comment by BorjeoVonDingle** [comment]
K-Thompson,
    Code hints are a problem for me still.  Sometimes they work and sometimes they don't.  It's really unpredictable as far as when they will or when they won't.  Hopefully, someone is looking into this.

Thanks for following up to clarify!

BVD

**Comment by crash5936** [comment]
Hello guys,

I have probably run into the same issue and I'm not able to fix it in any way.

I've tried reinstalling it even with deleting the config/cache, checked my firewall, but I'm simply not getting hints for JS anymore (I've tried HTML and it works fine). I've checked the console and network tabs in developer tools, console seems to return an error that I think is related
[brackets_error_log_tern.txt](https://github.com/adobe/brackets/files/405545/brackets_error_log_tern.txt)

I was able to get to get the hints running for a while, it wasn't completing automatically, but when I pressed ctrl + space multiple times, it showed hints as expected, but it stopped worked since and I was not able to replicate the behaviour.

Let me know if I can provide you with further information!

**Comment by ficristo** [comment]
Hi @crash5936, could you try the PR https://github.com/adobe/brackets/pull/11569 and see if fixes the issue for you?

**Comment by crash5936** [comment]
@ficristo Hello, thanks a lot, it actually does fix the issue. I saw the thread before, but because I'm pretty new to git and programming in general, I was discouraged by what seemed to be quite a complicated process. Now that you've pointed me in the direction, I went through the whole process and actually learned quite a few new things, so thanks for that :)

**Comment by MarcelGerber** [comment]
@crash5936 pointed out that #11569 fixed the issue for his copy of Brackets, so I just assume the overall issue is resolved as well. #11569 has been merged and will come to you in Release 1.8.
Please let us know if it still doesn't work for you when the Release ships.

**Comment by vvks** [comment]
@MarcelGerber hi, i just wanted to point out that i am currently running Brackets from source to try out the fix for #11826 and since then code hints have stopped working for me. i deleted the cef_data folder and i saw no relevant error in the console.

they used to work fine earlier.

**Comment by zaggino** [comment]
@vvks please run `npm install` in the cloned `brackets` directory and try again

**Comment by vvks** [comment]
@zaggino yes, after running `npn install` it works fine. thank you..
