### ISSUE TITLE
SQL Comment Syntax Highlighting Not Working Properly

### ISSUE THREAD

**Issue by benzen217** [adobe/brackets#12324]
**Problem:** A space is required after the SQL comment code "--" in order for the line to become a comment.

`-- This Comment Works`
` --This Comment does not work`

**Expected Outcome:** anything in a line after 2 dashes ("--") should be a comment.

**Current Behavior:** Here is a screenshot of behavior in Brackets, all lines should be commented after the first "--"

![screenshot_1](https://cloud.githubusercontent.com/assets/18053587/14021999/cd319618-f1ab-11e5-9590-fb3dd2e6c8f7.png)

**Possible Solution:** I noticed in the languages.json that sql does not have a "lineComment" specified.

Inserting the following line at line 222 of the file languates.json may fix the issue.
`"lineComment": ["--"]`

**Version Info:** I am running Windows 7 x64, Brackets Release 1.6 build 1.6.0-16680, Extensions Disabled

**Comment by ficristo** [comment]
Hi @benzen217, I looked a bit at this issue.
Brackets at the moment is mapping `sql` to the `mysql` dialect and [here](http://dev.mysql.com/doc/refman/5.7/en/ansi-diff-comments.html) it states you need a space after the two dash for mysql.
So what you see it is somewhat correct.
I tried changing `languates.json` but I guess the syntax highlighting come completely from codemirror.
[Here](http://codemirror.net/mode/sql/index.html) you can try several sql dialects.
Finally I tried to modify `languates.json` to something like the following to differentiate from sql and mysql:
```javascript
    "sql": {
        "name": "SQL",
        "mode": ["sql", "text/x-sql"],
        "fileExtensions": ["sql"]
    },

    "mysql": {
        "name": "MySQL",
        "mode": ["sql", "text/x-mysql"],
    },
```

I will not open a PR so feel free to steal the code. I'm not sure it is exact but seems to work.

**Comment by benzen217** [comment]
Interesting, never realized that it's supposed to have a space afterwards. [Oracle says the same thing ](https://docs.oracle.com/cd/E17952_01/refman-5.5-en/comments.html) 

It's odd because both Oracle SQL Developer and MS SQL Server Management Studio both consider a comment to start with "--" not "-- ".  Weird.  Oh well.

Thanks for looking into it ficristo!

**Comment by tobibeer** [comment]
Why did you close this @benzen217? I'm still unable to have comments properly highlighted, even with a `.languages.json` file in the repo.

**Comment by tobibeer** [comment]
@benzen217, please reopen, it's quite untenable that in `1--foo` the bit that reads `--foo` is not shown as a comment. I don't know how this can be resolved but the issue remains.
