### ISSUE TITLE
Multiple Cursor Shortcut bolds instead

### ISSUE THREAD

**Issue by grem28** [adobe/brackets#12331]
Hey guys, I'm trying to use multiple cursors but instead of that, when i cmd+B it bolds <b></b> instead of doing the cursors. how do i get this to work?

**Comment by petetnt** [comment]
Hey @grem28, 

are you following this guide: https://github.com/adobe/brackets/wiki/Working-with-Multiple-Selections?

You can make multiple cursors by using `Ctrl/Cmd-Click` combination; then you can use `CMD+B` to highlight the current range or word.

**Comment by grem28** [comment]
I am.... it does not work. I am doing exactly what it says. Saw the tutorial as well but nothing. don't get it

**Comment by redmunds** [comment]
@grem28
Try _Debug > Reload Without Extension_ to see if an extension is causing it.
Also try _Debug > Open User Key Map_ to see if you changed that shortcut (and forgot).

**Comment by grem28** [comment]
that was it! It was an extension. Thanks a lot!

damien
