### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by leoek** [adobe/brackets#12338]
It would be really nice to have a debian package compiled for arm. I tried really hard to compile it on my own on my chromebook running debian jessie but i failed -.-. maybe there is somone with more expertise who could build brackets for arm.

**Comment by abose** [comment]
Thanks @leoek . our expertise in Linux on ARM is a bit inadequate and there is not enough users to justify a large scare ARM push from the core team. Perhaps you could help with porting https://github.com/adobe/brackets-shell into ARM.
Duplicate of https://github.com/adobe/brackets/issues/10298
Closing.
