### ISSUE TITLE
Lubuntu 14.04.4 LTS

### ISSUE THREAD

**Issue by kutakizukari** [adobe/brackets#12337]
Using Lubuntu but running `lsb_release -a` returns `Ubuntu 14.04.4 LTS`.

Using the start project and moving around in it seemed to work fine.

When I opened an AngularJS project folder it freezes or moves extremely slow.

**Comment by petetnt** [comment]
Hey @kutakizukari,

try using an extension such as [brackets-file-tree-exclude](https://github.com/zaggino/brackets-file-tree-exclude) to (automatically) exclude some of the particularly performance intensive folders from your file tree.

**Comment by kutakizukari** [comment]
It won't unfreeze enough to navigate around.

**Comment by petetnt** [comment]
@kutakizukari Rename/move/delete the [cache folder](https://github.com/adobe/brackets/wiki/Cache-Folder) under `~/.config/` to reset your Brackets so your latest project doesn't crash Brackets.
