### ISSUE TITLE
brackets extensions reload

### ISSUE THREAD

**Issue by Barkanyi** [adobe/brackets#12335]
Hello Everyone!
I do not speak and write in English, sorry.
Brackets are very good, I like.
Is it possible that (only) the extension brackets reload?
I tried this:
`AppInit.extensionsLoaded ();`
But it gives an error.
Thank you for answers!

**Comment by petetnt** [comment]
Hi @Barkanyi,

do you want to reload a single extension or all extensions? For a single extension, you could try using [require.js undef](http://requirejs.org/docs/api.html#undef) and reloading the extension again with [ExtensionLoader#loadExtension](https://github.com/adobe/brackets/blob/master/src/utils/ExtensionLoader.js#L241). See this StackOverflow answer for similar case: http://stackoverflow.com/a/19967014/2138943. It might not work though.

For reloading all the extensions it would be simpler just to reload all of Brackets with `window.location.reload()`

**Comment by Barkanyi** [comment]
Hi @petetnt , 

Thanks for the reply! :+1:
