### ISSUE TITLE
Add ".gradle" to groovy syntax highlighting

### ISSUE THREAD

**Issue by paul-bjorkstrand** [adobe/brackets#12332]
As a helper for us gradlers out there, it would be helpful to at least have groovy-like syntax highlighting for gradle. It is as simple as adding "gradle" to the list of extensions for groovy.

**Comment by petetnt** [comment]
@paul-bjorkstrand Put up #12333 that adds `gradle` to Groovy-file extensions

**Comment by paul-bjorkstrand** [comment]
Awesome, thanks!
