### ISSUE TITLE
Add support to create and edit templates for python-flask.

### ISSUE THREAD

**Issue by ZeroCool940711** [adobe/brackets#12341]
Hi there, I would like to know if you could add support for editing and creating templates for [python-flask](http://flask.pocoo.org/) , it uses [jinja2](http://jinja.pocoo.org/) for templates. Would be nice to be able to use brackets for speeding up development, it is kinda annoying to edit things with notepad++ or sublime text for example and then every time you want to test something you have to open your browser and refresh the page to see changes, sometimes the development server for flask restart and you have to be opening and closing the browser to check the server console, wait for the server to start again and go back to the browser to see if the web work , it makes you waste lot of time, would be nice to have everything just in one place, or at least half of the things needed for flask web development.Thanks for your time and have a good day.

**Comment by abose** [comment]
Hi @ZeroCool940711  Brackets core is mainly targetted towards HTML,xCSS et.al and JS related functionality. Support for custom frameworks is best implemented as extensions. Closing as extension idea.
