### ISSUE TITLE
My chrome browser do not show the images

### ISSUE THREAD

**Issue by Maks1988** [adobe/brackets#12348]
In mine code i can see the images (when i put the cursor on the code lines of images with the path i can see the images).. but when i loading the HTML page the browser won't show me them.. what can be the problem ?

**Comment by petetnt** [comment]
Try opening your dev tools in Chrome (F12) and checking out either the console tab or network tab to see why your images aren't loading. Is your index.html located in the root of the project?

**Comment by Maks1988** [comment]
Yes it is mine index.html as a root..
I have a couple of error there..
one of them "ConsoleAgent: Not allowed to load local resource:
file:///C:/ImagesForHtmlTesting/1 (url:
http://127.0.0.1:63835/Html%20pages/index.html)"

**Comment by sanyashvets** [comment]
Try to remove spaces in directory names

**Comment by ficristo** [comment]
Please try latest release and if you still have the problem, open a new issue.
