### ISSUE TITLE
Can't create a new directory 

### ISSUE THREAD

**Issue by Maks1988** [adobe/brackets#12347]
I got the "Error not readable " message and can't create any new folders for java script developing and css and suff like that...need your help to solve the problem..

**Comment by petetnt** [comment]
Make sure that you are in a user-writable location. By default Brackets opens the Getting Started-project, which is read-only. To open a new project:

1. Go to `File -> Open Folder`
2. Navigate to user writable directory (such as My Documents on Windows)
3. Create a new folder there
4. Open the said folder with Brackets by selecting it and click `Select Folder`

You can now use Brackets to create files, sub-folders et cetera to said folder.

**Comment by Maks1988** [comment]
Thanks for the help now it's working
