### ISSUE TITLE
Windows 10 Installation Failed

### ISSUE THREAD

**Issue by Cr8zyC8tL8dy** [adobe/brackets#12349]
I'm a newbie and I'm taking a course on HTML and they recommend your product. I have tried to install it on Windows 10 and it just says, "Installation directory must be on local hard drive." I've tried changing it to a different hard drive. I've looked at your trouble shooting tips, but they don't provided step by step solutions for Windows 10. There is no run as admin option coming up. I've looked through the current issues and I didn't understand a word of any of the responses on how to fix it. So... I really need this for the course I'm taking, but I have no idea how to get it to install! Please help me and explain as plainly as possible what I need to do. Thank you.

**Comment by petetnt** [comment]
Hi @Cr8zyC8tL8dy,

Sorry about your troubles! Try the following steps to run the installer as admin:

1. Open start menu and type "cmd", you should see Command Prompt popping up

![image](https://cloud.githubusercontent.com/assets/7641760/14307502/13f865d2-fbd8-11e5-9162-a1e079dca0f3.png)

2. Right click it and select "run as administrator"

3. Enter your credentials if Windows asks for them

4. cmd.exe opens. You'll need to navigate to the location of your installer. For example, if it's on your desktop, type

```
cd C:/Users/Cr8zyC8tL8dy/Desktop
```

Where `Cr8zyC8tL8dy` is your Windows username

Next, type the following: 

```
msiexec /i "Brackets.Release.1.6.msi" WIXUI_DONTVALIDATEPATH="1"
```

Brackets should now install. After installing you can close the CMD.exe.

If that doesn't work, there are other workarounds listed in #2407.

**Comment by Cr8zyC8tL8dy** [comment]
Thank you for the very easy to follow step by step instructions! It worked and Brackets is now successfully installed in Windows 10. I also learned something about comnand prompt along the way!

**Comment by petetnt** [comment]
@Cr8zyC8tL8dy that's awesome! Happy Brackets'ing!

**Comment by JohnCallanan** [comment]
I'm having the same problem with Brackets.Release.1.10.msi. Even running from CMD as Administrator, I'm getting a permissions error on Program Files(x86). Any suggestions?

**Comment by karl-pogi** [comment]
I am having the same issue as @JohnCallanan been trying many different things, but getting permission error.

**Comment by MyoThuraZaw** [comment]
It worked like a charm!!!
I had been trying out other methods for about 3 hrs and nothing worked.
Thank you!!!

**Comment by fafchook** [comment]
Having the same issue, even after running CMD as administrator. 
Is there another fix?

**Comment by AndyTatel** [comment]
I am encountering the same problem installing bracket 1.14 in windows 10.
I managed to install it in Windows PowerShell even without running it as administrator.
