### ISSUE TITLE
Freezes On Startup; Cannot Open (Linux Mint 17.3) (CLOSE ME)

### ISSUE THREAD

**Issue by chewzerita** [adobe/brackets#12345]
## So I made a dumb move...
I am new to brackets, and I tried to open a folder to edit with. I accidentally opened my root folder (`/`). The application crashed, so I had to kill it via the command line. I think it is trying to open every folder every time I try to open brackets up again. Is there a way to make this go by faster because it could take days...
#### I have tried:

1. Restarting Brackets many times
2. Giving permissions to the `/` folder
3. Reinstalling Brackets (using the .deb file)
4. Restarting my computer

Every time I open brackets it just tries to load all of my files... it's been like 4 hours already (I have an ssd too!)

**Comment by chewzerita** [comment]
Finally! It gave me an error and is working now. This is a non issue now. It can be closed.

**Comment by abose** [comment]
Thanks closing.
