### ISSUE TITLE
Ctrl + W does not work properly in version 1.6.0-16689

### ISSUE THREAD

**Issue by mbsmt** [adobe/brackets#12356]
Hi.
I've installed Brackets version 1.6.0-16689 today and everything seems working fine. Just I found a bug in it up to now.
Imagine I opened 3 files, and want close them by pressing Ctrl+W. I do it and the current document closes. But this action occurs in background and any change won't be shown in the side bar (open documents list).
If I press Ctrl+W for all documents, and then click on a document name in the side bar, all previous documents name will disappeared.

I hope I could tell what I meant.

**Comment by nethip** [comment]
Tagging @swmitra

**Comment by petetnt** [comment]
Weirdly enough this should have been fixed with https://github.com/adobe/brackets/pull/12246.

**Comment by swmitra** [comment]
@petetnt @nethip should have been fixed by #12246

**Comment by joaojuniormail** [comment]
I thought it was my Macbook Pro that was in trouble, but now I see that is the brackets.

**Comment by joaojuniormail** [comment]
When i tape the shortcut cmd+w (mac) or ctrl+w (windows).
The file close but is not refresh in left menu.

**Comment by mbsmt** [comment]
Yes, that is. Although `Ctrl+Shift+W` works well and closes all open files completely.

**Comment by joaojuniormail** [comment]
Ok. But do not run the Ctrl + W / Cmd + W shortcut to close individual file

**Comment by mbsmt** [comment]
Yeah, it is what I said in this issue as a bug.

**Comment by joaojuniormail** [comment]
excuse me. I had misunderstood.

**Comment by petetnt** [comment]
Fixed in 1.7.
