### ISSUE TITLE
Expand/Collapse bug in code edit area

### ISSUE THREAD

**Issue by FreezeLogic** [adobe/brackets#12355]
Bug in code edit area with function Expand / Collapse code . 

This bug continuously from 1.5 to 1.6 version. in one moment after preset on "+" for expand code , "+" not change to "v" and after press to "+" don't have effect. This expand block of code don't collapse and don't have inner expand and collapse. after im press F5 and all work perfectly, but in one moment bug return. 
This problem affects a certain part of the code, I can not collapse the code above a certain place, below this point everything is working perfectly

ps : I'm edit js/node code, if this information help

**Comment by petetnt** [comment]
Hey @FreezeLogic,

could you most some minimal amounts of code that show this behavior?

**Comment by oldchilds** [comment]
Yes i have same problem too

**Comment by ficristo** [comment]
Very likely fixed by https://github.com/adobe/brackets/pull/12521 which will be in 1.8.
