### ISSUE TITLE
Responding Error

### ISSUE THREAD

**Issue by afrcracks** [adobe/brackets#12350]
Brackets _stop responding_ when ever I try to open **Base64** image files
Bracket also _stop responding_ where ever I open a big project of **Websites**

**Comment by petetnt** [comment]
Hi @afrcracks, 

1. How large are your Base64 image files?

2. For the big projects one, try using an extension such as [brackets-file-tree-exclude](https://github.com/zaggino/brackets-file-tree-exclude) to (automatically) exclude some of the particularly performance intensive folders from your file tree. You should see vast improvements in the performance after reloading Brackets.

**Comment by afrcracks** [comment]
Hi @petetnt 
Thanks for your advice it really help me a lot. :+1:

**Comment by petetnt** [comment]
Closing as answered 👍
