### ISSUE TITLE
Find & replace shortcut - not working

### ISSUE THREAD

**Issue by saturday1** [adobe/brackets#12351]
Hello!

When I press `alt + cmd + f ` in Brackets, nothing happens (I can still open by menu, but I like shortcuts). The other search shortcuts works fine. Like `cmd + f` or `shift + f`. Any suggestions what I should do?

**Comment by petetnt** [comment]
Hey @saturday1,

regular Find & Replace should be `CMD-H`. Does the menu show it as `alt+CMD+f`?

**Comment by saturday1** [comment]
Hello!

On Mac, "cmd + h" hides the window. See my menu options in attached image.

![skarmavbild 2016-04-07 kl 08 49 46](https://cloud.githubusercontent.com/assets/6339163/14342916/cd665da6-fc9d-11e5-8478-b5128b6c4668.png)

**Comment by petetnt** [comment]
Oh right, I am on a Windows workstation so I didn't remember that :fire_engine: 

The [keyboard.json](https://github.com/adobe/brackets/blob/master/src/base-config/keyboard.json#L211) file shows the MacOS shortcut correctly:

```
    "cmd.replace":  [
        {
            "key": "Ctrl-H"
        },
        {
            "key": "Cmd-Opt-F",
            "platform": "mac"
        }
    ],
```

Have you tried launching Brackets without extensions to rule out extension issues (`Debug -> Reload Without Extensions`)? 

Does dev tools show any errors when you press the key combo (F12 or Debug -> show developer tools -> console)

**Comment by saturday1** [comment]
Tried without extensions. Didn't do the trick.

Console does not show any errors.

**Comment by saturday1** [comment]
Can I change the shortcut? Since that is one of the most important shortcuts for me. I betetr get rid of some other shortcut that I usually do not use.

**Comment by petetnt** [comment]
Did you try `cmd.replace`?

**Comment by saturday1** [comment]
That works. :) Thanks a lot!

**Comment by petetnt** [comment]
Great! I'll try to check out if the default shortcut key works for me when I get home to my Mac.

**Comment by saturday1** [comment]
I think I know the problem now...

I have a software running on my Mac, called "Spectacle". It is a great thing for windows in mac, like when you for some reason cant see or grab a program window you can run functions here to get it right. The shortcut `Cmd-Opt-F` makes the window fullscreen. It most be the reason.

![skarmavbild 2016-04-07 kl 11 07 21](https://cloud.githubusercontent.com/assets/6339163/14346120/025636b8-fcb1-11e5-948c-31bdbe2778cc.png)

**Comment by petetnt** [comment]
@saturday1 Nice catch, that's most likely it!

**Comment by petetnt** [comment]
Closing as solved.
