### ISSUE TITLE
Brackets not responsive upon launch

### ISSUE THREAD

**Issue by anilnatha** [adobe/brackets#12363]
I tried using Brackets today; however, upon launching the app, it would immediately become unresponsive. It's not frozen as I am not getting the spinning beach ball of death, the app simply doesn't respond to any command I give it.. The Menu options are clickable, but none of them respond to my selections, and keyboard shortcuts do not respond either. Force quitting the application is the only thing I can do.

I opened up the Console app so that I can see if any errors were thrown, and the only thing I found was the following:

    4/13/16 4:25:25.740 PM Brackets Helper[5015]: Cannot find executable for CFBundle 0x79c2a9f0 </Applications/Brackets.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/PDF.plugin> (not loaded)

_Had to use code formatting to display the error log because using a blockquote causes part of the log statement to not be displayed on GH._

After reviewing the error, I thought, let me check that location to see if the file is truly missing...

It isn't missing, it's there, but for some reason it's 0 bytes...

![screen shot 2016-04-14 at 09 49 05](https://cloud.githubusercontent.com/assets/931107/14536314/9ae72d68-0226-11e6-8824-56e9fe7c185e.png)

And I also checked it's file permissions in Terminal, but I don't know what they should be, and if they are correct...

![screen shot 2016-04-14 at 09 53 33](https://cloud.githubusercontent.com/assets/931107/14536349/cccc19e2-0226-11e6-93e5-e984c984c174.png)

**Things I tried:**
  1. I deleted the app and reinstalled Brackets, but that did not resolve the issue.
  2. Deleting my cache folder as outlined [here](https://github.com/adobe/brackets/wiki/Cache-Folder) 
  3. Opening the app via terminal, by simply navigating to the folder I wanted to open and running the command `brackets .`
  4. Opening Brackets via Terminal using the -F option `brackets -F`

I wanted to try the option "Reload Without Extensions", but since the app doesn't respond upon launch, I wanted to try it from the terminal command, but I don't see an option for it in the help documentation for the terminal command.

```
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
      By default, opens each file using the default application for that file.  
      If the file is in the form of a URL, the file will be opened as a URL.
Options: 
      -a                Opens with the specified application.
      -b                Opens with the specified application bundle identifier.
      -e                Opens with TextEdit.
      -t                Opens with default text editor.
      -f                Reads input from standard input and opens with TextEdit.
      -F  --fresh       Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.
      -R, --reveal      Selects in the Finder instead of opening.
      -W, --wait-apps   Blocks until the used applications are closed (even if they were already running).
          --args        All remaining arguments are passed in argv to the application's main() function instead of opened.
      -n, --new         Open a new instance of the application even if one is already running.
      -j, --hide        Launches the app hidden.
      -g, --background  Does not bring the application to the foreground.
      -h, --header      Searches header file locations for headers matching the given filenames, and opens them.

```

**My System:**

  * OS X 10.10.5
  * Brackets 1.6

**Comment by anilnatha** [comment]
I wanted to try the option "Reload Without Extensions", but since the app freezes upon launch, I wanted to try it from the terminal command, but I don't see an option for it in the help documentation for the terminal command.

```
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
      By default, opens each file using the default application for that file.  
      If the file is in the form of a URL, the file will be opened as a URL.
Options: 
      -a                Opens with the specified application.
      -b                Opens with the specified application bundle identifier.
      -e                Opens with TextEdit.
      -t                Opens with default text editor.
      -f                Reads input from standard input and opens with TextEdit.
      -F  --fresh       Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.
      -R, --reveal      Selects in the Finder instead of opening.
      -W, --wait-apps   Blocks until the used applications are closed (even if they were already running).
          --args        All remaining arguments are passed in argv to the application's main() function instead of opened.
      -n, --new         Open a new instance of the application even if one is already running.
      -j, --hide        Launches the app hidden.
      -g, --background  Does not bring the application to the foreground.
      -h, --header      Searches header file locations for headers matching the given filenames, and opens them.

```

**Comment by petetnt** [comment]
I tried to look in to this yesterday but didn't find any clear fixes: most `Cannot find executable for CFBundle` errors were related things related to XCode (and iOS apps).

Things you could try out: 

- Update XCode and see if that has borked something (if you have XCode installed)
- Update/reinstall Google Chrome to see if that has somehow corrupted the CEF data (this happened to me a long while ago). 
- Delete Brackets, delete the cache folder (especially the `cef_data` folder) and installing 1.6. yet again (or an older version from https://github.com/adobe/brackets/releases)

**Comment by anilnatha** [comment]
Thanks for attempting to look at the issue @petetnt.

I do have Xcode installed, but it is already up to date. In fact, I haven't altered my Xcode installation in a few weeks, not to say that Xcode may not be the culprit.

As for Google Chrome, I failed to mention it was also one of the things I checked when debugging the issue.  I'm currently running the latest version of Chrome, 50.0.2661.75 (64-bit).

I've already tried reinstalling Brackets twice now including the removal of the cache one of those two times, but I'll try it again later this week when I have some free time.

**Comment by nethip** [comment]
@anilnatha From what you have described above, the CEF initialisation seems to be failing. I am sure you would be tried downloading again, but just in case if you have not done that, could you download the binaries again? 

You could also build Brackets shell on Mac. Please refer [here](https://github.com/adobe/brackets-shell/wiki/Building-brackets-shell) for instructions.

**Comment by anilnatha** [comment]
So I tried reinstalling the application again. Once again I:

1. As outlined [here](https://github.com/adobe/brackets/wiki/Cache-Folder), cleared the cef_data folder
2. Shutdown my machine, waited about 10 seconds.
3. Started the machine back up
4. Reinstalled Brackets

So I tried again, this time I did an additional step:

1. As outlined [here](https://github.com/adobe/brackets/wiki/Cache-Folder): 
 * Cleared the cef_data folder
 * Removed the `brackets.json` and `state.json` files
2. Shutdown my machine, waited about 10 seconds.
3. Started the machine back up
4. Reinstalled Brackets

Happy to say that resetting the preferences seems to have resolved the issue. I saved a copy of my brackets.json file, compared it with the detault brackets.json file that was created, and slowly brought over my preferences, and Brackets is still working. I compared the old state.json and new file but didn't bring over any old settings into that file.

In addition, the error:

    4/18/16 2:31:31.183 PM Brackets Helper[1586]: Cannot find executable for CFBundle 0x78f9b200 </Applications/Brackets.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/PDF.plugin> (not loaded)

Is still being added to my error logs upon startup, so it seems that the CEF error is unrelated. Not sure what is in my preferences file that caused the problem though.

**Comment by DrTechDaddy** [comment]
Had the same problem today. This solution worked for me. Thanks.
