### ISSUE TITLE
Add ability to move files via drag&drop

### ISSUE THREAD

**Issue by peacememories** [adobe/brackets#12369]
Many text editors allow drag&drop-moving of files in the file manager of the editor.

This speeds up changing program/site structure enormously, so I would love to see it in Brackets.

**Comment by nethip** [comment]
We already have this in our backlog. Please up vote this [trello card](https://trello.com/c/0WJ1aKw2/287-5-drag-drop-within-file-tree-copy-move-file). I am going ahead closing this issue as this is a feature request.
