### ISSUE TITLE
Missing file list from Working Files sidebar

### ISSUE THREAD

**Issue by info170** [adobe/brackets#12361]
I am using Macbook with OS X 10 but I code in Brackets 1.6 on Windows7 which installed over OS X (with Parallels Desktop). If I leave open Brackets and go away for a few minutes, MacBook goes to a sleep mode and lost file list from Working Files sidebar. I need to find and open all my files again. May be there is any way to keep file list on disk not in RAM ?..

**Comment by petetnt** [comment]
The Working Set is already kept on a file on disk called `state.json`  Can you check if the file either gets wiped or emptied when you return from sleep mode? You can find info on finding the file here: https://github.com/adobe/brackets/wiki/Cache-Folder

RAM not persisting sounds like a Parallers issue to me
