### ISSUE TITLE
CMD+W closes a file, but not in the sidebar

### ISSUE THREAD

**Issue by Bluefirecracker** [adobe/brackets#12364]
**This may be a repost but I did not find an issue like mine when searching.**

If I close a file using CMD+W, the file closes in the main interface, but remains in the sidebar. If I click on it in the sidebar, it reopens. If there are numerous "opened" files, clicking on one reopens the one I clicked on, but clears the others out. 

This doesn't happen if I close the file using the X in the sidebar, or the X in the upper right hand of the opened file panel. But this is a pain to constantly have to close files that way so they properly disappear from the sidebar.

**Comment by petetnt** [comment]
Hi @Bluefirecracker,

This issue should have been hotfixed with https://github.com/adobe/brackets/pull/12246. 

Try installing Brackets again from Brackets.io as the fix has been backported to 1.6. and see if the issue persist.

**Comment by nethip** [comment]
@petetnt @Bluefirecracker Unfortunately we could not refresh the builds with the fix. Please wait for Brackets 1.7, that is due in a few weeks time.

**Comment by Bluefirecracker** [comment]
Ah, OK. 
I've downgraded to 1.5 for now. I'll keep a look out for 1.7 though. 
Thanks!

**Comment by petetnt** [comment]
Fixed in 1.7
