### ISSUE TITLE
Brackets stating error keymap.json not valid json file  

### ISSUE THREAD

**Issue by ramz225** [adobe/brackets#12376]
Release 1.6 build 1.6.0-16680 (release 3df0ac6fa) 
build timestamp: Tue Jan 12 2016 05:35:00 GMT-0800

{
	"documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
	"overrides": {
	  "Ctrl-Shift-/": "dcblocks-brackets.createCommentForBlock",
	  "Cmd-Shift-L":     "edit.splitSelIntoLines",
	  "Ctrl-Shift-Up":   "edit.addCursorToPrevLine",
	  "Ctrl-Shift-Down": "edit.addCursorToNextLine",
	  "Cmd-Shift-D":     "edit.duplicate",
	  "Ctrl-Shift-K":    "edit.deletelines",
	  "Cmd-L":           "edit.selectLine",
	  "Cmd-D":           "cmd.addNextMatch",
	  "Cmd-Opt-1":       "cmd.splitViewNone",
	  "Cmd-Opt-2":       "cmd.splitViewVertical",
	  "Cmd-Opt-Shift-2": "cmd.splitViewHorizontal",
	  "Ctrl-G":          "navigate.gotoLine",
	  "Cmd-Opt-Right":   "navigate.nextDoc",
	  "Cmd-Opt-Left":    "navigate.prevDoc",
	  "Cmd-R":           "navigate.gotoDefinition",
	  "Cmd-P":           "navigate.quickOpen",
	}
}

**Comment by redmunds** [comment]
Last line inside braces cannot have a trailing comma:

``json
    "Cmd-P": "navigate.quickOpen",
```

So change to:

``json
    "Cmd-P": "navigate.quickOpen"
```

**Comment by ficristo** [comment]
Closing as answered.
