### ISSUE TITLE
Four Panel Editor Division

### ISSUE THREAD

**Issue by vagv19** [adobe/brackets#12370]
Hi guys,
First at all i want to apologize for my english, then I would like to see a four edit panel instead than two (vertical and horizontal)

Greetings

**Comment by petetnt** [comment]
Hi @vagv19,

This is a much wanted feature for sure. There was some discussion about implementing it on the Brackets-Dev forum quite recently: https://groups.google.com/forum/#!topic/brackets-dev/vdXYrSwvOvM. There's also some older issues like #12262 that request the feature :+1:

**Comment by petetnt** [comment]
Closing as duplicate
