### ISSUE TITLE
Closing a file via Cmd+W doesn't remove it from Working Files

### ISSUE THREAD

**Issue by stowball** [adobe/brackets#12375]
For some reason, this just stopped working. I managed to perform a complete uninstall with CleanMyMac and it worked for about 30 minutes of setting Brackets back up again, but then it just stopped working again. Doing a complete uninstall a 2nd time made no difference.

In the console, if I restart Node, it tells me that:

`File watchers went offline! (/filesystem/FileSystem.js:959)`
`WebSocket connection to 'ws://localhost:54053/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED (/utils/NodeConnection.js:89)`
`Watching disabled for /Users/stowball/Documents/Git/mdm/app/web-apps/mdm-ui/ (/filesystem/FileSystem.js:967)`
![image](https://cloud.githubusercontent.com/assets/853552/14674541/ef31b43a-0747-11e6-8ce4-3612d7d462de.png)

Is it related? How do I fix it? Why has it magically broken?

**Comment by petetnt** [comment]
Hi there @stowball,

this has been fixed in the master branch for a while now, but unfortunately it doesn't land until 1.7. As a workaround you can either [use the master version of Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets), downgrade to 1.5. until 1.7. lands or apply [the fix](https://github.com/adobe/brackets/pull/12246/files) yourself to brackets.js found in the Brackets folder.

**Comment by stowball** [comment]
Thanks, @petetnt!

I've just pulled down the repo to use that version, but the change isn't in master (https://github.com/adobe/brackets/blob/master/src/project/FileViewController.js#L162) so had to apply the fix manually

**Comment by petetnt** [comment]
@stowball Argh, my bad. The `release` branch hasn't been merged with the master yet and the fix only landed to `release`. There was going to be a hotfixed version of 1.6. but that didn't materialize so the fixes were rolled over to 1.7 (I keep forgetting that... :cat:). Sorry for the confusion, hope it works now!

**Comment by jry8412** [comment]
@petetnt may I know when is the 1.7 release date?

**Comment by petetnt** [comment]
Hi @jry8412 unfortunately I don't know the exact date, you could try asking in the Release related checklist issue here: https://github.com/adobe/brackets/issues/12388 🚢

**Comment by jry8412** [comment]
Hi @petetnt thanks for the information 👍

**Comment by petetnt** [comment]
Fixed in 1.7
