### ISSUE TITLE
Brackets inserting spaces before or after double quotes in asp file

### ISSUE THREAD

**Issue by corehop** [adobe/brackets#12394]
When opening an ascx/aspx file, I am seeing an issue where Brackets is inserting code-breaking spaces around double quotes.  An example would be:

Before:
`<div class="<%= Items["className"] %>"></div>`

After hitting save:
`<div class="<%= Items[" className "] %>"></div>`

This leaves the class of the div blank, since the key with padded by spaces is not found in the dictionary.

**Comment by ficristo** [comment]
I cannot reproduce. Can you try `Debug` --> `Reload without extensions`?
Maybe you have some autoformatter extension.

**Comment by corehop** [comment]
You are correct, it turns out to be the Beautify extension.  I will follow
up with the Beautify devs.
