### ISSUE TITLE
A better icon for Mac OS

### ISSUE THREAD

**Issue by tgottc** [adobe/brackets#12391]
Hello.
May I suggest a better icon for Mac OS? I'm currently using a modified version:
http://cvangilder64.deviantart.com/art/Adobe-Brackets-OSX-Yosemite-style-Icon-480044659

Thanks.
![adobe_brackets_osx_yosemite_style_icon_by_cvangilder64-d7xt0tv](https://cloud.githubusercontent.com/assets/11369395/14941847/cb83f192-0f80-11e6-8aca-3c939c7a573a.png)

**Comment by thany** [comment]
Why so big? :)

Just curious, but wxactly why does Brackets need a 13-in-a-dozen circular icon? What's wrong with the current one? And why only MacOS?

**Comment by tgottc** [comment]
Every icon is dynamically resized.

**Comment by abose** [comment]
Leaving this to upvotes from the community here.
Closing.
