### ISSUE TITLE
Jade file make brackets slower

### ISSUE THREAD

**Issue by TheNemus** [adobe/brackets#12398]
Hi,

I found that when I'm using jade file with over 100 lines the editor framerate dramatically drops. I'm using v 1.6.0-16680 (release 3df0ac6fa). Am I the only one?

**Comment by ficristo** [comment]
Hi @TheNemus, if you try `Debug \ Reload without extensions` can you still reproduce?
AFAICT Brackets doesn't support jade natively, so maybe is an extension problem.

**Comment by ficristo** [comment]
Hi @TheNemus,
if you were able to fix the problem could you share your solution? It could help other users.
Thank you.
