### ISSUE TITLE
CSSUtils cannot gather state in some mixed-HTML-CSS cases

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#12399]
``` HTML
<style>
.test {
background-image: url(index.htm
    }
</style>
```

1. Copy this rather simple HTML snippet into a file
2. Open Developer Tools (F12)
3. Put the cursor after `index.htm`
4. Press Ctrl+Space to invoke (URL) Code Hints

Result:
In console, a `Uncaught TypeError: Cannot read property 'localState' of undefined CSSUtils.js:95` will be output.

Expected:
URL Code Hints open up correctly.

Alternative Steps:
3. Put the cursor after `.test {`
4. Press Enter to insert a newline
5. Write out the first few letters of a CSS property, like `color`, then press Enter to accept the shown Code Hint

Result:
The suggested Hint will be output, but with a trailing newline instead of suggestions for values.

Notice that the snippet above is the minimum test case. The most important bit is the indented fourth line, which causes this bug to occur. If it isn't indented (independent of the 2 above lines), this bug does not occur.

Thanks @ficristo for reporting this (https://github.com/adobe/brackets/pull/11284#issuecomment-216619535)

(`git bisect` points to https://github.com/adobe/brackets/pull/11751/commits/439d185a8e8db9ae14bfde30096afdb4aa934e4c)

**Comment by ficristo** [comment]
@sprintr could you take a look?

**Comment by sprintr** [comment]
@ficristo @MarcelGerber It must be because of me. I did not check it in other mixed html files. Will put a PR up.
