### ISSUE TITLE
gray screen

### ISSUE THREAD

**Issue by chelle7** [adobe/brackets#12392]
new user - download of Brackets last week worked fine - opened up this morning and just gray screen - no sidebar, nothing.

Downloaded a fresh copy of Brackets. Still gray screen. No sidebar. 

"Open Folder or File" lets me select something - changes header on gray screen, but then nothing happens. 

No file opens. No sidebar appears.

Any ideas?

**Comment by ficristo** [comment]
Can you run `Debug` --> `Show Developer Tools` and eventually print the console?
Other reason that come to my mind can be the following:
Maybe your state.json is corrupted. If you try `Debug` --> `Show Extension Folder` you should see a state.json (if not there look at the parent folder, this at least on OSX). Try to delete it, make sure to have a backup!
Could be that you opened a very big project, in this case you could try this extension https://github.com/zaggino/brackets-file-tree-exclude

**Comment by chelle7** [comment]
nothing worked and then just now opened just fine - thanks for your reply and will try it again next time!




Sent with Unibox
