### ISSUE TITLE
CSS doesn't work

### ISSUE THREAD

**Issue by kroogmcmoog** [adobe/brackets#12395]
Hey there, the CSS does not work, I have added the code for linking it with my HTML file.

`<html>
    <head>
        <title>Greatest Animators</title>
        
    </head>
        <link type="text/css" rel="styleheet" href="mainpage.css">
    <body>
        <h1>My Favourite Animators on the Internet</h1>
        <div class="table">
            <a href="Zach.html"><img src="https://yt3.ggpht.com/-T0H7xR-9iA8/AAAAAAAAAAI/AAAAAAAAAAA/VA9CSBc5Q8A/s100-c-k-no-rj-c0xffffff/photo.jpg"></></a>
        </div>
        <div id="zach">
        </div>
    
    </body>

</html>`

All the brackets are closed in CSS, I've checked. Maybe there's a setting that I activated accidentally?
The title of the css file is indeed the same as displayed in href.
The preview just shows the picture that I've linked to, no styling of the CSS, what might be the problem?

**Comment by ficristo** [comment]
It seems you are missing an `s` in style**s**heet:
`<link type="text/css" rel="stylesheet" href="mainpage.css">`
