### ISSUE TITLE
Extract can not connect to cloud

### ISSUE THREAD

**Issue by sstyle** [adobe/brackets#12403]
Tried to load my PSD. Successfully login in the Creative cloud but:

![default](https://cloud.githubusercontent.com/assets/6489964/15015305/c1c209ce-1213-11e6-905e-c4350c2d0ede.JPG)

When I had such issue with extensions, I just changed https to http in config.json

**Comment by ficristo** [comment]
Extract has been deprecated: http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/
Closing.
