### ISSUE TITLE
Brackets is not fully compatible with Linux

### ISSUE THREAD

**Issue by WHK102** [adobe/brackets#12409]
To use all the advantages of this editor you need two parts: the editor and design, clearly the editor handles help you with your designs in PSD format but the PSD designs only can create on Windows since there is currently no Photoshop for systems based on Linux such as Debian, Ubuntu, Suse, etc.

To use the complete solution you must have two computers with two operating systems or one powerful with a virtual machine, one Linux and one with Windows, besides this generates an additional fee and you must pay more than 10 times the cost of Adobe Photoshop in the Windows license.

Brackets so the solution is not fully compatible with Linux because it requires files that can only be created in Windows to be able to use all its features.

**Comment by ficristo** [comment]
Extract was deprecated and removed from Brackets. I think we can close this now.
