### ISSUE TITLE
Is there an extension for yeoman integration for brackets?

### ISSUE THREAD

**Issue by qweasd1** [adobe/brackets#12404]
I'm new to brackets but I love it !

Just want to know if we have any extensions for scaffolding function like **yeoman** does?

any one know it?

**Comment by petetnt** [comment]
Hi @qweasd1,

there's this extension: https://github.com/hpoom/brackets-yeoman but not sure its current status is. One option would be using Yeoman inside Brackets with something like https://github.com/artoale/brackets-terminal

**Comment by qweasd1** [comment]
@petetnt great！ thanks :+1:

**Comment by petetnt** [comment]
Closing as answered 👍
