### ISSUE TITLE
PHP Syntax highlighting missing array_intersect_key keyword

### ISSUE THREAD

**Issue by mambroz27** [adobe/brackets#12400]
**Steps**
Use `array_intersect_key()` in a PHP file.

**What Happens**
The PHP keyword `array_intersect_key()` does not highlight. The keyword should highlight with other keywords.

**Version**
 Release 1.6 build 1.6.0-16680

**Working Before**
Unsure

**Extensions**
Results are the same with or without extensions.

**Comment by ficristo** [comment]
I can reproduce on CodeMirror demo page: http://codemirror.net/mode/php/index.html
I've tried the following keywords and only `array_map` is highlighted.
`array_intersect_key, array_combine, array_column, array_map`
You should file a bug against it.

**Comment by mambroz27** [comment]
Good point. I filed a bug with Codemirror including the other missing keywords you found.
