### ISSUE TITLE
brackets 1.6 shortcuts are not working [ubuntu]

### ISSUE THREAD

**Issue by hardikdangar** [adobe/brackets#12413]
I have ubuntu 14.04 and i upgraded my brackets from 1.3 to 1.6 but it seems there are issues with keyboard shortcuts like,

ctrl-p ( which opened fuzzy finder),
shift-cmd-p ( command pallete ),
etc...

although most of basic editor shortcuts like ctrl+c, ctrl+v works but the ones i used in 1.3 are not working.
I couldn't find the issue but i tried following,

i uninstalled brackets via,
sudo apt-get remove brackets --purge,
removed .config/brackets folder and

Reinstalled brackets by fetching it from brackets.io site and installed but still those shortcuts are not working.

I even tried with debug > reload without extensions. but it seems it doesnt work too.

I tried debug > show developer tools > console.
I see some warnings under warning section, here is gist of that,
https://gist.github.com/hardikdangar/31b765443fca3e5f41e7f6bc891645a7#file-console-log
those are warnings not error but suggest updating script files so i am confused. it it the reason behind this ?

Can somebody suggest me what to try next ?

**Comment by ficristo** [comment]
@hardikdangar could you try the latest version (1.7) to see if you still have problems?
