### ISSUE TITLE
Add file tree exclude in core

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#12417]
Right now every time an user has a performance issue one of the first things is to ask to install an extension so to exclude some files from the watchers.
It would be nice to have it in the core, to reduce these issues.
It would be help my PR https://github.com/adobe/brackets/pull/12190 because then I could read to exclude list from the configuration.
Plus all of these extensions seems to mess with a private method `_indexFilter` which could results in some problems in the future.

There are some extensions but I was mostly think to this one:
https://github.com/zaggino/brackets-file-tree-exclude
/cc @zaggino

**Comment by zaggino** [comment]
Fine with me, but there should be some sort of icon/indicator that there were some entries hidden from the file tree and the user would be taken to the filter settings when he clicks that icon.

**Comment by ficristo** [comment]
Mmm totally my fault to not try the extensions before...
What I'm personally really interested is the configuration for the purpose of the PR #12190.
Now I'm not sure if I really want all the features of those extensions...

**Comment by petetnt** [comment]
Check out my enhancement proposal called `black-box` in https://github.com/adobe/brackets/issues/11833#issuecomment-149285875 which is basically File Tree Exclude + @zaggino's suggestion for UI interactions.

**Comment by asthomasdk** [comment]
This would indeed be good to have built in. We have huge performance issues with new environments on our default projects - until we install https://github.com/zaggino/brackets-file-tree-exclude - after which they go away.

**Comment by ficristo** [comment]
I much prefer the approach in #12647, so closing.
