### ISSUE TITLE
Brackets opens file browser dialog, asking the user to point it to an index.html on start-up

### ISSUE THREAD

**Issue by fusion809** [adobe/brackets#12418]
Hi,

I'm building an [automated installer](https://github.com/fusion809/brackets-installer) for this editor on Linux (which is intended to support a wide variety of different distributions) and it builds Brackets from source code (to see the build procedure, if you are curious as to what exactly my installer is doing, see [here](https://github.com/fusion809/brackets-installer/blob/master/lib/brackets-build.sh)). It seems to be working now, the only problem is that whenever one launches Brackets installed from it, a file browser dialog opens, asking the user to direct it to a valid index.html file for Brackets to use. For example, on Debian this is what I see after launching Brackets (note how in the terminal emulator to the left I have typed in the command `brackets`): 

![](http://imgur.com/YhKj3HE.png)

This is a nuisance, partly because I haven't the foggiest how to solve this issue. Is there some modification I need to make to my build procedure or is there some adjustment I need to make to how I am executing brackets? 

Thanks for your time,
Brenton

**Comment by petetnt** [comment]
Hi Brenton,

check out https://github.com/adobe/brackets-shell#running which describes the locations Brackets Shell looks the index.html file from and adjust your installer accordingly.
