### ISSUE TITLE
Downloaded Brackets, but now I can't open the program.

### ISSUE THREAD

**Issue by kpeacock24** [adobe/brackets#12412]
I tried using FreeViewer, but that download is failing, does anyone know of a free program I could use to open Brackets?  Thanks!

**Comment by redmunds** [comment]
If you downloaded from github (https://github.com/adobe/brackets) then follow directions in README for building Brackets locally. This is necessary if you want to contribute to Brackets core code. If you just want to run Brackets, then download aninstaller from http://brackets.io/.

**Comment by ficristo** [comment]
@kpeacock24 Were you able to solve?

**Comment by ficristo** [comment]
If you still have the problem, please add more details and then reopen.
