### ISSUE TITLE
Folder colors in tree sidebar reflecting git status

### ISSUE THREAD

**Issue by Diliz** [adobe/brackets#12428]
### Hi brackets ppls! :D

I would love to see one feature on brackets that atom have, I didn't found anything about it actually? And sublime doesn't have it too, so here's the feature description:

https://github.com/kemayo/sublime-text-git/issues/204

I dunno if there's something similar existing actually, but if not, it would be really cool to have the git status to be displayed directly on folders and files as colored icons, atom does it like this: 

![687474703a2f2f752e6d662e76632f35353434642e706e67 1](https://cloud.githubusercontent.com/assets/5158949/15317494/0ddf43cc-1c22-11e6-857e-ba15d6ed9a68.png)

This is the image of @rnarian (better display the image directly but here's the link : https://github.com/kemayo/sublime-text-git/issues/204#issuecomment-36732403)

Thanks for reading :)

**Comment by petetnt** [comment]
Hi @Diliz,

have you checked out the great [Brackets-Git](https://github.com/zaggino/brackets-git) extension? IIRC it does something similar.

**Comment by Diliz** [comment]
Hi @petetnt,

Didn't see there was an option to mark modified files in file tree :)

Thanks, think I was pretty tired when I checked it... :/
