### ISSUE TITLE
Install failed on Debian Jessie

### ISSUE THREAD

**Issue by VVGIT** [adobe/brackets#12423]
When I try to install Brackets on a Debian Jessie OS, I get the following message: "Failed to install file - An unspecified transaction error has occurred. More information is available in the detailed report."

**Comment by ficristo** [comment]
The first thing that come to my mind is this issue: https://github.com/adobe/brackets/issues/10255

**Comment by dad7** [comment]
root@x51rl:~# dpkg -i /home/dad/Brackets.Release.1.8.64-bit.deb
....
 brackets depends of libgcrypt11 (>= 1.4.5), but:
 libgcrypt11 isn't installed.

**Comment by zaggino** [comment]
Please see this guide: https://nathanjplummer.github.io/Brackets/
The link to it is also in the README
