### ISSUE TITLE
Underline 

### ISSUE THREAD

**Issue by BarryEgan** [adobe/brackets#12424]
![screen shot 2016-05-15 at 02 22 07](https://cloud.githubusercontent.com/assets/19373684/15274645/149fa5f2-1ac0-11e6-96e2-a71f4333df20.png)

![screen shot 2016-05-15 at 02 21 57](https://cloud.githubusercontent.com/assets/19373684/15274644/149db378-1ac0-11e6-9a86-48c614237852.png)

is there any way that I can use without underlining the code when I click to write. It becomes bigger and moves to right and underlines, that's not good for me, loosing my concentration.

how can I change this and make it stay the same?

Thanks.

**Comment by MiguelCastillo** [comment]
@BarryEgan Can you give me a lil more background about your issue.  Just to confirm this is not brackets default dark theme, correct?  If it is not, then who created that theme?

**Comment by BarryEgan** [comment]
@MiguelCastillo At the first image you see the code not-underlined, normal; at the second image when I hit the code to write as you see it underlines and get bigger. This makes it hard to write and deal, cause the place I'm trying to edit goes to right. And no it's not the default theme, dark something, and now when i removed the theme, problem solved. White background but allright better then underline.

**Comment by ficristo** [comment]
The default dark theme (Brackets Dark) does highlight the tags without the underline.
Closing as theme issue.
