### ISSUE TITLE
problem in brackets default theme

### ISSUE THREAD

**Issue by AdelRK** [adobe/brackets#12431]
He , foreign bug !! with brackets 
when i  want  change brackets theme to another theme ( for ex Dark )
it chnage normaly , but if i close brackets and open it again .. theme will restore to the default theme ( light ) i'd like to ask if there is any method or fix for this bug !

**Comment by ficristo** [comment]
@AdelRK Do you have already tried `View \ Themes`?

**Comment by ficristo** [comment]
ping

**Comment by ficristo** [comment]
If you still have the problem, please add more details and then reopen.
