### ISSUE TITLE
Can brackets work like the "Folding Text" editor for the Mac?

### ISSUE THREAD

**Issue by chuck-brackets-questions** [adobe/brackets#12459]
I am looking for a folding text editor for text files. The "Folding Text" editor works will for the Mac, but I am looking for one the will run on a Mac and a Windows PC. I was hoping brackets would do what I need, I don't need everything Folding Text has. I am having trouble getting the "custom folding region" package working. I posted the problem as "custom folding region problem" #12443. Is there a problem with custom folding for plan text files vs. code? Are regions treated differently if they are in *.py or *.js files verses *.txt files?

**Comment by thehogfather** [comment]
@chuck-brackets-questions I missed the issue on the custom-region-folding extension. I'll have a look now and address there as the extension is managed completely outside of the context of brackets. 

Note to brackets Admin, this issue can be closed.
