### ISSUE TITLE
Can't install — 'protocol wrong type for socket'

### ISSUE THREAD

**Issue by isaacminogue** [adobe/brackets#12457]
On OSX10.11.5
Can't install either the extract or regular version of brackets.
Keep getting this error, every time. Any tips?

![screen shot 2016-05-26 at 12 17 10 pm](https://cloud.githubusercontent.com/assets/10933880/15560073/17e58e00-233c-11e6-8c70-1d5b982807f7.png)

**Comment by salazr** [comment]
@isaacminogue I'm having this issue, but it's happening with all .dmg files, and seems to be a 10.11.5 bug.

**Comment by ColinRioux** [comment]
Since OS X 10.11.5 was released recently, best you could do right now is submit a report to apple and wait. Most likely they'll push 10.11.6 within the coming weeks. 

It may also be that they pushed a dmg update and any dmg's may no longer work. Not sure. You could check the changelist.

**Comment by thelgevold** [comment]
This error when away for me once the auto updates were installed

**Comment by ficristo** [comment]
As pointed out by @salazr seems a 10.11.5 bug.
@isaacminogue if you have still the problem, could you fully update your system and retry?

**Comment by ficristo** [comment]
I close this since we didn't hear back and because this problem is most likely an OS issue.
