### ISSUE TITLE
There should be HTML hints for `aria-*` attributes

### ISSUE THREAD

**Issue by twang2218** [adobe/brackets#12461]
In the code: 
https://github.com/adobe/brackets/blob/master/src/extensions/default/HTMLCodeHints/HtmlAttributes.json

The `aria-*` attributes are missing, which are states and properties for Accessible Rich Internet Applications, defined in https://www.w3.org/TR/wai-aria/states_and_properties

**Comment by Coder206** [comment]
I'll try to fix this one

**Comment by Coder206** [comment]
The code is ready and is waiting the merge to master. It works well!

**Comment by Denisov21** [comment]
Fix in PR #12471

**Comment by Coder206** [comment]
@twang2218 I solved this issue and it has been pull requested.

**Comment by twang2218** [comment]
As #12471 has been merged and will be released as part of 1.8, I'm closing this issue.

**Comment by gparsloe** [comment]
Hello. I'm using Brackets 1.9 (just updated from 1.6 today). How do I trigger aria hints? I've tried just typing aria- and waiting, but nothing happens.

**Comment by Coder206** [comment]
@gparsloe Thanks for the information. I am glad you found a solution. :) I would suggest reporting this as an issue.
