### ISSUE TITLE
Shift extension ownership to (GitHub-)organization

### ISSUE THREAD

**Issue by Hirse** [adobe/brackets#12464]
Some time ago the popular [Brackets Beautify](https://github.com/brackets-beautify/brackets-beautify) extension was moved to the [organization with the same name](https://github.com/brackets-beautify) so we could maintain it together.

However, none of us now seems to be able to upload new version to the Brackets Extension Registry.

Is it possible to change the permission of that extension so that all members of the organization can upload new versions?  
I don't want to upload it as separate extension, because that would require manual update work for each user.

**Comment by redmunds** [comment]
@Hirse Brackets Registry currently only allows a single github id as owner. Can you setup a shared github id and use that account for all registry updates?

**Comment by Hirse** [comment]
@redmunds Thanks for the advice.

I have set up a new account ([brackets-beautify-updater](https://github.com/brackets-beautify-updater)). How can I transfer the ownership of the extension to it?

**Comment by redmunds** [comment]
@Hirse Go to the Brackets Registry web page here: https://brackets-registry.aboutweb.com/  In the upper-right corner, click "Sign in via Github" link and sign in to current owner (Hirse). All extensions owned by logged in account will have a "Change Ownership" link.

**Comment by Hirse** [comment]
@redmunds Thanks. It is not currently owned by me though.

@drewhamlett Could you try this, please?

**Comment by drewhamlett** [comment]
@hirse Done!

**Comment by Hirse** [comment]
@drewhamlett Sorry, I was not precise. We can't use the organization, so I made an [updater account](https://github.com/brackets-beautify-updater) (whose password I would share with you), which should be owner of the extension in the registry.

@redmunds I guess, now we might have a problem as the current owner is our organization account, which we cannot use to login. Can you (or another admin) change to ownership to `brackets-beautify-updater`?

**Comment by redmunds** [comment]
I don't have any authority on that system. If @drewhamlett can't make the change, and you can't change ownership of the your fork, then maybe submit a new extension from the updater account?

**Comment by Hirse** [comment]
But having a new extension would have the serious downside of not providing the update mechanism, so most user would not receive the new version.

Is it possible to get the old one removed and upload a new one (from the updater account) with the same id so we have updates?
