### ISSUE TITLE
Option to remove/close a folder

### ISSUE THREAD

**Issue by lukalazov** [adobe/brackets#12470]
I got an option to open a folder but not to remove it.

**Comment by petetnt** [comment]
Hi @lukalazov,

`Close current project` sounds good to me (but requires Brackets to be able to handle a state without any projects, which is in the backlog IIRC).

Mean while you can close projects (folders) by opening another project, clicking the project-dropdown (on top of the file tree/ under working set), hovering under the project and clicking the X.

![screen shot 2016-05-29 at 19 21 22](https://cloud.githubusercontent.com/assets/7641760/15634680/7bd7ade2-25d2-11e6-802f-9cf9b4067d64.png)

**Comment by lukalazov** [comment]
I could ask you when could I expect this feature, but that would be a silly question. But thanks for replying @petetnt
