### ISSUE TITLE
Brackets keep Editing my Code all by itself

### ISSUE THREAD

**Issue by Psarmmiey** [adobe/brackets#12479]
I don't actually know the cause of this but it keeps a happening any time I'm on the Live preview Barackets keep asking me to save my file and it happens until I end Brackets as a process

**Comment by redmunds** [comment]
Try: _Debug > Reload Without Extensions_ to see if this is being caused by an extension.

**Comment by Psarmmiey** [comment]
Still the same issue

**Comment by ColinRioux** [comment]
What operating system and what release version?
