### ISSUE TITLE
Dilato: LOC: JPN/FRA: String "Recent Files" is not localized.

### ISSUE THREAD

**Issue by chunyan123** [adobe/brackets#12489]
1. Launch Brackets.
2. File->Open Recent...
3. Observe string "Recent Files" in dialog.

Result:String "Recent Files" is not localized.
Expect: String "Recent Files" should be localized.
![fra_brackets1 7_lk_004_1 7 0 16894](https://cloud.githubusercontent.com/assets/19649461/15744896/5b9b8d00-2901-11e6-847f-1a236ea9cbe9.png)

**Comment by Zhanxin** [comment]
New issue for this 1.7 release

**Comment by KatarzynaWodzinska** [comment]
Hi All! Please note that the strings are localized in the TM database. Please retake the screens. Thank you!

**Comment by VibhaMalhotra** [comment]
![win_fr](https://cloud.githubusercontent.com/assets/19661774/15927833/5cbbd1b2-2e61-11e6-8c4e-9f704b55664b.png)
![win-jp](https://cloud.githubusercontent.com/assets/19661774/15927834/5cbd82f0-2e61-11e6-800e-693b0989772b.png)
