### ISSUE TITLE
auto complete for pseudo-selectors?

### ISSUE THREAD

**Issue by sterlingcooper** [adobe/brackets#12486]
Hi, I've been testing brackets out and I like the code completion for CSS, but am wondering if it does auto-complete for pesudo selectors? I can type them manually but it's helpful to not have to type out "first-of-type" etc. Is there an extension for this? Thanks.

**Comment by arthur801031** [comment]
Hi @petetnt  I would like to work on this. Do I add this to the core? Could you provide some guidance on how to tackle this problem? Thank you!

**Comment by petetnt** [comment]
The CSS code hinting is handled in https://github.com/adobe/brackets/blob/master/src/extensions/default/CSSCodeHints/main.js

The list of autocomplete values come from https://github.com/adobe/brackets/blob/master/src/extensions/default/CSSCodeHints/CSSProperties.json

I think @sprintr and @MarcelGerber have been working with CSSCodeHints the most lately, so they might be able to give out more specific pointers 👍

**Comment by redmunds** [comment]
CSSCodeHints is for `property:value;` pattern, so pseudo-selectors may not be a good fit there. May want to split pseudo-classes & pseudo-elements off into a new extension similar to how HTMLEntityCodeHints is separate from HTMLCodeHints.

**Comment by petetnt** [comment]
@redmunds you are correct, sounds good to me.

**Comment by swmitra** [comment]
Not sure whether I am late already and @arthur801031 has already started working on this. 
I have already done the same as part of Brackets in Dreamweaver and should be forward porting it to Brackets in release 1.9. This release will cover a whole bunch of things in terms of code hints which will be contributions from Abode back to Brackets. FYR , please check the following screenshots which depicts pseudo-selectors/elements and at-rules. 

![at-rules](https://cloud.githubusercontent.com/assets/12087205/19921613/aab45284-a104-11e6-9ee6-8ae8d031300f.png)
![pseudo-elements](https://cloud.githubusercontent.com/assets/12087205/19921614/aab798cc-a104-11e6-906c-8ab3e4554c46.png)
![pseudo-selector](https://cloud.githubusercontent.com/assets/12087205/19921615/aabc29c8-a104-11e6-9df7-733cc88b33eb.png)

What I would request is to contribute towards things like less variable hinting, saas variable hinting in a project. Brackets is lacking CSS pre-processor workflows in it's current form, if we can invest time and get in some pieces in this area it would be great!

**Comment by arthur801031** [comment]
Hi @swmitra @petetnt  I just started today, so no worries. I will find another bug/feature to work on. Thank you very much for your time! :)

**Comment by swmitra** [comment]
@arthur801031 I was late indeed in that case 😄  It's great to see the spirit of all the Brackets contributors, and this is what will keep Brackets growing bigger and better.  A big thumbs up for your last PR ( switching focus between panes ) 👍 , keep them coming.
 
There are a lot of missing things which all of us could focus for the next release. I will try to compile a section in the release card for 1.9 to mention some hot spots or contribution areas which potentially could take Brackets to the next level.

**Comment by guahanweb** [comment]
@arthur801031, how's this coming? In the example above, are you looking at the element as a way to reduce the available pseudo-classes? For instance, if you are defining something like `i.test:`, would the recommendations *remove* the link-specific pseudo classes? I'd love to help on this if it's still needed.

**Comment by MarcelGerber** [comment]
Implemented with #13295.
Closing.
