### ISSUE TITLE
Expanding/hiding block

### ISSUE THREAD

**Issue by Ppppackman** [adobe/brackets#12488]
Hello.
When you hide some block (for example inside the { } ) and expand it later you can't hide it again and the little triangle on the left side is not changing on the "expanded" status.
It happens all the time in all versions.
Win 7 32 / Win 7 64.
![expanding](https://cloud.githubusercontent.com/assets/8499438/15735822/41a36182-28a4-11e6-976f-ccb16f89731e.jpg)

**Comment by alexandredavi** [comment]
I've tested here in the 1.7 Pre-release version, and it's working. Maybe are you not using an extension?

**Comment by Ppppackman** [comment]
I'm using Brackets for a 2 years (almoust) and I can't understand the principle, when this bug is showing up. You just need to write some code for a some time.
And I have no installed extensions.

**Comment by ficristo** [comment]
This issue seems very likely the same fixed in https://github.com/adobe/brackets/pull/12521 which will be in 1.8
