### ISSUE TITLE
Dilato: LOC: JPN Only: Word "ture" and "false" are not localized in all comments.

### ISSUE THREAD

**Issue by chunyan123** [adobe/brackets#12490]
1. Launch the Brackets
2. Click Debug
3. Click Open Preferences File
4. Observe word "true" and "false" in all comments.

Result: Word "true" and "false" are not localized in all comments.
Expect: Word "true" and "false" should be localized.
![true](https://cloud.githubusercontent.com/assets/19649461/15745105/acb78a44-2902-11e6-97bb-db6ffdeed159.png)
![333](https://cloud.githubusercontent.com/assets/19649461/15746299/893772d6-2908-11e6-9a70-e5710a55de95.png)

**Comment by Zhanxin** [comment]
Checked and reproduce on release 1.6 build

**Comment by KatarzynaWodzinska** [comment]
Checking with the linguists.

**Comment by petetnt** [comment]
This one is OK, as the values can be only `true/false`

**Comment by KatarzynaWodzinska** [comment]
I just checked with the JP linguist. 

"true" / "false" here should not be localized but remain in English. 
Since they are used in the code sample and "true" / "false" should be kept in English in code sample comment.
