### ISSUE TITLE
Drop extract from web assets

### ISSUE THREAD

**Issue by Zverushko** [adobe/brackets#12497]
Hello!
From 28 june web assets delete extract.

It will work in the brackets?

**Comment by Zverushko** [comment]
http://blogs.adobe.com/creativecloud/update-for-extract-in-creative-cloud-assets-and-brackets/

**Comment by sirLisko** [comment]
Is there around any free alternative?

**Comment by ficristo** [comment]
Closing since Extract is deprecated.
I _think_ Dreamweaver has / will have this feature.
