### ISSUE TITLE
A better way to get suggestions in html

### ISSUE THREAD

**Issue by lukalazov** [adobe/brackets#12493]
Instead of typing the opening '<' and than 'a' and than getting a suggestion  for a, abbr, address, area...
![screenshot from 2016-06-04 11-21-30](https://cloud.githubusercontent.com/assets/19621015/15798822/03ca4cdc-2a47-11e6-90d4-df37d4fdc58a.png)
why not make it easier, when someone just type the letter 'a' this should happen
![screenshot from 2016-06-04 11-21-39](https://cloud.githubusercontent.com/assets/19621015/15798833/735c01ee-2a47-11e6-9eb4-998955329278.png)
Here is some example, if someone type 'h' he gets a suggestion for h1,h2...header..ect
![screenshot from 2016-06-04 11-21-55](https://cloud.githubusercontent.com/assets/19621015/15798840/bb634e16-2a47-11e6-8dff-e36d1b0cf8b8.png)
but if 'html' is chosen,  this should be like a snippet, and the result is 
![screenshot from 2016-06-04 11-22-01](https://cloud.githubusercontent.com/assets/19621015/15798845/fd485ede-2a47-11e6-9ce8-654e85384833.png)

**Comment by lukalazov** [comment]
come on people, I added photos, a thumbs up would be appreciated :disappointed: haha this is like instagit for me, I need a like :+1:

**Comment by sprintr** [comment]
You can use [Emmet](https://github.com/emmetio/brackets-emmet) for many of these tasks.

**Comment by lukalazov** [comment]
I could but I would prefer this one, I am using it already. I am just trying to suggest it to others.
![desktop-animation](https://cloud.githubusercontent.com/assets/19621015/15804670/4b71e7b4-2b11-11e6-9896-a1e30c3cb21e.gif)

**Comment by ItamarShDev** [comment]
@lukalazov how did you accomplish that?

**Comment by lukalazov** [comment]
I am not a programmer, so I installed Brackets Snippets (by edc), and it comes with a snippets manager, so I added all the html elements and created a snippet, template for each element, you can not see the whole list I added in this picture, but here is an example.
[Uploading Screenshot from 2016-06-08 15-41-48.png…]()
And when you type you get an instant suggestions. The only problem is that you get suggestions when you don't need them . For example when you need to type a href, or src or type attribute or any attribute you wont get the default suggestions, you will get snippets, but when you press ctrl+space, you get the results you are looking for.
[Uploading GIFrecord_2016-06-08_160131.gif…]()
so if there is anyone who can make this happen, I would like to help. :)

**Comment by lukalazov** [comment]
If any one wants to try this out, you can install this extension "Brackets Snippets (by edc)" than in Brackets click Help/ Show Extensions Folder. Than click user, open edc.brackets-snippets, replace the library-hints.yml with the same file 'ibrary-hints.yml ' you will download from https://github.com/lukalazov/brackets-snippets, I think you need to close and open brackets. than all you need is to open the snippets manager, click library and add all elements, so you could get the suggestions, I suggest first removing the defaults from the left pane.
