### ISSUE TITLE
Dragging a text on a Mac with a left click

### ISSUE THREAD

**Issue by Karol1984** [adobe/brackets#12499]
Hi,
Is it possible to drag a text on a Mac computer by holding a selected text with a left click and moving it to a different position, like in many other apps on Macs?

Thanks in advance for a reply.

**Comment by redmunds** [comment]
Yes, you can drag selected text.

**Comment by Karol1984** [comment]
I can't, unfortunately. After left click on a selected text it is immedietly unselected, so i can't drag it anywhere. It's very annoyinig.

**Comment by redmunds** [comment]
Maybe we're talking about different things, but "click" usually refers to pressing mouse down and then releasing it, which changes the selection. You should be able to press mouse down on selected text and then drag it.

Are you using a mouse or a trackpad? For a trackpad, I usually use 2 fingers -- 1 finger to press down and hold, while dragging with the other finger.

Maybe try creating a video or gif (although it's hard to tell when mouse is pressed and released).

**Comment by Karol1984** [comment]
I mean click and hold. I use a two button mouse. 

Video: https://vid.me/mi5S

**Comment by redmunds** [comment]
Do you have another computer or mouse that you can try?

**Comment by Karol1984** [comment]
No, unfortunately. But if I'll try on somebody else's computer I'll drop a line here. Sorry for my english.

**Comment by lukalazov** [comment]
What you can do is to select what you want to move, than press ctrl+shift and then arrow up or down, where you want it to move.

**Comment by ficristo** [comment]
Maybe you don't have enabled the preference `dragDropText`?
https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#list-of-supported-preferences

**Comment by Karol1984** [comment]
ficristo: Yes, you're right - it seems I have `dragDropText` disabled, but I don't know how to enable this. When I open preferences file (Debug > Open preferences file) I can't change setting to `true` .

**Comment by ficristo** [comment]
@Karol1984 You should add the preference on the __right__ panel.
Assuming you don't already have the preference you can add it at the end of the file before the brace.
Remember the comma before: you should have a valid json (not comments allowed).
```json
    "<last preference>": true,
    "dragDropText": false  
}
```

**Comment by Karol1984** [comment]
@ficristo Thank you very much. It works. I have to admit, that I had not read instruction at the begining of defaultPreferences.json :-( Thanks once again.
