### ISSUE TITLE
Extensions installation failed 

### ISSUE THREAD

**Issue by sohilj23** [adobe/brackets#12508]
I can't install any Extensions or Themes , I receive this error : Installation failed    Unknown internal error.
also Drag and install from URL has same problem.

Debug > console : 
[node-error 8:41:42 PM] [Launcher] uncaught exception at top level, exiting. Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1135:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)

I'm using ver 1.6 ( tried to install 1.7 but each time it installs ver 1.6 ! ) on Ubuntu 16.04 LTS
Please help me to figure out what should I do.

**Comment by ODenisov** [comment]
Caugth same issue on version 1.7.0-16898.

**Comment by sohilj23** [comment]
@ODenisov  I found only one solution after so many search, You should install them manually by putting them inside the user folder.
So for doing that first download one of the extension or theme you want to install, then go to : 
/Home/.config/Brackets/extensions/user 

*if you don't have extensions folder, create one folder and rename it to extensions and create one more for user.

After doing that , just extract your .zip files into one folder, the put that folder inside /user, Now it's ready just reopen Brackets.

**Comment by nethip** [comment]
We are currently looking at it. Sorry for the inconvenience. We should be able to fix this and refresh the build in a day or two.

**Comment by nethip** [comment]
We have refreshed the Linux builds with the fox. Could you try downloading the 1.7 build and reinstalling it again. ?

**Comment by ficristo** [comment]
@sohilj23 if you have still problem please open a new issue.

**Comment by vadi2** [comment]
Re-downloading and forcing a reinstall of the same 1.7.0-16898 version fixed the issue.
