### ISSUE TITLE
Menu items not responding and project files not visible in 1.7 OSX 10.11.5

### ISSUE THREAD

**Issue by rickcurran** [adobe/brackets#12500]
I just installed the latest 1.7 version via the .dmg installer, but when I open Brackets it shows no files and the Menu items won't respond.

I've attached a screenshot of what this looks like:

![screenshot 2016-06-10 13 34 11](https://cloud.githubusercontent.com/assets/878731/15964369/1bdab898-2f10-11e6-949b-6ff4105670a7.png)

Here's a screencast of the menu items not responding:

https://dl.dropboxusercontent.com/u/18567/brackets-1.7-menus-not-working.m4v

I'm running OSX 10.11.5 on a late 2011 15" MacBook Pro 2 GHz Intel Core i7, 8GB Ram, AMD Radeon HD 6490M 256 MB.

**Comment by nethip** [comment]
@rickcurran Can you delete the preferences and try launching Brackets?

**Comment by rickcurran** [comment]
Deleting the preferences did get it working, but unfortunately all of my project configurations are gone and it's just showing as if I'm using Brackets for the first time (which makes sense as I've just killed the preferences). It's going to be a bit of a pain having to go back through all of these projects and re-configure it! 👎

**Comment by nethip** [comment]
@rickcurran sorry to hear about that.  I should have been more explicit about renaming the preferences folder.

**Comment by rickcurran** [comment]
It's ok, I backed up all my preference files, but I've been unable to copy any of them back and get it back to where I was before this issue. I did get 95% of the way there by disabling all of the extensions I use and copying over my previous brackets.json file, this did bring in my site files but for some reason the dropdown menu for switching between projects wouldn't work. I think I'm going to have no choice but to re-configure it all (I'll use it as an opportunity to clean things up a bit!).

**Comment by redmunds** [comment]
@rickcurran Recent projects, etc are stored in state.json, so try renaming that file.

**Comment by ficristo** [comment]
@rickcurran were you able to solve your problem?

**Comment by rickcurran** [comment]
@ficristo Yep, as per my last comment above I had to basically reset everything in Brackets to get it working again, copying over the existing brackets.json file didn't work. So, a bit of a clean restart for me there to get it working again, not too big a deal as it was easy enough to get all the extensions back in.

**Comment by ficristo** [comment]
Glad you worked out your problem :+1:.
Closing.
