### ISSUE TITLE
HTML error on brackets.io

### ISSUE THREAD

**Issue by Xmashine** [adobe/brackets#12501]
On **Chrome** **53.0.2764.0** **Canary** _(64-bit)_ there is a rendering error on the main download button. this is a bug while computing the code `<div data-i18n="[html]index.page.hero.download">Download Brackets <d id="download-brackets-version">1.7</d></div>`.  the output is a portion of code malformed.<br>
![bug](https://cloud.githubusercontent.com/assets/18101935/15965210/cb565e4c-2f1c-11e6-8ff8-bb86fca48a42.png)<br><br>
![code-error](https://cloud.githubusercontent.com/assets/18101935/15965249/fff2fd9a-2f1c-11e6-8272-36e7e51caab7.png)

**Comment by ficristo** [comment]
Closing since it has been fixed.
