### ISSUE TITLE
Ubuntu 16.04 issues

### ISSUE THREAD

**Issue by onebelarusianguy** [adobe/brackets#12515]
I'm trying move from Windows(where is Brackets works well) to Ubuntu and it makes me sad :(
1. Remembering the last open state of project not working, as well as not working adding opened files to left and right panels in sidebar.
2. Double-click to close Brackets? wtf?
And I assume it's not all problems that can be on linux.

I love Brackets so much, please don't ignore linux users.

Builds that i've tried: 1.6, 1.7 - the same troubles

**Comment by NathanJPlummer** [comment]
The Brackets team recently refreshed the Linux deb installer and it fixed all the issues I was having with Ubuntu.

Unfortunately they didn't add a version change or any sort of announcement, and I just stumbled upon this information in another issue post.

I detailed how I got everything working at #12514 

The gist is:  Don't use the PPA, install libcrypt11 manually and then install the Brackets deb from the website.

**Comment by FTG-003** [comment]
Hi guys , 
Just to inform you that Brackets still crash on Ubuntu 16.04 (Xenial Xerus) X64
No luck with any of these combinations and tips to work around the problem, unfortunately.

Can someone help me to solve this issue splease? 
**_I love Brackets and and I'd really like to keep using it and share it's development in the community._**

Thanks in advance! :shipit:
