### ISSUE TITLE
Extensions or themes not installing after upgrade to 1.7

### ISSUE THREAD

**Issue by Psarmmiey** [adobe/brackets#12510]

**Comment by sohilj23** [comment]
I found only one solution after so many search, You should install them manually by putting them inside the user folder.
So for doing that first download one of the extension or theme you want to install, then go to :
/Home/.config/Brackets/extensions/user

*if you don't have extensions folder, create one folder and rename it to extensions and create one more for user.

After doing that , just extract your .zip files into one folder, the put that folder inside /user, Now it's ready just reopen Brackets.

**Comment by nethip** [comment]
If you are on Linux could you try re downloading the 1.7 Linux build and see if it is fixing the issue. We have refreshed the Linux builds as there was a issue with 1.7 64 bit

**Comment by ficristo** [comment]
Closing since the Linux build should have been fixed.
