### ISSUE TITLE
How to Update Extensions

### ISSUE THREAD

**Issue by syberknight** [adobe/brackets#12512]
hello,

forgive my ignorance here - i'm a complete Brackets noob.

i've gone thru & installed a select few Extensions & Themes - all seems well so far. 
i'm just curious... will Brackets let me know when these Extensions & Themes have updates?

i know it will for a Brackets update (experienced that already); just can't find how to deal with this part.
thanks.

**Comment by ficristo** [comment]
@syberknight the lego icon, the extension manager one, on the toolbar on the right will become colored (green) when there is an update.
Alternative you can open the extension manager and you see the icon colored.
This is true for the extensions, I think it will happen for themes too.

**Comment by syberknight** [comment]
COOL - thank you @ficristo 
much appreciated

**Comment by ficristo** [comment]
I forgot to write that if you didn't use the extensions manager I think you are on your own...

**Comment by syberknight** [comment]
yeah i understood that. thanks tho!
