### ISSUE TITLE
unable to install extensions after installing brackets v1.7

### ISSUE THREAD

**Issue by phani2791** [adobe/brackets#12525]
HI
Thanks in advance i am unable to install extensions in my ubuntu 14.04 and facing the internal error problem.
can you please help me

{
    "uuid": "9ce65cb1-3811-4dd8-b8a3-4a214a3cb655",
    "snapshotTime": 1465899191195,
    "os": "linux",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.80 Safari/537.36",
    "osLanguage": "en",
    "bracketsLanguage": "en",
    "bracketsVersion": "1.7.0-16898",
    "fileStats": {
        "openedFileExt": {
            "html": 1
        },
        "workingSetFileExt": {
            "html": 1
        }
    },
    "projectLoadTimes": ":0",
    "fileOpenTimes": ":0",
    "ModuleDepsResolved": 1,
    "AppStartupTime": 2,
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": [],
    "bracketsTheme": "light-theme"
}

**Comment by nethip** [comment]
@phani2791 Sorry for the inconvenience. We are working on this!

**Comment by nethip** [comment]
There was an issue with 1.7 Linux 64 builds. It was to do with brackets unable to connect to Node. We have now fixed the problem and refreshed the builds. Could you download the Linux 1.7 builds again from brackets.io and check?

**Comment by kowsoleea** [comment]
I just downloaded the 1.7 Linux 64 build. Everything seems to work fine (extensions, using git-extension). After 5 min. of testing I think it's ok now.

@nethip Thank you!!!! Wonderful job!!!

**Comment by xfg** [comment]
Wow! Good job! It's ok working.

**Comment by ficristo** [comment]
@phani2791 if you are still having issues after reinstalling please open a new issue.
