### ISSUE TITLE
Brackets Website Admin Extension stuck on loading

### ISSUE THREAD

**Issue by heavenkinder** [adobe/brackets#12524]
Hello. Yesterday i was looking for an extension that would make me able to edit files on my FTP server.
I have my website on runhosting, and i was able to connect brackets to the server, i  have the directory in my filetree. But when i click edit, it gets stuck on **"Edit file from FTP server: Contacting Server"**... I've been looking around in the server connection, seeing the information and credentials, but i can't see any problem. If i can see the files in the brackets filetree, why won't it let me edit? Using brackets to edit and make changes live on the server would speed up my performance so much but it's been a pain

**Comment by Intronet** [comment]
Try one of these
* Try setting up another FTP connection (different host) to see if this works
* Make sure your local project working folder is not write protected

**Comment by ficristo** [comment]
Extensions problems should be opened on the repository of the extension.

**Comment by rambod** [comment]
if you run it on windows please do brackets run as admin to fix this problem , i had same problem.

**Comment by corei8** [comment]
I am on Mac and am having the same issue. It seems like a good extension, but could it please be updated??
