### ISSUE TITLE
Contextual menu : paste don't work

### ISSUE THREAD

**Issue by jpdupont** [adobe/brackets#12522]
The keybord work (Cmd C, Cmd V) but if copy work on the contextual menu (Clik Right), Paste don't.
OSX 10.11.5

**Comment by ficristo** [comment]
Brackets doesn't have Copy&Paste as contextual menu.
Do you have an extension that add them? If so, you should file a bug against that extension.

**Comment by busykai** [comment]
As @ficristo explains, Brackets only supports keyboard shortcuts. Please file the issue against the extension which provides the context menu items.
