### ISSUE TITLE
Brackets 1.7 osx not working 

### ISSUE THREAD

**Issue by schroef** [adobe/brackets#12526]
Just tried Brackets 1.7 on OSX 10.11.4 and nothing works. The app opens but is not responding at all, only thing i can do is force quit. Nothing happens when i choose a menu item.

Also GUI is quite empty, not see the a proper file tree

**Comment by nethip** [comment]
Could you delete `cef_data` folder residing under preferences and relaunch the app? This should be under
`~/Library/Application Support/Brackets` on MAC

**Comment by schroef** [comment]
Do i need to make a backup of the preferences and plugins just to make sure?

**Comment by nethip** [comment]
Yes please !

On 15-Jun-2016, at 7:12 PM, schroef <notifications@github.com<mailto:notifications@github.com>> wrote:


Do i need to make a backup of the preferences and plugins just to make sure?

-

**Comment by schroef** [comment]
@nethip 

hi its still not working. Deleted the complete folder
<img width="1440" alt="screen shot 2016-06-15 at 11 58 49 am" src="https://cloud.githubusercontent.com/assets/6923008/16087360/bef37306-32f0-11e6-9932-6d5710cb062c.png">

**Comment by stgwww** [comment]
Same issue. 
Errors:
 Brackets Helper[29851] <Error>: CGAffineTransformInvert: singular matrix.

**Comment by nethip** [comment]
@schroef From the screenshot I see that there are some extensions that are still getting loaded. Could you delete the right preferences folder and try launching Brackets.  I would follow the following steps.

 - Open Finder
 - Invoke the `Go To Folder` dialog using the Cmd+Shift+G. 
 - Paste `~/Library/Application Support/Brackets/`in the input field and click "Go" .
 - That should land you in the right Brackets preferences folder.

@stgwww Could you try the same steps?

**Comment by schroef** [comment]
Sorry for the long wait, but putting in you code with cmd+shift+G actually goes to the usere folder. I the main library there is no bracket app. ive deleted every thing accept the extensions. Still the app freezes up on load

**Comment by schroef** [comment]
OKay when i load this extension, brackets gets stuck

`malas34.brackets-console-plus`

**Comment by Cath-O** [comment]
I had the same issue.

I started by removing cef_data, and the 2x .json files.

After no difference - moved malas34.brackets-console-plus to disabled plugins - Brackets now works.

**Comment by ficristo** [comment]
@schroef can you open an issue on the extension repository?
I'm closing this as extension problem.
