### ISSUE TITLE
request feature: add bookmarks

### ISSUE THREAD

**Issue by gilberto389** [adobe/brackets#12527]
Please, to create a bookmark without keyboard shortcuts

![brahelp](https://cloud.githubusercontent.com/assets/1904029/16058467/4b0606e0-3244-11e6-8081-9d76837b0920.png)

**Comment by petetnt** [comment]
Hi @gilberto389,

there's some Bookmarking extensions for Brackets and at least [this fork](https://github.com/pl86/brackets-bookmarks) of one of the extensions seem to support clicking on the gutter to add and remove bookmarks.

**Comment by gilberto389** [comment]
code folding indicator hides

**Comment by ficristo** [comment]
Closing as a dupe of https://github.com/adobe/brackets/issues/12435
