### ISSUE TITLE
Extract for Brackets not working

### ISSUE THREAD

**Issue by brandl3s** [adobe/brackets#12539]
Hello, suddenly whilst working in Brackets today the extract button doesn't work at all. Here are the errors I've found in the console:

2/lib/graphite-api/public/js/models/AuthModel.js:85 Uncaught TypeError: Cannot read property 'lastIndexOf' of undefined
isAdobeInternalUser: function () {
            var bAdobeInternal = false;
            if (this.user_data) {
                var emailAddress = this.user_data.email;
                var domainIndex = emailAddress.lastIndexOf('@');
                if (domainIndex !== -1) {
                    var domainName = emailAddress.substr(domainIndex + 1);
                    domainName = domainName.toLowerCase();
                    if ((domainName === 'adobe.com') ||
                            (domainName === 'adobetest.com') ||
                            (domainName === '601t.com')) {
                        bAdobeInternal = true;
and

/command/KeyBindingManager.js:749 Cannot assign Shift-Cmd-1 to codefolding.expand.all. It is already assigned to view.togglePanels_addBinding @ /command/KeyBindingManager.js:749
/utils/DeprecationWarning.js:90 Use brackets.getModule("thirdparty/path-utils/path-utils") instead of global PathUtils.
    at Object.defineProperty.get (/brackets.js:137:32)
    at Object.eval (/./utils/TemplateUtil.js:30:33)

if (ignoreGeneric) {
            // explicit command binding overrides this one
            return null;
        }

        if (existing) {
            // do not re-assign a key binding
            console.error("Cannot assign " + normalized + " to " + commandID + ". It is already assigned to " + _keyMap[normalized].commandID);
            return null;
        }

Please help!

**Comment by pridemusvaire** [comment]
Mine stopped working after updating to the latest preview

**Comment by nethip** [comment]
@pridemusvaire  @brandl3s Please refer to this announcement http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/ 

We will not be supporting Extract inside Brackets anymore.

**Comment by pridemusvaire** [comment]
so this means there's no more extract in brackets.
????/
It was a revolutionary plugin that lured me to use brackets.

**Comment by nethip** [comment]
@pridemusvaire It is just that Extract is not supported inside Brackets. Please checkout the extract panel in Dreamweaver CC. You should be able to use Extract service from within Dreamweaver. 

Oh by the way Dreamweaver Beta is out with a complete UI and coding surface overhaul (https://www.adobeprerelease.com). You might want to give it a run. J

**Comment by pridemusvaire** [comment]
Hi Thanks.

 

Will check it  out.

**Comment by brandl3s** [comment]
Seems a shame to remove that feature when the only reason I used brackets was to have extract. Anyway thank you for the answers, I'm moved onto Sublime 👍

**Comment by 4ndv** [comment]
No reason to use Brackets anymore, hello Atom :(

**Comment by ficristo** [comment]
Closing since Extract is deprecated.

**Comment by Mateusz96** [comment]
This killed this editor. Im move into VS Code.

**Comment by jCalderon80** [comment]
Totally sucks, it was a badass feature and just now that I moved from Adobe to Affinity I was gonna try the affinity PSD in brackets to see how it works but instead got the bad news, well still keeping brackets I already got used to it, and I liked that I didn't have to open Photoshop to navigate through my mockups, but I don't mind with Affinity now.

**Comment by SniCel** [comment]
It is pity. It was the best feature. Bye brackets :/

**Comment by klarkc** [comment]
Oh, I just installed Brackets... And uninstalled.

**Comment by mydesireiscoma** [comment]
Just installed brackets to work with PSD on Linux
And uninstalled
Adobe **hates** Linux

IMHO:
Dreamweaver sucks
Brackets without Extract sucks
Photoshop just for get color and size - sucks

**Comment by jCalderon80** [comment]
I uninstalled brackets too, instead I'm using netbeans or visual studio code... since I still can use extract on the web then no need to keep brackets.

**Comment by galban** [comment]
very sad

Hope extract as soon as possible return please

**Comment by jCalderon80** [comment]
Don't think they'll bring it back, they want to push Dreamweaver

**Comment by mydesireiscoma** [comment]
Dreamweaver sucks
