### ISSUE TITLE
How to retrieve mistakenly deleted file from brackets?

### ISSUE THREAD

**Issue by bansalvks** [adobe/brackets#12547]
Instead of `rename` I clicked on `delete` and the file got deleted (without any confirmation).

The file was very important and I need to get it back. please help. Urjent!!

**Comment by redmunds** [comment]
@bansalvks Deleted files should be in your Recycle Bin (aka Trash Can).

**Comment by bansalvks** [comment]
@redmunds many thanks. I am so silly that I did not check the file there.... However a confirmation message could save people a lot of time. is there a setting to activate the confirmation before delete?

**Comment by redmunds** [comment]
Currently no setting for this. This issue is a duplicate of #8651. Closing.
