### ISSUE TITLE
Live Preview for Mozilla Firefox is not working

### ISSUE THREAD

**Issue by kiyokokozui** [adobe/brackets#12541]
I wanted to change its default browser from chrome to mozilla but it doesn't work.
I typed "livedev.multibrowser": true, to brackets.json, but it doesn't seem to work :(

**Comment by Coder206** [comment]
@kiyokokozui I tried running the Live Preview feature with the Experimental option, it ran very well in FireFox 47 and Brackets 1.7.

**Comment by abhijitsahu** [comment]
https://www.youtube.com/watch?v=JgyeFRVUC9E - It should work.Refer it.
