### ISSUE TITLE
Can I use Vivaldi as the browser for live preview?

### ISSUE THREAD

**Issue by lovelyon9kuri** [adobe/brackets#12557]
Can I use Vivaldi as the browser for live preview? Thx.

**Comment by petetnt** [comment]
Live Preview should work with any browser with `livepreview.multibrowser` preference set to true. See [this document](https://github.com/adobe/brackets/wiki/Live-Preview-Multibrowser) for more information.

**Comment by petetnt** [comment]
Closing as answered, feel free to reopen if you cannot get Vivaldi working with Live Preview
