### ISSUE TITLE
Error Getting Update Info when try to check for updates

### ISSUE THREAD

**Issue by SurajVerma** [adobe/brackets#12559]
When I try to check for the updates from help menu in brackets it gives me the below error.

![untitled-1](https://cloud.githubusercontent.com/assets/5441349/16488177/debed146-3eec-11e6-92da-ec81f3ac0683.jpg)
I tried in my 3 different PC's/OS's with brackets installed on them. Below are the configurations.

OS: Windows 7
RAM: 8GB
Hard Disk: 500GB

OS: Windows 10
RAM: 8GB
Hard Disk: 1TB

OS: Ubuntu 14.04/16.04 LTS
RAM: 8GB
Hard Disk: 1TB

Connections used - Wired and wireless broadband (On 2mbps and 20mbps connections).

How to replicate the issue:
**Help > Check for Updates**

**Comment by Dobflem** [comment]
I also have this issue on Ubuntu 14.04. The extension manager is also failing.
![extension failure](https://cloud.githubusercontent.com/assets/7987620/16526861/53dfae64-3fab-11e6-92a9-597d696f315b.png)

**Comment by Dobflem** [comment]
UPDATE:
It seems for the Updating problem the site 'https://getupdates.brackets.io/getupdates/?locale=en&_=1467387426733' is down. This is where Brackets seems to try and pull data from.

As for the extensions problem I get the following error:
Unknown installation error extensionManager domain is undefined

**Comment by jpurviance** [comment]
Is there a timeline for when this will be fixed?

**Comment by nethip** [comment]
@jpurviance I will have a look at what is going wrong with the URL and will keep you updated. @SurajVerma Thanks for reporting and thanks to @Dobflem for providing more information about the issue.

**Comment by Lee4LH** [comment]
Same issue.  I am new and fearful of using anything with instant faults like this.

**Comment by Seius** [comment]
Any news?

**Comment by cjalonso1** [comment]
This behavior started with the last recent update to Brackets.  It’s the
same in my three Mac computers.

On July 7, 2016 at 7:36:57 PM, Lee4LH (notifications@github.com) wrote:

Same issue. I am new and fearful of using anything with instant faults like
this.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/adobe/brackets/issues/12559#issuecomment-231238271>,
or mute
the thread
<https://github.com/notifications/unsubscribe/ALaXwwky5Iivz6icGuqqCxT7fURs_hN1ks5qTY2FgaJpZM4JCHRX>
.

**Comment by nethip** [comment]
@cjalonso1 @Seius @Lee4LH The service seems to be down. We are working on it. Should be fixed by EOD.  I will keep you posted.

**Comment by cjalonso1** [comment]
The problem appears to have been resolved.

Regards,

Carlos 

On July 8, 2016 at 12:00:57 AM, Prashanth Nethi (notifications@github.com) wrote:

@cjalonso1 @Seius @Lee4LH The service seems to be down. We are working on it. Should be fixed by EOD. I will keep you posted.

**Comment by ficristo** [comment]
@SurajVerma are you still experiencing this issue? Linux builds should have been fixed since then.

**Comment by SurajVerma** [comment]
@ficristo Thanks for your response. I wasn't able to check as after Ubuntu 16.04 LTS upgrade, the installer wasn't working for me so I gave up. I will try and update you in a couple of hours.

**Comment by Dobflem** [comment]
@ficristo @SurajVerma This is working on Ubuntu 14.04  and Ubuntu 16.04. I have tested it on my work PC (14.04) and my home Laptop (16.04).

**Comment by SurajVerma** [comment]
@Dobflem Thanks for the confirmation, @ficristo working for me too. Closing the issue. Thanks everyone for help. :)

**Comment by ficristo** [comment]
@SurajVerma @Dobflem thank you to have verified.

**Comment by Hesterien** [comment]
I'm aware that this is an old thread.

I'm having this issue still.
*Unable to check for updates trough 'Help'
![brackets](https://cloud.githubusercontent.com/assets/11635545/21092610/b4dc95c4-c04d-11e6-8d14-9ac9da638b16.png)


Windows 10
Brackets 1.8
Build 1.8.0-17108

**Comment by gamevnlc** [comment]
I have same issue like this 

![image](https://user-images.githubusercontent.com/2215185/30255309-f107d6ac-96cc-11e7-8b73-86e78575f85f.png)

Windows 10
Release 1.8 build 1.8.0-17108
