### ISSUE TITLE
Running "grunt curl-dir" or "grunt curl-dir --force" gives errors

### ISSUE THREAD

**Issue by pratts** [adobe/brackets#12551]
Hello, 
https://github.com/adobe/brackets-shell/wiki/Building-Brackets-Shell and I encountered the errors while executing the tasks "grunt curl-dir".

This is the error I faced : 

prateek@prateek-debian:~/work/open-source/brackets-shell$ grunt curl-dir
Running "curl-dir:cef-linux32" (curl-dir) task
Warning: Fetching "http://s3.amazonaws.com/files.brackets.io/cef/cef_binary_3.2623.1397_linux32_release.zip" failed with HTTP status code 403 Use --force to continue.

Aborted due to warnings.
prateek@prateek-debian:~/work/open-source/brackets-shell$ grunt curl-dir --force
Running "curl-dir:cef-linux32" (curl-dir) task
Warning: Fetching "http://s3.amazonaws.com/files.brackets.io/cef/cef_binary_3.2623.1397_linux32_release.zip" failed with HTTP status code 403 Used --force, continuing.

Running "curl-dir:cef-linux64" (curl-dir) task
Warning: Fetching "http://s3.amazonaws.com/files.brackets.io/cef/cef_binary_3.2623.1397_linux64_release.zip" failed with HTTP status code 403 Used --force, continuing.

While directly opening the url in browser I get the following error:
![screenshot from 2016-06-26 14 30 36](https://cloud.githubusercontent.com/assets/5246231/16361338/be5af23a-3baa-11e6-9412-2bbeaabd8dd2.png)

**Comment by ficristo** [comment]
The linux version of CEF 3.2623 is not uploaded on the Adobe servers.
What I did to try it was:
- download the wanted version of CEF from cefbuilds.com
- convert the archive from 7z to zip and rename it to something like cef_binary_3.2623.1397_linux32_release.zip (now make sure to conserve a copy of it)
- create a folder with name `downloads` at the root of the project and copy inside it the zip.
Now the build will find the CEF and will not attempt to download it.

You will encouter some error when trying to compile since the current linux version is build from the `linux-1547` branch.

**Comment by pratts** [comment]
Thank you for the response @ficristo.

I tried to find the exact version 3.2623.1397 on cefbuilds.com. Closest version number I found was present in the branch_2623 (url : https://cefbuilds.com/#branch_2623) .If the version mentioned in the Gruntfile.js is not mentioned, shouldn't it be modified in the Gruntfile also.

**Comment by ficristo** [comment]
Yes, you have to change the gruntfile to match the version you want to test.
Personally I downloaded the last version of the branch mentioned in the gruntfile and renamed the zip to match the version.
`cef_binary_3.2623.1399.g64e2fe1_linux64.7z` --> `cef_binary_3.2623.1397_linux64_release.zip`

**Comment by pratts** [comment]
Thank you @ficristo . I did the same and now running the command grunt gives me the following error : 
prateek@prateek-debian:~/work/open-source/brackets-shell$ grunt
Running "cef" task

Running "cef-clean" task

Running "cef-extract" task

Running "cef-symlinks" task
>> Error: EEXIST, symlink 'deps/cef/Debug'
Warning: Task "cef-symlinks" failed. Use --force to continue.

Aborted due to warnings.
Unhandled rejected promise: Error: EEXIST, symlink 'deps/cef/include'
From previous event:
    at /home/prateek/work/open-source/brackets-shell/node_modules/q/q.js:1395:24
    at /home/prateek/work/open-source/brackets-shell/tasks/setup.js:61:20
    at /home/prateek/work/open-source/brackets-shell/tasks/setup.js:315:28
    at Array.forEach (native)
    at Object.<anonymous> (/home/prateek/work/open-source/brackets-shell/tasks/setup.js:310:34)
    at Object.thisTask.fn (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/grunt/task.js:78:16)
    at Object.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:282:30)
    at Task.runTaskFn (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:235:24)
    at Task.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:281:12)
    at Task.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:215:7)
Unhandled rejected promise: Error: EEXIST, symlink 'deps/cef/libcef_dll'
From previous event:
    at /home/prateek/work/open-source/brackets-shell/node_modules/q/q.js:1395:24
    at /home/prateek/work/open-source/brackets-shell/tasks/setup.js:61:20
    at /home/prateek/work/open-source/brackets-shell/tasks/setup.js:315:28
    at Array.forEach (native)
    at Object.<anonymous> (/home/prateek/work/open-source/brackets-shell/tasks/setup.js:310:34)
    at Object.thisTask.fn (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/grunt/task.js:78:16)
    at Object.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:282:30)
    at Task.runTaskFn (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:235:24)
    at Task.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:281:12)
    at Task.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:215:7)
Unhandled rejected promise: Error: EEXIST, symlink 'deps/cef/Release'
From previous event:
    at /home/prateek/work/open-source/brackets-shell/node_modules/q/q.js:1395:24
    at /home/prateek/work/open-source/brackets-shell/tasks/setup.js:61:20
    at /home/prateek/work/open-source/brackets-shell/tasks/setup.js:315:28
    at Array.forEach (native)
    at Object.<anonymous> (/home/prateek/work/open-source/brackets-shell/tasks/setup.js:310:34)
    at Object.thisTask.fn (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/grunt/task.js:78:16)
    at Object.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:282:30)
    at Task.runTaskFn (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:235:24)
    at Task.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:281:12)
    at Task.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:215:7)
Unhandled rejected promise: Error: EEXIST, symlink 'deps/cef/Resources'
From previous event:
    at /home/prateek/work/open-source/brackets-shell/node_modules/q/q.js:1395:24
    at /home/prateek/work/open-source/brackets-shell/tasks/setup.js:61:20
    at /home/prateek/work/open-source/brackets-shell/tasks/setup.js:315:28
    at Array.forEach (native)
    at Object.<anonymous> (/home/prateek/work/open-source/brackets-shell/tasks/setup.js:310:34)
    at Object.thisTask.fn (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/grunt/task.js:78:16)
    at Object.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:282:30)
    at Task.runTaskFn (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:235:24)
    at Task.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:281:12)
    at Task.<anonymous> (/home/prateek/work/open-source/brackets-shell/node_modules/grunt/lib/util/task.js:215:7)


When I run the same command second time, it works fine but I get a new error : 
prateek@prateek-debian:~/work/open-source/brackets-shell$ grunt
Running "cef" task

Running "node" task

Running "node-clean" task

Running "node-mac" task

Running "create-project" task
Building project files

Running "build" task

Running "build-linux" task
>> make: * No rule to make target 'out/Release/obj.target/libcef_dll_wrapper/libcef_dll/ctocpp/test/translator_test_ctocpp.o', needed by 'out/Release/obj.target/libcef_dll_wrapper.a'.  Stop.
Warning: Task "build-linux" failed. Use --force to continue.

Aborted due to warnings.


Is it fine if I mention this error in this conversation or should I raise a new issue ?

**Comment by ficristo** [comment]
I don't know what is your first issue, maybe some previous partial build.
The second is this https://github.com/adobe/brackets-shell/pull/562 and still don't know what it is...

**Comment by pratts** [comment]
Thank you for the help, @ficristo .

I used the change you submitted in your PR and tried to build, and I am still getting errors.

prateek@prateek-debian:~/work/open-source/brackets-shell$ grunt build
Running "build" task

Running "build-linux" task
>> In file included from appshell/command_callbacks.h:4:0,
>>                  from appshell/client_handler.h:14,
>>                  from appshell/appshell_extensions.h:27,
>>                  from appshell/appshell_extensions.cpp:24:
>> appshell/appshell_extensions_platform.h: In function ‘void* getMenuParent(CefRefPtr<CefBrowser>)’:
>> appshell/appshell_extensions_platform.h:74:57: error: ‘GTK_WIDGET’ was not declared in this scope
>>          GTK_WIDGET(browser->GetHost()->GetWindowHandle()),
>>                                                          ^
>> appshell/appshell_extensions_platform.h:75:9: error: ‘GTK_TYPE_VBOX’ was not declared in this scope
>>          GTK_TYPE_VBOX);
>>          ^
>> appshell/appshell_extensions_platform.h:75:22: error: ‘gtk_widget_get_ancestor’ was not declared in this scope
>>          GTK_TYPE_VBOX);
>>                       ^
>> make: * [out/Release/obj.target/Brackets/appshell/appshell_extensions.o] Error 1
Warning: Task "build-linux" failed. Use --force to continue.

Aborted due to warnings.
I am on master branch and I have modified the cef version from 3.2623.1397 to 3.2623.1399.

I searched the error mentioned above in the existing issues and found #10231 . Ingorichter mentioned branches linux-1547 and jasonsj/cef_2171_linux, that contain the fix for the issue. 

Issue I am getting for the while running grunt build for both the branches is : 
prateek@prateek-debian:~/work/open-source/brackets-shell$ grunt build
Running "build" task

Running "build-linux" task
>> g++: error: libcef_dll/transfer_util.cc: No such file or directory
>> g++: fatal error: no input files
>> compilation terminated.
>> make: * [out/Release/obj.target/libcef_dll_wrapper/libcef_dll/transfer_util.o] Error 4
Warning: Task "build-linux" failed. Use --force to continue.

Aborted due to warnings.

**Comment by ficristo** [comment]
As I said previously, If you are building the master branch of the shell on linux, errors are expected.
If you want to update the CEF version to the newest, (which would be great!), you have to overcome all the errors.
In this particular case I think you miss an `#include <gtk/gtk.h>` in appshell_extensions at line 71.

The second problem seems to me an error on a partial build.
If you look at appshell_path.gypi on master you have `libcef_dll/transfer_util.cc`, 
on linux-1547 you have `libcef_dll/transfer_util.cpp`: note the extension.
So I think you are building with the wrong CEF version.

You can try something like `sudo git clean -xdf` which will delete all the files not versioned.
(Make sure to backup eventual important files for you)
Personally I use it so I'm sure I'm compiling with the correct code.

**Comment by ficristo** [comment]
@pratts if you have any other question you can open a new issue or maybe join us on slack.
For now I close this.

**Comment by joepie91** [comment]
This ticket is closed, but the issue still remains - the URL is still causing a 403, despite being part of Brackets' buildscripts. I'm building from the `1.7` release, not `master`, so this is definitely something that still needs fixing.

Perhaps this can be reopened?

**Comment by ficristo** [comment]
To be able to compile `master` on Linux is the first step to be able to move on a newer version of CEF.
While it still says CEF 2171, https://github.com/adobe/brackets/issues/11047 is tracking the update.
That's why I don't see a reason to reopen this.

If you want to compile 1.7 for Linux you still have to use the `linux-1547` branch.

If you instead want to try to update Linux shell to use a newer version of CEF, using the default scripts, we could ask @nethip to upload the linux version of CEF on the Adobe servers.

**Comment by joepie91** [comment]
I've been trying to compile from the [`release-1.7` branch](https://github.com/adobe/brackets-shell/tree/release-1.7) though, not `master`. Why doesn't the `release-1.7` branch point at the version of CEF that's actually used for 1.7? Is this a Linux-specific thing?

**Comment by ficristo** [comment]
Yes, it's Linux specific.
@nethip I think it would be nice to have tag/branch for Linux releases too.
