### ISSUE TITLE
Ensure final new line in file

### ISSUE THREAD

**Issue by rovf** [adobe/brackets#12565]
It would be great to have an option which makes Brackets add a new line at the end of the file (if there is none yet).

**Comment by petetnt** [comment]
Hi @rovf,

there's various extensions, such as the great [whitespace normalizer](https://github.com/dsbonev/whitespace-normalizer) that provide this feature. You can search and install extensions under `File -> Extension Manager`.

**Comment by rovf** [comment]
Thank you.
