### ISSUE TITLE
Brackets in other languages

### ISSUE THREAD

**Issue by rovf** [adobe/brackets#12566]
When I downloaded and installed Brackets (on Windows 7), it came up with a German user interface (probably because the IP address of the computer which downloaded the installation file, is hosted under the .de TLD). It would be great to have the option to switch the language (for instance, to English).

**Comment by petetnt** [comment]
Hi @rovf,

you can switch Brackets languages under `Debug -> Switch Language` to any of the languages [provided by Brackets](https://github.com/adobe/brackets/tree/master/src/nls)!

**Comment by rovf** [comment]
Thank you!
