### ISSUE TITLE
Brackets freezes on startup v1.7

### ISSUE THREAD

**Issue by thrash646** [adobe/brackets#12570]
I am having the same issues as others and I can't figure out how to fix it. 
I disabled dev tools and then re-enabled them. The next time I used brackets, it just froze. 
Tried re-installing 1.5 and then upgraded to 1.7 and still the issue persists.

I'm new to dev world so I don't know about crash reports and stuff.

Windows 8.1 64bit
16Gb Ram
Intel i7 quad core 2.6GHz

Any help would be greatly appreciated. I don't want to switch editors again.

**Comment by thrash646** [comment]
Even though the #9011 thread was NO help, and no one came to help me here, I fixed the issue.

**Comment by ficristo** [comment]
Hi @thrash646, can you share how you solved your issue?
Maybe other people will have your same problem, so they can find a solution.

**Comment by thrash646** [comment]
Good point. I always get frustrated when people solve the issue without reporting how they did it. I was just frustrated at the lack of help I was given so I left in a huff.

Solution:
1)  Manually disabled ALL of the extensions by moving them from the USERS folder to the DISABLED folder. (see: https://github.com/adobe/brackets/wiki/Extension-Locations for help)
2) Restart Brackets and re-enable all the extensions.

That's it. 
For some reason clicking on "restart with extensions disabled" didn't work because it froze immediately so this was my only solution.

**Comment by ficristo** [comment]
@thrash646 thank you.

**Comment by mkoo** [comment]
(noting for reference) Manual disabling of extensions works with the same freezing up issue on later versions of Brackets v1.9
