### ISSUE TITLE
How can I change the editor font

### ISSUE THREAD

**Issue by boosters** [adobe/brackets#12576]
I am using Windows and want to change the editor font, but the view-themes option does not work. My font is already installed on Windows as I can use on other IDE. My font name is Monaco, how can I change it?

Screenshot - http://prntscr.com/bpmynl

**Comment by petetnt** [comment]
Hi @boosters,

the font-family name should probably be quoted, such as `'Monaco-Bold'`.

**Comment by boosters** [comment]
@petetnt , I tried that way too but still not working. Original font name - Monaco-Regular
