### ISSUE TITLE
Font setting ignored

### ISSUE THREAD

**Issue by rovf** [adobe/brackets#12578]
Brackets shows the text in the edit pane in a proportional font. For editing program files, I prefer a fixed font width.

I checked out the settings for View/Preferences/Editor, and found the following Font Family settings:

'SourceCodePro-Medium', MS ????, 'MS Gothic', monospace

(actually, what is shown in this post as a sequence of 4 question marks, displayed in the settings dialogue as the Japanese word "goshiku", i.e. "gothic", spelled in Katakana)

I changed this setting to 

"Courier New", Courier,'SourceCodePro-Medium', MS ????, 'MS Gothic', monospace

but although I do of course have Courier New installed on my PC, the font doesn't change - still proportional.

Brackets.io 1.7 running on 64-bit Windows 7.

**Comment by petetnt** [comment]
That should work. Maybe try changing the double quotes (") to single quotes (') if for one reason or another that causes some issues.

**Comment by rovf** [comment]
No, did not work, but I think I found the culprit. Actually, there are two, both extensions:

The first is Brackets Pryme Theme. If I enable only this extension, and choose this theme, my font setting will be ignored, but when I switch back to the original theme (brackets default), I get my font setting honored.

Things get interesting when I enable a second extension, Code Font. If this one is enabled too, I don't get non-proportional fonts even in the default theme.

Now I wanted to know what happens when I have Code Font enabled, but Pryme disabled. Interestingly, at this point I could not disable Pryme anymore (Brackets refused this). I could however remove it. I didn't go into detail for researching *this*, but at least I could find that with Pryme disabled and Code Font enabled, the fonts are proportional again.

As a summary, my conclusion: 

While the Brackets Pryme Theme has the bug that it doesn't accept my font settings, this is a minor problem, because it doesn't interfere with other themes. However,Code Font really blows things up.

My solution is to remove both Pryme and Code Font.

**Comment by chenryhen** [comment]
I'm getting this problem too with 1.7 for Mac. No matter what I do, the font stays the same, even after removing all of my extensions. What's weird is that I have the same theme, same font, on a different Mac, and I'm having no problems there.

**Comment by ficristo** [comment]
Closing as extension problem.
