### ISSUE TITLE
Debian 8.5 installation problem

### ISSUE THREAD

**Issue by MohebYarahmadi** [adobe/brackets#12575]
**Hi. when I try to install brackets on linux debian 8.5 it doesn't work and I can't install it.** 

`hanzo@debian:~/Downloads$ sudo dpkg -i Brackets.Release.1.7.64-bit.deb 
[sudo] password for hanzo: 
dpkg: error: dpkg status database is locked by another process
hanzo@debian:~/Downloads$ sudo dpkg -i Brackets.Release.1.7.64-bit.deb 
Selecting previously unselected package brackets.
(Reading database ... 217805 files and directories currently installed.)
Preparing to unpack Brackets.Release.1.7.64-bit.deb ...
Unpacking brackets (1.7.0-16898) ...
dpkg: dependency problems prevent configuration of brackets:
 brackets depends on libgcrypt11 (>= 1.4.5); however:
  Package libgcrypt11 is not installed.

dpkg: error processing package brackets (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.13-1) ...
Errors were encountered while processing:
 brackets
`

**Comment by pratts** [comment]
Hello @mohammadyaghobi 
Brackets depends on libgcrypt11 library but libgcrypt20 is installed on debian 8.5 by default. 
You can check these comments to get libgcrypt11 for debian 8.5 https://github.com/adobe/brackets/issues/10255#issuecomment-89624539 or http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/libg/libgcrypt11/


The actual reason behind the issue you are facing is discussed in issue #10255 

Regards,
Prateek

**Comment by ficristo** [comment]
@pratts thank you for have answered.
We are tracking the problem on #10255.
Closing as duplicate
