### ISSUE TITLE
Live Preview Base URL is not recognized

### ISSUE THREAD

**Issue by jadgsam** [adobe/brackets#12573]
Hello,
Currently I cannot open php files using Live Preview from my Mac using Safari only as browser and web server apache the one that comes with the MacBook Pro.

I opened the folder from menu File=>Open Folder, as a result I can see html and php files. A html file can be opened by using the live preview option in the side bar. However when I try to run any php file I am asked to provide a Live Preview Base URL. Once I provide this base URL in my case http://localhost/~jadsam/pagosweb/prueba/, it is not recognized. However in my browser http://localhost/~jadsam/pagosweb/prueba/test.php works without any problem. I have tried other combinations just to test http://localhost/~jadsam/pagosweb/ or http://localhost/~jadsam/ or http://localhost/ but none of them are recognised as valid Urls. 

Any support will be much appreciated

**Comment by redmunds** [comment]
Did you try `localhost/~jadsam/pagosweb/prueba/` (without http://) ?

**Comment by jadgsam** [comment]
Hi redmunds yes I tried different combinations including this "without http://"  but it didn't work. I had to install Chrome and now it works but my idea was not to install another browser. So far and as a conclusion I was not able to workaround this issue without installing Chrome and keep Safari only.

**Comment by redmunds** [comment]
Live Preview Base URL functionality is only supported for standard (not experimental) Live Preview so Chrome is a requirement. Closing.
