### ISSUE TITLE
unable to run Brackets on centos6/redhat6

### ISSUE THREAD

**Issue by manish-agnisys** [adobe/brackets#12581]
I was unable to run brackets on my centos6.5 machine. I got the following errors

/usr/bin/brackets: /lib64/libc.so.6: version GLIBC_2.14′ not found (required by /usr/bin/brackets)
/usr/bin/brackets: /lib64/libc.so.6: version GLIBC_2.14? not found (required by /opt/brackets/lib/libcef.so)
/usr/bin/brackets: /lib64/libc.so.6: version GLIBC_2.15′ not found (required by /opt/brackets/lib/libcef.so)
/usr/bin/brackets: /usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.15? not found (required by /opt/brackets/lib/libcef.so)

**Comment by ficristo** [comment]
I think you don't have the required libs installed.
Have you tryed what mentioned in [here](https://github.com/adobe/brackets/issues/4816#issuecomment-67396919)?
It seems you have to update `glibc`.

**Comment by ficristo** [comment]
Closing as duplicate.
