### ISSUE TITLE
Google

### ISSUE THREAD

**Issue by Lee4LH** [adobe/brackets#12583]
Google and advertising (order uncertain) have ruined the internet.  I and many others who have been internet users since 1982 (or thereabouts) do the best we can to keep Google off of our computers. Then I download brackets and it opens with Google Chrome -- good fast way to anger we Google haters. You would do better to dissassociate github from Google.  -- Lee

**Comment by ImAnnoying** [comment]
IIRC, you can enable Experimental Live Preview and have it work with other browsers like Firefox

**Comment by SamKeightley** [comment]
I'm curious, why the hate for Google? I love what they doXD Also I'd like to recommend atom as a text editor as well:)

**Comment by ficristo** [comment]
There is the Experimental Live Preview which will open your default browser.
If you have any trouble with it please open a new issue.
