### ISSUE TITLE
Indexing Error "Your solution has more than 30,000 files" but it does not

### ISSUE THREAD

**Issue by Metrophobe** [adobe/brackets#12586]
I started getting this weird error yesterday and did nothing to cause this issue. I would load the project (using context menu or even from inside brackets), and I would get the error that states that my solution exceeds the 30,000 files.  I am AWARE that there was such an issue before, however in this situation the "indexing error" is not being caused by the amount of files. I checked the solution, there are no shortcuts and physically there are 1,900 files. Solution size is 150MB. I uninstalled and reinstalled and also tried running Brackets without extensions to see if any extensions are causing this.  No change.

**Comment by petetnt** [comment]
Try renaming (/deleting) your application data folders too if the issue persist. They are under `%AppData%/Brackets` on Windows and `~/Library/Application Support/Brackets` on MacOS

**Comment by Metrophobe** [comment]
I think it was not clear from the post but I had done that. When I uninstalled the app I actually found  all folders named brackets in appdata and removed them. Still no joy! I realised that for some odd reason when I select to open a folder and use it as project. It loses "focus" and diverts to opening all of the desktop and all of the folders and drives. (because I saw onedrive in there and homegroups etc).  I am clearly selecting the folder and am doing nothing different.

**Comment by tr-rmit** [comment]
I just solved my "300,000+ files in root directory lockup error" by deleting this file (macOS):
~/Library/Application Support/Brackets/state.json
Then ForceQuit & restart Brackets

**Comment by MrADeveci** [comment]
Thanks @tr-rmit this solved my issue!

**Comment by MrADeveci** [comment]
> I just solved my "300,000+ files in root directory lockup error" by deleting this file (macOS):
> ~/Library/Application Support/Brackets/state.json
> Then ForceQuit & restart Brackets

Thanks @tr-rmit this solved my issue!
