### ISSUE TITLE
Almost nothing is working when updated to 1.7

### ISSUE THREAD

**Issue by mcmyt** [adobe/brackets#12595]
Hello,

I've just updated brackets to 1.7 and almost nothing is working, I can't open folders (The window to select one doesn't even appear), I don't have the folders I'm used to work on anymore on the left, the popup doesn't open when clicking on the plugins icon etc... really nothing is working. I'm stuck and have some urgent work to finish.

![180aa0454d83e25ebc5b84744ab7d7e5](https://cloud.githubusercontent.com/assets/623186/16901184/2034c816-4c34-11e6-8046-6566f3a872e4.gif)

Thank you.

**Comment by nethip** [comment]
@mcmyt You could try deleting `cef_data` folder. this would be present at `~/Library/Application Content/Brackets/cef_data` . Relaunch Brackets app.

**Comment by paulrevival** [comment]
I have the same problem both on linux (ubuntu 16.04 64bit) and win 10 64bit. Deleting cef_data folder does nothing :(

**Comment by ficristo** [comment]
You could try to move all your extensions under the `disabled` folder to see if it is an extension problem.
Mac: `~/Library/Application Support/Brackets/extensions/disabled`
Win: `C:\Users\<user>\AppData\Roaming\Brackets\extensions\disabled`
Linux: `~/.config/brackets/extensions/disabled`

**Comment by ficristo** [comment]
If you still have the problem, please add more details and then reopen.
