### ISSUE TITLE
Quick Edit panels too long

### ISSUE THREAD

**Issue by vsmith72** [adobe/brackets#12597]
I noticed with the latest version of Brackets (1.7) the quick edit panel is very long.
![capture](https://cloud.githubusercontent.com/assets/19600175/16904321/7ac935b4-4c48-11e6-9c78-b6a3a2a007f8.PNG)

**Comment by nethip** [comment]
@vsmith72 This change may not be specific to 1.7. Are you seeing the same after restarting Brackets and doing a QE ?

**Comment by vsmith72** [comment]
Yes I still get it after restarting brackets.  I use WE all the time and it only stared doing this after I installed 1.7

**Comment by vsmith72** [comment]
It was Overscroll that caused the issue [https://github.com/Emmeran/brackets-overscroll](url)

**Comment by ficristo** [comment]
@vsmith72 can you open an issue on the extension repository?
Closing as extension problem.
