### ISSUE TITLE
post processor signature  problem

### ISSUE THREAD

**Issue by Isaac2k1** [adobe/brackets#12599]
By using Brackets, called from Fusion360 I get following error message:

Information: Configuration: Generic Burny Plasma (WADR)
Information: Vendor: Lincoln Electric
Information: Posting intermediate data to 'I:\HG\Lab\10 MA Ordner\Mailand\ACAD\11.cnc'
Error: Failed to post process. See below for details.
...
Code page changed to '1252  (ANSI - Latin I)'
Start time: Monday, July 18, 2016 7:03:38 AM
Loading locale from 'C:\Users\chmamai\AppData\Local\Autodesk\webdeploy\production\00acb530044182955dd92b716af43e78c7229309\Applications\CAM360\Data\Posts\common.de.lang'
Code page changed to '20127 (US-ASCII)'
Post processor engine: 4.2.1 40927
Configuration path: C:\Users\chmamai\AppData\Local\Autodesk\webdeploy\production\00acb530044182955dd92b716af43e78c7229309\Applications\CAM360\Data\Posts\burny_plasma.cps
Include paths: C:\Users\chmamai\AppData\Local\Autodesk\webdeploy\production\00acb530044182955dd92b716af43e78c7229309\Applications\CAM360\Data\Posts
Configuration modification date: Thursday, June 02, 2016 7:33:36 PM
Output path: I:\HG\Lab\10 MA Ordner\Mailand\ACAD\11.cnc
Checksum of intermediate NC data: caff405652c3dde24629c359d3b9d850
Checksum of configuration: af258187ad9b5ef7633abb474bf7c289
Vendor url: http://www.burny.com
Legal: Copyright (C) 2012-2016 by Autodesk, Inc.
Post processor signature could not be verified (error 0xfffffffc).
Erzeugt von: Fusion 360 CAM 2.0.2139
...
Error: The CNC does not support the required tool/process. Only plasma cutting is supported.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Failed to invoke function 'onSection'.
Error: Failed to invoke 'onSection' in the post configuration.
Error: Failed to execute configuration.
Stop time: Monday, July 18, 2016 7:03:38 AM
Post processing failed.

**Comment by abose** [comment]
Can you give more details on what exactly the problem is? Contributors to the brackets projects may not know about fusion360/prost processing things. A write-up detailing the issue could help us in understanding the issue.

**Comment by ficristo** [comment]
If you still have the problem, please add more details and then reopen.
