### ISSUE TITLE
Live preview not working for HTML

### ISSUE THREAD

**Issue by Justin-Turner-Overdrive** [adobe/brackets#12594]
Went through your troubleshooting guide. Html file is in working set. There are no syntax errors in code. CSS live is working perfectly. Reload without extension makes no difference. Restarting brackets and chrome makes no difference. Tried a different project, same results. Not running my own server, just stock live preview setup for projects living on my desktop.

Brackets Release 1.7 build 1.7.0-16898 (release-b0a363b71) _(up to date)_
Chrome Version 51.0.2704.106 (64-bit) _(up to date)_

[https://gfycat.com/EmotionalBreakableAfricanwildcat](https://gfycat.com/EmotionalBreakableAfricanwildcat
)

The above video show me editing the same element in both CSS and HTML. In CSS I change the width, which works. In HTML, I delete a section of text inside that element without upsetting any tags, which doesn't work.

**Comment by Justin-Turner-Overdrive** [comment]
Also, _Live Preview Highlight_ is not working for me in html code. Works fine in CSS.

**Comment by Justin-Turner-Overdrive** [comment]
One (hopefully) final note... I tried bringing up dev tools in the debug menu (to see console errors), but nothing opens when I select Debug→Show Developer Tools. Same for keyboard shortcut. Tried restarting, but Brackets won't quit normally. Takes a force quit to kill it.

**Comment by redmunds** [comment]
JTO (@Justin-Turner-Overdrive), what is the file extension of your HTML doc? Brackets only recognizes "htm", "html", and "xhtml" as static HTML files.

**Comment by Justin-Turner-Overdrive** [comment]
It's .html

I also tested an older project, same results.

**Comment by redmunds** [comment]
@Justin-Turner-Overdrive 

> Html file is in working set

File needs to be in project tree, so make sure _File > Open Folder_ selects folder that contains all of your project files.

Not sure what else it could be. Did you try _File > Enable Experimental Live Preview_ ? That will open in page in your default browser, and then you can copy/paste url to any other browser and see edits in multiple browsers at once.

**Comment by Justin-Turner-Overdrive** [comment]
html and css are both in the project tree, both in working set on a horizontal split. I included a video in my first post that shows the folder hierarchy... pretty standard stuff— html in root of project folder, css and images and js in their own folders.

I've tried both experimental (which chrome and safari), and regular (chrome obvs), no differences in behavior.

I suppose I'll try a fresh install. Just wanted to be sure it wasn't something obvious, since I'm fairly new to web dev.

**Comment by Justin-Turner-Overdrive** [comment]
I figured this out, and it was my own fault.

Like I said, I'm new... and have been doing all my studying in CodePen for the past year. So I got in the habit of not typing <html></html> elements. Somehow Chrome was still displaying my local projects just fine without them, so I never noticed.

Adding the <html> elements to all my projects fixed this issue.

**Comment by kimberleyrode** [comment]
I'm experiencing this same problem. But I do have html included... So I don't think it could be that. 

I'm extremely new to this, it's only the second project I've tried to build.

**Comment by blind0x** [comment]
For everyone, this problem can be resolved by following steps:- 

1. On menu bar, go to  File --> Open Folder (folder which have your html file for live preview)

2. Select Folder

3. Select your html file from left side bar for live preview

4. Click on bolt icon on right (preview button) 

All it melts down to the fact, that you need that folder(which have your file) selected to view your output in live preview. 
Let me know, if it helps someone. :)
