### ISSUE TITLE
Nested folders won't open in v1.7

### ISSUE THREAD

**Issue by paddy1228** [adobe/brackets#12591]
On clicking a nested folder, it closes the parent folder. Renaming also doesn't work.

**Comment by busykai** [comment]
@paddy1228, does the #10574 sound like the issue you're seeing? Basically, right now you need to click on the name of the nested folder to close/open it. Clicking on the area left to it will result in collapsing the parent folder. Is this what you're seeing?

**Comment by ficristo** [comment]
#10574 should be fixed in 1.8.
If that is not the problem you were seeing please reopen.
