### ISSUE TITLE
File delete needs confirmation

### ISSUE THREAD

**Issue by VanagaS** [adobe/brackets#12600]
When right clicking on a file and selecting delete, it doesn't ask for a confirmation and just deletes the file. Quite dangerous!

**Comment by ficristo** [comment]
The deleted file should be in the Recycle Bin.
That said there is a pending PR: https://github.com/adobe/brackets/pull/10258

**Comment by abose** [comment]
Should be fixed in the next release thanks to @MarcelGerber .Closing as fixed.
