### ISSUE TITLE
Brackets!!

### ISSUE THREAD

**Issue by Adriano87** [adobe/brackets#12601]
Olá boa noite,eu gostaria que o editor Brackets fosse multi browsers,ou seja a renderização deveria ser para todos os navegadores modernos.

**Comment by petetnt** [comment]
Hi @Adriano87,

if I understood you correctly (through Google Translate), you can already use the Live Preview feature in Brackets with any browser. 

> It (Multibrowser live preview) can be enabled by setting livedev.multibrowser preference to true. If enabled, it will launch the page in your default browser when clicking on the Live Preview icon as it works today. You should then also be able to copy and paste the URL from that browser into any other browser, live edits will then update all connected browsers at once.

**Comment by abose** [comment]
Closing as answered. Please feel free to reopen this if you issue is not resolved.
