### ISSUE TITLE
Brackets on RaspberryPi ?

### ISSUE THREAD

**Issue by Lulucmy** [adobe/brackets#12603]
Hello,

I'm using a Raspberry Pi 3 but I can't install Brackets  because  I have armhf and Brackets only works  with 64-bit and 32-bit... Is there an other release for armhf ?

Thanks :)

**Comment by ficristo** [comment]
If you search other ARM issues, it seems to me that is not supported.
So I think you are pretty much on your own.
If you want to take a look to hack the [bracket-shell](https://github.com/adobe/brackets-shell)...

**Comment by abose** [comment]
Brackets do not officially support ARM-based environments. Chromium seems to be available for  RPi. This should make it technically possible to port brackets-shell to ARM. But it would require significant effort. Closing as answered.
