### ISSUE TITLE
Problems with compilation

### ISSUE THREAD

**Issue by KorvinAmber** [adobe/brackets#12604]
Problems with the compilation of the less in css.
LESS AutoCompile plugin installed.
// Out: ../style.css, compress: true, it is written. However, the compilation does not work.
How to fix?
![screenshot_3](https://cloud.githubusercontent.com/assets/20553307/16979037/aaba9c6a-4e67-11e6-969b-ed715ab0ffeb.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/20553307/16979036/aabaa0fc-4e67-11e6-93f1-2548466a171d.png)

**Comment by ficristo** [comment]
Have you looked at `Debug \ Show developer tools` to see if there is any error?

PS: it would be better to file extension problems on extension repo.

**Comment by abose** [comment]
As brackets-less-autocompile is an extension, we can do little about fixing the issue. Please log an issue in the extension repo at [https://github.com/jdiehl/brackets-less-autocompile](https://github.com/jdiehl/brackets-less-autocompile). 
Closing as extension problem.
