### ISSUE TITLE
Extract for Brackets to work with Experience Design

### ISSUE THREAD

**Issue by janukawijesinghe** [adobe/brackets#12602]
Brackets Code Editor has good integration with PSD Files, which allows it to grab layers, colors, font details and spacing info. More on that here (https://helpx.adobe.com/creative-cloud/help/extract-for-brackets.html) 
I wonder whether you can work on features that allow Adobe Extract to grab data(images, font names, sizing info etc) from XD and transfer for Brackets, the same way it happens to PSD ?

**Comment by abose** [comment]
Thanks for logging this new feature request. Extract service is now discontinued in brackets. 
[http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/ ](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/)
Closing.
