### ISSUE TITLE
Automatic close braces issue?

### ISSUE THREAD

**Issue by animationfund2** [adobe/brackets#12619]
Is there a way for Brackets not to end a code? For example: &lt;ul&gt;&lt;li&gt;&lt;/li&gt;&lt;/ul&gt;. It automatically adds in &lt;/li&gt;&lt;/ul&gt; I saw the option Edit >> Auto Close Braces. I have that option off and unfortunately it still automatically adds the end part of the code. Is there any way to fix this? Thanks!

**Comment by RaymondLim** [comment]
@animationfund2 That is not for close tag options. You need to update your preferences by selecting Debug > Open Preferences File. Then copy the close tag preferences from the defaultPreferences.json to your preference file and make some necessary changes.

**Comment by animationfund2** [comment]
Thanks for the help!
