### ISSUE TITLE
Right-clicking Bugged.

### ISSUE THREAD

**Issue by theosanthropos** [adobe/brackets#12614]
Release 1.7 experimental build 1.7.0-16898 (release b0a363b71) 
build timestamp: Wed Jun 15 2016 10:33:42 GMT+0000

Ubuntu 16.04 LTS, 64bit.

Bugged Feature: Right-click function.

Description of Bug:

When loading various documents into horizontal, split views, the right-click function becomes unresponsive. Other than reloading Brackets, the only working solution seems to be selecting a document from the document tree, then back into the editor pane corresponding to the document being edited.

**Comment by petetnt** [comment]
Hi @theosanthropos,

when this occurs, do you see any errors in the DevTools (Debug -> Show Developer Tools)?

**Comment by ficristo** [comment]
Closing since there was no answer.
If you still have problems, please, open a new issue.
