### ISSUE TITLE
Title files in top bar

### ISSUE THREAD

**Issue by greieras** [adobe/brackets#12610]
I wish to have brackets file open , separately in top bar, as notepad or sublime have them. How can I do that?

**Comment by ficristo** [comment]
If you mean tabs, Brackets doesn't support them.
However you can try to install an extension. For example https://github.com/DH3ALEJANDRO/custom-work-for-brackets

**Comment by greieras** [comment]
YES TABS ,sorry I didn't know exactly how to name those features, well
then, is ok, I will try to install this plugin, but the problem really was
like, when I have many files opened, let's say more then 5, that panel from
the left, above the project explorer become scrollable and all the time I
have to scroll down and up for specific file, which I work at. That's all.
Thank you.

**Comment by ficristo** [comment]
Oh, I think you will have a similar problem also with that plugin...
Alternatively, have you tryed `Navigate \ Quick Open`? You can write the name of the file you are looking for.

**Comment by abose** [comment]
Closing as this was a conscious UX design for brackets.
