### ISSUE TITLE
Live Preview Only Showing 'Getting Started'

### ISSUE THREAD

**Issue by HannahHam08** [adobe/brackets#12632]
Currently I'm trying to use the Live Preview function and it is not working correctly.

I'm in my project that I want to view, and have done the usual 'File' -> 'Open Folder' to set it as the current folder, but still it only shows the 'Getting Started' file.
I'm not sure what to do to fix this.

**Comment by markljackson** [comment]
Have you selected a FILE to preview, or just the folder?

**Comment by HannahHam08** [comment]
I do not know how to do that.
Clicking on the live preview button doesn't generate a drop down menu at all?

**Comment by ficristo** [comment]
@HannahHam08 if you click on the LivePreview button on the right sidebar, it should open Chrome with the html you selected to view. 
If you enabled the experimental LivePreview it should open your default browser.

So, you cannot switch projects? Is your first time using Brackets?
Can you look at https://github.com/adobe/brackets/wiki/Troubleshooting to see if there is anything that can help?

**Comment by HannahHam08** [comment]
Thank you, it seems to have fixed itself. 
I reinstalled the program and it seems to be working fine now.

Thank you
