### ISSUE TITLE
Faulty highlighting when line numbers are not enabled

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#12630]
![image](https://cloud.githubusercontent.com/assets/7641760/17253036/a436b00c-55b7-11e6-87bb-05eb2ebd3657.png)

When I was trying to address this comment on the indent wrapping hack PR https://github.com/adobe/brackets/pull/12110#issuecomment-228483676 I noticed that the faulty highlighting isn't due to the indent wrapping hack. 

Never noticed this before because I never have line numbers off.

**Comment by RaymondLim** [comment]
@petetnt I found out that just changing `@code-padding: 15px;` to `@code-padding: 0px;` fix the indentation issues for all cases.

**Comment by petetnt** [comment]
@RaymondLim interesting, I thought I tried that out yesterday when checking out your comment! I'll try that out and update the indent-wrap PR asap

**Comment by RaymondLim** [comment]
@petetnt Don't use it with any other changes in your PR. Just that simple change. I did verify with main editor and inline editor (both with line numbers and without line numbers). Not sure what other side effects this change might introduce though.
