### ISSUE TITLE
Code Hinting has turned off & I cannot get it back on

### ISSUE THREAD

**Issue by AaronRayRay** [adobe/brackets#12637]
Hi

Sorry if this has been done, however I cannot find a clear answer.

Sometimes code hinting turns off and usually when I close Brackets and re-open, it is working fine again. However this time it is not working at all. I notice there is a menu option "Show code hints" however it does not select when I click on it or try the Ctrl + space.

Does anyone know how to get it back on?

**Comment by AaronRayRay** [comment]
Can I just update this to say, it appears to only be code hinting within script tags when writing javascript. 

When I am doing css it is still working just fine.

**Comment by redmunds** [comment]
@AaronRayRay Code hinting in a simple `<script>` tag works for me, so I suspect that it's the language or some other attribute that you have specified. Please paste in an example of your script tag.

**Comment by AaronRayRay** [comment]
Hello @redmunds 

Thank you for getting back to me. I am going through a tutorial course.

The code is below what I am writing between:

**Comment by AaronRayRay** [comment]
`<script type="text/javascript">
            
           
           
           
            
        </script>`

So normally when I start typing between these codes docu... for example it would normally suggest document. Then after that getEle.... it comes up with a list of things I may want to select, in the case of what I am doing getElementById.

It has previously stopped displaying the hints to me, I just saved the work, restarted brackets and it would work again. However since around midday today it just stopped altogether. I have even reinstalled brackets to see if that would help.

**Comment by redmunds** [comment]
I know that works in .htm and .html files. Does your file have some other file extension? Or maybe it's a new file that has not yet been saved to disk (so it does not yet have a file extensions)?

**Comment by AaronRayRay** [comment]
@redmunds my extensions list shows as below and the file is saved. This one is arrays.html.

![image](https://cloud.githubusercontent.com/assets/20774542/17301373/8d3f58f0-580e-11e6-98c8-d29b3cc96dfe.png)

**Comment by AaronRayRay** [comment]
@redmunds I seem to have solved it.

I just clicked on Debug > Reload without extensions

then Debug > Reload with extensions

and now it appears to be working!

Very odd....but something to try for anyone else who gets the same problem at some point. 

Thank you for assisting me :+1:
