### ISSUE TITLE
Brackets not working

### ISSUE THREAD

**Issue by abhinavluv** [adobe/brackets#12633]
Getting an error "The application was unable to start correctly (0xc0000022). Click OK to close the application." Previously was getting an error for access related issues, so gave full control to the brackets application and brackets directory. After giving full control, i started getting this error.

**Comment by markljackson** [comment]
What version of Brackets, and what O/S are you on?

**Comment by abhinavluv** [comment]
I tried to install the latest version which I downloaded from brackets
website. V1.7

**Comment by abhinavluv** [comment]
Forgot to mention, OS is windows 10 64 bit

**Comment by petetnt** [comment]
Quick googling shows that this might be an anti-virus software issue. Which AV are you running?

**Comment by abhinavluv** [comment]
I too checked that.but the time I tried installing brackets, I did not have
an antivirus... I then later scanned my pc by installing an antivirus and
tried reinstalling but could go any further.

**Comment by ficristo** [comment]
As mentioned by @petetnt this seems an AV problem or some issue about your permission settings.
Closing as not an issue with Brackets itself.
