### ISSUE TITLE
Help wanted: update CEF version on Linux, help needed on OSX and Windows

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#12640]
The version of CEF on Linux is lagging behind and I would like to try to improve this situation.
To do so there are two ways:
- fix the crash on quit on https://github.com/adobe/brackets-shell/pull/499
- update the portion of cefclient used on the brackets shell which hopefully fix the crash

We tryed the first thing and asked for help without results.

Now I'm tryng the second way, but before I need some cleanup PR: I'm asking if someone of you could try to compile and run them on OSX and Windows and report the results.
If you will try, could you report in the PR mentioned which OS you used (Windows, OSX) and the compiler (GCC, Visual Studio 2015, ...)?

Thank you

PS: Here you can find how build the shell: https://github.com/adobe/brackets-shell/wiki/Building-brackets-shell

**Comment by ficristo** [comment]
Could you look at https://github.com/adobe/brackets-shell/pull/561?

**Comment by Learn-Digital-Audio** [comment]
Ficristo, it is fantastic news you are working on this! Thanks so much! Is there any news on your progress?

**Comment by ficristo** [comment]
@Learn-Digital-Audio I'll update this thread with any news.
Right now I have a couple of PR in the works, nothing big, but they are build one on top of each other.
So I need adobe/brackets-shell#561 before posting another one. And that PR has yet to be tested on OSX.
In general there is still a lot of work to do (especially since I'm not really a native developer)
Since Linux version is mostly community driven, as of now, if I receive more help I can do (a little) more.

**Comment by kirkins** [comment]
Anyone know if there is a workaround? I'm running brackets on my desktop which is Ubuntu 14.04 without a problem. On my laptop with 16.04 I get the libgcrypt11 issue.

**Comment by ficristo** [comment]
@kirkins have you searched it on other issues?
By the way there are some workarounds in #12380 and #10255 for the libgcrypt11 issue.

**Comment by ficristo** [comment]
Another, but much more ambitious way, to fix all problems on Linux would be to fix [this](https://github.com/electron/electron/issues/1582) electron issue and switch to that shell.

**Comment by kirkins** [comment]
As a work around I used the repackaged version of 1.6 found at the bottom of this page:

https://brbsix.github.io/2015/10/29/fix-missing-libgcrypt11-for-brackets-text-editor/

**Comment by ficristo** [comment]
Another cleanup https://github.com/adobe/brackets-shell/pull/570 ready to be looked at.

**Comment by ficristo** [comment]
https://github.com/adobe/brackets-shell/pull/571

**Comment by ficristo** [comment]
I'm not sure if I still continue on this given that @zaggino has released brackets-electron.
See this comment for a bit more context: https://github.com/adobe/brackets/issues/10255#issuecomment-243854796

**Comment by ficristo** [comment]
~~https://github.com/adobe/brackets-shell/pull/578~~
Merged

**Comment by ficristo** [comment]
https://github.com/adobe/brackets-shell/pull/581

**Comment by ficristo** [comment]
https://github.com/adobe/brackets-shell/pull/583

**Comment by ficristo** [comment]
~~https://github.com/adobe/brackets-shell/pull/584~~
Merged

**Comment by ficristo** [comment]
https://github.com/adobe/brackets-shell/pull/585
https://github.com/adobe/brackets-shell/pull/586

**Comment by ficristo** [comment]
https://github.com/adobe/brackets-shell/pull/588

**Comment by ficristo** [comment]
There are still some problems, but at least now I can run the application on Linux with the latest CEF.
https://github.com/adobe/brackets-shell/pull/589

**Comment by ficristo** [comment]
https://github.com/adobe/brackets-shell/pull/591

**Comment by ficristo** [comment]
With #562 and #589 I can compile and run master on Linux, I don't know how much is stable but could be a start.
That said this work was too much time consuming for me so I gave up.
For people on Linux the best alternative is simply to use brackets-electron.
