### ISSUE TITLE
Material Design!!

### ISSUE THREAD

**Issue by marcellopato** [adobe/brackets#12645]
How about put some Material Design frame work inside GWD?

**Comment by ficristo** [comment]
There are already some themes that have a material design.
I don't think we will change the two default themes anytime soon.

**Comment by marcellopato** [comment]
What themes?

**Comment by ficristo** [comment]
Under `File \ Extension Manager` on the `Themes` tab there are some themes that claim to use the material design (just search for material).
After installed you can switch to the new theme using `View \ Themes`.
I don't know how good they are.

**Comment by marcellopato** [comment]
An app llike this should improve the BEST material design with tools and so
on. Not just be a good tool for building banners...

Em qui, 4 de ago de 2016 às 05:56, ficristo <notifications@github.com>
escreveu:

**Comment by ficristo** [comment]
Oh, I thought you wanted a theme!
Instead you want some tools to write material things?
Can you describe which kind of tools?

**Comment by marcellopato** [comment]
All material tools togheter. Imagine if you can use GWD to create wep pages
on a blink of an eye just draging and droping a slider, a card, a
collection, and everything INSIDE GWD.
But the HTML MUST be clean, tight. Now a days I can write a entire web site
using just a few hours per day writing the HTML code. Put some features
ilke connect to a database and FTP and sey goodbye to Dreamweaver for good.
I allready don´t use DW for so long. I ´m using Brackets and it is very,
very good.

I think GWD will be THE app for writing the best web apps, mobile apps, etc.

What you say?


Em qui, 4 de ago de 2016 às 12:49, ficristo <notifications@github.com>
escreveu:

**Comment by ficristo** [comment]
Brackets is focused to be a code editor. Everything else is welcome as extension.

Maybe [this extension](https://github.com/swmitra/html-designer) could be something useful.

**Comment by marcellopato** [comment]
Yes, I know about Brackets extensions, but i´m talking about GWD and its cool about HTML5 animation. But it works great only for create banners. That´s it focus. But would be the best and powerfull web pages tool!
Maybe someone do a php, full of functioality and then, boom, you open it on GWD e visually put everything on its place with an gorgeous look, like, sliders, carrosels,cards, forms and toasts, accordions, navbars with a serach within, parallax backgrounds, all based on google´s material desing?
Pretty awesome, hã?

**Comment by raita** [comment]
Marcellopato that's so Futuristic what you talking about many's peoples doesn't even realize that but honest at you i don't know what really GWD that is

**Comment by marcellopato** [comment]
It is Google Web Design, a Google´s web design software. But it is good oonly for creating banners in HTML5. It is fantastic.

**Comment by raita** [comment]
Can you please give me a Link from that Material Web Design please .
Kindly.
Dezzy.
Sent from Yahoo Mail on Android 
 
  On Tue, 9 Aug, 2016 at 21:34, marcellopato<notifications@github.com> wrote:   
It is Google Web Design, a Google´s web design software. But it is good oonly for creating banners in HTML5. It is fantastic.

**Comment by marcellopato** [comment]
You can find GWD here https://www.google.com/webdesigner/ and the Material Design framwork that i use alot is http://materializecss.com/

**Comment by raita** [comment]
WoooooW so Beauty Bro but those need to work together in same time ? GWD and Materializecss?  well if i do a wedb site design can i put on Wordpress Bro?
 

    Le Mercredi 10 août 2016 13h34, marcellopato <notifications@github.com> a écrit :
 

 You can find GWD here https://www.google.com/webdesigner/ and the Material Design framwork that i use alot is http://materializecss.com/—

**Comment by marcellopato** [comment]
WP uses another framework called bootstrap.

**Comment by raita** [comment]
Can we make with Boostrap create material design and parallax effect?

Sent from Yahoo Mail on Android 
 
  On Tue, 16 Aug, 2016 at 23:29, marcellopato<notifications@github.com> wrote:   
WP uses another framework called bootstrap.

**Comment by marcellopato** [comment]
Yes. There´s a version for Material Design for Bootstrap, two, by the way.
http://mdbootstrap.com/material-design-for-bootstrap/ and http://fezvrasta.github.io/bootstrap-material-design/

Cheers!

**Comment by raita** [comment]
Oh that's my boy is good one but can we use also Brackets on it? 

    Le Jeudi 18 août 2016 13h37, marcellopato <notifications@github.com> a écrit :
 

 Yes. There´s a version for Material Design for Bootstrap, two, by the way.
http://mdbootstrap.com/material-design-for-bootstrap/ and http://fezvrasta.github.io/bootstrap-material-design/Cheers!—

**Comment by marcellopato** [comment]
Yes!

Em seg, 22 de ago de 2016 às 17:15, Raita Sorin <notifications@github.com>
escreveu:
