### ISSUE TITLE
Can't turn off Auto Close tags

### ISSUE THREAD

**Issue by Bryceratops88** [adobe/brackets#12653]
New to HTML or anything coding so bare with me...

So for instance, I type in tag and a closing tag immediately appears afterwards. This is a great unless I've already typed text and don't want to have to cut and paste. Opened up preferences and thought I inserted the proper code. "closeBrackets": False. I saved the file and still nothing happens.

**Comment by RaymondLim** [comment]
@Bryceratops88 Just answer this question a while back. See my answer [here](https://github.com/adobe/brackets/issues/12619#issuecomment-235098893).

**Comment by Bryceratops88** [comment]
Thank you, sir.
