### ISSUE TITLE
In Brackets, I can't turn off auto close brackets...

### ISSUE THREAD

**Issue by Bryceratops88** [adobe/brackets#12650]
New to HTML or anything coding so bare with me...

So for instance, I type in tag and a closing tag immediately appears afterwards. This is a great unless I've already typed text and don't want to have to cut and paste. Opened up preferences and thought I inserted the proper code. "closeBrackets": False. I saved the file and still nothing happens.

**Comment by RaymondLim** [comment]
@Bryceratops88 You can turn it off from Edit > Auto Close Braces.
