### ISSUE TITLE
Remember the selected syntax highlighting for extensionless files

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#12655]
Or maybe all files that have other highlighting than the default one applied to.

I actually have started to work on this months ago, it just needs some polish, I'll try to get that in as a PR sometime soon 👍

**Comment by sprintr** [comment]
@petetnt Have you had a look at #11560? This may be related to that.

**Comment by petetnt** [comment]
@sprintr Hmm never seen that one before, that is definitely related. My PR would build on top of that by applying the syntax highlighting for files not per filename, but path name. For example I have an bash file called `app` in project 1 and NodeJS file called `app` in project 2; if I apply JavaScript for the one in project 2, it shouldn't use that as syntax for the project 1 one.

**Comment by sprintr** [comment]
Cool, I still have to write unit tests for them but haven't been able to do so.
