### ISSUE TITLE
Code folding arrow on the script tag is invisible

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#12669]
For the following snippet:

``` html
<script type="text/javascript">
    function test() {

    }
</script>
```

the code folding arrow on the `script` tag is invisible but you can still collapse the tag.
If you highlight all the code then it arrow is visible.
/cc @thehogfather

**Comment by thehogfather** [comment]
As far as I can see this is no longer an issue. Worth revisiting.

**Comment by ficristo** [comment]
I can confirm on master is fixed.
