### ISSUE TITLE
Extract for Brackets (Preview) don't support cyrillic language

### ISSUE THREAD

**Issue by andreymokko** [adobe/brackets#12677]
If I [click to "Copy Text" for cyrillic language](https://cl.ly/h4TB) (example «Привет»), and paste it, i get html symbol code: "`&#1055;&#1088;&#1086;&#1076;&#1072;&#1078`" instead of text. It is very uncomfortable.

So, necessary to keep open Photoshop for copy the text, or write a text manually.

**Comment by nethip** [comment]
@andreymokko Extract is no longer supported from within Brackets(http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/). You could try Dreamweaver which will still support Extract.

**Comment by andreymokko** [comment]
@nethip Too bad :( I don't like Dreamweaver. Thank you for your answer!
