### ISSUE TITLE
dontCloseTags option is being ignored.

### ISSUE THREAD

**Issue by jGeek314** [adobe/brackets#12670]
Not sure what I'm doing wrong here.  I tried a cfbrackets extension and everything worked except the dontclosetags list.  So I tried to change my preferences manually and still can't get brackets to listen to the closeTags.dontCloseTags array.

Tried reloading with and without extensions... still couldn't get it to work.

Here are the contents of my brackets.json file:

```json
{
    "fonts.fontSize": "12px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "themes.theme": "dark-theme",
    "noDistractions": false,
    
    "closeTags": 
        {
            "dontCloseTags": ["cfset"],
            "indentTags": [],
            "whenOpening": false,
            "whenClosing": true  
        }
    
}
```

**Comment by ficristo** [comment]
It seems that if you have `whenClosing: true` the `dontCloseTags` attribute is ignored.
Filed: https://github.com/codemirror/CodeMirror/issues/4165

**Comment by ficristo** [comment]
Given the upstream discussion I think this is the expected behaviour.
@jGeek314 you can contact the author of the extension you are using to discuss more this issue.

**Comment by jGeek314** [comment]
@ficristo Does this mean it's impossible in brackets to use "whenClosing: true" with the  "dontCloseTags"?  Or is there some way to modify the autoselfclosers to get it to work?  It seems like a bug to me, or at least a missing feature.

**Comment by ficristo** [comment]
We are inheriting the CodeMirror behaviour which is the expected one, in this case, according its author. So yes, I think is impossible to use `whenClosing: true` with the `dontCloseTags`.
Perhaps you could define your own language (see https://github.com/adobe/brackets/wiki/Language-Support) using a new codemirror mode with the `autoselfclosers` option.
I think @MarcelGerber could help you more.
