### ISSUE TITLE
How i Close Getting Started File From Panel

### ISSUE THREAD

**Issue by muzammilijaz** [adobe/brackets#12682]
Please find the attachment.I want to exit Getting Started Files from left tab.
http://prnt.sc/c6rc4k

**Comment by ficristo** [comment]
ATM you can't close a project, you can only switch to another one. Just click on the project name or with `File \ Open Folder`.

**Comment by doliver3** [comment]
This is horrible. I want to see the files I have open. I shouldn't be forced to have the Getting Started Project open obscuring my list of open files.

**Comment by StudioBlox3089** [comment]
> This is horrible. I want to see the files I have open. I shouldn't be forced to have the Getting Started Project open obscuring my list of open files.

You don't understand, It doesn't show up your opened files (And stuff). It only has the _Getting Started_ files.

**Comment by xypd** [comment]
To get rid of the getting started, you simple need to start a NEW project and then pick a directory to save files to.

examples:
https://www.youtube.com/watch?v=GN0txxeT46A

https://stackoverflow.com/questions/13937018/how-to-create-a-new-project-in-adobe-brackets

Hope this helps explain how this works.

**Comment by 4th3LuLz0fIt** [comment]
Three years later and this issue is still an issue because I too have this issue. With any other IDE such as JetBrains Pycharm, you are able to close projects that show up in a side panel. What is so hard about following a standard format for an IDE?

PS: It is now 2019 and the OP is 2016 come on!

**Comment by techgeniuswang** [comment]
> Three years later and this issue is still an issue because I too have this issue. With any other IDE such as JetBrains Pycharm, you are able to close projects that show up in a side panel. What is so hard about following a standard format for an IDE?
> 
> PS: It is now 2019 and the OP is 2016 come on!

agree, we really need close "Getting Started" easily

**Comment by hancarv** [comment]
its now 2020 and I cant just open brackets and get onto my last project, I allways have to go and chose its folder, and everytime I have to look at that ridiculous getting started file thats driving me crazy

**Comment by TruthPictures** [comment]
It's bizarre that "Working Files" are given approximately 15% of the side panel, and the "Getting Started" portion of the side panel is given the other 85%.  Never use the "Getting Started".  

The Working Files, in which I have 15 or more open, disappears behind the "Getting Started" block, and no way to make the "Getting Started" portion disappear.  It's horrible design, and wastes a lot of time by hiding files I actually want to click on to open.

**Comment by OIITCONZ** [comment]
I'm giong to add my voice to this - just installed brackets and I'm already frustrated with it - Seriously - looking up support to close the default project?

**Comment by LorantPapai** [comment]
Ok, here's what you have to do:

1. Click on "Getting started" on the navigation panel (left side)
2. Choose "Open folder" (It's the only oprion anyway.)
3. Choose the root folder of the project you wish to work on
4. Voilá.

Hope it helped, I was struggling with this issue a lot myself too.

**Comment by Allardje** [comment]
I really want to be able to hide that whole block.

I actually like opening the files myself instead of browsing trough the folder within Brackets.

Therefore all i want is to get rid of the whole "getting started" block so i don't have to scroll through my files anymore. It's taking up 70% of that whole bar with a section i do not want at all and is forcing me to scroll trough the content i actually want. Is it so hard to just have a little "x" there to close it?
