### ISSUE TITLE
Possible swagger hub codegen issue with Enums: @JsonValue annotation is missing from toString()

### ISSUE THREAD

**Issue by ralgor14** [adobe/brackets#12689]
The @JsonValue annotation is missing when codegen creates java code (Server->jaxrs) for Enums.
This annotation should be on toString() method.
The following:
        "state": {
          "type": "string",
          "enum": [
            "active",
            "inactive"
          ]
        }

causes creation of the following Enum code:
  public enum StateEnum {
    ACTIVE("active"),
    
    INACTIVE("inactive");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @Override
     public String toString() {
      return String.valueOf(value);
    }
  }

Which causes "active" and "inactive" in JSON files to be unrecognized.
In order to correct it the annotation @JsonValue should be added before toString():
    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

It was OK in previous versions of swagger hub.
Annotations are used by jackson's fasterXml package.

**Comment by ficristo** [comment]
How is this related to Brackets?

**Comment by ralgor14** [comment]
I do not understand the question. It's connected to @JsonValue annotation for Enums . 
 Did I write anything connected to Brackets?

**Comment by ralgor14** [comment]
Sorry, I should move it to swagger-api/swagger-codegen
