### ISSUE TITLE
Creating widget

### ISSUE THREAD

**Issue by swathiAMD** [adobe/brackets#12691]
Hi,
  I followed the webinar : http://ww2.mendix.com/Expert-Webinar.Widgets.html.

I m unable to create an widget. The widget creation is freezing at '25%' not sure how to proceed.

PFA the screen shot.
![creatingwidget](https://cloud.githubusercontent.com/assets/4669814/17781586/bfa4ce0e-6567-11e6-9fbb-6988054cf87c.png)

**Comment by MarcelGerber** [comment]
This is not an issue related to Brackets, but rather regarding the [Widget Development Plugin for Brackets](https://github.com/mendix/WDPForBrackets).
Closing as extension problem.
