### ISSUE TITLE
Possible swagger hub codegen issue with nested elements: the @JsonProperty annotation is missing from get methods

### ISSUE THREAD

**Issue by ralgor14** [adobe/brackets#12690]
The @JsonProperty annotation is missing when codegen creates Java code (Server->jaxrs) for nested elements.

The following block:

    "PM_Session": {
      "description": "description",
      "type": "object",
      "properties": {
        "id": {
          "description": "description",
          "type": "string"
        },
		....
		"ethOamPerfMonCfg": {
          "$ref": "#/definitions/EthOamPerfMonCfg"
        }
    },
		
	"EthOamPerfMonCfg": {
      "description": "description.",
      "type": "object",
      "properties": {
        "startTime": {
          "description": "description",
          "type": "string"
        },
		...
        "EthOamDmCfg": {
          "$ref": "#/definitions/EthOamDmCfg"
        },
        "EthOamDmmCfg": {
          "$ref": "#/definitions/EthOamDmmCfg"
        },
      },
      "required": [
	    ...
      ]
    },
    ...
caused creation of the following Java code:

@ApiModel(description = "Performance Management Session also known as MA - Maintenance Association - Reference MEF 35.1 Section 10.1.1 General Overview of Parameters")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2016-08-16T13:50:07.517Z")
public class PMSession   {
  private String id = null;
  ...
  private EthOamPerfMonCfg ethOamPerfMonCfg = null;
  
  ...
 }
 
 @ApiModel(description = "Ethernet OAM Performance Monitoring Configuration.")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2016-08-16T13:50:07.517Z")
public class EthOamPerfMonCfg   {
  private String startTime = null;
  ...
  private EthOamDmCfg ethOamDmCfg = null;

  private EthOamDmmCfg ethOamDmmCfg = null;

  @ApiModelProperty(value = "")
  public EthOamDmCfg getEthOamDmCfg() {
    return ethOamDmCfg;
  }

  ...
  @ApiModelProperty(value = "")
  public EthOamDmmCfg getEthOamDmmCfg() {
    return ethOamDmmCfg;
  }
  ...
}

while get methods with @ApiModelProperty annotation should also have @JsonProperty("baseName").
In our case:

  @ApiModelProperty(value = "")
  @JsonProperty("EthOamDmCfg")
  public EthOamDmCfg getEthOamDmCfg() {
    return ethOamDmCfg;
  }

  ...
  @ApiModelProperty(value = "")
  @JsonProperty("EthOamDmmCfg")
  public EthOamDmmCfg getEthOamDmmCfg() {
    return ethOamDmmCfg;
  }

  Missing annotation causes the JSON file to be considered illegal.
  It was OK in previous versions of swagger hub.
Annotations are used by jackson's fasterXml package.

**Comment by ficristo** [comment]
How is this related to Brackets?

**Comment by ralgor14** [comment]
I do not understand the question. It's connected to @JsonProperty . 
Did I write anything connected to Brackets?

**Comment by ralgor14** [comment]
Sorry, I should move it to swagger-api/swagger-codegen
