### ISSUE TITLE
 mathematical operations

### ISSUE THREAD

**Issue by evliyabalik** [adobe/brackets#12708]
I can not do the multiplication gives an error in the code I wrote

**Comment by ficristo** [comment]
Which error do you see?

**Comment by evliyabalik** [comment]
Ben herhangi bir hata kodu sorun derleme yapımında tanınmaz alamadım

PRoGrAmER

2016-08-23 20:20 GMT+03:00 ficristo <notifications@github.com>:

**Comment by evliyabalik** [comment]
I do not get any error code is not recognized in making trouble compiling

PRoGrAmER

2016-08-24 17:56 GMT+03:00 Evliya BALIK <evliyabalik@gmail.com>:

**Comment by ficristo** [comment]
Could you give us more info like a snippet of code, which language you are using, maybe a screenshot, what are you compiling, etc? I really don't know how to help otherwise.
Maybe try also `Debug \ Reload without extensions` to see if it is an extension that is causing problems.

**Comment by evliyabalik** [comment]
Şimdi tamamen matematiksel bir çarpma (*) operasyonu olarak tek başına
sorunu çözüldü bilmek teşekkür ederim

PRoGrAmER

2016-08-24 20:52 GMT+03:00 ficristo <notifications@github.com>:

**Comment by evliyabalik** [comment]
now completely solved the problem by itself as a mathematical
multiplication (*) operation , thank you to know

PRoGrAmER

2016-08-24 20:52 GMT+03:00 ficristo <notifications@github.com>:
