### ISSUE TITLE
OS X. Cant open some files

### ISSUE THREAD

**Issue by BlackRockSoul** [adobe/brackets#12703]
I cant open some folders and files. v1.7
v1.5 works fine
Console error log
![image](https://cloud.githubusercontent.com/assets/4317830/17840782/ad94357e-6828-11e6-9952-88984395ab34.png)
![2016-08-22 5 29 47](https://cloud.githubusercontent.com/assets/4317830/17840827/766a26a2-6829-11e6-8b5e-abb879ddb786.png)

**Comment by petetnt** [comment]
Hi @BlackRockSoul, does this occur without extensions? Do the folders you are trying to open have anything special in them?

**Comment by BlackRockSoul** [comment]
@petetnt yep. Just installed
Folders have php and js files. V 1.5 and the windows latest version was ok

**Comment by BlackRockSoul** [comment]
I think I figured out what the problem is. Os X created icon files. I can't do anything with them
![image](https://cloud.githubusercontent.com/assets/4317830/17897255/f64502d6-696c-11e6-93d1-d74c440ea144.png)

**Comment by BlackRockSoul** [comment]
Okay, it was a problem. I just deleted these files and everything. No errors anymore.
_p.s. sorry for bad english ^^_

**Comment by petetnt** [comment]
@BlackRockSoul No problem!

I'll follow up and see if files called `Icon` cause problems in general as they seem to as far as the `React` error messages show.
