### ISSUE TITLE
php: ctrl + space not working in "Brackets"

### ISSUE THREAD

**Issue by peym4ns** [adobe/brackets#12715]
ctrl + space not work in "Brackets"

**Comment by ficristo** [comment]
I assume you meant "Brackets".
Can you be more specific: which language are you using? Do you use some extensions?
If you try `Debug \ Reload Without Extensions` does work again?

**Comment by peym4ns** [comment]
Yes, I'm use php Language 
I try  Debug \ Reload Without Extensions , but does not work.

**Comment by MarcelGerber** [comment]
By default, Brackets doesn't come with PHP Code Hints.
You can install an extension to get these. Try "PHP SmartHints", for example. Let us know if you're still having trouble.

**Comment by ficristo** [comment]
Closing as extension available.
