### ISSUE TITLE
File Inference Problem with CreateJs

### ISSUE THREAD

**Issue by johncarterdesign** [adobe/brackets#12714]
As I edit my project containing the createjs suite, I will get 3 or 4 warnings (like the screenshot below) that say JavaScript File Inference Problem, and each time it names a different file within createjs. After a few of these warnings the screen will randomly go blank while I am editing and the only way to get brackets working again is to quit from the dock and reopen. I have tried just deleting the file named in the warning but then it finds a new one the next time. I have also tried reloading without extensions and this did not work. 

<img width="609" alt="screen shot 2016-08-25 at 9 33 50 am" src="https://cloud.githubusercontent.com/assets/16950608/17975651/c5bbe59e-6aa7-11e6-9bc7-25b3898d9691.png">

**Comment by ficristo** [comment]
Brackets doesn't handle well big project: how big is yours?
In this case you could try https://github.com/zaggino/brackets-file-tree-exclude

**Comment by ficristo** [comment]
I close this since we didn't hear back from you.
