### ISSUE TITLE
Command ID for moving cursor to next line?

### ISSUE THREAD

**Issue by rococtz** [adobe/brackets#12729]
Hi,

I want to be able move my cursor up, down, left, right without using the arrow keys. Is there a command id for that?  If not, do you have any example of how to achieve that?

Thanks

**Comment by sprintr** [comment]
`Editor.prototype.setCursorPos` in `/src/editor/Editor.js` is the API you need.

**Comment by rococtz** [comment]
Thank you very much for the quick response.

I believe there's no key binding for this, right?

What would be the approach if I want to use this API? Should I create my own extension?

**Comment by sprintr** [comment]
You need to create your own extension to start with.

First get the editor instance.
```js
var EditorManager = brackets.getModule("editor/EditorManager"),
      editor = EditorManager.getCurrentFullEditor();
```
then set cursor position.
```js
editor.setCursorPos(1, 4);
```

**Comment by rococtz** [comment]
Thank you!
