### ISSUE TITLE
Html Shows but Css doesn't effect HTML? Is there a way to fix this?

### ISSUE THREAD

**Issue by alfredrb** [adobe/brackets#12728]
So i'm new to brackets I started yesterday, But my css isn't effecting HTML live preview here is the screen shots.

![css](https://cloud.githubusercontent.com/assets/20364059/18034912/d9985012-6d17-11e6-93c5-7e2c5b9fefc2.PNG)

**Comment by ficristo** [comment]
Can you reproduce with `Debug \ Reload Without Extensions`?

**Comment by alfredrb** [comment]
It still doesn't show CSS Effect in Debug \ Reload Without Extensions

**Comment by ficristo** [comment]
Could you share a snippet of code so we can reproduce?

**Comment by alfredrb** [comment]
Okay

**Comment by alfredrb** [comment]
Css: /* reset all the things */

*, 
*:before, 
*:after {
    margin:0; 
    padding:0; 
    border:0; 
    text-decoration:none; 
    outline:none; 
}

/* fonts */

body { 
    font-family:Arial, sans-serif; 
}

/* dimension animator */

.animate 
{
    -webkit-transition : max-width .4s, max-height .4s, width .4s, height .4s; 
	-moz-transition    : max-width .4s, max-height .4s, width .4s, height .4s; 
	-ms-transition     : max-width .4s, max-height .4s, width .4s, height .4s; 
	-o-transition      : max-width .4s, max-height .4s, width .4s, height .4s; 
	transition         : max-width .4s, max-height .4s, width .4s, height .4s;   
}

/* adds a little down arrow to the right */

.has-sub:after {
    content:"▼";     
    font-size:12px; 
    line-height:12px; 
    margin:0 0 0 10px; 
    color:#444; 
}

/* the navbar */

.navbar { 
    display:block; 
    background-color:#333; 
    color:#eee; 
    height:60px; 
    margin:0 0 20px 0; 
    padding:0; 
} 

.navbar * {
    display:inline-block; 
    list-style:none; 
}

.navbar:after { 
    display:block; 
    clear:both; 
    content:"";
} 

/* the logo */

.logo a { 
    font-weight:bold; 
    padding:20px; 
    color:#ccc; 
    overflow:hidden; 
    font-size:20px; 
    line-height:20px; 
}

/* menu items */

.menu-item {
    float:left; 
    position:relative; 
    cursor:pointer; 
    background-color:#333;
}

.menu-item > a {
    padding:20px; 
    color:#fff; 
    font-size:20px; 
    line-height:20px; 
}

.menu-item > a:hover, 
.menu-item > a:focus {
    background-color:#202020; 
}

/* this keeps the dropdown visible while a menu item has focus */

.menu-item > a:focus ~ .menu-sub {
    max-height:400px;  
}

/* sub-menu dropdowns */

.menu-sub {
    position:absolute; 
    display:inline-block; 
    overflow:hidden; 
    top:60px; 
    left:0; 
    max-height:0;
    width:auto; 
    background-color:#202020; 
    z-index:9; 
}
 
.menu-sub li a {
    display:block; 
    font-size:14px; 
    line-height:14px; 
    padding:20px; 
    color:#fff; 
    width:200px;
}

.menu-sub li a:hover {
    background-color:#111;
}

.content {
    padding:20px; 
}





































Html:
<nav class="navbar">
    
    <div class="logo">
        <a href="#">Website</a> 
    </div>
    
    <ul class="menu-wrap">
        
        <li class="menu-item">
            
            <a class="has-sub" href="#">About</a> 
            
            <ul class="menu-sub animate">
                <li><a href="#">The Company</a></li>
                <li><a href="#">Our Goal</a></li>
            </ul>
            
        </li>
        
        <li class="menu-item">
            
            <a class="has-sub" href="#">Work</a> 
            
            <ul class="menu-sub animate">
                <li><a href="#">Most Recent</a></li>
                <li><a href="#">Our clients</a></li>
                <li><a href="#">Projects</a></li>
            </ul>
            
        </li>
        
        <li class="menu-item">
            
            <a href="#">Contact</a> 
            
        </li>
        
    </ul>
    
</nav>


<div class="content">
Lorem ipsum dolor sit amet, consectetuer adipiscing elit

**Comment by ficristo** [comment]
In the html you posted there isn't the link to the stylesheet, something like:
```html
<link type="text/css" rel="stylesheet" href="Main.css">
```
And this has nothing to do with live preview.

Plus I remember some issues, while using live preview, on html files which aren't enclosed in a `<html>` tag. So I would suggest to add it.
