### ISSUE TITLE
Editor CSS content gets applied to Brackets

### ISSUE THREAD

**Issue by knox97** [adobe/brackets#12735]
Hey guys, lets get to the issue right away,here are couple of screenshots of the problem
![workspace 1_030](https://cloud.githubusercontent.com/assets/19645574/18051757/bf70354e-6df6-11e6-807f-4e4e190e1fc8.png)
![workspace 1_029](https://cloud.githubusercontent.com/assets/19645574/18051762/c8f59eec-6df6-11e6-87ec-4adb21443613.png)

All that you see on the pictures above is done with html internal css styles

Here is an example:
`<style> * { color: #F00 !important; }</style>`
the code above would make all the text on the brackets red, without backticks it wont work, you have to surround the code with backticks

**Comment by MarcelGerber** [comment]
Have you tried launching Brackets without extensions (`Debug > Reload without extensions`)?

**Comment by ficristo** [comment]
I close this since we didn't hear back from you.
