### ISSUE TITLE
Cannot find context with specified id

### ISSUE THREAD

**Issue by moukbel** [adobe/brackets#12733]
hi,

i'm new in devloping and  i keep get this message error in brackets,
"Cannot find context with specified id"
any one can help me please ?

**Comment by ficristo** [comment]
Where you see the message? Is an alert or you see in the console?
Can you reproduce with `Debug \ Reload Without Extensions`?

**Comment by moukbel** [comment]
it's keep appear in the console, when i reloaded without Extensions its disappear.
thanks,

**Comment by ficristo** [comment]
Closing as extension problem.
