### ISSUE TITLE
Paste option from the context menu

### ISSUE THREAD

**Issue by rdealmeida12** [adobe/brackets#12745]
I'm using the latest version of Brackets (1.7.0-16898). I can not paste from the context menu, but an able to paste from the edit menu and the Ctrl - V shortcut. I reloaded without extensions , still nothing..
any ideas ??

Bob

**Comment by ficristo** [comment]
Brackets doesn't have native context menu. Probably an extension problem.

**Comment by rdealmeida12** [comment]
If I highlight some text, right click and scroll down and left click on cut and then position the cursor some where else, right click and left click on paste nothing happens.. I've tried reloading without extensions, still the same thing..
Any Ideas??
Bob

**Comment by ficristo** [comment]
If you are trying to copy and paste from the context menu, Brackets doesn't have it currently: so you have an extension that add it.
If you have tryed reloading without extensions, you shouldn't see the context menu with copy and paste anymore.
And that is the expected behaviour.
