### ISSUE TITLE
Not all selected text highlighted?

### ISSUE THREAD

**Issue by AdeHarrison** [adobe/brackets#12740]
Using latest (Release 1.7 build 1.7.0-16898 (release b0a363b71) build timestamp: Wed Jun 08 2016 04:20:22 GMT-0700) on El Capitan

When I select text, the first 2 chars aren't highlighted (see attached), bizarre but any ideas? it's really off putting

thanks in advance 

![brackets](https://cloud.githubusercontent.com/assets/10206077/18119809/5b86a2a2-6f54-11e6-93e9-1e715c575b78.png)

**Comment by petetnt** [comment]
This has been fixed in https://github.com/adobe/brackets/pull/12635 and 12110, can you try the latest master (See: [How-to-Hack-on-Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets)).

Feel free to reopen if the problem still occurs on you on the latest master.
