### ISSUE TITLE
Using PHP When Building Extensions

### ISSUE THREAD

**Issue by isaacdew** [adobe/brackets#12759]
Is it possible to build an extensions' interface with PHP? I am working on an extension that I need to submit information to a database. The only way I know how to do this is through PHP but it seems to ignore all of the PHP syntax. If there are any other possibilities like doing it via Javascript let me know.

**Comment by ficristo** [comment]
Do you mean a Brackets extension? If so it's not possible.
But I don't understand what you mean with "ignore all of the PHP syntax".
Can you clarify?

**Comment by isaacdew** [comment]
Yes. I mean that it acknowledges all of the HTML within the PHP file but ignores all of the actual PHP. Thanks for answering. Is it possible that I can connect to a database another way? Is there a way to use JavaScript?

**Comment by zaggino** [comment]
@isaacdew using database might not be a best solution for brackets extension, can you share more information on what does your extension do and what kind of data do you need to save?

**Comment by isaacdew** [comment]
@zaggino - I built an in editor time clock (just a basic JS timer) to keep track of a user's development time but I want to allow the user to save their time in a database and associate it with a specific project in the database.

**Comment by zaggino** [comment]
1) https://github.com/adobe/brackets/wiki/Preferences-System Brackets have State object which is kind of a local data storage that you could utilize to save data on users computer
2) if you want to send it to a database in internet, you'll need to setup a api server somewhere and use jquery's `$.ajax` to send it there, that's how Health Data is being collected: https://github.com/adobe/brackets/blob/7814da193b98ff7889714a601d630973bddf02d0/src/extensions/default/HealthData/HealthDataManager.js#L93-L121

**Comment by isaacdew** [comment]
The second option will most likely be what I'm looking for. I want developers to be able to view their hours through a web application. Thank you.
