### ISSUE TITLE
Problem with saving html files

### ISSUE THREAD

**Issue by marek8623** [adobe/brackets#12756]
Hi everyone,

I have problem with saving html files. If I want to save a file I need to click on another file on the left side and then brackets will save the opened file.

Thank you for your response.

**Comment by ficristo** [comment]
Can you reproduce with `Debug \ Reload Without Extensions`?
If so, could you give us the exact steps to reproduce?
For example are you trying to save an existing file or one created with `Ctrl+N`?

**Comment by ficristo** [comment]
Closing since there was no answer.
If you still have problems, please, open a new issue.
