### ISSUE TITLE
Bold Font

### ISSUE THREAD

**Issue by AyushKenhi** [adobe/brackets#12754]
Is there any way to bold the font of the editor.

**Comment by ficristo** [comment]
It's depend on what you want it for. You could:
- try a theme that change the style of the editor (but it will not affect the file tree)
- play with an extension, but I'm not sure if you can theme completely the file tree
- change the font on `View \ Themes` to one installed on your system on use a bold font
- play with the styles on Developer Tools (but they will be forgetten on restart)

**Comment by WilfredRuck** [comment]
<b> </b>

**Comment by WilfredRuck** [comment]
"<b> </b>"

**Comment by WilfredRuck** [comment]
<b> tag?
