### ISSUE TITLE
Visual Studio Crash when 'Open Folder'

### ISSUE THREAD

**Issue by dhruvajoshi8** [adobe/brackets#12757]
Visual Studio on my machine gets crashed when i try to open a folder. Below is the error i get
![image](https://cloud.githubusercontent.com/assets/22031266/18279011/b7a4dc9e-7471-11e6-898b-9a6056fc0e7c.png)

I tried looking into various issues reported here. Though could not find any solution to this particular problem. Can somebody please help?

Thanks in advance!

**Comment by petetnt** [comment]
Hi @dhruvajoshi8,

you might be looking for VSCode repository located at https://github.com/Microsoft/vscode

This repository belongs to `Brackets` code editor.
