### ISSUE TITLE
Feature Request: Back-tick notation for multi-line strings.

### ISSUE THREAD

**Issue by efares** [adobe/brackets#12769]
### Description

It would be nice to use the back-tick notation for multi-line strings in TypeScript.
### Steps to Reproduce
1. Open a TypeScript file in Brackets
2. Use back-tick "`" (not single quote) and write a string
3. Enter new line and continue writing the string

**Expected behavior:** [What you expected to happen]
- This is Visual Studio Code
  ![screen shot 2016-09-09 at 2 33 23 pm](https://cloud.githubusercontent.com/assets/4211727/18398369/6c044808-769a-11e6-96cd-0ad53184a1b2.png)
  **Actual behavior:** [What actually happened]
- This is Brackets
  ![screen shot 2016-09-09 at 3 43 56 pm](https://cloud.githubusercontent.com/assets/4211727/18400519/4fa0321c-76a4-11e6-8365-344707a18477.png)
### Versions
- Brackets
  Release 1.7 build 1.7.0-16898 (release b0a363b71) 
  build timestamp: Wed Jun 08 2016 04:20:22 GMT-0700
- OS X
  Version 10.11.6 (15G1004)

**Comment by ficristo** [comment]
Next time could you follow the indications you see when you open a new issue?
I usually use only the master branch and I don't see any particular issue.
Could you add a screenshot of Brackets, which version it is, share the snippet of code you use and which language it is? (It seems a snippet of angularjs 2 to me).

**Comment by MarcelGerber** [comment]
I don't exactly see an issue in the screenshot. The whole multi-line string is highlighted as a string, and everything else isn't.
So what would you want to see instead?

**Comment by efares** [comment]
@ficristo sorry, I put it in the new issue format.
@MarcelGerber the first screenshot is of VS Code not Brackets.

**Comment by zaggino** [comment]
@efares as far as I know, Brackets support it fine, can you show how it fails in your Brackets?
![image](https://cloud.githubusercontent.com/assets/1067319/18401737/56823f1e-771f-11e6-848d-5e600f54301e.png)

**Comment by efares** [comment]
@zaggino it works fine on JavaScript files but I was wondering if it can also function the same with **TypeScript** files.

**Comment by zaggino** [comment]
@efares It works the same for TypeScript, I'm using my https://github.com/zaggino/brackets-typescript extension.
![image](https://cloud.githubusercontent.com/assets/1067319/18406218/8cae136a-773d-11e6-9819-11f8e04b1b58.png)
