### ISSUE TITLE
auto compile (sass, pug)

### ISSUE THREAD

**Issue by vicApakau** [adobe/brackets#12762]
This is the only place to chat / no forum?
(slack invite is not working)

In Atom, I can auto compile pug and sass.
How do I do that in Brackets?

I added the extensions and they ... don't auto compile? 
Vic

**Comment by zaggino** [comment]
Hi, you'd need to ask extension authors to implement auto-compile in their extensions.
Probably best place would be in the extension repositories:
https://github.com/ForbesLindesay/jade-brackets/issues
https://github.com/jasonsanjose/brackets-sass/issues
