### ISSUE TITLE
Can't condense code blocks without opening properly

### ISSUE THREAD

**Issue by ealgase** [adobe/brackets#12760]
### Description

Sometimes, after closing code blocks and not clicking the open button, when they do open, I can't close them.

### Steps to Reproduce

1. Condense code block
2. Do things such as moving cursor to the ... and opening it without clicking.
3. After a few tries, the arrow will turn right; however, the code block will not be condensed

**Expected behavior:** Arrow points down and allows me to close it

**Actual behavior:** Arrow points right and doesn't allow me to close it

### Versions

Windows 10
Release 1.7 build 1.7.0-16898 (release b0a363b71) 

**Note: **you can solve this problem by hitting f5 to reload brackets.  However, this is annoying.

**Comment by zaggino** [comment]
cc @thehogfather

**Comment by thehogfather** [comment]
I am unable to reproduce this using the steps to reproduce above. However I can reproduce a similar issue if lines are added above the folded code for example.

@ealgase could you clarify that this issue does occur exactly as stated (i.e., you don't need to add or remove lines from the file)?

 My initial suspicion is that it has been addressed in #12521 and is closely related to #12456 #12232

**Comment by zaggino** [comment]
Marking for 1.9 as this should be re-tested with 1.8 release.

**Comment by ealgase** [comment]
Hmm... I tested again and it is addressed by #12521, and you did need to delete lines above.
