### ISSUE TITLE
Do something about src/config.json

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#12771]
### Prerequisites
- [x] Can you reproduce the problem with `Debug \ Reload Without Extensions`?
- [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
- [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)
### Description

Now that `npm install` is part of the build we should do something about `config.json`:
it is regenerated everytime which is ok, but it needs different values if we are in dev or in production.
We should find a better way to manage the differences.
### Steps to Reproduce
1. Run `npm install`

**Expected behavior:**
Running `git status` `config.json` should not appear in the modified files.

**Actual behavior:** 
Running `git status` `config.json` appears in the modified files.
### Versions

Windows 10
master

**Comment by zaggino** [comment]
In `brackets-electron` I made `src/config.json` to be ignored by git, since it's recreated after every `npm install`

**Comment by ficristo** [comment]
AFAIK the only thing to manage is `healthDataServerURL` which points to `https://healthdev.brackets.io/healthDataLog` in dev and points to `https://health.brackets.io/healthDataLog` in production.
After we find a way for that we can put `src/config.json` in `.gitignore`.

**Comment by petetnt** [comment]
Can we use environment variables? Something like `healthDataServerURL = (BRACKETS_ENV !== "development" ? "https://healthdev.brackets.io/healthDataLog" : "https://health.brackets.io/healthDataLog")`?

**Comment by MarcelGerber** [comment]
We probably don't even need that.
`package.json` is used in dev and `src/config.json` in production, so we could just integrate this difference into the code that copies the values around.

**Comment by nethip** [comment]
Let me have a look at this issue. I am also thinking in line with @MarcelGerber

**Comment by MarcelGerber** [comment]
Mostly fixed with #12778.
Created #13458 to fix another small inconsistency I am experiencing, see the PR description for more information.
