### ISSUE TITLE
Paste (right click or ctrl+v) doesn't do anything

### ISSUE THREAD

**Issue by vankasteelj** [adobe/brackets#12770]
### Prerequisites

* [x] Can you reproduce the problem with `Debug \ Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

I cannot paste anything in Brackets. 

This isn't  #12745 or #12747 : when I reload without extensions, it still doesn't work (note that I do have cut/copy/paste in the context menu, even when reloading without extension: see fd2b8848ef).

I am not using Webroot.

The console is saying : `Error setting menu item shortcut: 1` and `Failed to load resource: net::ERR_FILE_NOT_FOUND` (about JavaScriptCodeHints, so I doubt it's related)

### Steps to Reproduce

1. Open Brackets
2. Load a new file (ctrl+n)
3. Write `ezezez` in the file
4. Select it (shift+home)
5. Copy it (ctrl+c)
6. Go to the end of the line to replicate (end)
7. Try to paste it (ctrl+v)
8. Cry a lot

**Expected behavior:** [What you expected to happen]
- CTRL-C / CTRL-V to work

**Actual behavior:** [What actually happened]
- CTRL-C does work, but CTRL-V does nothing. I can, however, paste elsewhere (in firefox, e.g.) what I copied from brackets.

### Versions

Windows 10 Pro 64 bits
Brackets : Latest master b9cae25 (as of sept. 10)

**Comment by vankasteelj** [comment]
UPDATE : it does work when I reset to 300f3d0. I'd be blaming d93ccc532 but I sadly don't know brackets code well enough to sustain that presumption

**Comment by ficristo** [comment]
If you use master it is expected. You need to build the brackets-shell too to use the paste feature.
Alternatively you could give a try to [brackets-electron](https://github.com/zaggino/brackets-electron/)
