### ISSUE TITLE
Unable to download Brackets 1.7

### ISSUE THREAD

**Issue by shirodkarsohan** [adobe/brackets#12777]
I am not able to download Brackets 1.7 (Release 1.7 - 06-10-2016). I am currently using Release 1.6 build 1.6.0-16680 (release 3df0ac6fa). When I try to download Brackets, it continues till 75%-78%, than the download speed drops slowly and download fails with 403 error code. I have tried downloading on numerous occasions but the same problem continues. I seriously feel this is a server issue.

Any help would be appreciated!

**Comment by zaggino** [comment]
Not sure what might be the issue but in the meantime you can try downloading brackets-electron directly from github - https://github.com/zaggino/brackets-electron/releases

**Comment by petetnt** [comment]
Have you had any luck downloading 1.7. or does the problem persist?

**Comment by shubham48648** [comment]
downloading is working fine, close this issue

**Comment by Olfredos6** [comment]
The downloading is not working fine. Listen to your community people!!!!! Before requesting for issues to be closed, verify the thing first. What will your editor be if no one uses it? Seriously!!!!
![need to tell these f](https://user-images.githubusercontent.com/13703962/28351634-640cc1f4-6c51-11e7-8bb5-542d0e9d53d8.JPG)

**Comment by petetnt** [comment]
Hi @Olfredos6,

the downloads both on brackets.io and GitHub are hosted on GitHub infrastructure, which are then again hosted on AWS S3.

I'd assume that the 403 Forbidden errors are related to some S3 specific throttling mechanisms and there's every little there we can do with those. I recommend using a regular browser to download the executables, or looking for an alternative mirror if that fails too.
