### ISSUE TITLE
Failed to connect to node

### ISSUE THREAD

**Issue by iegik** [adobe/brackets#12774]
v1.8.2 #8606d51ab Ubuntu 14.04
After clean start In console shows the error:
```
[Extensions] Failed to connect to node Arguments[1]
0: "timeout"
length: 1
(anonymous function) @ Package.js:533
```

**Comment by zaggino** [comment]
@iegik can you provide a list of installed extensions from `Help > Health Report` ?

**Comment by zaggino** [comment]
Solving here https://github.com/zaggino/brackets-electron/issues/72
