### ISSUE TITLE
file tree breaks on OSX when folder with folder icon is used

### ISSUE THREAD

**Issue by kromeyer** [adobe/brackets#12789]
### Description

Brackets file tree isn't working on OSX if folder with changed folder icon is opened. OSX creates an Icon file inside a folder if the user changes the folder icon or software like BTSync or Dropbox are in use which create specific folders and also use the icon mechanism.

### Steps to Reproduce

1. create a folder
2. change folder icon (more details here: https://support.apple.com/kb/PH22191)
3. open brackets
4. open created folder in file tree view
5. an error will show up in console and the file tree isn't working anymore

### Versions

OS Version: OS X 10.11.6 (15G1004)
Brackets Version: Release 1.7 Build 1.7.0-16898 (release b0a363b71)

**Comment by petetnt** [comment]
Also reported in https://github.com/adobe/brackets/issues/12694 and https://github.com/adobe/brackets/issues/12703.

As this seems to affect many users, giving this a higher priorty

**Comment by petetnt** [comment]
Fix pending at #12807

**Comment by petetnt** [comment]
Fixed in #12807
