### ISSUE TITLE
Bug/feature: Ctrl+Shift+Move selection with curser doesn't duplicate.

### ISSUE THREAD

**Issue by elron** [adobe/brackets#12787]
### Description

A feature that allows to **duplicate a code selection without Copy+Paste**.

###  Expected behavior: [What you expected to happen]

I used dreamweaver before this, there, if I wanted to duplicate a selection I did, I would:
1. Select something in the code
2. Hold CTRL+SHIFT, Clicking on the selection and dragging it to another place in the code.
3. That would cause:
- the original selection to stay where it was.
- Duplicate the selection, placing it in the place the mouse has dropped. (drag-drop)

### Actual behavior: [What actually happened]

It justs lets me re-select.

### Versions

Windows 7
Brackets 1.7

**Comment by ficristo** [comment]
You have to enable the `dragDropText` preference.
`Debug \ Open Preferences File` and add
```json
"dragDropText": true
```

**Comment by elron** [comment]
@ficristo How do I edit it?
Whenever I do the change and save + restart Brackets, it reverts back to defaultPreferences file.

**Comment by ficristo** [comment]
Are you modifying the **right** file?

**Comment by elron** [comment]
I am modifying the file that opens when I click - Debug->Open Preferences
File
בתאריך 16 בספט׳ 2016 21:34,‏ "ficristo" <notifications@github.com> כתב:

Are you modifying the *right* file?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/adobe/brackets/issues/12787#issuecomment-247674607>,
or mute
the thread

**Comment by ficristo** [comment]
When you click it, it should open the split view.
At the left you have the `defaultPreferences.json` file which isn't supposed to be modified.
On the right side you should see the `brackets.json` file where you have to put your changes.

**Comment by elron** [comment]
I see! I will try soon and let you know
בתאריך 16 בספט׳ 2016 21:40,‏ "ficristo" <notifications@github.com> כתב:

**Comment by elron** [comment]
You, @ficristo, an awesome person on the internet, you're my savior.
