### ISSUE TITLE
Suggestion...

### ISSUE THREAD

**Issue by Aphrodisiaque** [adobe/brackets#12798]
Bonjour à tous...

Une fonctionnalité toute simple me manque cruellement : le "copier / coller" accessible avec le clic droit de la souris...
Les habitudes sont tenaces !

Bonne journée à tous

**Comment by ficristo** [comment]
Google translation:
>Hello everyone...
>
>A simple feature sorely miss: the "copy / paste" available with the right mouse button ...
>The habits die hard!
>
>Good day to all

This is already available in 1.8 [prerelease](https://github.com/adobe/brackets/releases/tag/release-1.8-prerelease1).
