### ISSUE TITLE
Feature suggestion: All extensions in one place?

### ISSUE THREAD

**Issue by lednhatkhanh** [adobe/brackets#12790]
I think brackets needs a place to help users find all packages, theme, upload there extensions, etc...
Both Atom and vscode have their own page, and one more thing, brackets has a small number of packages compared to the others.

**Comment by ficristo** [comment]
This is the homepage for the registry where all extensions live: https://brackets-registry.aboutweb.com/
Here you can upload your extension or theme.
You can find the same through `File \ Extension Manager...`

**Comment by petetnt** [comment]
Hi @lednhatkhanh,

Brackets extension registry is available [here](https://brackets-registry.aboutweb.com/), where you can see all the existing extensions, upload new ones and update old ones.

There's also http://brackets.dnbard.com/ which lists most popular extensions by  various metrics.

Feel free to reopen if you have more questions.
