### ISSUE TITLE
Pressing Escape key is removing multiple popups

### ISSUE THREAD

**Issue by adityapaturi** [adobe/brackets#12799]
### Prerequisites

* [X] Can you reproduce the problem with `Debug \ Reload Without Extensions`?
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [X] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description
When quick edit and code hint popup are opened(code hint popup need not be within quick edit), pressing Escape key dismisses both code hint popup and Quick edit at one go. This is introduced by https://github.com/adobe/brackets/pull/12251 

### Steps to Reproduce

1. Open any JS file
2. Invoke Quick edit on a function call to see the function definition
3. Click within or outside the quick edit window
4. Invoke Code hint (Ctrl + Space)
5. Press Escape and observe both code hint and Quick edit go away

**Expected behavior:** [What you expected to happen]
Escape should dismiss only the code hint popup. To dismiss Quick edit escape needs to be pressed again.

**Actual behavior:** [What actually happened]
Both code hint and Quick edit go away with single stroke of Escape key
### Versions
Can be seen on latest master
Please include the OS and what version of the OS you're running.
Win 8.1
Please include the version of Brackets. You can find it under `Help \ About Brackets`
Release 1.8 development build 1.8.0-0 (master a340c3067)

**Comment by adityapaturi** [comment]
@petetnt, @bmax : Please have a look. This is introcuded by PR #12251

**Comment by petetnt** [comment]
@adityapaturi Thanks for this bug report, assigning to myself.
