### ISSUE TITLE
Windows 10 UWP Version

### ISSUE THREAD

**Issue by bdbch** [adobe/brackets#12801]
### Prerequisites
- [x] Can you reproduce the problem with `Debug \ Reload Without Extensions`?
- [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
- [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)
### Description

Since the Desktop Converter was released by Microsoft, and first Apps like "Evernote" and are getting moved into UWP apps, It would make sense to create a UWP app for Windows 10.

UWP apps are running faster and are more secure, since the whole application is inside an capsuled package.
You can read more about it here:
https://msdn.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter

I tested it on my local machine and it took me only 4 minutes to build. I could provide you with the `.appx` file if needed so you just have to add your App-Icon + Signature.
### Steps to Reproduce
1. Check Windows Store
2. Can't find Brackets
3. Be sad

**Expected behavior:**
Find Brackets and Install, read ratings, be happy
### Versions

Windows 10

**Comment by mvandermade** [comment]
I'm actually interested in learning how to create an UWP app.
How would one do it with an existing app like Brackets ?
