### ISSUE TITLE
CSS commands wont work at all

### ISSUE THREAD

**Issue by AgentO0** [adobe/brackets#12803]
Hello experts,

i am quite new here and i just started using Brackets and have only used html ages ago and not really advanced..

My problem now is, that no matter what codes i write in my CSS- file, it will not effect my html layout, which is really annoying. 

The commands are really really simple so there is not much i could have overlooked, but you never know.

In the Pics below you can see them. 

i would be really happy if anyone could help me with this, because if css is not working i wont get really far i guess.

Greetings from Germany

![screen shot 2016-09-23 at 12 31 55 pm](https://cloud.githubusercontent.com/assets/22392775/18783232/096f9c00-818b-11e6-961c-a458d503b99e.png)
![screen shot 2016-09-23 at 12 32 05 pm](https://cloud.githubusercontent.com/assets/22392775/18783233/0970d08e-818b-11e6-8474-a9260af3a58d.png)
![screen shot 2016-09-23 at 12 42 16 pm](https://cloud.githubusercontent.com/assets/22392775/18783305/5a022db8-818b-11e6-8ca5-1906916fe643.png)

**Comment by AgentO0** [comment]
already solved sorry

**Comment by zaggino** [comment]
👍

**Comment by ebot1515** [comment]
in CSS order your code better so you can find what you want, with spaces like this:
#logo {
margin-left: auto;
margin-right: auto;
ect
}
