### ISSUE TITLE
Directory Browsing Doesn't work in 1.7 or 1.8 pre release

### ISSUE THREAD

**Issue by caseyjonesaustralia** [adobe/brackets#12804]
Version 1.6 allows me to move through a sub-directory, but both version 1.7 and 1.8 (pre-release) does not.

I'm using a MacBook Pro 2015 build on OSX Sierra and a MacBook Air 2012 on El Capitain.

To reproduce, I drag a project folder onto the brackets icon similar to the following

project
>folder1
>>file.html
>>file2.html
>folder2
>>sub-folder1
>>sub-folder2

I can open "folder1" but folder2 won't open at all.

**Comment by petetnt** [comment]
Do you happen to have files called `Icon` in your folders? It seems to have caused some similar issues in https://github.com/adobe/brackets/issues/12789.

**Comment by caseyjonesaustralia** [comment]
Ah! Exactly! I do indeed have files called "Icon?" in these folders.
For production work I have been using brackets v1.6, as it works perfectly regardless of the icons being present.

Cheers mate,

**Comment by petetnt** [comment]
@caseyjonesaustralia, I'll try and fix the Icon issue this week, lets track this on #12789 for progress. 

Big thanks for the report, closing as duplicate.
