### ISSUE TITLE
Error brackets: Favicon + Fail to nomalize Cmd shift ]

### ISSUE THREAD

**Issue by manel00** [adobe/brackets#12808]
Hi everyone!

I'm using Brackets on a Windows 7, and It gives me some error that I cannot understand, I'll show you a screenshot, I dont know if it's my code, Bootstrap CDN... But I was sweeping along this problem since few days, What should I do?

![brackets error](https://cloud.githubusercontent.com/assets/8410687/18983216/c0c44508-86eb-11e6-8db1-70e93c1e8517.jpg)

**Comment by zaggino** [comment]
@manel00 this is an extension issue, report here please:
https://github.com/sixertoy/brackets-console-plus
