### ISSUE TITLE
Extension installation faied

### ISSUE THREAD

**Issue by mandar262** [adobe/brackets#12819]
I was installing the extension from the following link [Link to package]
(https://github.com/thehogfather/brackets-code-folding)

but it gave following error 

![capture](https://cloud.githubusercontent.com/assets/20091634/19212365/3c0e028a-8d6d-11e6-88ed-d4357de35489.JPG)

where will i find dissabled extension folder or uninstall it

**Comment by petetnt** [comment]
Hi @mandar262,

the code folding extension is now in the Brackets core, so the extension isn't needed anymore.

The disabled folder is under 

- Mac: ~/Library/Application Support/Brackets/extensions
- Win XP: C:\Documents and Settings\<username>\Application Data\Brackets\cef_data -- (aka %appdata%\Brackets\)
- Win Vista/7/8/10: C:\Users\<username>\AppData\Roaming\Brackets\-- (aka %appdata%\Brackets\)
- Linux: ~/.config/brackets/-- (aka $XDG_CONFIG_HOME/brackets/cef_data)

You can safely remove the extension.
