### ISSUE TITLE
libgcrypt11 dependency not satisfied. 

### ISSUE THREAD

**Issue by declanmarks** [adobe/brackets#12811]
When installing Brackets in Ubuntu 16.04 I get an error saying that the dependencies are not satisfied. After reading online Brackets using an old version of libgcrypt. Is this something that is going to be updated. I am currently using the latest version of brackets.

**Comment by petetnt** [comment]
Hi @declanmarks, 

please see https://github.com/adobe/brackets/issues/12640 and https://github.com/adobe/brackets/issues/10255 for workarounds for this issue.

Closing this as duplicate.

**Comment by ficristo** [comment]
For completeness there is this guide: https://nathanjplummer.github.io/Brackets/
My suggest for Linux users is to use brackets-electron.

**Comment by mackenza** [comment]
as a full time Linux user, I concur with @ficristo . There are some limitations to Brackets-Electron (I don't believe Live Preview works but I don't use it), but there are numerous advantages:

- retains window size between sessions
- doesn't require hitting the window close X button twice to close the window
- native menus vs. html menus
- no dependency issues as above. Can also run via AppImage which isolates from dependencies
