### ISSUE TITLE
Feature suggestion - 'reverse live view': link from browser to editor 

### ISSUE THREAD

**Issue by kaimdx** [adobe/brackets#12815]
### Description

I know with live view the part of the webpage that is being changed in the editor is highlighted in the browser. It will be very handy if the reverse also works: click somewhere in the browser, the editor cursor jumps to where the corresponding HTML code is.   

I found it easier to locate/find something, such as a paragraph or a title, in browser than in the editor. Also, you usually spot something that needs to be changed in browser, and this feature will then allow you to quickly locate the code in editor.

I would be surprised if this idea hasn't been mentioned before, but a quick search on the issues didn't return anything similar.

**Comment by mmcken3** [comment]
I am also not sure if this is mentioned anywhere else in issues. I checked and could not find it. But, I think this update could be pretty useful for larger pages and would get behind trying to get that set up.

**Comment by saurabh95** [comment]
This feature is added in https://github.com/adobe/brackets/pull/13044. You can clone the latest code to use this. Also this feature works in MultiBrowser Live Preview as well (https://github.com/adobe/brackets/pull/13103).

**Comment by kaimdx** [comment]
Cool! I will check it out.
