### ISSUE TITLE
JS ajax responseText typo

### ISSUE THREAD

**Issue by GreenCommunications** [adobe/brackets#12816]
![eed189f0dd5270c53c671b1f1165f817](https://cloud.githubusercontent.com/assets/10868929/19135511/0e9d17c8-8b33-11e6-8d92-3a9809b74b56.png)

OS: Windows 10

Brackets: 1.7

**Comment by mackenza** [comment]
I am running from master and the typo does not exist there. Can you re-submit this issue using the issue template? That would give us useful information like what version you are running.

**Comment by ficristo** [comment]
This was fixed with the upgrade of Tern available in 1.8.
