### ISSUE TITLE
Golang files do not have a theme option

### ISSUE THREAD

**Issue by luisalvarado** [adobe/brackets#12810]
Basically, opening a .go file shows the code but without coloring (no theme) as oppose to Sublimetext or Atom. I noticed today when I was moving my team from Atom or Sublimetext to Brackets and this happened.

Using Ubuntu 16.04 64-bit.

**Comment by petetnt** [comment]
Hi @luisalvarado,

Golang syntax highlighting is available via plugins such as https://github.com/petetnt/brackets-codemirror-go and https://github.com/devinceble/brackets-go. You can install them under `File -> Extension Manager`
