### ISSUE TITLE
Unable to create new file/directory on Brackets Ubuntu (error NotReadable)

### ISSUE THREAD

**Issue by Slayerxy** [adobe/brackets#12826]
Hello
I'm using Brackets on Ubuntu 16.04 and when im trying to create a new file or directory within an existing project i keep getting "An error occurred when trying to create the file (error NotReadable)" 

thou my server testing root folder and sub folders are owned by the current user 
nabil@nabil-Vostro-1015:~$ ls -l /var/www/introductionphp/
total 44
drwxrwxrwx  5 nabil nabil 4096 Oct 10 22:19 ch01
drwxrwxrwx 12 nabil nabil 4096 Oct 10 22:19 ch02
drwxrwxrwx  9 nabil nabil 4096 Oct 10 22:19 ch03
drwxrwxrwx  7 nabil nabil 4096 Oct 10 22:19 ch04
drwxrwxrwx  8 nabil nabil 4096 Oct 10 22:19 ch05
drwxrwxrwx  8 nabil nabil 4096 Oct 10 22:19 ch06
drwxrwxrwx  7 nabil nabil 4096 Oct 10 22:19 ch07
drwxrwxrwx  9 nabil nabil 4096 Oct 10 22:19 ch08
drwxrwxrwx 12 nabil nabil 4096 Oct 10 22:19 ch09
drwxrwxrwx  8 nabil nabil 4096 Oct 10 22:19 ch10
drwxrwxrwx  2 nabil nabil 4096 Oct 10 22:19 introduction

Thanks for any help

**Comment by ficristo** [comment]
If you use another editor what happen? Can you write the file?

Lately my usual advice for Linux user is to use [braclets-electron](https://github.com/zaggino/brackets-electron/): it has better support for Linux and maybe it will fix your problem

**Comment by Slayerxy** [comment]
first of all thank you for taking the time to respond to my qst
i've tried Netbeans IDE 8.2 and im still getting the same result 
![screenshot from 2016-10-18 14-22-13](https://cloud.githubusercontent.com/assets/22792488/19479388/5db0bc2e-953e-11e6-87b0-44b640400115.png)

**Comment by ficristo** [comment]
I'm not really familiar with linux world, but it seems to me `var/www` folder needs a special treatment.
Looking around, maybe you could try something like `chmod -R 774 /var/www/introductionphp/` (if you already didn't of course).

To workaround your issue you could try to move your project in your `home` folder and create a symbolic link inside `var/www`: `ln -s ....`

**Comment by Slayerxy** [comment]
Problem fixed, i tried "sudo chown -R nabil:nabil introducingphp/" and it did the job.

Thank you so much for your assistance

**Comment by ficristo** [comment]
Closing since #11182 is tracking a similar problem.
