### ISSUE TITLE
custom indentation

### ISSUE THREAD

**Issue by garrett85** [adobe/brackets#12823]
I would like to be able to customize whether or not brackets uses space or tabs when pressing space. And to matter which one it uses I would like to be able to customize the number of columns in the tab or spaces if it's inserting spaces. And I'd to be able to have a different configuration for different file types. I use different indentation on my python programs than I do just about everything else.

Linux Mint user

**Comment by redmunds** [comment]
You need to manually edit your brackets preferences json file to specify those settings per language. For example:

```json
    "language": {
        "javascript": {
            "spaceUnits": 2,
            "useTabChar": false
        },
        "html": {
            "spaceUnits": 4,
            "useTabChar": true
        }
    }
```

Note that you can set preferences globally or per project.

**Comment by garrett85** [comment]
Thanks. I didn't know that.
