### ISSUE TITLE
Brackets does not open any file after the ?Icon-File from Mac in the file tree

### ISSUE THREAD

**Issue by hadome** [adobe/brackets#12833]
Hello,
I have got a problem: Brackets does not open any php/image/… files below the "Icon?“ file from Mac.
I run Brackets without any Plugins.

System: macOS sierra
MacBook Pro 13“ 2015
Brackets: 1.7.0-16898

Thank you for reading.
hadome

**Comment by petetnt** [comment]
Hi @hadome!

I think this too is fixed with #12807.

Could you try the latest master? See [this article](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) for instructions.

**Comment by ficristo** [comment]
@hadome
> Thank's but how I execute this command?

If you are running from source, the fix should be already included.

**Comment by Rufury** [comment]
Just downloaded from brackets.io latest version and I have same issue.
Don't understand from the links above how should I fix it.

**Comment by zaggino** [comment]
@Rufury new builds will be available in brackets.io in a couple of days hopefully

**Comment by petetnt** [comment]
@Rufury have you tried the new pre-release?

**Comment by Rufury** [comment]
@petetnt no, I don't use pre-releases usually, was waiting for full release update.

**Comment by ficristo** [comment]
1.8 is out, if you still have problems please open a new issue.
