### ISSUE TITLE
Project-level preferences do not work

### ISSUE THREAD

**Issue by wilfordw** [adobe/brackets#12831]
### Steps to Reproduce

1. Follow[《How to Use Brackets》](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets)
2. create a `.brackets.json` in the root of my project
```json
{
    "fonts.fontSize": "14px",
   "jslint.options": {
        "node": true
    },
}
```

**Expected behavior:** font size of files in my project should change to 14px and jslint work for `node.js`

**Actual behavior:** nothing happened when I saved the json file, but it worked well when i did the same change for User-global preferences in `brackets.json` 

### Versions

OS : macOS Sierra 10.12
Brackets:Release 1.7 build 1.7.0-16898 (release b0a363b71) 

> Sorry for my poor English,I have done my best to find the way for the problem.but failed, someones had the same problem in 2014,but didn't get the answer.
http://stackoverflow.com/questions/27233323/using-brackets-json-for-jslint-in-brackets.

**Comment by ficristo** [comment]
I suppose you written a valid json, right? What you have is not (note the last trailing comma).
In the template issue it is aked if you see any error in Developer Tools, is there one?

**Comment by wilfordw** [comment]
@ficristo I copyed all the context from User-global preferences in `brackets.json`,but` .brackets.json` even didn't work,and there are no error in Developer Tools,So it's hard for me to find the way to resolve it.
And i want to find someone who had the same problem as my then had resoved it.

**Comment by redmunds** [comment]
@wilfordw There is a JSON Lint extension that will report this error.

@ficristo I have seen many others fall into same trap. Would be nice if Brackets would write an error to console when parsing any preferences json fails.

**Comment by ficristo** [comment]
@redmunds I think would be even better having a json linter in core.
And more better our json files should not be strict json, they should support, for example, comments in them. Something like gyp file which support also trailing commas.

**Comment by wilfordw** [comment]
i have made a stupid mistake!!!
**root of my project means the folder opened by Brackets**. But I create `.brackets.json` in the sub folder of the root,so the preference didn't be loaded.

**Comment by redmunds** [comment]
@ficristo 

> I think would be even better having a json linter in core.

I'm ok with that as long as user has a way to disable it.

> And more better our json files should not be strict json, they should support, for example, comments in them. Something like gyp file which support also trailing commas.

Totally agree.

>But yes, as short gap would be nice printing something in the console in case of error.

While I agree, with both of those suggestions, they won't catch all cases, so errors should still be written to console.

**Comment by ficristo** [comment]
@wilfordw happy to hear you found the problem.

@redmunds you are right about the extension. I'll open a new issue about the general problem.
