### ISSUE TITLE
suggested feature: suggest defined class in css

### ISSUE THREAD

**Issue by lukaskadan** [adobe/brackets#12838]
### Description

suggested feature: suggest defined class in css

Once you defined a class in html it could be a useful feature to suggest this class in the css document when you start typing a dot. This feature would reduce broken code because of typing errors.

### Steps to reproduce

1. define class in html
2. refer to a class in css

**Expected behavior:**

3. suggest defined class(es) from the html

**Actual behavior:**

nothing happens

###Versions
OS: os x el capitan version 10.11.6
Brackets: Release 1.7 Build 1.7.0-16898 (release b0a363b71)

**Comment by redmunds** [comment]
There's an extension called "Brackets CSS Class code hint" that does this. Maybe some others.

**Comment by lukaskadan** [comment]
thank you!



                      Lukas Kadan
Grafik- & Kommunikationsdesign
visual communication design
Lukas.kadan@gmail.com
+43 6 80 20 7 13 77

2016-10-17 22:13 GMT+02:00 Randy Edmunds <notifications@github.com>:

**Comment by swmitra** [comment]
@lukaskadan Closing the issue as the requested feature is already available as an extension. Please reopen the issue if the suggested extension or none of the other available extensions offer the requested feature.
