### ISSUE TITLE
Toogle-Code-Block-Button doesn't work sometimes

### ISSUE THREAD

**Issue by vince1995** [adobe/brackets#12832]
### Description

Sometimes the toggle button to hide or show code blocks doesn't work correctly. When I open a code block the button doesn't switch.

Here a picture of the issue:

![image](https://cloud.githubusercontent.com/assets/15120985/19344917/6cb390bc-913c-11e6-83ba-36732b81183d.png)

And how it should be:

![image](https://cloud.githubusercontent.com/assets/15120985/19344932/806e64f6-913c-11e6-9e7b-bbb0f20deda2.png)

When the issue occurs I can't close the code block anymore and have to reload brackets.

### Steps to Reproduce

I can't reproduce the issue. Sometimes it occurs, mostly not.

### Versions

I'm running on Windows 10 and my brackets version is Release 1.7 Build 1.7.0-16898 (release b0a363b71)

**Comment by SpeedyTechie** [comment]
I have this problem as well. I most often encounter it when dealing with large SVG files, but I haven't been able to consistently reproduce it either. Also on Windows 10 and Release 1.7 build 1.7.0-16898. If/when I encounter the issue again, I'll report more details.

**Comment by ficristo** [comment]
This is already fixed by #12521 
Can you try a prerelease to see if you still hit?

**Comment by SpeedyTechie** [comment]
Okay, first I confirmed that the issue I was seeing was related to deleting lines of code above the folded section, which it was. I installed Release 1.8 build 1.8.0-17080 and can verify that the problem no longer occurs. Can't speak for @vince1995, but this takes care of it for me.

**Comment by ficristo** [comment]
@SpeedyTechie thank you.
@vince1995 if you still have this problem with 1.8 prerelease could open a new issue? Thank you,

**Comment by vince1995** [comment]
I've installed 1.8 now. When I get the problem, I'll open a new issue.

Thank you.
