### ISSUE TITLE
Windows 10 can't install extensions

### ISSUE THREAD

**Issue by gultyaev** [adobe/brackets#12842]
Hello! I have some problem with extensions install. When i install any extension or theme brackets show error "Install error. Server connection is impossible". 

Sorry for my english.

P.S. On the Linux it works correctly.

**Comment by petetnt** [comment]
Hi @gultyaev,

do you have `node.exe` shipped with Brackets allowed in your firewall settings?

**Comment by gultyaev** [comment]
@petetnt 
All requests allowed. I tried disable firewall and this changes nothing

**Comment by petetnt** [comment]
Do you see any errors other in `Debug -> Show Developer Tools -> Console-tab` or `Debug -> Show Developer Tools -> Network-tab` ?

**Comment by gultyaev** [comment]
![pic](https://cloud.githubusercontent.com/assets/22374911/19554380/ff306904-96c0-11e6-8f60-487604a508c8.PNG)
Is this we need?

**Comment by gultyaev** [comment]
Finally! I install extension! I just disable secure connections scanning in my AV.
