### ISSUE TITLE
ES7 async and await keywords

### ISSUE THREAD

**Issue by DaAwesomeP** [adobe/brackets#12846]
Brackets does not properly highlight the JavaScript ES7 `async` and `await` keywords, and the following line is highlighted incorrectly as well.

Release 1.7 build 1.7.0-16898 (release b0a363b71) 
build timestamp: Wed Jun 08 2016 12:27:56 GMT+0100
Windows 10 Pro x64

**Comment by zaggino** [comment]
Hi @DaAwesomeP 

We're updating CodeMirror in soon to be released version 1.8

You can test the highlighting here https://codemirror.net/mode/javascript/index.html and if it's incorrect, open an issue with https://github.com/codemirror/CodeMirror

**Comment by DaAwesomeP** [comment]
Yeah, the new CodeMirror version works as expected. Thanks!
