### ISSUE TITLE
How To Hack on Brackets

### ISSUE THREAD

**Issue by efiator** [adobe/brackets#12843]
The How to Hack on Brackets page seems to be missing some instructions for mac users who are running El Capitan. Below is a proposed update:

Before step 5: If you have node.js, then continue with the following steps:

If you don’t currently have node.js on your computer, you need to go here and download node.js : https://docs.npmjs.com/getting-started/installing-node

		Then follow the instructions to update npm on the given link.

Then continue with step 6.

**Comment by efiator** [comment]
Or you can follow this url as well:

https://docs.npmjs.com/getting-started/installing-node

**Comment by petetnt** [comment]
Hi @efiator,

thanks for the heads up! I added `NodeJS` as an prerequisite to the guide, as it applies to all platforms now. 

Feel free to reopen the issue or open new ones if you see other missing things 👍
