### ISSUE TITLE
Copy/paste doesn't work, and tests hang? Latest master (Windows 10)

### ISSUE THREAD

**Issue by haslam22** [adobe/brackets#12862]
### Prerequisites

* [X] Can you reproduce the problem with `Debug \ Reload Without Extensions`?
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [X] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

Release 1.9 development build 1.9.0-0 (master c77d4f860)

Unsure if this is just me, but I've been trying to develop with Brackets on Windows but it's been really buggy. Copy and paste doesn't work, both through the keys and by right-clicking. The tests also hang after a while and become unresponsive.

I've tried this on two systems (both Windows 10) with the latest Brackets master and a new fork, following the installation process in the "How to hack with brackets" guide.

Console output when loading Brackets:
> less-2.5.1.min.js:13 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
less-2.5.1.min.js:13 rendered file:///C:/Program%20Files%20(x86)/Brackets/dev/src/styles/brackets.less successfully.
less-2.5.1.min.js:13 css for file:///C:/Program%20Files%20(x86)/Brackets/dev/src/styles/brackets.less generated in 672ms
less-2.5.1.min.js:13 less has finished. css generated in 672ms
react.js:6541 Download the React DevTools for a better development experience: https://fb.me/react-devtools
DeprecationWarning.js:88 PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/preferences/PreferencesManager.js:323:28)
    at Object.<anonymous> (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/utils/Resizer.js:557:24)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
DocumentCommandHandlers.js:1698 Brackets reloaded with extensions disabled
KeyBindingManager.js:578 Fail to nomalize Cmd-Shift-]
KeyBindingManager.js:578 Fail to nomalize Cmd-Shift-[
NodeSocketTransport.js:84 NodeSocketTransport - start

### Steps to Reproduce

1. Install Brackets on Windows, latest 1.7 release from brackets.io
2. Fork the repo, git clone, git submodule update --init and npm install, add remote upstream
3. Run tools/setup_for_hacking.bat
4. Open Brackets, copy and paste doesn't work and tests hang
5. Revert to 1.7 release and things work again

**Expected behavior:** [What you expected to happen]
Copy and paste works
Tests complete

**Actual behavior:** [What actually happened]
Copy and paste doesn't work
Tests hang and Brackets becomes unresponsive

### Versions

Please include the OS and what version of the OS you're running.

Windows 10 10586.494 (Laptop, old Windows 10 build)
Windows 10 14393.351 (Desktop, latest Windows 10 build)

Please include the version of Brackets. You can find it under `Help \ About Brackets`

Release 1.9 development build 1.9.0-0 (master c77d4f860)

![brackets-error-1](https://cloud.githubusercontent.com/assets/9113599/19839390/9eef7b6e-9ed8-11e6-83c4-0967da10f316.png)
![brackets-error-2](https://cloud.githubusercontent.com/assets/9113599/19839391/9ef291be-9ed8-11e6-8f10-620d670d26fe.png)

Anyone know what the problem might be?

**Comment by ficristo** [comment]
Hi @haslam22, since brackets 1.8 you need to have a newer version of the shell. 
While waiting for 1.8 release you can use a prerelease: https://github.com/adobe/brackets/releases/tag/release-1.8-prerelease
This should solve your copy/paste issue.

Again, with 1.8 `npm install` is a necessary step to run but seems you have run it. 👍 

Brackets test windows are known to have problems...
Running All / All test is most likely to end in your situation. I usually run only the specific suite I need: Unit, Integration, Live Preview, ...
Even in this way it is possible to hit this problem.
If you were able to run All / All tests in 1.7 I'll be quite surprised.

**Comment by haslam22** [comment]
@ficristo Ahh thank you. I had no idea what was going on but the 1.8 prerelease fixed the issues. I'll also be aware of the test thing. This can be closed whenever.
