### ISSUE TITLE
How to get/apply a bolder font version

### ISSUE THREAD

**Issue by Madebym** [adobe/brackets#12860]
I just can't get bold fonts to show in Brackets. For example, I have Fira Mono, Input Mono, Mononoki, all in bold versions installed on my computer(Win10 64bit).

I tried all possible word combinations, none of them displayed that particular font(via change font in view>themes). What is the correct way of writing font family?

Btw. I have no such issues on other editors.

**Comment by petetnt** [comment]
Hi @Madebym,

the font families should be 

- Quoted
- Written as they should be defined as a font family.

For example Fira Mono Bold should be `'Fira Mono Bold'`.

**Comment by Madebym** [comment]
@petetnt Thanks for the help, but that is the way I've been doing it, along with other possible combinations, e.g. `Fira Mono-Bold`, `FiraMonoBold`, etc.

It doesn't work. Nor with Fira Mono, Input Mono, or any other typeface I tried.

Are you able to display `Fira Mono Bold` written like this on your end?

**Comment by mmcken3** [comment]
I am running a Mac OS 10.10.5 and I can get this font-family to work in Brackets. I am using it by editing the CSS element. So for example...

p {
    font-family: Fira Mono Bold;
}

Could you possibly copy and paste or screenshot the snippet of code where you are trying to use this font?

**Comment by Madebym** [comment]
@mmcken3 I change fonts via `view > themes`. There is a setting called `'Font Family'` there.

This works, I get the regular version to display: 
`'Fira Mono', ＭＳ ゴシック, 'MS Gothic', monospace`

This doesn't work, and I have bolder versions installed on my system.
`'Fira Mono Bold', ＭＳ ゴシック, 'MS Gothic', monospace`

**Comment by ficristo** [comment]
@Madebym I confirm your behaviour.
But it seems the expected one to me: when set `'Fira Mono'` as font-family the bold variant is used for bold elements.

Messing around with the code, adding something like the following seems to work.
```css
.CodeMirror{ 
  /* This is added through View \ Theme */
  font-family: 'Fira Mono', 'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace;
  /* Use always the bold variant */
  font-weight: bold
}
```
@petetnt maybe we could add an option in the Theme settings?

**Comment by Madebym** [comment]
@ficristo The exact thing you wrote already crossed my mind, the thing that was bugging me is how the default font family works written this way : `SourceCodePro-Medium`.

Are we seeing the regular version or the medium? If it works like you said, then there must be `font-weight: 500` specified somewhere in the stylesheets. Or it picks the medium font directly, without the need to specify `font-weight`?

 All in all, this is all a bit of confusing to me !!

**Comment by ficristo** [comment]
I double clicked on the ttf files and saw that for `Fira Mono` and `Fira Mono Bold` the name is the same: `Fira Mono`. For `Fira Mono Medium` the name is `Fira Mono Medium`. And this one can be used in the theme settings.
I guess it is possible to set some sort of "baseline" for the font (regular, medium) and then you have all the variants (light, bold, ...). You can use only the baseline, CSS picks the correct variant.

**Comment by petetnt** [comment]
Yup, looking further I think Fira Mono only has different font weights, with bold being 700.

**Comment by Madebym** [comment]
Ok, guess the only way to apply the bold version is through overwriting editor stylesheets, either by hand or with an extension like https://github.com/tobibeer/brackets-custom-css.
