### ISSUE TITLE
Can Brackets be used for commercial purpose ?

### ISSUE THREAD

**Issue by user-12345** [adobe/brackets#12874]
First off, thumbs up for the incredible editor, Brackets.

### My commercial activities might include:
1) creating and selling WordPress based themes and WordPress based plugins.
2) creating and selling other software.

### My questions is:
1) can i use Brackets for commercial purpose stated above ?
2) can all Brackets themes and extensions be used for commercial purpose stated above ?

Please, kindly answer the questions as numbered.
It would be nice if someone from Brackets could answer me that.

Thank you,
Regards.

**Comment by manomoreno** [comment]
For any software you use, I recommend reading its license. In case of public repositories in Github, they are all open source. If you want to check for any specific license here, look for the LICENSE file in the root directory of the project.

Please, take a look at this link https://opensource.org/faq as well.

**Comment by petetnt** [comment]
Are you using Brackets as a base for the said software or creating the said software with Brackets? Anyway the answer is yes, as long as (as pointed out by @manomoreno) you comply the [LICENSE](https://github.com/adobe/brackets/blob/master/LICENSE) provided by Brackets. It's a standard MIT license.

**Comment by user-12345** [comment]
Dear petetnt, Thank you very much. Actually i will use Brackets only for creating the files and directories for the software and writing code for the software.

**Comment by petetnt** [comment]
@user-12345 you are welcome! Happy "Brackets"ing 👍
