### ISSUE TITLE
Dilato:Core: Copyright information is still displayed for Copyright 2012.

### ISSUE THREAD

**Issue by dil05621** [adobe/brackets#12871]
1.Launch the Brackets
2.Click Help
3.Click About Brackets on the drop-down of help menu.
4.Observe the string"Copyright 2012 - present Adobe Systems Incorporated and its licensors. All rights reserved."
Result: Copyright information is still displayed for Copyright 2012.
Expect: Copyright information is displayed for Copyright 2016.

![copyright](https://cloud.githubusercontent.com/assets/23234219/19961343/1d789e54-a1ed-11e6-87df-7920ac581a39.png)

**Comment by Zhanxin** [comment]
This is issue has been fixed when we tested release 1.7 build, and reproduce now, please check: https://github.com/adobe/brackets/issues/12268

**Comment by petetnt** [comment]
The clause was changed to `original year - present` to prevent unneeded license changes every year etc.

**Comment by Zhanxin** [comment]
Thanks for your explanation. Close this.
