### ISSUE TITLE
Error when installing in Lubuntu 16.04

### ISSUE THREAD

**Issue by DiegoTc** [adobe/brackets#12875]
### Description
Getting the following trying to install brackets.
`Error dependency is not satisfiable libgcrypt11 (>= 1.4.5)
`
Installation shouldn't cause any issue at the moment of executing the deb.

### Steps to Reproduce

1. Download Brackets Deb
2. Install the deb
3. Error appears

**Expected behavior:**  Brackets should be install with no complications

**Actual behavior:** Brackets isn't being installed.

### Versions

Please include the OS and what version of the OS you're running. Ubuntu 16.04.1 LTS

Please include the version of Brackets. 1.7.32

**Comment by zaggino** [comment]
@DiegoTc try this link from README: https://nathanjplummer.github.io/Brackets

**Comment by ficristo** [comment]
Dupe of #10255
Usual suggestion, give a try to https://github.com/zaggino/brackets-electron

**Comment by ErikThiart** [comment]
Same issue seems brackets relies on outdated software.
