### ISSUE TITLE
Brackets asking for adobe flash, even after it has been installed

### ISSUE THREAD

**Issue by Hablion** [adobe/brackets#12884]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

I am attempting to add the extension Pixlr, once installed attempted to run it, receive the: Adobe Flash Player not installed, Install adobe Flash player now! pop.  
after installing and resetting the computer the same pop up happens, i am unable to tell brackets adobe is installed in my computer.

### Steps to Reproduce

1. [Installed Pixlr]

2. [Installed Adobe]
3. [Tried to open image.]

**Expected behavior:** [What you expected to happen]
I expected for Pixlr to open and edit an image.
**Actual behavior:** [What actually happened]
After installing Adobe Flash player, it keeps asking for me to install adobe flash player.

### Versions

Please include the OS and what version of the OS you're running.
Windows 10
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and 
Linux) or `Brackets -> About Brackets` (macOS)
Release 1.7 build 1.70.-16898

**Comment by petetnt** [comment]
Hi @Hablion,

this issue is specific to the `brackets-pixlr` extension and should be reported to the `brackets-pixlr` repository at https://github.com/dnbard/brackets-pixlr. Feel free to follow up if you need any help or have other questions regarding the issue though 👍
