### ISSUE TITLE
Jasmine Spec Runner Not Working??

### ISSUE THREAD

**Issue by jmiller13** [adobe/brackets#12881]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

The Jasmine Spec Runner does not seem to be working for me. All I get is a blank white page with a toolbar on top and nothing else, the tabs don't work and I can't close the window after it is opened. If there's something else I need to do to get it running I would understand but I haven't found any documentation that says to do so.

### Steps to Reproduce

1. Uninstall and Reinstall brackets
2. Delete current cloned repo and clone it again
3. Repeat steps on "How to Hack on Brackets" wiki
4. Opened up Jasmine Spec Runner

**Expected behavior:** [What you expected to happen]
Tests to show up, tab bar able to change page and ability to close window

**Actual behavior:** [What actually happened]
Spec Runner doesn't seem to load, get a blank white page under the toolbar, doesn't seem to load and can't close the window.

### Versions

Running Windows 10 and release 1.8 development build 1.8.0-0 of brackets.

**Comment by petetnt** [comment]
Another case of the mysterious blank page with the runner. For some running `npm install` again has helped, for me just relaunching Brackets usually helps. Can you open the developers tools (in the Jasmine window) and see if there's any errors?

**Comment by jmiller13** [comment]
I can not, no. I'll run npm install again to see if it changes anything, I feel like I've done it multiple times, but I'll try again to make sure.

**Comment by zaggino** [comment]
also run `git submodule update --init` too if you missed that one (before npm install)

**Comment by jmiller13** [comment]
Running npm install again worked. Thanks for the help!

**Comment by petetnt** [comment]
Glad you got it working :+1:
