### ISSUE TITLE
When I open a .html file it goes straight to preview and I cannot see the code

### ISSUE THREAD

**Issue by steven-fernandez** [adobe/brackets#12888]
### Description

When I open a .html file it goes straight to preview and I cannot see the code

### Steps to Reproduce

1. Open the project folder
2. Select a .html file

**Expected behavior:** I should be able to see the source code

**Actual behavior:** I only saw the page preview

### Versions

Version 0.0.8
OSX

**Comment by ficristo** [comment]
> Version 0.0.8

If this is correct, it's really an outdated version. You should download 1.8.0.

Otherwise, do you have any extensions? Are you run `Debug \ Reload without extensions` and verified if you still can reproduce?

**Comment by ficristo** [comment]
I cannot reproduce.
