### ISSUE TITLE
Brackets freezes when I use Ctrl-X shortcut

### ISSUE THREAD

**Issue by IoannesBracciano** [adobe/brackets#12882]
Hello, I'm using Brackets on Elementary OS loki and I've stumbled upon a bug. Basically when I am editing a file and use the Ctrl-X shortcut to cut some text, the window becomes totally unresponsive and in addition it won't even close. This behaviour seems to persist even without extensions loaded. Reproducing the problem is quite simple:
* Open a file in Brackets
* Select some text
* Hit Ctrl-X

**Comment by petetnt** [comment]
Hi @IoannesBracciano ,

can you open the DevTools (Debug -> Open Developer Tools) and seeing if there are any errors in the console-tab. Also could you state your operating system and Brackets version?

**Comment by IoannesBracciano** [comment]
I've tried to reproduce the issue with developer tools open, after having put my laptop to sleep, and suddenly everything seems to be working fine!
I am using Elementary OS loki, it is based on ubuntu 16.04.
Brackets reports Release 1.7 experimental build 1.7.0-16898 (release b0a363b71)
I am going to report back when I encounter the issue again.

**Comment by ficristo** [comment]
> everything seems to be working fine

Closing for now.
