### ISSUE TITLE
Updating from v1.7 to v1.8--uninstall required?

### ISSUE THREAD

**Issue by quantbo** [adobe/brackets#12893]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description
The editor today notified me that an update to v1.8 is available. Does this require first uninstalling v1.7, or can a user simply run the update with v1.7 in place?
Platform is Windows 7.
Current brackets version installed:
Release 1.7 build 1.7.0-16898 (release b0a363b71) 
build timestamp: Wed Jun 08 2016 12:27:56 GMT+0100

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by IiroP** [comment]
No need to unistall, just run 1.8 installer

**Comment by ficristo** [comment]
As @IiroP said you can install the new version on top of the old one, without uninstall.
