### ISSUE TITLE
1.8 not working

### ISSUE THREAD

**Issue by carinlynchin** [adobe/brackets#12896]
### Prerequisites

* [ NO ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ NO ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ NO ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

connecting to sftp isn't working...it connects but doesn't display any of the files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by Tusko** [comment]
+1

**Comment by ficristo** [comment]
Please open an issue on the extension repository.
