### ISSUE TITLE
Brackets 1.8 - Brackets Git failed to connect to NodeJS

### ISSUE THREAD

**Issue by Cactusx09** [adobe/brackets#12897]
### Description
![image](https://cloud.githubusercontent.com/assets/9021479/20208923/e3751526-a7f9-11e6-8d5f-60f3258bdc11.png)

[Description of the bug or feature]

### Steps to Reproduce

1. Just open Brackets 1.8 with Brackets-git plugin

### Versions
Windows 10
Brackets 1.8

**Comment by Cactusx09** [comment]
Fix this trough reinstall brackets and brackets-git

**Comment by ficristo** [comment]
Happy to hear you were able to fix it.
Closing as extension problem.
