### ISSUE TITLE
Brackets is not working anymore since 1.8 install

### ISSUE THREAD

**Issue by AndrewWJordan** [adobe/brackets#12894]
Completed 1.8 msi install and since then Brackets opens, but it will not do anything.  Even the close button doesn't work.  If I click Open or Open File, nothing happens.  Uninstalled and tried to reinstall 1.7 MSI, and am still getting the same issues. Was using Brackets without an issue this morning until the initial install. 

### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by ficristo** [comment]
Could you try to delete the [Cache Folder](https://github.com/adobe/brackets/wiki/Cache-Folder)?
Keep in mind, as written in the link, this will reset all of your preferences.

**Comment by AndrewWJordan** [comment]
Thank you!  I cleared the cache, but it did not have any effect. I instead deleted the entire Brackets directory that was in my Roaming folder and then reinstalled 1.8.  It appears to be working now. Thanks, Andrew Jordan
Software Engineer
Marist College 
3399 North Road
Poughkeepsie, NY 12601
845-575-3509-----ficristo <notifications@github.com> wrote: -----To: adobe/brackets <brackets@noreply.github.com>From: ficristo <notifications@github.com>Date: 11/12/2016 04:48AMCc: Andrew W Jordan <andrew.jordan@marist.edu>, Author <author@noreply.github.com>Subject: Re: [adobe/brackets] Brackets is not working anymore since 1.8 install (#12894)Could you try to delete the Cache Folder?
Keep in mind, as written in the link, this will reset all of your preferences.

�You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ficristo** [comment]
> It appears to be working now

👍

**Comment by murillojohn** [comment]
Hi @ficristo ,

I just had the same problem with my recent installation of Brackets 1.8 on my Windows 10 laptop. After installing it and running it, it wasn't responding to any of my actions. I removed the "Brackets" folder from the path "...AppData\Roaming", and now Brackets 1.8 is working correctly =) 

Thank you for such a great code editor! Keep up the good work.
