### ISSUE TITLE
1.8 extract

### ISSUE THREAD

**Issue by gultyaev** [adobe/brackets#12899]
Extract error "An error occurred when trying to view the folder files".

Not works after update to 1.8

**Comment by SkyAx** [comment]
I have the same problem. 
Before when I drag and drop files into this area, the following:
![error](https://cloud.githubusercontent.com/assets/15022782/20219868/4c410a14-a83c-11e6-9fe3-0be0bd53526f.png)

**Comment by ficristo** [comment]
Extract is not supported anymore within Brackets.
http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/

**Comment by federojoavellaneda** [comment]
OMG Is the real reason why he used Brackets

**Comment by gultyaev** [comment]
Yep. Because it is most conveniently.

**Comment by AyratGaliev** [comment]
The problem in the new version node.exe located in the installed folder Brackets (C:\Program Files (x86)\Brackets). You need to replace the new version node.exe on the old version node.exe of Brackets v1.7.

**Comment by SkyAx** [comment]
How can I fix it on ubuntu 16.04?
