### ISSUE TITLE
I tried to install 1.8 but I can't because the brackets folder has a different permission. The first version which I had installed was 1.7 and now I have no permission to do nothing.

### ISSUE THREAD

**Issue by rodrigolossio** [adobe/brackets#12895]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by swmitra** [comment]
@rodrigolossio Can you please let us know about the permission issue in details? What kind of error you are seeing? Which platform you are trying to install Brackets on ?

I would request you to set required permission to a folder first and then try to install brackets in that folder by pointing that folder in the installer dialog.

**Comment by adrian-wright** [comment]
I have had a similar problem. I have been using brackets 1.7 on my windows 10 laptop. I was prompted to update to 1.8 and when trying to update the installer is telling me that I need administrator privileges; I am the administrator. "the installer has insufficient privileges to access this directory: C:\program files (x86)\brackets. The installation cannot continue. Log on as administrator ....."
I cannot access 1.7 either.
thanks

**Comment by petetnt** [comment]
Does this still occur?

**Comment by rodrigolossio** [comment]
No, I changed my SSD and newers versions is working good

2018-01-21 14:38 GMT-02:00 Pete Nykänen <notifications@github.com>:

**Comment by petetnt** [comment]
Thanks @rodrigolossio !
