### ISSUE TITLE
Cursor Problems, brackets gets slow

### ISSUE THREAD

**Issue by YoruNoTori** [adobe/brackets#12901]
I ve been working with brackets since their firt release, I didn´t have any issue at all, in version 1.7 it was terrible that I couldn´t go back steps my code when I used javascript, now in version 1.8, my project started get slower in code editing, and my javascript code continues having same sort of issues, what is going on guys? this was supposed to be the best ide ever made!

**Comment by ficristo** [comment]
> couldn´t go back steps my code
If you are talking about Ctrl-Z issue, I really hope it is fixed in 1.8

> my javascript code continues having same sort of issues
Could you elaborate?

**Comment by ficristo** [comment]
Since there wasn't an answer I close this.
There are other issues about performance jut look for the label `performance`.
