### ISSUE TITLE
An error occurred when trying to view the folder files

### ISSUE THREAD

**Issue by monarchvlad** [adobe/brackets#12906]
How can i fix it?
![image](https://cloud.githubusercontent.com/assets/13378944/20239508/6994a144-a912-11e6-80b6-51313afdeed6.png)

**Comment by tanguyvda** [comment]
Same problem here while moving to brackets 1.8. Had to go back on 1.7.

To go further, console was showing a lot of node error. (use of GLOBAL deprecated, node server stopping, couldn't load ws.localhost:port, node was still there in my task manager.) 

It was a fresh brackets 1.8 install with extract and no other plugin.

**Comment by monarchvlad** [comment]
Well, I go back on 1.7 and problem is solved, but I'll never be able of using next versions of brackets ?

**Comment by joedawalker** [comment]
I had the exact same issue and had to go back to 1.7 last week.

**Comment by ficristo** [comment]
Extract is not supported anymore within Brackets.
http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/

@swmitra @rbharti
Is still the extension supposed to work? If Adobe doesn't want to mantain it anymore, and the infrastructure is still available, can be "donated" to the community?

**Comment by swmitra** [comment]
@ficristo I will ask @rbharti to answer this on committer channel in slack as he is not on Github. As far as I know Extract workflow is part of creative cloud and offered with Dreamweaver. So If someone has to use Extracts for web development, then the option is to use Dreamweaver. 

In this case, as extract plugin used to get copied to user extension folder, after the recent install it's still remaining there but non functional. This extension is not supposed to work from Brackets 1.6 onward.

**Comment by rajnishb** [comment]
@ficristo is right. Extract service is no longer supported. The infrastructure is available only for requests from Dreamweaver.

**Comment by swmitra** [comment]
Closing the issue.
