### ISSUE TITLE
Plugins no install on brackets new version

### ISSUE THREAD

**Issue by MD-Nayeem** [adobe/brackets#12907]
Plugins no install on brackets new version . 
![1](https://cloud.githubusercontent.com/assets/22129078/20240107/6199fad4-a93a-11e6-8624-16f80357a04e.jpg)

**Comment by swmitra** [comment]
@MD-Nayeem Please tell us more about the problem. 
* Do you have a network proxy set? 
* Do you work with a authentication server first to connect to internet?  
* Are you able to open [Brackets Extension Registry](https://brackets-registry.aboutweb.com/) from browser?

**Comment by ficristo** [comment]
If you are on a 32 bit platform could you try this workaround?
https://github.com/adobe/brackets/issues/12918#issuecomment-261337603

**Comment by MD-Nayeem** [comment]
@swmitra
1 no
2 I am using wi-fi connection
3 yes

**Comment by MD-Nayeem** [comment]
@ficristo
Thank You it's working
