### ISSUE TITLE
Brakets right click menu is too big

### ISSUE THREAD

**Issue by Cichyy7** [adobe/brackets#12908]
My right click menu is way to big. I have lot of extensions and not all of options from right click menu are shown on my screen. Is there a way to split right click menu in two parts or fix this problem in some other way? 
![problem1](https://cloud.githubusercontent.com/assets/16727308/20240494/d9529f0c-a919-11e6-985d-6429b7f25b54.png)

**Comment by Denisov21** [comment]
I think you also installed my extension called "Pop-up menu"!
If you have installed "Pop-up menu" update to the new version!

**Comment by swmitra** [comment]
Closing this as not a Brackets issue.
