### ISSUE TITLE
Brackets 1.8 : Failed to connect to node

### ISSUE THREAD

**Issue by Tusko** [adobe/brackets#12904]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [X] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

`[node-info 6:45:13 PM] [Server] stopping
/filesystem/FileSystem.js:965 File watchers went offline!
/extensibility/Package.js:533 [Extensions] Failed to connect to node Arguments[1]0: "cleanup"callee: (...)get callee: ThrowTypeError()set callee: ThrowTypeError()caller: (...)get caller: ThrowTypeError()set caller: ThrowTypeError()length: 1Symbol(Symbol.iterator): values()__proto__: Object(anonymous function) @ /extensibility/Package.js:533
/utils/EventDispatcher.js:121 Possible memory leak: 18 'activeEditorChange' listeners attached to Objecton @ /utils/EventDispatcher.js:121
documents.js:436 Download the Brackets Git for a better development experience: https://github.com/zaggino/brackets-git`

### Steps to Reproduce

1. Open Brackets
2. Have error `File watchers went offline!`
2. The next error `Failed to connect to node Arguments[1]0: "cleanup"callee: (...)get callee:.......`

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

MacOS Sierra 10.12.1
Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4)

**Comment by ficristo** [comment]
Are those logs from a `Debug -> Reload Without Extensions` session?
Could you try to move all your extension in the disabled folder?
You can find extensions location here: https://github.com/adobe/brackets/wiki/Extension-Locations#user-extensions-folder. Up of a level there is a disabled folder.

**Comment by ficristo** [comment]
I close this issue since there wasn't an answer.
