### ISSUE TITLE
Feature Request (color picker/pallet )

### ISSUE THREAD

**Issue by MandarSant** [adobe/brackets#12913]
I use dreamweaver for coding i also like Brackets but what makes me to stick to dreamweaver is its color picker/pallet(While Coding CSS) so i request Brackets dev to create the dreamweaver like color picker/pallet for Brackets 

![47aa920e-a85a-11e6-8ff5-0cd918fdf0e3](https://cloud.githubusercontent.com/assets/20091634/20292224/e6105ad2-ab11-11e6-83bf-f6d2443d4a12.png)

**Comment by swmitra** [comment]
@MandarSant Thanks for reaching out to us. If you look closely there are only 2 feature differences between the DW color picker and Brackets color picker. 
* Custom pallet - favorite color shortcuts 
* Eye dropper - To pick colors from anyplace in the display

There are lot of color pickers provided by some popular JS libraries which can add the other missing features like preview, grayscale slider and favorite color icons. But none of these libraries offer an eye dropper. Reason? Implementation complexity. 

I would request you to try some of the Brackets plugins for color picker (based of jquery color picker).

**Comment by MandarSant** [comment]
@swmitra nearear to DW color picker is Exceptable i am not insiste for exactly same  but out of 100% 40% is exceptable

**Comment by meeple142** [comment]
@swmitra if you have your courser in a color like `#1F1F1F` or `#FFF`  or in between the parenthesis in `rbg(0,0,0)` then push `Ctrl + e`  it will open a color picker that does most all of those things. 
(tested in js, html and css file)
