### ISSUE TITLE
File lost after linux failed to resume from suspesion

### ISSUE THREAD

**Issue by nico22sa** [adobe/brackets#12917]
Hello
1)I saved the file in a folder in desktop.
2) put linux ubuntu 14.04 in suspension mode
3) due to a battery failure, resume failed too.
4) after recovery file was lost from brackets history and from computer
5) someone told me to check the tmp files of brackets but have no idea where to find them
Brackets
Release 1.6 experimental build 1.6.0-16680 (release 3df0ac6fa) 

* [have no extension installed ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [yes ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [yes ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

**Comment by ficristo** [comment]
Can you reproduce if you simply save the file and go in suspension mode?
I don't think we have a tmp folder, so if you cannot reproduce it seems to me the problem was the battery failure.

**Comment by nico22sa** [comment]
It was a battery failure for sure. It ran out of energy while suspended.
Hole linux recovered from failed resume suspension mode. But brackets just
dropped out the file. I am trying to locate the file, but do not know where.

thank you for answering.

2016-11-24 15:31 GMT-03:00 ficristo <notifications@github.com>:
