### ISSUE TITLE
Language .logs (synthax highlighting for log files) for Brackets

### ISSUE THREAD

**Issue by AgamlaRage** [adobe/brackets#12926]
I would like to propose this as a feature, or a potential extension.

I can have this kind of interface in Atom, with this package [https://github.com/mrodalgaard/language-log](language-log).
There is a filter input (different of searching is great for log reading.
You can also filter by level (Warning, Error, ...etc).

![sans titre](https://cloud.githubusercontent.com/assets/15155827/20440982/c03c8e76-adc2-11e6-9225-fcd1ecd7fa2d.png)

Synthax higlighting :
- date format
- strings
- http/local links
- Warning, Errors, ... etc in a unique color

**Comment by swmitra** [comment]
@AgamlaRage As @petetnt has already marked this as an Extension Idea, there is nothing which can be done from Brackets core. You can write an extension by using a CodeMirror overlay parser and some custom styling to have the desired code coloring for log files.

**Comment by swmitra** [comment]
Closing the issue.

**Comment by AgamlaRage** [comment]
@swmitra  @petetnt 
As you recommended, I started to wrote an extension to achieve this feature.

Here is the repository [brackets-language-log](https://github.com/AgamlaRage/brackets-language-log).
I called it **Language Log** into brackets-registry

This is my first brackets extension, and I didn't found all the regexp I need to release a more usefull version. Please be indulgent :)

Is that possible to let this issue into the **Extension Idea** label for the moment, so some other people can find it and maybe participate/help to the extension development ?
