### ISSUE TITLE
Feature Request (Package Website)

### ISSUE THREAD

**Issue by MandarSant** [adobe/brackets#12923]
It is very convinient to have brackets package/Theme  website like

- [Atom](atom.io)
- [VSCode](code.visualstudio.com) also like 
-  [Sublime Text](packagecontrol.io)

**Comment by TWOWhite** [comment]
It is here https://brackets-registry.aboutweb.com/

**Comment by MandarSant** [comment]
@TWOWhite is it official website?

**Comment by petetnt** [comment]
@MandarSant it is. It's also the interface for adding, updating and removing extensions.

There's also http://brackets.dnbard.com/ which ranks the extensions by downloads and such.

Closing as answered, but feel free to ask more questions if needed or send suggestions! 👍

**Comment by MandarSant** [comment]
@petetnt  http://brackets.dnbard.com/ is down

**Comment by petetnt** [comment]
Thanks notifying @MandarSant, pinging @dnbard

**Comment by dnbard** [comment]
@petetnt  Thanks for notification.
This site have some external issues with database. I'm working on resolving them atm.

**Comment by MandarSant** [comment]
@dnbard please inform me after website is up...!
