### ISSUE TITLE
typing a tag gives an autocomplete </a> next to it

### ISSUE THREAD

**Issue by lawfets** [adobe/brackets#12938]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
          yes I have no extentions
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
         yes, didn't find the same problem elsewhere
* [x] Did you read the [Troubleshooting guide]
         yes, I did(https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description
what ever tag I use in a html page (`<p> <div> <li>` ...) it always autocompletes with `</a>.`
It doesn't give the right closing tag.
[Description of the bug or feature]

### Steps to Reproduce
just start a html file with a body and type any tag in it.
1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

if for instance you type `<p>` it'll autocomplete `</p>`

**Actual behavior:** [What actually happened]
if for instance you type `<p>` it'll autocomplete `</a>` without asking.
### Versions

Windows 10 home edition 64 bits x64 processor
sprint 8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) 
build timestamp: Wed Nov 02 2016 12:07:29 GMT+0000

**Comment by petetnt** [comment]
Hi @lawfets,

pretty weird. Could not reproduce myself on a Windows 10 nor MacOS machines. Could you try reinstalling the latest Brackets from http://brackets.io? Could you also give us a sample file that shows these issues. 

Thanks!

**Comment by lawfets** [comment]
wel, to be honest, I cannot reproduce it either anymore, don't know why I had it in the first place, it just started randomly and all of a sudden it didn't stop using the end a tag.
Now I cleaned my computer with ccleaner and the problem is over.

Sorry for the disturbance.

**Comment by petetnt** [comment]
No problem, glad you got it fixes. Feel free to reopen if it comes back!
