### ISSUE TITLE
brackets duplicate line issue

### ISSUE THREAD

**Issue by ToBeM12** [adobe/brackets#12935]
sometimes when i use (ctr+d) to duplicate line it just shift the line to the right (like i pressed tap).
how to solve this

**Comment by petetnt** [comment]
Hi @ToBeM12, 

can you give us a repeatable small sample? Does this occur without any extensions (Debug -> Launch Without Extensions)?

**Comment by ficristo** [comment]
I close this issue since there wasn't an answer.
