### ISSUE TITLE
CodeMirror update

### ISSUE THREAD

**Issue by zaggino** [adobe/brackets#12937]
@adobe/brackets-committers 

Latest master of CodeMirror doesn't contain built `codemirror.js` in the lib directory: https://github.com/codemirror/CodeMirror/tree/master/lib

Since we'll definitely want to upgrade for next version there are two options:

a) add a task to our grunt scripts that'll build `codemirror.js` by calling `npm run build` in the CodeMirror submodule
b) use CodeMirror as npm dependency

Let me know which solution you prefer.

**Comment by petetnt** [comment]
Voting for b)

**Comment by swmitra** [comment]
My vote for 'b'.
Off topic - We should do the same even for 'tern'.

**Comment by zaggino** [comment]
@petetnt @swmitra 
Please also have a look at related https://github.com/adobe/brackets/pull/12933
confirmed to work in https://github.com/adobe/brackets/issues/12898#issuecomment-262322859

**Comment by zaggino** [comment]
PR here https://github.com/adobe/brackets/pull/12940

**Comment by ficristo** [comment]
Done in https://github.com/adobe/brackets/pull/12972
@swmitra Acorn and Tern are already installed from npm, see https://github.com/adobe/brackets/pull/11569
It would be nice to also look at https://github.com/adobe/brackets/issues/12744
