### ISSUE TITLE
Open recently closed file

### ISSUE THREAD

**Issue by rafaqf** [adobe/brackets#12943]
### Description

Sometimes you close a file that you don't want to close. It would be nice to have something like on chrome or sublime, a command like 'ctrl + shift + t' to open again the last file closed. 

### Versions

Mac Os El Capitan, Brackets Release 1.7 versión 1.7.0-16898 (release b0a363b71)

**Comment by petetnt** [comment]
Hi @rafaqf,

you can re-open Recently Opened files via File -> Open Recent (or CTRL+O). Files removed from the working space should be somewhat more transparent than the ones still open.
