### ISSUE TITLE
Feature Request Automaticaly add Script tag also link  tag for external libraries like for jquery,Bootstrap or our own external css/js etc

### ISSUE THREAD

**Issue by MandarSant** [adobe/brackets#12947]
I am requesting for feature that whenever we download external libraries like jquey,bootstrap and etc....
we have to add script and also link  tag to html so when we download it the script should automaticaly generated insted of typing for save time same feature can work for external our own css/javascript and also same for cdn link insted of copy paste the tag will be auto generated

i am just a beginer so i cant create a screen shot

**Comment by zaggino** [comment]
How will Brackets know that you downloaded a script?
How will Brackets figure out into which html the script should be inserted?

**Comment by MandarSant** [comment]
@zaggino in our project folder what or which ever `css` or` js` file if present in folder will be linked and in case of buld systems like `grunt ` &` gulp` there will be settings in` .json` file

**Comment by zaggino** [comment]
that's too specific to be considered as an editor feature, but you could write it as an extension for brackets if you need it

**Comment by MandarSant** [comment]
@zaggino  it can be also done by just draging file from project view in the head tag and link or script tag with attr will be generated

**Comment by zaggino** [comment]
again, it's too difficult to get it right, there're hundreds of frameworks, build systems, etc 
the editor would have to know exactly what your setup is to get it right and the amount of effort doesn't seem to satisfy saving to write a line of code

**Comment by MandarSant** [comment]
@zaggino but this is the feature from visual studio how there is posible

**Comment by pelatx** [comment]
@MandarSant I've made an extension that has some of the functionality you want. You must have downloaded the files, or created in your project. But then, you just have to right-click on the CSS or Javascript file, select "Link File" and the link is inserted in the focused  HTML document with the correct relative path. You may find it useful.
