### ISSUE TITLE
Feature suggestion: Indent cleanup.

### ISSUE THREAD

**Issue by stmaus** [adobe/brackets#12945]
After a lot of editing the indents can get very misaligned. Also a smart indent cleanup feature would allow you to see when your applying a closing tab inappropriately. For example have too many/few </div>s.

**Comment by petetnt** [comment]
Hi @stmaus, 

there's lots of auto-indent options available via the Extension Manager.  For example I am using this very simple one https://github.com/ahuth/brackets-indentator daily, but there are more robust options available too. 

You can find them from File -> Extension Manager and searching for Indent.
