### ISSUE TITLE
I broke Brackets and need some assistance.

### ISSUE THREAD

**Issue by nedredmond** [adobe/brackets#12956]
While trying to open a new project folder, I accidentally opened an entire shared server at work. I'm sure I've maxed out the program memory, and nothing in the Brackets window will respond. I've tried opening a new Brackets window, but it just comes up blank. I've tried opening the folder again, but it doesn't seem to work. Is there anything I can do other than deleting and re-installing Brackets?

Thanks.

**Comment by nedredmond** [comment]
After waiting half an hour after opening Brackets to the public drive, an error message appeared and Brackets closed the directory itself. Thanks anyway!

**Comment by zaggino** [comment]
In case you need it in the future, `Resetting cache & preferences`:
https://github.com/adobe/brackets/wiki/cache-folder#resetting-cache--preferences
