### ISSUE TITLE
Save All not working

### ISSUE THREAD

**Issue by akash-vartak** [adobe/brackets#12954]
The **Save All** option and even it's shortcut ```Ctrl + Alt + S``` doesn't work in Ubutnu14.04 with version of Brackets: ```Release 1.8 experimental build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) 
build timestamp: Wed Nov 09 2016 02:47:52 GMT+0000```

**Comment by petetnt** [comment]
Hi @akash-vartak, can you see any errors in the developer tools console? `Debug -> Show developer tools -> Console`

**Comment by Pk13055** [comment]
@petetnt I've verified that it does indeed not 'save all' using the keyboard shortcut, but does through the drop-down menu. Checked on `Ubuntu 16.04` and `14.04` running brackets `Release 1.8 experimental build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) `

I would like to work on this bug if no-one else is picking it up. (ps - pretty new to open source)

**Comment by petetnt** [comment]
Hi @Pk13055,

That's great! See the article [How to hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) to get started with the Brackets codebase. If you have any questions, feel free to post them here! We also have a [Slack channel](https://brackets.slack.com) for day-to-day communication. (You can join by sending a mail to admin@brackets.io with the subject line `slack registration request` specifying the email addresses you would like to register).

**Comment by Pk13055** [comment]
@petetnt I have setup the codebase as instructed. I would love some help on how I would approach this issue;
I've seen that onClick `save all` invokes `handleFileSaveAll()` as on
[](https://github.com/adobe/brackets/blob/master/src/document/DocumentCommandHandlers.js#L1094) 
which in turn returns `saveAll()` as on
[](https://github.com/adobe/brackets/blob/master/src/document/DocumentCommandHandlers.js#L1059) 
finally leading us to `_saveFileList()`
[](https://github.com/adobe/brackets/blob/master/src/document/DocumentCommandHandlers.js#L1016)
All this checks out; I traced the click of the `Save All` button, and it does do what it's supposed to. This leads me to think that there might be a problem in the `KeyBinding Manager.js`, ie, proper key mapping isn't done when `Ctrl + Alt + S` is pressed. It's definitely registering the press, but doesn't seem to call the `saveAll()` function.
[](https://github.com/adobe/brackets/blob/master/src/command/KeyBindingManager.js)

**Comment by petetnt** [comment]
Hmm, maybe try `console.log`:ing what happens in the keybinding phases from this point forward: https://github.com/adobe/brackets/blob/master/src/command/KeyBindingManager.js#L662

**Comment by haslam22** [comment]
@Pk13055 By default `Ctrl + Alt + S` is mapped to a [system shortcut](http://askubuntu.com/questions/145185/how-to-disable-the-roll-up-shade-keyboard-shortcut-in-gnome-3-after-upgra), so when disabling that it seems to work with me, is it the same in your case?

**Comment by Pk13055** [comment]
@haslam22 Yes, even though the shortcut seems somewhat obsolete. 
@petetnt Would there be a workaround to keep using `Ctrl + Alt + S` without disabling the system shortcut? I think for now at least maybe we could add a pop up or some tooltip text telling users to disable the system shortcut?

**Comment by petetnt** [comment]
@Pk13055 I tried to quickly Google for a solution but didn't find one... as it seems to be a distribution quirk, Adding it to the Brackets Linux guide and pointing users there might be the easiest way out: https://github.com/adobe/brackets/wiki/Brackets-Linux-Guide. If there's a way to catch the shortcut "failing" in Brackets context, it would be nice to show it as `console.warn` in the Developer Tools at least too, but I am not sure if that is possible. 🤔

**Comment by Pk13055** [comment]
@petetnt I don't think there is; I think Brackets does register the key press but since the system shortcut takes higher priority, doesn't do anything about it. I could go ahead with adding the required steps into the wiki; there's this one-line terminal command to disable the shade menu; the shortcut works just fine after disabling.

**Comment by petetnt** [comment]
@Pk13055: great! I think that the wiki is now read-only for non-members of the Adobe org, but if you add the steps below I can add it to the wiki and attribute it to you 👍

**Comment by Pk13055** [comment]
How's this: 
> #Save all keyboard shortcut bug
The save all keyboard shortcut `Ctrl + Alt + S` doesn't work on Linux as it is overshadowed by a system shortcut to disable/enable “roll up” / “shade” on an active window. 
You can enter this command (in the terminal) to disable this shortcut and have `Save All` working:
` gsettings set org.gnome.desktop.wm.keybindings toggle-shaded "['disabled']" `
Alternatively, you can re-map said shortcut to another key group of your choice (for example `Ctrl + Super + S`) with:
` gsettings set org.gnome.desktop.wm.keybindings toggle-shaded "['<Control><Super>s']" `
Note: The `Save All` option from the drop-down menu works without any modification; you can always resort to that in case you don't want to alter the system shortcut.

**Comment by petetnt** [comment]
Added the issue and fix to the wiki https://github.com/adobe/brackets/wiki/Brackets-Linux-Guide#save-all-keyboard-shortcut-issue

Thanks a lot @haslam22 and @Pk13055, closing this one for now.

**Comment by Pk13055** [comment]
Thank you!
