### ISSUE TITLE
libgcrypt11

### ISSUE THREAD

**Issue by garrett85** [adobe/brackets#12960]
Linux Mint 18 64-bit (Cinnamon)

When I try to install this is what I get.

Error: Dependency is not satisfiable: libgcrypt11 (>=1.4.5)

When I search apt-cache this is what I find.

user@mothership ~ $ sudo apt-get install libgcrypt11-dev
[sudo] password for user: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgcrypt11-dev is already the newest version (1.5.4-3+really1.6.5-2ubuntu0.2).
0 upgraded, 0 newly installed, 0 to remove and 40 not upgraded.

**Comment by petetnt** [comment]
Hi @garrett85,

see [this page](https://nathanjplummer.github.io/Brackets/) for workarounds for this issue.

**Comment by garrett85** [comment]
Thanks for your help. That worked perfect.
