### ISSUE TITLE
Dragging an image to window while editing files causes progress loss of unsaved changes

### ISSUE THREAD

**Issue by NixonNixus** [adobe/brackets#12961]
### Description
While editing a html file, i added an image view, rendered live preview and added an image tag, then i tried resizing the browser window and the i accidentally dragged the image from the browser window (chrome)  into brackets window and my project closed and i lost all my unsaved changes.
### Steps to Reproduce

1. Create a new project and add atleast an html file and add a image tag with an image.
2. Render live preview.
3. drag the image to brackets and drop it.
4. ops! you just lost all your project progress.

**Expected behavior:** [At Least should have opened it in a new file window or prompt me to save my changes or a warning that i will loose my progress]

**Actual behavior:** [It just opened the image a a new project dropping all my previous progress]

### Versions
Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) 
build timestamp: Wed Nov 02 2016 12:07:29 GMT+0000
Windows 10 Version 1607(OS Build 14393.222)

**Comment by petetnt** [comment]
Hi @NixonNixus,

pretty sure this is fixed with https://github.com/adobe/brackets/pull/12946, or the PR could be updated to address that too.

**Comment by NixonNixus** [comment]
Just saw it am taking it down

**Comment by petetnt** [comment]
Let's keep it open until it's properly fixes so we can track the issue. 

Thanks for the bug report @NixonNixus 👍

**Comment by petetnt** [comment]
Fixed in #12946
