### ISSUE TITLE
Live preview will not work unless saved #12962

### ISSUE THREAD

**Issue by amunim** [adobe/brackets#12962]
I installed brackets 1.8 only 1 day ago and live preview is not working at all I have to save it to work 
I did not expected that.The only reason I installed brackets was live preview and the html file is not editing live 
And if I check live experimental preview then it gives the error

![image](https://cloud.githubusercontent.com/assets/24316328/20834120/43be0394-b848-11e6-9fc5-2779e1f41662.png)

without live preview 
![untitled](https://cloud.githubusercontent.com/assets/24316328/20834250/2c14f79c-b849-11e6-85d6-7f280312d534.png)

my developer console

![image](https://cloud.githubusercontent.com/assets/24316328/20834272/5318aa8c-b849-11e6-8cd2-8ee89f18d4d1.png)

**Comment by ficristo** [comment]
The error `Error watching project root` is quite worrisome.
Do you have this same error every time you open a new project? Are you running on a Windows 32 bit?
I'm not sure if related to your problem but can create instability and performance issues.

Do you have always that error `Exception in ...` when running LivePreview?

**Comment by Zlind** [comment]
Im getting the exact same errors and no live preview, no highlights

**Comment by ficristo** [comment]
@Zlind could you try this workaround https://github.com/adobe/brackets/issues/12918#issuecomment-261337603? It'll fix the first error.

**Comment by Zlind** [comment]
@ficristo This is what im getting now

https://i.sli.mg/SfU743.jpg

**Comment by amunim** [comment]
Guys congratulation it works on intel xdk now no need for brackets

**Comment by ficristo** [comment]
@Zlind there are two things that comes to my mind: your project is too big or you don't have .NET Framework 4.5 installed.
Since 1.8 we are using https://github.com/Microsoft/vscode-filewatcher-windows which requires .NET.

PS: if you still have problems please open a new issue, is easier to track.
PS2: you can drop images on Github instead of using 3th party sites.
