### ISSUE TITLE
The theme of Brackets 1.8 mismatch the index page of official website.

### ISSUE THREAD

**Issue by huyaxiong** [adobe/brackets#12965]
This is Brackets on my local mac.
![image](https://cloud.githubusercontent.com/assets/6245250/20856472/7a4a2b06-b94a-11e6-9e47-e2d867834fc0.png)

This is from official website.
![image](https://cloud.githubusercontent.com/assets/6245250/20856476/8aaab628-b94a-11e6-9006-fd077f5035ae.png)

The themes are mismatched,I want a theme which like the image of official website,Is there any way I can get the theme?
Also the icons on the right bar mismatch,I only have 2,but the image of official website have 5.

**Comment by haslam22** [comment]
This is the [Coolwater ](https://github.com/Brackets-Themes/Coolwater)theme for Brackets, you can install it from the extension manager, under themes.
To use it, go to View > Themes, and select it from the dropdown list.

**Comment by ficristo** [comment]
The theme and extensions used in the screenshot are not the default one.
There is an issue to change the screenshot https://github.com/adobe/brackets.io/issues/183
As explained by @haslam22 you can try new themes and extensions, some of which add an icon in the sidebar, in the extension manager (`File \ Extension Manager`)
