### ISSUE TITLE
[Feature Request | Portable Linux]

### ISSUE THREAD

**Issue by owenloveclaire** [adobe/brackets#12966]
Can you add a feature such that you can have a portable version on Linux? I am using a persistent Kali Linux booted on an 8GB USB flash drive. It is very useful in my scripts and for my school activivties.

**Comment by ficristo** [comment]
Dupe of #12835
AFAIK there isn't anything officially.
I don't think it supports portable build but you can try https://github.com/zaggino/brackets-electron
