### ISSUE TITLE
Brackets not launching via GUI not shows in applications in  Linux 

### ISSUE THREAD

**Issue by Zainzakie** [adobe/brackets#12969]
![screenshot from 2016-12-05 03-16-55](https://cloud.githubusercontent.com/assets/22868786/20869715/5da33cbc-ba9a-11e6-9577-cc43e0053b94.png)

![screenshot from 2016-12-05 03-17-31](https://cloud.githubusercontent.com/assets/22868786/20869692/e05436da-ba99-11e6-8821-6dc72df67367.png)

Hi,

I have installed brackets on Kali Linux but it isn't opening via GUI . It also does not show in applications. Not even when I search for it . It only opens via terminal . I have attached 2 screenshots . Please solve my problem. This is happening ever since I installed it.

**Comment by zaggino** [comment]
@Zainzakie try alternative installers here https://github.com/zaggino/brackets-electron/releases

**Comment by Zainzakie** [comment]
Thank you so much. It has solved my problem. But, can you tell me why the original brackets is not working? 

The previous versions of the "original" brackets were working on Kali Linux but this one isn't. Why?

**Comment by zaggino** [comment]
@Zainzakie Official Brackets builds use Chromium Embedded Framework (CEF) and especially the Linux builds use very old version of it. It's quite buggy and there doesn't seem to be anyone skilled enough with CEF and Linux to fix these bugs people are running into.

**Comment by Zainzakie** [comment]
Oh. Thanks @zaggino  .

My problem is solved .
