### ISSUE TITLE
File corruption issue

### ISSUE THREAD

**Issue by plasensa** [adobe/brackets#12975]
Hello. My computer got frozen and when I was able to reboot it 3 of my .js files that I was updating with brackets cannot open. I am getting the  message "An error ocurred  when trying to open the following files  .... Brackets currently only supports UTF-8 encoded text files". WHen I try to open them with notepad they are empty. In the explorer the size reflects the amount of data created in those files. Is there a way to restore them?

**Comment by petetnt** [comment]
Hi @plasensa,

you could try some of the tips at http://superuser.com/questions/223677/recovering-a-corrupted-txt-file. As a generic corruption issue, we aren't sadly able to provide much other help. You could also try retrieving your file from backups if you have those enabled.
