### ISSUE TITLE
[Bug] Horizontal Rule (<hr>) inside paragraph (<p>) generates syntax error

### ISSUE THREAD

**Issue by BinarySpike** [adobe/brackets#12971]
### Prerequisites

* [Yes] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [Yes] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [Yes] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

In HTML, if you put a horizontal rule inside a paragraph tag, you get a syntax error.  Chrome renders it fine.  However, I also noticed W3's validator generates strange (nonsense) errors with the same layout.

### Steps to Reproduce

1. Create a new HTML file and name it "index.html" for live-preview
2. Fill it with:
```
<html>
<head><title>Test</title></head>
<body>
<p>This is a test<hr> of the horizontal rule bar<p>
</body>
</html>
```
3. Start Live Preview
4. Activate syntax recheck (add a new line)

**Expected behavior:** Live preview works as expected

**Actual behavior:** Live preview is disabled due to syntax error

### Versions

Windows 7, Brackets Release 1.8 build 1.8.0-17108

**Comment by redmunds** [comment]
This *is* a syntax error. You shouldn't put a block-level tag inside a text formatting block.

You say " Chrome renders it fine". That is exactly the problem. Years ago, some browser decided to render it, then some other browser decided to also render it because the first browser rendered it. Now they all support if for legacy reasons.

You should end your paragraph before the HR and then start a new one:

```
<html>
<head><title>Test</title></head>
<body>
<p>This is a test</p>
<hr>
<p>of the horizontal rule bar</p>
</body>
</html>
```

**Comment by BinarySpike** [comment]
I see.  With the additional information from your response I was able to find this bit of important information: 
`In the DOM, the opening tag on a block-level element will close the <p> element.`

Which matches the functionality of Brackets.  Unfortunately, this seems to be poorly handled or documented in most other systems I tried.  Even the W3 validator throws strange errors!
