### ISSUE TITLE
Right way to create a non existing codemirror mode, syntax highlighter

### ISSUE THREAD

**Issue by converge** [adobe/brackets#12978]
Hey guys,

I created the GAS extension for Brackets, now I'm going to create NASM highlighter. I follow the [Custom CodeMirror modes](https://github.com/adobe/brackets/wiki/language-support), and developed a new CodeMirror mode, did a pull request, and CodeMirror return was:

["... we aren't accepting new modes anymore. The recommended way to publish a mode is to create a separate package ..."](https://github.com/codemirror/CodeMirror/pull/4428)

I saw some examples of new language highlighters (non existing CodeMirror mode), and I can't see a common way of doing it.

Can anyone guide me ?

**Comment by petetnt** [comment]
Hi @converge,

Now that you have your custom mode created, you need to

1. Create a project/repository for it (for example `brackets-nasm`)
2. Add your module to your repository (for example under `lib/` folder)
2. In your mode definition file, use `require` to require it (`require("./lib/nasm/nasm)` which registers the language via CodeMirror#defineLanguage
3. Use language manager to register it to Brackets

var LanguageManager = brackets.getModule("language/LanguageManager");

```
LanguageManager.defineLanguage("nasm", {
    name: "nasm",
    mode: "nasm",
    fileExtensions: ["file extensions"],
    blockComment: ["... comments ..."],
    lineComment: ["... comments ..."]
});
```

**Comment by converge** [comment]
@petetnt thanks man! I'm still doing something wrong, can you take a look ? https://github.com/converge/brackets-nasm-syntax-highlighter

When I try to install the extension I get extension error.

**Comment by petetnt** [comment]
In https://github.com/converge/brackets-nasm-syntax-highlighter/blob/master/lib/nasm/nasm.js, instead of the UMD wrapper, you could try using just plain AMD style like rest of Brackets currently does:

```
define(function (require, exports, module) {
    var CodeMirror  = brackets.getModule("thirdparty/CodeMirror/lib/codemirror"),
    CodeMirror.defineMode("nasm", function() {
      /** rest of the code **/
    });
    /** rest of the code **/
});
```

Now it should have the correct context and CodeMirror should resolve to the CodeMirror in Brackets.

**Comment by converge** [comment]
@petetnt thank you so much ! I couldn't finish it without your help ! https://github.com/converge/brackets-nasm-syntax-highlighter

**Comment by petetnt** [comment]
No problem @coverge, great that you got it working! :+1:
