### ISSUE TITLE
Install issue with Ubuntu 16.04

### ISSUE THREAD

**Issue by marcdragon123** [adobe/brackets#12976]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

The requirement for installing brackets using libgcrytp11 1.4.5. This package is no longer used, ubuntu uses libgcrypt20 now. 

[Description of the bug or feature]

### Steps to Reproduce

1. try to install with the command prompt or with gdebi gui.

**Expected behavior:** [What you expected to happen]

does not install. 

**Actual behavior:** [What actually happened]

no installation

### Versions

ubuntu 16.04

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by zaggino** [comment]
https://nathanjplummer.github.io/Brackets/
