### ISSUE TITLE
[Question] Did this Edge Code feature ever make it into Brackets?

### ISSUE THREAD

**Issue by BobbyBabes** [adobe/brackets#12986]
Reference : https://www.youtube.com/watch?v=3OMWTqq5-WU&t=74s

From 01:14 into this YT demo video for Edge Code with Theseus, there is a demo of an Edge Code feature. Where by Ctrl+clicking on a webpage (displayed in the browser) a dropdown is displayed on top of that webpage which shows a cross-reference of all matching/apllied CSS rules.
You can then click on a matched selector in the dropdown to be taken to Brackets with that particular CSS selector highlighted and positioned in view.

**Comment by redmunds** [comment]
No, that was never implemented.

Note: That was a working prototype, not Photoshop magic, so it's do-able if you care to take on that feature.
