### ISSUE TITLE
error en las extensiones

### ISSUE THREAD

**Issue by jose-06** [adobe/brackets#12981]
Buenas... . disculpa tengo error en gestionar extensiones, ya instale barckets y al querer instalar alguna extencion me sale "error en la instalacion",  "error interno desconocido" y la verdad nose que es, me podrian orientar para solucionar mi problema.

**Comment by ficristo** [comment]
If you are on 32 bit Windows could you try this: https://github.com/adobe/brackets/issues/12918#issuecomment-261337603?

Otherwise could you open `Debug \ Show Developers Tools` and see if there is any error on the console?

**Comment by ficristo** [comment]
I know there are some problems in 1.8 and there are some other issues about them.
Without more info I consider this a duplicate. Closing.
