### ISSUE TITLE
Notepadqq regular expression subgroup can't be reused in search and replace

### ISSUE THREAD

**Issue by adeel-raza-azeemi** [adobe/brackets#12992]
### Prerequisites

* [ y] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ y] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

If you want to search and replace using regular expression in notepadqq you will not able to replace a group more than once in replace.

### Steps to Reproduce

1. Search a replace a string in notepadqq
2. In replace use any group more than once e.g. \1 more than one
3. only once it will be replaced

**Expected behavior:** [Needs debugging]

**Actual behavior:** [Should be able to reuse as much as we needed]

### Versions

I am using ubuntu 16.10
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by ficristo** [comment]
AFAICT Brackets does support group reusage.
Maybe you need to open the issue to Notepadqq?
