### ISSUE TITLE
Line endings always include carriage return on a new file

### ISSUE THREAD

**Issue by rovf** [adobe/brackets#12995]
When I create a new file with brackets.io Release 1.7 build 1.7.0-16898 (release b0a363b71) running on Windows 7, line endings are always CRLF, which makes the editor nearly unusable for creating files, because it means that we have to convert ever new file to LF line endings, before we can use it. Opening a file which alread has a LF ending works fine.

The problem is: While by far most applications on Windows, Linux or Mac OSX are able to process LF-line-terminated files, the CR ending typically causes problems as soon as you leave the Windows world, and even on Windows it breaks some code (for instance, when using brackets.io for creating shell scripts running under Cygwin).

I suggest that the defaul line ending should be uniformly LF on all platforms. Of course it would be handy if we could manually switch to CRLF, if we need this for a particular file.

ADDITIONAL FINDING: After Installing Brackets.IO 1.8, I now see the following change: When I create a new file and hover above the CRLF indicator in the status line, the tooltip says "Click to  Convert from CRLF to LF", which would basically solve this issue, BUT THIS DOES NOT WORK! Clicking on this status field does not have any effect.

**Comment by zaggino** [comment]
@rovf I use this extension https://github.com/LonelyStorm/brackets-newline and it works very well.

**Comment by petetnt** [comment]
Closing as answered 👍
