### ISSUE TITLE
Preserve any code inline or preserve small objects inline

### ISSUE THREAD

**Issue by chengtie** [adobe/brackets#13001]
At present, the beautifier of brackets turns the following code

    opt = $.extend({ handle: "", cursor: "ew-resize", min: 10}, opt);

to

    opt = $.extend({
      handle: "",
      cursor: "ew-resize",
      min: 10
    }, opt);

Actually, I don't want the beautifier to add the newlines; the beautifier could well leave the line as it is.

Either we could let the beautifier not add newlines for any code, or we let it preserve small objects inline (see [this issue](https://github.com/beautify-web/js-beautify/issues/995)). Does anyone know if any of these solutions has been implemented?

Thanks
OS: macOS Sierra 10.12.2
Brackets: Release 1.8 build 1.8.0-17108

**Comment by petetnt** [comment]
Are you using [this extension (brackets-beautify)](https://github.com/brackets-beautify/brackets-beautify)? I think you can configure it the same way as you can `js-beautify`: https://github.com/brackets-beautify/brackets-beautify#beautifier-options.

As it's an extension issue, I suggest that you re-post the issue to the [extensions issues](https://github.com/brackets-beautify/brackets-beautify/issues) as you most likely get faster answers there if the above doesn't help 👍

**Comment by ficristo** [comment]
Closing since not a Brackets issue.
If you aren't aware, the last version of the extension pointed out by @petetnt is not avalable in the extension manager (because of some limitation of the registry). You can read more on the extension repo.
