### ISSUE TITLE
Is it possible to hide the triangle block icons in Brackets?

### ISSUE THREAD

**Issue by chengtie** [adobe/brackets#13000]
I would like to hide the triangles on the left hand. Does anyone know if it is possible to hide them?

![screen shot 2016-12-23 at 07 12 08](https://cloud.githubusercontent.com/assets/774409/21446865/ecdf7f2e-c906-11e6-9e59-88d3c61ad130.png)

**Comment by petetnt** [comment]
Hi @chengtie,

you can turn off the code folding arrows by going to `Debug -> Show Preferences File` and adding `"code-folding.enabled": false` to your `brackets.json` file.
