### ISSUE TITLE
Can't open a file!

### ISSUE THREAD

**Issue by NikkiRaeGamer** [adobe/brackets#13004]
Hello! I'm having a problem with my brackets, I can't open so-called "encoded 8 files" or something like that..?... Can anyone help me with this?

Thanks!

-NikkiRaeGamer

Picture of what I'm experiencing below

![problems with brackets](https://cloud.githubusercontent.com/assets/24718353/21468076/050da2c2-c9d1-11e6-83f8-a624b3c2cb2f.PNG)

**Comment by petetnt** [comment]
Hi @NikkiRaeGamer,

`UTF-8` refers to the _character encoding_ you file is presented in, which is currently the only format Brackets supports.  It's by far the most commonly used format on the internet, but some other tools could have created the files in another format. You could try converting your files using an extension such as https://github.com/Armacryss/brackets-utf8-converter, which can be found under `File -> Extension Manager`. Alternatively you can use other tool such as [Notepad++](https://notepad-plus-plus.org/) to perform the conversion (open a file -> Encode -> Convert to UTF-8 with BOM -> save the file and it should open in Brackets too).

For more information, see https://en.wikipedia.org/wiki/UTF-8

**Comment by petetnt** [comment]
Closing as answered
