### ISSUE TITLE
Markdown support incomplete

### ISSUE THREAD

**Issue by frakman1** [adobe/brackets#13018]
Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) 
build timestamp: Wed Nov 02 2016 12:07:29 GMT+0000

Markdown does not support the [+addition+] and [-deletion-] colouring for diffs that Github and Gitlab supports.

**Comment by ficristo** [comment]
We support two kind of Markdown: the default and the GitHub one.
If you try the second one it should highlight the code correctly.
