### ISSUE TITLE
Would like PHP syntax colors to be more prominent

### ISSUE THREAD

**Issue by tzhu07** [adobe/brackets#13015]
Perhaps making the` <?php` and` ?>` in red or something that's a stark contrast to the HTML. Right now the PHP snippets and HTML just sort of blend in with each other.

**Comment by petetnt** [comment]
Hi @tzhu07,

you can override the keyword `.cm-m-clike.cm-meta` to achieve that:

```
.cm-m-clike.cm-meta {
color: red;
}
```

which will look something like this:

![image](https://cloud.githubusercontent.com/assets/7641760/21700212/f69e8040-d3a7-11e6-8c37-f8de84eb1248.png)

To do this, you'll need to create a theme and in your `package.json` you'll need to make sure that _Mode aware styles` are enabled with     

```
"theme": {
  "file": "theme.less",
  "addModeClass": true
},
```

To get started, see https://github.com/adobe/brackets/wiki/Creating-Themes and sure to post back if you have any issues!

**Comment by Th30** [comment]
@humphd I can try this as well for lab 5:)

**Comment by bbhagwandeen** [comment]
Hello, I'd like to try to help with this bug.

**Comment by petetnt** [comment]
Closing as answered 👍
