### ISSUE TITLE
Can't remove the "collapse all" keybind

### ISSUE THREAD

**Issue by dasphillipbrau** [adobe/brackets#13016]
Hello.

So I've been trying to remove the keybind for "collapse all" because the default keybind is alt-1 and so every time I try to use an ASCII code to get a special character that includes 1 like curly brackets or square brackets, my whole code collapses and it's extremely annoying.

This is what I'm trying to do for overriding it
Debug>open user keymap
At the keymap, the file keymap.json opens.
I delete everything from the file (because I only want to override this key) and write exactly this.

```
<!-->
{
    "overrides": {
        "<Alt 1>": "null>"
        [, "<Alt 1>": "null>"]
    }
}
```

![brackets](https://cloud.githubusercontent.com/assets/24864399/21582101/82fe28d8-d010-11e6-90b6-579ae7c3a15d.png)
(NOTE: The obvious errors in syntax such as no MINUS

 between Alt and 1 and the lack of "less than" sign on the nulls were done on purpose because for some reason, when writing them, the post would be blank)

But upon saving I get the message "Error reading file: Your file is not valid JSON, the file will be opened so that you can correct the format"

I honestly cannot see why this is the default keybind for a code editor if the combination of alt-1 is used for so many ascii characters

**Comment by dasphillipbrau** [comment]
![brackets](https://cloud.githubusercontent.com/assets/24864399/21582099/6e4fad44-d010-11e6-810b-e555485c3ab3.png)

**Comment by redmunds** [comment]
In the syntax above, you need to replace the `<`, `>`, `[`, and `]` chars. Try this:

```
{
    "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
    "overrides": {
        "Alt-1": null
    }
}
```

Note that I used the Display Shortcuts extension, then right-clicked on item and selected "Disable Shortcut". This updates keymap.json file which then needs to be saved.

**Comment by dasphillipbrau** [comment]
Thank you! I feel a bit silly now. Thought those were actual command tags to be used
