### ISSUE TITLE
features

### ISSUE THREAD

**Issue by gerald2799** [adobe/brackets#13022]
### Description

1.In some programms(Dreamweaver) you can select and move selection;
2.Some sites gives you a possibility to compress your CSS/HTML/JS code;
3.Also some programs have some special features for CSS code what called "Add Vendor Prefix"

It would be nice to see in Brackets this features. Also features №2 and №3 could be realised in three ways, so you can change your current file, change and safe or create a new one;

### Versions

windows 10 pro
version of Brackets 1.8

**Comment by ficristo** [comment]
1. Enable the `dragDropText` [preference](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences)
2. & 3. There should be some extensions for them like "JS CSS Minifier" and "Autoprefixer"

**Comment by petetnt** [comment]
Closing as answered
