### ISSUE TITLE
<!DOCTYPE html> not recognized in brackets Release 1.8 build 1.8.0-17108

### ISSUE THREAD

**Issue by vaishnaviprasad** [adobe/brackets#13029]
![image](https://cloud.githubusercontent.com/assets/19556834/21799942/6ebb2424-d741-11e6-8a0b-8006fc193bde.png)

Please refer to the screenshot above.
Please tell me why <!DOCTYPE html> tag is not getting closed.

OS:win 7 Pro
browser:Chrome Version 55.0.2883.87

**Comment by martingraham** [comment]
Because the tag at the top is doctype, not html. You still need an opening <html> tag

**Comment by vaishnaviprasad** [comment]
Cool Thanks
