### ISSUE TITLE
Problem with brackets 1.8

### ISSUE THREAD

**Issue by Dreter1** [adobe/brackets#13033]
Hi guys,

I'm using brackets v1.8 but i cant find the option of the extract option like in the v1.6 Extract bundle

hope can some help me.

thanks

**Comment by petetnt** [comment]
Hi @Dreter1,

sadly Adobe discontinued the service back in April 2016: http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/?lang=en

AFAIK the Extract team is looking for options on open sourcing it, but sadly there's nothing concrete to share about it.

**Comment by Dreter1** [comment]
Hi @petetnt , so there is no other ? i dont find the installer of brackets  v1.6 Extract bundle you have it or any idea where to find it?

**Comment by petetnt** [comment]
@Dreter1 here's the bundle: https://github.com/adobe/brackets/releases/tag/release-1.6%2Beb4 

But not sure if it works, as the actual Extract service was a web service instead of local app (which also makes the open sourcing part harder)

**Comment by Dreter1** [comment]
@petetnt i have download it but how i put in my brackets or i can use it :/ some help
