### ISSUE TITLE
Accidently dragged all applications into Brackets

### ISSUE THREAD

**Issue by cool2live** [adobe/brackets#13031]
### Prerequisites

* [yes ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [yes ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ yes] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

I accidently dragged all my applications from my finder into the Brackets application. It won't let me delete these applications from Brackets even though I deleted Brackets 5 times and reinstalled it. I also tried some other methods but they didn't work. Now, the problem is that my laptop is getting super glitchy whenever I launch Brackets and it gives me an error saying that I have 30,000+ files.

![screen shot 2017-01-10 at 9 01 19 pm](https://cloud.githubusercontent.com/assets/25048702/21836189/fcb1fd9e-d777-11e6-9625-da96791504d9.png)

**Expected behavior:** When I deleted Brackets, I expected the application files sitting in Brackets to get deleted. 

**Actual behavior:**  This of course did not happen and the problem just stayed there.

let me know if there is more info I need to include. I am currently learning HTML but would like writing code to become more familiar with the HTML program.

I would much appreciate it if anyone could tell me how to solve this problem.   :)

Brackets version 1.8.0
OSX El Capitan 10.11.6

**Comment by ryanstewart** [comment]
I think all you may need to do is push the down arrow next to `Applications` in the sidebar on the left then select "Open a Folder" and find a folder that doesn't have anything in it. 

If you want to start completely from scratch you can try [clearing your cache/preferences](https://github.com/adobe/brackets/wiki/Cache-Folder). That should reset things so that `Applications` isn't your working directory.

**Comment by cool2live** [comment]
Even if i click the down arrow next to applications it won't go away🙁. I
will try the other thing you suggested to see if that will work.

Thank you for your help!:)
