### ISSUE TITLE
Why I set print range does not work?

### ISSUE THREAD

**Issue by ustcshopping** [adobe/brackets#13037]
This is my print adapter class, no matter what I set the range of print, it will all print to the last page of pdf file, for example I have a file with 6 pages, I set page range as 2,4-5 then it will print 2,4-6. I think it matters with parameter pages in the onWrite, I try to pass in into onWriteFinished, but it will print all 6 pages no matter what you set. And I try the way like Android developer website, I always meet the error 
java.lang.RuntimeException: can not open a halmode pdf file.  Any one can give some idea or some sample can work  well? Thank you!
`  class PdfFragmentPrintDocumentAdapter extends PrintDocumentAdapter {

        /**
         * Called each time a user changes a print setting which impacts the output.
         *
         * @param oldAttributes      The old print attributes.
         * @param newAttributes      The new print attributes.
         * @param cancellationSignal Signal for observing cancel layout requests.
         * @param callback           Callback to inform the system for the layout result.
         * @param extras             Additional information about how to layout the content.
         */
        @Override
        public void onLayout(PrintAttributes oldAttributes, PrintAttributes newAttributes, CancellationSignal cancellationSignal, LayoutResultCallback callback, Bundle extras) {
            Log.i(sClassTag, "onLayout");

            addCancelListenerInOnLayout(cancellationSignal, callback);
            //TODO The second parameter should be false if the print request is the same as the previous one.
            callback.onLayoutFinished(mPrintDocumentInformation, true);
        }

        /**
         * Add a cancel listener on cancellationSignal in the parameter of onLayout.
         *
         * @param cancellationSignal Signal for observing cancel layout requests.
         * @param callback           Callback to inform the system for the layout result.
         */
        private void addCancelListenerInOnLayout(CancellationSignal cancellationSignal, final LayoutResultCallback callback) {
            Log.i(sClassTag, "addCancelListenerInOnLayout");

            cancellationSignal.setOnCancelListener(new CancellationSignal.OnCancelListener() {
                @Override
                public void onCancel() {
                    Log.i(sClassTag, "CancellationSignal works inside onLayout");
                    callback.onLayoutCancelled();
                }
            });
        }

        /**
         * Called to render printed pages into a file to be printed. This method may be called one or more times after each onLayout() call.
         *
         * @param pages              The pages whose content to print - non-overlapping in ascending order.
         * @param destination        The destination file descriptor to which to write.
         * @param cancellationSignal Signal for observing cancel writing requests.
         * @param callback           Callback to inform the system for the write result.
         */
        @Override
        public void onWrite(PageRange[] pages, ParcelFileDescriptor destination, CancellationSignal cancellationSignal, WriteResultCallback callback) {
            Log.i(sClassTag, "onWrite");

            implementOnWriteInDedicatedThread(pages, destination, cancellationSignal, callback);
        }

        /**
         * Run onWrite in a dedicated thread in case the printed content is large, the parameters need to be declared as final for it is accessed from inner class.
         *
         * @param pages              The pages whose content to print - non-overlapping in ascending order.
         * @param destination        The destination file descriptor to which to write.
         * @param cancellationSignal Signal for observing cancel writing requests.
         * @param callback           Callback to inform the system for the write result.
         */
        private void implementOnWriteInDedicatedThread(final PageRange[] pages, final ParcelFileDescriptor destination, final CancellationSignal cancellationSignal, final WriteResultCallback callback) {
            Log.i(sClassTag, "implementOnWriteInDedicatedThread");

            new Runnable() {
                @Override
                public void run() {
                    InputStream input = null;
                    OutputStream output = null;

                    try {
                        input = new FileInputStream(mPdfDocumentName);
                        output = new FileOutputStream(destination.getFileDescriptor());
                        addCancelListenerInOnWrite(cancellationSignal, callback, input, output);
                        byte[] buf = new byte[1024];
                        int bytesRead;
                        while ((bytesRead = input.read(buf)) > 0) {
                            output.write(buf, 0, bytesRead);
                        }
                        callback.onWriteFinished(new PageRange[]{PageRange.ALL_PAGES});
                    } catch (FileNotFoundException e) {
                        Log.e(sClassTag, "FileNotFoundException in PDFFragmentPrint", PdfFragmentErrorCode.MSPDF_FR_FILE_PRINT_FILE_NOT_FOUND);
                        callback.onWriteFailed("Print service failed because file " + getFileNameFromPath(mPdfDocumentName) + " was not found");
                    } catch (IOException e) {
                        Log.e(sClassTag, "IOException in PDFFragmentPrint", PdfFragmentErrorCode.MSPDF_FR_FILE_PRINT_IO_EXCEPTION);
                        callback.onWriteFailed("Print service failed because " + e.toString());
                    } finally {
                        closeInputInOnWrite(input);
                        closeOutputInOnWrite(output);
                    }

                }
            }.run();
        }

        /**
         * Add a cancel listener on cancellationSignal in the parameter of onWrite.
         *
         * @param cancellationSignal Signal for observing cancel writing requests.
         * @param callback           Callback to inform the system for the write result.
         * @param input              If input is open and cancellation happens, we need to close the input.
         * @param output             If output is open and cancellation happens, we need to close the output.
         */
        private void addCancelListenerInOnWrite(CancellationSignal cancellationSignal, final WriteResultCallback callback, final InputStream input, final OutputStream output) {
            Log.i(sClassTag, "addCancelListenerInOnWrite");

            cancellationSignal.setOnCancelListener(new CancellationSignal.OnCancelListener() {
                @Override
                public void onCancel() {
                    Log.i(sClassTag, "CancellationSignal works inside onWrite");
                    closeInputInOnWrite(input);
                    closeOutputInOnWrite(output);
                    callback.onWriteCancelled();
                }
            });
        }

        /**
         * Close InputStream in onWrite function.
         *
         * @param input If input is open, we need to close it.
         */
        private void closeInputInOnWrite(InputStream input) {
            Log.i(sClassTag, "closeFile");

            try {
                if (input != null) {
                    input.close();
                }
            } catch (IOException e) {
                Log.e(sClassTag, "IOException inside onCancel", PdfFragmentErrorCode.MSPDF_FR_FILE_PRINT_IO_EXCEPTION);
            }
        }

        /**
         * Close OutputStream in onWrite function.
         *
         * @param output If output is open, we need to close it.
         */
        private void closeOutputInOnWrite(OutputStream output) {
            Log.i(sClassTag, "closeFile");

            try {
                if (output != null) {
                    output.close();
                }
            } catch (IOException e) {
                Log.e(sClassTag, "IOException inside onCancel", PdfFragmentErrorCode.MSPDF_FR_FILE_PRINT_IO_EXCEPTION);
            }
        }
    }`

### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by petetnt** [comment]
This doesn't seem to be relevant to USB
