### ISSUE TITLE
Quick Edit

### ISSUE THREAD

**Issue by flapjack17** [adobe/brackets#13036]
Qiuck edit does not display the entire funciton when using template literatles with embed expressions.
```
function hi(name){
    let works `hello ` + name;
    let breaks = `Hello ${name}`; // quick edit ends on this line
    console.log(works); //the rest of the function does not return
    console.log(breaks);
}
```
When using quick edit code is displayed like:
```
function hi(name){
    let works `hello ` + name; 
    let breaks = `Hello ${name}`; // quick edit ends on this line
```

**Comment by redmunds** [comment]
Backtick (\`) is not a valid string delimiter is JS. It should work if you use either single (') or double (") quotes instead.

**Comment by flapjack17** [comment]
The first line of the function is using backticks and returns the next line. the problem appears to arise when using a place holder ${}; [How is the backtick not valid?](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

**Comment by redmunds** [comment]
QuickEdit is implemented for JS. Whatever language you are using that uses backtick for string delimiters is not supported.

But, it looks like the `${}` placeholder you are using could also be used outside of a string, so my original suggestion doesn't fix all cases of the problem. That type of placeholder is also not supported (i.e. the closing brace is interpretted as the end of the function).

**Comment by petetnt** [comment]
@redmunds backticks (and `${experssions}` are used) in [templated literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and are valid string delimeters (in ES2015)

**Comment by redmunds** [comment]
@petetnt Thanks for clarifying. Either CodeMirror does not yet support ES2015, or Brackets is not recognizing the new tokens.

**Comment by RaymondLim** [comment]
It is a bug in the regular expression that is used to extract functions in https://github.com/adobe/brackets/blob/master/src/language/JSUtils.js. It is mistakenly taking the closing brace inside the template literal as the closing brace of the function definition.
