### ISSUE TITLE
<!DOCTYPE html>features

### ISSUE THREAD

**Issue by gerald2799** [adobe/brackets#13041]
when you write `<!DOCTYPE html>` brackets create basic html code:
```
<!DOCTYPE html>
<html>
<head>
  <title></title>

</head>
<body>

</body>
</html>
```

**Comment by petetnt** [comment]
Hi @gerald2799,

you can add this feature with something like https://github.com/jrowny/brackets-snippets or https://github.com/chuyik/brackets-snippets.

There's also an HTML templates extension that might be of help: https://github.com/talmand/Brackets-HTML-Templates.

All of the above extensions can be found in the Extension Manager.

**Comment by bokub** [comment]
With the [Emmet](https://github.com/emmetio/brackets-emmet) extension (most popular extension of Brackets BTW), you can achieve this pressing `!` then `TAB`

**Comment by petetnt** [comment]
Closing as answered / Extension available

**Comment by vivekkhillar** [comment]
but i have failed this attempt can anyone please guide me?

**Comment by bokub** [comment]
1. Install the "Emmet" extension
2. Create a new HTML file
3. Write `!` in your new file
4. Press `TAB`
