### ISSUE TITLE
Brackets eats more than 1GB of disk space

### ISSUE THREAD

**Issue by sashabeep** [adobe/brackets#13040]
Just saw in cleanmymac that Brackets folder in Applications support is 1.3GB
How to clean it? What to delete?

**Comment by zaggino** [comment]
@sashabeep can you open it and report what particular files / directories take up?
![image](https://cloud.githubusercontent.com/assets/1067319/21958865/d0fecd98-db0b-11e6-9ed6-f2cd84a16488.png)


For example mine is 200 megs but 180 megs is coming just from the extensions I've installed

**Comment by sashabeep** [comment]
live-dev-profile folder is more than 1GB
The other ones is less than 20MB

**Comment by zaggino** [comment]
Someone from @adobe/brackets-committers could have a look if we can limit a size of this temp folder please.

**Comment by sashabeep** [comment]
What to do now? Can i just empty this folder for now?

**Comment by zaggino** [comment]
Yes, it should be safe to delete.

**Comment by petetnt** [comment]
@zaggino Do we even need to keep the temp profile data or could we just nuke the folder after live preview session ends?

**Comment by sashabeep** [comment]
Thanks to all! Just deleted this folder without issues

**Comment by zaggino** [comment]
@petetnt I have never ever used or digged inside the code of live preview so I can't answer that. But I'd assume that it can be safely deleted once Brackets is closed.

**Comment by sashabeep** [comment]
@zaggino i'm pretty sure that this folder must be empty on close

**Comment by petetnt** [comment]
Only thing I would be worried about is live preview launching sliiiiightly slower on subsequent launches, but then again we already use `--temp-profile` flag while launching so 🤔

**Comment by sheraz2016** [comment]
why brackets goes slow and shows more errors after installing extentions in it than before and also goes hang on save all ... ant also hang on when goes fron css file to HTML file it takes some seconds and then allows you to edit code... why? can anyone tell solution?

**Comment by ingorichter** [comment]
does anybody have more information what data is written to the temp folder? I wonder why it's growing to that size.

**Comment by ingorichter** [comment]
@sheraz2016 well, extensions might be buggy and cause issues if they are not aware of the lifecycle and run expensive operations on save, lint, you name it. The best advice is to try isolating the extensions that behave abnormal. I know that this can by a bit cumbersome, but that will be valuable feedback fort extension developer. Which extensions did you install?

**Comment by sheraz2016** [comment]
i installed these extensions -- Brackets Css Color Preview, Brackets CSS Class Code hint, Brackets CSS Class Code hint, More CSS Code Hints, More HTML5 Code Hints, Number Tabs, PHP SmartHints, Show Tabs , Super Right Click, word wrap icon.

**Comment by sheraz2016** [comment]
i think save button extention was causing problem now it is working good.

**Comment by haslam22** [comment]
@ingorichter I think it contains the bookmarks, history, cache, settings, etc. for the live browser. Here's another related issue:  #11165

**Comment by saurabh95** [comment]
@ingorichter @zaggino I think we can delete this folder once user quits brackets(as it is just storing the profile information). 
What's you opinion on this solution?

**Comment by redmunds** [comment]
Deleting that folder on quit should be ok, but it will slow down Live Preview on next use.
 
Is there any way to programmatically set the cache size? If so, it would be nice to have a `liveDevCacheSize` preference which defaults to something like 250MB.

**Comment by saurabh95** [comment]
@redmunds  I checked for available flags and I found  --disk-cache-size which can be used to restrict the size of the cache, but since the change needs to be done in the brackets-shell so we can't have any preference for the size. so we have to fix the size of the cache to a particular limit, 250 MB seems reasonable to me. 
@ingorichter @petetnt @zaggino any views on the size limit?

**Comment by zaggino** [comment]
250MB seems to be fine, definitely not more

**Comment by saurabh95** [comment]
Created a PR regarding the same change https://github.com/adobe/brackets-shell/pull/596

**Comment by saurabh95** [comment]
#
