### ISSUE TITLE
[Linux] obsolete libgcrypt11 issue

### ISSUE THREAD

**Issue by gpl4all** [adobe/brackets#13042]
hi all,

i've just found out brackets and to my disappointment, i can not be installed on latest Debian Jessie due to dependency on (very old) libgcrypt11, and also very surprised that this is issue for more than 2 years now (am referring to https://github.com/adobe/brackets/issues/10255).

[10255](https://github.com/adobe/brackets/issues/10255) is a long discussion and ended up nowhere, and on last comment there is a suggestion to use brackets-electron instead.

i've tried to install brackets-electron, and it has other dependency that luckily easier to overcome than brackets, but it's performance much worst.

so i decided to find a way out for myself to make brackets run in my Debian Jessie, and the solution i choose is to get libgcrypt11 binary compiled and installed, here is list what i did:

- get libgcrypt source for [Debian Wheezy](https://packages.debian.org/wheezy/libgcrypt11):
- compile it using normal _debian/rules binary_ command, which resulting some deb package files 
- instead installing libgcrupt11 deb packages and cause more dependency problem i simply copied: 
debian/libgcrypt11/lib/x86_64-linux-gnu/libgcrypt.so.11.7.0
debian/libgcrypt11/lib/x86_64-linux-gnu/libgcrypt.so.11 (symlink to libgcrypt.so.11.7.0)
to /lib/x86_64-linux-gnu

anyone who needs that binary file can get it [here](https://github.com/gpl4all/any-binary)

to brackets developer: kindly considering solve this ugly issue by compiling brackets against libgcrypt20, it's much more simply solution to user than suggesting users to check this and that and leads nowhere.

**Comment by petetnt** [comment]
Hi @gpl4all,

sadly the `libcrypt` issue still persist, mostly because we are currently missing a dedicated Linux native developer that could handle the issue of updating and keeping Linux CEF up-to-date (thus solving the dependency issue). Shipping the obsolete `libcrypt11` dependency with the Brackets binary is not an option due to legal reasons. There are other workarounds for the issue which are listed here: https://github.com/adobe/brackets/wiki/Brackets-Linux-Guide

If you would like to help us bringing the Linux build up-to-date (or know someone that does!) please see https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md 👍

**Comment by gpl4all** [comment]
hi @petetnt

i understand completely situation you explained, except CEF issue since i have not familiar with it and just found brackets for few days now, so i better put it asside. i've seen 2 workarounds you write and first one is basically close to my approach only that i use my own compiled binary because i'm not on ubuntu and too hassle for me because actually i still on Debian Wheezy.

i'll think about contributing as you suggested, main consideration is my spare time :( will let you know about it later on.

and thank you for your response  :+1: and with this i believe i can close this and pending solution for time being.

**Comment by petetnt** [comment]
👍 

CEF is the Chromium Embedded Framework application framework which Brackets uses. It pre-dates things like Electron, which also means that it's a tad more complicated to setup and use than Electrons largely functional "it just work on all platforms"-approach.
