### ISSUE TITLE
Bracckets is hanging when i use the responsive tool

### ISSUE THREAD

**Issue by Mohammad1277** [adobe/brackets#13052]
when i use the responsive tool the Brackets is hanging and not respond.
i use windows 7, and my app version is 1.8 build 1.8.0-17108, the version of the downloaded tool is 0.1.0 for Ben Rooney.

**Comment by petetnt** [comment]
Hi @Mohammad1277,

could you report this to the extension repository: https://github.com/brimelow/Response-for-Brackets/issues. You might find better luck there. Hope you get it solved 👍
