### ISSUE TITLE
Problem Of "Brackets File Tree Extension" ???

### ISSUE THREAD

**Issue by MHHerock** [adobe/brackets#13056]
### Problem With Brackets File Tree Extension !!!
![01](https://cloud.githubusercontent.com/assets/24572443/22158699/a868e2be-df67-11e6-900d-15384f891f61.png)

When I Was Installed **"Brackets File Tree Extension"** It Shows Me A Problem [See In Picture]. Two Option In One Place. One Is **"Brackets File Tree Extension"** And Another Is **"Split Option"**. I Think It's Not Correct. It Should Be Correct. Please Solve This Problem As Sooooon As Possible !!!

### Versions
Mac OS Sierra [App Store Version]
Brackets [V1.8]

**Comment by swmitra** [comment]
@MHHerock This looks like a problem with the extension rather than Brackets core projects panel. Please raise the same issue against the git repo of Brackets File Tree extension.

**Comment by swmitra** [comment]
Closing.
