### ISSUE TITLE
Extension manager not working

### ISSUE THREAD

**Issue by danaviya** [adobe/brackets#13059]
I can't get any extensions to load.
I erased chorme, renistalled it and then installed a fresh Barcket (1.8).
The errror given is "Unknown internel error"
The debugger says this:
Unknown installation error extensionManager domain is undefined
I tried also with URL and droping the sip into the drop box.
Lastly this is windows 7.
This is such a good editor. I am really stuck on it.
Anyway love to help solve the issue.
Daniel.

### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by danaviya** [comment]
I just installed an extension manuelly and it worked!!!
please see this link: [manual Install/Remove/Update](https://github.com/Jayuda/Flexide/wiki/Brackets-Extensions)
OK sofar so good.

**Comment by schindld** [comment]
This sounds like the 32-bit issue. Is your version of windows 32-bit? If so, find a 32-bit version of node.exe, and copy/save it into the Brackets folder (replacing the node.exe there), and restart Brackets.

**Comment by danaviya** [comment]
You were right!!!!
Well done. I wonder how you new that?
