### ISSUE TITLE
Brackets does not auto close double quotes (") and single quote (')

### ISSUE THREAD

**Issue by linocatucci** [adobe/brackets#13067]
Hi,

I am working with a macbook Pro macOS with brackets 1.8.0-17108. See below for more details.

But in my brackets installation Brackets does not auto close double quotes (") and single quote (').
{}, [] and () are auto closing correctly.

Who can help me?
Thanks,
Lino

{
"uuid": "511a6c49-1ada-4dd3-ab05-6c4c70e7d703",
"snapshotTime": 1485464301455,
"os": "mac",
"userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.8.0 Chrome/49.0.2623.110 Safari/537.36",
"osLanguage": "nl-NL",
"bracketsLanguage": "nl-NL",
"bracketsVersion": "1.8.0-17108",
"fileStats": {
"openedFileExt": {
"html": 4,
"css": 4,
"js": 2,
"json": 2
},
"workingSetFileExt": {}
},
"ProjectDetails": {
"prj3059181": {
"numFiles": 14,
"cacheSize": 798640
}
},
"projectLoadTimes": ":245",
"fileOpenTimes": ":165(336)507[171]:133(180)226[47]:306:352:254:251",
"ModuleDepsResolved": 264636,
"AppStartupTime": 267076,
"prefNodeSearchDisabled": false,
"prefInstantSearchDisabled": false,
"installedExtensions": [
{
"name": "artemsolovev.anode",
"version": "1.0.1"
},
{
"name": "brackets-macos-xcode-dusk",
"version": "1.1.4"
},
{
"name": "grimaldo.coder",
"version": "1.0.0"
},
{
"name": "insya.atom.dark",
"version": "1.0.4"
},
{
"name": "insya.atom.light",
"version": "1.0.5"
},
{
"name": "jsecademy",
"version": "1.0.0"
},
{
"name": "martypenner.autosave-files-on-window-blur",
"version": "1.0.6"
},
{
"name": "jquinter",
"version": "0.3.3"
},
{
"name": "ftp-sync",
"version": "2.0.4"
},
{
"name": "gbratsos.zurb-foundation",
"version": "1.2.2"
},
{
"name": "chrisgriffith.zurbappshints",
"version": "0.1.0"
},
{
"name": "globexdesigns.brackets-jsxhint",
"version": "0.0.7"
},
{
"name": "mikailcolak.brackets-color-picker",
"version": "0.1.3"
},
{
"name": "qw0101.colorhighlighter",
"version": "1.2.1"
},
{
"name": "interactive-linter",
"version": "1.0.5"
},
{
"name": "ivogabe.icons",
"version": "1.5.7"
},
{
"name": "brackets-minify",
"version": "1.1.7"
},
{
"name": "mikaeljorhult.brackets-autoprefixer",
"version": "0.6.4"
},
{
"name": "brackets-beautify",
"version": "1.2.0"
},
{
"name": "brackets-nodejs-integration",
"version": "1.8.9"
},
{
"name": "hirse.outline-list",
"version": "1.0.0-alpha.0"
},
{
"name": "zaggino.brackets-git",
"version": "0.16.6"
}
],
"bracketsTheme": "dark-theme"
}
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by petetnt** [comment]
Hi @linocatucci,

seems to work for me at least for JS files. Which document mode are you using?

**Comment by linocatucci** [comment]
Hi, I am using JS files. In HTML and CSS I don't have this problem.
I have checked my keyboard settings which are US EN
thx

-- 
Lino Catucci

Op 27 januari 2017 om 09:47:18, Pete Nykänen (notifications@github.com)
schreef:

**Comment by ficristo** [comment]
Can you reproduce the problem with `Debug -> Reload Without Extensions`?
Also could you share your preferences and a snippet of code to reproduce?

**Comment by linocatucci** [comment]
Hello ficristo,
It worked! With Debug -> Reload Without Extensions, the double quotes and single quotes are closed automatically.

Thanks,
Lino

**Comment by petetnt** [comment]
Closing as extension issue 👍
