### ISSUE TITLE
Dead link in the wiki

### ISSUE THREAD

**Issue by JigAma** [adobe/brackets#13076]
### Description

Hello, in the page https://github.com/adobe/brackets/wiki/How-to-Use-Brackets
the link to the JSLint reference is dead and return a 404 page.

### Steps to Reproduce

1. Go to https://github.com/adobe/brackets/wiki/How-to-Use-Brackets
2. Search in the page "jslint.options"
3. Click on "the JSLint reference"

**Expected behavior:** Go to the JSLint reference

**Actual behavior:** Go to 404 page

**Comment by petetnt** [comment]
Fixed this earlier, thanks again!
