### ISSUE TITLE
'Auto Indent' and in-line indenting doesn't handle if/elseif/else/end structures in languages that don't use braces

### ISSUE THREAD

**Issue by ianshmean** [adobe/brackets#13073]
### Description

'Auto Indent' and in-line indenting doesn't handle if/elseif/else/end structures in languages that don't use braces

### Steps to Reproduce

1. Use language like Julia that doesn't use braces for if statements
2. type out if statement and see auto-indent occurring incorrectly
3. also try 'auto indent' option from edit menu

**Expected behavior:** 
```
if
    #some code
elseif
    #some code
else
    #some code
end
```

**Actual behavior:**
```
if
    #some code
    elseif
        #some code
    else
        #some code
    end
```
### Versions

Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) 
build timestamp: Wed Nov 02 2016 04:47:30 GMT-0700

MacOS

**Comment by ficristo** [comment]
I've installed the `Julia Syntax Highlighter` extension and I've created a `test.jl` file
The `elseif` seem dedented correctly.
And I cannot reproduce on http://codemirror.net/mode/julia/
But I also don't see any 'auto indent' option on Edit menu: do you have some other extensions?

**Comment by ianshmean** [comment]
I've drilled down and it seems to be an issue when the conditional statement is present beside the `elseif`

For instance, this indents properly:
```
if something
    #some code
elseif
    #some code
else
    #some code
end
```

But this doesn't
```
if somecondition
    #some code
    elseif someothercondition
    #some code
else
    #some code
end
```


And you're correct, the 'auto indent' option in the edit menu was in an extension. I didn't realise.

**Comment by ficristo** [comment]
If I write simply 
```julia
if somecondition
    #some code
```
and then write `elseif` is dedented correctly.

Can you reproduce on the codemirror demo? If so, you should file an issue upstream.

**Comment by ianshmean** [comment]
I get that behaviour too, but if you make the 2nd line code, not a comment, the issue arises:

```
if something
    something
    elseif something
else
end
```
```
if something
    #some code
elseif something
else
end
```

**Comment by ficristo** [comment]
I'm using the exact example you wrote and still cannot reproduce.
Do I need some real code?
That said, if you can reproduce on CodeMirror demo the issue should be fixed there.

**Comment by ianshmean** [comment]
The last example I gave should be sufficient to reproduce. I have no idea why you're not seeing the same behavior. I can reproduce this on CodeMirror, so I'll do as you suggest and post an issue there

**Comment by ianshmean** [comment]
Issue [found](https://github.com/codemirror/CodeMirror/issues/4519) and [addressed](https://github.com/codemirror/CodeMirror/commit/73044ab7cc377d4e039400d9ca23d044169cde0b) in codemirror

**Comment by ficristo** [comment]
In #13116 we have upgraded CodeMirror. This should be fixed in next release.
