### ISSUE TITLE
Preferences objects are not extended with defaults values

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#13072]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

When you get a preference object it is does not extends the defaults values but it overwrite them.

### Steps to Reproduce

1. Define a preference object
like `closeTags` in `editor/Editor.js`
2. Set your preference using `Debug / Open Preferences File`
something like `"closeTags": { "whenOpening": false }`
3. Retrieve it
using PreferencesManager.get

If `closeTags` is defined like this:
```js
"closeTags": {
    "dontCloseTags": [],
    "indentTags": [],
    "whenClosing": true,
    "whenOpening": true
}
```

**Expected behavior:** 
The object retrieved should be
```js
"closeTags": {
    "dontCloseTags": [],
    "indentTags": [],
    "whenClosing": true,
    "whenOpening": false
}
```

**Actual behavior:**
```js
"closeTags": {
    "whenOpening": false
}
```

Is this the correct behaviour? It was totally unexpected to me.

### Versions
Windows 10
master (1.9)

**Comment by saurabh95** [comment]
@ficristo I was trying to look at this issue and I found that even if we don't have any changes in brackets.json, then also `PreferencesManager.get("closeTags")` returns
`"closeTags": {
    "indentTags": [],
    "whenClosing": true,
    "whenOpening": true
}`
`dontCloseTags` is also missing.

**Comment by zaggino** [comment]
Definitely a bug, should be extended from the defaults.
