### ISSUE TITLE
Extract for brackets preview

### ISSUE THREAD

**Issue by enriqueguido** [adobe/brackets#13088]
I am unable to open any files from adobe like psd and ai. I do not have a show extract button. I tried several tutorials, as well as uninstalling it and reinstalling, but it has not worked. I get the following error in the console developer tool.  
![image](https://cloud.githubusercontent.com/assets/16198465/22789140/1e5864e8-eeb0-11e6-8e65-71ba19c3ca67.png)

**Comment by petetnt** [comment]
Sadly the Adobe Extract service has been discontinued by Adobe (see http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/?lang=en for more information).

There has been some talks about open sourcing some of the technology behind it, but there's nothing further to comment on sadly. Dreamweaver seems to still offer this feature if Adobe CC subscription is an option.

Sorry about this.

**Comment by enriqueguido** [comment]
Thank you!!
