### ISSUE TITLE
Kindly resolve my issue

### ISSUE THREAD

**Issue by Memoon** [adobe/brackets#13082]
I m using Bracket 1.8 wanted to uploaded the new psd file but now its given me the error plear resolved 
Extract for Brackets
Extract for Brackets service is no longer available. If you wish to continue using Extract, download Adobe Dreamweaver CC:
 
https://creative.adobe.com/products/download/dreamweaver

**Comment by ficristo** [comment]
Is the problem that you cannot use anymore Extract within Brackets?

**Comment by Memoon** [comment]
So how can we use PSD file in Brackets

**Comment by petetnt** [comment]
Sadly the Adobe Extract service has been discontinued by Adobe (see http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/?lang=en for more information).

There has been some talks about open sourcing some of the technology behind it, but there's nothing further to comment on sadly. Dreamweaver seems to still offer this feature if Adobe CC subscription is an option. 

Sorry about this.
