### ISSUE TITLE
emmet is installed but its not working in Brackets

### ISSUE THREAD

**Issue by Memoon** [adobe/brackets#13084]
emmet is installed but its not working in bracket please let me know what should i do

**Comment by petetnt** [comment]
Hi @Memoon,

did you install https://github.com/emmetio/brackets-emmet extension or just plain `emmet`?

**Comment by Memoon** [comment]
thanks my issue is solve however i enter "Enter key " instead of tab .

**Comment by wallirashid** [comment]
MY tab key is not working for words I already install emmet but when i press tab or some TAG it will create space what shoud i do?

**Comment by Jonaxgzz** [comment]
Hello there, 

I have the same problem... the tab key is doing nothing. I try to disable some other plugins to see if there is one in conflict but still not working. 

Any suggestions? (Im using it on mac)

**Comment by ui-coder** [comment]
In my case, Emmet is installed but it doesn't work at all after I tried to fix the _keymap.json_ to fix the "Wrap with Abbreviation" shortcut. After that (I'm sure though) Emmet on Brackets toolbar does not even open by clicking on it to see the menu. Any suggestions could be a help. Thank y'all.

**Comment by nsprince** [comment]
Probably you did not save the file with an extension like indext.php or index.html

**Comment by reazhemel** [comment]
Emmet is already installed in brackets but when I press the tab it create space. How can I fix it? please Help!!
