### ISSUE TITLE
PHP: Problem with unwanted double apostrophes in strings

### ISSUE THREAD

**Issue by dacramp** [adobe/brackets#13081]
Hello everyone,

there is some weird behaviour in PHP strings when variables are involved.

Basically, when I want to write something like:
![1](https://cloud.githubusercontent.com/assets/25581183/22641658/ee37364a-ec57-11e6-936b-71a868874540.png)
I will end up with this:
![2](https://cloud.githubusercontent.com/assets/25581183/22641676/ff11ea1e-ec57-11e6-9fbd-88ab3fd25de7.png)

The issue is that when you are in a string environment ("..."), you will normally get single apostrophes when you hit the apostrophe key (e.g. blue box). But, when you put a variable in your string and want to put a single apostrophe behind it, you will get automatically two apostrophes (red box), which is kind of annoying and probably not intended.

The problem occurs most likely because of the (new) feature of colouring variables in strings in black instead of string-orange. Actually, I wonder whether the black-colouring of variables in strings is beneficial at all. Personally, I think it makes it a tad more difficult to grasp where strings actually end.

**Comment by ficristo** [comment]
Opened codemirror/CodeMirror#4549

**Comment by ficristo** [comment]
Fixed upstream.

**Comment by ficristo** [comment]
Fixed in Brackets by #13116
