### ISSUE TITLE
emmet stopped working for new docs

### ISSUE THREAD

**Issue by creativemac73** [adobe/brackets#13094]
Hi there
I am on a windows machine and I use emmet in Brackets. For some reason the plugin has stopped working for new documents. Curiously it's working fine with older documents. I have reinstalled the plugin and checked that it is enabled...does anyone know why this is?

thanks in advance
Linda

**Comment by petetnt** [comment]
Hi @creativemac73,

as this is an extension issue, you most likely will find answers in the extension repository: https://github.com/emmetio/brackets-emmet. Could you repost the issue there? Meanwhile you can check if there's any errors (for example plugin conflicts in the dev tools (Debug -> Show Developer Tools -> Console).

Hope you get the issue resolved, and thanks! 👍
