### ISSUE TITLE
Conflicting keyboard shortcut

### ISSUE THREAD

**Issue by Narfinas** [adobe/brackets#13115]
### Description

Hey, I'm not a programmer but a writer, using Brackets to write my stuff in clean HTML. When I try to write Polish, with Polish (programmers) keyboard in my system, I hit "Option - O" on my Mac in order to produce letter "ó", but instead a "Recent Files" window appears. I tried to unbind it, but doesn't seem to be able to. Could you please avoid Option - Letter shortcuts in the future versions?

Thanks for making Brackets so awsome! :)

### Versions

Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) 
build timestamp: Wed Nov 02 2016 04:47:30 GMT-0700
Mac OS X 10.12.3

**Comment by ficristo** [comment]
Do you have tryed this? It seems to work for me.
```json
{
    "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
    "overrides": {
         "Alt-O": ""
    }
}
```

**Comment by Filip-Rogalski** [comment]
Where should I put it? in brackets.json? (Not working)

`{
    "fonts.fontSize": "15px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "livedev.multibrowser": false,
    "beautify.io.on_save": true,
    "styleActiveLine": true,
    "linting.collapsed": true,
    "documentation": "https://github.com/adobe/brackets/wiki/User-Key-Bindings",
    "overrides": {
        "Alt-O": ""
    },
    "sacah.keyremapper.loadremapperdialog.keymap": {
        "navigate.toggleQuickEdit": {
            "commandID": "navigate.toggleQuickEdit",
            "key": "Cmd-E"
        },[…]`

**Comment by Filip-Rogalski** [comment]
@ficristo Where did you put this code?

**Comment by ficristo** [comment]
You should use `Debug \ Open User Key Map`.
You can find some more info at https://github.com/adobe/brackets/wiki/User-Key-Bindings

**Comment by Filip-Rogalski** [comment]
Thanks!!!

**Comment by Narfinas** [comment]
Finally i managed to undbind it using solution provided above. The problem was that I used comma "," in    
 "overrides": {
         "Opt-O": "" ,
    }
as it was in documentation. The comma caused error "This is not a valid JSON file"...

**Comment by lkcampbell** [comment]
@Narfinas, looks like you solve this problem using customized key bindings so I am closing this issue. If that is not the case feel free to reopen so we can investigate further.
