### ISSUE TITLE
Brackets Requires libgcrypt11 and Fails to Install

### ISSUE THREAD

**Issue by mohnjatthews** [adobe/brackets#13118]
### Description

The [.deb package](https://github.com/adobe/brackets/releases/download/release-1.8/Brackets.Release.1.8.64-bit.deb) downloadable from http://brackets.io/ asks for `libgcrypt11` when `sudo dkpg -i Brackets.Release.1.8.64-bit.deb` is ran.

According to [this post on Stackoverflow](http://askubuntu.com/a/616651/412161) `libgcryp11` was replaced by `libgcrypt20` some time ago.

### Steps to Reproduce

1. Go to [Brackets.io](http://brackets.io/) and download the Brackets.Release.1.8.64-bit.deb package
2. `cd` into the download location and run `sudo dpkg -i Brackets.Release.1.8.64-bit.deb`

**Expected behavior:** Brackets should successfully install.

**Actual behavior:** Error message is received in terminal:

```
$ sudo dpkg -i Brackets.Release.1.8.64-bit.deb
Selecting previously unselected package brackets.
(Reading database ... 191109 files and directories currently installed.)
Preparing to unpack Brackets.Release.1.8.64-bit.deb ...
Unpacking brackets (1.8.0-17108) ...
dpkg: dependency problems prevent configuration of brackets:
 brackets depends on libgcrypt11 (>= 1.4.5); however:
  Package libgcrypt11 is not installed.

dpkg: error processing package brackets (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
 brackets
```

### Versions

OS: elementary OS 0.4 Loki (64-bit), Built on "Ubuntu 16.04.2 LTS"
Brackets Version: 1.8.64-bit

**Comment by zaggino** [comment]
Hi @mohnjatthews , this is a known issue, please read https://github.com/adobe/brackets/wiki/Brackets-Linux-Guide

Alternatively, you can try to solve this and open a PR for https://github.com/adobe/brackets-shell/tree/linux-1547

**Comment by mohnjatthews** [comment]
Thanks for the reply @zaggino, sorry I didn't notice that before.
