### ISSUE TITLE
Live preview issue

### ISSUE THREAD

**Issue by MandarSant** [adobe/brackets#13117]
When ever i open live preview it gives me the following error 
 
![capture](https://cloud.githubusercontent.com/assets/20091634/23213089/9912dad6-f92f-11e6-8ec2-75737e5fc90f.JPG)

and in the background the index.html file is open

**Comment by redmunds** [comment]
Make sure there is no space after `.html`

**Comment by MandarSant** [comment]
@redmunds there is no any space

**Comment by ficristo** [comment]
I cannot reproduce.
Could you share your code? Also are you using the experimental (multi browser) live preview and browser is your default?
If you do `Debug \ Reload Without Extensions` does work?

**Comment by MandarSant** [comment]
@ficristo  which code should I share? And my browser(**Chrome** )is a default browser

I am not using multi browser

**Comment by ficristo** [comment]
I'm sorry, I completely forgot about this...
I wanted to try to reproduce with the same files as yours. So I wanted the index.html and the Stylesheet.css which are shown in the screenshot.
Were you able to solve?
I not could you try `Debug \ Reload Without Extensions`?
Also you could try the multi browser live preview.

**Comment by MandarSant** [comment]
I tried all the option as u described above but still not able to solve & the problem is not with the particular
index.html ,Stylesheet.css file it happens every time
