### ISSUE TITLE
JavaScript Code Hinting tests

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#13126]
### Description

While looking at #13116 I noticed these tests fail.
I tryed on master and they fail there too.
Running `git bisect` pointed to 7883b0134b9923418632bf01ad48849aa8c14d2e

/cc @saurabh95 @swmitra @zaggino 

### Steps to Reproduce

1. `Debug \ Run Tests`
2. Go to `Extensions`
3. Run `JavaScript Code Hinting`

**Expected behavior:** Tests pass

**Actual behavior:** Tests fail

### Versions

Windows 10
master

**Comment by zaggino** [comment]
Fixed in #13116 by https://github.com/adobe/brackets/pull/13116/commits/1de6b887c7fcf23dfe4e93e4d8408811ab55c098?w=1
