### ISSUE TITLE
brackets admin webiste stuck in opening when edit file in ftp

### ISSUE THREAD

**Issue by arc92** [adobe/brackets#13124]
Hi
I have install brackets earlier,and i am compeletly new to this editor
I have install brackets admin website to control ftp remote server but when i click some file to open or download the editor stuck in connecting and opening that file,has anyone,any solution???

**Comment by arc92** [comment]
problem solved:
the problem was,the folder that i save my ftp on it is protected,and need permission to write on it, i was created folder in C:// and save ftp information on it

**Comment by mohanad1980** [comment]
can somebady can help me with jw player i can pay but jw player for google drive
