### ISSUE TITLE
Cat ruined my life

### ISSUE THREAD

**Issue by Jontronics** [adobe/brackets#13120]
Cat jumped on my computer and shut the computer off. 

Me being amazing at life didn't save in brackets. So the working files index.html and styles.css have lost all of work that i've done for two days. Is there any way to retrieve the work i've done? If there isn't a way to retrieve the work that i've lost. Is there a good way to have the sessions auto save? 

ps don't worry, I wont kill the cat. 

### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by zaggino** [comment]
So you didn't save the files at all for the 2 days?
Sorry but this sounds like trolling.

**Comment by ficristo** [comment]
Brackets doesn't have an autosave feature builtin. So your work is lost, unfortunately.
There are a couple of autosave extensions, if you want to give a try.
