### ISSUE TITLE
Laravel code support markup

### ISSUE THREAD

**Issue by TilakMaddy** [adobe/brackets#13127]
Laravel PHP code doesn't go well with this editor

**Comment by petetnt** [comment]
Hi @TilakMaddy,

is there anything specific about it that doesn't work? Is this issue about syntax highlighting or code completion (etc.)? The syntax seems good to me:

![image](https://cloud.githubusercontent.com/assets/7641760/23474208/9e33fa40-febb-11e6-926f-3f2781520a7f.png)

**Comment by petetnt** [comment]
Closing as answered, feel free to reopen if the issue persists
