### ISSUE TITLE
Incorrect syntax highlighting in Ruby

### ISSUE THREAD

**Issue by rovf** [adobe/brackets#13139]
In the following Ruby statement:

`if cr =~ /(?: \( #{RE_NOT}\( | #{RE_NOT_PAR_OR}* #{RE_OPA_OR} )/x`
   
everything from the first '#' is highlighted as if it were a comment.

Running brackets 1.8 on Windows 7.

**Comment by zaggino** [comment]
Filed as https://github.com/codemirror/CodeMirror/issues/4623

**Comment by zaggino** [comment]
CodeMirror issue is now fixed and we'll need to update CodeMirror version before 1.9 for this.

**Comment by ficristo** [comment]
Fixed.
