### ISSUE TITLE
Flash Player

### ISSUE THREAD

**Issue by loganone2000** [adobe/brackets#13135]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ X] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [X ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

Pixlr extension gives me "Adobe Flash Player Not Installed!"
I have flash player installed and up to date.

### Steps to Reproduce

1. Install Brackets
2. Install Pixlr
3. Run Pixlr

**Expected behavior:** Pixlr runs.

**Actual behavior:** Error message "Adobe Flash Player Not Installed!"

### Versions
Windows 7 Ultimate, 64 bit service pack 1
Bracket 1.8 build 1/8/0-17108
Flash Player 24,0,0,221 installed

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by ficristo** [comment]
You should file an issue https://github.com/dnbard/brackets-pixlr
Closing as an extension problem
