### ISSUE TITLE
Core: Suggest to add a limit to the length of the exclusion set name.

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#13140]
Steps:
1. Launch the Brackets
2. Click Find -> Replace in Files
3. Drop down the Edit exclusion set list, click New Exclusion Set...
4. Input a long string  as the exclusion set name

Result: No limit to the length of the exclusion set name, and it would be a layout issue if the name is too long
Expect: There is a limit to the length of the exclusion set name.

![3](https://cloud.githubusercontent.com/assets/2245179/23501422/c2ff010e-ff6e-11e6-8507-1e86081edd0c.png)

**Comment by bomanimc** [comment]
I can do this!

**Comment by bomanimc** [comment]
Making good process. I've gone ahead and added a character count to the Edit Exclusion Set modal that only appears when the name field starts to be edited. You can see it in the photo below:

<img width="1440" alt="screen shot 2017-03-05 at 8 55 03 am" src="https://cloud.githubusercontent.com/assets/6589909/23587896/2827695c-0183-11e7-833e-d84376334b06.png">

What is the process for adding new strings to the project? I've added it to the nls/root string set. Is that all? Waiting to be added to the Slack group to address other questions!

**Comment by zaggino** [comment]
Hi @bomanimc , please submit a PR with your code and ask your questions there, it's the best place to ask, even better than Slack. As for the strings, just add it to the `nls/root`.

**Comment by zaggino** [comment]
Fixed in https://github.com/adobe/brackets/pull/13155
