### ISSUE TITLE
LB: LOC: fr_FR: "Last Updated" string is not localized

### ISSUE THREAD

**Issue by Tania-Jiacomini** [adobe/brackets#13145]
Problem: "Last Updated" string is not localized

String ID: EXTENSIONS_LAST_UPDATED

EN: Last Updated
Current FR: Last Updated
Correct FR: Dernières mises à jour

![sortby](https://cloud.githubusercontent.com/assets/2284774/23547639/40826b44-0004-11e7-8d60-9002017ad8de.png)

![sortby_fr](https://cloud.githubusercontent.com/assets/2284774/23547640/408641c4-0004-11e7-9383-ce090d51ecef.png)

**Comment by KatarzynaWodzinska** [comment]
Issue fixed. Please provide the most recent screen.

**Comment by Zhanxin** [comment]
Uploaded the latest screen for FR with build 1.9.0-17310-806, please help to verify:
![13145](https://cloud.githubusercontent.com/assets/2245179/24098381/255a1ab6-0da5-11e7-92d8-d3a63240a8fa.png)

**Comment by Tania-Jiacomini** [comment]
Confirmed as fixed, thanks!
      
      Regards,
    
    
      
      
       
        Tania Jiacomini
          Translation
          
          Stoquart France SARL
          Translation & Localisation
          Espace Beethoven
          1208 route des Lucioles
          06560 Valbonne
          France
          Tel: +33 (0)4 92 96 09 55
          email: tania.jiacomini@stoquart.fr
      Web: www.stoquart.com
      
                    
                   
          
    Le 20/03/2017 à 12:41, Zhanxin a
      écrit :
    
    
      Uploaded the latest screen for FR with build 1.9.0-17310-806,
        please help to verify:
        
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adobe/brackets","title":"adobe/brackets","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/adobe/brackets"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Zhanxin in #13145: Uploaded the latest screen for FR with build 1.9.0-17310-806, please help to verify:\r\n![13145](https://cloud.githubusercontent.com/assets/2245179/24098381/255a1ab6-0da5-11e7-92d8-d3a63240a8fa.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/adobe/brackets/issues/13145#issuecomment-287736492"}}}
    
    
  www.stoquart.com

An ISO 9001:2008-certified company

**Comment by KatarzynaWodzinska** [comment]
Closing the bug
