### ISSUE TITLE
ESLint plugin install problems

### ISSUE THREAD

**Issue by Seasle** [adobe/brackets#13156]
I cant install in my Brackets ESLint plugin, but as me need latest version Brackets. Me already installed latest version. 

### Screenshots:
![Plugin List](http://i.imgur.com/xoGBAGM.jpg)
![Brackets Version](http://i.imgur.com/theVWCr.jpg)

**Comment by zaggino** [comment]
Latest version is 1.8 now, ESLint will be supported from release 1.9
or you can try running from latest source codes - https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets

**Comment by Seasle** [comment]
Thanks you!

**Comment by zaggino** [comment]
@Seasle now you can try also https://github.com/adobe/brackets/releases/tag/release-1.9-prerelease
