### ISSUE TITLE
Insider/Beta Releases

### ISSUE THREAD

**Issue by macjabeth** [adobe/brackets#13157]
This is just a request. I think it would be nice to include nightly (or weekly) builds for users to test out the latest features like they have in place for other popular coding editors (VSCode Insiders, Atom Beta).

**Comment by petetnt** [comment]
Hi @bunster, thanks for the feature request! Not sure if `nightly`s are possible at this point as Brackets is a bit lacking on the update system, but using Brackets against the latest master is pretty simple:

1. Clone the repo `git clone https://github.com/adobe/brackets && cd brackets`
2. Run `npm install`
3. Run setup for hacking script:

    |  |  |
    |---|---|
    | Mac | `tools/setup_for_hacking.sh "/Applications/Brackets.app"` |
    | Windows | `tools\setup_for_hacking.bat "C:\Program Files (x86)\Brackets"` <br>_(MUST be run in a Command Prompt started with "Run as Administrator")_ |
    | Linux | `sudo tools/setup_for_hacking.sh "/opt/brackets"` |

Then you can set up a cron job or something to `git pull origin master` daily ^^

The master is usually very stable, so there aren't that many risks.

https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets

**Comment by zaggino** [comment]
@bunster for now: https://github.com/adobe/brackets/releases/tag/release-1.9-prerelease

**Comment by swmitra** [comment]
Closing this issue. We are going to have releases in every two months with a couple of pre-releases before that. That would make the release frequency quite evenly.
