### ISSUE TITLE
File Open throws "Uncaught TypeError: Cannot read property 'lastIndexOf' of null"

### ISSUE THREAD

**Issue by saurabh95** [adobe/brackets#13158]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

Throws null exception on File Open.

### Steps to Reproduce

1. Open File using File->Open

**Expected behavior:** File Opens without any error.

**Actual behavior:** It throws a null exception.

### Versions
Latest Master

![image](https://cloud.githubusercontent.com/assets/5630113/23697662/9bc0fd0a-040e-11e7-94f3-84d7e9f5b6b7.png)

**Comment by zaggino** [comment]
Fixed in https://github.com/adobe/brackets/pull/13159
