### ISSUE TITLE
Tags such as <br> and <hr> autocomplete

### ISSUE THREAD

**Issue by johnroper100** [adobe/brackets#13161]
### Description

In the latest master of Brackets, HTML tags that should only have one tag (eg. `<hr>` instead of `<hr></hr>`) autocomplete.

### Steps to Reproduce

1. Add a tag such as `<hr>`

**Expected behavior:** `<hr>`

**Actual behavior:** `<hr></hr>`
### Versions

Windows 10 x64
Release 1.9 development build 1.9.0-0 (master 68e3705d4)

**Comment by evgnTarasevich** [comment]
Ubuntu 16.04 x64, the same release as yours, the same problem.

**Comment by johnroper100** [comment]
I update to master every day and still have this problem. I don't have any extensions installed which should be causing this issue.

**Comment by ficristo** [comment]
Meanwhile you could add in your preferences something like this:
```
"closeTags": {
    "dontCloseTags": ["br", "hr"]
}
```

**Comment by evgnTarasevich** [comment]
It does not work.

**Comment by evgnTarasevich** [comment]
The only way is to use 1.8 v, untill this bug is fixed.

**Comment by johnroper100** [comment]
Ok, thanks. It is a real pain. I will just have to put up with it.

**Comment by zaggino** [comment]
This is now fixed in latest master @johnroper100 @evgnTarasevich

**Comment by johnroper100** [comment]
Thanks, it works perfectly now!
