### ISSUE TITLE
I cant't install brackets from packge deb in ubuntu 16.04

### ISSUE THREAD

**Issue by pyroxar** [adobe/brackets#13173]
<a href="http://i.imgur.com/FUJrrSX.png">
  <img src="http://imgur.com/FUJrrSXl.png" />
</a>

**Comment by zaggino** [comment]
https://github.com/adobe/brackets/wiki/Brackets-Linux-Guide

**Comment by pyroxar** [comment]
It is not bug, Its feature. I understand.

**Comment by zaggino** [comment]
Hi, if you took a time to quickly search issues for `libgcrypt` you'd see that this is an issue that has been reported on 2014 (https://github.com/adobe/brackets/issues/10255) and so far, no-one that'd be able to fix this has been found. You're free to open a PR of course. Thanks
