### ISSUE TITLE
Brackets 1.8 crashes leaving black frame on macOS Sierra 

### ISSUE THREAD

**Issue by trmcc** [adobe/brackets#13172]
### Prerequisites

* [yes ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [yes ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [yes ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

Brackets crashes (white panes disappear and leave black frame) after a few minutes of use. Cmd-Q will not close it. Click and hold on Brackets icon in dock and quitting from there works. It was taking longer between crashes, about an hour, now it is 5 or so minutes.

I have reinstalled Brackets and the problem persists. I did delete ~/Library/Applications Support/Brackets folder first.

There is a good description of this for a Windows machine by [K-Thompson](https://github.com/adobe/brackets/issues/12918), but I thought I should open a new report for macOS.

### Steps to Reproduce

1. Open editor, work for a few minutes, and crash

**Expected behavior:** In January when I first started using Brackets, I could keep it open for days, using live preview and it never crashed.

**Actual behavior:** Crashes within a few minutes, original files are not corrupted.

### Versions

macOS Sierra 10.12.3 (16D32)

Brackets Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4) 
build timestamp: Wed Nov 02 2016 04:47:30 GMT-0700

**Comment by zaggino** [comment]
@trmcc can you try setting preference (Debug > Open preferences file) `"codehint.JSHints": false,` to see if it helps?

**Comment by trmcc** [comment]
@zaggino Thanks for your idea! I have been editing for 20 minutes with no crashes. I will post back later on after I have worked for a while and let you know how it is going. Very happy to have my editor back, thank you!

**Comment by zaggino** [comment]
@trmcc If you have some free time, can you try https://github.com/adobe/brackets/releases/tag/release-1.9-prerelease (setting `codehint.JSHints` back to true) to see if the 1.9-prerelease still contains this issue?

**Comment by trmcc** [comment]
@zaggino Thanks again for your help! I worked many hours yesterday with no crashes at all. I will download the version you recommended, try it, and report back. I cannot get to it until Tues or Wed, but I will let you know.

**Comment by trmcc** [comment]
@zaggino I downloaded version:
Release 1.9 build 1.9.0-17262 (master 0b292eaa4) 
build timestamp: Thu Mar 09 2017 00:41:07 GMT-0800

and have been running it with:
"codehint.JSHints": true

I have not used it as much as usual each day, but have been running it for several days and have not encountered any crashes. Thank you!

**Comment by swmitra** [comment]
@trmcc Can you please let us know whether you ran into the same issue after 1.9 release?

**Comment by trmcc** [comment]
I have been working with the version 
Release 1.9 build 1.9.0-17312 (release 189f6d39a) 
build timestamp: Tue Mar 21 2017 03:04:51 GMT-0700 
on OSX 10.12.5
since May with no issues. Very happily, thanks! Am I supposed to close the issue or do you do that?

**Comment by swmitra** [comment]
Well I can close this issue :smile. Thanks again @trmcc for the quick confirmation 👍
