### ISSUE TITLE
Before i begin, i got a question.

### ISSUE THREAD

**Issue by Nerdietony** [adobe/brackets#13187]
How does Brackets look on windows 10?

**Comment by saurabh95** [comment]
![brackets](https://cloud.githubusercontent.com/assets/5630113/24068754/0d1603c8-0bbd-11e7-9971-4bca4b292449.png)

**Comment by Nerdietony** [comment]
That looks absolutely stunning, does this possibly support sftp?

**Comment by swmitra** [comment]
@Nerdietony Not out of the box. But there might be extensions to support that feature.

**Comment by saurabh95** [comment]
@Nerdietony  SFtpUpload and FTP-Sync Plus are some of the popular extensions which add support for sftp to brackets.
You can get more info about these extensions in Brackets itself or  https://brackets-registry.aboutweb.com/
