### ISSUE TITLE
Start with a taller window, remember window size from previous run

### ISSUE THREAD

**Issue by joyously** [adobe/brackets#13182]
I would like to see this feature added to Brackets.

### Steps to Reproduce

1. Open Brackets
2. Size the window as desired
3. Close Brackets
4. Open Brackets

**Expected behavior:** The second(and subsequent) time Brackets opens, the window is the same size as it was when it was closed.

**Actual behavior:** Every time Brackets opens, you have to size the window to a workable size.

### Versions

I'm running Ubuntu Studio 16.04 with Brackets Release 1.8 experimental build 1.8.0-17108

**Comment by johnroper100** [comment]
I can reproduce on a macOS system.

**Comment by petetnt** [comment]
Thanks for the report @joyously & repro @johnroper100. Couldn't replicate this on Win10 just now, so might be Mac/Linux only 🤔

**Comment by ficristo** [comment]
I quite sure on Linux this doesn't work at the moment.
I wasn't able to reproduce on macOS El Capitan and I'm a bit surprised @johnroper100 you were able to.
Are you using a newer version?

**Comment by petetnt** [comment]
Couldn't replicate the size issue on MacOS either, but Brackets always opens to my main screen (laptop) instead of the screen it was on last time (desktop display). The size is correct though (corner to corner).

**Comment by johnroper100** [comment]
I can't replicate on Windows 10.

**Comment by lkcampbell** [comment]
I can't reproduce this on macOS Sierra 10.12.4.

**Comment by Reydavid** [comment]
I have the same issue on a Windows 10 machine.

**Comment by literallysofia** [comment]
I can't reproduce this issue on macOS High Sierra, version 10.13.1.

**Comment by IMOUNGA** [comment]
Hi ! I'm a student and I want to try to solve this issue for Linux. 
However, i can't install with _**npm install**_  : 

_npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN Brackets@1.13.0-0 No license field.
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "husky" "--save-dev"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! husky@0.13.2 install: `node ./bin/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the husky@0.13.2 install script 'node ./bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the husky package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs husky
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls husky
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vins/Documents/resolution_bug/bracket_/brackets/npm-debug.log_


I have try to do : **_npm install husky --save-dev_**
I search on **_Google_** and at _**npm bugs husky**_ but i have no answer.

If someone have the solution, i'll take it (of course i'm still searching !) ! 🤕

**Comment by IMOUNGA** [comment]
I solved the problem. 
In the beginnig I had just : apt-get install nodejs
But it's not enough you have to do : apt install nodejs-legacy

I hope it help someone ! 👍🏿

**Comment by IMOUNGA** [comment]
I read this in the bracket-shell file : client_handler.cpp -
**" // CefWIndowInfo.height/.width aren't impelemented on Linux for some reason
//  we'll want to revisit this when we integrate the next version of CEF
"**

I think it's the reason why we can't resolved this issue

**Comment by joyously** [comment]
I just installed the new version which says on the About: Release 1.14 build 1.14.0-17740 (release 329d08ffc) 
The first time I opened it, the window was fullscreen, unlike before when it was small. I changed it to my preference and the second time I opened it, it was my preferred size.
So I considered this fixed.
