### ISSUE TITLE
Brand new to Brackets and HTML - Images aren't displaying

### ISSUE THREAD

**Issue by hes63** [adobe/brackets#13186]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
I don't think so but I'm  not sure I'm using Debug correctly (brand new to HTML and Brackets)

* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
Yes, searched on the term "Images not displaying".  

* [ ] Did you read the [Troubleshooting guide]
Yes, searched on "Image" and "Images" under Page not Loading"
No(https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description
I am brand new to writing code.  I just completed the Lynda.com course in HTML Essentials (will start the CSS course very soon) and I downloaded Brackets.  I used it to do all the Lynda exercises so I think I'm getting comfortable with it.

I'm writing my first page and the image I'm trying to display isn't showing.  The preview clearly shows the browser is trying to pull the image.  The dimensions and alt text are all correct.  I have the folder name in the path so everything seems to be correct but there is no image.  The images in the Lynda exercises displayed fine so I don't think it's the browser or my MacBook.

ANY HELP or direction to look would be deeply appreciated.

### Steps to Reproduce

Not sure what to do here . . .  the code is pretty simple. Do I copy it here?

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
Wanted to see image. 

**Actual behavior:** [What actually happened]
Didn't see the image but the dimensions and alt text are there so Chrome is reading the img code but the image isn't displaying.  

### Versions

Please include the OS and what version of the OS you're running. Mac OSX
Please include the version of Brackets.  Brackets 1.8

**Comment by saurabh95** [comment]
Try opening Developer console in Preview, and see if there are any errors, there might be an issue with the path.
If there is no error in console, then you can share the directory structure and your code snippet for the image?

**Comment by hes63** [comment]
Hello Saurabh95,

Thank you for your reply.  I checked the code in the console, it seems to me to be correct.  Here is the HTML I wrote in Brackets based on what I learned in Lynda.com:

<!DOCTYPE>
<html lang="en">
<head>
<meta charset="utf-8">
<title>J3D Services - 3D Printing</title>
    <p><img src="_J3D Web Files/J3D Images/Purchased Image.jpg" width="600" height="600" alt="J3D Home Page Image"></p>
    <p></p>
    <p></p>

I think the issue is with the path to the image but the file folder name is correct and so is the name of the image.

Hes63

**Comment by hes63** [comment]
I got it to WORK!!!!  I feel as if I'm standing on Everest!!!!   Thanks for help.  I'm sure I'be back with other issues.

Hes63

**Comment by saurabh95** [comment]
@hes63 Great to hear that it works for you now. Feel to free to post any queries on github or slack  
I am closing this issue now.

**Comment by DonP199** [comment]
I wish you would have said _how you got it to work.

**Comment by srigowrideo** [comment]
hello, i am facing the same problem in brackets !! can i know the procedure please ?
thanks

**Comment by js76155** [comment]
Hi there, I am having the same problems. does anyone have the solution that they wish to share? Obviously, hes63 is a 'taker' as opposed to a 'giver'.

**Comment by mac-vi** [comment]
You would put the correct codes for the image and size. Then click SAVE file then click LIVE PREVIEW

**Comment by AdamRoyaie** [comment]
i had the same problem after an hour of searching on internet found no solution and fix for this problem , 
but it was very simple the parent file of the images name was ( images on the home page )  and i change it to ( images-on-the-home-page ) and finally everything worded the images was shown on the live preview . 
i did change the folder name back to it's initial name just to checking if that was really the problem and yeah i faced the same problem so just see if the parent folder of the images has spaces in between words or not . 
Thank you

**Comment by tammie020881** [comment]
Having the same problem as well~
