### ISSUE TITLE
Command Pallete (Feature Request)

### ISSUE THREAD

**Issue by xahon** [adobe/brackets#13188]
### Description

Want to see command pallette like in sublime for find files in project (Ctrl + P), saving and switching projects (Ctrl + ALT + P), all available commands (CTRL + SHIFT + P). I'm used to using sublime and I see a good future in this editor, but now i cannot use this at full power.

I'm using Linux

**Comment by ficristo** [comment]
Dupe of https://github.com/adobe/brackets/issues/12990
