### ISSUE TITLE
Bracket Isn't Closing on my Ubuntu 16.04

### ISSUE THREAD

**Issue by abuzaforbg** [adobe/brackets#13196]
I've tried several attempts to close barckets, But it isn't closing. Even the editor and opened project isn't coming up.
![brackets_008](https://cloud.githubusercontent.com/assets/10008159/24091429/3c01546a-0d72-11e7-891c-f19e6c7a0f67.png)

**Comment by ficristo** [comment]
It seems something was corrupted: could you try to delete `state.json`?
See here for details https://github.com/adobe/brackets/wiki/Cache-Folder

**Comment by abuzaforbg** [comment]
Hi @ficristo thanks for your valuable comment. Deleting `state.json` worked.

**Comment by ficristo** [comment]
I'm glad it worked out.
