### ISSUE TITLE
LB: LOC: fr_FR:  Accents missing in FR strings.

### ISSUE THREAD

**Issue by KatarzynaWodzinska** [adobe/brackets#13197]
Please fix the FR strings as per the below:

Source:  CSS Timing Function Quick Edit: invalid syntax
Current FR:  Edition rapide des fonctions de temporisation CSS : syntaxe incorrecte
Expected:  Édition rapide des fonctions de temporisation CSS : syntaxe incorrecte

Source: No Quick Edit available for current cursor position
Current FR: Fonction Edition rapide non disponible pour la position actuelle du curseur
Expected: Fonction Édition rapide non disponible pour la position actuelle du curseur

Source: JS Quick Edit: place cursor in function name
Current FR: Edition rapide JS : placez le curseur dans le nom de fonction
Expected: Édition rapide JS : placez le curseur dans le nom de fonction

Source: CSS Quick Edit: place cursor in tag, class, or id
Current FR: Edition rapide CSS : placez le curseur dans la balise, la classe ou l’ID
Expected: Édition rapide CSS : placez le curseur dans la balise, la classe ou l’ID

Source: CSS Quick Edit: incomplete id attribute
Current FR: Edition rapide CSS : attribut d’ID incomplet
Expected: Édition rapide CSS : attribut d’ID incomplet

Source: CSS Quick Edit: incomplete class attribute
Current FR: Edition rapide CSS : attribut de classe incomplet
Expected: Édition rapide CSS : attribut de classe incomplet

Source: CSS Quick Edit: place cursor on a single class name
Current FR: Edition rapide CSS : placez le curseur sur un seul nom de classe
Expected: Édition rapide CSS : placez le curseur sur un seul nom de classe

Source: Installation failed.
Current FR: Echec de l’installation.
Expected: Échec de l’installation.

Source: Login Failed
Current FR: Echec de la connexion
Expected: Échec de la connexion

Source: Quick Edit
Current FR: Edition rapide
Expected: Édition rapide

Source: About {APP_TITLE}
Current FR: A propos de {APP_TITLE}
Expected: À propos de {APP_TITLE}

Source: About
Current FR: A propos
Expected: À propos

**Comment by ficristo** [comment]
The accents were added in https://github.com/adobe/brackets/pull/12420 and reverted in https://github.com/adobe/brackets/pull/13193: they were reverted by accident?

**Comment by KatarzynaWodzinska** [comment]
Issue fixed in Slate.

**Comment by ficristo** [comment]
I didn't find any string about "Login Failed" anywhere, all the other it seems to me are translated.
