### ISSUE TITLE
Menus not showing… only Brackets and Window and no coding window!!!

### ISSUE THREAD

**Issue by Duckmandu** [adobe/brackets#13191]
<img width="575" alt="brackets weirdness" src="https://cloud.githubusercontent.com/assets/22085700/24084208/092ea710-0ca3-11e7-922e-d891cf172fed.png">

Strange… Brackets is not showing any menus but the Brackets and Windows menus. Hence, no Debug selection! I deinstalled Brackets and all the related files, then reinstalled. Same problem. Also tried restarting the computer.

Also, I can open only one file, and it opens as though it's a browser, no coding window!!

Here's my computer info, and an attached screenshot:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,4
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Memory:	16 GB
  System Version:	macOS 10.12.1 (16B2657)

**Comment by saurabh95** [comment]
I guess you are opening html file using Shift+Click
