### ISSUE TITLE
Brackets extension error

### ISSUE THREAD

**Issue by Kooldiv** [adobe/brackets#13207]
#my brackets is upto date yet some extensions are showing that they require newer version of brackets
My current version is 1.8

**Comment by zaggino** [comment]
@Kooldiv latest version is now 1.9 - https://github.com/adobe/brackets/releases/tag/release-1.9
I've released some extensions earlier so pre-release users could install them.

**Comment by hrvojegolcic** [comment]
Try modifying the extension to use `"view/WorkspaceManager"` instead of `"view/PanelManager"`. I had problem installing the most of the extensions too.
https://github.com/adobe/brackets/issues/11960#issuecomment-374403225
