### ISSUE TITLE
Brackets API Docs Page...Top Navigation

### ISSUE THREAD

**Issue by akinhwan** [adobe/brackets#13206]
http://brackets.io/docs/current/modules/brackets.html#dependencies

In the "Brackets API" Documentation Page, the top navigation "Dependencies" "Variables" "Functions" "Classes" does not change the `<section>` below as expected.

The page in fact remains completely unchanged. Navigation is either broken or unnecessary?

**Comment by redmunds** [comment]
@akinhwan Those top navigation links scroll to the appropriate section anchor of the module being displayed. Some navigation doesn't apply to some modules, so nothing is done in that case. For example, the "brackets" module does not have a "variables" section.

I tried a few random navigation links in a few random modules and it seems to be working. Let us know if you find any specific links in specific modules that don't appear to be working. Thanks.
