### ISSUE TITLE
LB: ja_JP: In-context translation change in string "Port on which WebSocket Server runs for Live Preview"

### ISSUE THREAD

**Issue by MayaFuruto** [adobe/brackets#13200]
In-context translation change in string "Port on which WebSocket Server runs for Live Preview"
(current translation is not exactly accurate)

EN string: Port on which WebSocket Server runs for Live Preview
Current target string: WebSocket サーバーがライブプレビューで実行するポート
Expected target string: ライブプレビューで WebSocket サーバーが実行されるポート

![preferencesport](https://cloud.githubusercontent.com/assets/6737567/24142789/fd1c1922-0e27-11e7-9276-f6e6897ecc66.png)
![preferencesport](https://cloud.githubusercontent.com/assets/6737567/24142811/11f43064-0e28-11e7-9932-86a6d52b123a.png)

**Comment by KatarzynaWodzinska** [comment]
Issue fixed. Please provide most recent screen.

**Comment by ficristo** [comment]
It should have been fixed by https://github.com/adobe/brackets/pull/13204
