### ISSUE TITLE
Core: There is a layout issue on extension manager panel when narrow down the window

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#13209]
Steps:
1. Open the Brackets.
2. Click the icon about Extension Manager.
3. Narrow down the window.
4. Observe the sort toggle and the search bar.

Result:
The sort toggle and the search bar are misplaced.

Expected:
The sort toggle and the search bar should be displayed in the correct position.
![layout](https://cloud.githubusercontent.com/assets/2245179/24198353/89b8c22c-0f40-11e7-9073-dab355a250b3.png)

**Comment by Zhanxin** [comment]
Could reproduce on release 1.8 build.

**Comment by petetnt** [comment]
Also reported by me at https://github.com/adobe/brackets/pull/13080#issuecomment-278798445

**Comment by lkcampbell** [comment]
I will be glad to fix this bug.

@Zhanxin, would you mind providing a fake screenshot graphic depicting what the phrase "displayed in the correct position" means?

**Comment by petetnt** [comment]
@lkcampbell there's a PR fixing this alteady if you want to review it https://github.com/adobe/brackets/pull/13245 :+1:

**Comment by lkcampbell** [comment]
@petetnt okay thanks I will look at it this weekend.

**Comment by zaggino** [comment]
Fixed in https://github.com/adobe/brackets/pull/13245
