### ISSUE TITLE
Core: The "more information" link on extension manager panel would redirect to a 404 error page

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#13203]
Steps:
1. Open the Brackets.
2. Click the icon about extension management.
3. Look up "Brackets Java" and click the "more information" link.
4. Observe the new page.
Result:
It would link to a 404 error page
Expected:
It could link to a correct page
![404](https://cloud.githubusercontent.com/assets/2245179/24147992/c7fed446-0e77-11e7-985d-9eaa37c23456.png)

**Comment by swmitra** [comment]
This is not a Brackets core issue. 'More Info' links to the provided URL in package.json uploaded by the extension author. 
Please contact the author of 'Brackets Java' extension to take corrective measure about the unreachable github url.
