### ISSUE TITLE
fonts not working especially when changing size

### ISSUE THREAD

**Issue by bobrowski** [adobe/brackets#13205]
i noticed this recently, windows 7, on brackets 1.8 and the 1.9 pre-release, i uninstalled, deleted all files and extensions, did a fresh re-install

setting a custom font works *sometimes*, but as soon as you go to resize it it resets to whatever the default font is, i made a video so its crystal clear

[Video](https://www.youtube.com/watch?v=_Rp8ANd_9FM)

**Comment by bestguy** [comment]
Seeing same on Mac OS - resizing the font (ctrl+/-) reverts the font, and same occurs if I change font size in 'View>Themes..'

**Comment by guillecro** [comment]
I can confirm this.
Same issue on Ubuntu 16.04 LTS x64

Here is a preview.
https://gfycat.com/FirmBigheartedHarlequinbug

**Comment by Tusko** [comment]
Have the same problem.
My font is SourceCodePro (default in Brackets, if I'm not mistaken)

But it is bolder than was in Brackets 1.8

**Comment by kobezhu** [comment]
me too！

**Comment by swmitra** [comment]
I will have a look at it and keep you guys updated about the fix.

**Comment by swmitra** [comment]
Closing this as fixed by #13279 and available as part of 1.10 pre-release 1 build https://github.com/adobe/brackets/releases/tag/release-1.10-prerelease-1
