### ISSUE TITLE
JP: raw UTF-8 character code is shown on replace dialog

### ISSUE THREAD

**Issue by assialiholic** [adobe/brackets#13219]
### Description

Under Japanese language setting, raw UTF-8 character code is shown on replace dialog.
![issue](https://cloud.githubusercontent.com/assets/6077519/24284320/10e85b40-10ae-11e7-9ffa-c282c6fd923d.png)

### Steps to Reproduce

1. Set the language setting to Japanese.
2. Call "replace" `検索 -> 置換`
3. Raw UTF-8 character code is shown on "バッチ" in replace dialog.

**Expected behavior:** バッチ…
**Actual behavior:** バッチ¥u2026

### Versions

**Mac:** OS X El Capitan (Version 10.11.6)
**Brackets:** 1.9.0-17312

**Comment by ficristo** [comment]
The `¥` should be a `\`

**Comment by ficristo** [comment]
I think this has been fixed.
