### ISSUE TITLE
Does Brackets have autocomplete for SASS?

### ISSUE THREAD

**Issue by DalonK** [adobe/brackets#13211]
I started to use SASS instead of SCSS sometime ago and found out there is no the same autocomplete as it was for SCSS. While typing SASS markup, Brackets doesn't suggest me names of CSS properties and values. Should I enable something in settings or do something similar?

![sass-no-autocomplete](https://cloud.githubusercontent.com/assets/7037108/24201539/6302ad56-0f21-11e7-97a2-6fd32a34f2ea.jpg)

Use version of 1.8.0.

**Comment by swmitra** [comment]
@DalonK Brackets in it's current for doesn't provide any tooling out of the box for tab based SAAS format. However you may try to find some relevant extensions in brackets extension registry.

**Comment by DalonK** [comment]
Have found what I've been searched for: [Brackets SASS Code Hints](https://github.com/sprintr/brackets-sass-code-hints).

**Comment by petetnt** [comment]
@DalonK great! Closing as solved 😸

**Comment by ydd3064** [comment]
How to make Brackets compile sass?

**Comment by petetnt** [comment]
Hi @ydd3064, see https://github.com/jasonsanjose/brackets-sass for autocompiling SASS inside Brackets

**Comment by ydd3064** [comment]
@petetnt ,I can't understand……

**Comment by kumarabhi007** [comment]
@ydd3064 you can use the terminal(cmd or terminal) to set a watch for your sass files and automatically dump it into your css files
1. install ruby
2. in search explorer open cmd using ruby
3. go to your work folder in cmd
4. sass --watch yourSASSFileName.sass:yourCSSFileName.css
5. this will automatically set a watch and whatever changes you do in your sass file will reflect in your css file

**Comment by Aakrity1105** [comment]
I am facing same problem as @SkyFlame00,does any have better suggestions?
