### ISSUE TITLE
best upgrading procedure for brackets on windows 10

### ISSUE THREAD

**Issue by TheMongooseBytes** [adobe/brackets#13228]
Hi

I am running Brackets 1.8 on my Windows 10 machine, a HP z620 workstation and I was prompted by Brackets to upgrade.

My question is simple: Do I uninstall this 1.8 version before installing 1.9 or will 1.9 overwrite the 1.8 install by default and will I run into issues performing the upgrade this way?

**Comment by petetnt** [comment]
Hi @TheMongooseBytes,

you can just run the 1.9. installer: it will overwrite the Brackets files, but you will keep your settings, extensions, history and other related, user specific things. There shouldn't be any issues performing the upgrade whatsoever.

**Comment by petetnt** [comment]
Closing as answered
