### ISSUE TITLE
Replace .border-radius mixin with border-radius css in brackets_patterns_override.less

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#13227]
### Description

In `src/styles/brackets_patterns_override.less` there are some mentions of `.border-radius` mixin.
These can safely replaced with the corresponding css `border-radius`.
So `.border-radius(0 0 3px 3px);` will be `border-radius: 0 0 3px 3px;`

There are some other mentions in the tree, but they are in bootstrap files or in files where it is necessary, so there should be left untouched.

**Comment by parthsharma2** [comment]
Hi, I would like to take this issue

**Comment by parthsharma2** [comment]
Made a pull request to fix this issue. Checkout #13235
