### ISSUE TITLE
Unable to download v1.9

### ISSUE THREAD

**Issue by muba00** [adobe/brackets#13222]
Download fails after 3-10%. 
![screen shot 2017-03-25 at 12 08 17 am](https://cloud.githubusercontent.com/assets/11701997/24311809/31e282a8-10ef-11e7-9c98-854c7eaf9976.jpg)

**Comment by saurabh95** [comment]
@muba00 Can you try downloading the dmg from https://github.com/adobe/brackets/releases/download/release-1.9/Brackets.Release.1.9.dmg

**Comment by muba00** [comment]
@saurabh95 Here is the result..
![screen shot 2017-03-25 at 11 48 18 pm](https://cloud.githubusercontent.com/assets/11701997/24325609/9edeecc2-11b5-11e7-93a4-f15e1229e803.jpg)
