### ISSUE TITLE
La fenêtre d'édition du code n'apparait pas. Comment puis-je la faire apparaitre ?

### ISSUE THREAD

**Issue by Manon52** [adobe/brackets#13223]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by ficristo** [comment]
Google translated:
The code editing window does not appear. How can I make it appear?
Can you give use more info? Maybe a screenshot?

**Comment by Manon52** [comment]
![capture d ecran 2017-03-25 a 16 56 30](https://cloud.githubusercontent.com/assets/9582528/24331359/8e43b88e-1200-11e7-8f98-d438e34f0c62.png)

**Comment by Manon52** [comment]
Oups  ! This one is more explicite : 
![capture d ecran 2017-03-25 a 16 56 41](https://cloud.githubusercontent.com/assets/9582528/24331374/e7eb26c4-1200-11e7-9e07-dcf592c6827e.png)

If i drag the line : 
![capture d ecran 2017-03-26 a 08 50 16](https://cloud.githubusercontent.com/assets/9582528/24331391/54758a8c-1201-11e7-99f4-224d2703cd88.png)

I can drag it down.
![capture d ecran 2017-03-26 a 08 51 44](https://cloud.githubusercontent.com/assets/9582528/24331397/82a0e9e2-1201-11e7-8bd1-0bc3e0272c95.png)

I have to do this each time I look Css code and come back on html page.

**Comment by ficristo** [comment]
It seems to me a problem within one of the extensions you have installed.
If you run `Debug \ Reload Without Extensions` can you reproduce your issue?

**Comment by Manon52** [comment]
OK !  I got it ! Thank you very much ! It's working !

**Comment by ficristo** [comment]
Closing as extension problem
