### ISSUE TITLE
Brackets UI Themes not working/showing up? 

### ISSUE THREAD

**Issue by APoetsGutReaction** [adobe/brackets#13229]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
Yes? It's the themes not showing up that's the problem, and they don't show up with the extensions off either.
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
Yes, couldn't find any similar posts.
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?
Yes.

### Description

 Trying to install a new Brackets UI Theme. No matter what I do, the colour/background of Brackets stays the same (as the default). Tried all combinations of themes, reloading, enabling/disabling, deleteing and reinstalling plugins, restarting Brackets, restarting my mac. Nothing changes anything. All other (non-theme) plugins work fine. I have Brackets UI Theming Enabler installed too. Screenshots attached of all my plugins and the fact that the brackets theme is unchanged (in the background).

### Steps to Reproduce

1. Go to the Brackets Extension Manager within the application
2. Add a UI theme, either by going to the themes pannel and installing one, copying it from a URL, or dragging a .zip file.
3. Close the Extension Manager and reload the plugins.

**Expected behavior:** The theme I installed to change the appearance of the UI.

**Actual behavior:** Nothing. The colour/background of Brackets stays the same (as the default). 

### Versions

Please include the OS and what version of the OS you're running.
macOS Sierra v.10.12.3, Brackets build 1.9.0-17312 
![screen shot 2017-03-26 at 8 09 24 pm](https://cloud.githubusercontent.com/assets/26033413/24334324/2c23a49c-1260-11e7-8f95-51ae8809717f.png)
![screen shot 2017-03-26 at 8 09 29 pm](https://cloud.githubusercontent.com/assets/26033413/24334326/2c5cba20-1260-11e7-82bd-43024d7691bd.png)
![screen shot 2017-03-26 at 8 09 35 pm](https://cloud.githubusercontent.com/assets/26033413/24334327/2c5d1da8-1260-11e7-8f27-3f14c8e423c1.png)

**Comment by petetnt** [comment]
Hi @APoetsGutReaction,

Sounds like a broken extension to me or faulty configuration file to me. 🤔 

Can you check out Debug -> Show Developer Tools -> Console to see if there are any visible errors there.

**Comment by ficristo** [comment]
Just to be sure, after you installed the theme, have you tryed to change the theme with `View \ Themes...` menu?

**Comment by erinlloyd** [comment]
ficristo is a genius

**Comment by jesusbravo50** [comment]
simple solution, Thanks ficristo!

**Comment by rajhlinux** [comment]
Thats really dumb, have to go to two different places. One place to install it, another place to apply the install. Really stupid, but hey its free no wonder people will pay for common sense.

**Comment by Amypate85** [comment]
> Thats really dumb, have to go to two different places. One place to install it, another place to apply the install. Really stupid, but hey its free no wonder people will pay for common sense.

I'm sorry you aren't capable of going to 2 different places. That is sad.

**Comment by Amypate85** [comment]
@APoetsGutReaction, you could have said thank you.
