### ISSUE TITLE
No WebRTC support for extensions

### ISSUE THREAD

**Issue by RationalCoding** [adobe/brackets#13233]
The dev console states that Brackets uses Chrome 49, and some parts of the WebRTC spec are present, but most of it is missing. (Notably RTCPeerConnection)

Is this due to Brackets being on an older Chromium build, or have these features been disabled?

**Comment by petetnt** [comment]
Hi @RationalCoding,

that's exactly it. We are looking for updating the CEF (Chromium Embedded Frame) to match Chrome 58 for the next release. Meanwhile you try communicating with `WebRTC` through the Node Connection and something like https://github.com/js-platform/node-webrtc

**Comment by RationalCoding** [comment]
I figured that was the case. Well, looks like embedded video chat will have to wait :p 

Thanks!

**Comment by swmitra** [comment]
Ah.. Missed this thread earlier. I am a bit confused now. I thought starting Brackets with '--enable-media-stream' does the job and you can get the av stream through user media handle. I have a working embedded video chat app running with Brackets 1.8.

**Comment by RationalCoding** [comment]
@swmitra So getUserMedia is exposed by starting with that flag? Interesting. What about RTCPeerConnection?

**Comment by RationalCoding** [comment]
It looks like Chrome has had a prefixed RTCPeerConnection since v23. I don't think the Chromium version is the cause of this.

**Comment by RationalCoding** [comment]
SOLVED: On passing the flag `--enable-media-stream --enable-usermedia-screen-capturing`, the prefixed `webkitRTCPeerConnection` is available.
