### ISSUE TITLE
There HAS to be a bug in Brackts because my javasript event "onmouseover" is not working in JavaScript! SOMEONE HELP!!!

### ISSUE THREAD

**Issue by CheckLife** [adobe/brackets#13239]
I downloaded Brackets TODAY and converted all my files to use on there. When I literally run the exact same code in NotePad++ the "onmouseover" event DOES NOT WORK PROPERLY. So basically i converted from Notepad++ to Brackets today and the issue is when i use the "onmouseover" event the image transition is immediate, but when i use the "on-click" event the transition is smooth. However when i use the exact same code in Notepad++ either event executes my function properly. I even RECORDED A VIDEO of whats going on and upload it to my repository  folder titled "Brackets_Bug" to show whats happening with my event. The onmouseover event either doesn't work properly or there is something wrong with Brackets. HOW do i contact them directly for their support OR can SOMEONE PLEASE HELP!!!

**Comment by petetnt** [comment]
Hi @CheckLife,

are you using the Live Preview feature of Brackets? 

Brackets the code runs on actual browsers and shouldn't have anything to do with Brackets itself. However there might be differences on _how_ you run the code: running the code from the FileSystem (with Notepad++) might behave differently than over the remote debugging protocol (like through Brackets Live Preview).

**Comment by CheckLife** [comment]
@petetnt Did you see the video of whats happening in my repository? I literally run both events in NotePad++ and it works fine. What is a solution to this!!!???? because "onmouseover" should not produce a faster transition if i haven't changed anything in my function or CSS

**Comment by zaggino** [comment]
@CheckLife Please watch your tone. I've checked your video, cloned your code and the problem has nothing to do with Brackets, I can reproduce it even when changing code through Notepad++.

Your problem is that by moving the mouse across button, `onmouseover` is executed multiple times. You can try to write
```
function slow() {	
console.log('slow executed');
```
and check the developer tools for how many times it outputs slow executed text.

Simple solution to this is:
```
    var slowHasRun = false;
    function slow() {	
        if (slowHasRun) { return; }
	slowHasRun = true;
        document.getElementsByClassName("tracy")[0].style.opacity = 0;
        ... rest of your code
```

Closing this as it's not a Brackets issue.
