### ISSUE TITLE
ligatures not working

### ISSUE THREAD

**Issue by MandarSant** [adobe/brackets#13234]
### Description

[ligatures of fira code not working in newest version of brackets 1.9 refer to the following [issue](https://github.com/tonsky/FiraCode/issues/393#issuecomment-289385186) ] 

**Actual behavior:**

 [When I change font line, it applies the changes and shows everything(ligatures ) in Fira Code. But when I restart Brackets it starts in default font]

### Versions

windows 8.1 
Brackets 1.9

**Comment by ficristo** [comment]
Closing as a dupe of #13221. (I hope to have understood the issue correctly)
