### ISSUE TITLE
"defaultPreferences.json" Error: Found a punctuator character '}' when expecting a quoteless string (check your syntax) at line 564,2 >>>	}

### ISSUE THREAD

**Issue by hackseoer** [adobe/brackets#13230]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

"defaultPreferences.json" Error: Found a punctuator character '}' when expecting a quoteless string (check your syntax) at line 564,2 >>>	}

```
	...
	"xmlhint.options":
	}
}
```

Maybe is:

```
	"xmlhint.options": {}
}
```

You can try:
http://hjson.org/try.html

### Versions

Brackets 1.8 1.9
Windows 10

**Comment by ficristo** [comment]
The `defaultPreferences.json` should not be modified, and xmlhint is not part of Brackets defaults.
Since I think it is a problem with an extension I close this as such.

**Comment by hackseoer** [comment]
@ficristo Thanks, I have found the cause of the error, from the extension: [htmlHint](https://github.com/cfjedimaster/brackets-htmlhint)
