### ISSUE TITLE
Auto-Identation and Switch Statements

### ISSUE THREAD

**Issue by jdiehl** [adobe/brackets#1324]
I noticed that the auto-indentation seems to be confused after switch statements. Consider the following (JSLint-approved) code:

function foo(a) {
    "use strict";
    switch (a) {
    case 1:
        break;
    }
}

When hitting enter after the first closing }, auto-indentation inserts 3 tabs (1 would be correct).
When hitting enter after the second closing }, auto-indentation again inserts 3 tabs (0 would be correct).
This goes on, even if additional functions, scopes, whatever are defined, auto-indentation always adds 3 tabs.

**Comment by prafulVaishnav** [comment]
Fixed by PR #9387 Closing it.
