### ISSUE TITLE
working on .php extension 

### ISSUE THREAD

**Issue by elrasool** [adobe/brackets#13241]
Hello . The most feature I missed in Brackets is working with .php files . I hope you solve this problem because I don't want to use any other editors while working on server side files . I'm waiting for this , and I know you will do it . congratulations .

**Comment by petetnt** [comment]
Hi @elrasool,

Brackets already supports syntax highlighting for PHP files, and there's some extensions like https://github.com/Brackets-PHP/Brackets-PHP-SmartHints that provide additional features if that helps 👍

**Comment by petetnt** [comment]
Closing as answered
