### ISSUE TITLE
Noob needs your help: Brackets doesnt start 

### ISSUE THREAD

**Issue by FriedrichLeineweber** [adobe/brackets#13249]
Hey, as the title says: I installed Brackets to do some html stuff from the arch user repository, but it just looks like this when I start it: ![brackets](https://cloud.githubusercontent.com/assets/26656736/24512257/605d012a-156e-11e7-98e5-44061500a69d.png)
 and is stuck at the page. Cant close it either. Tried reinstalling. Read the troubleshooting page.

When I start it from the terminal I get this error most of the time: [0330/173034:ERROR:tcp_listen_socket.cc(72)] Could not bind socket to 127.0.0.1:9234

What I downloaded: https://aur.archlinux.org/packages/brackets/

I`m running 64bit antergos (arch).

Thanks in advance, Fritz

**Comment by edyedy123** [comment]
Hey, I'm in an open source class and my prof made a very comprehensive guide for installing brackets and Mozilla thimble to use it if you choose to. It is a guide to fixing bugs in Mozilla thimble code but it dose tell you how to install brackets. Hopefully this helps. 
Heres the link:
http://blog.humphd.org/fixing-a-bug-in-mozilla-thimble/

**Comment by Fallon9111** [comment]
I am also having this issue (i3 wm, arch). I fixed this by instead installing brackets-bin from the AUR

**Comment by FriedrichLeineweber** [comment]
Yeah have it installed to. Doesnt help sadly

**Comment by FriedrichLeineweber** [comment]
Nevermind it worked! Thank you very much!
