### ISSUE TITLE
Unable to change font family AND font size

### ISSUE THREAD

**Issue by brunnopleffken** [adobe/brackets#13240]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

Go to View > Themes.
Change the font size, the font family is automatically changed to Source Code Pro.
Now go to View > Themes and change the font family, the font size is automatically reseted to the default (12 or 13 I guess), ignoring the one I saved before.

It's just one or another...

### Versions

Release 1.9 build 1.9.0-17312 (release 189f6d39a) 
build timestamp: Tue Mar 21 2017 03:04:51 GMT-0700

macOS Sierra 10.12.3

**Comment by guillecro** [comment]
Watch this issue
https://github.com/adobe/brackets/issues/13221
It has been reported

**Comment by swmitra** [comment]
Closing this as fixed by #13279 and available as part of 1.10 pre-release 1 build https://github.com/adobe/brackets/releases/tag/release-1.10-prerelease-1
