### ISSUE TITLE
Feature Request: Show project path

### ISSUE THREAD

**Issue by mikemedd** [adobe/brackets#13242]
Could you please make it possible to view the current project's path in the app header or Open Folder menu? Currently, the only way to be sure of which project is open is to view one of the files in Finder or reopen the project. Thank you.

**Comment by haslam22** [comment]
Hovering over the project name on the sidebar shows the full path for me. Which OS are you using?

**Comment by mikemedd** [comment]
Thanks, @haslam22 . I'm using MacOS Sierra and that works. The hover is a bit slow but its sufficient.
