### ISSUE TITLE
Problem with Wiki

### ISSUE THREAD

**Issue by Blackweda** [adobe/brackets#13252]
This is just a suggestion for the Wiki: 

https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets

I tried to follow all the steps until:

6. Add an "upstream" remote: git remote add upstream https://github.com/adobe/brackets.git

7. Run setup_for_hacking script:

Mac:	tools/setup_for_hacking.sh "/Applications/Brackets.app"

Windows:	_tools\setup_for_hacking.bat "C:\Program Files (x86)\Brackets"_ 
**(MUST be run in a Command Prompt started with "Run as Administrator")**

Linux:	sudo tools/setup_for_hacking.sh "/opt/brackets"

Now, I must be really stupid, because I went into command prompt as administrator and tried running the line of code right away. It would be better to to leave a note saying to go into Command Prompt and find your repo inside command prompt and do all this!) Wasted an hour of my life.

**Comment by swmitra** [comment]
@Blackweda Thanks a lot for letting us know about this ambiguity in the setup for hacking steps. We will update the wiki with more specific info for this step.

**Comment by petetnt** [comment]
Thanks @Blackweda, addressed the issue by modifying the step to:

> `tools\setup_for_hacking.bat "C:\Program Files (x86)\Brackets"`
_(MUST be run in a Command Prompt started with "Run as Administrator". If you opened a new Command Prompt you might need to navigate back to the repository folder you cloned in step 3 with eg. cd C:/path/to/brackets`)_ .

**Comment by Blackweda** [comment]
thanks a lot guys!! :)
