### ISSUE TITLE
Could you please list the theme used on the homepage? I really like it!

### ISSUE THREAD

**Issue by BluTiger** [adobe/brackets#13255]
I didn't know where to add comments/suggestions and this was the only link I could find. Sorry if I'm in the wrong place. On the homepage for brackets.io there's a really cool theme being used for markup and I'd like to use it! :)

**Comment by haslam22** [comment]
It's the [Coolwater ](https://github.com/Brackets-Themes/Coolwater)theme. It's available in the extension manager, or you can download the .zip and drag into Brackets. Hope that helps.

**Comment by petetnt** [comment]
Closing as answered, glad you liked the theme @BluTiger 👍
