### ISSUE TITLE
why brackets is using network?

### ISSUE THREAD

**Issue by muba00** [adobe/brackets#13253]
![screen shot 2017-03-31 at 12 45 43 am](https://cloud.githubusercontent.com/assets/11701997/24576078/3c40a874-16c6-11e7-8778-2a2f13177c96.jpg)

**Comment by swmitra** [comment]
Brackets core does use network to upload anonymous Health Data pertaining to feature usage,  extension usage and some other relevant data. But there might be some other user installed extensions which uses some network features. Do let us know if this clarifies your doubt.

**Comment by redmunds** [comment]
@muba00 You can go to `Help > Health Report` to turn off sharing of anonymous data if you don't want to participate.

**Comment by muba00** [comment]
It's not health report:
[https://i.imgur.com/P32YHxI.jpg](url)

**Comment by redmunds** [comment]
Try _Debug > Reload Without Extensions_ to determine if it still happens or not when no extensions are loaded.

**Comment by muba00** [comment]
Solved, without extensions it's not using network. thanks for your help @redmunds
