### ISSUE TITLE
[Wiki] Update Releases list ?

### ISSUE THREAD

**Issue by bokub** [adobe/brackets#13257]
Hi,

Just wanted to let you know that in the [homepage of the wiki](https://github.com/adobe/brackets/wiki#releases) , the last release note if for **version 1.6**.

You might want to change that so people can easily find the one for 1.9.
Just sayin'

![capture](https://cloud.githubusercontent.com/assets/17952318/24590099/458199da-17e7-11e7-95eb-1739538ee45b.PNG)

**Comment by petetnt** [comment]
Thanks @bokub, added the release notes to the list 👍
