### ISSUE TITLE
Braces auto-close and indentation

### ISSUE THREAD

**Issue by moseleyi** [adobe/brackets#13258]
I installed newest version of Brackets of my new laptop and not sure if I had an extension previously or if my old machine (older version) had different settings.

Auto-close for braces is switched on. For example I'm pressing a tab in CSS file name of a class and when I press opening curly brace the closing one appears (which is great) but the indentation disappears and everything is moved to the far left.

Is this a default behaviour and do I have to install an extension to disable it?

**Comment by ficristo** [comment]
Do you have the same of https://github.com/adobe/brackets/issues/13305 ?
