### ISSUE TITLE
Anyway we can get an SFTP option? None of the SFTP options work with current brackets

### ISSUE THREAD

**Issue by BluTiger** [adobe/brackets#13260]
I only need SFTP and the ability to download/upload from remote server. Is this possible? I've tried all 4 that come up when typing SFTP and none of them work with current brackets.

**Comment by BluTiger** [comment]
For example:
 eqFTP errors out.
osFTP errors out.
Synapse has no icons for adding servers (+, folder, etc)

**Comment by saurabh95** [comment]
Did you try SFtpUpload it seems to work

**Comment by GreenSage** [comment]
I'm reinstalling right now! Would be nice. :) I'll be sure to update.

**Comment by BluTiger** [comment]
I'm reinstalling right now! Would be nice. :) 

It seems to connect but it's requiring me to full download the project first before it can work. I can work with this. :)
