### ISSUE TITLE
Selected text that has bg color

### ISSUE THREAD

**Issue by codingForFood** [adobe/brackets#13286]
I'm using version 1.9
I added this to change the background color of my php code.
.cm-m-clike, .cm-meta {background: #e9e9e9;}
Which works but I can't see my text selection anymore.
How can I change the selected text background color for those classes?
![brackets1](https://cloud.githubusercontent.com/assets/27122964/24835124/ccd92f0e-1d2a-11e7-91bc-02da786f7e59.jpg)

I can't find any other place to ask this.  Thank you for your time.

**Comment by saurabh95** [comment]
Try this
`.CodeMirror .CodeMirror-selected {
    background-color: #e9e9e9;
}`

**Comment by codingForFood** [comment]
That changes all selected text to the same background as my php background color.  But I am still not able to see what I am selecting in php.

**Comment by codingForFood** [comment]
I was able to solve this problem by making the php code background color slightly transparent.
