### ISSUE TITLE
Using Operator Font

### ISSUE THREAD

**Issue by kneeki** [adobe/brackets#13291]
### Description

Using any of the the (.otf) [Operator Font](https://www.typography.com/blog/introducing-operator) Italic versions causes Brackets to revert to what I assume is Arial. Any of the 'standard' Operator fonts work fine (Light, Medium, Book, Bold, ect).

Without Italic
![Without Italic](http://i.imgur.com/fkvkvDc.png)

With Italic
![With Italic](http://i.imgur.com/Mnzvhwe.png)

### Steps to Reproduce

- Operator Mono xxx Italic
- Operator Mono xxx-Italic
- Operator-Mono-xxx-Italic
- OperatorMonoxxxItalic
- OperatorMonoxxx-Italic
- Operator Mono xxx-Italic

**Expected behavior:** The font is applied to the Brackets Editor

**Actual behavior:** A 'default' font, assumed to be Arial is applied instead.

### Versions

```
                          ./+o+-       dave@dave-laptop
                  yyyyy- -yyyyyy+      OS: Ubuntu 16.10 yakkety
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.8.0-46-generic
           .++ .:/++++++/-.+sss/`      Uptime: 26m
         .:++o:  /++++++++/:--:/-      Packages: 3118
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 4.3.46
       .:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
  .++/+:+oo+o:`             /sssooo.   DE: Gnome 
 /+++//+:`oo+o               /::--:.   WM: GNOME Shell
 \+/+o+++`o++o               ++////.   WM Theme: Flat Plat
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Flat-Plat-light-laptop [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Numix-Circle
        \+.++o+o``-````.:ohdhhhhh+     Font: SFNS Display 10
         `:o+++ `ohhhhhhhhyo++os:      CPU: Intel Core i7-6700HQ CPU @ 3.5GHz
           .o:`.syhhhhhhh/.oo++o`      GPU: GeForce GTX 980M
               /osyyyyyyo++ooo+++/     RAM: 11283MiB / 32128MiB
                   ````` +oo+++o\:    
                          `oo++.      
```

```
Release 1.9 experimental build 1.9.0-17312 (release 189f6d39a) 
build timestamp: Tue Mar 21 2017 09:36:10 GMT+0000
```

**Comment by ficristo** [comment]
So you want to see your code in italic?
I reminds me something like https://github.com/adobe/brackets/issues/12860

**Comment by kneeki** [comment]
Well, it's not really in italic. Here's what the end result should appear as:

![operator italic](http://i.imgur.com/UQFYbj4.png)

**Comment by sldobri** [comment]
you need add the font name like:
OperatorMono-Book
OperatorMono-Light
OperatorMono-Medium

**Comment by kneeki** [comment]
@sldobri That doesn't work either.

**Comment by ficristo** [comment]
Looking around, I don't think your use case is supported by default.
You could create a [new theme](https://github.com/adobe/brackets/wiki/Creating-Themes) and apply the italic style to the classes you expect to be in italic.

**Comment by kneeki** [comment]
@ficristo That was exactly the problem! I modified my current theme and added `font-style: italic;` to one of the css selectors and it's working as expected.
