### ISSUE TITLE
How to change font in theme ?

### ISSUE THREAD

**Issue by gthibaud** [adobe/brackets#13304]
Hi,
I'm working on a Theme for Brackets, and I want to use a custom font instead of the default Brackets font. 
I tried to use a @font-face in the theme.less file, but it seem to not working...
`@font-face {
        font-family: 'myfont';
        src: url(fonts/myfont.ttf) format('ttf');
        font-weight: normal;
        font-style:normal;
}

.CodeMirror, .CodeMirror-scroll {
    background-color: @background;
    color: @foreground;
    line-height: 25px;
    font-family: 'myfont', Menlo;
}`

Does anyone have any idea how to do this?

Thank you very much for your help ! ;)

**Comment by saurabh95** [comment]
You can change `font-size` and `font-family` in preferences file.
Go to Debug->Open Preferences File. Then in the right pane in brackets.json file edit `"fonts.fontSize"` and `"fonts.fontFamily"`

**Comment by saurabh95** [comment]
Also are you using 1.9 version? If yes, then there are some issues related to font-size and font-family in this, so you can install a stable pre-release for 1.10 in which above issue is fixed, https://github.com/adobe/brackets/releases/tag/release-1.10-prerelease-1

**Comment by gthibaud** [comment]
Ok thank you very much !
I will download the pre-release 😊👍🏻

**Comment by JLewis82** [comment]
Thank you so much!

**Comment by GameAppsBD** [comment]
thanks

**Comment by bnarris** [comment]
i have failed coz  the  font-size and font-family nothing changing

**Comment by iffitheking** [comment]
For me easier way is to go to view >> Themes... >> font-family 
Make sure font name should be within quotes
