### ISSUE TITLE
How to disable the reverse inspect ?

### ISSUE THREAD

**Issue by Doremiska** [adobe/brackets#13307]
Hi, I'm starting to get bothered by the new feature "reverse inspect", it's moving me in my code and I spend time always to come back where I was and I didn't find any way to disable this feature. Can you please let me know if there is a way to disable this feature ?

**Comment by swmitra** [comment]
We don't have a dedicated preference for this, but setting 'livedev.wsport' to null should do the trick as websocket for reverse inspect won't be created in that case.

**Comment by swmitra** [comment]
Just realized it might not work. Let us work on this to expose a preference.

**Comment by AntonioDeCasper** [comment]
Same problem here. I want to disable this feature but i can't...

**Comment by onmyflow** [comment]
Same problem here,
its really starting to annoy me, when I'm working on a section **at the bottom of my website**, that has the same class as one at the top of my website, and then the browser **always jumps to the top**. 
But I also wouldn't want to work without live preview ... 
Well then. 
I'm downgrading again.

**Comment by siuangie91** [comment]
Same here! I thought I was the only one super annoyed by it. I was annoyed within the first 5 minutes of using it. Shame, because I liked the other updated features.

**Comment by G3-Logic** [comment]
Another request to PLEASE give us a way to turn reverse inspect off. Can't think of any situation where I would want to have to sift through my code to find out where I was, just because I happened to click on an element in the browser. SUPER annoying.

**Comment by G3-Logic** [comment]
Any progress on this? Thought Enable/Disable default extensions in 1.10 would mean that I could turn this off. But not seeing it.

**Comment by manchinesmith** [comment]
does this work with the livedev.multibrowser true
