### ISSUE TITLE
CSS Indents removed when closing a declaration

### ISSUE THREAD

**Issue by ElecRei** [adobe/brackets#13305]
### Description

For a while now when working on a CSS file in Brackets whenever I open or close a declaration it removes any indentation. I've tried searching for a solution but I only find submitted issues about auto indentation and nothing about this. I turned off auto-close and also fiddled around with the preferences but nothing seems to fix this.

### Example:

So I'll type the selector:

![example1](https://cloud.githubusercontent.com/assets/10943594/25064803/313ec5b8-21d0-11e7-867c-70535f6e6e85.gif)

Then once I put an opening "{" it'll remove my indentation, the same thing happens if I were to close it:

![example2](https://cloud.githubusercontent.com/assets/10943594/25064804/32f49c02-21d0-11e7-8016-1068a34983a1.gif)

All I'm expecting is that it will retain the indentation I did before typing out my CSS. This doesn't happen when I'm in an HTML or JS file so I'm not sure if this is a bug or intended.

### Version

Currently using Brackets 1.9 build 1.9.0-17312 on Windows 10.

**Comment by ficristo** [comment]
I think what you see it is the expected behaviour.
You could try to disable the `smartIndent` option in the preferences, maybe only for CSS like this:
```json
{
    "language": {
        "css": {
            "smartIndent": false
        }
    }
}
```

**Comment by ElecRei** [comment]
Thanks for the reply, that fix worked.
