### ISSUE TITLE
Drag and Drop is only supported for the open files tab, not for the file overview

### ISSUE THREAD

**Issue by tweakimp** [adobe/brackets#13306]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [X] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

While it is possible to drag and drop files in the open files tab, it is not possible with files in the project folder.

![alt text](https://media.giphy.com/media/3ohzdGArkcleXljrtS/giphy.gif)

### Steps to Reproduce

1. Try to drag and drop in the open files tab > works.
2. Try to drag and drop in the project folder overview > doesnt work.

**Expected behavior:**
2. Try to drag and drop in the project folder overview > works.

### Versions
Windows 10
Brackets Version`Release 1.9 Build 1.9.0-17312 (release 189f6d39a) `

**Comment by tweakimp** [comment]
Noone?

**Comment by redmunds** [comment]
@tweakimp Correct -- there is no way to change order of files in project folder using drag/drop. It would be difficult to keep track of random display order of every file in every subfolder of every project.

There is a `sortDirectoriesFirst` preference that you can use to change the order. Is there some other sort order that you would prefer?
