### ISSUE TITLE
I can not  found Extract for Brackets (Preview)

### ISSUE THREAD

**Issue by aloha1003** [adobe/brackets#13309]
I install Bractkets  version 1.9
But I don't see Extract for Brackets (Preview) on right sidebar
How can I fix it ?

**Comment by petetnt** [comment]
Hi @aloha1003,

sadly the Extract For Brackets service was discontinued: http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/?lang=en

Like the blog post says, the feature is available in Dreamweaver CC now, if that helps.

Sorry for the inconvenience.

**Comment by abinabrahamanchery** [comment]
Any Alternative for extract addon ??

**Comment by pedrozo96** [comment]
.
