### ISSUE TITLE
Can't install on WIndows 10 with error "must be on local hard drive"

### ISSUE THREAD

**Issue by luison** [adobe/brackets#13311]
### Description
Error installing to new installation of Windows 10.
Any destination I choose on my system disk (C:) fails with the attached error.
![brackets](https://cloud.githubusercontent.com/assets/745632/25174614/38314b5e-24f8-11e7-8829-30565feadf37.png)

### Steps to Reproduce

1. Download 1.9 msi installation. Tried moving the installer to C: as well. 
2. Install (administrative privileges or not)
3. Accept default destination or change to any other.

**Expected behavior:**  Install

**Actual behavior:** Attached screenshot no matter what I do.

### Versions
1.9
Recently installed Windows 10 Pro updated.

**Comment by luison** [comment]
Just found a workaround as this has something to do with Windows and that kind of installer and it seems to be running around for years (tipical windows). Same issue and solution as:

https://github.com/adobe/brackets/issues/2407

Installing via an administrative cmd and "msiexec /i "

**Comment by ficristo** [comment]
Closing as a dupe.
