### ISSUE TITLE
css wont link to html

### ISSUE THREAD

**Issue by Shawn58** [adobe/brackets#13315]
![preview 1](https://cloud.githubusercontent.com/assets/27468422/25240632/57e4ce2a-25c1-11e7-85bf-14aea3486b1b.png)
![preview 2](https://cloud.githubusercontent.com/assets/27468422/25240636/59c5099e-25c1-11e7-9054-2ef3e585d743.png)
![preview part 3](https://cloud.githubusercontent.com/assets/27468422/25240647/5e12e3c2-25c1-11e7-8db3-f2f923ca5dd2.png)
![preview part 4](https://cloud.githubusercontent.com/assets/27468422/25240650/5fb0aa34-25c1-11e7-9deb-8f79c6b1ce20.png)
![preview part 5](https://cloud.githubusercontent.com/assets/27468422/25240654/63303616-25c1-11e7-9dfe-85b57603cf02.png)

my css will not link ive tried litteraly everything please someone help me and im still in the getting started folder

**Comment by swmitra** [comment]
'style.css' doesn't exist in your current project root.  Looking at the first image, I could see 'chat style.css' . Either change the link red to this file or rename the physical file.

**Comment by Shawn58** [comment]
ok thanks im new to this tho lol how am i supposed to do that try to simplify it as best as you can please man thanks for the response tho i really appreciate it lol

**Comment by redmunds** [comment]
@Shawn58 Brackets features such as Live Preview and Find in Files work based on the current "project".

I can see from your screenshots that you are still in the Getting Started project. You need to change to _your_ project.

A "project" in Brackets is simply a folder that contains your files.

Yes, Brackets will allow you to open and edit files outside of your "project". They show up in your Working Set. Find in Files does search these files, but they don't work in Live Preview.

To set the current "project", use _File > Open Folder..._ and choose a folder on your system that contains all of your project files.

**Comment by Shawn58** [comment]
ok i fixed it thanks guys lol i was going crazy

**Comment by Shawn58** [comment]
![image](https://cloud.githubusercontent.com/assets/27468422/25244823/3b680780-25d0-11e7-8685-94d8382b77ae.png)

**Comment by Shawn58** [comment]
![image](https://cloud.githubusercontent.com/assets/27468422/25244849/56b6c0da-25d0-11e7-8e95-f091d45d5d3e.png) lol i got the login page to work lol thanks alot

**Comment by Shawn58** [comment]
Ok man i might need a little more assitance lmao my background imgage doesnt show up lol why is this happening

**Comment by ficristo** [comment]
Sorry but this place is to report issues about Brackets itself not about the correctness of your code.
