### ISSUE TITLE
Site bug download not working

### ISSUE THREAD

**Issue by tallesairan** [adobe/brackets#13322]
I don't know if this is the right place to report this bug, but I noticed today when you download, and a wordpress error in json

[http://prntscr.com/ez65gw](http://prntscr.com/ez65gw)

`Uncaught SyntaxError: Unexpected token 
http://blog.brackets.io/feed/json?callback=jQuery211032960339032121344_1492787729067&_=1492787729068
`

**Comment by xshotD** [comment]
This bug is confirmed for me, because I downloaded, checked dev tools and the error did pop up.

**Comment by petetnt** [comment]
Thanks for reporting, I reposted this to https://github.com/adobe/brackets.io/issues/196
