### ISSUE TITLE
Compiling brackets

### ISSUE THREAD

**Issue by psingl** [adobe/brackets#13324]
Hi there!
I have downloaded this repo and want to compile code of this repo into a msi setup file as offered by brackets on its site. Can anybody help me?

**Comment by saurabh95** [comment]
You have to clone https://github.com/adobe/brackets-shell/ also, and for msi generation steps are mentioned in this [README ](https://github.com/adobe/brackets-shell/blob/master/installer/win/README.MD)

**Comment by psingl** [comment]
Thanks @saurabh95
