### ISSUE TITLE
extension manager isn't working

### ISSUE THREAD

**Issue by rexrjd** [adobe/brackets#13326]
### Prerequisites

* [+] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [+] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [+] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

Cant install any extension from fancy gui, brackets thumbnail keep spinning forever. Meanwhile if i just move extension zip to folder with extensions, it will work fine.
 

### Versions

![out](https://cloud.githubusercontent.com/assets/27899754/25307607/8f1145d0-27ac-11e7-9370-48ba26609b23.gif)
![screenshot_20170422_224854](https://cloud.githubusercontent.com/assets/27899754/25307696/feaede60-27ad-11e7-8d93-4bc9869caf05.png)
![screenshot_20170422_230425](https://cloud.githubusercontent.com/assets/27899754/25307797/3b4dc9e2-27b0-11e7-97da-83334d465472.png)

**Comment by ficristo** [comment]
Could you open the Developer Tools before opening the Extension Managere and report here if there are any issues?
