### ISSUE TITLE
Disable autoclosing

### ISSUE THREAD

**Issue by GermanJohn** [adobe/brackets#13325]
Hello everyone,

so this issue has been answered already. It's just that the solution didn't work for me for some reason.
So whenever I open a bracket, say, `<p>,` it auto-closes it. This is annoying, as I'm editing existing code for practice at the moment - I just have to erase the added `</p>.` I tried the troubleshooing outlined [here](https://github.com/adobe/brackets/issues/12066). This is what my brackets.json looks like:

> {
    "fonts.fontSize": "12px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "soimon.DocumentOutliner.enabled": true,
    "closeBrackets": false,
    "closeTags": false
}

So... how do I get rid of that behaviour?

EDIT: fixed code
EDIT: OS is Windows 10, Version of Brackets is release 1.9 build 1.9.0-17312

**Comment by redmunds** [comment]
@GermanJohn `closeTags` format is different. Try this:

```json
	"closeTags": {
		"dontCloseTags": [],
		"indentTags": [],
		"whenClosing": false,
		"whenOpening": false
	}
```

**Comment by GermanJohn** [comment]
@redmunds 
Hey, thanks. It tells me it's not valid syntax - I left the `"dontCloseTags":[ ]` and `"indentTags":[ ]` empty - do I have to specify each individual bracket I don't want closed?

**Comment by redmunds** [comment]
You only need to specify individual tags if you want to close some but not others. Try just removing those props:

```json
	"closeTags": {
		"whenClosing": false,
		"whenOpening": false
	}
```

**Comment by GermanJohn** [comment]
@redmunds 
Still tells me it's invalid... 
Is there anything else that might be the issue? 

`{
    "fonts.fontSize": "12px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "soimon.DocumentOutliner.enabled": true,
    "closeBrackets": false,
    "closeTags": "closeTags": {
		"whenClosing": false,
		"whenOpening": false
	}
    
}`

**Comment by redmunds** [comment]
You have `closeTags` twice. Should be:

```
"closeTags": {
  "whenClosing": false,
  "whenOpening": false
}
```

**Comment by GermanJohn** [comment]
@redmunds 
Thanks a lot! I would've never spotted that... finally worked :)

**Comment by redmunds** [comment]
@GermanJohn Glad you got it work. There's a JSONLint extension that will catch errors like that.
