### ISSUE TITLE
failure of visualization of codigo

### ISSUE THREAD

**Issue by xanderjara** [adobe/brackets#13328]
Release 1.9 versión experimental 1.9.0-17312
Ubuntu 16.04
When I add <img src = "/img/foto.png" alt = ""> I do not appear in any firefox, google chrome, browser only when I open the Brackets preview terminal

**Comment by ficristo** [comment]
Could you add some additional info?
It's not clear to me if you have problems with Brackets itself, the LivePreview or yuor site...
