### ISSUE TITLE
creating a small social network with php please help?

### ISSUE THREAD

**Issue by Shawn58** [adobe/brackets#13330]
Ok so i need help with the database

**Comment by Shawn58** [comment]
http://imgur.com/insU9o8
http://imgur.com/Ttlw8Iz
http://imgur.com/arUc9ni
http://imgur.com/XTdjJWH
http://imgur.com/7NIFbeC 




Ok these are screenshots of whats going on

**Comment by ficristo** [comment]
Sorry but this place is to report issues about Brackets itself. Also in future, please, upload the images directly on GitHub.
I briefly looked at the screenshots and in the last one you have some trouble with the strings. You should verify to close them correctly.
