### ISSUE TITLE
CSS Enhancement - Add support for `flow-root` as value for `display` property

### ISSUE THREAD

**Issue by praveenpuglia** [adobe/brackets#13335]
`display: flow-root` is now a thing and I thought it would be nice to have it come up on autocompletion. 

I am coming here from [here](https://github.com/atom/language-css/issues/115).

Raised a PR #13334 . Please let me know if I missed something.
Ref - 
- http://caniuse.com/#feat=flow-root
- https://developer.mozilla.org/en-US/docs/Web/CSS/display

**Comment by petetnt** [comment]
Fixed in #13334! 👍
