### ISSUE TITLE
Files not updating automatically

### ISSUE THREAD

**Issue by aaronmohr** [adobe/brackets#13336]
My files don't seem to be updated automatically in Brackets anymore. Whenever I externally add a new file into my code's root folder (images, JS libraries, etc.) I have to restart Brackets before I can access them within the program. Whereas before they would be immediately accessible within Brackets.

I'm currently running version 1.9.0 on Sierra, this issue only started since I updated to the most recent build.

**Comment by ficristo** [comment]
What is the name of your project? Does it contains chars like `(` or `*` for example?

**Comment by ficristo** [comment]
Closing as a dupe of https://github.com/adobe/brackets/issues/12864
