### ISSUE TITLE
Auto-Indentation Issue : Problem With indentation of Switch Case statement, after new update it's not working fine.

### ISSUE THREAD

**Issue by mejainankit** [adobe/brackets#13338]
### Prerequisites

* [y] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [y] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [y] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description
Auto-Indentation Issue : Problem With indentation of Switch Case statement, after new update it's not working fine.

### Steps to Reproduce
1. Write Switch case statement in JavaScript
2. Now save and indent.
3. See the indentation of code.

Indentation should be proper, but look at the following screenshot, it's not proper.
![a](https://cloud.githubusercontent.com/assets/7077837/25377545/88c906ca-29c5-11e7-9888-237e461a2717.png)

### Versions
Found on Windows 7 Home Basic OS & Brackets Release 1.9 build 1.9.0-17312 (release 189f6d39a)

**Comment by petetnt** [comment]
Can replicate on the plain CodeMirror in http://codemirror.net/mode/javascript/

Testcase from MDN

```
var foo = 0;
switch (foo) {
  case -1:
    console.log('negative 1');
    break;
  case 0: // foo is 0 so criteria met here so this block will run
    console.log(0);
    // NOTE: the forgotten break would have been here
  case 1: // no break statement in 'case 0:' so this case will run as well
    console.log(1);
    break; // it encounters this break so will not continue into 'case 2:'
  case 2:
    console.log(2);
    break;
  default:
    console.log('default');
}
```

**Comment by petetnt** [comment]
Filed upstream at https://github.com/codemirror/CodeMirror/issues/4707

**Comment by petetnt** [comment]
This have been now fixed upstream, thanks for reporting @mejainankit!

**Comment by mejainankit** [comment]
Thanks a lot @petetnt !

**Comment by petetnt** [comment]
I think this has landed in Brackets by now.
