### ISSUE TITLE
Adobe Sign In Error

### ISSUE THREAD

**Issue by riaanoliver** [adobe/brackets#13341]
### Description

When I try to sign into to my adobe account to use Adobe extract I get an error message with the following message.

Error
Please report broken authorization link: invalid value for parameter client_id

### Steps to Reproduce

1. Help > Sign in to Creative Cloud

**Expected behavior:** Able to access files on creative cloud for extract.

**Actual behavior:** error message 
Error
Please report broken authorization link: invalid value for parameter client_id

### Versions
Running MacOS 10.12.4 Sierra
Brackets Version: Release 1.9 build 1.9.0-17312 (release 189f6d39a)

**Comment by riaanoliver** [comment]
<img width="1639" alt="screen shot 2017-04-28 at 12 24 25 pm" src="https://cloud.githubusercontent.com/assets/20329156/25512338/38f690c0-2c10-11e7-80ed-f32048be8e5c.png">

**Comment by petetnt** [comment]
Sorry @riaanoliver,

the Extract for Brackets service has been discontinued for Brackets since 1.6.  For more information, see http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/?lang=en. 

The extract feature is available in Dreamweaver CC, which is now based on Brackets if that helps.

Sorry again.

**Comment by FDiskas** [comment]
:broken_heart: link to blog is broken

**Comment by petetnt** [comment]
HI @FDiskas,

sorry about that. The blog is up again, thanks for reporting.

**Comment by FDiskas** [comment]
That was the core feature why I was trying to use brackets. These days there are plenty of good IDE as alternative

**Comment by petetnt** [comment]
@FDiskas sorry about that, there's not much we can do from our side. There has been some talks about open sourcing the technology, but nothing concrete about that yet and I wouldn't hold my breath. Dreamweaver CC is now based on Brackets and offers this feature.

Hopefully you'll come back and try Brackets some other time, but I do ❤️ other similar IDEs like `vscode` and `atom` too and I hope that you find the one that fits you the best!
