### ISSUE TITLE
Please correct the error when installing in Ubuntu

### ISSUE THREAD

**Issue by AlexParovozoff** [adobe/brackets#13340]
### Description

Please correct the error when installing in Ubuntu 17.4, dependency on libgcrypt11. Ubuntu has the libgcrypt20 package installed.

**Comment by petetnt** [comment]
Hi @AlexParovozoff!

Various workarounds for this issue has been listed in https://github.com/adobe/brackets/wiki/Brackets-Linux-Guide#libcrypt11-missing-dependency-in-ubuntu

Closing as duplicate of https://github.com/adobe/brackets/issues/10255

**Comment by mgraves9803** [comment]
you can also go here: https://fourthfruit.github.io/fixes/
