### ISSUE TITLE
Cannot change font

### ISSUE THREAD

**Issue by hee-develop** [adobe/brackets#13351]
### Prerequisites

* [O] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [O] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [O] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description
I can't change font - when I change fonts and then change font size,
brackets change fonts to "SourceCodePro-Medium".

### Steps to Reproduce

1. Open setting(brackets.json) and change fonts.fontFamily (ex: "fonts.fontFamily": D2Coding)
2. Change font size (Ctrl + or -)
3. Custom fonts are ignored.
(current setting : D2Coding / in editor : Source Code Pro)

### Versions
sprint 9 build 1.9.0-17312
windows 10 build 1703 64bit

**Comment by petetnt** [comment]
Hi @hee-develop,

could you try putting the `D2Coding`  to quotes `"D2Coding"` or try to set the font from `View -> Themes -> Font Family`?

**Comment by hee-develop** [comment]
@petetnt Yes, I already tried both, but still same.

**Comment by imbhavin95** [comment]
i also have same problem with Brackets Release 1.9 build 1.9.0-17312 (release 189f6d39a)

**Comment by saurabh95** [comment]
@hee-develop Actually we have fixed this issue and also did a pre-release.
You can download the stable pre-release from https://github.com/adobe/brackets/releases/tag/release-1.10-prerelease-1

**Comment by Ohstapit** [comment]
Oh god, finally. I can change the font now... I've been suffering for half a year.

**Comment by hee-develop** [comment]
Oh I got it. Thanks!

**Comment by isabelle-me** [comment]
Thanks @saurabh95, works for me! :)
