### ISSUE TITLE
Can not Launch/uninstall/reinistall/delete Brackets! 

### ISSUE THREAD

**Issue by ghost** [adobe/brackets#13355]
Hello.

Was able to Launch brackets 1.9 since I installed Adobe Reader! Now I cant launch or reinstall brackets! tried everythin on th troubleshooting site: Cleared The Cache, Checked the File Permissions, Run Brackets From The Command Line, tried to Reinstall!
Nothing helped! I cant even delete the Brackets Folder! So how to get rid of this buggy virus like Software?
I am using Windows 10x64 and when I reinstall/uninstall Brackets i get error code 2330 during uninstall and it rolls back...

**Comment by petetnt** [comment]
Sorry about this.

Which OS are you using? Are you getting some specific errors?

You should be able to manually remove Brackets by deleting the installation folder (for example `C:\Program Files (x86)\Brackets` and the application data folder (``%APPDATA%/Brackets`)

**Comment by petetnt** [comment]
Closing as inactive.

**Comment by rajeev0903** [comment]
it just makes my system slow, uses 70% of the disk when startup and keep using is . till i kill the process, need to fix such issues. and while uninstalling says, unable to uninstall.

**Comment by sonofkyuss** [comment]
I have the same issue. I'm on Win 8.1
