### ISSUE TITLE
PHP arrays are not indented correctly

### ISSUE THREAD

**Issue by Nihilivin** [adobe/brackets#13350]
### Description / Steps to Reproduce

Simply declare an array in PHP mode. Either using auto indentation plugins  or by pressing enter, the indentation is not correct after the newline

**Expected behavior:** [What you expected to happen]
```
$hello = array(
    'foo' => array(
        'bar' => 'baz'
    )
);
```

**Actual behavior:** [What actually happened]
```
$hello = array(
'foo' => array(
'bar' => 'baz'
)
);
```

### Infos

There is no error, and the problem is still present without any extension
This is probably a CodeMirror problem, just tell me and I'll open a ticket on their GitHub

### Versions

Brackets 1.8.0-17108 on Fedora 24

**Comment by petetnt** [comment]
Hi @Nihilivin,

Couldn't replicate myself on Windows 10, `1.10 development build 1.10.0-0` nor CodeMirrors PHP mode test page (http://codemirror.net/mode/php/).

Could you try updating to Brackets 1.9? 👍

**Comment by Nihilivin** [comment]
I can't, I wasn't able to update since 1.9 requires libs that were not available for my Fedora distribution... Gonna wait then
