### ISSUE TITLE
A failure occurred in build - Antergos (Arch) Linux

### ISSUE THREAD

**Issue by vT0K3N** [adobe/brackets#13359]
Hello,
I'm using Antergos Linux (Arch) on a ThinkPad X1 Carbon 5th Gen (20HR002MGE) and somehow the installation for 1.9 with the GUI Antergegos installer over AUR won't work. I get this error:

`  CCLD     scsi_id
  CC       src/v4l_id/v4l_id.o
  CCLD     v4l_id
  CC       src/accelerometer/accelerometer.o
  CCLD     accelerometer
  CC       src/keymap/keymap-keymap.o
In file included from src/keymap/keymap.c:41:0:
src/keymap/keys-from-name.h:158:1: error: conflicting types for ‘lookup_key’
 lookup_key (register const char *str, register size_t len)
 ^~~~~~~~~~
src/keymap/keymap.c:39:19: note: previous declaration of ‘lookup_key’ was here
 const struct key* lookup_key (const char *str, unsigned int len);
                   ^~~~~~~~~~
make[2]: *** [Makefile:2051: src/keymap/keymap-keymap.o] Error 1
make[1]: *** [Makefile:3190: all-recursive] Error 1
make: *** [Makefile:1333: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

`
please consider in your answers that I'm not that advanced with Linux yet.
Thanks a lot!

**Comment by petetnt** [comment]
Hmm, looking at https://aur.archlinux.org/packages/brackets/?comments=all it should work now. 

A comment to similar issue than yours says that

```
@alfredo.ardito You can use libudev0-shim instead of libudev0
```

So installing that dep first could work. The `archlinux` package is supported by a thirdparty, so you might be able to find more help by asking help from https://aur.archlinux.org/packages/brackets instead.

Hopefully this helps you somewhat

**Comment by vT0K3N** [comment]
That solved my problem :) Awesome! Thank you! I really appreciate your help!

**Comment by petetnt** [comment]
Awesome 👍
