### ISSUE TITLE
(Cannot open storage cglist_safe.csv): cgmode

### ISSUE THREAD

**Issue by JustAnotherGamer11303** [adobe/brackets#13360]
With one of my games and one of my moddling programs, when i go to extra's in my game it says (Cannot open storage cglist_safe.csv): cgmode then it force closses the game and in game it doesnt show any of my addons, and with the moddeling program when i go to load it says (Cannot open storage cglist_safe.csv): cgmode

**Comment by petetnt** [comment]
Hi @JustAnotherGamer11303,

this doesn't seem to be relevant to Brackets ¯\\\_(ツ)_/¯
