### ISSUE TITLE
I Cannot Change Font Family in 1.9

### ISSUE THREAD

**Issue by imbhavin95** [adobe/brackets#13362]
I cannot change fonts in brackets Release 1.9 build 1.9.0-17312 (release 189f6d39a) previous version i can change properly but after install new version i cannot.

actually i change default font to "consolas" it changed but font size is being very small. after i increase font size change font automatically to default font. how can i fix this?

Note : I check "reload without extension" but it helpless

**Comment by saurabh95** [comment]
@imbhavin95 Actually we have fixed this issue and also did a pre-release.
You can download the stable pre-release from https://github.com/adobe/brackets/releases/tag/release-1.10-prerelease-1

**Comment by imbhavin95** [comment]
Yes @saurabh95 i do this and it's now working. Topic Closed.
Thank you.
