### ISSUE TITLE
CSS Styling the Class

### ISSUE THREAD

**Issue by Loganpi** [adobe/brackets#13379]
### Description
In css, Brackets does not recognize my classes. So when want to use css for a class, it totally ignores the class.

**Expected behavior:** [The css to recognize my class. ]

**Actual behavior:** [Brackets did not recognize the class.]

### Versions

On brackets 1.9,

**Comment by petetnt** [comment]
Hi @Loganpi,

could you share some code where this occurs?

**Comment by Loganpi** [comment]
![screen shot 2017-05-12 at 10 41 37 pm](https://cloud.githubusercontent.com/assets/28762498/26245771/b8130290-3c63-11e7-9671-2237d04424cd.png)


Here you go, you can see that the css styling is not recognizing the class

**Comment by swmitra** [comment]
@Loganpi From the screen shot it seems both the language mode CSS and HTML is rendered using consistent code coloring.  What's the theme you are using?  Looks like the theme has been written to color selectors as red. To avoid any confusion, if you are using a custom theme, switch back to Brackets default theme. If that's not the case, please share the whole CSS file.

**Comment by Loganpi** [comment]
What is a theme?

**Comment by Loganpi** [comment]
In the live preview it didn't style as it was supposed to.

**Comment by swmitra** [comment]
Please share the whole CSS file.  Looks like it has a broken syntax...

**Comment by Loganpi** [comment]
OK. I will do it this afternoon.

**Comment by Loganpi** [comment]
https://drive.google.com/drive/folders/0B7mODDgNFqgFajY4YnJDRU9CeGM
Go to this link, I cant upload the files directly to github.

**Comment by Loganpi** [comment]
I am doing a slideshow.

**Comment by ficristo** [comment]
The files linked in the comment above seems to have changed.
I think you had a syntax error in your css.
Closing.
