### ISSUE TITLE
Brackets's screen becomes white

### ISSUE THREAD

**Issue by HuangZhenyang** [adobe/brackets#13374]
### Description

It seems that if I open Brackets a long time and don't use it. Its screen will become white. Only the navigation bar will show, but couldn't make a response to my operations.

### Versions

1. Windows 8.1
2. Bracktes: sprint 6 `发布版`(released version) 1.6.0-16680 (release 3df0ac6fa)

**Comment by petetnt** [comment]
Hi @HuangZhenyang,

could you try updating Brackets to the latest version (1.9)? 

This has something to do with large code bases IIRC, as seen in https://github.com/adobe/brackets/issues/12617, https://github.com/adobe/brackets/issues/12959, https://github.com/adobe/brackets/issues/12192 and others. Ignoring some larger folders (of third party code, built code etc.) might be helpful, see https://github.com/zaggino/brackets-file-tree-exclude for more information.

**Comment by HuangZhenyang** [comment]
OK! I'm so sorry to disturb u that I didn't  try to look for such problem carefully.
Thank you so much!

**Comment by petetnt** [comment]
No problem @HuangZhenyang, do report if the problem persists! 👍
