### ISSUE TITLE
Stylus used in a vue/htmlmixed CM mode resolves to unknown Brackets language

### ISSUE THREAD

**Issue by opl-** [adobe/brackets#13378]
### Description

Defining a Brackets language for Vue components using the vue mode for CodeMirror results in the language being [resolved to an unknown language](https://github.com/adobe/brackets/blob/c62e106d00a2263cbff808629e4f65f615d673ec/src/language/LanguageManager.js#L347) for [the Brackets code hinter](https://github.com/adobe/brackets/blob/63962ceec71d20e25a47bf250be04dccecf041b8/src/editor/CodeHintManager.js#L489) when using Stylus in the style tag. This breaks potential Stylus code hint providers.

From what I understand, the issue seems to be with the Brackets language for Stylus being defined as if Stylus was a variation of the CSS mode (a MIME mode) in CodeMirror, when in reality it is completely separate. This results in the CodeMirror mode that Brackets tries to resolve being `stylus`, while due to [this part of LanguageManager](https://github.com/adobe/brackets/blob/c62e106d00a2263cbff808629e4f65f615d673ec/src/language/LanguageManager.js#L603) the Stylus Brackets language is mapped to the `text/x-styl` CodeMirror mode.

I managed to find two possible solutions:
* Adding a mapping from `text/x-styl` to `stylus` [here](https://github.com/adobe/brackets/blob/c62e106d00a2263cbff808629e4f65f615d673ec/src/language/LanguageManager.js#L1145) in LanguageManager like this:
```javascript
var stylus = getLanguage("stylus");
_setLanguageForMode("stylus", stylus);
```
* Changing the `mode` for Stylus in `language/languages.json` from `["stylus", "text/x-styl"]` to `"stylus"`

CodeMirror defines the Vue component mode [here](https://github.com/codemirror/CodeMirror/blob/master/mode/vue/vue.js) using the htmlmixed mode with a `tags` option.

### Steps to Reproduce

1. Define a language using the vue mode for CodeMirror by running the code below
```javascript
LanguageManager.defineLanguage('vue', {
    name: 'Vue Component',
    mode: 'vue',
    fileExtensions: ['vue'],
    blockComment: ['<!--', '-->']
});
```
2. Create a .vue file with a `<style lang="stylus">` tag
```html
<style lang="stylus">
.example {
    font-size: 20px;
}
</style>
```
3. Type anything in the style tag
4. An error should appear in the console

**Expected behavior:** The code hints _should_ work (though Brackets currently [doesn't show](https://github.com/adobe/brackets/blob/79afc18f951841b7b3f4e5a230f3c7c90b58d76e/src/extensions/default/CSSCodeHints/main.js#L471) [any](https://github.com/adobe/brackets/blob/79afc18f951841b7b3f4e5a230f3c7c90b58d76e/src/extensions/default/CSSPseudoSelectorHints/main.js#L159) [code hints](https://github.com/adobe/brackets/blob/79afc18f951841b7b3f4e5a230f3c7c90b58d76e/src/extensions/default/CSSAtRuleCodeHints/main.js#L115) for Stylus files).

**Actual behavior:** An error is logged.

### Versions

Windows 7 64 bit, Brackets 1.10.0

**Comment by petetnt** [comment]
👍 Nice work @opl-, PRs very welcome

**Comment by petetnt** [comment]
Note to self: The option 1. can also be used to overriding JavaScript mode with `jsx` mode.
