### ISSUE TITLE
Brackets won't load from source code

### ISSUE THREAD

**Issue by lkisac** [adobe/brackets#13388]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
_I am running from source code and I don't get as far as seeing the menu in Brackets._
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
_Related issues I was able to find are running brackets from original install._
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?
_I tried clearing the cache as suggested [here](https://github.com/adobe/brackets/wiki/Troubleshooting#-cant-launch-brackets)_

### Description

Brackets will not start when running from source code, from this [commit](https://github.com/adobe/brackets/commits/efa56bff83e23d133764af4f61a361c9ca6d5322) (no changes to code).

### Steps to Reproduce

1. Installed Brackets from these [steps](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets#setting-up-your-dev-environment)
2. Set up to run own copy of code from these [steps](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets#-running-your-copy-of-the-code)
3. Open Brackets:
![image](https://cloud.githubusercontent.com/assets/5377677/26374691/381e90b2-3fd4-11e7-8df6-22e62654eff2.png)
4. Click on hosted.html
5. Right click on loading screen, select 'Dev Tools', then 'Console' tab:
![image](https://cloud.githubusercontent.com/assets/5377677/26374775/780f095e-3fd4-11e7-821d-c61aa737ca90.png)

### Versions

OS: Windows 10
Brackets: Release 1.9 build 1.9.0-17312 (release 189f6d39a) 
build timestamp: Tue Mar 21 2017 10:29:45 GMT+0000

**Comment by petetnt** [comment]
Hi @lkisac,

any particular reason you are trying to build from that specific commit? /cc @humphd

**Comment by humphd** [comment]
It looks like you've got your local brackets (Desktop) setup to run from your source dir, which is running Mozilla Brackets vs. Adobe Brackets.

**Comment by lkisac** [comment]
Hi @petetnt, no particular reason.  It was the latest commit I last pulled.

@humphd  Following [this](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets#-running-your-copy-of-the-code) guide, I ran `tools\setup_for_hacking.bat "C:\Program Files (x86)\Brackets"` from the repository directory.
![image](https://cloud.githubusercontent.com/assets/5377677/26411708/8c7c4e6a-4074-11e7-9524-c4753f2f09ac.png)

I did a `git remote -v` and see that I am running [mozilla](https://github.com/mozilla/brackets) brackets, not [adobe](https://github.com/adobe/brackets) brackets.  I will clone the adobe brackets repo and let you know if it works.

Thanks for the feedback.

**Comment by lkisac** [comment]
Running Mozilla Brackets vs. Adobe Brackets was the issue.  It is fixed now after running Adobe Brackets.  

Thanks

**Comment by petetnt** [comment]
Excellent! Closing as solved.
