### ISSUE TITLE
Brackets Extension Registry: "NPM_INSTALL_FAILED"

### ISSUE THREAD

**Issue by Hirse** [adobe/brackets#13403]
When trying to upload the [latest version](https://github.com/Hirse/brackets-ungit/releases/tag/v0.4.0) of [Brackets Ungit](https://github.com/Hirse/brackets-ungit) to the Brackets Extension Registry I got the following error:
> The extension package is invalid: An error occurred, but unfortunately I don't know how to say this nicely: NPM_INSTALL_FAILED

When I install the npm dependencies locally, I don't have any issues and the packages used have been used by this extension (or another of my extensions) before.

```json
  "dependencies": {
    "ungit": "^1.1.19"
  },
  "devDependencies": {
    "eslint": "3.x.x",
    "grunt": "1.x.x",
    "grunt-contrib-compress": "1.x.x"
  },
```

See the [archive](https://github.com/Hirse/brackets-ungit/releases/download/v0.4.0/hirse.ungit.zip) and the [`package.json`](https://github.com/Hirse/brackets-ungit/blob/v0.4.0/package.json) for reference.

**Comment by ficristo** [comment]
Same problem I have in https://github.com/adobe/brackets/issues/13312
See also https://github.com/adobe/brackets-registry/pull/78
