### ISSUE TITLE
Dilato: LOC: There are some strings not localized

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#13414]
Steps:
1. launch Beackets
2. Click Extension Manager
3. Click Debug -> Open preferences file

Result: Some strings are not localized
Expect: All strings are localized

Build: 1.10.0-17455
![1](https://cloud.githubusercontent.com/assets/2245179/26725482/541c3d46-47d1-11e7-80e3-bdc9b76de323.png)
![2](https://cloud.githubusercontent.com/assets/2245179/26725484/542843f2-47d1-11e7-9653-f69244ed25d3.png)
![3](https://cloud.githubusercontent.com/assets/2245179/26725483/5422a820-47d1-11e7-922e-a09183bb20d2.png)

**Comment by rj-adobe** [comment]
It seems that these strings are not externalized

**Comment by Zhanxin** [comment]
Most of the string is localized now, only one string "Live Preview Hightlight settings" still not localized, seems a hardcode issue. Please help to check.

**Comment by ZuoBaogang** [comment]
Vierify this issue with build 1.10.0-17313, Fixed
![01](https://user-images.githubusercontent.com/17721679/27853678-43673f6c-6196-11e7-9a2e-c12b89851ec8.png)
![02](https://user-images.githubusercontent.com/17721679/27853679-44350636-6196-11e7-9bf0-7e2c4ade5aa2.png)
![03](https://user-images.githubusercontent.com/17721679/27853680-4546d720-6196-11e7-80d4-e863b91bd770.png)
