### ISSUE TITLE
Brackets indent guide appears with dashed lines instead of straight

### ISSUE THREAD

**Issue by frankny** [adobe/brackets#13420]
Any ideas how to fix this? Image attached displaying behavior. Thanks 

![screen shot 2017-06-05 at 10 22 17 am](https://cloud.githubusercontent.com/assets/27034893/26787680/e25039ce-49d8-11e7-87a2-b4cddb252ec5.png)

**Comment by petetnt** [comment]
Hi @frankny, are you using the `index-guides` extension? https://github.com/lkcampbell/brackets-indent-guides

If you are, could you repost this issue/question to that repo, thanks! 👍

**Comment by frankny** [comment]
Yup, sorry didnt see that repo, thx.
