### ISSUE TITLE
Dilato: Core: Brackets still not support other encodings

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#13422]
Steps:
1. Launch Beackets
2. Try to open other encoding files other than UTF-8, tried with Unicode and UTF-16

Result: I always get an error that Brackets only support UTF-8 files
Expect: The files could be opened and edit
[aaa.txt](https://github.com/adobe/brackets/files/1054719/aaa.txt)
![error](https://cloud.githubusercontent.com/assets/2245179/26826253/f0158600-4aea-11e7-9cde-8b7e1a690c49.png)

**Comment by petetnt** [comment]
Encoding support is WIP in https://github.com/adobe/brackets/pull/13412

**Comment by Zhanxin** [comment]
Tried again with build 1.10.0-17455 21, still could reproduce this issue. When open a unicode file, I would get an error message that the file is not support.
I also tried a file with encoding Chinese GB2312, the file could be opened, but the Chinese characters can't be displayed on the Brackets:
![characternotdisplay](https://user-images.githubusercontent.com/2245179/27076296-658ef582-505f-11e7-95a9-c0320722a58e.png)

Testing file:
Unicode:
[aaa.txt](https://github.com/adobe/brackets/files/1070945/aaa.txt)
GB2312:
[new 1.txt](https://github.com/adobe/brackets/files/1070946/new.1.txt)

**Comment by Zhanxin** [comment]
This issue still available, if open a utf-16 LE or utf-16 BE file, the brackets would display nothing.
Attached files:
utf-be: 

utf-le:

**Comment by saurabh95** [comment]
We are not currently supporting files with BOM characters (UTF-16 LE and UTF-16BE)

**Comment by saurabh95** [comment]
I have fixed the issue with attached new 1.txt.

**Comment by ZuoBaogang** [comment]
Retest this issue, UTF-16 has been removed form the encoding list. The error message is reasonable if open an UTF-16 file.
![errormessage](https://user-images.githubusercontent.com/17721679/27865385-f867c192-61c4-11e7-8f29-624e9b5e89d4.png)
