### ISSUE TITLE
Auto-formatting & Auto-complete

### ISSUE THREAD

**Issue by Crashnorun** [adobe/brackets#13421]
1) Feature request for auto-formatting code by some combination of shortcut keys
2) Feature request for auto-complete. The code highlights when the user types, but when I press TAB to accept the highlighted option, the cursor just moves over rather then injecting the highlighted code

Great work!

**Comment by redmunds** [comment]
> auto-formatting code by some combination of shortcut keys

Formatting should work pretty well (there are some quirks) as you type. Any specific cases that don't work as you expect? Also, try extensions such as Beautify to reformat your code.

> when I press TAB to accept the highlighted option...

You need to turn on the `insertHintOnTab` preference:
https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences

**Comment by Crashnorun** [comment]
The insertHintOnTab works perfect! Thanks for pointing that out. I'm looking into Beautify extension. Thanks for the recommendations. I think I finally found an editor I like for JS and web development!
