### ISSUE TITLE
Quick Open doesn't auto-select the first item any more

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#13437]
### Prerequisites

* [X] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [X] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

In Quick Open, the first item is no longer automatically selected. That is, entering some shorthand and pressing Enter doesn't work any more.

### Steps to Reproduce

1. Use `Navigation > Quick Open` to invoke the Quick Open bar
2. Enter some shorthand for a file
3. Press `Enter`

**Expected behavior:** The first entry should be opened.

**Actual behavior:** Nothing happens

### Further information
The line responsible for this change in behavior is https://github.com/adobe/brackets/commit/ab91035bbdca54e1e1b210d515dde63189c7ecd9#diff-8b20ffb2a91b5df10e73d5d627c8c5b4R266 (commit found via `git bisect`).
cc @saurabh95 @petetnt @ficristo @swmitra 

### Versions

Windows 10
Brackets running off master b9c57953c

**Comment by petetnt** [comment]
I misreported this in https://github.com/adobe/brackets/pull/11948#issuecomment-305710043. Thanks for bisecting it @MarcelGerber, it's been driving me crazy for the past few days.

**Comment by MarcelGerber** [comment]
I'm not sure on what priority we should go for. I'd vote high priority because it's a regression, but I'm not sure how commonly used Quick Open is (I wonder how this could go unnoticed for almost two months. Maybe we are the only ones who use Quick Open?).

**Comment by petetnt** [comment]
I'd like to see it fixed for 1.10 myself

**Comment by saurabh95** [comment]
@petetnt I will try to fix this.
