### ISSUE TITLE
Can't open files from FileZilla in Brackets

### ISSUE THREAD

**Issue by DogMap** [adobe/brackets#13439]
Hi,

I just installed **Brackets** and really love the design and all the features, but I just noticed that I cant' open files (.html, .css, .php, ...) from **FileZilla** with **Brackets**. 
In **FileZilla**, I right-click on the file, chose "edit", **Brackets** opens, but there's no file opened in it...

Can I fix this ?

**Comment by aditya-simplecrm** [comment]
Did you get the solution?

**Comment by TrevHall** [comment]
yeah. what args do I need to put in my file associations to open in brackets?

**Comment by MatiasBrunacci** [comment]
Is this fixed? I'm having the same problem atm
