### ISSUE TITLE
Cannot run brackets due to segmentation fault on Debian 8

### ISSUE THREAD

**Issue by pratts** [adobe/brackets#13464]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [*] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description
Brackets cannot run on Debian 8 after updating the master branch to latest code on brackets repository.

### Steps to Reproduce

1. Pull the latest code on brackets repository
2. Checked out to jasonsanjose/cef_2171_linux branch in brackets-shell repository. Updated the control file to use libcrypt20 in installer/linux/control
3. Run 'grunt build' in brackets repository and 'grunt installer' in brackets-shell repository. Install the brackets .deb file from installer/linux folder.
4. Run brackets using command 'brackets' on command line.

**Expected behavior:** Brackets should successfully open and run.

**Actual behavior:** Brackets screen opens and suddenly closes and "Segmentation fault" prints on the screen.
Output of running brackets from command line : 
prateek@prateek-debian:~/work/open-source/brackets-shell/installer/linux$ brackets 
[0618/235112:ERROR:browser_main_loop.cc(163)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[0618/235112:ERROR:renderer_main.cc(207)] Running without renderer sandbox
[0618/235112:ERROR:nss_util.cc(819)] After loading Root Certs, loaded==false: NSS error code: -8018
Segmentation fault

Output of dmesg afterwards : 
[17577.767302] Brackets[28555]: segfault at 3600001 ip 00007fd8d347c614 sp 00007ffd638ef550 error 4 in libgobject-2.0.so.0.4200.1[7fd8d3449000+51000]
[17622.581046] Brackets[28753]: segfault at 3c00001 ip 00007fb8ee9ce614 sp 00007fffe7f652d0 error 4 in libgobject-2.0.so.0.4200.1[7fb8ee99b000+51000]
[19648.369458] Brackets[3063]: segfault at 2600001 ip 00007fc440674614 sp 00007fff4eb46b60 error 4 in libgobject-2.0.so.0.4200.1[7fc440641000+51000]

### Versions

Please include the OS and what version of the OS you're running. : Debian 8
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS) : 1.10.0-17439 is the version printed while installing brackets

One more thing, do you have any plans to include libgcrypt20 (as mentioned in [10255](https://github.com/adobe/brackets/issues/10255) )? Any other separate stable build for debian 8 ?

Regards,
Prateek Sharma

**Comment by saurabh95** [comment]
@pratts` jasonsanjose/cef_2171_linux` branch is not a stable one, there are some issues with it, I would suggest you to use `linux-1547 branch`(now it supports native menus also), we are currently working on upgrading CEF version in Linux also, and we will remove the dependency of libcrypt11 in that upgrade.
If latest cef vesion has libgcrypt20 dependency then we will include it also.

**Comment by pratts** [comment]
Thank you for your reply @saurabh95 
I tried the following 2 commands and had compilation errors while building brackets-shell.
prateek@prateek-debian:~/work/open-source/brackets-shell$ git checkout -b linux-1547 upstream/linux-1547
prateek@prateek-debian:~/work/open-source/brackets-shell$ grunt installer
Running "git:www" (git) task
Skipping fetch for www repo

Running "git:shell" (git) task
Skipping fetch for shell repo

Running "create-project" task
Building project files

Running "build-www" task
/home/prateek/work/open-source/brackets/dist

Running "build" task

Running "build-linux" task
>> In file included from appshell/command_callbacks.h:4:0,
>>                  from appshell/client_handler.h:14,
>>                  from appshell/appshell_extensions.h:27,
>>                  from appshell/appshell_extensions.cpp:24:
>> appshell/appshell_extensions_platform.h: In function ‘void* getMenuParent(CefRefPtr<CefBrowser>)’:
>> appshell/appshell_extensions_platform.h:76:57: error: ‘GTK_WIDGET’ was not declared in this scope
>>          GTK_WIDGET(browser->GetHost()->GetWindowHandle()),
>>                                                          ^
>> appshell/appshell_extensions_platform.h:77:9: error: ‘GTK_TYPE_VBOX’ was not declared in this scope
>>          GTK_TYPE_VBOX);
>>          ^
>> appshell/appshell_extensions_platform.h:77:22: error: ‘gtk_widget_get_ancestor’ was not declared in this scope
>>          GTK_TYPE_VBOX);
>>                       ^
>> In file included from ./include/cef_app.h:42:0,
>>                  from appshell/client_app.h:13,
>>                  from appshell/appshell_extensions.h:26,
>>                  from appshell/appshell_extensions.cpp:24:
>> appshell/client_handler.h: At global scope:
>> ./include/cef_base.h:178:11: error: ‘Lock’ in namespace ‘base’ does not name a type
>>      base::Lock lock_;
>>            ^
>> appshell/client_handler.h:294:3: note: in expansion of macro ‘IMPLEMENT_LOCKING’
>>    IMPLEMENT_LOCKING(ClientHandler);
>>    ^
>> In file included from appshell/appshell_extensions.h:27:0,
>>                  from appshell/appshell_extensions.cpp:24:
>> appshell/client_handler.h:160:16: error: conflicting return type specified for ‘virtual void ClientHandler::OnRequestGeolocationPermission(CefRefPtr<CefBrowser>, const CefString&, int, CefRefPtr<CefGeolocationCallback>)’
>>    virtual void OnRequestGeolocationPermission(
>>                 ^
>> In file included from ./include/cef_client.h:48:0,
>>                  from appshell/client_handler.h:12,
>>                  from appshell/appshell_extensions.h:27,
>>                  from appshell/appshell_extensions.cpp:24:
>> ./include/cef_geolocation_handler.h:76:16: error:   overriding ‘virtual bool CefGeolocationHandler::OnRequestGeolocationPermission(CefRefPtr<CefBrowser>, const CefString&, int, CefRefPtr<CefGeolocationCallback>)’
>>    virtual bool OnRequestGeolocationPermission(
>>                 ^
>> In file included from ./include/cef_app.h:42:0,
>>                  from appshell/client_app.h:13,
>>                  from appshell/appshell_extensions.h:26,
>>                  from appshell/appshell_extensions.cpp:24:
>> appshell/client_handler.h: In member function ‘void ClientHandler::Lock()’:
>> ./include/cef_base.h:175:19: error: ‘lock_’ was not declared in this scope
>>      void Lock() { lock_.Acquire(); }                                       \
>>                    ^
>> appshell/client_handler.h:294:3: note: in expansion of macro ‘IMPLEMENT_LOCKING’
>>    IMPLEMENT_LOCKING(ClientHandler);
>>    ^
>> appshell/client_handler.h: In member function ‘void ClientHandler::Unlock()’:
>> ./include/cef_base.h:176:21: error: ‘lock_’ was not declared in this scope
>>      void Unlock() { lock_.Release(); }                                     \
>>                      ^
>> appshell/client_handler.h:294:3: note: in expansion of macro ‘IMPLEMENT_LOCKING’
>>    IMPLEMENT_LOCKING(ClientHandler);
>>    ^
>> appshell/appshell_extensions.cpp: In member function ‘virtual bool appshell_extensions::ProcessMessageDelegate::OnProcessMessageReceived(CefRefPtr<ClientHandler>, CefRefPtr<CefBrowser>, CefProcessId, CefRefPtr<CefProcessMessage>)’:
>> appshell/appshell_extensions.cpp:365:53: error: ‘class CefBrowserHost’ has no member named ‘GetDevToolsURL’
>>              ExtensionString url(browser->GetHost()->GetDevToolsURL(true));
>>                                                      ^
>> make: * [out/Release/obj.target/Brackets/appshell/appshell_extensions.o] Error 1
Warning: Task "build-linux" failed. Use --force to continue.

Aborted due to warnings.
prateek@prateek-debian:~/work/open-source/brackets-shell$

**Comment by saurabh95** [comment]
Fixed By: https://github.com/adobe/brackets-shell/pull/619
