### ISSUE TITLE
CodeHintManager: Pressing "Ctrl+Space" causes TypeError each time

### ISSUE THREAD

**Issue by karmatys** [adobe/brackets#13481]
### Description
I was working on hint extension, which uses CodeHintManager API. During tests I noticed, that each time when I'm pressing Ctrl+Space, TypeError appears in brackets console: 

Full message: 
>TypeError: Cannot set property type of #<Event> which has only a getter TypeError: Cannot set property type of #<Event> which has only a getter.

I tested it in different ways (by runs Brackets without extensions for example) and results was always the same. In fact problem concerns CodeHintList's method named **`callMoveUp`** (line 520). This method tries to change read only property of KeyboardEvent instance as message shows. 

Decided to do extra test in two ways:
- First, I tried to comment this fragment of code and see the results. After running unit tests I made manual tests and nothing wrong happened.
- Fixed this code by cloning instance to new fake event object and noticed strange behavior. When I pressed *Ctrl+Space* keys, hint list was shown, but selection jumped to second element and when I pressed it again selection moved to third element. 
Screenshot below:
![codehintmanager](https://user-images.githubusercontent.com/23077032/27498349-ebec8584-585e-11e7-95c7-ad1884bdcb6b.gif)

I think, that this part of code could be removed, but I don't know what was the finally purpose of this functionality.

### Steps to Reproduce

1. Open any JS, CSS, SCSS file and debug console
2. Set cursor near the CSS property (for example)
3. Press **`Ctrl+Space`**

**Expected behavior:** Show code hint list without any errors

**Actual behavior:** Show code hint list with TypeError

### Versions
Brackets 1.9 and 1.10 pre-release 2 (Windows 7)

**Comment by swmitra** [comment]
If I recall correctly a feature was added few months back to navigate in the hint list using ctrl+space. I have also noticed this error but didn't have time to analyze. We have to bisect it now I guess.  Thanks a lot @karmatys for reporting this, we will resolve this soon.
