### ISSUE TITLE
HTML and CSS not linking properly

### ISSUE THREAD

**Issue by thecoog** [adobe/brackets#13499]
Hi, 

I'm using google chrome. I exported files from Codepen. I uploaded them to Github and tried to view them as a page here. I can't seem to get my CSS to link to the HTML. I even tried copying my CSS into the HTML file to see if that helped. The background and animations are missing from CSS when I view the HTML as a page. I've tried changing the code some to see if anything happens, but nothing seems to work. 

Here is my HTML:
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>My Portfolio</title>
  
  
  <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css'>

<link rel="stylesheet" href="css/style.css">

  
</head>

<body>
   <html lang="en">
<head>           
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />           
<meta name="viewport" content="width=device-width, initial-scale=1" />            <style>
 unknown-element-name {                            display: block;
          }
               @media screen and (min-width: 769px)
                     @media screen and (min-width: 992px) 
                     @media screen and (min-width: 1200px) </style>
 </head> 
 
<div class="container-fluid">
<h1><center>
 <a href="#about"><img src="https://s5.postimg.org/ixjvdi00n/About.png" style="float: left; width: 30%; margin-right: 1%; margin-bottom: 0.5em;"><a href="#work"><img src="https://s5.postimg.org/gmilhpeon/Work.png"style="float: left; width: 30%; margin-right: 1%; margin-bottom: 0.5em;"></a><a href="#contact"><img src="https://s5.postimg.org/gnx4ov5w7/Contact.png"style="float: left; width: 30%; margin-right: 1%; margin-bottom: 0.5em;"></a>
  </center></h1>
  
  <br><b><p class="about"id="about"style="clear: both; 40px">Welcome to my portfolio! My name, in case you haven't guessed, is Steven Stiefer. I am originally from Texas, and I currently live in Berlin, Germany. At the present time, I am working as a freelancer until I land my 'dream job' as a full time Web Developer. I have a passion for creative design and coffee. If you would like to get to know me a bit more, please feel free to click any and all links you find. You never know where they may take you.</p></b></br>
  
<p><center><a target="_blank" href="https://www.youtube.com/playlist?list=PLwbjgzgEniqGZjoxWTlt2_sCvNU2-iqfI"><img src="https://s5.postimg.org/rpx7dq653/music_4x.png" style="margin: 40px"></img></a> 
  <a target="_blank" href="https://www.google.com/doodles/30th-anniversary-of-pac-man"><img src="https://s5.postimg.org/vuzdrj63b/boo.png"style="margin: 40px"></img></a>
  <a target="_blank" href="http://www.homewetbar.com/images/prod/w-Giant-Coffee-Cup75917.jpg"><img src="https://s5.postimg.org/mee5ynbmf/coffeee_4x.png"style="margin: 40px"></img></a>
<a target="_blank" href="https://www.youtube.com/playlist?list=PLwbjgzgEniqHgclm1Y2blkpsolbdMxvhV"><img src="https://s5.postimg.org/b0rmng13r/tv.png"style="margin: 40px"></img></a></center></p>
<center><p class="work blink-image"id="work"><img src="https://s5.postimg.org/hpx90pok7/MINI_TEXT.png"></img>
</p></center>
<p class="contact"id="contact"><center><a href="call:+49 152 0247 4092" target="_blank"><img src="https://s5.postimg.org/bbyz5z4wn/Asset_1.png"></img></a>
  <a target='_blank' href="mailto:sstiefer@gmx.de"><img src="https://s5.postimg.org/peu3cfp1z/Asset_1_4x.png"></img></a>
<a target='_blank' href="skype:sstiefer_1?userinfo"><img src="https://s5.postimg.org/s3ow2gujb/Asset_4.png"</img></a>
<a target='_blank' href="https://www.freecodecamp.com/thecoog"><img src="https://s5.postimg.org/w6fx1jonr/hopesooo_4x.png"></img></a>
<a target='_blank' href="https://www.facebook.com/thecoogster"><img src="https://s5.postimg.org/6fzxs0u53/Asset_3.png"></img></a>
<a target='_blank' href="https://www.linkedin.com/in/steven-stiefer/"><img src="https://s5.postimg.org/sqnsrzrfb/Asset_2.png"></img></a></center>
  </p>
@-moz-keyframes blink {
    0% {
        opacity:1;
    }
    50% {
        opacity:0;
    }
    100% {
        opacity:1;
    }
} 
@-webkit-keyframes blink {
    0% {
        opacity:1;
    }
    50% {
        opacity:0;
    }
    100% {
        opacity:1;
    }
}
@-ms-keyframes blink {
    0% {
        opacity:1;
    }
    50% {
        opacity:0;
    }
    100% {
        opacity:1;
    }
} 
@keyframes blink {
    0% {
        opacity:1;
    }
    50% {
        opacity:0;
    }
    100% {
        opacity:1;
    }
  } </style>
</div>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js'></script>
</body>
</html>

Here is my CSS:

body { background-image: url(https://s5.postimg.org/yzj6s9p5j/neon-light-text-effect.png);
  background-repeat: no-repeat;
  background-size: cover; 
  background-position: center;
  
}
h1 { padding-top: 500px;
    padding-right: 0px;
    padding-bottom: 50px;
    padding-left: 100px;}

.about 
{color: rgba(175, 238, 238, .75); padding-top: 10px;
padding-right: 40px;
padding-bottom: 10px;
padding-left: 60px;
 margin: 30px
    border: 4px solid 	#6666ff;
  margin: 40px;
      ;-webkit-box-shadow: 0px 0px 15px 5px rgba(102, 102, 255, .75);
-moz-box-shadow: 0px 0px 15px 5px rgba(102, 102, 255, .75);
box-shadow: 0px 0px 15px 5px rgba(102, 102, 255, .75);-webkit-border-radius: 15px;
-moz-border-radius: 15px;
border-radius: 15px;
}

.work
{color: rgba(221, 44, 228, .75); padding-top: 10px;
padding-right: 40px;
padding-bottom: 10px;
padding-left: 60px;
    border: 4px solid 	#dd2ce4;
  margin: 40px;
      ;-webkit-box-shadow: 0px 0px 15px 5px rgba(221, 44, 228, .75);
-moz-box-shadow: 0px 0px 15px 5px rgba(221, 44, 228, .75);
box-shadow: 0px 0px 15px 5px rgba(221, 44, 228, .75);-webkit-border-radius: 15px;
-moz-border-radius: 15px;
border-radius: 15px;}

.contact
{ padding-top: 10px;
padding-right: 0px;
padding-bottom: 10px;
padding-left: 200px;
    
}
.blink-image {
    -moz-animation: blink normal 2s infinite ease-in-out; 
    -webkit-animation: blink normal 2s infinite ease-in-out; 
    -ms-animation: blink normal 2s infinite ease-in-out; 
  animation: blink normal 2s infinite ease-in-out; }
.container-fluid{}

**Comment by Zimboboys** [comment]
First off, I was just looking through your code in your repository and I noticed a **lot** of style mistakes. I corrected these, so [here is a link](https://github.com/adobe/brackets/files/1118924/thecoog.zip). No offense, but your original code is sloppy and looks like you did a lot of cutting and pasting, which would make it difficult to spot errors.

Secondly, you have to setup [GitHub Pages](https://pages.github.com/) in order to view any of your pages. When running your code locally, I didn't see any errors, so this is most likely your problem. This tutorial is simple to follow, so you shouldn't have any problems viewing your page online.

Finally, and most importantly, this isn't an issue with Brackets. It is an issue with **your** personal code. A better place to search for solutions to code problems is with Google or StackOverflow. Hopefully you can find help in these places in the future :)

Also, it would help make your repository look cleaner and more professional if you removed unnecessary files (readme.txt and license.txt). If you want to add a license, GitHub can do that for you.

**Comment by swmitra** [comment]
Thank you @Zimboboys for looking into this issue 👍  
Closing as not related to Brackets...
