### ISSUE TITLE
Can't build shell - CEF download fails

### ISSUE THREAD

**Issue by der-eismann** [adobe/brackets#13498]
### Description

I wanted to download and build the brackets-shell under Solus Linux according to that [how-to](https://github.com/adobe/brackets-shell/wiki/Building-Brackets-Shell), however the setup fails because the CEF download isn't available.
```
> grunt
Running "cef" task

Running "cef-download" task
Downloading http://s3.amazonaws.com/files.brackets.io/cef/cef_binary_3.2623.1397_linux64_release.zip. This may take a while...

Running "curl-dir:cef-linux64" (curl-dir) task
Warning: Fetching "http://s3.amazonaws.com/files.brackets.io/cef/cef_binary_3.2623.1397_linux64_release.zip" failed with HTTP status code 403 Use --force to continue.

Aborted due to warnings.
```

### Steps to Reproduce

1. Download the source of the latest [brackets-shell release](https://github.com/adobe/brackets-shell/archive/release-1.9.tar.gz)
2. Unpack, run `npm install`
3. Run `grunt`

**Expected behavior:** Continue to build brackets-shell

**Actual behavior:** CEF download fails

**Comment by saurabh95** [comment]
For building brackets-shell in linux you have to use linux-1547 branch.
