### ISSUE TITLE
Portrait display orientation, half of Brackets is missing

### ISSUE THREAD

**Issue by StevenWillett** [adobe/brackets#13490]
![brackets bug - portrait orientation](https://user-images.githubusercontent.com/10869028/27636982-e25979fa-5c05-11e7-9d8a-c65134130a31.PNG)
**### Description**
When using Brackets on a desktop display in portrait orientation, half of the Brackets window is missing.

**### Steps to Reproduce**
1. Open Brackets
2. Set a single display to be in portrait orientation
3. Drag / move brackets to this display to replicate.

****Expected behaviour:**** 
Brackets to take over the full display height.

Actual behaviour:
It would appear a max-height type setting is applied and crops the Brackets application window at just over 50% of the portrait displays height.

**### Versions**
- Windows 10 Pro
- Version 1703
- OS Build 15063.413
- Brackets
-- Release 1.9 build 1.9.0-17312 (release 189f6d39a) 
-- build timestamp: Tue Mar 21 2017 10:29:45 GMT+0000

I hope this helps.

**Comment by saurabh95** [comment]
I tried the latest [pre-releas](https://github.com/adobe/brackets/releases/tag/release-1.10-prerelease-3)e on Win8 and Win10, I am not able to reproduce the error, it is working fine

**Comment by StevenWillett** [comment]
@saurabh95 I removed my version entirely, tried to re-run the install but same outcome.

I then re-downloaded the .exe and installed again, works perfectly. (Corrupted download potentially)
Second attempt to fresh install has resolved the issue.

Thanks for investigating.

![brackets bug resolved](https://user-images.githubusercontent.com/10869028/27677237-d4daa292-5ca8-11e7-8847-f9bd29b5ecff.PNG)
