### ISSUE TITLE
are there any good color picker extension for brackets?

### ISSUE THREAD

**Issue by salehmosleh** [adobe/brackets#13500]
can somebody create a color picker like [this](https://github.com/thomaslindstrom/color-picker) for brackets ? in Extension manager , there are not any good color picker up to now! please someone do it.
i found [this color picker ](https://github.com/mikailcolak/brackets-color-picker) but it has some bugs and does not work/show some times.

**Comment by mittalyashu** [comment]
Try [this extension](https://github.com/sprintr/brackets-color-palette), this package helps in picking colors from any image.

**Comment by salehmosleh** [comment]
thank you so much , but im looking for a color picker from many colors , not from images.

**Comment by Cyan101** [comment]
Google "Color Picker", built in colour selector by google.

I'm sure someone with proper knowledge can build this into a package/extension pretty easily

**Comment by ficristo** [comment]
Is the integrated color picker not good enough? 
Use Ctrl + E on an existing color to show it.

**Comment by salehmosleh** [comment]
Ctrl + E is a good Idea , i didnt know it , thank you.

**Comment by omsm** [comment]
thanks @ficristo  Ctrl + E just helped saved me from checking every color, one by one

**Comment by Sourish2321** [comment]
How is Ctrl + E works for color picker
