### ISSUE TITLE
Dilato: Core: Suggest to add an error message when save the file before change encoding

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#13516]
Build: Release 1.10 build 1.10.0-17313
Steps:
1. Launch Brackets
2. Make some change of an opened file (Such as index.html)
3. Changeing encoding

Result: Save as dialog appears

Expect: Suggest to add an error message when save the file before chang encoding

![issue](https://user-images.githubusercontent.com/17721679/27828399-96177b4e-60ee-11e7-842c-9fbc0d8898ed.gif)

**Comment by saurabh95** [comment]
We have changed the workflow now. So closing it
