### ISSUE TITLE
read method on filesystem/File throws UnsupportedEncoding error when reading a .jpg file (and many other file types)

### ISSUE THREAD

**Issue by RationalCoding** [adobe/brackets#13518]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description
When using the extension API to read a file that is not a text file (specifically a jpg), the `read` method will fail with the error `UnsupportedEncoding`.

It seems to be impossible to read some encodings with the filesystem/File API.

Stack trace:
```
UnsupportedEncoding
(anonymous function) @ mycode.js:41
(anonymous function) @ /filesystem/File.js:108
(anonymous function) @ /filesystem/impls/appshell/AppshellFileSystem.js:368
```

**Expected behavior:** [What you expected to happen]
File should be read.

**Actual behavior:** [What actually happened]
Error is thrown.

### Versions

Mac OSX 10.11.6
Brackets 1.9.0

**Comment by RationalCoding** [comment]
I'm noticing there is an option to set encoding for the read method, but there is no documentation of how to correctly determine the file encoding type.

**Comment by saurabh95** [comment]
Could you try opening the same file in the  latest pre-release build?
Also it would be great if you could share the image also, so that I can test the workflow.

**Comment by saurabh95** [comment]
@RationalCoding in 1.10 pre-release we have added auto detection of encoding of file if it is not UTF-8 readable, then it will open file with the detected encoding and then from the bottom right dropdown you can change the encoding, and it will try to reload the file with the newly selected encoding.

**Comment by saurabh95** [comment]
And as an extension author, if you know the encoding before hand, then you can set `file._encoding` to that encoding and then try to call read function, it will consider this encoding only while reading the file.

**Comment by RationalCoding** [comment]
Hi @saurabh95. Thanks for the reply.

I'm getting several unrelated errors in my extension with the pre-release, but I'll try to test on a simpler case.

The `file._encoding` trick seems to work, is there a way to also write to a file with a specific encoding?

**Comment by saurabh95** [comment]
If you set the file encoding, using `file._encoding`, then the same encoding will be used in the write file.

**Comment by RationalCoding** [comment]
Are the supported encodings the same as Node.js?

**Comment by RationalCoding** [comment]
It actually looks like the problem goes deeper than simply setting the encoding. The appshel filesystem will throw a `ERR_UNSUPPORTED_ENCODING` regardless of the encoding set. It seems to be determining the encoding type from the file or something?

Is `appshell.fs` the Node `fs` module or something else?

**Comment by RationalCoding** [comment]
I tried bypassing the method with `getDocumentText`, but seeing as it calls on the same filesystem read method, and images can never be "opened" in the editor, it fails as well.

**Comment by RationalCoding** [comment]
Does Brackets still not support binary files? This might be the issue.

**Comment by RationalCoding** [comment]
I think lack of binary support was the problem. I ended up using a Node script with 'binary' encoding and it works great. Thanks for your assistance in debugging this!
