### ISSUE TITLE
Brackets 1.10 won't start on Windows 10 (vcruntime140.dll missing)

### ISSUE THREAD

**Issue by sjaakbanaan** [adobe/brackets#13534]
I tried reinstalling VC++ redist., almost all available versions. After one hour of trying I decided to go back to 1.09. Any idea what could cause this?

**Comment by drinkard** [comment]
I had the same issue with Windows 7. Installing [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) fixed the issue.

**Comment by LodanZark** [comment]
Try this tool: Visual C++ Runtime Installer (All-In-One)
http://www.majorgeeks.com/files/details/visual_c_runtime_installer.html

It installs all visual c++ runtimes and uninstall all outdated ones easily

**Comment by DatiQ** [comment]
reinstalling VC++ not help =(

**Comment by rafiquej** [comment]
I just bought a new laptop. I am trying to install brackets but it's not working. I am facing same issue. Any appropriate solution? because none of the above solutions worked!

**Comment by rafiquej** [comment]
Okay found the fix! Download x86 version even if your system is 64bit. Then re-install the brackets. It will open now :)

**Comment by rocket-martue** [comment]
@rafiquej 
Where is x86 version ?

**Comment by drinkard** [comment]
Here: https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by baoang** [comment]
rafiquej's solution worked on my Win10x64. The installation of prev version of Brackets worked fine on my x64 platform. Its current version may need a slight adjustment to avoid this issue.

**Comment by rafiquej** [comment]
@rocket-martue  you can download x86 version here Download x86 version of [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145)

@baoang Glad to hear that it worked :)

**Comment by Zulfikr** [comment]
After installing Visual C++ 2015 Redistributable (x86) on my Window 7 Pro another message pop-up!!!!
![capture](https://user-images.githubusercontent.com/30003317/27986194-7a443f8c-6419-11e7-90a4-14f407f45e55.PNG)

Better to stick on previous version 1.9 which works well on my system.

**Comment by Zulfikr** [comment]
Just reinstalled the previous version, works fine.

**Comment by swmitra** [comment]
We are happy to inform, the missing dll issue at launch has been fixed and windows build has been refreshed. If you are having the same issue, please download the new windows installer from [brackets.io](http://brackets.io/). 

Thanks everyone for pointing this out and helping us fixing the issue in the early days of Brackets 1.10 release 👍
