### ISSUE TITLE
Not possible to save files

### ISSUE THREAD

**Issue by TheArbalist** [adobe/brackets#13536]
Running Brackets 1.10 (1.10.0-17483), the save function does not work.
There is no error message or indication that it did not work, other than the fact that the small bullet symbol indicating unsaved changes remains visible. Neither the hotkey, nor any menu option to save either a single or all files is functional. Save As still prompts for a save file location, but no file is created.

Issue persists after reloading without extensions, the only difference is that I've just updated to the latest build.

Currently using Windows 8.1.

**Comment by NilsFrkal** [comment]
Same problem with Windows 10.

**Comment by saurabh95** [comment]
@TheArbalist @NilsFrkal, Could you try removing older version of brackets using add or remove programs and then reinstalling the latest version?
Also are you using the hacked brackets(I mean if you are running directly from master), then you have to update to the latest master.

**Comment by Mantene** [comment]
I can confirm that uninstalling Brackets completely before installing the new release seems to fix this issue.

**Comment by TheArbalist** [comment]
Uninstalling and reinstalling ended up working.
Thanks for the help, guys. :)

**Comment by NilsFrkal** [comment]
Yes, full uninstall did it for me as well. Thanks.

**Comment by anephew** [comment]
Same here 8(

**Comment by saurabh95** [comment]
@anephew is it fixed now?

**Comment by anephew** [comment]
@saurabh95 yes, uninstalling Brackets and then installing the new )) 
tnx

**Comment by jonaspm** [comment]
I ran into the same problem, uninstall & re-install is a kind of a hacky solution. But thanks :)

**Comment by thany** [comment]
Sorry but, is a release tested even once? This is too obvious. Bugs so bleedingly obvious mustn't happen.

**Comment by thany** [comment]
Closed means fixed? Won't happen next time?
