### ISSUE TITLE
Launching Issue brackets 1.10 VCRUNTIME140.dll is missing

### ISSUE THREAD

**Issue by MandarSant** [adobe/brackets#13541]
### Description

[Editor is not opening]

### Steps to Reproduce

1. [Open Editor by double clicking or any another way]

**Expected behavior:** [Should open editor]

**Actual behavior:** [Not opening editor gives error]

![capture](https://user-images.githubusercontent.com/20091634/27991005-8dcb1612-6486-11e7-8cbe-edcc74e8dcb0.PNG)

### Versions
OS:-Win 8.1 WMC
Brackets:-1.10

**Comment by saurabh95** [comment]
You have to download [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) as mentioned in this comment https://github.com/adobe/brackets/issues/13534#issuecomment-313835199

**Comment by MandarSant** [comment]
@saurabh95  still not resolved

**Comment by saurabh95** [comment]
@MandarSant Did you download the x86 version or x64?

**Comment by MandarSant** [comment]
x64

**Comment by saurabh95** [comment]
You have to download x86 since Brackets is 32 bit.

**Comment by MandarSant** [comment]
should i uninstall x64?

**Comment by saurabh95** [comment]
I think you can have both, there shouldn't be any issue

**Comment by abose** [comment]
![image](https://user-images.githubusercontent.com/5336369/27991660-f79fecec-649b-11e7-8fe8-e21ddebac02f.png)
 I too am getting the same issue. It is no present in previous releases. 
The installer needs to be fixed adding the required DLLs.

**Comment by abose** [comment]
VC++ redistributable will not be present in most consumer machines. Marking this as high priority.
Tests with brackets 1.9 installer, it does not have this requirement.

**Comment by saurabh95** [comment]
This issue is seen because of migration to Visual Studio 2015 which requires this dll. AFAIK this issue is not there in Windows 10 update, it is seen only in prior versions.

**Comment by abose** [comment]
Yes, but in the case where the DLL is not present, which seems to be the case in Windows 8+ machines, the required dependencies need to be shipped as part of the installer. 

The release engineering team would be able to help with this. It is not a good install experience if the user has to go ahead and fix the dependencies(remembering linux deps resolutions 📦 ).
Mostly the required DLLs just needs to be shipped with the installer. That should fix this issue.

**Comment by saurabh95** [comment]
yeah we will do that and change the release builds

**Comment by MandarSant** [comment]
@saurabh95  thanks it worked

**Comment by abose** [comment]
Reopening as the installer issue is not resolved yet.

**Comment by MandarSant** [comment]
@abose I didnt git what u say

**Comment by abose** [comment]
Closing in favor of https://github.com/adobe/brackets/issues/13534 .
@MandarSant we do not expect users to install other software to be able to run brackets. Ideally, brackets installer should install all its requirements by itself. That fix is being tracked in the linked issue.
Closing this as a duplicate.
