### ISSUE TITLE
EncodeFileFailed when creating a new file

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#13551]
I just ran into this issue:

![image](https://user-images.githubusercontent.com/7641760/28094539-f5690a74-66a5-11e7-9bd0-007bbd77d22c.png)

My steps were:

1. Created an app with `create-react-app`.
2. Deleted `index.css`
3. Tried to create it again.

Expected:

File gets created

Actual: Ran into that error.

The file is created, but shows this when trying to open it:

![image](https://user-images.githubusercontent.com/7641760/28094561-24edb8d0-66a6-11e7-9584-6059be73f0fd.png)

**Comment by petetnt** [comment]
Restarting Brackets seemingly fixes the issue, but there were no other errors in the console.

**Comment by saurabh95** [comment]
Did you use utf-8 or some other encoding?

**Comment by petetnt** [comment]
ISO-8859-1 mosly likely as CRA templates default to that but might have been UTF8 too

**Comment by petetnt** [comment]
Most likely already fixed
