### ISSUE TITLE
Unable to update or install extensions (code: "EACCES" errno: -13)

### ISSUE THREAD

**Issue by gps03** [adobe/brackets#13555]
### Description
Every attempt (from the web or directly from drag & drop of zip file) to update or install extension results in an object error for the extension and the extension fails update/install. I suspect that I have a local permissions issue but cannot figure out what needs to be changed to get this to work.

I have already set the directories under ~/Library/Application Support/Brackets/extensions/ to rwx for all users, yet I still get the error. Error below, using beautify as an example.

<pre>
Object {item: "brackets-beautify", error: Object}
     error:Object
     code:"EACCES"
     errno:-13
     path:"~/Library/Application Support/Brackets/extensions/user/brackets-beautify"
     syscall:"rmdir"
</pre>

### Steps to Reproduce

1. Open Extension manager
2. Click update next to extension I want to update
3. Get the modal that extension was downloaded
4. Close Extension manager
5. Click Update and reload
6. Get error that brackets was "Unable to update one or more extensions: extenison list. brackets will still reload."
7. Click OK.

**Expected behavior:** 
Extensions would be updated.

**Actual behavior:**
Extensions are not updated.

### Versions
OS: macOS Sierra 10.12.5
Node.js v: 6.9.2
npm v: 5.2.0
Brackets: Release 1.10 build 1.10.0-17483 (release 024bee940) 
build timestamp: Tue Jul 04 2017 23:07:56 GMT-0700
Note this behavior has been observed in the last several versions of Brackets.

**Comment by MathiasMaurilio** [comment]
Hi @gps03, it's been a while since you opened this issue.
Could you tell me if in the new version this is still going on?

**Comment by gps03** [comment]
This can be closed. Updates seem to be working normally under recent updates of brackets. Thanks.
