### ISSUE TITLE
Doesn't save files after the last update

### ISSUE THREAD

**Issue by Beta6484** [adobe/brackets#13564]
I just installed the latest update of Brackets and now it does not save any changes to the files! Neither the shortcut (ctrl + s) nor the command in the menu. Can you help me?

I already disabled the plugins and I already looked for the problem, I can't solve this!

**Comment by saurabh95** [comment]
Are you on windows, if yes, then there might be a problem with the update not getting properly installed. Could you please uninstall previous version using "Add or Remove Programs" and then resinstall the latest version?

**Comment by Beta6484** [comment]
Thank you! Now it's working properly!
