### ISSUE TITLE
install brackets.release.1.10

### ISSUE THREAD

**Issue by DetSchu** [adobe/brackets#13578]
The Windows Installer shows: "This Istallation-Pack can't be opened. Let the producer of this application test, if it is a valid Windows Installer-Packet." (in german).
Running: Windows 10 Pro Version 1703, Brackets 1.9

**Comment by petetnt** [comment]
Hey @DetSchu,

can you try uninstalling the existing version first and then trying again? If that doesn't work, could you try downloading the binary again?

**Comment by DetSchu** [comment]
Hey - tryed both, but didn't work - same notification. 
What i see: there is a difference between the mouseover (Windows Installer Paket) from 1.9 to 1.10..
In 1.10 missing declaration: author, titel, concerning, "installer for brackets".

**Comment by petetnt** [comment]
Does this issue still persist with https://github.com/adobe/brackets/releases/tag/release-1.11-prerelease-1

**Comment by DetSchu** [comment]
Hello,

 

today I installed 1.10 without any problems – now it’s o.k.

 

greetings

 

Detlef Schüler

 

*********************

Plater Weg 30

29439 Lüchow

detlef.schueler@online.de

 

Von: Pete Nykänen [mailto:notifications@github.com] 
Gesendet: Montag, 11. September 2017 07:42
An: adobe/brackets <brackets@noreply.github.com>
Cc: DetSchu <detlef.schueler@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [adobe/brackets] install brackets.release.1.10 (#13578)

 

Does this issue still persist with https://github.com/adobe/brackets/releases/tag/release-1.11-prerelease-1

**Comment by petetnt** [comment]
Great! Thanks @DetSchu!
