### ISSUE TITLE
Can't uninstall Brackets on Mac

### ISSUE THREAD

**Issue by jstrobel** [adobe/brackets#13572]
I want to uninstall Brackets on my Mac. But i cannot find any data i have to cleanup. AppCleaner cannot find it too.
Can you help me?

**Comment by petetnt** [comment]
Hi @jstrobel,

sorry for the late reply. Uninstalling Brackets should be possible by just trashing the application, but if you want to double check all the data from Brackets is saved to `~/Library/Application Support/Brackets/` on MacOS.

**Comment by jstrobel** [comment]
Hi. There isn't a application which i can trash and there isn't a Library-Folder, but on some file extensions the bracket-app opens.

**Comment by sQuarecoW** [comment]
Even if your app is in the trash it will open a file that is associated with Brackets.

**Comment by jstrobel** [comment]
No i cannot find it in the trash - it is empty.

As you can see on the screen it will be provided as Standard.
![brackets](https://user-images.githubusercontent.com/1428396/29309300-645a75e4-81a9-11e7-9f1c-983f1fe9d752.jpg)

**Comment by sQuarecoW** [comment]
You can use `locate Brackets.app` to find Brackets?

**Comment by jstrobel** [comment]
Sorry no, doesn't show anything.

**Comment by jstrobel** [comment]
Any other ideas?

**Comment by jstrobel** [comment]
Locks like i found the solution, deleted all folders and now it is gone.

./Library/Application Support/Autodesk/webdeploy/shared/Brackets
./Library/Application Support/Autodesk/webdeploy/shared/Brackets/1.2.0c/MAC64/Brackets.framework/Brackets.app/Contents/MacOS/Brackets
./Library/Application Support/Brackets
