### ISSUE TITLE
Live Preview - Opens in a new Chrome App and not in current Chrome App (macOS)

### ISSUE THREAD

**Issue by FlyteWizard** [adobe/brackets#13580]
### Prerequisites

* [X] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?
    * I'm pretty sure...
* [X] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

On Mac Sierra 10.12.6 Brackets opens a new Chrome App when `Live Preview` is activate. 
I'd prefer if it opened in my current Chrome App as a new tab.

### Steps to Reproduce

1. Write some code.
2. Click the `lighting bolt`
3. Chrome is opened in a new App and not the existing App

**Expected behavior:** I expect it to open in the current Chrome App as a new tab. 

**Actual behavior:** Opens a new Chrome App

### Versions

**OS** 

macOS Sierra 10.12.6

**Brackets Version**

Version 1.10 édition 1.10.0-17483 (release 024bee940) 
Horodatage de la version : Tue Jul 04 2017 23:07:56 GMT-0700

**Comment by saurabh95** [comment]
If you want to open in the current chrome app, you have to enable Experimental Live Preview.
Go to `File->Enable Experimental Live Preview`, and then if you click on Live Preview Button it will open the instance in the default browser, (if it is chrome in your case, then it will create a new tab in that instance)

**Comment by FlyteWizard** [comment]
I guess that `solves` the problem. 

What is `Experimental Live Preview` ?

**Comment by saurabh95** [comment]
Experimental Live Preview works for both Firefox and Chrome whereas Live Preview works only in Chrome.
To open in Firefox you can directly copy the link of your Experimental Live Preview instance to your Firefox.

We will soon be adding support for other Browsers also in Experimental Live Preview.

**Comment by FlyteWizard** [comment]
Okay, I'll mark this as closed as there is a `solution` but not the preferred `solution`.

**Comment by supremleo** [comment]
Hi @saurabh95  this solution helped me, thanks!!
