### ISSUE TITLE
Buttons aren't being styled. (Steps and screenshots!)

### ISSUE THREAD

**Issue by BANKROLLBASH** [adobe/brackets#13588]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description
Buttons aren't being styled. On live preview, they appear on the bottom right rather than styling.

### Steps to Reproduce

1. Setup the header in HTML. Div, h1, two classes.
2. In CSS, setup two buttons. btn-full and btn-ghost. style with padding, font-weight, change display to inline-block
3. See the results in Live Preview.

**Expected behavior:** 
I expected the words "I'm hungry" and "Show me more" to appear as buttons.

**Actual behavior:** 
The words aren't styled. The buttons appear on the bottom right of h1 on live preview.

### Versions

Please include the OS and what version of the OS you're running. Windows 7
Please include the version of Brackets. Current version of Brackets

Extensions? Confirm that you've tested with Debug > Reload Without Extensions first (see below). Yes, tested without Extensions.
Any errors logged in Debug > Show Developer Tools - Console view
![devtools](https://user-images.githubusercontent.com/30575588/28755853-1c1f0d14-7518-11e7-880b-a01c2c0e2bfd.JPG)

![btnissue](https://user-images.githubusercontent.com/30575588/28755858-265c6952-7518-11e7-820d-95375fdec514.JPG)

![btnissue2](https://user-images.githubusercontent.com/30575588/28755863-2c666302-7518-11e7-9dd8-7b808107bf70.JPG)

![html](https://user-images.githubusercontent.com/30575588/28755864-3226cd4a-7518-11e7-8e6d-2d918c3e57b6.JPG)

![css](https://user-images.githubusercontent.com/30575588/28755874-6b535912-7518-11e7-8bb1-85a62fa8805c.JPG)

**Comment by petetnt** [comment]
Hi BANKROLLBASH, for the buttons to look like buttons use a `<button>`. You can style your links to look like buttons yourself (for example `border: 2px solid #555`). Frameworks like `Bootstrap` often have a `.btn` helper class that will style even anchor links `<a>` to look like buttons, but you need to add those frameworks (or parts of those frameworks)  first.

**Comment by ficristo** [comment]
Closing as without answer.
