### ISSUE TITLE
Live Preview - Chrome Developer Tools and Brackets cannot work together (macOS)

### ISSUE THREAD

**Issue by FlyteWizard** [adobe/brackets#13582]
### Prerequisites

* [X] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
    * Yup, didn't find anything to this problem.
* [X] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

Have the ability to have Chrome Developer Tools and Brackets `Live Preview` open at the same time. Currently `Live Preview` stops and doesn't restart when the Chrome Developer Tools are closed. You need to close the `Live Preview` and re-open it for the `Live Preview` to work again. 

Opening Chrome Developer Tools

<img width="1680" alt="openinspecttool" src="https://user-images.githubusercontent.com/10472448/28637884-ed9dc638-71f7-11e7-832a-4c93c243691a.png">

Live Preview Stopped

<img width="1680" alt="livepreviewstopped" src="https://user-images.githubusercontent.com/10472448/28637878-e134786a-71f7-11e7-855d-e50b74d7202c.png">

### Steps to Reproduce

1. Write some code.
2. Open `Live Preview`
3. Open Inspect Tool in Chrome

**Expected behavior:** To have both `Live Preview` and Chrome Developer Tools open and have both functional. 

**Actual behavior:** `Live Preview` stops when Chrome Developer Tools are open. 

### Versions

**OS**

macOS Sierra 10.12.6

**Brackets Version**

Version 1.10 édition 1.10.0-17483 (release 024bee9)
Horodatage de la version : Tue Jul 04 2017 23:07:56 GMT-0700

**Comment by Ashtheyogi** [comment]
Has anyone been able to answer your question? Or have you figured it out? I'm having the same problem

**Comment by FlyteWizard** [comment]
@Ashtheyogi Considering the amount of Issues on this repo, I do not expect this to be resolved anytime soon. 

I've since stopped using brackets as it wasn't functional for me anymore.

**Comment by FlyteWizard** [comment]
Stale Issue - Closing
