### ISSUE TITLE
Brackets or Brackets Beautify added a space before every closing quote in my file.

### ISSUE THREAD

**Issue by seejayjames** [adobe/brackets#13587]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by seejayjames** [comment]
Not sure whether it was Brackets or Brackets Beautify. Probably was Beautify because it happened after saving (which beautified it). Really liked this extension and Brackets until now...just spent over an hour eliminating all those spaces, because most of them cause errors (class names etc.)

If there's not a decent explanation and a fix for this, I will never use this program again.

**Comment by petetnt** [comment]
Hi @seejayjames,

there's [an issue on the `brackets-beautify` repo](https://github.com/brackets-beautify/brackets-beautify/issues/236) that has a similar issue with certain quotes, which seemed to be caused by invalid HTML.

You could try pinpointing the issue by removing lines until `brackets-beautify` works correct to find the issue or report it to `brackets-beautify` for more debugging. Brackets itself doesn't do any code modifying on save by default.

**Comment by seejayjames** [comment]
Ah ok, it did in fact do it after I entered a line incorrectly. Good to know about the known issue on the repo, I had a feeling it was Beautify and not Brackets itself. Thanks for the info!
