### ISSUE TITLE
Javascript is not styled correctly in some edge cases (fixed in CodeMirror 5.27.0)

### ISSUE THREAD

**Issue by tech4him1** [adobe/brackets#13590]
### Description

In the edge case described in https://github.com/codemirror/CodeMirror/issues/4785, JavaScript will no longer have syntax highlighting for the rest of the file. This bug was fixed in CodeMirror 5.27.0 and later.

### Steps to Reproduce

Copy an example from https://github.com/codemirror/CodeMirror/issues/4785 into file in the latest version of Brackets.

**Expected behavior:** The syntax highlighting should work for the whole file.

**Actual behavior:** The syntax highlighting breaks for the rest of the file below that particular code example.

### Versions

Brackets Release 1.10 build 1.10.0-17483

**Comment by petetnt** [comment]
Hi @tech4him1!

CodeMirror update should land on the next Brackets release, at which point this will be fixed in Brackets too.

Keeping this issue open until that, thanks for reminding (I made the CodeMirror issue 😹)!

**Comment by tech4him1** [comment]
Yeah, I was wondering about that! Sounds good.

**Comment by swmitra** [comment]
Fixed by #13596.

**Comment by swmitra** [comment]
Marking this issue as closed.
