### ISSUE TITLE
Brackets new instance don't show Linux native menu bar.

### ISSUE THREAD

**Issue by pelatx** [adobe/brackets#13615]
### Description

When you open a new Brackets window using the Development menu, it does not show the Linux native menu bar.

### Steps to Reproduce

1. Open Brackets.
2. Go to Development -> Brackets new window.

**Expected behavior:** The secondary instances of Brackets show the Linux native menu bar. 

**Actual behavior:** The secondary instances of Brackets don't show the Linux native menu bar.

![brackets-issue](https://user-images.githubusercontent.com/6791792/29348095-6b13eff2-8251-11e7-96e9-1f3b313b26e4.png)

### Versions

Debian GNU/Linux 9
Brackets 1.10

**Comment by saurabh95** [comment]
Hey @pelatx this issue is fixed in https://github.com/adobe/brackets-shell/pull/619

**Comment by pelatx** [comment]
Thanks @saurabh95. Waiting for merge and release.

**Comment by saurabh95** [comment]
We will do a pre-release once the PR is merged. Will update this thread once we merge.

**Comment by pelatx** [comment]
Perfect. Thank you again.
