### ISSUE TITLE
Brackets 1.10 update does not work on Windows 10 Home

### ISSUE THREAD

**Issue by teethnclaws** [adobe/brackets#13627]
### Description

I recently tried to update to the newest version of brackets.io 1.10. When I did I was no longer able to open regular HTML & CSS files other than the bracket's getting started html/css. While these files would appear in the working tree, the editor itself would not open these files (though they had been working in the earlier version of brackets). 

### Steps to Reproduce

1. [First Step] - update to 1.10 version of brackets
2. [Second Step] - map to any folders containing index.html/css, etc...
3. [and so on...] - try to open them in brackets on Windows 10 home version

**Expected behavior:** [What you expected to happen]
I would expect that my index.html, css, live preview, etc.. would open and work as normal, but it doesn't.
These were files that had worked before but now, on the new version of brackets, did not. 

**Actual behavior:** [What actually happened]
While the files appear in the tree alongside the text box area, the files themselves will not open. It is as though Brackets does not recognize these files. 

### Versions

Tried to run this on Windows 10 Home after I updated from the brackets 1.08 ver to the most recent 1.10 version. Previous version worked while the 1.10 version of brackets does not recognize or open any files including basic html & css unless it is the getting started html & css that accompanies brackets. 

I did manage to revert back to the 1.08 version, as I reinstalled the older version, and the text editor functioned properly, recognizing and opening my html, css, js, etc.. files.

UPDATE: I should have clarified, I uninstalled and reinstalled the newest version several times as well as restarting my computer after each new install and tested various types of language files. The only ones that would open were the html & css that was included with the brackets.io. No other files were recognized nor would they open in the editor once it was updated. When I reinstalled the older version of 1.08, everything worked properly.

**Comment by petetnt** [comment]
Try deleting Brackets completely and reinstall Brackets via the latest installer again. There were some backwards incompatible changes to file handling which require the new version of Brackets Shell. Sorry for you troubles!

**Comment by teethnclaws** [comment]
I should have mentioned this in the initial statement - I uninstalled and reinstalled this newer version 3 times along with restarting the computer each time. Ultimately, I had to go back to the older version in order to get any of the editor's features to work/to get my html files to open.
