### ISSUE TITLE
Quick-menu shows maximum 50 suggestions

### ISSUE THREAD

**Issue by NRG52** [adobe/brackets#13637]
Hi,
When programming in HTML the auto-suggest menu for adding attributes to an HTML-element shows only a maximum of 50 possible attribute-names in alphabetically order.

For example: if you enter 
`<input `
the auto-suggest menu ends at `oncanplay`, even there are many more possibilities like `onfocus`, `onsubmit`, `placeholder`, `required`, etc. which aren't possible to select.

![brackets](https://user-images.githubusercontent.com/31311070/29665126-f124b310-88d2-11e7-900d-1bb2c4e82298.jpg)

Clean installation of Brackets 1.10 on Windows 10 64bit didn't help. Even with all extensions disabled. Problem also shows up in Brackets Portable 1.10.

**Comment by FilipePintoReis** [comment]
I've noticed that this error does not only happen in html, is commun to all code hints.
I also traced it back to CodeHintList, on directory src/editor/CodeHintList, line 68
"this.maxResults = ValidationUtils.isIntegerInRange(maxResults, 1, 1000) ? maxResults : 50;"

This sent me to the function isIntegerInRange() on ValidationUtils 
"  function isIntegerInRange(value, lowerLimit, upperLimit) {
        // Validate value is an integer
        if (!isInteger(value)) {
            return false;
        }

        // Validate integer is in range
        var hasLowerLimt = (typeof (lowerLimit) === "number"),
            hasUpperLimt = (typeof (upperLimit) === "number");

            return ((!hasLowerLimt || value >= lowerLimit) && (!hasUpperLimt || value <= upperLimit));
    }
" 
This must be returning false and therefore 50 is the value that goes into maxResults

**Comment by navch** [comment]
Is this hint list getting updated or not on typing ? I mean if you type "o" there, then hints are getting updated right ?

**Comment by kiroma** [comment]
I think it would be a better idea to enable configuration of the limit by drawing maxResults from brackets.json. The limit is there for a reqson after all.

**Comment by navch** [comment]
Yes Performance is one reason behind this.
This is already there you can change maxhints from preference. (i.e. "maxCodeHints": 100)

We are taking this value from preference only check CodeHintManager.js 
"maxCodeHints = PreferencesManager.get("maxCodeHints");"

**Comment by navch** [comment]
I hope this solves your problem. Closing this issue. Feel free to open again if this doesn't help you.
