### ISSUE TITLE
Revert node tern module: https://github.com/adobe/brackets/pull/11948

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#13634]
I'm using the latest master at work and with that PR it makes Brackets unusable for me.

I'm using on macOS, I'll try to fill with some more details soonish.

**Comment by swmitra** [comment]
@ficristo I will wait for the issue details from you. But wanted some initial info. Do you see any malformed message which is passed to tern and in turn making it crash? Or anything relevant to tern in console?

**Comment by ficristo** [comment]
Yes, there was an error about malformed message. Then some other about accessing `.map` on undefined, which lead then to file watcher offline and Brackets become unusable.
Also, I tryed to run the `Extensions \ JavaScript Code Hinting` test, on Windows, and there are some failures

**Comment by swmitra** [comment]
@ficristo I will try to resolve this asap. If for some reason it is not being fixed immediately ( need to borrow at least a day though ) , I will revert the tern PR and fix it separately.

**Comment by ficristo** [comment]
I just want to be sure next prerelease comes with js code hints fixed or that PR reverted.
Locally I reverted it.

**Comment by ficristo** [comment]
After just some minutes of usage (switch projects, open & close some files) I have something like this:

```js
ErrorNotification.js:122 [NodeConnection] received error: Unable to parse message: {"id":47,"domain":"TernNodeDomain","command":"invokeTernCommand","parameters":[{"type":"AddFiles","files":["...<file-name>.js"]}]

ErrorNotification.js:122 [NodeConnection] received error: Unable to parse message: {"id":1195,"domain":"TernNodeDomain","command":"invokeTernCommand","parameters":[{"type":"GetFile","file":"...<file-name>.js","text":""}]

ErrorNotification.js:122 [node-error 10:37:28 AM] [Launcher] uncaught exception at top level, exiting. RangeError: out of range index
    at RangeError (native)
    at fastCopy (/Applications/Brackets.app/Contents/node-core/thirdparty/ws/lib/Receiver.js:323:24)
    at Receiver.add (/Applications/Brackets.app/Contents/node-core/thirdparty/ws/lib/Receiver.js:84:3)
    at Socket.firstHandler (/Applications/Brackets.app/Contents/node-core/thirdparty/ws/lib/WebSocket.js:524:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)

NodeDebugUtils.js:111 [node-info 10:37:28 AM] [Server] stopping

FileSystem.js:965 File watchers went offline!

6NodeConnection.js:84 WebSocket connection to 'ws://localhost:50892/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

FileSystem.js:973 Watching disabled for <project-name>
```

**Comment by swmitra** [comment]
@ficristo I am not seeing any errors, I am on node version 6.11.0 ( using latest shell). Can you please change Barckets node version to 6.11.0 or switch to shell master and let me know if you are still getting any issues regarding JS code hints?

**Comment by ficristo** [comment]
I have updated to latest prerelease (1.11-prerelease.1) and `git clean -xdf` the repo.
It seems more stable, but I didn't use Brackets much.
I still hit the error about `.map on undefined`.

**Comment by ficristo** [comment]
At this point I think it was my tree to be in a bad state.
