### ISSUE TITLE
SASS Support

### ISSUE THREAD

**Issue by AndiLeni** [adobe/brackets#13646]
Hello,

I wanted to ask whether brackets will ever get full sass support or not.
I don't want to sound rude, but it's the middle of the year 2017 and there is still no sass support by default. Relying on plugins is not very easy and useful in most cases. Also the "a plugin for everything" policy got a little annoying over the years.

Brackets has always been an IDE for front end developers, but instead of focusing to implement the new features the development seems to be pretty slow.

I would be glad to know what's going to happen in the future with sass support. If I need to change my editor or not.

Regards 
AndiLeni

**Comment by swmitra** [comment]
@AndiLeni Be assured that, Brackets is a growing community and we are focused on providing the best and latest support to web developers. "saas" support in question here is in our backlog and we are working on it to provide essential tooling in Brackets. Do let us know what kind of saas tooling would make Brackets more useful for front-end developers 👍
