### ISSUE TITLE
Dilato: LOC: FR/JP: There is no space between the string Errors and the colon

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#13658]
Steps:
1. Launch Brackets
2. New a file by click File - New
3. Click "Debug" - Shows Errors in Status Bar"
4. Click "Debug" - "Enable Node Debugger"
5. Click "Debug" - "Restart Node"
6. Relaunch Brackets
7. New a file

Result: There is no space between the string Errors and the colon

Expect: There should has a space between the string Errors and the colon

![enu](https://user-images.githubusercontent.com/17721679/30028195-b0a495e8-91b6-11e7-949d-b1a1cf875214.png)
![fra](https://user-images.githubusercontent.com/17721679/30028197-b18d3c1c-91b6-11e7-8774-999cfc2b9409.png)
![jpn](https://user-images.githubusercontent.com/17721679/30028198-b3df3b50-91b6-11e7-8a25-30436f5f66fc.png)

**Comment by ZuoBaogang** [comment]
This issue also reproduce on previous version of Brackets

**Comment by rj-adobe** [comment]
Fixed this via PR - https://github.com/adobe/brackets/pull/13660/files

**Comment by ficristo** [comment]
Why do you want a space before the colon? IMO it is correct what we have now, at least for english

**Comment by ZuoBaogang** [comment]
In French this is the language habit. There should be a non-break space between the string and the colon.
In Japanese, according to the adobe style guide, it should use the single byte colon and add a space between the string and colon on application.
For core side, the whole string "Errors:" should be externalized, then linguistic team would translate it correctly.

**Comment by ficristo** [comment]
> In French...
> In Japanese...

Ah, makes sense. Thank you.

**Comment by ZuoBaogang** [comment]
Verify this issue on build 1.11.0-17517-918 for all platform. Fixed.
Please see the screenshots
![13658_fr_fixed](https://user-images.githubusercontent.com/17721679/30484983-9d31d7cc-9a5e-11e7-8a5e-873e002f944e.png)
![13658_jp_fixed](https://user-images.githubusercontent.com/17721679/30484985-9df01cfa-9a5e-11e7-9f5a-218c0ece81e5.png)
