### ISSUE TITLE
is it useful for c++ programming ?

### ISSUE THREAD

**Issue by MotiBaadror** [adobe/brackets#13653]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by petetnt** [comment]
Hi @MotiBaadror,

while Brackets is not a fully fledged C++ IDE, Brackets has C++ syntax highlighting built in and there are some extensions like https://github.com/peterflynn/brackets-nativecode that offer some extra C++ programming features. So Brackets can be used for some lightweight C++ programming easily but for more robust projects there are other IDEs that are better equipped for this task 👍
