### ISSUE TITLE
Dilato: LOC: JP: The space is missing between the strings and the colon on Themes Settings

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#13672]
1. Launch Bracket
2. Click "View"
3. Click "Themes..."

Result: The space is missing between the strings and the colon
Expect: There should have a space between he strings and the colon for JP locale
ENU
![enu](https://user-images.githubusercontent.com/17721679/30160723-51a6ebf8-9400-11e7-8b58-eb9d74a6bbd2.png)
JPN
![jpn](https://user-images.githubusercontent.com/17721679/30160730-57940618-9400-11e7-944b-ebb400afa464.png)

**Comment by rj-adobe** [comment]
Fixed via PR https://github.com/adobe/brackets/pull/13660

**Comment by ZuoBaogang** [comment]
Verify this issue on build  1.11.0-17517-918 for all platform. Fixed. 
Please see the screenshot
![13672_jp_fixed](https://user-images.githubusercontent.com/17721679/30484846-42eb6454-9a5e-11e7-8524-123e4043402d.png)
