### ISSUE TITLE
Linux download not working missing a library

### ISSUE THREAD

**Issue by wisdomlight** [adobe/brackets#13688]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by wisdomlight** [comment]
On linux mint 18.2 
I downloaded the file from brackets

when package installer does its check for dependencies - there is a problem with a libgcrypt 11 (>=1.4.5)
the repository of linux mint says the lib has been replaced by 2.0 
I installed the upgraded lib but brackets still does not install.

the people from linux mint say that ppssible problem is that the libgcrypt11  has been hard coded and this prevents the next libegcrypt that is supposed to replace the libgcrypt 11 take effect.

any how brackets does not work on my linux mint 18.2

**Comment by petetnt** [comment]
Hi @wisdomlight, could you try the 1.11. pre-release which should (finally) fix this issue: https://github.com/adobe/brackets/releases/tag/release-1.11-prerelease-1

**Comment by facchettos** [comment]
Hey, I got this problem on ubuntu 17.04. The last version seems to work, thanks for the fix =)

**Comment by wisdomlight** [comment]
It works!!

**Comment by petetnt** [comment]
Awesome! Thanks for confirming @facchettos & @wisdomlight!

**Comment by mmahmoudian** [comment]
On Ubuntu 16.04 I had the issue with the downloaded [.deb file from the website](https://github.com/adobe/brackets/releases/download/release-1.10/Brackets.Release.1.10.64-bit.deb)  and libgcrypt11 and I made sure libgcrypt20 is installed and updated (since libgcrypt11 is deprecated).

The [pre-release 1.11](https://github.com/adobe/brackets/releases/tag/release-1.11-prerelease-1) works fine with the libgcrypt20.

Thanks all for the thread.
