### ISSUE TITLE
[Fixed]getupdates.brackets.io can't be reached

### ISSUE THREAD

**Issue by glenndevenish** [adobe/brackets#13690]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

**I am unable to reach getupdates.brackets.io on my computer.**

This is both through brackets, and through my browser:

![capture](https://user-images.githubusercontent.com/31036664/30264567-fbd3b8a4-96d0-11e7-9329-6c34b9444b4a.PNG)

![capture1](https://user-images.githubusercontent.com/31036664/30264584-0be62f74-96d1-11e7-9d56-df9df6e0d1f9.png)

This means I can't get updates for brackets or extensions (extensions are less of an issue, but it's still annoying having to manually download them).

I'm behind a corporate SSL certificate if that's a problem, which I have. I'm not sure if this is a proxy, so I don't know if it can be solved by following [this guide](https://github.com/adobe/brackets/wiki/Troubleshooting#working-behind-proxy).

### Steps to Reproduce

1. Get a computer like mine
2. Run brackets

(sorry, not very helpful, I'm not sure what's happening and it's always been like this...)

**Expected behavior:** I can access getupdates.brackets.io

**Actual behavior:** I can't access getupdates.brackets.io

### Versions

Windows 10 Pro version 1701

Brackets Release 1.10 build 1.10.0-17483 (release 024bee940) 
build timestamp: Wed Jul 05 2017 07:39:31 GMT+0100

**Comment by glenndevenish** [comment]
health.brackets.io doesn't work either, but brackets.io does...

As a side note, this isn't normal behaviour for our company whitelist. Normally it shows a 'blocked' sign, rather than the request timing out.

**Comment by swmitra** [comment]
Fixed now! Thanks @glenndevenish for reporting this 👍

**Comment by glenndevenish** [comment]
@swmitra great! what happened?

**Comment by swmitra** [comment]
The node process which actually serves the health data update requests (Health Server) was stopped. Had to restart the process.
