### ISSUE TITLE
NEED TO REMOVE BRACKETS

### ISSUE THREAD

**Issue by KalyD** [adobe/brackets#13702]
ok so i don't have time for all of this crap - I accidentally tapped the root folder on my Mac and now I can't bloody well use brackets, uninstall it, and the configuration files are all suddenly impossible to find...

I WILL use it, but I need to know EXACTLY where Brackets installs all it's files on OS X Sierra, so I can uninstall it, strip it completely from my Mac, restart, and reinstall.

Root is CLEARLY not where anyone is going to code on any operating system, so why would it even be selectable...

**Comment by petetnt** [comment]
Hi @KalyD,

Brackets installs all it's data to `~/Library/Application Support/Brackets` on MacOS

**Comment by KalyD** [comment]
Got it figured out, thanks!
