### ISSUE TITLE
Dilato: I18N: The string "Other Binary" is not localized

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#13703]
Test build: 1.11.0-17517-918
Steps:
1. Launch Brackets
2. Create a  Excel file and drag it to the main panel

Result: The string "Other Binary" is not localized
Expect: The string "Other Binary" is localized

ENU
![enu](https://user-images.githubusercontent.com/17721679/30485328-9fce92bc-9a5f-11e7-9970-a8916d9dcbbf.png)

FRA
![fra](https://user-images.githubusercontent.com/17721679/30485331-a2db4c66-9a5f-11e7-855a-e74d27a87352.png)

JPN
![jpn](https://user-images.githubusercontent.com/17721679/30485336-a83c3b52-9a5f-11e7-9c8b-8d589fbc0a6c.png)

**Comment by Zhanxin** [comment]
Also could reproduce on previous version.

**Comment by Zhanxin** [comment]
Close this as duplicate with https://github.com/adobe/brackets/issues/10964
