### ISSUE TITLE
Unable to Install - old Dependency required

### ISSUE THREAD

**Issue by HuwJanus** [adobe/brackets#13727]
### Description

Unable to install on Mint 18 Sarah 64-bit

Dependency not satisfied: libgcrypt11 (version too low)

However libgcrypt11 is out of date and replaced with libgcrypt20

**Comment by jibraniqbal666** [comment]
This package(libgcrypt11) is not available for xenial base.
please download required package and install it. 

 `wget https://launchpad.net/~ubuntu-security-proposed/+archive/ubuntu/ppa/+build/7110687/+files/libgcrypt11_1.5.4-2ubuntu1.1_amd64.deb`
`sudo dpkg -i libgcrypt11_1.5.4-2ubuntu1.1_amd64.deb`
 
then you can install brackets.
`sudo dpkg -i ./Brackets.Release.1.10.64-bit.deb`

**Comment by petetnt** [comment]
Hi @HuwJanus,

the latest prerelease should work without `libcrypt11` 

https://github.com/adobe/brackets/releases

**Comment by petetnt** [comment]
Should be fixed by 1.11.
