### ISSUE TITLE
displaying javascript errors without any reason in v1.11

### ISSUE THREAD

**Issue by salehmosleh** [adobe/brackets#13734]
i update my brackets to version 1.11 , but it displays javascript errors without any reason like below screenshot. also "assigning a variable without using" is not a error is a WARNING! some of variables i defined in another js files , but brackets says 'it is not defined' !
![error](https://user-images.githubusercontent.com/3959998/30873318-af4e912c-a2f9-11e7-994f-4be29bae6e40.jpg)

**Comment by petetnt** [comment]
Hi @salehmosleh,

consider adding a `.eslintrc` file to your project for adjusting how `ESLint` behaves. You can find the configuration options here: https://eslint.org/docs/user-guide/configuring. 

For example for variables in different files, add them as globals either with

```
{
    "globals": {
        "var1": true,
        "var2": true
    }
}
```

or inline (top of the file) with
```
/* global var1, var2 */
```

**Comment by salehmosleh** [comment]
Hi @petetnt , thank you for your comment.
I think , brackets has to make and add .eslintrc file to my project by default configuration options at the first time. Not me! You know , it's not fair , 'mixed spaces and tabs' is not an error even its not a warning. But brackets says 'ERROR'. And many things like this ...

**Comment by petetnt** [comment]
I understand your frustration. As there's as many possible combinations of options as there are projects, it's not quite possible to create a one-size-fit-all configuration. However, there are many popular ones like https://www.npmjs.com/package/eslint-config-airbnb and https://www.npmjs.com/package/eslint-config-standard that aim to unify rules used into a common best practice set. Project that haven't been coded against a linter before might be cumbersome to adapt into, but it also might be worth it. Remember that you can also start from just a few rules and turn on more if you want to in the future. Also did you know that you can fix many simple issues with Right Click -> `Auto-fix with ESLint`? That would solve small issues like mixed tabs/spaces.

That said, you can also turn linting off altogether by setting `linting.enabled` to `false` in preferences (or Edit -> Lint files on save)

**Comment by whryan** [comment]
Is there any way to get something closer to sublime text's default javascript linting? The linting by default is enough to make me not use Brackets, despite it being preferable for development in so many other ways. Maybe I'm just way too unfamiliar with js standards, but having it flag every single time I use console.log, and having to be sure to copy every single global variable and function into a linter file is annoying and makes the linting effectively useless because it crys wolf so much.

**Comment by petetnt** [comment]
@whryan 

Hi,

no idea how Sublime Text lints files by default, but `.eslintrc.js` file is the de-facto way of configuring ESLint.

For example for disabling `no-console`, you can use

``` js
module.exports = {
    rules: {
        "no-console": 0,
         ... other rules ...
    }
}
```

Alternatively you can extend the `recommended` config and disable the rules you don't need (https://eslint.org/docs/rules/).

If you find linting distracting you can also disable it altogether from preferences.

See https://eslint.org/docs/user-guide/configuring for complete documentation.

**Comment by whryan** [comment]
Ah thank you! I should have looked for a manual more, really appreciate
that you linked this

**Comment by petetnt** [comment]
Closing as answered, thanks!
