### ISSUE TITLE
Extension Manager Not Loading

### ISSUE THREAD

**Issue by Elucin** [adobe/brackets#13730]
Extension manager is not loading. I bring up the extension manager and the little animated loading icon just keeps looping. In Developer tools, I get this message: 
`GET http://online-dnbard.rhcloud.com/tick/53e1fa4f5c9674bcbe00004c net::ERR_NAME_NOT_RESOLVED`
followed by 
`Can't track online status, retry in 5 mins`
both of which repeat every 5 minutes.

Running Ubuntu 16.04 Xenial
and Brackets Release 1.11 build 1.11.0-17524 (release 86b5e2d4e) 
(although this was still a problem before updating to the latest version)

**Comment by mikeeverts** [comment]
I had the same issue.  I changed the language under debug from system default to English(US) and the extension manager started to work again.

**Comment by alisabrikim** [comment]
I was just wondering, how di?

> I had the same issue. I changed the language under debug from system default to English(US) and the extension manager started to work again.

I just wondered,How did you think this solution

**Comment by shabalalaz** [comment]
I cannot believe it was that easy, Thanks.

**Comment by navch** [comment]
Looks like the issue is resolved, Closing this.

**Comment by 555STi** [comment]
> I had the same issue. I changed the language under debug from system default to English(US) and the extension manager started to work again.

Same issue here.
Ubuntu 18.04
Brackets Release 1.13 versión 1.13.0-17696 (release 49d29a8bc)

Did the language change to Español and worked flawlessly. I was trying to work with a network folder on a remote server and it didn't worked, until this.

Thanks!

**Comment by burningraven06** [comment]
> I had the same issue. I changed the language under debug from system default to English(US) and the extension manager started to work again.

Thanks a lot man. This solved the issue.

**Comment by leimao** [comment]
> I had the same issue. I changed the language under debug from system default to English(US) and the extension manager started to work again.

I have to say, this is brilliant...

**Comment by JobinM** [comment]
> I had the same issue. I changed the language under debug from system default to English(US) and the extension manager started to work again.

Had the same issue did what you said and instant fix. Thnx a lot man

**Comment by mdPial** [comment]
> I had the same issue. I changed the language under debug from system default to English(US) and the extension manager started to work again.

It also worked for me. Many many thanks for sharing.

**Comment by baditaflorin** [comment]
This should be fixed or at least give a warning to the user,

**Comment by shubhsnov** [comment]
It seems like this issue is related to https://github.com/adobe/brackets/issues/14581#issuecomment-491566321, which can be fixed by installing the language pack in Ubuntu.

See my comment here: https://github.com/adobe/brackets/issues/14581#issuecomment-491569033

**Comment by tonyllo** [comment]
Thanks for the answer, it was fine for me too.

**Comment by fschein** [comment]
2019 ending and still a issue. Solved changing language to English US

**Comment by ashutosh-akss** [comment]
It's now 2020 I managed to fix it by changing language, hope someone commits a fix soon!

**Comment by paras009** [comment]
> I had the same issue. I changed the language under debug from system default to English(US) and the extension manager started to work again.

Thanks, that works perfectly fine!

**Comment by paras009** [comment]
> It's now 2020 I managed to fix it by changing language, hope someone commits a fix soon!

Yeah. exactly that should not be the case.

**Comment by Landsil** [comment]
Still an issue.
btw. don't panic if fix doesn't work for you, it still has to load for 5-10s.

**Comment by maxton-projects** [comment]
> It's now 2020 I managed to fix it by changing language, hope someone commits a fix soon!

Did you try installing an extension? Because i can't

**Comment by JerryJames** [comment]
Thanks, It's fixed My the same Issue...
