### ISSUE TITLE
[Resolved][Arch Linux]Menu font from Brackets 1.11

### ISSUE THREAD

**Issue by arthurflor** [adobe/brackets#13731]
### Prerequisites

* [ x ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ x ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ x ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

I upgraded to version 1.11 and I had some problems. First I had to execute this command for the brackets to open (only this to open):
````
sudo chmod 4755 /opt/brackets/chrome-sandbox
````

Second, when the brackets finally open:
![image](https://user-images.githubusercontent.com/11759042/30837172-79372114-a239-11e7-8e37-1993481c27a2.png)

and

![image](https://user-images.githubusercontent.com/11759042/30837290-4811b1de-a23a-11e7-9ec6-e6b4f8ad746f.png)

### Steps to Reproduce

1. Open the Brackets

**Expected behavior:** Menu font correct

**Actual behavior:** Menu font is square (missing?)

### Versions

````
Release 1.11 build 1.11.0-17524 (release 86b5e2d4e) 
build timestamp: Wed Sep 20 2017 10:21:22 GMT+0000
````

````
OS: Arch Linux 
Kernel: x86_64 Linux 4.12.13-1-ARCH
DE: KDE 5.38.0 / Plasma 5.10.5
WM: KWin
GTK Theme: Breeze [GTK2/3]
Icon Theme: Papirus
Font: Noto Sans Regular
````

**Comment by nackd** [comment]
Same thing here. Also Arch Linux with a similar config, though I have the GTK font set to Oxygen-Sans.

**Comment by swmitra** [comment]
@arthurflor Thanks for choosing Brackets and letting us know about this rendering issue 👍. As  Arch Linux is not a platform where Brackets normally gets tested, can you please let us know the process involved in installing Brackets on Arch Linux? 
Unless we actually debug this issue, can't comment on what's going wrong with the configuration.

**Comment by arthurflor** [comment]
It's just the install command:
````
yaourt -S brackets-bin
````
More info from the package: https://aur.archlinux.org/packages/brackets-bin/

Can do installing error? I will check the package build

**Comment by arthurflor** [comment]
Process: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=brackets-bin

**Comment by sachinkamath** [comment]
+1 can confirm this affects Arch Linux install. I tried installing most of the fonts referenced in `src/styles/` and rebuilding the font cache but the issue persists.

**Comment by arthurflor** [comment]
The package brackets (without "-bin") doesn't install here. Results in compilation error.
But I'll go into more detail with this compilation error. Thanks!

**Comment by anthonytex** [comment]
Yes, a dep "libudev0-shim" must be installed you can install my compiled version https://drive.google.com/open?id=0BzKigOTG5qLEMFIyWGU3R2g1N28 
`sudo pacman -U brackets-1.11-1-x86_64.pkg.tar.xz`

**Comment by swmitra** [comment]
@anthonytex Great work! You made my day. I love this community for the passion it brings in making a developers day. Sincerely hoping the trend continues 👍

**Comment by plascadeine** [comment]
Have the same problem in ubuntu, I have no idea what to do.

**Comment by swmitra** [comment]
@plascadeine Brackets is rigorously tested on Ubuntu and we have never noticed this kind of problem with the package posted officially. Are you using one of the deb package posted in GitHub releases for Brackets?

**Comment by plascadeine** [comment]
Yes I download witl link posted on brackets info on app, install deb package and see this [](https://i.imgur.com/KK3kB3w.png) but previous version works fine, without any problems

**Comment by arthurflor** [comment]
@anthonytex Yea! thanks!
The problem was the "libudev0". The Brackets package caught libudev0 from AUR as dependence (here had compilation error). So I installed "libudev0-shim" before and works like a charm.

and
![image](https://user-images.githubusercontent.com/11759042/30877100-0646f13e-a2cf-11e7-97ba-147b11471eab.png)

=)

**Comment by swmitra** [comment]
@arthurflor Thanks a lot for quick confirmation 👍 . If the reported problem is fixed to your satisfaction, please consider closing this issue.

**Comment by hnaparst** [comment]
Installing libudev on Gentoo does not fix the problem.

**Comment by kuboosoft** [comment]
The error persists!

```
[makerpm@localhost brackets]$ ./Brackets
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0318
Received signal 11 SEGV_ACCERR 0000008d813e
#0 0x7ff5dabba7db base::debug::(anonymous namespace)::StackDumpSignalHandler()
#1 0x7ff5d7d993b0 <unknown>
#2 0x7ff5ddbd2db3 sandbox::CrashSIGSYS_Handler()
#3 0x7ff5ddbd19fb sandbox::Trap::SigSys()
#4 0x7ff5d7d993b0 <unknown>
#5 0x7ff5d79f21db getrandom
#6 0x7ff5d6e79b05 <unknown>
#7 0x7ff5d6e7b743 XML_ParseBuffer
#8 0x7ff5c210e6fd <unknown>
#9 0x7ff5c215069c <unknown>
#10 0x7ff5c210bbc7 <unknown>
#11 0x7ff5c3d8c52e <unknown>
#12 0x7ff5c3d5bcc9 <unknown>
#13 0x7ff5c3d8d2f8 <unknown>
#14 0x7ff5db44f6b1 gfx::GLContextGLX::Initialize()
#15 0x7ff5db43de67 gfx::GLContext::CreateGLContext()
#16 0x7ff5db84f95a gpu::GpuCommandBufferStub::OnInitialize()
#17 0x7ff5db84f33a _ZN3IPC8MessageTI35GpuCommandBufferMsg_Initialize_MetaSt5tupleIJN4base14FileDescriptorEEES2_IJbN3gpu12CapabilitiesEEEE18DispatchDelayReplyINS6_20GpuCommandBufferStubEvMSB_FvS4_PNS_7MessageEEEEbPKSC_PT_PT0_T1_
#18 0x7ff5db84eb63 gpu::GpuCommandBufferStub::OnMessageReceived()
#19 0x7ff5db840a48 IPC::MessageRouter::RouteMessage()
#20 0x7ff5db84c163 gpu::GpuChannel::HandleMessageHelper()
#21 0x7ff5db84c0e2 gpu::GpuChannel::HandleMessage()
#22 0x7ff5db84cbb3 _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0ELm1EEEENS0_9BindStateINS0_15RunnableAdapterIMN3gpu10GpuChannelEFvRK13scoped_refptrINS6_22GpuChannelMessageQueueEEEEEFvPS7_SC_EJNS_7WeakPtrIS7_EESC_EEENS0_12InvokeHelperILb1EvSF_EEFvvEE3RunEPNS0_13BindStateBaseE
#23 0x7ff5dabbb9ec base::debug::TaskAnnotator::RunTask()
#24 0x7ff5dabd5355 base::MessageLoop::RunTask()
#25 0x7ff5dabd5678 base::MessageLoop::DeferOrRunPendingTask()
#26 0x7ff5dabd583b base::MessageLoop::DoWork()
#27 0x7ff5dabb0cfa base::(anonymous namespace)::WorkSourceDispatch()
#28 0x7ff5d88a6247 g_main_context_dispatch
#29 0x7ff5d88a65e8 <unknown>
#30 0x7ff5d88a667c g_main_context_iteration
#31 0x7ff5dabb0bd6 base::MessagePumpGlib::Run()
#32 0x7ff5dabec030 base::RunLoop::Run()
#33 0x7ff5dabd4b7a base::MessageLoop::Run()
#34 0x7ff5dd469b9d content::GpuMain()
#35 0x7ff5ddc9b257 content::ContentMainRunnerImpl::Run()
#36 0x7ff5ddc99d00 content::ContentMain()
#37 0x7ff5daac0b03 CefExecuteProcess()
#38 0x7ff5daa64ba7 cef_execute_process
#39 0x0000004925c2 CefExecuteProcess()
#40 0x0000004212dd client::(anonymous namespace)::RunMain()
#41 0x000000421c07 main
#42 0x7ff5d79d650a __libc_start_main
#43 0x00000040c849 <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000246
 r12: 0000000000000000 r13: 00007ff5de6b77d9 r14: 00000000000d813e r15: 00007fff90e849e0
  di: 0000000000000002  si: 00007ff5de6b77d8  bp: 000000000000013e  bx: 0000000000000000
  dx: 0000000000000001  ax: 00000000000d8000  cx: 00000000008d813e  sp: 00007fff90e849d0
  ip: 00007ff5ddbd2db3 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 00000000008d813e
[end of stack trace]
[0927/200314:ERROR:command_buffer_proxy_impl.cc(194)] Could not send GpuCommandBufferMsg_Initialize.
[0927/200314:ERROR:webgraphicscontext3d_command_buffer_impl.cc(199)] CommandBufferProxy::Initialize failed.
[0927/200314:ERROR:webgraphicscontext3d_command_buffer_impl.cc(218)] Failed to initialize command buffer.
[0927/200314:ERROR:gpu_channel_host.cc(228)] Failed to send GpuChannelMsg_CreateCommandBuffer.
[0927/200314:ERROR:webgraphicscontext3d_command_buffer_impl.cc(218)] Failed to initialize command buffer.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0318
Received signal 11 SEGV_ACCERR 00000080813e
#0 0x7f61adbab7db base::debug::(anonymous namespace)::StackDumpSignalHandler()
#1 0x7f61aad8a3b0 <unknown>
#2 0x7f61b0bc3db3 sandbox::CrashSIGSYS_Handler()
#3 0x7f61b0bc29fb sandbox::Trap::SigSys()
#4 0x7f61aad8a3b0 <unknown>
#5 0x7f61aa9e31db getrandom
#6 0x7f61a9e6ab05 <unknown>
#7 0x7f61a9e6c743 XML_ParseBuffer
#8 0x7f61950ff6fd <unknown>
#9 0x7f619514169c <unknown>
#10 0x7f61950fcbc7 <unknown>
#11 0x7f6196d7d52e <unknown>
#12 0x7f6196d4ccc9 <unknown>
#13 0x7f6196d7e2f8 <unknown>
#14 0x7f61ae4406b1 gfx::GLContextGLX::Initialize()
#15 0x7f61ae42ee67 gfx::GLContext::CreateGLContext()
#16 0x7f61ae84095a gpu::GpuCommandBufferStub::OnInitialize()
#17 0x7f61ae84033a _ZN3IPC8MessageTI35GpuCommandBufferMsg_Initialize_MetaSt5tupleIJN4base14FileDescriptorEEES2_IJbN3gpu12CapabilitiesEEEE18DispatchDelayReplyINS6_20GpuCommandBufferStubEvMSB_FvS4_PNS_7MessageEEEEbPKSC_PT_PT0_T1_
#18 0x7f61ae83fb63 gpu::GpuCommandBufferStub::OnMessageReceived()
#19 0x7f61ae831a48 IPC::MessageRouter::RouteMessage()
#20 0x7f61ae83d163 gpu::GpuChannel::HandleMessageHelper()
#21 0x7f61ae83d0e2 gpu::GpuChannel::HandleMessage()
#22 0x7f61ae83dbb3 _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0ELm1EEEENS0_9BindStateINS0_15RunnableAdapterIMN3gpu10GpuChannelEFvRK13scoped_refptrINS6_22GpuChannelMessageQueueEEEEEFvPS7_SC_EJNS_7WeakPtrIS7_EESC_EEENS0_12InvokeHelperILb1EvSF_EEFvvEE3RunEPNS0_13BindStateBaseE
#23 0x7f61adbac9ec base::debug::TaskAnnotator::RunTask()
#24 0x7f61adbc6355 base::MessageLoop::RunTask()
#25 0x7f61adbc6678 base::MessageLoop::DeferOrRunPendingTask()
#26 0x7f61adbc683b base::MessageLoop::DoWork()
#27 0x7f61adba1cfa base::(anonymous namespace)::WorkSourceDispatch()
#28 0x7f61ab897247 g_main_context_dispatch
#29 0x7f61ab8975e8 <unknown>
#30 0x7f61ab89767c g_main_context_iteration
#31 0x7f61adba1bd6 base::MessagePumpGlib::Run()
#32 0x7f61adbdd030 base::RunLoop::Run()
#33 0x7f61adbc5b7a base::MessageLoop::Run()
#34 0x7f61b045ab9d content::GpuMain()
#35 0x7f61b0c8c257 content::ContentMainRunnerImpl::Run()
#36 0x7f61b0c8ad00 content::ContentMain()
#37 0x7f61adab1b03 CefExecuteProcess()
#38 0x7f61ada55ba7 cef_execute_process
#39 0x0000004925c2 CefExecuteProcess()
#40 0x0000004212dd client::(anonymous namespace)::RunMain()
#41 0x000000421c07 main
#42 0x7f61aa9c750a __libc_start_main
#43 0x00000040c849 <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000246
 r12: 0000000000000000 r13: 00007f61b16a87d9 r14: 000000000000813e r15: 00007ffea8d71920
  di: 0000000000000002  si: 00007f61b16a87d8  bp: 000000000000013e  bx: 0000000000000000
  dx: 0000000000000001  ax: 0000000000008000  cx: 000000000080813e  sp: 00007ffea8d71910
  ip: 00007f61b0bc3db3 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 000000000080813e
[end of stack trace]
[0927/200315:ERROR:command_buffer_proxy_impl.cc(194)] Could not send GpuCommandBufferMsg_Initialize.
[0927/200315:ERROR:webgraphicscontext3d_command_buffer_impl.cc(199)] CommandBufferProxy::Initialize failed.
[0927/200315:ERROR:webgraphicscontext3d_command_buffer_impl.cc(218)] Failed to initialize command buffer.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0318
Received signal 11 SEGV_ACCERR 00000082813e
#0 0x7f14613d97db base::debug::(anonymous namespace)::StackDumpSignalHandler()
#1 0x7f145e5b83b0 <unknown>
#2 0x7f14643f1db3 sandbox::CrashSIGSYS_Handler()
#3 0x7f14643f09fb sandbox::Trap::SigSys()
#4 0x7f145e5b83b0 <unknown>
#5 0x7f145e2111db getrandom
#6 0x7f145d698b05 <unknown>
#7 0x7f145d69a743 XML_ParseBuffer
#8 0x7f144892d6fd <unknown>
#9 0x7f144896f69c <unknown>
#10 0x7f144892abc7 <unknown>
#11 0x7f144a5ab52e <unknown>
#12 0x7f144a57acc9 <unknown>
#13 0x7f144a5ac2f8 <unknown>
#14 0x7f1461c6e6b1 gfx::GLContextGLX::Initialize()
#15 0x7f1461c5ce67 gfx::GLContext::CreateGLContext()
#16 0x7f146206e95a gpu::GpuCommandBufferStub::OnInitialize()
#17 0x7f146206e33a _ZN3IPC8MessageTI35GpuCommandBufferMsg_Initialize_MetaSt5tupleIJN4base14FileDescriptorEEES2_IJbN3gpu12CapabilitiesEEEE18DispatchDelayReplyINS6_20GpuCommandBufferStubEvMSB_FvS4_PNS_7MessageEEEEbPKSC_PT_PT0_T1_
#18 0x7f146206db63 gpu::GpuCommandBufferStub::OnMessageReceived()
#19 0x7f146205fa48 IPC::MessageRouter::RouteMessage()
#20 0x7f146206b163 gpu::GpuChannel::HandleMessageHelper()
#21 0x7f146206b0e2 gpu::GpuChannel::HandleMessage()
#22 0x7f146206bbb3 _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0ELm1EEEENS0_9BindStateINS0_15RunnableAdapterIMN3gpu10GpuChannelEFvRK13scoped_refptrINS6_22GpuChannelMessageQueueEEEEEFvPS7_SC_EJNS_7WeakPtrIS7_EESC_EEENS0_12InvokeHelperILb1EvSF_EEFvvEE3RunEPNS0_13BindStateBaseE
#23 0x7f14613da9ec base::debug::TaskAnnotator::RunTask()
#24 0x7f14613f4355 base::MessageLoop::RunTask()
#25 0x7f14613f4678 base::MessageLoop::DeferOrRunPendingTask()
#26 0x7f14613f483b base::MessageLoop::DoWork()
#27 0x7f14613cfcfa base::(anonymous namespace)::WorkSourceDispatch()
#28 0x7f145f0c5247 g_main_context_dispatch
#29 0x7f145f0c55e8 <unknown>
#30 0x7f145f0c567c g_main_context_iteration
#31 0x7f14613cfbd6 base::MessagePumpGlib::Run()
#32 0x7f146140b030 base::RunLoop::Run()
#33 0x7f14613f3b7a base::MessageLoop::Run()
#34 0x7f1463c88b9d content::GpuMain()
#35 0x7f14644ba257 content::ContentMainRunnerImpl::Run()
#36 0x7f14644b8d00 content::ContentMain()
#37 0x7f14612dfb03 CefExecuteProcess()
#38 0x7f1461283ba7 cef_execute_process
#39 0x0000004925c2 CefExecuteProcess()
#40 0x0000004212dd client::(anonymous namespace)::RunMain()
#41 0x000000421c07 main
#42 0x7f145e1f550a __libc_start_main
#43 0x00000040c849 <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000246
 r12: 0000000000000000 r13: 00007f1464ed67d9 r14: 000000000002813e r15: 00007ffe83e82120
  di: 0000000000000002  si: 00007f1464ed67d8  bp: 000000000000013e  bx: 0000000000000000
  dx: 0000000000000001  ax: 0000000000028000  cx: 000000000082813e  sp: 00007ffe83e82110
  ip: 00007f14643f1db3 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 000000000082813e
[end of stack trace]
[0927/200315:ERROR:command_buffer_proxy_impl.cc(194)] Could not send GpuCommandBufferMsg_Initialize.
[0927/200315:ERROR:webgraphicscontext3d_command_buffer_impl.cc(199)] CommandBufferProxy::Initialize failed.
[0927/200315:ERROR:webgraphicscontext3d_command_buffer_impl.cc(218)] Failed to initialize command buffer.
getrlimit(RLIMIT_NOFILE) failed
```

**Comment by saurabh95** [comment]
@hnaparst , You can try to reinstall brackets using command `sudo dpkg -i <PATH_OF_DEB_FILE>`, it will list the dependencies which failed(there would probably be 1 or 2). You can then install those dependencies, and then launching Brackets should work fine.

**Comment by sachinkamath** [comment]
@swmitra and others, thank you for supporting the Linux versions. You guys rock.

@anthonytex Thanks for the package. It just works :)

**Comment by martinwprior** [comment]
Installed onto Debian Siduction

Preparing to unpack Brackets.Release.1.11.64-bit.deb ...
Unpacking brackets (1.11.0-17524) over (1.11.0-17524) ...
Setting up brackets (1.11.0-17524) ...
xdg-icon-resource: size argument must be numeric
Try 'xdg-icon-resource --help' for more information.
Processing triggers for menu (2.1.47+b1) ...
Processing triggers for hicolor-icon-theme (0.17-1) ...
I also get the square boxes on the menu bar...... Previous versions worked, but not well. Often it would list the files but not allow me edit. I was hoping the new version would be an improvement.

**Comment by hnaparst** [comment]
@saurabh95  Gentoo does not use dpkg.  It installs all dependencies and
will not continue if one of them fails to install.

On Wed, Sep 27, 2017, at 11:20 PM, Saurabh Kathpalia wrote:
> @hnaparst[1] , You can try to reinstall brackets using command sudo
> dpkg -i <PATH_OF_DEB_FILE>, it will list the dependencies which
> failed(there would probably be 1 or 2). You can then install those
> dependencies, and then launching Brackets should work fine.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/hnaparst
  2. https://github.com/adobe/brackets/issues/13731#issuecomment-332738915

**Comment by Jeymz** [comment]
I am running an ubuntu variant Pop OS and seeing the same issues with the menu fonts. DPKG Results below

> sudo dpkg -i Brackets.Release.1.11.64-bit.deb 
(Reading database ... 226744 files and directories currently installed.)
Preparing to unpack Brackets.Release.1.11.64-bit.deb ...
Unpacking brackets (1.11.0-17524) over (1.11.0-17524) ...
Setting up brackets (1.11.0-17524) ...
xdg-icon-resource: size argument must be numeric
Try 'xdg-icon-resource --help' for more information.
Processing triggers for hicolor-icon-theme (0.17-1) ...

**Comment by assunluis80** [comment]
Using Ubuntu Budgie 17.10 and the problem persists.
![screenshot from 2017-10-22 02-16-10](https://user-images.githubusercontent.com/8853276/31857179-20460a8e-b6cf-11e7-930d-1324f8e5343f.png)

**Comment by ahmedWessamF** [comment]
Same Problem on Kali Linux 2.0 Sana using the latest Brackets Version
I tried changing the font and refreshing font cache but problem presists
![screenshot from 2017-10-27 01-35-15](https://user-images.githubusercontent.com/33124826/32081687-3cd4a200-bab7-11e7-86ab-45365a5672e9.png)

**Comment by assunluis80** [comment]
Please correct this BUG, wich makes Brackets useless therefore. This is the screenshot on Ubuntu 17.10
![brackets_on_ubuntu](https://user-images.githubusercontent.com/8853276/32151953-afa4066e-bd18-11e7-8127-5b50ef0e22d6.png)

**Comment by chsjr1996** [comment]
To fix the square fonts bug, I downloaded the package libpangoft2-1.0-0_1.40.5-1_amd64.deb in the debian repository and extract the libs "libpangoft2-1.0.so.0" and "libpangoft2-1.0.so.0.4000.5" in /opt/brackets.

**Comment by arthurflor** [comment]
@chsjr1996 It works, thanks!!

**Comment by assunluis80** [comment]
Yes! The solution provided by @chsjr1996 solved this issue.
Thanks a lot! :) :1st_place_medal:

**Comment by jegjessing** [comment]
Extracing pango files worked for me too

**Comment by kiroma** [comment]
Works here as well, going to pinpoint the broken commit now. Should we report it to pango's devs?

**Comment by kiroma** [comment]
Faulty commit: https://git.gnome.org/browse/pango/commit/?id=906509e22bf617d97a71f41d335d7a0dec344187

**Comment by Nidustash** [comment]
Thanks for great answer @chsjr1996. Ya da best

**Comment by Faouzi91** [comment]
@chsjr1996 thanks it worked for me.

**Comment by sonozaki** [comment]
Thanks! It works fine for debian testing :)

**Comment by 1efty1337** [comment]
So can I be the guy who explains how new they are to linux and ask for some more detailed instrustions on @chsjr1996 's fix?

**Comment by sachinkamath** [comment]
@1efty1337 Here you go: 

1) Download the package from libpangoft2 package from [here](http://ftp.br.debian.org/debian/pool/main/p/pango1.0/libpangoft2-1.0-0_1.40.5-1_amd64.deb)

2) Instead of opening it with Software Install, open it using Archive Manager and extract it. You will see two files. Again extract `data.tar.xz` and navigate to the folder `usr/lib/x86_64-linux-gnu` that you got after extracting.

3) Copy those files to `/opt/brackets`. You might require root depending on how you've configured your system and restart Brackets if it is already running :)

**Comment by 1efty1337** [comment]
@sachinkamath Thank you very much. I understand how easy it would have been to ignore such a simple question, and i appreciate the help!

**Comment by sachinkamath** [comment]
@1efty1337 Np! Feel free to ping if you're stuck and welcome to Linux! :)

**Comment by maicardi** [comment]
@sachinkamath 

Your method works great on Ubuntu 17.10 with Brackets 1.11.0-17524 amd64 deb taken from Brackets homepage.

Thanks!

**Comment by sachinkamath** [comment]
@maicardi, I just expanded @chsjr1996's solution but you're very welcome. Glad I could help you :)

**Comment by abargnesi** [comment]
On Ubuntu 17.10 @chsjr1996's solution wasn't complete.

I moved the libpangoft shared object files to `/opt/brackets/lib`:

```bash
/opt/brackets$ ls lib/
libpangoft2-1.0.so.0  libpangoft2-1.0.so.0.4000.5
``` 

Then I run the `/opt/brackets/brackets` script which specifically sets `LD_LIBRARY_PATH` to `/opt/brackets/lib`. This allows brackets to link to older libpangoft files.

**Comment by DarkPijem** [comment]
Hi, @abargnesi, could you kindly explain to me what exactly you did? I don't quite understand the phrases:


>  I moved the libpangoft shared object files to /opt/brackets/lib:
> 
> /opt/brackets$ ls lib/
> libpangoft2-1.0.so.0  libpangoft2-1.0.so.0.4000.5

I tried @1efty1337 's approach but it didn't work, then I tried you approach, made a file called lib in /opt/brackets and put the two files there, then ran the script you specified, it didn't work. Then I understood I have a 32-bit system, downloaded libpangoft2-1.0-0_1.40.12-1_i386.deb (which is the 32-bit version) and did the same, it didn't work. Then I tried to take your approach again, but soon realised I don't understand what you write.

Thx in advance
DarkPijem
