### ISSUE TITLE
Characters with accent marks not working

### ISSUE THREAD

**Issue by hiro-web** [adobe/brackets#13755]
### Prerequisites

* [X ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [X ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [X ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

Letters with accent marks like ^ or ' not working with new update. If you try to write á or â in editor, no matter what type of file you're editing, result is always "a" without the accent mark.

Also, i cannot write specials characters like ^ alone. White space is always the result.

**Expected behavior:** à, â, á

**Actual behavior:** a,a,a

### Versions

Brackets: Release 1.11 versión 1.11.0-17524 (release 86b5e2d4e) 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by Hraesvelg** [comment]
Same problem !! since the update on 1.11...

the antiquote ` (altgr + 7) not working ! with copy/paste it work...

i have the same configuration that hiro-web (Ubuntu etc...)

**Comment by arjonatorres** [comment]
I have the same problem too.
Please fix it.
Thank you

**Comment by moebiusgt** [comment]
In my academy the same thing happens in Ubuntu, however, in Windows it works well.

**Comment by kaskalis** [comment]
Definitely in relation to:
https://github.com/adobe/brackets/issues/13721

**Comment by moebiusgt** [comment]
I definitely have to switch to Atom, your community must be more numerous, and it is updated very often, putting patches where it is needed. I liked this Brackets, but we can not wait a day or two to fix it. If every mistake like this is incapable of fixing it in a week, you do not have to use it. Sorry about the English used, but I used the google translator.

**Comment by fanborges** [comment]
Same problem. This is sad... so sad...

**Comment by assunluis80** [comment]
Same problem I can't insert characters like "é, ç, ã" etc... since brackets 1.11. the app is full of bugs and the maintainers seems to don't care.

**Comment by nethip** [comment]
Sorry for the inconvinience. This is fixed now internally. We are currently testing the patch and will let you know about the status.

**Comment by leoleite13k** [comment]
Same problem . This was not fixed.

**Comment by filiperolopes** [comment]
Same problem. Ubuntu 14.04

**Comment by wensttay** [comment]
Same problem. Ubuntu 16.04

**Comment by Edely** [comment]
Same. Debian 9 64bits.

**Comment by chavezbosquez** [comment]
Same happens to me in Ubuntu 17.10 (64 bits). No 'á', ó, É', but 'ñ' is working fine.

**Comment by crivote** [comment]
I confirm this same issue using Brackets 1.11 versión 1.11.0-17524 on Debian 8.7 and also on Linux Mint 18.2

**Comment by nethip** [comment]
This is fixed now. We have refreshed the Linux builds of 1.11 release. Please re-download the installers from http://brackets.io
