### ISSUE TITLE
Can not toggle Mozc input-method to on at Linux

### ISSUE THREAD

**Issue by PrsPrsBK** [adobe/brackets#13762]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

After upgrading Brackets to version 1.11, I can not input japanese at Linux edition.
In order to start or stop inputting japanese,  in the system where fcitx+Mozc are working, I press toggle-key (ZenkakuHankaku on keyboard) to toggle input-mode for the language.
Now I can not toggle.

About other keys, works well as shown on physical keytop.

About versions, I tried; uninstall version 1.11, clear the cache, and re-install version 1.10 by sudo dpkg -i ./Brackets.Release.1.10.32-bit.deb, no problem.

About the way to toggle, that is Not-By-Key one via Mozc menu on desktop, it also failed.

About other softwares, terminal, text editor, firefox or so, toggle works.

About another OSs, Windows Vista, I can input japanese with MS-IME (Mozc is not installed) with the same keypress for both versions, the same machine and keyboard (laptop).
Windows 10, I can the same, but another machine and keyboard.

I tried Debug from menu and set break point to KeyEvent, following happens.
![2017-10-09-154804_910x674_scrot](https://user-images.githubusercontent.com/24764443/31333747-40c9acdc-ad26-11e7-8fe6-ff42108bc02b.png)

As for version 1.10, the debugger does not stand up.

As Windows Vista mentioned above, has a differnce.
![2017-10-09_brackets01](https://user-images.githubusercontent.com/24764443/31333812-817b03f2-ad26-11e7-8b3b-8c92c56c9691.jpg)

I can not break down any further about 'Brackets or not'.
If this issue is not Brackets' one, excuse me. Thanks in advance.

### Steps to Reproduce

1. Open Brackets and toggle by key.

**Expected behavior:** toggle input-mode by keypress as it used to.

**Actual behavior:** not toggle.

### Versions

Please include the OS and what version of the OS you're running. Lubuntu 17.04 zetsy 4.10.0-35-generic i686
Please include the version of Brackets. 1.11, without extensions.

**Comment by petetnt** [comment]
Thanks for reporting @PrsPrsBK,

are there any errors reported in the console? Sounds like a regression with CEF to me 🤔

**Comment by PrsPrsBK** [comment]
Hi. I tried, and there was no output after keypress.
![2017-10-12-195738_802x628_scrot](https://user-images.githubusercontent.com/24764443/31549802-38d0967a-b06a-11e7-9736-87421966a0e8.png)

**Comment by nethip** [comment]
This is fixed now internally. We have in the process of testing the patch and we will update the status.

@petetnt Indeed this is a bug in CEF. IME is not implemented in CEF and we are trying to patch that gap.

**Comment by nethip** [comment]
We have uploaded a pre-release build (Linux 64 only) to address this issue. Please try the build and let us know your feedback. You can download the build from https://github.com/adobe/brackets/releases/tag/release-1.12-prerelease.

**Comment by nethip** [comment]
This is fixed now. We have refreshed the Linux builds of 1.11 release. Please re-download the installers from http://brackets.io

**Comment by PrsPrsBK** [comment]
Now I can input japanese by Mozc. Thanks for your works!
