### ISSUE TITLE
Brackets live preview error... Different from other errors....

### ISSUE THREAD

**Issue by PearlAhead** [adobe/brackets#13769]
So i just installed brackets i setup the project settings and changed the theme and i was trying to make a index.html document and upload it brackets everyone was fine but i couldn't life preview  
![](https://i.gyazo.com/53cad39f1bc6353bf69e9ac3298a02d7.png)

So i looked around i enabled experimental live session multiple times and had my project settings right and i found out that brackets has a getting started with brackets html project so i clicked on it and funny enough i could open that page without a problem
![](https://i.gyazo.com/ec7967b1c5c365a659cb8e232ef45bc1.png)

so i was like ok that's odd, so i save as.. the file on my desktop and i try to live session it now and it wouldn't work and i exited the program tried to open up again but i could open up the getting started project just not the one's i saved anyone know how to fix this???  would appreciate it thanks :)

Image of me when saved not being able to open getting started project...
![](https://i.gyazo.com/cb8eae9790080e4530a22078f8b2def2.png)

**Comment by redmunds** [comment]
Move all of your files out of the Getting Started folder and into a new "project" folder. Then use _File > Open Folder..._ to select your project folder.

**Comment by codewarrior77** [comment]
Thanks redmunds . solved

**Comment by blind0x** [comment]
For everyone, this problem can be resolved by following steps:- 

1. On menu bar, go to  File --> Open Folder (folder which have your html file for live preview)

2. Select Folder

3. Select your html file from left side bar for live preview

4. Click on bolt icon on right (preview button) 

All it melts down to the fact, that you need that folder(which have your file) selected to view your output in live preview. 
Let me know, if it helps someone. :)
![2](https://user-images.githubusercontent.com/16700931/83773256-efb84d80-a6a1-11ea-8805-138f065561a9.JPG)
![3](https://user-images.githubusercontent.com/16700931/83773258-f0e97a80-a6a1-11ea-908f-b6a49236d99b.JPG)
![4](https://user-images.githubusercontent.com/16700931/83773261-f1821100-a6a1-11ea-8862-8e20a0d22c01.JPG)
![5](https://user-images.githubusercontent.com/16700931/83773262-f21aa780-a6a1-11ea-851e-a596afccf90a.JPG)

**Comment by npatel-web** [comment]
Thanks, it worked!!
