### ISSUE TITLE
Brackets v1.11 windows opens but does not respond to a single action.

### ISSUE THREAD

**Issue by Cappuccino90** [adobe/brackets#13779]
Hi there,
I just downloaded Brackets v1.11 from the official website and installed it with default settings. The bracket windows opens but I can't use any of the functions. Every single action (like open Folder, open File, About Brackets etc.) in the top navigation bar is clickable but does not do a thing. I can't even close the Brackets window.

My OS: Windows 10 Pro x64

Need more informations?

**Comment by petetnt** [comment]
Hi @Cappuccino90,

Have you previously installed Brackets? Might be that the profile under `%APPDATA%` has been corrupted (somehow?), you could try navigating to `%APPDATA%` and moving `brackets` folder to `brackets.bak` and launching again.

**Comment by Cappuccino90** [comment]
Hi @petetnt ,
it worked! Thank you very much. I am quite happy that my beloved brackets is working again! Live preview, here I come! Goodbye Visual Studio Code!
