### ISSUE TITLE
Find/Replace modifies defaultPreferences.json on disk even though it is opened read-only on Ubuntu

### ISSUE THREAD

**Issue by kenstuddy** [adobe/brackets#13774]
### Prerequisites

* [Y] Can you reproduce the problem with `Debug -> Reload Without Extensions`? 
* [Y] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [Y] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

In Ubuntu 16.04 with Xfce4.12 as my DE, if I open up defaultPreferences.json for editing by going to Debug > Open Preferences File and I do a find/replace, I am able to modify the contents of defaultPreferences.json. This is not a huge deal as I can delete the defaultPreferences.json and recreate it by going to Debug > Open Preferences File without losing any settings since my custom settings would obviously be stored in brackets.json, but it would still be nice to have this fixed eventually. This is a pretty low priority bug in my opinion.

### Steps to Reproduce

1. Open Brackets
2. Go to Debug > Open Preferences File
3. Do a find/replace and replace some text
4. Save the defaultPreferences.json file

**Expected behavior:** I expect to not be able to modify the defaultPreferences.json file.
**Actual behavior:** I am able to modify the defaultPreferences.json file.

### Versions
Ubuntu 16.04 LTS with Xfce4.12 
Brackets 1.11

### Media

Here is what it looks like before replacing:
![](https://i.imgur.com/Mhs8Gme.png)
Here is what it looks like after replacing:
![](https://i.imgur.com/oAWigxP.png)
Here we can verify that the file has actually been modified:
![](https://i.imgur.com/QGSWqcr.png)

### Updates

I have been able to replicate this bug on Windows 10 on a completely clean install of Brackets 1.11.

**Comment by petetnt** [comment]
Thanks for reporting this @kenstuddy!

Tagging' as a starter bug, not sure if it actually is non-trivial to fix though.

**Comment by kenstuddy** [comment]
Oh I certainly didn't mean to imply it's non-trivial to fix in case I did imply that, I just meant that it's probably not as high of a priority in my opinion as the other bug I reported.

**Comment by petetnt** [comment]
@kenstuddy Yeah sorry that was a bit vague from my side, but I _think_ that it's a one line fix somewhere around DocumentManager (or relevant) but it might not be too 👍

**Comment by 99M8** [comment]
Hello! Has this issue been resolved?
