### ISSUE TITLE
Erro de Download 

### ISSUE THREAD

**Issue by LBtek** [adobe/brackets#13788]
Olá, entro em contato pois não consigo fazer o download do brackets, tentei varias vezes de varias formas e sempre dá erro de acesso não permitido ou negado, sou novo no github e gostaria de utilizar o brackets para começar meus projetos web, mas infelizmente não consegui fazer o download dessa última versão e nem da 1.8, em todos os casos chega no seguinte erro:

Download no Chrome
![erro download](https://user-images.githubusercontent.com/33045622/31922247-a6010ba4-b852-11e7-9392-aca12d1e59b2.jpg)

Download no Gerenciador de downloads
![erro download 2](https://user-images.githubusercontent.com/33045622/31922321-0b6de55c-b853-11e7-92cd-ccebe1a0bc67.jpg)

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<X-Amz-Expires>300</X-Amz-Expires>
<Expires>2017-10-24T02:17:36Z</Expires>
<ServerTime>2017-10-24T02:31:34Z</ServerTime>
<RequestId>2FC19CB65F77D442</RequestId>
<HostId>
DAlVvFF6gFURI+bBYumDZol60dXi9DUPZNYqm8Mjwlvvai52SBPS47V4hcwALZZyHPfZkLd/mpM=
</HostId>
</Error>

Estou no aguardo de uma posição, desde já agradeço!

Att,
LBtek

**Comment by petetnt** [comment]
Some other users have had this issue too, reloading the app has eventually helped.

**Comment by castor3** [comment]
PT:
Conseguiste resolver o problema?
Penso que não era suposto usares nenhum gerenciador de downloads, isso pode ser de alguma forma incompativel.
Fizeste o download diretamente do site do brackets (brackets.io)?

EN:
Did you manage to solve the problem?
I think you were not supposed to use a downloads manager, that might be somehow incompatible.
Did you try to download directly from the brackets webiste (brackets.io)?

**Comment by asfelix** [comment]
@LBtek , como explicado pelo @castor3 : Faça o Download diretamente pelo site http://brackets.io/ - Acabei de fazer o download aqui e está funcionando normalmente.

**Comment by LBtek** [comment]
Resolvido amigos, consegui fazer o download na semana seguinte
