### ISSUE TITLE
i can't download it even from the official web page

### ISSUE THREAD

**Issue by Mohammad1277** [adobe/brackets#13781]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by petetnt** [comment]
Hi @Mohammad1277,

which error are you running into?

**Comment by Mohammad1277** [comment]
no error messages  just stop downloading progress

**Comment by Mohammad1277** [comment]
at least solved now

**Comment by HuserB8927** [comment]
I've been downloading it for 3 hours, stopped once. I tried using Safari and Google Chrome. I can download everything else very fast but this... doesnt want to be done. Any idea?

**Comment by Explikation** [comment]
I tried to download brackets yesterday and today. The download from the main page brackets.io is quite hopeless. I have tried it with 2 Windows pcs and my Macbook Pro. It takes hours to get the download nearly finished and then at around 70 mb it breakes. This is really unfortunate, because brackets is such a superb tool.
