### ISSUE TITLE
problem with auto closing of tags

### ISSUE THREAD

**Issue by 9192939495969798** [adobe/brackets#13787]
Respected Sir/Madam,

I'm confused overcoming my problem, that if I have to add a tag to existing content then it is very difficult to do so......because it closes the tag automatically, Then I have to select the unnecessary closing tag and cut it, then by pasting it the end of the content I continue my coding.
![scrshot_5](https://user-images.githubusercontent.com/33022492/31881183-a57a61d2-b797-11e7-8e30-16859700ea68.PNG)

**Comment by navch** [comment]
@9192939495969798 You can disable auto close by adding below line 
**"closeTags": { "whenOpening": false, "whenClosing": true, "indentTags": [] }** 
in "C:\Users\name\AppData\Roaming\Brackets\brackets.json"

If think this is what you want. I am closing this issue, Please feel free to open it again if you have any concern ?

**Comment by 9192939495969798** [comment]
Thank you sir ji.
