### ISSUE TITLE
CSS doesn't work

### ISSUE THREAD

**Issue by joshieex** [adobe/brackets#13791]
CSS doesn't work even after i  put both my index.html and style.css in the same project/folder and link the style.css within the html. 
'<title> Free Your Mind </title>
`<link type="text/css"rel="stylesheet"href="Style.css"/>`
`<ul id="nav">
            <li> <a href="#"> Home </a> </li>
            <li> <a href="#"> Websites </a> </li>
            <li> <a href="#"> Contact </a> </li>
            <li> <a href="#"> Shadow :)</a> </li>
            <li> <a href="#"> Blog </a> </li>
        </ul>`

I put basic css in like to change the color of something but nothing changes and am wondering what im doing wrong

**Comment by kiroma** [comment]
Make sure the name casing matches, I see you're linking to `Style.css` but you said you wanted to link to `style.css`.
You can also put multiline code in like this:
\`\`\`
code
\`\`\`
