### ISSUE TITLE
how to use mptcp in user application

### ISSUE THREAD

**Issue by sukkhi** [adobe/brackets#13792]
I am pretty new to MPTCP & have successfully installed mptcp v-0.92 from  multipath-tcp.org.
But I am unable to use MPTCP in user applications.
I am unable to find any of examples in C programming.

even after installing mptcp no user space headers were found in usr/include/
kind help will be appreciated.

**Comment by nethip** [comment]
@sukkhi I am not sure if we can help you with the above query in this forum.
