### ISSUE TITLE
Refactoring Javascript

### ISSUE THREAD

**Issue by boopeshmahendran** [adobe/brackets#13803]
Hi All, 
                   We are planning to implement Refactoring feature (as of now JavaScript only) in Brackets.
So we are trying to understand more useful features as part of refactoring. We are listing down some features here:-

1. **Rename named variables, functions, members**
                         This feature will help a user with renaming variables, function etc, within a restricted scope.
Please check this #13047  for more details.

2. **Extract Selected Block**
            
- **As variable**
This feature is about extracting an expression to a new variable. For example, in the following snippet, `navigator.name `can be extracted as say, `someVar`, and the occurences of `navigator.name `will be replaced by `someVar`

```javascript
if (navigator.name.indexOf(“Opera”) != -1) { 
   Browser = “O”;
}
else if (navigator.name.indexOf(“Microsoft”) != -1) {
   Browser = “MSTE”;
}
```
The above snippet will be refactored to 
```javascript
var someVar = navigator.name;
if (someVar.indexOf(“Opera”) != -1) {
    Browser = “O”;
}
else if (someVar.indexOf(“Microsoft”) != -1) {
    Browser = “MSTE”;
}
```

- **As function**
This feature will help the user to create new function/method from the selected code block, this will also take care of parameters that need to be passed.

3. **Code Generation**
 
 - Wrap in try/catch
 - Create Getters/Setters
 - Wrap in Arrow function
 - Wrap in Condition

4. **Parameter wrapping**
- **Multiple arguments to a single object**
This feature will allow a user to combine all arguments of a function to a single object. For example, see the below snippet 

```javascript
function select(start, end, steps, clear) { ... }
```

The above snippet will be refactored to 

```javascript
function select(options) {
    var start = options.start,
    end = options.end,
... }
```

This will change the function invocation part as well.

Please feel free to add more features and mention the features which would be the most useful to you. Looking forward to your feedback.

**Comment by swmitra** [comment]
@petetnt @ficristo @zaggino @MarcelGerber @busykai @abose @saurabh95 @peterflynn @ingorichter Can you please let us know your opinion about the usefulness of having these features built in to Brackets?

**Comment by redmunds** [comment]
This sounds awesome, but would be better implemented as an extension (to keep Brackets core leaner for those that don't use it). If it's not possible to implement with current API, then where does it not work? In other words, what APIs need to be added to Brackets to make it work?

**Comment by busykai** [comment]
+1 for the feature: I've been hearing this feedback many times. People felt that refactoring was something missing in Brackets. I also second @redmunds suggestion, it's better off as an extension.

**Comment by ingorichter** [comment]
+1 I agree with @redmunds and @busykai. It's easier to maintain in a separate extension.
