### ISSUE TITLE
Any intentions for supporting Language Server Protocol ?

### ISSUE THREAD

**Issue by pushqrdx** [adobe/brackets#13802]
I love brackets and i think it can more awesome if LSP support is added so we can have more languages supported out of the box. is there anyone working on this already or am i missing something ?

**Comment by pushqrdx** [comment]
is there even anyone here 🌵

**Comment by nethip** [comment]
@pushqrdx Could you be site some examples as part of LSP support inside Brackets?

**Comment by pushqrdx** [comment]
@nethip sorry i don't get what you asking for but enabling LSP support in Brackets will open up a plethora of enhancements to the editor, you can look at all the languages that will immediately be supported once Brackets get LSP implementation.

**Comment by pushqrdx** [comment]
it's sad how a very nice editor as Brackets is abandoned like that..

**Comment by nethip** [comment]
@pushqrdx We usually prioritize our work items based on the community feedback posted on our Trello board. I have created a card for this specific feature [here](https://trello.com/c/vsKPRRxw/1439-draft-support-lsp-inside-brackets). Please upvote the card and add your comments there about what are the possible ways Brackets can help in authoring LSP files.

**Comment by thorade** [comment]
@nethip Please read about LSP here:
https://github.com/Microsoft/language-server-protocol
and see an example of LSP in action here:
https://github.com/palantir/python-language-server
It is not another language, so this is NOT about authoring LSP files.

**Comment by pushqrdx** [comment]
Language Server Protocol is a contract between an editor and a language author making it possible for all editors that support that protocol to be extendable by language authors without minimum to no effort. If LSP is implemented in Brackets brackets will instantly support:
- C# via Omnisharp
- CPP via Microsoft Language Server
- Typescript via Microsoft Language Server
- Javascript
- PHP
- Java

The list goes on and on as nearly all major programming languages have already implemented open source language servers to be consumed in any LSP supported editor. So Brackets will be an equally competing editor to vscode, atom and others (maybe even better). 
Other things that will just naturally be supported out of the box is auto completion, code fixes, go to in every single language without any effort from Brackets team.

**Comment by swmitra** [comment]
@pushqrdx We understand the importance of LSP in Brackets context. We are working towards bringing LSP as our Language tools interface. However we can't commit an ETA at this point of time. It would be available eventually once we finish the implementation.
