### ISSUE TITLE
file/NativeFileSystem has not been loaded (accessability)

### ISSUE THREAD

**Issue by pauledd** [adobe/brackets#13806]
### Prerequisites

* [n] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
*  [y] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [y] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

I get an error trying to load the extension accessability

### Steps to Reproduce

1. load the accessability extension

**Expected behavior:** Should load and be usable

**Actual behavior:** get an error message and extension is not usable

### Versions

Using brackets Release 1.11 Build 1.11.0-17524 (release 86b5e2d4e) on gentoo linux.
accessability 2.2.2 — 17.07.2015.

I get this error message:

```
ErrorNotification.js:122 [Extension] failed to load /home/paul/.config/Brackets/extensions/user/accessability - Error: Module name "file/NativeFileSystem" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloaded
window.console.error	@	ErrorNotification.js:122
/utils/ExtensionLoader.js:231 Error: Module name "file/NativeFileSystem" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloaded
    at makeError (require.js:166)
    at Object.localRequire [as getModule] (require.js:1400)
    at Object.<anonymous> (main.js:13)
    at Object.execCb (require.js:1658)
    at Object.check (require.js:869)
    at Object.<anonymous> (require.js:1121)
    at require.js:132
    at require.js:1164
    at each (require.js:57)
    at Object.emit (require.js:1163)
```
any ideas anyone?

**Comment by ficristo** [comment]
`file/NativeFileSystem.js` was a file present in core which was removed in a previous release.
You should file an issue to the extension to update to use the newer api.
