### ISSUE TITLE
v1.11 broke application menus

### ISSUE THREAD

**Issue by kneeki** [adobe/brackets#13816]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

After updating to the latest version of Brackets, my menus and submenus look like:

![image](https://user-images.githubusercontent.com/1012169/32455500-939b90e6-c2c6-11e7-9573-07a5336bfdeb.png)

After downgrading to Brackets v1.10 the problem went away.

### Versions

OS: Ubuntu 17.10 x64
Brackets: Release 1.11 build 1.11.0-17524 (release 86b5e2d4e)

**Comment by kiroma** [comment]
Known issue at #13738, please look at #13731 for resolution.
In essence, to solve it please install libpangoft2-1.0-0 >= 1.40.5 or unpack the libs from the package to path of Brackets installation.

**Comment by kneeki** [comment]
Thanks!
