### ISSUE TITLE
Mac: After exiting Live Preview feature, external links don't open in Chrome

### ISSUE THREAD

**Issue by brij1234** [adobe/brackets#13819]
### Description
After done using the live preview feature, any link clicked from outside Chrome (ex: Mail) open a new window with the new tab page.

### Steps to Reproduce

1. Use Live Preview feature in Brackets
2. Close Live Preview
3. Attempt to click a link anywhere outside of chrome

**Expected behavior:** [What you expected to happen]

- Links open in chrome

**Actual behavior:** [What actually happened]
- While using the live preview feature, all external links open in the live preview window.
- When the live preview is turned off, a new chrome instance is created briefly and then a new tab page is shown.

### Versions

- Brackets -- Release 1.11 build 1.11.0-17524 (release 86b5e2d4e) 
- macOS 10.13.1

**Comment by RoneyThomas** [comment]
I have the same issue. But i don't have brackets installed seems like its a problem with Chrome. I am running same version of mac as you.

**Comment by asfelix** [comment]
There's no this issue in  MacOS Sierra 10.12.5 (16F73). The links don't open in Live Preview, but in a new windows. I'm use a link in the Notes to test.

**Comment by brij1234** [comment]
this is a chrome issue
