### ISSUE TITLE
Release plan for Brackets 1.12

### ISSUE THREAD

**Issue by nethip** [adobe/brackets#13821]
Here is a list of items that are currently worked upon for Brackets 1.12

**Features**

- [x] JS Refactoring](https://github.com/adobe/brackets/issues/13803) : Allow rename of variables across the project as well as extracting expressions to variables. We are currently looking for feedback. If you have any, please ping us on slack or provide your comments [here](https://github.com/adobe/brackets/issues/13803). (@boopeshmahendran)

**Bug fixes**
- [x] Linux: Font menu corruption bug on Ubuntu 17 (@nethip) (Fixed locally: under review) - Done Refreshed the builds.
- [x] Linux: IME not working after CEF update (@nethip) (Fixed locally: under review) - Done Refreshed 1.11 builds
- [ ] More bugs, that need to be fixed, to be added after scrubbing through the issues. (@nethip, @boopeshmahendran )

**Postponed**

- Auto-updater framework:  Allow Brackets updates to be applied seamlessly, without having to download the installers manually. (@nethip) (Moved out to next release). I have updated the ]next release card](https://github.com/adobe/brackets/issues/14044) with this item.

**Comment by SalemCode8** [comment]
So Good the Auto-updater framework is the idea needed for programs for a long time this will make brackets more powerful but please don't forgot to add dialog to notice the user to the new features because of conflicting i know if you change something in new release and the brackets update himself with the new change this may cause a problem to the user

and as idea you can add also a automatic feedback 
i mean when error happens or bug appear the brackets send it directly to you so you can make list of changes in every release because there is some problems may happen without any one getting notice on it

**Comment by nethip** [comment]
@SalemCode8 Sure!  We will keep that in mind about the new features dialog coming along with the update dialog message.

About the feedback: That's a good idea! We did think about it a while back but could not get onto the feedback mechanism part. I will bring this up in our daily standup again and provide an update.

**Comment by petetnt** [comment]
Autoupdater was one of top wants 🙆‍♂️ 

Let me know if there's anything I could help 🆗

**Comment by Irbidan** [comment]
Also you can add a HTML editor like in Dreamweaver with some facilities and main features of that software.

**Comment by kiroma** [comment]
Could you give us an example of a feature that you think is missing in Brackets?

**Comment by petetnt** [comment]
@Irbidan have you tried https://github.com/swmitra/html-designer?

**Comment by Irbidan** [comment]
@petetnt 2 years ago last update...

**Comment by Irbidan** [comment]
@kiroma i think a UI for beginners in programming. Dreamweaver has it. Colors, paletes, insert codes, etc. That idea of a complete 'editor'.

**Comment by kiroma** [comment]
Colour choosers and palettes are already implemented in Brackets, there are a lot of different extensions and plugins which also provide additional features. Don't underestimate extensions just because they have been created some time ago, it doesn't mean they aren't useful.

**Comment by nethip** [comment]
@petetnt Sure! Thanks.

**Comment by Ahmed3essa** [comment]
What about Lagging problem ? I think thats have a high priority

**Comment by nethip** [comment]
@Ahmed3essa Please log a new bug with appropriate details, if you are seeing any performance issues with Brackets?  We will have a look at it!

**Comment by petetnt** [comment]
Could we do checksums for the 1.13 release?

Related: https://github.com/adobe/brackets/issues/13364
