### ISSUE TITLE
CTRL + F

### ISSUE THREAD

**Issue by SamDickey** [adobe/brackets#13835]
This is not an issue, this is a suggestion.  I'm sorry if this is annoying, but I don't see anywhere else to leave suggestions.  I think that it would be really nice when you used CTRL + F to find strings in your code if there was a way to put a cursor at each result.  For instance, I just finished a javascript project, and there were a lot of "console.log()" statements that I had to remove.  It would've been much faster if I could've used CTRL + F to find all the console.log() statements and then put a cursor at each one so that I could delete them simultaneously.

**Comment by petetnt** [comment]
Hi @SamDickey,

there's an option called `Find All And Select` in the Find menu (on Mac it's `shift+command+G`, so something like `ctrl+shift+f` which does what you want: find a console.log, highlight it, press the command and delete with backspace.

**Comment by JungGaBin** [comment]
Hi @SamDickey,


In addition to the Find menu, there are shortcuts you can use to change the words you find to other words. `Ctrl+Shift+H`
