### ISSUE TITLE
Brackets crashes if file is open in it and when I download the same file from the server and replace it in the destination

### ISSUE THREAD

**Issue by devdmore** [adobe/brackets#13839]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by devdmore** [comment]
Whenever I work on the live project, We are 3 peoples works on a single page at the same time. So to get the latest file when I download the same file from the server; brackets stop's working every time. In the earlier version, it used to update the file with new content now it only hangs.

**Comment by nethip** [comment]
@devdmore Could you mention more details like your setup(git, files on server e.t.c) so that we can try to recreate the issue at our end to see what is causing the crash?

**Comment by devdmore** [comment]
Dear
​
Prashanth,

Thanks for the quick response.Basically, I am a Fronted developer, so I
work on the HTML files mostly. So whenever I work on the particular
project, I keep related files(html, css, js files) open in the brackets and
I use FileZilla to upload and download the files on our test server. If I
download any of the files from the server which is already open in the
brackets editor, then suddenly brackets stop working every time. I am using
brackets for last 1 year, but this never happened to me. But nowadays this
is happening every time. Thanks in advance.

Regards,
Devendra More.

On Thu, Nov 16, 2017 at 10:56 AM,
​​

**Comment by K1noCo** [comment]
yup, same thing here... looking for the solutions...

**Comment by nethip** [comment]
I have created a task item for this. This should be fixed for 1.13.

**Comment by nethip** [comment]
https://github.com/adobe/brackets-shell/pull/635 should fix this.

**Comment by ayushrathi15** [comment]
Tested on 1.13.0-17666.
This is working fine now.
