### ISSUE TITLE
Cannot link html with css

### ISSUE THREAD

**Issue by DavidShield** [adobe/brackets#13838]
I just follow some steps along one of udemy's course, but it seems that my .css cannot linked to my index.html. 
I have changed the margin or set the background color of .row to green but nothing changes.
Can somebody help me?

![image](https://user-images.githubusercontent.com/26129973/32744981-4e1eadf0-c87f-11e7-9c99-79f88c082781.png)

![image](https://user-images.githubusercontent.com/26129973/32745030-7f32d2f4-c87f-11e7-9d64-af81b66c7f33.png)

**Comment by DavidShield** [comment]
it seems that I use res instead of rel, but even I changed it to 
        <link rel="stylesheet" type="text/css" href="resources/css/style.css">
It still not work

**Comment by DavidShield** [comment]
I found the problem....
I accidentally name the resources as resourses

**Comment by FlyteWizard** [comment]
@DavidShield Make sure to close the issue.

**Comment by ficristo** [comment]
Closing as resolved.

**Comment by DavidShield** [comment]
Sorry, this is my first time post an issue here. Here comes a suggestion. Maybe it is better to have a tool to detect whether the folder index exist, as I use the wrong path but it can still find files.
