### ISSUE TITLE
Menu font displayed in squares instead of letters

### ISSUE THREAD

**Issue by Babayasin** [adobe/brackets#13836]
![_2017-11-13_11-25-27](https://user-images.githubusercontent.com/2748461/32706069-1e466d7a-c866-11e7-9bab-a6dbdedc67e4.png)

Debian 4.12.13-1 (2017-09-19) x86_64 GNU/Linux
Brackets 1.11
LANG=ru_RU.UTF-8

Changing menu font in window manager settings has no effect. Any font is displayed in squares. Changing the language of Brackets (English/Russian) has no effect either.

**Comment by petetnt** [comment]
Hi @Babayasin,

this should be fixed in 1.12. as stated in https://github.com/adobe/brackets/issues/13821.

**Comment by vincenzoml** [comment]
Ok but what can I do right now? I just downloaded brackets and can't use it.
