### ISSUE TITLE
Text replaces existing neighbouring text.

### ISSUE THREAD

**Issue by kriadmin** [adobe/brackets#13880]
### Description
When I Use Brackets and  I have some text for example this one.![image](https://user-images.githubusercontent.com/31792358/32988890-6935b80a-cd33-11e7-870b-719fd0e68c12.png)

Now when I place the cursor anywhere in the middle of the text it starts replacing the existing text(see the GIF).

![](https://im4.ezgif.com/tmp/ezgif-4-4cc6a7619e.gif)

### Steps to Reproduce

1. [Enter any random text. It can be any text(even HTML).]
2. [Next Place the cursor in between the text and starting typing anything. ]
3. [You will see that the new text will replace the existing one.]

**Expected behavior:** [I expected that the text will be inserted in between the existing text and the existing text will not be affected]

**Actual behavior:** [The existing text was replaced by the new text(see the GIF).]

### Versions

I am using windows 10
Brackets Version : Release 1.11 build 1.11.0-17524 (release 86b5e2d4e)

**Comment by ficristo** [comment]
You are in the Overwrite mode, you can see it in the statusbar where there is the OVR label.
To go back in the Insert mode you can click it again or press the Ins button on your keyboard.
