### ISSUE TITLE
Node.js fails. LivePreview opens "file://...". Also "Cannot read property restartNode of undefined"

### ISSUE THREAD

**Issue by kevin28east** [adobe/brackets#13899]
### Prerequisites

* [yes] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [yes] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [yes] Did you read the [Troubleshooting guide]?

### Description

This happened after we had to use Node.js development. The included node debugger did not seem to respond to any actions so we installed the nodejsdebugger extension. This also did not respond/work. We reinstalled and them updated Node.js. During these 3 actions the issues started appearing, not necessarily in that order.

1. LivePreview opens the page as `file://...` and not as `localhost` or `127.0.0.1` Thus objects aren't highlighted or selected either direction. Though closing the tab shows expected error of "detached process"
2. Extensions like Git don't open/work (clicking the extension on the right hand menu does nothing) though other extensions like file icons and beautify work.
3. Updating/Installing/Uninstalling extensions returns error "Installation failed. Unknown internal error."
4. `Debug > Restart Node` or `Debug > Enable Node Debugger` returns JavaScript Alert "Failed trying to enable Node debugger: Cannot read property 'enableDebugger' of undefined"

Attempts to fix
1. Reinstalling does not help. (Brackets and Node (though I think it might be the wrong versions, we tried 8 and 9))
2. Restarting does not help.
3. Chrome is installed for multiple users.

We are now stuck with Node.js Installed and Brackets installed but can't for the life of the pope get these 2 to notice each other.

### Steps to Reproduce

Guesstimate : Update Node / Uninstall Node / Reinstall Node /Update Windows

**Expected behavior:** 
Expected included node debugger to work.

**Actual behavior:** 
Everything halted/malfunctioned. LivePreview, Extensions, Extension Manager and Node.js function inside Brackets

### Versions

Windows 10

Release 1.11 build 1.11.0-17524 (release 86b5e2d4e) 
build timestamp: Wed Sep 20 2017 11:49:15 GMT+0100

**Comment by kevin28east** [comment]
Using node 6.12 Still no luck. Brackets can't find node
![image](https://user-images.githubusercontent.com/26323923/33073268-071bedb2-cecb-11e7-92ca-f2b67916f6b9.png)

**Comment by nethip** [comment]
@boopeshmahendran Is it possible for you to look into this?

**Comment by boopeshmahendran** [comment]
@kevin28east Brackets uses a node process (node.exe found in brackets installed folder **Ex:** `C:\Program Files(x86)\Brackets\node.exe`) for some of it's features.

The options you mentioned `Debug > Restart Node` and `Debug > Enable Node debugger` are for debugging the node code in brackets i.e they are for debugging brackets itself.

Brackets still doesn't support node js debugging.

And in your case, it seems that brackets node process failed. Do you see any errors in your console?

**Comment by kevin28east** [comment]
@boopeshmahendran 
![image](https://user-images.githubusercontent.com/26323923/33254446-7efd99a4-d351-11e7-9a9c-5212458fe707.png)

**Comment by kevin28east** [comment]
@boopeshmahendran 

Is that what you required?
I can provide more information if needed.

**Comment by kevin28east** [comment]
@boopeshmahendran node.exe exists in that folder for brackets and is executable

Here is a screen dump of the whole console after launching brackets
![image](https://user-images.githubusercontent.com/26323923/33546366-7b0f209a-d8e9-11e7-868c-3da65ecf940c.png)

**Comment by boopeshmahendran** [comment]
@kevin28east I am absolutely sorry for the late reply. There might be some brackets extensions which crashes the node process. Could you provide the names of your installed brackets extensions. You can get the info at `Help->Health Report`.

Also do you see this problem on every brackets launch?
Did you try uninstalling and reinstalling brackets?

**Comment by kevin28east** [comment]
@boopeshmahendran Thanks.

In the first post i mentioned I tried reinstalling which does not work. If I count all the frustrated reinstalls it could count to about 20 times :( 

This is consistent with every launch.

here is my next health report.

`{
    "snapshotTime": 1512392512362,
    "os": "win",
    "userAgent": "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.11.0.0 Chrome/49.0.2623.110 Safari/537.36",
    "osLanguage": "en-US",
    "bracketsLanguage": "en-US",
    "bracketsVersion": "1.11.0-17524",
    "fileStats": {
        "openedFileExt": {
            "json": 4
        },
        "workingSetFileExt": {},
        "openedFileEncoding": {
            "UTF-8": 4
        }
    },
    "projectLoadTimes": ":3383",
    "fileOpenTimes": ":584:841",
    "ModuleDepsResolved": 854,
    "AppStartupTime": 6799,
    "prefNodeSearchDisabled": false,
    "prefInstantSearchDisabled": false,
    "installedExtensions": [
        {
            "name": "monokai-darkness-reborn",
            "version": "1.0.0"
        },
        {
            "name": "brackets-npm-registry",
            "version": "0.6.5"
        },
        {
            "name": "szdc.cdn-suggestions",
            "version": "2.0.3"
        },
        {
            "name": "brackets-minimap",
            "version": "3.2.6"
        },
        {
            "name": "ivogabe.icons",
            "version": "1.5.7"
        },
        {
            "name": "zaggino.brackets-git",
            "version": "0.16.6"
        },
        {
            "name": "js-minifier-offline-google-closure",
            "version": "0.1.4"
        },
        {
            "name": "brackets-beautify",
            "version": "2.5.0"
        }
    ],
    "bracketsTheme": "monokai-darkness-reborn",
    "uuid": "661d-aff5-ef83-0319-0f6f",
    "olderuuid": "1700232e-e322-4b38-8fec-946b34cd947d"
}`

**Comment by kevin28east** [comment]
@boopeshmahendran 

Just to clarify if if I could uninstall extensions from within brackets I would but the process crashes when trying to update/install/uninstall an extension.

is there any way to uninstall or remove an extension externally?

**Comment by boopeshmahendran** [comment]
@kevin28east the extensions folder can be accessed by `Help > Show Extensions Folder`. You can remove or move the extension folder to uninstall an extension.

**Comment by kevin28east** [comment]
"Fixed" it by formatting....
