### ISSUE TITLE
 problem with the menu in ubuntu 17.10

### ISSUE THREAD

**Issue by paletGerardo** [adobe/brackets#13905]
the bracket menu bar appears with symbols. this only happens with the latest version. I already try several methods but I can not solve it.

**Comment by nethip** [comment]
@paletGerardo This is currently being worked upon. Sorry for the inconvenience! This is currently fixed and in under testing and we will be refreshing the builds with the fix in a few days time.

**Comment by ogerly** [comment]
the problem is still there

**Comment by archandha** [comment]
Probably this issue is a duplicate from #13738 (cf. https://github.com/adobe/brackets/issues/13738 )

This fixed it for me:
https://github.com/adobe/brackets/issues/13738#issuecomment-342639039

**Comment by paletGerardo** [comment]
Hola! cambie el sistema op por kde neo, y aca si funciona perfecto.

2017-12-12 8:49 GMT-03:00 Alexander Friedland <notifications@github.com>:

**Comment by nethip** [comment]
This is fixed now. We have refreshed the builds of 1.11 release. Please re-download the installers from http://brackets.io
