### ISSUE TITLE
[Question] How to use the Tern in Brackets?

### ISSUE THREAD

**Issue by wozjac** [adobe/brackets#13911]
Hello,

could you send me some guidance how to use the built-in Tern server? Didn't find docs about it.
In my extension I would like to get the variable type.

Best,
Jacek

**Comment by nethip** [comment]
@navc, @boopeshmahendran Could either of you take this question?

**Comment by navch** [comment]
@wozjac If you want to find type of variable in current editor then you can use this ?

`var tokenType = TokenUtils.getTokenAt(cm, cm.getCursor()).type;`

tokenType will be like  "variable-2" "variable" "property", "def" etc.

Does this solve your problem ? Or you don't have editor for that document ?

**Comment by wozjac** [comment]
Hi, thanks for your response.

Actually I'm looking for more detailed type/source information, like in http://ternjs.net/doc/demo/index.html#requirejs - when you hit ctrl+i (find type command) you get the object details (and internally it find the origin "text_util.js" module.

Right now I'm using the mentioned getTokenAt and do some analysis by myself.
Basically Javascript Code Hints extension do the right job - Session.getHints returns a variable and its type, so I will try to go this way and reuse it. I see that Tern server is launched with requirejs plugin, what is still to do for me is to make it run with OpenUI5 framework way of modularizing, which has basically the same syntax, but it starts with sap.ui.define(....), so instead:
requirejs(["text_util", "output"], function(text, output) {
I have
sap.ui.define(["text_util", "output"], function(text, output) {

Best,
Jacek

**Comment by navch** [comment]
In JS code hitns we have another tern server not the build in one. So May be you can create one more tern server. It looks like you exposed require by sap.ui as same as bracket.getModule instead of require I am not sure does tern allow to set this kind of value in tern preferences. But they have a seperate require module in tern's plugin folder there you can check.
