### ISSUE TITLE
Tabs on top of editor are unreadable

### ISSUE THREAD

**Issue by GarrukApex** [adobe/brackets#13927]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

First of all, I'm trying to use the stable version, 1.11.6, downloaded both from github and the big button of brackets.io. The top of the editor (where tabs like file, edit, help, etc go) is instead replaced by black squares. All sub buttons are also black squares. This is a new, unmodified release, I just downloaded. I've downloaded 3 separate times, same issue. I'm running a freshly updated version of kubuntu 17.10. I attached a screenshot. 

### Steps to Reproduce

1. Open Brackets
2. Look at top bar
3. Can't read top bar
4. Profit???
![screenshot_20171126_195504](https://user-images.githubusercontent.com/20913473/33250144-bd5b00f6-d2e3-11e7-9e1b-7b177967e95d.png)

**Expected behavior:** 
Be able to read top buttons

**Actual behavior:** 
Unable to read top buttons

### Versions

Please include the OS and what version of the OS you're running.
Kubuntu 17.10
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)
1.11.6

**Comment by ParadauxDev** [comment]
Running on Linux just fine, Ubuntu 16.04 no missing tabs

**Comment by mrVragec** [comment]
Same issue here. 
Working on Ubuntu 17.10. 
Tried Reload Without Extensions but same issue persist.
Previous version (1.10 and 1.9) working without issues. 

![screenshot from 2017-12-01 22-16-29](https://user-images.githubusercontent.com/2029195/33503949-e1eda3f0-d6e5-11e7-8ab7-9dcb719d9b3b.png)

![screenshot from 2017-12-01 22-17-34](https://user-images.githubusercontent.com/2029195/33503952-e539cc50-d6e5-11e7-86f5-4cc731a3e62e.png)

![screenshot from 2017-12-01 22-18-40](https://user-images.githubusercontent.com/2029195/33503956-e7d9b2a4-d6e5-11e7-9c11-0edb401481c1.png)

**Comment by kenstuddy** [comment]
This appears to be a duplicate of 13738.

**Comment by GarrukApex** [comment]
This issue was fixed in the latest early/developer release for me. I'm closing the issue now.
