### ISSUE TITLE
Linking Css File To HTML

### ISSUE THREAD

**Issue by VikramadityaRajawat** [adobe/brackets#13926]
Unable to link css to html is the linking code line correct given below⬇
![capture](https://user-images.githubusercontent.com/30496088/33240619-dd587e7e-d2de-11e7-9e7f-cc3e38e201a6.JPG)

**Comment by redmunds** [comment]
`<link rel="stylesheet" ... />` tags should always be inside the `<head>` tag.

**Comment by veryprofessionaldodo** [comment]
Please close this issue.
