### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by redmangospros** [adobe/brackets#13947]
WHY IS THE WEBSITE UNSERUCE?

**Comment by VutonDesign** [comment]
It's not necessarily "unsecure", it just doesn't have an SSL certificate linked to it. (There is no login page or forum so It doesn't really a certificate)

**Comment by redmangospros** [comment]
Oh Thanks, How DId you find this? DO YOU TRACK My issues?

**Comment by VutonDesign** [comment]
No, I just watch this repository 😆

**Comment by VutonDesign** [comment]
I think this can be closed now ✔️

**Comment by redmangospros** [comment]
Do you use this?

**Comment by VutonDesign** [comment]
Yeah

**Comment by redmangospros** [comment]
cool.
