### ISSUE TITLE
Menu bar missing icon

### ISSUE THREAD

**Issue by simon1tan** [adobe/brackets#13954]
Ubuntu 17.04
Brackets 1.11.0-17524
openbox

Brackets seems to be missing a menubar icon. It is using a generic window icon as can be seen in the image. Next to Brackets is Firefox with the proper icon. This becomes problematic when other applications also use a generic icon(yes, they exist).
![screenshot from 2017-12-03 12-58-55](https://user-images.githubusercontent.com/1250858/33529724-bccbed30-d829-11e7-83ab-0e1d338cb20f.png)

**Comment by nethip** [comment]
Thanks for reporting @simon1tan . We will have a look at it.

**Comment by FilipePintoReis** [comment]
@simon1tan  I also have that SO and openbox, where are you getting those windows from?

**Comment by parAndrei** [comment]
I'm on xUbuntu running Ubuntu 17.10 32bits, and all Menus are missing, top level and inside the dropdown.

Here is the error message I got in the terminal when installing it:
```
(Lecture de la base de données... 360581 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de Brackets1.11.deb ...
Dépaquetage de brackets (1.11.0-17524) sur (1.10.0-17483) ...
Paramétrage de brackets (1.11.0-17524) ...
xdg-icon-resource: size argument must be numeric
Try 'xdg-icon-resource --help' for more information.
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.17-1) ...

```

Looks like the icons-file is missing or something else causing problems with xdg-icon-resource.
Wanted to have the latest official version, but now my Brackets is unusable.

I maybe should get rid totally of my Brackets 1.10 then install again, but I see no reason why a regular update won't work as expected.

![brackets1 11](https://user-images.githubusercontent.com/128460/35476715-cd95b1b2-03b4-11e8-9898-74c1126eb787.png)

**Comment by nethip** [comment]
@parAndrei Can you redownload the builds from http://brackets.io and see if that fixes the issues. We fixed this problem and refreshed our 1.11 builds.

**Comment by parAndrei** [comment]
I can't thank you all enough for all the work! 
Brackets is back, up and running smoothly.

**Comment by KeeeN** [comment]
Same missing icon issue using Release 1.12 build 1.12.0-17621 (release d3b783b99)  on ubuntu 17.10.

![screenshot from 2018-03-31 15-59-06](https://user-images.githubusercontent.com/3985700/38163951-c48b739e-34fc-11e8-8143-86db7509eac2.png)
