### ISSUE TITLE
Git and Brackets are linked somehow and I can't undo it

### ISSUE THREAD

**Issue by hughesgm8** [adobe/brackets#13958]
### Description

I had a repeating issue where, whenever I pulled changes from a remote git repository, my terminal would print the following several times and launch Brackets:

`[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`

I have no idea why it launched Brackets, especially since Sublime Text is my default editor and I never use Brackets anymore. In order to stop that, I uninstalled Brackets. Now when I try to pull I get this message: 

```
error: There was a problem with the editor '/Applications/Brackets.app/Contents/MacOS/Brackets -wl1'.
Not committing merge; use 'git commit' to complete the merge.
```

And when I try again: 

```
error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge.
```

This happens when I have not made any local changes and git should just pull all new changes without conflict. I know at some point, years ago, I made Brackets my default editor, but soon switched to Sublime Text. Git and Brackets must still be linked somehow but I don't know how to figure it out.

### Versions

N/A because I uninstalled Brackets, but I'm running MacOS High Sierra.

**Comment by petetnt** [comment]
Hi @hughesgm8,

sounds like your git config `core.editor` or `GIT_EDITOR` env variable has been set to `brackets` for some reason.

You can reset it with

``` bash
git config --global core.editor "vim"

# or if it has been set with the ENV variable
export GIT_EDITOR=vim
```
(You can also set `vim` to Sublime Text if you want to).

**Comment by petetnt** [comment]
Closing as answered, do ping back if the issue still persists
