### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by KBPsystem777** [adobe/brackets#13957]
Enhancement suggestion: hope `brackets` will be able to add terminal console on inside the app

**Comment by nethip** [comment]
@KBPsystem777 I have created a backlog item for this in trello (https://trello.com/c/kJvyAeTY/1437-add-terminal-support-inside-brackets). Please upvote it.

**Comment by ficristo** [comment]
FWIW there are a couple of extensions which let you use a terminal:
https://github.com/artoale/brackets-terminal
https://github.com/ficristo/brackets-terminal-x
