### ISSUE TITLE
`onBeforeUnload` occurs on the Jasmine test runner too

### ISSUE THREAD

**Issue by petetnt** [adobe/brackets#13963]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

https://github.com/adobe/brackets/pull/13711 introduced `onbeforeunload` to prevent data loss. However this prompt also occurs while trying to change tabs / run tests with the Jasmine test runner.

### Steps to Reproduce

1. Run tests
2. Click anything

**Expected behavior:** [What you expected to happen]

Tests will run

**Actual behavior:** [What actually happened]

Prompt occurs

### Versions

Brackets master 13af302

**Comment by petetnt** [comment]
PR pending in #13964

**Comment by nethip** [comment]
I have merged the PR. Thanks @petetnt for the PR.
