### ISSUE TITLE
Problem of downloading qq video

### ISSUE THREAD

**Issue by palarewe** [adobe/brackets#13962]
I have tried to download a video of qq and an error was reported as below:
C:\Users\user_name>you-get --debug https://v.qq.com/x/cover/gvuzs7kkl79lza1/z00250yhf9z.htmlIt seems that your ffmpeg is a nightly build.Please switch to the latest stable if merging failed.[DEBUG] get_content: https://v.qq.com/x/cover/gvuzs7kkl79lza1/z00250yhf9z.html[DEBUG] get_content: http://vv.video.qq.com/getinfo?otype=json&appver=3.2.19.333&platform=11&defnpayver=1&vid=z00250yhf9zyou-get: version 0.4.985, a tiny downloader that scrapes the web.you-get: Namespace(URL=['https://v.qq.com/x/cover/gvuzs7kkl79lza1/z00250yhf9z.html'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, timeout=600, url=False, version=False)Traceback (most recent call last):  File "C:\Users\user_name\AppData\Local\Programs\Python\Python36\Scripts\you-get-script.py", line 11, in     load_entry_point('you-get==0.4.985', 'console_scripts', 'you-get')()  File "c:\users\user_name\appdata\local\programs\python\python36\lib\site-packages\you_get__main__.py", line 92, in main    main(*kwargs)  File "c:\users\user_name\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1576, in main    script_main(any_download, any_download_playlist, *kwargs)  File "c:\users\user_name\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1465, in script_main    *extra  File "c:\users\user_name\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1209, in download_main    download(url, *kwargs)  File "c:\users\user_name\appdata\local\programs\python\python36\lib\site-packages\you_get\common.py", line 1567, in any_download    m.download(url, **kwargs)  File "c:\users\user_name\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\qq.py", line 152, in qq_download    qq_download_by_vid(vid, title, output_dir, merge, info_only)  File "c:\users\user_name\appdata\local\programs\python\python36\lib\site-packages\you_get\extractors\qq.py", line 16, in qq_download_by_vid    fn_pre = video_json['vl']['vi'][0]['lnk']KeyError: 'vl'

**Comment by nethip** [comment]
@palarewe I am not sure if we can be of any help to you as this is Brackets forum, where we discuss around Brackets related issues.
