### ISSUE TITLE
JS default arguments cause Lint error

### ISSUE THREAD

**Issue by kentconf** [adobe/brackets#13979]
I've had Brackets for like a minute and I opened a js file with this function definition
function addChild(parent, child, after=-2)
and Lint doesn't recognise the syntax.

Also it gave me 51 errors for "space expected", "5 spaces expected but 4 found" and silly whitespace related things like that. Maybe I'll get used to it because I hope this code editor is very powerful.

**Comment by navch** [comment]
Thanks for bringing this up. You can configure these rules yourself. Please add a .eslintrc file at root level of your project. You can check rules at [eslint](https://eslint.org/docs/rules/). For sample file you can have a look [here](https://github.com/adobe/brackets/blob/master/.eslintrc.js). As default argument are introduces in ES6 so may be that is not enabled in you case. Please check in latest brackets. Default args are working perfectly fine for me.

**Comment by navch** [comment]
Closing this issue. Please feel free to reopen it, if you still have any issue related to this.
