### ISSUE TITLE
Autocomplete text

### ISSUE THREAD

**Issue by onewildgamer** [adobe/brackets#13985]
Hey, does Brackets support general autocomplete based on the file's text just like Notepad++? Or are there any extension that supports it?

**Comment by navch** [comment]
No, Brackets don't support general autocomplete from text. I think there is no extension on this. Where do you need this ? I mean are you writing plain text or some specific language ?

**Comment by onewildgamer** [comment]
We write plain text content a lot along with web design and development. We use brackets for everything. Except when I write content for products, websites I switch to notepad++

It'll be good to have this feature. Btw we all are in love with this editor. 😄

**Comment by navch** [comment]
Thank you so much @onewildgamer  👍 

As this is a web editor, that's why we don't have any extension for this till now. So closing this issue for now. We will update you if we get any such extension.
