### ISSUE TITLE
Dilato: I18N: The default app lauguage is English if install Brackes on local environment

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#13988]
Test build: 1.12.0-17538
Test environment: Debian 9.3.0; Ubuntu 17.10; Ubuntu 16.04.3

1. Install Brackets into the local linux system. (For Ubuntu system, install language package, change the system language and region and then install the Brackets)
2. Launch Brackets

Result: The Brackets' UI is English

Expect: The Brackets' UI keep consistent with the system language

![bracketsuidisplayinenglish](https://user-images.githubusercontent.com/17721679/34210696-c00f4216-e5d1-11e7-9ba8-22f477c2c3b7.jpg)

**Comment by nethip** [comment]
@ZuoBaogang Can you check and let us know if this is happening with 1.11 as well?

**Comment by ZuoBaogang** [comment]
Hi @nethip , I just checked this issue with 1.11
This issue doesn't reproduce
Test enveronment: Debian 9.3.0 64bit
Test build: 1.11.0-17524 download from: https://github.com/adobe/brackets/releases

**Comment by ZuoBaogang** [comment]
This issue also reproduce on Windows environment.
Test build: 1.12.0-17619
Test environment: Windows 8.1 fra; Windows 8,1 jpn; Windows 10 fra

**Comment by Zhanxin** [comment]
Have tried more, this issue not reproduce on build 1.12.0-17577. But start appears on build 1.12.0-17579.

**Comment by ZuoBaogang** [comment]
Verified this issue on build 1.12.0-17621-984. It fixed now. The default app language is the default system langage. 
Checked on linux, windows, mac environments
![1](https://user-images.githubusercontent.com/17721679/35716565-a930eeea-0814-11e8-89e5-c0196581f0ca.jpg)
![2](https://user-images.githubusercontent.com/17721679/35716566-aa1aa5c6-0814-11e8-80b8-1d556db816b4.jpg)
