### ISSUE TITLE
Could not find xdg-icon-resource

### ISSUE THREAD

**Issue by almessare** [adobe/brackets#14004]
hi guys i have this Problem can somebody help me ? 
sorry for my bad english& thank you 
<pre><font color="#CC0000"><b>root@Mohammad</b></font>:<font color="#3465A4"><b>~</b></font># dpkg -i Brackets.Release.1.11.64-bit.deb
<b>dpkg:</b> <font color="#CC0000"><b>error:</b></font> cannot access archive &apos;Brackets.Release.1.11.64-bit.deb&apos;: No such file or directory
<font color="#CC0000"><b>root@Mohammad</b></font>:<font color="#3465A4"><b>~</b></font># dpkg -i &apos;/root/Downloads/Brackets.Release.1.11.64-bit.deb&apos; 
(Reading database ... 340019 files and directories currently installed.)
Preparing to unpack .../Brackets.Release.1.11.64-bit.deb ...
Unpacking brackets (1.11.0-17525) over (1.11.0-17525) ...
Setting up brackets (1.11.0-17525) ...
xdg-icon-resource: size argument must be numeric
Try &apos;xdg-icon-resource --help&apos; for more information.
Processing triggers for menu (2.1.47+b1) ...
Processing triggers for hicolor-icon-theme (0.17-1) ...
<font color="#CC0000"><b>root@Mohammad</b></font>:<font color="#3465A4"><b>~</b></font># 
</pre>

**Comment by nethip** [comment]
@almessare Which version of Linux are you on? Are you able to launch Brackets in spite of the error above? After the installation, try typing `brackets` in the terminal and see if you are able to launch Brackets.

**Comment by parAndrei** [comment]
It's the same issue as [https://github.com/adobe/brackets/issues/13954](https://github.com/adobe/brackets/issues/13954) 

Here still at the same point too. Re-installed, launched from the console and indeed it launch but still no menus and still the same `xdg-icon-resource: size argument must be numeric` error on install. (Xubuntu 17.10 32bit)

With 2000+ Issues it take some courage to be into the maintainers team, so i'll maybe just switch to another editor and wait for 1.12 if the xdg-icon-resource issue falls under the radar. 

But still hope i'll find a way to be back in Brackets is just Great.

**Comment by markreznor** [comment]
i have the same problem bro someone can fix it? plz help

**Comment by ExpertSunny** [comment]
@markreznor Thank-you so much! It worked! I too had problem launching it in Kali Rolling.

**Comment by Christian1998** [comment]
If i use "brackets -i --no-sandbox" My settings dont get saved :( Anyone has a solution?

**Comment by singh-sumit** [comment]
root@kali:~/Downloads# dpkg -i Brackets.Release.1.14.64-bit.deb 
Selecting previously unselected package brackets.
(Reading database ... 398509 files and directories currently installed.)
Preparing to unpack Brackets.Release.1.14.64-bit.deb ...
Unpacking brackets (1.14.0-17740) ...
Setting up brackets (1.14.0-17740) ...
xdg-icon-resource: size argument must be numeric
Try 'xdg-icon-resource --help' for more information.
Processing triggers for menu (2.1.47+b1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...


what does this mean:xdg-icon-resource :size argument must be numeric
my brackets is not starting?

**Comment by maxirios** [comment]
i'm not an expert, just a curious person but...

there's a file called "postinst" on the /DEBIAN/ folder. It's the only file i found that has a XDG_ICON_RESOURCE thing:


 # Add icons to the system icons
XDG_ICON_RESOURCE="`which xdg-icon-resource 2> /dev/null`"
if [ ! -x "$XDG_ICON_RESOURCE" ]; then
  echo "Error: Could not find xdg-icon-resource" >&2
  exit 1
fi
for icon in "/opt/brackets/appshell"*.png; do
  size="${icon##*/appshell}"
  "$XDG_ICON_RESOURCE" install --novendor --size "${size%.png}" "$icon" "brackets"
done

(i can't write it between  **`** 's)
