### ISSUE TITLE
Can't move toolbar (has launcher, extension manager and other in it)

### ISSUE THREAD

**Issue by doncusack** [adobe/brackets#14006]
Figured it out. It was the Extension "Custom View" that created my problem.

The initial install of brackets worked fine. As I progressed through adding extensions, I noticed that the bar containing my live view and other icons had moved to the left bottom of the window. I have looked high and low for a way to put it back the way it originally was and have had no luck.
Any help would greatly be appreciated.
 I have attached a file showing what the current window looks like.

Expected the bar containing (live preview, extension manager, comment and beautify), work bar to be on the right side of the screen

Bar is showing up on left side bottom under file structures.

Brackets - Release 1.11 build 1.11.0-17524 (release 86b5e2d4e) 
build timestamp: Wed Sep 20 2017 03:34:28 GMT-0700

MacOS High Sierra
Version 10.13.2

![brackets_2018-01-01_16-41-02](https://user-images.githubusercontent.com/34890622/34471657-6fb9aae4-ef14-11e7-946f-847d43e721fb.jpg)

**Comment by boopeshmahendran** [comment]
@doncusack It seems you have figured out the reason for this issue. I am closing this issue now. Please feel free to reopen this issue if you face this issue again.
