### ISSUE TITLE
Results window does not suport UTF-8?

### ISSUE THREAD

**Issue by LudovicRousseau** [adobe/brackets#14002]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
Not tested. The problem was detected using the "Integrated Development for Brackets" plugin https://github.com/jadbox/brackets-integrated-development
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

In Brackets "Run Results" window I get the error:

```
, in
     print("voici voil\xe0")
UnicodeEncoreError: 'ascii' codec can't encode character '\xe0' in position 10: ordinal not in range(128)
```

### Steps to Reproduce

1. install "Integrated Development for Brackets" plugin https://github.com/jadbox/brackets-integrated-development
2. configure the plugin to use Python3 as described in https://github.com/jadbox/brackets-integrated-development/issues/1#issuecomment-172174051
3. create a Python program containing:
```python
#! /usr/bin/env python3

print("voici voilà")
```
4. Execute the program from Brackets

**Expected behavior:** 
The "Bracket Builder Extended" window should contain the output of the program execution.
```
voici voilà
```
**Actual behavior:**
I get an error instead:
```
, in
     print("voici voil\xe0")
UnicodeEncoreError: 'ascii' codec can't encode character '\xe0' in position 10: ordinal not in range(128)
```

### Versions

macOS High Sierra 10.32.2
Brackets Version 1.11 édition 1.11.0-17524 (release 86b5e2d4e)

### Possible bug fix

Define ``LANG=fr_FR.UTF-8`` before running Brackets.

At first I opened a bug on the "Integrated Development for Brackets" plugin at https://github.com/jadbox/brackets-integrated-development/issues/30. Then I tried to fix the problem and found the ``LANG=fr_FR.UTF-8`` solution so I think the issue is more with Brackets itself.

**Comment by petetnt** [comment]
Hi @LudovicRousseau,

not quite sure what the bug fix here should be 🤔 Unicode errors seem to be [quite common](https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20) with Python (without LANG being set at least), but not sure we'd want to define something like `LANG=en_US.utf8` before launching as it might screw up settings from those who do not default to such encoding.

Maybe the simplest way of handling this would be documenting the behavior to the `brackets-integrated-development` README.

**Comment by LudovicRousseau** [comment]
I also don't think the problem should be fixed in Brackets.
The plugin should define LANG to a "correct" value before launching Python.

Feel free to close this issue.

**Comment by petetnt** [comment]
👍
