### ISSUE TITLE
Product.cab file is corrupted

### ISSUE THREAD

**Issue by awaissaeed53** [adobe/brackets#14016]
When trying to install Brackets 1.11 on windows 10 I get an error
"The cabinet file product.cab is corrupted and cannot be used. This may due to network error or CD/DVD rom error."

**Comment by petetnt** [comment]
Hi @awaissaeed53,

that sounds weird. Did you try redownloading the installer?

**Comment by awaissaeed53** [comment]
That worked. Thanks

**Comment by petetnt** [comment]
Awesome!
