### ISSUE TITLE
Nice but have big problem>

### ISSUE THREAD

**Issue by hamzakhuswan** [adobe/brackets#14021]
This app is so slow and you open another app and put it in the background make it does not continue, it stop and reload again and take 999 years. 
Can you please fix that

**Comment by glenndevenish** [comment]
Sounds like a computer issue rather than a program issue.

**Comment by petetnt** [comment]
Hey @hamzakhuswan,

can you share your Help -> Health Report? Otherwise there's not much we can do.

**Comment by hamzakhuswan** [comment]
Could you please delete this issue? Because it's not a software issue, the computer was faulty.
