### ISSUE TITLE
LB:[fr_FR] Translation change needed for "Select valid code to wrap in a Try-catch block" and "Wrap in Try Catch"

### ISSUE THREAD

**Issue by tiwariaman55** [adobe/brackets#14024]
Steps:
1. Launch Brackets
2. New a .js file and input below code:
"try {
try_statements
}"
3. Select all the text and click Edit -> Wrap in Try-catch

Source: Select valid code to wrap in a Try-catch block
Current FR: Sélectionner un code valide à envelopper dans un bloc Try/Catch
Expected FR: Sélectionner un code valide à encapsuler dans un bloc Try/Catch

EN Screen:

![1514894915731errorwraptrycatch](https://user-images.githubusercontent.com/29482313/34771161-9a75fc3a-f629-11e7-9e05-b5037bc51565.png)

FR Screen:

![1515579575982fra_1514894915731errorwraptrycatch](https://user-images.githubusercontent.com/29482313/34771169-a3220b62-f629-11e7-80c5-693acc944e34.jpg)

Steps:
1. Launch Brackets
2. Click Edit

Source: Wrap in Try catch
Current FR: Envelopper dans Try/Catch
Expected FR: Encapsuler dans Try/Catch

EN Screen:
![1514885309318cmd](https://user-images.githubusercontent.com/2284774/34779532-c60d8f38-f620-11e7-85ea-11d2050d4927.png)

FR Screen:
![1514885309318cmd_fr](https://user-images.githubusercontent.com/2284774/34779543-d0c19262-f620-11e7-926c-0c5d51615990.png)

**Comment by rj-adobe** [comment]
This is fixed in build 967.

**Comment by ZuoBaogang** [comment]
Upload the screenshots with build 1.12.0-17611, please help to verify.
cc @tiwariaman55 

![14024_01](https://user-images.githubusercontent.com/17721679/35040776-5ee8ba42-fbbd-11e7-901f-d1f2b2864f98.jpg)
![14024_02](https://user-images.githubusercontent.com/17721679/35040777-60f509a8-fbbd-11e7-8604-964f3fa77335.jpg)

**Comment by Tania-Jiacomini** [comment]
fr_FR strings are fixed, thanks

**Comment by tiwariaman55** [comment]
Closing the bug as fixed.
