### ISSUE TITLE
LB:[fr_FR] Translation change needed for "Create Getters Setters"

### ISSUE THREAD

**Issue by tiwariaman55** [adobe/brackets#14023]
Steps:

1. Launch Brackets
2. Click Edit

Actual Translation: Créer des accesseurs (getters) et mutateurs (setters)
Expected Translation: Créer des getters/setters

EN:

![1514885309318cmd](https://user-images.githubusercontent.com/29482313/34770711-e4d95d1e-f627-11e7-9a1a-af11dc4f8db0.png)

FR:

![1514885309318cmd_fr](https://user-images.githubusercontent.com/29482313/34770724-ee7dd322-f627-11e7-8874-05d660b6bb8a.png)

**Comment by rj-adobe** [comment]
This is fixed in the build 967.

**Comment by ZuoBaogang** [comment]
Upload the screenshots with build 1.12.0-17611, please help to verify.
cc @tiwariaman55 

![14023](https://user-images.githubusercontent.com/17721679/35040788-6c364ade-fbbd-11e7-9bad-dc1a50ea8826.jpg)

**Comment by tiwariaman55** [comment]
Closing the bug as fixed.
