### ISSUE TITLE
Dilato: I18N: Some error messages are not localized when use "Rename" for JS code

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14025]
Test build: 1.12.0-17584

Scenario 1.
1. Launch Brackets
2. Create a JS file
3. Input the string under below (inloude the quotation marks)
"aaa"
4. Right click the string then click "Rename"

Result: The string "Not at a variable or property name." is not localized

Scenario 2.
1. Launch Brackets
2. Create a JS file
3. Input the string under blow
var
4. Right click the string then click "Reanme"

Result: The string "No expression at the given position." is not localized

Scenario 3.
1. Launch Brackets
2. Create a JS file
3. Input the string under blow
aaaaaa
4. Right click the string then click "Reanme"

Result: The string "Could not find a definition for aaaaaa" is not localized

Screenshot for Scenario1
![not at a variable or property name](https://user-images.githubusercontent.com/17721679/34770988-ea299444-f63d-11e7-86d1-ee2506966478.jpg)

Screenshot for Scenario2
![no expression at the given position](https://user-images.githubusercontent.com/17721679/34771003-f5a4a64c-f63d-11e7-9dd6-6600bed0a918.jpg)

Screenshot for Scenario3
![could not find a definition for](https://user-images.githubusercontent.com/17721679/34771011-ff6482f6-f63d-11e7-9f45-9bdbe0d24515.jpg)

**Comment by navch** [comment]
These errors are directly thrown from TernJs. We are not adding these strings. So We can't localize this.
