### ISSUE TITLE
LB: [fr_FR] Translation change needed for "Select valid code to wrap in a Condition block" and "Wrap in Condition"

### ISSUE THREAD

**Issue by Tania-Jiacomini** [adobe/brackets#14026]
Steps:

Launch Brackets
New a .js file and input below code:
"try {
try_statements
}"
Select all the text and click Edit -> Wrap in Condition

Source: Select valid code to wrap in a Condition block
Current FR: Sélectionner un code valide à envelopper dans un bloc Condition
Expected FR: Sélectionner un code valide à encapsuler dans un bloc Condition

EN Screen:
![1514894857418errorwrapcondition](https://user-images.githubusercontent.com/2284774/34779199-c4503a2a-f61f-11e7-9c01-4d0d0f274e3a.png)

FR Screen:
![1515579633963fra_1514894857418errorwrapcondition](https://user-images.githubusercontent.com/2284774/34779216-cba3382c-f61f-11e7-9e77-f7d1b1571964.jpg)

Source: Wrap in Condition
Current FR: Envelopper dans Condition
Expected FR: Encapsuler dans Condition

EN Screen:
![1514885309318cmd](https://user-images.githubusercontent.com/2284774/34779653-242944ea-f621-11e7-8ab8-a013fc441b23.png)

FR Screen:
![1514885309318cmd_fr](https://user-images.githubusercontent.com/2284774/34779663-29f6c582-f621-11e7-8212-35f2603ac3a5.png)

**Comment by ZuoBaogang** [comment]
Upload the screenshots with build 1.12.0-17611, please help to verify.
cc @tiwariaman55 

![14026_01](https://user-images.githubusercontent.com/17721679/35040751-48581462-fbbd-11e7-9d33-c99544175c1a.jpg)
![14026_02](https://user-images.githubusercontent.com/17721679/35040753-49e51604-fbbd-11e7-8ef8-3826a361338f.jpg)

**Comment by Tania-Jiacomini** [comment]
fr_FR strings are fixed, thanks

**Comment by tiwariaman55** [comment]
Closing the bug as fixed.
