### ISSUE TITLE
Dilato: Core: There is no code created or warning message when use Try Catch/Condition in an blank area outside the method

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14029]
Test build: 1.12.0-17584
1. Launch brackets
2. Create a JS/C#/Java file
3. Write two funciton/method
4. Using "Try Catch/Condition" in an blank area outside the method

Result: No warning message or code created

Expect: 
Try Catch/Condition code is created or a waring message appears

![issue](https://user-images.githubusercontent.com/17721679/34820216-d85f6a64-f6fa-11e7-8310-b13463cfa53f.gif)

**Comment by navch** [comment]
Fixed in PR https://github.com/adobe/brackets/pull/14019

**Comment by ZuoBaogang** [comment]
Verify this issue on build 1.12.0-17613-971. Fixed
![14029_build_1 12 0-17613-971](https://user-images.githubusercontent.com/17721679/35088510-036e9972-fc6f-11e7-9e7e-37c3d851cd0c.gif)
