### ISSUE TITLE
Javascript showing non-errors as errors.

### ISSUE THREAD

**Issue by ntpotus** [adobe/brackets#14038]
### Prerequisites

* [ yes ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ yes ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ yes ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

When you type up javascript, Brackets goes bonkers with errors that simply _aren't_ errors.

For example:
Expected 'document' at column 9, not column 13.

This makes me think: Who the *expletive* are you to try and FORCE your coding styling on me!?  It works if I have it at column 1 as well as if at column 9.  This is **_NOT_** and error.  It's simply the way I want to tab my project.  The red circle X is not appreciated for something that is nothing more than cosmetic in the way I write my code.  Same goes for the words error and warning.  The authors of this program need to keep their ideas of properly (aesthetic-only) coded javascript to themselves or give me a button to press to turn your thoughts on the matter off easily.

Another example:
X="this"

This is obviously not real code but it would work just as well as

X = "this"

But I personally find the first one to be more readable and less messy.  The white spaces here, again, are the aesthetic thoughts of the coders of the javascript section of Brackets and has absolutely NO bearing on how my code preforms.  It's annoying that you want to try and force me to do it your way when my way not only works but is more readable to me and easier to understand.  Again, for this, your red circled X is not appreciated and takes away from my ability to code.  Please either completely remove it and keep you ideas of best coding practices to yourself, or give me a way to turn it off myself.

Just stop being an annoying nanny for my coding.  If I want to code in a hot mess, then I should be able to.  What's next?  Is Brackets going to start REQUIRING me to comment my code or else a blue box will ugly up the space beside the line numbers causing a huge distraction to me simply because you believe that this line needs a comment?

BUGGER OFF with this annoying crap!  If it's a REAL error that will cause my code to NOT function then this functionality is completely welcome.  But since it's mostly just the way YOU LOT simply THINK it's the way I SHOULD be coding it, bugger off.

**UPDATE:** I just noticed that `Right Click->Auto-fix with ESLint` does nothing.

SO!  Brackets sets the tabbing to a default setting (which I like and makes tabbing easier after the fact) but then it complains that the tabbing (that it set itself) is wrong.  Then, when you try to use the option to fix the problem that isn't really a problem, it does absolutely nothing.  Wonderful.  Turn it off or give me a way to do it.  Little button at the bottom with the other quick option to turn off nanny coding.

### Steps to Reproduce

1. Code anything in Javascript that is correct but isn't on the proper column or doesn't have what Brackets considers required whitespace.
2. Save that file.
3. Watch in awe as Brackets complains about "errors" and "warnings" that are only SUGGESTIONS of proper coding.
4. Complain to Brackets about this until they change it because it annoying to be told how someone else thinks you should be writing your code.

**Expected behavior:**

I expect Brackets to accept whatever coding style I want to use and only complain at me when there is an ACTUAL error or something that I need to be warned about.  The amount of spaces or tabs isn't it.

By the way:  If I have my tabs or spaces set to say 4, why does this deserve a warning with the big red circle X?  **Let me remind you that if you let Brackets do the tabbing itself, this is where it puts it all by default.  So this is how Brackets says it SHOULD be tabbed, but then it warns you that it isn't tabbed properly.**  What!?  Why!?  Just GO AWAY!  [Or at LEAST become more consistent.]

```
function thisFunction(value) {
    switch (value) {
        case 'thisValue':
            document.getElementById("thisElement").style.height="168px";
```

Warnings output:

Missing 'use strict' statement.  (I don't want to use this.  Why can't I turn off its annoying red circle X!?)
Expected 'case' at column 5, not column 9.
Expected 'document' at column 9, not column 13.
Missing space between 'height' and '='.  (spaces not required for proper functionality)
Missing space between '=' and '168px'.  (spaces not required for proper functionality)

**Actual behavior:**

Brackets currently does this:

Little baby:
WHHAAAA!  You wrote that without the correct number of tabs or spaces that I require!  I'm going to "complain" and moan until you code the way I say you ought to!

Strict Old Nun (with a ruler):
TAB THAT LINE, YOUNG MAN or ELSE!

### Versions

macOS Sierra 10.12.4
Brackets Release 1.11 build 1.11.0-17524 (release 86b5e2d4e)

**Comment by kiroma** [comment]
I understand that while dealing with an issue a person can get mad, however pouring that frustration into an issue report isn't the best idea, as it makes the report quite difficult to read and understand.
What I see here is an issue with one of the linters. Those are external automatic modules, which if I recall are customizable to suit one's coding style.

**Comment by petetnt** [comment]
Hi @ntpotus,

sorry that the built-in ESLint linter frustrated you. If you find the linter non-productive, you can turn it off my settings the `"linting.enabled": true,` to `false` in Debug -> Open Preferences File -> `brackets.json`.
