### ISSUE TITLE
LB:[ja_JP] Translation change needed for "Selection does not form an expression"

### ISSUE THREAD

**Issue by tiwariaman55** [adobe/brackets#14041]
Steps:

1. Launch Brackets
2. Create a new JS file
3. Copy paste the strings as below
function a(){}
function b(){}
4. Select all strings
5. Right click the selected strings
6. Select Refactor then click Extract to Variable

**EN Source:** Selection does not form an expression

**Actual Translation:** 選択内容で式が形成されません
**Expected Translation:** 選択内容は式になっていません

EN:

![mock-id_pr](https://user-images.githubusercontent.com/29482313/35035057-223ae722-fb96-11e7-8c75-b3c12217f15f.jpg)

JP:

![pr](https://user-images.githubusercontent.com/29482313/35035070-2bc95616-fb96-11e7-8bb2-c9496c351234.jpg)

**Comment by ZuoBaogang** [comment]
Upload the screenshot with build 1.12.0-17613-971, please help to verify.
cc @tiwariaman55

![ja_jp](https://user-images.githubusercontent.com/17721679/35092399-332dc75e-fc7a-11e7-92b2-5bc12c1525ef.jpg)

**Comment by tiwariaman55** [comment]
Closing the bug as fixed.
