### ISSUE TITLE
Dilato: Core: Some functions in Refactor has no response after restart node

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14043]
Test build: 1.12.0-17611-968

1. Launch Brackets
2. Open a js file
3. Use the functions "Rename", "Extract to Variable", "Extract to Funcation" --- These funcations works well
4. Click Debug -> Restart Node
5. Try to use the functions "Rename", "Extract to Variable", "Extract to Funcation"

Result:  functions: "Rename", "Extract to Variable", "Extract to Funcation" has no response after restart node

Expect: These three functions work well. please help to check if this is designed.

![issue](https://user-images.githubusercontent.com/17721679/35047380-b449b858-fbd4-11e7-9ef1-65ddc8ae4c44.gif)

**Comment by navch** [comment]
After restarting the node, once you will start editing. Tern server will restarted on editor change. It just takes few extra seconds to do refactoring job. We can make it fast but that may introduce some unknown issues in JS hints or in node memory issues. So We are not fixing this issue as of now.
