### ISSUE TITLE
Dilato: Core: The rename function doesn't work from the second time

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14053]
Testing build: 1.12.0-17613-971
1. Launch Brackets
2. Open a JS file
3. Try to Rename a function name use Refactor -> Reanme
4. Change the function name
5. Repeat the step 3 again

Result: The rename function doesn't work

Expect: The Refactor -> Reanme function works well or give an error message

![issue](https://user-images.githubusercontent.com/17721679/35150831-e134b1e6-fd56-11e7-867d-3240a8d70493.gif)

**Comment by ZuoBaogang** [comment]
Verified this issue on build 1.12.0-17621-984, fixed
![14053_fixed](https://user-images.githubusercontent.com/17721679/35681443-62f0d868-0798-11e8-9e7d-0d6b2dbdcd41.gif)

**Comment by nethip** [comment]
@navch Can you have a look at this?
