### ISSUE TITLE
Sound of coin everytime I code

### ISSUE THREAD

**Issue by Harry71997** [adobe/brackets#14064]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

Is there anyone who would like to help my silly issue?The problem is I'm hearing the sound of coin everytime I code.It won't stop until I stopped.I know it might be the one from extension manager wihich I've installed but I couldn't manage to find one. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by petetnt** [comment]
Hi @Harry71997,

sadly there's not much to do except disabling the extensions one by one to find the culprit and removing it

**Comment by Harry71997** [comment]
@petetnt It worked!Thank you so much and I appreciate your concerns and suggestions!I have no idea why didn't I think like that sooner.Silly me!
