### ISSUE TITLE
Feature request: Syntax highlighting for Batch files

### ISSUE THREAD

**Issue by Yolo-Jerome** [adobe/brackets#14082]
Brackets is awesome and I use it for a lot of file types mainly because of its multiline edditing, syntax highlighting and customizability by Plug-Ins.

Unfortunately one for me important file type is missing: Batch scripts (.bat)

Would be great if there was a syntax highlighting also for those.

**Comment by nethip** [comment]
@Yolo-Jerome We usually prioritize features based on community feedback from our trello board [here](https://trello.com/c/N043d0x0/1438-support-for-batch-files-in-brackets). Please upvote this card.

**Comment by Yolo-Jerome** [comment]
Did so, thank you very much!
