### ISSUE TITLE
Dilato: Core: Windows Only: After upgrade the build to the latest 1.12 build from the defective 1.12 build, the default language is English and two brackets icon in uninstall program panel

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#14086]
Steps
1. Install 1.12 build (containing the OS language bug). Launch Brackets, app language is English.
2. Install latest 1.12 build (containing the fix).

Result:
1) Launching Brackets still launches it in English.
2) There are two brackets icon on uninstall program panel

Expected:
1.) Launch in Local language
2.) Only one brackets icon on uninstall program panel
![twobracketsicon](https://user-images.githubusercontent.com/2245179/35719857-419c4ae2-0826-11e8-95da-7174056cc73f.png)

**Comment by vahid-sanati** [comment]
why not just uninstall the buggy version and install fixed version?

**Comment by nethip** [comment]
This is fixed now!
