### ISSUE TITLE
Can't get rid of Getting Started folder

### ISSUE THREAD

**Issue by jlaskowski** [adobe/brackets#14113]
This topic had been handled before, but the topic was closed unless your a contributor.  I'm just here to give my reason for installing Brackets one minute and uninstalling it the next.  I don't like that there's always a "project" open, as so many others have expressed.  If I can't work on a file or a couple files without having an open folder or project, I have no interest in continuing with Brackets.

**Comment by petetnt** [comment]
Sorry about that @jlaskowski, most / many of Brackets functionalities are built around the concept of root folders and that behaviour is unlikely to change any time soon. Alternatives like VSCode or Atom work similarly, but might fit better for your use-case or you could try something simpler like Notepad++ on Windows.

Thanks for using Brackets anyway 🙏

**Comment by jlaskowski** [comment]
I am not using it.
