### ISSUE TITLE
Brackets suddenly started writing in Greek

### ISSUE THREAD

**Issue by thinnling** [adobe/brackets#14119]
All of a sudden as I was typing the English letters turned to Greek alphabet.  I must have hit some keys together that changed it to Greek and after trying out different combinations it is still in Greek.  I'm a sloppy typer.
--Release 1.12 build 1.12.0-17621
--Win 7
--I already restarted without extensions

How can I change it back?

**Comment by Shieke** [comment]
The language settings are in Debug > Switch Languages. Have you tried that?

**Comment by thinnling** [comment]
I just started Brackets again today and now it is fine.  Yesterday, when I went to  Debug > Switch Language it was set to System Default, then I changed it to English (US) and restarted, but it was still coming up in Greek.  Today, though, it is back to English.  I ended up just downloading Sublime Text 3 so I'm gonna try that one out for a bit.  But I think I still like Brackets better.  Thanks for the reply.
