### ISSUE TITLE
Image Preview for Large Images Freezes Application

### ISSUE THREAD

**Issue by Bolpat** [adobe/brackets#14117]
### Prerequisites

* [x] I can reproduce the problem with `Debug -> Reload Without Extensions` on a fresh installation on a new computer.
* [x] I did perform a cursory search to see if your bug or enhancement is already reported.
* [x] I did read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting).

### Description

When refering to a large image, in particular, exactly when one dimension has at least 4096 pixels, in e.g. an `img` tag, hovering on the link to that image makes the program freeze. The only way to abort Brackets (on Windows) is killing it with Task Manager. Unsaved changes are lost.

### Steps to Reproduce

1. Install Brackets on a fresh (Windows) computer.
2. Open Brackets and create a new file (like the default `index.html`).
3. Enter a simple HTML snippet with `img` referring to an image larger than 4096 pixels in height or width; e.g.
```html
<!DOCTYPE html>
<html>
<body>
  <img src="large_image.jpg">
</body>
</html>
```
4. Hover on `large_image.jpg`.

**Expected behavior:** An image preview as for small images, or at least a message that the image is too large for preview.

**Actual behavior:** Program freezes.

### Versions

OS: Windows 7 and Windows 10, both 64-bit 
Brackets version: Release 1.12 Build 1.12.0-17621 (release d3b783b99)

**Comment by jhelfgot1** [comment]
I was not able to reproduce this bug with a 1.57 MB image w/ dimensions 4288 X 2844 pixels running Brackets Release 1.11 or Brackets Release 1.12. I also tried previewing a much larger image that was 14.94 MB w/ dimensions 10800 x 5400 pixels and still had no problems.

### Versions

OS: 
OSX El Capitan 10.11.6

Brackets Versions: 
Release 1.11 build 1.11.0-17524 (release 86b5e2d4e) 
Release 1.12 build 1.12.0-17621 (release d3b783b99)

**Comment by Bolpat** [comment]
My brother, the one actually using the application, just told me, in the latest version the bug is not present anymore. Closing.
