### ISSUE TITLE
Cannot type some characters with German keyboard layout

### ISSUE THREAD

**Issue by boldt** [adobe/brackets#14111]
### Description

My issue is quite simple: I cannot type the following characters (German keyboard layout):

* `^` (roof character)
* `` ` `` (backtick character)
* `` ´ `` (tick character)

[EDIT:] By switsching to the "English (USA)" keyboard, I can type the roof and the backtick.

### Versions

Please include the OS and what version of the OS you're running:

* Ubuntu 14.04.5 LTS

Please include the version of Brackets:

* Release: 1.11

**Comment by nethip** [comment]
This is fixed in Brackets 1.12. Can you give the latest version a spin?

**Comment by boldt** [comment]
Thanks for the pointer. I installed the release 1.12 and it works again. Just also this comment on the [releases page](https://github.com/adobe/brackets/releases):

> [05-02-2018] This newer build of Brackets 1.12 includes fix for an issue, specific to non-English locales, present in the previously released build. The issue prevented users from loading Brackets in a non-English language of their choice.

Thank you!
