### ISSUE TITLE
[Brackets auto-update Windows] Install time for 1.13 is more as compared to 1.12 (Upgrade Scenario)

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14127]
### Description
Install time for 1.13 is more as compared to 1.12.

### Steps to Reproduce
1. Install brackets 1.12.
2. now install 1.13 on top of 1.12 (Upgrade scenario).
3. install time is 4 min 10 sec.

**Expected behavior:** Install time should be low.

**Actual behavior:** Install time is more.

### Versions
Windows 10 64 Bit
Release 1.13 build 1.13.0-17624

**Comment by mbhavi** [comment]
Please validate this with the latest changes and builds. Also, this issue should be assigned to RE as it is an installer change. @ayushrathi15 Please assign accordingly.

**Comment by ayushrathi15** [comment]
Verified on build Release 1.13 prerelease build 1.13.0-17689.
The time to upgrade was 3 min 27 sec.
Closing the issue.
