### ISSUE TITLE
Help for first pull request

### ISSUE THREAD

**Issue by pelatx** [adobe/brackets#14121]
Hi.

I have working properly, in a branch derived from "linux-1547" branch of Brackets-shell, the native menus with checked items in Linux (#13606, #13685).

I have been reading the documentation on how to contribute to Brackets, but I have a question:

After signing the CLA, should I create a branch of Brackets-shell "master" and make the changes there? Or should I create the branch derived from "linux-1547"? 

Maybe it's an obvious question, but I'm pretty new at contributing to such large projects.

Thank you.

**Comment by petetnt** [comment]
Hi @pelatx,

first of all, thanks for contributing!

While I am not completely up to speed with the current state of the said branch, master got big [linux updates](https://github.com/adobe/brackets-shell/pull/619) a while back so I think it should be safe to target the PR against the master

**Comment by pelatx** [comment]
Thanks @petetnt.

**Comment by petetnt** [comment]
Closing this as answered, do message back if there's more questions!
