### ISSUE TITLE
[Brackets auto-update Windows] Once user clicks on Update Now button, brackets closes immediately. 

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14129]
### Description
Once user clicks on Update Now button, brackets closes immediately. 

### Steps to Reproduce
1. Launch brackets 1.13.
2. Go to help > Check for updates.
3. Update dialogue appears. Click on Get it now.
4. Click on Update Now.
5. Once user clicks on Update Now button, brackets closes immediately. 

**Expected behavior:** Once user clicks on Update Now button, brackets closes immediately. Instead, it could give a fading notification stating "Brackets will now close" and then close the brackets.

**Actual behavior:** Once user clicks on Update Now button, brackets closes immediately. 

### Versions
Windows 10 64 Bit
Release 1.13 build 1.13.0-17624

**Comment by mbhavi** [comment]
With the new UI, the buttons read "Restart" and "Later", which is self-sufficient, and hence, there is no need for the proposed change anymore. Please close this issue.

**Comment by ayushrathi15** [comment]
Verified as per new UI. Hence closing the issue.
