### ISSUE TITLE
[Brackets auto-update Windows] Once the product is installed, the finish dialogue does not comes up.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14128]
### Description
Once the product is installed, the finish dialogue does not comes up.

### Steps to Reproduce
1. Run brackets installer for 1.13.
2. Once the installation is complete, installer dialogue disappears. There is no finish dialogue.

**Expected behavior:** Finish dialogue should come once the installation is done.

**Actual behavior:** Once the product is installed, the finish dialogue does not comes up.

### Versions
Windows 10 64 Bit
Release 1.13 build 1.13.0-17624

**Comment by Shieke** [comment]
I noticed when I installed Brackets a couple weeks ago that the finish dialogue did come up, but it was nearly pushed off of the left side of my screen. Perhaps it is a positioning issue? I am unsure if that is helpful to you while testing. I am also running the Windows 64-bit 1.13 release.

**Comment by ayushrathi15** [comment]
@Shieke I guess you are running brackets 1.12.
Could you please confirm ?

**Comment by mbhavi** [comment]
Please validate this with the latest changes and builds. Also, this issue should be assigned to RE as it is an installer change. @ayushrathi15 Please assign accordingly.

**Comment by gavankar** [comment]
@ayushrathi15 I'm unable to repro this in 1.13.0-17665, which is the latest autoupdate build.
Could you please check this build?

**Comment by ayushrathi15** [comment]
Verified on Build 1.13.0-17674.
