### ISSUE TITLE
[Brackets auto-update Windows] No message is given to user if user clicks on Cancel in Save As dialogue.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14131]
### Description
No message is given to user if user clicks on Cancel in Save As dialogue.

### Steps to Reproduce
1. Launch brackets 1.13.
2. Create a new file and type some text. Do not save this file.
3. Go to help > Check for updates.
4. Update dialogue appears. Click on Get it now.
5. Click on Update Now.
6. Save Changes dialogue will appear.
7. Click on Save button. Save As dialogue appears.
7. Click on cancel. No message is given to user.

**Expected behavior:** A message "Brackets could not be updated" should be given to user if user clicks on Cancel in Save As dialogue.

**Actual behavior:** No message is given to user if user clicks on Cancel in Save As dialogue.

### Versions
Windows 10 64 Bit
Release 1.13 build 1.13.0-17624

**Comment by mbhavi** [comment]
This issue has been fixed in the latest builds. Please validate. @ayushrathi15

**Comment by ayushrathi15** [comment]
Verified on build 1.13.0-17666.
