### ISSUE TITLE
[Brackets auto-update Windows] Update Now button does not work, if user clicks on Cancel in Save Changes dialogue.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14130]
### Description
Update Now button does not work, if user clicks on Cancel in Save Changes dialogue.

### Steps to Reproduce
1. Launch brackets 1.13.
2. Create a new file and type some text. Do not save this file.
3. Go to help > Check for updates.
4. Update dialogue appears. Click on Get it now.
5. Click on Update Now.
6. Save Changes dialogue will appear.
7. Click on cancel. Update failed notification comes up.
8. After this, Update is ready dialogue can be still seen. Click on Update Now button does not work.
9. Update Now button does not work.

**Expected behavior:** Update Now button should work, even if user clicks on Cancel in Save Changes dialogue.

**Actual behavior:** Update Now button does not work, if user clicks on Cancel in Save Changes dialogue.

### Versions
Windows 10 64 Bit
Release 1.13 build 1.13.0-17624

**Comment by mbhavi** [comment]
With the new UI in place now for AutoUpdate, this issue is no longer seen. Please validate in the latest builds @ayushrathi15

**Comment by ayushrathi15** [comment]
Verified on build 1.13.0-17666.
