### ISSUE TITLE
[Brackets auto-update Windows] A message should be given to user to close all the instances of brackets so as to begin updating brackets.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14133]
### Description
A message should be given to user to close all the instances of brackets so as to begin updating brackets.

### Steps to Reproduce
1. Run multiple instances of brackets.
2. Go to help > Check for updates.
3. Update dialogue appears. Click on Get it now.
4. Click on Update Now.
5. Only the current instance of brackets gets closed.

**Expected behavior:** A message should be given to user stating "Close all the instances of Brackets to begin updating Brackets".

**Actual behavior:** Only one instance of brackets closes. Other all instances are running and no message is given to user.

### Versions
Windows 10 64 Bit
Release 1.13 build 1.13.0-17624

**Comment by mbhavi** [comment]
Installer does that for us on Windows already. It prompts the user if multiple instances of the app are running, and asks the user to close the other instances.
As per discussion with PDM, this need not be addressed, and hence, can be deferred/closed.

**Comment by ayushrathi15** [comment]
This is as designed.
Closing the issue.
