### ISSUE TITLE
can i change some preferences?

### ISSUE THREAD

**Issue by pbbob1** [adobe/brackets#14144]
I would expect to see some sort of preferences menu, like file --> preferences where i can change some simple preferences. I find it frustrating that some very simple things, like changing the default autocomplete quotes from `"` tp `'`, changing color codes(ie make all html elements green instead of blue), or even turn off auto  indent. As a text editor that is made for editing code, brackets REALLY should have at least some very basic user-changable preferences.

**Comment by redmunds** [comment]
Have you tried _Debug > Open Preferences File_ ?

**Comment by navch** [comment]
You can change Preference in brackets.json file(Debug-> Open Preference File). All prefs are not listed in this file. But If you will add any preference to this file, then it will work. I am not sure if there is any wiki on all preferences. For example: for auto complete quotes, you can add preference ["autoCloseBrackets":  false] in brackets.json. Please close this issue if you got answer. You can changes themes in View -> themes

**Comment by redmunds** [comment]
Preferences wiki is here: https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences
