### ISSUE TITLE
 Brackets 1.12  stoped working on macOS High Sierra.

### ISSUE THREAD

**Issue by OctoberBloom** [adobe/brackets#14147]
Hello, I have a problem with Brackets 1.12 on macOS High Sierra. 
It just stopped working. I did't do any updates and did't install new applications. I have a gray screen and the menu responds only to closing and minimizing the window. I was trying to remove the new version of the old version, clean up the cache and even updated the OS again. Still not working.
I tried to fixed it with https://github.com/adobe/brackets/wiki/Troubleshooting#launching.
Please, help.
P.S. I also sent email to admin.

![bin1](https://user-images.githubusercontent.com/37118881/37053428-d1f31180-2184-11e8-85d0-0edc3e35c45e.jpeg)
![bin2](https://user-images.githubusercontent.com/37118881/37053429-d2168c3c-2184-11e8-8725-1d802be8416d.jpeg)
![brackets terminal](https://user-images.githubusercontent.com/37118881/37053430-d2373a18-2184-11e8-8518-8ceb76ec684c.jpeg)

**Comment by nethip** [comment]
@OctoberBloom Can you try renaming the Brackets preferences (don't delete the preferences folder yet) and start Brackets to see if you are still seeing the issue. Brackets preferences folder is located at `~/Library/Application Support/` on Mac. 

Also are you seeing this error when launching from `Finder`?

**Comment by OctoberBloom** [comment]
Thank you! It works again!

**Comment by petetnt** [comment]
Glad you got it working! Closing as solved 👍
