### ISSUE TITLE
Safari used for Live Preview instead of Chrome browser on Mac OSX 10.11.6

### ISSUE THREAD

**Issue by oligraph** [adobe/brackets#14146]
### Prerequisites

* [ x ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ x ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ x ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description
Safari is being used for Live Preview instead of Chrome browser on Mac OSX 10.11.6 in latest version of Brackets on two different Macs. Starting Chrome beforehand does still invoke Safari.
[Description of the bug or feature]

### Steps to Reproduce

1. [Start Brackets]
2. [Open html document]
3. [click Arrow icon for Live Preview]

**Expected behavior:** [Chrome Browser should have started up]

**Actual behavior:** [Safari Browser starts up]

### Versions

Please include the OS and what version of the OS you're running.
–> 10.11.6
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)
–> Release 1.12 Build 1.12.0-17621 (release d3b783b99)

**Comment by sobisht** [comment]
@oligraph Check whether File-> Enable Experimental Live Preview is enabled. If this option is enabled and your default browser is Safari, then preview will get launched in Safari only.

**Comment by oligraph** [comment]
Thank you, sobisht,

your hint did the trick. But only after a restart of the Mac, not only Brackets.
