### ISSUE TITLE
Links working in Live Development but not standalone [Fixed]

### ISSUE THREAD

**Issue by mommaleo** [adobe/brackets#14155]
###Description:

When previewing my html files in Live Development, links to css work just fine, but when trying to open the html files directly with Chrome, there are no css modifications.

###Steps to Reproduce:

1. Linked `style.css` as `"/css/style.css"` in folder open in Brackets.

**Expected behavior:** css would modify webpage as usual.

**Actual behavior:** css did not modify the webpage.

### Versions

Brackets: `1.12.0-17621 (release d3b783b99)`
macOS: `10.13.3`

Screenshots:
The `<head>` link: 
![bracketsissue01](https://user-images.githubusercontent.com/23516137/37250922-b191666e-24bb-11e8-8836-ca864bbf61f7.png)
The file tree: 
![bracketsissue02](https://user-images.githubusercontent.com/23516137/37250923-b1b1d408-24bb-11e8-90fe-7eca9e45b131.png)
The webpage in Live Development: 
![bracketsissue03](https://user-images.githubusercontent.com/23516137/37250924-b1d0c2f0-24bb-11e8-84b4-b5efaca0d38c.png)
The webpage when opened in Chrome: 
![bracketsissue04](https://user-images.githubusercontent.com/23516137/37250925-b1f5dfea-24bb-11e8-8fd2-87ac97c8b6a9.png)

Any help is appreciated.

**Comment by sobisht** [comment]
@mommaleo You have added "[Fixed]" to your title. Is the problem fixed at your side?

**Comment by mommaleo** [comment]
Yes! I made a user error 😬
