### ISSUE TITLE
Brackets auto-closes tags even when setting "whenOpening" to false

### ISSUE THREAD

**Issue by csauvageau** [adobe/brackets#14156]
### Prerequisites

* [X] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [X] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description
When running Brackets v.1.12 (and also checked v1.11) for MacOS 10.10.5, and setting whenOpening to false, the tag auto-completion feature still completes the tag as soon as the opening tag is typed.  This is a nuisance when editing code vs. writing code from scratch as I always have to delete the second tag that is auto-created every time I type in a tag.
[Description of the bug or feature]

### Steps to Reproduce

1. Install Brackets v1.12 for MacOS.
2. Start Brackets and click Brackets > Preferences.
3. Scroll down to the closeTags section and change "whenOpening" to false.
4. Save the preferences.
5. Close Brackets.
6. Re-open Brackets.
7. Open any HTML file.
8. Type <p> and notice that the closing tag </p> is auto-generated.  It seems to be true for all other tags as well.
>>This is a hassle because every time I type a tag, I get a closing tag and when I'm editing HTML, this is not the way to go.  I have to delete the closing tag all the time.
>>Another time, I also deleted the following files to clear any cache after saving the changes to defaultPreferences.json from the same folder and restarting Brackets:
     brackets.json
     state.json
     /cef_data/
>>I also have tried launching Brackets with Debug > Reload Without Extensions

**Expected behavior:** [What you expected to happen]
When editing the defaultPreferences.json as described in the steps above, the expectation is that a tag can be typed without a closing tag being auto-generated.
**Actual behavior:** [What actually happened]
Closing tags are auto-generated every time an opening tag is typed.

### Versions
Seen with versions 1.11 and 1.12 for MacOS v10.10.5.

More...
Release 1.12 build 1.12.0-17621 (release d3b783b99) 
build timestamp: Thu Feb 01 2018 03:32:03 GMT-0800

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by navch** [comment]
Working perfectly fine for me. Please check you have the same entries in brackets.json

```
"closeTags": {
        "whenOpening": false,
        "whenClosing": false
    },
```

Please make sure there is no parsing error in brackets.json and this "closeTags" is same as mentioned here.

**Comment by csauvageau** [comment]
Hi Navch,

Thanks for your reply.  I tried, but no avail.  I have attached the preferences file and a couple of screen shots to show the tags still auto-complete.  Would you mind checking?

Thanks,
Chris

<img width="367" alt="brackets_starting paragraph tag" src="https://user-images.githubusercontent.com/37272448/37618572-ea77e4a8-2b73-11e8-9260-4599a0a2d546.png">
<img width="370" alt="brackets_paragraph tag auto-generates" src="https://user-images.githubusercontent.com/37272448/37618593-f2342b3e-2b73-11e8-867b-3370431ae26d.png">
[defaultPreferences.json.zip](https://github.com/adobe/brackets/files/1826686/defaultPreferences.json.zip)

**Comment by navch** [comment]
Hi @csauvageau
It looks like you are updating defaultPreferenc.json, I think you need to update brackets.json file. On clicking  Brackets > Preference, it will open both files. And you need to update in brackets.json. Brackets pick preference from brackets.json, defaultPreference.json is there just for reference.
Please try this and let me know.

**Comment by csauvageau** [comment]
Hi Naveen,

Just tried modifying brackets.son and got this error message.  Looks like it doesn't recognize the properties.  I also restarted Brackets as well.  If you have any other suggestions, please do let me know.  I appreciate your help.

See screen shot below.
<img width="745" alt="brackets json" src="https://user-images.githubusercontent.com/37272448/37686994-14f85bac-2c57-11e8-8a0a-68a612a3d2a5.png">

Thanks,
Chris

**Comment by navch** [comment]
you missed comma (,) on the 6th line. Add that and then press enter. and paste the code written here

`"closeTags": {
        "whenOpening": false,
        "whenClosing": false
    },`

It will work like charm :)

**Comment by csauvageau** [comment]
Great!  Thank you!  Yes, works like a charm!  I wonder why it was not configured this way out of the box, though.  Still, it works and is much more usable now.  Thanks so much, Naveen!

Chris

**Comment by leolaps** [comment]
Hello there! I am starting to learn HTML, really a newby here... When I have read these explanation I though I would resolve my issue, which is exactly the same. However, I'm still getting error messages when I try to change my brackets.json file. Here is how I wrote it:

![captura de tela 2018-08-01 as 11 41 37](https://user-images.githubusercontent.com/41794304/43528670-e2fd7c08-957f-11e8-8372-d0b6bd630535.png)

I think I did not get the comme thing on the 6th line. Could someone explain it for me, or even show me the entire code?

Thank you kindly!

**Comment by navch** [comment]
I guess no need of comma at the end of 6th line

**Comment by navch** [comment]
what is exactly you want to do? If you want to get rid of this. Then just delete %appdata%/Brackets/brackets.json
It will auto generate this file on next launch. Then just do Debug > Open preference file
It will open two file one is brackets.json other is defaultPreference.json. Whatever setting you want to do copy that piece of code from defaultPreference file and paste in brackets. And modify accordingly. Make sure you put comma at right place. And you can use some online json validator to validate your json.

**Comment by leolaps** [comment]
Ok, thank you, mate. I will try it now...
I am trying to eliminate the autoclosing tags default.

**Comment by leolaps** [comment]
It seems like there was that extra comma at the end of 6th line! It is working now.
Still learning to get smart at these details!

Thank you for this very fast helping hand! :)

**Comment by navch** [comment]
@leolaps Enjoy learning 👍 Go through brackets feature. This editor has amazing features like multi cursor, quick edit, hints and many more. This editor has a lot of wonderful extensions as well. Then you will enjoy learning more :)

**Comment by redmunds** [comment]
It looks like you have the same problem as above -- a comma at the end of the "closeTags" line. In JSON, commas are _separators_, not _terminators_.

There's a JSONLint extension that will catch this for you.

**Comment by NinjaBryden** [comment]
Thanks that helped fix the problem

**Comment by BrunoColibri** [comment]
Thank you, it helped me out.

**Comment by Bdog12345** [comment]
![image](https://user-images.githubusercontent.com/44851822/48308095-c4df3500-e510-11e8-9bec-787101bdaee4.png)
what is wrong

**Comment by navch** [comment]
looks like comma missing on 8th line and extra comma on 9th line. You could catch this by code colouring on 9th line colour of key is different.

**Comment by okFox** [comment]
Thank you so much for this thread!

**Comment by MarianneLarssen** [comment]
Hi.
I´m trying to change the bracket.json as instructed above, but I get the following error:

<img width="1121" alt="screenshot 2019-02-13 at 23 47 25" src="https://user-images.githubusercontent.com/45150783/52750170-c7f43080-2feb-11e9-898d-e0124e1cf276.png">

Any ideas what I´m doing wrong?

**Comment by escagedo** [comment]
Hi! 
Is my first week using brackets and I am having the same issue than above: Not being able to remove the automatic closing of the tags.

I checked many times the preferences and try different ways of writing them but the tags are still closing automatically.

Here is how my actual brackets.json file looks like:

<img width="695" alt="screen shot 2019-03-08 at 19 16 18" src="https://user-images.githubusercontent.com/48363690/54047184-b5c67600-41d6-11e9-943d-b9ba7ac2fd86.png">

**Comment by csauvageau** [comment]
Hi escapeedo,

I just downloaded the latest Brackets (Release 1.13 build 1.13.0-17696 (release 49d29a8bc)).

Auto-close still seems to be off, which is the behavior I want.  Here is my brackets.json file:

{
    "brackets-eslint.gutterMarks": true,
    "brackets-eslint.useLocalESLint": false,
    "fonts.fontSize": "12px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "closeBrackets": false,
    "closeTags": { "whenOpening": false, "whenClosing": false },
    "closeOthers.below": true,
    "closeOthers.others": true
 
}

Good luck!

Chris

**Comment by escagedo** [comment]
Thanks @csauvageau 

I think the issue was in the comma on my line 9, which it was redundant with the comma in line 10.

I could realize that checking your settings.

Thank you very much, Chris! 🤘🤘🤘

**Comment by Candy-bar** [comment]
I am having the same issues as all others, i keep getting my tags closed when i dont want to. 
I tried copying @csauvageau info, but still having the issue. In my image exaple i show that <div> auto closed when i put the end bracket, i do not want that!
![image](https://user-images.githubusercontent.com/51992774/59753762-190b7e00-9285-11e9-9374-7fe695e463e6.png)

**Comment by Anand-anand** [comment]
![Screenshot (71)](https://user-images.githubusercontent.com/56036028/100087893-5e1de180-2e75-11eb-80a0-01538d457937.png)
I am not getting the auto close brackets or hints please help me with this 
i tried changing the preference, uninstalled and re-installed, but nothing worked
