### ISSUE TITLE
Stop the Cursor From Blinking 

### ISSUE THREAD

**Issue by RichieD83** [adobe/brackets#14150]
### Prerequisites

* [n ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ y] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [y ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

How can I stop the Cursor from blinking? Please stop the cursor from blinking.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

For the cursor to stop blinking

**Actual behavior:** [What actually happened]

The cursor keeps blinking (annoying)

### Versions

Please include the OS and what version of the OS you're running.
Windows 10 and the latest version of Brackets
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by navch** [comment]
Hi @RichieD83
I am not sure if you can do it with preference as of now. If you fine with [setting dev environment of brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) then I can suggest a fix for this.

**Comment by lip-d** [comment]
Hi RichieD83

This extension can do that.

Cursor Options
https://github.com/maupin/brackets-cursor

Works fine with me on Win7 and Win10 using Brackets 1.12.

**Comment by RichieD83** [comment]
Thanks a million!!
