### ISSUE TITLE
Copy command is not working properly i.e Ctrl+C ? 

### ISSUE THREAD

**Issue by Engrkartik** [adobe/brackets#14167]
Hello developers !! copy command is not working properly. When i hit the command 3 or 4 times then it works. Please check the issue. By the way the brackets code editor is very good in all the aspects.

**Comment by navch** [comment]
Hi @Engrkartik Is there any extension installed. Can you please try this:-
1) Debug > Reload Without Extension 
2) Now try your steps

Still, you are facing this issue then can you please check, is there any console error for that you need to open Debug > Show Developer Tools.

**Comment by navch** [comment]
Closing this issue. If you still have any issues around this, please feel free to reopen this.
