### ISSUE TITLE
Reverse live preview doesn't work

### ISSUE THREAD

**Issue by john-cj** [adobe/brackets#14179]
### Prerequisites

* [v] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [v] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [v] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

Brackets 1.12, clean install, clean user profile. Windows 7 32-bit.

How I can ENABLE reverse live preview? 

I have this html file:

``` html
<div>
	<p>foo</p>
	<p>bar</p>
</div>
<div>
	<p>foo</p>
	<p>bar</p>
</div>

<table>
    <tr>
        <td>foo</td>
        <td>bar</td>
    </tr>
</table>
```

And I haven't any other Chrome instances running. Yes, live preview works, but what should I do to see it's reverse effect?

![brackets](https://user-images.githubusercontent.com/18004961/38001311-cc574f8c-3234-11e8-9273-1577b433dca2.PNG)

**Comment by sobisht** [comment]
@john-cj Could you show a gif or video of the behavior.

**Comment by john-cj** [comment]
@sobisht No. I tried to click everywhere in Chrome window - nothing happens. How does it work for you? Wha you do when you use reverse preview?
