### ISSUE TITLE
[Brackets auto-update Windows] Once the update is done, brackets does not automatically launch.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14184]
### Description
Once the update is done, brackets does not automatically launch.

### Steps to Reproduce
1. Launch brackets 1.13.
2. Click on Update Notification Button.
3. Click on Get it now button.
4. Click on Restart button.
5. Brackets gets updated but does not launch after update is completed.

**Expected behavior:** Once the update is done, brackets should launch.

**Actual behavior:** Once brackets gets updated, user has to manually launch brackets.

### Versions
Windows 10 64 Bit
Release 1.13 build 1.13.0-17639

**Comment by mbhavi** [comment]
This in an installer level issue, and should be assigned to RE. Please assign accordingly @ayushrathi15

**Comment by ayushrathi15** [comment]
Tested in Release 1.13 build 1.13.0-17665.
Working fine now.
