### ISSUE TITLE
[Brackets auto-update Windows] In the update notification dialogue, get it now button should change to Install Now.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14182]
### Description
In the update notification dialogue, get it now button should change to Install Now.

### Steps to Reproduce
1. Launch brackets 1.13.
2. Click on Update Notification Button.
3. Click on Get it now button.
4. Click on later button in the update info bar at the bottom.
5. Again click on update notification button.
6. The get it now button should now change to install update button.

**Expected behavior:** Once user has clicked on get it now button after that when ever user opens update notification dialogue in the same session then user must see the install update button. 

**Actual behavior:** In the update notification dialogue, the get it now button does not change to install update button.

### Versions
Windows 10 64 Bit
Release 1.13 build 1.13.0-17639

**Comment by mbhavi** [comment]
As per the discussion with PDM, the string in the update notification dialog need not be changed, from GetItNow to InstallUpdate.
Please close this issue. @ayushrathi15

**Comment by ayushrathi15** [comment]
This is as designed. hence closing the issue.
