### ISSUE TITLE
[Brackets auto-update Windows/Mac] Red colored update info bar comes up on launching brackets after it has been updated.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14185]
### Description
Red colored update info bar comes up on launching brackets after it has been updated.

### Steps to Reproduce
1. Launch brackets 1.13.
2. Click on Update Notification Button.
3. Click on Get it now button.
4. Click on Restart button.
5. Brackets gets updated.
6. Launch brackets.
7. Red colored update info bar comes up on launching brackets after it has been updated.
This bar does not display any message.

**Expected behavior:** Green colored update info bar should come showing Update Successful message.

**Actual behavior:** Red colored update info bar comes up on launching brackets after it has been updated.

### Versions
Windows 10 64 Bit
Mac 10.13
Release 1.13 build 1.13.0-17639

**Comment by ayushrathi15** [comment]
Tested in Release 1.13 build 1.13.0-17665.
This issue is still reproducible.

**Comment by RuchiAgrawalAdobe** [comment]
Issue is reproducible on JP as well.
Tested in Release 1.13 build 1.13.0-17665 on Win 7 JP machine.

**Comment by ayushrathi15** [comment]
Verified in build 1.13.17674. Working fine now.
