### ISSUE TITLE
is brackets is lying to me ?

### ISSUE THREAD

**Issue by fz-sl** [adobe/brackets#14190]
I built a website page in brackets(html & css) ... If I get live preview in the app, everything is in place ... If the page is opened directly through the browser, most of the elements aren't in place...

![screenshot 28](https://user-images.githubusercontent.com/26028317/38162417-2a5c89da-34f6-11e8-89e1-16227b2def07.png)

![screenshot 29](https://user-images.githubusercontent.com/26028317/38162418-2a8c110a-34f6-11e8-8501-fee500f10a2e.png)

**Comment by JBallin** [comment]
Try setting the zoom to 100% in your browser, seems like you're zoomed in a bit.
View -> Actual Size

If that solves, this issue should be closed.

**Comment by fz-sl** [comment]
no .... its not from zoom 
 I cant trust live preview
It wasn't like this before.

**Comment by fz-sl** [comment]
all of the font size chenges ...

**Comment by JBallin** [comment]
hmm ok not sure then. are you using "experimental live preview"? (look at menu bar -> file -> toward the bottom and see if it's checked). Maybe try toggling that? I believe it uses a new chrome browser instead of safari (may need chrome installed?).

**Comment by fz-sl** [comment]
no .. i wasn't using experimental live preview ... but when i checket it .. its similar with "when the web page  opend with browser ... " But not exactly  the same ...
I think the main issue is font sizes .....
if its need tell me to send my project here to make sure the problem is not mine ...

**Comment by Crytiqal** [comment]
Maybe an issue with relative paths to the .css file?

**Comment by DRXDesign** [comment]
Please check your CSS file directory
and the font used

**Comment by fz-sl** [comment]
problems GONE  !!!!
I unstalled breackets  and than reinstall it ... 
and checked the experimental livepreview ....
also I checked the zoom of web page  for sure  ...

Thank every one for your attention... have good coding in your life guys
