### ISSUE TITLE
[Brackets auto-update Macs] UI issue when mounting dmg.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14201]
### Description
UI issue when mounting dmg.

### Steps to Reproduce
1. Open brackets 1.13 dmg to  mount it.
2. Once mounted, the dialogue for moving brackets dmg to application folder would be shown.
3. Lot of white space can be seen in the dialogue. 

<img width="496" alt="screen shot 2018-04-05 at 1 41 07 am" src="https://user-images.githubusercontent.com/25339865/38355935-f3afe032-38db-11e8-916a-2574e00a03e7.png">

<img width="786" alt="screen shot 2018-04-05 at 1 41 53 am" src="https://user-images.githubusercontent.com/25339865/38355937-f5533b50-38db-11e8-9589-5c57307d6a0d.png">

**Expected behavior:** There should be no white space shown to user.

**Actual behavior:** Lot of white space can be seen as shown in screenshot.

### Versions
Mac 10.13
Release 1.13 build 1.13.0-17639

**Comment by gavankar** [comment]
@ayushrathi15 Fixed in autoupdate build 1.13.0-17655. Please verify.

**Comment by ayushrathi15** [comment]
Verified in build 1.13.0.-17655.
