### ISSUE TITLE
Disable Auto close tag

### ISSUE THREAD

**Issue by AsalEtemad** [adobe/brackets#14206]
Hi,
When I type a tag for example <section> (after greater than angular (>)) automatically was written close tag </section>
How can disable it? or we have shortcut for this?
Thanks

**Comment by navch** [comment]
Hi @AsalEtemad 
Steps to disable auto close feature:-
1) Debug > Open Preferences File (This will open two files called defaultPreference.json and brackets.json, You have to edit brackets.json to enable or disable a feature)
2) Add entries in brackets.json to disable auto close feature
    a)  "closeBrackets": false (This will disable automatically close braces, brackets and parentheses)
    b) "closeTags": {
        "whenOpening": false,
        "whenClosing": false  (**As per your example this is true in your case, make it false**)
        } (Sets the tag closing options)

For the detailed explanation of these preferences, you can have a look at defaultPreference.json

Closing this issue. Please feel free to reopen this, If you still have any concern.

**Comment by AsalEtemad** [comment]
Thank you, The problem was solved but before this change when I close tag and typed "/" IntelliSense offer automatically and type close tag but now disabled. 
How can Enable this feature but disable auto close tag?

**Comment by navch** [comment]
// Close tag when / of closing tag is typed
"whenClosing": true

//Close tag when > of opening tag
"whenOpening": true

This will enable that If I understood right.

All preferences around this


// Sets the tag closing options
	"closeTags": {
		// An array of tags that should not be auto-closed
		"dontCloseTags": [],

		// An array of tags that when opened has a blank line
		"indentTags": [],

		// Close when / of closing tag is typed
		"whenClosing": true,

		// Close when > of opening tag is typed
		"whenOpening": true
	}

**Comment by Shivani1304** [comment]
Thank you so much for solution because I was really annoyed by that auto closing thing @navch

**Comment by naenaek22** [comment]
I am having this same problem with the auto close. But every time I type the the code in brackets.json to disable auto close it says that the code isn't correct. When I simply turn off the auto close in the preferences menu when I restart it reverts back to default. Can someone please help me?
