### ISSUE TITLE
[Brackets auto-update Windows/Mac] Update bar should show three dots for the strings if the view is small.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14218]
### Description
[Brackets auto-update Windows/Mac] Update bar should show three dots for the strings if the view is small.

### Steps to Reproduce
1. Launch brackets 1.13.
2. Click on Update Notification Button.
3. Click on Get it Now.
4. Update bar will be shown.
5. Shrink brackets window.
7. the string in update info bar gets truncated and does not show three dots at the end.

![screen shot 2018-04-12 at 1 50 55 am](https://user-images.githubusercontent.com/25339865/38734571-c03085ea-3f43-11e8-92ca-22c9452a4dc0.png)

**Expected behavior:** Update bar should show three dots for the strings if the view is small.

**Actual behavior:** The update bar show the truncated string.

### Versions
Windows 10 64 Bit
Mac 10.13
Release 1.13 build 1.13.0-17665

**Comment by niteskum** [comment]
Fixed in https://github.com/adobe/brackets/pull/14295

**Comment by ayushrathi15** [comment]
Working fine now.
Verified in latest build - Release 1.13 prerelease build 1.13.0-17689.
