### ISSUE TITLE
[Brackets auto-update Windows/Mac] The buttons in update bar should have border radius of 3px as per specs.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14219]
### Description
[Brackets auto-update Windows/Mac] The buttons in update bar should have border radius of 3px as per specs.

### Steps to Reproduce
1. Launch brackets 1.13.
2. Open another brackets window.
3. Click on Update Notification Button.
4. Click on Get it Now.
5. Update bar will be displayed along with buttons.
6. The buttons in update bar should have border radius of 3px as per specs.

<img width="240" alt="screen shot 2018-04-12 at 1 54 31 am" src="https://user-images.githubusercontent.com/25339865/38734691-258a0538-3f44-11e8-912a-10c90505233c.png">

**Expected behavior:** The buttons in update bar should have border radius of 3px as per specs.

**Actual behavior:** The buttons does not have any border radius.

### Versions
Windows 10 64 Bit
Mac 10.13
Release 1.13 build 1.13.0-17665

**Comment by niteskum** [comment]
https://github.com/adobe/brackets/pull/14295

**Comment by ayushrathi15** [comment]
Working fine now.
Verified in latest build - Release 1.13 prerelease build 1.13.0-17689.
