### ISSUE TITLE
[Brackets auto-update Windows/Mac] Content of status bar gets overlapped when the brackets window is resized to a smaller size.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14223]
### Description
[Brackets auto-update Windows/Mac] Content of status bar gets overlapped when the brackets window is resized to a smaller size.

### Steps to Reproduce
1. Launch brackets 1.13.
2. Resize the brackets window to a smaller size. 
3. Click on Update Notification Button.
4. Click on Get it Now.
5. Check status bar.
6. Content of status bar gets overlapped when the brackets window is resized to a smaller size.

![screen shot 2018-04-16 at 4 41 25 am](https://user-images.githubusercontent.com/25339865/38810874-acb72316-41a5-11e8-8d5a-d18c3928d62e.png)

![screen shot 2018-04-16 at 4 40 49 am](https://user-images.githubusercontent.com/25339865/38810883-b072ba06-41a5-11e8-9b65-6c07e2297cc4.png)

**Expected behavior:** The content shown in status bar should not get overlapped

**Actual behavior:** Content of status bar gets overlapped when the brackets window is resized to a smaller size.

### Versions
Windows 10 64 Bit
Mac 10.13
Release 1.13 build 1.13.0-17665

**Comment by niteskum** [comment]
https://github.com/adobe/brackets/pull/14295

**Comment by ayushrathi15** [comment]
Working fine now.
Verified in latest build - Release 1.13 prerelease build 1.13.0-17689.
