### ISSUE TITLE
Auto update: Dilato: Core: The update notification icon isn't disabled when the update build is downloading

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#14231]
Steps:
1. Launch Brackets 1.13
2. Click on Notification icon
3. Click Get it now
4. Click the Notification icon again

Result: The Update panel still could be launched, and could download more installers at the same time
Expected: The Notification icon is disabled
![iconenable](https://user-images.githubusercontent.com/2245179/38989942-0fbe3eec-440b-11e8-901f-60c5833c3a96.png)
![updateopen](https://user-images.githubusercontent.com/2245179/38990117-9c588c40-440b-11e8-81b5-8ba0627f3914.png)
![twodownloading](https://user-images.githubusercontent.com/2245179/38990451-ed55213e-440c-11e8-925a-e4cbe74b89a5.png)

**Comment by niteskum** [comment]
Fixed in https://github.com/adobe/brackets/pull/14295

**Comment by ZuoBaogang** [comment]
Verified this issue on build 1.13.17688-1049  Fixed
![14231_fixed](https://user-images.githubusercontent.com/17721679/40887334-e4b067c4-6779-11e8-9842-79c6ae93c8f9.png)
