### ISSUE TITLE
Auto update: Dilato: Core: There is no message after disconnect the network when the update is downloading

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#14232]
Steps:
1. Launch Brackets 1.13
2. Click the Notification icon
3. Click Get it now
4. Disconnect the network

Result: There is no error message pop up, and the download process would always keep there, after connect the network, the downloading wouldn't continue

Expected: 
1. There is an error message pop up, and the downloading stopped
2. The message in status bar is changed to another one, tell user the network is disconnect, and after connect the network, let user retry the downloading

**Comment by ZuoBaogang** [comment]
Verified this issue on build 1.13.17688-1049 Fixed
![14232](https://user-images.githubusercontent.com/17721679/40887437-6236f2ca-677b-11e8-8065-e3ea56120276.png)
