### ISSUE TITLE
Auto update: Dilato: Core: The auto update will not happen if reload the Brackets and then close it

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#14233]
Steps:
1. Launch Brackets 1.13
2. Click the Notification icon
3. Click Get it now
4. After the downloading completed
5. Click Debug -> Reload with/without extensions
6. After the reload, close Brackets

Result: The auto update isn't happen
Expected: The auto update could start after closed the Brackets

**Comment by niteskum** [comment]
Ideally Auto Update starts when User click on "Restart" Button in Update Bar after Download.
Is the Expectation to start Auto Update even if User has not clicked on "Restart" Button??

**Comment by Zhanxin** [comment]
Tried again, user must click Restart then the Brackets would be updated. @RuchiAgrawalAdobe Please help to double confirm the correct behavior.
