### ISSUE TITLE
[Brackets auto-update Windows] Seeing two entries in Control panel and build number is not updated in the app if the auto-updated build has the same version number as installed build

### ISSUE THREAD

**Issue by DivyaBC** [adobe/brackets#14236]
Description
[Brackets auto-update Windows] Seeing two entries in Control panel and build number is not updated if the auto-updated build has the same version number as installed build

Steps to Reproduce

1. Upload 1.13.0-17656 on to server
2. Install brackets 1.13.0-17655 on windows machine (note that the only difference between the build on server and installed one is the build number. The version is same in both places)
3. Launch Brackets 1.13.0-17655
4. Click on Check for updates.
5. Click on Get it now.
6. Once download is complete, Click on Restart in the pop up 
7. Once Brackets is auto launched go to Help->About Brackets
8. Launch Control Panel and go to uninstall programs
10. Check the Brackets entries in the list of programs

Expected behavior: The build number should be of the latest build 1.13.0-17656 and control panel should have only one entry of Brackets for uninstallation

Actual behavior: The build number is of previous  build 1.13.0-17655 and control panel has two entries for Brackets. Both these entries can be uninstalled

Versions: Win 10
Release 1.13 build 1.13.0-17655 
![controlpanel](https://user-images.githubusercontent.com/23053850/39052183-d3ab45da-44c8-11e8-93c2-74110a300862.PNG)

**Comment by DivyaBC** [comment]
We are seeing the correct build number on manually installing 1.13.1 build on top of 1.13.0 build but auto update is failing

**Comment by ayushrathi15** [comment]
Working fine now.
Verified in latest build - Release 1.13 prerelease build 1.13.0-17689.
