### ISSUE TITLE
[Brackest auto-update] The update logs should be retained irrespective of whether the update is successful or failed

### ISSUE THREAD

**Issue by DivyaBC** [adobe/brackets#14243]
Description
[Brackest auto-update] The update logs should be retained irrespective of whether the update is successful or failed

Steps to Reproduce
Install Brackets 1.13
Click on Check for updates.
Click on Get it now.
Once download is complete, Click on Restart in the pop up
Go to  C:\Users\<username>\AppData\Roaming\Brackets\updateTemp and check that there is a the log file generated
Once Brackets is auto launched go to Help->About Brackets
Verify that updated build number shown
Go to  C:\Users\<username>\AppData\Roaming\Brackets\

Expected behavior: The log file should be retained irrespective of whether the update is successful or failed
Also the logs should be moved to C:\Users\<username>\AppData\Local\Temp

Actual behavior: The log file is deleted once update is successful
Versions: Win 10
Release 1.13 build 1.13.0-17656

**Comment by mbhavi** [comment]
@DivyaBC , the removal of update logs on successful update is as per design. The intention is to not bloat up user's storage with heavy logs unless needed. Only in case of update failure is when we really need the logs to be retained, for further information about failure reasons. And so, if the update is successfully installed , keeping the logs is not needed.
Hence, not a bug.

**Comment by DivyaBC** [comment]
@mbhavi , this ask was logged because we once saw an issue where the update was successful but on launching brackets, it was still the older version and because the logs were also cleared we could not figure out what went wrong. In such cases logs can be helpful if retained. hence, the ask to retain the logs irrespective of whether the update is successful or failure

**Comment by niteskum** [comment]
we will keep the installer log within Brackets folder in Appdata.
On every subsequent auto update, we can cleanup previous installation logs.

**Comment by ayushrathi15** [comment]
Verified on 1.13 Prerelease Build 17689
