### ISSUE TITLE
Code Issue. Brackets in () are marked RED in my index.html, any ideas why?? Please help

### ISSUE THREAD

**Issue by benmcreations** [adobe/brackets#14260]
<section id="header">
        <div class="container">
            <div class="row">
                <div class="col-md-12 wow fadeIn data-wow-delay="1s" data-wow-duration="2s">
                    (<)img src="images/ben m logo header.png" class="img-fluid">
                    (<)h2>THINGS LOOK BETTER IN THE GREAT BEYOND(<)/h2>
                    (<)p class="lead">We dream, explore, create and craft progressive creative experiences. We design for you. We’re strategic experts and creative explorers committed to solving complex challenges.(<)/p>
                    (<)p class="hidden-sm-down d-none d-md-block wow fadeIn data-wow-delay="2.0s" data-wow-duration="2s">We are deep thinking, creative experts and we
                    <b>GIVE A BRAND!</b>
                    </p>
                </div>
            </div>
            <div class="row wow swing" data-wow-duration="2s">
                <div class="col text-center">
                    <a href="#social">
                        <i class="fa fa-chevron-down fa-3x" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>

**Comment by redmunds** [comment]
You're missing a closing double-quote: `class="col-md-12 wow fadeIn`.
