### ISSUE TITLE
[Drag and drop] Not able to drag and drop file/folder in LINUX

### ISSUE THREAD

**Issue by NithinK123** [adobe/brackets#14265]
Description
In Linux machines drag and drop of file/folder is not working. File/Folder is not able to drag and drop to other.
Steps to Reproduce

1. Launch Brackets(1.13 17655)
2. Right click and create new folder(left side panel)
3. create one more folder 
4.Left click on the first folder
5.Move mouse over second folder
6. Leave the mouse to drop the folder 

Expected behavior:
Step4: File name should appear
Stept5: Folder should be highlighted
Step6: Folder should move to second folder
Actual behavior:
Step4: File name is not appearing, blank whitespace is coming
Stept5: Folder is not getting highlighted
Step6: Folder is not moved into second folder
Notes 
1. Verified with files also , same issue is happening
2. Verified by opening folder from brackets(file->Open folder), issue is happening
3. Scrollbar is not moving up, when trying to drop file or folder
Versions
Ubuntu 16.04, Ubuntu 17.1

**Comment by boopeshmahendran** [comment]
Fixed in https://github.com/adobe/brackets-shell/pull/642
