### ISSUE TITLE
[Brackets Auto Update ] Error should not be shown to user on failing to clean up the updateTemp folder after Autoupdate

### ISSUE THREAD

**Issue by DivyaBC** [adobe/brackets#14266]
Description
[Brackets Auto Update ] No error should be shown to user on failing to clean up the updateTemp folder after Autoupdate

 Steps to Reproduce
1. Install Brackets 1.13
2. Launch Brackets 
3. Go to Help->Check for Updates
4. Click Get it now
5. Disconnect internet after download reaches above say 15%
6. Wait for sometime
7. Reconnect Internet
8. Press F5 (Relead Brackets with Extensions)

Or
This error can also be simulated by making the updateTemp folder readonly

Expected behavior:  We should not shown this error to user as there is no user action involved here. Also user has no idea about what the update directory is. Ideally we should just log this error in Console and also log a failure to the Analytics Server.

Actual behavior: User is shown the below "Cleanup failed! Update directory could not be cleaned"

Versions Win/Mac
Release 1.13.0 17657
![cleanupfailure](https://user-images.githubusercontent.com/23053850/39302778-74294b86-4971-11e8-95de-5b95dfc000e0.png)

**Comment by ayushrathi15** [comment]
Working fine now.
Verified in latest build - Release 1.13 prerelease build 1.13.0-17689.
