### ISSUE TITLE
Dilato: [I18N]: EPV: The image info in Brackets is not localized.

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14277]
Problem:  The image info in Brackets view window is not localized.

Test device:  windows 10 64bit, Mac 10.12
Test build: 1.13.17657

Method:
1. Launch Brackets.
2. Drop and drag an image to Brackets. (Such as jpg/png  ect) 
3. Observe the image info in the view window.

Result:
The image info in Brackets view window is not localized.

Expected:
The image info in Brackets view window should be localized.

image:
![enu](https://user-images.githubusercontent.com/17721679/39360821-4b346e72-4a52-11e8-839a-7b6d4a77ce60.png)
![fra](https://user-images.githubusercontent.com/17721679/39360824-4e02eee4-4a52-11e8-833d-76e0ad585685.png)

**Comment by ZuoBaogang** [comment]
This issue is also reproed in 1.12 build.

**Comment by RuchiAgrawalAdobe** [comment]
Closing the bug as numbers and units are not expected to be localized.
