### ISSUE TITLE
Red tags error

### ISSUE THREAD

**Issue by 0ffPACY** [adobe/brackets#14284]
### Description

[My start tags are blue n' stuff but most of my end tags suddenly turned red? When I click on the red ones it still turns green and shows the start tag.]
![fuk0fferror](https://user-images.githubusercontent.com/27310381/39388678-302266b8-4a82-11e8-8d63-a19d3e997024.png)

### Steps to Reproduce

Can't really Reproduce it because I don't know what's causing it

### Versions
Windows 10 build 1709
Brackets build 1.12.0-17621

**Comment by 0ffPACY** [comment]
nvm solved

**Comment by redmunds** [comment]
The tag coloring is also know as "syntax coloring". It does help readability, but it also indicates correct syntax. In general, start where the syntax coloring is wrong and go backwards until you get to correct coloring -- the error will be near there.

Error is in this block:

![syntax-coloring](https://user-images.githubusercontent.com/1197144/39389355-78eb59e0-4a3c-11e8-906f-3306bff42f52.png)

The `<` character is interpreted as the start of a tag which is indicated by the blue color. It should be encoded as `&lt;`.
