### ISSUE TITLE
error js

### ISSUE THREAD

**Issue by dndubov** [adobe/brackets#14294]
Hello, tell me what  this error is related to
[Документ Microsoft Word.docx](https://github.com/adobe/brackets/files/1969746/Microsoft.Word.docx)

**Comment by navch** [comment]
This is an ESLint error. You can configure these rules by keeping a .eslintrc file at your project root. Basically, In your case, it's picking default rule which is no console logs in code. Here you can find how to configure .eslintrc file https://eslint.org/docs/user-guide/configuring

I am closing this issue. Feel free to reopen this if still have any issues.
