### ISSUE TITLE
Core: No error on moving a read-only file/folder.

### ISSUE THREAD

**Issue by RuchiAgrawalAdobe** [adobe/brackets#14296]
Test build: 1.13.0-17657

### Description

No error on moving a read-only file/folder.

### Steps to Reproduce

Scenario 1:
1. Create a read-only file in a folder.
2. Launch Brackets and load the folder in step 1.
3. Move the read-only file in that folder to some other folder.

Result: No error.

Scenario 2:
1. Place some files in a folder and make that folder read-only such that all files in the folder become read-only.
2. Launch Brackets and and load the folder in step 1.
3. Move the read-only file in that folder to some other folder.
OR Move some files from another folder in the read-only folder

Result: No error.

**Expected behavior:** Error should appear.

Test Platform/Locale: Win 10/English

**Comment by RuchiAgrawalAdobe** [comment]
@ayushrathi15 - Could you please close the issue if it is working AsExpected.

**Comment by ayushrathi15** [comment]
@RuchiAgrawalAdobe  It should give an error.

**Comment by vickramdhawal** [comment]
looks similar to https://github.com/adobe/brackets/issues/14269

**Comment by RuchiAgrawalAdobe** [comment]
Closing as Dup of #14269
