### ISSUE TITLE
Dilato: Core: User couldn't drag a file from filetree to working area

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14303]
Steps:

1. Launch Brackets
2. Open a folder which has many subfolders and files
3. Drag a drop a file from filetree to working area

Result: User couldn't drag a file from filetree to working area

Expect: User could drag a file from filetree to working area

![issue](https://user-images.githubusercontent.com/17721679/39628369-70b04e94-4fdb-11e8-813a-1f8a6aa6baa4.gif)

**Comment by ZuoBaogang** [comment]
This issue reproduce on Windows, Mac, Linux(Ununtu & Debian) systems
Test build:
Linux: 1.13.17668
Windows & Mac: 1.13.17666-1019

**Comment by vickramdhawal** [comment]
A single click already opens the file and if a user edits the file or double clicks in file tree the file gets added to the working set. I don't see a reason to drag to working area to open the file.
