### ISSUE TITLE
Dilato: [Core]: Ubuntu 64 bit only: Cannot open the available remote files from recent files dialogue.

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14318]
Problem: Cannot open the available remote files from recent files dialogue.

Test build: 1.13.0-17668

Method:
1. Launch Brackets.
2. Press ctrl+shift+O and open the Quick open model.
3. Enter a network URL that supports http or https.
4. Press enter and the page displayed in the brackets.
5. Close the file.
6. Go to File -> Open Recent and click on the currently opened remote file.
7. Observe.

Result:
The file cannot be opened from recent files dialogue.

Expected:
The file cannot be opened from recent files dialogue.

![issue](https://user-images.githubusercontent.com/17721679/39756309-9c7946c0-52fb-11e8-824a-82a48be08638.gif)

**Comment by ZuoBaogang** [comment]
Verified issue is also reproed in 1.12 build.

**Comment by ayushrathi15** [comment]
@ZuoBaogang
I am able to open remote file from recent file list on Ubuntu 16.04 64 Bit.

**Comment by ZuoBaogang** [comment]
@ayushrathi15 Verified this issue in latest build 1.13.117668.
Issue is reproed on Ubuntu 17.10.1 64 bit, not reproed on Ubuntu 16.04.3 64/32 bit.

**Comment by ayushrathi15** [comment]
@RuchiAgrawalAdobe , please close this isse as it is not reproducible in Ubuntu 16.04 and 18.04 LTS.

**Comment by ZuoBaogang** [comment]
Verified this issue in Ubuntu 18.04 LTS with build 1.13.17679, it is not reproducible.
