### ISSUE TITLE
Dilato: Core: There is no file name in the working files panel when remote a URL with / at the end for the first time

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#14315]
Steps:
1. Launch Brackets 1.13
2. Press ctrl+shift+O for win and cmd+shift+O for mac
3. Input a URL with / at the end, such as "https://www.adobe.com/"
4. Press ctrl+shift+O for win and cmd+shift+O for mac
5. Input another URL with / at the end, such as "https://stock.adobe.com/"

Result: 
After step 3: there is no file name in the Working files panel
After step 5: the file name appears, but there is no color change when select one

Expected: There is always a file name for the URL, and it could change the color when select them

After step 3:
![nofilename](https://user-images.githubusercontent.com/2245179/39706623-8ea12778-5244-11e8-9e49-4ef78eb21cdc.png)
After step 5
![nocolor](https://user-images.githubusercontent.com/2245179/39706674-b9e6a782-5244-11e8-8f6e-b7fb0a9abf24.png)
Normal:
![normal](https://user-images.githubusercontent.com/2245179/39706728-e553be1e-5244-11e8-9262-80afc981efdc.png)

Build: 1.13.17668-1023

**Comment by ayushrathi15** [comment]
@RuchiAgrawalAdobe, Please verify and close this issue.

**Comment by ZuoBaogang** [comment]
Verified this issue on build 1.13.0-17688 Fixed
![14315_build_1 13 0-17688](https://user-images.githubusercontent.com/17721679/40886845-da40e4c4-6771-11e8-89cc-545566d22167.gif)
