### ISSUE TITLE
Dilato: Core: The code for the URL baidu.com can't be loaded

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#14314]
Steps:
1. Launch Brackets 1.13
2. Press ctrl+shift+O for win and cmd+shift+O for mac
3. Input the URL: https://www.baidu.com/

Result: The whole code can't be loaded
Expected: The whole code could be loaded
![cannotloadbaiducode](https://user-images.githubusercontent.com/2245179/39706155-153cbfa6-5243-11e8-814d-738c4fce0867.png)

Build: 1.13.17668-1023

**Comment by boopeshmahendran** [comment]
@Zhanxin It seems the whole code is loaded. Brackets show 749 lines in your screenshot (the same as source of that website). Can you scroll down and see?

**Comment by Zhanxin** [comment]
@boopeshmahendran Thanks a lot for the explanation. Yes, we could see the code after scroll down the panel. But in fact, there is no such spaces on website. Shall we remove the extra spaces? So much spaces is not good user experiences.
![baiducode](https://user-images.githubusercontent.com/2245179/39740363-dc6fe844-52c7-11e8-8c7b-5df30192ba9f.png)

**Comment by boopeshmahendran** [comment]
@Zhanxin Actullay the source of the mentioned website does contains spaces. `Right click` -> `View Page source`. You are seeing the DOM Explorer which removes the extra spaces.

**Comment by Zhanxin** [comment]
Thanks a lot for the explanation. Close this issue.
