### ISSUE TITLE
[Remote File][Linux] Brackets crashes when user tries to locate the remote file in OS

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14311]
### Description
Brackets crashes when user tries to locate the remote file in OS

### Steps to Reproduce
1. Launch brackets 1.13.
2. Press ctrl+shift+O for win and cmd+shift+O for mac.
3. Quick open modal bar will open.
4. Enter a network url that supports http or https. Example: https://www.google.com/
5. Right click on file in working set in file tree.
6. Context menu will appear.
7. Click on Show in OS.

**Expected behavior:** Brackets should not crash and user should be given a message that file could not be found.

**Actual behavior:** Brackets crashes when user tries to locate the remote file in OS

### Versions
Linux Ubuntu 16.04 64 Bit
Release 1.13 build 1.13.0-17668

**Comment by vickramdhawal** [comment]
@ayushrathi15 this is fixed on the latest brackets-shell and should be available on the release branch.

**Comment by ayushrathi15** [comment]
Working fine now.
Verified in latest build - Release 1.13 build 1.13.0-17693.
