### ISSUE TITLE
Live preview was cancelled because the browser navigated to a page

### ISSUE THREAD

**Issue by IMANTMN** [adobe/brackets#14339]
In brackets [latest version 1.12.0-17621] I am facing with the following errors. My Mac OS's version is 10.13.4.  
"Live preview was cancelled because the browser navigated to a page that is not part of the current project."  
Google Chrome says:  This site can’t be reached localhost refused to connect. Search Google for localhost html index ERR_CONNECTION_REFUSED  

<img width="601" alt="screen shot 2018-05-17 at 2 22 49 pm" src="https://user-images.githubusercontent.com/28578072/40196210-dc8214d4-59dd-11e8-9535-3818cb28aa49.png">
<img width="643" alt="screen shot 2018-05-17 at 2 22 41 pm" src="https://user-images.githubusercontent.com/28578072/40196211-dc962762-59dd-11e8-8cc3-b6301034712a.png">

I disabled my mac firewall. I am not using any proxy. My Google Chrome is up-to-date "Version 66.0.3359.181".   

My index.html is in a folder named html on my mac desktop. Project setting is set to: http://localhost/html/ 

Is there something I'm doing wrong?

**Comment by sobisht** [comment]
@IMANTMN  Since you set project settings to: http://localhost/html/ , brackets is expecting the folder in your local server. Since, for the file you are looking for the live preview is not in the local server, it shows error.

Either you copy the folder "html" to your local server.  Or, unset project settings so that the live preview will work on the current project opened in brackets.

**Comment by IMANTMN** [comment]
@sobisht Thank you so much. The issue is solved now!

**Comment by almaz180599** [comment]
Hey guys, 
I am having the same problem with Brackets. Can you please explain how to fix the problem step by step?
I understand what to do, but I don't know how to do that.

**Comment by icatalyse** [comment]
Hi there,
i have my "project folder" in the "htdocs folder"  in the "xampp folder" still it doesn't work. i keep having the same issue (live preview was cancelled because the g with Brackets.
i'm using xampp on a windows10. please i need help it is really frustrating.
thanks.
