### ISSUE TITLE
[Remote File][Mac] The save, rename and show in finder options are still enabled for remote file in mac.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14334]
### Description
The save, rename and show in finder options are still enabled for remote file in mac.

### Steps to Reproduce
1. Launch brackets 1.13.
2. Press ctrl+shift+O for win and cmd+shift+O for mac.
3. Quick open modal bar will open.
4. Enter a network url that supports http or https. Example: https://www.google.com
5. The code for the page is displayed in brackets and file is visible in working files in file tree.
6. In the file tree, right click on file.
7. Context menu will appear.
8. Save, rename, show in finder options are still enable for remote file.
9. Also, the option to save the file is enabled in file menu.

<img width="282" alt="screen shot 2018-05-16 at 9 57 57 pm" src="https://user-images.githubusercontent.com/25339865/40157889-0727489a-59bf-11e8-8add-f5c7ff58f6c0.png">

<img width="308" alt="screen shot 2018-05-16 at 9 58 06 pm" src="https://user-images.githubusercontent.com/25339865/40157902-19813c9e-59bf-11e8-85ad-f938e1c210e4.png">

**Expected behavior:** The save, rename and show in finder options should not be enabled for remote file.

**Actual behavior:** The save, rename and show in finder options are still enabled for remote file in mac.

### Versions
Mac 10.12
Release 1.13 build 1.13.0-17679

**Comment by swmitra** [comment]
@boopeshmahendran Can you please verify the issue?

**Comment by boopeshmahendran** [comment]
Yeah, sure. Raised a [PR](https://github.com/adobe/brackets/pull/14336) with the fix.
