### ISSUE TITLE
[Remote File] Apart from badge for protocol, the http and https are appended to the remote file if you open the same file with different protocol.

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14335]
### Description
Apart from badge for protocol, the http and https are appended to the remote file if you open the same file with different protocol.

### Steps to Reproduce
1. Launch brackets 1.13.
2. Press ctrl+shift+O for win and cmd+shift+O for mac.
3. Quick open modal bar will open.
4. Enter a network url that supports http. Example: http://www.google.com
4. Enter the same network url using https. Example: https://www.google.com
5. Two files are visible in working files with same name in file tree.
6. Apart from badge for protocol, the http and https are appended to the remote file if you open the same file with different protocol.

![remote file 1](https://user-images.githubusercontent.com/25339865/40157850-ccbd1cf2-59be-11e8-86ac-3f56b2e17633.PNG)

**Expected behavior:** Apart from badge for protocol, the http and https should not be appended to the remote file if you open the same file with different protocol.

**Actual behavior:** Apart from badge for protocol, the http and https are appended to the remote file if you open the same file with different protocol.

### Versions
Win 10 64 Bit
Mac 10.12
Release 1.13 build 1.13.0-17679

**Comment by swmitra** [comment]
This is not a bug. If we change the protocol, the resource URI is different and hence they are identified as different resource. Technically http and HTTPS are two different file servers and it's technically possible to serve different content (though no one does that). We will not change the implementation in this context.

**Comment by ayushrathi15** [comment]
This is As Designed.
Closing the issue.
