### ISSUE TITLE
Adobe Brackets FULL SCREEN

### ISSUE THREAD

**Issue by lucasdepessoa** [adobe/brackets#14340]
Olá, alguém sabe me dizer se é possível colocar o adobe brackets em tela cheia ? Exatamente como sublime faz com a tecla (F11). No brackets existe a opção de ocultar as barras laterais utilizando o comando (ALT+SHIFT+2) porém as guias de ferramentas que ficam em cima ainda me atrapalham.. quero somente o código na tela.. Não consigo compreender como uma ferramenta tão completa não tem essa opção ???
Alguém sabe me dizer? ...

// English google translate version //

Hello, can anyone tell me if it is possible to put adobe brackets in full screen? Exactly how sublime it is with the key (F11). In the brackets there is the option to hide the sidebars using the command (ALT + SHIFT + 2) but the toolbars that remain on top still hinder me .. I just want the code on the screen .. I can not understand how such a complete tool Do not have this option ???
Can anyone tell me? ...

**Comment by sobisht** [comment]
Duplicate of https://github.com/adobe/brackets/issues/11594
