### ISSUE TITLE
[Dilato]: [Core]: URL name is displayed from somewhere in between omitting the protocol as well as some initial characters on opening a remote file with long URL.

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14351]
Problem: URL name is displayed from somewhere in between omitting the protocol as well as some initial characters on opening a remote file with long URL.

Test device: Mac 10.13, win 7, Ubuntu 18.04
Test build: 1.13.0.17679

Method:
1. Launch Brackets 1.13.
2. Press ctrl+shift+O for win/linux and cmd+shift+O for mac.
3. Quick open modal bar will open.
4. Input a URL which is long, such as “http://www.baidu.com/s?ie=utf-8&f=3&rsv_bp=0&rsv_idx=1&tn=baidu&wd=%E9%A6%96%E9%83%BD%E5%8D%9A%E7%89%A9%E9%A6%86&rsv_pq=8a880d180000121c&rsv_t=5a5au2RiMw4aK8tEHK4Jdd%2B7FTrkeY4MubGOJcyFhYc9mevwSNATfJX39YE&rqlang=cn&rsv_enter=1&rsv_sug3=2&rsv_sug1=2&rsv_sug7=100&rsv_sug2=1&prefixsug=shoudu&rsp=3&inputT=2078&rsv_sug4=2079”
5. Press enter and the code for this page is displayed in brackets. 

CASE1:
Observe the file name in the file tree.

Result:
The URL name is displayed from somewhere in between omitting the protocol as well as some initial characters of the URL.
The problem here is there is no tool tip even to show the complete URL.

CASE2:
Go to File -> open recent. Observe the file name.

Result:
The URL name is displayed from somewhere in between omitting the protocol as well as some initial characters of the URL.
The problem here can be lived with since tooltip is available to show the complete file name.

Expected:
Fir both cases, the URL name should be displayed from the beginning instead of from somewhere in between.

![image](https://user-images.githubusercontent.com/31060760/40407590-8ea21814-5e82-11e8-9ca6-f8e8cec270b0.png)

**Comment by yprasad1** [comment]
Closing the bug as the behavior is as designed.
If the URL just has domain name, then that will be displayed in the UI.
Else the path post the last / is displayed in the UI
