### ISSUE TITLE
[Dilato]: [Core]: It only record one kind of operation one time whatever you do this operation many times

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14365]
Test build: 1.13.0.17679
This issue reproduce on Windows, Mac and Linux (Ununtu & Debian) system.

Steps:
1. Launch Brackets
2. Open Debug -> Show Developer Tools -> Netowrk
3. Click on "Network"
4. Check "preserve log" checkbox and type "ingest" in the text box
5. Open a js file or html file
6. Do a operation for js file or html file. (Such as "Refactor -> Wrap in Try Catch" for js file)
7. Check the record in debug
8. Repeated the step6 for same operation more times then check the record in debug

Result: It only record one kind of operation one time whatever you do this operation many times

Expect: It should record the operation time according to how many times you have operated

**Comment by sobisht** [comment]
@ZuoBaogang This is the expectation with the analytics logging, that it should log for one type of event only once in one session. 
Closing the issue. Feel free if you still have any issue.
