### ISSUE TITLE
[Dilato]: [Core]: Country code is displayed in Event.language in Brackets devtools.

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14363]
Problem: Country code is displayed in Event.language in Brackets devtools.

Test device: Win 7 (64bit), Mac 10.13
Test build: 1.13.0.17679

Method:
1.	Launch Brackets.
2.	Execute a few scenarios for which you want to verifiy the logging.
3. Go to Debug -> Show Developer Tools.
4. Click on “Network”.
5. Check “preserve log” checkbox and type “ingest” in the text box.
6. Hit F5 to refresh.
7. Check the ingest entry whose Type is "xhr"
8. In the "Headers" tab that opens up, scroll down to "Request Payload"
9.  Keep expanding until you get the "data" dropdown
10. Observe the Event.language.

Result:
Country code is displayed in Event.language in Brackets devtools.

Expected:
Country code should not display in Event.language in Brackets devtools.

image: 
![language](https://user-images.githubusercontent.com/17721679/40575026-dd0f16fc-610f-11e8-971f-f6045acdd8a5.png)

**Comment by RuchiAgrawalAdobe** [comment]
This is working as expected. A 5 character code is being logged.

**Comment by ZuoBaogang** [comment]
This screenshot captured on Linux system, it only display language code.
![linux](https://user-images.githubusercontent.com/17721679/40659987-663587f8-6382-11e8-914f-f266a67b135e.png)
