### ISSUE TITLE
to many projects.

### ISSUE THREAD

**Issue by alandtic** [adobe/brackets#14366]
in brakets you can add projects from your computer i acdently add all my desktop how can i delte it all fast i'm on macbookair.

**Comment by navch** [comment]
I am not sure what exactly you want to delete. If I am understanding you right, then you can right click on your folder which you want to open and click open with brackets. If this doesn't work for you then you can delete state.json file from Application Support/Brackets/state.json and reopen brackets. Closing this issue, feel free to reopen if you still have issues.

**Comment by alandtic** [comment]
thank you that worked
