### ISSUE TITLE
Auto-update: Dilato: Core: There is an extra % when user try to attempt the download for the second time

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#14379]
Steps:
1. Configure the setting for Brackets so that it could connect to the auto update server
2. Launch Brackets 1.13.17688-1049
3. Click the update icon
4. Click Get it now button
5. Disconnect the network to get the attempt download message

Result: There is an extra % for the second time
Expected: No extra %

![extra](https://user-images.githubusercontent.com/2245179/40786142-f29593dc-651c-11e8-8ba6-ce509b9161da.png)

**Comment by Zhanxin** [comment]
Now the build on update server is unavailable for testing, will regress on Monday.

**Comment by ZuoBaogang** [comment]
Verified this issue on build 1.13.17693-1056 Fixed
![2018-6-8 17-28-36](https://user-images.githubusercontent.com/17721679/41150890-b8286d02-6b41-11e8-9d7b-f888a33db893.png)
