### ISSUE TITLE
Dilato: Core: The download status bar doesn't shift to main Brackets window after close the one display the loading process

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14386]
Steps:
1. Open brackets 1.13
2. Go to Debug > New Brackets Window
3. Go to Help Menu in newly opened window
4. Click on Check for Updates --- Update Notification Dialogue should open in the same window where user clicked on Check for update.
5. Click on Get it Now button --- Download will start and you can see the download status in status bar
6. Close this brackets window while the installer is getting downloaded

Result: The download status bar doesn't shift to main Brackets window

Expect: The download status should now be visible in main brackets window

**Comment by ayushrathi15** [comment]
@RuchiAgrawalAdobe  This is duplicate of #14380
