### ISSUE TITLE
Dilato: Core: Windows only: There update notification dialogue doesn't appear automatically for the first time

### ISSUE THREAD

**Issue by ZuoBaogang** [adobe/brackets#14398]
Test build: 1.13.0-17689-1053

1. Open brackets 1.13 on windows system
2. Launch Brackets
3. Close the Brackets
4. Change the config.json file and redirect the update server to stage environment
5. Launch Brackets again

Result: 
There update notification dialogue doesn't appear automatically unless click Check for Updates, if clear the cache folder, the notification will appear.
This issue doesn't reproduce on Mac OS

Expect: There update notification dialogue should appears automatically if there has a new update

**Comment by ayushrathi15** [comment]
@ZuoBaogang @RuchiAgrawalAdobe Update notification dialogue is shown after 24 hours.
If it has been show once, then it will not be shown again to user.

This is expected. Please close the issue.
