### ISSUE TITLE
Dilato: Core: The subtype value is not same between the dev tools and the wiki

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#14395]
Steps:
1. Install Brackets 1.13 and modify the config file
2. Launch Brackets 1.13
3. Go to Help→Check for updates
4. Verify that you get the Auto-Update Notification dialog
5. Click on "Get It Now"
6. Downloading of build starts
7. Disconnect internet
8. Downloading fails, and check the dev tool

Result: The value is "Network is Disconnected or too slow." for subtype
Expect: Due to the wiki, the value should be "Error occurred while downloading" for subtype
![subtype](https://user-images.githubusercontent.com/2245179/40916700-3bf014f8-6833-11e8-81ec-faad99969579.png)

**Comment by ayushrathi15** [comment]
This is expected. Please close the issue.

**Comment by ayushrathi15** [comment]
This is as expected. Closing the issue.
