### ISSUE TITLE
Dilato: Loc FR/JP: Some error strings still display in English for auto update feature

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#14393]
Steps:
1. Install Brackets
2. Modify the config file to support auto-update feature
3. Launch Brackets
4. Click Help -> Check for updates
5. Click Get it now button to download the new build
6. Open a new Brackets window
7. Click the update icon and try to download the build, an error pop up
8. Disconnect the network and wait for the error pop up

Result: The error messages display in English
Expect: The error messages are localized. The strings haven't been localized in slate, please help to add in the build

Build: 1.13.17689
![networkslow](https://user-images.githubusercontent.com/2245179/40914317-48cf6be6-682a-11e8-90b8-1aeee44b742f.png)
![inprogress](https://user-images.githubusercontent.com/2245179/40914327-556ab5ae-682a-11e8-8db0-316cd08ba124.png)

**Comment by vickramdhawal** [comment]
this bugs is addressed and can be verified on the "release" branch.

**Comment by Zhanxin** [comment]
Now the build on update server is unavailable for testing, will regress on Monday.
