### ISSUE TITLE
Keyboard does not work.

### ISSUE THREAD

**Issue by dmitriiv84** [adobe/brackets#14406]
I installed Brakkets from the official site and after launch the program does not respond to the keyboard at all. OS - Ubuntu 16.04 x686. Brackets Version - sprint 12 build 1.12.0-17621

**Comment by navch** [comment]
@dmitriiv84 Thanks for reporting this issue. Can you please check whether this happens only on brackets 1.12 or this issue exist on every version of brackets let's say 1.11 or 1.13 pre-release.

@ayush can you please have a look into this. May be we can try to replicate this issue on our machines.

**Comment by dmitriiv84** [comment]
In version 1.11, the same problem exists in version 1.13 pre-release 3 all ok

**Comment by navch** [comment]
@dmitriiv84 That's really awesome. So Please use this pre-release for now. Brackets 1.13 will be live in this month. Closing this issue now, feel free to reopen this if you have any problem.
