### ISSUE TITLE
Click line number to quickly select line.

### ISSUE THREAD

**Issue by shoelaced** [adobe/brackets#14408]
### Description:

As a developer, it would be helpful to be able to to click the line number in a document to quickly select the entire line.

Better yet, ctrl + click multiple line numbers or click + drag down numbers to quickly select multiple lines.

**Comment by navch** [comment]
Thanks @shoelaced  for suggesting this.
Have you tried ctrl+alt+drag down its almost same as click + drag down. Anyways we will get back to you shortly on this feature request.

**Comment by navch** [comment]
@shoelaced I just found an extension for this. Even I tried this extension it works like a charm. Please try out this extension (https://github.com/talmand/Brackets-Select-Lines) named Select Lines

Closing this issue for now, feel free to reopen this if you have anything else.
