### ISSUE TITLE
[Brackets Auto-Update] Update failed message appears in update notification bar even after a successful update

### ISSUE THREAD

**Issue by ayushrathi15** [adobe/brackets#14411]
### Description
[Brackets Auto-Update] Update failed message appears in update notification bar even after a successful update

### Steps to Reproduce
1. Launch brackets 1.13.
2. Create a new file and type some text. Do not save this file.
3. Go to help > Check for updates.
4. Update dialogue appears. Click on Get it now.
5. Click on Update Now.
6. Brackets will close and update will begin.
7. Brackets will auto launch once update is done.
8. Update failed message appears in update notification bar even after a successful update.

**Expected behavior:** User should get a update successful message in update notification bar on successful update of brackets.

**Actual behavior:** Update failed message appears in update notification bar even after a successful update

Note : This issue has been encountered 3 times so far.

### Versions
Windows 10 64 Bit
Mac 10.13
Release 1.13 build 1.13.0-17624

**Comment by shubhsnov** [comment]
Fixed in https://github.com/adobe/brackets/pull/14412
