### ISSUE TITLE
Project name is not displayed in title bar on launch and shows the previous file name on closing all the files.

### ISSUE THREAD

**Issue by yprasad1** [adobe/brackets#14422]
### Description
Project name is not displayed in title bar on launch and shows the previous file name on closing all the files.

[Description of the bug or feature]
When Brackets is launched titlebar just shows "Brackets" instead of [Project name - Brackets] and when all open files are closed, titlebar continues to show the last closed file's path & name.

### Steps to Reproduce
1. launch Brackets
2. Open a file
3. Close the file

**Expected behavior:** [What you expected to happen]
When Brackets is launched titlebar shows [Project name - Brackets] 
When all open files are closed, titlebar shows [Project name - Brackets] 

**Actual behavior:** [What actually happened]
When Brackets is launched titlebar just shows "Brackets" 
when all open files are closed, titlebar continues to show the last closed file's path & name

### Versions
Brackets prerlease: 1.13.0-17693

Platform: All platforms

**Comment by sobisht** [comment]
Fixed with PR https://github.com/adobe/brackets/pull/14421
