### ISSUE TITLE
Error Renaming File | Live Preview Error in Brackets

### ISSUE THREAD

**Issue by Dan3DTV** [adobe/brackets#14444]
![screenshot 3](https://user-images.githubusercontent.com/40477254/41784940-feb00dc0-75f5-11e8-9893-cf44adb3354c.png)

**This picture might explain why I cannot rename a SINGLE file...**

![screenshot 4](https://user-images.githubusercontent.com/40477254/41785016-3431e540-75f6-11e8-94ee-7f6cd248e175.png)

**This picture might explain why I cannot live preview a SINGLE file.**

**Comment by Dan3DTV** [comment]
I will delete Brackets if no one answers...

**Comment by ayushrathi15** [comment]
Hi @Dan3DTV,

Make sure that you are in a user-writable location. By default Brackets opens the Getting Started-project, which is read-only. To open a new project:

Go to File -> Open Folder
Navigate to user writable directory (such as My Documents on Windows)
Create a new folder there
Open the said folder with Brackets by selecting it and click Select Folder
You can now use Brackets to create files, sub-folders etc to said folder.

**Comment by ayushrathi15** [comment]
Hi @Dan3DTV 

I am closing this issue.
Please feel free to reopen it in case you have any queries.

**Comment by JonHilderbrand** [comment]
I am having the same problem. Followed the instructions to the letter and am still
![2018-11-30](https://user-images.githubusercontent.com/45478744/49271922-a13b4a80-f43d-11e8-8e91-a139a5e8eceb.png)
 getting the same message.

**Comment by cpe-2001** [comment]
i created this very quickly you need so save as first to rename it
