### ISSUE TITLE
Quick Find and Replace (CTRL + C and CTRL + H) not working

### ISSUE THREAD

**Issue by vixson** [adobe/brackets#14457]
### Description

Selection Quick find, searches previous string typed in the search box

### Steps to Reproduce

1. Cursor select a group of text on the editor. eg:  **Hello**
2. Press CTRL + F or CTRL + H.
    **NOTE** for the first instants, it would makes the search for the selected text.
3. Type in some text on the search box. eg: **Helloxyz**.
4. Repeat **step 1 and 2**, This time select another text eg: **World**.
    **NOTICE** the previous text **Helloxyz** would still be showing in the search box.

**Expected behavior:** It was suppose to search for the new selected text **World**

**Actual behavior:** It still makes the search on the previous text **Helloxyz**

### Versions

**OS**: windows 10 pro (Creators Update)
**Bracket Version**: 1.11

**Comment by ayushrathi15** [comment]
@vixson This issue does not exist in the latest release of brackets.
Please upgrade to Brackets 1.13.

**Comment by vixson** [comment]
Sorry am already using **Bracket Version:** 1.13 **not** 1.11, I found the issue in v1.13
