### ISSUE TITLE
I'm asking explanation how to build and compile Brackets as Linux app

### ISSUE THREAD

**Issue by abdulbadii** [adobe/brackets#14478]
Sorry I am just I'm just desperate not knowing where or whom I am supposed to ask.
Now I am asking clear explanation on how to build and compile Brackets as a Linux application.
Anybody would sincerely help me ?
Thanks in advance

**Comment by sobisht** [comment]
You can have a look at this
https://github.com/adobe/brackets-shell/wiki/Building-Brackets-Shell
