### ISSUE TITLE
Live syntax Heigithing for PHP

### ISSUE THREAD

**Issue by JohnyByk** [adobe/brackets#14484]
It's possible to configure (without install php binaries) Bracket for syntax error heighliting (when you made error in Aptana this line is heighlighted).

I tried a lot of solutions and plugin but nothing dosen't work.

I want change Ecclipse to Brackets becasue Brackets is better (faster, modern) but this feature is very needed. Without these feature still i must use Eclipse :(

Regards

**Comment by navch** [comment]
Currently brackets doesn't support PHP. As some plugins are available for that but those don't work that well. We have this feature in our roadmap. So closing this for now.
