### ISSUE TITLE
Problem with selection

### ISSUE THREAD

**Issue by Tumite** [adobe/brackets#14491]
Hello guys!

I have a problem when i want to select something ina  doc.
https://prnt.sc/k9rvb8
This os is a windows server 2016.
When i tried on my desktop machine this problem is not have, just in win server machine.
Any help?

Release 1.13 build 1.13.0-17696 (release 49d29a8bc) 
build timestamp: Thu Jun 14 2018 08:13:54 GMT+0100

**Comment by rakibulmuhajir** [comment]
i had "color the tag name" extension installed, which caused this issue

**Comment by navch** [comment]
Cool. Closing this.
