### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Abasalt-yar** [adobe/brackets#14493]
Hello.  When I relaunch the brackets all settings or the others like themes or font-size and ... Goes to the default!
also, live preview
&
help list [ctrl + space] [i'm not sure about the name[help list] ]
&
I reinstall it too. but not working and Goes to the default!

**Comment by Abasalt-yar** [comment]
also, live preview
&
help list [ctrl + space] [i'm not sure about the name[help list] ]

**Comment by navch** [comment]
Please check %appdata%/Brackets/brackets.json
Is this getting modified when you change any settings?
Are you changing the setting in right file? I mean to say when you say open prefs file it opens both file default prefs and brackets.json mentioned above, you have to make changes in brackets.json.
On reopening, entries are there in brackets.json which you modified? Are you creating any json errors in that case it will not respect your preference it will goes to default?

**Comment by Abasalt-yar** [comment]
@navch I fixed it I Uninstall it manually and then this was fixed  . thanks of you help.
