### ISSUE TITLE
Is it possible to see both CSS and html on the same screen [noobie]

### ISSUE THREAD

**Issue by raboush2** [adobe/brackets#14510]
Hey - Sorry I am not sure whether this is the correct place to ask this question but I am wondering if you can place your .css file and .html file on the same screen instead of having to click back and forth between the two. THANKS!

Rami

### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by navch** [comment]
Try verticle/horizontal split. You can find this icon in the files panel. (In front of word Working files)

**Comment by raboush2** [comment]
![image](https://user-images.githubusercontent.com/42186179/44049216-7f0f5ab4-9f01-11e8-8e58-b062d1308c66.png)

That's exactly it! Thank you so much, Naveen.

Rami
