### ISSUE TITLE
Exposing removeFromWorkingSet() API seems error prone

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#1451]
A few sprints ago we changed removeFromWorkingSet() from a private method to a public one, to support #1197 (see 59e40a9).

It seems easy to misread this as the API to call when you want the same effect as the user clicking the "X" button in the working set.  However, it's actually a low-level model API that doesn't handle prompting for unsaved changes, etc.  (The FILE_CLOSE command would be the right thing to call).

I propose we change removeFromWorkingSet() back to private, and have the DocumentCommandHandlers error case call notifyFileDeleted() instead (which is more semantically correct anyway, and is already a public API).

**Comment by JeffryBooher** [comment]
@peterflynn can we close this? The API has been deprecated and removed with SplitView
