### ISSUE TITLE
Default plugin DebugCommands causing Brackets 1.13 not to start up.

### ISSUE THREAD

**Issue by Andrew-Snell** [adobe/brackets#14517]
Hi Good Day 

I have installed brackets 1.13 about a month ago and been having a issue with a default plugin called DebugCommands, this plugin is causing brackets not to start up, does anyone have the same issue ?.

I enabled and disabled each extension one by one to see which extension is causing the issue.

I am running Windows 10, Chrome Version 68.0.3440.106

**Comment by navch** [comment]
There is no update in this extension since long. Can you please share your console log? Go to Debug -> Show developer tools 
Then please paste that log here.

**Comment by Andrew-Snell** [comment]
Hi navch, I had to enable plugin DebugCommands here is the console log as requested, 

Less has finished and no sheets were loaded.
2/utils/ExtensionUtils.js:269 Default extension has been disabled on startup: DebugCommands
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-]
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-[
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - start
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "staticServer": timeout(anonymous function) @ /utils/NodeDomain.js:144
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "zaggino.brackets-eslint": timeout(anonymous function) @ /utils/NodeDomain.js:144
/extensibility/Package.js:579 [Extensions] Failed to connect to node Arguments[1](anonymous function) @ /extensibility/Package.js:579
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "AutoUpdate": timeout(anonymous function) @ /utils/NodeDomain.js:144
main.js:589 AutoUpdate : node domain could not be initialized.(anonymous function) @ main.js:589
https://s3.amazonaws.com/extend.brackets/registry.json?_=1534423114765 Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
https://health.brackets.io/healthDataLog Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
HealthDataManager.js:203 Error in sending Health Data. Response : undefined. Status : error. Error : (anonymous function) @ HealthDataManager.js:203
https://cc-api-data.adobe.io/ingest Failed to load resource: net::ERR_NETWORK_IO_SUSPENDED
HealthDataManager.js:232 Error in sending Adobe Analytics Data. Response : undefined. Status : error. Error : (anonymous function) @ HealthDataManager.js:232

**Comment by navch** [comment]
Are you able to start brackets in this instance as per these logs DebugCommand is disabled in this brackets instance? Apart from this Node is not able to start. A lot of feature in brackets depends on Node but this should not cause any problem in brackets launch. I don't know why Node is not initialized. But If rest of the things are fine maybe you can try reinstalling.

**Comment by Andrew-Snell** [comment]
Hi navch

I have reinstalled brackets 1.13 as per request, I am having an issue with brackets not starting up. I have copied and pasted my console output below.

Less has finished and no sheets were loaded.
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-]
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-[
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - start
main.js:313 AutoUpdate : updateHelper.json cannot be parsed, does not exist
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - send,,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":1}
NodeDebugUtils.js:114 [node-log 3:37:22 PM] WebSocketServer - received - {"type":"connect","url":"http://127.0.0.1:6169/HTML%20and%20CSS/index.html"}
NodeDebugUtils.js:114 [node-log 3:37:22 PM] emitting connect event
NodeDebugUtils.js:114 [node-log 3:37:22 PM] WebSocketServer - received - {"type":"message","message":"{\"method\":\"DocumentRelated\",\"related\":{\"scripts\":{\"http://127.0.0.1:6169/HTML%20and%20CSS/main.js\":true},\"stylesheets\":{\"http://127.0.0.1:6169/HTML%20and%20CSS/main.css\":[\"http://127.0.0.1:6169/HTML%20and%20CSS/main.css\"]}}}"}
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - connect - [1,"http://127.0.0.1:6169/HTML%20and%20CSS/index.html"]
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - message - [1,"{\"method\":\"DocumentRelated\",\"related\":{\"scripts\":{\"http://127.0.0.1:6169/HTML%20and%20CSS/main.js\":true},\"stylesheets\":{\"http://127.0.0.1:6169/HTML%20and%20CSS/main.css\":[\"http://127.0.0.1:6169/HTML%20and%20CSS/main.css\"]}}}"]
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - send,1,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":2}
NodeDebugUtils.js:114 [node-log 3:38:26 PM] WebSocketServer - received - {"type":"message","message":"{\"id\":2}"}
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - message - [1,"{\"id\":2}"]
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - send,1,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":3}
NodeDebugUtils.js:114 [node-log 3:41:05 PM] WebSocketServer - received - {"type":"message","message":"{\"id\":3}"}
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - message - [1,"{\"id\":3}"]
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - send,1,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":4}
NodeDebugUtils.js:114 [node-log 3:41:35 PM] WebSocketServer - received - {"type":"message","message":"{\"id\":4}"}
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - message - [1,"{\"id\":4}"]

**Comment by navch** [comment]
Not really sure why brackets is not starting. Are you able to start brackets after disabling any extension? Yes then which extension? Can you please share some more details like this happens on any project launch or normal brackets open? What happens if you delete %appdata%/brackets and then relaunch?

**Comment by Andrew-Snell** [comment]
Hi navch, I managed to change the the default language for brackets by going to Debug->switch language from system default to English UK. Brackets start up with no error messages but today brackets took three attempts to start up, I may have a buggy extension I have included my console output below, 

Less has finished and no sheets were loaded.
2/command/KeyBindingManager.js:747 Cannot assign Tab to brackets_html_boilerplate.expandWithTab. It is already assigned to brackets_html_boilerplate.expandWithTab_addBinding @ /command/KeyBindingManager.js:747
/utils/ExtensionLoader.js:227 [Extension] failed to load C:/Users/Andrew_2/AppData/Roaming/Brackets/extensions/user/brackets-beautify - Error: Load timeout for modules: i18n!nls/strings_unnormalized4,i18n!nls/strings,nls/strings
http://requirejs.org/docs/errors.html#timeouterrback @ /utils/ExtensionLoader.js:227
/utils/ExtensionLoader.js:227 [Extension] failed to load C:/Users/Andrew_2/AppData/Roaming/Brackets/extensions/user/brackets-display-shortcuts - Error: Load timeout for modules: i18n!nls/strings_unnormalized4,i18n!nls/strings,nls/strings
http://requirejs.org/docs/errors.html#timeouterrback @ /utils/ExtensionLoader.js:227
/utils/ExtensionLoader.js:227 [Extension] failed to load C:/Users/Andrew_2/AppData/Roaming/Brackets/extensions/user/ivogabe.icons - Error: Load timeout for modules: dist/preset-dictionary,dist/user-dictionary
http://requirejs.org/docs/errors.html#timeouterrback @ /utils/ExtensionLoader.js:227
/utils/ExtensionLoader.js:227 [Extension] failed to load C:/Users/Andrew_2/AppData/Roaming/Brackets/extensions/user/dnbard.extensions-rating - Error: Load timeout for modules: vendor/q,achievements/achievement,locale/en-US,locale/it,locale/ro,locale/es,locale/ca-ES,locale/sv-SE,locale/tr,locale/uk,locale/de-DE,locale/fr,locale/ru,locale/zh-TW,locale/pl
http://requirejs.org/docs/errors.html#timeouterrback @ /utils/ExtensionLoader.js:227
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-]
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-[
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - start
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "webSocketTransport": timeout(anonymous function) @ /utils/NodeDomain.js:144
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "nodeSocketTransport": timeout(anonymous function) @ /utils/NodeDomain.js:144
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "fileWatcher": timeout(anonymous function) @ /utils/NodeDomain.js:144
/filesystem/FileSystem.js:967 Failed to watch root:  C:/Users/Andrew_2/Documents/Desktop/Programing/ timeout
/project/ProjectManager.js:800 Error watching project root:  C:/Users/Andrew_2/Documents/Desktop/Programing/ timeout(anonymous function) @ /project/ProjectManager.js:800
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "launcher": timeout(anonymous function) @ /utils/NodeDomain.js:144
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "FindInFiles": timeout(anonymous function) @ /utils/NodeDomain.js:144
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "zaggino.brackets-eslint": timeout(anonymous function) @ /utils/NodeDomain.js:144
/extensibility/Package.js:579 [Extensions] Failed to connect to node Arguments[1](anonymous function) @ /extensibility/Package.js:579
/utils/NodeDomain.js:144 [NodeDomain] Error loading domain "AutoUpdate": timeout(anonymous function) @ /utils/NodeDomain.js:144
main.js:589 AutoUpdate : node domain could not be initialized.(anonymous function) @ main.js:589

If I delete %appdata%/brackets, brackets starts up with no issues, I am running brackets as a window user not as an administrator, does brackets need administrator rights to run ?.

**Comment by Andrew-Snell** [comment]
Hi navch

I have disabled the following extensions within brackets they are as following, 

1.Beautify.
2.Brackets Icons.
3.Display Shortcuts.
4.Extensions Rating.
5.HTML Boilerplate.

The following extensions I have not disabled are as following,

1.Monokai.
2.TypeScript.

Here is my console output from within brackets, 

Less has finished and no sheets were loaded.
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-]
/command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-[
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - start
main.js:313 AutoUpdate : updateHelper.json cannot be parsed, does not exist
2http://127.0.0.1:9222/json Failed to load resource: net::ERR_CONNECTION_REFUSED
NodeDebugUtils.js:114 [node-log 6:27:05 PM] webSocketTransport closed
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - send,,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":1}
NodeDebugUtils.js:114 [node-log 6:27:39 PM] WebSocketServer - received - {"type":"connect","url":"http://127.0.0.1:3433/index.html"}
NodeDebugUtils.js:114 [node-log 6:27:39 PM] emitting connect event
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - connect - [1,"http://127.0.0.1:3433/index.html"]
NodeDebugUtils.js:114 [node-log 6:27:39 PM] WebSocketServer - received - {"type":"message","message":"{\"method\":\"DocumentRelated\",\"related\":{\"scripts\":{},\"stylesheets\":{\"http://127.0.0.1:3433/main.css\":[\"http://127.0.0.1:3433/main.css\"]}}}"}
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - message - [1,"{\"method\":\"DocumentRelated\",\"related\":{\"scripts\":{},\"stylesheets\":{\"http://127.0.0.1:3433/main.css\":[\"http://127.0.0.1:3433/main.css\"]}}}"]
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - send,1,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":2}
NodeDebugUtils.js:114 [node-log 6:27:49 PM] WebSocketServer - received - {"type":"message","message":"{\"id\":2}"}
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - message - [1,"{\"id\":2}"]
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - send,1,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":3}
NodeDebugUtils.js:114 [node-log 6:32:18 PM] WebSocketServer - received - {"type":"message","message":"{\"id\":3}"}
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - message - [1,"{\"id\":3}"]
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - send,1,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":4}
NodeDebugUtils.js:114 [node-log 6:34:06 PM] WebSocketServer - received - {"type":"message","message":"{\"id\":4}"}
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - message - [1,"{\"id\":4}"]
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - send,1,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":5}
NodeDebugUtils.js:114 [node-log 6:35:03 PM] WebSocketServer - received - {"type":"message","message":"{\"id\":5}"}
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - message - [1,"{\"id\":5}"]
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - send,1,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":6}
NodeDebugUtils.js:114 [node-log 6:35:22 PM] WebSocketServer - received - {"type":"message","message":"{\"id\":6}"}
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - message - [1,"{\"id\":6}"]
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - send,1,{"method":"Runtime.evaluate","params":{"expression":"_LD.hideHighlight()"},"id":7}
NodeDebugUtils.js:114 [node-log 6:36:28 PM] WebSocketServer - received - {"type":"message","message":"{\"id\":7}"}
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:67 NodeSocketTransport - event - message - [1,"{\"id\":7}"]

I hope this helps you.

**Comment by Andrew-Snell** [comment]
Hi navch 

Brackets is opening on it's first attempt with no issues, I have disabled the following extensions, they are as follows,

1. Beautify.
2. Display Shortcuts.
3. Extensions Rating.
4. HTML Boilerplate.

The following extension are enabled, they are as follows,

1.Brackets Icons.
2.Monokai Theme.
3.TypeScript.

I will work through the disabled extensions to see which one is causing the issue, Thank you for your help. I will close this issue.

**Comment by navch** [comment]
Sure @Andrew-Snell Great Job. Please update here as well about extension which i causing this problem

**Comment by Andrew-Snell** [comment]
Hi @navch 

I have been running brackets with the Beautify extension enabled and causing brackets not to load correctly, I have disabled this extension and brackets loaded five times in a row without and issue.

Regards
Andrew

**Comment by navch** [comment]
Hi @Andrew-Snell This is working fine for me, As per the extension's use guide

`Brackets Beautify can be run manually on the whole file or on a selection. Use the Toolbar Button with the wand icon, the menu entry Edit > Beautify, the context-menu entry Beautify, or one of the keyboard shortcuts Ctrl-Alt-B (Windows/Linux), Ctrl-Shift-L (Windows), Cmd-Shift-L (Mac), or define your own.

Alternatively it can be enabled to run automatically on save. Use the menu entry Edit > Beautify on Save or the more advanced settings to activate.` 

This extension should not kick in on load. Could you please try to debug this?

**Comment by Andrew-Snell** [comment]
Hi @navch 

I have enabled Beautify extension and will post debug info. 

Regards
Andrew

**Comment by Andrew-Snell** [comment]
Hi @navch 

I have been using brackets for the past two months with no issues, as result I am closing this issue, Thank you for your help.

Regards
Andrew Snell
