### ISSUE TITLE
Live Preview opens four tabs in Chrome

### ISSUE THREAD

**Issue by JBJblaze** [adobe/brackets#14539]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`? _Yes._
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported? _Yes._
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

_When I turn on Live Preview (without Experimental enabled), four tabs in Chrome are opened simultaneously._

### Steps to Reproduce

_1. Reload Brackets without Extensions.
2. Click the lightning bolt button for Live Preview.
3. Check Chrome to find that four tabs are open with the preview loading._

**Expected behavior:** _Chrome to open with just one tab for the Live Preview._

**Actual behavior:** _Chrome opens with four tabs loading the Live Preview._

### Versions

Please include the OS and what version of the OS you're running. _Windows 10 Home 1803 17134.285_
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS) _Release 1.13 build 1.13.0-17696 (release 49d29a8bc)_

**Comment by Andrew-Snell** [comment]
Hi @JBJblaze 

Have enabled " Enable Experimental Live Preview" in the file tag ?, see if this helps, are you using the keyboard combination to enable live preview ( Ctrl + Alt + P ) and click on the orange lighting bolt to open live preview in chrome.

Regards
Andrew

**Comment by JBJblaze** [comment]
This does work, yes. I think my aforementioned issue tends to occur on occasion, rather than frequently.

**Comment by Andrew-Snell** [comment]
Hi @JBJblaze 

If your issue has been resolved, please close this issue, Thank you.

Regards
Andrew
