### ISSUE TITLE
Very bad font rendering (Brackets 1.13) [Linux]

### ISSUE THREAD

**Issue by NusryNizam** [adobe/brackets#14552]
Font rendering is very bad in brackets. 
Btw, this solution `--disable-direct-write` didn't work either.

OS Version: Lubuntu 18.04 with XFCE (64-bit)

![1111](https://user-images.githubusercontent.com/24385617/46472813-fff89500-c7fb-11e8-8f99-3df29703354a.png)

**Comment by hk456** [comment]
I'm having the same issue with Brackets, but it's with Ubuntu 20.04 LTS relese (64 bit)

**Comment by gaganyadav80** [comment]
Goto your fonts settings and set Antialiasing to Grayscale. It will be better.
