### ISSUE TITLE
How can I close eslint tool or disable [no-console] and ['no-undef']

### ISSUE THREAD

**Issue by huanglw** [adobe/brackets#14567]
![image](https://user-images.githubusercontent.com/24634832/47056737-821b8d00-d1f0-11e8-9c96-fb7eb16371b4.png)
my code like above pic, it's really a problem for me. it seems every thing is okay, but there are many errors like [no-undef] or [no-console]

**Comment by navch** [comment]
These are eslint errors. You can configure .eslintrc file, If you don't want to get these error you can specify this in that file, Please check out this to know more https://eslint.org/docs/user-guide/configuring
I guess this file should be there at your root folder if you don't find it there then you can add a file there. Closing this bug, Please feel free to reopen this if you face any other issues.
