### ISSUE TITLE
Kotlin language support

### ISSUE THREAD

**Issue by HasnainAD** [adobe/brackets#14594]
Brackets does not seem to be usable for Kotlin language. Please add Kotlin language support as new requested feature.

**Comment by x13machine** [comment]
Language support is done through CodeMirror. CodeMirror supports Kotlin, but it's not in the src/language/languages.json file. There's a bunch of languages that CodeMirror supports but aren't in the languages.json file. I'll submit a pull request shortly.

You add to add this to src/language/languages.json:

```
    "kotlin": {
        "name": "Kotlin",
        "mode": ["clike", "text/x-kotlin"],
        "fileExtensions": ["kt"],
        "blockComment": ["/*", "*/"],
        "lineComment": ["//"]
    }
```

**Comment by HasnainAD** [comment]
@x13machine Hi. I couldn't find the the file src/language/languages.json file. I am using windows.

**Comment by x13machine** [comment]
I dunno, build it from scratch?

**Comment by cyberespia** [comment]
To date, I've searched for an extension to Kotlin and I can not find any. - Please add Kotlin language support.
