### ISSUE TITLE
LB: LOC: fr_FR: first letter in the beginning of the paragraph has to be in Upper case : “cette mise à jour comprend des correctifs…”.

### ISSUE THREAD

**Issue by aman-lion** [adobe/brackets#14600]
**Problem:** First letter in the beginning of the paragraph has to be in Upper case

**EN Source:**  This update includes fixes to improve overall performance of Brackets from launch to key coding workflows.

**Actual Translation:** cette mise à jour comprend des correctifs visant à améliorer les performances générales Brackets, du lancement aux principaux workflows de codage.

**Expected Translation:** Cette mise à jour comprend des correctifs visant à améliorer les performances générales Brackets, du lancement aux principaux workflows de codage.

**FR Screen:**

![1](https://user-images.githubusercontent.com/18438761/48999169-d153c680-f17b-11e8-8ae9-50c240fe34b4.png)

**Comment by RuchiAgrawalAdobe** [comment]
This is fixed now:

![image](https://user-images.githubusercontent.com/31060760/49005323-6bbc0600-f18c-11e8-86b5-09ce1585c949.png)
