### ISSUE TITLE
Spam on brackets blog.

### ISSUE THREAD

**Issue by gobijan** [adobe/brackets#14623]
Don't know how this spam made it to the brakets blog but now it's there:

http://blog.brackets.io/2019/01/03/triumphant-strategies-intended-for-data-room-services-which-you-can-use-at-this-time/

**Comment by DavidCao22** [comment]
Update on this issue:

The first few blog posts are now all spam. Starting either yesterday or today, the blog sometimes redirects me to spammy links

**Comment by anewuser** [comment]
@jasonsanjose  @njx @peterflynn @gruehle @swmitra @saurabh95

**Comment by TheSkwiggs** [comment]
They just fixed this issue. @navch probably need to close this, too :)

**Comment by navch** [comment]
Thanks everybody for reporting this.
