### ISSUE TITLE
Blog entries don't seem legitimate

### ISSUE THREAD

**Issue by TheSkwiggs** [adobe/brackets#14629]
I'm subscribed to the RSS feed of the Brackets blog on the official website (http://blog.brackets.io/) but for the past few days it seems some illegitimate person or entity got hold of the credentials and started publishing some random crap.

It looks like blog posts were authored by @RaymondLim but the contents just look like some deceitful ads.

Could someone look into this ?

CF attached screenshots of recent blog posts.
<img width="1677" alt="screenshot 2019-01-09 at 12 45 32" src="https://user-images.githubusercontent.com/6209874/50897578-d8255880-140c-11e9-9951-b0fa9b1c1d78.png">
<img width="1339" alt="screenshot 2019-01-09 at 12 47 41" src="https://user-images.githubusercontent.com/6209874/50897592-e1aec080-140c-11e9-8bf0-738cc16cdc91.png">

Highlighted link leads to this:
<img width="1680" alt="screenshot 2019-01-09 at 12 48 55" src="https://user-images.githubusercontent.com/6209874/50897638-0145e900-140d-11e9-9499-4897b7262a68.png">

**Comment by badcat** [comment]
Agreed - this has been going on for some time.   Maybe Adobe / Brackets team could also update to WordPress 5.0.2 too?

**Comment by navch** [comment]
Looks like issue got fixed. So closing this.
