### ISSUE TITLE
Failed to install Brackets.Release.1.12.64-bit on Ubuntu 18.10 x64

### ISSUE THREAD

**Issue by smartwebdever** [adobe/brackets#14632]
Well, I failed to install Brackets.Release.1.12.64-bit
Att. log’s and some information.

`smartwebdev@smartwebdev-notebook-ubuntu:~$ sudo -i

root@smartwebdev-notebook-ubuntu:~# dpkg -i '/home/smartwebdev/Downloads/Brackets.Release.1.13.64-bit.deb' 
Selecting previously unselected package brackets.
(Reading database ... 167945 files and directories currently installed.)
Preparing to unpack .../Brackets.Release.1.13.64-bit.deb ...
Unpacking brackets (1.13.0-17696) ...
dpkg: dependency problems prevent configuration of brackets:
 brackets depends on gconf-service; however:
  Package gconf-service is not installed.
 brackets depends on libgconf-2-4 (>= 2.31.1); however:
  Package libgconf-2-4 is not installed.
 brackets depends on libgtk2.0-0 (>= 2.24.0); however:
  Package libgtk2.0-0 is not installed.
 brackets depends on libpango1.0-0 (>= 1.22.0); however:
  Package libpango1.0-0 is not installed.
 brackets depends on libcurl3; however:
  Package libcurl3 is not installed.

dpkg: error processing package brackets (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 brackets
`
Well, it can be resolve via install folloing components : `gconf-service, libgconf-2-4, libgtk2.0-0, libpango1.0-0, libcurl3.`

For installing this compomnents first – I switch to previligated user to run shell commands as auper user

`sudo -i`

After I have run following commands :

`sudo apt install gconf-service
sudo apt install libgconf-2-4
sudo apt install libgtk2.0-0
sudo apt install libpango1.0-0
sudo apt install libcurl3`

All of components, EXCEPTing libcurl3 was installed.
Well, in Ubuntu 18.10 imposible install libcurl3 as I can see.

I think this problemm will be mass for beginers as me, and I will be realy helpfuel to get support from community or software developer.
Appreciated. Peter.

**Comment by Qik000** [comment]
> I have libcurl4 installed but to no avail. Bracket.io doesn't seem to be compatiable with libcurl4
> Package libcurl3 is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
> libcurl4:i386 libcurl4
> 
> E: Package 'libcurl3' has no installation candidate
> someone@caslab-:/$ sudo apt install libcurl4
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> libcurl4 is already the newest version (7.61.0-1ubuntu2.2).
> someone@caslab:/$ sudo dpkg -i ~/Downloads/Brackets.Release.1.13.64-bit.deb
> (Reading database ... 335581 files and directories currently installed.)
> Preparing to unpack .../Brackets.Release.1.13.64-bit.deb ...
> Unpacking brackets (1.13.0-17696) over (1.13.0-17696) ...
> dpkg: dependency problems prevent configuration of brackets:
> brackets depends on libcurl3; however:
> Package libcurl3 is not installed.
> 
> dpkg: error processing package brackets (--install):
> dependency problems - leaving unconfigured
> Processing triggers for hicolor-icon-theme (0.17-2) ...
> Errors were encountered while processing:
> brackets

The same happens to me on Ubuntu 18.04.

**Comment by cosmin-vi** [comment]
@smartwebdever , @carolsand , @Qik000 

The Brackets build requires libcurl3, while Ubuntu & Mint switched to libcurl4. 
Until they fix the Brackets build (which is taking an absurdly long time), you need to unpack the Brackets build, change dependency and repack.

Instructions here: https://github.com/adobe/brackets/issues/14338#issuecomment-400378169
