### ISSUE TITLE
New extension for new file templates

### ISSUE THREAD

**Issue by yeohsoonkeat** [adobe/brackets#14656]
I’ve made an extension for making new file with a basic templates and register it to bracket registry. So can i make a pull request  ? If so, should the new extension be in scr/extension/sample or in scr/extension/dev ? And how do i tell bracket about the extension as said in the guideline, in package.json ? 

Sorry I’m a beginner.

**Comment by navch** [comment]
Publish your extension to registry. Follow this link to upload -  https://github.com/adobe/brackets/wiki/How-to-write-extensions

Brackets will automatically look for package.json file in a specific folder. Just upload your extension and install it via extension dialogue on brackets. You can look for some other extension at https://registry.brackets.io/ so you can write you package.json properly.
Closing this Issue. Feel free reopen if you still have any question.
