### ISSUE TITLE
File tree collapses by itself when opening directories.

### ISSUE THREAD

**Issue by sykeben** [adobe/brackets#14666]
When I open a subdirectory in the file tree, it completely collapses, and I have to uncollapse the directory I was working in. Basically, when I open or close a directory, the whole file tree collapses. This is really annoying, and I really need help fixing it.

Here's a GIF showing what's happening:
![2019-03-12_13-49-35](https://user-images.githubusercontent.com/33205078/54223586-2cf95400-44ce-11e9-9526-3afb635f9bb0.gif)

**Comment by sykeben** [comment]
Is anyone going to help fix this? It's been 13 days, and it's really bugging me.

**Comment by sykeben** [comment]
Okay, it's been more than a month? Has this been fixed yet?

**Comment by swmitra** [comment]
@sykeben Did you try reloading brackets without extensions? Looks to me a problem caused by some extension which is modifying file tree DOM.

**Comment by sykeben** [comment]
Ill take a look, I tried that before but I don't remember it working, but I'll check again for my own sanity.

**Comment by sykeben** [comment]
So, I reloaded without extensions (through the debug menu) and the issue still happens. If you need to know, the version I have is `windows-release-1.13.1 fc2ebbeea`.

**Comment by shubhsnov** [comment]
Thanks for reporting this @sykeben. We're looking into the issue at the moment. Meanwhile can you help us by checking the console in developer tools, and report if there are any warnings or errors logged.

Also, can you provide us with the list of extensions that you currently work with. Thanks again for reporting. Allow us sometime to debug the issue.

**Comment by sykeben** [comment]
I'll take a look at the logs, and send you my list of extensions. Thanks a ton for looking into this!

**Comment by sykeben** [comment]
Below are the logs (I couldn't copy-paste so I had to insert screenshots).  

**With Extensions**
![image](https://user-images.githubusercontent.com/33205078/56854754-ca3b0b00-6909-11e9-80e8-bbbf91fd619a.png)
![image](https://user-images.githubusercontent.com/33205078/56854762-db841780-6909-11e9-9fe1-8205cb53b01b.png)
![image](https://user-images.githubusercontent.com/33205078/56854766-e474e900-6909-11e9-9c33-025233c60241.png)  

**Without Extensions**
![image](https://user-images.githubusercontent.com/33205078/56854781-230aa380-690a-11e9-80c3-06bade046393.png)
![image](https://user-images.githubusercontent.com/33205078/56854786-3289ec80-690a-11e9-9bb9-073e4dfa9cfc.png)
![image](https://user-images.githubusercontent.com/33205078/56854792-41709f00-690a-11e9-9184-b03595915697.png)
![image](https://user-images.githubusercontent.com/33205078/56854796-4c2b3400-690a-11e9-9f75-e5d8ad9e99c4.png)  

Once again, thanks for all your help!

**Comment by shubhsnov** [comment]
Thanks a ton for the error logs. I'll take a look into this. Also, do provide me with list of extension if you can.

**Comment by sykeben** [comment]
Here's a list of non-default extensions I'm currently running:
- [Beautify 2.8.0](https://github.com/brackets-beautify/brackets-beautify)
- [Brackets Icons 1.5.7](https://github.com/ivogabe/Brackets-Icons)
- [Indent Guides 1.3.11](https://github.com/lkcampbell/brackets-indent-guides)
- [JSHint 2.2.20](https://github.com/cfjedimaster/brackets-jshint)
- [Reasonable Comments 1.3.0](https://github.com/peterflynn/reasonable-comments)

**Comment by shubhsnov** [comment]
Thanks.

**Comment by shubhsnov** [comment]
I am not able to reproduce this on my machine. But, this might be due to a corrupted state. 

Try this:
- Completely close Brackets (very important)
- Open Run Command Box (Win + R)
- Paste `%appdata%`
- Open `Brackets` Folder
- Copy the `state.json` to some safe location, and then delete it from the Brackets folder
- Relaunch Brackets

You'll start over from a fresh state.
Check if the problem is solved. If so then probably something went wrong with the serialization of your existing state. 

If the problem still occurs, close Brackets again (important) and restore your original state.json back.

**Comment by sykeben** [comment]
Looks like moving the original `state.json` file away from the `Brackets` appdata folder fixed it. Thank you guys so much for helping me fix this.
