### ISSUE TITLE
No recent releases? (Just a query) 

### ISSUE THREAD

**Issue by ankushdas9** [adobe/brackets#14689]
I personally use Brackets a lot for my work - however, I don't see any recent releases. Can anyone shed some light on it?

P.S: I'm just curious about it.

**Comment by shubhsnov** [comment]
Hey @ankushdas9, we are planning a release very soon. We've integrated the Language Server Protocol in Brackets, and are currently working on the PHP reference app at the moment. Watch this space, we are hoping that the community will help propel Brackets even further now. :)

**Comment by Taariqq** [comment]
> Hey @ankushdas9, we are planning a release very soon. We've integrated the Language Server Protocol in Brackets, and are currently working on the PHP reference app at the moment. Watch this space, we are hoping that the community will help propel Brackets even further now. :)

WOW ... this is gReAt news. Very welcome.

**Comment by narayani28** [comment]
Brackets v1.14 is Live!! Please do use the new features and give us feedback.


Adobe Brackets team
