### ISSUE TITLE
</section> </body> </html> end tags all red. I've checked code and can't figure it out

### ISSUE THREAD

**Issue by cloudytea** [adobe/brackets#14707]
For my index.html, I can't find the route to my problem which is that the:
</section>
</body>
</html>
end tags are all red. 

I have checked my code 10 times over and can't find the issue. 

I am using brackets version 1.13 build 1.13.0-17696 on mac OS Mojave

The code is from a sample project i'm working on from a udemy course. 
--------------------------------------------------------------------------------------------
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <link rel="stylesheet" type="text/css" href="Vendors/css/normalize.css"> 
        <link rel="stylesheet" type="text/css" href="Vendors/css/grid.css"> 
        <link rel="stylesheet" type="text/css" href="Resources/css/style.css">
        <link href="https://fonts.googleapis.com/css?family=Lato:100,300,300i,400" rel="stylesheet" type='text/css'>
        <title>Omnifood</title>
    </head>

    <body>
        <header>
            <nav>
                <div class="row">
                    <img src="resources/img/logo-white.png" alt="Omnifood logo" class="logo">
                    <ul class="main-nav">
                        <li><a href="#">Food delivery</a></li>
                        <li><a href="#">How it works</a></li>
                        <li><a href="#">Our cities</a></li>
                        <li><a href="#">Sign up</a></li>
                    </ul>
            
                </div>
            </nav>
            <div class="hero-text-box">
                <h1>Goodbye junk food.<br>Hello super healthy meals.</h1>
                <a class="btn btn-full" href="#">I'm hungry</a>
                <a class="btn btn-ghost" href="#">Show me more</a>
            </div>
        </header>
        
        <section class="section-features">
            <div class="row">
                <h2>Get food fast &mdash; not fast food</h2>
                <p class="long-copy">
                    Hello, we’re Omnifood, your new premium food delivery service. We know you’re always busy. No time for cooking. So let us take care of that, we’re really good at it, we promise!
                </p>
            </div>
        
            <div class="row">
                <div class="col span-1-of-4">
                    <h3>Up to 365 days/year</h3>
                    <p>
                        Never cook again! We really mean that. Our subscription plans include up to 365 days/year coverage. You can also choose to order more flexibly if that's your style.
                    </p>
                </div>
                
                <div class="row">
                    <div class="col span-1-of-4">
                        <h3>Ready in 20 minutes</h3>
                        <p>
                        You're only twenty minutes away from your delicious and super healthy meals delivered right to your home. We work with the best chefs in each town to ensure that you're 100% happy.
                        </p>
                </div>
                    
                <div class="row">
                    <div class="col span-1-of-4">
                        <h3>100% organic</h3>
                        <p>
                        All our vegetables are fresh, organic and local. Animals are raised without added hormones or antibiotics. Good for your health, the environment, and it also tastes better!
                        </p>
                </div>
                    
                <div class="row">
                    <div class="col span-1-of-4">
                        <h3>Order anything</h3>
                        <p>
                        NWe don't limit your creativity, which means you can order whatever you feel like. You can also choose from our menu containing over 100 delicious meals. It's up to you!
                        </p>
                    </div>
                </div>
            </section>
    </body>
    
</html>

**Comment by shubhsnov** [comment]
The code is missing closing div tags for columns.
```html
<head>
    <link rel="stylesheet" type="text/css" href="Vendors/css/normalize.css">
    <link rel="stylesheet" type="text/css" href="Vendors/css/grid.css">
    <link rel="stylesheet" type="text/css" href="Resources/css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,300i,400" rel="stylesheet" type='text/css'>
    <title>Omnifood</title>
</head>

<body>
    <header>
        <nav>
            <div class="row">
                <img src="resources/img/logo-white.png" alt="Omnifood logo" class="logo">
                <ul class="main-nav">
                    <li><a href="#">Food delivery</a></li>
                    <li><a href="#">How it works</a></li>
                    <li><a href="#">Our cities</a></li>
                    <li><a href="#">Sign up</a></li>
                </ul>

            </div>
        </nav>
        <div class="hero-text-box">
            <h1>Goodbye junk food.<br>Hello super healthy meals.</h1>
            <a class="btn btn-full" href="#">I'm hungry</a>
            <a class="btn btn-ghost" href="#">Show me more</a>
        </div>
    </header>

    <section class="section-features">
        <div class="row">
            <h2>Get food fast &mdash; not fast food</h2>
            <p class="long-copy">
                Hello, we’re Omnifood, your new premium food delivery service. We know you’re always busy. No time for cooking. So let us take care of that, we’re really good at it, we promise!
            </p>
        </div>

        <div class="row">
            <div class="col span-1-of-4">
                <h3>Up to 365 days/year</h3>
                <p>
                    Never cook again! We really mean that. Our subscription plans include up to 365 days/year coverage. You can also choose to order more flexibly if that's your style.
                </p>
            </div>
        </div>

        <div class="row">
            <div class="col span-1-of-4">
                <h3>Ready in 20 minutes</h3>
                <p>
                    You're only twenty minutes away from your delicious and super healthy meals delivered right to your home. We work with the best chefs in each town to ensure that you're 100% happy.
                </p>
            </div>
        </div>

        <div class="row">
            <div class="col span-1-of-4">
                <h3>100% organic</h3>
                <p>
                    All our vegetables are fresh, organic and local. Animals are raised without added hormones or antibiotics. Good for your health, the environment, and it also tastes better!
                </p>
            </div>
        </div>

        <div class="row">
            <div class="col span-1-of-4">
                <h3>Order anything</h3>
                <p>
                    NWe don't limit your creativity, which means you can order whatever you feel like. You can also choose from our menu containing over 100 delicious meals. It's up to you!
                </p>
            </div>
        </div>

    </section>
</body>
```

The code below should work fine.
