### ISSUE TITLE
Where is the release-1.14-prerelease-1 tag on brackets-shell?

### ISSUE THREAD

**Issue by petronny** [adobe/brackets#14711]
Hi, I want to build brackets at `release-1.14-prerelease-1` from the source.
But I cannot find the corresponding tag in brackets-shell.
Which version of brackets-shell are you using to build `1.14-prerelease-1`?

**Comment by shubhsnov** [comment]
You can use the master branch itself. We didn't make any changes to brackets-shell for the pre-release.

**Comment by petronny** [comment]
Got it.
