### ISSUE TITLE
All Files deleted

### ISSUE THREAD

**Issue by bhenling** [adobe/brackets#14749]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by bhenling** [comment]
I just upgraded Brackets and it deleted every single one of my files that was in Brackets except the one that was open
HOW IS THIS POSSIBLE?

**Comment by bhenling** [comment]
looks like Brackets indiscriminately deletes all files in certain default  directories when upgrading. Horrible design.

**Comment by narayani28** [comment]
Sorry to hear that. Kindly provide OS and the workflow to recreate the issue to help us resolve the same.

**Comment by bhenling** [comment]
I had my files in the samples directory as that was the default save area.

**Comment by bhenling** [comment]
Wait, Abobe, already know of this problem from as far back as 2016 and chose to do Nothing about it???? absolutely nothing - I lost 4 months of files because of this unprofessional code. My image of Adobe is definitely different now. One thing to make a mistake, it is another thing to code something that causes damage, know about it for years, and then not fix. Especially since the fix is so easy.

https://github.com/adobe/brackets/issues/13729

**Comment by shubhsnov** [comment]
@bhenling Thank you for bringing this to our attention. We regret the inconvenience this has caused you.

The intention of Getting Started was to allow the users to get to know Brackets a bit, probably try out features like QuickEdit, and Live Preview before they start using it properly. The assumption from there onwards was that people would then move on to create their own projects using any custom location that they saw fit. Getting Started was never meant to be used as the default directory.

We have duly noted your feedback and will definitely address this in further releases. 

Also as a side note, in future, I would like to recommend the use of some version control system like git to maintain a remote copy of your work.

**Comment by bhenling** [comment]
All my code is in GIT, this was just notes from 4 months. True, I should have had it backed up, but did not put out in company repo as was just my work related notes. Was going to formalize it.
