### ISSUE TITLE
Platform specific download counts in brackets.io does not match with download counts on github

### ISSUE THREAD

**Issue by Nainabhandari8** [adobe/brackets#14748]
Platform specific download counts in brackets.io does not match with download counts on github

Example. The download counts in below url do not match with download counts on brackets.io: 
https://api.github.com/repos/adobe/brackets/releases/11325010

**Comment by yprasad1** [comment]
We should refer to https://api.github.com/repos/adobe/brackets/releases for the download count as this will include downloads for direct downloads from GitHub too.
