### ISSUE TITLE
CSS styling 

### ISSUE THREAD

**Issue by Shadowheron** [adobe/brackets#14787]
In CSS, Brackets does not recognize my classes. So when want to use css for a class, it totally ignores the class.

Expected behavior: [The CSS to recognize my class. ]

Actual behavior: [Brackets did not recognize the class.]

Running on windows 10 (latest version)

With default settings of brackets

  ####Versions

Release 1.14 prerelease build 1.14.0-17717

**Comment by shubhsnov** [comment]
Thanks for reporting this issue. Can you provide us with some more information, perhaps a reproducible scenario which we can use to debug the issue at our end?

**Comment by Shadowheron** [comment]
Thank you very much for concerning the issue have being resolved just a syntax error
