### ISSUE TITLE
Broken link to a theme

### ISSUE THREAD

**Issue by shamilsdq** [adobe/brackets#14796]
## VERSION
windows 10 home x64
brackets release 1.14 build 1.14.0-17740

## ISSUE - Broken link
Clicking **"more info"** on **"Ocelots_Theme"** in Extension Manager gives a 404 on Github.

**Comment by shubhsnov** [comment]
This is not a Brackets issue. Raise the bug here: https://github.com/OcelotDive/ocelots_theme
