### ISSUE TITLE
Tab Bug. 1.14

### ISSUE THREAD

**Issue by HachikoR** [adobe/brackets#14799]
Hello, I found a rather awkward bug in brackets. After adding support for php, tabulation between in the tag `<??>` / `<? php?>` - does not work. Earlier, when there was no php support, tabulation, although it worked poorly, but it worked, now completely refuses. If you do not understand, I'm talking about: you write code in `<? // code?>`, and the next line does not take into account spaces / tabs from the last line. 
Example:
`<?
    (here is the tab)$name = "Dennis";`
`(there is no tab)echo "Hello, $name"; /*<---------- Do you see it? There are no spaces, but in the last line - there are. */
?>`

#FIXBRACKETS #FIXPHP #FIXBRACKETSPHP #FIXPHPBRACKETS #PHP #BRACKETS #HELP #BUG #BRACKETSBUG #BUGBRACKETS
![Снимок](https://user-images.githubusercontent.com/49492348/58212937-29b5ec00-7cf9-11e9-8688-481e67dc0235.PNG)

**Comment by HachikoR** [comment]
Sorry if I did not write correctly, I do not know English well.

**Comment by shubhsnov** [comment]
Sorry to hear this. Thanks for taking out the time and reporting this issue.
As a preliminary check can you reload without extensions `(Debug->Reload Without Extensions)`, and tell us if the issue is still reproducible.

If it works then it might be an extension issue. This will help us debug the issue.

**Comment by HachikoR** [comment]
![Снимок](https://user-images.githubusercontent.com/49492348/58254889-72f75180-7d74-11e9-9255-a8df1bd70b5f.PNG)
I tried and .... no, it does not work: (

**Comment by shubhsnov** [comment]
Try setting the "smartIndent" preference to false in **brackets.json.**
`Debug -> Open Preferences File`

![image](https://user-images.githubusercontent.com/16770513/58307310-e43e0f80-7e1b-11e9-851b-8e4090ca3f39.png)

**Comment by HachikoR** [comment]
Hurray! Works! Thanks for the help :)
