### ISSUE TITLE
Brackets for PHP5

### ISSUE THREAD

**Issue by Yeehoo** [adobe/brackets#14802]
Hello!
I was getting error message for undefind php.exe.
I read some issues and I write in **brackets,json**:

```
"php": {
        "enablePhpTooling": true,
        "executablePath": "D:\\xampp\\php\\php.exe",
        "memoryLimit": "4095M",
        "validateOnType": "false"
    }
```
Now I get error message when I run php file via Brackets.

![image](https://user-images.githubusercontent.com/19960646/58441691-a6c3d580-80ec-11e9-85a1-9d7aa3e5ba3d.png)

But we at work use PHP5...

And Beautify-plugin don't work for php-files on Brackets  **1.14** :(

**Comment by shubhsnov** [comment]
The language server we are using can only be run on PHP7 and not PHP5 as mentioned here: https://github.com/felixfbecker/php-language-server/issues/23

However, that said, the parser can parse both PHP5 and PHP7 files, so all you need to do is to download PHP7 from here: https://www.php.net/downloads.php

and give the path to the PHP7 executable in brackets.json. You should still be able to get the PHP5 support you need in terms of hints. Not sure about linting though.

As for beautify, the plugin is based on jsBeautify which currently only works for JS HTML and CSS. You're free to raise a feature request with them.

**Comment by Yeehoo** [comment]
**shubhsnov**
Yes! It works! Thank you! ^_^
