### ISSUE TITLE
why does css not work on my macbook I have tried Brakets and Sublime Text 2

### ISSUE THREAD

**Issue by A-mirSaleh** [adobe/brackets#14839]
I have a 'Macbook OS X Yosemite' version 10.10.5 and I have been trying to learn programming through practice. I have tried 'Sublime Text 2' and 'Brackets' for the practice. 
When I use these editors, the HTML works just fine in both of them(I had to delete an extension in Brackets for the live preview to work.). I have cleared the cache on my browser and I can still not figure out the problem. I think there might be a problem with my macbook.
I have used 'google chrome' for both the things btw.

**Comment by RoLoDeXx** [comment]
> I have a 'Macbook OS X Yosemite' version 10.10.5 and I have been trying to learn programming through practice. I have tried 'Sublime Text 2' and 'Brackets' for the practice.
> When I use these editors, the HTML works just fine in both of them(I had to delete an extension in Brackets for the live preview to work.). I have cleared the cache on my browser and I can still not figure out the problem. I think there might be a problem with my macbook.
> I have used 'google chrome' for both the things btw.

Can you provide some screenshots?

**Comment by A-mirSaleh** [comment]
hey, I have the issue solved. But i am not sure what did it for me. 
There were three things9I remember what 2 were) which could have possibly made it work. 
1. I re-installed chrome. 
2. Got the network I was joined with changed. (I was moving countries)

Thank you for offering to help.
