### ISSUE TITLE
Ability to switch between \n new lines instead of \r\n on Windows

### ISSUE THREAD

**Issue by ErikThiart** [adobe/brackets#14841]
I see this has been addressed before but does not appear to be implemented yet:

https://github.com/adobe/brackets/issues/10095

https://github.com/adobe/brackets/issues/12995

https://github.com/adobe/brackets/pull/13152 

https://github.com/adobe/brackets/issues/10106

Any feedback on this guys, I am currently forced to use notepad++ because brackets default to CR LF instead I want the default to be UNIX's line endings LF since the majority of PHP projects built with brackets on a Windows client, will run on a UNIX system.

![2019-08-02_11-51-56](https://user-images.githubusercontent.com/9626641/62361769-f6bf7e00-b51b-11e9-8f53-5dd6a5b07b6f.png)

**Comment by rfrozza** [comment]
I was having the same problem. Search for "Newline" in the extensions and install (probably the first extension). You will see in the botton, right side, a new option to change between CRLF and LF. Worked for me.

**Comment by ErikThiart** [comment]
@rfrozza That worked like a bomb, for now, the workaround will have to do. Thank you very much.
