### ISSUE TITLE
ERROR: Parsing Error: The keyword 'const' is reserved

### ISSUE THREAD

**Issue by pixel3rr0r** [adobe/brackets#14960]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

I've started a new project only containing three files, HTML, CSS and JS. HTML works fine, CSS works fine, but I just can't get the JavaScript to work. I've only written 
```
'use strict'

const body = document.body;
```
I then get three JSLint Errors and one ESLint Errors:

![image](https://user-images.githubusercontent.com/27219018/68609394-6ea32a00-04b5-11ea-9da6-3aab8243151a.png)

Apparently Brackets does not support ES6. Since I have never worked with JSLint, I have absolutely no idea what to do.

Is there a global fix that works for new projects as well?

### Steps to Reproduce

1. Create a JavaScript-File with a fresh installation of Brackets
2. Write the code mentioned above
3. Voilà!

**Expected behavior:** Accept ES6 code

**Actual behavior:** Outputing warnings and an error.

### Versions

I'm running Brackets Release 1.14 build 1.14.0-17740 (release 329d08ffc) on Windows 10

**Comment by PortPixel** [comment]
Add /*eslint-env es6*/ to the top of the file(s)

**Comment by pixel3rr0r** [comment]
Thanks, that worked! And sorry for the late reply!

**Comment by pixel3rr0r** [comment]
It worked for a while, but then I started getting errors like these:
![image](https://user-images.githubusercontent.com/27219018/71686731-48ef1e80-2d9c-11ea-90dd-bb81fa99e16a.png)

Is it because of Node not starting?

**Comment by PortPixel** [comment]
No, it's because its not defined anywhere jslint can see, add `/*global require*/` to the top of the file(s) to say it's defined elsewhere.

**Comment by pixel3rr0r** [comment]
Aha, now it worked! Thanks for your help!

**Comment by anna-rosew** [comment]
Hi, 

I've had exactly the same issue but it doesn't work to insert `/*global require*/` or '/*eslint-env es6*/' to the top of the files. Sorry to have to rake up an old issue, am new to .js and need some help. 

<img width="1440" alt="Screenshot 2020-11-30 at 10 13 27" src="https://user-images.githubusercontent.com/72981644/100596970-bda44300-32f4-11eb-8311-74c947e7eef5.png">

**Comment by anna-rosew** [comment]
Hi,
I've had exactly the same issue but it doesn't work to insert `/*global require*/` to the top of the file having added `/eslint-env es6/S`, I didn't know if there was an issues with my placement? I'm attempting to create a basic voice recognition app and I;m new to .js so could use some help. 
<img width="1440" alt="Screenshot 2020-11-30 at 10 25 15" src="https://user-images.githubusercontent.com/72981644/100598230-5c7d6f00-32f6-11eb-9918-096492314731.png">
