### ISSUE TITLE
Not able to launch Brackets application on Mac 10.15.1 and Mac 10.14

### ISSUE THREAD

**Issue by ranjithagp** [adobe/brackets#14969]
1.On mac 10.15.1 and Mac 10.14,install Brackets 10.15 from the link 

2.Double click "Brackets" to open the app from Application.

<img width="422" alt="Screenshot 2019-11-18 at 3 30 18 PM" src="https://user-images.githubusercontent.com/57896718/69045022-06f06000-0a1c-11ea-9950-67e62e336c14.png">

Expected behavior : Should be able to launch brackets successfully.

Actual behavior :Not able to launch Brackets as its throwing a dialog saying "Brackets is damaged and can't be opened".

Versions: 1.15.0

@jha-g @narayani28 @yprasad1

**Comment by yprasad1** [comment]
@ranjithagp, Please re-validate with latest build.

**Comment by ranjithagp** [comment]
The issue is fixed with the build 1.15.0-17742-40. Closing the bug.
