### ISSUE TITLE
If the port number is invalid, error message should be shown in the info bar

### ISSUE THREAD

**Issue by ranjithagp** [adobe/brackets#14972]
1.Open Cmd line and run a command to launch Brackets with Remote debugging with the invalid port number (ex: 1024 or 155367455638738). 
2. Brackets remote debugging will be failed.

Expected behavior: Should get a toast notification on info bar, saying  "Brackets Remote debugging is disabled due to invalid port number"

Actual behavior:  Error logs are going to file: /c/Program Files (x86)/Brackets/debug.log.

Brackets version: 1.14.1

Platform: Windows

@jha-g @yprasad1 @narayani28

**Comment by jha-g** [comment]
@ranjithagp  now we have port validation error on info-bar.

<img width="840" alt="Screen Shot 2019-11-22 at 3 45 59 PM" src="https://user-images.githubusercontent.com/1094605/69423510-497fa880-0d4c-11ea-916f-317087141e21.png">

**Comment by ranjithagp** [comment]
Validated, Not reproducible with Brackets 1.14.1-17752 on Win, Mac and Ubuntu. Hence closing the bug.
