### ISSUE TITLE
If there is no port number given for remote debugging, it is showing as "0"

### ISSUE THREAD

**Issue by ranjithagp** [adobe/brackets#14973]
Steps to Reproduce;

1.Open console in Brackets application.
2.Call a function without giving any port number : appshell.app.getRemoteDebuggingPort(function(err,arg){console.log(arg);})

Expected behavior: It should return something which is not a valid port number (ex : NULL or  '-1')

Actual behavior: Its returning "0" which is a valid port number 

Note : Port numbers range from 0 to 65535 (anything within this range will be a valid port number including "0".
 Brackets vesrion: 1.14.1

Platform: Win and Mac

@yprasad1 @narayani28 @jha-g

**Comment by jha-g** [comment]
Fixed the issue, lack of `remote-debugging-port` is denoted by `null` now.
<img width="1677" alt="Screen Shot 2019-11-22 at 3 29 50 PM" src="https://user-images.githubusercontent.com/1094605/69416658-1aae0600-0d3d-11ea-91d0-0bf18820978b.png">

**Comment by ranjithagp** [comment]
Validated with the Brackets 1.14.1-17752 on Mac ,Win and Ubuntu. Hence closing the bug.
