### ISSUE TITLE
[EPV] Update Notification not localized on WIN and MAC

### ISSUE THREAD

**Issue by malik-Surbhi** [adobe/brackets#14994]
### Description
[EPV] Update Notification not localized on WIN and MAC in Brackets 1.14.1

### Steps to Reproduce

1. Launch Brackets 1.14 in French/Japanese.
2. Go to Help->Check for Updates

**Expected behavior:** The Update Notification is localized in the corresponding locales.

**Actual behavior:** The Update Notification is not localized in the corresponding locales.

### Versions
Mac All, Win All
Also reproducible with Brackets 1.13 auto update to Brackets 1.14.

![image](https://user-images.githubusercontent.com/33049951/70222865-a3cb3100-1770-11ea-8949-fcc75b34bdc7.png)
![image](https://user-images.githubusercontent.com/33049951/70222897-b2194d00-1770-11ea-8e37-9e196bba4b91.png)

**Comment by nayankankariya** [comment]
@jha-g
