### ISSUE TITLE
Brackets freezing and slowing down  after 1.14.1 update. this specially happening when scrolling or changing the tabs or clicking mouse. i can't work.

### ISSUE THREAD

**Issue by Tauhid8k** [adobe/brackets#14998]
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ ] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by SuzetteBuxmann** [comment]
It's doing the same for me.  Running extremely slowly.  
Windows 10 64 bit OS
Brackets Release 1.14 build 1.14.0-17740 (release 329d08ffc)

**Comment by shubhsnov** [comment]
@narayani28 @jha-g
