### ISSUE TITLE
Brackets not 'matching' some HTML open and close tags; </body> and </html> are red; code works and is identical to a colleague's

### ISSUE THREAD

**Issue by Lillian2611** [adobe/brackets#15027]
I have spent hours trying to figure out what's happening. If there's an unclosed div I can't find it. 

Live Preview works most of the time, despite the red &lt;body&gt; and &lt;html&gt;. Every now and then the lightning bolt goes red/pink but if I save the code it'll go orange again, or if I close/re-start it'll also go orange.

Here are the details of what's wrong and the code I'm referring to:
1. The closing tags &lt;/body&gt; and &lt;/html&gt; are red from the forward slash onward;
2. All the open divs can find their closing partners except:
a) the &lt;div class="row"&gt; that falls between the second instance of &lt;div class="container"&gt; and &lt;div class="col col-md-8 push-down-sm"&gt;. Sometimes this div finds no match at all but right now it's finding a match in &lt;/div&gt;&lt;!-- /container --&gt; near the end of the code. The &lt;/div&gt;&lt;!-- /row --&gt; it *should* be matching with is completely grayed out instead of the blue of a 'live' div.
b) the second instance of &lt;div class="container"&gt; near the top is matching itself to &lt;/div&gt;&lt;!-- /contentArea clearfix --&gt; at the bottom.
c) &lt;div id="contentArea" class="clearfix section"&gt; isn't matching itself to anything.

My head will probably explode when someone points out the problem, but I've gone over it line-by-line and can't see the issue. As I mention in my title, I've even compared it line-by-line with someone else's working code.

Thanks in advance for your help!

<!DOCTYPE HTML>

<html>

    <head>
        <title>CSS3 Special Effects</title>
        <link rel="stylesheet" href ="stylesheet.css">
        <meta name="viewport" content="width=device width, initial-scale=1">
    </head>
    
    <body>
    
        <header class="section">
        
            <div class="container">
                <h1>Website Title</h1>
                <p class="hideSmall">Website slogan</p>
       
        
                <nav id="siteNavigation">
                    <ul class="clearfix">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Portfolio</a></li>
                        <li class="hideSmall"><a href="#">FAQs</a></li>
                        <li class="hideSmall"><a href="#">Links</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </nav>
        
            </div>
        
        </header>
        
        <div id="contentArea" class="clearfix section">
        
            <div class="container">
        
                <div class="row">
                
                    <div class="col col-md-8 push-down-sm">
                    
                        <h2>Welcome to the page!</h2>
                
                        <div class="row">

                            <div class="col col-sm-6 col-lg-3">
                                <div class="box-a">
                                    <p>Key feature 1</p>
                                </div>
                            </div>

                            <div class="col col-sm-6 col-lg-3">
                                <div class="box-a">
                                    <p>Key feature 2</p>
                                </div>
                            </div>

                            <div class="col col-sm-6 col-lg-3">
                                <div class="box-a">
                                    <p>Key feature 3</p>
                                </div>
                            </div>

                            <div class="col col-sm-6 col-lg-3">
                                <div class="box-a">
                                    <p>Key feature 4</p>
                                </div>
                            </div>

                        </div>

                        <div id="box-b">
                            I wish I were a circle.
                        </div>

                        <div id="box-c">
                            I wish I were an oval.
                        </div>

                        <div class="row">

                            <div class="col col-xs-6">
                                <img src="bird.jpg">
                            </div> 

                            <div class="col col-xs-6">
                                <img src="squirrel.jpg">
                            </div> 
                        
                        </div> 
                               
                    </div>

                    <div class="col col-md-4" id="sidebar">
                        <h3>Sidebar Heading</h3>
                        <p>Sidebar Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.</p>

                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

                        <p>Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.</p>
                    </div>
     
            </div>
        
        </div>
        
        <footer>
            <p>&copy;2020 - this is the footer</p>
        </footer>
                        
    </body>
    
</html>

**Comment by JulianG36** [comment]
You are missing the two dashes at the bottom of one of your comments causing one of the div's to be commented out
Yours:
`</div><!-- /col-md-4>`
Fixed:
`</div><!-- /col-md-4 -->`

**Comment by Lillian2611** [comment]
Thank you so much! No wonder I couldn't find it: I wasn't paying attention to the comments.

> 
> 
> You are missing the two dashes at the bottom of one of your comments causing one of the div's to be commented out
> Yours:
> `</div><!-- /col-md-4>`
> Fixed:
> `</div><!-- /col-md-4 -->`
