### ISSUE TITLE
Weird graphical glitches on latest version of Mint and Brackets

### ISSUE THREAD

**Issue by alekexe** [adobe/brackets#15095]
### Prerequisites

* [x]  Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)

### Description

Weird lines and dots on ends of characters, I tried changing themes to dark and light ones(default) but the bug is still present on sidebar and text editor area only. Im using font "MS Gothic', monospace", but changing fonts doesnt fix the issue.

![image](https://user-images.githubusercontent.com/34973145/76974516-973ea300-6931-11ea-99f5-2977cfee5cbb.png)
![image](https://user-images.githubusercontent.com/34973145/76974614-b4737180-6931-11ea-8b51-be48cc58a7d2.png)

### Steps to Reproduce

There are no steps, this bug begins from launch. 
### Versions

Linux Mint Cinnamon 19.3, Cinnamon version 4.4.5, kernel 5.0.0-32-generic
AMD Ryzen 3 2200g with Radeon Graphics Vega 8
Brackets Release 1.13 build 1.13.0-17696 (release 49d29a8bc)

**Comment by alekexe** [comment]
Weirdly enough, 4 days later and it fixed itself. I did not update anything, download any software or modify any configuration.

**Comment by vianin** [comment]
I have the exact same problem. I just installed it and it's there.

**Comment by alekexe** [comment]
Related to the issue #14290
