### ISSUE TITLE
Link to download Brackets installation packages is broken

### ISSUE THREAD

**Issue by blahboybaz** [adobe/brackets#15110]
### Prerequisites

- Start from http://brackets.io/
- Click the big blue button that says "Download Brackets 1.14.2"

### Result

 - Attempts to resolve https://github.com/adobe/brackets/releases/download/release-1.14.2/Brackets.Release.1.14.2.64-bit.deb
 - Receives 404 error page

### Environment

 - Firefox 74.0.1
 - Ubuntu 18.04.4 LTS
 - Current date and time

### Problem

We can't download Brackets
  
![Screenshot_2020-04-06 Build software better, together](https://user-images.githubusercontent.com/63227071/78533583-0f182480-779e-11ea-83d7-dcc0d208cbea.png)

**Comment by nayankankariya** [comment]
Validated on Ubuntu and Debian OS. Issue is fixed now with PR [#222](https://github.com/adobe/brackets.io/pull/222).
