### ISSUE TITLE
Near-All Functionality Broken on Mac

### ISSUE THREAD

**Issue by Meanderbilt** [adobe/brackets#15114]
All Brackets functionality is broken on Mac, except for minimize. Brackets must be force quit to close. I've re-downloaded the most recent version of Brackets but the issue persists.

Files can be dragged into Brackets and edited, but not saved.

A screen recording of the issue can be viewed [here](https://youtu.be/_3bAJb1iaio/).

No issues with Brackets prior to this issue.

macOS 10.15.4
Brackets 1.14.2

**Comment by Nainabhandari24** [comment]
Hi,

Thanks for reporting us.
We tried to recreate this issue on MacOS 10.15.4, but issue is not reproducible at our end. 
Tried on multiple machines.
Will let you know once we encounter the same.

Thanks!

**Comment by Nainabhandari24** [comment]
Hi,

Thanks for reporting us.
We tried to recreate this issue on MacOS 10.15.4, but issue is not reproducible at our end.
Tried on multiple machines.

Could you please follow below steps and let us know if issue still persist.
- Clear preferences, go to Folder (~/Library/Application Support)
Delete Brackets folder and then relaunch Brackets.
- Also try after restarting the machine.

Thanks!

**Comment by Meanderbilt** [comment]
Deleting the Brackets folder within Application Support resolved the issue for me—thank you!
