### ISSUE TITLE
HTML doesn't launch when clicking live preview

### ISSUE THREAD

**Issue by IgorArnaut** [adobe/brackets#15131]
HTML doesn't launch when clicking live preview. The lightning icon hover says that it's connecting...

Opened Brackets.
Enabled experimental live preview, because I don't use Google Chrome.
Opened a folder.
Opened a HTML file from that folder.
Clicked live preview.

HTML file to be launched in the browser when clicking live preview.
It doesn't open when clicking live preview. Live preview is just "activated" and says "connecting..."

Windows 7 Pro 64-bit
Release 1.14 build 1.14.2-17770

**Comment by Igor-Arnaut** [comment]
I'll add that "Project Settings" is grayed out.

**Comment by THE-VR7** [comment]
Hello. I am new  and would love to contribute.
I would like to fix this issue, if no one is already on it.

**Comment by alizeh12** [comment]
Hi @Igor-Arnaut I am a first-timer to contributing and would like to work on this issue if no one has fixed it already
