### ISSUE TITLE
Error Code 1 encountered while starting the PHP process.- How do i fix this?

### ISSUE THREAD

**Issue by booperlv** [adobe/brackets#15158]
So I had just downloaded Brackets today and encountered the php runtime problem- I tried multiple methods and ended up using this on my brackets.json file.
`{
    "brackets-eslint.gutterMarks": true,
    "brackets-eslint.useLocalESLint": false,
    "fonts.fontSize": "16px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "php": {
        "executablePath": "C:\\xampp\\php\\php.exe"
    },
    "themes.theme": "dark-theme"
}`
I had expected it to work. as the php runtime error did dissapear afterall.

Apparently, a new error popped up and there seems to be no posts about this.
<img src="https://media.discordapp.net/attachments/448379303227555850/712285964239896607/unknown.png?width=845&height=475">

Im running on windows 7 64bit, Brackets 1.14

Found this on Node Debugging as well.
```
NodeDebugUtils.js:111 [node-error 8:49:18 PM] { Error: Command failed: C:\xampp\php\php.exe --version
PHP Warning:  'vcruntime140.dll' 14.0 is not compatible with this PHP build linked with 14.16 in Unknown on line 0


    at makeError (C:\Program Files (x86)\Brackets\www\extensions\default\PhpTooling\node_modules\execa\index.js:174:9)
    at Promise.all.then.arr (C:\Program Files (x86)\Brackets\www\extensions\default\PhpTooling\node_modules\execa\index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 1,
  stdout: '',
  stderr: 'PHP Warning:  \'vcruntime140.dll\' 14.0 is not compatible with this PHP build linked with 14.16 in Unknown on line 0\n',
  failed: true,
  signal: null,
  cmd: 'C:\\xampp\\php\\php.exe --version',
  timedOut: false,
  killed: false }
```

**Comment by VZangoGame** [comment]
backup XAMPP
try re- install XAMPP in a different path different by C:, be sure during the istalling it will no ask you for UAC protocol on your computer, if it is, you definitely install it outside from C:
