### ISSUE TITLE
brackets account/login

### ISSUE THREAD

**Issue by susuhi** [adobe/brackets#15246]
hi i dont really have a problem, i was just wondering if i had to make an account somewhere for brackets?

i might transfer my information to my gaming PC. if i deleted brackets on this laptop, would my information and codes already in the program, delete?

is there anyway i can save it? do i have to create an account and if so, how do i do that? 

i looked around for any answers and i couldn't find some. i came across this website and made an account to "issue a new issue". so, i apologize in advance if this question seems a bit dumb lmao

im only using brackets to make a website! nothing serious but i have been working pretty hard on it considering i dont know anything about coding 

thank you! :) <3

**Comment by tomas1971** [comment]
https://github.com/adobe/brackets/issues/15246#issue-742874665
