### ISSUE TITLE
Libcurl3 dependency problem in Ubuntu MATE 20.04

### ISSUE THREAD

**Issue by benhanx** [adobe/brackets#15281]
I couldn't install .deb binary. It wants libcurl3 dependency. On my system, libcurl4 is already installed. And libcurl3 package is couldn't be installed because of libcurl4.
Maybe, this should be checked.

**Comment by flopezre** [comment]
https://github.com/adobe/brackets/issues/14786

**Comment by benhanx** [comment]
thanks so much, it worked!
