### ISSUE TITLE
Installation error in Xubuntu 20.4 (Linux)

### ISSUE THREAD

**Issue by ahmadfaizan965** [adobe/brackets#15312]
I tried to install Brackets, i downloaded the **.deb file** from [Brackets Website](http://brackets.io/) to my Linux operating system (Xubuntu 20.4 LTS 64-Bit). i received this error ```The following packages have unmet dependencies:
 brackets : Depends: libcurl3 but it is not installable
E: Unable to correct problems, you have held broken packages.```

![Brackets Error](https://user-images.githubusercontent.com/69793423/106278664-1e062100-6261-11eb-9571-34a075be10f5.png)

**Comment by ahmadfaizan965** [comment]
Initiated an issue regrading installation error in Xubuntu Linux.

**Comment by Biguelini** [comment]
I don't know if you've tried installing libcurl3, but that's what I would do. Follow the necessary commands:
Update the package index:
# sudo apt-get update
Install libcurl3-gnutls deb package:
# sudo apt-get install libcurl3-gnutls

Hope this helps :)

I'm sorry if I missed something in the message, because I had to use the Google Translate...

**Comment by SolomonLeon** [comment]
Brackets use libcurl3. However, libcurl4 has been installed to ubuntu>=18.04 by default, which provide better security.

The following link might helps. [https://github.com/adobe/brackets/issues/15297#issuecomment-752983532]()

**Comment by ahmadfaizan965** [comment]
> Brackets use libcurl3. However, libcurl4 has been installed to ubuntu>=18.04 by default, which provide better security. You should not remove libcurl4 (I have already tried:( ) because this will cause more serious compatibility issues.
> 
> The following link might helps. [#15297 (comment)](https://github.com/adobe/brackets/issues/15297#issuecomment-752983532)

Issue Resolved. Thanks.

Clossing issue.
