### ISSUE TITLE
Corner resize handle/gripper appears briefly while resizing window (Win only)

### ISSUE THREAD

**Issue by gruehle** [adobe/brackets#1741]
1. Resize the Brackets window horizontally or vertically

Result: A native corner-resize gripper flickers visible in the lower-right corner. As soon as you stop moving the mouse, it disappears.

Expected: No native controls become visible while resizing.

I'm seeing this on Win XP. Not sure if it happens on other versions of Windows too.

**Comment by MarcelGerber** [comment]
I think this is now fixed... @JeffryBooher Could you just quickly check?

**Comment by JeffryBooher** [comment]
Yeah I'm not seeing it in 3.2171.1902 @redmunds if you're ok with this then let's close it.

**Comment by redmunds** [comment]
LGTM. Closing.
