### ISSUE TITLE
Take advantage of markText() API for inline editor ranges

### ISSUE THREAD

**Issue by njx** [adobe/brackets#2165]
Currently, the inline color editor uses two bookmarks to track the ends of the range in the host editor that the color editor is editing. This is a little fragile, and we have some heuristics in place to adjust for the case where the user deletes the end of the color. The markText() API in our old version of CodeMirror v2 doesn't work as well for this, but it's been completely rewritten and significantly enhanced in v3, so we should migrate to that once we switch to v3. Another advantage would be that we could have a persistent visual marker of which range the inline editor is referencing, so even if the user changes the selection while the editor is open, you could still see what it's editing.

**Comment by MarcelGerber** [comment]
@redmunds This was also fixed by #10401.

**Comment by redmunds** [comment]
Closing.
