### ISSUE TITLE
When end of range is deleted in color editor, it can edit the wrong remaining portion

### ISSUE THREAD

**Issue by njx** [adobe/brackets#2166]
1. In a CSS file, type `#abcdef;`
2. Put the cursor inside the color
3. Cmd-E to bring up the color editor
4. In the main editor, select `f;` and delete it
5. Make a change in the color editor

Result: the change overwrites `#abc` instead of all of `#abcde`.
Expected result: either close the color editor at step 4, or properly apply the edit to the entire hex string.

**Comment by redmunds** [comment]
Confirmed. Closing.
