### ISSUE TITLE
FileUtils.canonicalizeFolderPath() is confusing (now deprecated - need to remove)

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#2818]
This utility function "canonicalizes" paths by making sure paths pointing to folders don't end in a trailing slash.  However, the canonical format of NativeFileSystem.DirectoryEntry (and thus most paths in the Brackets code), is the opposite of this -- directories _always_ have a trailing slash.

Looking at references to this API, it appears to only be used by code related to Recent Projects.  Perhaps we should clean up that code and then remove this API?

**Comment by le717** [comment]
@peterflynn This can be closed. The API was removed with #8992.
