### ISSUE TITLE
Changes to value returned by PreferenceStorage getValue() are saved without setValue()

### ISSUE THREAD

**Issue by njx** [adobe/brackets#2822]
If `PreferenceStorage` returns an object or array from `getValue()`, and you modify that object or array, the changes get saved back to storage even if you never explicitly call `setValue()`. This might just be the way it works, but we should be clear about that in the documentation for `getValue()`.

**Comment by le717** [comment]
@jasonsanjose This can be closed due to PreferencesStorage being deprecated/replaced and pending removal in #9752.

**Comment by jasonsanjose** [comment]
Thanks. Closing.
