### ISSUE TITLE
Windows: Brackets may fail to launch on a very clean OS image

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#2872]
1. Get a clean Windows image with no preinstalled software (e.g. no MS Office)
2. Install Brackets; don't install anything else yet
3. Try to launch Brackets

Result: Error message about MSVCP100.dll being missing.  Brackets doesn't launch.
(I haven't repro'ed this myself, but that's the report we've gotten and it makes sense to me)

Expected: Brackets still launches fine

Workaround: manually install the DLL from http://www.microsoft.com/en-us/download/details.aspx?id=5555, or just install a couple of other Windows apps and it will generally wind up on your computer

A huge number of native Windows apps require this DLL, which is basically the MS Visual C runtime library (often called the "redistributable").  There are many versions of it and different apps require different versions, but this version is common enough that any computer with other apps installed on it is virtually guaranteed to already have the DLL.  That said, the Brackets installer should actually include this file so that we're not just assuming it's present.

I'm not sure if we should go to the trouble of installing it in a standard location to be shared with other apps.  That would have a tiny benefit in disk space savings, but would probably be trickier to get working.  I _think_ we can just place the file next to our .exe instead and be all good...

**Comment by abose** [comment]
Closing this as no one has reported this issue in a long time.
