### ISSUE TITLE
Toggle Block Comment doesn't work if the open/close delimiters are the same

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#3057]
1. Add this line to the CoffeeScript section of languages.json: `"blockComment": ["###", "###"],`
2. Open a .coffee file with these contents:
```
foo = 42
bar = true
baz = "hello"
number = -42 if bar
square = (x) -> x * x
```
3. Select the middle 3 lines and Toggle Block Comment
4. Immediately Toggle Block Comment again
5. Undo back to clean state
6. Repeat step 3
7. Select all the lines, including the `###` lines, _then_ Toggle Block Comment again
8. Undo back to a clean state
9. Select just one line (without including newlines) and Toggle Block Comment
10. Either (a) immediately toggle again, or (b) re-select the whole line to include delimiters and then toggle

Result:
4 - closing delimiter isn't removed
7 - comment is wrapped in a second pair of `###` lines
10 - one "#" is removed from the opening `###`, but nothing else changes

**Comment by TomMalbran** [comment]
I am going to close this, since it does work.
