### ISSUE TITLE
Quick open shouldn't jump to item until you type a character

### ISSUE THREAD

**Issue by njx** [adobe/brackets#3405]
1. Open a JS file
2. Cmd-T

Result: The editor immediately scrolls to the first definition in the file. I would expect it to wait until I've either typed a character or selected an item in the list.

I think it's always worked this way, but it just occurred to me that it's been bugging me all this time :)

**Comment by peterflynn** [comment]
Fixed in 1.3

**Comment by rroshan1** [comment]
Verified the fix.. The issue no longer exists!! 
Closing the issue.
