### ISSUE TITLE
Code editor font makes me cry (with Russian / Cyrillic text)

### ISSUE THREAD

**Issue by ainop** [adobe/brackets#3465]
### Workaround: [How to switch to a different code font](https://github.com/adobe/brackets/wiki/Customize-Your-Code-Font)

----

I have no 'SourceCodePro' and Russian text looks awfully in "ＭＳ ゴシック" and "MS Gothic" (which is default according to developer tools). Is there way to set custom font in editor view?

sprint 23 experimental build 0.23.0-6726 (master 6908b48b7), Windows7

![2013-04-17_1227](https://f.cloud.github.com/assets/107447/390321/54d1efe0-a73c-11e2-80c2-7f4ec9320cab.png)

**Comment by abose** [comment]
#11301 With latest source code pro addresses this issue.

**Comment by rawat11** [comment]
@abose The latest ttf fonts displays the characters nicely.

Updating the SS for both MAC and WIn

![1-russian-win](https://cloud.githubusercontent.com/assets/10069885/8424392/8910d640-1f17-11e5-9a2b-980a77d6e812.png)
![2-russian-win](https://cloud.githubusercontent.com/assets/10069885/8424394/8c0f90a2-1f17-11e5-8929-b514737374dd.png)
![5-russian-mac](https://cloud.githubusercontent.com/assets/10069885/8424398/91d79bb0-1f17-11e5-9ad0-a52cf07689d0.png)
![6-russian-mac](https://cloud.githubusercontent.com/assets/10069885/8424401/951005ce-1f17-11e5-94de-8963b97f8478.png)

**Comment by abose** [comment]
Updated source code pro has support for  Russian / Cyrillic text. Closing.
If certain glyphs are not rendered properly, raise another issue stating the details. Closing this issue now.
