### ISSUE TITLE
[PM] Cleanup WebPlatformDocs css.json

### ISSUE THREAD

**Issue by jasonsanjose** [adobe/brackets#3471]
Comment from pull #3449 

* use lowercase instead of uppercase properties
* remove unnecessary forward slash escaping
* resize the inline widget when the sidebar visibility changes

**Comment by MarcelGerber** [comment]
Already fixed in #9686.

**Comment by peterflynn** [comment]
FBNC @jasonsanjose in that case

**Comment by jasonsanjose** [comment]
Confirmed. Closing.
