### ISSUE TITLE
Feature Request: Add the Brackets Shell version to the About Dialog

### ISSUE THREAD

**Issue by lkcampbell** [adobe/brackets#3904]
Per [this discussion](https://github.com/adobe/brackets/pull/2128#issuecomment-18103358).

The current About dialog only shows the version of brackets, but not brackets-shell.  I know these two projects are in sync during Sprint releases but dev versions sometimes get out of sync.  It might be useful to have both version numbers in the About dialog.

**Comment by ficristo** [comment]
While testing https://github.com/adobe/brackets-shell/pull/564 this would helped me a bit (simply to realize if the shell I built was the correct one).

**Comment by lkcampbell** [comment]
Never going to happen. Closing.
