### ISSUE TITLE
CSS code hints stay open too long after typing enumerated value

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#4888]
1. In a CSS rule, type out `max-height: none;`
2. Continue typing ` /*`

Result:
Code hints popup remains open the whole time, until you type "*". (After your type ";" the hints switch back to property names).

Expected:
Hints should close after the ";" and not reappear until you start typing a property name.

It works properly if you type things like `padding: 0;` or `border: none`, so I think this is a problem specifically caused by code hints to enumerated values.

**Comment by peterflynn** [comment]
The `/*` part of the original steps above no longer repros, but here's a similar bug that still exists:

1. Type `max-height: none;`
2. Press Enter

Result: code hints stay open (listing property names), and follow the cursor onto the next line with a distracting swooping animation

Expected: code hints close after typing `;`, and don't open again until you type a letter key or whitespace, or explicitly reopen them via Ctrl-Space.

<br>The expected behavior seems consistent with #2627 & the forum post it links to, so this must have regressed at some point.

Also note that if you have `max-height: none` and code hints are not open, typing `;` does not trigger them to reopen -- which again seems to support that they should close after typing the `;` in the steps above.

**Comment by MarcelGerber** [comment]
#10524 fixes this issue.

**Comment by MarcelGerber** [comment]
This should now be fixed. Please check and let us know whether you still see this issue.
