### ISSUE TITLE
Focus lost after closing Project Settings

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#4954]
1. File > Project Settings
2. Click Cancel
3. Try to type anything

Result: Nothing happens. Keyboard focus is not in editor area.

We just need a simple `EditorManager.focusEditor()` call to fix this, so marking as a starter bug.  Or we could use this as an opportunity to finally fix post-dialog focus more generally :-)

**Comment by webjocky** [comment]
n00b here, searching for my first bug to tackle. Unless I'm mistaken, the status of this issue should no longer be open since @Jerhamre seems to have added a fix that's been merged in #12824?

**Comment by petetnt** [comment]
Thanks @webjocky 👍
