### ISSUE TITLE
[Core][Dropdown menu]: Switch Language native <select> dropdown doesn't move when window resized

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets#5291]
Steps:
1. Launch Brackets and don't maximize its window.
2. Click Navigate>Quick Open.
3. Resize the window of Brackets.
4. Click Debug>Switch Language and click the dropdown icon to select a language.
5. Put your mouse on the titlebar of Brackets and drag the Window.

Results:
At step3, the dropdown menu of Quick Open keeps still and cannot change its position with the window. This issue reproduces on both Win and MAC.
At step5, the dropdown menu of Switch language keeps still and distaches with the Switch Language dialog. This issue only reproduce on Win OS, not reproduces on MAC OS.

Expected:
The dropdown menu should move with Switch language dialog or Quick Open bar.

ENV: MAC10.8 and Win8.1 English OS
Build: 0.32.0-9586

Snapshots:
Please refer to snapshots for details:
Quick Open:
![222](https://f.cloud.github.com/assets/4251563/1189734/a8c42076-2420-11e3-95fa-6d94bdf1aa9a.jpg)
Switch dialog on Win OS:
![1111](https://f.cloud.github.com/assets/4251563/1189730/960fa586-2420-11e3-9b39-4a7abe89305f.jpg)

**Comment by redmunds** [comment]
Confirmed. Closing.
