### ISSUE TITLE
Quick Find Definition doesn't update on paste (when copying between files)

### ISSUE THREAD

**Issue by globexdesigns** [adobe/brackets#5360]
Steps to reproduce:

1) Load two different files in Brackets that both have the same function definition.
2) Copy the name of the function in File 1.
3) Go to File 2 in brackets via the Working Files list.
4) Press Command + T to open the Quick Find Definition input box
5) Press Command + V to paste into the Quick Find

Note that the Quick Find doesn't update the results. If you press some arrow keys or any other keydown event -- it will eventually fire.

What should happen:

The Quick Find input should detect a paste command and execute the search for that value.

**Comment by peterflynn** [comment]
This is fixed in the upcoming 1.3 release
