### ISSUE TITLE
Unable to position cursor after a hyphen in word-wrapped, hyphenated text.

### ISSUE THREAD

**Issue by bchintx** [adobe/brackets#5408]
With the fix for Issue #4998, you now can no longer position the cursor after a hyphen in word-wrapped, hyphenated text.

Steps to Reproduce:
1. Paste the following text into a blank Brackets document: `Cernantur quorum dolor ut fugiat, non in dolore nostrud, anim minim veniam eernantur–coniunctione enim coniunctione.`
2. Resize the editor width so that the hyphen is close to the right edge of the editor window and the "coniunctione" part of the word shows up on the next line: ![hyphen-cursor-problem](https://f.cloud.github.com/assets/1774931/1049811/7781a850-10af-11e3-933a-846828cdecef.PNG)
3. Click the mouse cursor in the space at the end of the 1st line of text, specifically to the right of "eernantur-".

=> The editor will position the cursor to the **left** of the hyphen, rather than to the *_right_.  Even using the arrow keys, you can only be positioned to the left of the hyphen or at the beginning of the next line.

Other text editors, such as Notepad and the Visual Studio editor allow the cursor to be positioned of the right of the hyphen.

**Comment by adrianheine** [comment]
Is this still reproducible with a current CodeMirror version?

**Comment by ficristo** [comment]
I tryed in Firefox 51 on Windows 10 and cannot reproduce anymore.
I also tryed on Brackets master, which has CodeMirror 5.24.2, and cannot reproduce there too.
I'd say this is fixed.
