### ISSUE TITLE
Script block with unquoted 'type' attribute has no JS syntax highlighting

### ISSUE THREAD

**Issue by capolino** [adobe/brackets#5451]
Hello, my name is Kevin.
I am writing this comment to tell you of script that has not been added to the program and that would add to the efficiency and ease of use of the program.
There is no Js syntax highlighting when you are editing a HTML doc.
There are themes that can help with this with the "Themes" plugin (Very useful plugin btw, should be implemented) but not all of them, and the ones that do are very eye-sore-ish and not something that I want to be looking at when I'm sitting and programming for hours on-end.
Here is a link to a screen shot of the problem with the default Brackets theme: http://puu.sh/4L2Ix.png
Here it is in the theme that I use: http://puu.sh/4L2zI.png

Thank you, 
--Kevin

**Comment by le717** [comment]
@RaymondLim This issue can be closed. JavaScript is syntax highlighted when embedded into an HTML document using `<script>` tags (as seen in the following image), I've seen this behavior for as long as I can remember, whenever I started using Brackets around February 2014.

![syntax highlighting](https://cloud.githubusercontent.com/assets/3382464/6313006/f0ad7bf2-b962-11e4-906f-13c82491bed5.png)

**Comment by ficristo** [comment]
With 1.8 `<script type >` should also work.
