### ISSUE TITLE
DocumentManager.closeFullEditor()'s skipAutoSelect arg seems unused

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#5706]
This was once used by notifyPathDeleted()'s call to notifyFileDeleted() (which then passes the flag along to closeFullEditor()).  But now that notifyPathDeleted() simply delegates over to FileSyncManager.syncOpenDocuments(), nothing in our codebase calls either closeFullEditor() or notifyFileDeleted() with this flag.

We should either (a) decide it's definitely unneeded and remove it to reduce complexity, or (b) decide it still _is_ needed and then figure out how it should be worked into FileSyncManager.

I'm not clear on why it was needed originally -- possibly just for efficiency?  Or maybe reducing flicker in the case that many images were closed at once?

**Comment by le717** [comment]
@peterflynn This can closed due to Split View refactoring (and subsequent deprecation of this API).
