### ISSUE TITLE
[Core][Extension Manager]:  Extensions under Available tab cannot show if click available tab while loading the extensions.

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets#5852]
Steps:
1. Launch Brackets.
2. Click Extension Manager icon on the right sidebar.
3. On the Extension Manager dialog, click tab Available while the extensions are loading.
4. Waite several seconds until the extensions are loaded, then observe the extension dialog.

Results:
No extension list under tab Available.

Expected:
Available extensions should show on the dialog.

ENV: Mac 10.8 and Win8.1 English OS
Build: 0.34.0-10242(win) and 0.34.0-10251(Mac)

Notes:
There is no extension installed on my mac and VM. After step4, if I click tab Installed, then back to tab Available, extensions could list on the dialog. 

Snapshots:
Please refer to snapshots for details:
Step3:
![222](https://f.cloud.github.com/assets/4251563/1471422/9ca0051a-45e2-11e3-9df2-1c5b5a6b00cb.jpg)
Step4:
![1111](https://f.cloud.github.com/assets/4251563/1471423/9ccb88d4-45e2-11e3-96e7-096e86979493.jpg)

**Comment by MarcelGerber** [comment]
@julieyuan @peterflynn This is now hopefully fixed on master.

**Comment by peterflynn** [comment]
Closing as fixed
