### ISSUE TITLE
Clicking on item in Quick Open briefly shows weird path in input field

### ISSUE THREAD

**Issue by njx** [adobe/brackets#5871]
1. Cmd-Shift-O
2. Type the beginning of a filename, e.g. "br"
3. Click on an item in the dropdown

Result: You briefly see the path of the file appended to the characters you previously typed in the input field. However, the correct file opens anyway.

**Comment by peterflynn** [comment]
Fixed in 1.3

**Comment by nethip** [comment]
@rroshan1 Can you verify and close if this is fixed.

**Comment by rroshan1** [comment]
Verified the fix.. The issue no longer exists!! 
Closing the issue.
