### ISSUE TITLE
[ImagePreview] img-header moving out of view

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#5960]
1. Open a image that is too high to show it completely, so it has to be resized (in my case `src/styles/images/propertiespanel_back@2x.png`
2. Decrease the height of the Brackets window

Result: The img-header content (resolution, path) moves up too far.

Expected: The img-header should be displayed correctly, the image itself should be resized.

Note: This also happens with pictures with more normal-shaped pictures (like `Getting Started` screenshot).

Screen:
![image](https://f.cloud.github.com/assets/2641501/1526002/f91fd8a0-4bdd-11e3-9ab4-623990da00fb.png)

**Comment by EJanuszewski** [comment]
Anyone mind if I take a look at this?

**Comment by redmunds** [comment]
@EJanuszewski Nobody is working on it, so it's all yours. Thanks.

**Comment by peterflynn** [comment]
@EJanuszewski Note that this may be tangled up in #10180 now, which is also related to vertical sizing.

**Comment by EJanuszewski** [comment]
@peterflynn Someone appears to have assigned themselves onto #10180 which appears to be related but not the same, so I'll still fix this one.

**Comment by JeffryBooher** [comment]
@EJanuszewski Can you put up a Pull Request and tag both issues in the description then let @prksingh know that your solution may fix the issue he's looking at? 

He picked that up because we tagged the issue with the 1.2 milestone but he may not have a solution yet,

**Comment by EJanuszewski** [comment]
@JeffryBooher Both should be in here https://github.com/adobe/brackets/pull/10364

**Comment by prafulVaishnav** [comment]
Pull request #10514 merged.. Thanks @EJanuszewski for the fix..
