### ISSUE TITLE
Add support for DART

### ISSUE THREAD

**Issue by ronag** [adobe/brackets#6087]

**Comment by tryagains** [comment]
Hi, It seems the Dart extension is removed from github https://github.com/Arubaruba/Dart-Codemirror
Update needed for Dart 1.8.3 syntax

Dart should have better support! autocompletion and Dartium launcher

**Comment by dvorapa** [comment]
Well, I thought the same about language support, but now I see it is on us. So let's code new extension!

**Comment by MarcelGerber** [comment]
CM now has a Dart mode, so we can include that in Brackets 1.2

**Comment by dvorapa** [comment]
Really? That's great!

**Comment by MarcelGerber** [comment]
Yeah, you can have a look at the [CM Dart demo](http://codemirror.net/mode/dart/) already.
Notice though it's only syntax-highlighting; code hints and so on still have to be done by an extension.

But I don't see anything preventing us from having a Dart mode in Brackets 1.2

**Comment by dvorapa** [comment]
Highlighting was the main problem, code hints, analyzer (linter) or live preview (in dartium) is not so important at the moment

**Comment by tryagains** [comment]
Can live preview in dartium be done via extension?

**Comment by redmunds** [comment]
@tryagains 

> Can live preview in dartium be done via extension?

Starting in Brackets 1.1, you can turn on the Live Preview MultiBrowser feature. For details see: https://github.com/adobe/brackets/wiki/Live-Preview-Multibrowser

This will start Live Preview in your default browser, and then you can copy/paste url to any other browser. I'm not sure if anyone's tried dartium, so let us know how it goes.

**Comment by dvorapa** [comment]
I haven't known about the Live Preview MultiBrowser feature. It works as expected...

**Comment by MarcelGerber** [comment]
FYI, Dart mode will be in Brackets 1.2 (and this issue can probably be closed now).
