### ISSUE TITLE
Change all font-sizes, line-heights and dimensions to use rems and allow method to scale base font-size

### ISSUE THREAD

**Issue by stowball** [adobe/brackets#6316]
I recently bought a Sony VAIO Ultrabook which has a High DPI screen (1920x1080 resolution in 11").

By default, Windows scales apps, but this makes the UI blurry. Upon disabling scaling on brackets.exe, the UI is too small to read, but is crisp. Thus, I created an extension called [Legibility](https://github.com/stowball/brackets-legibility) and manually changed font-sizes, line-heights, heights, widths etc to make them readable.

This took a lot of inspecting and trial and error to get right.

It would be much better if you changed all of these values to use rems (you could write a mixin to divide the target value by 16), that way, a user would simply need to change the font-size on html for the whole app to scale.

You could implement this natively - similar to Code Mirror zooming (Ctr+Shift+ -/+, perhaps?) or an extension developer could easily write something to allow an end user to change the UI size to match their needs.

I think this is really important - everyone is different and needs different sizes to be able to use Brackets comfortably. I can't be the only one with a High DPI device and/or poor eyesight

**Comment by abose** [comment]
HiDPI support for windows is enabled in brackets 1.2. Fonts and icons should look clear in windows when scaling is applied. Closing the issue.

**Comment by matrs** [comment]
So, there isn't a simple way to change the UI font size  in linux? The font-size! in a editor written in and for code where the font size in so important !

(it's 2015, hundreds of   2560x1440 displays have been sold, among others)

**Comment by ryanstewart** [comment]
@matrs I'm not sure what you mean. If you go to View->Themes you can change the font size.

**Comment by revxx14** [comment]
Any news on this? I just set up Ubuntu on a high DPI display and Brackets is unusable :(
