### ISSUE TITLE
Add Debian package to Ubuntu software centre

### ISSUE THREAD

**Issue by isaacrg** [adobe/brackets#6504]
Would it be possible for the Brackets Debian package to be added to the Ubuntu Software Centre, enabling readily available updates, and readier availability?

I am willing to upload the packages to the software centre, but I was wondering whether I would be permitted to upload and manage the packages for distribution on the Ubuntu Software Centre

**Comment by peterflynn** [comment]
Closing in favor of #7237, which has more up to date info
