### ISSUE TITLE
Improved / Customizable Code Highlighting

### ISSUE THREAD

**Issue by ericbieller** [adobe/brackets#6566]
As it stands currently, there isn't a simple way to highlight, for example, style.css.less.erb as CSS.

In prior versions you were able to edit a languages.json file but that seems to be removed (I think it's actually just minified now).

I'm running sprint 0.35.0-10897

Ideally there would be a dropdown to force association. Or possibly clicking the language definition at the bottom right would allow you to override.

**Comment by redmunds** [comment]
@ericbieller There is now a dropdown menu in status bar for overriding the language for any file. This was introduced in Release 0.42. Additional "Set as Default" functionality was added in Release 0.44. Closing.
