### ISSUE TITLE
Go to Line shows Quick Open-style file matches if they contain ":"

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#6646]
1. On **Windows**, open a file external to the project
2. Invoke 'Go to Line'

Result: the external file is listed in a dropdown like a regular Quick Open result, even though the leading ":" means we're in "Go to Line" mode.  If the path/filename contains numbers, it can continue to show as you type a line number too.

I assume this will also repro if you're on Mac with a filename that contains ":" (I think that is a legal filename char on Mac/Linux).

Repros in Sprint 35 but not Sprint 33, so this is a semi-recent regression.

**Comment by MarcelGerber** [comment]
@peterflynn Looks like you missed closing this issue :)

**Comment by peterflynn** [comment]
Yep, confirmed this is fixed now too -- thanks
