### ISSUE TITLE
Sidebar can't be resized once filling whole window

### ISSUE THREAD

**Issue by FezVrasta** [adobe/brackets#6822]
If you expand the sidebar to take the entire width of the brackets' window, you can't resize it again to the original size...

![image](https://f.cloud.github.com/assets/5382443/2124175/5c50921a-9239-11e3-8743-1c4f85ed040b.png)

**Comment by solugebefola** [comment]
Has this issue been resolved?

**Comment by demonofthemist** [comment]
As of today this issue is still there, I just tried it on my computer :)
