### ISSUE TITLE
Pressing [Enter] in Extension Manager Search box closes Extension Manager

### ISSUE THREAD

**Issue by ashmind** [adobe/brackets#6904]
**Steps to reproduce:**

1. Open Extension Manager
2. Place focus in the Search box
3. (Optional) Type any text
4. Press Enter

**Expected result:**
Nothing happens. Since a lot of search boxes in web and desktop only search on Enter, it is natural to press Enter after typing. If the search is immediate, Enter should do nothing.

**Actual result:**
Extension Manager closes without doing anything, so I have to reopen it and re-type my search.

**Environment:**

* Windows 7
* Brackets Sprint 36 experimental build 0.36.0-11506 (release 942505c3a)

**Comment by lostlime** [comment]
+1

**Comment by FezVrasta** [comment]
Any news on this?

**Comment by abose** [comment]
Tagging @rroshan1 for extension manager improvements.

**Comment by niklasHagner** [comment]
+1

**Comment by Denisov21** [comment]
+1

**Comment by petetnt** [comment]
Fixed in #12839
