### ISSUE TITLE
Join (selected) lines

### ISSUE THREAD

**Issue by bburky** [adobe/brackets#7045]
Feature request: join the current line with the following line or join all selected lines.

A single space character should be added if needed between the joined lines.

A keyboard shortcut should be added too. Cmd-J is already taken for jump to definition, not sure what shortcut would be best.

This feature is useful for unwrapping hard wrapped lines in HTML.

**Comment by redmunds** [comment]
There is an extension called Oneliner that joins lines. Closing.

**Comment by juanpastas** [comment]
Will that be integrated in the core? that would be great.
