### ISSUE TITLE
Live preview opens Chrome Canary instead of stable Chrome

### ISSUE THREAD

**Issue by sapeish** [adobe/brackets#7062]
If both versions of Chrome are installed, Brackets opens Canary instead of regular stable Chrome.
```
Stable Chrome path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Chrome Canary path: C:\Users\sapeish\AppData\Local\Google\Chrome SxS\Application\chrome.exe
Brackets version: sprint 36 build 0.36.0-11506
OS: Windows 7
```

**Comment by redmunds** [comment]
Everything here is covered in [Chrome section of Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting#livedev-chrome). Closing.
