### ISSUE TITLE
Error 2503 installing brackets on windows 8.1

### ISSUE THREAD

**Issue by Sala7ism** [adobe/brackets#7140]
Hello

I faced a problem when trying to install brackets on my computer

"The installer has encountered an unexpected error installing the package. This may indicate a problem with this package. The error code is 2503."

I downloaded the last 4 versions from the download page on brackets.io and still get the same error.

Print screen of the error
![error-2503](https://f.cloud.github.com/assets/6896723/2367461/5661f726-a761-11e3-82dd-b36a637d4dae.jpg)

**Comment by peterflynn** [comment]
Closing since we never heard back from the filer. We have a newer report of the same issue in #10330 that may give us more info.
