### ISSUE TITLE
[PM] No Native Linux Menus

### ISSUE THREAD

**Issue by JeffryBooher** [adobe/brackets#7236]
Linux needs native menus.  The HTML menus look bad and to 
@ingorichter has done some of the work but ran into a conflict when another contributor said he was doing the work but then neither of them finished.

**Comment by dvorapa** [comment]
Is it still in progress?

**Comment by peterflynn** [comment]
@ingorichter should we remove the 'fix in progress' label if you don't have cycles for this?  Would it be worth pushing up a branch or a dummy PR with the work you started, so it's easier for another contributor to pick up where you left off?

**Comment by ficristo** [comment]
@ingorichter I removed "fix in progress".

**Comment by IgorNovozhilov** [comment]
A little negative publicity.
This is so old bug that I had to abandon the brackets and go to use VSCode :disappointed: 
#11501 
PS: Yes, it's not the only reason

**Comment by ficristo** [comment]
@IgorNovozhilov you can give a try to https://github.com/zaggino/brackets-electron/releases
