### ISSUE TITLE
[NodeConnection] Implement progress callback

### ISSUE THREAD

**Issue by zaggino** [adobe/brackets#7356]
I have a domain which spawns git commands - some of them are running quite a long time - especially the ones that communicate over network. The core of the code spawning processes is here: https://github.com/zaggino/brackets-git/blob/master/src/Domains/cli.js#L51-L71

I'd require a means for a "progress callback", which I can call multiple times before calling `callback` which will resolve the jQuery deferred on Brackets side. jQuery deferred already supports progress with `deferred.notify` so that shouldn't be a problem there, but I'm not quite sure how to do this in a domain code.

cc @iwehrman

**Comment by abose** [comment]
@zaggino I have merged the related PR's in both shell and brackets. Could we close out this issue?

**Comment by zaggino** [comment]
Sure, this has been resolved in the related PRs.
