### ISSUE TITLE
Quick Open dropdown doesn't move into position while Cmd/Shift are held

### ISSUE THREAD

**Issue by njx** [adobe/brackets#7367]
Tried this on Mac, not sure about Windows.
1. Open a project like citrus completed
2. Hold down Cmd-Shift
3. While still holding down Cmd-Shift, press O and then release (don't let go of Cmd-Shift)
4. Note the position of the Quick Open dropdown when it appears
5. Release Cmd-Shift

Result: While Cmd-Shift are held down, the dropdown slightly overlaps the text field. When you release Cmd-Shift, the dropdown jumps downward to the correct position. I think this is part of the reason why opening Quick Open can sometimes feel weirdly stuttery.

**Comment by peterflynn** [comment]
Should be fixed in 1.3
