### ISSUE TITLE
Auto New Line Between Opening and Closing HTML tags.

### ISSUE THREAD

**Issue by tilwinjoy** [adobe/brackets#7592]
Though the auto suggestion for closing tags is helpful, while using some other editors if i press enter between an opening and closing html tag, the cursor is automatically placed in a new line between them with proper indentation- This is really helpful and time saving.
          As for now, if i press  enter between an opening and closing html tag the cursor is placed on a new line followed by the closing tag. Then i have to press enter again to push the closing tag below, then press up to come back to the line in between and give proper indentation. It'd be great if this is automated... 

 Keep up the good work.

Thanks and regards.

**Comment by usual1989** [comment]
@njx  sorry I just start use Brackets. I have Emmet extension but still can`t do that. I mean press enter before closing tag,  and can`t get a new line. But in sublime text I can get it  with Emmet. Is there something in Brackets that I need to set?  Thank you.

**Comment by anjildhamala** [comment]
Followed Mr. TomMalbran suggestion and I am not entirely sure what he meant but writing "closeTags": true but I figured out that he meant have both whenOpening and whenClosing to be set to true. And Voila! It works!

**Comment by huadaonan** [comment]
i try it set the configuration  both all.still can not work
"closeTags":  {
    "whenOpening": false,
    "whenClosing": true
}
"closeTags":  {
    "whenOpening": true,
    "whenClosing": true
}
