### ISSUE TITLE
24 failures when running all unit tests

### ISSUE THREAD

**Issue by lkcampbell** [adobe/brackets#7637]
**OS:** Mac OSX Mavericks

**Brackets Version:** sprint 39 development build 0.39.0-0 (test 4d968b2c2).

**Repro  Steps:**
1. Launch the Jasmine Spec Runner from Brackets
2. Select the `All` tab and click on `All` tests.

**Expected Results:**
All unit tests should pass.

**Observed Results:**
There are 24 total failures every time.  Ten failures in the URL Code Hinting and fourteen failures in the JavaScript Code Hinting.

**Other Notes:**
If you run the URL Code Hinting and JavaScript Code Hinting suites individually, they all pass.  If you select `All` unit tests from the `Extensions` tab, which also includes both these test suites, all tests pass.

**Comment by redmunds** [comment]
We keep adding unit tests, so it's impossible as far as I know to run All/All unit tests. I created a [wiki page with Tips and Tricks for running Brackets unit tests](https://github.com/adobe/brackets/wiki/Running-Brackets-Unit-Tests) to help people work around this issue.

**Comment by lkcampbell** [comment]
I'm closing this issue as resolved by documentation per @redmunds comment above.
