### ISSUE TITLE
Brackets sometimes doesn't pick up file modifications

### ISSUE THREAD

**Issue by dbkaplun** [adobe/brackets#7638]
Is there any way to manually reload an open file from disk? If a file has been modified outside of Brackets, sometimes Brackets doesn't pick up these changes. It would be great to be able to do it manually.

**Comment by nethip** [comment]
Moving this to 1.3

**Comment by andyburke** [comment]
I mistakenly began discussing this issue in #7344. But this seems to be exactly what I am experiencing, see comments here:

https://github.com/adobe/brackets/issues/7344#issuecomment-77299224
https://github.com/adobe/brackets/issues/7344#issuecomment-77359739
https://github.com/adobe/brackets/issues/7344#issuecomment-77509422

**Comment by ryanstewart** [comment]
Moving this to tackle in 1.4.

**Comment by dynamicdan** [comment]
This also happens when files are modified outside of brackets via the command line or scripts. Most likely related to the "within 1 second" issue that is also logged here. File changes don't get picked up when they happen within 1 second.

**Comment by jpcaram** [comment]
This is consistently happening to me when the file is edited externally. No symlinks but on network drive.  Edits to my files take minutes (big logs). Refreshing the file tree as suggested does not fix it.

I used to be able to fix it by doing `touch myfile.txt` but not any more. No idea why.

**Comment by menocomp** [comment]
The same issue is still happen to me.
Whenever I run npm commands that add changes to the package.json file, that file never change and I have to restart brackets.

**Comment by busykai** [comment]
@nethip, I have a grasp of what might be going on with this. let me take this issue.

**Comment by MarcelGerber** [comment]
Finally fixed by #12353.
Closing.
