### ISSUE TITLE
Trackback warnings in blog.brackets.io

### ISSUE THREAD

**Issue by bchintx** [adobe/brackets#7692]
At the bottom of several of the blog post pages, WordPress is displaying a Trackback warning resulting from a missing 'thematic_pings' function parameter.

For example, below the comments [in this post](http://blog.brackets.io/2014/04/17/css-shapes-editor/#comments), the following warning appears:

`One Trackback
Warning: call_user_func() expects parameter 1 to be a valid callback, function 'thematic_pings' not found or invalid function name in /home/wp_twqxv4/blog.brackets.io/wp-includes/comment-template.php on line 1694
`

These messages appeared after we migrated to our new WordPress host.

**Comment by peterflynn** [comment]
These warnings seem to have gone away (even on older preexisting posts like the one linked above), so I'll close this as fixed.
