### ISSUE TITLE
Support for color definition format beginning with "0x"

### ISSUE THREAD

**Issue by arieljake** [adobe/brackets#7723]
In the ColorUtils file, I don't see a regex to match colors like this:

0xFFFFFF

Can we add this?

**Comment by PlanetVaster** [comment]
@redmunds Where is the ColorEditorTemplete.html located?

**Comment by redmunds** [comment]
ColorEditor template is in:

src/extensions/default/InlineColorEditor/ColorEditorTemplate.html

**Comment by PlanetVaster** [comment]
@redmunds Like this `<li title="{{COLOR_EDITOR_HEX_BUTTON_TIP}}"><a href="#" tabindex="0" class="0x">0x</a></li>` sorry if that is wrong I don't understand what your saying

**Comment by redmunds** [comment]
@PlanetVaster That's basically it, but it needs a unique `title` which is the tooltip.

**Comment by PlanetVaster** [comment]
So like `<li title="{{COLOR_EDITOR_0X_BUTTON_TIP}}"><a href="#" tabindex="0" class="0x">0x</a></li>`

**Comment by redmunds** [comment]
Yes, Then `COLOR_EDITOR_0X_BUTTON_TIP` string needs to be defined in src/nls/root/strings.js

**Comment by sQuarecoW** [comment]
What is the status of this?

**Comment by KrithikaNarayanan** [comment]
Guess i arrived here late... is this issue still open for claiming?

**Comment by petetnt** [comment]
@KrithikaNarayanan I think this hasn't been fixed / added yet. Feel free to work on it if you'd like to! 

See the article [How to hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) to get started with the Brackets codebase. If you have any questions, feel free to post them here! We also have a [Slack channel](https://brackets.slack.com) for day-to-day communication. (You can join by sending a mail to admin@brackets.io with the subject line `slack registration request` specifying the email addresses you would like to register).

**Comment by nyteksf** [comment]
Hello. I found myself interested in taking a crack at this issue if that could be approved.  :)

@zaggino

**Comment by zaggino** [comment]
Hi @nyteksf , you don't need anyone's approval to start working on an issue that's not being worked on. Just open a PR (unfinished is absolutely fine) that you're working on this and mention the link here. That will let others will know that the issue is being worked on.

**Comment by nyteksf** [comment]
Hello again. I believe I'm finished with this one. Please do feel free to let me know if any changes need to be made, and I'll be happy to get right on that for you. Thank you.

@zaggino @ficristo

**Comment by ficristo** [comment]
@nyteksf  thank you for filing the issue.
As a side note: in future, in your PRs, could you add the issue number also in the comment?
In this way GitHub cans generate an automatic link to your PRs in the issue itself.

**Comment by nyteksf** [comment]
@ficristo Noob question here, I suppose; being that this is my second PR ever. Could you please elaborate for me just a little about what was meant so I can do that for you all the next time? I already try to always add the issue number to the title and every commit message. Do you mean to also add it to the literal comments I am making much like this one? My bad. Thanks for your help.

**Comment by ficristo** [comment]
Don't worry about asking, you are welcome.
Yes, I meant exactly comments like this. Right now, for example, I don't know if you have already opened a PR, I can only see commits that were done in you fork.
So if I add the PR number like this #13154 now GitHub will show a link in the PR to this issue.
Adding the issue number in the title is fine, but will not generate a link.

**Comment by nyteksf** [comment]
#13154 - @ficristo Aha. I see now. And thank you very much.
