### ISSUE TITLE
Renaming a file to the same name but a different case produces an error

### ISSUE THREAD

**Issue by JeffryBooher** [adobe/brackets#7846]
Issue reported in PR #5096.

When renaming a file in the Project Manager without changing the name of the file (only changing the case), Brackets will throw an error because the OS (on certain platforms) doesn't recognize that only the case has changed.

This needs to be implemented in the native shell code to check to see if we're only changing case and rename the file using a method that doesn't cause the OS to fail.

**Comment by solugebefola** [comment]
Hasn't this been resolved in the brackets-shell PR aforementioned?  Should it be closed?

**Comment by abose** [comment]
Closing as fixed.
Thanks @solugebefola
