### ISSUE TITLE
Toggle Line Comment - removing leading whitespace breaks Jade preprocessor

### ISSUE THREAD

**Issue by Joe5** [adobe/brackets#8012]
Using toggle line comment eq Ctrl+/ places the opening comment character on the beginning of the line and includes the white space. It should be placed before actual content of that line. Problem is that this style of commenting breaks the flow of the document which results in crash of the compilers. For example Jade needs correct indentation levels to compile correctly.

**Comment by demisx** [comment]
+1 This issue breaks stylus code too. Indentation must be preserved.

**Comment by Moter8** [comment]
Same here, using stylus. It expects comments to be indented too :(

**Comment by mseiler025** [comment]
https://github.com/adobe/brackets/issues/11953

**Comment by MarcelGerber** [comment]
PR #11954 has added an option to indent at the beginning of line content (as opposed to at the beginning of the line).

It has been done by using a preference that is disabled by default.
To enable it for Jade/Stylus files only, use something along these lines in your `brackets.json`:
``` json
{
  "language": {
    "jade": {
      "indentLineComment": true
    },
    "stylus": {
      "indentLineComment": true
    }
}
```

**Comment by blairdow** [comment]
i've been working around this for months, so happy with this easy solution! I wish i had investigated wayyyy sooner :)
