### ISSUE TITLE
Extension folder not created

### ISSUE THREAD

**Issue by smalldelta** [adobe/brackets#8024]
Information:
I'm using brackets sprint 39 experimental build 0.39.0-12914 on Ubuntu GNOME 14.04LTS.

To reproduce:
Try to open the extension folder from the gui. It doesn't open.

I know this is an experimental build, so I'm not expecting perfection. But still, I feel I have to tell you so this won't be a bug in a "real" release.

EDIT:

I used the debug tool to further look into this and fount this error message printed on the console:

[Extension] Error -- could not read native directory: /home/tony/.config/Brackets/extensions/user 

EDIT 2:

The problem appears to be that the brackets/extensions/user directory is simply not created on install. I created it manually and now it works.

**Comment by le717** [comment]
@ingorichter @peterflynn FBNC in v1.2. The PR in brackets-shell has been merged.

**Comment by peterflynn** [comment]
Closing as fixed. @smalldelta please let us know if it does not appear fixed for you in 1.2
