### ISSUE TITLE
Expose mode and getTokenAt() on editor

### ISSUE THREAD

**Issue by gruehle** [adobe/brackets#804]
This is related to #803

While writing the "Inline Editor for JavaScript functions" and "Inline Image Viewer" extensions, I needed to access the "private" `_codeMirror` property in order to get the current mode (using `getOption("mode")`) and call the `getTokenAt()` function. 

We should either expose these on Editor, or consider just making the `_codeMirror` property public.

**Comment by ficristo** [comment]
Is there still something to do here? Has "token stream" landed?

**Comment by MarcelGerber** [comment]
I guess this can be closed now, as we've managed to achieve everything we need from our TokenUtils implementation.
Thanks for noticing, @ficristo (and yeah, it's been some time, I'm catching up with my mail again ;) )
