### ISSUE TITLE
auto-complete Not Work well for html5 canvas

### ISSUE THREAD

**Issue by sambook** [adobe/brackets#8081]
Missing auto-completion for `fillText` function at canvas context

```
 var ctx = canvas.getContext("2d");
 ctx.fillStyle="rgb(200,0,0)"; // auto-complete work
 ctx.fillText("Canvas API in Komodo!", 25, 40); // auto-complete NOT Work here.
```

**Comment by redmunds** [comment]
I submitted a pull request to Tern repo: https://github.com/marijnh/tern/pull/474

**Comment by redmunds** [comment]
Tern PR https://github.com/marijnh/tern/pull/474 was merged, so this updates Brackets with the fix.

**Comment by peterflynn** [comment]
Removing milestone since the fix isn't urgent -- but this will likely land for 1.2 anyway since the Tern update is already in progress.

**Comment by redmunds** [comment]
Closing. Fixed.
