### ISSUE TITLE
[Cycle times] Improving throughput calculation (based on Github label change)

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#8088]
Original Subject: Throughput calculation appears to be wrong

Copied from PR comment:

I think the cycle time data shouldn't actually factor into the throughput calculation at all.  For example:

* If we finish 5 cards in a week in serial, each card has a 1-day cycle time -> `avgCycleTime === 1`
* If we finish 5 cards in a week in parallel, each card has a 5-day cycle time -> `avgCycleTime === 5`

The throughput should be the same in both cases: 5 cards per week. But the equation in `getCategorySummary()` will instead give very different answers for these two cases...

**Comment by redmunds** [comment]
@peterflynn @pthiess Since we're now using Waffle this issue is obsolete. Closing.
