### ISSUE TITLE
[Cycle times] "% of total time" numbers may not be meaningful

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#8090]
From discussion in the PR:

@dangoor:
> I wasn't there for this discussion, but it seems like listing process cards as a percentage of the "total time" is not necessarily meaningful. I don't think we can look at this number and say something like "we spend 5% of our time doing process stuff" because the calendar time it takes for something to get through is not completely the same as how much effort goes into it.

@peterflynn:
> I think this has the same problem as the throughput calculation above: the cycle times are affected by parallelism, so this number will be skewed in ways that make it hard to reason about. Using the same example above, 5 cards completed in serial yield `allTotal === 5` while 5 cards completed in parallel yield `allTotal === 25`. This seems like it makes even the trend of percentages over time meaningless (since we can't assume the degree of story parallelization is always the same).

> Since this wasn't in the original story criteria and doesn't seem to be well defined/specified, maybe we should just remove or comment out this block of code for now?

**Comment by redmunds** [comment]
@peterflynn @pthiess Since we're now using Waffle this issue is obsolete. Closing.
