### ISSUE TITLE
White screen when starting Brackets

### ISSUE THREAD

**Issue by ingalls** [adobe/brackets#8098]
When starting Brackets it will occasionally start with a white screen. The window will become unresponsive and have to be killed from terminal. 

As per #5381 this can be temporarily fixed by clearing `cef_data` and restarting.

**Comment by ingalls** [comment]
Stale, haven't experienced this issue in more recent versions of brackets.

**Comment by mflow42** [comment]
I faced this issue yesterday. Don't know why.

**Comment by SherrodWare** [comment]
When I open brackets all I get is a black screen.  Why is this?
