### ISSUE TITLE
Expand/Collapse all can cause some files in list to do the opposite

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#8208]
1. Do a Replace In Files...
2. Click to collapse one item (optionally collapse a couple more items individually too)
3. Ctrl/Cmd+click that item (should mean "expand all")

UPDATE: this only happens for "Replace in Files...", not "Find in Files...", so updated recipe.

Result: that item expands but all the ones you didn't touch collapse instead. Any time you do an expand/collapse all, those items will now be inverted relative to the individually-touched ones.

**Comment by PatrickDallarosa** [comment]
Looking for a simple way to contribute for a first timer. Providing the unit testing seems simple enough. Can I undertake this bug? Any guidance would be appreciated.

**Comment by Denisov21** [comment]
PR Added unit testing for issue [#12390](https://github.com/adobe/brackets/pull/12390)
