### ISSUE TITLE
Electric char auto-indentation doesn't work with multiple cursors

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#8434]
Start with this:
```
if (foo) {
    |
if (bar) {
    |
```

1. Put a cursor where each '|' is (don't actually include the '|'s in the text)
2. Type '}'

Result: Only the last one is back-indented properly:
```
if (foo) {
    }
if (bar) {
}
```

This is because `Editor._checkElectricChars()` isn't multi-cursor aware.

**Comment by prafulVaishnav** [comment]
Fixed by PR #9387
