### ISSUE TITLE
Select parts of camelCase strings

### ISSUE THREAD

**Issue by davidbarredo** [adobe/brackets#8545]
Like eclipse, with (Ctrl + Shift + Left arrow or Ctrl + Shift + Right) or (Ctrl + Left arrow or Ctrl + Right arrow) select or go to next uppercase letter in string with camelCase style

**Comment by Denisov21** [comment]
I created a extension: https://github.com/Denisov21/Popup-menu-extension

**Comment by MarcelGerber** [comment]
Closing as an extension is available now.
