### ISSUE TITLE
Dragging in color picker square rapidly causes hue to change

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#8572]
1. Open a color picker on `#94A3A7`
2. Start dragging the saturation-brightness picker in circles

Result: the hue slider starts jumping around. If you drag it in bigger circles, the hue jumps to the end of the slider (red).

This looks to be an older regression: it's UTR in Sprint 33, but it does repro for me in Edge Code Preview 7 (Sprint 38).

**Comment by MarcelGerber** [comment]
@peterflynn Still FBNC
