### ISSUE TITLE
Deleting a file shows no confirm dialog

### ISSUE THREAD

**Issue by Mark-Simulacrum** [adobe/brackets#8651]
Even if files can be retrieved from the trash bin, this seems like something that should at least be optional. I often accidentally click delete when attempting to rename a file, which causes me to have to either go find the file in trash (which often takes up 5 minutes or so of time) or to restore it from Git (if I am in a Git repository).

I am not really sure how Brackets will handle a file system without a trash location (read only discs, file shares, USB drives often have this), it seems safer to just open up a (optional) dialog to ask the user if they really want to delete the file.

**Comment by wilfm** [comment]
I am trying out Brackets (very good so far :), but find it odd that the delete function has no prompt, and moves any files 'deleted' to trash with no questions asked (but does prompt for folders... ?)

Would it be possible to build a extension to do this, or are extensions not allowed to manage this functionality? (I am guessing from looking at the pull request that it has to be compiled in from source).

Built from source (this morning - don't want to do it again today..), Fedora 21 (Linux) x86_64

**Comment by MarcelGerber** [comment]
A Confirm dialog is now shown when deleting a file.
Closing.
