### ISSUE TITLE
Extension Manager returns 404 error for when extension version contains "+"

### ISSUE THREAD

**Issue by jasonsanjose** [adobe/brackets#8692]
I posted an extension zip named `jasonsanjose.brackets-sass-0.4.1+sha.fc425b5.zip`. The link from the registry https://brackets-registry.aboutweb.com/ points to https://s3.amazonaws.com/extend.brackets/jasonsanjose.brackets-sass/jasonsanjose.brackets-sass-0.4.1+sha.fc425b5.zip which returned a 4040.

I rebuilt my extension to drop the `+sha...` metadata. 

Since we explicitly link to semver here https://github.com/adobe/brackets/wiki/Extension-package-format#packagejson-format, we should either note the exception for `+` plus signs or update the registry to support plus signs.

**Comment by ingorichter** [comment]
Closing. This got deployed in the meantime.
