### ISSUE TITLE
CSS Colors Highlight

### ISSUE THREAD

**Issue by wootimes** [adobe/brackets#8695]
As a designer, I would like to see color highlight of my project.

In the attached screenshot hex colors highlight left side.

![snap 2014-08-08 at 01 28 21](https://cloud.githubusercontent.com/assets/8388437/3848268/34de76cc-1e6e-11e4-908f-07764594dee3.png)

**Comment by QW0101** [comment]
I finished a similar plugin
https://github.com/QW0101/Brackets-Color-Highlighter

**Comment by talmand** [comment]
@QW0101

Really nice.

I haven't had any time for a while now to tinker with this. Good to see someone moved forward with it. I had played with the idea of the background color but needed a way to contrast the text inside in case of matching colors. I just didn't have time to look into it. I see that it appears you went that direction with making sure text was legible inside the background color. Excellent.

**Comment by QW0101** [comment]
@talmand
Simple formula
`Color.prototype.light = function () { return (this.r * 0.8 + this.g + this.b * 0.2) / 510 * 100; }`

**Comment by abose** [comment]
Closing as several extensions available :)
