### ISSUE TITLE
Show / link to actual source path when running from symlink in developer 'setup for hacking' mode

### ISSUE THREAD

**Issue by apdarshan** [adobe/brackets#8795]
I am working on brackets core source code. I have different repositories (in different locations) of source code and I keep swapping(by [hacking](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets)) between them. And each time I forget last hacked directory location. Figuring out by adding alert/console on all brackets.js files in every repositiores :-(

So, I would like to have a menu something like ```Open Brackets Source Directory```  under ```Debug``` menu.

I guess this would also be handy in general use cases like,
* If you forget your hacked directory
* If you are using your buddy's computer, in which you don't know the hacked source dir. path
* -If that menu is disabled, we can even identify that its not yet hacked

-You can still open brackets **installed** source directory, *though its not yet hacked*. For quick check.

**Comment by MarcelGerber** [comment]
This one can be closed - Already implemented.

**Comment by apdarshan** [comment]
Thank You Guys :+1:
