### ISSUE TITLE
Live Highlighting: unpredictable when changing selection will "flash" the highlight

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#8914]
1. Open the Getting Started project and launch Live Preview
2. Click around rapidly in the HTML or CSS code, while watching the browser window

Result: seemingly randomly, as the Live Highlighting changes, some of the time it will just draw a blue border with no animation and other times it will flash the entire rectangle with a fade-out animation.

It _seems_ like the pattern is: if you change the highlight while the previous one was still animating, the next one won't animate at all.

I'm guessing the intent was to suppress the animation while moving the cursor around rapidly.  But this isn't the behavior: because the second highlight is drawn without animation, the third _will_ be animated, the fourth won't, the fifth will, etc.  So the animation flashes on & off as the cursor is moved instead of just staying off.

But it actually may be even buggier than that: if you click around enough, it seems like you get into states where, even many seconds after the animation is over, clicking to a different item still doesn't animate sometimes.  But that's harder to repro.

**Comment by redmunds** [comment]
This seems to have been fixed by @busykai 's PR #10151. FBNC back to @peterflynn .

**Comment by prafulVaishnav** [comment]
@peterflynn Hi. I checked for this issue. It has been fixed. 
Can we close this issue?

**Comment by nethip** [comment]
Closing as this seems to be fixed now.
