### ISSUE TITLE
Application freeze

### ISSUE THREAD

**Issue by jcw-** [adobe/brackets#8916]
On August 17, 2014 I installed Brackets (sprint 42 experimental build 0.42.0-13957 (release f9fcb884f) build timestamp: Thu Jul 31 2014 10:35:35 GMT-0700) on Windows 7. I have not installed any extensions.

I have been using it fairly heavily for html/css and a bit of javascript for the past two weeks, in which time it has frozen three times, with this most recent time resulting in the loss of work.

When it freezes, the main portion of the application (the tree on the left and the editor panel) become frozen, but the top portion of the application is usable, I can use the File menu, but clicking the menu items seem to have no effect. Clicking the application's close button (the X) also has no effect. I have to kill the process.

The first time this happened, I think I was switching files using the "Working Files" area. I don't have a project (I don't think?) I just drag files from Windows Explorer into the Working Files area as I need them. I have a couple html files, a couple css files, and in one case I might have had a js file opened (although only css and html files open this last time, 5 html and 1 css).

The first time it froze (when I was switching active files), the screen looked kind of weird, I think part of it was not drawn, I don't really recall. I forget the details of the second time, I think I had left it open since the previous day and when I switched to it, the entire window was unresponsive (which might be a different issue, not entirely sure). This most recent time, I had just pressed the keyboard paste shortcut, I saw the text appear in my html file, and then it was frozen - no input was accepted in the navigator on the left or on the editor portion of the window.

I have enabled the crash logs in the registry as described on the wiki, and I will post more information as it becomes available.

Thanks!

**Comment by JeffryBooher** [comment]
Closing.  @jcw- let us know if you see this issue resurface.
