### ISSUE TITLE
Editor.selectWordAt() disagrees with double-clicking

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#8925]
1. Double-click the variable name in `var $panel;`
2. Right-click the same variable name

Result: all of `$panel` is selected when double-clicking, but only `panel` is selected when right-clicking.

It looks like we forked CodeMirror's `findWordAt()` into a copy in Editor (`selectWordAt()`) back in #2012, but they haven't been kept in sync since.  The CM version is now more language-aware, while ours is still generic.  It seems like we should make the CM version public if possible, and just use that going forward.

**Comment by nethip** [comment]
Closing this as the PR is now merged.
