### ISSUE TITLE
Brackets crash after closing developer tools

### ISSUE THREAD

**Issue by n1kkou** [adobe/brackets#9011]
Opening Developer Tools will crash the Brackets window, after closing the Developer Tools window.
Current configuration: Windows7 / 64bits operation system

**Comment by MarcelGerber** [comment]
I think we can close this now that we have CEF 2171. I haven't hit it a single time since updating to Brackets 1.1 Shell.
Or should we leave it open as long as the Linux users still have CEF 1547?

**Comment by peterflynn** [comment]
@MarcelGerber Good point!  I don't think this has ever been reported on any OS other than Windows, so it should be safe to close it.

**Comment by thrash646** [comment]
I now have this same issue on v1.5-1.7 of brackets. 
Pretty sure it happened when I accidentally removed dev tools and then turned it back on.

I started a new thread here:
https://github.com/adobe/brackets/issues/12570
