### ISSUE TITLE
Whole line cut/copy/paste indentation/new line issues

### ISSUE THREAD

**Issue by le717** [adobe/brackets#9130]
I'm not totally sure how to explain this, so here is a GIF showing the issue using the Getting Started project. Feel free to rename the issue for clarification.

Running Brackets 0.44 at bf9efc319 from master, also repos in 0.43 or whenever https://github.com/marijnh/CodeMirror/commit/12e3efe4aeff5c02e8299d62a80ec481ea14b6bd (marijnh/CodeMirror#2382) was pulled in.

![whole-line-cut-copy-paste2](https://cloud.githubusercontent.com/assets/3382464/4294370/d991c19e-3dde-11e4-9a5d-d45aae0b929d.gif)

**Comment by ficristo** [comment]
@peterflynn is the current behaviour the expected one or should we match Sublime?

**Comment by mallman** [comment]
I would like to add my perspective here.

The main issue that's frustrating for me is there doesn't seem to be a way to cut/copy a block of text without codemirror adding an extra newline at the end. This is especially frustrating when I'm trying to paste multiple copies of a single line. I end up having to go back and manually delete an empty line for every paste I performed. Personally, I've never used or seen another editor that behaves this way, so I assumed this is a bug. But maybe this is desirable behavior in some cases?

Cheers.

**Comment by mallman** [comment]
> The main issue that's frustrating for me is there doesn't seem to be a way to cut/copy a block of text without codemirror adding an extra newline at the end.

Sorry, this seems to be a Safari-only bug: #2900. Guess what browser I'm using? *sigh*
