### ISSUE TITLE
accidently press of ctrl+C or Option+C clears clipboard. even nothing is selected

### ISSUE THREAD

**Issue by mfarooqi** [adobe/brackets#9311]
<b>Brackets version </b>
I found following bug in Brackets Release 0.42 and 0.43. I don't know if it has in previous versions. 

<b>OS version </b>
Mavericks 10.9.4

<b>steps to trigger the problem </b>
By following this scenario you can notice the bug...

.. type something in Brackets
.. select some text
.. copy that by pressing "Ctrl+C" or "Options+C" or "Edit -> Copy"
.. In the new lines press "Ctrl+V" or "Options+V" etc.. that copied text is pasted..
.. now Don't select anything. and just press "Ctrl/Option+C" on some empty line.
.. try to paste the previously copied text By pressing Ctrl/Option+V... you wouldn't get anything. our pasted text is empty.

<b>what you expected to happen </b>
. while untill we don't select anything, our previously copied text should remain on the clipboard...

<b>What happened </b>
I'm working on a one page application using HTML+JS on one page and CSS on another.. it's 3000 lines of code almost .. It might get longer in next few days.. 
If i find something within my codes and copy them to paste on other lines.. one accidental press of Option+C or Ctrl+C on next blank lines empties my clipboard

Please notice this as bug and remove this. I have used Adobe Code CC .. This kind of issue doesn't exists in Adobe Code CC.

**Comment by pjwalmsley** [comment]
:+1: 

Never noticed this in other editors, but it really bothers me in brackets (my primary editor).  Often, I go to paste something but accidentally hit ctrl-c and copy over my previous content forcing me to undo a lot, recopy, then redo a lot.  I prefer to use duplicate or triple click to copy a line.

**Comment by MarcelGerber** [comment]
In the next Brackets release, there will be a pref `lineWiseCopyCut`, which you can disable so this doesn't happen again,
Closing.
