### ISSUE TITLE
Visual indication of file's read-only status

### ISSUE THREAD

**Issue by isonno** [adobe/brackets#9329]
Those of us using Perforce often browse files that are read-only because they're not checked out yet (unlike Git, which always keeps files writable).  

It would be very useful to have a visual indication of a file's read-only vs. read-write status, e.g., a lock icon next to the filename in the title bar or the "Working Files" list.

**Comment by PhiLhoSoft** [comment]
I had a look and apparently Brackets doesn't expose the read-only (or other attributes) status in the file API.
My starting point was the Various Improvements plugin which fetches the file date / time and display it.
https://github.com/Dammmien/brackets-various-improvements.git

I found something better (somehow): the Perforce plugin:
https://github.com/JoshGalvin/brackets-perforce.git

Very primitive (just checkout to default CL the file if dirty / add it if new / delete it if removed) but already eases my life.

Having a read-only indicator can still be useful ("it is file in a CL?").

**Comment by mseiler025** [comment]
I made an extension for this - https://github.com/mseiler025/show-read-only

**Comment by abose** [comment]
Thanks @mseiler025 .
Could you post a screenshot in the GitHub readme.md page in the extension repo?

**Comment by mseiler025** [comment]
@abose posted screenshot

**Comment by mseiler025** [comment]
There is more work to be done on this extension, but I wanted to get something out there for now.

Things that I can think of that could be done:

-handle listed known limitations

-optionally, use addClassProvider to make file names for read only files another color, etc (might be useful if you have another icon provider and don't want to see multiple icons)

-as @isonno mentioned, add visual indication at that top (title bar) of current open document

-as @1for mentioned, have an option to make the read only file writable (possibly through a context menu item), or make a copy of the read only file to write to it

**Comment by abose** [comment]
Thanks @mseiler025 For updating. 
Closing as extension available.
