### ISSUE TITLE
Cannot create new file in the project root once you create new files in a folder.

### ISSUE THREAD

**Issue by RaymondLim** [adobe/brackets#9341]
1. Create a new project.
2. Right click in the file tree and select New Folder. Accept the default name.
3. Right click in the blank space and create another folder with the default name.
4. Right click in the first folder and create a new file with the default name.
5. Right click in the blank space below the second folder and try to create a new file or folder.

Result: the new file/folder is created inside the first folder created in step 2.

**Comment by bobiblazeski** [comment]
Any update on this ? It's annoying for both files and folder. Though with folders you have workaround by opening the lowest folder first, for root files there is no solution.

**Comment by Soulcyber** [comment]
Same problem for me while trying to create a new file in the root folder.
Near a year from the report and no fix yet :(

**Comment by redmunds** [comment]
It's not obvious, but a workaround is to right-click on any file (not folder) in root, then *New File* and *New Folder* will create new items in the root.
