### ISSUE TITLE
Extension Manager throws TypeError on selecting tab

### ISSUE THREAD

**Issue by yaddran** [adobe/brackets#9466]
Mac OS X 10.9.5

Release 0.44 experimental build 0.44.0-14876 (release 6d2d33d80) 
build timestamp: Fri Oct 03 2014 15:05:19 GMT-0700

console log:
```
Uncaught TypeError: Cannot set property 'scrollPos' of undefined /extensibility/ExtensionManagerDialog.js:310
setActiveTab /extensibility/ExtensionManagerDialog.js:310
(anonymous function) /extensibility/ExtensionManagerDialog.js:319
o.event.dispatch thirdparty.min.js:560
r.handle thirdparty.min.js:560
```

The code in question:
```javascript
function setActiveTab($tab) {
    models[_activeTabIndex].scrollPos = $(".modal-body", $dlg).scrollTop(); //line 310
    $tab.tab("show");
    $(".modal-body", $dlg).scrollTop(models[_activeTabIndex].scrollPos || 0);
    $searchClear.click();
}
```

How to reproduce:
1. Debug -> Show Developer Tools
2. File -> Extension Manager
3. As soon as you see the dialog click on "Installed". You have more time to produce the error if you do this after fresh start of the Brackets but it is always there.

**Comment by MarcelGerber** [comment]
This is now hopefully fixed on master.

**Comment by peterflynn** [comment]
Closing as fixed

**Comment by busykai** [comment]
@peterflynn seems like you forgot to close.

**Comment by peterflynn** [comment]
Good catch!
