### ISSUE TITLE
can't search extensions and themes

### ISSUE THREAD

**Issue by Turqueso** [adobe/brackets#9489]
It's the second time this happens to me but last time was a while a go, so I thought it was because of the extension uninstalled. Not sure how reproduce this but this is what happened:

I opened extension manager, went to uninstall a Theme, closed and reloaded.
Then when I open the extension manager to search for another theme or an extension and I can't type anything on the search field.

Everything else seems to work fine.

**Comment by arunlodhi** [comment]
I had the same problem and I found that it was caused due to the extension "Various Improvements". Removing the extension fixed this error.

**Comment by Turqueso** [comment]
@arunlodhi i did the same as you and it's fine now

**Comment by redmunds** [comment]
@Turqueso @arunlodhi Can someone open an issue on the repo of that extension? Thanks.

**Comment by arunlodhi** [comment]
@Turqueso Glad that it helped you :)
@redmunds I have already opened the issue:
https://github.com/Dammmien/brackets-various-improvements/issues/19
Thanks.
