### ISSUE TITLE
Typing a new CSS property: value pair (A) in front of another (B) on same line ends up replacing B's property name

### ISSUE THREAD

**Issue by kylelondonuk** [adobe/brackets#9496]
I'm not sure if this is by design, as I've found several issues/fixes listed on here about neighbouring content being replaced instead of new content being inserted, but here's what happens.

When typing CSS, i tend to alphabetise my properties, which means sometimes i put my cursor in front of an existing property/value pair to start typing a new one. To give an example, i may have a line like this:

`position: absolute;`

and I might put my cursor in front of the "p" of position to start typing a new property/value (let's say I want to type:

`left: auto;`

Whenever I do this, the following happens:

If the VALUE I'm typing for the new property is a text string like "center", "auto", "uppercase" (so NOT an integer or a unit like "2" or "2px" or "2em", then once i complete the new line with a semi colon and hit the ENTER button, the cursor doesn't break to a new line as expected. Instead, code hinting replaces the "position" property (just the property, NOT the colon coming after it) with the first matching code hint (which is always the "align-content" CSS property) including a NEW and NEW space. so what I would like to see on my screen is:

    left: auto;
    [cursor is now here after hitting ENTER]position: absolute;

but instead i have:

`left: auto;align-content: : absolute;`

So you end up:
1. losing the "position" property
2. gaining an unwanted "align-content" property
3. gaining an unnecessary extra colon and space (because the colon and space that belonged to "position" is kept, and a new colon and space are added after the new, unwanted, "align-content" property)
4. not getting a new line (although this is perhaps a reasonable consequence of number 2, since hitting ENTER while the code hinting list is visible always selects a property instead of creating a new line)

Can anybody help?

**Comment by MarcelGerber** [comment]
This should now be fixed. Please check and let us know whether you still see this issue.
