### ISSUE TITLE
Can't use as default text editor for file associations: no file is open

### ISSUE THREAD

**Issue by nchieffo** [adobe/brackets#9500]
Ubuntu 14.04
Bracket 0.44.0-14876

I associated brackets as the default editor for text files.
When I double click on a text file, bracket opens, but the file is not opened

**Comment by akhil111** [comment]
Me too.Im using both atom and sublime but,problem is same.when i right click on that file and checked its properties it says you don not have permission

**Comment by au42** [comment]
I'm also getting this on the earlier 12.04.5 LTS Ubuntu release as well as the latest one. It's annoying because I want to set Brackets as a default editor for my php, css, etc files.

**Comment by wizzor** [comment]
+1

**Comment by peterflynn** [comment]
Closing since this is already tracked on our feature backlog: [Open File/Folder from Command Line on Linux](https://trello.com/c/6JZLKIHn/1379-open-file-folder-from-command-line-on-linux).  Please upvote that item to help raise its priority.

(See also duplicates of this issue such as #8128, #6991)
