### ISSUE TITLE
No error recovery or logging for invalid state.json files

### ISSUE THREAD

**Issue by sarciszewski** [adobe/brackets#9520]
On Windows 8.1...

1. Install Brackets
2. Open a folder
3. Install an extension (e.g. brackets-git)
4. Restart to install the extension

You end up back at the "Getting Started" folder. The extension is still installed, but on every startup it displays the "we just installed" prompt.

**Comment by sarciszewski** [comment]
I've recreated the issue. Apparently it has to do with Windows 8 file corruption when a sudden power outage occurs. I would recommend notifying users when state.json is corrupt and giving them the option to reset it within Brackets.

**Comment by redmunds** [comment]
@sarciszewski This sounds like the same underlying issue as #9880. I submitted pull request #10390 yesterday as a proposed fix. Marking this as Fix in Progress.

**Comment by rroshan1** [comment]
Issue fixed with PRs #10390 and #10951.

**Comment by sarciszewski** [comment]
:+1: Awesome, thanks ;)
