### ISSUE TITLE
Re-open unsaved tabs/files

### ISSUE THREAD

**Issue by teenage** [adobe/brackets#9592]
Just like Sublime-text, all opened files (new or not) should be saved* on Brackets close (without asking for it). 
On brackets re-open, these files should be restored in their last state.

\* modifications on existing files should not be save on the file itself but elsewhere, so it will be reopened in a "modifed state" letting the user the final word on saving these changes or not in the actual file

**Comment by kalligator** [comment]
+1

**Comment by ApfelUser** [comment]
+1

**Comment by inovek** [comment]
+1

**Comment by Ksrinivas92** [comment]
+1

**Comment by skaneria** [comment]
+1

**Comment by nethip** [comment]
We already have a trello card for this. Please upvote this trello card.
https://trello.com/c/xFiAjzTK/327-auto-save-backups-to-temp-location

Closing this.
