### ISSUE TITLE
OSX Yosemite: green “stoplight” doesn't show when you expand brackets to full mode.

### ISSUE THREAD

**Issue by ghost** [adobe/brackets#9608]
As you know, Yosemite made the green button function as the full screen button. When you click on the full screen button, you can't see the green button therefore, you can't get out of fullscreen unless you close the application.

**Comment by excomedia** [comment]
The problem pops up again on 10.11 beta. Maybe checking for 10.10 and later would do the trick here.

**Comment by nethip** [comment]
@excomedia Thanks for reporting this! I am seeing this bug in 10.11. Let me check `brackets-shell` code to understand what might be causing this issue.

**Comment by nethip** [comment]
Found it!  https://github.com/adobe/brackets-shell/blob/master/appshell/cefclient_mac.mm#L255 is the culprit. Will fix this!

**Comment by ingorichter** [comment]
There must be a better way to distinguish `new` from `old` OSX versions.

**Comment by nethip** [comment]
@ingorichter I am done with the fix. I will put up a PR for this.

**Comment by nethip** [comment]
@vonStein @ingorichter This is fixed now with this PR https://github.com/adobe/brackets-shell/issues/526
