### ISSUE TITLE
Using CTRL-G with split screen causes selected line to be at different locations in each window

### ISSUE THREAD

**Issue by mitchhentges** [adobe/brackets#9629]
When using the "Go to line" functionality, the selected line is at a different height on my screen: the left split screen is 3 lines higher than the right side.

This is on a 1680x1050 screen.

This is a slight issue when I'm doing diffs between files and I want to compare lines above and below content that doesn't match between files. Having an offset between them requires me to align them manually for each discrepancy.

To reproduce:
1. Change to split-screen mode
2. Fill up both screens with the same content
3. Use "Go to line" to move to some line
![differentline](https://cloud.githubusercontent.com/assets/7784737/4739453/c878ba1a-5a04-11e4-961e-6bfc345a2dc5.gif)

**Comment by peterflynn** [comment]
This was seemingly fixed by PR #9624, so closing
