### ISSUE TITLE
Working Set > Rename on external file will result in the first file tree entry being highlighted

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#9650]
1. Open some external file in Brackets
2. Right click it (in the Working Files) and select "Rename..."

Result:
The first file/folder in the file tree is subtly highlighted

Expected:
No-op or some error visualization

**Comment by ficristo** [comment]
and, as I just discovered, you cannot rename that file :cry:

**Comment by MarcelGerber** [comment]
Confirmed fixed.
