### ISSUE TITLE
Selection highlight right edge is misaligned while naming New Folder

### ISSUE THREAD

**Issue by MarcelGerber** [adobe/brackets#9700]
1. Right click a folder in the file tree
2. Select "New Folder"

Result:
The right part of the selection highlight is off
![unbenannt](https://cloud.githubusercontent.com/assets/2641501/5710701/93ab69fa-9aa4-11e4-83c9-f442e375a5bf.png)

**Comment by peterflynn** [comment]
@MarcelGerber I'm confused by this description: in the screenshot, it looks like the default folder name fits fully in the naming box, and nothing is cut off.  What is missing in the screenshot that you expect to be visible?

**Comment by MarcelGerber** [comment]
As you can see in the outlined screen version below, the right part of the different-colored selection is off.
![unbenannt](https://cloud.githubusercontent.com/assets/2641501/5710701/93ab69fa-9aa4-11e4-83c9-f442e375a5bf.png)

**Comment by peterflynn** [comment]
Ahh sorry, I thought you said "cut off" not just "off" -- my mistake.  Will clarify title.

**Comment by MarcelGerber** [comment]
Oops, sorry for the non-helpful title.

**Comment by peterflynn** [comment]
No worries!

**Comment by MarcelGerber** [comment]
Fixed in #10402 
Closing.
