### ISSUE TITLE
[Extension Registry] Certain images cannot be found

### ISSUE THREAD

**Issue by Mark-Simulacrum** [adobe/brackets#9762]
When opening the Dev Tools in the Extension Registry, I see the following:

```
GET https://brackets-registry.aboutweb.com/img/AboutWeb-Logo-square-medium.png 404 (Not Found)
GET https://brackets-registry.aboutweb.com/img/Linode_logo.png 404 (Not Found)
GET https://brackets-registry.aboutweb.com/img/AboutWeb-Logo-square-medium.png 404 (Not Found)
GET https://brackets-registry.aboutweb.com/img/Linode_logo.png 404 (Not Found)
```

These images should either be added, or removed from the HTML (so as not to be requested).

**Comment by saurabh95** [comment]
I have added the images in brackets-registry (https://github.com/adobe/brackets-registry/pull/77), 404 error is resolved now.
