### ISSUE TITLE
[UX] Inactive panel gets dimmed in split view in release v1.0 

### ISSUE THREAD

**Issue by MikeSpock** [adobe/brackets#9785]
This isn't necessarily a bug, but definitely a usability issue. Split view is often used when you want to read one code and write the other. The inactive panel gets dimmed which makes the content hard to read.
This is especially bad when you want to use Brackets in a strongly lit enviroment.

**Comment by peterflynn** [comment]
We discussed this again in review today and here's what we want to do:

* Editor content does not dim anymore when a pane is inactive.  (If people want this effect, they can install the "Zen Panes" extension).
* Pane header _does_ still dim when pane is inactive.
* If users report that this makes it too hard to tell the pane is focused (and the dimming/"Zen Panes" effect isn't a good enough fix), then we can revisit this and consider other treatments like a pane border or a brighter highlight in the pane header.

**Comment by le717** [comment]
@peterflynn +1 I like that idea. I'd rather install an extension dim the pane rather than undim it.

**Comment by prksingh** [comment]
@peterflynn Please review

**Comment by peterflynn** [comment]
Closing -- this will be fixed in 1.2 per my [comment above](https://github.com/adobe/brackets/issues/9785#issuecomment-69669669).  Please let us know if you have any more feedback.
