### ISSUE TITLE
Opening file and adding to working set sometimes opens duplicate

### ISSUE THREAD

**Issue by mat-mcloughlin** [adobe/brackets#9864]
I've been using the command 

    CommandManager.execute(Commands.CMD_ADD_TO_WORKINGSET_AND_OPEN, { fullPath: unixPath, paneId: 'first-pane' }).done(function() { });

to open up a file. But occasionally this opens up a new instance of the file in the working set.

I've not been able to reliably pin down a reason for this happening yet.

**Comment by peterflynn** [comment]
I'm unable to reproduce this too.  @mat-mcloughlin, any luck on figuring out a sequence of steps that can consistently cause this?

**Comment by mat-mcloughlin** [comment]
I __could__ consistently call it. But this was before 1.0 so it may have been inadvertently fixed

Feel free to close

**Comment by prksingh** [comment]
Closing for now. Please let us know if you see this again and we can reopen the bug. Thanks.
