### ISSUE TITLE
Brackets doesn't detect corrupt state.json file

### ISSUE THREAD

**Issue by SirCheeseyMelon** [adobe/brackets#9880]
The program works fine an all, but every time I open it, it opens with the "getting started" folder

**Comment by peterflynn** [comment]
We should consider showing an error if we're unable to write to it also, since that seems to have cropped up as a problem on Linux for several users

**Comment by redmunds** [comment]
Updated title. Bracket should detect when state.json cannot be read or written and try to delete it so a new file can be created (i.e. start from scratch). If it cannot be deleted, then an informational message should be displayed explaining that file needs to be manually deleted.

**Comment by nethip** [comment]
Moving this to 1.3

**Comment by rroshan1** [comment]
Issue fixed with PRs #10390 and #10951.
