### ISSUE TITLE
Extract for Brackets: Unicode characters are converted into HTML entity codes

### ISSUE THREAD

**Issue by vstephenzhou** [adobe/brackets#9882]
when I use "copytext" in "assets.adobe.com" , I paste Chinese characters into brackets and these characters are normal.
but in New version of "Extract for Brackets Private Preview": chinese text will be converted into code like '&#x8bf6'(you are right, i am sorry @peterflynn)
In my opinion these become lengthy and can not read and modify.
It is very inconvenient to read, modify and maintain. 
how can i copy the original text from psd?

**Comment by VladIT4** [comment]
Good afternoon! Sorry for my English. Here is my solution to this problem. Open the console in the editor (F12), and run the code.
```javascript
jQuery('#project-files-container').append('<textarea id="text"></textarea>');
jQuery('#text').css('margin-top', '100px')
jQuery('#text').css('height', '100px')
document.getElementById('text').onblur = function() {
		var el = document.createElement('div');
		el.innerHTML = document.getElementById('text').value;
		document.getElementById('text').value = el.innerText; 
}
```
After you copy the text from the PSD, insert text into this field. Take the focus off the field and it is the text you want.
The decision is bad, but it works.

**Comment by abose** [comment]
Deprecated feature. Closing.
