### ISSUE TITLE
Ubunti 14.10 Problems

### ISSUE THREAD

**Issue by stollar** [adobe/brackets#9883]
Ob Ubuntu 14.10 Brackets opens but the window does not initialize.  The left-nav is just an empty grey area and there is a menu above the main window ares (File | Edit | Find | ... ) Ths icons at the right do not function.
Installed from: Brackets.Release.1.0.64-bit.deb
I need to kill -9 brackets -  File -> Quit does nothing!

**Comment by pickettd** [comment]
I ran into this problem today. I don't have any experience with locales in Ubuntu so please excuse me if I'm stating the obvious or have mistakes in this process.

I managed to get Brackets working by following trompa's advice. I'm not sure which steps exactly were required to get it going. I think this is what I ended up doing (for English in the US):
```
sudo locale-gen en_US.UTF-8
sudo dpkg-reconfigure locales
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
```

**Comment by nethip** [comment]
Closing as it is resolved now.

**Comment by MathewLech** [comment]
For the sake of helping someone in the future who runs into this issue. Simply go to Debug-->Switch Language. change from system default to the language of interest and the issue should be resolved.

**Comment by epexa** [comment]
> For the sake of helping someone in the future who runs into this issue. Simply go to Debug-->Switch Language. change from system default to the language of interest and the issue should be resolved.

@MathewLech it helped me, thank you!

**Comment by imsahil007** [comment]
Thanks @epexa 
Changing the language to en-us from Debug>Switch language worked like a charm
