### ISSUE TITLE
Split View needs API to inject content into view header

### ISSUE THREAD

**Issue by lkcampbell** [adobe/brackets#9891]
Filing this issue as a reminder to follow up on this discussion:

https://groups.google.com/forum/#!topicsearchin/brackets-dev/author$3Ame/brackets-dev/yI1WlsFvOgk

I need this functionality to solve issue https://github.com/lkcampbell/brackets-ruler/issues/37.

Might also want to consider adding a footer to each Split View panel and an API to inject content into that as well.

**Comment by peterflynn** [comment]
@lkcampbell Is this something you'd be interested in submitting a PR to core for?  For the height calculation stuff, it seems like code similar to what's in `WorkspaceManager.calcAvailableHeight()` could work...

**Comment by lkcampbell** [comment]
@peterflynn, I'm interested in working on it. I'm not sure when I will have the time though. I remember discussing the problem with @JeffryBooher a while back and it is more complex than just calculating the height because it is creating a rudimentary change to the view architecture.

**Comment by lkcampbell** [comment]
This is never going to happen and I am going to rewrite the ruler extension anyway. Closing.
