### ISSUE TITLE
Javascript File Inference problem with Telerik Kendo files

### ISSUE THREAD

**Issue by andreas1974** [adobe/brackets#9898]
This is one example of files from Telerik Kendo that results in a "javascript inference problem". This file was included in another file, and not even opened by me, when the error showed up in Brackets.

It's a local file on my computer, but I guess you can find them at Teleriks site. The error message from Bracket asks me to provide a copy of the file, but only image files are allowed to attach here. I tried to add the javascript.

![capture](https://cloud.githubusercontent.com/assets/998258/4996662/07a10af2-69c9-11e4-9b48-d2b024bd9407.PNG)

**Comment by peterflynn** [comment]
@andreas1974 I downloaded Kendo version 2014.3.1316, opened the whole 'js' folder in Brackets, and then opened the file above -- didn't get any error message.  That suggests this may be a false alarm.  If your system was bogged down with other tasks at the time, processing this file could have taken long enough to trigger the timeout warning even with nothing wrong.

Does it happen every time you're working on this project?  If so, try increasing the `jscodehints.inferenceTimeout` [preference](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences) (default is 30000, i.e. 30 seconds).  If you raise the limit to 60 or 90 seconds, does the error go away?

**Comment by andreas1974** [comment]
I'm no longer using Brackets.
But thanks for trying to help.
