### ISSUE TITLE
Add current syntax as a class to the body tag

### ISSUE THREAD

**Issue by mattbob** [adobe/brackets#9912]
Currently the themes are limited by classes. For example, An HTML element has the class `.cm-tag` and a CSS selector also has the class `.cm-tag` which forces these elements to be styled the same.

It would be nice to have the ability to style the `.cm-tag` and others differently based on the files syntax. If the files syntax was included as a class on the body tag (just like there is already a `dark` class if you are using a dark theme) it would allow for much better themes.

**Comment by MarcelGerber** [comment]
@mattbob As of Release 1.1, you can use the `addModeClass` flag in order to make your theme language-aware. See [Creating Themes](https://github.com/adobe/brackets/wiki/Creating-Themes) for more information.

@peterflynn Guess you can close this issue.
