### ISSUE TITLE
Brackets crash because thread cannot read from virtual address

### ISSUE THREAD

**Issue by simonhoss** [adobe/brackets#9920]
Hi,

I develop a plugin which uses worker and IndexedDB. I have the problem that brackets crashes after a random time (sometimes 10 Minutes, sometime 4 hours), but always after typing, because the plugin reacts on user input and parses the text. I'm not able to reproduce the crash because of the randomness. 

The exception is: **The thread tried to read from or write to a virtual address for which it does not have the appropriate access.** 

Im working with Brackets 1.0, Windows 7 x64

I tried to start Brackets as Administrator, I also switched from IndexedDB to WebSQL but with no result. 

Here is my dump: https://www.dropbox.com/s/rye1pwewktlryop/Brackets.exe.9604.dmp?dl=0

Any idea?

Greets

**Comment by simonhoss** [comment]
No problems anymore with the new cef.

**Comment by peterflynn** [comment]
@simonhoss Awesome, thanks for checking back in!
