### ISSUE TITLE
File Manager Reload

### ISSUE THREAD

**Issue by ksindhi** [adobe/brackets#9928]
I'M currently using Brackets 1.0 version on Windows 8.1, having an issue with the File Manager

Issue Explain:
If i am working on any Project name(XYZ), later on if i switch to any other project name (ABC) using file explorer, then Editor windows is changed but their is no changed in the File Manager as their is no files tree open for project ABC, instead still showing the files tree for previously opened project XYZ.

Until i restart/reopen Brackets its not working/showing the currently selected project folder.

Please look into the matter.

Thanks
Kunal Sindhi
www.jankiphulkari.com
www.whatkhabar.com
www.facebook.com/k.sindhi89

**Comment by peterflynn** [comment]
Closing since there's been no response from the filer
