### ISSUE TITLE
PSD not show properly in Brackets 

### ISSUE THREAD

**Issue by misyaath** [adobe/brackets#9943]
Upload and load my PSD in Bracket that's shows like in Image. can you tell me how can i fix or what is the problem is it ?
![barcketissue1](https://cloud.githubusercontent.com/assets/9785451/5062167/96770540-6ddb-11e4-9ee8-6b3a9c628b95.png)

**Comment by peterflynn** [comment]
@misyaath Are you still seeing this issue?  (Also make sure you've updated to the 0.6.1 release of Extract for Brackets, which was released December 18).

**Comment by abose** [comment]
Deprecated feature. Closing.
