### ISSUE TITLE
Can't install/remove extensions / Mac OS 10.10

### ISSUE THREAD

**Issue by mjurczyk** [adobe/brackets#9957]
Hey,

I wanted to replace Sublime Text with Brackets, but it seems to be really tricky to install on Mac OS :/ 
I can only install extensions manually by dragging them to ~/Library/.../Brackets/extensions/user/.
**Trying to add or remove any extensions from inside the Brackets results in an `unknown internal error`**.

Looks like a permission's error? Does any Bracket folder require some special permissions to be manually set?

**Comment by mjurczyk** [comment]
@ingorichter installed the latest version on Brackets `1.3` and the problem seems to be no more - should I close the issue?

**Comment by abose** [comment]
As Unknown internal error issue is already tracked by #9895. closing this .

**Comment by ingorichter** [comment]
@mjurczyk yes and thanks!
