### ISSUE TITLE
CodeMirror cursor disappears sporadically in large minified files

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#9977]
1. Open a large minified file.  I used the 'main.js' inside E4B
2. Leave cursor on 1st column, and hit the Down arrow repeatedly
    * Result: on some lines the cursor disappears (but active line highlight remains). For me, lines 17 & 19.
3. On one of the lines where cursor is invisible, hit Right a few times
    * Result: reported cursor pos jumps to the last column on that same line. But most of the line appears to be blank in the viewport.  I confirmed in another editor that it is not actually blank there -- CM seems to cut off about halfway into the line, at column 55,740.  It's blank from there until the last 24 chars of the line, columns 121,276-121,300.  (It looks like the whole blank stretch is one long string literal, although the beginning 50,000+ chars of it _are_ displayed correctly).
4. Now press Left once
    * Result: CodeMirror throws:
    ```
Cannot read property 'top' of undefined codemirror.js:3719
maybeScrollWindow codemirror.js:3719
endOperation_finish codemirror.js:2107
endOperations codemirror.js:2020
endOperation codemirror.js:2003
(anonymous function)
```
5. Place cursor back at start of line, then scroll the view to the right a bunch of screenfuls (you don't need to go far enough or the line to start going blank though). Then click in the visible part of the line.
    * Result: CodeMirror throws the same error again

This is _not_ a regression in the new CodeMirror update we just merged -- I can repo on our previous version too.

**Comment by redmunds** [comment]
CodeMirror was recently updated. Marking FBNC back to @peterflynn .

**Comment by peterflynn** [comment]
Confirmed fixed!
